# -*- coding: utf-8 -*-
"""The directory rows in Bulgarian.

The Local Church labels follow the Bulgarian Patriarchate's own list and
publications. The diocesan labels use the same Bulgarian ecclesial vocabulary
already published on this site: eparchy, archdiocese and metropolis, with the
received Bulgarian place forms gathered from the corpus where available.

The official styles are separate from the list labels. They follow the
Bulgarian Patriarchate's list of local Orthodox Churches and its formal usage
for the Ecumenical Patriarchate, Antioch, Bulgaria and the Ukrainian Church.
Addresses, websites and each body's own local-language name remain untouched.
"""

NAMES = {
    "constantinople": u"Константинополска патриаршия",
    "alexandria": u"Александрийска патриаршия",
    "antioch": u"Антиохийска патриаршия",
    "jerusalem": u"Йерусалимска патриаршия",
    "russia": u"Руска православна църква",
    "georgia": u"Грузинска православна църква",
    "serbia": u"Сръбска православна църква",
    "romania": u"Румънска православна църква",
    "bulgaria": u"Българска православна църква",
    "cyprus": u"Кипърска православна църква",
    "greece": u"Еладска православна църква",
    "albania": u"Албанска православна църква",
    "poland": u"Полска православна църква",
    "czech-slovakia": u"Православна църква на Чешките земи и Словакия",
    "oca": u"Православна църква в Америка",
    "macedonia": u"Македонска православна църква - Охридска архиепископия",
    "ukraine-uoc": u"Украинска православна църква",
    "ukraine-ocu": u"Православна църква на Украйна",
    "sinai": u"Синайска православна църква",
    "finland": u"Автономна православна църква на Финландия",
    "japan": u"Японска православна църква",
    "estonia-eaok": u"Православна църква на Естония",
    "albanian-americas": u"Албанска православна епархия на двете Америки",
    "acrod": u"Американска карпаторуска православна епархия на Северна Америка",
    "ep-thyateira": u"Архиепископия на Тиатир и Великобритания",
    "goarch": u"Гръцка православна архиепископия в Америка",
    "ep-france": u"Гръцка православна митрополия на Франция",
    "ep-germany": u"Гръцка православна митрополия на Германия",
    "ep-austria": u"Света митрополия на Австрия",
    "ep-korea": u"Света митрополия на Корея",
    "ep-spain": u"Света митрополия на Испания и Португалия",
    "ep-belgium": u"Митрополия на Белгия",
    "ep-sweden": u"Митрополия на Швеция и цяла Скандинавия",
    "ep-switzerland": u"Митрополия на Швейцария",
    "ep-hongkong": u"Православна митрополия на Хонконг и Югоизточна Азия",
    "ep-singapore": u"Православна митрополия на Сингапур и Южна Азия",
    "ep-italy": u"Свещена православна архиепископия на Италия и Малта",
    "uocc": u"Украинска православна църква в Канада",
    "uoc-usa": u"Украинска православна църква в САЩ",
    "antiochian-na": u"Антиохийска православна християнска архиепископия на Северна Америка",
    "rocor": u"Руска православна задгранична църква",
    "mp-parishes-usa": u"Патриаршески енории в САЩ",
    "serbian-eastern": u"Епархия на Източна Америка",
    "serbian-midwestern": u"Епархия на Нова Грачаница и Средния запад на Америка",
    "serbian-western": u"Епархия на Западна Америка",
    "romanian-americas": u"Румънска православна митрополия на двете Америки",
    "bulgarian-usa": u"Българска източноправославна епархия в САЩ, Канада и Австралия",
    "oca-albanian": u"Албанска архиепископия",
    "oca-canada": u"Архиепископия на Канада",
    "oca-washington": u"Архиепископия на Вашингтон, окръг Колумбия",
    "oca-western-pa": u"Архиепископия на Западна Пенсилвания",
    "oca-bulgarian": u"Българска епархия",
    "oca-eastern-pa": u"Епархия на Източна Пенсилвания",
    "oca-mexico": u"Мексиканска епархия",
    "oca-new-england": u"Епархия на Нова Англия",
    "oca-ny-nj": u"Епархия на Ню Йорк и Ню Джърси",
    "oca-alaska": u"Епархия на Ситка и Аляска",
    "oca-midwest": u"Епархия на Средния запад",
    "oca-south": u"Епархия на Юга",
    "oca-west": u"Епархия на Запада",
    "oca-romanian": u"Румънска епископия",
    "ro-bucharest": u"Архиепископия на Букурещ",
    "ro-chisinau": u"Архиепископия на Кишинев",
    "ro-craiova": u"Архиепископия на Крайова",
    "ro-iasi": u"Архиепископия на Яш",
    "ro-sibiu": u"Архиепископия на Сибиу",
    "ro-timisoara": u"Архиепископия на Тимишоара",
    "ro-tomis": u"Архиепископия на Томис",
    "ro-cluj": u"Архиепископия на Вад, Фелеак и Клуж",
    "ro-western-europe": u"Румънска православна архиепископия на Западна Европа",
    "ro-germany": u"Румънска православна митрополия на Германия, Централна и Северна Европа",
}

SEATS = {
    "Istanbul": u"Константинопол",
    "Alexandria": u"Александрия",
    "Damascus": u"Дамаск",
    "Jerusalem": u"Йерусалим",
    "Moscow": u"Москва",
    "Tbilisi": u"Тбилиси",
    "Belgrade": u"Белград",
    "Bucharest": u"Букурещ",
    "Sofia": u"София",
    "Nicosia": u"Никозия",
    "Athens": u"Атина",
    "Tirana": u"Тирана",
    "Warsaw": u"Варшава",
    "Prešov": u"Прешов",
    "Syosset, New York": u"Сайосет, Ню Йорк",
    "Skopje": u"Скопие",
    "Kyiv": u"Киев",
    "Mount Sinai": u"Синайската планина",
    "Helsinki": u"Хелзинки",
    "Tokyo": u"Токио",
    "Tallinn": u"Талин",
    "Alexandria, Virginia": u"Александрия, Вирджиния",
    "Alhambra, California": u"Алхамбра, Калифорния",
    "Anchorage, Alaska": u"Анкоридж, Аляска",
    "Bath, Pennsylvania": u"Бат, Пенсилвания",
    "Bonn": u"Бон",
    "Boston, Massachusetts": u"Бостън, Масачузетс",
    "Bronxville, New York": u"Бронксвил, Ню Йорк",
    "Brussels": u"Брюксел",
    "Chambesy": u"Шамбези",
    "Chicago, Illinois": u"Чикаго, Илинойс",
    "Cranberry Township, Pennsylvania": u"Кранбъри Тауншип, Пенсилвания",
    "Dallas, Texas": u"Далас, Тексас",
    "Englewood, New Jersey": u"Енгълууд, Ню Джърси",
    "Hong Kong": u"Хонконг",
    "Jackson, Michigan": u"Джаксън, Мичиган",
    "Johnstown, Pennsylvania": u"Джонстаун, Пенсилвания",
    "London": u"Лондон",
    "Madrid": u"Мадрид",
    "Mexico City": u"Мексико Сити",
    "New Rochelle, New York": u"Ню Рошел, Ню Йорк",
    "New York": u"Ню Йорк",
    "Paris": u"Париж",
    "Rawdon, Quebec": u"Родон, Квебек",
    "San Francisco, California": u"Сан Франциско, Калифорния",
    "Seoul": u"Сеул",
    "Singapore": u"Сингапур",
    "Somerset, New Jersey": u"Съмърсет, Ню Джърси",
    "Stockholm": u"Стокхолм",
    "Third Lake, Illinois": u"Търд Лейк, Илинойс",
    "Toledo, Ohio": u"Толидо, Охайо",
    "Venice": u"Венеция",
    "Vienna": u"Виена",
    "Windsor, Connecticut": u"Уиндзор, Кънектикът",
    "Winnipeg, Manitoba": u"Уинипег, Манитоба",
    "Chisinau": u"Кишинев",
    "Cluj-Napoca": u"Клуж-Напока",
    "Constanta": u"Констанца",
    "Craiova": u"Крайова",
    "Jassy": u"Яш",
    "Limours": u"Лимур",
    "Nuremberg": u"Нюрнберг",
    "Sibiu": u"Сибиу",
    "Timisoara": u"Тимишоара",
}

STYLED = {
    "constantinople": u"Вселенска патриаршия",
    "alexandria": u"Александрийска патриаршия",
    "antioch": u"Патриаршия на Антиохия и целия Изток",
    "jerusalem": u"Йерусалимска патриаршия",
    "russia": u"Руска православна църква",
    "serbia": u"Сръбска православна църква",
    "romania": u"Румънска православна църква",
    "bulgaria": u"Българска православна църква - Българска патриаршия",
    "ukraine-uoc": u"Украинска православна църква",
}
