# -*- coding: utf-8 -*-
"""The English the rest are written from.

This file is the list of keys as much as it is a translation: a row id that
is not here is a row nobody has been asked to name, and a seat that is not
here is a city nobody has been asked to place.
"""
NAMES = {
    "constantinople": u"The Church of Constantinople",
    "alexandria": u"The Church of Alexandria",
    "antioch": u"The Church of Antioch",
    "jerusalem": u"The Church of Jerusalem",
    "russia": u"The Church of Russia",
    "georgia": u"The Church of Georgia",
    "serbia": u"The Church of Serbia",
    "romania": u"The Church of Romania",
    "bulgaria": u"The Church of Bulgaria",
    "cyprus": u"The Church of Cyprus",
    "greece": u"The Church of Greece",
    "albania": u"The Church of Albania",
    "poland": u"The Church of Poland",
    "czech-slovakia": u"The Church of the Czech Lands and Slovakia",
    "oca": u"The Orthodox Church in America",
    "macedonia": u"The Macedonian Orthodox Church - Ohrid Archbishopric",
    "ukraine-uoc": u"The Church of Ukraine",
    "ukraine-ocu": u"Orthodox Church of Ukraine",
    "sinai": u"The Church of Sinai",
    "finland": u"The Autonomous Church of Finland",
    "japan": u"The Church of Japan",
    "estonia-eaok": u"Orthodox Church of Estonia",
    "albanian-americas": u"Albanian Orthodox Diocese of the Americas",
    "acrod": u"American Carpatho-Russian Orthodox Diocese of North America",
    "ep-thyateira": u"Archdiocese of Thyateira and Great Britain",
    "goarch": u"Greek Orthodox Archdiocese of America",
    "ep-france": u"Greek Orthodox Metropolis of France",
    "ep-germany": u"Greek Orthodox Metropolis of Germany",
    "ep-austria": u"Holy Metropolis of Austria",
    "ep-korea": u"Holy Metropolis of Korea",
    "ep-spain": u"Holy Metropolis of Spain and Portugal",
    "ep-belgium": u"Metropolis of Belgium",
    "ep-sweden": u"Metropolis of Sweden and All Scandinavia",
    "ep-switzerland": u"Metropolis of Switzerland",
    "ep-hongkong": u"Orthodox Metropolitanate of Hong Kong and South East Asia",
    "ep-singapore": u"Orthodox Metropolitanate of Singapore and South Asia",
    "ep-italy": u"Sacred Orthodox Archdiocese of Italy and Malta",
    "uocc": u"Ukrainian Orthodox Church of Canada",
    "uoc-usa": u"Ukrainian Orthodox Church of the USA",
    "antiochian-na": u"Antiochian Orthodox Christian Archdiocese of North America",
    "rocor": u"Russian Orthodox Church Outside of Russia",
    "mp-parishes-usa": u"The Patriarchal Parishes in the USA",
    "serbian-eastern": u"Diocese of Eastern America",
    "serbian-midwestern": u"Diocese of New Gracanica and Midwestern America",
    "serbian-western": u"Diocese of Western America",
    "romanian-americas": u"Romanian Orthodox Metropolia of the Americas",
    "bulgarian-usa": u"Bulgarian Eastern Orthodox Diocese of the USA, Canada and Australia",
    "oca-albanian": u"Albanian Archdiocese",
    "oca-canada": u"Archdiocese of Canada",
    "oca-washington": u"Archdiocese of Washington, D.C.",
    "oca-western-pa": u"Archdiocese of Western Pennsylvania",
    "oca-bulgarian": u"Bulgarian Diocese",
    "oca-eastern-pa": u"Diocese of Eastern Pennsylvania",
    "oca-mexico": u"Diocese of Mexico",
    "oca-new-england": u"Diocese of New England",
    "oca-ny-nj": u"Diocese of New York and New Jersey",
    "oca-alaska": u"Diocese of Sitka and Alaska",
    "oca-midwest": u"Diocese of the Midwest",
    "oca-south": u"Diocese of the South",
    "oca-west": u"Diocese of the West",
    "oca-romanian": u"Romanian Episcopate",
    "ro-bucharest": u"Archdiocese of Bucharest",
    "ro-chisinau": u"Archdiocese of Chisinau",
    "ro-craiova": u"Archdiocese of Craiova",
    "ro-iasi": u"Archdiocese of Jassy",
    "ro-sibiu": u"Archdiocese of Sibiu",
    "ro-timisoara": u"Archdiocese of Timisoara",
    "ro-tomis": u"Archdiocese of Tomis",
    "ro-cluj": u"Archdiocese of Vad, Feleac and Cluj",
    "ro-western-europe": u"Romanian Orthodox Archdiocese of Western Europe",
    "ro-germany": u"Romanian Orthodox Metropolis of Germany, Central and Northern Europe",
    "ax-accra": u"Holy Archdiocese of Accra",
    "ax-aksum": u"Holy Archdiocese of Aksum",
    "ax-antananarivo": u"Holy Archdiocese of Antananarivo and North Madagascar",
    "ax-cameroon": u"Holy Archdiocese of Cameroon",
    "ax-carthage": u"Holy Archdiocese of Carthage",
    "ax-cyrene": u"Holy Archdiocese of Cyrene",
    "ax-ermoupolis": u"Holy Archdiocese of Ermoupolis",
    "ax-guinea": u"Holy Archdiocese of Guinea",
    "ax-irinopolis": u"Holy Archdiocese of Irinopolis",
    "ax-johannesburg": u"Holy Archdiocese of Johannesburg and Pretoria",
    "ax-kinshasa": u"Holy Archdiocese of Kinshasa",
    "ax-leontopolis": u"Holy Archdiocese of Leontopolis",
    "ax-nairobi": u"Holy Archdiocese of Nairobi",
    "ax-nigeria": u"Holy Archdiocese of Nigeria",
    "ax-nubia": u"Holy Archdiocese of Nubia",
    "ax-ptolemais": u"Holy Archdiocese of Ptolemais",
    "ax-zimbabwe": u"Holy Archdiocese of Zimbabwe and Angola",
    "ax-good-hope": u"Holy Archdiocese of the Cape of Good Hope",
    "ax-arusha": u"Holy Diocese of Arusha and Central Tanzania",
    "ax-benin": u"Holy Diocese of Benin, Togo and Burkina Faso",
    "ax-bujumbura": u"Holy Diocese of Bujumbura and Burundi",
    "ax-bukoba": u"Holy Diocese of Bukoba and West Tanzania",
    "ax-kisangani": u"Holy Diocese of Bunia, Kisangani and Eastern Congo",
    "ax-eldoret": u"Holy Diocese of Eldoret and Northern Kenya",
    "ax-gaborone": u"Holy Diocese of Gaborone and Botswana",
    "ax-goma": u"Holy Diocese of Goma and Great Kivu",
    "ax-gulu": u"Holy Diocese of Gulu and Northern Uganda",
    "ax-jinja": u"Holy Diocese of Jinja and Eastern Uganda",
    "ax-juba": u"Holy Diocese of Juba and South Sudan",
    "ax-kigali": u"Holy Diocese of Kigali and Rwanda",
    "ax-kisumu": u"Holy Diocese of Kisumu and Western Kenya",
    "ax-malawi": u"Holy Diocese of Malawi",
    "ax-nieri": u"Holy Diocese of Nieri and Mount Kenya",
    "ax-toliara": u"Holy Diocese of Toliara and Southern Madagascar",
    "ax-brazzaville": u"Holy Metropolis of Brazzaville and Gabon",
    "ax-caesarea": u"Holy Metropolis of Caesarea",
    "ax-diospolis": u"Holy Metropolis of Diospolis",
    "ax-heliopolis": u"Holy Metropolis of Heliopolis",
    "ax-kampala": u"Holy Metropolis of Kampala",
    "ax-kananga": u"Holy Metropolis of Kananga",
    "ax-katanga": u"Holy Metropolis of Katanga",
    "ax-libya": u"Holy Metropolis of Libya",
    "ax-memphis": u"Holy Metropolis of Memphis",
    "ax-pelusium": u"Holy Metropolis of Pelusium",
    "ax-zambia": u"Holy Metropolis of Zambia and Mozambique",
    "an-akkar": u"Archdiocese of Akkar and Dependencies",
    "an-aleppo": u"Archdiocese of Aleppo, Alexandretta and Dependencies",
    "an-australia": u"Archdiocese of Australia, New Zealand and the Philippines",
    "an-baghdad": u"Archdiocese of Baghdad, Kuwait and Dependencies",
    "an-beirut": u"Archdiocese of Beirut and Dependencies",
    "an-bosra": u"Archdiocese of Bosra, Hauran and Jabal al-Arab",
    "an-buenos-aires": u"Archdiocese of Buenos Aires and All Argentine",
    "an-byblos": u"Archdiocese of Byblos, Batroun and Dependencies",
    "an-france": u"Archdiocese of France, Western and Southern Europe",
    "an-germany": u"Archdiocese of Germany and Central Europe",
    "an-hama": u"Archdiocese of Hama and Dependencies",
    "an-homs": u"Archdiocese of Homs and Dependencies",
    "an-lattakia": u"Archdiocese of Lattakia and Dependencies",
    "an-mexico": u"Archdiocese of Mexico, Venezuela, Central America and the Islands of the Caribbean Sea",
    "an-santiago": u"Archdiocese of Santiago and All Chile",
    "an-sao-paulo": u"Archdiocese of Sao Paulo and All Brazil",
    "an-tripoli": u"Archdiocese of Tripoli, Al-Koura and Dependencies",
    "an-tyre-sidon": u"Archdiocese of Tyre, Sidon and Dependencies",
    "an-zahleh": u"Archdiocese of Zahleh, Baalbek and Dependencies",
    "an-british-isles": u"Archdiocese of the British Isles and Ireland",
    "ro-alba-iulia": u"Archdiocese of Alba Iulia",
    "ro-arad": u"Archdiocese of Arad",
    "ro-arges": u"Archdiocese of Arges and Muscel",
    "ro-buzau": u"Archdiocese of Buzau and Vrancea",
    "ro-lower-danube": u"Archdiocese of Lower Danube",
    "ro-ramnic": u"Archdiocese of Ramnic",
    "ro-roman": u"Archdiocese of Roman and Bacau",
    "ro-suceava": u"Archdiocese of Suceava and Radauti",
    "ro-targoviste": u"Archdiocese of Targoviste",
    "ro-alexandria-teleorman": u"Diocese of Alexandria and Teleorman",
    "ro-balti": u"Diocese of Balti (formerly Hotin)",
    "ro-caransebes": u"Diocese of Caransebes",
    "ro-covasna": u"Diocese of Covasna and Harghita",
    "ro-dacia-felix": u"Diocese of Dacia Felix",
    "ro-deva": u"Diocese of Deva and Hunedoara",
    "ro-giurgiu": u"Diocese of Giurgiu",
    "ro-husi": u"Diocese of Husi",
    "ro-salaj": u"Diocese of Salaj",
    "ro-severin": u"Diocese of Severin and Strehaia",
    "ro-slatina": u"Diocese of Slatina and Romanati",
    "ro-slobozia": u"Diocese of Slobozia and Calarasi",
    "ro-south-bessarabia": u"Diocese of South Bessarabia (formerly of Cetatea Alba-Ismail)",
    "ro-tulcea": u"Diocese of Tulcea",
    "ro-great-britain": u"Romanian Orthodox Archdiocese of Great Britain and Northern Ireland",
    "ro-australia-nz": u"Romanian Orthodox Diocese of Australia and New Zealand",
    "ro-canada": u"Romanian Orthodox Diocese of Canada",
    "ro-hungary": u"Romanian Orthodox Diocese of Hungary",
    "ro-ireland-iceland": u"Romanian Orthodox Diocese of Ireland and Iceland",
    "ro-italy": u"Romanian Orthodox Diocese of Italy",
    "ro-maramures": u"Romanian Orthodox Diocese of Maramures and Satmar",
    "ro-northern-europe": u"Romanian Orthodox Diocese of Northern Europe",
    "ro-oradea": u"Romanian Orthodox Diocese of Oradea",
    "ro-spain": u"Romanian Orthodox Diocese of Spain and Portugal",
    "fi-helsinki": u"Diocese of Helsinki",
    "fi-kuopio": u"Diocese of Kuopio and Karelia",
    "fi-oulu": u"Diocese of Oulu",
    "ep-australia": u"Archdiocese of Australia",
    "ep-canada": u"Archdiocese of Canada",
    "ep-crete": u"Archdiocese of Crete",
    "ep-adrianople": u"Metropolis of Adrianople",
    "ep-alexandroupolis": u"Metropolis of Alexandroupolis",
    "ep-arkalochorion": u"Metropolis of Arkalochorion",
    "ep-atlanta": u"Metropolis of Atlanta",
    "ep-beroia": u"Metropolis of Beroia Naousa and Kampania",
    "ep-boston": u"Metropolis of Boston",
    "ep-buenos-aires": u"Metropolis of Buenos Aires",
    "ep-bursa": u"Metropolis of Bursa",
    "ep-chalcedon": u"Metropolis of Chalcedon",
    "ep-chicago": u"Metropolis of Chicago",
    "ep-chios": u"Metropolis of Chios",
    "ep-denver": u"Metropolis of Denver",
    "ep-derkoi": u"Metropolis of Derkoi",
    "ep-detroit": u"Metropolis of Detroit",
    "ep-didymoteichon": u"Metropolis of Didymoteichon Orestiada and Souflion",
    "ep-drama": u"Metropolis of Drama",
    "ep-dryinoupolis": u"Metropolis of Dryinoypolis Pogoniane and Konitsa",
    "ep-edessa": u"Metropolis of Edessa and Pella",
    "ep-eleftheroupolis": u"Metropolis of Eleftheroupolis",
    "ep-ganos-chora": u"Metropolis of Ganou and Chora",
    "ep-gortyne": u"Metropolis of Gortyne and Arkadia",
    "ep-goumenissa": u"Metropolis of Goumenissa Axiopolis and Polykarpos",
    "ep-grevena": u"Metropolis of Grevena",
    "ep-elassona": u"Metropolis of Helassona",
    "ep-hierapytne": u"Metropolis of Hierapytne and Siteia",
    "ep-hierissos": u"Metropolis of Hierissos the Holy Mountain and Ardamerion",
    "ep-imbros-tenedos": u"Metropolis of Imbros and Tenedos",
    "ep-ioannina": u"Metropolis of Ioannina",
    "ep-karpathos": u"Metropolis of Karpathos and Kasos",
    "ep-kassandreia": u"Metropolis of Kassandreia",
    "ep-kastoria": u"Metropolis of Kastoria",
    "ep-kisamos": u"Metropolis of Kisamos and Selinos",
    "ep-kitros": u"Metropolis of Kitros",
    "ep-kos": u"Metropolis of Kos and Nisyros",
    "ep-kydonia": u"Metropolis of Kydonia and Apokoronos",
    "ep-lagadas": u"Metropolis of Lagadas Lete and Komotini",
    "ep-lampe": u"Metropolis of Lampe, Syvrito and Sfakia",
    "ep-lemnos": u"Metropolis of Lemnos",
    "ep-leros": u"Metropolis of Leros, Kalymnos, and Astypalaia",
    "ep-maroneia": u"Metropolis of Maroneia and Komotini",
    "ep-mexico": u"Metropolis of Mexico",
    "ep-mithymna": u"Metropolis of Mithymna",
    "ep-mytilene": u"Metropolis of Mytilene",
    "ep-nea-krini": u"Metropolis of Nea Krini and Kalamaria",
    "ep-neapolis-stavroupolis": u"Metropolis of Neapolis and Stavroupolis",
    "ep-new-jersey": u"Metropolis of New Jersey",
    "ep-new-zealand": u"Metropolis of New Zealand",
    "ep-nikopolis": u"Metropolis of Nikopolis and Prebeza",
    "ep-paramythia": u"Metropolis of Paramythia Filiata and Geromerion",
    "ep-petra": u"Metropolis of Petra and Cherronesos",
    "ep-philippoi": u"Metropolis of Philippoi Neapolis and Thasos",
    "ep-phlorina": u"Metropolis of Phlorina Prespes and Eordaia",
    "ep-pisidia": u"Metropolis of Pisidia",
    "ep-pittsburgh": u"Metropolis of Pittsburgh",
    "ep-polyane": u"Metropolis of Polyane and Kilkis",
    "ep-princes-islands": u"Metropolis of Princes Islands",
    "ep-rethymne": u"Metropolis of Rethymne and Avlopotamos",
    "ep-rhodes": u"Metropolis of Rhodes",
    "ep-samos": u"Metropolis of Samos and Ikaria",
    "ep-san-francisco": u"Metropolis of San Francisco",
    "ep-selybria": u"Metropolis of Selybria",
    "ep-serres": u"Metropolis of Serres and Nigrite",
    "ep-servia-kozani": u"Metropolis of Servia and Kozani",
    "ep-siderokastron": u"Metropolis of Siderokastron",
    "ep-sisanion": u"Metropolis of Sisanion and Siatista",
    "ep-smyrna": u"Metropolis of Smyrna",
    "ep-syme": u"Metropolis of Syme",
    "ep-thessaloniki": u"Metropolis of Thessaloniki",
    "ep-vryoula": u"Metropolis of Vryoula",
    "ep-xanthi": u"Metropolis of Xanthi",
    "ep-zihna": u"Metropolis of Zihna and Nevrokopion",
    "ep-ireland": u"Metropolitan of Ireland",
    "ep-lithuania": u"Patriarchal Exarchate of Lithuania",
    "ep-malta": u"Patriarchal Exarchate of Malta",
    "ep-patmos": u"Patriarchal Exarchate of Patmos",
    "je-exarch-constantinople": u"Exarchate of the Holy Sepulchre in Constantinople",
    "je-exarch-cyprus": u"Exarchate of the Holy Sepulchre in Cyprus",
    "je-exarch-greece": u"Exarchate of the Holy Sepulchre in Greece",
    "je-exarch-moscow": u"Exarchate of the Holy Sepulchre in Moscow",
    "je-nazareth": u"Holy Metropolis of Nazareth",
    "je-ptolemais": u"Holy Metropolis of Ptolemais",
    "je-amman": u"Patriarchal Commissaryship in Amman",
    "je-gaza": u"Patriarchal Commissaryship in Gaza",
    "je-jaffa": u"Patriarchal Commissaryship in Jaffa",
    "je-qatar": u"Patriarchal Commissaryship in Qatar",
    "ru-abakan": u"Abakan Diocese",
    "ru-akhtubinsk": u"Akhtubinsk Diocese",
    "ru-aktobe": u"Aktobe Diocese",
    "ru-alapayevsk": u"Alapayevsk Diocese",
    "ru-alatyr": u"Alatyr Diocese",
    "ru-aleksandrov": u"Aleksandrov Diocese",
    "ru-almetevsk": u"Almetevsk Diocese",
    "ru-amur": u"Amur Diocese",
    "ru-anadyr": u"Anadyr Diocese",
    "ru-ardatov": u"Ardatov Diocese",
    "ru-arkhangelsk": u"Arkhangelsk Diocese",
    "ru-armavir": u"Armavir Diocese",
    "ru-arsenev": u"Arsenev Diocese",
    "ru-astana": u"Astana Diocese",
    "ru-astrakhan": u"Astrakhan Diocese",
    "ru-babruysk": u"Babruysk Diocese",
    "ru-baku": u"Baku Diocese",
    "ru-balakovo": u"Balakovo Diocese",
    "ru-balashikha": u"Balashikha Diocese",
    "ru-balashov": u"Balashov Diocese",
    "ru-balti": u"Balti Diocese",
    "ru-barnaul": u"Barnaul Diocese",
    "ru-barysaw": u"Barysaw Diocese",
    "ru-barysh": u"Barysh Diocese",
    "ru-belgorod": u"Belgorod Diocese",
    "ru-belyov": u"Belyov Diocese",
    "ru-bezhetsk": u"Bezhetsk Diocese",
    "ru-birobidzhan": u"Birobidzhan Diocese",
    "ru-birsk": u"Birsk Diocese",
    "ru-bishkek": u"Bishkek Diocese",
    "ru-biysk": u"Biysk Diocese",
    "ru-blagoveshchensk": u"Blagoveshchensk Diocese",
    "ru-borisoglebsk": u"Borisoglebsk Diocese",
    "ru-borovichi": u"Borovichi Diocese",
    "ru-bratsk": u"Bratsk Diocese",
    "ru-brest": u"Brest Diocese",
    "ru-bryansk": u"Bryansk Diocese",
    "ru-buzuluk": u"Buzuluk Diocese",
    "ru-cahul": u"Cahul Diocese",
    "ru-cheboksary": u"Cheboksary Diocese",
    "ru-chelyabinsk": u"Chelyabinsk Diocese",
    "ru-cherepovets": u"Cherepovets Diocese",
    "ru-chernyakhovsk": u"Chernyakhovsk Diocese",
    "ru-chistopol": u"Chistopol Diocese",
    "ru-chita": u"Chita Diocese",
    "ru-daugavpils": u"Daugavpils Diocese",
    "ru-argentina-and-south-america": u"Diocese of Argentina and South America",
    "ru-australia-and-new-zealand-rocor": u"Diocese of Australia and New Zealand (ROCOR)",
    "ru-berlin-and-germany": u"Diocese of Berlin and Germany",
    "ru-brussels-and-belgium": u"Diocese of Brussels and Belgium",
    "ru-budapest-and-hungary": u"Diocese of Budapest and Hungary",
    "ru-canada-rocor": u"Diocese of Canada (ROCOR)",
    "ru-eastern-america-rocor": u"Diocese of Eastern America (ROCOR)",
    "ru-germany-rocor": u"Diocese of Germany (ROCOR)",
    "ru-great-britain-and-western-europe-rocor": u"Diocese of Great Britain and Western Europe (ROCOR)",
    "ru-korea": u"Diocese of Korea",
    "ru-mid-america-rocor": u"Diocese of Mid-America (ROCOR)",
    "ru-north-africa": u"Diocese of North Africa",
    "ru-petropavl-and-bulayevo": u"Diocese of Petropavl and Bulayevo",
    "ru-singapore": u"Diocese of Singapore",
    "ru-sourozh": u"Diocese of Sourozh",
    "ru-south-africa": u"Diocese of South Africa",
    "ru-south-america-rocor": u"Diocese of South America (ROCOR)",
    "ru-spain-and-portugal": u"Diocese of Spain and Portugal",
    "ru-thailand": u"Diocese of Thailand",
    "ru-hague-and-the-netherlands": u"Diocese of The Hague and the Netherlands",
    "ru-vienna-and-austria": u"Diocese of Vienna and Austria",
    "ru-western-america-rocor": u"Diocese of Western America (ROCOR)",
    "ru-yerevan-and-armenia": u"Diocese of Yerevan and Armenia",
    "ru-philippines-and-vietnam": u"Diocese of the Philippines and Vietnam",
    "ru-dushanbe": u"Dushanbe Diocese",
    "ru-edinet": u"Edinet Diocese",
    "ru-elista": u"Elista Diocese",
    "ru-galich": u"Galich Diocese",
    "ru-gatchina": u"Gatchina Diocese",
    "ru-georgiyevsk": u"Georgiyevsk Diocese",
    "ru-glazov": u"Glazov Diocese",
    "ru-gorno-altaysk": u"Gorno-Altaysk Diocese",
    "ru-gorodets": u"Gorodets Diocese",
    "ru-grozny": u"Grozny Diocese",
    "ru-gubkin": u"Gubkin Diocese",
    "ru-homel": u"Homel Diocese",
    "ru-hrodna": u"Hrodna Diocese",
    "ru-irkutsk": u"Irkutsk Diocese",
    "ru-ishim": u"Ishim Diocese",
    "ru-isilkul": u"Isilkul Diocese",
    "ru-iskitim": u"Iskitim Diocese",
    "ru-ivanovo-voznesensk": u"Ivanovo-Voznesensk Diocese",
    "ru-izhevsk": u"Izhevsk Diocese",
    "ru-kainsk": u"Kainsk Diocese",
    "ru-kalach": u"Kalach Diocese",
    "ru-kalachinsk": u"Kalachinsk Diocese",
    "ru-kaliningrad": u"Kaliningrad Diocese",
    "ru-kaluga": u"Kaluga Diocese",
    "ru-kamensk": u"Kamensk Diocese",
    "ru-kanash": u"Kanash Diocese",
    "ru-kansk": u"Kansk Diocese",
    "ru-karaganda": u"Karaganda Diocese",
    "ru-karasuk": u"Karasuk Diocese",
    "ru-kasimov": u"Kasimov Diocese",
    "ru-kazan": u"Kazan Diocese",
    "ru-kemerovo": u"Kemerovo Diocese",
    "ru-khabarovsk": u"Khabarovsk Diocese",
    "ru-khanty-mansiysk": u"Khanty-Mansiysk Diocese",
    "ru-kinel": u"Kinel Diocese",
    "ru-kineshma": u"Kineshma Diocese",
    "ru-klintsy": u"Klintsy Diocese",
    "ru-kokshetau": u"Kokshetau Diocese",
    "ru-kolomna": u"Kolomna Diocese",
    "ru-kolpashevo": u"Kolpashevo Diocese",
    "ru-korsun": u"Korsun Diocese",
    "ru-kostanay": u"Kostanay Diocese",
    "ru-kostomuksha": u"Kostomuksha Diocese",
    "ru-kostroma": u"Kostroma Diocese",
    "ru-kotlas": u"Kotlas Diocese",
    "ru-kozelsk": u"Kozelsk Diocese",
    "ru-krasnoslobodsk": u"Krasnoslobodsk Diocese",
    "ru-krasnoyarsk": u"Krasnoyarsk Diocese",
    "ru-kudymkar": u"Kudymkar Diocese",
    "ru-kurgan": u"Kurgan Diocese",
    "ru-kursk": u"Kursk Diocese",
    "ru-kuznetsk": u"Kuznetsk Diocese",
    "ru-kyzyl": u"Kyzyl Diocese",
    "ru-lida": u"Lida Diocese",
    "ru-lipetsk": u"Lipetsk Diocese",
    "ru-livny": u"Livny Diocese",
    "ru-lyskovo": u"Lyskovo Diocese",
    "ru-magadan": u"Magadan Diocese",
    "ru-magnitogorsk": u"Magnitogorsk Diocese",
    "ru-mahilyow": u"Mahilyow Diocese",
    "ru-makhachkala": u"Makhachkala Diocese",
    "ru-maladzyechna": u"Maladzyechna Diocese",
    "ru-mariinsk": u"Mariinsk Diocese",
    "ru-maykop": u"Maykop Diocese",
    "ru-melekess": u"Melekess Diocese",
    "ru-michurinsk": u"Michurinsk Diocese",
    "ru-minsk": u"Minsk Diocese",
    "ru-minusinsk": u"Minusinsk Diocese",
    "ru-moscow-city": u"Moscow City Diocese",
    "ru-murmansk": u"Murmansk Diocese",
    "ru-murom": u"Murom Diocese",
    "ru-naberezhnye-chelny": u"Naberezhnye Chelny Diocese",
    "ru-nakhodka": u"Nakhodka Diocese",
    "ru-narva": u"Narva Diocese",
    "ru-naryan-mar": u"Naryan-Mar Diocese",
    "ru-navahrudak": u"Navahrudak Diocese",
    "ru-neftekamsk": u"Neftekamsk Diocese",
    "ru-nerchinsk": u"Nerchinsk Diocese",
    "ru-nikolayevsk-on-amur": u"Nikolayevsk-on-Amur Diocese",
    "ru-nizhny-novgorod": u"Nizhny Novgorod Diocese",
    "ru-nizhny-tagil": u"Nizhny Tagil Diocese",
    "ru-norilsk": u"Norilsk Diocese",
    "ru-novgorod": u"Novgorod Diocese",
    "ru-novokuznetsk": u"Novokuznetsk Diocese",
    "ru-novorossiysk": u"Novorossiysk Diocese",
    "ru-novosibirsk": u"Novosibirsk Diocese",
    "ru-odintsovo": u"Odintsovo Diocese",
    "ru-omsk": u"Omsk Diocese",
    "ru-orenburg": u"Orenburg Diocese",
    "ru-orsk": u"Orsk Diocese",
    "ru-oryol": u"Oryol Diocese",
    "ru-otradny": u"Otradny Diocese",
    "ru-turkmenistan": u"Patriarchal Deanery of the Parishes in Turkmenistan",
    "ru-pavlodar": u"Pavlodar Diocese",
    "ru-penza": u"Penza Diocese",
    "ru-pereslavl": u"Pereslavl Diocese",
    "ru-perm": u"Perm Diocese",
    "ru-pesochnya": u"Pesochnya Diocese",
    "ru-petropavlovsk": u"Petropavlovsk Diocese",
    "ru-petrozavodsk": u"Petrozavodsk Diocese",
    "ru-pinsk": u"Pinsk Diocese",
    "ru-plesetsk": u"Plesetsk Diocese",
    "ru-podolsk": u"Podolsk Diocese",
    "ru-pokrovsk": u"Pokrovsk Diocese",
    "ru-polatsk": u"Polatsk Diocese",
    "ru-pskov": u"Pskov Diocese",
    "ru-pyatigorsk": u"Pyatigorsk Diocese",
    "ru-riga": u"Riga Diocese",
    "ru-roslavl": u"Roslavl Diocese",
    "ru-rossosh": u"Rossosh Diocese",
    "ru-rostov-on-don": u"Rostov-on-Don Diocese",
    "ru-rubtsovsk": u"Rubtsovsk Diocese",
    "ru-ryazan": u"Ryazan Diocese",
    "ru-rybinsk": u"Rybinsk Diocese",
    "ru-rzhev": u"Rzhev Diocese",
    "ru-saint-petersburg": u"Saint Petersburg Diocese",
    "ru-salavat": u"Salavat Diocese",
    "ru-salekhard": u"Salekhard Diocese",
    "ru-samara": u"Samara Diocese",
    "ru-saransk": u"Saransk Diocese",
    "ru-sarapul": u"Sarapul Diocese",
    "ru-saratov": u"Saratov Diocese",
    "ru-sayansk": u"Sayansk Diocese",
    "ru-serdobsk": u"Serdobsk Diocese",
    "ru-sergiyev-posad": u"Sergiyev Posad Diocese",
    "ru-serov": u"Serov Diocese",
    "ru-severobaykalsk": u"Severobaykalsk Diocese",
    "ru-severomorsk": u"Severomorsk Diocese",
    "ru-shadrinsk": u"Shadrinsk Diocese",
    "ru-shakhty": u"Shakhty Diocese",
    "ru-shchigry": u"Shchigry Diocese",
    "ru-shuya": u"Shuya Diocese",
    "ru-shymkent": u"Shymkent Diocese",
    "ru-simbirsk": u"Simbirsk Diocese",
    "ru-skopin": u"Skopin Diocese",
    "ru-slavgorod": u"Slavgorod Diocese",
    "ru-slutsk": u"Slutsk Diocese",
    "ru-smolensk": u"Smolensk Diocese",
    "ru-sochi": u"Sochi Diocese",
    "ru-solikamsk": u"Solikamsk Diocese",
    "ru-soroca": u"Soroca Diocese",
    "ru-stavropol": u"Stavropol Diocese",
    "ru-syktyvkar": u"Syktyvkar Diocese",
    "ru-syzran": u"Syzran Diocese",
    "ru-taldykorgan-vicariate": u"Taldykorgan Vicariate",
    "ru-tallinn": u"Tallinn Diocese",
    "ru-tambov": u"Tambov Diocese",
    "ru-tara": u"Tara Diocese",
    "ru-tashkent": u"Tashkent Diocese",
    "ru-tikhoretsk": u"Tikhoretsk Diocese",
    "ru-tikhvin": u"Tikhvin Diocese",
    "ru-tiraspol": u"Tiraspol Diocese",
    "ru-tobolsk": u"Tobolsk Diocese",
    "ru-tolyatti": u"Tolyatti Diocese",
    "ru-tomsk": u"Tomsk Diocese",
    "ru-troitsk": u"Troitsk Diocese",
    "ru-tula": u"Tula Diocese",
    "ru-turaw": u"Turaw Diocese",
    "ru-tver": u"Tver Diocese",
    "ru-ufa": u"Ufa Diocese",
    "ru-ulan-ude": u"Ulan-Ude Diocese",
    "ru-ungheni": u"Ungheni Diocese",
    "ru-uralsk": u"Uralsk Diocese",
    "ru-uryupinsk": u"Uryupinsk Diocese",
    "ru-urzhum": u"Urzhum Diocese",
    "ru-ust-kamenogorsk": u"Ust-Kamenogorsk Diocese",
    "ru-uvarovo": u"Uvarovo Diocese",
    "ru-valuyki": u"Valuyki Diocese",
    "ru-vanino": u"Vanino Diocese",
    "ru-velikiye-luki": u"Velikiye Luki Diocese",
    "ru-veliky-ustyug": u"Veliky Ustyug Diocese",
    "ru-vilnius": u"Vilnius Diocese",
    "ru-vitebsk": u"Vitebsk Diocese",
    "ru-vladikavkaz": u"Vladikavkaz Diocese",
    "ru-vladimir": u"Vladimir Diocese",
    "ru-vladivostok": u"Vladivostok Diocese",
    "ru-volgodonsk": u"Volgodonsk Diocese",
    "ru-volgograd": u"Volgograd Diocese",
    "ru-vologda": u"Vologda Diocese",
    "ru-volzhsk": u"Volzhsk Diocese",
    "ru-vorkuta": u"Vorkuta Diocese",
    "ru-voronezh": u"Voronezh Diocese",
    "ru-vyatka": u"Vyatka Diocese",
    "ru-vyazma": u"Vyazma Diocese",
    "ru-vyborg": u"Vyborg Diocese",
    "ru-vyksa": u"Vyksa Diocese",
    "ru-yakutsk": u"Yakutsk Diocese",
    "ru-yaransk": u"Yaransk Diocese",
    "ru-yaroslavl": u"Yaroslavl Diocese",
    "ru-yekaterinburg": u"Yekaterinburg Diocese",
    "ru-yekaterinodar": u"Yekaterinodar Diocese",
    "ru-yelets": u"Yelets Diocese",
    "ru-yeniseysk": u"Yeniseysk Diocese",
    "ru-yeysk": u"Yeysk Diocese",
    "ru-yoshkar-ola": u"Yoshkar-Ola Diocese",
    "ru-yugorsk": u"Yugorsk Diocese",
    "ru-yuzhno-sakhalinsk": u"Yuzhno-Sakhalinsk Diocese",
    "ru-zheleznogorsk": u"Zheleznogorsk Diocese",
    "ru-zlatoust": u"Zlatoust Diocese",
    "jp-tokyo": u"Archdiocese of Tokyo",
    "jp-east": u"Diocese of Eastern Japan",
    "jp-west": u"Diocese of Western Japan",
    "ee-tallinn": u"Archdiocese of Tallinn",
    "ee-parnu-saare": u"Diocese of Pärnu and Saare",
    "ee-tartu": u"Diocese of Tartu",
    "lv-riga": u"Diocese of Riga",
    "lv-daugavpils": u"Diocese of Daugavpils and Rēzekne",
    "ekok-tallinn": u"Diocese of Tallinn",
    "ekok-narva": u"Diocese of Narva and Peipsi",
    "gr-athens": u"Archdiocese of Athens",
    "gr-aitolia": u"Metropolis of Aitolia and Acarnania",
    "gr-argolis": u"Metropolis of Argolis",
    "gr-arta": u"Metropolis of Arta",
    "gr-chalkis": u"Metropolis of Chalkis",
    "gr-demetrias": u"Metropolis of Demetrias and Almyros",
    "gr-fthiotis": u"Metropolis of Fthiotis",
    "gr-glyfada": u"Metropolis of Glyfada",
    "gr-gortys": u"Metropolis of Gortys and Megalopolis",
    "gr-ilia": u"Metropolis of Ilia and Oleni",
    "gr-ilion": u"Metropolis of Ilion, Petroupolis and Acharnai",
    "gr-kaisariani": u"Metropolis of Kaisariani, Vyron and Ymittos",
    "gr-kalavryta": u"Metropolis of Kalavryta and Aigialeia",
    "gr-karpenision": u"Metropolis of Karpenision",
    "gr-karystia": u"Metropolis of Karystia and Skyros",
    "gr-kefallinia": u"Metropolis of Kefallinia",
    "gr-kerkyra": u"Metropolis of Kerkyra, Paxoi and Diapontioi Nisoi",
    "gr-kifisia": u"Metropolis of Kifisia, Amarousion, Oropos and Marathon",
    "gr-korinthos": u"Metropolis of Korinthos, Sikion, Zemenon, Tarsos and Polyfengos",
    "gr-kythira": u"Metropolis of Kythira",
    "gr-larisa": u"Metropolis of Larisa and Tyrnavos",
    "gr-lefkas": u"Metropolis of Lefkas and Ithaki",
    "gr-mani": u"Metropolis of Mani",
    "gr-mantineia": u"Metropolis of Mantineia and Kynouria",
    "gr-megara": u"Metropolis of Megara and Salamis",
    "gr-mesogaia": u"Metropolis of Mesogaia and Lavreotiki",
    "gr-messinia": u"Metropolis of Messinia",
    "gr-monemvasia": u"Metropolis of Monemvasia and Sparta",
    "gr-nafpaktos": u"Metropolis of Nafpaktos and Agios Vlasios",
    "gr-nea-ionia": u"Metropolis of Nea Ionia and Philadelphia",
    "gr-nea-smyrni": u"Metropolis of Nea Smyrni",
    "gr-nikaia": u"Metropolis of Nikaia",
    "gr-paronaxia": u"Metropolis of Paronaxia",
    "gr-patrai": u"Metropolis of Patrai",
    "gr-peiraeus": u"Metropolis of Peiraeus",
    "gr-peristerion": u"Metropolis of Peristerion",
    "gr-phokis": u"Metropolis of Phokis",
    "gr-stagoi": u"Metropolis of Stagoi and Meteora",
    "gr-syros": u"Metropolis of Syros, Tinos, Andros, Kea and Milos",
    "gr-thera": u"Metropolis of Thera, Amorgos, and Nisoi",
    "gr-thessaliotis": u"Metropolis of Thessaliotis and Fanariofersala",
    "gr-thebes": u"Metropolis of Thevai, Levadeia and Aulis",
    "gr-trikki": u"Metropolis of Trikki, Gardiki and Pyli",
    "gr-triphylia": u"Metropolis of Triphylia and Olympia",
    "gr-ydra": u"Metropolis of Ydra, Spetsai and Aigina",
    "gr-zakynthos": u"Metropolis of Zakynthos and Strophades",
    "uoc-balta": u"Balta Eparchy",
    "uoc-berdiansk": u"Berdiansk Eparchy",
    "uoc-bila-tserkva": u"Bila Tserkva Eparchy",
    "uoc-boryspil": u"Boryspil Eparchy",
    "uoc-cherkasy": u"Cherkasy Eparchy",
    "uoc-chernihiv": u"Chernihiv Eparchy",
    "uoc-chernivtsi": u"Chernivtsi-Bukovyna Eparchy",
    "uoc-dnipropetrovsk": u"Dnipropetrovsk Eparchy",
    "uoc-donetsk": u"Donetsk Eparchy",
    "uoc-dzhankoi": u"Dzhankoi Eparchy",
    "uoc-feodosia": u"Feodosia Eparchy",
    "uoc-horlivka": u"Horlivka Eparchy",
    "uoc-ivano-frankivsk": u"Ivano-Frankivsk Eparchy",
    "uoc-izium": u"Izium Eparchy",
    "uoc-kamianets-podilskyi": u"Kamianets-Podilskyi Eparchy",
    "uoc-kamianske": u"Kamianske Eparchy",
    "uoc-kharkiv": u"Kharkiv Eparchy",
    "uoc-kherson": u"Kherson Eparchy",
    "uoc-khmelnytskyi": u"Khmelnytskyi Eparchy",
    "uoc-khust": u"Khust Eparchy",
    "uoc-kirovohrad": u"Kirovohrad Eparchy",
    "uoc-konotop": u"Konotop Eparchy",
    "uoc-kremenchuk": u"Kremenchuk Eparchy",
    "uoc-kryvyi-rih": u"Kryvyi Rih Eparchy",
    "uoc-kyiv": u"Kyiv Eparchy",
    "uoc-luhansk": u"Luhansk Eparchy",
    "uoc-lviv": u"Lviv Eparchy",
    "uoc-mohyliv-podilskyi": u"Mohyliv-Podilskyi Eparchy",
    "uoc-mukachevo": u"Mukachevo Eparchy",
    "uoc-mykolaiv": u"Mykolaiv Eparchy",
    "uoc-nizhyn": u"Nizhyn Eparchy",
    "uoc-nova-kakhovka": u"Nova Kakhovka Eparchy",
    "uoc-odesa": u"Odesa Eparchy",
    "uoc-oleksandriia": u"Oleksandriia Eparchy",
    "uoc-ovruch": u"Ovruch Eparchy",
    "uoc-poltava": u"Poltava Eparchy",
    "uoc-rivne": u"Rivne Eparchy",
    "uoc-romny": u"Romny Eparchy",
    "uoc-rovenky": u"Rovenky Eparchy",
    "uoc-sarny": u"Sarny Eparchy",
    "uoc-shepetivka": u"Shepetivka Eparchy",
    "uoc-sievierodonetsk": u"Sievierodonetsk Eparchy",
    "uoc-simferopol": u"Simferopol Eparchy",
    "uoc-sumy": u"Sumy Eparchy",
    "uoc-ternopil": u"Ternopil Eparchy",
    "uoc-tulchyn": u"Tulchyn Eparchy",
    "uoc-uman": u"Uman Eparchy",
    "uoc-vinnytsia": u"Vinnytsia Eparchy",
    "uoc-volodymyr-volynskyi": u"Volodymyr-Volynskyi Eparchy",
    "uoc-volyn": u"Volyn Eparchy",
    "uoc-voznesensk": u"Voznesensk Eparchy",
    "uoc-zaporizhzhia": u"Zaporizhzhia Eparchy",
    "uoc-zhytomyr": u"Zhytomyr Eparchy",
    "ocu-cherkasy": u"Cherkasy Eparchy",
    "ocu-chernihiv": u"Chernihiv Eparchy",
    "ocu-chernivtsi": u"Chernivtsi Eparchy",
    "ocu-crimea": u"Crimea Eparchy",
    "ocu-dnipropetrovsk": u"Dnipropetrovsk Eparchy",
    "ocu-donetsk": u"Donetsk Eparchy",
    "ocu-drohobych": u"Drohobych-Sambir Eparchy",
    "ocu-ivano-frankivsk": u"Ivano-Frankivsk Eparchy",
    "ocu-kharkiv": u"Kharkiv Eparchy",
    "ocu-kharkiv-poltava": u"Kharkiv-Poltava Eparchy",
    "ocu-kherson": u"Kherson Eparchy",
    "ocu-khmelnytskyi": u"Khmelnytskyi Eparchy",
    "ocu-kirovohrad": u"Kirovohrad Eparchy",
    "ocu-kolomyia": u"Kolomyia Eparchy",
    "ocu-kyiv": u"Kyiv Eparchy",
    "ocu-luhansk": u"Luhansk Eparchy",
    "ocu-lviv": u"Lviv Eparchy",
    "ocu-mukachevo": u"Mukachevo-Karpaty Eparchy",
    "ocu-mykolaiv": u"Mykolaiv Eparchy",
    "ocu-odesa": u"Odesa Eparchy",
    "ocu-pereiaslav": u"Pereiaslav-Vyshneve Eparchy",
    "ocu-poltava": u"Poltava Eparchy",
    "ocu-rivne": u"Rivne Eparchy",
    "ocu-sumy": u"Sumy Eparchy",
    "ocu-ternopil": u"Ternopil Eparchy",
    "ocu-ternopil-buchach": u"Ternopil-Buchach Eparchy",
    "ocu-ternopil-terebovlia": u"Ternopil-Terebovlia Eparchy",
    "ocu-vinnytsia": u"Vinnytsia Eparchy",
    "ocu-vinnytsia-bar": u"Vinnytsia-Bar Eparchy",
    "ocu-vinnytsia-tulchyn": u"Vinnytsia-Tulchyn Eparchy",
    "ocu-volodymyr-volynskyi": u"Volodymyr-Volynskyi Eparchy",
    "ocu-volyn": u"Volyn Eparchy",
    "ocu-zakarpattia": u"Zakarpattia Eparchy",
    "ocu-zaporizhzhia": u"Zaporizhzhia Eparchy",
    "ocu-zhytomyr-ovruch": u"Zhytomyr-Ovruch Eparchy",
    "ocu-zhytomyr-polissia": u"Zhytomyr-Polissia Eparchy",
    "china": u"The Chinese Autonomous Orthodox Church",
    "latvia": u"The Latvian Orthodox Church",
    "moldova": u"The Orthodox Church of Moldova",
    "estonia-ekok": u"Estonian Orthodox Christian Church",
    "belarus": u"The Belarusian Exarchate",
    "athos": u"Monastic Community of the Holy Mountain",
    "ge-akhalkalaki": u"Eparchy of Akhalkalaki and Kumurdo",
    "ge-akhaltsikhe": u"Eparchy of Akhaltsikhe and Tao-Klarjeti",
    "ge-alaverdi": u"Eparchy of Alaverdi",
    "ge-batumi": u"Eparchy of Batumi and Lazeti",
    "ge-bichvinta": u"Eparchy of Bichvinta and Tskhum-Abkhazia",
    "ge-bodbe": u"Eparchy of Bodbe",
    "ge-bolnisi": u"Eparchy of Bolnisi",
    "ge-borjomi": u"Eparchy of Borjomi and Bakuriani",
    "ge-chiatura": u"Eparchy of Chiatura and Sachkhere",
    "ge-chqondidi": u"Eparchy of Chqondidi",
    "ge-dmanisi": u"Eparchy of Dmanisi and Agarak-Tashiri",
    "ge-gori": u"Eparchy of Gori and Ateni",
    "ge-gurjaani": u"Eparchy of Gurjaani and Velistsikhe",
    "ge-khoni": u"Eparchy of Khoni and Samtredia",
    "ge-khornabuji": u"Eparchy of Khornabuji and Hereti",
    "ge-kutaisi": u"Eparchy of Kutaisi and Gaenati",
    "ge-manglisi": u"Eparchy of Manglisi and Tetritsqaro",
    "ge-margveti": u"Eparchy of Margveti and Ubisi",
    "ge-marneuli": u"Eparchy of Marneuli and Hujabi",
    "ge-martqopi": u"Eparchy of Martqopi and Gardabani",
    "ge-mestia": u"Eparchy of Mestia and Upper Svaneti",
    "ge-mtskheta-tbilisi": u"Eparchy of Mtskheta-Tbilisi",
    "ge-nekresi": u"Eparchy of Nekresi",
    "ge-nikortsminda": u"Eparchy of Nikortsminda",
    "ge-nikozi": u"Eparchy of Nikozi and Tskhinvali",
    "ge-poti": u"Eparchy of Poti and Khobi",
    "ge-ruisi": u"Eparchy of Ruisi and Urbnisi",
    "ge-rustavi": u"Eparchy of Rustavi",
    "ge-sagarejo": u"Eparchy of Sagarejo and Ninotsminda",
    "ge-samtavisi": u"Eparchy of Samtavisi and Kaspi",
    "ge-senaki": u"Eparchy of Senaki and Chkhorotsqu",
    "ge-shemokmedi": u"Eparchy of Shemokmedi",
    "ge-skhalta": u"Eparchy of Skhalta",
    "ge-stepantsminda": u"Eparchy of Stepantsminda and Khevi",
    "ge-surami": u"Eparchy of Surami and Khashuri",
    "ge-tianeti": u"Eparchy of Tianeti and Pshav-Khevsureti",
    "ge-tqibuli": u"Eparchy of Tqibuli and Terjola",
    "ge-tsageri": u"Eparchy of Tsageri and Lentekhi",
    "ge-tsalka": u"Eparchy of Tsalka",
    "ge-tsilkani": u"Eparchy of Tsilkani and Dusheti",
    "ge-vani": u"Eparchy of Vani and Baghdati",
    "ge-zugdidi": u"Eparchy of Zugdidi and Tsaishi",
    "sr-belgrade-karlovci": u"Archbishopric of Belgrade and Karlovci",
    "sr-austria-switzerland": u"Eparchy of Austria and Switzerland",
    "sr-backa": u"Eparchy of Backa",
    "sr-banat": u"Eparchy of Banat",
    "sr-banja-luka": u"Eparchy of Banja Luka",
    "sr-bihac-petrovac": u"Eparchy of Bihac and Petrovac",
    "sr-branicevo": u"Eparchy of Branicevo",
    "sr-britain-scandinavia": u"Eparchy of Britain and Scandinavia",
    "sr-buda": u"Eparchy of Buda",
    "sr-budimlja-niksic": u"Eparchy of Budimlja and Niksic",
    "sr-buenos-aires": u"Eparchy of Buenos Aires",
    "sr-canada": u"Eparchy of Canada",
    "sr-dalmatia": u"Eparchy of Dalmatia",
    "sr-dusseldorf-germany": u"Eparchy of Duesseldorf and Germany",
    "sr-gornji-karlovac": u"Eparchy of Gornji Karlovac",
    "sr-krusevac": u"Eparchy of Krusevac",
    "sr-milesevo": u"Eparchy of Mileseva",
    "sr-nis": u"Eparchy of Nis",
    "sr-osijek-baranja": u"Eparchy of Osijek-Polje and Baranja",
    "sr-raska-prizren": u"Eparchy of Raska and Prizren",
    "sr-sabac": u"Eparchy of Sabac",
    "sr-slavonia": u"Eparchy of Slavonia",
    "sr-srem": u"Eparchy of Srem",
    "sr-sumadija": u"Eparchy of Sumadija",
    "sr-timisoara": u"Eparchy of Timisoara",
    "sr-timok": u"Eparchy of Timok",
    "sr-valjevo": u"Eparchy of Valjevo",
    "sr-vranje": u"Eparchy of Vranje",
    "sr-western-europe": u"Eparchy of Western Europe",
    "sr-zahumlje-herzegovina": u"Eparchy of Zahumlje and Herzegovina",
    "sr-zica": u"Eparchy of Zica",
    "sr-zvornik-tuzla": u"Eparchy of Zvornik and Tuzla",
    "sr-australia-new-zealand": u"Metropolitanate of Australia and New Zealand",
    "sr-dabar-bosna": u"Metropolitanate of Dabar-Bosna",
    "sr-montenegro-littoral": u"Metropolitanate of Montenegro and the Littoral",
    "sr-zagreb-ljubljana": u"Metropolitanate of Zagreb and Ljubljana",
    "bg-western-central-europe": u"Bulgarian Eastern Orthodox Diocese of Western and Central Europe",
    "bg-dorostol": u"Diocese of Dorostol",
    "bg-lovech": u"Diocese of Lovech",
    "bg-nevrokop": u"Diocese of Nevrokop",
    "bg-pleven": u"Diocese of Pleven",
    "bg-plovdiv": u"Diocese of Plovdiv",
    "bg-ruse": u"Diocese of Ruse",
    "bg-sliven": u"Diocese of Sliven",
    "bg-sofia": u"Diocese of Sofia",
    "bg-stara-zagora": u"Diocese of Stara Zagora",
    "bg-varna": u"Diocese of Varna and Veliki Preslav",
    "bg-veliko-tarnovo": u"Diocese of Veliko Tarnovo",
    "bg-vidin": u"Diocese of Vidin",
    "bg-vratsa": u"Diocese of Vratsa",
    "cn-labdarin": u"Church of St Innocent of Irkutsk in Labdarin",
    "cn-harbin": u"Church of the Intercession in Harbin",
    "cy-archbishopric": u"Holy Archbishopric of Cyprus",
    "cy-amathus": u"Holy Bishopric of Amathus",
    "cy-arsinoe": u"Holy Bishopric of Arsinoe",
    "cy-karpasia": u"Holy Bishopric of Karpasia",
    "cy-constantia": u"Holy Metropolis of Constantia and Ammochostos",
    "cy-kition": u"Holy Metropolis of Kition",
    "cy-kykkos": u"Holy Metropolis of Kykkos and Tillyria",
    "cy-kyrenia": u"Holy Metropolis of Kyrenia",
    "cy-limassol": u"Holy Metropolis of Limassol",
    "cy-morphou": u"Holy Metropolis of Morphou",
    "cy-paphos": u"Holy Metropolis of Paphos",
    "cy-tamasos": u"Holy Metropolis of Tamasos and Oreini",
    "cy-trimythous": u"Holy Metropolis of Trimythous",
    "pl-bialystok-gdansk": u"Diocese of Bialystok and Gdansk",
    "pl-lodz-poznan": u"Diocese of Lodz and Poznan",
    "pl-lublin-chelm": u"Diocese of Lublin and Chelm",
    "pl-przemysl-gorlice": u"Diocese of Przemysl and Gorlice",
    "pl-warsaw-bielsk": u"Diocese of Warsaw and Bielsk",
    "pl-wroclaw-szczecin": u"Diocese of Wroclaw and Szczecin",
    "pl-army-ordinariate": u"Orthodox Ordinariate of the Polish Army",
    "mk-bregalnica": u"Diocese of Bregalnica",
    "mk-debar-kicevo": u"Diocese of Debar and Kicevo",
    "mk-kumanovo-osogovo": u"Diocese of Kumanovo and Osogovo",
    "mk-povardarie": u"Diocese of Povardarie",
    "mk-prespa-pelagonia": u"Diocese of Prespa and Pelagonia",
    "mk-skopje": u"Diocese of Skopje",
    "mk-strumica": u"Diocese of Strumica",
    "mk-tetovo-gostivar": u"Diocese of Tetovo and Gostivar",
    "al-tirana-durres": u"Archdiocese of Tirana and Durrës",
    "al-apollonia-fier": u"Metropolis of Apollonia and Fier",
    "al-berat": u"Metropolis of Berat",
    "al-elbasan": u"Metropolis of Elbasan",
    "al-gjirokaster": u"Metropolis of Gjirokastër",
    "al-korce": u"Metropolis of Korçë",
    "cs-michalovce-kosice": u"Eparchy of Michalovce and Kosice",
    "cs-olomouc-brno": u"Eparchy of Olomouc and Brno",
    "cs-prague": u"Eparchy of Prague",
    "cs-presov": u"Eparchy of Presov",
    # Each lane writes under its own line, so that five of them can
    # add to this list at once without landing on each other.
    # -- names: greece
    # -- names: constantinople
    "ep-constantinople": u"Archdiocese of Constantinople",
    "ep-crete-synod": u"Eparchial Synod of the Church of Crete",
    "ep-mon-alabama": u"Sacred Patriarchal and Stavropegic Monastery of the "
                      u"Entry of the Theotokos in Alabama, USA",
    "ep-mon-anastasia": u"Sacred Royal, Patriarchal and Stavropegic Monastery "
                        u"of Saint Anastasia Pharmakolytria in Chakidiki",
    "ep-mon-essex": u"Sacred Patriarchal and Stavropegic Monastery of the "
                    u"Venerable Forerunner in Essex, UK",
    "ep-mon-kyiv": u"Stavropegic Monastery of the Ecumenical Patriarchate "
                   u"in Kyiv",
    "ep-mon-st-irene": u"Sacred Patriarchal and Stavropegic Monastery of "
                       u"Saint Irene Chrysovalantou in Astoria, NY, USA",
    "ep-mon-vlatades": u"Sacred Royal, Patriarchal and Stavropegic Monastery "
                       u"of Vlatades in Thessaloniki",
    # -- names: russia
    # -- names: balkans
    # -- names: ukraine-antioch
}
SEATS = {
    "Istanbul": u"Istanbul",
    "Alexandria": u"Alexandria",
    "Damascus": u"Damascus",
    "Jerusalem": u"Jerusalem",
    "Moscow": u"Moscow",
    "Tbilisi": u"Tbilisi",
    "Belgrade": u"Belgrade",
    "Bucharest": u"Bucharest",
    "Sofia": u"Sofia",
    "Nicosia": u"Nicosia",
    "Athens": u"Athens",
    "Tirana": u"Tirana",
    "Warsaw": u"Warsaw",
    "Prešov": u"Prešov",
    "Syosset, New York": u"Syosset, New York",
    "Skopje": u"Skopje",
    "Kyiv": u"Kyiv",
    "Mount Sinai": u"Mount Sinai",
    "Helsinki": u"Helsinki",
    "Tokyo": u"Tokyo",
    "Tallinn": u"Tallinn",
    "Alexandria, Virginia": u"Alexandria, Virginia",
    "Alhambra, California": u"Alhambra, California",
    "Anchorage, Alaska": u"Anchorage, Alaska",
    "Bath, Pennsylvania": u"Bath, Pennsylvania",
    "Bonn": u"Bonn",
    "Boston, Massachusetts": u"Boston, Massachusetts",
    "Bronxville, New York": u"Bronxville, New York",
    "Brussels": u"Brussels",
    "Chambesy": u"Chambesy",
    "Chicago, Illinois": u"Chicago, Illinois",
    "Cranberry Township, Pennsylvania": u"Cranberry Township, Pennsylvania",
    "Dallas, Texas": u"Dallas, Texas",
    "Englewood, New Jersey": u"Englewood, New Jersey",
    "Hong Kong": u"Hong Kong",
    "Jackson, Michigan": u"Jackson, Michigan",
    "Johnstown, Pennsylvania": u"Johnstown, Pennsylvania",
    "London": u"London",
    "Madrid": u"Madrid",
    "Mexico City": u"Mexico City",
    "New Rochelle, New York": u"New Rochelle, New York",
    "New York": u"New York",
    "Paris": u"Paris",
    "Rawdon, Quebec": u"Rawdon, Quebec",
    "San Francisco, California": u"San Francisco, California",
    "Seoul": u"Seoul",
    "Singapore": u"Singapore",
    "Somerset, New Jersey": u"Somerset, New Jersey",
    "Stockholm": u"Stockholm",
    "Third Lake, Illinois": u"Third Lake, Illinois",
    "Toledo, Ohio": u"Toledo, Ohio",
    "Venice": u"Venice",
    "Vienna": u"Vienna",
    "Windsor, Connecticut": u"Windsor, Connecticut",
    "Winnipeg, Manitoba": u"Winnipeg, Manitoba",
    "Chisinau": u"Chisinau",
    "Cluj-Napoca": u"Cluj-Napoca",
    "Constanta": u"Constanta",
    "Craiova": u"Craiova",
    "Jassy": u"Jassy",
    "Limours": u"Limours",
    "Nuremberg": u"Nuremberg",
    "Sibiu": u"Sibiu",
    "Timisoara": u"Timisoara",
    "Accra": u"Accra",
    "Addis Ababa": u"Addis Ababa",
    "Alba Iulia": u"Alba Iulia",
    "Aleppo": u"Aleppo",
    "Alexandria, Teleorman": u"Alexandria, Teleorman",
    "Antananarivo": u"Antananarivo",
    "Arad": u"Arad",
    "Arusha": u"Arusha",
    "Baghdad": u"Baghdad",
    "Baia Mare": u"Baia Mare",
    "Balti": u"Balti",
    "Beirut": u"Beirut",
    "Blantyre": u"Blantyre",
    "Brummana": u"Brummana",
    "Buenos Aires": u"Buenos Aires",
    "Bujumbura": u"Bujumbura",
    "Bukoba": u"Bukoba",
    "Buzau": u"Buzau",
    "Cahul": u"Cahul",
    "Cairo": u"Cairo",
    "Cape Town": u"Cape Town",
    "Caransebes": u"Caransebes",
    "Cheikh Taba": u"Cheikh Taba",
    "Cologne": u"Cologne",
    "Conakry": u"Conakry",
    "Curtea de Arges": u"Curtea de Arges",
    "Dar es Salaam": u"Dar es Salaam",
    "Deva": u"Deva",
    "Drobeta-Turnu Severin": u"Drobeta-Turnu Severin",
    "Dublin": u"Dublin",
    "Enfield": u"Enfield",
    "Gaborone": u"Gaborone",
    "Galati": u"Galati",
    "Giurgiu": u"Giurgiu",
    "Goma": u"Goma",
    "Gulu": u"Gulu",
    "Gyula": u"Gyula",
    "Hama": u"Hama",
    "Haninge": u"Haninge",
    "Harare": u"Harare",
    "Homs": u"Homs",
    "Husi": u"Husi",
    "Ismailia": u"Ismailia",
    "Jinja": u"Jinja",
    "Johannesburg": u"Johannesburg",
    "Juba": u"Juba",
    "Kampala": u"Kampala",
    "Kananga": u"Kananga",
    "Kapsabet": u"Kapsabet",
    "Khartoum": u"Khartoum",
    "Kigali": u"Kigali",
    "Kinshasa": u"Kinshasa",
    "Kisangani": u"Kisangani",
    "Kisumu": u"Kisumu",
    "Kuopio": u"Kuopio",
    "Lagos": u"Lagos",
    "Lattakia": u"Lattakia",
    "Lubumbashi": u"Lubumbashi",
    "Lusaka": u"Lusaka",
    "Marjayoun": u"Marjayoun",
    "Melton West, Victoria": u"Melton West, Victoria",
    "Miercurea-Ciuc": u"Miercurea-Ciuc",
    "Minya": u"Minya",
    "Nairobi": u"Nairobi",
    "Nyeri": u"Nyeri",
    "Oradea": u"Oradea",
    "Oulu": u"Oulu",
    "Pointe-Noire": u"Pointe-Noire",
    "Port Said": u"Port Said",
    "Porto-Novo": u"Porto-Novo",
    "Ramnicu Valcea": u"Ramnicu Valcea",
    "Roman": u"Roman",
    "Rome": u"Rome",
    "Saint-Hubert, Quebec": u"Saint-Hubert, Quebec",
    "Santiago": u"Santiago",
    "Sao Paulo": u"Sao Paulo",
    "Slatina": u"Slatina",
    "Slobozia": u"Slobozia",
    "Suceava": u"Suceava",
    "Suwayda": u"Suwayda",
    "Sydney": u"Sydney",
    "Tanta": u"Tanta",
    "Targoviste": u"Targoviste",
    "Toliara": u"Toliara",
    "Tripoli": u"Tripoli",
    "Tulcea": u"Tulcea",
    "Tunis": u"Tunis",
    "Vrsac": u"Vrsac",
    "Yaounde": u"Yaounde",
    "Zahleh": u"Zahleh",
    "Zalau": u"Zalau",
    "Abakan": u"Abakan",
    "Akhtubinsk": u"Akhtubinsk",
    "Akko": u"Akko",
    "Aktobe": u"Aktobe",
    "Alapayevsk": u"Alapayevsk",
    "Alatyr": u"Alatyr",
    "Aleksandrov": u"Aleksandrov",
    "Alexandroupolis": u"Alexandroupolis",
    "Almaty": u"Almaty",
    "Almetevsk": u"Almetevsk",
    "Amman": u"Amman",
    "Anadyr": u"Anadyr",
    "Antalya": u"Antalya",
    "Ardatov": u"Ardatov",
    "Arkhangelsk": u"Arkhangelsk",
    "Armavir": u"Armavir",
    "Arnaia": u"Arnaia",
    "Arsenev": u"Arsenev",
    "Ashgabat": u"Ashgabat",
    "Astrakhan": u"Astrakhan",
    "Atlanta, Georgia": u"Atlanta, Georgia",
    "Babruysk": u"Babruysk",
    "Baku": u"Baku",
    "Balakovo": u"Balakovo",
    "Balashikha": u"Balashikha",
    "Balashov": u"Balashov",
    "Bangkok": u"Bangkok",
    "Barnaul": u"Barnaul",
    "Barysaw": u"Barysaw",
    "Barysh": u"Barysh",
    "Belgorod": u"Belgorod",
    "Belyov": u"Belyov",
    "Berlin": u"Berlin",
    "Bezhetsk": u"Bezhetsk",
    "Birobidzhan": u"Birobidzhan",
    "Birsk": u"Birsk",
    "Bishkek": u"Bishkek",
    "Biysk": u"Biysk",
    "Blagoveshchensk": u"Blagoveshchensk",
    "Borisoglebsk": u"Borisoglebsk",
    "Borovichi": u"Borovichi",
    "Bratsk": u"Bratsk",
    "Brest": u"Brest",
    "Brookline, Massachusetts": u"Brookline, Massachusetts",
    "Bryansk": u"Bryansk",
    "Budapest": u"Budapest",
    "Bursa": u"Bursa",
    "Buzuluk": u"Buzuluk",
    "Chania": u"Chania",
    "Cheboksary": u"Cheboksary",
    "Chelyabinsk": u"Chelyabinsk",
    "Cherepovets": u"Cherepovets",
    "Chernyakhovsk": u"Chernyakhovsk",
    "Chios": u"Chios",
    "Chistopol": u"Chistopol",
    "Chita": u"Chita",
    "Daugavpils": u"Daugavpils",
    "Delvinaki": u"Delvinaki",
    "Denver, Colorado": u"Denver, Colorado",
    "Des Plaines": u"Des Plaines",
    "Didymoteicho": u"Didymoteicho",
    "Dimitrovgrad": u"Dimitrovgrad",
    "Doha": u"Doha",
    "Drama": u"Drama",
    "Dushanbe": u"Dushanbe",
    "Edessa": u"Edessa",
    "Edinet": u"Edinet",
    "Elassona": u"Elassona",
    "Eleftheroupoli": u"Eleftheroupoli",
    "Elista": u"Elista",
    "Engels": u"Engels",
    "Florina": u"Florina",
    "Galich": u"Galich",
    "Gatchina": u"Gatchina",
    "Gaza": u"Gaza",
    "Georgiyevsk": u"Georgiyevsk",
    "Glazov": u"Glazov",
    "Gorno-Altaysk": u"Gorno-Altaysk",
    "Gorodets": u"Gorodets",
    "Goumenissa": u"Goumenissa",
    "Grevena": u"Grevena",
    "Grozny": u"Grozny",
    "Gubkin": u"Gubkin",
    "Heraklion": u"Heraklion",
    "Homel": u"Homel",
    "Hrodna": u"Hrodna",
    "Imbros": u"Imbros",
    "Ioannina": u"Ioannina",
    "Irkutsk": u"Irkutsk",
    "Ishim": u"Ishim",
    "Isilkul": u"Isilkul",
    "Iskitim": u"Iskitim",
    "Ivanovo": u"Ivanovo",
    "Izhevsk": u"Izhevsk",
    "Izmir": u"Izmir",
    "Jaffa": u"Jaffa",
    "Kalach-on-Don": u"Kalach-on-Don",
    "Kalachinsk": u"Kalachinsk",
    "Kalamaria": u"Kalamaria",
    "Kaliningrad": u"Kaliningrad",
    "Kalloni": u"Kalloni",
    "Kaluga": u"Kaluga",
    "Kamensk-Uralsky": u"Kamensk-Uralsky",
    "Kanash": u"Kanash",
    "Kansk": u"Kansk",
    "Karaganda": u"Karaganda",
    "Karasuk": u"Karasuk",
    "Karpathos": u"Karpathos",
    "Kasimov": u"Kasimov",
    "Kastoria": u"Kastoria",
    "Katerini": u"Katerini",
    "Kavala": u"Kavala",
    "Kazan": u"Kazan",
    "Kemerovo": u"Kemerovo",
    "Khabarovsk": u"Khabarovsk",
    "Khanty-Mansiysk": u"Khanty-Mansiysk",
    "Kilkis": u"Kilkis",
    "Kinel": u"Kinel",
    "Kineshma": u"Kineshma",
    "Kirov": u"Kirov",
    "Kissamos": u"Kissamos",
    "Klintsy": u"Klintsy",
    "Kokshetau": u"Kokshetau",
    "Kolomna": u"Kolomna",
    "Kolpashevo": u"Kolpashevo",
    "Komotini": u"Komotini",
    "Komsomolsk-on-Amur": u"Komsomolsk-on-Amur",
    "Kos": u"Kos",
    "Kostanay": u"Kostanay",
    "Kostomuksha": u"Kostomuksha",
    "Kostroma": u"Kostroma",
    "Kotlas": u"Kotlas",
    "Kozani": u"Kozani",
    "Kozelsk": u"Kozelsk",
    "Krasnodar": u"Krasnodar",
    "Krasnoslobodsk": u"Krasnoslobodsk",
    "Krasnoturyinsk": u"Krasnoturyinsk",
    "Krasnoyarsk": u"Krasnoyarsk",
    "Kudymkar": u"Kudymkar",
    "Kurgan": u"Kurgan",
    "Kursk": u"Kursk",
    "Kuybyshev": u"Kuybyshev",
    "Kuznetsk": u"Kuznetsk",
    "Kyoto": u"Kyoto",
    "Kyzyl": u"Kyzyl",
    "Lagadas": u"Lagadas",
    "Leros": u"Leros",
    "Lida": u"Lida",
    "Lipetsk": u"Lipetsk",
    "Livny": u"Livny",
    "Lyskovo": u"Lyskovo",
    "Magadan": u"Magadan",
    "Magnitogorsk": u"Magnitogorsk",
    "Mahilyow": u"Mahilyow",
    "Makhachkala": u"Makhachkala",
    "Maladzyechna": u"Maladzyechna",
    "Manila": u"Manila",
    "Maykop": u"Maykop",
    "Mazyr": u"Mazyr",
    "Michurinsk": u"Michurinsk",
    "Minsk": u"Minsk",
    "Minusinsk": u"Minusinsk",
    "Montreal": u"Montreal",
    "Munich": u"Munich",
    "Murmansk": u"Murmansk",
    "Murom": u"Murom",
    "Myrina": u"Myrina",
    "Mytilene": u"Mytilene",
    "Naberezhnye Chelny": u"Naberezhnye Chelny",
    "Nakhodka": u"Nakhodka",
    "Narva": u"Narva",
    "Naryan-Mar": u"Naryan-Mar",
    "Navahrudak": u"Navahrudak",
    "Nazareth": u"Nazareth",
    "Nea Zichni": u"Nea Zichni",
    "Neapoli": u"Neapoli",
    "Neftekamsk": u"Neftekamsk",
    "Nerchinsk": u"Nerchinsk",
    "Nikolayevsk-on-Amur": u"Nikolayevsk-on-Amur",
    "Nizhny Novgorod": u"Nizhny Novgorod",
    "Nizhny Tagil": u"Nizhny Tagil",
    "Norilsk": u"Norilsk",
    "Novokuznetsk": u"Novokuznetsk",
    "Novorossiysk": u"Novorossiysk",
    "Novosibirsk": u"Novosibirsk",
    "Odintsovo": u"Odintsovo",
    "Omsk": u"Omsk",
    "Orenburg": u"Orenburg",
    "Orsk": u"Orsk",
    "Oryol": u"Oryol",
    "Otradny": u"Otradny",
    "Paramythia": u"Paramythia",
    "Patmos": u"Patmos",
    "Pavlodar": u"Pavlodar",
    "Penza": u"Penza",
    "Pereslavl-Zalessky": u"Pereslavl-Zalessky",
    "Perm": u"Perm",
    "Petropavl": u"Petropavl",
    "Petropavlovsk-Kamchatsky": u"Petropavlovsk-Kamchatsky",
    "Petrozavodsk": u"Petrozavodsk",
    "Pinsk": u"Pinsk",
    "Pittsburgh, Pennsylvania": u"Pittsburgh, Pennsylvania",
    "Plesetsk": u"Plesetsk",
    "Podolsk": u"Podolsk",
    "Polatsk": u"Polatsk",
    "Polygyros": u"Polygyros",
    "Preveza": u"Preveza",
    "Pskov": u"Pskov",
    "Pyatigorsk": u"Pyatigorsk",
    "Pärnu": u"Pärnu",
    "Rethymno": u"Rethymno",
    "Rhodes": u"Rhodes",
    "Riga": u"Riga",
    "Roslavl": u"Roslavl",
    "Rossosh": u"Rossosh",
    "Rostov-on-Don": u"Rostov-on-Don",
    "Rubtsovsk": u"Rubtsovsk",
    "Ryazan": u"Ryazan",
    "Rybinsk": u"Rybinsk",
    "Rzhev": u"Rzhev",
    "Saint Petersburg": u"Saint Petersburg",
    "Salavat": u"Salavat",
    "Salekhard": u"Salekhard",
    "Samara": u"Samara",
    "Samos": u"Samos",
    "San Francisco": u"San Francisco",
    "Saransk": u"Saransk",
    "Sarapul": u"Sarapul",
    "Saratov": u"Saratov",
    "Sayansk": u"Sayansk",
    "Sendai": u"Sendai",
    "Serdobsk": u"Serdobsk",
    "Sergiyev Posad": u"Sergiyev Posad",
    "Serres": u"Serres",
    "Severobaykalsk": u"Severobaykalsk",
    "Severomorsk": u"Severomorsk",
    "Shadrinsk": u"Shadrinsk",
    "Shakhty": u"Shakhty",
    "Shchigry": u"Shchigry",
    "Shuya": u"Shuya",
    "Shymkent": u"Shymkent",
    "Siatista": u"Siatista",
    "Siderokastro": u"Siderokastro",
    "Skopin": u"Skopin",
    "Slavgorod": u"Slavgorod",
    "Slutsk": u"Slutsk",
    "Smolensk": u"Smolensk",
    "Sochi": u"Sochi",
    "Solikamsk": u"Solikamsk",
    "Soroca": u"Soroca",
    "Stavropol": u"Stavropol",
    "Syktyvkar": u"Syktyvkar",
    "Syme": u"Syme",
    "Syzran": u"Syzran",
    "Taldykorgan": u"Taldykorgan",
    "Tambov": u"Tambov",
    "Tara": u"Tara",
    "Tartu": u"Tartu",
    "Tashkent": u"Tashkent",
    "The Hague": u"The Hague",
    "Thessaloniki": u"Thessaloniki",
    "Tikhoretsk": u"Tikhoretsk",
    "Tikhvin": u"Tikhvin",
    "Tiraspol": u"Tiraspol",
    "Tobolsk": u"Tobolsk",
    "Tolyatti": u"Tolyatti",
    "Tomsk": u"Tomsk",
    "Toronto, Ontario": u"Toronto, Ontario",
    "Troitsk": u"Troitsk",
    "Tula": u"Tula",
    "Tver": u"Tver",
    "Ufa": u"Ufa",
    "Ulan-Ude": u"Ulan-Ude",
    "Ulyanovsk": u"Ulyanovsk",
    "Ungheni": u"Ungheni",
    "Uralsk": u"Uralsk",
    "Uryupinsk": u"Uryupinsk",
    "Urzhum": u"Urzhum",
    "Ust-Kamenogorsk": u"Ust-Kamenogorsk",
    "Uvarovo": u"Uvarovo",
    "Valletta": u"Valletta",
    "Valuyki": u"Valuyki",
    "Vanino": u"Vanino",
    "Velikiye Luki": u"Velikiye Luki",
    "Veliky Novgorod": u"Veliky Novgorod",
    "Veliky Ustyug": u"Veliky Ustyug",
    "Veroia": u"Veroia",
    "Vilnius": u"Vilnius",
    "Vitebsk": u"Vitebsk",
    "Vladikavkaz": u"Vladikavkaz",
    "Vladimir": u"Vladimir",
    "Vladivostok": u"Vladivostok",
    "Volgodonsk": u"Volgodonsk",
    "Volgograd": u"Volgograd",
    "Vologda": u"Vologda",
    "Volzhsk": u"Volzhsk",
    "Vorkuta": u"Vorkuta",
    "Voronezh": u"Voronezh",
    "Vyazma": u"Vyazma",
    "Vyborg": u"Vyborg",
    "Vyksa": u"Vyksa",
    "Westfield, New Jersey": u"Westfield, New Jersey",
    "Xanthi": u"Xanthi",
    "Yakutsk": u"Yakutsk",
    "Yaransk": u"Yaransk",
    "Yaroslavl": u"Yaroslavl",
    "Yekaterinburg": u"Yekaterinburg",
    "Yelets": u"Yelets",
    "Yeniseysk": u"Yeniseysk",
    "Yerevan": u"Yerevan",
    "Yeysk": u"Yeysk",
    "Yoshkar-Ola": u"Yoshkar-Ola",
    "Yugorsk": u"Yugorsk",
    "Yurga": u"Yurga",
    "Yuzhno-Sakhalinsk": u"Yuzhno-Sakhalinsk",
    "Zheleznogorsk": u"Zheleznogorsk",
    "Zlatoust": u"Zlatoust",
    "Aigio": u"Aigio",
    "Amfissa": u"Amfissa",
    "Argostoli": u"Argostoli",
    "Arta": u"Arta",
    "Balta": u"Balta",
    "Berdiansk": u"Berdiansk",
    "Bila Tserkva": u"Bila Tserkva",
    "Chalkida": u"Chalkida",
    "Cherkasy": u"Cherkasy",
    "Chernihiv": u"Chernihiv",
    "Chernivtsi": u"Chernivtsi",
    "Corfu": u"Corfu",
    "Corinth": u"Corinth",
    "Dimitsana": u"Dimitsana",
    "Dnipro": u"Dnipro",
    "Donetsk": u"Donetsk",
    "Dzhankoi": u"Dzhankoi",
    "Ermoupoli": u"Ermoupoli",
    "Fira": u"Fira",
    "Gytheio": u"Gytheio",
    "Horlivka": u"Horlivka",
    "Hydra": u"Hydra",
    "Ilion": u"Ilion",
    "Ivano-Frankivsk": u"Ivano-Frankivsk",
    "Izium": u"Izium",
    "Kaisariani": u"Kaisariani",
    "Kalamata": u"Kalamata",
    "Kalambaka": u"Kalambaka",
    "Kamianets-Podilskyi": u"Kamianets-Podilskyi",
    "Kamianske": u"Kamianske",
    "Karditsa": u"Karditsa",
    "Karpenisi": u"Karpenisi",
    "Kerch": u"Kerch",
    "Kharkiv": u"Kharkiv",
    "Kherson": u"Kherson",
    "Khmelnytskyi": u"Khmelnytskyi",
    "Khust": u"Khust",
    "Kifisia": u"Kifisia",
    "Konotop": u"Konotop",
    "Kremenchuk": u"Kremenchuk",
    "Kropyvnytskyi": u"Kropyvnytskyi",
    "Kryvyi Rih": u"Kryvyi Rih",
    "Kymi": u"Kymi",
    "Kyparissia": u"Kyparissia",
    "Kythira": u"Kythira",
    "Lamia": u"Lamia",
    "Larissa": u"Larissa",
    "Lefkada": u"Lefkada",
    "Livadeia": u"Livadeia",
    "Luhansk": u"Luhansk",
    "Lutsk": u"Lutsk",
    "Lviv": u"Lviv",
    "Megara": u"Megara",
    "Missolonghi": u"Missolonghi",
    "Mohyliv-Podilskyi": u"Mohyliv-Podilskyi",
    "Mukachevo": u"Mukachevo",
    "Mykolaiv": u"Mykolaiv",
    "Nafpaktos": u"Nafpaktos",
    "Nafplio": u"Nafplio",
    "Naxos": u"Naxos",
    "Nea Ionia": u"Nea Ionia",
    "Nea Smyrni": u"Nea Smyrni",
    "Nikaia": u"Nikaia",
    "Nizhyn": u"Nizhyn",
    "Nova Kakhovka": u"Nova Kakhovka",
    "Odesa": u"Odesa",
    "Oleksandriia": u"Oleksandriia",
    "Ovruch": u"Ovruch",
    "Patras": u"Patras",
    "Peristeri": u"Peristeri",
    "Pervomaisk": u"Pervomaisk",
    "Piraeus": u"Piraeus",
    "Poltava": u"Poltava",
    "Pyrgos": u"Pyrgos",
    "Rivne": u"Rivne",
    "Romny": u"Romny",
    "Rovenky": u"Rovenky",
    "Sarny": u"Sarny",
    "Shepetivka": u"Shepetivka",
    "Sievierodonetsk": u"Sievierodonetsk",
    "Simferopol": u"Simferopol",
    "Sparta": u"Sparta",
    "Spata": u"Spata",
    "Sumy": u"Sumy",
    "Ternopil": u"Ternopil",
    "Trikala": u"Trikala",
    "Tulchyn": u"Tulchyn",
    "Uman": u"Uman",
    "Vinnytsia": u"Vinnytsia",
    "Volodymyr": u"Volodymyr",
    "Volos": u"Volos",
    "Voula": u"Voula",
    "Zakynthos": u"Zakynthos",
    "Zaporizhzhia": u"Zaporizhzhia",
    "Zhytomyr": u"Zhytomyr",
    "Drohobych": u"Drohobych",
    "Kolomyia": u"Kolomyia",
    "Uzhhorod": u"Uzhhorod",
    "Akhalkalaki": u"Akhalkalaki",
    "Akhaltsikhe": u"Akhaltsikhe",
    "Alaverdi": u"Alaverdi",
    "Ambrolauri": u"Ambrolauri",
    "Batumi": u"Batumi",
    "Berane": u"Berane",
    "Bijeljina": u"Bijeljina",
    "Bodbe": u"Bodbe",
    "Bolnisi": u"Bolnisi",
    "Borjomi": u"Borjomi",
    "Bosanski Petrovac": u"Bosanski Petrovac",
    "Cabramatta, New South Wales": u"Cabramatta, New South Wales",
    "Cetinje": u"Cetinje",
    "Chiatura": u"Chiatura",
    "Dedoplistsqaro": u"Dedoplistsqaro",
    "Dmanisi": u"Dmanisi",
    "Gardabani": u"Gardabani",
    "Gori": u"Gori",
    "Gotse Delchev": u"Gotse Delchev",
    "Gracanica": u"Gracanica",
    "Gurjaani": u"Gurjaani",
    "Harbin": u"Harbin",
    "Kareli": u"Kareli",
    "Karlovac": u"Karlovac",
    "Kazbegi": u"Kazbegi",
    "Khoni": u"Khoni",
    "Kragujevac": u"Kragujevac",
    "Kraljevo": u"Kraljevo",
    "Krusevac": u"Krusevac",
    "Kutaisi": u"Kutaisi",
    "Kvareli": u"Kvareli",
    "Labdarin": u"Labdarin",
    "Lovech": u"Lovech",
    "Manglisi": u"Manglisi",
    "Marneuli": u"Marneuli",
    "Martvili": u"Martvili",
    "Mestia": u"Mestia",
    "Mtskheta": u"Mtskheta",
    "Nikozi": u"Nikozi",
    "Ninotsminda": u"Ninotsminda",
    "Nis": u"Nis",
    "Ozurgeti": u"Ozurgeti",
    "Pleven": u"Pleven",
    "Plovdiv": u"Plovdiv",
    "Poti": u"Poti",
    "Pozarevac": u"Pozarevac",
    "Ruse": u"Ruse",
    "Rustavi": u"Rustavi",
    "Samtavisi": u"Samtavisi",
    "Sarajevo": u"Sarajevo",
    "Senaki": u"Senaki",
    "Silistra": u"Silistra",
    "Skhalta": u"Skhalta",
    "Sliven": u"Sliven",
    "Sokhumi": u"Sokhumi",
    "Stara Zagora": u"Stara Zagora",
    "Surami": u"Surami",
    "Szentendre": u"Szentendre",
    "Terjola": u"Terjola",
    "Tianeti": u"Tianeti",
    "Trebinje": u"Trebinje",
    "Tsageri": u"Tsageri",
    "Tsalka": u"Tsalka",
    "Tsilkani": u"Tsilkani",
    "Valjevo": u"Valjevo",
    "Vani": u"Vani",
    "Varna": u"Varna",
    "Veliko Tarnovo": u"Veliko Tarnovo",
    "Vidin": u"Vidin",
    "Vratsa": u"Vratsa",
    "Zagreb": u"Zagreb",
    "Zajecar": u"Zajecar",
    "Zestaponi": u"Zestaponi",
    "Zugdidi": u"Zugdidi",
    "Agios Tychonas": u"Agios Tychonas",
    "Aigialousa": u"Aigialousa",
    "Bialystok": u"Bialystok",
    "Episkopeio": u"Episkopeio",
    "Famagusta": u"Famagusta",
    "Gorlice": u"Gorlice",
    "Idalion": u"Idalion",
    "Kumanovo": u"Kumanovo",
    "Kyrenia": u"Kyrenia",
    "Larnaca": u"Larnaca",
    "Limassol": u"Limassol",
    "Lodz": u"Lodz",
    "Lublin": u"Lublin",
    "Morphou": u"Morphou",
    "Paphos": u"Paphos",
    "Peristerona": u"Peristerona",
    "Stip": u"Stip",
    "Strumica": u"Strumica",
    "Tetovo": u"Tetovo",
    "Wroclaw": u"Wroclaw",
    "Berat": u"Berat",
    "Elbasan": u"Elbasan",
    "Fier": u"Fier",
    "Gjirokastër": u"Gjirokastër",
    "Korçë": u"Korçë",
    "Michalovce": u"Michalovce",
    "Olomouc": u"Olomouc",
    "Prague": u"Prague",
    "Presov": u"Presov",
    # -- seats: greece
    # -- seats: constantinople
    "Astoria, New York": u"Astoria, New York",
    "Tolleshunt Knights": u"Tolleshunt Knights",
    "Vasilika": u"Vasilika",
    # -- seats: russia
    # -- seats: balkans
    # -- seats: ukraine-antioch
}
