# -*- coding: utf-8 -*-
"""The English the rest are written from.

This file is the list of keys as much as it is a translation: a row id that
is not here is a row nobody has been asked to name, and a seat that is not
here is a city nobody has been asked to place.
"""
NAMES = {
    "constantinople": u"The Church of Constantinople",
    "alexandria": u"The Church of Alexandria",
    "antioch": u"The Church of Antioch",
    "jerusalem": u"The Church of Jerusalem",
    "russia": u"The Church of Russia",
    "georgia": u"The Church of Georgia",
    "serbia": u"The Church of Serbia",
    "romania": u"The Church of Romania",
    "bulgaria": u"The Church of Bulgaria",
    "cyprus": u"The Church of Cyprus",
    "greece": u"The Church of Greece",
    "albania": u"The Church of Albania",
    "poland": u"The Church of Poland",
    "czech-slovakia": u"The Church of the Czech Lands and Slovakia",
    "oca": u"The Orthodox Church in America",
    "macedonia": u"The Macedonian Orthodox Church - Ohrid Archbishopric",
    "ukraine-uoc": u"The Church of Ukraine",
    "ukraine-ocu": u"Orthodox Church of Ukraine",
    "sinai": u"The Church of Sinai",
    "finland": u"The Autonomous Church of Finland",
    "japan": u"The Church of Japan",
    "estonia-eaok": u"Orthodox Church of Estonia",
    "albanian-americas": u"Albanian Orthodox Diocese of the Americas",
    "acrod": u"American Carpatho-Russian Orthodox Diocese of North America",
    "ep-thyateira": u"Archdiocese of Thyateira and Great Britain",
    "goarch": u"Greek Orthodox Archdiocese of America",
    "ep-france": u"Greek Orthodox Metropolis of France",
    "ep-germany": u"Greek Orthodox Metropolis of Germany",
    "ep-austria": u"Holy Metropolis of Austria",
    "ep-korea": u"Holy Metropolis of Korea",
    "ep-spain": u"Holy Metropolis of Spain and Portugal",
    "ep-belgium": u"Metropolis of Belgium",
    "ep-sweden": u"Metropolis of Sweden and All Scandinavia",
    "ep-switzerland": u"Metropolis of Switzerland",
    "ep-hongkong": u"Orthodox Metropolitanate of Hong Kong and South East Asia",
    "ep-singapore": u"Orthodox Metropolitanate of Singapore and South Asia",
    "ep-italy": u"Sacred Orthodox Archdiocese of Italy and Malta",
    "uocc": u"Ukrainian Orthodox Church of Canada",
    "uoc-usa": u"Ukrainian Orthodox Church of the USA",
    "antiochian-na": u"Antiochian Orthodox Christian Archdiocese of North America",
    "rocor": u"Russian Orthodox Church Outside of Russia",
    "mp-parishes-usa": u"The Patriarchal Parishes in the USA",
    "serbian-eastern": u"Diocese of Eastern America",
    "serbian-midwestern": u"Diocese of New Gracanica and Midwestern America",
    "serbian-western": u"Diocese of Western America",
    "romanian-americas": u"Romanian Orthodox Metropolia of the Americas",
    "bulgarian-usa": u"Bulgarian Eastern Orthodox Diocese of the USA, Canada and Australia",
    "oca-albanian": u"Albanian Archdiocese",
    "oca-canada": u"Archdiocese of Canada",
    "oca-washington": u"Archdiocese of Washington, D.C.",
    "oca-western-pa": u"Archdiocese of Western Pennsylvania",
    "oca-bulgarian": u"Bulgarian Diocese",
    "oca-eastern-pa": u"Diocese of Eastern Pennsylvania",
    "oca-mexico": u"Diocese of Mexico",
    "oca-new-england": u"Diocese of New England",
    "oca-ny-nj": u"Diocese of New York and New Jersey",
    "oca-alaska": u"Diocese of Sitka and Alaska",
    "oca-midwest": u"Diocese of the Midwest",
    "oca-south": u"Diocese of the South",
    "oca-west": u"Diocese of the West",
    "oca-romanian": u"Romanian Episcopate",
    "ro-bucharest": u"Archdiocese of Bucharest",
    "ro-chisinau": u"Archdiocese of Chisinau",
    "ro-craiova": u"Archdiocese of Craiova",
    "ro-iasi": u"Archdiocese of Jassy",
    "ro-sibiu": u"Archdiocese of Sibiu",
    "ro-timisoara": u"Archdiocese of Timisoara",
    "ro-tomis": u"Archdiocese of Tomis",
    "ro-cluj": u"Archdiocese of Vad, Feleac and Cluj",
    "ro-western-europe": u"Romanian Orthodox Archdiocese of Western Europe",
    "ro-germany": u"Romanian Orthodox Metropolis of Germany, Central and Northern Europe",
    "ax-accra": u"Holy Archdiocese of Accra",
    "ax-aksum": u"Holy Archdiocese of Aksum",
    "ax-antananarivo": u"Holy Archdiocese of Antananarivo and North Madagascar",
    "ax-cameroon": u"Holy Archdiocese of Cameroon",
    "ax-carthage": u"Holy Archdiocese of Carthage",
    "ax-cyrene": u"Holy Archdiocese of Cyrene",
    "ax-ermoupolis": u"Holy Archdiocese of Ermoupolis",
    "ax-guinea": u"Holy Archdiocese of Guinea",
    "ax-irinopolis": u"Holy Archdiocese of Irinopolis",
    "ax-johannesburg": u"Holy Archdiocese of Johannesburg and Pretoria",
    "ax-kinshasa": u"Holy Archdiocese of Kinshasa",
    "ax-leontopolis": u"Holy Archdiocese of Leontopolis",
    "ax-nairobi": u"Holy Archdiocese of Nairobi",
    "ax-nigeria": u"Holy Archdiocese of Nigeria",
    "ax-nubia": u"Holy Archdiocese of Nubia",
    "ax-ptolemais": u"Holy Archdiocese of Ptolemais",
    "ax-zimbabwe": u"Holy Archdiocese of Zimbabwe and Angola",
    "ax-good-hope": u"Holy Archdiocese of the Cape of Good Hope",
    "ax-arusha": u"Holy Diocese of Arusha and Central Tanzania",
    "ax-benin": u"Holy Diocese of Benin, Togo and Burkina Faso",
    "ax-bujumbura": u"Holy Diocese of Bujumbura and Burundi",
    "ax-bukoba": u"Holy Diocese of Bukoba and West Tanzania",
    "ax-kisangani": u"Holy Diocese of Bunia, Kisangani and Eastern Congo",
    "ax-eldoret": u"Holy Diocese of Eldoret and Northern Kenya",
    "ax-gaborone": u"Holy Diocese of Gaborone and Botswana",
    "ax-goma": u"Holy Diocese of Goma and Great Kivu",
    "ax-gulu": u"Holy Diocese of Gulu and Northern Uganda",
    "ax-jinja": u"Holy Diocese of Jinja and Eastern Uganda",
    "ax-juba": u"Holy Diocese of Juba and South Sudan",
    "ax-kigali": u"Holy Diocese of Kigali and Rwanda",
    "ax-kisumu": u"Holy Diocese of Kisumu and Western Kenya",
    "ax-malawi": u"Holy Diocese of Malawi",
    "ax-nieri": u"Holy Diocese of Nieri and Mount Kenya",
    "ax-toliara": u"Holy Diocese of Toliara and Southern Madagascar",
    "ax-brazzaville": u"Holy Metropolis of Brazzaville and Gabon",
    "ax-caesarea": u"Holy Metropolis of Caesarea",
    "ax-diospolis": u"Holy Metropolis of Diospolis",
    "ax-heliopolis": u"Holy Metropolis of Heliopolis",
    "ax-kampala": u"Holy Metropolis of Kampala",
    "ax-kananga": u"Holy Metropolis of Kananga",
    "ax-katanga": u"Holy Metropolis of Katanga",
    "ax-libya": u"Holy Metropolis of Libya",
    "ax-memphis": u"Holy Metropolis of Memphis",
    "ax-pelusium": u"Holy Metropolis of Pelusium",
    "ax-zambia": u"Holy Metropolis of Zambia and Mozambique",
    "an-akkar": u"Archdiocese of Akkar and Dependencies",
    "an-aleppo": u"Archdiocese of Aleppo, Alexandretta and Dependencies",
    "an-australia": u"Archdiocese of Australia, New Zealand and the Philippines",
    "an-baghdad": u"Archdiocese of Baghdad, Kuwait and Dependencies",
    "an-beirut": u"Archdiocese of Beirut and Dependencies",
    "an-bosra": u"Archdiocese of Bosra, Hauran and Jabal al-Arab",
    "an-buenos-aires": u"Archdiocese of Buenos Aires and All Argentine",
    "an-byblos": u"Archdiocese of Byblos, Batroun and Dependencies",
    "an-france": u"Archdiocese of France, Western and Southern Europe",
    "an-germany": u"Archdiocese of Germany and Central Europe",
    "an-hama": u"Archdiocese of Hama and Dependencies",
    "an-homs": u"Archdiocese of Homs and Dependencies",
    "an-lattakia": u"Archdiocese of Lattakia and Dependencies",
    "an-mexico": u"Archdiocese of Mexico, Venezuela, Central America and the Islands of the Caribbean Sea",
    "an-santiago": u"Archdiocese of Santiago and All Chile",
    "an-sao-paulo": u"Archdiocese of Sao Paulo and All Brazil",
    "an-tripoli": u"Archdiocese of Tripoli, Al-Koura and Dependencies",
    "an-tyre-sidon": u"Archdiocese of Tyre, Sidon and Dependencies",
    "an-zahleh": u"Archdiocese of Zahleh, Baalbek and Dependencies",
    "an-british-isles": u"Archdiocese of the British Isles and Ireland",
    "ro-alba-iulia": u"Archdiocese of Alba Iulia",
    "ro-arad": u"Archdiocese of Arad",
    "ro-arges": u"Archdiocese of Arges and Muscel",
    "ro-buzau": u"Archdiocese of Buzau and Vrancea",
    "ro-lower-danube": u"Archdiocese of Lower Danube",
    "ro-ramnic": u"Archdiocese of Ramnic",
    "ro-roman": u"Archdiocese of Roman and Bacau",
    "ro-suceava": u"Archdiocese of Suceava and Radauti",
    "ro-targoviste": u"Archdiocese of Targoviste",
    "ro-alexandria-teleorman": u"Diocese of Alexandria and Teleorman",
    "ro-balti": u"Diocese of Balti (formerly Hotin)",
    "ro-caransebes": u"Diocese of Caransebes",
    "ro-covasna": u"Diocese of Covasna and Harghita",
    "ro-dacia-felix": u"Diocese of Dacia Felix",
    "ro-deva": u"Diocese of Deva and Hunedoara",
    "ro-giurgiu": u"Diocese of Giurgiu",
    "ro-husi": u"Diocese of Husi",
    "ro-salaj": u"Diocese of Salaj",
    "ro-severin": u"Diocese of Severin and Strehaia",
    "ro-slatina": u"Diocese of Slatina and Romanati",
    "ro-slobozia": u"Diocese of Slobozia and Calarasi",
    "ro-south-bessarabia": u"Diocese of South Bessarabia (formerly of Cetatea Alba-Ismail)",
    "ro-tulcea": u"Diocese of Tulcea",
    "ro-great-britain": u"Romanian Orthodox Archdiocese of Great Britain and Northern Ireland",
    "ro-australia-nz": u"Romanian Orthodox Diocese of Australia and New Zealand",
    "ro-canada": u"Romanian Orthodox Diocese of Canada",
    "ro-hungary": u"Romanian Orthodox Diocese of Hungary",
    "ro-ireland-iceland": u"Romanian Orthodox Diocese of Ireland and Iceland",
    "ro-italy": u"Romanian Orthodox Diocese of Italy",
    "ro-maramures": u"Romanian Orthodox Diocese of Maramures and Satmar",
    "ro-northern-europe": u"Romanian Orthodox Diocese of Northern Europe",
    "ro-oradea": u"Romanian Orthodox Diocese of Oradea",
    "ro-spain": u"Romanian Orthodox Diocese of Spain and Portugal",
    "fi-helsinki": u"Diocese of Helsinki",
    "fi-kuopio": u"Diocese of Kuopio and Karelia",
    "fi-oulu": u"Diocese of Oulu",
}
SEATS = {
    "Istanbul": u"Istanbul",
    "Alexandria": u"Alexandria",
    "Damascus": u"Damascus",
    "Jerusalem": u"Jerusalem",
    "Moscow": u"Moscow",
    "Tbilisi": u"Tbilisi",
    "Belgrade": u"Belgrade",
    "Bucharest": u"Bucharest",
    "Sofia": u"Sofia",
    "Nicosia": u"Nicosia",
    "Athens": u"Athens",
    "Tirana": u"Tirana",
    "Warsaw": u"Warsaw",
    "Prešov": u"Prešov",
    "Syosset, New York": u"Syosset, New York",
    "Skopje": u"Skopje",
    "Kyiv": u"Kyiv",
    "Mount Sinai": u"Mount Sinai",
    "Helsinki": u"Helsinki",
    "Tokyo": u"Tokyo",
    "Tallinn": u"Tallinn",
    "Alexandria, Virginia": u"Alexandria, Virginia",
    "Alhambra, California": u"Alhambra, California",
    "Anchorage, Alaska": u"Anchorage, Alaska",
    "Bath, Pennsylvania": u"Bath, Pennsylvania",
    "Bonn": u"Bonn",
    "Boston, Massachusetts": u"Boston, Massachusetts",
    "Bronxville, New York": u"Bronxville, New York",
    "Brussels": u"Brussels",
    "Chambesy": u"Chambesy",
    "Chicago, Illinois": u"Chicago, Illinois",
    "Cranberry Township, Pennsylvania": u"Cranberry Township, Pennsylvania",
    "Dallas, Texas": u"Dallas, Texas",
    "Englewood, New Jersey": u"Englewood, New Jersey",
    "Hong Kong": u"Hong Kong",
    "Jackson, Michigan": u"Jackson, Michigan",
    "Johnstown, Pennsylvania": u"Johnstown, Pennsylvania",
    "London": u"London",
    "Madrid": u"Madrid",
    "Mexico City": u"Mexico City",
    "New Rochelle, New York": u"New Rochelle, New York",
    "New York": u"New York",
    "Paris": u"Paris",
    "Rawdon, Quebec": u"Rawdon, Quebec",
    "San Francisco, California": u"San Francisco, California",
    "Seoul": u"Seoul",
    "Singapore": u"Singapore",
    "Somerset, New Jersey": u"Somerset, New Jersey",
    "Stockholm": u"Stockholm",
    "Third Lake, Illinois": u"Third Lake, Illinois",
    "Toledo, Ohio": u"Toledo, Ohio",
    "Venice": u"Venice",
    "Vienna": u"Vienna",
    "Windsor, Connecticut": u"Windsor, Connecticut",
    "Winnipeg, Manitoba": u"Winnipeg, Manitoba",
    "Chisinau": u"Chisinau",
    "Cluj-Napoca": u"Cluj-Napoca",
    "Constanta": u"Constanta",
    "Craiova": u"Craiova",
    "Jassy": u"Jassy",
    "Limours": u"Limours",
    "Nuremberg": u"Nuremberg",
    "Sibiu": u"Sibiu",
    "Timisoara": u"Timisoara",
    "Accra": u"Accra",
    "Addis Ababa": u"Addis Ababa",
    "Alba Iulia": u"Alba Iulia",
    "Aleppo": u"Aleppo",
    "Alexandria, Teleorman": u"Alexandria, Teleorman",
    "Antananarivo": u"Antananarivo",
    "Arad": u"Arad",
    "Arusha": u"Arusha",
    "Baghdad": u"Baghdad",
    "Baia Mare": u"Baia Mare",
    "Balti": u"Balti",
    "Beirut": u"Beirut",
    "Blantyre": u"Blantyre",
    "Brummana": u"Brummana",
    "Buenos Aires": u"Buenos Aires",
    "Bujumbura": u"Bujumbura",
    "Bukoba": u"Bukoba",
    "Buzau": u"Buzau",
    "Cahul": u"Cahul",
    "Cairo": u"Cairo",
    "Cape Town": u"Cape Town",
    "Caransebes": u"Caransebes",
    "Cheikh Taba": u"Cheikh Taba",
    "Cologne": u"Cologne",
    "Conakry": u"Conakry",
    "Curtea de Arges": u"Curtea de Arges",
    "Dar es Salaam": u"Dar es Salaam",
    "Deva": u"Deva",
    "Drobeta-Turnu Severin": u"Drobeta-Turnu Severin",
    "Dublin": u"Dublin",
    "Enfield": u"Enfield",
    "Gaborone": u"Gaborone",
    "Galati": u"Galati",
    "Giurgiu": u"Giurgiu",
    "Goma": u"Goma",
    "Gulu": u"Gulu",
    "Gyula": u"Gyula",
    "Hama": u"Hama",
    "Haninge": u"Haninge",
    "Harare": u"Harare",
    "Homs": u"Homs",
    "Husi": u"Husi",
    "Ismailia": u"Ismailia",
    "Jinja": u"Jinja",
    "Johannesburg": u"Johannesburg",
    "Juba": u"Juba",
    "Kampala": u"Kampala",
    "Kananga": u"Kananga",
    "Kapsabet": u"Kapsabet",
    "Khartoum": u"Khartoum",
    "Kigali": u"Kigali",
    "Kinshasa": u"Kinshasa",
    "Kisangani": u"Kisangani",
    "Kisumu": u"Kisumu",
    "Kuopio": u"Kuopio",
    "Lagos": u"Lagos",
    "Lattakia": u"Lattakia",
    "Lubumbashi": u"Lubumbashi",
    "Lusaka": u"Lusaka",
    "Marjayoun": u"Marjayoun",
    "Melton West, Victoria": u"Melton West, Victoria",
    "Miercurea-Ciuc": u"Miercurea-Ciuc",
    "Minya": u"Minya",
    "Nairobi": u"Nairobi",
    "Nyeri": u"Nyeri",
    "Oradea": u"Oradea",
    "Oulu": u"Oulu",
    "Pointe-Noire": u"Pointe-Noire",
    "Port Said": u"Port Said",
    "Porto-Novo": u"Porto-Novo",
    "Ramnicu Valcea": u"Ramnicu Valcea",
    "Roman": u"Roman",
    "Rome": u"Rome",
    "Saint-Hubert, Quebec": u"Saint-Hubert, Quebec",
    "Santiago": u"Santiago",
    "Sao Paulo": u"Sao Paulo",
    "Slatina": u"Slatina",
    "Slobozia": u"Slobozia",
    "Suceava": u"Suceava",
    "Suwayda": u"Suwayda",
    "Sydney": u"Sydney",
    "Tanta": u"Tanta",
    "Targoviste": u"Targoviste",
    "Toliara": u"Toliara",
    "Tripoli": u"Tripoli",
    "Tulcea": u"Tulcea",
    "Tunis": u"Tunis",
    "Vrsac": u"Vrsac",
    "Yaounde": u"Yaounde",
    "Zahleh": u"Zahleh",
    "Zalau": u"Zalau",
}
