# -*- coding: utf-8 -*-
"""The English the rest are written from.

This file is the list of keys as much as it is a translation: a row id that
is not here is a row nobody has been asked to name, and a seat that is not
here is a city nobody has been asked to place.
"""
NAMES = {
    "constantinople": u"The Church of Constantinople",
    "alexandria": u"The Church of Alexandria",
    "antioch": u"The Church of Antioch",
    "jerusalem": u"The Church of Jerusalem",
    "russia": u"The Church of Russia",
    "georgia": u"The Church of Georgia",
    "serbia": u"The Church of Serbia",
    "romania": u"The Church of Romania",
    "bulgaria": u"The Church of Bulgaria",
    "cyprus": u"The Church of Cyprus",
    "greece": u"The Church of Greece",
    "albania": u"The Church of Albania",
    "poland": u"The Church of Poland",
    "czech-slovakia": u"The Church of the Czech Lands and Slovakia",
    "oca": u"The Orthodox Church in America",
    "macedonia": u"The Macedonian Orthodox Church - Ohrid Archbishopric",
    "ukraine-uoc": u"The Church of Ukraine",
    "ukraine-ocu": u"Orthodox Church of Ukraine",
    "sinai": u"The Church of Sinai",
    "finland": u"The Autonomous Church of Finland",
    "japan": u"The Church of Japan",
    "estonia-eaok": u"Orthodox Church of Estonia",
    "albanian-americas": u"Albanian Orthodox Diocese of the Americas",
    "acrod": u"American Carpatho-Russian Orthodox Diocese of North America",
    "ep-thyateira": u"Archdiocese of Thyateira and Great Britain",
    "goarch": u"Greek Orthodox Archdiocese of America",
    "ep-france": u"Greek Orthodox Metropolis of France",
    "ep-germany": u"Greek Orthodox Metropolis of Germany",
    "ep-austria": u"Holy Metropolis of Austria",
    "ep-korea": u"Holy Metropolis of Korea",
    "ep-spain": u"Holy Metropolis of Spain and Portugal",
    "ep-belgium": u"Metropolis of Belgium",
    "ep-sweden": u"Metropolis of Sweden and All Scandinavia",
    "ep-switzerland": u"Metropolis of Switzerland",
    "ep-hongkong": u"Orthodox Metropolitanate of Hong Kong and South East Asia",
    "ep-singapore": u"Orthodox Metropolitanate of Singapore and South Asia",
    "ep-italy": u"Sacred Orthodox Archdiocese of Italy and Malta",
    "uocc": u"Ukrainian Orthodox Church of Canada",
    "uoc-usa": u"Ukrainian Orthodox Church of the USA",
    "antiochian-na": u"Antiochian Orthodox Christian Archdiocese of North America",
    "rocor": u"Russian Orthodox Church Outside of Russia",
    "mp-parishes-usa": u"The Patriarchal Parishes in the USA",
    "serbian-eastern": u"Diocese of Eastern America",
    "serbian-midwestern": u"Diocese of New Gracanica and Midwestern America",
    "serbian-western": u"Diocese of Western America",
    "romanian-americas": u"Romanian Orthodox Metropolia of the Americas",
    "bulgarian-usa": u"Bulgarian Eastern Orthodox Diocese of the USA, Canada and Australia",
    "oca-albanian": u"Albanian Archdiocese",
    "oca-canada": u"Archdiocese of Canada",
    "oca-washington": u"Archdiocese of Washington, D.C.",
    "oca-western-pa": u"Archdiocese of Western Pennsylvania",
    "oca-bulgarian": u"Bulgarian Diocese",
    "oca-eastern-pa": u"Diocese of Eastern Pennsylvania",
    "oca-mexico": u"Diocese of Mexico",
    "oca-new-england": u"Diocese of New England",
    "oca-ny-nj": u"Diocese of New York and New Jersey",
    "oca-alaska": u"Diocese of Sitka and Alaska",
    "oca-midwest": u"Diocese of the Midwest",
    "oca-south": u"Diocese of the South",
    "oca-west": u"Diocese of the West",
    "oca-romanian": u"Romanian Episcopate",
    "ro-bucharest": u"Archdiocese of Bucharest",
    "ro-chisinau": u"Archdiocese of Chisinau",
    "ro-craiova": u"Archdiocese of Craiova",
    "ro-iasi": u"Archdiocese of Jassy",
    "ro-sibiu": u"Archdiocese of Sibiu",
    "ro-timisoara": u"Archdiocese of Timisoara",
    "ro-tomis": u"Archdiocese of Tomis",
    "ro-cluj": u"Archdiocese of Vad, Feleac and Cluj",
    "ro-western-europe": u"Romanian Orthodox Archdiocese of Western Europe",
    "ro-germany": u"Romanian Orthodox Metropolis of Germany, Central and Northern Europe",
}
SEATS = {
    "Istanbul": u"Istanbul",
    "Alexandria": u"Alexandria",
    "Damascus": u"Damascus",
    "Jerusalem": u"Jerusalem",
    "Moscow": u"Moscow",
    "Tbilisi": u"Tbilisi",
    "Belgrade": u"Belgrade",
    "Bucharest": u"Bucharest",
    "Sofia": u"Sofia",
    "Nicosia": u"Nicosia",
    "Athens": u"Athens",
    "Tirana": u"Tirana",
    "Warsaw": u"Warsaw",
    "Prešov": u"Prešov",
    "Syosset, New York": u"Syosset, New York",
    "Skopje": u"Skopje",
    "Kyiv": u"Kyiv",
    "Mount Sinai": u"Mount Sinai",
    "Helsinki": u"Helsinki",
    "Tokyo": u"Tokyo",
    "Tallinn": u"Tallinn",
    "Alexandria, Virginia": u"Alexandria, Virginia",
    "Alhambra, California": u"Alhambra, California",
    "Anchorage, Alaska": u"Anchorage, Alaska",
    "Bath, Pennsylvania": u"Bath, Pennsylvania",
    "Bonn": u"Bonn",
    "Boston, Massachusetts": u"Boston, Massachusetts",
    "Bronxville, New York": u"Bronxville, New York",
    "Brussels": u"Brussels",
    "Chambesy": u"Chambesy",
    "Chicago, Illinois": u"Chicago, Illinois",
    "Cranberry Township, Pennsylvania": u"Cranberry Township, Pennsylvania",
    "Dallas, Texas": u"Dallas, Texas",
    "Englewood, New Jersey": u"Englewood, New Jersey",
    "Hong Kong": u"Hong Kong",
    "Jackson, Michigan": u"Jackson, Michigan",
    "Johnstown, Pennsylvania": u"Johnstown, Pennsylvania",
    "London": u"London",
    "Madrid": u"Madrid",
    "Mexico City": u"Mexico City",
    "New Rochelle, New York": u"New Rochelle, New York",
    "New York": u"New York",
    "Paris": u"Paris",
    "Rawdon, Quebec": u"Rawdon, Quebec",
    "San Francisco, California": u"San Francisco, California",
    "Seoul": u"Seoul",
    "Singapore": u"Singapore",
    "Somerset, New Jersey": u"Somerset, New Jersey",
    "Stockholm": u"Stockholm",
    "Third Lake, Illinois": u"Third Lake, Illinois",
    "Toledo, Ohio": u"Toledo, Ohio",
    "Venice": u"Venice",
    "Vienna": u"Vienna",
    "Windsor, Connecticut": u"Windsor, Connecticut",
    "Winnipeg, Manitoba": u"Winnipeg, Manitoba",
    "Chisinau": u"Chisinau",
    "Cluj-Napoca": u"Cluj-Napoca",
    "Constanta": u"Constanta",
    "Craiova": u"Craiova",
    "Jassy": u"Jassy",
    "Limours": u"Limours",
    "Nuremberg": u"Nuremberg",
    "Sibiu": u"Sibiu",
    "Timisoara": u"Timisoara",
}
