# -*- coding: utf-8 -*-
"""German lives for the Saints index. TEXT = {English name: the life}.

German is the fifth language, after Russian, Greek, Romanian and Ukrainian,
and the first written for a Church that received Orthodoxy in translation
rather than in her own tongue. The danger here is not a neighbouring Slavonic
language but Western church vocabulary, which is at hand for every word and
carries a different Church behind it: Kirchenvater and not Kirchenlehrer,
ehrwürdig and not selig, Gottesgebärerin and not Muttergottes alone,
Entschlafung and not Himmelfahrt Mariens, Göttliche Liturgie and not Messe,
Ikone and not Heiligenbild, Presbyter and not Pfarrer. See docs/GERMAN.md,
where the register was settled before a line of this file was written.

German does what Greek and Romanian do and Russian does not: der heilige
Nikolaus is ordinary German. So only one distinction is asserted, and it is
the one German Orthodox usage keeps: a monastic is ehrwürdig, never merely
heilig.

Two rules of spelling govern every line. The site writes ss and never the
sharp s, because these pages are read in Switzerland as well as in Germany
and Austria. And Cyrillic is transliterated the German way and not the
English: Sergij von Radonesch, Serafim von Sarow, Feodossij von den Höhlen,
Tschernigow, Kiew, Moskau.

The keys are the English names exactly as the index writes them, so a life
cannot quietly attach itself to the wrong saint.
"""
TEXT = {

"1,003 Martyrs of Nicomedia":
"Die eintausenddrei Märtyrer von Nikomedien litten im Jahre 303, im Auge des "
"Sturmes der Verfolgung Diokletians, und ihr Fest krönt das grösste Hauswesen "
"des Kalenders. Sie waren die Diener der vier kaiserlichen Würdenträger "
"Bassus, Eusebius, Eutychius und Basilides, Höflinge Diokletians, die Christus "
"bekannt hatten und zu Beginn desselben Jahres samt ihren Frauen gemartert "
"worden waren; und als die Herren vollendet waren, vollendeten die Häuser das "
"Urteil, denn die Diener, die Freigelassenen und die Angehörigen der vier "
"Häuser beschlossen mit ihren eigenen Frauen und Kindern gemeinsam, ihre "
"Herren nicht im Abfall zu überleben, sondern ihnen im Bekenntnis zu folgen. "
"Als sie sich zu Christen erklärten, wurde die grosse Schar von den Soldaten "
"des Kaisers umstellt, die meinten, der Anblick gezückter Schwerter werde "
"einen Haufen Hausgesindes auseinandertreiben; und das Gesinde blieb stehen, "
"die ganze Versammlung von Verwaltern und Türhütern, Köchen und Ammen, Männern "
"und Frauen mit Säuglingen auf dem Arm, und verweigerte bis auf den letzten "
"das Opfer, so dass die Verfolger, die unter eintausenddrei nicht einen "
"Verräter fanden, sie allesamt niederhieben und die gesamte Dienerschaft "
"vierer christlicher Häuser in einer einzigen Stunde vom Dienst unten in die "
"Herrlichkeit oben überging. Die Kirche hat ihre genaue und beredte Zahl "
"bewahrt, eintausenddrei, die Zählung einer Treue, die keinen verlor; und sie "
"ehrt in den Märtyrern von Nikomedien die Heiligkeit des Hauses, den Beweis "
"dafür, dass der Glaube der Herren vor den Dienern nicht aufgeführt, sondern "
"mit ihnen geteilt worden war, und dass in einem wahrhaft christlichen Hause, "
"wie in der Kirche selbst, der Unterschied zwischen Tafel und Küche das "
"Bekenntnis nicht überdauert und den Kranz nicht erreicht.",

"10 Holy Martyrs of Crete":
"Die zehn heiligen Märtyrer von Kreta, Theodulos, Saturninus, Euporos, "
"Gelasios, Eunikianos, Zotikos, Pompios, Agathopus, Basilides und Euaristos, "
"litten im Jahre 250 unter dem Kaiser Decius, dessen Statthalter auf der "
"Insel, ein Decius gleichfalls an Namen und an Grausamkeit, sich vornahm, den "
"Glauben aus Kreta auszureissen. Aus der Hauptstadt Gortyn und aus den Orten "
"der ganzen Insel zusammengebracht, so dass ganz Kreta in den zehn wie in "
"einem Chor vertreten war, wurden sie ergriffen und dreissig Tage lang durch "
"Spott und Marter geschleift, geschlagen, gesteinigt, angespien und vor den "
"Götzen zur Schau geführt, und die Menge und die Foltern mühten sich "
"miteinander vergebens; vor dem Gericht aber bekannten sie Christus mit so "
"strahlender Freude, dass die Berichte ihren heiligen Wettstreit "
"aufzeichnen, wie ein jeder der zehn danach drängte, der erste unter dem "
"Schwert zu sein, und um den Tod stritt, wie andere Menschen um Ehren "
"streiten, und die Götter der Verfolger als Dämonen aus Stein verlachte. Sie "
"wurden gemeinsam an dem Ort namens Alonion bei Gortyn enthauptet, zehn "
"Häupter für ein Bekenntnis; ihre Reliquien wurden verherrlicht, und Teile "
"davon wurden in späteren Zeiten zu Rom und zu Konstantinopel verehrt. Die "
"Kirche von Kreta hält sie als ihre Krone und Erstlingsfrucht, zehn Beeren "
"einer Traube, wie die Hymnen singen, in der Kelter von Gortyn zum Wein des "
"Reiches gepresst, und ihr Fest steht unmittelbar vor der Tür der Geburt des "
"Herrn, als hätte die Insel zehn Gesandte nach Bethlehem vorausgeschickt.",

"12 Greeks who built the Dormition Cathedral in the Kyiv Caves, Far Caves, Lavra":
"Der zwölf Griechen, die die grosse Entschlafungskathedrale der Kiewer Höhlen "
"erbauten, wird an diesem Tage gedacht, Baumeister aus Konstantinopel, die die "
"Gottesmutter selbst für das grösste Bauwerk der alten Rus in Dienst nahm. Das "
"Paterikon der Höhlen bewahrt ihren eigenen eidlichen Bericht: die Königin "
"des Himmels erschien ihnen an der Blachernenkirche zu Konstantinopel in "
"Gestalt einer Kaiserin, von Kriegern begleitet, und gebot ihnen, in die Rus "
"zu ziehen, nach Kiew, und dort an dem Ort, der ihnen gezeigt werden würde, "
"eine Kirche zu ihren Ehren zu bauen; sie gab ihnen Gold zum Lohn, Reliquien "
"von sieben heiligen Märtyrern, die sie in das Fundament legen sollten, und "
"eine Ikone ihrer Entschlafung, und sagte, sie selbst werde kommen, die Kirche "
"zu sehen, und werde in ihr wohnen. Als die Baumeister bei den Höhlen "
"ankamen und die Altväter fragten, wo die Kirche stehen solle, fanden sie, "
"dass der Himmel den ganzen Auftrag in eins gefügt hatte, denn Antonij betete, "
"und Tau und Feuer bezeichneten die Stätte wie einst das Vlies Gideons, und "
"die gegebenen Masse stimmten mit der Schau überein. So erhob sich zwischen "
"1073 und ihrer Weihe im Jahre 1089 die Grosse Kirche der Höhlen, die "
"Entschlafungskathedrale, die zur Mutter der ganzen russischen Baukunst wurde, "
"deren Verhältnisse jahrhundertelang von Wladimir bis Moskau nachgebildet "
"wurden, deren Fundament die Reliquien der Märtyrer barg und deren Altarraum "
"die wundertätige Ikone der Entschlafung barg, welche die Baumeister aus "
"Blachernen mitgebracht hatten. Die Baumeister selbst aber gaben der "
"Geschichte den Schluss, der aus einem Werkvertrag ein Fest macht, denn als "
"sie die Kirche der Gottesgebärerin vollendet hatten, weigerten sich die zwölf "
"Meister, sie zu verlassen, empfingen bei den Höhlen die Mönchsschur und "
"beschlossen ihr Leben als Asketen des Klosters, das sie erbaut hatten, und "
"wurden in den Nahen Höhlen bestattet, wo ihre Reliquien bis heute beisammen "
"ruhen. Die Kirche ehrt in den zwölf Griechen die Heiligung des Handwerks "
"selbst, Werkleute, die einen Auftrag aus der Hand der Gottesmutter "
"annahmen, ihn zur Ehre ihres Sohnes ausführten und dann, als sie begriffen, "
"was sie gebaut hatten, zur Tür hineingingen und nie wieder herauskamen; und "
"sie erinnert sich an ihrem gemeinsamen Grab daran, dass das sicherste "
"Zeichen guter Arbeit ist, dass der Werkmann in ihr wohnen will.",

"120 Martyrs of Persia":
"Die heiligen hundertzwanzig Märtyrer Persiens litten in der grossen "
"Verfolgung unter König Schapur dem Zweiten, um das Jahr 344, in den Jahren, "
"da das persische Reich, im Krieg mit dem neu christlich gewordenen Reich der "
"Römer, sich gegen die Kirche in den eigenen Grenzen wandte wie gegen eine "
"feindliche Niederlassung, und die Bekenner Christi in Mesopotamien und "
"Persien zu Tausenden ergriffen wurden. Die hundertzwanzig dieses Festes "
"wurden gemeinsam gefangen genommen, eine ganze versammelte Schar der "
"Gläubigen, und unter ihnen waren, wie die Überlieferung berichtet, neun "
"geweihte Jungfrauen, Christus gelobte Frauen, deren Gegenwart in der Liste "
"die Kirche stets mit Zärtlichkeit vermerkt hat, denn die Verfolgung raffte "
"das ganze Hauswesen der Kirche zusammen, Männer und Frauen, Verheiratete und "
"Geweihte, in ein einziges Bekenntnis; und die Forderung, die man ihnen "
"vorlegte, war die übliche Probe der zoroastrischen Macht: Feuer und Sonne "
"anzubeten, die sichtbaren Götter des Reiches, und den gekreuzigten Gott der "
"Römer zu verleugnen. Die hundertzwanzig verweigerten es mit einer Stimme, "
"bekannten den Schöpfer von Feuer und Sonne und weigerten sich, dem Geschöpf "
"die Ehre des Schöpfers zu geben; und nachdem Kerker und die Überredungen und "
"Martern ihrer Häscher nicht einen von ihnen gebrochen hatten, wurde die Schar "
"gemeinsam verurteilt und vollendet, überliefert, so berichten die Quellen, "
"eben dem Element, das sie anzubeten verweigert hatten, und das Feuer nahm "
"als Märtyrer auf, die es nicht als Anbeter empfangen konnte, und "
"hundertzwanzig Kronen stiegen an einem Tage herab. Die Kirche ehrt in ihnen "
"das gemeinsame Martyrium der persischen Kirche, deren Leiden unter Schapur "
"grösser waren als die des Westens unter irgendeinem Kaiser, und sie liest "
"ihren Kampf als einen einzigen leuchtenden Schluss: dass das Feuer ein "
"Geschöpf ist, dass ein Geschöpf nicht anzubeten ist, und dass die Männer und "
"Frauen, die lieber starben, als beides zu verwechseln, das erste Kapitel der "
"Genesis besser verstanden hatten als die ganze Priesterschaft der heiligen "
"Flamme.",

"1st Saturday of Great Lent: The Miracle of the Boiled Wheat":
"Am ersten Samstag der Grossen Fastenzeit begeht die Kirche das Wunder des "
"gekochten Weizens, der Kolyva, das der Grossmärtyrer Theodor der Rekrut ein "
"halbes Jahrhundert nach seinem eigenen Martyrium wirkte, der tote Soldat "
"Christi, der über der ersten Fastenwoche der Kirche Wache hielt. Als Julian "
"der Abtrünnige, feiner als die offenen Verfolger, die Christen nicht töten, "
"sondern beflecken wollte, befahl er dem Eparchen von Konstantinopel, während "
"der ersten Woche der Fastenzeit alle Speisen auf den Märkten heimlich mit dem "
"Blut der Götzenopfer besprengen zu lassen, damit die Gläubigen, wenn sie ihre "
"Fastenspeisen kauften, ohne es zu wissen ihre Reinheit brächen und an ihrem "
"eigenen Tisch Gemeinschaft mit den Götzen hätten, die Verfolgung "
"herabgesetzt zu einer Vergiftung von Lebensmitteln; und Gott deckte die List "
"durch seinen Märtyrer auf. Der Grossmärtyrer Theodor erschien dem Eudoxios, "
"dem Erzbischof der Stadt, in strahlender Schau, offenbarte den Anschlag des "
"Kaisers und gebot, die Gläubigen sollten in jener Woche nichts auf den "
"Märkten kaufen, sondern den Weizen kochen, den sie zu Hause hatten, die "
"Kolyva, und ihn mit Honig essen und so die Woche unbefleckt zubringen; der "
"Erzbischof gehorchte, die Kirche der Hauptstadt lebte jene Tage von der "
"Speise des Märtyrers, und die Kriegslist Julians brach in öffentlichen Spott "
"zusammen, der Abtrünnige in der ersten Woche der Fastenzeit von einem toten "
"Rekruten und einem Topf Getreide geschlagen. Zum Dank setzte die Kirche das "
"jährliche Gedächtnis auf diesen Samstag, mit dem Kanon an den Grossmärtyrer "
"und der Segnung der Kolyva, des mit Honig gesüssten gekochten Weizens, den "
"die Gläubigen bis heute darbringen und miteinander teilen, und dieselbe "
"Speise dient im Brauch der Kirche dem Gedächtnis des Märtyrers und dem aller "
"Entschlafenen, da der Herr selbst gelehrt hat, dass das Weizenkorn, das in "
"die Erde fällt und stirbt, viele Frucht bringt. Die Kirche ehrt in diesem "
"Fest die Wachsamkeit der triumphierenden Kirche über der fastenden Kirche "
"und lehrt, dass die Märtyrer nicht in den Ruhestand treten, dass die "
"feinsten Angriffe des Feindes eher dem gewöhnlichen Tisch als der Arena "
"gelten, und dass die Antwort damals wie immer die gesegnete Einfalt von "
"Weizen, Honig und Gehorsam ist.",

"1st Sunday of Great Lent: Sunday of Orthodoxy":
"Am ersten Sonntag der Grossen Fastenzeit begeht die Kirche den Sonntag der "
"Orthodoxie, das Fest des Sieges des wahren Glaubens, eingesetzt im Jahre "
"843, als die heilige Kaiserin Theodora und der heilige Patriarch Methodios "
"die Verehrung der Ikonen wiederherstellten und die letzte grosse Häresie der "
"alten Welt beendeten; an jenem ersten Sonntag der Fastenzeit zogen die "
"Geistlichen und das Volk von Konstantinopel mit den heiligen Ikonen in "
"Prozession zur Grossen Kirche, und die Bilder kehrten an die Wände und "
"Ikonostasen zurück, von denen zwei Menschenalter kaiserlicher Erlasse sie "
"gerissen hatten, und die Kirche bestimmte, dass der Sieg an diesem Sonntag "
"für immer begangen werde. Das Fest ist weiter als sein Anlass: indem sie die "
"Ikonen wiederherstellte, besiegelte die Kirche die ganze Reihe ihrer Kämpfe, "
"denn die Ikone ruht auf der Menschwerdung und die Menschwerdung auf der "
"Dreifaltigkeit, und indem die Kirche das Bild Christi rechtfertigte, "
"rechtfertigte sie zugleich die Wirklichkeit seines Fleisches, die Fülle "
"seiner Gottheit und den ungebrochenen Glauben der Apostel, der Propheten und "
"der Väter, so dass der Tag zur jährlichen Verkündigung der Orthodoxie selbst "
"wurde, des Glaubens, der die Welt gegründet hat. In seinem Herzen steht das "
"Synodikon der Orthodoxie, das an diesem Tage feierlich gelesen wird, in dem "
"die Kirche mit einer Stimme das Gedächtnis der Vorkämpfer des Glaubens "
"segnet, Ewiges Gedenken über die Väter und Bekenner ruft und ihr Anathema "
"wider die Häresien setzt, die an ihr rissen, und vor Himmel und Erde in den "
"Worten erklärt, die der Ritus festgelegt hat: Dies ist der Glaube der "
"Apostel, dies ist der Glaube der Väter, dies ist der Glaube der Orthodoxen, "
"dieser Glaube hat die Welt gegründet; und in den Gemeinden tragen die "
"Gläubigen und vor allem die Kinder die Ikonen in Prozession, und die ganze "
"streitende Kirche stellt im Kleinen die grosse Prozession von 843 dar. Die "
"Kirche ehrt an diesem Sonntag die Barmherzigkeit Gottes, der die Wahrheit "
"nicht untergehen lässt, und lehrt, dass die Häresien ihre Geschlechter "
"haben, der Glaube aber die Zeitalter; und sie setzt das Fest auf den ersten "
"Gipfel der Fastenzeit, damit jeder Pilger dieser Wochen von Anfang an weiss, "
"in welcher Kirche, in welchem Glauben und unter welchem unbesiegten Banner "
"er nach Pascha zieht.",

"20,000 Martyrs of Nicomedia":
"Die heiligen zwanzigtausend Märtyrer von Nikomedien litten im Jahre 302, als "
"der Kaiser Maximian, der erfuhr, wie mächtig der Glaube in seiner eigenen "
"Hauptstadt gewachsen war, beschloss, die Christen der Stadt in einer einzigen "
"Nacht zu vernichten, und dafür die Nacht wählte, in der sie alle versammelt "
"sein würden: das Fest der Geburt Christi. Während die Menge, an die "
"zwanzigtausend Seelen, beim Festgottesdienst in der Kathedrale stand, "
"umstellten Soldaten das Gebäude, und der Herold des Kaisers trat mit dem "
"Urteil ein: wer herauskomme und den Göttern opfere, dürfe leben; die übrigen "
"würden mit der Kirche verbrennen. Nicht einer kam heraus. Und Bischof "
"Anthimos, Herr über die einzigen Augenblicke, die blieben, taufte auf der "
"Stelle alle anwesenden Taufbewerber und reichte der ganzen Versammlung die "
"heiligen Mysterien; und so ging die ganze Gemeinde, besiegelt und gespeist, "
"als ein Leib in das Feuer, und die Weihnachtsliturgie von Nikomedien stieg "
"auf, auf Erden unvollendet und im Himmel vollendet, und unter den Gekrönten "
"waren die Äbtissin Agathe und die gerettete Theophila. Danach erntete die "
"Verfolgung den Rest einen nach dem anderen: der Presbyter Glykerios, der dem "
"Kaiser ins Angesicht geantwortet hatte, wurde verbrannt; der Befehlshaber "
"Zenon enthauptet; der Diakon Theophilos, der die verborgenen Briefe des "
"Bischofs trug, gefoltert und erschlagen, ohne etwas zu verraten; Dorotheos, "
"Mardonios und der Diakon Migdonios wurden jeder zu seiner Zeit vollendet; und "
"die einstige Palastpriesterin Domna, durch die Schrift bekehrt und mit dem "
"Kämmerer Indes getauft, verbarg sich in einer Höhle, bestattete die Leiber "
"des Indes, des Gorgonios und des Petrus, als das Meer sie den Netzen der "
"Fischer zurückgab, und wurde, während sie die Gräber der Märtyrer beräucherte, "
"entdeckt und mit dem Märtyrer Euthymios enthauptet. Die Kirche hält die ganze "
"Ernte an diesem Tage im Glanz der Geburt des Herrn selbst, des Festes, das "
"diese Märtyrer in einer brennenden Kirche begannen und für immer dort "
"begehen, wohin kein Feuer reicht.",

"26 Martyrs in the Crimea":
"Die heiligen sechsundzwanzig Märtyrer, deren Reliquien die Krim heiligten, "
"litten um das Jahr 375 im Lande der Goten jenseits der Donau, als der "
"heidnische Gotenkönig eine Verfolgung gegen die Christen seines Volkes "
"erhob und die junge gotische Kirche, von Gefangenen und Missionaren "
"gepflanzt, ihren ersten grossen Preis in Blut bezahlte. Die Art ihres "
"Martyriums machte die Gemeinde selbst zur Opfergabe: die Verfolger "
"überraschten die Christen, die zum Gottesdienst versammelt waren, und "
"steckten die Kirche über ihren Häuptern in Brand, und die sechsundzwanzig, "
"Presbyter und Mönche, Männer und Frauen miteinander, verbrannten darin bei "
"ihren Gebeten, und die Versammlung stieg mit ihrem eigenen Weihrauch empor, "
"unter ihnen, wie die Überlieferung ihre Namen bewahrt, die Presbyter "
"Bathusius und Wereka, der Mönch Arpila, Laien aus dem Volk und heilige "
"Frauen, darunter Anna, Alla und Larissa, die Liste der Gläubigen eines "
"einzigen Sonntags, die zu einer Seite des Martyrologiums wurde. Was das "
"Feuer übrigliess, barg die Liebe: die gotische Königin Gaatha, eine Christin, "
"sammelte die Reliquien der Märtyrer ehrfürchtig aus der Asche und trug mit "
"ihrer Tochter Duklida die heiligen Überreste aus dem verfolgenden Land "
"hinaus, auf die Krim zu und zu den christlichen Städten am Meer, wo der "
"Schatz in die Obhut der Kirche gegeben wurde, und die Königin machte aus "
"ihrem Rang das Geleit eines Reliquiars; und von jener Übertragung her "
"breitete sich die Verehrung der Märtyrer aus, und die Kirche hat ihr "
"Gedächtnis mit dem Krimland verbunden gehalten, das sie aufnahm. Die Kirche "
"ehrt in den sechsundzwanzig das Martyrium der Gemeinde, das vollständigste "
"Bild, das sie von sich selbst hat, ein Volk, das sich von der Liturgie nicht "
"zerstreuen liess, obwohl das Dach in Flammen stand; und sie gedenkt mit "
"ihnen der beiden königlichen Frauen, die bewiesen, dass, wenn eine "
"Verfolgung ihr Ärgstes getan hat, die Antwort der Kirche eine Frau ist, die "
"Asche sammelt, als sammelte sie Perlen.",
}
