# -*- coding: utf-8 -*-
"""German lives for the Saints index. TEXT = {English name: the life}.

German is the fifth language, after Russian, Greek, Romanian and Ukrainian,
and the first written for a Church that received Orthodoxy in translation
rather than in her own tongue. The danger here is not a neighbouring Slavonic
language but Western church vocabulary, which is at hand for every word and
carries a different Church behind it: Kirchenvater and not Kirchenlehrer,
ehrwürdig and not selig, Gottesgebärerin and not Muttergottes alone,
Entschlafung and not Himmelfahrt Mariens, Göttliche Liturgie and not Messe,
Ikone and not Heiligenbild, Presbyter and not Pfarrer. See docs/GERMAN.md,
where the register was settled before a line of this file was written.

German does what Greek and Romanian do and Russian does not: der heilige
Nikolaus is ordinary German. So only one distinction is asserted, and it is
the one German Orthodox usage keeps: a monastic is ehrwürdig, never merely
heilig.

Two rules of spelling govern every line. The site writes ss and never the
sharp s, because these pages are read in Switzerland as well as in Germany
and Austria. And Cyrillic is transliterated the German way and not the
English: Sergij von Radonesch, Serafim von Sarow, Feodossij von den Höhlen,
Tschernigow, Kiew, Moskau.

The keys are the English names exactly as the index writes them, so a life
cannot quietly attach itself to the wrong saint.
"""
TEXT = {

"1,003 Martyrs of Nicomedia":
"Die eintausenddrei Märtyrer von Nikomedien litten im Jahre 303, im Auge des "
"Sturmes der Verfolgung Diokletians, und ihr Fest krönt das grösste Hauswesen "
"des Kalenders. Sie waren die Diener der vier kaiserlichen Würdenträger "
"Bassus, Eusebius, Eutychius und Basilides, Höflinge Diokletians, die Christus "
"bekannt hatten und zu Beginn desselben Jahres samt ihren Frauen gemartert "
"worden waren; und als die Herren vollendet waren, vollendeten die Häuser das "
"Urteil, denn die Diener, die Freigelassenen und die Angehörigen der vier "
"Häuser beschlossen mit ihren eigenen Frauen und Kindern gemeinsam, ihre "
"Herren nicht im Abfall zu überleben, sondern ihnen im Bekenntnis zu folgen. "
"Als sie sich zu Christen erklärten, wurde die grosse Schar von den Soldaten "
"des Kaisers umstellt, die meinten, der Anblick gezückter Schwerter werde "
"einen Haufen Hausgesindes auseinandertreiben; und das Gesinde blieb stehen, "
"die ganze Versammlung von Verwaltern und Türhütern, Köchen und Ammen, Männern "
"und Frauen mit Säuglingen auf dem Arm, und verweigerte bis auf den letzten "
"das Opfer, so dass die Verfolger, die unter eintausenddrei nicht einen "
"Verräter fanden, sie allesamt niederhieben und die gesamte Dienerschaft "
"vierer christlicher Häuser in einer einzigen Stunde vom Dienst unten in die "
"Herrlichkeit oben überging. Die Kirche hat ihre genaue und beredte Zahl "
"bewahrt, eintausenddrei, die Zählung einer Treue, die keinen verlor; und sie "
"ehrt in den Märtyrern von Nikomedien die Heiligkeit des Hauses, den Beweis "
"dafür, dass der Glaube der Herren vor den Dienern nicht aufgeführt, sondern "
"mit ihnen geteilt worden war, und dass in einem wahrhaft christlichen Hause, "
"wie in der Kirche selbst, der Unterschied zwischen Tafel und Küche das "
"Bekenntnis nicht überdauert und den Kranz nicht erreicht.",

"10 Holy Martyrs of Crete":
"Die zehn heiligen Märtyrer von Kreta, Theodulos, Saturninus, Euporos, "
"Gelasios, Eunikianos, Zotikos, Pompios, Agathopus, Basilides und Euaristos, "
"litten im Jahre 250 unter dem Kaiser Decius, dessen Statthalter auf der "
"Insel, ein Decius gleichfalls an Namen und an Grausamkeit, sich vornahm, den "
"Glauben aus Kreta auszureissen. Aus der Hauptstadt Gortyn und aus den Orten "
"der ganzen Insel zusammengebracht, so dass ganz Kreta in den zehn wie in "
"einem Chor vertreten war, wurden sie ergriffen und dreissig Tage lang durch "
"Spott und Marter geschleift, geschlagen, gesteinigt, angespien und vor den "
"Götzen zur Schau geführt, und die Menge und die Foltern mühten sich "
"miteinander vergebens; vor dem Gericht aber bekannten sie Christus mit so "
"strahlender Freude, dass die Berichte ihren heiligen Wettstreit "
"aufzeichnen, wie ein jeder der zehn danach drängte, der erste unter dem "
"Schwert zu sein, und um den Tod stritt, wie andere Menschen um Ehren "
"streiten, und die Götter der Verfolger als Dämonen aus Stein verlachte. Sie "
"wurden gemeinsam an dem Ort namens Alonion bei Gortyn enthauptet, zehn "
"Häupter für ein Bekenntnis; ihre Reliquien wurden verherrlicht, und Teile "
"davon wurden in späteren Zeiten zu Rom und zu Konstantinopel verehrt. Die "
"Kirche von Kreta hält sie als ihre Krone und Erstlingsfrucht, zehn Beeren "
"einer Traube, wie die Hymnen singen, in der Kelter von Gortyn zum Wein des "
"Reiches gepresst, und ihr Fest steht unmittelbar vor der Tür der Geburt des "
"Herrn, als hätte die Insel zehn Gesandte nach Bethlehem vorausgeschickt.",

"12 Greeks who built the Dormition Cathedral in the Kyiv Caves, Far Caves, Lavra":
"Der zwölf Griechen, die die grosse Entschlafungskathedrale der Kiewer Höhlen "
"erbauten, wird an diesem Tage gedacht, Baumeister aus Konstantinopel, die die "
"Gottesmutter selbst für das grösste Bauwerk der alten Rus in Dienst nahm. Das "
"Paterikon der Höhlen bewahrt ihren eigenen eidlichen Bericht: die Königin "
"des Himmels erschien ihnen an der Blachernenkirche zu Konstantinopel in "
"Gestalt einer Kaiserin, von Kriegern begleitet, und gebot ihnen, in die Rus "
"zu ziehen, nach Kiew, und dort an dem Ort, der ihnen gezeigt werden würde, "
"eine Kirche zu ihren Ehren zu bauen; sie gab ihnen Gold zum Lohn, Reliquien "
"von sieben heiligen Märtyrern, die sie in das Fundament legen sollten, und "
"eine Ikone ihrer Entschlafung, und sagte, sie selbst werde kommen, die Kirche "
"zu sehen, und werde in ihr wohnen. Als die Baumeister bei den Höhlen "
"ankamen und die Altväter fragten, wo die Kirche stehen solle, fanden sie, "
"dass der Himmel den ganzen Auftrag in eins gefügt hatte, denn Antonij betete, "
"und Tau und Feuer bezeichneten die Stätte wie einst das Vlies Gideons, und "
"die gegebenen Masse stimmten mit der Schau überein. So erhob sich zwischen "
"1073 und ihrer Weihe im Jahre 1089 die Grosse Kirche der Höhlen, die "
"Entschlafungskathedrale, die zur Mutter der ganzen russischen Baukunst wurde, "
"deren Verhältnisse jahrhundertelang von Wladimir bis Moskau nachgebildet "
"wurden, deren Fundament die Reliquien der Märtyrer barg und deren Altarraum "
"die wundertätige Ikone der Entschlafung barg, welche die Baumeister aus "
"Blachernen mitgebracht hatten. Die Baumeister selbst aber gaben der "
"Geschichte den Schluss, der aus einem Werkvertrag ein Fest macht, denn als "
"sie die Kirche der Gottesgebärerin vollendet hatten, weigerten sich die zwölf "
"Meister, sie zu verlassen, empfingen bei den Höhlen die Mönchsschur und "
"beschlossen ihr Leben als Asketen des Klosters, das sie erbaut hatten, und "
"wurden in den Nahen Höhlen bestattet, wo ihre Reliquien bis heute beisammen "
"ruhen. Die Kirche ehrt in den zwölf Griechen die Heiligung des Handwerks "
"selbst, Werkleute, die einen Auftrag aus der Hand der Gottesmutter "
"annahmen, ihn zur Ehre ihres Sohnes ausführten und dann, als sie begriffen, "
"was sie gebaut hatten, zur Tür hineingingen und nie wieder herauskamen; und "
"sie erinnert sich an ihrem gemeinsamen Grab daran, dass das sicherste "
"Zeichen guter Arbeit ist, dass der Werkmann in ihr wohnen will.",

"120 Martyrs of Persia":
"Die heiligen hundertzwanzig Märtyrer Persiens litten in der grossen "
"Verfolgung unter König Schapur dem Zweiten, um das Jahr 344, in den Jahren, "
"da das persische Reich, im Krieg mit dem neu christlich gewordenen Reich der "
"Römer, sich gegen die Kirche in den eigenen Grenzen wandte wie gegen eine "
"feindliche Niederlassung, und die Bekenner Christi in Mesopotamien und "
"Persien zu Tausenden ergriffen wurden. Die hundertzwanzig dieses Festes "
"wurden gemeinsam gefangen genommen, eine ganze versammelte Schar der "
"Gläubigen, und unter ihnen waren, wie die Überlieferung berichtet, neun "
"geweihte Jungfrauen, Christus gelobte Frauen, deren Gegenwart in der Liste "
"die Kirche stets mit Zärtlichkeit vermerkt hat, denn die Verfolgung raffte "
"das ganze Hauswesen der Kirche zusammen, Männer und Frauen, Verheiratete und "
"Geweihte, in ein einziges Bekenntnis; und die Forderung, die man ihnen "
"vorlegte, war die übliche Probe der zoroastrischen Macht: Feuer und Sonne "
"anzubeten, die sichtbaren Götter des Reiches, und den gekreuzigten Gott der "
"Römer zu verleugnen. Die hundertzwanzig verweigerten es mit einer Stimme, "
"bekannten den Schöpfer von Feuer und Sonne und weigerten sich, dem Geschöpf "
"die Ehre des Schöpfers zu geben; und nachdem Kerker und die Überredungen und "
"Martern ihrer Häscher nicht einen von ihnen gebrochen hatten, wurde die Schar "
"gemeinsam verurteilt und vollendet, überliefert, so berichten die Quellen, "
"eben dem Element, das sie anzubeten verweigert hatten, und das Feuer nahm "
"als Märtyrer auf, die es nicht als Anbeter empfangen konnte, und "
"hundertzwanzig Kronen stiegen an einem Tage herab. Die Kirche ehrt in ihnen "
"das gemeinsame Martyrium der persischen Kirche, deren Leiden unter Schapur "
"grösser waren als die des Westens unter irgendeinem Kaiser, und sie liest "
"ihren Kampf als einen einzigen leuchtenden Schluss: dass das Feuer ein "
"Geschöpf ist, dass ein Geschöpf nicht anzubeten ist, und dass die Männer und "
"Frauen, die lieber starben, als beides zu verwechseln, das erste Kapitel der "
"Genesis besser verstanden hatten als die ganze Priesterschaft der heiligen "
"Flamme.",

"1st Saturday of Great Lent: The Miracle of the Boiled Wheat":
"Am ersten Samstag der Grossen Fastenzeit begeht die Kirche das Wunder des "
"gekochten Weizens, der Kolyva, das der Grossmärtyrer Theodor der Rekrut ein "
"halbes Jahrhundert nach seinem eigenen Martyrium wirkte, der tote Soldat "
"Christi, der über der ersten Fastenwoche der Kirche Wache hielt. Als Julian "
"der Abtrünnige, feiner als die offenen Verfolger, die Christen nicht töten, "
"sondern beflecken wollte, befahl er dem Eparchen von Konstantinopel, während "
"der ersten Woche der Fastenzeit alle Speisen auf den Märkten heimlich mit dem "
"Blut der Götzenopfer besprengen zu lassen, damit die Gläubigen, wenn sie ihre "
"Fastenspeisen kauften, ohne es zu wissen ihre Reinheit brächen und an ihrem "
"eigenen Tisch Gemeinschaft mit den Götzen hätten, die Verfolgung "
"herabgesetzt zu einer Vergiftung von Lebensmitteln; und Gott deckte die List "
"durch seinen Märtyrer auf. Der Grossmärtyrer Theodor erschien dem Eudoxios, "
"dem Erzbischof der Stadt, in strahlender Schau, offenbarte den Anschlag des "
"Kaisers und gebot, die Gläubigen sollten in jener Woche nichts auf den "
"Märkten kaufen, sondern den Weizen kochen, den sie zu Hause hatten, die "
"Kolyva, und ihn mit Honig essen und so die Woche unbefleckt zubringen; der "
"Erzbischof gehorchte, die Kirche der Hauptstadt lebte jene Tage von der "
"Speise des Märtyrers, und die Kriegslist Julians brach in öffentlichen Spott "
"zusammen, der Abtrünnige in der ersten Woche der Fastenzeit von einem toten "
"Rekruten und einem Topf Getreide geschlagen. Zum Dank setzte die Kirche das "
"jährliche Gedächtnis auf diesen Samstag, mit dem Kanon an den Grossmärtyrer "
"und der Segnung der Kolyva, des mit Honig gesüssten gekochten Weizens, den "
"die Gläubigen bis heute darbringen und miteinander teilen, und dieselbe "
"Speise dient im Brauch der Kirche dem Gedächtnis des Märtyrers und dem aller "
"Entschlafenen, da der Herr selbst gelehrt hat, dass das Weizenkorn, das in "
"die Erde fällt und stirbt, viele Frucht bringt. Die Kirche ehrt in diesem "
"Fest die Wachsamkeit der triumphierenden Kirche über der fastenden Kirche "
"und lehrt, dass die Märtyrer nicht in den Ruhestand treten, dass die "
"feinsten Angriffe des Feindes eher dem gewöhnlichen Tisch als der Arena "
"gelten, und dass die Antwort damals wie immer die gesegnete Einfalt von "
"Weizen, Honig und Gehorsam ist.",

"1st Sunday of Great Lent: Sunday of Orthodoxy":
"Am ersten Sonntag der Grossen Fastenzeit begeht die Kirche den Sonntag der "
"Orthodoxie, das Fest des Sieges des wahren Glaubens, eingesetzt im Jahre "
"843, als die heilige Kaiserin Theodora und der heilige Patriarch Methodios "
"die Verehrung der Ikonen wiederherstellten und die letzte grosse Häresie der "
"alten Welt beendeten; an jenem ersten Sonntag der Fastenzeit zogen die "
"Geistlichen und das Volk von Konstantinopel mit den heiligen Ikonen in "
"Prozession zur Grossen Kirche, und die Bilder kehrten an die Wände und "
"Ikonostasen zurück, von denen zwei Menschenalter kaiserlicher Erlasse sie "
"gerissen hatten, und die Kirche bestimmte, dass der Sieg an diesem Sonntag "
"für immer begangen werde. Das Fest ist weiter als sein Anlass: indem sie die "
"Ikonen wiederherstellte, besiegelte die Kirche die ganze Reihe ihrer Kämpfe, "
"denn die Ikone ruht auf der Menschwerdung und die Menschwerdung auf der "
"Dreifaltigkeit, und indem die Kirche das Bild Christi rechtfertigte, "
"rechtfertigte sie zugleich die Wirklichkeit seines Fleisches, die Fülle "
"seiner Gottheit und den ungebrochenen Glauben der Apostel, der Propheten und "
"der Väter, so dass der Tag zur jährlichen Verkündigung der Orthodoxie selbst "
"wurde, des Glaubens, der die Welt gegründet hat. In seinem Herzen steht das "
"Synodikon der Orthodoxie, das an diesem Tage feierlich gelesen wird, in dem "
"die Kirche mit einer Stimme das Gedächtnis der Vorkämpfer des Glaubens "
"segnet, Ewiges Gedenken über die Väter und Bekenner ruft und ihr Anathema "
"wider die Häresien setzt, die an ihr rissen, und vor Himmel und Erde in den "
"Worten erklärt, die der Ritus festgelegt hat: Dies ist der Glaube der "
"Apostel, dies ist der Glaube der Väter, dies ist der Glaube der Orthodoxen, "
"dieser Glaube hat die Welt gegründet; und in den Gemeinden tragen die "
"Gläubigen und vor allem die Kinder die Ikonen in Prozession, und die ganze "
"streitende Kirche stellt im Kleinen die grosse Prozession von 843 dar. Die "
"Kirche ehrt an diesem Sonntag die Barmherzigkeit Gottes, der die Wahrheit "
"nicht untergehen lässt, und lehrt, dass die Häresien ihre Geschlechter "
"haben, der Glaube aber die Zeitalter; und sie setzt das Fest auf den ersten "
"Gipfel der Fastenzeit, damit jeder Pilger dieser Wochen von Anfang an weiss, "
"in welcher Kirche, in welchem Glauben und unter welchem unbesiegten Banner "
"er nach Pascha zieht.",

"20,000 Martyrs of Nicomedia":
"Die heiligen zwanzigtausend Märtyrer von Nikomedien litten im Jahre 302, als "
"der Kaiser Maximian, der erfuhr, wie mächtig der Glaube in seiner eigenen "
"Hauptstadt gewachsen war, beschloss, die Christen der Stadt in einer einzigen "
"Nacht zu vernichten, und dafür die Nacht wählte, in der sie alle versammelt "
"sein würden: das Fest der Geburt Christi. Während die Menge, an die "
"zwanzigtausend Seelen, beim Festgottesdienst in der Kathedrale stand, "
"umstellten Soldaten das Gebäude, und der Herold des Kaisers trat mit dem "
"Urteil ein: wer herauskomme und den Göttern opfere, dürfe leben; die übrigen "
"würden mit der Kirche verbrennen. Nicht einer kam heraus. Und Bischof "
"Anthimos, Herr über die einzigen Augenblicke, die blieben, taufte auf der "
"Stelle alle anwesenden Taufbewerber und reichte der ganzen Versammlung die "
"heiligen Mysterien; und so ging die ganze Gemeinde, besiegelt und gespeist, "
"als ein Leib in das Feuer, und die Weihnachtsliturgie von Nikomedien stieg "
"auf, auf Erden unvollendet und im Himmel vollendet, und unter den Gekrönten "
"waren die Äbtissin Agathe und die gerettete Theophila. Danach erntete die "
"Verfolgung den Rest einen nach dem anderen: der Presbyter Glykerios, der dem "
"Kaiser ins Angesicht geantwortet hatte, wurde verbrannt; der Befehlshaber "
"Zenon enthauptet; der Diakon Theophilos, der die verborgenen Briefe des "
"Bischofs trug, gefoltert und erschlagen, ohne etwas zu verraten; Dorotheos, "
"Mardonios und der Diakon Migdonios wurden jeder zu seiner Zeit vollendet; und "
"die einstige Palastpriesterin Domna, durch die Schrift bekehrt und mit dem "
"Kämmerer Indes getauft, verbarg sich in einer Höhle, bestattete die Leiber "
"des Indes, des Gorgonios und des Petrus, als das Meer sie den Netzen der "
"Fischer zurückgab, und wurde, während sie die Gräber der Märtyrer beräucherte, "
"entdeckt und mit dem Märtyrer Euthymios enthauptet. Die Kirche hält die ganze "
"Ernte an diesem Tage im Glanz der Geburt des Herrn selbst, des Festes, das "
"diese Märtyrer in einer brennenden Kirche begannen und für immer dort "
"begehen, wohin kein Feuer reicht.",

"26 Martyrs in the Crimea":
"Die heiligen sechsundzwanzig Märtyrer, deren Reliquien die Krim heiligten, "
"litten um das Jahr 375 im Lande der Goten jenseits der Donau, als der "
"heidnische Gotenkönig eine Verfolgung gegen die Christen seines Volkes "
"erhob und die junge gotische Kirche, von Gefangenen und Missionaren "
"gepflanzt, ihren ersten grossen Preis in Blut bezahlte. Die Art ihres "
"Martyriums machte die Gemeinde selbst zur Opfergabe: die Verfolger "
"überraschten die Christen, die zum Gottesdienst versammelt waren, und "
"steckten die Kirche über ihren Häuptern in Brand, und die sechsundzwanzig, "
"Presbyter und Mönche, Männer und Frauen miteinander, verbrannten darin bei "
"ihren Gebeten, und die Versammlung stieg mit ihrem eigenen Weihrauch empor, "
"unter ihnen, wie die Überlieferung ihre Namen bewahrt, die Presbyter "
"Bathusius und Wereka, der Mönch Arpila, Laien aus dem Volk und heilige "
"Frauen, darunter Anna, Alla und Larissa, die Liste der Gläubigen eines "
"einzigen Sonntags, die zu einer Seite des Martyrologiums wurde. Was das "
"Feuer übrigliess, barg die Liebe: die gotische Königin Gaatha, eine Christin, "
"sammelte die Reliquien der Märtyrer ehrfürchtig aus der Asche und trug mit "
"ihrer Tochter Duklida die heiligen Überreste aus dem verfolgenden Land "
"hinaus, auf die Krim zu und zu den christlichen Städten am Meer, wo der "
"Schatz in die Obhut der Kirche gegeben wurde, und die Königin machte aus "
"ihrem Rang das Geleit eines Reliquiars; und von jener Übertragung her "
"breitete sich die Verehrung der Märtyrer aus, und die Kirche hat ihr "
"Gedächtnis mit dem Krimland verbunden gehalten, das sie aufnahm. Die Kirche "
"ehrt in den sechsundzwanzig das Martyrium der Gemeinde, das vollständigste "
"Bild, das sie von sich selbst hat, ein Volk, das sich von der Liturgie nicht "
"zerstreuen liess, obwohl das Dach in Flammen stand; und sie gedenkt mit "
"ihnen der beiden königlichen Frauen, die bewiesen, dass, wenn eine "
"Verfolgung ihr Ärgstes getan hat, die Antwort der Kirche eine Frau ist, die "
"Asche sammelt, als sammelte sie Perlen.",

"2nd Sunday of Great Lent: St Gregory Palamas":
"Am zweiten Sonntag der Grossen Fastenzeit begeht die Kirche das Gedächtnis "
"des heiligen Gregorios Palamas, des Erzbischofs von Thessaloniki, und dieser "
"Tag heisst mit Recht der zweite Sieg der Orthodoxie, denn er führt den ersten "
"weiter: wie der erste Sonntag verkündet, dass Gott dargestellt werden darf, "
"weil er wahrhaft Mensch geworden ist, so verkündet der zweite, dass Gott "
"erfahren werden darf, weil er sich wahrhaft schenkt, und die Ikone und das "
"Licht sind zwei Urteilssprüche eines Glaubens. Gregorios, der athonitische "
"Mönch, der im vierzehnten Jahrhundert auf den Sitz von Thessaloniki erhoben "
"wurde, war der von Gott gerüstete Verteidiger der Hesychasten, jener Mönche "
"der Stille, denen durch das Gebet des Herzens - Herr Jesus Christus, Sohn "
"Gottes, erbarme dich meiner - gegeben war, das göttliche Licht zu schauen, "
"denselben ungeschaffenen Glanz, der auf dem Tabor von Christus ausging; und "
"als der Philosoph Barlaam ihr Gebet und ihren Anspruch verspottete und "
"lehrte, Gott sei nur durch Begriffe und Geschöpfe erkennbar, antwortete "
"Gregorios mit der Unterscheidung, die die Kirche sich zu eigen machte: dass "
"Gott in seinem Wesen in der Tat unerkennbar und unteilhaftig ist und dennoch "
"in seinen ungeschaffenen Energien wahrhaft erkannt und wahrhaft empfangen "
"wird, in seiner Gnade, seinem Licht, seinem Leben, so dass das Heil kein "
"Gleichnis und die Vergöttlichung keine Redewendung ist, sondern die "
"wirkliche Durchdringung des Menschen durch Gott; und die Konzilien von "
"Konstantinopel in den Jahren 1341, 1347 und 1351 bestätigten seine Theologie "
"als den Glauben der Väter, und die Kirche legte bald nach seinem Entschlafen "
"sein Gedächtnis auf diesen Sonntag und setzte das Siegel der zweiten "
"Fastenwoche auf seinen Sieg. Die Stellung ist selbst die Predigt: die "
"Fastenzeit ist keine Zeit der Selbstverbesserung, sondern der Weg in eben "
"dieses Licht, und das Gebet, die Verneigungen und der Hunger dieser Wochen "
"sind die Wissenschaft der Hesychasten, jedem Gläubigen angeboten, das "
"Mittel, durch das das Herz zur Ruhe kommt, bis die Gnade nicht erschlossen, "
"sondern angetroffen werden kann; und so zeigt die Kirche, nachdem sie ihren "
"Kindern am ersten Sonntag gezeigt hat, in welchem Glauben sie reisen, ihnen "
"am zweiten, wozu die Reise dient. Die Kirche ehrt an diesem Sonntag das "
"Dogma der lebendigen Begegnung und verkündet mit Gregorios wider den Barlaam "
"jedes Zeitalters, dass das Licht des Tabor nicht erloschen ist, dass die "
"Gnade ungeschaffen, unverdient und gegeben ist, und dass das Ziel der "
"Fastenzeit und des ganzen christlichen Lebens nichts Geringeres ist als Gott "
"selbst, wahrhaft berührt.",

"33 Holy Martyrs of Melitene":
"Die heiligen dreiunddreissig Märtyrer von Melitene litten um das Jahr 290, "
"unter der Herrschaft Diokletians und Maximians, als eine Abteilung unter dem "
"Befehlshaber Lysias nach Kappadokien gesandt wurde, um die Christen "
"auszurotten und starke Männer für das Heer auszuheben. An ihrer Spitze steht "
"Hieron, ein Bauer aus Tyana, von seiner Mutter in der Frömmigkeit erzogen, "
"ein Mann von aussergewöhnlicher Leibeskraft; und als Soldaten kamen, ihn für "
"den Dienst unter Kaisern auszuheben, die Christus verfolgten, trieb er die "
"Bewaffneten mit nichts als seinem hölzernen Gerät davon und verbarg sich mit "
"anderen Christen in einer Höhle, die keine Belagerung zu nehmen vermochte. "
"Zuletzt von seinem Freund Kyriakos überredet, nicht weiter zu widerstehen, "
"zog er mit den Ausgehobenen nach Melitene, wo ihm ein Traum das Martyrium "
"offenbarte, das ihn erwartete; und als Lysias den versammelten Soldaten "
"befahl zu opfern, bekannten Hieron und zweiunddreissig andere vor allen "
"Christus. Der Befehlshaber liess Hieron den Arm am Ellbogen abschlagen, und "
"nach grausamen Schlägen wurden die Bekenner in den Kerker geworfen und vier "
"Tage später gemeinsam enthauptet und tauschten den Dienst des Kaisers gegen "
"das Heer des Himmels; und ein wohlhabender Christ namens Chrysanthos kaufte "
"das Haupt Hierons los, während die Kirche die Namen aller dreiunddreissig in "
"ihrem Gottesdienst dieses Tages bewahrt hat.",

"3rd Sunday of Great Lent: Veneration of the Cross":
"Am dritten Sonntag der Grossen Fastenzeit bringt die Kirche das kostbare und "
"lebenspendende Kreuz hervor und stellt es, mit Blumen geschmückt, inmitten "
"der Gläubigen zur Verehrung für die folgende Woche auf; und die Stellung ist "
"die ganze Theologie des Tages, denn das Kreuz wird genau in die Mitte der "
"Fastenzeit gepflanzt, in die Mitte der vierzig Tage, als ein Baum der Rast "
"inmitten eines harten Weges. Die Väter erklärten das Fest gern aus seiner "
"Stellung: wie Moses die bitteren Wasser von Mara süss machte, indem er Holz "
"hineinwarf, so macht die Kirche die Bitterkeit der halben Fastenzeit mit dem "
"Holz des Kreuzes süss; wie der Baum des Lebens mitten im Paradies stand, so "
"steht der Baum des wahren Lebens mitten in der Fastenzeit, damit die Müden "
"von seiner Frucht essen und aufleben; und wie Wanderer vor einem steilen "
"Anstieg unter einem Schattenbaum rasten, so setzen sich die Pilger der "
"Fastenzeit, wund an den Füssen am halben Wege, in den Schatten des Kreuzes, "
"ehe sie weiter nach Golgotha und zum Grabe steigen, und schöpfen Mut, wie "
"die Hymnen des Tages singen, indem sie im Kreuz die Freude der ganzen Welt "
"und die Ankündigung der drei Wochen entfernten Auferstehung erblicken. Der "
"Ritus selbst lehrt: das Kreuz wird in feierlicher Prozession in die Mitte "
"der Kirche getragen, und das Volk fällt davor nieder und singt den Hymnus, "
"der an diesem Tage sogar das Trishagion vertritt: Vor deinem Kreuze fallen "
"wir anbetend nieder, o Gebieter, und deine heilige Auferstehung preisen wir, "
"und die beiden Sätze sind untrennbar, da die Kirche das Kreuz nie anders "
"verehrt denn als Werkzeug des Sieges; und die Gläubigen treten die Woche "
"hindurch hinzu, um das Holz zu küssen, durch das der Tod getötet wurde. So "
"steht der Sonntag des Kreuzes als die eigene Predigt der Fastenzeit über "
"ihren Zweck, dass die asketischen Mühen dieser Wochen keine Selbstbestrafung "
"sind, sondern Kreuztragen, das Aufnehmen des Joches, das der Herr sanft "
"genannt hat; und die Kirche ehrt in diesem Fest die Barmherzigkeit der "
"Mitte und lehrt, dass Gott, der den Lauf bestimmt hat, auch seine Erquickung "
"bestimmte und die Siegestrophäe des Zieles auf halbem Wege aufstellte, damit "
"niemand, der den dritten Sonntag gesehen hat, daran zweifeln müsse, wie die "
"sechste Woche endet.",

"40 Holy Martyrs of Sebaste":
"Die heiligen vierzig Märtyrer von Sebaste waren Soldaten der berühmten "
"Zwölften Legion, der Donnernden, um das Jahr 320 zu Sebaste in Armenien in "
"Garnison, welches das byzantinische Synaxarion als 322 oder 323 rechnet, als "
"der Kaiser Licinius seinen Frieden mit der Kirche brach und seinen Heeren "
"befahl zu opfern; und die vierzig, Kappadokier und die Blüte ihrer Legion, "
"Kyrion und Candidus und Domnus und ihre Gefährten, verweigerten es "
"miteinander und antworteten ihrem Befehlshaber Agrikolaos, sie seien im "
"Kriege Soldaten des Kaisers und in der Anbetung Soldaten Christi. Weder "
"Versprechungen der Beförderung noch der Kerker bewegten sie, und im Kerker, "
"während sie die Nacht hindurch die Psalmen sangen, hörten sie die Stimme des "
"Herrn, die sie stärkte, dass, wer bis ans Ende ausharrt, gerettet wird; und "
"der Befehlshaber ersann für sie ein Martyrium von ausgesuchter Grausamkeit, "
"dem armenischen Winter angemessen: die vierzig wurden nackt ausgezogen und in "
"einer Nacht bitteren Frostes auf den gefrorenen See vor der Stadt "
"hinausgetrieben, und am Ufer wurde vor ihren Augen ein Badehaus geheizt und "
"erleuchtet gehalten, damit ein jeder von ihnen zu jeder Stunde der Nacht sein "
"Leben mit ein paar warmen Schritten erkaufen könne. Die Nacht hindurch "
"standen die vierzig auf dem Eis und ermutigten einander, dass sie als vierzig "
"in den Kampf getreten seien und als vierzig gekrönt werden sollten; und "
"einem versagte das Ausharren, und er brach aus der Schar und lief zum Bade, "
"und auf der Schwelle seiner Wärme starb er und gewann weder dieses Leben "
"noch das andere; und der Wächter Aglaios, der am Ufer wachte, sah in der "
"Nacht ein Licht um die Märtyrer leuchten und neununddreissig strahlende "
"Kronen auf sie herabsteigen, und da er die eine Krone begriff, die "
"unbeansprucht schwebte, rief er aus: Auch ich bin ein Christ, warf seine "
"Kleider ab und ging hinaus auf das Eis, um sich ihnen anzuschliessen, und "
"der Henker vollendete die vierzig. Am Morgen brachen die Verfolger den "
"erfrorenen und noch lebenden Märtyrern die Beine; und der jüngste, Meliton, "
"der noch atmete, als die Leiber zum Feuer gekarrt wurden, wurde von seiner "
"eigenen Mutter begleitet, die ihren Sohn auf die Arme hob und dem Karren "
"nachtrug, bis er starb, und ihn zu seinen Brüdern legte, und die Mutter des "
"Jüngsten brachte ihn mit eigenen Händen dar. Die Leiber wurden verbrannt und "
"die Überreste in den Fluss geworfen, doch die Gläubigen sammelten, was Gott "
"bewahrte, und die Reliquien der Vierzig verbreiteten sich durch die ganze "
"Kirche; die Märtyrer hinterliessen ausserdem ein schriftliches Testament an "
"die Brüder, am Vorabend ihres Kampfes besiegelt, und ihr Fest wird mit solcher "
"Ehre begangen, dass die Kirche sogar in der Grossen Fastenzeit ihre Strenge "
"um ihretwillen mildert. Die Kirche ehrt in den Vierzig von Sebaste das "
"Martyrium der Schar, der Bruderschaft, von der nichts abgezogen werden "
"konnte und die statt dessen aus den Reihen ihrer Feinde vollzählig gemacht "
"wurde; und sie stellt ihren gefrorenen See vor jede wankende Seele mit der "
"einen Lehre jener Nacht, dass das Badehaus immer erleuchtet, immer nahe und "
"immer der Tod dessen ist, der es erreicht.",

"42 Martyrs of Ammoria in Phrygia":
"Die heiligen zweiundvierzig Märtyrer von Amorion waren die Befehlshaber und "
"Edlen des byzantinischen Heeres, die gefangen wurden, als die grosse Stadt "
"Amorion in Phrygien im Jahre 838 an die Sarazenen fiel, unter ihnen "
"Konstantin, Aetios, Theophilos, Theodor, Melissenos, Kallistos und Basoes, "
"die Blüte der Führung des Reiches, nach Mesopotamien verschleppt. Sieben "
"Jahre lang wurden sie in den Kerkern von Samarra am Tigris gehalten, und "
"während dieser Jahre mühte sich der Hof des Kalifen nicht darum, zuerst ihre "
"Leiber zu brechen, sondern ihre Seelen zu erobern, und sandte Gelehrte und "
"Beamte, um sie von Christus abzureden, und versprach ihnen Freiheit, Ehre und "
"hohen Rang im Dienste des Kalifen, wenn sie den Glauben des Islam annähmen, "
"und drohte ihnen den Tod an, wenn sie es nicht täten; und die Märtyrer, "
"gelehrte Männer so gut wie tapfere, antworteten den Streitgesprächen Punkt "
"für Punkt, bekannten die Heilige Dreifaltigkeit und den fleischgewordenen "
"Herrn und wiesen die ganze lange Gefangenschaft hindurch jeden Anreiz "
"zurück und ermutigten einander, dass die Ehren, die man ihnen anbot, Staub "
"seien und der Tod, den man ihnen androhte, eine Tür. Als es zuletzt "
"offenkundig war, dass weder Beweisführung noch Bestechung noch das Zermürben "
"von sieben Jahren sie bewegen würde, wurden sie hinausgeführt und gemeinsam "
"enthauptet, nach gewöhnlicher Rechnung im Jahre 845 oder, wie das "
"byzantinische Synaxarion aufzeichnet, im Jahre 848 unter dem Kalifen "
"al-Mutawakkil, und ihre Leiber wurden in den Euphrat geworfen; und die Kirche "
"empfing sie als Passionsträger und Bekenner, die nicht nur gegen das Schwert "
"standgehalten hatten, sondern gegen den feineren und längeren Ansturm der "
"Überredung. Die Kirche ehrt in den Zweiundvierzig von Amorion das Martyrium "
"des Ausharrens, Soldaten, die eine Stadt und einen Krieg verloren und den "
"einzigen Sieg gewannen, der bleibt, und die durch sieben Jahre von "
"Streitgesprächen bewiesen, dass ein Bekenntnis, das ebenso durchdacht wie "
"geliebt ist, einem treuen Herzen nicht ausgeredet werden kann.",

"45 Holy Martyrs at Nicopolis in Armenia":
"Die fünfundvierzig heiligen Märtyrer von Nikopolis in Armenien litten unter "
"dem Kaiser Licinius, der über den Osten herrschte und die Kirche heftig "
"verfolgte und jedem Christen den Tod androhte, der nicht zu den Götzen "
"zurückkehrte. Als die Verfolgung Nikopolis erreichte, beschlossen mehr als "
"vierzig Gläubige unter der Führung des Leontios, des Maurikios, des Daniel, "
"des Antonios und des Alexander, sich nicht zu verbergen, sondern offen vor "
"die Verfolger zu treten und Christus zu bekennen. Vor den Statthalter Lysias "
"gebracht, widerlegten sie kühn die Torheit der heidnischen Götter und liessen "
"sich weder durch Drohungen noch durch Versprechungen bewegen. In den Kerker "
"geworfen, wurden sie um Mitternacht von einem Engel besucht, der die Zelle "
"mit Licht erfüllte und ihnen sagte, ihr Kampf sei nahe am Ende und ihre Namen "
"schon im Himmel geschrieben; und bei diesem Anblick kamen zwei der Wächter "
"selbst zum Glauben. Als sie am folgenden Tage wiederum mit einer Stimme "
"riefen: Wir sind Christen, liess der erzürnte Statthalter ihnen Hände und "
"Füsse abschlagen und ihre Leiber verbrennen und die Gebeine in einen Fluss "
"werfen. Später sammelten die Gläubigen ihre Reliquien, und als der Kirche der "
"Friede kam, wurde über der Stätte ihres Martyriums ein Gotteshaus errichtet.",

"4th Sunday of Great Lent: St John Climacus (of the Ladder)":
"Am vierten Sonntag der Grossen Fastenzeit stellt die Kirche ihren Kindern den "
"heiligen Johannes Klimakos vor Augen, den Abt vom Sinai und Verfasser der "
"Leiter des göttlichen Aufstiegs, und die Anordnung ist bedachte Pädagogik: "
"jenseits der Mitte der Fastenzeit, wenn das Kreuz verehrt und Pascha noch "
"nicht in Sicht ist, bringt die Kirche ihren meisterlichen Kartographen des "
"geistlichen Lebens hervor, den Mann, der den ganzen Aufstieg von der "
"Absage an die Welt bis zum Gipfel der Liebe in dreissig genauen Stufen "
"vermessen hat, und sagt den Müden gleichsam: der Weg, auf dem ihr seid, ist "
"vermessen, die Pässe sind bekannt, und der Gipfel wird erreicht. Der Sonntag "
"predigt das Buch ebenso wie den Mann: die Leiter, vom Einsiedler von Tholas "
"für die Mönche von Raithu geschrieben und sogleich von der ganzen Kirche "
"ergriffen, führt den Steigenden Stufe um Stufe durch eben den Kampf, den "
"jeder Pilger der Fastenzeit in diesem Augenblick führt, durch Gehorsam, "
"Busse, das Gedenken des Todes, die Trauer, die zur Freude wird, die Zähmung "
"des Zorns und der Zunge, die langen Belagerungen von Mutlosigkeit und "
"Völlerei und Begierde, hinauf durch Stille und Gebet zu den dreien, die "
"bleiben; und ihr Geist, der Grund, warum die Kirche sie in jeder Fastenzeit "
"in ihren Klöstern liest und an jedem vierten Sonntag allen empfiehlt, ist "
"ihre Vereinigung von Strenge und Hoffnung, denn Johannes gibt der Lauheit "
"nichts nach und der Gnade nichts ab und lehrt, dass der Aufstieg steil, "
"geordnet und möglich ist, dass Menschen aus Fleisch ihn erstiegen haben, und "
"dass die Leiter nicht an der Leistung lehnt, sondern an Christus, der oben "
"steht, nicht als Prüfer, sondern als Preis. Hierher gestellt, zwischen den "
"Sonntag des Kreuzes und den Sonntag der Maria von Ägypten, vollendet "
"Klimakos das mittlere Triptychon der Fastenzeit, das Kreuz als das Mittel, "
"die Leiter als die Weise und Maria als den Beweis; und die Kirche ehrt an "
"diesem Sonntag das Dogma des Fortschreitens wider die Verzweiflung jedes "
"Zeitalters an der Veränderung und verkündet mit dem Abt vom Sinai, dass die "
"Seele sich bewegt, dass die Busse ein Weg ist und keine Stimmung, und dass, "
"wer heute auf der dritten Stufe steht oder von der fünften gefallen ist, mit "
"Namen zur vierten geladen wird, in eben dieser Woche.",

"5th Saturday of Great Lent: of the Akathist to the Theotokos":
"Am fünften Samstag der Grossen Fastenzeit begeht die Kirche das Fest des "
"Akathistos und singt in einer feierlichen Nacht den grossen Hymnus an die "
"Allheilige Gottesgebärerin ganz, den sie das übrige Jahr hindurch in Teilen "
"singt; und das Fest ist ebenso ein Kriegerdenkmal wie ein Gottesdienst, denn "
"es wurde zum Dank für die Errettungen Konstantinopels eingesetzt. Als im "
"Jahre 626 die Awaren und die Perser zugleich die Stadt einschlossen, während "
"Kaiser und Heer fern waren, hatte das Volk keine Verteidigung als die Mauern "
"und die Gottesmutter; der Patriarch trug ihre Ikone und ihr Gewand um die "
"Wälle, und die feindliche Flotte wurde im Goldenen Horn von einem Sturm "
"zerschmettert, den die Stadt als ihr Urteil empfing, und die Belagerung "
"brach; und das Volk, das zur grossen Kirche der Gottesgebärerin zu "
"Blachernen strömte, sang ihr die ganze Nacht hindurch, stehend, denn keiner "
"wagte es, sich im Angesicht einer solchen Errettung zu setzen, und von jener "
"stehenden Vigil nahm der Hymnus seinen Namen, Akathistos, der Hymnus, zu dem "
"man sich nicht setzt; und als in späteren Geschlechtern die arabischen "
"Flotten des siebten und achten Jahrhunderts ihrerseits an der behüteten Stadt "
"zerbrachen, nahm das Fest auch jene Errettungen in seine Danksagung auf. Der "
"Hymnus selbst, älter als die erste Belagerung und, wie die Überlieferung "
"hält, aus dem Wunder der Verkündigung gewoben, ist das Meisterwerk der "
"Dichtung der Kirche, und seine vierundzwanzig Strophen grüssen die Jungfrau "
"in strömenden Anreden, die Brücke, die die Erde zum Himmel führt, die Leiter, "
"die Jakob sah, das Gefäss des unfassbaren Gottes, und jede Strophe bricht "
"sich am eigenen Wort des Engels: Freue dich; und an ihre Spitze setzte die "
"Kirche das Vorwort der Siege: Dir, der streitbaren Anführerin, weihen wir, "
"deine Knechte, ein Fest des Sieges und des Dankes, als die aus Nöten "
"Erretteten, o Gottesgebärerin, die schlichte Quittung der Stadt für "
"geleistete Dienste. Die Kirche ehrt am Akathistos-Samstag die Feldherrnschaft "
"der Gottesmutter und lehrt, dass die fünfte Woche der Fastenzeit zu Füssen "
"derer endet, die die ganze Hoffnung der Fastenzeit in Person ist, und dass "
"die richtige Haltung vor einer solchen Beschützerin von Konstantinopel längst "
"entschieden wurde: auf den Füssen, die ganze Nacht, singend.",

"5th Sunday of Great Lent: St Mary of Egypt":
"Die heilige Maria von Ägypten, deren Leben in der Grossen Fastenzeit in der "
"Kirche als ein Bild der Busse gelesen wird, verbrachte ihre Jugend zu "
"Alexandria in grosser Zügellosigkeit. Als sie nach Jerusalem reiste, wurde "
"sie von einer unsichtbaren Macht daran gehindert, am Fest der Kreuzerhöhung "
"die Kirche zu betreten, und ins Herz getroffen, weinte sie vor einer Ikone "
"der Gottesmutter und gelobte, ihr Leben zu ändern. Sie ging über den Jordan "
"in die Wüste und lebte dort siebenundvierzig Jahre in Einsamkeit, von "
"niemandem gesehen, und kämpfte wider ihre Leidenschaften, bis sie grosse "
"Heiligkeit erlangte. Gegen das Ende ihres Lebens wurde sie von dem Priester "
"Sosima gefunden, dem sie ihre Geschichte erzählte und von dem sie die "
"Kommunion empfing und der sie bestattete, als sie entschlief. Ihr Leben steht "
"in der Kirche als ein Zeugnis dafür, dass keine Tiefe der Sünde ausserhalb "
"der Reichweite der Busse liegt.",

"7 Holy Maccabee Martyrs":
"Die sieben heiligen Makkabäerbrüder, Abim, Antonius, Gurias, Eleasar, "
"Eusebonos, Alimos und Marcellus, litten im Jahre 166 vor Christus unter dem "
"gottlosen König Antiochus Epiphanes, der den Glauben der Juden verachtete und "
"sich mühte, das Volk vom Gesetz Mosis abzubringen, den Tempel entweihte und "
"darin ein Bild des Zeus zur allgemeinen Anbetung aufstellte. Als viele den "
"Gott Abrahams verliessen, standen diese sieben Jünglinge, die Schüler des "
"Greises Eleasar und die Söhne der mutigen Solomonia, fest und weigerten sich, "
"Schweinefleisch zu essen oder den Bund Gottes zu brechen. Vor den Augen ihrer "
"Mutter liess der König sie einen nach dem anderen mit furchtbarer Grausamkeit "
"foltern und töten, und doch verleugnete nicht einer von ihnen seinen Glauben, "
"und der jüngste von allen wies den Tyrannen ins Angesicht zurecht und litt um "
"so tapferer. Obwohl sie vor der Ankunft Christi lebten, ehrt die Kirche sie "
"als Märtyrer vor dem Zeitalter der Märtyrer, sieben Säulen der Weisheit "
"Gottes, die den Tod dem geringsten Verrat am wahren Glauben vorzogen und "
"deren Standhaftigkeit den Eifer des Judas Makkabäus entzündete, sich zu "
"erheben und den Tempel des Herrn zu reinigen.",

"7 Holy Youths “Seven Sleepers” of Ephesus":
"Die sieben heiligen Jünglinge von Ephesus, Maximilianos, Iamblichos, "
"Martinianos, Johannes, Dionysios, Exakustodianos und Antoninos, lebten im "
"dritten Jahrhundert und waren Söhne angesehener Bürger, von Kindheit an "
"Freunde und gemeinsam Soldaten. Als der Kaiser Decius nach Ephesus kam und "
"allen befahl, den Götzen zu opfern, bekannten die sieben Christus, und obwohl "
"ihnen die Gürtel ihres Amtes abgenommen wurden, liess der Kaiser sie eine "
"Zeitlang frei, in der Hoffnung, sie würden nachgeben. Statt dessen gaben sie "
"ihre Güter den Armen und verbargen sich in einer Höhle am Berge Ochlon, um zu "
"beten und sich auf das Martyrium zu bereiten, und als Decius zurückkehrte und "
"ihr Versteck erfuhr, befahl er, den Eingang der Höhle mit Steinen zu "
"verschliessen, damit sie umkämen. Der Herr aber sandte ihnen einen wunderbaren "
"Schlaf, und dort schliefen sie beinahe zweihundert Jahre. Unter der Herrschaft "
"Theodosius' des Jüngeren, als manche die Auferstehung der Toten leugneten, "
"wurden die Steine von Arbeitern weggeräumt, und Gott erweckte die Jünglinge "
"wie aus der Ruhe einer einzigen Nacht, so dass Iamblichos, der um Brot in die "
"Stadt ging, sich wunderte, Kreuze über Ephesus errichtet zu finden, und "
"selbst für einen Finder alter Schätze gehalten wurde, als er die alten Münzen "
"des Decius darbot. Als der Bischof und der Kaiser kamen und ihre Erzählung "
"hörten und die Tafeln sahen, die sie nannten, priesen alle Gott, denn die "
"Schläfer waren als lebendiges Zeichen der Auferstehung der Toten erweckt "
"worden. Dann neigten die sieben vor allen ihre Häupter und entschliefen "
"abermals, diesmal im Tode, und über ihrer Höhle wurde eine grosse Kirche "
"errichtet.",

"Afterfeast of the Dormition of the Mother of God":
"In den Tagen des Nachfestes der Entschlafung feiert die Kirche weiter das "
"selige Entschlafen unserer Allheiligen Herrin, der Gottesgebärerin, und ihre "
"Aufnahme in Herrlichkeit in das himmlische Reich. Die Hymnen dieser Tage "
"verkünden, dass sie, die den Urheber des Lebens gebar, die Welt in ihrer Ruhe "
"nicht verlassen hat, sondern von ihrem Sohne aufgenommen wurde, um mit ihm zu "
"herrschen und unaufhörlich für alle zu bitten, die sie ehren. Wie die Apostel, "
"auf wunderbare Weise von den Enden der Erde versammelt, ihr Hinscheiden "
"schauten und ihr Grab ihres Leibes leer fanden, so freuen sich die Gläubigen "
"in diesen Tagen in der gewissen Hoffnung der Auferstehung, die in der "
"Gottesmutter als der Erstlingsfrucht derer aufleuchtet, die in Christus "
"entschlafen sind. Durch das Nachfest verlängert die Kirche die Freude des "
"Festes bis zu seinem Beschluss und gibt dem Herrn die Ehre, der seine Mutter "
"verherrlicht hat.",

"Afterfeast of the Elevation of the Cross":
"Dies sind die Tage des Nachfestes der weltweiten Erhöhung des kostbaren und "
"lebenspendenden Kreuzes, an denen die Kirche das grosse Fest des Kreuzes des "
"Herrn weiter begeht. Die Hymnen der Kreuzerhöhung werden den täglichen "
"Gottesdiensten beigefügt, und die Gläubigen verehren weiterhin das heilige "
"Holz, das inmitten der Erde erhöht wurde, und betrachten das Geheimnis, durch "
"das das Werkzeug des Todes zum Baum des Lebens wurde. Die Kirche singt vom "
"Kreuz als der unbesiegbaren Waffe, der Befestigung der Gläubigen, dem Ruhm "
"der Märtyrer und der Asketen und der Tür des Paradieses und ruft die ganze "
"Schöpfung auf, den anzubeten, der daran erhöht wurde; und die Feier dauert "
"durch diese Tage fort, bis das Fest seinen Beschluss erhält.",

"Afterfeast of the Entry of the Most Holy Mother of God into the Temple":
"In den Tagen des Nachfestes des Einzugs der Allheiligen Gottesgebärerin in "
"den Tempel bleibt die Kirche im Licht des Festes, singt weiter seine Hymnen "
"und betrachtet sein Geheimnis: das dreijährige Kind, von Joachim und Anna in "
"Erfüllung ihres Gelübdes gebracht, das die grossen Stufen des Tempels ohne "
"Hilfe hinaufsteigt, vom Hohenpriester Zacharias empfangen und wider allen "
"Brauch in das Allerheiligste selbst geführt wird, wo einst die Lade und der "
"Gnadenthron standen; denn sie selbst wird nun als die lebendige Lade "
"bereitet, als der Tempel, der den Unfassbaren fassen wird. Durch diese Tage "
"entfalten die Kanones des Festes das Wunder: die Jungfrau, im Heiligtum "
"genährt und, wie die Überlieferung sagt, von der Hand eines Engels gespeist, "
"die im Hause Gottes heranwächst als die verborgene Morgenröte des Heils der "
"Welt; und die Gläubigen, die das Nachfest mitten im Weihnachtsfasten "
"begehen, werden gelehrt, aus ihrer eigenen Seele einen gekehrten und "
"bereiteten Tempel zu machen. Das Nachfest währt bis zum Beschluss, an dem "
"die Kirche mit einer letzten Wiederholung der Festhymnen die Feier "
"besiegelt und ihre Gnade nach Bethlehem hin weiterträgt.",

"Afterfeast of the Meeting of our Lord in the Temple":
"Das Nachfest der Begegnung des Herrn im Tempel trägt das Fest des zweiten "
"Februar durch die folgenden Tage bis zum Beschluss am neunten, und in ihnen "
"bleibt die Kirche mit dem Kinde auf den Armen im Tempel stehen; denn die "
"Begegnung ist die Angel, an der sich der ganze Kreis der Geburt des Herrn "
"schliesst, die Erfüllung des Gesetzes der Menschwerdung am vierzigsten Tage, "
"und ein Geheimnis solchen Gewichtes wird nicht an einem Tage entlassen. "
"Durch das Nachfest hindurch singen die Gottesdienste weiter das Troparion "
"des Festes: Freue dich, gnadenerfüllte Jungfrau und Gottesgebärerin, denn "
"aus dir ging auf die Sonne der Gerechtigkeit, Christus, unser Gott, der die "
"erleuchtet, die in der Finsternis sind; und die Kirche betrachtet weiter die "
"vier Gestalten der Begegnung, das Kind, das der Alte an Tagen ist, die "
"Jungfrau, die ihren Schöpfer trägt, den greisen Symeon, der in seinen "
"erlahmenden Armen die Stärke des Alls empfängt, und die betagte Prophetin "
"Anna, die die Botschaft allen kundtut, die auf die Erlösung warteten, und so "
"begegnen einander Alter und Kindheit, Erwartung und Erfüllung ein für "
"allemal. Die Tage des Nachfestes sind in der Frömmigkeit der Gläubigen von "
"den am Fest gesegneten Kerzen erhellt, die nach Hause getragen werden als "
"die kleine tragbare Predigt des Wortes Symeons, dass das Kind ein Licht zur "
"Erleuchtung der Völker ist; und die Zeit lehrt die Kirche, den Lobgesang "
"Symeons zu ihrem eigenen Abendgebet zu machen, wie sie es an jeder Vesper "
"des Jahres tut: Herr, nun lässest du deinen Diener im Frieden fahren, und "
"das Nachfest übt jede Seele für die eine Begegnung, die ihr noch bleibt. "
"Selig, wer diese Tage so durchschreitet, wie der Greis den Tempel verliess, "
"gesättigt, nachdem er in den Armen des Glaubens alles gehalten hat, was je "
"verheissen war.",

"Afterfeast of the Nativity of our Lord and Savior Jesus Christ":
"Das Nachfest der Geburt unseres Herrn trägt die Feier durch die Tage, die "
"dem Fest folgen, denn die Kirche schliesst die Höhle von Bethlehem nicht "
"nach einem Tage, sondern wohnt darin und wiederholt bei jedem Gottesdienst "
"das Troparion und das Kontakion des Festes und singt Christus ist geboren, "
"preiset ihn über den Heiligen jedes Tages und den Mühen jedes Tages, so dass "
"Märtyrer, Hierarchen und Asketen, deren in diesen Tagen gedacht wird, "
"allesamt im Licht der Krippe geschaut werden. Die Tage des Nachfestes "
"währen bis zum Beschluss am einunddreissigsten Dezember, und sie lehren die "
"ungeeilte Freude der Kirche: ein Geheimnis dieser Grösse wird nicht begangen, "
"sondern bewohnt, und den Gläubigen wird eine Woche gegeben, es zu umschreiten "
"und das Kind bald mit der Mutter, bald mit den Hirten und den Weisen, bald "
"neben seinen ersten Märtyrern zu sehen. Die Jahreszeit selbst predigt mit der "
"Kirche, denn in eben diesen Tagen beginnt das Tageslicht zu wachsen, und die "
"Väter wiesen gern vom wachsenden Licht auf den Herrn, der die Sonne der "
"Gerechtigkeit heisst, und gedachten des Wortes des Vorläufers, dessen "
"Empfängnis die Kirche auf die Abnahme des Lichtes gelegt hat: Er muss "
"wachsen, ich aber muss abnehmen. So vergehen die Tage des Nachfestes in "
"Danksagung an Christus, unseren Gott, geboren aus der Jungfrau zu unserem "
"Heil; und die Kirche, die noch zu Bethlehem steht, lernt, das Fest in die "
"gewöhnliche Zeit hinein weiterzutragen, was die ganze Kunst des christlichen "
"Jahres ist.",

"Afterfeast of the Nativity of the Mother of God":
"Dies sind die Tage des Nachfestes der Geburt der Allheiligen Gottesgebärerin, "
"an denen die Kirche die Geburt der Gottesmutter aus den gerechten Joachim "
"und Anna weiter feiert. Die Hymnen des Festes werden mit den täglichen "
"Gottesdiensten gesungen und verlängern die Freude der Feier, während die "
"Gläubigen die Lösung der Unfruchtbarkeit Annas betrachten und das Erscheinen "
"derer in der Welt, die von Ewigkeit her dazu bestimmt war, die Mutter des "
"Erlösers zu werden. Die Kirche erblickt in der neugeborenen Jungfrau den "
"Anfang unseres Heils, die Tür, die sich nach Osten öffnen wird, den Tempel, "
"in dem Gott wohnen wird; und sie ruft die ganze Schöpfung auf, sich mit den "
"gerechten Vorfahren Gottes zu freuen, bis das Fest an seinem Beschluss zu "
"Ende geführt wird.",

"Afterfeast of the Theophany of our Lord and Savior Jesus Christ":
"Das Nachfest der Theophanie unseres Herrn trägt das Fest der Taufe des Herrn "
"durch die folgenden Tage bis zum Beschluss am vierzehnten Januar, und in "
"ihnen bleibt die Kirche am Jordan stehen und wiederholt bei jedem "
"Gottesdienst das Troparion des Festes: Als du, o Herr, im Jordan getauft "
"wurdest, wurde die Anbetung der Dreifaltigkeit offenbar; denn die Theophanie "
"ist das Fest des ersten offenen Aufleuchtens der drei Personen, der Stimme "
"des Vaters, des Sohnes im Wasser, des Geistes als Taube, und ein Geheimnis "
"solchen Ausmasses wird nicht besucht, sondern bewohnt. Durch diese Tage "
"hindurch werden die Heiligen, deren gedacht wird, und der Vorläufer unter "
"ihnen zuerst, allesamt im Licht des Stromes geschaut; die Gläubigen tragen "
"das grosse Weihwasser des Festes in ihre Häuser, und die Geistlichen gehen "
"mit dem Segen von Haus zu Haus, und der Jordan tritt, wie die Väter sagten, "
"über seine Ufer in jede Wohnung der Getauften; und die Hymnen lassen die "
"grosse Lehre des Festes weiterklingen, dass der Sündlose, indem er in das "
"Wasser hinabstieg, die Sünden der Welt begrub, die Häupter der Drachen in "
"den Wassern zerschmetterte und das Element jeder Taufe für immer zu einem "
"Schoss der Annahme an Kindes Statt machte. Das Nachfest lehrt die Kirche, "
"eine Zeitlang in ihrer eigenen Taufe zu leben, und erinnert daran, dass, was "
"am Jordan geschah, durch Gnade an jedem Taufbecken geschah; und es führt sie "
"stetig zum Beschluss hin, gleichsam nass vom Fest und aufs Neue als das Haus "
"des geliebten Sohnes gezeichnet.",

"Afterfeast of the Transfiguration of our Lord":
"Dies ist der erste Tag des Nachfestes der Verklärung des Herrn, an dem die "
"Kirche die Herrlichkeit weiter feiert, die auf dem heiligen Berge offenbart "
"wurde. Die Hymnen des Festes rufen das Staunen der Apostel Petrus, Jakobus "
"und Johannes ins Gedächtnis, als sie ihren Meister vor sich verklärt sahen, "
"sein Antlitz und seine Gewänder heller leuchtend als die Sonne, und sie "
"verkünden seine Gleichheit mit dem Vater, denn er, der sich mit Licht kleidet "
"wie mit einem Gewande, zeigte seinen Jüngern seinen göttlichen Glanz. Durch "
"diese Tage sind die Gläubigen gerufen, ihre Sinne zum ungeschaffenen Licht "
"Christi zu erheben und sich wie die Apostel zu bereiten, ihm zu seinem Leiden "
"und zu seiner Herrlichkeit zu folgen.",

"Apostle Alphaeus of the Seventy":
"Der heilige Apostel Alphäus war einer der Siebzig, die der Herr erwählte und "
"zu zweien vor sich her in jede Stadt und an jeden Ort sandte, wohin er selbst "
"kommen wollte, und wird von der Kirche unter jener zweiten Schar von Aposteln "
"geehrt, die nach den Zwölf das Evangelium durch die Welt trugen. Die "
"Überlieferung der Kirche verbindet ihn mit den apostolischen Häusern des "
"ersten Geschlechts und gedenkt seiner als eines Vaters von Heiligen, denn der "
"Apostel Jakobus, der Sohn des Alphäus, einer der Zwölf, und nach der Rechnung "
"vieler Väter auch der Evangelist Matthäus, der auch Levi, der Sohn des "
"Alphäus, genannt wird, werden zu seinen Söhnen gezählt, so dass aus seinem "
"Hause Apostel sowohl der Zwölf als auch der Siebzig hervorgingen, eine "
"Familie, die ganz dem Dienste Christi hingegeben war. Von den Einzelheiten "
"seiner eigenen Mühen bewahrt die Überlieferung wenig, wie sie von den meisten "
"der Siebzig wenig bewahrt, deren Namen gehalten und deren Apostelamt geehrt "
"wird, obwohl ihre gesonderten Geschichten nicht alle auf uns gekommen sind; "
"die Kirche aber zählt Alphäus zuverlässig unter die ersten Herolde des "
"Reiches, von der Hand des Herrn selbst gesandt, und ehrt ihn in der Synaxis "
"der Siebzig. Und sie ehrt in Alphäus den Apostel, dessen Haus zu einem "
"Saatbeet des Evangeliums wurde, und lehrt, dass die Gnade Gottes ganze "
"Familien in das apostolische Werk sammelte, dass der Vater, der selbst unter "
"den Siebzig ausgesandt war, der Kirche Söhne gab, die neben den Zwölf "
"predigten, und dass es eine Herrlichkeit ist, die keiner weiteren Chronik "
"bedarf, unter die ersten Apostel des Herrn gezählt zu werden, auch ohne eine "
"erhaltene Geschichte.",

"Apostle Ananias of the Seventy":
"Der heilige Apostel Ananias von den Siebzig war ein Jünger des Herrn, der zu "
"Damaskus wohnte, dem der Herr in einer Schau erschien und ihm gebot, in die "
"Strasse zu gehen, die die Gerade heisst, und dem Saulus von Tarsus die Hände "
"aufzulegen, dem Verfolger der Kirche, der dort blind im Gebet lag. Ananias, "
"obwohl er gehört hatte, wieviel Böses dieser Mann den Heiligen zu Jerusalem "
"angetan hatte, gehorchte dem Worte des Herrn, der offenbarte, dass Saulus "
"sein auserwähltes Werkzeug sei; und als er in das Haus trat, legte er ihm die "
"Hände auf und sprach: Bruder Saul, sei wieder sehend, und alsbald fiel es ihm "
"wie Schuppen von den Augen, und er wurde getauft und wurde Paulus, der grosse "
"Apostel der Völker. Ananias war danach Bischof von Damaskus und predigte das "
"Evangelium dort und zu Eleutheropolis im Lande Israel, wo er viele Heilungen "
"wirkte und viele zu Christus führte und dadurch den Zorn des Statthalters "
"Lucian erregte, und nach Geisselung und Martern wurde er vor der Stadt "
"gesteinigt und empfing die Krone des Martyriums und den ersten Platz unter "
"denen, die den Namen Christi jenem Apostel brachten, der ihn bis an die Enden "
"der Erde tragen sollte.",
}
