# -*- coding: utf-8 -*-
"""Italian headwords and definitions for the Glossary. TERMS = {id: (headword, definition)}."""
TERMS = {
"abbot": ("Igumeno (Abate)", "Il superiore di un monastero."),
"aer": ("Aer (velo grande)", "Il più grande dei veli, che copre insieme il disco e il calice, e che si agita sopra i doni durante il Simbolo della fede."),
"toll-houses": ("Dogane aeree", "Un racconto del passaggio dell'anima dopo la morte, nel quale essa è esaminata dai demoni a tappe successive. Si trova in fonti patristiche, agiografiche e liturgiche, ed è difeso da molti santi. La sua forma sistematizzata è contestata da alcuni teologi e gerarchi contemporanei. Plithos presenta le fonti senza decidere fra esse."),
"akathist": ("Akathistos", "Inno di ventiquattro strofe cantato in piedi, giacché il nome significa non seduto. L'originale è alla Theotokos; molti più tardi ne seguono la forma."),
"akriveia": ("Akribeia (Esattezza)", "L'applicazione rigorosa dei canoni, il corrispettivo dell'economia."),
"vigil": ("Veglia di tutta la notte", "Vespro, Orthros e Prima Ora uniti in un solo ufficio alla vigilia delle domeniche e delle grandi feste."),
"alleluiarion": ("Alleluiario", "L'Alleluia con i suoi versetti, cantato fra l'Epistola e il Vangelo."),
"ambo": ("Ambone", "La sporgenza della solea davanti alle porte regali, dalla quale si legge il Vangelo e si dice la preghiera dietro l'ambone."),
"analavos": ("Analavos", "La veste del grande schema, ricamata con la Croce, la lancia, la spugna e le parole della Passione."),
"analogion": ("Analogio", "Il leggio inclinato che regge un'icona o un libro liturgico."),
"anaphora": ("Anafora", "La preghiera centrale della Liturgia, l'offerta, che contiene le parole dell'istituzione e l'epiclesi."),
"antidoron": ("Antidoron", "Il resto della prosfora, benedetto ma non consacrato, distribuito al termine della Liturgia. Il nome significa al posto del dono: si dà a tutti i presenti, anche a chi non si è comunicato."),
"antimension": ("Antimensio", "Il panno firmato dal vescovo, contenente reliquie, steso sulla Santa Mensa. Senza di esso la Liturgia non può essere celebrata: è l'autorizzazione del vescovo per l'altare."),
"apatheia": ("Apatheia (Impassibilità)", "Non insensibilità, ma la guarigione delle passioni, così che le potenze dell'anima si muovano rettamente verso Dio."),
"apostles-fast": ("Digiuno degli Apostoli", "Il digiuno dal lunedì dopo Ognissanti fino alla festa dei santi Pietro e Paolo, il 29 giugno. La sua durata varia con la data di Pasqua."),
"archbishop": ("Arcivescovo", "Vescovo di rango elevato. Nell'uso greco sta di solito sopra il metropolita, in quello slavo sotto."),
"archimandrite": ("Archimandrita", "Sacerdote monaco di rango elevato, spesso superiore di un monastero o candidato all'episcopato."),
"archpriest": ("Arciprete", "Sacerdote parrocchiale di rango elevato; è una distinzione, non un ordine distinto."),
"artoklasia": ("Artoclasia (frazione dei pani)", "La benedizione e frazione di cinque pani alla litia, in memoria della moltiplicazione per i cinquemila."),
"asterisk": ("Asterisco", "La stella snodabile posta sopra il disco perché il velo non tocchi le particole; ricorda la stella sopra Betlemme."),
"autocephaly": ("Autocefalia", "Condizione di una Chiesa che elegge da sé il proprio primate e non è soggetta ad altra, pur restando in comunione con le altre."),
"autonomy": ("Autonomia", "Condizione di una Chiesa che si governa da sé, ma il cui primate è confermato da una Chiesa madre."),
"baptism": ("Battesimo", "La triplice immersione nella morte e risurrezione di Cristo, per la quale si entra nella Chiesa."),
"odes": ("Odi bibliche", "I nove cantici scritturistici, dai canti di Mosè al Magnificat e alla preghiera di Zaccaria, sui quali sono modellate le odi di un canone."),
"bishop": ("Vescovo", "Il più alto dei tre ordini maggiori, che possiede la pienezza del sacerdozio, ordina i chierici ed è il centro dell'unità della sua diocesi."),
"bright-week": ("Settimana Luminosa", "La settimana che segue la Pasqua, tenuta come un solo giorno continuo della festa, senza digiuno e con le porte regali aperte."),
"canon-hymn": ("Canone (inno)", "Il lungo inno dell'Orthros in otto o nove odi, ciascuna legata a uno dei cantici biblici."),
"canon-law": ("Canone (regola)", "Regola della Chiesa data da un concilio o da un padre e ricevuta dall'intero corpo. Da distinguere dal canone cantato all'Orthros."),
"catechumen": ("Catecumeno", "Chi è istruito nella fede in preparazione al battesimo; secondo l'uso antico è congedato prima della Liturgia dei fedeli."),
"catholicity": ("Cattolicità", "L'interezza della Chiesa: non estensione ma pienezza, poiché ogni Chiesa locale raccolta attorno al suo vescovo possiede il tutto. L'espressione secondo il tutto rende kath' holon."),
"censer": ("Turibolo", "Il vaso in cui si brucia l'incenso, con campanelli nell'uso slavo e nella maggior parte di quelli greci."),
"chalice": ("Calice", "La coppa che contiene il vino dell'offerta e, dopo la consacrazione, il Sangue di Cristo."),
"cherubic-hymn": ("Inno Cherubico", "L'inno cantato durante la Grande Entrata, nel quale i fedeli depongono ogni cura terrena per accogliere il Re di tutti."),
"chrismation": ("Crismazione", "L'unzione con il santo myron subito dopo il battesimo, sigillo del dono dello Spirito Santo."),
"churching": ("Presentazione in chiesa", "La presentazione della madre e del bambino in chiesa al quarantesimo giorno, con preghiere di ringraziamento e benedizione."),
"clean-monday": ("Lunedì Puro", "Il primo giorno della Grande Quaresima, dopo la domenica del Perdono."),
"spoon": ("Cucchiaio della comunione", "Il cucchiaio con cui i fedeli ricevono insieme il Corpo e il Sangue. Il suo nome greco significa tenaglia, dal carbone preso con le tenaglie nella visione di Isaia."),
"compline": ("Compieta (Apodipnon)", "L'ufficio dopo la cena, prima del sonno. La Piccola Compieta si usa la maggior parte dell'anno; la Grande appartiene alla Grande Quaresima e a certe veglie."),
"compunction": ("Compunzione (Katanyxis)", "Il trafiggimento del cuore che porta le lacrime e lo ammorbidisce verso Dio."),
"confession": ("Confessione", "Il mistero del pentimento, nel quale i peccati sono confessati davanti a Dio alla presenza di un sacerdote e viene data l'assoluzione. La sua frequenza differisce notevolmente fra le tradizioni."),
"crowning": ("Incoronazione (Matrimonio)", "Il mistero del matrimonio, così chiamato dalle corone poste sul capo degli sposi, che significano insieme regalità e martirio."),
"deacon": ("Diacono", "Il terzo ordine, che serve all'altare, dice le litanie e non può celebrare da solo i misteri."),
"dikirion": ("Dikirion e trikirion", "I candelieri a due e a tre bracci con cui il vescovo benedice, che significano le due nature di Cristo e le tre Persone della Trinità."),
"diptychs": ("Dittici", "Gli elenchi dei vivi e dei defunti commemorati alla Liturgia, e fra i primati l'ordine di precedenza e di comunione."),
"diskos": ("Disco (Patena)", "Il piatto con piede su cui si pongono l'Agnello e le particole commemorative."),
"dispassion": ("Impassibilità (ingl. dispassion)", "La resa inglese di apatheia; vedi quella voce."),
"divine-liturgy": ("Divina Liturgia", "L'ufficio eucaristico della Chiesa, nel quale il pane e il vino sono offerti e divengono il Corpo e il Sangue di Cristo. Si celebra il più delle volte nella forma di san Giovanni Crisostomo."),
"dormition-fast": ("Digiuno della Dormizione", "Il digiuno dal 1 al 14 agosto, prima della Dormizione della Theotokos."),
"economia": ("Economia", "La discrezione pastorale per cui l'applicazione rigorosa di un canone viene mitigata per la salvezza delle anime; il corrispettivo dell'akribeia."),
"ecumenical-council": ("Concilio Ecumenico", "Concilio le cui definizioni la Chiesa intera ha ricevuto. La Chiesa ortodossa ne tiene sette, da Nicea nel 325 a Nicea II nel 787."),
"elder": ("Anziano (Starets, Gheronda)", "Monaco di discernimento al quale altri svelano i propri pensieri e dal quale ricevono direzione."),
"epigonation": ("Epigonation", "Il panno rigido a forma di rombo appeso al ginocchio destro, dato come distinzione; significa la spada dello Spirito."),
"epiklesis": ("Epiclesi", "L'invocazione dello Spirito Santo sui doni e su coloro che sono radunati, alla quale la Chiesa ortodossa intende che la consacrazione si compia."),
"epimanikia": ("Epimanikia (manichini)", "I polsini indossati dai chierici, che stringono le maniche e significano i legami di Cristo."),
"epitaphios": ("Epitafio", "Il panno ricamato con l'immagine di Cristo deposto nel sepolcro, portato in processione il Venerdì Santo."),
"epitimia": ("Epitimia (penitenza)", "Regola data alla confessione come medicina e non come castigo: prostrazioni, elemosina o astensione dalla comunione per un tempo."),
"epitrachelion": ("Epitrachelion (stola)", "La stola del sacerdote, portata attorno al collo. Nessun ufficio sacerdotale si compie senza di essa."),
"essence-energies": ("Essenza ed energie", "La distinzione, formulata da san Gregorio Palamas, fra l'essenza inconoscibile di Dio e le sue energie increate, per le quali egli è veramente partecipato."),
"euchologion": ("Eucologio", "Il libro liturgico del sacerdote, che contiene le preghiere della Liturgia, i misteri e gli uffici occasionali."),
"fast-free": ("Settimana senza digiuno", "Settimana in cui il digiuno del mercoledì e del venerdì è tolto, come la Settimana Luminosa e la settimana dopo Pentecoste."),
"forefeast": ("Prefesta e postfesta", "I giorni di preparazione prima di una grande festa e quelli di prosecuzione dopo di essa."),
"forgiveness-vespers": ("Vespro del Perdono", "Il vespro della sera che precede l'inizio della Grande Quaresima, nel quale i fedeli si chiedono perdono a vicenda."),
"glorification": ("Glorificazione (Canonizzazione)", "Il riconoscimento da parte della Chiesa che una persona è fra i santi, che formalizza una venerazione già sorta fra i fedeli."),
"theophany-water": ("Grande Benedizione delle Acque", "La benedizione dell'acqua a Teofania; si conserva tutto l'anno e si beve al bisogno."),
"doxology": ("Grande Dossologia", "Gloria a Dio nel più alto dei cieli, cantata verso la fine dell'Orthros nelle domeniche e nelle feste."),
"great-entrance": ("Grande Entrata", "La processione che porta i doni preparati dalla mensa dell'offerta alla Santa Mensa, durante l'Inno Cherubico."),
"great-feasts": ("Grandi Feste", "Le dodici feste maggiori dell'anno insieme alla Pasqua, che sta sopra di esse come festa delle feste."),
"great-lent": ("Grande Quaresima", "Il digiuno di quaranta giorni prima della Settimana Santa e della Pasqua, che comincia nel Lunedì Puro."),
"great-schema": ("Grande Schema", "Il grado più alto della tonsura monastica, con l'analavos e una regola di preghiera intensificata e di ritiro."),
"hesychasm": ("Esicasmo", "La tradizione della quiete interiore e della preghiera incessante, difesa da san Gregorio Palamas e confermata dai concili del quattordicesimo secolo."),
"hierodeacon": ("Ierodiacono", "Monaco ordinato diacono."),
"hieromonk": ("Ieromonaco", "Monaco ordinato sacerdote."),
"myron": ("Santo Myron (Crisma)", "L'olio profumato consacrato da un patriarca o da un sinodo e usato nella crismazione."),
"altar-table": ("Santa Mensa (Altare)", "La mensa al centro del santuario sulla quale si offre la Liturgia; contiene reliquie."),
"unction": ("Santa Unzione", "L'unzione dei malati con olio benedetto per la guarigione dell'anima e del corpo, celebrata da più sacerdoti dove è possibile."),
"holy-week": ("Settimana Santa", "La settimana dalla Domenica delle Palme al Sabato Santo, dopo la Grande Quaresima e prima della Pasqua."),
"horologion": ("Orologion", "Il libro delle ore, che contiene le parti fisse del ciclo quotidiano degli uffici."),
"hypostasis": ("Ipostasi", "Persona, distinta dalla natura o essenza. La Trinità è tre ipostasi in una essenza; Cristo è una ipostasi in due nature."),
"iconography": ("Icona", "Immagine scritta di Cristo, della Theotokos o dei santi, venerata perché l'onore passa al prototipo. Difesa al Settimo Concilio Ecumenico."),
"iconostasis": ("Iconostasi", "La parete di icone fra la navata e il santuario, con le porte regali al centro e un ordine fisso delle icone."),
"incarnation": ("Incarnazione", "L'assunzione della natura umana da parte del Verbo eterno, vero Dio e vero uomo in una sola persona."),
"incense": ("Incenso", "Bruciato agli uffici, significa la preghiera che sale davanti a Dio."),
"incorrupt": ("Incorruzione", "La preservazione del corpo di un santo dalla corruzione, accolta come segno di santità, benché non richiesta per la glorificazione."),
"indiction": ("Indizione", "L'inizio dell'anno ecclesiastico il 1 settembre."),
"irmos": ("Irmos", "Il primo tropario di ciascuna ode di un canone, che ne fissa la melodia e il metro e la lega al cantico biblico."),
"jesus-prayer": ("Preghiera di Gesù", "Signore Gesù Cristo, Figlio di Dio, abbi pietà di me peccatore, ripetuta come fondamento della preghiera incessante."),
"julian-calendar": ("Calendari giuliano e giuliano riveduto", "L'antico giuliano, tenuto da alcune Chiese per tutto l'anno, e il giuliano riveduto, che segue il gregoriano per le feste fisse conservando il computo pasquale giuliano."),
"katavasia": ("Katavasia", "L'irmos ripetuto alla fine di un'ode; così chiamato perché i cori scendevano dai loro posti per cantarlo insieme."),
"kathisma": ("Kathisma", "Una delle venti divisioni del Salterio; anche un inno sessionale cantato dopo di essa, durante il quale è permesso sedere."),
"kenosis": ("Kenosi", "L'annientamento di sé del Figlio nell'Incarnazione, di cui parla Filippesi 2."),
"klobuk": ("Klobuk", "Il copricapo monastico: un cappello cilindrico con velo."),
"koliva": ("Koliva", "Grano bollito con miele e frutti, benedetto ai memoriali, dalle parole del Signore che il chicco deve morire per portare frutto."),
"kontakion": ("Kontakion", "Secondo inno breve che riassume la festa o il santo. In origine era un lungo sermone poetico in molte strofe, di cui il kontakion superstite è la prima."),
"lance": ("Lancia", "Il coltellino a forma di lancia usato alla prothesis per tagliare l'Agnello e le particole; ricorda la lancia che trafisse il costato di Cristo."),
"leavetaking": ("Chiusura della festa (Apodosis)", "L'ultimo giorno della postfesta, tenuto con gran parte dell'innografia della festa stessa."),
"little-entrance": ("Piccola Entrata", "La processione con il libro del Vangelo verso l'inizio della Liturgia."),
"liturgy-of-basil": ("Liturgia di san Basilio", "Forma più lunga della Divina Liturgia con anafora propria, celebrata dieci volte l'anno: le domeniche della Grande Quaresima tranne le Palme, il Giovedì Santo e il Sabato Santo, le vigilie del Natale e della Teofania, e la festa di san Basilio il 1 gennaio."),
"presanctified": ("Liturgia dei Doni Presantificati", "Ufficio di vespro con comunione ai Doni consacrati alla Liturgia della domenica precedente, celebrato nei giorni feriali della Grande Quaresima, quando non si celebra la Liturgia piena."),
"litya": ("Litia", "La processione e intercessione alla veglia, nella quale si benedicono pani, grano, vino e olio."),
"logismoi": ("Logismoi (pensieri)", "I pensieri o suggestioni che assalgono la mente, da discernere e respingere prima che diventino consenso."),
"mandyas": ("Mandyas", "Il mantello intero indossato dal vescovo in processione, e in forma più semplice dai monaci del grande schema."),
"menaion": ("Menaion", "I dodici volumi di inni per le feste fisse, uno per ciascun mese dell'anno."),
"menologion": ("Menologio", "Raccolta di vite di santi ordinata secondo i giorni del mese."),
"metanoia": ("Metanoia (Pentimento)", "Letteralmente cambiamento della mente, la conversione dell'intera persona verso Dio. La stessa parola designa la prostrazione."),
"metropolitan": ("Metropolita", "Vescovo di una città principale, che sta sopra i vescovi della sua provincia. L'uso differisce fra le Chiese greche e quelle slave."),
"moleben": ("Moleben (ufficio di supplica)", "Ufficio di supplica a Cristo, alla Theotokos o a un santo, fuori del ciclo fisso, per un bisogno particolare o in ringraziamento."),
"monk": ("Monaco", "Chi è tonsurato alla vita monastica, sotto i voti di obbedienza, castità e povertà."),
"mystery": ("Mistero (Sacramento)", "Azione della Chiesa nella quale la grazia è data per mezzi visibili. La Chiesa ortodossa non ne ha mai fissato il numero per dogma, benché comunemente se ne enumerino sette."),
"nabedrennik": ("Nabedrennik", "Panno rettangolare portato all'anca, distinzione delle Chiese slave senza corrispettivo greco."),
"narthex": ("Nartece", "L'atrio d'ingresso della chiesa, dove un tempo stavano i catecumeni e i penitenti e dove cominciano diversi uffici."),
"nativity-fast": ("Digiuno della Natività", "Il digiuno di quaranta giorni dal 15 novembre prima della Natività di Cristo."),
"nave": ("Navata", "Il corpo della chiesa dove stanno i fedeli."),
"nepsis": ("Nepsis (Sobrietà)", "Attenzione sobria ai pensieri man mano che sorgono, per affrontarli prima che mettano radice."),
"novice": ("Novizio", "Chi vive in un monastero alla prova prima della tonsura."),
"obedience": ("Obbedienza", "Il taglio della propria volontà davanti a un anziano o a una regola; anche il compito particolare assegnato a un monaco."),
"octoechos": ("Octoechos", "Il libro degli otto toni, che regola gli inni della risurrezione delle settimane ordinarie in un ciclo di otto settimane."),
"oikos": ("Oikos", "La strofa che segue il kontakion e ne sviluppa il tema."),
"omophorion": ("Omophorion", "La fascia larga portata sulle spalle del vescovo, che significa la pecora smarrita portata dal Buon Pastore. Contrassegna il suo ufficio."),
"orarion": ("Orarion", "La fascia lunga e stretta portata sulla spalla sinistra del diacono, alzata alle litanie."),
"orthros": ("Orthros (Mattutino)", "L'ufficio del mattino, il più lungo del ciclo quotidiano, che contiene i sei salmi, il canone e nella maggior parte degli usi la Grande Dossologia."),
"panagia": ("Panagia", "Il medaglione con l'icona della Theotokos portato sul petto dal vescovo."),
"panikhida": ("Panichida", "L'ufficio di memoria per i defunti, celebrato al terzo, nono e quarantesimo giorno, agli anniversari e ai Sabati delle Anime."),
"paraklesis": ("Paraklisis", "Il canone di supplica alla Theotokos. Il Piccolo si canta durante il digiuno della Dormizione; il Grande appartiene a tempi di particolare afflizione."),
"pascha": ("Pasqua (Pascha)", "La Risurrezione di Cristo, la festa delle feste, dalla quale si computa il ciclo mobile."),
"paschalion": ("Pascalion", "Il computo della data di Pasqua, e la tavola con cui la si trova."),
"passions": ("Passioni", "I moti disordinati dell'anima, non i desideri naturali in sé ma la loro corruzione in schiavitù."),
"patriarch": ("Patriarca", "Il primate di una Chiesa autocefala di rango patriarcale."),
"pentecostarion": ("Pentecostario", "Il libro e il tempo dalla Pasqua alla Domenica di Tutti i Santi."),
"penthos": ("Penthos (Lutto)", "Il lutto per il peccato, la tristezza secondo Dio che opera pentimento, spesso unita alle lacrime."),
"phelonion": ("Phelonion", "L'ampia veste esterna senza maniche del sacerdote alla Liturgia."),
"philokalia": ("Filocalia", "L'antologia di testi ascetici e contemplativi dal quarto al quindicesimo secolo, compilata da san Nicodemo e san Macario di Corinto, pubblicata nel 1782."),
"phronema": ("Phronema", "La mente o mentalità della Chiesa, formata dal vivere in essa e non dallo studio soltanto."),
"phyletism": ("Filetismo", "La confusione della Chiesa con la nazione, condannata come eresia dal Concilio di Costantinopoli nel 1872."),
"polyeleos": ("Polyeleos", "I salmi 134 e 135 cantati all'Orthros festivo, così chiamati dal loro ritornello poiché eterna è la sua misericordia."),
"departed-prayers": ("Preghiera per i defunti", "La pratica della Chiesa di pregare per coloro che sono morti, espressa nella panichida, nei Sabati delle Anime e nelle commemorazioni alla prothesis."),
"prayer-of-heart": ("Preghiera del cuore", "La Preghiera di Gesù discesa dalla mente nel cuore e divenuta continua."),
"prayer-rope": ("Corda da preghiera", "La corda di lana annodata usata per contare la Preghiera di Gesù, comunemente di trentatré, cinquanta o cento nodi."),
"priest": ("Sacerdote (Presbitero)", "Il secondo ordine, ordinato da un vescovo per celebrare la Liturgia e i misteri in una parrocchia."),
"prokeimenon": ("Prokimenon", "Versetto, di solito dai salmi, cantato prima di una lettura della Scrittura."),
"prosoche": ("Prosoche (Attenzione)", "L'attenzione; la custodia della mente nella preghiera."),
"prosphora": ("Prosfora", "Il pane lievitato offerto per la Liturgia, impresso con un sigillo dal quale si taglia l'Agnello."),
"prostration": ("Prostrazione", "L'inchino fino a terra fatto in penitenza e adorazione. Non si fanno prostrazioni la domenica né nel tempo pasquale."),
"prothesis": ("Prothesis (Proscomidia)", "La preparazione del pane e del vino prima della Liturgia, alla mensa dell'offerta, nella quale si tagliano particole per i vivi e per i defunti."),
"psalter": ("Salterio", "I 150 salmi divisi in venti kathismata per la lettura lungo gli uffici, insieme alle nove odi bibliche."),
"rassophore": ("Rassoforo", "Il primo grado della tonsura monastica, il portatore dell'abito, senza i voti pieni."),
"reader": ("Lettore", "Ordine minore posto a parte per leggere l'Epistola e i testi prescritti."),
"relics": ("Reliquie", "I resti corporei dei santi, onorati perché il corpo è tempio dello Spirito Santo. Reliquie sono sigillate nell'antimensio e nell'altare."),
"royal-doors": ("Porte Regali", "Le porte centrali dell'iconostasi, per le quali passano solo i chierici e per le quali sono portati i Doni."),
"sakkos": ("Sakkos", "La veste esterna del vescovo, che ha sostituito il phelonion per i gerarchi."),
"salutations": ("Salutazioni", "Gli uffici del venerdì sera della Grande Quaresima nei quali l'Akathistos alla Theotokos è cantato a parti."),
"sanctuary": ("Santuario (Altare)", "Lo spazio dietro l'iconostasi che contiene la Santa Mensa, la mensa dell'offerta e il seggio alto."),
"solea": ("Solea", "Il camminamento rialzato davanti all'iconostasi, dal quale i fedeli si comunicano."),
"soul-saturday": ("Sabato delle Anime", "I sabati stabiliti per la commemorazione di tutti i defunti."),
"spiritual-father": ("Padre spirituale", "Il sacerdote o l'anziano che ascolta la confessione e guida la vita di una persona in Cristo."),
"stavrophore": ("Stavroforo (Piccolo Schema)", "Il secondo grado della tonsura monastica, il portatore della croce, nel quale si emettono i voti pieni."),
"stavrotheotokion": ("Stavrotheotokion", "Un theotokion sulla Madre di Dio presso la Croce, usato il mercoledì e il venerdì."),
"sticharion": ("Sticharion", "La tunica lunga indossata da tutti i gradi del clero, e dai lettori e dai ministranti."),
"sticheron": ("Stichirà", "Inno cantato fra i versetti di un salmo, soprattutto al vespro e all'orthros."),
"subdeacon": ("Suddiacono", "Ordine minore che assiste il vescovo e ha cura dei vasi."),
"synaxarion": ("Sinassario", "Il racconto dei santi e delle feste stabiliti per il giorno, letto all'Orthros; anche il libro che li raccoglie."),
"tabernacle": ("Tabernacolo", "Il vaso sulla Santa Mensa nel quale si conservano i Doni Presantificati per i malati e per la Liturgia dei Presantificati."),
"hours": ("Le Ore", "I quattro brevi uffici del giorno: Prima, Terza, Sesta e Nona, computate dal levar del sole, ciascuna con i propri salmi e il proprio tema."),
"lamb": ("L'Agnello", "La porzione quadrata tagliata dalla prima prosfora, che è consacrata e diviene il Corpo di Cristo."),
"rudder": ("Il Timone (Pedalion)", "La principale raccolta greca dei canoni della Chiesa con commento, compilata da san Nicodemo del Monte Athos e da sant'Agapio, pubblicata nel 1800."),
"theosis": ("Theosis (Deificazione)", "La partecipazione della persona umana alla vita divina per grazia, il fine per cui l'uomo è stato fatto. Per grazia e non per natura."),
"theotokion": ("Theotokion", "Inno alla Madre di Dio, posto alla fine di un gruppo di inni."),
"theotokos": ("Theotokos", "Colei che genera Dio, titolo della Vergine Maria affermato a Efeso nel 431. Custodisce la verità che colui che è nato da lei è Dio."),
"tone": ("Tono (Echos)", "Uno degli otto modi musicali nei quali si cantano gli inni, che cambia di settimana in settimana attraverso l'Octoechos."),
"triodion": ("Triodion", "Il libro e il tempo delle settimane prima della Grande Quaresima e lungo di essa, fino al Sabato Santo. Così chiamato dai suoi canoni di tre odi."),
"trisagion": ("Trisagio", "Santo Dio, Santo Forte, Santo Immortale, abbi pietà di noi, cantato tre volte; anche il nome del breve insieme di preghiere con cui comincia la maggior parte degli uffici."),
"troparion": ("Tropario", "Il principale inno breve di una festa o di un santo, che ne enuncia il tema. Chiamato anche apolytikion quando è cantato al congedo."),
"typikon": ("Typikon", "Il libro delle rubriche, che dirige come si tengono gli uffici e i digiuni e come si combinano i cicli quando coincidono."),
"veneration": ("Venerazione e adorazione", "La distinzione affermata a Nicea II: l'adorazione spetta a Dio soltanto, mentre la venerazione è offerta alle icone, alle reliquie e ai santi."),
"vespers": ("Vespro", "L'ufficio della sera, con il quale comincia il giorno liturgico. Si apre con il salmo 103 e con l'accensione delle lampade."),
"xerophagy": ("Xerofagia", "Mangiare secco: il grado più rigoroso del digiuno ordinario, senza olio né vino, tenuto nei giorni feriali della Grande Quaresima."),
"zeon": ("Zeon", "L'acqua calda versata nel calice prima della comunione, che significa il calore dello Spirito Santo e che il Corpo ricevuto è vivo."),
"zone": ("Zona (Cintura)", "La cintura portata dal sacerdote o dal vescovo sopra lo sticharion e l'epitrachelion."),
}
