# -*- coding: utf-8 -*-
"""Arabic for the vocabulary that stands beside the lives.

TEXT = {the phrase the index shows: the rendering}. The keys are the phrases
exactly as the index writes them, so a rendering cannot quietly attach itself
to the wrong saint.

A language may later declare PARTS and an expand() to assemble the compound
place-names from pieces rendered once, as the older languages do. It is an
optimisation and not a requirement: everything written in TEXT stands over
whatever expand() builds.
"""
TEXT = {
}

TEXT.update({
    "(Abibus) of Egypt": "(أبيبوس) المصري",
    "(Apphianus) and Edesius (Aedesius) of Lycia": "(أبيانوس) وإديسيوس (أيديسيوس) من ليكية",
    "(Eustace) the Confessor, Bishop of Bithynia": "(إفستاثيوس) المعترف، أسقف بيثينية",
    "(Jacob) the Presbyter, and Azadanes and Abdiesus the Deacons, of Persia": "(يعقوب) القس، وأزادانيس وعبديشوع الشماسان، من بلاد فارس",
    "(Vadim) of Persia": "(واديم) الفارسي",
    "(Voino-Yasenetsky), Archbishop of Simferopol and Crimea": "(فوينو-ياسينيتسكي)، رئيس أساقفة سيمفيروبول والقرم",
    "(also called Susanna), New Martyr of Lesbos": "(المدعوة أيضا سوسنة)، الشهيدة الجديدة من لسبوس",
    "(tonsured David and Euphrosyne), Wonderworkers of Murom": "(المحلوقان داود وإفروسيني)، العجائبيان في موروم",
    "A Cappadocian centurion bowing beneath the sword with his eyes lifted in thanksgiving, the walnut tree of the tradition behind him, the churches of Byzantium rising over his relics.": "قائد مئة من كبادوكية ينحني تحت السيف ورأسه مرفوع بالشكر، وشجرة الجوز التي يذكرها التقليد خلفه، وكنائس بيزنطية ترتفع فوق رفاته.",
    "A Celtic hermit of the Devon coast bearing his own severed head to the spring, the robbers behind him, crowned as a martyr among the saints of Britain.": "ناسك كلتي من ساحل ديفون يحمل رأسه المقطوع إلى النبع، واللصوص خلفه، مكللا شهيدا بين قديسي بريطانيا.",
    "A Christian general casting down the temples of Galatia, his twelve tribunes and his thousands of soldiers with their wives and children crowned around him, the converted sorcerer Callinicus among them.": "قائد مسيحي يهدم هياكل غلاطية، واثنا عشر من قواده وألوف من جنده مع نسائهم وأولادهم مكللون حوله، وبينهم الساحر كالينيكوس الذي اهتدى.",
    "A Christian of Alexandria standing before the tribunal to denounce its cruelty, the confession volunteered and the sword received.": "مسيحي من الإسكندرية يقف أمام المحكمة ليندد بقسوتها، اعتراف بذله من نفسه وسيف قبله.",
    "A Creole-Aleut priest in vestments holding a Gospel and a cross, against an Alaskan landscape.": "كاهن من الكريول والأليوت بالحلة الكهنوتية يحمل إنجيلا وصليبا، على خلفية من طبيعة ألاسكا.",
    "A Georgian bishop with a book and a restored church, schoolchildren and monasteries behind him.": "أسقف جورجي بكتاب وكنيسة أعاد بناءها، وتلاميذ مدارس وأديرة خلفه.",
    "A Georgian commander marking his forehead with the cross in his own blood, his soldiers crowned around him.": "قائد جورجي يرسم الصليب على جبهته بدمه، وجنوده مكللون حوله.",
    "A Georgian monk in prayer before the cave monastery of Gareji in the desert hills.": "راهب جورجي في الصلاة أمام دير المغاور في غاريجي بين تلال البرية.",
    "A Georgian monk-abbot holding a scroll or a book.": "راهب جورجي رئيس دير يحمل درجا أو كتابا.",
    "A Georgian prince and commander refusing to trample the icon of Christ before the conqueror, crowned as a great-martyr, the defender of the Georgian faith.": "أمير جورجي وقائد يأبى أن يدوس أيقونة المسيح أمام الفاتح، مكللا عظيما في الشهداء، حامي الإيمان الجورجي.",
    "A Gothic congregation at worship within the burning church, twenty-six crowns rising with the smoke, the queen gathering the holy remains from the ashes.": "جماعة قوطية في الصلاة داخل الكنيسة المشتعلة، وستة وعشرون إكليلا تصعد مع الدخان، والملكة تجمع الرفات المقدسة من الرماد.",
    "A Gothic general of Rome casting down his military belt before Aurelian, seventy soldiers confessing behind him, the river receiving the wonderworking commander.": "قائد قوطي في جيش رومة يطرح منطقة جنديته أمام أفرليانوس، وسبعون جنديا يعترفون خلفه، والنهر يتقبل القائد العجائبي.",
    "A Great Prince of Kyiv with the churches of Smolensk he raised, the monastic habit he longed for held by an angel, the elder Polycarp pointing him back to his throne.": "أمير كييف الأكبر مع كنائس سمولنسك التي شادها، والثوب الرهباني الذي اشتهاه يحمله ملاك، والشيخ بوليكاربوس يرده إلى عرشه.",
    "A Greek bishop preaching Christ to the pagan Rostov land, the first shepherd of a hostile flock, the see of Rostov founded amid the idols of the north.": "أسقف يوناني يبشر بالمسيح في أرض روستوف الوثنية، أول راع لرعية معادية، وكرسي روستوف يقوم بين أصنام الشمال.",
    "A Greek iconographer of Constantinople founding the island monastery of Lake Onega, the Sophia icon he copied in his hands, the peoples of the north gathering to his light at the age of one hundred and five.": "مصور أيقونات يوناني من القسطنطينية يؤسس دير الجزيرة في بحيرة أونيغا، وأيقونة الحكمة التي نسخها في يديه، وشعوب الشمال تجتمع إلى نوره وهو ابن مئة وخمس سنين.",
    "A Greek metropolitan enthroned at Moscow beside the shrine of Peter, standing unbowed before the khan of the Horde, the Church's charter of freedom in his hand.": "مطران يوناني على كرسي موسكو إلى جانب ضريح بطرس، يقف غير منحن أمام خان القبيلة، وميثاق حرية الكنيسة في يده.",
    "A Greek of Ephesus at the Apostle Paul's side, the Temple riot swirling around his innocent presence, the sickbed of Miletus and the sword of Rome completing his long companionship.": "يوناني من أفسس إلى جانب الرسول بولس، وشغب الهيكل يدور حول براءته، وفراش المرض في ميليتس وسيف رومة يتمان رفقته الطويلة.",
    "A Greek prince laying aside his rank for the monastic habit, the Uchma hermitage rising on the bank of the Volga, the exile made a wonderworker in his adopted land.": "أمير يوناني يضع رتبته جانبا ويلبس الثوب الرهباني، ومعتكف أوتشما يقوم على ضفة الفولغا، والغريب يصير عجائبيا في الأرض التي تبنته.",
    "A Patriarch of Constantinople seated upright in death as in blessing, the Mgar monastery of Lubny receiving the traveler, the two worlds of Greece and Rus' joined at his throne.": "بطريرك القسطنطينية جالسا في موته كأنه يبارك، ودير مغار في لوبني يستقبل المسافر، وعالما اليونان والروس مجتمعان عند عرشه.",
    "A Persian noble offering his severed members one by one, each with a prayer, angels gathering his prayers.": "شريف فارسي يقدم أعضاءه المقطوعة واحدا واحدا، مع كل عضو صلاة، والملائكة تجمع صلواته.",
    "A Persian soldier turned monk, the captive Cross of the Lord shining before him, the waters and the sword of Bethsaloe beneath his crown.": "جندي فارسي صار راهبا، وصليب الرب المسبي يلمع أمامه، ومياه بيت سلوخ وسيفها تحت إكليله.",
    "A Roman centurion kneeling before the Apostle Peter, or vested as a bishop holding a Gospel.": "قائد مئة روماني راكعا أمام الرسول بطرس، أو بحلة أسقف يحمل إنجيلا.",
    "A Roman general in armor holding a cross, his soldiers behind him, a spring at his feet.": "قائد روماني في سلاحه يحمل صليبا، وجنوده خلفه، وينبوع عند قدميه.",
    "A Roman maiden in flight across the sea with two servants, the convent of Saint Stephen at Mylasa, a cross of stars brighter than the sun above her repose.": "فتاة رومانية هاربة عبر البحر مع خادمتين، ودير القديس إسطفانوس في ميلاسا، وصليب من نجوم أشد بهاء من الشمس فوق رقادها.",
    "A Roman matron refusing the Arian rite, the fire kindled behind her, Saint Ambrose blessing from afar.": "سيدة رومانية تأبى الطقس الأريوسي، والنار تضرم خلفها، والقديس أمبروسيوس يبارك من بعيد.",
    "A Roman noblewoman scattering deeds and treasure to the poor, thousands of freed slaves behind her, her small cell on the Mount of Olives before her.": "شريفة رومانية تبدد صكوكها وكنوزها على الفقراء، وألوف من العبيد الذين أعتقتهم خلفها، وقلايتها الصغيرة على جبل الزيتون أمامها.",
    "A Roman senator opening his house to the Apostle Peter, the household at prayer becoming a church, the greeting of the epistle shining over the door.": "شيخ من مجلس رومة يفتح بيته للرسول بطرس، وأهل البيت في الصلاة يصيرون كنيسة، وتحية الرسالة تشرق فوق الباب.",
    "A Roman widow standing amid seven crowned sons, encouraging each to the contest, her own crown descending last.": "أرملة رومانية واقفة بين سبعة أبناء مكللين، تشجع كل واحد على الجهاد، وإكليلها ينزل آخر الجميع.",
    "A Russian captive in the winter night of Kazan, bound and wounded in the snow, alive at dawn with his confession unbroken.": "أسير روسي في ليل قازان الشتوي، مقيدا مجروحا في الثلج، حيا عند الفجر واعترافه غير منكسر.",
    "A Russian soldier-slave at prayer in his master's stable, the Turkish household softened by his faith, his incorrupt relics glorified across the Greek world.": "جندي روسي في العبودية يصلي في إسطبل سيده، وبيت التركي يلين بإيمانه، ورفاته غير البالية تمجد في العالم اليوناني كله.",
    "A Serbian prince leading his army at Kosovo, choosing the kingdom of heaven over the kingdom of earth, crowned as a great-martyr, his incorrupt relics the treasure of his people.": "أمير صربي يقود جيشه في كوسوفو، مختارا ملكوت السماء على ملك الأرض، مكللا عظيما في الشهداء، ورفاته غير البالية كنز شعبه.",
    "A Spanish dignitary in the Great Schema, the roads of his pilgrimage from Rome to Jerusalem behind him, the Saracen sword before him.": "وجيه إسباني في الإسكيم الكبير، ودروب حجه من رومة إلى أورشليم خلفه، وسيف السراسنة أمامه.",
})

TEXT.update({
    "A Swedish princess become mother of Rus, her sainted son Vladimir beside her, the crowns of France, Hungary, and Norway among her daughters, the nun's habit her final vesture.": "أميرة سويدية صارت أما للروس، وابنها القديس فلاديمير إلى جانبها، وتيجان فرنسا والمجر والنرويج بين بناتها، والثوب الرهباني آخر لباسها.",
    "A Syrian stranger standing three days in prayer in the church of Spoleto, the garden thieves fed at his table and converted, the offered estates refused with a smiling shake of the head.": "غريب سوري يقف ثلاثة أيام في الصلاة في كنيسة سبوليتو، ولصوص البستان يطعمهم على مائدته فيهتدون، والضياع المعروضة يردها بهزة رأس باسمة.",
    "A Tatar captive baptized and tonsured, founding a monastery on the shore of Lake Kozha in the far north, the wilderness hallowed by his prayer.": "أسير تتري اعتمد ولبس الثوب الرهباني، يؤسس ديرا على شاطئ بحيرة كوجا في أقصى الشمال، والبرية تتقدس بصلاته.",
    "A Yup'ik mother in a kuspuk holding a basin and towel, the northern lights above the tundra behind her.": "أم من اليوبيك في ثوب الكوسبوك تحمل مطهرة ومنشفة، وأنوار الشمال فوق التندرا خلفها.",
    "A barefoot ascetic in rags, blessing, at Novgorod.": "ناسك حافي القدمين في أسمال، يبارك، في نوفغورود.",
    "A barefoot fool in tattered clothing by a northern river, giving away what was given to him.": "متباله حافي القدمين في ثياب رثة عند نهر شمالي، يعطي ما أعطي له.",
    "A barefoot fool-for-Christ holding a head of cabbage, at Novgorod by the river.": "متباله بالمسيح حافي القدمين يحمل رأس ملفوف، في نوفغورود عند النهر.",
    "A barefoot fool-for-Christ in a sheepskin holding an axe, by the river defending the city.": "متباله بالمسيح حافي القدمين في فروة يحمل فأسا، عند النهر يدافع عن المدينة.",
    "A barefoot holy fool with long hair, holding a Psalter, of gentle and sorrowful aspect.": "متباله مقدس حافي القدمين طويل الشعر يحمل مزمورا، على وجهه وداعة وحزن.",
    "A basilica at Lydda, the tomb of Saint George within, hierarchs consecrating the church.": "بازيليكا في اللد وفيها قبر القديس جاورجيوس، ورؤساء كهنة يكرسون الكنيسة.",
    "A bearded missionary priest with a traveler's bag, the church of Jackson and the hills of California behind him.": "كاهن مرسل ذو لحية بحقيبة مسافر، وكنيسة جاكسون وتلال كاليفورنيا خلفه.",
    "A beggar beneath the staircase of his father's palace, unknown to all his household, the finished scroll of his life clasped in his dead hand while the emperor and the pope kneel to read it.": "شحاذ تحت سلم قصر أبيه، لا يعرفه أحد من أهل بيته، ودرج سيرته المكتمل مقبوض في يده الميتة بينما الإمبراطور والبابا يركعان ليقرآه.",
    "A bent elder in white on his knees upon the rock, the Theotokos of Tenderness before him, a bear at the edge of the forest clearing.": "شيخ منحن بثوب أبيض راكعا على الصخرة، وأيقونة والدة الإله الحنونة أمامه، ودب عند طرف فسحة الغابة.",
    "A bishop alone in an emptied city awaiting the persecutors, then crucified at Perge, teaching from the cross until his voice failed into glory.": "أسقف وحده في مدينة أخليت ينتظر المضطهدين، ثم مصلوبا في برغي، يعلم من على الصليب حتى انقطع صوته إلى المجد.",
    "A bishop and a presbyter of Persia holding crosses, swords above them.": "أسقف وقس من بلاد فارس يحملان صليبين، والسيوف فوقهما.",
    "A bishop and a virgin holding crosses, broken books of sorcery burning at their feet.": "أسقف وعذراء يحملان صليبين، وكتب السحر المكسورة تحترق عند أقدامهما.",
    "A bishop and his companions holding crosses, cast into a furnace, a soldier among them.": "أسقف ورفاقه يحملون صلبانا، مطروحين في أتون، وبينهم جندي.",
    "A bishop and presbyter cast into a pit, angels crowning them from above.": "أسقف وقس مطروحان في جب، وملائكة تكللهما من فوق.",
    "A bishop and theologian of Lycia with the scroll of his Banquet of the Ten Virgins, refuting the errors of Origen, crowned at the last with martyrdom.": "أسقف ولاهوتي من ليكية بدرج وليمة العذارى العشر، يفند أضاليل أوريجانس، مكللا في الآخر بالشهادة.",
    "A bishop answering the emperor that the Church's questions belong to the Church, the road of exile opening behind him.": "أسقف يجيب الإمبراطور بأن مسائل الكنيسة للكنيسة، وطريق المنفى ينفتح خلفه.",
    "A bishop baptizing an African king, a boy captive and a royal tutor shown in the scenes of his life.": "أسقف يعمد ملكا إفريقيا، وصبي أسير ومؤدب ملكي في مشاهد سيرته.",
    "A bishop barring the church door to an emperor, a beehive at his feet, a scroll of his hymns in hand.": "أسقف يسد باب الكنيسة في وجه إمبراطور، وخلية نحل عند قدميه، ودرج من تسابيحه في يده.",
    "A bishop before a fallen idol, a demon bearing a great stone altar behind him, hot springs at his feet.": "أسقف أمام صنم ساقط، وشيطان يحمل مذبحا حجريا عظيما خلفه، وينابيع حارة عند قدميه.",
    "A bishop before the burning temple of Marnas, the cross-guardian's keys at his belt, the Good Thief descending from the Cross in his vision, the Eudoxiana church rising over pagan Gaza.": "أسقف أمام هيكل مرناس المحترق، ومفاتيح حارس الصليب في منطقته، واللص اليمين ينزل عن الصليب في رؤياه، وكنيسة إفدوكسيانة ترتفع فوق غزة الوثنية.",
    "A bishop before the emperor, pointing to the emperor's son, teaching the honor due the Son of God.": "أسقف أمام الإمبراطور يشير إلى ابن الإمبراطور، يعلم أي كرامة تليق بابن الله.",
    "A bishop beheaded at the altar in mid-Liturgy, twenty-eight years of tribunals and torments ranged behind him like waves, Agathangelus crowned at his side.": "أسقف يقطع رأسه عند المذبح في وسط القداس، وثمانية وعشرون عاما من المحاكم والعذابات مصطفة خلفه كالأمواج، وأغاثانغيلوس مكللا إلى جانبه.",
    "A bishop beholding the ladder to heaven with his predecessor calling from above, one hundred and twenty-eight companions ascending behind him under the Persian sword.": "أسقف يعاين السلم إلى السماء وسلفه يناديه من فوق، ومئة وثمانية وعشرون رفيقا يصعدون خلفه تحت السيف الفارسي.",
    "A bishop by night in a plain cloak, leaving firewood at a poor widow's door, his cathedral of Belgorod behind him.": "أسقف في الليل بعباءة بسيطة يترك حطبا عند باب أرملة فقيرة، وكاتدرائيته في بلغورود خلفه.",
    "A bishop drinking the sorcerer's cup unharmed, the magician kneeling converted beside his cast-down instruments.": "أسقف يشرب كأس الساحر فلا يتأذى، والساحر راكعا قد اهتدى إلى جانب أدواته المطروحة.",
    "A bishop enthroned with a Gospel, the first hierarch of Jerusalem, of ascetic and venerable countenance.": "أسقف على العرش يحمل إنجيلا، أول رؤساء كهنة أورشليم، على وجهه نسك ووقار.",
    "A bishop holding a Gospel, refuting heretics who shrink before his word.": "أسقف يحمل إنجيلا، يفند الهراطقة فينكمشون أمام كلمته.",
    "A bishop holding a page of the alphabet he invented, the sacred birch of the Zyrians felled behind him, the sorcerer Pam turning from the fire and the water, a new people reading the Gospel in its own letters.": "أسقف يحمل صفحة من الأبجدية التي وضعها، وبتولة الزيريان المقدسة مقطوعة خلفه، والساحر بام يرتد عن النار والماء، وشعب جديد يقرأ الإنجيل بحروفه.",
    "A bishop holding a scroll of the Creed, the Theotokos and John the Theologian appearing above, a mountain moved behind.": "أسقف يحمل درج قانون الإيمان، ووالدة الإله ويوحنا اللاهوتي يظهران من فوق، وجبل قد انتقل خلفه.",
    "A bishop holding an icon of Christ against the imperial decree, the sick healed at his hands.": "أسقف يحمل أيقونة المسيح في وجه المرسوم الإمبراطوري، والمرضى يشفون على يديه.",
    "A bishop holding the book of the Divine Names, the darkened sun of the Crucifixion above him.": "أسقف يحمل كتاب الأسماء الإلهية، وشمس الصلب المظلمة فوقه.",
    "A bishop in a laborer's tunic drawing water and hauling wood at Nitria, the omophorion of Damascus folded away, heaven alone reading the monk's true rank.": "أسقف بثوب عامل يستقي الماء ويحمل الحطب في نيتريا، وأومفوريون دمشق مطوي بعيدا، والسماء وحدها تقرأ رتبة الراهب الحقيقية.",
    "A bishop in a mitre holding a crozier, with a gray beard and an ascetic, gentle face.": "أسقف بميطرة يحمل عكازا، بلحية بيضاء ووجه ناسك وديع.",
    "A bishop in monastic poverty, Cernica's island monastery at one hand and the Frasinei he founded at the other, the seminary and the printing press of Ramnic behind him, his face worn bright by fasting.": "أسقف في فقر رهباني، ودير جزيرة تشرنيكا عن يمينه وفراسيني الذي أسسه عن شماله، ومدرسة رمنيك ومطبعتها خلفه، ووجهه قد صقله الصوم.",
    "A bishop in the omophorion and mantle holding a book, of gentle and humble aspect.": "أسقف بالأومفوريون والعباءة يحمل كتابا، على وجهه وداعة وتواضع.",
    "A bishop in the omophorion and sakkos holding a Gospel book, with a Greek-style beard.": "أسقف بالأومفوريون والساكوس يحمل كتاب الإنجيل، بلحية على الطراز اليوناني.",
})

TEXT.update({
    "A bishop in the omophorion blessing the waters at a river confluence, holding a cross.": "أسقف بالأومفوريون يبارك المياه عند ملتقى نهرين، حاملا صليبا.",
    "A bishop in the omophorion blessing, holding a Gospel, before the cathedral of Tambov.": "أسقف بالأومفوريون يبارك حاملا إنجيلا، أمام كاتدرائية تامبوف.",
    "A bishop in the omophorion holding a Gospel book or the scroll of his Great Canon.": "أسقف بالأومفوريون يحمل كتاب الإنجيل أو درج قانونه الكبير.",
    "A bishop in the omophorion holding a Gospel book, a white dove upon his head.": "أسقف بالأومفوريون يحمل كتاب الإنجيل، وحمامة بيضاء على رأسه.",
    "A bishop in the omophorion holding a Gospel, of humble aspect.": "أسقف بالأومفوريون يحمل إنجيلا، على وجهه تواضع.",
    "A bishop in the omophorion holding a Gospel, sometimes with a banner or before a battle.": "أسقف بالأومفوريون يحمل إنجيلا، وأحيانا براية أو أمام معركة.",
    "A bishop in the omophorion holding a Gospel, the cathedral of Saints Cyril and Methodius behind him.": "أسقف بالأومفوريون يحمل إنجيلا، وكاتدرائية القديسين كيرلس ومثوديوس خلفه.",
    "A bishop in the omophorion holding an icon and a Gospel.": "أسقف بالأومفوريون يحمل أيقونة وإنجيلا.",
    "A bishop in the omophorion surrounded by his ten disciples, all crowned as martyrs.": "أسقف بالأومفوريون يحيط به تلاميذه العشرة، وكلهم مكللون شهداء.",
    "A bishop in the omophorion, his hands or face marked by charcoal, holding a Gospel.": "أسقف بالأومفوريون، ويداه أو وجهه موسومان بالفحم، يحمل إنجيلا.",
    "A bishop in the schema and omophorion holding a Gospel, before the city of Voronezh.": "أسقف بالإسكيم والأومفوريون يحمل إنجيلا، أمام مدينة فورونيج.",
    "A bishop in the snows of Siberia, a school of native children beside him, the gates of China closed behind.": "أسقف في ثلوج سيبيريا، ومدرسة لأولاد الأهالي إلى جانبه، وأبواب الصين مغلقة خلفه.",
    "A bishop laying aside his omophorion at the mouth of a desert gorge, the monastery of Choziba in the cliffs.": "أسقف يضع أومفوريونه جانبا عند مدخل واد صحراوي، ودير خوزيبا في الصخور.",
    "A bishop led by an angel from torture to torture and city to city, Sirmium converted behind him and Formia receiving him, the lamps of the sailors burning at his name.": "أسقف يقوده ملاك من عذاب إلى عذاب ومن مدينة إلى مدينة، وسيرميوم قد اهتدت خلفه وفورميا تستقبله، وقناديل البحارة تضيء لاسمه.",
    "A bishop of Aegina laying down his omophorion and returning to the monastic habit, his island see behind him.": "أسقف إيجينا يضع أومفوريونه ويعود إلى الثوب الرهباني، وكرسيه في الجزيرة خلفه.",
    "A bishop of Amasea standing between the hunted virgin and the tyrant's demand, the sea giving back his body in the fishermen's nets, the last crowns of the persecution descending as the peace of the Church dawns.": "أسقف أماسية يقف بين العذراء المطاردة وبين مطلب الطاغية، والبحر يرد جسده في شباك الصيادين، وآخر أكاليل الاضطهاد تنزل مع فجر سلام الكنيسة.",
    "A bishop of Argos measuring out grain that does not diminish, the ransomed captives returning from the sea behind him, his monastic family in Christ around the one see he consented to hold.": "أسقف أرغوس يكيل قمحا لا ينقص، والأسرى المفتدون عائدون من البحر خلفه، وأسرته في المسيح حول الكرسي الوحيد الذي رضي أن يحمله.",
    "A bishop of Benevento unharmed in the furnace, the beasts of the arena lying at his feet, Naples receiving his body and his blood, his deacons and companions crowned around him.": "أسقف بنيفنتو سالما في الأتون، ووحوش الحلبة رابضة عند قدميه، ونابولي تتقبل جسده ودمه، وشمامسته ورفاقه مكللون حوله.",
    "A bishop of Bithynia holding the icon of Christ and the open Scriptures together, the road of exile behind him.": "أسقف بيثينية يحمل أيقونة المسيح والكتب المقدسة المفتوحة معا، وطريق المنفى خلفه.",
    "A bishop of Bithynia on the road of exile, his cathedral behind him and the icon of Christ unsurrendered before him.": "أسقف بيثينية على طريق المنفى، وكاتدرائيته خلفه وأيقونة المسيح غير المسلمة أمامه.",
    "A bishop of Brooklyn with the map of a continent behind him, thirty parishes rising from immigrant streets, The Word in his hand, Tikhon of Moscow laying hands upon the first-consecrated of America.": "أسقف بروكلين وخريطة قارة خلفه، وثلاثون رعية تنهض من شوارع المهاجرين، ومجلة الكلمة في يده، وتيخون الموسكوفي يضع يديه على أول مرسوم في أميركا.",
    "A bishop of Catania in exile for the holy images, the icon of Christ held fast against the imperial decree.": "أسقف كاتانيا في المنفى لأجل الصور المقدسة، وأيقونة المسيح ممسوكة بشدة في وجه المرسوم الإمبراطوري.",
    "A bishop of Chalcedon and his fellow ascetic standing together for the icons, the see of the Fourth Council refusing the new heresy, exile shared as the cell had been.": "أسقف خلقيدونية ورفيقه في النسك واقفان معا لأجل الأيقونات، وكرسي المجمع الرابع يأبى الهرطقة الجديدة، والمنفى مشترك كما كانت القلاية.",
    "A bishop of Chalcedon defending the holy icons, his hand open to the poor, the exile that crowned his confession before him.": "أسقف خلقيدونية يدافع عن الأيقونات المقدسة، ويده مبسوطة للفقراء، والمنفى الذي كلل اعترافه أمامه.",
    "A bishop of Corinth falsely accused, the newborn infant speaking at his prayer to name its true father, the slander confounded and the saint vindicated.": "أسقف كورنثوس متهما بالباطل، والرضيع المولود ينطق عند صلاته فيسمي أباه الحقيقي، والافتراء مخزيا والقديس مبرأ.",
    "A bishop of Cyprus blessing a dry vine-branch that bears fruit before its time, the poor fed at his hand, the idols of the island cast down.": "أسقف قبرص يبارك غصن كرمة يابسا فيثمر قبل أوانه، والفقراء يطعمون من يده، وأصنام الجزيرة مطروحة.",
    "A bishop of Cyprus crowned with martyrdom, his myrrh-streaming relics borne across the sea to Constantinople, the sick healed at his shrine.": "أسقف قبرص مكللا بالشهادة، ورفاته الفائضة طيبا محمولة عبر البحر إلى القسطنطينية، والمرضى يشفون عند ضريحه.",
    "A bishop of Cyprus with the nails of his torture, teaching the faithful gathered at what he thought his end, the edict of Constantine opening his prison to a few more years of shepherding.": "أسقف قبرص ومسامير عذابه، يعلم المؤمنين المجتمعين عند ما ظنه نهايته، ومرسوم قسطنطين يفتح سجنه لسنوات أخرى من الرعاية.",
    "A bishop of Epirus striking down the great serpent at the poisoned spring, the rain descending on the parched fields at his prayer, a dead man rising from the bier to witness against the false creditor.": "أسقف إبيروس يقتل الحية العظيمة عند النبع المسموم، والمطر ينزل على الحقول العطشى عند صلاته، وميت ينهض عن النعش ليشهد على الدائن الكاذب.",
    "A bishop of Melitene serene under the torturers, the emperor's own order opening his prison, the confessor's crown worn through years of peace.": "أسقف ملطية هادئا تحت المعذبين، وأمر الإمبراطور نفسه يفتح سجنه، وإكليل المعترف يلبسه سنين من السلام.",
    "A bishop of Novgorod standing alone against an uncanonical council, the Caves that formed him receiving him in confinement and in death, Theodosius appearing to welcome him home.": "أسقف نوفغورود يقف وحده في وجه مجمع غير قانوني، والمغاور التي ربته تتقبله في الحبس وفي الموت، وثيودوسيوس يظهر ليرحب به في بيته.",
    "A bishop of Pergamum standing where Satan's throne was, the brazen bull glowing behind him, the open Apocalypse naming him the faithful witness in the Lord's own voice.": "أسقف برغامس يقف حيث كان عرش الشيطان، والثور النحاسي متوهج خلفه، والرؤيا المفتوحة تسميه الشاهد الأمين بفم الرب نفسه.",
    "A bishop of Perm baptizing the peoples of the far north, the idols of the Permians thrown down and the churches rising, the mission of Saint Stephen carried onward.": "أسقف بيرم يعمد شعوب أقصى الشمال، وأصنام البرميين مطروحة والكنائس قائمة، ورسالة القديس ستيفانوس ماضية إلى الأمام.",
    "A bishop of Persia with staff of prophecy, a ruined city behind him, two disciples at his side.": "أسقف من بلاد فارس بعصا النبوة، ومدينة خربة خلفه، وتلميذان إلى جانبه.",
    "A bishop of Pisidian Antioch refusing the iconoclast decree, the icons standing in his churches while he goes into exile, the confessor's crown replacing the surrendered see.": "أسقف أنطاكية البيسيدية يأبى المرسوم المحطم للأيقونات، والأيقونات قائمة في كنائسه وهو ماض إلى المنفى، وإكليل المعترف يحل محل الكرسي المتروك.",
    "A bishop of Prusa destroying a great serpent by the sign of the Cross, preaching Christ under Julian the Apostate, crowned with martyrdom by the sword.": "أسقف بروسة يقتل حية عظيمة بإشارة الصليب، يبشر بالمسيح في زمن يوليانوس الجاحد، مكللا بالشهادة بالسيف.",
    "A bishop of Prusa standing unharmed in the boiling spring, preaching the God who made both the healing waters and the fire of hell, his three presbyters crowned beside him.": "أسقف بروسة واقفا سالما في الينبوع المغلي، يبشر بالإله الذي صنع مياه الشفاء ونار الجحيم معا، وقسوسه الثلاثة مكللون إلى جانبه.",
    "A bishop of Rome in the omophorion holding a Gospel, with a martyr's palm.": "أسقف رومة بالأومفوريون يحمل إنجيلا، وبيده سعف الشهادة.",
    "A bishop of Rome of the age of the martyrs, shepherding his flock in the catacombs, bringing the noble and the humble alike to the faith of Christ.": "أسقف رومة في زمن الشهداء، يرعى قطيعه في السراديب، ويقود الشريف والوضيع معا إلى إيمان المسيح.",
    "A bishop of Rostov preaching Christ to the half-pagan land, the idols thrown down and the churches rising, the grace of wonders confirming the word of the Caves-trained shepherd.": "أسقف روستوف يبشر بالمسيح في أرض نصف وثنية، والأصنام مطروحة والكنائس قائمة، ونعمة العجائب تصدق كلمة الراعي الذي ربته المغاور.",
})

TEXT.update({
    "A bishop of Rostov whose very funeral became a glorification, wonders flowing from his body before burial, the shepherd of the yoke-time honored as a saint from the hour of his death.": "أسقف روستوف الذي صارت جنازته نفسها تمجيدا، والعجائب تفيض من جسده قبل الدفن، وراعي زمن النير مكرم قديسا منذ ساعة موته.",
    "A bishop of Salamis with the five tongues of his learning and the Panarion of his refutations, the ascetic of the Palestinian desert crowned with the long white rule of Cyprus.": "أسقف سلامينا وألسنته الخمسة في العلم وبانريونه في تفنيد الهرطقات، ناسك برية فلسطين مكللا بحكم طويل أبيض في قبرص.",
    "A bishop of Samosata refusing to surrender the record of the faith though his hand be cut off, traveling in disguise to strengthen the Orthodox, crowned by the tile of an Arian.": "أسقف ساموساطة يأبى تسليم سجل الإيمان ولو قطعت يده، يتنقل متنكرا ليشدد الأرثوذكس، مكللا بآجرة رماها أريوسي.",
    "A bishop of Sardis scourged for Christ, the dry wooden stake stained with his blood taking root and growing into a green tree of healing beside him.": "أسقف سارديس مجلودا لأجل المسيح، والوتد الخشبي اليابس المخضب بدمه يضرب جذورا ويصير شجرة خضراء للشفاء إلى جانبه.",
    "A bishop of Synnada bearing the icons he defended, the courts of caliph and emperor behind him, the exile that crowned his confession before him.": "أسقف سنادا يحمل الأيقونات التي دافع عنها، وبلاطا الخليفة والإمبراطور خلفه، والمنفى الذي كلل اعترافه أمامه.",
    "A bishop of Tver reconciling princes with the Gospel between them, the Zheltikov monastery rising by the river, the Kyiv Caves Paterikon copied out under his hand.": "أسقف تفير يصالح الأمراء والإنجيل بينهم، ودير جيلتيكوف يقوم عند النهر، وباتريكون مغاور كييف منسوخا بيده.",
    "A bishop of Verona with a fishing rod and a line of catechumens for his catch, the Adige rising in flood behind him and standing like a wall at the open doors of his church.": "أسقف فيرونا بصنارة وصف من الموعوظين صيدا له، ونهر الأديجه يفيض خلفه ويقف كالجدار عند أبواب كنيسته المفتوحة.",
    "A bishop of Vladimir with the founding letter of the Caves Paterik in his hand, his friend Polikarp cautioned against vainglory, the Near Caves receiving the author home to the monastery of his heart.": "أسقف فلاديمير ورسالة تأسيس باتريك المغاور في يده، وصديقه بوليكاربوس محذرا من المجد الباطل، والمغاور القريبة تتقبل الكاتب عائدا إلى دير قلبه.",
    "A bishop of ascetic countenance in the omophorion, blessing, his incorrupt relics in a shrine.": "أسقف على وجهه نسك، بالأومفوريون، يبارك، ورفاته غير البالية في ضريح.",
    "A bishop of gentle countenance distributing alms, a schema laid ready beside his omophorion.": "أسقف وديع الوجه يوزع الصدقات، وإسكيم مهيأ إلى جانب أومفوريونه.",
    "A bishop of the Black Sea coast with his city walls behind him, Saracen raiders scattered by his prayer, the northern raiders frozen at his sepulcher until the captives go free.": "أسقف من ساحل البحر الأسود وأسوار مدينته خلفه، وغزاة سراسنة يتبددون بصلاته، وغزاة الشمال متجمدون عند قبره حتى يطلق الأسرى.",
    "A bishop of the Crimean Goths defending the holy icons, consecrated in Orthodox Georgia, sharing the sufferings of his people under the Khazar yoke.": "أسقف قوط القرم يدافع عن الأيقونات المقدسة، مرسوما في جورجيا الأرثوذكسية، مشاركا شعبه آلامه تحت نير الخزر.",
    "A bishop of the Hellespont in chains for the icons, the letters of Theodore the Studite in his hands.": "أسقف الهلسبنت في القيود لأجل الأيقونات، ورسائل ثيودوروس الستوديتي في يديه.",
    "A bishop of the Hellespont on the road again, the iconoclasts' document forever unsigned behind him, the icon of Christ carried from refuge to refuge.": "أسقف الهلسبنت على الطريق من جديد، ووثيقة محطمي الأيقونات غير موقعة إلى الأبد خلفه، وأيقونة المسيح محمولة من ملجأ إلى ملجأ.",
    "A bishop of the Nicene fathers leading the serpent by his staff into the fire, and on the mountain road the ambush of the heretics, the stone of the murderess turned against her until his grave healed her.": "أسقف من آباء نيقية يقود الحية بعصاه إلى النار، وعلى طريق الجبل كمين الهراطقة، وحجر القاتلة يرتد عليها حتى يشفيها قبره.",
    "A bishop of the Siberian frontier among the peoples of the east, the churches and schools of his planting behind him, the lamp of his night prayers burning over Irkutsk.": "أسقف تخوم سيبيريا بين شعوب المشرق، وكنائس ومدارس غرسها خلفه، وقنديل صلواته الليلية يضيء فوق إركوتسك.",
    "A bishop of the apostolic line blessing a bitter spring at Catania, the water running sweet and the city believing.": "أسقف من السلسلة الرسولية يبارك ينبوعا مرا في كاتانيا، فيجري الماء عذبا وتؤمن المدينة.",
    "A bishop ordained by the hand of the Theologian, laying his own hand on the young Polycarp, a myrtle flowering from his tomb.": "أسقف رسم بيد اللاهوتي، يضع يده هو على بوليكاربوس الفتى، وشجرة آس تزهر من قبره.",
    "A bishop rapt in divine song at the funeral of the Theotokos, the apostles around the bier.": "أسقف مخطوف في الترتيل الإلهي عند جنازة والدة الإله، والرسل حول النعش.",
    "A bishop rising from a deep pit, the king with the face of a beast healed before him, a church shown from heaven.": "أسقف ينهض من جب عميق، وملك بوجه وحش قد شفي أمامه، وكنيسة تظهر من السماء.",
    "A bishop sailing upon his mantle across the lake, the city that expelled him kneeling on the shore.": "أسقف يبحر على عباءته عبر البحيرة، والمدينة التي طردته راكعة على الشاطئ.",
    "A bishop scourged with ox-hide thongs, the icon of Christ held fast in his hands through four exiles.": "أسقف مجلود بسيور من جلد الثور، وأيقونة المسيح ممسوكة بشدة في يديه خلال أربعة منافي.",
    "A bishop serene in prison, the false witness healed and confessing, an open book of Ecclesiastes before him.": "أسقف هادئ في السجن، وشاهد الزور قد شفي واعترف، وكتاب الجامعة مفتوح أمامه.",
    "A bishop set upon by schismatics with swords, praying for his murderers as he falls.": "أسقف يهجم عليه المنشقون بالسيوف، يصلي لأجل قاتليه وهو يسقط.",
    "A bishop standing unharmed in the flames with the sorcerer bound in his omophorion, the fire dividing the true wonder from the false before the whole city.": "أسقف واقفا سالما في اللهيب والساحر مربوط في أومفوريونه، والنار تفرز العجيبة الحقة من الكاذبة أمام المدينة كلها.",
    "A bishop standing upon his mantle spread on the waters of the Oka, the Murom icon of the Mother of God in his hands, borne upstream to Ryazan, his innocence proclaimed by the wonder.": "أسقف واقفا على عباءته المبسوطة على مياه الأوكا، وأيقونة موروم لوالدة الإله في يديه، محمولا إلى أعلى النهر إلى ريازان، وبراءته معلنة بالعجيبة.",
    "A bishop struck down at the altar during the Divine Liturgy, angels receiving his soul.": "أسقف يصرع عند المذبح في أثناء القداس الإلهي، وملائكة تتقبل نفسه.",
    "A bishop tried by fire, beasts, and sword, the great company of five hundred forty-six confessors about him, Jerusalem's name upon a martyrdom the whole East shared.": "أسقف مجرب بالنار والوحوش والسيف، وجمع عظيم من خمسمئة وستة وأربعين معترفا حوله، واسم أورشليم على شهادة شاركها المشرق كله.",
    "A bishop upon a pillar with a pen, the paschal sermons streaming from his mouth like light, the prayer book of the faithful open at the prayers he wrote for every day of the week.": "أسقف على عمود بقلم، والعظات الفصحية تنساب من فمه كالنور، وكتاب صلاة المؤمنين مفتوح على الصلوات التي وضعها لكل يوم من الأسبوع.",
    "A bishop vested in the omophorion, with a short rounded beard, holding a Gospel book and blessing.": "أسقف مرتديا الأومفوريون، بلحية قصيرة مستديرة، يحمل كتاب الإنجيل ويبارك.",
    "A bishop washing the wounds of lepers with his own hands, then standing before Leo the Armenian foretelling his swift destruction, the fortress of his thirty-year exile behind him.": "أسقف يغسل قروح البرص بيديه، ثم واقفا أمام لاون الأرمني ينبئ بهلاكه السريع، وقلعة منفاه الثلاثيني خلفه.",
    "A bishop who once wore Tatar chains preaching Christ in the Tatar tongue at Kazan, the Savior monastery rising in the kremlin, the sick of two faiths healed at his prayer.": "أسقف لبس قيود التتر يوما يبشر بالمسيح بلسان التتر في قازان، ودير المخلص يقوم في القلعة، ومرضى الملتين يشفون بصلاته.",
    "A bishop who was a surgeon, the omophorion over his shoulders and the healing of the sick in his hands, the prisons and exiles of his confession behind him, the light of Christ in a godless age.": "أسقف كان جراحا، والأومفوريون على كتفيه وشفاء المرضى في يديه، وسجون اعترافه ومنافيه خلفه، ونور المسيح في زمن بلا إله.",
    "A bishop with a Gospel preaching to the people of Volhynia, a cave monastery in the distance.": "أسقف بإنجيل يبشر شعب فولينيا، ودير مغاور في البعد.",
    "A bishop with a company of one hundred ninety-nine disciples, the sign of the Cross that saved him in battle above, the swords of Sicily gathering the whole school into one harvest.": "أسقف مع جماعة من مئة وتسعة وتسعين تلميذا، وعلامة الصليب التي خلصته في الحرب فوقه، وسيوف صقلية تجمع المدرسة كلها في حصاد واحد.",
    "A bishop with a high domed forehead and short pointed beard, a thin ascetic face, vested in the omophorion and holding a Gospel book.": "أسقف بجبهة عالية مقببة ولحية قصيرة مدببة، ووجه ناسك نحيل، مرتديا الأومفوريون ويحمل كتاب الإنجيل.",
    "A bishop with a lamp, a serpent fleeing before him, the island of Crete behind.": "أسقف بمصباح، وحية تهرب أمامه، وجزيرة كريت خلفه.",
    "A bishop with a long dark tapering beard and high forehead, vested in the omophorion, holding a Gospel book and blessing.": "أسقف بلحية طويلة داكنة مستدقة وجبهة عالية، مرتديا الأومفوريون، يحمل كتاب الإنجيل ويبارك.",
    "A bishop with the Prologue open in his hands, the lake of Ohrid behind one shoulder and the wire of Dachau behind the other, preaching Christ to the peoples in every tongue he knew.": "أسقف والبرولوغ مفتوح في يديه، وبحيرة أوهريد وراء كتف وأسلاك داخاو وراء الكتف الآخر، يبشر بالمسيح للشعوب بكل لسان عرفه.",
    "A bishop with the marks of long warfare, demons fleeing behind him, angels and the Theotokos receiving his soul before him.": "أسقف عليه آثار جهاد طويل، والشياطين تهرب خلفه، والملائكة ووالدة الإله تتقبلان نفسه أمامه.",
})

TEXT.update({
    "A bishop with the paschal fire blazing on the hill of Slane against the high king's darkness, the shamrock of the Trinity in his hand, the tribes of Ireland kneeling to the font.": "أسقف والنار الفصحية مشتعلة على تل سلين في وجه ظلمة الملك الأعلى، وورقة النفل رمز الثالوث في يده، وقبائل إيرلندة راكعة عند جرن المعمودية.",
    "A bishop with verses branded upon his face, holding an icon of Christ and a scroll of canons.": "أسقف وأبيات موسومة على وجهه، يحمل أيقونة المسيح ودرج قوانين.",
    "A bishop writing canons at a desk, the Theotokos appearing to bless him.": "أسقف يكتب قوانين على منضدة، ووالدة الإله تظهر لتباركه.",
    "A bishop's omophorion hidden beneath a novice's habit, an aged hesychast silent in his cell at the Lavra.": "أومفوريون أسقف مخفي تحت ثوب مبتدئ، وشيخ هدوئي طاعن في السن صامت في قلايته في اللافرا.",
    "A bishop, a deacon, a servant, and a holy woman crowned together amid flames at Pergamum.": "أسقف وشماس وخادم وامرأة مقدسة مكللون معا وسط اللهيب في برغامس.",
    "A bishop-ascetic in chains beneath an iron cage, Saint George leading him from childhood as a companion, the possessed freed and the storms stilled at his prayer, the resigned omophorion folded beside the hermit's cave.": "أسقف ناسك في القيود تحت قفص من حديد، والقديس جاورجيوس يقوده من طفولته رفيقا، والمجانين محررين والعواصف ساكنة بصلاته، والأومفوريون المتروك مطوي إلى جانب مغارة الناسك.",
    "A bishop-confessor bearing the marks of his wounds, holding a Gospel.": "أسقف معترف عليه آثار جراحه، يحمل إنجيلا.",
    "A bishop-envoy on the road between empires, gifts flowing through his hands to the poor of his city.": "أسقف سفير على الطريق بين إمبراطوريتين، والهدايا تجري من يديه إلى فقراء مدينته.",
    "A bishop-martyr barring an emperor from the church doors, three youths and their mother beside him.": "أسقف شهيد يمنع إمبراطورا من أبواب الكنيسة، وثلاثة فتيان وأمهم إلى جانبه.",
    "A bishop-martyr by the sea, ships in the distance, flames beneath his feet trampled down.": "أسقف شهيد عند البحر، وسفن في البعد، ولهيب تحت قدميه مدوس.",
    "A bishop-martyr holding a Gospel, a lion at his feet praising God.": "أسقف شهيد يحمل إنجيلا، وأسد عند قدميه يسبح الله.",
    "A bishop-martyr in the omophorion holding a Gospel and a cross.": "أسقف شهيد بالأومفوريون يحمل إنجيلا وصليبا.",
    "A bishop-martyr in the omophorion holding a Gospel or a scroll inscribed against heresy.": "أسقف شهيد بالأومفوريون يحمل إنجيلا أو درجا مكتوبا ضد الهرطقة.",
    "A bishop-martyr in the omophorion holding a Gospel or a scroll on the unity of the Church.": "أسقف شهيد بالأومفوريون يحمل إنجيلا أو درجا في وحدة الكنيسة.",
    "A bishop-martyr in the omophorion holding a Gospel, a burning church in the background.": "أسقف شهيد بالأومفوريون يحمل إنجيلا، وكنيسة محترقة في الخلفية.",
    "A bishop-martyr in the omophorion holding a Gospel, sometimes with a ship or flames.": "أسقف شهيد بالأومفوريون يحمل إنجيلا، وأحيانا بسفينة أو لهيب.",
    "A bishop-martyr in the omophorion holding a Gospel, with his three companions and tamed beasts.": "أسقف شهيد بالأومفوريون يحمل إنجيلا، مع رفاقه الثلاثة ووحوش مروضة.",
    "A bishop-martyr with a soldier and four women, all crowned together.": "أسقف شهيد مع جندي وأربع نساء، مكللين جميعا معا.",
    "A bishop-martyr with a young nun and two servants, holding crosses.": "أسقف شهيد مع راهبة شابة وخادمتين، يحملون صلبانا.",
    "A bishop-physician and his sister holding crosses, his hands extended in healing.": "أسقف طبيب وأخته يحملان صليبين، ويداه ممدودتان للشفاء.",
    "A bishop-physician at the Persian court, the king healed and the hidden trickster unearthed from beneath the temple floor, caravans of martyrs' relics entering the city of his name.": "أسقف طبيب في بلاط الفرس، والملك قد شفي والمحتال المستور مستخرج من تحت أرض الهيكل، وقوافل رفات الشهداء تدخل المدينة التي تحمل اسمه.",
    "A bishop-physician in a mountain cave with the wild beasts gathered gently around him, a child healed of a choking bone, seven women and two children crowned beside him.": "أسقف طبيب في مغارة جبلية والوحوش مجتمعة حوله في وداعة، وطفل قد شفي من عظم اختنق به، وسبع نساء وطفلان مكللون إلى جانبه.",
    "A blind eldress seated small and radiant in a Moscow room, the lines of the troubled stretching through the Soviet dark to her door, her closed eyes seeing all of it in God.": "شيخة عمياء جالسة صغيرة مشرقة في غرفة بموسكو، وصفوف المتضايقين تمتد عبر ظلمة السوفييت إلى بابها، وعيناها المغمضتان تريان ذلك كله في الله.",
    "A boy bishop-to-be praying before an emptied granary as it fills again, coins and wine multiplying in his open hands.": "صبي سيصير أسقفا يصلي أمام أهراء فرغت فتمتلئ من جديد، والنقود والخمر تتكاثر في يديه المبسوطتين.",
    "A boy confessing Christ with his tutor Modestus and nurse Crescentia beside him, the cauldron and the beasts before them, the child and his guardians crowned together.": "صبي يعترف بالمسيح ومؤدبه موديستوس ومرضعته كريسكنتيا إلى جانبه، والمرجل والوحوش أمامهم، والطفل وحارساه مكللون معا.",
    "A boy in peasant dress with a harrow, lightning above, angels receiving his soul.": "صبي بثياب فلاح ومعه مشط الحراثة، وبرق فوقه، وملائكة تتقبل نفسه.",
    "A boy martyr with a white dove above him, water springing from the rock at his prayer, the lion of his mountain cave refusing to harm him in the arena.": "صبي شهيد وحمامة بيضاء فوقه، وماء ينبع من الصخر عند صلاته، وأسد مغارته الجبلية يأبى أن يؤذيه في الحلبة.",
    "A boy prince in royal robes bearing the palm of the passion-bearer, the yard of Uglich behind him where he fell, his incorrupt relics enshrined in the Kremlin to confound the pretenders.": "أمير صبي في حلة ملكية يحمل سعف حامل الآلام، وساحة أوغليتش خلفه حيث سقط، ورفاته غير البالية في ضريح بالكرملين تخزي المدعين.",
    "A bread merchant with pierced hands and feet, walking his last steps for Christ.": "تاجر خبز مثقوب اليدين والقدمين، يمشي خطواته الأخيرة لأجل المسيح.",
    "A bridegroom and bride in virginal crowns, the lion guarding Daria's honor, the tribune Claudius converted with his whole house, the sand pit of the Via Salaria closing over the two alive.": "عريس وعروس بإكليلي بتولية، والأسد يحرس شرف داريا، والقائد كلافديوس يهتدي مع بيته كله، وحفرة الرمل في طريق سالاريا تنطبق على الاثنين حيين.",
    "A brother and sister crowned as martyrs, holding crosses and palms.": "أخ وأخت مكللان شهيدين، يحملان صلبانا وسعفا.",
    "A brother and sister martyrs, he upon a tree, she with a spear, both crowned.": "أخ وأخت شهيدان، هو على شجرة وهي بحربة، وكلاهما مكلل.",
    "A canonarch of the Far Caves directing the chanting of the brethren, the book of the services in his hand, the monastic life embraced from his childhood.": "قانونرخس المغاور البعيدة يقود ترتيل الإخوة، وكتاب الخدم في يده، والحياة الرهبانية معتنقة منذ طفولته.",
    "A captain of the guard bound to a tree and shot with arrows, the widow Irene tending him, his converted companions with their crowns around him.": "قائد الحرس مربوطا إلى شجرة ومرشوقا بالسهام، والأرملة إيريني تعتني به، ورفاقه الذين اهتدوا بأكاليلهم حوله.",
    "A cathedral in flames on the night of the Nativity, the bishop baptizing and communing the multitude within, twenty thousand crowns rising in the smoke.": "كاتدرائية في اللهيب ليلة الميلاد، والأسقف يعمد الجمع ويناوله في داخلها، وعشرون ألف إكليل تصعد في الدخان.",
    "A centurion striding from the desert into the crowded amphitheater, proclaiming Christ before the astonished city.": "قائد مئة يخرج من البرية إلى المدرج المزدحم، معلنا المسيح أمام المدينة المذهولة.",
    "A centurion with spear at the foot of the Cross, his eyes lifted to the Crucified, confessing.": "قائد مئة بحربة عند أسفل الصليب، عيناه مرفوعتان إلى المصلوب، معترفا.",
    "A church at Nicopolis in Armenia": "كنيسة في نيقوبوليس بأرمينية",
    "A church built over his grave at Skepsis": "كنيسة بنيت على قبره في سكيبسيس",
    "A church in her honor at Chalcedon by 450": "كنيسة على اسمها في خلقيدونية قبل سنة 450",
})

TEXT.update({
    "A church in his honor at Constantinople": "كنيسة على اسمه في القسطنطينية",
    "A church sexton in poor clothing, a princely ring and gold chain revealed beside his coffin.": "سادن كنيسة بثياب فقيرة، وخاتم أميري وسلسلة ذهب تظهر إلى جانب نعشه.",
    "A church was later raised over their burial place": "أقيمت كنيسة فيما بعد على موضع دفنهم",
    "A church was raised over their grave by Saint John Chrysostom": "أقام القديس يوحنا الذهبي الفم كنيسة على قبرهم",
    "A clergyman of Hagia Sophia radiant in his enclosed cell, a lamp newly kindled in the great city.": "إكليريكي من آيا صوفيا مشرقا في قلايته المغلقة، قنديل أوقد حديثا في المدينة العظمى.",
    "A commander and his son with seventy soldiers, bound to the trees of the marsh, the ten-day martyrdom of the smallest executioners, seventy-two crowns over the swamp.": "قائد وابنه مع سبعين جنديا، مربوطين إلى أشجار المستنقع، وعشرة أيام من استشهاد بأصغر الجلادين، واثنان وسبعون إكليلا فوق المستنقع.",
    "A company of martyrs holding crosses amid flames.": "جماعة من الشهداء يحملون صلبانا وسط اللهيب.",
    "A company of martyrs with hands raised amid flames, an angel above bearing crowns.": "جماعة من الشهداء رافعي الأيدي وسط اللهيب، وملاك فوقهم يحمل أكاليل.",
    "A company of monks bearing icons and the marks of mutilation, crowned together after their father Stephen.": "جماعة من الرهبان يحملون أيقونات وعليهم آثار التمثيل، مكللين معا في إثر أبيهم ستيفانوس.",
    "A company of one hundred twenty captives of Persia, nine consecrated virgins among them, refusing the worship of fire and sun, one crown descending in a hundred twenty parts.": "جماعة من مئة وعشرين أسيرا في بلاد فارس، بينهم تسع عذارى مكرسات، يأبون السجود للنار والشمس، وإكليل واحد ينزل في مئة وعشرين جزءا.",
    "A company of soldier-martyrs of Sebaste laying down their military belts, fire and sword behind them.": "جماعة من الشهداء الجنود في سبسطية يضعون مناطق جنديتهم، والنار والسيف خلفهم.",
    "A company of virgin-martyrs led by two, crowned, the churches of Etchmiadzin behind them.": "جماعة من الشهيدات العذارى تقودهما اثنتان، مكللات، وكنائس إتشميادزين خلفهن.",
    "A convert of Britain in the priest's cloak giving himself up in the priest's place, led to the hill above the city, the first martyr of the land crowned by the sword.": "مهتد من بريطانيا في عباءة الكاهن يسلم نفسه مكان الكاهن، مقادا إلى التل فوق المدينة، أول شهداء الأرض مكللا بالسيف.",
    "A court official in fine dress holding a cross, a small church beside him.": "موظف بلاط بثياب فاخرة يحمل صليبا، وكنيسة صغيرة إلى جانبه.",
    "A courtier and his bride exchanging rings for monastic crowns, the Chronography open on his desk, the prison of Leo the Armenian and the island of his exile behind.": "رجل بلاط وعروسه يستبدلان الخاتمين بإكليلي الرهبنة، والكرونوغرافيا مفتوحة على مكتبه، وسجن لاون الأرمني وجزيرة منفاه خلفهما.",
    "A courtier casting his belt and mantle at the emperor's feet, declaring himself a soldier of the Heavenly King, the cage of fire receiving him.": "رجل بلاط يطرح منطقته وعباءته عند قدمي الإمبراطور، معلنا أنه جندي للملك السماوي، وقفص النار يتقبله.",
    "A courtier of Maximian with his mother's letter open in his hands, the denied Christ confessed again, the sword of Nicomedia completing his repentance.": "رجل من بلاط مكسيميانوس ورسالة أمه مفتوحة في يديه، والمسيح المنكور معترفا به من جديد، وسيف نيقوميذية يتم توبته.",
    "A courtier with a prince and princess of Persia, all three holding crosses.": "رجل بلاط مع أمير وأميرة من فارس، وثلاثتهم يحملون صلبانا.",
    "A courtier-martyr before the emperor, a multitude of crucified soldiers behind him.": "رجل بلاط شهيد أمام الإمبراطور، وجمع من الجنود المصلوبين خلفه.",
    "A crowned king with harp and scroll of the Psalms, the shepherd's sling at his feet, the Son of David foreshown above his throne.": "ملك متوج بقيثارة ودرج المزامير، ومقلاع الراعي عند قدميه، وابن داود مرموزا إليه فوق عرشه.",
    "A crowned prince in royal robes holding a cross and a church, with a long beard.": "أمير متوج في حلة ملكية يحمل صليبا وكنيسة، بلحية طويلة.",
    "A crowned prince in royal robes holding a model of a church, and sometimes a sword or cross.": "أمير متوج في حلة ملكية يحمل مجسم كنيسة، وأحيانا سيفا أو صليبا.",
    "A crowned princess in royal robes holding a cross and a model of a church.": "أميرة متوجة في حلة ملكية تحمل صليبا ومجسم كنيسة.",
    "A dark-skinned monk-priest in the schema, of humble and peaceful aspect, holding a scroll.": "راهب كاهن أسمر البشرة في الإسكيم، على وجهه تواضع وسلام، يحمل درجا.",
    "A deacon and his jailer bound in one net above the Danube, the third-day promise shining over the water.": "شماس وسجانه مربوطان في شبكة واحدة فوق الدانوب، ووعد اليوم الثالث يشرق فوق الماء.",
    "A deacon baptizing the Ethiopian eunuch beside a chariot on the desert road.": "شماس يعمد خصي الحبشة إلى جانب مركبة على طريق البرية.",
    "A deacon in a sticharion holding the Gospel book, sometimes with the book hung about his neck.": "شماس في الستيخارية يحمل كتاب الإنجيل، وأحيانا والكتاب معلق في عنقه.",
    "A deacon of Heliopolis given to the mob under Julian, the broken idols of his youth held against him, the crowns descending on him and the martyrs of Gaza and Ascalon.": "شماس من هليوبوليس مسلما إلى الغوغاء في زمن يوليانوس، وأصنام صباه المكسورة محسوبة عليه، والأكاليل تنزل عليه وعلى شهداء غزة وعسقلان.",
    "A deacon of Rome confessing Christ in chains, his fellow-martyrs and the princess Artemia gathered about him, the crown of the Roman confessors descending.": "شماس من رومة يعترف بالمسيح في القيود، ورفاقه الشهداء والأميرة أرطاميا مجتمعون حوله، وإكليل المعترفين الرومان ينزل.",
    "A deacon of the Near Caves at his fast, the lamp of the Egyptian Macarius shining upon his namesake's exploit.": "شماس المغاور القريبة في صومه، وقنديل مكاريوس المصري يضيء على جهاد سميه.",
    "A deacon of the Near Caves with censer and lifted hands, every petition granted, the martyr's crown above his diaconal orarion.": "شماس المغاور القريبة بمبخرة ويدين مرفوعتين، وكل طلبة مستجابة، وإكليل الشهادة فوق بطرشيله الشماسي.",
    "A deacon of the caves standing at prayer on the ambo, demons fleeing from the sick brought to him.": "شماس المغاور واقفا في الصلاة على المنبر، والشياطين تهرب عن المرضى الذين يحملون إليه.",
    "A deacon of the first seven with the vessels of service, the stones of Stephen's day falling upon the whole company.": "شماس من السبعة الأولين بآنية الخدمة، وحجارة يوم إسطفانوس تقع على الجماعة كلها.",
    "A deacon on the ambo with a scroll, the Theotokos above giving him the scroll to eat.": "شماس على المنبر بدرج، ووالدة الإله من فوق تعطيه الدرج ليأكله.",
    "A deacon upon a gridiron, angels filling his prison with light.": "شماس على مشواة، وملائكة تملأ سجنه نورا.",
    "A deacon with severed tongue still praising God, a child-martyr beside him, a prison rope above.": "شماس مقطوع اللسان وهو بعد يسبح الله، وطفل شهيد إلى جانبه، وحبل السجن فوقه.",
    "A deacon with the harp of hymnody, tears on his face and the Lenten prayer on his scroll, the schools of Nisibis and Edessa singing behind him.": "شماس بقيثارة التسبيح، والدموع على وجهه وصلاة الصوم على درجه، ومدرستا نصيبين والرها ترتلان خلفه.",
    "A deacon-bishop standing unharmed in a red-hot furnace, the crown descending upon him through the flames.": "شماس أسقف واقفا سالما في أتون محمى، والإكليل ينزل عليه من خلال اللهيب.",
    "A deacon-martyr in the sticharion holding a censer and a cross, stones at his feet.": "شماس شهيد في الستيخارية يحمل مبخرة وصليبا، وحجارة عند قدميه.",
    "A deaconess in a maphorion holding a scroll, sometimes shown with Saint John Chrysostom.": "شماسة في المافوريون تحمل درجا، وتصور أحيانا مع القديس يوحنا الذهبي الفم.",
})
