# -*- coding: utf-8 -*-
"""German for the vocabulary that stands beside the lives.

TEXT = {the phrase the index shows: the German}. PARTS holds the pieces the
compound place-names are built from, and expand() assembles the wholes, so a
town cannot be spelled one way on one card and another way on the next.

The rank vocabulary was settled before any of this was written, and is set
down in docs/GERMAN.md. German is not a Slavonic tongue and does not require
a rank before a name: der heilige Nikolaus is ordinary German. But it keeps
one distinction that the Western churches around it do not, and that
distinction is asserted everywhere here: the monastic saint is ehrwuerdig,
never merely heilig.

The trap in this language is not a neighbouring alphabet but the Western
church vocabulary standing ready for every word. Kirchenvater and not
Kirchenlehrer, which is a Roman category with a list. Entschlafung and not
Himmelfahrt Mariens, which is a Roman dogma of 1950 and a different claim.
Goettliche Liturgie and not Messe. Gottesgebaererin where the Theotokos is
named as such, because that is what the Council of Ephesus said. Ikone and
not Heiligenbild.

The site writes ss and never the sharp s, because these pages are read in
Switzerland as well as in Germany and Austria and Grossmaertyrer is right in
all three. Umlauts are written as umlauts.

The keys are the phrases exactly as the index writes them, so a rendering
cannot quietly attach itself to the wrong saint.
"""
TEXT = {}


# The orders of sanctity, as the badge on a card names them.
TEXT.update({
    "Angelic": "Himmlische Mächte",
    "Apostle": "Apostel",
    "Confessor": "Bekenner",
    "Equal-to-the-Apostles": "Apostelgleicher",
    "Feast": "Fest",
    "Fool-for-Christ": "Narr um Christi willen",
    "Great Martyr": "Grossmärtyrer",
    "Hierarch": "Hierarch",
    "Hieromartyr": "Priestermärtyrer",
    "Martyr": "Märtyrer",
    "Monastic": "Mönch oder Nonne",
    "New Martyr": "Neumärtyrer",
    "Other": "Weitere",
    "Passion-bearer": "Passionsträger",
    "Prophet": "Prophet",
    "Righteous": "Gerechter",
    "Unmercenary": "Uneigennütziger",
    "Virgin Martyr": "Jungfrau und Märtyrerin",
})


# The attributes a life is marked with.
TEXT.update({
    "Church Father": "Kirchenvater",
    "Desert ascetic": "Wüstenasket",
    "Enlightener": "Erleuchter",
    "Healing intercessor": "Helfer der Kranken",
    "Hymnographer": "Hymnendichter",
    "Iconographer": "Ikonenmaler",
    "Incorrupt relics": "Unverweste Reliquien",
    "Monastery founder": "Klostergründer",
    "Myrrh-bearer": "Myrrhenträgerin",
    "Myrrh-streaming": "Myrrhenströmend",
    "New martyr": "Neumärtyrer",
    "Ruler or royal": "Herrscher oder Königshaus",
    "Stylite": "Stylit",
    "Warrior saint": "Kriegerheiliger",
    "Wonderworker": "Wundertäter",
})


# The ranks the Typikon gives a feast.
TEXT.update({
    "Doxology": "Doxologie",
    "Great Feast": "Hochfest",
    "Polyeleos": "Polyeleos",
    "Simple": "Einfach",
    "Vigil": "Vigil",
})


# The jurisdictions whose calendars the index keeps.
TEXT.update({
    "Antiochian": "Antiochenisch",
    "Greek": "Griechisch",
    "OCA": "OCA",
    "Romanian": "Rumänisch",
    "Russian": "Russisch",
    "Serbian": "Serbisch",
    "Ukrainian": "Ukrainisch",
})


# The estate a saint stood in.
TEXT.update({
    "Apostolic": "Apostolisch",
    "Clergy": "Klerus",
    "Laity": "Laien",
    "Layman": "Laie",
    "Laywoman": "Laiin",
    "Laywomen": "Laiinnen",
    "Married": "Verheiratet",
    "Military": "Soldat",
    "Monastic": "Mönchtum",
    "Prophet": "Prophet",
    "Royal": "Königlich",
    "Royalty": "Königshaus",
    "Unknown": "Unbekannt",
    "Unmarried": "Unverheiratet",
    "Widowed": "Verwitwet",
})


# The ages the lives are set in.
TEXT.update({
    "Age of the Celtic Saints": "Zeit der keltischen Heiligen",
    "Age of the Ecumenical Councils": "Zeit der Ökumenischen Konzilien",
    "Age of the Martyrs": "Zeit der Märtyrer",
    "Apostolic Age": "Apostolische Zeit",
    "Byzantine": "Byzantinisch",
    "Byzantine Balkans": "Byzantinischer Balkan",
    "Byzantine Era": "Byzantinische Zeit",
    "Byzantine Iconoclasm": "Byzantinischer Bilderstreit",
    "Cossack Era": "Kosakenzeit",
    "Desert Fathers": "Wüstenväter",
    "Early Medieval West": "Frühmittelalterlicher Westen",
    "Imperial Russia": "Kaiserliches Russland",
    "Kievan Rus'": "Kiewer Rus",
    "Medieval Georgia": "Mittelalterliches Georgien",
    "Medieval Rus'": "Mittelalterliche Rus",
    "Medieval Serbia": "Mittelalterliches Serbien",
    "Modern": "Neuzeit",
    "Modern Era": "Neuzeit",
    "Muscovite Russia": "Moskauer Russland",
    "Old Testament": "Altes Testament",
    "Ottoman Balkans": "Osmanischer Balkan",
    "Ottoman Era": "Osmanische Zeit",
    "Ottoman period": "Osmanische Zeit",
    "Polish-Lithuanian period": "Polnisch-litauische Zeit",
    "Soviet Era": "Sowjetzeit",
    "Soviet period": "Sowjetzeit",
    "Synodal Russia": "Synodales Russland",
})


# The one movable commemoration the index names.
TEXT.update({
    "Sunday of the Holy Forefathers": "Sonntag der heiligen Altväter",
})


# The countries and the regions.
TEXT.update({
    "Aegean": "Ägäis",
    "America": "Amerika",
    "Arabia": "Arabien",
    "Armenia": "Armenien",
    "Asia Minor": "Kleinasien",
    "Balkans": "Balkan",
    "Belarus": "Weissrussland",
    "Bithynia": "Bithynien",
    "Britain": "Britannien",
    "British Isles": "Britische Inseln",
    "Bulgaria": "Bulgarien",
    "Cappadocia": "Kappadokien",
    "Cilicia": "Kilikien",
    "Constantinople": "Konstantinopel",
    "Crimea": "Krim",
    "Cyprus": "Zypern",
    "Czech Lands": "Böhmische Länder",
    "Dalmatia": "Dalmatien",
    "Danube lands": "Donauländer",
    "Egypt": "Ägypten",
    "England": "England",
    "Ethiopia": "Äthiopien",
    "Gaul": "Gallien",
    "Georgia": "Georgien",
    "Greece": "Griechenland",
    "Holy Land": "Heiliges Land",
    "Illyria": "Illyrien",
    "Illyricum": "Illyricum",
    "India": "Indien",
    "Ireland": "Irland",
    "Italy": "Italien",
    "Lithuania": "Litauen",
    "Macedonia": "Makedonien",
    "Mesopotamia": "Mesopotamien",
    "Moldavia": "Moldau",
    "Montenegro": "Montenegro",
    "Moravia": "Mähren",
    "Mount Athos": "Berg Athos",
    "North Africa": "Nordafrika",
    "North America": "Nordamerika",
    "North Macedonia": "Nordmazedonien",
    "Palestine": "Palästina",
    "Persia": "Persien",
    "Phoenicia": "Phönizien",
    "Poland": "Polen",
    "Pontus": "Pontos",
    "Romania": "Rumänien",
    "Rome": "Rom",
    "Russia": "Russland",
    "Scythia": "Skythien",
    "Serbia": "Serbien",
    "Siberia": "Sibirien",
    "Sinai": "Sinai",
    "Spain": "Spanien",
    "Syria": "Syrien",
    "Thrace": "Thrakien",
    "Ukraine": "Ukraine",
    "Western Rus": "Westliche Rus",
})


# The lands the fasting rule is kept in.
TEXT.update({
    "Albania": "Albanien",
    "Bohemia": "Böhmen",
    "China": "China",
    "France": "Frankreich",
    "Judah": "Juda",
    "Moesia": "Mösien",
    "Sicily": "Sizilien",
    "United States": "Vereinigte Staaten",
})


# The rank a saint held, as the menaia name it. The monastic is ehrwuerdig
# throughout, which is the one distinction German Orthodox usage keeps and
# the Western churches do not; see docs/GERMAN.md.
TEXT.update({
    "Abbess": "Äbtissin",
    "Abbot (Archimandrite)": "Abt (Archimandrit)",
    "Abbot (Founder)": "Abt (Gründer)",
    "Abbot (Igumen)": "Abt (Igumen)",
    "Abbot (Igumen), Confessor": "Abt (Igumen), Bekenner",
    "Abbot (Igumen), Hieromartyr": "Abt (Igumen), Priestermärtyrer",
    "Abbot (Igumen), Martyr": "Abt (Igumen), Märtyrer",
    "Abbot (Igumen), Monastic Martyr": "Abt (Igumen), Mönchsmärtyrer",
    "Abbot, Confessor": "Abt, Bekenner",
    "Abbot, Confessor-Martyr": "Abt, Bekenner und Märtyrer",
    "Abbot, Priest": "Abt, Priester",
    "Abbots": "Äbte",
    "Anchorite": "Anachoret",
    "Apostle of the Seventy": "Apostel der Siebzig",
    "Apostle of the Seventy, Bishop": "Apostel der Siebzig, Bischof",
    "Apostle of the Seventy, Martyr": "Apostel der Siebzig, Märtyrer",
    "Apostle, Evangelist": "Apostel und Evangelist",
    "Apostle, Martyr": "Apostel und Märtyrer",
    "Apostles": "Apostel",
    "Apostles of the Seventy": "Apostel der Siebzig",
    "Apostles of the Seventy, Martyrs": "Apostel der Siebzig, Märtyrer",
    "Archangel": "Erzengel",
    "Archbishop": "Erzbischof",
    "Archbishop, Confessor": "Erzbischof, Bekenner",
    "Archbishop, Equal-to-the-Apostles": "Erzbischof, Apostelgleicher",
    "Archdeacon": "Erzdiakon",
    "Archimandrite": "Archimandrit",
    "Bishop": "Bischof",
    "Bishop, Church Father": "Bischof, Kirchenvater",
    "Bishop, Confessor": "Bischof, Bekenner",
    "Bishop, Equal-to-the-Apostles": "Bischof, Apostelgleicher",
    "Bishop, Hieromartyr": "Bischof, Priestermärtyrer",
    "Bishop, Monk": "Bischof, Mönch",
    "Bishops": "Bischöfe",
    "Blessed Eldress": "Selige Starzin",
    "Chamberlain (cubicularius)": "Kämmerer (cubicularius)",
    "Childmartyr": "Kindermärtyrer",
    "Commander": "Feldherr",
    "Confessor, Archpriest": "Bekenner, Erzpriester",
    "Deacon": "Diakon",
    "Deacon, Monk-martyr": "Diakon, Mönchsmärtyrer",
    "Deaconess": "Diakonisse",
    "Deaconess and Martyr": "Diakonisse und Märtyrerin",
    "Elder": "Starez",
    "Empress": "Kaiserin",
    "Equal-to-the-Apostles, Emperor": "Apostelgleicher, Kaiser",
    "Equals-to-the-Apostles": "Apostelgleiche",
    "Grand Duchess": "Grossfürstin",
    "Grand Prince": "Grossfürst",
    "Grand Princess": "Grossfürstin",
    "Great Martyr, Equal-to-the-Apostles": "Grossmärtyrerin, Apostelgleiche",
    "Great Prince, Martyr": "Grossfürst, Märtyrer",
    "Great-martyr": "Grossmärtyrer",
    "Great-martyr, Prince": "Grossmärtyrer, Fürst",
    "Hermit": "Einsiedler",
    "Hermits": "Einsiedler",
    "Hierarchs": "Hierarchen",
    "Hieromartyr (Hermit)": "Priestermärtyrer (Einsiedler)",
    "Hieromartyr, Apostle": "Priestermärtyrer, Apostel",
    "Hieromartyr, Archbishop": "Priestermärtyrer, Erzbischof",
    "Hieromartyr, Archimandrite": "Priestermärtyrer, Archimandrit",
    "Hieromartyr, Archpriest": "Priestermärtyrer, Erzpriester",
    "Hieromartyr, Bishop": "Priestermärtyrer, Bischof",
    "Hieromartyr, Confessor": "Priestermärtyrer, Bekenner",
    "Hieromartyr, Deacon": "Priestermärtyrer, Diakon",
    "Hieromartyr, Patriarch": "Priestermärtyrer, Patriarch",
    "Hieromartyr, Pope": "Priestermärtyrer, Papst",
    "Hieromartyr, and his son": "Priestermärtyrer, und sein Sohn",
    "Hieromartyrs": "Priestermärtyrer",
    "Hieromonk": "Priestermönch",
    "Hieroschemamonk": "Priesterschemamönch",
    "High Priest": "Hoherpriester",
    "Icon of the Mother of God": "Ikone der Gottesmutter",
    "King and Martyr": "König und Märtyrer",
    "King and Prophet": "König und Prophet",
    "Laymen": "Laien",
    "Martyrs": "Märtyrer",
    "Master Builders, Monks": "Baumeister, Mönche",
    "Metropolitan": "Metropolit",
    "Metropolitan, Equal-to-the-Apostles": "Metropolit, Apostelgleicher",
    "Monastic Martyr": "Mönchsmärtyrer",
    "Monastic Martyrs": "Mönchsmärtyrer",
    "Monastic New Martyr": "Neuer Mönchsmärtyrer",
    "Monastics": "Mönche und Nonnen",
    "Monk": "Mönch",
    "Monk (Founder)": "Mönch (Gründer)",
    "Monk (Hermit)": "Mönch (Einsiedler)",
    "Monk (elder)": "Mönch (Starez)",
    "Monk (hermit)": "Mönch (Einsiedler)",
    "Monk (novice)": "Mönch (Novize)",
    "Monk (recluse)": "Mönch (Klausner)",
    "Monk (stylite)": "Mönch (Stylit)",
    "Monk, Church Father": "Mönch, Kirchenvater",
    "Monk, Confessor": "Mönch, Bekenner",
    "Monk, Elder": "Mönch, Starez",
    "Monk, Hymnographer": "Mönch, Hymnendichter",
    "Monk, Martyr": "Mönch, Märtyrer",
    "Monk, Recluse": "Mönch, Klausner",
    "Monk, Unmercenary Physician": "Mönch, uneigennütziger Arzt",
    "Monk, former Great Zhupan": "Mönch, vormals Grosszupan",
    "Monk-martyr": "Mönchsmärtyrer",
    "Monk-martyrs": "Mönchsmärtyrer",
    "Monks": "Mönche",
    "Monks (Founders)": "Mönche (Gründer)",
    "Mother": "Mutter",
    "Myrrhbearer": "Myrrhenträgerin",
    "New Martyrs": "Neumärtyrer",
    "New Martyrs and Confessors": "Neumärtyrer und Bekenner",
    "Nun": "Nonne",
    "Nun-martyr": "Nonnenmärtyrerin",
    "Patriarch": "Patriarch",
    "Patriarch, Church Father": "Patriarch, Kirchenvater",
    "Patriarch, Confessor": "Patriarch, Bekenner",
    "Patriarch, Hieromartyr": "Patriarch, Priestermärtyrer",
    "Physician": "Arzt",
    "Physicians": "Ärzte",
    "Pope": "Papst",
    "Pope of Rome, Confessor": "Papst von Rom, Bekenner",
    "Presbyter and Deacon": "Presbyter und Diakon",
    "Presbyters, Confessors": "Presbyter, Bekenner",
    "Priest": "Priester",
    "Prince": "Fürst",
    "Prince of Moldavia": "Fürst der Moldau",
    "Prince, Passion-Bearer": "Fürst, Passionsträger",
    "Princes": "Fürsten",
    "Princess": "Fürstin",
    "Princess, Nun": "Fürstin, Nonne",
    "Proconsul (military commander)": "Prokonsul (Feldherr)",
    "Prophet and Forerunner": "Prophet und Vorläufer",
    "Prophetess": "Prophetin",
    "Protomartyr": "Erzmärtyrer",
    "Protopresbyter": "Protopresbyter",
    "Recluse": "Klausner",
    "Right-believing Prince": "Rechtgläubiger Fürst",
    "Right-believing Prince (Monk)": "Rechtgläubiger Fürst (Mönch)",
    "Right-believing Prince and Princess": "Rechtgläubiger Fürst und Fürstin",
    "Right-believing Prince, Passion-bearer": "Rechtgläubiger Fürst, Passionsträger",
    "Right-believing Princess (Nun)": "Rechtgläubige Fürstin (Nonne)",
    "Right-believing Princess, Martyr": "Rechtgläubige Fürstin, Märtyrerin",
    "Righteous (Child)": "Gerechter (Kind)",
    "Righteous (Children)": "Gerechte (Kinder)",
    "Righteous (Unmercenary)": "Gerechter (Uneigennütziger)",
    "Righteous Forefather": "Gerechter Altvater",
    "Righteous Virgin": "Gerechte Jungfrau",
    "Righteous, Priest": "Gerechter, Priester",
    "Roman soldier": "Römischer Soldat",
    "Schemamonk": "Schemamönch",
    "Synaxis": "Synaxis",
    "Tsar and Imperial Family": "Zar und Kaiserfamilie",
    "Unmercenary Martyrs": "Uneigennützige Märtyrer",
    "Venerable": "Ehrwürdiger",
    "Venerable Prince": "Ehrwürdiger Fürst",
    "Venerable Princess": "Ehrwürdige Fürstin",
    "Virgin": "Jungfrau",
    "Virgin Martyrs": "Jungfrauen und Märtyrerinnen",
    "Virgin-martyr": "Jungfrau und Märtyrerin",
    "Youths": "Jünglinge",
})


# The places, which are not a list but a grammar: a card names a town, a
# province and a country in one line, and the same town appears on twenty
# other cards inside a different line. The pieces are rendered once here and
# the wholes are assembled from them, so a town cannot be spelled one way on
# one card and another way on the next.
PARTS = {}


def expand(phrases):
    """The compounds, assembled from the parts above.

    Only the place line is built here - a town and a province and a country
    set down in one line. The title a card hangs on a name is not built,
    because German forms it with von and a case the map has no room for:
    "of Ancyra" is von Ankyra, but "of the Kyiv Caves" is von den Kiewer
    Hoehlen, and the article changes with the place. Those are written out
    in TEXT.
    """
    out = {}
    for p in phrases:
        bits = p.split(", ")
        if all(b in PARTS for b in bits):
            out[p] = ", ".join(PARTS[b] for b in bits)
    return out


# The places, first part. Cyrillic is transliterated the German way -
# Radonesch, Sarow, Belosersk - as the German Orthodox books write it; see
# docs/GERMAN.md.
PARTS.update({
    "Abel-meholah": "Abel-Mehola",
    "Abkhazeti": "Abchaseti",
    "Achaia": "Achaia",
    "Adamovka": "Adamowka",
    "Adrianople": "Adrianopel",
    "Adrianopolis": "Adrianopel",
    "Aegae": "Aigai",
    "Aegean": "Ägäis",
    "Aegina": "Ägina",
    "Aetolia": "Ätolien",
    "Africa": "Afrika",
    "Agrigentum": "Agrigent",
    "Akhaltsikhe": "Achalziche",
    "Aksum": "Aksum",
    "Alaska": "Alaska",
    "Albania": "Albanien",
    "Albanopolis": "Albanopolis",
    "Aleppo": "Aleppo",
    "Alexandria": "Alexandria",
    "All America": "Ganz Amerika",
    "Amasea": "Amaseia",
    "Amasia": "Amaseia",
    "Amastridea": "Amastris",
    "Amastris": "Amastris",
    "Amathus": "Amathus",
    "America": "Amerika",
    "Amida": "Amida",
    "Amisos": "Amisos",
    "Amisus": "Amisos",
    "Amnia": "Amnia",
    "Amorion": "Amorion",
    "Amphipolis": "Amphipolis",
    "Anaplus": "Anaplus",
    "Anastasiopolis": "Anastasiopolis",
    "Anathoth": "Anatot",
    "Anatolia": "Anatolien",
    "Anazarbus": "Anazarbos",
    "Ancyra": "Ankyra",
    "Andronikov Monastery": "Andronikow-Kloster",
    "Anga": "Anga",
    "Annesi": "Annesi",
    "Annisa": "Annisa",
    "Antinoe": "Antinoë",
    "Antioch": "Antiochien",
    "Antioch in Pisidia": "Antiochien in Pisidien",
    "Antioch of Pisidia": "Antiochien in Pisidien",
    "Anzersk": "Ansersk",
    "Anzersk Island": "Insel Ansersk",
    "Apamea": "Apameia",
    "Aphrodisias": "Aphrodisias",
    "Apollonia": "Apollonia",
    "Apulia": "Apulien",
    "Aquileia": "Aquileia",
    "Arabia": "Arabien",
    "Arabian Desert": "Arabische Wüste",
    "Arauraka": "Arauraka",
    "Arbela": "Arbela",
    "Archangel Gabriel": "Erzengel Gabriel",
    "Arethusa": "Arethusa",
    "Argos": "Argos",
    "Arianzus": "Arianzos",
    "Arkhangelsk": "Archangelsk",
    "Arkhangelsk lands": "Gebiet von Archangelsk",
    "Armagh": "Armagh",
    "Armenia": "Armenien",
    "Armenia Minor": "Kleinarmenien",
    "Arsinoe": "Arsinoë",
    "Arta": "Arta",
    "Artanuji": "Artanudschi",
    "Ascalon": "Askalon",
    "Asia Minor": "Kleinasien",
    "Asikha": "Asicha",
    "Athens": "Athen",
    "Atka Island": "Insel Atka",
    "Atskuri": "Azkuri",
    "Atsquri": "Azkuri",
    "Attica": "Attika",
    "Auleneia": "Auleneia",
    "Auxerre": "Auxerre",
    "Avnezh": "Awnesch",
    "Babylon": "Babylon",
    "Balkans": "Balkan",
    "Barcelona": "Barcelona",
    "Bari": "Bari",
    "Basarbov": "Basarbowo",
    "Beauvais": "Beauvais",
    "Beirut": "Beirut",
    "Belarus": "Weissrussland",
    "Belev": "Beljow",
    "Belgorod": "Belgorod",
    "Belgorod (Akkerman)": "Belgorod (Akkerman)",
    "Belgrade": "Belgrad",
    "Belozersk": "Belosersk",
    "Belozersk lands": "Gebiet von Belosersk",
    "Belozersk lands and Mozhaisk": "Gebiet von Belosersk und Moschaisk",
    "Benevento": "Benevent",
    "Beocin Monastery": "Kloster Beocin",
    "Berezan": "Beresan",
    "Berezniko": "Beresniko",
    "Beroea": "Beroia",
    "Besanduc": "Besanduk",
    "Bethany": "Bethanien",
    "Bethel": "Bethel",
    "Bethlapeta": "Bethlapeta",
    "Bethlehem": "Bethlehem",
    "Bethsaida": "Bethsaida",
    "Bethsaloe": "Bethsaloe",
    "Bezhetsk lands": "Gebiet von Beschezk",
    "Bialystok": "Bialystok",
    "Bisericani Monastery": "Kloster Bisericani",
    "Bithynia": "Bithynien",
    "Blachernae": "Blachernen",
    "Black Lake": "Schwarzer See",
    "Black Sea coast": "Schwarzmeerküste",
    "Bodbe": "Bodbe",
    "Boeotia": "Böotien",
    "Bogolyubovo": "Bogoljubowo",
    "Bohemia": "Böhmen",
    "Bolgar": "Bolgar",
    "Borovichi": "Borowitschi",
    "Borovsk": "Borowsk",
    "Bosnia": "Bosnien",
    "Boston": "Boston",
    "Bostra": "Bostra",
    "Braunton": "Braunton",
    "Brest": "Brest",
    "Briansk": "Brjansk",
    "Britain": "Britannien",
    "British Isles": "Britische Inseln",
    "Brooklyn": "Brooklyn",
})


# The places, second part.
PARTS.update({
    "Bryansk": "Brjansk",
    "Bucharest": "Bukarest",
    "Budimlje": "Budimlje",
    "Bulgaria": "Bulgarien",
    "Butovo": "Butowo",
    "Buzau Mountains": "Buzau-Gebirge",
    "Byblos": "Byblos",
    "Byzantine Empire": "Byzantinisches Reich",
    "Byzantium": "Byzanz",
    "Byzantium (Constantinople)": "Byzanz (Konstantinopel)",
    "Caesarea": "Cäsarea",
    "Caesarea Maritima": "Cäsarea am Meer",
    "Caesarea in Cappadocia": "Cäsarea in Kappadokien",
    "California": "Kalifornien",
    "Campania": "Kampanien",
    "Cana": "Kana",
    "Cana of Galilee": "Kana in Galiläa",
    "Canaan": "Kanaan",
    "Canopus": "Kanopos",
    "Capernaum": "Kafarnaum",
    "Cappadocia": "Kappadokien",
    "Caria": "Karien",
    "Carpathian Rus'": "Karpatenrus",
    "Carpatho-Russia": "Karpatenrus",
    "Carthage": "Karthago",
    "Catania": "Catania",
    "Cephalonia": "Kephalonia",
    "Cernica": "Cernica",
    "Cernica Monastery": "Kloster Cernica",
    "Chalcedon": "Chalkedon",
    "Chalcis": "Chalkis",
    "Chalcis desert": "Wüste von Chalkis",
    "Chelm": "Chelm",
    "Chelma Hill": "Berg Chelma",
    "Cherepovets": "Tscherepowez",
    "Chernigov": "Tschernigow",
    "Chernigov lands": "Gebiet von Tschernigow",
    "Chernihiv": "Tschernihiw",
    "Chernihiv lands": "Gebiet von Tschernihiw",
    "Cherson": "Cherson",
    "Chersonesus": "Chersones",
    "Chicago": "Chicago",
    "China": "China",
    "Chios": "Chios",
    "Chonae": "Chonai",
    "Choziba": "Choziba",
    "Chukhloma": "Tschuchloma",
    "Cilicia": "Kilikien",
    "Claudiopolis": "Klaudiopolis",
    "Colophon": "Kolophon",
    "Colossae": "Kolossä",
    "Coma": "Koma",
    "Comana": "Komana",
    "Constantia": "Constantia",
    "Constantinople": "Konstantinopel",
    "Cordoba": "Cordoba",
    "Corfu": "Korfu",
    "Corinth": "Korinth",
    "Corsica": "Korsika",
    "Cotyaeum": "Kotyaion",
    "Crete": "Kreta",
    "Crimea": "Krim",
    "Cucomo": "Cucomo",
    "Cucusus": "Kukusos",
    "Cyprus": "Zypern",
    "Cyrene": "Kyrene",
    "Cyrenia": "Kyrenia",
    "Cyrrhus": "Kyrrhos",
    "Cyzicus": "Kyzikos",
    "Czech Lands": "Böhmische Länder",
    "Dabuda": "Dabuda",
    "Dalmatia": "Dalmatien",
    "Dalmatian Monastery": "Dalmatos-Kloster",
    "Damascus": "Damaskus",
    "Danube lands": "Donauländer",
    "David Gareji": "Dawit Garedscha",
    "Davit-Gareji": "Dawit Garedscha",
    "Decapolis": "Dekapolis",
    "Decapolis of Isauria": "Dekapolis in Isaurien",
    "Demetsana": "Dimitsana",
    "Demitsana": "Dimitsana",
    "Desert beyond the Jordan": "Wüste jenseits des Jordan",
    "Devich": "Dewitsch",
    "Devon": "Devon",
    "Dimitsana": "Dimitsana",
    "Dioclea": "Dioklea",
    "Dioclea (Duklja)": "Dioklea (Duklja)",
    "Disevi": "Disewi",
    "Diveyevo": "Diwejewo",
    "Dobrogea": "Dobrudscha",
    "Dorostolum": "Dorostolon",
    "Dorostolum (Silistra)": "Dorostolon (Silistra)",
    "Drenica": "Drenica",
    "Durostorum": "Durostorum",
    "Dymsk": "Dymsk",
    "Dymskoe Lake": "Dymskoje-See",
    "East Anglia": "Ostanglien",
    "Edessa": "Edessa",
    "Edra": "Edra",
    "Egypt": "Ägypten",
    "Egyptian Desert": "Ägyptische Wüste",
    "Elbasan": "Elbasan",
    "Eleutheropolis": "Eleutheropolis",
    "Elkosh": "Elkosch",
    "Emesa": "Emesa",
    "England": "England",
    "Ephesus": "Ephesus",
    "Epirus": "Epirus",
    "Epivato": "Epivato",
    "Essex": "Essex",
    "Ethiopia": "Äthiopien",
    "Euboea": "Euböa",
    "Euchaita": "Euchaita",
    "Euroea": "Euroia",
    "European Russia": "Europäisches Russland",
    "Evia": "Euböa",
    "Ferapontov": "Ferapontow",
    "Ferapontov Monastery": "Ferapontow-Kloster",
    "Ferapontovo": "Ferapontowo",
    "Feremane": "Feremane",
    "Ferentino": "Ferentino",
    "Flavia Neapolis": "Flavia Neapolis",
    "Florishchi": "Florischtschi",
    "Formia": "Formia",
    "France": "Frankreich",
    "Frasinei": "Frasinei",
    "Galata": "Galata",
    "Galatia": "Galatien",
    "Galich": "Galitsch",
    "Galicia": "Galizien",
    "Galilee": "Galiläa",
    "Gangra": "Gangra",
    "Gareji": "Garedscha",
    "Gary": "Gary",
    "Gath-hepher": "Gat-Hefer",
    "Gaul": "Gallien",
    "Gaza": "Gaza",
    "Gdov": "Gdow",
    "Gdov lands": "Gebiet von Gdow",
    "George Hill": "Georgsberg",
    "Georgia": "Georgien",
    "Germany": "Deutschland",
    "Gibeah of Phinehas": "Gibea des Pinhas",
    "Gilead": "Gilead",
    "Glendalough": "Glendalough",
    "Glushitsa": "Gluschiza",
    "Gori district": "Bezirk Gori",
    "Gortyna": "Gortyna",
    "Gothia": "Gotien",
    "Gothic lands": "Gotenland",
    "Great Lavra": "Grosse Lavra",
    "Great Lavra of Saint Sabbas": "Grosse Lavra des heiligen Sabas",
    "Great Moravia": "Grossmähren",
    "Greece": "Griechenland",
    "Guria": "Gurien",
    "Hartland": "Hartland",
    "Hauran": "Hauran",
    "Hebron": "Hebron",
    "Heliopolis": "Heliopolis",
    "Hellas": "Hellas",
})


# The places, third part.
PARTS.update({
    "Hellespont": "Hellespont",
    "Heraclea": "Heraklea",
    "Hereti": "Hereti",
    "Hermopolis": "Hermupolis",
    "Herzegovina": "Herzegowina",
    "Hierapolis": "Hierapolis",
    "Hilandar": "Chilandar",
    "Holy Land": "Heiliges Land",
    "Holy Trinity-Saint Sergius Lavra": "Dreifaltigkeits-Sergius-Lavra",
    "Hosios Loukas": "Hosios Lukas",
    "Hungary": "Ungarn",
    "Hypaepa": "Hypaipa",
    "Iași": "Iasi",
    "Iconium": "Ikonion",
    "Iken": "Iken",
    "Illinois": "Illinois",
    "Illyria": "Illyrien",
    "Illyricum": "Illyricum",
    "India": "Indien",
    "Indiana": "Indiana",
    "Ioannina": "Ioannina",
    "Irap": "Irap",
    "Ireland": "Irland",
    "Irenopolis": "Irenopolis",
    "Irkutsk": "Irkutsk",
    "Irkutsk province": "Gouvernement Irkutsk",
    "Isauria": "Isaurien",
    "Israel": "Israel",
    "Italy": "Italien",
    "Iza": "Isa",
    "Jackson": "Jackson",
    "Jerusalem": "Jerusalem",
    "Joppa": "Joppe",
    "Jordan River": "Jordan",
    "Judah": "Juda",
    "Judea": "Judäa",
    "Judean Desert": "Judäische Wüste",
    "Judean Wilderness": "Judäische Wüste",
    "Kallippi": "Kallippi",
    "Kaluga": "Kaluga",
    "Kaluga lands": "Gebiet von Kaluga",
    "Kalyazin": "Kaljasin",
    "Kampsada": "Kampsada",
    "Kaniv": "Kaniw",
    "Karelia": "Karelien",
    "Kargopol": "Kargopol",
    "Kargopol lands": "Gebiet von Kargopol",
    "Kartli": "Kartlien",
    "Kartli (Iberia)": "Kartlien (Iberien)",
    "Kashin": "Kaschin",
    "Kasperovo": "Kasperowo",
    "Kastoria": "Kastoria",
    "Kastorion": "Kastorion",
    "Kavsokalyvia": "Kavsokalyvia",
    "Kazan": "Kasan",
    "Kekhta": "Kechta",
    "Kellia": "Kellia",
    "Keno Lake": "Keno-See",
    "Kerch": "Kertsch",
    "Kerkyra": "Kerkyra",
    "Kerkyra (Corfu)": "Kerkyra (Korfu)",
    "Khakhuli": "Chachuli",
    "Khakhuli Monastery": "Kloster Chachuli",
    "Kharkiv": "Charkiw",
    "Kherson": "Cherson",
    "Kherson lands": "Gebiet von Cherson",
    "Khlynov": "Chlynow",
    "Kholm": "Cholm",
    "Khust": "Chust",
    "Khutyn": "Chutyn",
    "Kios": "Kios",
    "Klarjeti": "Klardscheti",
    "Klops Monastery": "Klops-Kloster",
    "Kodiak": "Kodiak",
    "Kola": "Kola",
    "Komel": "Komel",
    "Komel Forest": "Wald von Komel",
    "Kondakovo": "Kondakowo",
    "Konevets": "Konewez",
    "Korets": "Korez",
    "Korissos": "Korissos",
    "Kornet": "Kornet",
    "Korotsk": "Korozk",
    "Kosinsk": "Kosinsk",
    "Kosovo": "Kosovo",
    "Kostroma": "Kostroma",
    "Kostroma lands": "Gebiet von Kostroma",
    "Kozelshchyna": "Koselschtschyna",
    "Kozelsk": "Koselsk",
    "Kozhe Lake": "Koschesee",
    "Krasny Kholm": "Krasny Cholm",
    "Kratovo": "Kratowo",
    "Kremenets": "Kremenez",
    "Kromna": "Kromna",
    "Kronstadt": "Kronstadt",
    "Krushedol": "Krusedol",
    "Kubensk": "Kubensk",
    "Kudinovo": "Kudinowo",
    "Kursk": "Kursk",
    "Kushta": "Kuschta",
    "Kvabtakhevi Monastery": "Kloster Kwabtachewi",
    "Kveli fortress": "Festung Kweli",
    "Kwethluk": "Kwethluk",
    "Kyiv": "Kiew",
    "Kyiv Caves": "Kiewer Höhlen",
    "Kyiv Caves Lavra": "Kiewer Höhlenlavra",
    "Kyiv Far Caves": "Fernen Höhlen von Kiew",
    "Kyiv Near Caves": "Nahen Höhlen von Kiew",
    "Kyiv region": "Gebiet von Kiew",
    "Laconia": "Lakonien",
    "Lake Iliamna": "Iliamnasee",
    "Lake Ilmen": "Ilmensee",
    "Lake Ilo": "Ilosee",
    "Lake Kubenskoye": "Kubenasee",
    "Lake Ladoga": "Ladogasee",
    "Lake Onega": "Onegasee",
    "Lake Orta": "Ortasee",
    "Lake Pskov": "Pskower See",
    "Lake Seliger": "Seligersee",
    "Lake Vorbozomsk": "Worbosomsee",
    "Lampsacus": "Lampsakos",
    "Land of Asher": "Land Ascher",
    "Land of Uz": "Land Uz",
    "Land of Zebulun": "Land Sebulon",
    "Land of the tribe of Simeon": "Land des Stammes Simeon",
    "Langres": "Langres",
    "Laodicea": "Laodizea",
    "Lavra of Saint Sabbas": "Lavra des heiligen Sabas",
    "Lazica": "Lasika",
    "Le Mans": "Le Mans",
    "Lebanon": "Libanon",
    "Leinster": "Leinster",
    "Lelich": "Lelitsch",
    "Lentini": "Lentini",
    "Leokhnovo": "Leochnowo",
    "Leontini": "Leontinoi",
    "Lesbos": "Lesbos",
    "Leucosia (Nicosia)": "Leukosia (Nikosia)",
    "Lezna River": "Lesna",
    "Libertyville": "Libertyville",
    "Libya": "Libyen",
    "Lindisfarne": "Lindisfarne",
    "Lipari": "Lipari",
    "Lithuania": "Litauen",
    "Little Russia (Ukraine)": "Kleinrussland (Ukraine)",
    "Liubech": "Ljubetsch",
    "Liubimograd": "Ljubimograd",
    "Loma": "Loma",
    "Loutraki": "Loutraki",
    "Lubny": "Lubny",
    "Lubyatov": "Lubjatowo",
    "Lucania": "Lukanien",
    "Lukhov": "Luchow",
    "Lycaonia": "Lykaonien",
    "Lycia": "Lykien",
    "Lycopolis": "Lykopolis",
    "Lydda": "Lydda",
    "Lydia": "Lydien",
    "Lykaonia": "Lykaonien",
    "Lyons": "Lyon",
})


# The places, fourth part.
PARTS.update({
    "Lystra": "Lystra",
    "Lérins": "Lérins",
    "Macedonia": "Makedonien",
    "Magdala": "Magdala",
    "Magedon": "Magedon",
    "Magnesia": "Magnesia",
    "Magydos": "Magydos",
    "Maiuma": "Maiuma",
    "Makarovo": "Makarowo",
    "Makhrishche": "Machrischtsche",
    "Malopinega": "Malopinega",
    "Malta": "Malta",
    "Mandera": "Mandera",
    "Mangup": "Mangup",
    "Mantinea": "Mantineia",
    "Mar Saba": "Mar Saba",
    "Maratha": "Maratha",
    "Marathon": "Marathon",
    "Marcianopolis": "Markianopolis",
    "Marikat": "Marikat",
    "Marseilles": "Marseille",
    "Martyropolis": "Martyropolis",
    "Mauretania": "Mauretanien",
    "Medikion": "Medikion",
    "Medikion Monastery": "Kloster Medikion",
    "Medin": "Medin",
    "Mega Dendron": "Mega Dendron",
    "Meglin": "Meglin",
    "Melitene": "Melitene",
    "Melitopolis": "Melitopolis",
    "Menuthis": "Menuthis",
    "Menyusha": "Menjuscha",
    "Merkushino": "Merkuschino",
    "Mesopotamia": "Mesopotamien",
    "Mesteacăn": "Mesteacan",
    "Methymna": "Methymna",
    "Mezen": "Mesen",
    "Mgvime": "Mgwime",
    "Milan": "Mailand",
    "Mineo": "Mineo",
    "Minneapolis": "Minneapolis",
    "Moesia": "Mösien",
    "Mogarissos": "Mogarissos",
    "Mogilev": "Mogiljow",
    "Moldavia": "Moldau",
    "Moldova": "Moldau",
    "Monembasia": "Monemvasia",
    "Monte Cassino": "Montecassino",
    "Monteluco": "Monteluco",
    "Montenegro": "Montenegro",
    "Monza River": "Monsa",
    "Moravia": "Mähren",
    "Morea (Peloponnese)": "Morea (Peloponnes)",
    "Moresheth": "Moreschet",
    "Moscow": "Moskau",
    "Moscow lands": "Gebiet von Moskau",
    "Mount Athos": "Berg Athos",
    "Mount Colzim": "Berg Kolzim",
    "Mount Ephraim": "Gebirge Efraim",
    "Mount Galesion": "Berg Galesion",
    "Mount Galesius": "Berg Galesion",
    "Mount Hor": "Berg Hor",
    "Mount Kyminas": "Berg Kyminas",
    "Mount Maleon": "Berg Maleon",
    "Mount Myrsinon": "Berg Myrsinon",
    "Mount Nebo": "Berg Nebo",
    "Mount Olympus": "Berg Olymp",
    "Mount Sagmata": "Berg Sagmata",
    "Mount Sinai": "Berg Sinai",
    "Mount Skopa": "Berg Skopa",
    "Mount Taurus": "Taurusgebirge",
    "Mount of Olives": "Ölberg",
    "Mozhaisk": "Moschaisk",
    "Mrkonjici": "Mrkonjici",
    "Mtskheta": "Mzcheta",
    "Murom": "Murom",
    "Murom Island": "Insel Murom",
    "Mutalaska": "Mutalaska",
    "Mylapore": "Mylapore",
    "Mylasa": "Mylasa",
    "Myra": "Myra",
    "Myra in Lycia": "Myra in Lykien",
    "Myrgorod": "Myrhorod",
    "Mytilene": "Mytilene",
    "Naissus": "Naissus",
    "Najran": "Nadschran",
    "Nalšia": "Nalsia",
    "Nanterre": "Nanterre",
    "Naples": "Neapel",
    "Nauplion": "Nauplion",
    "Nazareth": "Nazareth",
    "Nazianzus": "Nazianz",
    "Nea Makri": "Nea Makri",
    "Neamts Monastery": "Kloster Neamt",
    "Neamț": "Neamt",
    "Neapolis": "Neapolis",
    "Near Constantinople": "Bei Konstantinopel",
    "Neocaesarea": "Neocäsarea",
    "Nerchinsk": "Nertschinsk",
    "New Lake": "Neuer See",
    "New York": "New York",
    "Nicaea": "Nizäa",
    "Nicea": "Nizäa",
    "Nicomedia": "Nikomedien",
    "Nicopolis": "Nikopolis",
    "Nicosia": "Nikosia",
    "Nikiforovskaya": "Nikiforowskaja",
    "Nisibis": "Nisibis",
    "Nitria": "Nitrien",
    "Nizhni-Novgorod": "Nischni Nowgorod",
    "Nizhny Novgorod": "Nischni Nowgorod",
    "Nizhny Novgorod lands": "Gebiet von Nischni Nowgorod",
    "Nizhyn": "Nischyn",
    "North Africa": "Nordafrika",
    "North America": "Nordamerika",
    "North Macedonia": "Nordmazedonien",
    "Northumbria": "Northumbrien",
    "Novara": "Novara",
    "Novgorod": "Nowgorod",
    "Novgorod lands": "Gebiet von Nowgorod",
    "Noviodunum": "Noviodunum",
    "Novoezersk": "Nowoesersk",
    "Nurma": "Nurma",
    "Nursia": "Nursia",
    "Nyssa": "Nyssa",
    "Obnora River": "Obnora",
    "Odessa": "Odessa",
    "Odrino": "Odrino",
    "Ohrid": "Ohrid",
    "Old Lavra of Chariton": "Alte Lavra des Chariton",
    "Olonets": "Olonez",
    "Olonets lands": "Gebiet von Olonez",
    "Olshansk": "Olschansk",
    "Olympus": "Olymp",
    "Omala": "Omala",
    "Ondrusov": "Ondrussow",
    "Ophrah": "Ofra",
    "Opso": "Opso",
    "Orel lands": "Gebiet von Orjol",
    "Oshevensk": "Oschewensk",
    "Osrhoene": "Osrhoene",
    "Ostia": "Ostia",
    "Ostracine": "Ostrakine",
    "Ostrog": "Ostrog",
    "Ovche Pole": "Ovce Pole",
    "Ovruch": "Owrutsch",
    "Ozovia": "Osowia",
    "Palermo": "Palermo",
    "Palestine": "Palästina",
    "Palii Island": "Insel Palii",
    "Pamphylia": "Pamphylien",
    "Pannonia": "Pannonien",
    "Paphlagonia": "Paphlagonien",
    "Paphos": "Paphos",
    "Paramythia": "Paramythia",
    "Paris": "Paris",
    "Parium": "Parion",
    "Paros": "Paros",
    "Parthia": "Parthien",
    "Patara": "Patara",
})


# The places, fifth part.
PARTS.update({
    "Patmos": "Patmos",
    "Patras": "Patras",
    "Pec": "Pec",
    "Pechenga": "Petschenga",
    "Pechenga Monastery": "Kloster Petschenga",
    "Pekhorka": "Pechorka",
    "Pelecete": "Pelekete",
    "Pelekete": "Pelekete",
    "Pelekete Monastery": "Kloster Pelekete",
    "Peloponnese": "Peloponnes",
    "Pelshma": "Pelschma",
    "Pelusium": "Pelusium",
    "Pennsylvania": "Pennsylvania",
    "Perekop (Perekomsky) Monastery": "Perekomski-Kloster",
    "Pereslavl": "Pereslawl",
    "Pereslavl-Zalessky": "Pereslawl-Salesski",
    "Pereyaslavl": "Perejaslawl",
    "Pereyaslavl-Zalessky": "Perejaslawl-Salesski",
    "Pergamum": "Pergamon",
    "Perge": "Perge",
    "Peristerai": "Peristerai",
    "Perm": "Perm",
    "Perm lands": "Gebiet von Perm",
    "Persia": "Persien",
    "Persia and the East": "Persien und der Osten",
    "Peshnosha": "Peschnoscha",
    "Petrograd": "Petrograd",
    "Peć": "Pec",
    "Pharan": "Pharan",
    "Pharasa": "Pharasa",
    "Philadelphia": "Philadelphia",
    "Philippopolis": "Philippopolis",
    "Philotheou Monastery": "Kloster Philotheou",
    "Phocis": "Phokis",
    "Phoenicia": "Phönizien",
    "Phrygia": "Phrygien",
    "Pinega": "Pinega",
    "Pinsk": "Pinsk",
    "Pisidia": "Pisidien",
    "Plousias": "Plusias",
    "Pochaev": "Potschajew",
    "Pochaiv": "Potschajiw",
    "Podolia": "Podolien",
    "Poiana Marului": "Poiana Marului",
    "Pokutia": "Pokutien",
    "Poland": "Polen",
    "Polotsk": "Polozk",
    "Poltava": "Poltawa",
    "Poltava lands": "Gebiet von Poltawa",
    "Poltava region": "Gebiet von Poltawa",
    "Polybotum": "Polybotos",
    "Pomorie": "Pomorie",
    "Pompeiopolis": "Pompeiopolis",
    "Pontus": "Pontos",
    "Popovo": "Popowo",
    "Porkhov": "Porchow",
    "Poshekhonye": "Poschechonje",
    "Pozzuoli": "Pozzuoli",
    "Prague": "Prag",
    "Pretorium": "Pretorium",
    "Priluki": "Priluki",
    "Prokopion": "Prokopion",
    "Protection Convent": "Schutzkloster",
    "Prusa": "Prusa",
    "Pryluky": "Pryluky",
    "Prymnessus": "Prymnessos",
    "Pshinja": "Psinja",
    "Pskov": "Pskow",
    "Pskov Caves Monastery": "Pskower Höhlenkloster",
    "Ptinapor": "Ptinapor",
    "Ptolemais": "Ptolemais",
    "Puteoli": "Puteoli",
    "Putna": "Putna",
    "Pythias": "Pythia",
    "Périgueux": "Périgueux",
    "Radonezh": "Radonesch",
    "Radonezh and Serpukhov": "Radonesch und Serpuchow",
    "Radoviste": "Radoviste",
    "Raithu": "Raithu",
    "Ramah": "Rama",
    "Ramathaim": "Ramatajim",
    "Ramathaim-Zophim": "Ramatajim-Zofim",
    "Ramnic": "Ramnic",
    "Ravanica": "Ravanica",
    "Ravenna": "Ravenna",
    "Resafa": "Resafa",
    "Rethymnon": "Rethymnon",
    "Rhosus": "Rhosos",
    "Rila": "Rila",
    "Robeika": "Robeika",
    "Robeika River": "Robeika",
    "Roman Britain": "Römisches Britannien",
    "Romania": "Rumänien",
    "Rome": "Rom",
    "Rome and Milan": "Rom und Mailand",
    "Rome and the East": "Rom und der Osten",
    "Rossos": "Rhosos",
    "Rostov": "Rostow",
    "Rostov lands": "Gebiet von Rostow",
    "Rus'": "Rus",
    "Russia": "Russland",
    "Russian North": "Russischer Norden",
    "Russian nobility": "Russischer Adel",
    "Ryazan": "Rjasan",
    "Ryazan province": "Gouvernement Rjasan",
    "Rzhev": "Rschew",
    "Saint John": "Saint John",
    "Saint Petersburg": "Sankt Petersburg",
    "Salamis": "Salamis",
    "Salamis (Constantia)": "Salamis (Constantia)",
    "Salona": "Salona",
    "Samaria": "Samaria",
    "Samegrelo": "Samegrelo",
    "Samosata": "Samosata",
    "Samothrace": "Samothrake",
    "Samtskhe": "Samzche",
    "San Francisco": "San Francisco",
    "Saragossa": "Saragossa",
    "Sardis": "Sardes",
    "Sarov": "Sarow",
    "Scetis": "Sketis",
    "Scotland": "Schottland",
    "Scythia": "Skythien",
    "Scythia Minor": "Kleinskythien",
    "Sebaste": "Sebaste",
    "Sebastea": "Sebaste",
    "Sebino": "Sebino",
    "Seleucia": "Seleukia",
    "Seleucia-Ctesiphon": "Seleukia-Ktesiphon",
    "Selymbria": "Selymbria",
    "Serbia": "Serbien",
    "Sergiev Posad": "Sergijew Possad",
    "Serpukhov": "Serpuchow",
    "Serres": "Serres",
    "Shanghai": "Schanghai",
    "Shenkursk": "Schenkursk",
    "Shiloh": "Schilo",
    "Shio-Mgvime Monastery": "Kloster Schio-Mgwime",
    "Shovskoe": "Schowskoje",
    "Shuya": "Schuja",
    "Shuzhgora": "Schuschgora",
    "Siberia": "Sibirien",
    "Siblag camps": "Lager von Siblag",
    "Sicily": "Sizilien",
    "Side": "Side",
    "Sigriane": "Sigriane",
    "Silistra": "Silistra",
    "Simferopol": "Simferopol",
    "Sinai": "Sinai",
    "Sinai and Raithu": "Sinai und Raithu",
    "Sinai wilderness": "Wüste Sinai",
    "Singidunum": "Singidunum",
    "Sinope": "Sinope",
    "Sinope and Amasea": "Sinope und Amaseia",
    "Sinozersk": "Sinosersk",
    "Sirmium": "Sirmium",
    "Sisan": "Sisan",
    "Sitka": "Sitka",
    "Siya Monastery": "Kloster Sija",
    "Skepsis": "Skepsis",
    "Sketis": "Sketis",
    "Skrino": "Skrino",
    "Slutsk": "Sluzk",
    "Smolensk": "Smolensk",
    "Smyrna": "Smyrna",
    "Snetogorsk": "Snetogorsk",
    "Snetogorsk Monastery": "Kloster Snetogorsk",
    "Sofia": "Sofia",
    "Sokhot River": "Sochot",
    "Solovki": "Solowki",
})


# The places, sixth part.
PARTS.update({
    "Solovki Islands": "Solowezki-Inseln",
    "Solovki Monastery": "Solowezki-Kloster",
    "Sophene": "Sophene",
    "Sora River": "Sora",
    "Soreoi": "Soreoi",
    "Spain": "Spanien",
    "Spoleto": "Spoleto",
    "Spruce Island": "Fichteninsel",
    "Srem": "Srem",
    "St Albans": "St Albans",
    "St. Petersburg": "Sankt Petersburg",
    "Stara Zagora": "Stara Sagora",
    "Staritsa": "Stariza",
    "Starytsa": "Staryzja",
    "Steirion": "Steirion",
    "Stolobny Island": "Insel Stolobny",
    "Storozhi Hill": "Storoschi-Berg",
    "Strobil": "Strobilos",
    "Strumica": "Strumica",
    "Studenica": "Studenica",
    "Subiaco": "Subiaco",
    "Suceava": "Suceava",
    "Sura": "Sura",
    "Susa": "Susa",
    "Suzdal": "Susdal",
    "Svensky Monastery": "Kloster Swensk",
    "Svir": "Swir",
    "Sviyazhsk": "Swijaschsk",
    "Sweden": "Schweden",
    "Syandeba": "Sjandeba",
    "Syandemsk": "Sjandemsk",
    "Syanzhema": "Sjanschema",
    "Syanzhema River": "Sjanschema",
    "Sykeon": "Sykeon",
    "Symbola": "Symbola",
    "Symbola Monastery": "Kloster Symbola",
    "Synnada": "Synnada",
    "Syracuse": "Syrakus",
    "Syria": "Syrien",
    "Tabatha": "Tabatha",
    "Tabenna": "Tabenna",
    "Tabennisi": "Tabennisi",
    "Tambov": "Tambow",
    "Tao": "Tao",
    "Tao-Klarjeti": "Tao-Klardscheti",
    "Taormina": "Taormina",
    "Taphanes": "Taphanes",
    "Targala": "Targala",
    "Tarnovo": "Tarnowo",
    "Tarsus": "Tarsus",
    "Tarsus and Achaia": "Tarsus und Achaia",
    "Tarsus and Rossos": "Tarsus und Rhosos",
    "Tarsus and the East": "Tarsus und der Osten",
    "Tashkent": "Taschkent",
    "Tauresium": "Tauresium",
    "Tazlău": "Tazlau",
    "Tazlău Monastery": "Kloster Tazlau",
    "Tbilisi": "Tiflis",
    "Tekoa": "Tekoa",
    "Tenedos": "Tenedos",
    "Tennis": "Tennis",
    "Teratyn": "Teratyn",
    "Terracina": "Terracina",
    "The East": "Der Osten",
    "The Jordan": "Der Jordan",
    "Thebaid": "Thebais",
    "Thebes": "Theben",
    "Thebes of Egypt": "Theben in Ägypten",
    "Thessalonica": "Thessaloniki",
    "Thessaloniki": "Thessaloniki",
    "Thessaly": "Thessalien",
    "Thrace": "Thrakien",
    "Thyateira": "Thyateira",
    "Tikhvin": "Tichwin",
    "Tiksna": "Tiksna",
    "Tishbe of Gilead": "Tischbe in Gilead",
    "Tmutarakan": "Tmutarakan",
    "Tobolsk": "Tobolsk",
    "Tolva": "Tolwa",
    "Toropets": "Toropez",
    "Torzhok": "Torschok",
    "Totma": "Totma",
    "Trajanopolis": "Traianopolis",
    "Tralles": "Tralleis",
    "Transcarpathia": "Transkarpatien",
    "Trebia": "Trebia",
    "Trebizond": "Trapezunt",
    "Tremithus": "Tremithus",
    "Trier": "Trier",
    "Triglia": "Triglia",
    "Trikala": "Trikala",
    "Trinity Lavra": "Dreifaltigkeits-Lavra",
    "Trinity-Sergius Lavra": "Dreifaltigkeits-Sergius-Lavra",
    "Tripoli": "Tripolis",
    "Troas": "Troas",
    "Tsarskoye Selo": "Zarskoje Selo",
    "Tula lands": "Gebiet von Tula",
    "Turchasovo": "Turtschassowo",
    "Turov": "Turow",
    "Tuscany": "Toskana",
    "Tver": "Twer",
    "Tver lands": "Gebiet von Twer",
    "Tyana": "Tyana",
    "Tyre": "Tyrus",
    "Uchma": "Utschma",
    "Uglich": "Uglitsch",
    "Ukraine": "Ukraine",
    "United States": "Vereinigte Staaten",
    "Unzha": "Unscha",
    "Upper Thebaid": "Obere Thebais",
    "Ur of the Chaldees": "Ur in Chaldäa",
    "Ushchelye": "Uschtschelje",
    "Ust-Totma": "Ust-Totma",
    "Ust-Vym": "Ust-Wym",
    "Ustiug": "Ustjug",
    "Ustyug": "Ustjug",
    "Vaga": "Waga",
    "Vaga lands": "Gebiet von Waga",
    "Vagharshapat": "Wagharschapat",
    "Valaam": "Walaam",
    "Valencia": "Valencia",
    "Varnitsa": "Warniza",
    "Varzuga": "Warsuga",
    "Vasilevo": "Wassiljewo",
    "Vaste": "Vaste",
    "Vasyliv": "Wassyliw",
    "Vazheozero region": "Gebiet von Waschesero",
    "Velehrad": "Velehrad",
    "Veliki Luki": "Welikije Luki",
    "Veliky Ustiug": "Weliki Ustjug",
    "Veliky Ustyug": "Weliki Ustjug",
    "Venice": "Venedig",
    "Verkhoturye": "Werchoturje",
    "Verkola": "Werkola",
    "Verona": "Verona",
    "Verulamium": "Verulamium",
    "Verulamium (St Albans)": "Verulamium (St Albans)",
    "Vetluga": "Wetluga",
    "Videlebye": "Widelebje",
    "Vilnius": "Wilna",
    "Vishera": "Wischera",
    "Vladimir": "Wladimir",
    "Vladimir lands": "Gebiet von Wladimir",
    "Vladimir-Suzdal": "Wladimir-Susdal",
    "Vladimir-in-Volhynia": "Wladimir in Wolhynien",
    "Volga Bulgaria": "Wolgabulgarien",
    "Volhynia": "Wolhynien",
    "Volissos": "Volissos",
    "Volodymyr-Volhynia": "Wolodymyr-Wolynskyj",
    "Vologda": "Wologda",
    "Vologda lands": "Gebiet von Wologda",
    "Volokolamsk": "Wolokolamsk",
    "Vorbozomsk Lake": "Worbosomsee",
    "Voronezh": "Woronesch",
    "Vracar": "Vracar",
    "Vyatka": "Wjatka",
    "Vyazma": "Wjasma",
    "Vyritsa": "Wyriza",
    "Vyshgorod": "Wyschgorod",
    "Vyshhorod": "Wyschhorod",
})


# The places, seventh part, with the prepositional pieces a card sets beside
# a town: "near Kyiv", "the Judean desert". They are parts like the rest,
# because they stand in the same line and must agree with what follows.
PARTS.update({
    "Wales": "Wales",
    "Warsaw": "Warschau",
    "Western Rus": "Westliche Rus",
    "White Lake": "Weisser See",
    "White Lake (Beloozero)": "Weisser See (Beloosero)",
    "White Lake region": "Gebiet am Weissen See",
    "White Sea": "Weisses Meer",
    "Wilkes-Barre": "Wilkes-Barre",
    "Wonderful Mountain": "Wunderbarer Berg",
    "Yakhroma": "Jachroma",
    "Yarenga": "Jarenga",
    "Yaroslavl": "Jaroslawl",
    "Yaroslavl lands": "Gebiet von Jaroslawl",
    "Yaroslavl province": "Gouvernement Jaroslawl",
    "Yashezero": "Jaschesero",
    "Yazvishche": "Jaswischtsche",
    "Yekaterinburg": "Jekaterinburg",
    "Yuriev (Tartu)": "Jurjew (Tartu)",
    "Yuriev Monastery": "Jurjew-Kloster",
    "Yuriev-Polsky": "Jurjew-Polski",
    "Yuryegorsk": "Jurjegorsk",
    "Zadonsk": "Sadonsk",
    "Zahumlje": "Zahumlje",
    "Zahumlje (Zakholm)": "Zahumlje (Sacholm)",
    "Zakynthos": "Zakynthos",
    "Zaozersk": "Saosersk",
    "Zelenets": "Selenez",
    "Zemplin region": "Gebiet von Zemplin",
    "Zeta": "Zeta",
    "Zeugma": "Zeugma",
    "Zhabyn Monastery": "Kloster Schabyn",
    "Zheleznoborov": "Schelesnoborowo",
    "Zhicha": "Zica",
    "Zhicha Monastery": "Kloster Zica",
    "Zvenigorod": "Swenigorod",
    "Zverki": "Swerki",
    "all Greece": "ganz Griechenland",
    "all Rus'": "ganz Rus",
    "all Russia": "ganz Russland",
    "all Slavic lands": "alle slawischen Länder",
    "all schools": "alle Schulen",
    "all the Slavic lands": "alle slawischen Länder",
    "and Ephesus": "und Ephesus",
    "beyond the Danube": "jenseits der Donau",
    "gardens and vineyards": "Gärten und Weinberge",
    "near Agrigentum": "bei Agrigent",
    "near Alexandria": "bei Alexandria",
    "near Ancyra": "bei Ankyra",
    "near Antioch": "bei Antiochien",
    "near Apamea": "bei Apameia",
    "near Bialystok": "bei Bialystok",
    "near Borovsk": "bei Borowsk",
    "near Cherepovets": "bei Tscherepowez",
    "near Chernigov": "bei Tschernigow",
    "near Constantinople": "bei Konstantinopel",
    "near Cyrrhus": "bei Kyrrhos",
    "near Dorostolum": "bei Dorostolon",
    "near Edessa": "bei Edessa",
    "near Ephesus": "bei Ephesus",
    "near Galich": "bei Galitsch",
    "near Gaza": "bei Gaza",
    "near Kargopol": "bei Kargopol",
    "near Kiev": "bei Kiew",
    "near Kyiv": "bei Kiew",
    "near Moscow": "bei Moskau",
    "near Mount Tabor": "beim Berg Tabor",
    "near Mtskheta": "bei Mzcheta",
    "near Novgorod": "bei Nowgorod",
    "near Prusa": "bei Prusa",
    "near Pskov": "bei Pskow",
    "near Rostov": "bei Rostow",
    "near Samosata": "bei Samosata",
    "near Staraya Russa": "bei Staraja Russa",
    "near Totma": "bei Totma",
    "near Uglich": "bei Uglitsch",
    "near Verkhoturye": "bei Werchoturje",
    "near Vladimir": "bei Wladimir",
    "near Volokolamsk": "bei Wolokolamsk",
    "near the Dvina": "an der Dwina",
    "on the Dvina": "an der Dwina",
    "on the Onega": "an der Onega",
    "the Balkans": "der Balkan",
    "the Belozersk country": "das Land um Belosersk",
    "the Bistrița valley": "das Bistrita-Tal",
    "the Black Sea coast and the Caucasus": "die Schwarzmeerküste und der Kaukasus",
    "the Buzau Mountains": "das Buzau-Gebirge",
    "the Caucasus": "der Kaukasus",
    "the Cells": "die Kellia",
    "the Cherepovets country": "das Land um Tscherepowez",
    "the Danube lands": "die Donauländer",
    "the Dvina country": "das Land an der Dwina",
    "the East": "der Osten",
    "the Egyptian desert": "die ägyptische Wüste",
    "the Gentile nations": "die Heidenvölker",
    "the Golden Horde": "die Goldene Horde",
    "the Holy Land": "das Heilige Land",
    "the Jordan": "der Jordan",
    "the Jordan desert": "die Wüste am Jordan",
    "the Judean desert": "die judäische Wüste",
    "the Judean wilderness": "die judäische Wüste",
    "the Kola north": "der Norden von Kola",
    "the Komi lands": "das Land der Komi",
    "the Mount of Olives": "der Ölberg",
    "the Obnora": "die Obnora",
    "the Oka country": "das Land an der Oka",
    "the Olonets country": "das Land um Olonez",
    "the Onega country": "das Land an der Onega",
    "the Palestinian desert": "die palästinische Wüste",
    "the Peloponnese": "der Peloponnes",
    "the Pinega country": "das Land an der Pinega",
    "the Pskov Caves": "die Pskower Höhlen",
    "the Pčinja valley": "das Pcinja-Tal",
    "the Russian North": "der russische Norden",
    "the Russian north": "der russische Norden",
    "the Seto lands": "das Land der Seto",
    "the Smolensk cemetery": "der Smolensker Friedhof",
    "the Sora": "die Sora",
    "the Studios monastery": "das Studios-Kloster",
    "the Thebaid": "die Thebais",
    "the Tikhvin country": "das Land um Tichwin",
    "the Urals": "der Ural",
    "the Volga lands": "das Wolgaland",
    "the Vologda country": "das Land um Wologda",
    "the White Sea": "das Weisse Meer",
    "the White Sea coast": "die Küste des Weissen Meeres",
    "the Wonderful Mountain": "der Wunderbare Berg",
    "the Yakhroma": "die Jachroma",
    "the desert of Egypt": "die Wüste Ägyptens",
    "the inner Egyptian desert": "die innere ägyptische Wüste",
    "the lands of the apostolic mission": "die Länder der apostolischen Mission",
    "the northern Thebaid": "die nördliche Thebais",
    "the northern missions": "die Missionen des Nordens",
    "the whole world": "die ganze Welt",
    "the wilderness beyond Mesopotamia": "die Wüste jenseits Mesopotamiens",
    "travelers' gates": "Tore der Reisenden",
    "Žiča": "Zica",
})
