# -*- coding: utf-8 -*-
"""Greek for the vocabulary that stands beside the lives.

TEXT = {the phrase the index shows: the Greek}. PARTS holds the pieces the
compound place-names are built from, and expand() assembles the wholes, so a
town cannot be spelled one way on one card and another way on the next.

Greek is the tongue the greater part of this vocabulary was first said in,
and where that is so the phrase goes home rather than being carried across:
the orders of sanctity, the ranks of the Typikon, the ancient sees and the
provinces of the Christian East are given as the Greek Church gives them,
not as renderings of the English renderings of them. The Slavic, Georgian
and Latin names take the forms the Greek synaxaria have received, and where
no received form exists the name is transliterated.

The keys are the phrases exactly as the index writes them, so a rendering
cannot quietly attach itself to the wrong saint.
"""
TEXT = {}



# The orders of sanctity, as the badge on a card names them.
TEXT.update({
    "Angelic": "Ασώματοι Δυνάμεις",
    "Apostle": "Απόστολος",
    "Confessor": "Ομολογητής",
    "Equal-to-the-Apostles": "Ισαπόστολος",
    "Feast": "Εορτή",
    "Fool-for-Christ": "Διά Χριστόν σαλός",
    "Great Martyr": "Μεγαλομάρτυς",
    "Hierarch": "Ιεράρχης",
    "Hieromartyr": "Ιερομάρτυς",
    "Martyr": "Μάρτυς",
    "Monastic": "Όσιος",
    "New Martyr": "Νεομάρτυς",
    "Other": "Άλλο",
    "Passion-bearer": "Παθοφόρος",
    "Prophet": "Προφήτης",
    "Righteous": "Δίκαιος",
    "Unmercenary": "Ανάργυρος",
    "Virgin Martyr": "Παρθενομάρτυς",
})


# The attributes a life is marked with.
TEXT.update({
    "Apostle": "Απόστολος",
    "Church Father": "Πατήρ της Εκκλησίας",
    "Confessor": "Ομολογητής",
    "Desert ascetic": "Ασκητής της ερήμου",
    "Enlightener": "Φωτιστής",
    "Fool-for-Christ": "Διά Χριστόν σαλός",
    "Healing intercessor": "Ιαματικός",
    "Hymnographer": "Υμνογράφος",
    "Iconographer": "Αγιογράφος",
    "Incorrupt relics": "Άφθαρτα λείψανα",
    "Monastery founder": "Κτίτωρ μονής",
    "Myrrh-bearer": "Μυροφόρος",
    "Myrrh-streaming": "Μυροβλύτης",
    "New martyr": "Νεομάρτυς",
    "Passion-bearer": "Παθοφόρος",
    "Prophet": "Προφήτης",
    "Ruler or royal": "Ηγεμών ή βασιλικού γένους",
    "Stylite": "Στυλίτης",
    "Unmercenary": "Ανάργυρος",
    "Warrior saint": "Στρατιωτικός άγιος",
    "Wonderworker": "Θαυματουργός",
})


# The ranks the Typikon gives a feast.
TEXT.update({
    "Doxology": "Δοξολογία",
    "Great Feast": "Μεγάλη εορτή",
    "Polyeleos": "Πολυέλεος",
    "Simple": "Απλή",
    "Vigil": "Αγρυπνία",
})


# The jurisdictions whose calendars the index keeps.
TEXT.update({
    "Antiochian": "Αντιοχειανή",
    "Greek": "Ελληνική",
    "OCA": "ΟΕΑ",
    "Romanian": "Ρουμανική",
    "Russian": "Ρωσική",
    "Serbian": "Σερβική",
    "Ukrainian": "Ουκρανική",
})


# The estate a saint stood in.
TEXT.update({
    "Apostolic": "Αποστολική",
    "Clergy": "Κλήρος",
    "Laity": "Λαϊκοί",
    "Layman": "Λαϊκός",
    "Laywoman": "Λαϊκή",
    "Laywomen": "Λαϊκές",
    "Married": "Έγγαμος βίος",
    "Military": "Στρατιωτικός",
    "Monastic": "Μοναχικός",
    "Prophet": "Προφήτης",
    "Royal": "Βασιλικό",
    "Royalty": "Βασιλικό γένος",
    "Unknown": "Άγνωστο",
    "Unmarried": "Αγαμία",
    "Widowed": "Χηρεία",
})


# The ages the lives are set in.
TEXT.update({
    "Age of the Celtic Saints": "Εποχή των Κελτών αγίων",
    "Age of the Ecumenical Councils": "Εποχή των Οικουμενικών Συνόδων",
    "Age of the Martyrs": "Εποχή των Μαρτύρων",
    "Apostolic Age": "Αποστολική εποχή",
    "Byzantine": "Βυζαντινή",
    "Byzantine Balkans": "Βυζαντινά Βαλκάνια",
    "Byzantine Era": "Βυζαντινή εποχή",
    "Byzantine Iconoclasm": "Βυζαντινή εικονομαχία",
    "Cossack Era": "Εποχή των Κοζάκων",
    "Desert Fathers": "Πατέρες της ερήμου",
    "Early Medieval West": "Πρώιμη μεσαιωνική Δύση",
    "Imperial Russia": "Αυτοκρατορική Ρωσία",
    "Kievan Rus'": "Ρωσία του Κιέβου",
    "Medieval Georgia": "Μεσαιωνική Γεωργία",
    "Medieval Rus'": "Μεσαιωνική Ρωσία",
    "Medieval Serbia": "Μεσαιωνική Σερβία",
    "Modern": "Νεότερη",
    "Modern Era": "Νεότερη εποχή",
    "Muscovite Russia": "Ρωσία της Μόσχας",
    "Old Testament": "Παλαιά Διαθήκη",
    "Ottoman Balkans": "Οθωμανικά Βαλκάνια",
    "Ottoman Era": "Οθωμανική εποχή",
    "Ottoman period": "Οθωμανική περίοδος",
    "Polish-Lithuanian period": "Πολωνολιθουανική περίοδος",
    "Soviet Era": "Σοβιετική εποχή",
    "Soviet period": "Σοβιετική περίοδος",
    "Synodal Russia": "Συνοδική Ρωσία",
})


# The countries and the regions.
TEXT.update({
    "Aegean": "Αιγαίο",
    "Albania": "Αλβανία",
    "America": "Αμερική",
    "Arabia": "Αραβία",
    "Armenia": "Αρμενία",
    "Asia Minor": "Μικρά Ασία",
    "Balkans": "Βαλκάνια",
    "Belarus": "Λευκορωσία",
    "Bithynia": "Βιθυνία",
    "Bohemia": "Βοημία",
    "Britain": "Βρετανία",
    "British Isles": "Βρετανικές Νήσοι",
    "Bulgaria": "Βουλγαρία",
    "Cappadocia": "Καππαδοκία",
    "China": "Κίνα",
    "Cilicia": "Κιλικία",
    "Constantinople": "Κωνσταντινούπολη",
    "Crimea": "Κριμαία",
    "Cyprus": "Κύπρος",
    "Czech Lands": "Τσεχικές χώρες",
    "Dalmatia": "Δαλματία",
    "Danube lands": "Παραδουνάβιες χώρες",
    "Egypt": "Αίγυπτος",
    "England": "Αγγλία",
    "Ethiopia": "Αιθιοπία",
    "France": "Γαλλία",
    "Gaul": "Γαλατία",
    "Georgia": "Γεωργία",
    "Greece": "Ελλάδα",
    "Holy Land": "Άγιοι Τόποι",
    "Illyria": "Ιλλυρία",
    "Illyricum": "Ιλλυρικό",
    "India": "Ινδία",
    "Ireland": "Ιρλανδία",
    "Italy": "Ιταλία",
    "Judah": "Ιουδαία",
    "Lithuania": "Λιθουανία",
    "Macedonia": "Μακεδονία",
    "Mesopotamia": "Μεσοποταμία",
    "Moesia": "Μοισία",
    "Moldavia": "Μολδαβία",
    "Montenegro": "Μαυροβούνιο",
    "Moravia": "Μοραβία",
    "Mount Athos": "Άγιον Όρος",
    "North Africa": "Βόρεια Αφρική",
    "North America": "Βόρεια Αμερική",
    "North Macedonia": "Βόρεια Μακεδονία",
    "Palestine": "Παλαιστίνη",
    "Persia": "Περσία",
    "Phoenicia": "Φοινίκη",
    "Poland": "Πολωνία",
    "Pontus": "Πόντος",
    "Romania": "Ρουμανία",
    "Rome": "Ρώμη",
    "Russia": "Ρωσία",
    "Scythia": "Σκυθία",
    "Serbia": "Σερβία",
    "Siberia": "Σιβηρία",
    "Sicily": "Σικελία",
    "Sinai": "Σινά",
    "Spain": "Ισπανία",
    "Syria": "Συρία",
    "Thrace": "Θράκη",
    "Ukraine": "Ουκρανία",
    "United States": "Ηνωμένες Πολιτείες",
    "Western Rus": "Δυτική Ρωσία",
})


# The one movable commemoration the index names.
TEXT.update({
    "Sunday of the Holy Forefathers": "Κυριακή των Αγίων Προπατόρων",
})


# The rank a saint is given.
TEXT.update({
    "Abbess": "Ηγουμένη",
    "Abbot (Archimandrite)": "Ηγούμενος (αρχιμανδρίτης)",
    "Abbot (Founder)": "Ηγούμενος (κτίτωρ)",
    "Abbot (Igumen)": "Ηγούμενος",
    "Abbot (Igumen), Confessor": "Ηγούμενος, ομολογητής",
    "Abbot (Igumen), Hieromartyr": "Ηγούμενος, ιερομάρτυς",
    "Abbot (Igumen), Martyr": "Ηγούμενος, μάρτυς",
    "Abbot (Igumen), Monastic Martyr": "Ηγούμενος, οσιομάρτυς",
    "Abbot, Confessor": "Ηγούμενος, ομολογητής",
    "Abbot, Confessor-Martyr": "Ηγούμενος, ομολογητής και μάρτυς",
    "Abbot, Priest": "Ηγούμενος, ιερεύς",
    "Abbots": "Ηγούμενοι",
    "Anchorite": "Αναχωρητής",
    "Apostle": "Απόστολος",
    "Apostle of the Seventy": "Απόστολος εκ των Εβδομήκοντα",
    "Apostle of the Seventy, Bishop": "Απόστολος εκ των Εβδομήκοντα, επίσκοπος",
    "Apostle of the Seventy, Martyr": "Απόστολος εκ των Εβδομήκοντα, μάρτυς",
    "Apostle, Evangelist": "Απόστολος, ευαγγελιστής",
    "Apostle, Martyr": "Απόστολος, μάρτυς",
    "Apostles": "Απόστολοι",
    "Apostles of the Seventy": "Απόστολοι εκ των Εβδομήκοντα",
    "Apostles of the Seventy, Martyrs": "Απόστολοι εκ των Εβδομήκοντα, μάρτυρες",
    "Archangel": "Αρχάγγελος",
    "Archbishop": "Αρχιεπίσκοπος",
    "Archbishop, Confessor": "Αρχιεπίσκοπος, ομολογητής",
    "Archbishop, Equal-to-the-Apostles": "Αρχιεπίσκοπος, ισαπόστολος",
    "Archdeacon": "Αρχιδιάκονος",
    "Archimandrite": "Αρχιμανδρίτης",
    "Bishop": "Επίσκοπος",
    "Bishop, Church Father": "Επίσκοπος, πατήρ της Εκκλησίας",
    "Bishop, Confessor": "Επίσκοπος, ομολογητής",
    "Bishop, Equal-to-the-Apostles": "Επίσκοπος, ισαπόστολος",
    "Bishop, Hieromartyr": "Επίσκοπος, ιερομάρτυς",
    "Bishop, Monk": "Επίσκοπος, μοναχός",
    "Bishops": "Επίσκοποι",
    "Blessed Eldress": "Μακαρία γερόντισσα",
    "Chamberlain (cubicularius)": "Κουβικουλάριος",
    "Childmartyr": "Παιδομάρτυς",
    "Commander": "Στρατηλάτης",
    "Confessor": "Ομολογητής",
    "Confessor, Archpriest": "Ομολογητής, πρωτοπρεσβύτερος",
    "Deacon": "Διάκονος",
    "Deacon, Monk-martyr": "Διάκονος, οσιομάρτυς",
    "Deaconess": "Διακόνισσα",
    "Deaconess and Martyr": "Διακόνισσα και μάρτυς",
    "Elder": "Γέρων",
    "Empress": "Αυτοκράτειρα",
    "Equal-to-the-Apostles": "Ισαπόστολος",
    "Equal-to-the-Apostles, Emperor": "Ισαπόστολος, αυτοκράτωρ",
    "Equals-to-the-Apostles": "Ισαπόστολοι",
    "Feast": "Εορτή",
    "Fool-for-Christ": "Διά Χριστόν σαλός",
    "Grand Duchess": "Μεγάλη δούκισσα",
    "Grand Prince": "Μέγας ηγεμών",
    "Grand Princess": "Μεγάλη ηγεμονίδα",
    "Great Martyr": "Μεγαλομάρτυς",
    "Great Martyr, Equal-to-the-Apostles": "Μεγαλομάρτυς, ισαπόστολος",
    "Great Prince, Martyr": "Μέγας ηγεμών, μάρτυς",
    "Great-martyr": "Μεγαλομάρτυς",
    "Great-martyr, Prince": "Μεγαλομάρτυς, ηγεμών",
    "Hermit": "Ερημίτης",
    "Hermits": "Ερημίτες",
    "Hierarchs": "Ιεράρχες",
    "Hieromartyr": "Ιερομάρτυς",
    "Hieromartyr (Hermit)": "Ιερομάρτυς (ερημίτης)",
    "Hieromartyr, Apostle": "Ιερομάρτυς, απόστολος",
    "Hieromartyr, Archbishop": "Ιερομάρτυς, αρχιεπίσκοπος",
    "Hieromartyr, Archimandrite": "Ιερομάρτυς, αρχιμανδρίτης",
    "Hieromartyr, Archpriest": "Ιερομάρτυς, πρωτοπρεσβύτερος",
    "Hieromartyr, Bishop": "Ιερομάρτυς, επίσκοπος",
    "Hieromartyr, Confessor": "Ιερομάρτυς, ομολογητής",
    "Hieromartyr, Deacon": "Ιερομάρτυς, διάκονος",
    "Hieromartyr, Patriarch": "Ιερομάρτυς, πατριάρχης",
    "Hieromartyr, Pope": "Ιερομάρτυς, πάπας",
    "Hieromartyr, and his son": "Ιερομάρτυς και ο υιός αυτού",
    "Hieromartyrs": "Ιερομάρτυρες",
    "Hieromonk": "Ιερομόναχος",
    "Hieroschemamonk": "Ιεροσχημόναχος",
    "High Priest": "Αρχιερεύς",
    "Icon of the Mother of God": "Εικόνα της Θεοτόκου",
    "King and Martyr": "Βασιλεύς και μάρτυς",
    "King and Prophet": "Βασιλεύς και προφήτης",
    "Laity": "Λαϊκοί",
    "Layman": "Λαϊκός",
    "Laymen": "Λαϊκοί",
    "Laywoman": "Λαϊκή",
    "Martyr": "Μάρτυς",
    "Martyrs": "Μάρτυρες",
    "Master Builders, Monks": "Αρχιτέκτονες, μοναχοί",
    "Metropolitan": "Μητροπολίτης",
    "Metropolitan, Equal-to-the-Apostles": "Μητροπολίτης, ισαπόστολος",
    "Monastic": "Όσιος",
    "Monastic Martyr": "Οσιομάρτυς",
    "Monastic Martyrs": "Οσιομάρτυρες",
    "Monastic New Martyr": "Οσιονεομάρτυς",
    "Monastics": "Όσιοι",
    "Monk": "Μοναχός",
    "Monk (Founder)": "Μοναχός (κτίτωρ)",
    "Monk (Hermit)": "Μοναχός (ερημίτης)",
    "Monk (elder)": "Μοναχός (γέρων)",
    "Monk (hermit)": "Μοναχός (ερημίτης)",
    "Monk (novice)": "Μοναχός (δόκιμος)",
    "Monk (recluse)": "Μοναχός (έγκλειστος)",
    "Monk (stylite)": "Μοναχός (στυλίτης)",
    "Monk, Church Father": "Μοναχός, πατήρ της Εκκλησίας",
    "Monk, Confessor": "Μοναχός, ομολογητής",
    "Monk, Elder": "Μοναχός, γέρων",
    "Monk, Hymnographer": "Μοναχός, υμνογράφος",
    "Monk, Martyr": "Μοναχός, μάρτυς",
    "Monk, Recluse": "Μοναχός, έγκλειστος",
    "Monk, Unmercenary Physician": "Μοναχός, ανάργυρος ιατρός",
    "Monk, former Great Zhupan": "Μοναχός, πρώην Μέγας Ζουπάνος",
    "Monk-martyr": "Οσιομάρτυς",
    "Monk-martyrs": "Οσιομάρτυρες",
    "Monks": "Μοναχοί",
    "Monks (Founders)": "Μοναχοί (κτίτορες)",
    "Mother": "Μήτηρ",
    "Myrrhbearer": "Μυροφόρος",
    "New Martyr": "Νεομάρτυς",
    "New Martyrs": "Νεομάρτυρες",
    "New Martyrs and Confessors": "Νεομάρτυρες και ομολογητές",
    "Nun": "Μοναχή",
    "Nun-martyr": "Οσιομάρτυς",
    "Passion-bearer": "Παθοφόρος",
    "Patriarch": "Πατριάρχης",
    "Patriarch, Church Father": "Πατριάρχης, πατήρ της Εκκλησίας",
    "Patriarch, Confessor": "Πατριάρχης, ομολογητής",
    "Patriarch, Hieromartyr": "Πατριάρχης, ιερομάρτυς",
    "Physician": "Ιατρός",
    "Physicians": "Ιατροί",
    "Pope": "Πάπας",
    "Pope of Rome, Confessor": "Πάπας Ρώμης, ομολογητής",
    "Presbyter and Deacon": "Πρεσβύτερος και διάκονος",
    "Presbyters, Confessors": "Πρεσβύτεροι, ομολογητές",
    "Priest": "Ιερεύς",
    "Prince": "Ηγεμών",
    "Prince of Moldavia": "Ηγεμών της Μολδαβίας",
    "Prince, Passion-Bearer": "Ηγεμών, παθοφόρος",
    "Princes": "Ηγεμόνες",
    "Princess": "Ηγεμονίδα",
    "Princess, Nun": "Ηγεμονίδα, μοναχή",
    "Proconsul (military commander)": "Ανθύπατος (στρατηλάτης)",
    "Prophet": "Προφήτης",
    "Prophet and Forerunner": "Προφήτης και Πρόδρομος",
    "Prophetess": "Προφήτις",
    "Protomartyr": "Πρωτομάρτυς",
    "Protopresbyter": "Πρωτοπρεσβύτερος",
    "Recluse": "Έγκλειστος",
    "Right-believing Prince": "Ευσεβής ηγεμών",
    "Right-believing Prince (Monk)": "Ευσεβής ηγεμών (μοναχός)",
    "Right-believing Prince and Princess": "Ευσεβείς ηγεμών και ηγεμονίδα",
    "Right-believing Prince, Passion-bearer": "Ευσεβής ηγεμών, παθοφόρος",
    "Right-believing Princess (Nun)": "Ευσεβής ηγεμονίδα (μοναχή)",
    "Right-believing Princess, Martyr": "Ευσεβής ηγεμονίδα, μάρτυς",
    "Righteous": "Δίκαιος",
    "Righteous (Child)": "Δίκαιος (παιδίον)",
    "Righteous (Children)": "Δίκαιοι (παιδία)",
    "Righteous (Unmercenary)": "Δίκαιος (ανάργυρος)",
    "Righteous Forefather": "Δίκαιος προπάτωρ",
    "Righteous Virgin": "Δικαία παρθένος",
    "Righteous, Priest": "Δίκαιος, ιερεύς",
    "Roman soldier": "Ρωμαίος στρατιώτης",
    "Schemamonk": "Μεγαλόσχημος μοναχός",
    "Stylite": "Στυλίτης",
    "Synaxis": "Σύναξις",
    "Tsar and Imperial Family": "Τσάρος και η αυτοκρατορική οικογένεια",
    "Unmercenary Martyrs": "Ανάργυροι μάρτυρες",
    "Venerable": "Όσιος",
    "Venerable Prince": "Όσιος ηγεμών",
    "Venerable Princess": "Οσία ηγεμονίδα",
    "Virgin": "Παρθένος",
    "Virgin Martyr": "Παρθενομάρτυς",
    "Virgin Martyrs": "Παρθενομάρτυρες",
    "Virgin-martyr": "Παρθενομάρτυς",
    "Youths": "Παίδες",
})
