# -*- coding: utf-8 -*-
"""Greek for the vocabulary that stands beside the lives.

TEXT = {the phrase the index shows: the Greek}. PARTS holds the pieces the
compound place-names are built from, and expand() assembles the wholes, so a
town cannot be spelled one way on one card and another way on the next.

Greek is the tongue the greater part of this vocabulary was first said in,
and where that is so the phrase goes home rather than being carried across:
the orders of sanctity, the ranks of the Typikon, the ancient sees and the
provinces of the Christian East are given as the Greek Church gives them,
not as renderings of the English renderings of them. The Slavic, Georgian
and Latin names take the forms the Greek synaxaria have received, and where
no received form exists the name is transliterated.

The keys are the phrases exactly as the index writes them, so a rendering
cannot quietly attach itself to the wrong saint.
"""
TEXT = {}



# The orders of sanctity, as the badge on a card names them.
TEXT.update({
    "Angelic": "Ασώματοι Δυνάμεις",
    "Apostle": "Απόστολος",
    "Confessor": "Ομολογητής",
    "Equal-to-the-Apostles": "Ισαπόστολος",
    "Feast": "Εορτή",
    "Fool-for-Christ": "Διά Χριστόν σαλός",
    "Great Martyr": "Μεγαλομάρτυς",
    "Hierarch": "Ιεράρχης",
    "Hieromartyr": "Ιερομάρτυς",
    "Martyr": "Μάρτυς",
    "Monastic": "Όσιος",
    "New Martyr": "Νεομάρτυς",
    "Other": "Άλλο",
    "Passion-bearer": "Παθοφόρος",
    "Prophet": "Προφήτης",
    "Righteous": "Δίκαιος",
    "Unmercenary": "Ανάργυρος",
    "Virgin Martyr": "Παρθενομάρτυς",
})


# The attributes a life is marked with.
TEXT.update({
    "Apostle": "Απόστολος",
    "Church Father": "Πατήρ της Εκκλησίας",
    "Confessor": "Ομολογητής",
    "Desert ascetic": "Ασκητής της ερήμου",
    "Enlightener": "Φωτιστής",
    "Fool-for-Christ": "Διά Χριστόν σαλός",
    "Healing intercessor": "Ιαματικός",
    "Hymnographer": "Υμνογράφος",
    "Iconographer": "Αγιογράφος",
    "Incorrupt relics": "Άφθαρτα λείψανα",
    "Monastery founder": "Κτίτωρ μονής",
    "Myrrh-bearer": "Μυροφόρος",
    "Myrrh-streaming": "Μυροβλύτης",
    "New martyr": "Νεομάρτυς",
    "Passion-bearer": "Παθοφόρος",
    "Prophet": "Προφήτης",
    "Ruler or royal": "Ηγεμών ή βασιλικού γένους",
    "Stylite": "Στυλίτης",
    "Unmercenary": "Ανάργυρος",
    "Warrior saint": "Στρατιωτικός άγιος",
    "Wonderworker": "Θαυματουργός",
})


# The ranks the Typikon gives a feast.
TEXT.update({
    "Doxology": "Δοξολογία",
    "Great Feast": "Μεγάλη εορτή",
    "Polyeleos": "Πολυέλεος",
    "Simple": "Απλή",
    "Vigil": "Αγρυπνία",
})


# The jurisdictions whose calendars the index keeps.
TEXT.update({
    "Antiochian": "Αντιοχειανή",
    "Greek": "Ελληνική",
    "OCA": "ΟΕΑ",
    "Romanian": "Ρουμανική",
    "Russian": "Ρωσική",
    "Serbian": "Σερβική",
    "Ukrainian": "Ουκρανική",
})


# The estate a saint stood in.
TEXT.update({
    "Apostolic": "Αποστολική",
    "Clergy": "Κλήρος",
    "Laity": "Λαϊκοί",
    "Layman": "Λαϊκός",
    "Laywoman": "Λαϊκή",
    "Laywomen": "Λαϊκές",
    "Married": "Έγγαμος βίος",
    "Military": "Στρατιωτικός",
    "Monastic": "Μοναχικός",
    "Prophet": "Προφήτης",
    "Royal": "Βασιλικό",
    "Royalty": "Βασιλικό γένος",
    "Unknown": "Άγνωστο",
    "Unmarried": "Αγαμία",
    "Widowed": "Χηρεία",
})


# The ages the lives are set in.
TEXT.update({
    "Age of the Celtic Saints": "Εποχή των Κελτών αγίων",
    "Age of the Ecumenical Councils": "Εποχή των Οικουμενικών Συνόδων",
    "Age of the Martyrs": "Εποχή των Μαρτύρων",
    "Apostolic Age": "Αποστολική εποχή",
    "Byzantine": "Βυζαντινή",
    "Byzantine Balkans": "Βυζαντινά Βαλκάνια",
    "Byzantine Era": "Βυζαντινή εποχή",
    "Byzantine Iconoclasm": "Βυζαντινή εικονομαχία",
    "Cossack Era": "Εποχή των Κοζάκων",
    "Desert Fathers": "Πατέρες της ερήμου",
    "Early Medieval West": "Πρώιμη μεσαιωνική Δύση",
    "Imperial Russia": "Αυτοκρατορική Ρωσία",
    "Kievan Rus'": "Ρωσία του Κιέβου",
    "Medieval Georgia": "Μεσαιωνική Γεωργία",
    "Medieval Rus'": "Μεσαιωνική Ρωσία",
    "Medieval Serbia": "Μεσαιωνική Σερβία",
    "Modern": "Νεότερη",
    "Modern Era": "Νεότερη εποχή",
    "Muscovite Russia": "Ρωσία της Μόσχας",
    "Old Testament": "Παλαιά Διαθήκη",
    "Ottoman Balkans": "Οθωμανικά Βαλκάνια",
    "Ottoman Era": "Οθωμανική εποχή",
    "Ottoman period": "Οθωμανική περίοδος",
    "Polish-Lithuanian period": "Πολωνολιθουανική περίοδος",
    "Soviet Era": "Σοβιετική εποχή",
    "Soviet period": "Σοβιετική περίοδος",
    "Synodal Russia": "Συνοδική Ρωσία",
})


# The countries and the regions.
TEXT.update({
    "Aegean": "Αιγαίο",
    "Albania": "Αλβανία",
    "America": "Αμερική",
    "Arabia": "Αραβία",
    "Armenia": "Αρμενία",
    "Asia Minor": "Μικρά Ασία",
    "Balkans": "Βαλκάνια",
    "Belarus": "Λευκορωσία",
    "Bithynia": "Βιθυνία",
    "Bohemia": "Βοημία",
    "Britain": "Βρετανία",
    "British Isles": "Βρετανικές Νήσοι",
    "Bulgaria": "Βουλγαρία",
    "Cappadocia": "Καππαδοκία",
    "China": "Κίνα",
    "Cilicia": "Κιλικία",
    "Constantinople": "Κωνσταντινούπολη",
    "Crimea": "Κριμαία",
    "Cyprus": "Κύπρος",
    "Czech Lands": "Τσεχικές χώρες",
    "Dalmatia": "Δαλματία",
    "Danube lands": "Παραδουνάβιες χώρες",
    "Egypt": "Αίγυπτος",
    "England": "Αγγλία",
    "Ethiopia": "Αιθιοπία",
    "France": "Γαλλία",
    "Gaul": "Γαλατία",
    "Georgia": "Γεωργία",
    "Greece": "Ελλάδα",
    "Holy Land": "Άγιοι Τόποι",
    "Illyria": "Ιλλυρία",
    "Illyricum": "Ιλλυρικό",
    "India": "Ινδία",
    "Ireland": "Ιρλανδία",
    "Italy": "Ιταλία",
    "Judah": "Ιουδαία",
    "Lithuania": "Λιθουανία",
    "Macedonia": "Μακεδονία",
    "Mesopotamia": "Μεσοποταμία",
    "Moesia": "Μοισία",
    "Moldavia": "Μολδαβία",
    "Montenegro": "Μαυροβούνιο",
    "Moravia": "Μοραβία",
    "Mount Athos": "Άγιον Όρος",
    "North Africa": "Βόρεια Αφρική",
    "North America": "Βόρεια Αμερική",
    "North Macedonia": "Βόρεια Μακεδονία",
    "Palestine": "Παλαιστίνη",
    "Persia": "Περσία",
    "Phoenicia": "Φοινίκη",
    "Poland": "Πολωνία",
    "Pontus": "Πόντος",
    "Romania": "Ρουμανία",
    "Rome": "Ρώμη",
    "Russia": "Ρωσία",
    "Scythia": "Σκυθία",
    "Serbia": "Σερβία",
    "Siberia": "Σιβηρία",
    "Sicily": "Σικελία",
    "Sinai": "Σινά",
    "Spain": "Ισπανία",
    "Syria": "Συρία",
    "Thrace": "Θράκη",
    "Ukraine": "Ουκρανία",
    "United States": "Ηνωμένες Πολιτείες",
    "Western Rus": "Δυτική Ρωσία",
})


# The one movable commemoration the index names.
TEXT.update({
    "Sunday of the Holy Forefathers": "Κυριακή των Αγίων Προπατόρων",
})


# The rank a saint is given.
TEXT.update({
    "Abbess": "Ηγουμένη",
    "Abbot (Archimandrite)": "Ηγούμενος (αρχιμανδρίτης)",
    "Abbot (Founder)": "Ηγούμενος (κτίτωρ)",
    "Abbot (Igumen)": "Ηγούμενος",
    "Abbot (Igumen), Confessor": "Ηγούμενος, ομολογητής",
    "Abbot (Igumen), Hieromartyr": "Ηγούμενος, ιερομάρτυς",
    "Abbot (Igumen), Martyr": "Ηγούμενος, μάρτυς",
    "Abbot (Igumen), Monastic Martyr": "Ηγούμενος, οσιομάρτυς",
    "Abbot, Confessor": "Ηγούμενος, ομολογητής",
    "Abbot, Confessor-Martyr": "Ηγούμενος, ομολογητής και μάρτυς",
    "Abbot, Priest": "Ηγούμενος, ιερεύς",
    "Abbots": "Ηγούμενοι",
    "Anchorite": "Αναχωρητής",
    "Apostle": "Απόστολος",
    "Apostle of the Seventy": "Απόστολος εκ των Εβδομήκοντα",
    "Apostle of the Seventy, Bishop": "Απόστολος εκ των Εβδομήκοντα, επίσκοπος",
    "Apostle of the Seventy, Martyr": "Απόστολος εκ των Εβδομήκοντα, μάρτυς",
    "Apostle, Evangelist": "Απόστολος, ευαγγελιστής",
    "Apostle, Martyr": "Απόστολος, μάρτυς",
    "Apostles": "Απόστολοι",
    "Apostles of the Seventy": "Απόστολοι εκ των Εβδομήκοντα",
    "Apostles of the Seventy, Martyrs": "Απόστολοι εκ των Εβδομήκοντα, μάρτυρες",
    "Archangel": "Αρχάγγελος",
    "Archbishop": "Αρχιεπίσκοπος",
    "Archbishop, Confessor": "Αρχιεπίσκοπος, ομολογητής",
    "Archbishop, Equal-to-the-Apostles": "Αρχιεπίσκοπος, ισαπόστολος",
    "Archdeacon": "Αρχιδιάκονος",
    "Archimandrite": "Αρχιμανδρίτης",
    "Bishop": "Επίσκοπος",
    "Bishop, Church Father": "Επίσκοπος, πατήρ της Εκκλησίας",
    "Bishop, Confessor": "Επίσκοπος, ομολογητής",
    "Bishop, Equal-to-the-Apostles": "Επίσκοπος, ισαπόστολος",
    "Bishop, Hieromartyr": "Επίσκοπος, ιερομάρτυς",
    "Bishop, Monk": "Επίσκοπος, μοναχός",
    "Bishops": "Επίσκοποι",
    "Blessed Eldress": "Μακαρία γερόντισσα",
    "Chamberlain (cubicularius)": "Κουβικουλάριος",
    "Childmartyr": "Παιδομάρτυς",
    "Commander": "Στρατηλάτης",
    "Confessor": "Ομολογητής",
    "Confessor, Archpriest": "Ομολογητής, πρωτοπρεσβύτερος",
    "Deacon": "Διάκονος",
    "Deacon, Monk-martyr": "Διάκονος, οσιομάρτυς",
    "Deaconess": "Διακόνισσα",
    "Deaconess and Martyr": "Διακόνισσα και μάρτυς",
    "Elder": "Γέρων",
    "Empress": "Αυτοκράτειρα",
    "Equal-to-the-Apostles": "Ισαπόστολος",
    "Equal-to-the-Apostles, Emperor": "Ισαπόστολος, αυτοκράτωρ",
    "Equals-to-the-Apostles": "Ισαπόστολοι",
    "Feast": "Εορτή",
    "Fool-for-Christ": "Διά Χριστόν σαλός",
    "Grand Duchess": "Μεγάλη δούκισσα",
    "Grand Prince": "Μέγας ηγεμών",
    "Grand Princess": "Μεγάλη ηγεμονίδα",
    "Great Martyr": "Μεγαλομάρτυς",
    "Great Martyr, Equal-to-the-Apostles": "Μεγαλομάρτυς, ισαπόστολος",
    "Great Prince, Martyr": "Μέγας ηγεμών, μάρτυς",
    "Great-martyr": "Μεγαλομάρτυς",
    "Great-martyr, Prince": "Μεγαλομάρτυς, ηγεμών",
    "Hermit": "Ερημίτης",
    "Hermits": "Ερημίτες",
    "Hierarchs": "Ιεράρχες",
    "Hieromartyr": "Ιερομάρτυς",
    "Hieromartyr (Hermit)": "Ιερομάρτυς (ερημίτης)",
    "Hieromartyr, Apostle": "Ιερομάρτυς, απόστολος",
    "Hieromartyr, Archbishop": "Ιερομάρτυς, αρχιεπίσκοπος",
    "Hieromartyr, Archimandrite": "Ιερομάρτυς, αρχιμανδρίτης",
    "Hieromartyr, Archpriest": "Ιερομάρτυς, πρωτοπρεσβύτερος",
    "Hieromartyr, Bishop": "Ιερομάρτυς, επίσκοπος",
    "Hieromartyr, Confessor": "Ιερομάρτυς, ομολογητής",
    "Hieromartyr, Deacon": "Ιερομάρτυς, διάκονος",
    "Hieromartyr, Patriarch": "Ιερομάρτυς, πατριάρχης",
    "Hieromartyr, Pope": "Ιερομάρτυς, πάπας",
    "Hieromartyr, and his son": "Ιερομάρτυς και ο υιός αυτού",
    "Hieromartyrs": "Ιερομάρτυρες",
    "Hieromonk": "Ιερομόναχος",
    "Hieroschemamonk": "Ιεροσχημόναχος",
    "High Priest": "Αρχιερεύς",
    "Icon of the Mother of God": "Εικόνα της Θεοτόκου",
    "King and Martyr": "Βασιλεύς και μάρτυς",
    "King and Prophet": "Βασιλεύς και προφήτης",
    "Laity": "Λαϊκοί",
    "Layman": "Λαϊκός",
    "Laymen": "Λαϊκοί",
    "Laywoman": "Λαϊκή",
    "Martyr": "Μάρτυς",
    "Martyrs": "Μάρτυρες",
    "Master Builders, Monks": "Αρχιτέκτονες, μοναχοί",
    "Metropolitan": "Μητροπολίτης",
    "Metropolitan, Equal-to-the-Apostles": "Μητροπολίτης, ισαπόστολος",
    "Monastic": "Όσιος",
    "Monastic Martyr": "Οσιομάρτυς",
    "Monastic Martyrs": "Οσιομάρτυρες",
    "Monastic New Martyr": "Οσιονεομάρτυς",
    "Monastics": "Όσιοι",
    "Monk": "Μοναχός",
    "Monk (Founder)": "Μοναχός (κτίτωρ)",
    "Monk (Hermit)": "Μοναχός (ερημίτης)",
    "Monk (elder)": "Μοναχός (γέρων)",
    "Monk (hermit)": "Μοναχός (ερημίτης)",
    "Monk (novice)": "Μοναχός (δόκιμος)",
    "Monk (recluse)": "Μοναχός (έγκλειστος)",
    "Monk (stylite)": "Μοναχός (στυλίτης)",
    "Monk, Church Father": "Μοναχός, πατήρ της Εκκλησίας",
    "Monk, Confessor": "Μοναχός, ομολογητής",
    "Monk, Elder": "Μοναχός, γέρων",
    "Monk, Hymnographer": "Μοναχός, υμνογράφος",
    "Monk, Martyr": "Μοναχός, μάρτυς",
    "Monk, Recluse": "Μοναχός, έγκλειστος",
    "Monk, Unmercenary Physician": "Μοναχός, ανάργυρος ιατρός",
    "Monk, former Great Zhupan": "Μοναχός, πρώην Μέγας Ζουπάνος",
    "Monk-martyr": "Οσιομάρτυς",
    "Monk-martyrs": "Οσιομάρτυρες",
    "Monks": "Μοναχοί",
    "Monks (Founders)": "Μοναχοί (κτίτορες)",
    "Mother": "Μήτηρ",
    "Myrrhbearer": "Μυροφόρος",
    "New Martyr": "Νεομάρτυς",
    "New Martyrs": "Νεομάρτυρες",
    "New Martyrs and Confessors": "Νεομάρτυρες και ομολογητές",
    "Nun": "Μοναχή",
    "Nun-martyr": "Οσιομάρτυς",
    "Passion-bearer": "Παθοφόρος",
    "Patriarch": "Πατριάρχης",
    "Patriarch, Church Father": "Πατριάρχης, πατήρ της Εκκλησίας",
    "Patriarch, Confessor": "Πατριάρχης, ομολογητής",
    "Patriarch, Hieromartyr": "Πατριάρχης, ιερομάρτυς",
    "Physician": "Ιατρός",
    "Physicians": "Ιατροί",
    "Pope": "Πάπας",
    "Pope of Rome, Confessor": "Πάπας Ρώμης, ομολογητής",
    "Presbyter and Deacon": "Πρεσβύτερος και διάκονος",
    "Presbyters, Confessors": "Πρεσβύτεροι, ομολογητές",
    "Priest": "Ιερεύς",
    "Prince": "Ηγεμών",
    "Prince of Moldavia": "Ηγεμών της Μολδαβίας",
    "Prince, Passion-Bearer": "Ηγεμών, παθοφόρος",
    "Princes": "Ηγεμόνες",
    "Princess": "Ηγεμονίδα",
    "Princess, Nun": "Ηγεμονίδα, μοναχή",
    "Proconsul (military commander)": "Ανθύπατος (στρατηλάτης)",
    "Prophet": "Προφήτης",
    "Prophet and Forerunner": "Προφήτης και Πρόδρομος",
    "Prophetess": "Προφήτις",
    "Protomartyr": "Πρωτομάρτυς",
    "Protopresbyter": "Πρωτοπρεσβύτερος",
    "Recluse": "Έγκλειστος",
    "Right-believing Prince": "Ευσεβής ηγεμών",
    "Right-believing Prince (Monk)": "Ευσεβής ηγεμών (μοναχός)",
    "Right-believing Prince and Princess": "Ευσεβείς ηγεμών και ηγεμονίδα",
    "Right-believing Prince, Passion-bearer": "Ευσεβής ηγεμών, παθοφόρος",
    "Right-believing Princess (Nun)": "Ευσεβής ηγεμονίδα (μοναχή)",
    "Right-believing Princess, Martyr": "Ευσεβής ηγεμονίδα, μάρτυς",
    "Righteous": "Δίκαιος",
    "Righteous (Child)": "Δίκαιος (παιδίον)",
    "Righteous (Children)": "Δίκαιοι (παιδία)",
    "Righteous (Unmercenary)": "Δίκαιος (ανάργυρος)",
    "Righteous Forefather": "Δίκαιος προπάτωρ",
    "Righteous Virgin": "Δικαία παρθένος",
    "Righteous, Priest": "Δίκαιος, ιερεύς",
    "Roman soldier": "Ρωμαίος στρατιώτης",
    "Schemamonk": "Μεγαλόσχημος μοναχός",
    "Stylite": "Στυλίτης",
    "Synaxis": "Σύναξις",
    "Tsar and Imperial Family": "Τσάρος και η αυτοκρατορική οικογένεια",
    "Unmercenary Martyrs": "Ανάργυροι μάρτυρες",
    "Venerable": "Όσιος",
    "Venerable Prince": "Όσιος ηγεμών",
    "Venerable Princess": "Οσία ηγεμονίδα",
    "Virgin": "Παρθένος",
    "Virgin Martyr": "Παρθενομάρτυς",
    "Virgin Martyrs": "Παρθενομάρτυρες",
    "Virgin-martyr": "Παρθενομάρτυς",
    "Youths": "Παίδες",
})


# How a saint came to be numbered among the saints.
TEXT.update({
    "Ancient commemoration of the Church": "Αρχαία μνήμη της Εκκλησίας",
    "Ancient commemoration of the universal Church": "Αρχαία μνήμη της καθόλου Εκκλησίας",
    "Ancient observance of the Church": "Αρχαία τήρηση της Εκκλησίας",
    "Ancient observance of the universal Church": "Αρχαία τήρηση της καθόλου Εκκλησίας",
    "Church of Greece, glorified in 1921": "Εκκλησία της Ελλάδος, αγιοκατάταξη το 1921",
    "Church of Rus'": "Εκκλησία της Ρωσίας",
    "Church of Rus', among the fathers of the Caves": "Εκκλησία της Ρωσίας, μεταξύ των πατέρων των Σπηλαίων",
    "Church of Rus', glorified in 1108": "Εκκλησία της Ρωσίας, αγιοκατάταξη το 1108",
    "Church of Rus'; the common synaxis established for the whole company": "Εκκλησία της Ρωσίας· η κοινή σύναξη θεσπίστηκε για ολόκληρη τη χορεία",
    "Constantinople, under Patriarch Philotheos, within a generation of their death": "Κωνσταντινούπολη, επί πατριάρχου Φιλοθέου, μέσα σε μία γενεά από τον θάνατό τους",
    "Ecumenical Patriarchate": "Οικουμενικό Πατριαρχείο",
    "Ecumenical Patriarchate of Constantinople": "Οικουμενικό Πατριαρχείο Κωνσταντινουπόλεως",
    "Ecumenical Patriarchate of Constantinople, 1961": "Οικουμενικό Πατριαρχείο Κωνσταντινουπόλεως, 1961",
    "Ecumenical Patriarchate of Constantinople, 2015": "Οικουμενικό Πατριαρχείο Κωνσταντινουπόλεως, 2015",
    "Ecumenical Patriarchate of Constantinople, 2019": "Οικουμενικό Πατριαρχείο Κωνσταντινουπόλεως, 2019",
    "Ecumenical Patriarchate, 1703": "Οικουμενικό Πατριαρχείο, 1703",
    "Ecumenical Patriarchate, 1734": "Οικουμενικό Πατριαρχείο, 1734",
    "Ecumenical Patriarchate, 1961": "Οικουμενικό Πατριαρχείο, 1961",
    "Ecumenical Patriarchate, 1987": "Οικουμενικό Πατριαρχείο, 1987",
    "Ecumenical Patriarchate, November 27, 2013": "Οικουμενικό Πατριαρχείο, 27 Νοεμβρίου 2013",
    "Established by the Church at the restoration of the icons in 843": "Θεσπίστηκε από την Εκκλησία κατά την αναστήλωση των εικόνων το 843",
    "Established by the Church in thanksgiving for the deliverances of Constantinople": "Θεσπίστηκε από την Εκκλησία σε ευχαριστία για τις σωτηρίες της Κωνσταντινουπόλεως",
    "Established by the Church of Constantinople": "Θεσπίστηκε από την Εκκλησία της Κωνσταντινουπόλεως",
    "Established by the Russian Orthodox Church in 1964": "Θεσπίστηκε από τη Ρωσική Ορθόδοξη Εκκλησία το 1964",
    "Established by the observance of the Church": "Θεσπίστηκε από την τήρηση της Εκκλησίας",
    "Feast of the Church": "Εορτή της Εκκλησίας",
    "Feast of the Church of Rus'": "Εορτή της Εκκλησίας της Ρωσίας",
    "Feast of the Church, kept with especial devotion in the churches of Rus'": "Εορτή της Εκκλησίας, τηρούμενη με ιδιαίτερη ευλάβεια στις εκκλησίες της Ρωσίας",
    "Feast of the Russian Orthodox Church": "Εορτή της Ρωσικής Ορθόδοξης Εκκλησίας",
    "Feast of the Serbian Orthodox Church": "Εορτή της Σερβικής Ορθόδοξης Εκκλησίας",
    "Georgian Orthodox Church": "Γεωργιανή Ορθόδοξη Εκκλησία",
    "Glorified August 9, 1970, the first glorification on American soil": "Αγιοκατάταξη στις 9 Αυγούστου 1970, η πρώτη αγιοκατάταξη σε αμερικανικό έδαφος",
    "Glorified December 18, 1694, at Merkushino": "Αγιοκατάταξη στις 18 Δεκεμβρίου 1694, στο Μερκούσινο",
    "Glorified among the New Martyrs and Confessors of Russia by the Russian Orthodox Church": "Αγιοκατάταξη μεταξύ των Νεομαρτύρων και Ομολογητών της Ρωσίας από τη Ρωσική Ορθόδοξη Εκκλησία",
    "Glorified among the New Martyrs and Confessors of Russia by the Russian Orthodox Church in 2000": "Αγιοκατάταξη μεταξύ των Νεομαρτύρων και Ομολογητών της Ρωσίας από τη Ρωσική Ορθόδοξη Εκκλησία το 2000",
    "Glorified among the saints; his veneration embraced by the Churches of Constantinople and Rus'": "Αγιοκατάταξη μεταξύ των αγίων· η τιμή του έγινε δεκτή από τις Εκκλησίες της Κωνσταντινουπόλεως και της Ρωσίας",
    "Glorified by the Autocephalous Orthodox Church of Poland in 2003, among the New Martyrs of Chelm and Podlasie": "Αγιοκατάταξη από την Αυτοκέφαλη Ορθόδοξη Εκκλησία της Πολωνίας το 2003, μεταξύ των Νεομαρτύρων του Χελμ και του Ποντλάσιε",
    "Glorified by the Orthodox Church in America in 1994 at Saint Tikhon's monastery": "Αγιοκατάταξη από την Ορθόδοξη Εκκλησία στην Αμερική το 1994 στη μονή του Αγίου Τύχωνος",
    "Glorified by the Romanian Orthodox Church": "Αγιοκατάταξη από τη Ρουμανική Ορθόδοξη Εκκλησία",
    "Glorified by the Russian Orthodox Church": "Αγιοκατάταξη από τη Ρωσική Ορθόδοξη Εκκλησία",
    "Glorified by the Russian Orthodox Church in 1547": "Αγιοκατάταξη από τη Ρωσική Ορθόδοξη Εκκλησία το 1547",
    "Glorified by the Russian Orthodox Church in 1558": "Αγιοκατάταξη από τη Ρωσική Ορθόδοξη Εκκλησία το 1558",
    "Glorified by the Russian Orthodox Church in 1650; veneration restored in 1909": "Αγιοκατάταξη από τη Ρωσική Ορθόδοξη Εκκλησία το 1650· η τιμή αποκαταστάθηκε το 1909",
    "Glorified by the Russian Orthodox Church in 1916": "Αγιοκατάταξη από τη Ρωσική Ορθόδοξη Εκκλησία το 1916",
    "Glorified by the Russian Orthodox Church in 1989": "Αγιοκατάταξη από τη Ρωσική Ορθόδοξη Εκκλησία το 1989",
    "Glorified by the Russian Orthodox Church on May 12, 1913": "Αγιοκατάταξη από τη Ρωσική Ορθόδοξη Εκκλησία στις 12 Μαΐου 1913",
    "Glorified by the Russian Orthodox Church, locally in 1999 and for the whole Church in 2004": "Αγιοκατάταξη από τη Ρωσική Ορθόδοξη Εκκλησία, τοπικά το 1999 και για ολόκληρη την Εκκλησία το 2004",
    "Glorified in 1339, the first saint of Moscow": "Αγιοκατάταξη το 1339, ο πρώτος άγιος της Μόσχας",
    "Glorified in 2000": "Αγιοκατάταξη το 2000",
    "His veneration, springing from the revelation of 1950, was formally recognized by the Great Church of Christ": "Η τιμή του, που πήγασε από την αποκάλυψη του 1950, αναγνωρίστηκε επισήμως από τη Μεγάλη του Χριστού Εκκλησία",
    "Instituted by the Church of Constantinople": "Θεσπίστηκε από την Εκκλησία της Κωνσταντινουπόλεως",
    "Local veneration": "Τοπική τιμή",
    "Local veneration (glorified 1071)": "Τοπική τιμή (αγιοκατάταξη το 1071)",
    "Local veneration at the Murom monastery": "Τοπική τιμή στη μονή του Μουρόμ",
    "Local veneration in the Church of Rus'": "Τοπική τιμή στην Εκκλησία της Ρωσίας",
    "Local veneration of the Kyiv Caves": "Τοπική τιμή των Σπηλαίων του Κιέβου",
    "Local veneration of the Kyiv Caves; in the canon of the Caves fathers": "Τοπική τιμή των Σπηλαίων του Κιέβου· στον κανόνα των πατέρων των Σπηλαίων",
    "Numbered among the New Martyrs venerated by the Church": "Συγκαταλέγεται μεταξύ των Νεομαρτύρων που τιμά η Εκκλησία",
    "Numbered among the New Martyrs venerated by the Church of Greece": "Συγκαταλέγεται μεταξύ των Νεομαρτύρων που τιμά η Εκκλησία της Ελλάδος",
    "Numbered among the saints of Mount Athos": "Συγκαταλέγεται μεταξύ των αγίων του Αγίου Όρους",
    "Orthodox Church in America": "Ορθόδοξη Εκκλησία στην Αμερική",
    "Orthodox Church in America, 1980": "Ορθόδοξη Εκκλησία στην Αμερική, 1980",
    "Orthodox Church in America, 1994": "Ορθόδοξη Εκκλησία στην Αμερική, 1994",
    "Orthodox Church in America; glorified at Kwethluk, June 19, 2025": "Ορθόδοξη Εκκλησία στην Αμερική· αγιοκατάταξη στο Κουέθλουκ, 19 Ιουνίου 2025",
    "Orthodox Church, 1659": "Ορθόδοξη Εκκλησία, 1659",
    "Patriarchate of Antioch, 1993": "Πατριαρχείο Αντιοχείας, 1993",
    "Pre-congregational veneration": "Τιμή από αρχαιοτάτων χρόνων",
    "Pre-congregational veneration; Equals-to-the-Apostles": "Τιμή από αρχαιοτάτων χρόνων· ισαπόστολοι",
    "Pre-congregational veneration; among the first saints of Rus": "Τιμή από αρχαιοτάτων χρόνων· μεταξύ των πρώτων αγίων της Ρωσίας",
    "Pre-congregational veneration; glorified by miracles": "Τιμή από αρχαιοτάτων χρόνων· επιβεβαιωμένη με θαύματα",
    "Pre-congregational veneration; venerated as patron of Moldavia": "Τιμή από αρχαιοτάτων χρόνων· τιμάται ως προστάτης της Μολδαβίας",
    "Pre-congregational veneration; vindicated by the Sixth Ecumenical Council": "Τιμή από αρχαιοτάτων χρόνων· δικαιώθηκε από την Έκτη Οικουμενική Σύνοδο",
    "Prophet of the Old Covenant": "Προφήτης της Παλαιάς Διαθήκης",
    "Recognized among the New Martyrs by the Great Church of Christ": "Συγκαταλέχθηκε μεταξύ των Νεομαρτύρων από τη Μεγάλη του Χριστού Εκκλησία",
    "Recognized among the New Martyrs venerated in the Church of Greece": "Συγκαταλέχθηκε μεταξύ των Νεομαρτύρων που τιμώνται στην Εκκλησία της Ελλάδος",
    "Romanian Orthodox Church, 1992": "Ρουμανική Ορθόδοξη Εκκλησία, 1992",
    "Romanian Orthodox Church, 2008": "Ρουμανική Ορθόδοξη Εκκλησία, 2008",
    "Romanian Orthodox Church, glorified in 1955": "Ρουμανική Ορθόδοξη Εκκλησία, αγιοκατάταξη το 1955",
    "Russian Church Abroad, 1994": "Ρωσική Εκκλησία της Διασποράς, 1994",
    "Russian Orthodox Church": "Ρωσική Ορθόδοξη Εκκλησία",
    "Russian Orthodox Church, 1108": "Ρωσική Ορθόδοξη Εκκλησία, 1108",
    "Russian Orthodox Church, 1448": "Ρωσική Ορθόδοξη Εκκλησία, 1448",
    "Russian Orthodox Church, 1467": "Ρωσική Ορθόδοξη Εκκλησία, 1467",
    "Russian Orthodox Church, 1544 (local veneration)": "Ρωσική Ορθόδοξη Εκκλησία, 1544 (τοπική τιμή)",
    "Russian Orthodox Church, 1547": "Ρωσική Ορθόδοξη Εκκλησία, 1547",
    "Russian Orthodox Church, 1549": "Ρωσική Ορθόδοξη Εκκλησία, 1549",
    "Russian Orthodox Church, 1579": "Ρωσική Ορθόδοξη Εκκλησία, 1579",
    "Russian Orthodox Church, 1591": "Ρωσική Ορθόδοξη Εκκλησία, 1591",
    "Russian Orthodox Church, 1595": "Ρωσική Ορθόδοξη Εκκλησία, 1595",
    "Russian Orthodox Church, 1597": "Ρωσική Ορθόδοξη Εκκλησία, 1597",
    "Russian Orthodox Church, 1645": "Ρωσική Ορθόδοξη Εκκλησία, 1645",
    "Russian Orthodox Church, 1646": "Ρωσική Ορθόδοξη Εκκλησία, 1646",
    "Russian Orthodox Church, 1649": "Ρωσική Ορθόδοξη Εκκλησία, 1649",
    "Russian Orthodox Church, 1650; veneration restored 1909": "Ρωσική Ορθόδοξη Εκκλησία, 1650· η τιμή αποκαταστάθηκε το 1909",
    "Russian Orthodox Church, 1652": "Ρωσική Ορθόδοξη Εκκλησία, 1652",
    "Russian Orthodox Church, 1659": "Ρωσική Ορθόδοξη Εκκλησία, 1659",
    "Russian Orthodox Church, 1664": "Ρωσική Ορθόδοξη Εκκλησία, 1664",
    "Russian Orthodox Church, 1687": "Ρωσική Ορθόδοξη Εκκλησία, 1687",
    "Russian Orthodox Church, 1698": "Ρωσική Ορθόδοξη Εκκλησία, 1698",
    "Russian Orthodox Church, 1757": "Ρωσική Ορθόδοξη Εκκλησία, 1757",
    "Russian Orthodox Church, 1798": "Ρωσική Ορθόδοξη Εκκλησία, 1798",
    "Russian Orthodox Church, 1800": "Ρωσική Ορθόδοξη Εκκλησία, 1800",
    "Russian Orthodox Church, 1804": "Ρωσική Ορθόδοξη Εκκλησία, 1804",
    "Russian Orthodox Church, 1832": "Ρωσική Ορθόδοξη Εκκλησία, 1832",
    "Russian Orthodox Church, 1861": "Ρωσική Ορθόδοξη Εκκλησία, 1861",
    "Russian Orthodox Church, 1896": "Ρωσική Ορθόδοξη Εκκλησία, 1896",
    "Russian Orthodox Church, 1903": "Ρωσική Ορθόδοξη Εκκλησία, 1903",
    "Russian Orthodox Church, 1911": "Ρωσική Ορθόδοξη Εκκλησία, 1911",
    "Russian Orthodox Church, 1913": "Ρωσική Ορθόδοξη Εκκλησία, 1913",
    "Russian Orthodox Church, 1914": "Ρωσική Ορθόδοξη Εκκλησία, 1914",
    "Russian Orthodox Church, 1978": "Ρωσική Ορθόδοξη Εκκλησία, 1978",
    "Russian Orthodox Church, 1988": "Ρωσική Ορθόδοξη Εκκλησία, 1988",
    "Russian Orthodox Church, 1994": "Ρωσική Ορθόδοξη Εκκλησία, 1994",
    "Russian Orthodox Church, 2000": "Ρωσική Ορθόδοξη Εκκλησία, 2000",
    "Russian Orthodox Church, December 4, 1994": "Ρωσική Ορθόδοξη Εκκλησία, 4 Δεκεμβρίου 1994",
    "Russian Orthodox Church, Jubilee Council of 2000; earlier by the Russian Church Abroad, 1981": "Ρωσική Ορθόδοξη Εκκλησία, Ιωβηλαία Σύνοδος του 2000· νωρίτερα από τη Ρωσική Εκκλησία της Διασποράς, 1981",
    "Russian Orthodox Church, October 6, 1977": "Ρωσική Ορθόδοξη Εκκλησία, 6 Οκτωβρίου 1977",
    "Russian Orthodox Church, October 9, 1989": "Ρωσική Ορθόδοξη Εκκλησία, 9 Οκτωβρίου 1989",
    "Russian Orthodox Church, September 4, 1911": "Ρωσική Ορθόδοξη Εκκλησία, 4 Σεπτεμβρίου 1911",
    "Russian Orthodox Church, at the Council of 1547": "Ρωσική Ορθόδοξη Εκκλησία, στη Σύνοδο του 1547",
    "Russian Orthodox Church, at the Council of 1549": "Ρωσική Ορθόδοξη Εκκλησία, στη Σύνοδο του 1549",
    "Russian Orthodox Church, at the Moscow Council of 1549": "Ρωσική Ορθόδοξη Εκκλησία, στη Σύνοδο της Μόσχας του 1549",
    "Russian Orthodox Church, c. 1452": "Ρωσική Ορθόδοξη Εκκλησία, περ. 1452",
    "Russian Orthodox Church, commemoration established at the Council of 1547": "Ρωσική Ορθόδοξη Εκκλησία, η μνήμη θεσπίστηκε στη Σύνοδο του 1547",
    "Russian Orthodox Church, commemoration established at the Council of 1549": "Ρωσική Ορθόδοξη Εκκλησία, η μνήμη θεσπίστηκε στη Σύνοδο του 1549",
    "Russian Orthodox Church, glorified at the end of the sixteenth century": "Ρωσική Ορθόδοξη Εκκλησία, αγιοκατάταξη στα τέλη του δέκατου έκτου αιώνα",
    "Russian Orthodox Church, glorified in 1595": "Ρωσική Ορθόδοξη Εκκλησία, αγιοκατάταξη το 1595",
    "Russian Orthodox Church, glorified in 1820": "Ρωσική Ορθόδοξη Εκκλησία, αγιοκατάταξη το 1820",
    "Russian Orthodox Church, glorified in 1918": "Ρωσική Ορθόδοξη Εκκλησία, αγιοκατάταξη το 1918",
    "Russian Orthodox Church, glorified in 1977": "Ρωσική Ορθόδοξη Εκκλησία, αγιοκατάταξη το 1977",
    "Russian Orthodox Church, glorified in 2000": "Ρωσική Ορθόδοξη Εκκλησία, αγιοκατάταξη το 2000",
    "Russian Orthodox Church, local veneration": "Ρωσική Ορθόδοξη Εκκλησία, τοπική τιμή",
    "Russian Orthodox Church; commemoration restored in 1888": "Ρωσική Ορθόδοξη Εκκλησία· η μνήμη αποκαταστάθηκε το 1888",
    "Russian Orthodox Church; local veneration from 1715": "Ρωσική Ορθόδοξη Εκκλησία· τοπική τιμή από το 1715",
    "Serbian Orthodox Church": "Σερβική Ορθόδοξη Εκκλησία",
    "Serbian Orthodox Church, 1961": "Σερβική Ορθόδοξη Εκκλησία, 1961",
    "Serbian Orthodox Church, May 15, 2005": "Σερβική Ορθόδοξη Εκκλησία, 15 Μαΐου 2005",
    "Serbian Orthodox Church, May 29, 2015": "Σερβική Ορθόδοξη Εκκλησία, 29 Μαΐου 2015",
    "Serbian Orthodox Church, glorified in 2003": "Σερβική Ορθόδοξη Εκκλησία, αγιοκατάταξη το 2003",
    "Serbian Orthodox Church; venerated among the first saints of the Serbian lands": "Σερβική Ορθόδοξη Εκκλησία· τιμάται μεταξύ των πρώτων αγίων των σερβικών χωρών",
    "Serbian and Bulgarian Orthodox Churches": "Σερβική και Βουλγαρική Ορθόδοξη Εκκλησία",
    "Ukrainian Orthodox Church, 2001": "Ουκρανική Ορθόδοξη Εκκλησία, 2001",
    "Veneration established by the Russian Orthodox Church": "Η τιμή θεσπίστηκε από τη Ρωσική Ορθόδοξη Εκκλησία",
    "Veneration established in the Russian Orthodox Church": "Η τιμή θεσπίστηκε στη Ρωσική Ορθόδοξη Εκκλησία",
    "Veneration established on the Holy Mountain": "Η τιμή θεσπίστηκε στο Άγιον Όρος",
})


# The name a saint bore in the world.
TEXT.update({
    "Abraham": "Αβραάμ",
    "Alexander": "Αλέξανδρος",
    "Alexi": "Αλέξι",
    "Alexios": "Αλέξιος",
    "Alexis": "Αλέξιος",
    "Amos": "Αμώς",
    "Anastasios Kephalas": "Αναστάσιος Κεφαλάς",
    "Andrei": "Αντρέι",
    "Andrew": "Ανδρέας",
    "Anna": "Άννα",
    "Antipas": "Αντίπας",
    "Arsenios": "Αρσένιος",
    "Bartholomew": "Βαρθολομαίος",
    "Basil": "Βασίλειος",
    "Constantin Antonescu": "Κωνσταντίν Αντωνέσκου",
    "Constantine": "Κωνσταντίνος",
    "Constantine and Michael": "Κωνσταντίνος και Μιχαήλ",
    "Daniel": "Δανιήλ",
    "David": "Δαβίδ",
    "Diamantes": "Διαμαντής",
    "Diomedes": "Διομήδης",
    "Draganigos": "Δραγανίγος",
    "Eleutherios": "Ελευθέριος",
    "Eleutherius": "Ελευθέριος",
    "Elias": "Ηλίας",
    "Eudokia": "Ευδοκία",
    "Eusebia": "Ευσεβία",
    "Eustathius": "Ευστάθιος",
    "Evangelos": "Ευάγγελος",
    "Feodor": "Φεντόρ",
    "Feodor Kolychev": "Φεντόρ Κολίτσεφ",
    "Gabriel": "Γαβριήλ",
    "George": "Γεώργιος",
    "Georgios Angelopoulos": "Γεώργιος Αγγελόπουλος",
    "Gregory": "Γρηγόριος",
    "Helen": "Ελένη",
    "Irene": "Ειρήνη",
    "Ivan": "Ιβάν",
    "Ivan (John) Zhelezo": "Ιβάν (Ιωάννης) Ζελέζο",
    "Ivan Popov-Veniaminov": "Ιβάν Ποπόφ-Βενιαμίνοφ",
    "Joachim": "Ιωακείμ",
    "John": "Ιωάννης",
    "Joseph": "Ιωσήφ",
    "Jovan (John)": "Γιόβαν (Ιωάννης)",
    "Konon": "Κόνων",
    "Konstas": "Κώνστας",
    "Kosmas": "Κοσμάς",
    "Kumets, Nezhilo, and Kruglets": "Κούμετς, Νεζίλο και Κρούγκλετς",
    "Manuel": "Μανουήλ",
    "Mary": "Μαρία",
    "Matrona Dimitrievna Nikonova": "Ματρώνα Ντμίτριεβνα Νικόνοβα",
    "Matthew": "Ματθαίος",
    "Matthew Kozhin": "Ματθαίος Κόζιν",
    "Matthias": "Ματθίας",
    "Menas": "Μηνάς",
    "Michael": "Μιχαήλ",
    "Michael Trivolis": "Μιχαήλ Τριβώλης",
    "Mitrofan": "Μιτροφάν",
    "Neanius": "Νεάνιος",
    "Nicetas": "Νικήτας",
    "Nicholas": "Νικόλαος",
    "Nicholas Maikov": "Νικόλαος Μάικοφ",
    "Nikola Velimirovich": "Νικόλα Βελιμίροβιτς",
    "Nikon": "Νίκων",
    "Olga": "Όλγα",
    "Otar": "Οτάρ",
    "Parthenius": "Παρθένιος",
    "Penelope": "Πηνελόπη",
    "Peter": "Πέτρος",
    "Predislav": "Πρεντισλάβ",
    "Predslava": "Πρεντσλάβα",
    "Procopius": "Προκόπιος",
    "Prokhor": "Πρόχορος",
    "Rastko": "Ράστκο",
    "Reprebus": "Ρέπρεβος",
    "Roman and David": "Ρωμανός και Δαβίδ",
    "Romanus and David": "Ρωμανός και Δαβίδ",
    "Saul": "Σαύλος",
    "Semyon": "Σεμιόν",
    "Sergei": "Σεργκέι",
    "Sergius": "Σέργιος",
    "Simeon": "Συμεών",
    "Simon": "Σίμων",
    "Solomonia": "Σολομονία",
    "Stefan Kristalevsky": "Στέφαν Κρισταλέφσκι",
    "Stephen Nemanja": "Στέφανος Νεμάνια",
    "Stojan Jovanovic": "Στόγιαν Γιοβάνοβιτς",
    "Tarasius": "Ταράσιος",
    "Thekla": "Θέκλα",
    "Theodore": "Θεόδωρος",
    "Theodulia": "Θεοδουλία",
    "Theophilus": "Θεόφιλος",
    "Timothy": "Τιμόθεος",
    "Valentin": "Βαλεντίνος",
    "Vasily": "Βασίλι",
    "Vasily Ivanovich Bellavin": "Βασίλι Ιβάνοβιτς Μπελλάβιν",
    "Vasily Muravyov": "Βασίλι Μουράβιοφ",
    "Victorinus": "Βικτωρίνος",
    "Vojislav": "Βόισλαβ",
    "Yaroslav": "Γιαροσλάβ",
    "Yermolai": "Ερμόλαος",
})


# The places, which are not a list but a grammar: a card names a town, a
# province and a country in one line, and the same town appears on twenty
# other cards inside a different line. The pieces are rendered once here and
# the wholes are assembled from them, so a town cannot be spelled one way on
# one card and another way on the next.
PARTS = {}

def expand(phrases):
    """The compounds, assembled from the parts above."""
    out = {}
    for p in phrases:
        bits = p.split(", ")
        if all(b in PARTS for b in bits):
            out[p] = ", ".join(PARTS[b] for b in bits)
    return out


# The places, first part.
PARTS.update({
    "Abel-meholah": "Αβελμαουλά",
    "Abkhazeti": "Αμπχαζέτι",
    "Achaia": "Αχαΐα",
    "Adamovka": "Αντάμοβκα",
    "Adrianople": "Αδριανούπολη",
    "Adrianopolis": "Αδριανούπολις",
    "Aegae": "Αιγαί",
    "Aegean": "Αιγαίο",
    "Aegina": "Αίγινα",
    "Aetolia": "Αιτωλία",
    "Africa": "Αφρική",
    "Agrigentum": "Ακράγας",
    "Akhaltsikhe": "Αχαλτσίχε",
    "Aksum": "Αξούμ",
    "Alaska": "Αλάσκα",
    "Albania": "Αλβανία",
    "Albanopolis": "Αλβανόπολις",
    "Aleppo": "Χαλέπι",
    "Alexandria": "Αλεξάνδρεια",
    "All America": "Όλη η Αμερική",
    "Amasea": "Αμάσεια",
    "Amasia": "Αμάσεια",
    "Amastridea": "Αμάστριδα",
    "Amastris": "Άμαστρις",
    "Amathus": "Αμαθούς",
    "America": "Αμερική",
    "Amida": "Άμιδα",
    "Amisos": "Αμισός",
    "Amisus": "Αμισός",
    "Amnia": "Άμνια",
    "Amorion": "Αμόριον",
    "Amphipolis": "Αμφίπολη",
    "Anaplus": "Άναπλους",
    "Anastasiopolis": "Αναστασιούπολις",
    "Anathoth": "Αναθώθ",
    "Anatolia": "Ανατολία",
    "Anazarbus": "Ανάζαρβος",
    "Ancyra": "Άγκυρα",
    "Andronikov Monastery": "Μονή Αντρόνικωφ",
    "Anga": "Άνγκα",
    "Annesi": "Άννησα",
    "Annisa": "Άννησα",
    "Antinoe": "Αντινόη",
    "Antioch": "Αντιόχεια",
    "Antioch in Pisidia": "Αντιόχεια της Πισιδίας",
    "Antioch of Pisidia": "Αντιόχεια της Πισιδίας",
    "Anzersk": "Ανζέρσκ",
    "Anzersk Island": "Νήσος Ανζέρσκ",
    "Apamea": "Απάμεια",
    "Aphrodisias": "Αφροδισιάς",
    "Apollonia": "Απολλωνία",
    "Apulia": "Απουλία",
    "Aquileia": "Ακυληία",
    "Arabia": "Αραβία",
    "Arabian Desert": "Αραβική έρημος",
    "Arauraka": "Αραυράκα",
    "Arbela": "Άρβηλα",
    "Archangel Gabriel": "Αρχάγγελος Γαβριήλ",
    "Arethusa": "Αρέθουσα",
    "Argos": "Άργος",
    "Arianzus": "Αριανζός",
    "Arkhangelsk": "Αρχάγγελσκ",
    "Arkhangelsk lands": "Χώρες του Αρχάγγελσκ",
    "Armagh": "Άρμαγκ",
    "Armenia": "Αρμενία",
    "Armenia Minor": "Μικρά Αρμενία",
    "Arsinoe": "Αρσινόη",
    "Arta": "Άρτα",
    "Artanuji": "Αρτανούτζι",
    "Ascalon": "Ασκάλων",
    "Asia Minor": "Μικρά Ασία",
    "Asikha": "Ασίχα",
    "Athens": "Αθήνα",
    "Atka Island": "Νήσος Άτκα",
    "Atskuri": "Ατσκούρι",
    "Atsquri": "Ατσκούρι",
    "Attica": "Αττική",
    "Auleneia": "Αυλήνεια",
    "Auxerre": "Οσέρ",
    "Avnezh": "Αβνέζ",
    "Babylon": "Βαβυλώνα",
    "Balkans": "Βαλκάνια",
    "Barcelona": "Βαρκελώνη",
    "Bari": "Μπάρι",
    "Basarbov": "Μπασάρμποβο",
    "Beauvais": "Μποβέ",
    "Beirut": "Βηρυτός",
    "Belarus": "Λευκορωσία",
    "Belev": "Μπελέφ",
    "Belgorod": "Μπέλγκοροντ",
    "Belgorod (Akkerman)": "Μπέλγκοροντ (Ακέρμαν)",
    "Belgrade": "Βελιγράδι",
    "Belozersk": "Μπελοζέρσκ",
    "Belozersk lands": "Χώρες του Μπελοζέρσκ",
    "Belozersk lands and Mozhaisk": "Χώρες του Μπελοζέρσκ και Μοζάισκ",
    "Benevento": "Μπενεβέντο",
    "Beocin Monastery": "Μονή Μπέοτσιν",
    "Berezan": "Μπερεζάν",
    "Berezniko": "Μπερεζνίκο",
    "Beroea": "Βέροια",
    "Besanduc": "Βεσαντούκ",
    "Bethany": "Βηθανία",
    "Bethel": "Βαιθήλ",
    "Bethlapeta": "Βηθλαπέτα",
    "Bethlehem": "Βηθλεέμ",
    "Bethsaida": "Βηθσαϊδά",
    "Bethsaloe": "Βηθσαλόη",
    "Bezhetsk lands": "Χώρες του Μπεζέτσκ",
    "Bialystok": "Μπιάλιστοκ",
    "Bisericani Monastery": "Μονή Μπισερικάνι",
    "Bithynia": "Βιθυνία",
    "Blachernae": "Βλαχέρνες",
    "Black Lake": "Μαύρη Λίμνη",
    "Black Sea coast": "Ακτή του Ευξείνου Πόντου",
    "Bodbe": "Μπόντμπε",
    "Boeotia": "Βοιωτία",
    "Bogolyubovo": "Μπογκολιούμποβο",
    "Bohemia": "Βοημία",
    "Bolgar": "Μπολγκάρ",
    "Borovichi": "Μποροβιτσί",
})


# The places, second part.
PARTS.update({
    "Borovsk": "Μπορόφσκ",
    "Bosnia": "Βοσνία",
    "Boston": "Βοστώνη",
    "Bostra": "Βόστρα",
    "Braunton": "Μπράουντον",
    "Brest": "Μπρεστ",
    "Briansk": "Μπριάνσκ",
    "Britain": "Βρετανία",
    "British Isles": "Βρετανικές Νήσοι",
    "Brooklyn": "Μπρούκλιν",
    "Bryansk": "Μπριάνσκ",
    "Bucharest": "Βουκουρέστι",
    "Budimlje": "Μπούντιμλιε",
    "Bulgaria": "Βουλγαρία",
    "Butovo": "Μπούτοβο",
    "Buzau Mountains": "Όρη Μπουζέου",
    "Byblos": "Βύβλος",
    "Byzantine Empire": "Βυζαντινή Αυτοκρατορία",
    "Byzantium": "Βυζάντιο",
    "Byzantium (Constantinople)": "Βυζάντιο (Κωνσταντινούπολη)",
    "Caesarea": "Καισάρεια",
    "Caesarea Maritima": "Καισάρεια της Παλαιστίνης",
    "Caesarea in Cappadocia": "Καισάρεια της Καππαδοκίας",
    "California": "Καλιφόρνια",
    "Campania": "Καμπανία",
    "Cana": "Κανά",
    "Cana of Galilee": "Κανά της Γαλιλαίας",
    "Canaan": "Χαναάν",
    "Canopus": "Κάνωβος",
    "Capernaum": "Καπερναούμ",
    "Cappadocia": "Καππαδοκία",
    "Caria": "Καρία",
    "Carpathian Rus'": "Καρπαθορωσία",
    "Carpatho-Russia": "Καρπαθορωσία",
    "Carthage": "Καρχηδόνα",
    "Catania": "Κατάνη",
    "Cephalonia": "Κεφαλονιά",
    "Cernica": "Τσερνίκα",
    "Cernica Monastery": "Μονή Τσερνίκα",
    "Chalcedon": "Χαλκηδόνα",
    "Chalcis": "Χαλκίδα",
    "Chalcis desert": "Έρημος της Χαλκίδος",
    "Chelm": "Χελμ",
    "Chelma Hill": "Λόφος Τσέλμα",
    "Cherepovets": "Τσερεποβέτς",
    "Chernigov": "Τσερνίγκοφ",
    "Chernigov lands": "Χώρες του Τσερνίγκοφ",
    "Chernihiv": "Τσερνίχιφ",
    "Chernihiv lands": "Χώρες του Τσερνίχιφ",
    "Cherson": "Χερσών",
    "Chersonesus": "Χερσόνησος",
    "Chicago": "Σικάγο",
    "China": "Κίνα",
    "Chios": "Χίος",
    "Chonae": "Χώναι",
    "Choziba": "Χοζεβά",
    "Chukhloma": "Τσουχλομά",
    "Cilicia": "Κιλικία",
    "Claudiopolis": "Κλαυδιούπολις",
    "Colophon": "Κολοφών",
    "Colossae": "Κολοσσαί",
    "Coma": "Κόμα",
    "Comana": "Κόμανα",
    "Constantia": "Κωνσταντία",
    "Constantinople": "Κωνσταντινούπολη",
    "Cordoba": "Κόρδοβα",
    "Corfu": "Κέρκυρα",
    "Corinth": "Κόρινθος",
    "Corsica": "Κορσική",
    "Cotyaeum": "Κοτυάειον",
    "Crete": "Κρήτη",
    "Crimea": "Κριμαία",
    "Cucomo": "Κούκομο",
    "Cucusus": "Κουκουσός",
    "Cyprus": "Κύπρος",
    "Cyrene": "Κυρήνη",
    "Cyrenia": "Κερύνεια",
    "Cyrrhus": "Κύρρος",
    "Cyzicus": "Κύζικος",
    "Czech Lands": "Τσεχικές χώρες",
    "Dabuda": "Δαβούδα",
    "Dalmatia": "Δαλματία",
    "Dalmatian Monastery": "Μονή Δαλμάτου",
    "Damascus": "Δαμασκός",
    "Danube lands": "Παραδουνάβιες χώρες",
    "David Gareji": "Νταβίντ Γκαρέτζι",
    "Davit-Gareji": "Νταβίτ-Γκαρέτζι",
    "Decapolis": "Δεκάπολις",
    "Decapolis of Isauria": "Δεκάπολις της Ισαυρίας",
    "Demetsana": "Δημητσάνα",
    "Demitsana": "Δημητσάνα",
    "Desert beyond the Jordan": "Έρημος πέραν του Ιορδάνου",
    "Devich": "Ντέβιτς",
    "Devon": "Ντέβον",
    "Dimitsana": "Δημητσάνα",
    "Dioclea": "Διόκλεια",
    "Dioclea (Duklja)": "Διόκλεια (Ντούκλια)",
    "Disevi": "Ντισέβι",
    "Diveyevo": "Ντιβέγιεβο",
    "Dobrogea": "Δοβρουτσά",
    "Dorostolum": "Δορύστολον",
    "Dorostolum (Silistra)": "Δορύστολον (Σιλίστρα)",
    "Drenica": "Ντρένιτσα",
    "Durostorum": "Δορύστολον",
    "Dymsk": "Ντιμσκ",
    "Dymskoe Lake": "Λίμνη Ντίμσκογιε",
    "East Anglia": "Ανατολική Αγγλία",
    "Edessa": "Έδεσσα",
    "Edra": "Έδρα",
    "Egypt": "Αίγυπτος",
    "Egyptian Desert": "Αιγυπτιακή έρημος",
    "Elbasan": "Ελμπασάν",
    "Eleutheropolis": "Ελευθερόπολις",
    "Elkosh": "Ελκές",
    "Emesa": "Έμεσα",
    "England": "Αγγλία",
    "Ephesus": "Έφεσος",
    "Epirus": "Ήπειρος",
    "Epivato": "Επιβάται",
    "Essex": "Έσσεξ",
})


# The places, third part.
PARTS.update({
    "Ethiopia": "Αιθιοπία",
    "Euboea": "Εύβοια",
    "Euchaita": "Ευχάιτα",
    "Euroea": "Ευρόη",
    "European Russia": "Ευρωπαϊκή Ρωσία",
    "Evia": "Εύβοια",
    "Ferapontov": "Φεραπόντωφ",
    "Ferapontov Monastery": "Μονή Φεραπόντωφ",
    "Ferapontovo": "Φεραπόντοβο",
    "Feremane": "Φερεμάνη",
    "Ferentino": "Φερεντίνο",
    "Flavia Neapolis": "Φλαβία Νεάπολις",
    "Florishchi": "Φλορίστσι",
    "Formia": "Φορμία",
    "France": "Γαλλία",
    "Frasinei": "Φρασινέι",
    "Galata": "Γαλατάς",
    "Galatia": "Γαλατία",
    "Galich": "Γκάλιτς",
    "Galicia": "Γαλικία",
    "Galilee": "Γαλιλαία",
    "Gangra": "Γάγγρα",
    "Gareji": "Γκαρέτζι",
    "Gary": "Γκάρι",
    "Gath-hepher": "Γεθχοφέρ",
    "Gaul": "Γαλατία",
    "Gaza": "Γάζα",
    "Gdov": "Γκντοφ",
    "Gdov lands": "Χώρες του Γκντοφ",
    "George Hill": "Λόφος του Αγίου Γεωργίου",
    "Georgia": "Γεωργία",
    "Germany": "Γερμανία",
    "Gibeah of Phinehas": "Γαβαά του Φινεές",
    "Gilead": "Γαλαάδ",
    "Glendalough": "Γκλενταλόχ",
    "Glushitsa": "Γκλουσίτσα",
    "Gori district": "Περιφέρεια Γκόρι",
    "Gortyna": "Γόρτυνα",
    "Gothia": "Γοτθία",
    "Gothic lands": "Γοτθικές χώρες",
    "Great Lavra": "Μεγίστη Λαύρα",
    "Great Lavra of Saint Sabbas": "Μεγάλη Λαύρα του Αγίου Σάββα",
    "Great Moravia": "Μεγάλη Μοραβία",
    "Greece": "Ελλάδα",
    "Guria": "Γκουρία",
    "Hartland": "Χάρτλαντ",
    "Hauran": "Χαυράν",
    "Hebron": "Χεβρών",
    "Heliopolis": "Ηλιούπολις",
    "Hellas": "Ελλάς",
    "Hellespont": "Ελλήσποντος",
    "Heraclea": "Ηράκλεια",
    "Hereti": "Χερέτι",
    "Hermopolis": "Ερμούπολις",
    "Herzegovina": "Ερζεγοβίνη",
    "Hierapolis": "Ιεράπολις",
    "Hilandar": "Χιλανδάρι",
    "Holy Land": "Άγιοι Τόποι",
    "Holy Trinity-Saint Sergius Lavra": "Λαύρα της Αγίας Τριάδος και του Αγίου Σεργίου",
    "Hosios Loukas": "Όσιος Λουκάς",
    "Hungary": "Ουγγαρία",
    "Hypaepa": "Ύπαιπα",
    "Iași": "Ιάσιο",
    "Iconium": "Ικόνιο",
    "Iken": "Άικεν",
    "Illinois": "Ιλινόις",
    "Illyria": "Ιλλυρία",
    "Illyricum": "Ιλλυρικό",
    "India": "Ινδία",
    "Indiana": "Ιντιάνα",
    "Ioannina": "Ιωάννινα",
    "Irap": "Ιράπ",
    "Ireland": "Ιρλανδία",
    "Irenopolis": "Ειρηνούπολις",
    "Irkutsk": "Ιρκούτσκ",
    "Irkutsk province": "Επαρχία Ιρκούτσκ",
    "Isauria": "Ισαυρία",
    "Israel": "Ισραήλ",
    "Italy": "Ιταλία",
    "Iza": "Ίζα",
    "Jackson": "Τζάκσον",
    "Jerusalem": "Ιερουσαλήμ",
    "Joppa": "Ιόππη",
    "Jordan River": "Ποταμός Ιορδάνης",
    "Judah": "Ιουδαία",
    "Judea": "Ιουδαία",
    "Judean Desert": "Έρημος της Ιουδαίας",
    "Judean Wilderness": "Έρημος της Ιουδαίας",
    "Kallippi": "Καλλίππη",
    "Kaluga": "Καλούγκα",
    "Kaluga lands": "Χώρες της Καλούγκα",
    "Kalyazin": "Καλιάζιν",
    "Kampsada": "Καμψάδα",
    "Kaniv": "Κάνιφ",
    "Karelia": "Καρελία",
    "Kargopol": "Καργκοπόλ",
    "Kargopol lands": "Χώρες του Καργκοπόλ",
    "Kartli": "Καρτλί",
    "Kartli (Iberia)": "Καρτλί (Ιβηρία)",
    "Kashin": "Κάσιν",
    "Kasperovo": "Κασπέροβο",
    "Kastoria": "Καστοριά",
    "Kastorion": "Καστόριον",
    "Kavsokalyvia": "Καυσοκαλύβια",
    "Kazan": "Καζάν",
    "Kekhta": "Κέχτα",
    "Kellia": "Κελλία",
    "Keno Lake": "Λίμνη Κένο",
    "Kerch": "Κερτς",
    "Kerkyra": "Κέρκυρα",
    "Kerkyra (Corfu)": "Κέρκυρα",
    "Khakhuli": "Χαχούλι",
    "Khakhuli Monastery": "Μονή Χαχούλι",
    "Kharkiv": "Χάρκοβο",
    "Kherson": "Χερσώνα",
    "Kherson lands": "Χώρες της Χερσώνας",
    "Khlynov": "Χλίνοφ",
    "Kholm": "Χολμ",
    "Khust": "Χουστ",
    "Khutyn": "Χούτιν",
})


# The places, fourth part.
PARTS.update({
    "Kios": "Κίος",
    "Klarjeti": "Κλαρτζέτι",
    "Klops Monastery": "Μονή Κλοπς",
    "Kodiak": "Κόντιακ",
    "Kola": "Κόλα",
    "Komel": "Κομέλ",
    "Komel Forest": "Δάσος του Κομέλ",
    "Kondakovo": "Κοντάκοβο",
    "Konevets": "Κόνεβετς",
    "Korets": "Κόρετς",
    "Korissos": "Κόρισσος",
    "Kornet": "Κορνέτ",
    "Korotsk": "Κορότσκ",
    "Kosinsk": "Κόσινσκ",
    "Kosovo": "Κοσσυφοπέδιο",
    "Kostroma": "Κοστρομά",
    "Kostroma lands": "Χώρες της Κοστρομά",
    "Kozelshchyna": "Κοζελστσίνα",
    "Kozelsk": "Κοζέλσκ",
    "Kozhe Lake": "Λίμνη Κόζε",
    "Krasny Kholm": "Κράσνι Χολμ",
    "Kratovo": "Κράτοβο",
    "Kremenets": "Κρεμενέτς",
    "Kromna": "Κρώμνα",
    "Kronstadt": "Κρονστάνδη",
    "Krushedol": "Κρούσεντολ",
    "Kubensk": "Κούμπενσκ",
    "Kudinovo": "Κουντίνοβο",
    "Kursk": "Κουρσκ",
    "Kushta": "Κούστα",
    "Kvabtakhevi Monastery": "Μονή Κβαμπταχέβι",
    "Kveli fortress": "Φρούριο Κβέλι",
    "Kwethluk": "Κουέθλουκ",
    "Kyiv": "Κίεβο",
    "Kyiv Caves": "Σπήλαια του Κιέβου",
    "Kyiv Caves Lavra": "Λαύρα των Σπηλαίων του Κιέβου",
    "Kyiv Far Caves": "Απώτερα Σπήλαια του Κιέβου",
    "Kyiv Near Caves": "Εγγύτερα Σπήλαια του Κιέβου",
    "Kyiv region": "Περιοχή του Κιέβου",
    "Laconia": "Λακωνία",
    "Lake Iliamna": "Λίμνη Ιλιάμνα",
    "Lake Ilmen": "Λίμνη Ίλμεν",
    "Lake Ilo": "Λίμνη Ίλο",
    "Lake Kubenskoye": "Λίμνη Κούμπενσκογιε",
    "Lake Ladoga": "Λίμνη Λαντόγκα",
    "Lake Onega": "Λίμνη Ονέγκα",
    "Lake Orta": "Λίμνη Όρτα",
    "Lake Pskov": "Λίμνη του Πσκοφ",
    "Lake Seliger": "Λίμνη Σελιγκέρ",
    "Lake Vorbozomsk": "Λίμνη Βορμποζόμσκ",
    "Lampsacus": "Λάμψακος",
    "Land of Asher": "Γη του Ασήρ",
    "Land of Uz": "Γη Αυσίτις",
    "Land of Zebulun": "Γη του Ζαβουλών",
    "Land of the tribe of Simeon": "Γη της φυλής του Συμεών",
    "Langres": "Λανγκρ",
    "Laodicea": "Λαοδίκεια",
    "Lavra of Saint Sabbas": "Λαύρα του Αγίου Σάββα",
    "Lazica": "Λαζική",
    "Le Mans": "Λε Μαν",
    "Lebanon": "Λίβανος",
    "Leinster": "Λένστερ",
    "Lelich": "Λέλιτς",
    "Lentini": "Λεντίνι",
    "Leokhnovo": "Λεόχνοβο",
    "Leontini": "Λεοντίνοι",
    "Lesbos": "Λέσβος",
    "Leucosia (Nicosia)": "Λευκωσία",
    "Lezna River": "Ποταμός Λέζνα",
    "Libertyville": "Λίμπερτιβιλ",
    "Libya": "Λιβύη",
    "Lindisfarne": "Λίντισφαρν",
    "Lipari": "Λίπαρι",
    "Lithuania": "Λιθουανία",
    "Little Russia (Ukraine)": "Μικρή Ρωσία (Ουκρανία)",
    "Liubech": "Λιούμπετς",
    "Liubimograd": "Λιουμπίμογκραντ",
    "Loma": "Λόμα",
    "Loutraki": "Λουτράκι",
    "Lubny": "Λούμπνι",
    "Lubyatov": "Λιουμπιάτοβο",
    "Lucania": "Λευκανία",
    "Lukhov": "Λούχοφ",
    "Lycaonia": "Λυκαονία",
    "Lycia": "Λυκία",
    "Lycopolis": "Λυκόπολις",
    "Lydda": "Λύδδα",
    "Lydia": "Λυδία",
    "Lykaonia": "Λυκαονία",
    "Lyons": "Λυών",
    "Lystra": "Λύστρα",
    "Lérins": "Λερίνος",
    "Macedonia": "Μακεδονία",
    "Magdala": "Μάγδαλα",
    "Magedon": "Μαγεδών",
    "Magnesia": "Μαγνησία",
    "Magydos": "Μάγυδος",
    "Maiuma": "Μαϊουμάς",
    "Makarovo": "Μακάροβο",
    "Makhrishche": "Μαχρίστσε",
    "Malopinega": "Μαλοπινέγκα",
    "Malta": "Μάλτα",
    "Mandera": "Μανδέρα",
    "Mangup": "Μανγκούπ",
    "Mantinea": "Μαντίνεια",
    "Mar Saba": "Μαρ Σάμπα",
    "Maratha": "Μαράθα",
    "Marathon": "Μαραθώνας",
    "Marcianopolis": "Μαρκιανούπολις",
    "Marikat": "Μαρικάτ",
    "Marseilles": "Μασσαλία",
    "Martyropolis": "Μαρτυρόπολις",
    "Mauretania": "Μαυριτανία",
    "Medikion": "Μηδίκιον",
    "Medikion Monastery": "Μονή Μηδικίου",
    "Medin": "Μεντίν",
    "Mega Dendron": "Μέγα Δένδρον",
    "Meglin": "Μεγλίνη",
    "Melitene": "Μελιτηνή",
    "Melitopolis": "Μελιτούπολις",
})


# The places, fifth part.
PARTS.update({
    "Menuthis": "Μενουθίς",
    "Menyusha": "Μενιούσα",
    "Merkushino": "Μερκούσινο",
    "Mesopotamia": "Μεσοποταμία",
    "Mesteacăn": "Μεστεακάν",
    "Methymna": "Μήθυμνα",
    "Mezen": "Μεζέν",
    "Mgvime": "Μγκβίμε",
    "Milan": "Μεδιόλανα",
    "Mineo": "Μινέο",
    "Minneapolis": "Μινεάπολις",
    "Moesia": "Μοισία",
    "Mogarissos": "Μογάρισσος",
    "Mogilev": "Μογκιλιόφ",
    "Moldavia": "Μολδαβία",
    "Moldova": "Μολδαβία",
    "Monembasia": "Μονεμβασία",
    "Monte Cassino": "Μόντε Κασσίνο",
    "Monteluco": "Μοντελούκο",
    "Montenegro": "Μαυροβούνιο",
    "Monza River": "Ποταμός Μόνζα",
    "Moravia": "Μοραβία",
    "Morea (Peloponnese)": "Μοριάς (Πελοπόννησος)",
    "Moresheth": "Μωρασθί",
    "Moscow": "Μόσχα",
    "Moscow lands": "Χώρες της Μόσχας",
    "Mount Athos": "Άγιον Όρος",
    "Mount Colzim": "Όρος Κολζίμ",
    "Mount Ephraim": "Όρος Εφραίμ",
    "Mount Galesion": "Όρος Γαλήσιον",
    "Mount Galesius": "Όρος Γαλήσιον",
    "Mount Hor": "Όρος Ωρ",
    "Mount Kyminas": "Όρος Κυμινάς",
    "Mount Maleon": "Όρος Μαλέον",
    "Mount Myrsinon": "Όρος Μυρσινών",
    "Mount Nebo": "Όρος Ναβαύ",
    "Mount Olympus": "Όρος Όλυμπος",
    "Mount Sagmata": "Όρος Σαγματά",
    "Mount Sinai": "Όρος Σινά",
    "Mount Skopa": "Όρος Σκοπά",
    "Mount Taurus": "Όρος Ταύρος",
    "Mount of Olives": "Όρος των Ελαιών",
    "Mozhaisk": "Μοζάισκ",
    "Mrkonjici": "Μρκόνιτσι",
    "Mtskheta": "Μτσχέτα",
    "Murom": "Μουρόμ",
    "Murom Island": "Νήσος Μουρόμ",
    "Mutalaska": "Μουταλάσκη",
    "Mylapore": "Μυλαπόρ",
    "Mylasa": "Μύλασα",
    "Myra": "Μύρα",
    "Myra in Lycia": "Μύρα της Λυκίας",
    "Myrgorod": "Μίργκοροντ",
    "Mytilene": "Μυτιλήνη",
    "Naissus": "Ναϊσσός",
    "Najran": "Ναγιράν",
    "Nalšia": "Νάλσια",
    "Nanterre": "Ναντέρ",
    "Naples": "Νεάπολη",
    "Nauplion": "Ναύπλιο",
    "Nazareth": "Ναζαρέτ",
    "Nazianzus": "Ναζιανζός",
    "Nea Makri": "Νέα Μάκρη",
    "Neamts Monastery": "Μονή Νεάμτς",
    "Neamț": "Νεάμτς",
    "Neapolis": "Νεάπολις",
    "Near Constantinople": "Πλησίον της Κωνσταντινουπόλεως",
    "Neocaesarea": "Νεοκαισάρεια",
    "Nerchinsk": "Νερτσίνσκ",
    "New Lake": "Νέα Λίμνη",
    "New York": "Νέα Υόρκη",
    "Nicaea": "Νίκαια",
    "Nicea": "Νίκαια",
    "Nicomedia": "Νικομήδεια",
    "Nicopolis": "Νικόπολις",
    "Nicosia": "Λευκωσία",
    "Nikiforovskaya": "Νικιφόροβσκαγια",
    "Nisibis": "Νίσιβις",
    "Nitria": "Νιτρία",
    "Nizhni-Novgorod": "Νίζνι Νόβγκοροντ",
    "Nizhny Novgorod": "Νίζνι Νόβγκοροντ",
    "Nizhny Novgorod lands": "Χώρες του Νίζνι Νόβγκοροντ",
    "Nizhyn": "Νίζιν",
    "North Africa": "Βόρεια Αφρική",
    "North America": "Βόρεια Αμερική",
    "North Macedonia": "Βόρεια Μακεδονία",
    "Northumbria": "Νορθουμβρία",
    "Novara": "Νοβάρα",
    "Novgorod": "Νόβγκοροντ",
    "Novgorod lands": "Χώρες του Νόβγκοροντ",
    "Noviodunum": "Νοβιόδουνον",
    "Novoezersk": "Νοβοεζέρσκ",
    "Nurma": "Νούρμα",
    "Nursia": "Νουρσία",
    "Nyssa": "Νύσσα",
    "Obnora River": "Ποταμός Ομπνόρα",
    "Odessa": "Οδησσός",
    "Odrino": "Οντρίνο",
    "Ohrid": "Αχρίδα",
    "Old Lavra of Chariton": "Παλαιά Λαύρα του Χαρίτωνος",
    "Olonets": "Ολονέτς",
    "Olonets lands": "Χώρες του Ολονέτς",
    "Olshansk": "Όλσανσκ",
    "Olympus": "Όλυμπος",
    "Omala": "Ομαλά",
    "Ondrusov": "Οντρούσοφ",
    "Ophrah": "Οφρά",
    "Opso": "Όψο",
    "Orel lands": "Χώρες του Οριόλ",
    "Oshevensk": "Οσεβένσκ",
    "Osrhoene": "Οσροηνή",
    "Ostia": "Όστια",
    "Ostracine": "Οστρακίνη",
    "Ostrog": "Όστρογκ",
    "Ovche Pole": "Όβτσε Πόλε",
    "Ovruch": "Οβρούτς",
    "Ozovia": "Οζόβια",
    "Palermo": "Παλέρμο",
    "Palestine": "Παλαιστίνη",
    "Palii Island": "Νήσος Πάλιι",
})


# The places, sixth part.
PARTS.update({
    "Pamphylia": "Παμφυλία",
    "Pannonia": "Παννονία",
    "Paphlagonia": "Παφλαγονία",
    "Paphos": "Πάφος",
    "Paramythia": "Παραμυθιά",
    "Paris": "Παρίσι",
    "Parium": "Πάριον",
    "Paros": "Πάρος",
    "Parthia": "Παρθία",
    "Patara": "Πάταρα",
    "Patmos": "Πάτμος",
    "Patras": "Πάτρα",
    "Pec": "Πετς",
    "Pechenga": "Πετσένγκα",
    "Pechenga Monastery": "Μονή Πετσένγκα",
    "Pekhorka": "Πεχόρκα",
    "Pelecete": "Πελεκητή",
    "Pelekete": "Πελεκητή",
    "Pelekete Monastery": "Μονή Πελεκητής",
    "Peloponnese": "Πελοπόννησος",
    "Pelshma": "Πέλσμα",
    "Pelusium": "Πηλούσιον",
    "Pennsylvania": "Πενσυλβάνια",
    "Perekop (Perekomsky) Monastery": "Μονή Περεκόπ (Περεκόμσκι)",
    "Pereslavl": "Περεσλάβλ",
    "Pereslavl-Zalessky": "Περεσλάβλ-Ζαλέσκι",
    "Pereyaslavl": "Περεγιασλάβλ",
    "Pereyaslavl-Zalessky": "Περεγιασλάβλ-Ζαλέσκι",
    "Pergamum": "Πέργαμος",
    "Perge": "Πέργη",
    "Peristerai": "Περιστεραί",
    "Perm": "Περμ",
    "Perm lands": "Χώρες του Περμ",
    "Persia": "Περσία",
    "Persia and the East": "Περσία και η Ανατολή",
    "Peshnosha": "Πεσνόσα",
    "Petrograd": "Πετρούπολη",
    "Peć": "Πετς",
    "Pharan": "Φαράν",
    "Pharasa": "Φάρασα",
    "Philadelphia": "Φιλαδέλφεια",
    "Philippopolis": "Φιλιππούπολις",
    "Philotheou Monastery": "Μονή Φιλοθέου",
    "Phocis": "Φωκίδα",
    "Phoenicia": "Φοινίκη",
    "Phrygia": "Φρυγία",
    "Pinega": "Πινέγκα",
    "Pinsk": "Πινσκ",
    "Pisidia": "Πισιδία",
    "Plousias": "Πλουσιάς",
    "Pochaev": "Ποτσάεφ",
    "Pochaiv": "Ποτσάιφ",
    "Podolia": "Ποδολία",
    "Poiana Marului": "Ποϊάνα Μαρουλούι",
    "Pokutia": "Ποκούτια",
    "Poland": "Πολωνία",
    "Polotsk": "Πόλοτσκ",
    "Poltava": "Πολτάβα",
    "Poltava lands": "Χώρες της Πολτάβα",
    "Poltava region": "Περιοχή της Πολτάβα",
    "Polybotum": "Πολύβοτον",
    "Pomorie": "Πομόριε",
    "Pompeiopolis": "Πομπηιούπολις",
    "Pontus": "Πόντος",
    "Popovo": "Πόποβο",
    "Porkhov": "Πόρχοφ",
    "Poshekhonye": "Ποσεχόνιε",
    "Pozzuoli": "Ποτσουόλι",
    "Prague": "Πράγα",
    "Pretorium": "Πραιτώριον",
    "Priluki": "Πριλούκι",
    "Prokopion": "Προκόπιον",
    "Protection Convent": "Μονή της Σκέπης",
    "Prusa": "Προύσα",
    "Pryluky": "Πριλούκι",
    "Prymnessus": "Πρύμνησσος",
    "Pshinja": "Πσίνια",
    "Pskov": "Πσκοφ",
    "Pskov Caves Monastery": "Μονή των Σπηλαίων του Πσκοφ",
    "Ptinapor": "Πτιναπόρ",
    "Ptolemais": "Πτολεμαΐς",
    "Puteoli": "Ποτίολοι",
    "Putna": "Πούτνα",
    "Pythias": "Πυθίας",
    "Périgueux": "Περιγκέ",
    "Radonezh": "Ραντονέζ",
    "Radonezh and Serpukhov": "Ραντονέζ και Σερπούχοφ",
    "Radoviste": "Ράντοβιστε",
    "Raithu": "Ραϊθώ",
    "Ramah": "Ραμά",
    "Ramathaim": "Αρμαθαίμ",
    "Ramathaim-Zophim": "Αρμαθαίμ-Σωφίμ",
    "Ramnic": "Ράμνικ",
    "Ravanica": "Ραβάνιτσα",
    "Ravenna": "Ραβέννα",
    "Resafa": "Ρεσάφα",
    "Rethymnon": "Ρέθυμνο",
    "Rhosus": "Ρωσσός",
    "Rila": "Ρίλα",
    "Robeika": "Ρομπέικα",
    "Robeika River": "Ποταμός Ρομπέικα",
    "Roman Britain": "Ρωμαϊκή Βρετανία",
    "Romania": "Ρουμανία",
    "Rome": "Ρώμη",
    "Rome and Milan": "Ρώμη και Μεδιόλανα",
    "Rome and the East": "Ρώμη και η Ανατολή",
    "Rossos": "Ρωσσός",
    "Rostov": "Ροστόφ",
    "Rostov lands": "Χώρες του Ροστόφ",
    "Rus'": "Ρωσία",
    "Russia": "Ρωσία",
    "Russian North": "Ρωσικός Βορράς",
    "Russian nobility": "Ρωσική αριστοκρατία",
    "Ryazan": "Ριαζάν",
    "Ryazan province": "Επαρχία Ριαζάν",
    "Rzhev": "Ρζεφ",
    "Saint John": "Άγιος Ιωάννης",
    "Saint Petersburg": "Αγία Πετρούπολη",
    "Salamis": "Σαλαμίς",
    "Salamis (Constantia)": "Σαλαμίς (Κωνσταντία)",
})


# The places, seventh part.
PARTS.update({
    "Salona": "Σαλώνα",
    "Samaria": "Σαμάρεια",
    "Samegrelo": "Σαμεγκρέλο",
    "Samosata": "Σαμόσατα",
    "Samothrace": "Σαμοθράκη",
    "Samtskhe": "Σαμτσχέ",
    "San Francisco": "Σαν Φρανσίσκο",
    "Saragossa": "Σαραγόσα",
    "Sardis": "Σάρδεις",
    "Sarov": "Σάρωφ",
    "Scetis": "Σκήτη",
    "Scotland": "Σκωτία",
    "Scythia": "Σκυθία",
    "Scythia Minor": "Μικρά Σκυθία",
    "Sebaste": "Σεβάστεια",
    "Sebastea": "Σεβάστεια",
    "Sebino": "Σεμπίνο",
    "Seleucia": "Σελεύκεια",
    "Seleucia-Ctesiphon": "Σελεύκεια-Κτησιφών",
    "Selymbria": "Σηλυβρία",
    "Serbia": "Σερβία",
    "Sergiev Posad": "Σεργκίεφ Ποσάντ",
    "Serpukhov": "Σερπούχοφ",
    "Serres": "Σέρρες",
    "Shanghai": "Σαγκάη",
    "Shenkursk": "Σενκούρσκ",
    "Shiloh": "Σηλώ",
    "Shio-Mgvime Monastery": "Μονή Σίο-Μγκβίμε",
    "Shovskoe": "Σόβσκογιε",
    "Shuya": "Σούγια",
    "Shuzhgora": "Σουζγκορά",
    "Siberia": "Σιβηρία",
    "Siblag camps": "Στρατόπεδα Σιμπλάγκ",
    "Sicily": "Σικελία",
    "Side": "Σίδη",
    "Sigriane": "Σιγριανή",
    "Silistra": "Σιλίστρα",
    "Simferopol": "Συμφερούπολη",
    "Sinai": "Σινά",
    "Sinai and Raithu": "Σινά και Ραϊθώ",
    "Sinai wilderness": "Έρημος του Σινά",
    "Singidunum": "Σιγγιδούνον",
    "Sinope": "Σινώπη",
    "Sinope and Amasea": "Σινώπη και Αμάσεια",
    "Sinozersk": "Σινοζέρσκ",
    "Sirmium": "Σίρμιον",
    "Sisan": "Σισάν",
    "Sitka": "Σίτκα",
    "Siya Monastery": "Μονή Σίγια",
    "Skepsis": "Σκήψις",
    "Sketis": "Σκήτη",
    "Skrino": "Σκρίνο",
    "Slutsk": "Σλουτσκ",
    "Smolensk": "Σμολένσκ",
    "Smyrna": "Σμύρνη",
    "Snetogorsk": "Σνετογκόρσκ",
    "Snetogorsk Monastery": "Μονή Σνετογκόρσκ",
    "Sofia": "Σόφια",
    "Sokhot River": "Ποταμός Σοχότ",
    "Solovki": "Σολόβκι",
    "Solovki Islands": "Νήσοι Σολόβκι",
    "Solovki Monastery": "Μονή Σολόβκι",
    "Sophene": "Σωφηνή",
    "Sora River": "Ποταμός Σόρα",
    "Soreoi": "Σορεοί",
    "Spain": "Ισπανία",
    "Spoleto": "Σπολέτο",
    "Spruce Island": "Νήσος Σπρους",
    "Srem": "Σρεμ",
    "St Albans": "Σεντ Όλμπανς",
    "St. Petersburg": "Αγία Πετρούπολη",
    "Stara Zagora": "Στάρα Ζαγόρα",
    "Staritsa": "Στάριτσα",
    "Starytsa": "Στάριτσα",
    "Steirion": "Στείριον",
    "Stolobny Island": "Νήσος Στολόμπνι",
    "Storozhi Hill": "Λόφος Στορόζι",
    "Strobil": "Στρόβιλος",
    "Strumica": "Στρώμνιτσα",
    "Studenica": "Στουντένιτσα",
    "Subiaco": "Σουμπιάκο",
    "Suceava": "Σουτσεάβα",
    "Sura": "Σούρα",
    "Susa": "Σούσα",
    "Suzdal": "Σούζνταλ",
    "Svensky Monastery": "Μονή Σβένσκι",
    "Svir": "Σβιρ",
    "Sviyazhsk": "Σβιγιάζσκ",
    "Sweden": "Σουηδία",
    "Syandeba": "Σιαντέμπα",
    "Syandemsk": "Σιαντέμσκ",
    "Syanzhema": "Σιανζέμα",
    "Syanzhema River": "Ποταμός Σιανζέμα",
    "Sykeon": "Συκεών",
    "Symbola": "Σύμβολα",
    "Symbola Monastery": "Μονή Συμβόλων",
    "Synnada": "Σύνναδα",
    "Syracuse": "Συρακούσες",
    "Syria": "Συρία",
    "Tabatha": "Θαβαθά",
    "Tabenna": "Ταβέννα",
    "Tabennisi": "Ταβεννήσι",
    "Tambov": "Ταμπόφ",
    "Tao": "Τάο",
    "Tao-Klarjeti": "Τάο-Κλαρτζέτι",
    "Taormina": "Ταορμίνα",
    "Taphanes": "Ταφνάς",
    "Targala": "Τάργαλα",
    "Tarnovo": "Τύρνοβο",
    "Tarsus": "Ταρσός",
    "Tarsus and Achaia": "Ταρσός και Αχαΐα",
    "Tarsus and Rossos": "Ταρσός και Ρωσσός",
    "Tarsus and the East": "Ταρσός και η Ανατολή",
    "Tashkent": "Τασκένδη",
    "Tauresium": "Ταυρήσιον",
    "Tazlău": "Ταζλάου",
    "Tazlău Monastery": "Μονή Ταζλάου",
    "Tbilisi": "Τιφλίδα",
    "Tekoa": "Θεκουέ",
    "Tenedos": "Τένεδος",
})


# The places, eighth part.
PARTS.update({
    "Tennis": "Τέννησος",
    "Teratyn": "Τερατίν",
    "Terracina": "Τερρακίνα",
    "The East": "Η Ανατολή",
    "The Jordan": "Ο Ιορδάνης",
    "Thebaid": "Θηβαΐδα",
    "Thebes": "Θήβα",
    "Thebes of Egypt": "Θήβαι της Αιγύπτου",
    "Thessalonica": "Θεσσαλονίκη",
    "Thessaloniki": "Θεσσαλονίκη",
    "Thessaly": "Θεσσαλία",
    "Thrace": "Θράκη",
    "Thyateira": "Θυάτειρα",
    "Tikhvin": "Τίχβιν",
    "Tiksna": "Τίκσνα",
    "Tishbe of Gilead": "Θεσβίτις της Γαλαάδ",
    "Tmutarakan": "Τμουταρακάν",
    "Tobolsk": "Τομπόλσκ",
    "Tolva": "Τόλβα",
    "Toropets": "Τορόπετς",
    "Torzhok": "Τορζόκ",
    "Totma": "Τότμα",
    "Trajanopolis": "Τραϊανούπολις",
    "Tralles": "Τράλλεις",
    "Transcarpathia": "Υπερκαρπαθία",
    "Trebia": "Τρέβια",
    "Trebizond": "Τραπεζούντα",
    "Tremithus": "Τριμυθούς",
    "Trier": "Τρίερ",
    "Triglia": "Τρίγλια",
    "Trikala": "Τρίκαλα",
    "Trinity Lavra": "Λαύρα της Αγίας Τριάδος",
    "Trinity-Sergius Lavra": "Λαύρα Αγίας Τριάδος και Αγίου Σεργίου",
    "Tripoli": "Τρίπολις",
    "Troas": "Τρωάς",
    "Tsarskoye Selo": "Τσάρσκογιε Σελό",
    "Tula lands": "Χώρες της Τούλα",
    "Turchasovo": "Τουρτσάσοβο",
    "Turov": "Τούροφ",
    "Tuscany": "Τοσκάνη",
    "Tver": "Τβερ",
    "Tver lands": "Χώρες του Τβερ",
    "Tyana": "Τύανα",
    "Tyre": "Τύρος",
    "Uchma": "Ούτσμα",
    "Uglich": "Ούγκλιτς",
    "Ukraine": "Ουκρανία",
    "United States": "Ηνωμένες Πολιτείες",
    "Unzha": "Ούνζα",
    "Upper Thebaid": "Άνω Θηβαΐδα",
    "Ur of the Chaldees": "Ουρ των Χαλδαίων",
    "Ushchelye": "Ουστσέλιε",
    "Ust-Totma": "Ουστ-Τότμα",
    "Ust-Vym": "Ουστ-Βιμ",
    "Ustiug": "Ουστιούγκ",
    "Ustyug": "Ουστιούγκ",
    "Vaga": "Βάγκα",
    "Vaga lands": "Χώρες της Βάγκα",
    "Vagharshapat": "Βαγκαρσαπάτ",
    "Valaam": "Βαλαάμ",
    "Valencia": "Βαλένθια",
    "Varnitsa": "Βαρνίτσα",
    "Varzuga": "Βαρζούγκα",
    "Vasilevo": "Βασίλεβο",
    "Vaste": "Βάστε",
    "Vasyliv": "Βασίλιφ",
    "Vazheozero region": "Περιοχή Βαζεοζέρο",
    "Velehrad": "Βέλεχραντ",
    "Veliki Luki": "Βελίκιε Λούκι",
    "Veliky Ustiug": "Βελίκι Ουστιούγκ",
    "Veliky Ustyug": "Βελίκι Ουστιούγκ",
    "Venice": "Βενετία",
    "Verkhoturye": "Βερχοτούριε",
    "Verkola": "Βερκόλα",
    "Verona": "Βερόνα",
    "Verulamium": "Βερουλάμιον",
    "Verulamium (St Albans)": "Βερουλάμιον (Σεντ Όλμπανς)",
    "Vetluga": "Βετλούγκα",
    "Videlebye": "Βιντελέμπιε",
    "Vilnius": "Βίλνιους",
    "Vishera": "Βισέρα",
    "Vladimir": "Βλαντίμιρ",
    "Vladimir lands": "Χώρες του Βλαντίμιρ",
    "Vladimir-Suzdal": "Βλαντίμιρ-Σούζνταλ",
    "Vladimir-in-Volhynia": "Βλαντίμιρ της Βολυνίας",
    "Volga Bulgaria": "Βουλγαρία του Βόλγα",
    "Volhynia": "Βολυνία",
    "Volissos": "Βολισσός",
    "Volodymyr-Volhynia": "Βολοντίμιρ-Βολυνσκί",
    "Vologda": "Βόλογκντα",
    "Vologda lands": "Χώρες της Βόλογκντα",
    "Volokolamsk": "Βολοκολάμσκ",
    "Vorbozomsk Lake": "Λίμνη Βορμποζόμσκ",
    "Voronezh": "Βορόνεζ",
    "Vracar": "Βράτσαρ",
    "Vyatka": "Βιάτκα",
    "Vyazma": "Βιάζμα",
    "Vyritsa": "Βίριτσα",
    "Vyshgorod": "Βίσγκοροντ",
    "Vyshhorod": "Βίσχοροντ",
    "Wales": "Ουαλία",
    "Warsaw": "Βαρσοβία",
    "Western Rus": "Δυτική Ρωσία",
    "White Lake": "Λευκή Λίμνη",
    "White Lake (Beloozero)": "Λευκή Λίμνη (Μπελοοζέρο)",
    "White Lake region": "Περιοχή της Λευκής Λίμνης",
    "White Sea": "Λευκή Θάλασσα",
    "Wilkes-Barre": "Ουίλκς-Μπάρε",
    "Wonderful Mountain": "Θαυμαστόν Όρος",
    "Yakhroma": "Γιάχρομα",
    "Yarenga": "Γιαρένγκα",
    "Yaroslavl": "Γιαροσλάβλ",
    "Yaroslavl lands": "Χώρες του Γιαροσλάβλ",
    "Yaroslavl province": "Επαρχία Γιαροσλάβλ",
    "Yashezero": "Γιασεζέρο",
    "Yazvishche": "Γιαζβίστσε",
    "Yekaterinburg": "Γεκατερίνμπουργκ",
    "Yuriev (Tartu)": "Γιούριεφ (Τάρτου)",
    "Yuriev Monastery": "Μονή Γιούριεφ",
    "Yuriev-Polsky": "Γιούριεφ-Πόλσκι",
})


# The places, ninth and last part.
PARTS.update({
    "Yuryegorsk": "Γιουριέγκορσκ",
    "Zadonsk": "Ζαντόνσκ",
    "Zahumlje": "Ζαχούμλιε",
    "Zahumlje (Zakholm)": "Ζαχούμλιε (Ζάχολμ)",
    "Zakynthos": "Ζάκυνθος",
    "Zaozersk": "Ζαοζέρσκ",
    "Zelenets": "Ζελενέτς",
    "Zemplin region": "Περιοχή Ζέμπλιν",
    "Zeta": "Ζέτα",
    "Zeugma": "Ζεύγμα",
    "Zhabyn Monastery": "Μονή Ζαμπίν",
    "Zheleznoborov": "Ζελεζνομπόροφ",
    "Zhicha": "Ζίτσα",
    "Zhicha Monastery": "Μονή Ζίτσα",
    "Zvenigorod": "Ζβενίγκοροντ",
    "Zverki": "Ζβέρκι",
    "all Greece": "όλη η Ελλάδα",
    "all Rus'": "όλη η Ρωσία",
    "all Russia": "όλη η Ρωσία",
    "all Slavic lands": "όλες οι σλαβικές χώρες",
    "all schools": "όλα τα σχολεία",
    "all the Slavic lands": "όλες οι σλαβικές χώρες",
    "and Ephesus": "και Έφεσος",
    "beyond the Danube": "πέραν του Δουνάβεως",
    "gardens and vineyards": "κήποι και αμπελώνες",
    "near Agrigentum": "πλησίον του Ακράγαντος",
    "near Alexandria": "πλησίον της Αλεξανδρείας",
    "near Ancyra": "πλησίον της Άγκυρας",
    "near Antioch": "πλησίον της Αντιοχείας",
    "near Apamea": "πλησίον της Απάμειας",
    "near Bialystok": "πλησίον του Μπιάλιστοκ",
    "near Borovsk": "πλησίον του Μπορόφσκ",
    "near Cherepovets": "πλησίον του Τσερεποβέτς",
    "near Chernigov": "πλησίον του Τσερνίγκοφ",
    "near Constantinople": "πλησίον της Κωνσταντινουπόλεως",
    "near Cyrrhus": "πλησίον της Κύρρου",
    "near Dorostolum": "πλησίον του Δορυστόλου",
    "near Edessa": "πλησίον της Εδέσσης",
    "near Ephesus": "πλησίον της Εφέσου",
    "near Galich": "πλησίον του Γκάλιτς",
    "near Gaza": "πλησίον της Γάζης",
    "near Kargopol": "πλησίον του Καργκοπόλ",
    "near Kiev": "πλησίον του Κιέβου",
    "near Kyiv": "πλησίον του Κιέβου",
    "near Moscow": "πλησίον της Μόσχας",
    "near Mount Tabor": "πλησίον του όρους Θαβώρ",
    "near Mtskheta": "πλησίον της Μτσχέτα",
    "near Novgorod": "πλησίον του Νόβγκοροντ",
    "near Prusa": "πλησίον της Προύσας",
    "near Pskov": "πλησίον του Πσκοφ",
    "near Rostov": "πλησίον του Ροστόφ",
    "near Samosata": "πλησίον των Σαμοσάτων",
    "near Staraya Russa": "πλησίον της Στάραγια Ρούσα",
    "near Totma": "πλησίον της Τότμα",
    "near Uglich": "πλησίον του Ούγκλιτς",
    "near Verkhoturye": "πλησίον του Βερχοτούριε",
    "near Vladimir": "πλησίον του Βλαντίμιρ",
    "near Volokolamsk": "πλησίον του Βολοκολάμσκ",
    "near the Dvina": "πλησίον της Ντβινά",
    "on the Dvina": "επί της Ντβινά",
    "on the Onega": "επί της Ονέγκα",
    "the Balkans": "τα Βαλκάνια",
    "the Belozersk country": "η χώρα του Μπελοζέρσκ",
    "the Bistrița valley": "η κοιλάδα του Μπιστρίτσα",
    "the Black Sea coast and the Caucasus": "η ακτή του Ευξείνου Πόντου και ο Καύκασος",
    "the Buzau Mountains": "τα όρη Μπουζέου",
    "the Caucasus": "ο Καύκασος",
    "the Cells": "τα Κελλία",
    "the Cherepovets country": "η χώρα του Τσερεποβέτς",
    "the Danube lands": "οι παραδουνάβιες χώρες",
    "the Dvina country": "η χώρα της Ντβινά",
    "the East": "η Ανατολή",
    "the Egyptian desert": "η αιγυπτιακή έρημος",
    "the Gentile nations": "τα έθνη",
    "the Golden Horde": "η Χρυσή Ορδή",
    "the Holy Land": "οι Άγιοι Τόποι",
    "the Jordan": "ο Ιορδάνης",
    "the Jordan desert": "η έρημος του Ιορδάνου",
    "the Judean desert": "η έρημος της Ιουδαίας",
    "the Judean wilderness": "η έρημος της Ιουδαίας",
    "the Kola north": "ο βορράς της Κόλα",
    "the Komi lands": "οι χώρες των Κόμι",
    "the Mount of Olives": "το όρος των Ελαιών",
    "the Obnora": "η Ομπνόρα",
    "the Oka country": "η χώρα του Οκά",
    "the Olonets country": "η χώρα του Ολονέτς",
    "the Onega country": "η χώρα της Ονέγκα",
    "the Palestinian desert": "η έρημος της Παλαιστίνης",
    "the Peloponnese": "η Πελοπόννησος",
    "the Pinega country": "η χώρα της Πινέγκα",
    "the Pskov Caves": "τα Σπήλαια του Πσκοφ",
    "the Pčinja valley": "η κοιλάδα της Πτσίνια",
    "the Russian North": "ο ρωσικός Βορράς",
    "the Russian north": "ο ρωσικός βορράς",
    "the Seto lands": "οι χώρες των Σέτο",
    "the Smolensk cemetery": "το κοιμητήριο του Σμολένσκ",
    "the Sora": "η Σόρα",
    "the Studios monastery": "η μονή Στουδίου",
    "the Thebaid": "η Θηβαΐδα",
    "the Tikhvin country": "η χώρα του Τίχβιν",
    "the Urals": "τα Ουράλια",
    "the Volga lands": "οι χώρες του Βόλγα",
    "the Vologda country": "η χώρα της Βόλογκντα",
    "the White Sea": "η Λευκή Θάλασσα",
    "the White Sea coast": "η ακτή της Λευκής Θάλασσας",
    "the Wonderful Mountain": "το Θαυμαστόν Όρος",
    "the Yakhroma": "η Γιάχρομα",
    "the desert of Egypt": "η έρημος της Αιγύπτου",
    "the inner Egyptian desert": "η εσωτέρα αιγυπτιακή έρημος",
    "the lands of the apostolic mission": "οι χώρες της αποστολικής ιεραποστολής",
    "the northern Thebaid": "η βόρεια Θηβαΐδα",
    "the northern missions": "οι βόρειες ιεραποστολές",
    "the whole world": "όλη η οικουμένη",
    "the wilderness beyond Mesopotamia": "η έρημος πέραν της Μεσοποταμίας",
    "travelers' gates": "πύλες των οδοιπόρων",
})


# One more, spelled as its own land spells it.
PARTS.update({
    "Žiča": "Ζίτσα",
})


# How else a saint is named, first part.
TEXT.update({
    "(Abibus) of Egypt": "(Άβιβος) της Αιγύπτου",
    "(Apphianus) and Edesius (Aedesius) of Lycia": "(Απφιανός) και Αιδέσιος της Λυκίας",
    "(Eustace) the Confessor, Bishop of Bithynia": "(Ευστάθιος) ο Ομολογητής, επίσκοπος Βιθυνίας",
    "(Jacob) the Presbyter, and Azadanes and Abdiesus the Deacons, of Persia": "(Ιάκωβος) ο πρεσβύτερος, και Αζαδάνης και Αβδιησούς οι διάκονοι, εκ Περσίας",
    "(Vadim) of Persia": "(Βαδίμος) της Περσίας",
    "(Voino-Yasenetsky), Archbishop of Simferopol and Crimea": "(Βόινο-Γιασενέτσκι), αρχιεπίσκοπος Συμφερουπόλεως και Κριμαίας",
    "(also called Susanna), New Martyr of Lesbos": "(καλουμένη και Σουσάννα), νεομάρτυς της Λέσβου",
    "(tonsured David and Euphrosyne), Wonderworkers of Murom": "(κείραντες Δαβίδ και Ευφροσύνη), θαυματουργοί του Μουρόμ",
    "Abba Salama, Revealer of Light": "Αββάς Σαλαμά, ο Αποκαλύπτης του Φωτός",
    "Abbess of Polotsk": "Ηγουμένη του Πόλοτσκ",
    "Abbot at Cucomo, in Sicily": "Ηγούμενος εν Κουκόμω της Σικελίας",
    "Abbot in the Vranski Desert on the River Pshinja": "Ηγούμενος εν τη ερήμω Βράνσκι επί του ποταμού Πσίνια",
    "Abbot of Belozersk": "Ηγούμενος του Μπελοζέρσκ",
    "Abbot of Borovsk": "Ηγούμενος του Μπορόφσκ",
    "Abbot of Dymsk": "Ηγούμενος του Ντιμσκ",
    "Abbot of Galich": "Ηγούμενος του Γκάλιτς",
    "Abbot of Glushitsa": "Ηγούμενος της Γκλουσίτσα",
    "Abbot of Komel": "Ηγούμενος του Κομέλ",
    "Abbot of Komel, disciple of Saint Cornelius": "Ηγούμενος του Κομέλ, μαθητής του αγίου Κορνηλίου",
    "Abbot of Konevits": "Ηγούμενος του Κόνεβετς",
    "Abbot of Kushta": "Ηγούμενος της Κούστα",
    "Abbot of Moscow": "Ηγούμενος της Μόσχας",
    "Abbot of Obnora": "Ηγούμενος της Ομπνόρα",
    "Abbot of Oshevensk": "Ηγούμενος του Οσεβένσκ",
    "Abbot of Paleostrov": "Ηγούμενος του Παλεόστροφ",
    "Abbot of Pelecete": "Ηγούμενος της Πελεκητής",
    "Abbot of Perekop, Wonderworker of Novgorod": "Ηγούμενος του Περεκόπ, θαυματουργός του Νόβγκοροντ",
    "Abbot of Pereslavl-Zalessky": "Ηγούμενος του Περεσλάβλ-Ζαλέσκι",
    "Abbot of Peshnosha, disciple of Saint Sergius of Radonezh": "Ηγούμενος της Πεσνόσα, μαθητής του αγίου Σεργίου του Ραντονέζ",
    "Abbot of Robeika, Novgorod": "Ηγούμενος της Ρομπέικα, Νόβγκοροντ",
    "Abbot of Snetogorsk, with Basil of Mirozh": "Ηγούμενος του Σνετογκόρσκ, μετά του Βασιλείου του Μιρόζ",
    "Abbot of Solovki": "Ηγούμενος των Σολόβκι",
    "Abbot of Sora": "Ηγούμενος της Σόρα",
    "Abbot of Syandemsk, Vologda": "Ηγούμενος του Σιαντέμσκ, Βόλογκντα",
    "Abbot of Uglich": "Ηγούμενος του Ούγκλιτς",
    "Abbot of Vetluga": "Ηγούμενος της Βετλούγκα",
    "Abbot of Vorbozomsk": "Ηγούμενος του Βορμποζόμσκ",
    "Abbot of White Lake": "Ηγούμενος της Λευκής Λίμνης",
    "Abbot of Zheleznoborov": "Ηγούμενος του Ζελεζνομπόροφ",
    "Abbot of the Kyiv Caves": "Ηγούμενος των Σπηλαίων του Κιέβου",
    "Abbot of the Kyiv Far Caves Monastery": "Ηγούμενος της Μονής των Απωτέρων Σπηλαίων του Κιέβου",
    "Abbot of the Kyiv Far Caves, and Bishop of Vladimir, in Volhynia": "Ηγούμενος των Απωτέρων Σπηλαίων του Κιέβου και επίσκοπος Βλαντίμιρ της Βολυνίας",
    "Abbot of the Pskov Caves Monastery": "Ηγούμενος της Μονής των Σπηλαίων του Πσκοφ",
    "Abbots of Avnezh, Vologda": "Ηγούμενοι του Αβνέζ, Βόλογκντα",
    "All-Praised": "Πανεύφημος",
    "Ancestor of God": "Θεοπάτωρ",
    "Ancestors of God": "Θεοπάτορες",
    "Apodosis": "Απόδοσις",
    "Apollos, and Quadratus, of Nicomedia": "Απολλώς και Κοδράτος, εκ Νικομηδείας",
    "Apostle and Evangelist": "Απόστολος και ευαγγελιστής",
    "Apostle and Evangelist, the Theologian": "Απόστολος και ευαγγελιστής, ο Θεολόγος",
    "Apostle of the Americas": "Απόστολος των Αμερικών",
    "Apostle to the Americas": "Απόστολος προς τας Αμερικάς",
    "Appearance of the Icon of the Mother of God “The Footprint” at Pochaiv": "Εμφάνισις της εικόνος της Θεοτόκου \"Το Ίχνος\" εν Ποτσάιφ",
    "Archbishop of Alexandria": "Αρχιεπίσκοπος Αλεξανδρείας",
    "Archbishop of Antioch": "Αρχιεπίσκοπος Αντιοχείας",
    "Archbishop of Chernihiv": "Αρχιεπίσκοπος Τσερνίχιφ",
    "Archbishop of Constantinople": "Αρχιεπίσκοπος Κωνσταντινουπόλεως",
    "Archbishop of Jerusalem": "Αρχιεπίσκοπος Ιεροσολύμων",
    "Archbishop of Kharkov and Akhtyrsk": "Αρχιεπίσκοπος Χάρκοβο και Αχτίρσκ",
    "Archbishop of Novgorod": "Αρχιεπίσκοπος Νόβγκοροντ",
    "Archbishop of Serbia": "Αρχιεπίσκοπος Σερβίας",
    "Archbishop of Suzdal": "Αρχιεπίσκοπος Σούζνταλ",
    "Archdeacon of Catania": "Αρχιδιάκονος Κατάνης",
    "Archdeacon of Rome": "Αρχιδιάκονος Ρώμης",
    "Archimandrite of Ovruch and Pinsk": "Αρχιμανδρίτης Οβρούτς και Πινσκ",
    "Archimandrite of the Caves": "Αρχιμανδρίτης των Σπηλαίων",
    "Archimandrite of the Trinity-Sergius Lavra": "Αρχιμανδρίτης της Λαύρας Αγίας Τριάδος και Αγίου Σεργίου",
    "Ascetic of the Syrian Deserts": "Ασκητής των συριακών ερήμων",
    "Asistavi": "Ασιστάβι",
    "Barsabas": "Βαρσαβάς",
    "Basil, Ephraim, Capito, Eugene, Aetherius, Elpidius, and Agathodorus": "Βασίλειος, Εφραίμ, Καπίτων, Ευγένιος, Αιθέριος, Ελπίδιος και Αγαθόδωρος",
    "Beginning of Great Lent": "Αρχή της Μεγάλης Τεσσαρακοστής",
    "Bishop in Persia, and 272 others with him": "Επίσκοπος εν Περσίδι, και 272 έτεροι μετ' αυτού",
    "Bishop in Persia, and those with him": "Επίσκοπος εν Περσίδι, και οι συν αυτώ",
    "Bishop of Amasea": "Επίσκοπος Αμασείας",
    "Bishop of Amastris on the Black Sea": "Επίσκοπος Αμάστριδος επί του Ευξείνου Πόντου",
    "Bishop of Amathus in Cyprus": "Επίσκοπος Αμαθούντος της Κύπρου",
    "Bishop of Ancyra, with the Martyr Agathangelus": "Επίσκοπος Αγκύρας, μετά του μάρτυρος Αγαθαγγέλου",
    "Bishop of Antioch": "Επίσκοπος Αντιοχείας",
    "Bishop of Arethusa, who suffered under Julian the Apostate": "Επίσκοπος Αρεθούσης, ο αθλήσας επί Ιουλιανού του Παραβάτου",
    "Bishop of Armagh, Enlightener of Ireland": "Επίσκοπος Άρμαγκ, φωτιστής της Ιρλανδίας",
    "Bishop of Athens": "Επίσκοπος Αθηνών",
    "Bishop of Beauvais, and those with him": "Επίσκοπος Μποβέ, και οι συν αυτώ",
    "Bishop of Benevento, and his companions, at Pozzuoli": "Επίσκοπος Μπενεβέντο, και οι σύντροφοι αυτού, εν Ποτσουόλι",
    "Bishop of Brooklyn": "Επίσκοπος Μπρούκλιν",
    "Bishop of Catania": "Επίσκοπος Κατάνης",
    "Bishop of Catania in Sicily": "Επίσκοπος Κατάνης της Σικελίας",
    "Bishop of Chalcedon, and his fellow ascetic Auxentius": "Επίσκοπος Χαλκηδόνος, και ο συνασκητής αυτού Αυξέντιος",
    "Bishop of Cyprus": "Επίσκοπος Κύπρου",
    "Bishop of Cyprus, the Pentaglot": "Επίσκοπος Κύπρου, ο Πεντάγλωσσος",
    "Bishop of Cyrenia": "Επίσκοπος Κερυνείας",
    "Bishop of Damascus, called Barsanuphius, of Nitria": "Επίσκοπος Δαμασκού, ο καλούμενος Βαρσανούφιος, εκ Νιτρίας",
    "Bishop of Euroea in Epirus": "Επίσκοπος Ευροίας της Ηπείρου",
    "Bishop of Formia in Campania": "Επίσκοπος Φορμίας της Καμπανίας",
    "Bishop of Gaza": "Επίσκοπος Γάζης",
    "Bishop of Hierapolis": "Επίσκοπος Ιεραπόλεως",
    "Bishop of Iconium": "Επίσκοπος Ικονίου",
    "Bishop of Irkutsk": "Επίσκοπος Ιρκούτσκ",
    "Bishop of Lampsakos": "Επίσκοπος Λαμψάκου",
    "Bishop of Leucosia (Nicosia), Cyprus": "Επίσκοπος Λευκωσίας, Κύπρου",
    "Bishop of Magnesia": "Επίσκοπος Μαγνησίας",
    "Bishop of Magydos in Pamphylia": "Επίσκοπος Μαγύδου της Παμφυλίας",
    "Bishop of Martyropolis in Mesopotamia": "Επίσκοπος Μαρτυρουπόλεως της Μεσοποταμίας",
    "Bishop of Melitene": "Επίσκοπος Μελιτηνής",
    "Bishop of Nicomedia": "Επίσκοπος Νικομηδείας",
    "Bishop of Nicomedia, with the Martyr Theonas": "Επίσκοπος Νικομηδείας, μετά του μάρτυρος Θεωνά",
    "Bishop of Novgorod": "Επίσκοπος Νόβγκοροντ",
    "Bishop of Novgorod, Recluse of the Kyiv Caves": "Επίσκοπος Νόβγκοροντ, έγκλειστος των Σπηλαίων του Κιέβου",
    "Bishop of Nyssa, Father of Fathers": "Επίσκοπος Νύσσης, Πατήρ Πατέρων",
    "Bishop of Patara": "Επίσκοπος Πατάρων",
    "Bishop of Pergamum and Disciple of Saint John the Theologian": "Επίσκοπος Περγάμου και μαθητής του αγίου Ιωάννου του Θεολόγου",
    "Bishop of Perm": "Επίσκοπος Περμ",
    "Bishop of Perm, Hieromartyr": "Επίσκοπος Περμ, ιερομάρτυς",
    "Bishop of Persia, and 128 Martyrs with him": "Επίσκοπος Περσίδος, και 128 μάρτυρες μετ' αυτού",
    "Bishop of Plousias in Bithynia": "Επίσκοπος Πλουσιάδος της Βιθυνίας",
    "Bishop of Prusa": "Επίσκοπος Προύσης",
    "Bishop of Prusa, and his companions": "Επίσκοπος Προύσης, και οι σύντροφοι αυτού",
    "Bishop of Samosata": "Επίσκοπος Σαμοσάτων",
    "Bishop of Sardis": "Επίσκοπος Σάρδεων",
    "Bishop of Sebaste": "Επίσκοπος Σεβαστείας",
    "Bishop of Seleucia": "Επίσκοπος Σελευκείας",
    "Bishop of Sirmium": "Επίσκοπος Σιρμίου",
    "Bishop of Smyrna": "Επίσκοπος Σμύρνης",
    "Bishop of Turov": "Επίσκοπος Τούροφ",
    "Bishop of Tver": "Επίσκοπος Τβερ",
    "Bishop of Tyre": "Επίσκοπος Τύρου",
    "Bishop of Verona": "Επίσκοπος Βερόνης",
    "Bishop of Vladimir and Suzdal, of the Kyiv Near Caves": "Επίσκοπος Βλαντίμιρ και Σούζνταλ, εκ των Εγγυτέρων Σπηλαίων του Κιέβου",
    "Bishop of Zakholmsk in Montenegro, Serbia": "Επίσκοπος Ζάχολμ εν Μαυροβουνίω, Σερβίας",
})


# How else a saint is named, second part.
TEXT.update({
    "Bishop of the Goths in the Crimea": "Επίσκοπος των Γότθων εν Κριμαία",
    "Brother of the Lord": "Αδελφόθεος",
    "Calabytes, the Hut-Dweller": "Καλυβίτης",
    "Chariessa, Nike, Galina, Kallista, Nunechia, Basilissa, Theodora, and Irene, of Corinth": "Χαρίεσσα, Νίκη, Γαλήνη, Καλλίστη, Νουνεχία, Βασίλισσα, Θεοδώρα και Ειρήνη, εκ Κορίνθου",
    "Chrysostom": "Χρυσόστομος",
    "Claudia, Euphrasia, Matrona, Juliana, Euphemia, and Theodosia, of Amisus": "Κλαυδία, Ευφρασία, Ματρώνα, Ιουλιανή, Ευφημία και Θεοδοσία, εξ Αμισού",
    "Cleonicus, and Basiliscus of Amasea": "Κλεόνικος και Βασιλίσκος εξ Αμασείας",
    "Commemoration of the Apparition of the Sign of the Precious Cross over Jerusalem": "Ανάμνησις της εμφανίσεως του σημείου του Τιμίου Σταυρού υπέρ την Ιερουσαλήμ",
    "Commemoration of the Founding of Constantinople": "Ανάμνησις των εγκαινίων της Κωνσταντινουπόλεως",
    "Commemoration of the Holy Fathers of the First Ecumenical Council": "Ανάμνησις των αγίων Πατέρων της Α' Οικουμενικής Συνόδου",
    "Commemoration of the Holy Fathers of the Second Ecumenical Council": "Ανάμνησις των αγίων Πατέρων της Β' Οικουμενικής Συνόδου",
    "Confessors with Stephen the New": "Ομολογηταί μετά Στεφάνου του Νέου",
    "Constantinople Icon of the Mother of God": "Η Κωνσταντινουπολίτισσα εικών της Θεοτόκου",
    "David, and John, of Palestine": "Δαβίδ και Ιωάννης, εκ Παλαιστίνης",
    "Dephourkinos, of Mount Kyminas": "Δεφουρκινός, εκ του όρους Κυμινά",
    "Dialogus, Pope of Rome": "ο Διάλογος, πάπας Ρώμης",
    "Disciple of Saint Gregory of Decapolis": "Μαθητής του αγίου Γρηγορίου του Δεκαπολίτου",
    "Disciple of Saint Sergius": "Μαθητής του αγίου Σεργίου",
    "Ecumenical Teacher": "Οικουμενικός διδάσκαλος",
    "Enlightener of Alaska": "Φωτιστής της Αλάσκας",
    "Enlightener of Armenia": "Φωτιστής της Αρμενίας",
    "Enlightener of North America": "Φωτιστής της Βορείου Αμερικής",
    "Enlightener of Northumbria": "Φωτιστής της Νορθουμβρίας",
    "Enlightener of the Aleuts": "Φωτιστής των Αλεούτων",
    "Enlightener of the Vyatichi": "Φωτιστής των Βιάτιτσι",
    "Eparch of Constantinople": "Έπαρχος Κωνσταντινουπόλεως",
    "Equal of the Apostles": "Ισαπόστολος",
    "Equal of the Apostles and Emperor, with his Mother Helen": "Ισαπόστολος και αυτοκράτωρ, μετά της μητρός αυτού Ελένης",
    "Equal of the Apostles and Teacher of the Slavs": "Ισαπόστολος και διδάσκαλος των Σλάβων",
    "Equal of the Apostles, Archbishop of Moravia, Enlightener of the Slavs": "Ισαπόστολος, αρχιεπίσκοπος Μοραβίας, φωτιστής των Σλάβων",
    "Equal of the Apostles, Enlightener of Georgia": "Ισαπόστολος, φωτίστρια της Γεωργίας",
    "Equals of the Apostles and Teachers of the Slavs": "Ισαπόστολοι και διδάσκαλοι των Σλάβων",
    "Eugenikos, Archbishop of Ephesus, Pillar of Orthodoxy": "Ευγενικός, αρχιεπίσκοπος Εφέσου, στύλος της Ορθοδοξίας",
    "Evangelist": "Ευαγγελιστής",
    "Fifth Saturday of Great Lent: of the Akathist to the Theotokos": "Ε' Σάββατον της Μεγάλης Τεσσαρακοστής: του Ακαθίστου Ύμνου προς την Θεοτόκον",
    "Fifth Sunday of Great Lent: Saint Mary of Egypt": "Ε' Κυριακή της Μεγάλης Τεσσαρακοστής: της οσίας Μαρίας της Αιγυπτίας",
    "Finding of the Relics of Saints Basil and Constantine, Princes of Yaroslavl": "Εύρεσις των λειψάνων των αγίων Βασιλείου και Κωνσταντίνου, ηγεμόνων του Γιαροσλάβλ",
    "Finding of the relics of Saint Basil, Bishop of Ryazan": "Εύρεσις των λειψάνων του αγίου Βασιλείου, επισκόπου Ριαζάν",
    "First Archbishop of Serbia": "Πρώτος αρχιεπίσκοπος Σερβίας",
    "First Bishop of Jerusalem": "Πρώτος επίσκοπος Ιεροσολύμων",
    "First High Priest, Brother of Moses": "Πρώτος αρχιερεύς, αδελφός του Μωυσέως",
    "First Metropolitan of Kyiv": "Πρώτος μητροπολίτης Κιέβου",
    "First Saturday of Great Lent: The Miracle of the Boiled Wheat": "Α' Σάββατον της Μεγάλης Τεσσαρακοστής: το θαύμα των κολλύβων",
    "First Sunday of Great Lent: Sunday of Orthodoxy": "Α' Κυριακή της Μεγάλης Τεσσαρακοστής: Κυριακή της Ορθοδοξίας",
    "First Wonderworker of Vologda": "Πρώτος θαυματουργός της Βόλογκντα",
    "First and Second Findings": "Πρώτη και δευτέρα εύρεσις",
    "Forefather": "Προπάτωρ",
    "Forefather of Christ": "Προπάτωρ του Χριστού",
    "Forefeast of the Annunciation": "Προεόρτια του Ευαγγελισμού",
    "Foremother": "Προμήτωρ",
    "Founder of the Dalmatos Monastery at Constantinople": "Κτίτωρ της μονής Δαλμάτου εν Κωνσταντινουπόλει",
    "Fourth Sunday of Great Lent: Saint John Climacus": "Δ' Κυριακή της Μεγάλης Τεσσαρακοστής: του οσίου Ιωάννου της Κλίμακος",
    "Gobron": "Γοβρών",
    "Golden Stream": "Χρυσορρόας",
    "Grand Duchess of Moscow": "Μεγάλη δούκισσα της Μόσχας",
    "Grand Princess of Moscow, in monasticism Euphrosyne": "Μεγάλη ηγεμονίδα της Μόσχας, εν τω μοναχικώ σχήματι Ευφροσύνη",
    "Graptus, the Branded, Confessor": "Γραπτός, ο Ομολογητής",
    "Great Princess of Kashin, Wonderworker": "Μεγάλη ηγεμονίδα του Κάσιν, θαυματουργός",
    "Heraclius, Paulinus, and Benedimus": "Ηράκλειος, Παυλίνος και Βενέδιμος",
    "Hermit of Syria": "Ερημίτης της Συρίας",
    "Icon of the Mother of God of Kasperov": "Η εικών της Θεοτόκου του Κασπέροβο",
    "Icon of the Mother of God of Kyiv-Bratsk": "Η εικών της Θεοτόκου Κιέβου-Μπρατσκ",
    "Icon of the Mother of God of Mt. Athos, “Sweet Kissing”": "Η εικών της Θεοτόκου του Αγίου Όρους, η Γλυκοφιλούσα",
    "Icon of the Mother of God “The Unbreakable Wall”": "Η εικών της Θεοτόκου το Τείχος το Άρρηκτον",
    "Icon of the Mother of God “of the Passion”": "Η εικών της Θεοτόκου του Πάθους",
    "Icon of the Mother of God “the Surety of Sinners”": "Η εικών της Θεοτόκου η Εγγυήτρια των Αμαρτωλών",
    "Igor-George, Tonsured Gabriel, Grand Prince of Chernihiv and Kyiv": "Ιγκόρ-Γεώργιος, μοναχός Γαβριήλ, μέγας ηγεμών Τσερνίχιφ και Κιέβου",
    "Igumen of Radonezh": "Ηγούμενος του Ραντονέζ",
    "Igumen of White Lake": "Ηγούμενος της Λευκής Λίμνης",
    "Inexhaustible Chalice Icon of the Mother of God": "Η εικών της Θεοτόκου το Ανεξάντλητον Ποτήριον",
    "Intercisus": "ο Κατατμηθείς",
    "Irene, and Chionia, at Thessalonica": "Ειρήνη και Χιονία, εν Θεσσαλονίκη",
    "John, and Eustathius of Vilnius": "Ιωάννης και Ευστάθιος του Βίλνιους",
    "Julius, Presbyter of Novara, and his brother, Julian the Deacon": "Ιούλιος, πρεσβύτερος Νοβάρας, και ο αδελφός αυτού Ιουλιανός ο διάκονος",
    "Keeper of Orphans, Orphanotrophos, Hieromartyr": "Ορφανοτρόφος, ιερομάρτυς",
    "King of Georgia": "Βασιλεύς της Γεωργίας",
    "Kochanov": "Κοτσάνοφ",
    "Kokkinos": "Κόκκινος",
    "Kuropalates, King of Georgia": "Κουροπαλάτης, βασιλεύς της Γεωργίας",
    "Leader of the Apostles": "Κορυφαίος των αποστόλων",
    "Leaders of the Apostles, Peter and Paul": "Οι κορυφαίοι των αποστόλων, Πέτρος και Παύλος",
    "Leavetaking of the Annunciation": "Απόδοσις του Ευαγγελισμού",
    "Martyrs of Persia": "Μάρτυρες της Περσίας",
    "Martysz, Archpriest, New Martyr": "Μάρτις, πρωτοπρεσβύτερος, νεομάρτυς",
    "Matskvereli, of Atskuri": "Ματσκβερέλι, του Ατσκούρι",
    "Matushka of All Alaska": "Μάτουσκα πάσης Αλάσκας",
    "Maximus, and Quinctilian, at Dorostolum": "Μάξιμος και Κυντιλιανός, εν Δορυστόλω",
    "Meeting of the Vladimir Icon of the Mother of God": "Η υπαπαντή της Βλαδιμηρινής εικόνος της Θεοτόκου",
    "Metropolitan of All Russia": "Μητροπολίτης πάσης Ρωσίας",
    "Metropolitan of Kyiv": "Μητροπολίτης Κιέβου",
    "Metropolitan of Kyiv and All Rus": "Μητροπολίτης Κιέβου και πάσης Ρωσίας",
    "Metropolitan of Kyiv and All Russia": "Μητροπολίτης Κιέβου και πάσης Ρωσίας",
    "Metropolitan of Moscow": "Μητροπολίτης Μόσχας",
    "Metropolitan of Moscow and All Russia, Wonderworker": "Μητροπολίτης Μόσχας και πάσης Ρωσίας, θαυματουργός",
    "Metropolitan of Moscow and All Russia, Wonderworker, Hieromartyr": "Μητροπολίτης Μόσχας και πάσης Ρωσίας, θαυματουργός, ιερομάρτυς",
    "Metropolitan of Moscow, Enlightener of North America": "Μητροπολίτης Μόσχας, φωτιστής της Βορείου Αμερικής",
    "Metropolitan of Tobolsk and all Siberia": "Μητροπολίτης Τομπόλσκ και πάσης Σιβηρίας",
    "Mother of Saint Basil the Great": "Μήτηρ του Μεγάλου Βασιλείου",
    "Mother of the Prophet Samuel": "Μήτηρ του προφήτου Σαμουήλ",
    "Mother of the Unmercenaries": "Μήτηρ των Αναργύρων",
    "Mstislav (George), Prince of Novgorod": "Μστισλάβ (Γεώργιος), ηγεμών του Νόβγκοροντ",
    "Murin": "ο Αιθίοψ",
    "Neolampes": "Νεολαμπής",
    "Nevsky": "Νιέφσκι",
    "New Martyrs and Confessors of Butovo": "Νεομάρτυρες και ομολογηταί του Μπούτοβο",
    "Paramony": "Παραμονή",
    "Passion-Bearer": "Παθοφόρος",
    "Patellarios, of Lubensk, Patriarch of Constantinople": "Πατελλάριος, του Λούμπνι, πατριάρχης Κωνσταντινουπόλεως",
    "Patriarch of Alexandria": "Πατριάρχης Αλεξανδρείας",
    "Patriarch of Antioch": "Πατριάρχης Αντιοχείας",
    "Patriarch of Constantinople": "Πατριάρχης Κωνσταντινουπόλεως",
    "Patriarch of Jerusalem": "Πατριάρχης Ιεροσολύμων",
    "Patriarch of Moscow and All Russia": "Πατριάρχης Μόσχας και πάσης Ρωσίας",
    "Patriarch of Moscow and All Russia, Wonderworker": "Πατριάρχης Μόσχας και πάσης Ρωσίας, θαυματουργός",
    "Patriarch of Moscow, Enlightener of North America": "Πατριάρχης Μόσχας, φωτιστής της Βορείου Αμερικής",
    "Peter, Dionysius, Andrew, Paul, and Christina": "Πέτρος, Διονύσιος, Ανδρέας, Παύλος και Χριστίνα",
    "Petka": "Πέτκα",
    "Philadelphus, Cyprian, Alphius, Onesimus, Erasmus, and 14 others, in Sicily": "Φιλάδελφος, Κυπριανός, Αλφειός, Ονήσιμος, Έρασμος και 14 έτεροι, εν Σικελία",
    "Physician of Corinth": "Ιατρός της Κορίνθου",
    "Placidas": "Πλακίδας",
    "Pope of Rome": "Πάπας Ρώμης",
    "Pope of Rome, and those with him": "Πάπας Ρώμης, και οι συν αυτώ",
    "Prince of Dioclea, Great Martyr and Wonderworker": "Ηγεμών της Διοκλείας, μεγαλομάρτυς και θαυματουργός",
    "Prince of Ethiopia": "Ηγεμών της Αιθιοπίας",
    "Prince of Kyiv": "Ηγεμών του Κιέβου",
    "Prince of Ordinsk, Rostov": "Ηγεμών του Ορντίνσκ, Ροστόφ",
    "Prince of Ostrog": "Ηγεμών του Όστρογκ",
    "Prince of Pskov, in baptism Timothy": "Ηγεμών του Πσκοφ, εν τω βαπτίσματι Τιμόθεος",
    "Prince of Smolensk and Yaroslavl, with his sons David and Constantine": "Ηγεμών του Σμολένσκ και του Γιαροσλάβλ, μετά των υιών αυτού Δαβίδ και Κωνσταντίνου",
    "Prince of Tver": "Ηγεμών του Τβερ",
})


# How else a saint is named, third part.
TEXT.update({
    "Prince of Uglich, tonsured as Ignatius": "Ηγεμών του Ούγκλιτς, καρείς Ιγνάτιος",
    "Prince of Volodymyr-Volhynia": "Ηγεμών του Βολοντίμιρ-Βολυνσκί",
    "Princess of Lithuania": "Ηγεμονίδα της Λιθουανίας",
    "Princess of Olshansk": "Ηγεμονίδα του Όλσανσκ",
    "Princess of Vyazma": "Ηγεμονίδα της Βιάζμα",
    "Protomartyr among women": "Πρωτομάρτυς μεταξύ των γυναικών",
    "Protomartyr and Archdeacon": "Πρωτομάρτυς και αρχιδιάκονος",
    "Protomartyr of America": "Πρωτομάρτυς της Αμερικής",
    "Protomartyr of Britain": "Πρωτομάρτυς της Βρετανίας",
    "Publius, Timolaus, Romulus, two named Dionysius, and two named Alexander, at Caesarea": "Πούβλιος, Τιμόλαος, Ρωμύλος, δύο ονόματι Διονύσιος και δύο ονόματι Αλέξανδρος, εν Καισαρεία",
    "Publius, and Terence, of Carthage": "Πούβλιος και Τερέντιος, εκ Καρχηδόνος",
    "Pyatnitsa": "Παρασκευή",
    "Queen of Georgia": "Βασίλισσα της Γεωργίας",
    "Recluse of the Far Caves": "Έγκλειστος των Απωτέρων Σπηλαίων",
    "Recluse of the Kyiv Caves and Bishop of Turov": "Έγκλειστος των Σπηλαίων του Κιέβου και επίσκοπος Τούροφ",
    "Recluse of the Kyiv Far Caves": "Έγκλειστος των Απωτέρων Σπηλαίων του Κιέβου",
    "Righteous Child": "Δίκαιον παιδίον",
    "Righteous Youths John and Jacob of Meniugi": "Οι δίκαιοι παίδες Ιωάννης και Ιάκωβος της Μενιούσα",
    "Sabas the Elder": "Σάββας ο Πρεσβύτερος",
    "Salos, of Pskov, the Fool-For-Christ": "Σαλός, του Πσκοφ, ο διά Χριστόν σαλός",
    "Sava II, Archbishop of Serbia": "Σάββας Β', αρχιεπίσκοπος Σερβίας",
    "Second Sunday of Great Lent: Saint Gregory Palamas": "Β' Κυριακή της Μεγάλης Τεσσαρακοστής: του αγίου Γρηγορίου του Παλαμά",
    "Second Translation of the relics of Saint Herman, Archbishop of Kazan": "Δευτέρα ανακομιδή των λειψάνων του αγίου Γερμανού, αρχιεπισκόπου Καζάν",
    "Seven Martyred Brothers, in Georgia": "Επτά αδελφοί μάρτυρες, εν Γεωργία",
    "Son of Alphaeus": "Υιός του Αλφαίου",
    "Son of Jacob": "Υιός του Ιακώβ",
    "Starets of Neamts": "Γέρων του Νεάμτς",
    "Stratelates “the General” of Rome, and 70 soldiers with him": "Στρατηλάτης της Ρώμης, και 70 στρατιώται μετ' αυτού",
    "Stratelates, the General": "Στρατηλάτης",
    "Stratelates, who suffered in Galatia, and those with him": "Στρατηλάτης, ο αθλήσας εν Γαλατία, και οι συν αυτώ",
    "Stylites the Younger, of the Wonderful Mountain": "Στυλίτης ο Νέος, του Θαυμαστού Όρους",
    "Sviatosha": "Σβιατόσα",
    "Sweet-Singer": "ο Μελωδός",
    "Synaxis of the Holy, Glorious and All-Praised Twelve Apostles": "Σύναξις των αγίων ενδόξων και πανευφήμων Δώδεκα Αποστόλων",
    "Synaxis of the Saints of Rostov and Yaroslavl": "Σύναξις των αγίων του Ροστόφ και του Γιαροσλάβλ",
    "Tanqilria Arrsamquq": "Τανκίλρια Αρρσάμκουκ",
    "Thaumaturgus": "Θαυματουργός",
    "The Burning of Saint Sava's relics": "Η καύσις των λειψάνων του αγίου Σάββα",
    "Theodotus, Hesychius, and Asclepiodota": "Θεόδοτος, Ησύχιος και Ασκληπιοδότη",
    "Theognes, Rufus, Antipater, Theostichus, Artemas, Magnus, Theodotus, Thaumasius, and Philemon": "Θεογνής, Ρούφος, Αντίπατρος, Θεόστιχος, Αρτεμάς, Μάγνος, Θεόδοτος, Θαυμάσιος και Φιλήμων",
    "Theonas, and Anthony, at Rome": "Θεωνάς και Αντώνιος, εν Ρώμη",
    "Third Finding of the Honorable Head of the Holy Prophet, Forerunner and Baptist John": "Τρίτη εύρεσις της τιμίας κεφαλής του αγίου προφήτου, Προδρόμου και Βαπτιστού Ιωάννου",
    "Third Sunday of Great Lent: Veneration of the Cross": "Γ' Κυριακή της Μεγάλης Τεσσαρακοστής: της Σταυροπροσκυνήσεως",
    "Toth, Confessor and Defender of Orthodoxy in America": "Τοθ, ομολογητής και υπερασπιστής της Ορθοδοξίας εν Αμερική",
    "Translation of his relics": "Ανακομιδή των λειψάνων αυτού",
    "Translation of the Relics of the Holy Passionbearers Borys and Hlib": "Ανακομιδή των λειψάνων των αγίων παθοφόρων Βόρις και Γκλεμπ",
    "Translation of the Relics of the holy and wonderworking Unmercenaries Cyrus and John": "Ανακομιδή των λειψάνων των αγίων και θαυματουργών αναργύρων Κύρου και Ιωάννου",
    "Translation of the relics of Blessed Vsevolod (in Baptism Gabriel), Prince of Pskov": "Ανακομιδή των λειψάνων του μακαρίου Βσέβολοντ (εν τω βαπτίσματι Γαβριήλ), ηγεμόνος του Πσκοφ",
    "Translation of the relics of Saint Gurias, Archbishop of Kazan": "Ανακομιδή των λειψάνων του αγίου Γουρία, αρχιεπισκόπου Καζάν",
    "Translation of the relics of Saint Nicholas the Wonderworker from Myra to Bari": "Ανακομιδή των λειψάνων του αγίου Νικολάου του θαυματουργού εκ Μύρων εις Μπάρι",
    "Translation of the relics of Saint Tikhon of Luchov, Kostroma": "Ανακομιδή των λειψάνων του αγίου Τύχωνος του Λούχοφ, Κοστρομά",
    "Translation of the relics of Venerable Nilus of Stolobensk": "Ανακομιδή των λειψάνων του οσίου Νείλου του Στολομπένσκ",
    "Translation of the relics of slain Crown Prince Demetrius of Moscow": "Ανακομιδή των λειψάνων του σφαγέντος διαδόχου Δημητρίου της Μόσχας",
    "Translation of the relics of the Greatmartyr Theodore Stratelates": "Ανακομιδή των λειψάνων του μεγαλομάρτυρος Θεοδώρου του Στρατηλάτου",
    "Tribimius, Marcellus, and Anthony, of Perge": "Τριβίμιος, Μάρκελλος και Αντώνιος, εκ Πέργης",
    "Tsar Lazar (Vidovdan)": "Τσάρος Λάζαρος (Βίντοβνταν)",
    "Tsarevich of Uglich and Moscow": "Τσαρέβιτς του Ούγκλιτς και της Μόσχας",
    "Tverdislov, Fool-for-Christ and Wonderworker of Rostov": "Τβερντισλόφ, διά Χριστόν σαλός και θαυματουργός του Ροστόφ",
    "Uncovering of the Precious Cross and the Nails, by Empress Helena": "Η εύρεσις του Τιμίου Σταυρού και των Ήλων υπό της αυτοκράτειρας Ελένης",
    "Uncovering of the Relics of Saint Alexander of Svir": "Εύρεσις των λειψάνων του αγίου Αλεξάνδρου του Σβιρ",
    "Uncovering of the relics of Saint Alexis, Metropolitan of Moscow and Wonderworker of All Russia": "Εύρεσις των λειψάνων του αγίου Αλεξίου, μητροπολίτου Μόσχας και θαυματουργού πάσης Ρωσίας",
    "Uncovering of the relics of Saint Basil, Bishop of Amasea": "Εύρεσις των λειψάνων του αγίου Βασιλείου, επισκόπου Αμασείας",
    "Uncovering of the relics of Saint Nikḗtas, Bishop of Novgorod": "Εύρεσις των λειψάνων του αγίου Νικήτα, επισκόπου Νόβγκοροντ",
    "Uncovering of the relics of Venerable Ephraim, Abbot of Novy Torg": "Εύρεσις των λειψάνων του οσίου Εφραίμ, ηγουμένου του Νόβι Τορκ",
    "Uncovering of the relics of Venerable James, Abbot of Zheleznoborov": "Εύρεσις των λειψάνων του οσίου Ιακώβου, ηγουμένου του Ζελεζνομπόροφ",
    "Uncovering of the relics of Venerable Macarius, Abbot of Kalyazin": "Εύρεσις των λειψάνων του οσίου Μακαρίου, ηγουμένου του Καλιάζιν",
    "Uncovering of their relics": "Εύρεσις των λειψάνων αυτών",
    "Velichkovsky": "Βελιτσκόφσκι",
    "Victor, Nikephoros, Claudius, Diodorus, Serapion, and Papias, of Corinth": "Βίκτωρ, Νικηφόρος, Κλαύδιος, Διόδωρος, Σεραπίων και Παπίας, εκ Κορίνθου",
    "Virgin Martyr of Nisibis": "Παρθενομάρτυς της Νισίβεως",
    "Wonderworker of Aegina": "Θαυματουργός της Αιγίνης",
    "Wonderworker of Priluki, Vologda": "Θαυματουργός του Πριλούκι, Βόλογκντα",
    "Wonderworker of Ustiug": "Θαυματουργός του Ουστιούγκ",
    "Wonderworker of the Kyiv Caves": "Θαυματουργός των Σπηλαίων του Κιέβου",
    "Wonderworker, Abbot of Triglia": "Θαυματουργός, ηγούμενος της Τρίγλιας",
    "Wonderworkers of Valaam": "Θαυματουργοί του Βαλαάμ",
    "Yaroslavl-Pechersk Icon of the Mother of God": "Η Γιαροσλάβλ-Πετσέρσκαγια εικών της Θεοτόκου",
    "Zoticus, Zeno, Acindynus, and Severian, of Nicomedia": "Ζωτικός, Ζήνων, Ακίνδυνος και Σεβηριανός, εκ Νικομηδείας",
    "and 199 disciples with him in Sicily": "και 199 μαθηταί μετ' αυτού εν Σικελία",
    "and 40 others beheaded at Carthage": "και 40 έτεροι αποκεφαλισθέντες εν Καρχηδόνι",
    "and Anastasia of Rome, disciples of the Apostles Peter and Paul": "και Αναστασία η Ρωμαία, μαθηταί των αποστόλων Πέτρου και Παύλου",
    "and Antoninus, ascetics of the Syrian deserts": "και Αντωνίνος, ασκηταί των συριακών ερήμων",
    "and Daria, and those with them at Rome: Claudius, Hilaria, Jason, Maurus, Diodorus the presbyter, and Marianus the deacon": "και Δαρεία, και οι συν αυτοίς εν Ρώμη: Κλαύδιος, Ιλαρία, Ιάσων, Μαύρος, Διόδωρος ο πρεσβύτερος και Μαριανός ο διάκονος",
    "and Eucarpus of Nicomedia": "και Ευκάρπιος εκ Νικομηδείας",
    "and Euphrosynē of Alexandria": "και Ευφροσύνη εξ Αλεξανδρείας",
    "and Limnus of Smyrna, with Sabina, Macedonia, and Asclepiades": "και Λιμναίος εκ Σμύρνης, μετά Σαβίνης, Μακεδονίας και Ασκληπιάδου",
    "and Macarius, Presbyters and Confessors, at Antioch": "και Μακάριος, πρεσβύτεροι και ομολογηταί, εν Αντιοχεία",
    "and Martinian of Rome": "και Μαρτινιανός ο Ρωμαίος",
    "and Myrope, of Chios": "και Μυρόπη, εκ Χίου",
    "and Pasikrates in Moesia, Bulgaria": "και Πασικράτης εν Μοισία, Βουλγαρίας",
    "and Philemon of the Seventy, and Martyr Apphia": "και Φιλήμων εκ των Εβδομήκοντα, και η μάρτυς Απφία",
    "and Protoleon, soldiers converted by witnessing the martyrdom of Saint George": "και Πρωτολέων, στρατιώται οι πιστεύσαντες ιδόντες το μαρτύριον του αγίου Γεωργίου",
    "and Rhodopianus, Deacons, at Aphrodisia in Anatolia": "και Ροδοπιανός, διάκονοι, εν Αφροδισιάδι της Ανατολίας",
    "and Sosipater of the Seventy, the Virgin Kerkyra, and those with them": "και Σωσίπατρος εκ των Εβδομήκοντα, η παρθένος Κερκύρα, και οι συν αυτοίς",
    "and Theodosius": "και Θεοδόσιος",
    "and Zoilus": "και Ζωίλος",
    "and companions, of Gaul": "και οι σύντροφοι αυτού, εκ Γαλατίας",
    "and his son Photinus, and Martyrs Theodore, Philip, and 70 soldiers": "και ο υιός αυτού Φωτεινός, και οι μάρτυρες Θεόδωρος, Φίλιππος και 70 στρατιώται",
    "and the 370 Martyrs": "και οι 370 μάρτυρες",
    "and those who suffered with him at Byzantium": "και οι συναθλήσαντες αυτώ εν Βυζαντίω",
    "and those with him at Corinth": "και οι συν αυτώ εν Κορίνθω",
    "and those with him at Nicomedia, with Saturninus and Rufinus": "και οι συν αυτώ εν Νικομηδεία, μετά Σατορνίνου και Ρουφίνου",
    "at Alexandria": "εν Αλεξανδρεία",
    "at Arbela": "εν Άρβηλοις",
    "at Caesarea in Cappadocia": "εν Καισαρεία της Καππαδοκίας",
    "at Chalcedon": "εν Χαλκηδόνι",
    "at Comana": "εν Κομάνοις",
    "at Damascus": "εν Δαμασκώ",
    "at Heraclea": "εν Ηρακλεία",
    "at Lucania": "εν Λευκανία",
    "at Nicomedia": "εν Νικομηδεία",
    "at Rome": "εν Ρώμη",
    "at Rome, with his companions": "εν Ρώμη, μετά των συντρόφων αυτού",
    "at Tarsus, with Righteous Aglaida of Rome": "εν Ταρσώ, μετά της δικαίας Αγλαΐδος της Ρωμαίας",
    "at Tripoli in Syria": "εν Τριπόλει της Συρίας",
    "brother of Saint Gregory the Theologian": "αδελφός του αγίου Γρηγορίου του Θεολόγου",
    "called Marinus, and her father Eugene": "η καλουμένη Μαρίνος, και ο πατήρ αυτής Ευγένιος",
    "daughter of Emperor Trajan": "θυγάτηρ του αυτοκράτορος Τραϊανού",
    "disciple of Venerable Sergius of Radonezh": "μαθητής του οσίου Σεργίου του Ραντονέζ",
    "disciple of the Apostle Paul": "μαθητής του αποστόλου Παύλου",
    "disciple of the Apostles": "μαθητής των αποστόλων",
    "disciples of the Apostle Andrew in Scythia": "μαθηταί του αποστόλου Ανδρέου εν Σκυθία",
    "first Bishop of Rostov and Suzdal": "πρώτος επίσκοπος Ροστόφ και Σούζνταλ",
    "first Patriarch of Constantinople": "πρώτος πατριάρχης Κωνσταντινουπόλεως",
    "grandson of Aaron": "έγγονος του Ααρών",
    "in Baptism Gabriel, Wonderworker of Pskov": "εν τω βαπτίσματι Γαβριήλ, θαυματουργός του Πσκοφ",
    "in Cilicia": "εν Κιλικία",
    "in Martyropolis": "εν Μαρτυρουπόλει",
    "in baptism Yaroslav, with his children Michael and Theodore, Wonderworkers of Murom": "εν τω βαπτίσματι Γιαροσλάβ, μετά των τέκνων αυτού Μιχαήλ και Θεοδώρου, θαυματουργών του Μουρόμ",
    "in monasticism Simeon, the Myrrh-gusher": "εν τω μοναχικώ σχήματι Συμεών, ο Μυροβλύτης",
})
