# -*- coding: utf-8 -*-
"""Greek for the vocabulary that stands beside the lives.

TEXT = {the phrase the index shows: the Greek}. PARTS holds the pieces the
compound place-names are built from, and expand() assembles the wholes, so a
town cannot be spelled one way on one card and another way on the next.

Greek is the tongue the greater part of this vocabulary was first said in,
and where that is so the phrase goes home rather than being carried across:
the orders of sanctity, the ranks of the Typikon, the ancient sees and the
provinces of the Christian East are given as the Greek Church gives them,
not as renderings of the English renderings of them. The Slavic, Georgian
and Latin names take the forms the Greek synaxaria have received, and where
no received form exists the name is transliterated.

The keys are the phrases exactly as the index writes them, so a rendering
cannot quietly attach itself to the wrong saint.
"""
TEXT = {}



# The orders of sanctity, as the badge on a card names them.
TEXT.update({
    "Angelic": "Ασώματοι Δυνάμεις",
    "Apostle": "Απόστολος",
    "Confessor": "Ομολογητής",
    "Equal-to-the-Apostles": "Ισαπόστολος",
    "Feast": "Εορτή",
    "Fool-for-Christ": "Διά Χριστόν σαλός",
    "Great Martyr": "Μεγαλομάρτυς",
    "Hierarch": "Ιεράρχης",
    "Hieromartyr": "Ιερομάρτυς",
    "Martyr": "Μάρτυς",
    "Monastic": "Όσιος",
    "New Martyr": "Νεομάρτυς",
    "Other": "Άλλο",
    "Passion-bearer": "Παθοφόρος",
    "Prophet": "Προφήτης",
    "Righteous": "Δίκαιος",
    "Unmercenary": "Ανάργυρος",
    "Virgin Martyr": "Παρθενομάρτυς",
})


# The attributes a life is marked with.
TEXT.update({
    "Apostle": "Απόστολος",
    "Church Father": "Πατήρ της Εκκλησίας",
    "Confessor": "Ομολογητής",
    "Desert ascetic": "Ασκητής της ερήμου",
    "Enlightener": "Φωτιστής",
    "Fool-for-Christ": "Διά Χριστόν σαλός",
    "Healing intercessor": "Ιαματικός",
    "Hymnographer": "Υμνογράφος",
    "Iconographer": "Αγιογράφος",
    "Incorrupt relics": "Άφθαρτα λείψανα",
    "Monastery founder": "Κτίτωρ μονής",
    "Myrrh-bearer": "Μυροφόρος",
    "Myrrh-streaming": "Μυροβλύτης",
    "New martyr": "Νεομάρτυς",
    "Passion-bearer": "Παθοφόρος",
    "Prophet": "Προφήτης",
    "Ruler or royal": "Ηγεμών ή βασιλικού γένους",
    "Stylite": "Στυλίτης",
    "Unmercenary": "Ανάργυρος",
    "Warrior saint": "Στρατιωτικός άγιος",
    "Wonderworker": "Θαυματουργός",
})


# The ranks the Typikon gives a feast.
TEXT.update({
    "Doxology": "Δοξολογία",
    "Great Feast": "Μεγάλη εορτή",
    "Polyeleos": "Πολυέλεος",
    "Simple": "Απλή",
    "Vigil": "Αγρυπνία",
})


# The jurisdictions whose calendars the index keeps.
TEXT.update({
    "Antiochian": "Αντιοχειανή",
    "Greek": "Ελληνική",
    "OCA": "ΟΕΑ",
    "Romanian": "Ρουμανική",
    "Russian": "Ρωσική",
    "Serbian": "Σερβική",
    "Ukrainian": "Ουκρανική",
})


# The estate a saint stood in.
TEXT.update({
    "Apostolic": "Αποστολική",
    "Clergy": "Κλήρος",
    "Laity": "Λαϊκοί",
    "Layman": "Λαϊκός",
    "Laywoman": "Λαϊκή",
    "Laywomen": "Λαϊκές",
    "Married": "Έγγαμος βίος",
    "Military": "Στρατιωτικός",
    "Monastic": "Μοναχικός",
    "Prophet": "Προφήτης",
    "Royal": "Βασιλικό",
    "Royalty": "Βασιλικό γένος",
    "Unknown": "Άγνωστο",
    "Unmarried": "Αγαμία",
    "Widowed": "Χηρεία",
})


# The ages the lives are set in.
TEXT.update({
    "Age of the Celtic Saints": "Εποχή των Κελτών αγίων",
    "Age of the Ecumenical Councils": "Εποχή των Οικουμενικών Συνόδων",
    "Age of the Martyrs": "Εποχή των Μαρτύρων",
    "Apostolic Age": "Αποστολική εποχή",
    "Byzantine": "Βυζαντινή",
    "Byzantine Balkans": "Βυζαντινά Βαλκάνια",
    "Byzantine Era": "Βυζαντινή εποχή",
    "Byzantine Iconoclasm": "Βυζαντινή εικονομαχία",
    "Cossack Era": "Εποχή των Κοζάκων",
    "Desert Fathers": "Πατέρες της ερήμου",
    "Early Medieval West": "Πρώιμη μεσαιωνική Δύση",
    "Imperial Russia": "Αυτοκρατορική Ρωσία",
    "Kievan Rus'": "Ρωσία του Κιέβου",
    "Medieval Georgia": "Μεσαιωνική Γεωργία",
    "Medieval Rus'": "Μεσαιωνική Ρωσία",
    "Medieval Serbia": "Μεσαιωνική Σερβία",
    "Modern": "Νεότερη",
    "Modern Era": "Νεότερη εποχή",
    "Muscovite Russia": "Ρωσία της Μόσχας",
    "Old Testament": "Παλαιά Διαθήκη",
    "Ottoman Balkans": "Οθωμανικά Βαλκάνια",
    "Ottoman Era": "Οθωμανική εποχή",
    "Ottoman period": "Οθωμανική περίοδος",
    "Polish-Lithuanian period": "Πολωνολιθουανική περίοδος",
    "Soviet Era": "Σοβιετική εποχή",
    "Soviet period": "Σοβιετική περίοδος",
    "Synodal Russia": "Συνοδική Ρωσία",
})


# The countries and the regions.
TEXT.update({
    "Aegean": "Αιγαίο",
    "Albania": "Αλβανία",
    "America": "Αμερική",
    "Arabia": "Αραβία",
    "Armenia": "Αρμενία",
    "Asia Minor": "Μικρά Ασία",
    "Balkans": "Βαλκάνια",
    "Belarus": "Λευκορωσία",
    "Bithynia": "Βιθυνία",
    "Bohemia": "Βοημία",
    "Britain": "Βρετανία",
    "British Isles": "Βρετανικές Νήσοι",
    "Bulgaria": "Βουλγαρία",
    "Cappadocia": "Καππαδοκία",
    "China": "Κίνα",
    "Cilicia": "Κιλικία",
    "Constantinople": "Κωνσταντινούπολη",
    "Crimea": "Κριμαία",
    "Cyprus": "Κύπρος",
    "Czech Lands": "Τσεχικές χώρες",
    "Dalmatia": "Δαλματία",
    "Danube lands": "Παραδουνάβιες χώρες",
    "Egypt": "Αίγυπτος",
    "England": "Αγγλία",
    "Ethiopia": "Αιθιοπία",
    "France": "Γαλλία",
    "Gaul": "Γαλατία",
    "Georgia": "Γεωργία",
    "Greece": "Ελλάδα",
    "Holy Land": "Άγιοι Τόποι",
    "Illyria": "Ιλλυρία",
    "Illyricum": "Ιλλυρικό",
    "India": "Ινδία",
    "Ireland": "Ιρλανδία",
    "Italy": "Ιταλία",
    "Judah": "Ιουδαία",
    "Lithuania": "Λιθουανία",
    "Macedonia": "Μακεδονία",
    "Mesopotamia": "Μεσοποταμία",
    "Moesia": "Μοισία",
    "Moldavia": "Μολδαβία",
    "Montenegro": "Μαυροβούνιο",
    "Moravia": "Μοραβία",
    "Mount Athos": "Άγιον Όρος",
    "North Africa": "Βόρεια Αφρική",
    "North America": "Βόρεια Αμερική",
    "North Macedonia": "Βόρεια Μακεδονία",
    "Palestine": "Παλαιστίνη",
    "Persia": "Περσία",
    "Phoenicia": "Φοινίκη",
    "Poland": "Πολωνία",
    "Pontus": "Πόντος",
    "Romania": "Ρουμανία",
    "Rome": "Ρώμη",
    "Russia": "Ρωσία",
    "Scythia": "Σκυθία",
    "Serbia": "Σερβία",
    "Siberia": "Σιβηρία",
    "Sicily": "Σικελία",
    "Sinai": "Σινά",
    "Spain": "Ισπανία",
    "Syria": "Συρία",
    "Thrace": "Θράκη",
    "Ukraine": "Ουκρανία",
    "United States": "Ηνωμένες Πολιτείες",
    "Western Rus": "Δυτική Ρωσία",
})


# The one movable commemoration the index names.
TEXT.update({
    "Sunday of the Holy Forefathers": "Κυριακή των Αγίων Προπατόρων",
})


# The rank a saint is given.
TEXT.update({
    "Abbess": "Ηγουμένη",
    "Abbot (Archimandrite)": "Ηγούμενος (αρχιμανδρίτης)",
    "Abbot (Founder)": "Ηγούμενος (κτίτωρ)",
    "Abbot (Igumen)": "Ηγούμενος",
    "Abbot (Igumen), Confessor": "Ηγούμενος, ομολογητής",
    "Abbot (Igumen), Hieromartyr": "Ηγούμενος, ιερομάρτυς",
    "Abbot (Igumen), Martyr": "Ηγούμενος, μάρτυς",
    "Abbot (Igumen), Monastic Martyr": "Ηγούμενος, οσιομάρτυς",
    "Abbot, Confessor": "Ηγούμενος, ομολογητής",
    "Abbot, Confessor-Martyr": "Ηγούμενος, ομολογητής και μάρτυς",
    "Abbot, Priest": "Ηγούμενος, ιερεύς",
    "Abbots": "Ηγούμενοι",
    "Anchorite": "Αναχωρητής",
    "Apostle": "Απόστολος",
    "Apostle of the Seventy": "Απόστολος εκ των Εβδομήκοντα",
    "Apostle of the Seventy, Bishop": "Απόστολος εκ των Εβδομήκοντα, επίσκοπος",
    "Apostle of the Seventy, Martyr": "Απόστολος εκ των Εβδομήκοντα, μάρτυς",
    "Apostle, Evangelist": "Απόστολος, ευαγγελιστής",
    "Apostle, Martyr": "Απόστολος, μάρτυς",
    "Apostles": "Απόστολοι",
    "Apostles of the Seventy": "Απόστολοι εκ των Εβδομήκοντα",
    "Apostles of the Seventy, Martyrs": "Απόστολοι εκ των Εβδομήκοντα, μάρτυρες",
    "Archangel": "Αρχάγγελος",
    "Archbishop": "Αρχιεπίσκοπος",
    "Archbishop, Confessor": "Αρχιεπίσκοπος, ομολογητής",
    "Archbishop, Equal-to-the-Apostles": "Αρχιεπίσκοπος, ισαπόστολος",
    "Archdeacon": "Αρχιδιάκονος",
    "Archimandrite": "Αρχιμανδρίτης",
    "Bishop": "Επίσκοπος",
    "Bishop, Church Father": "Επίσκοπος, πατήρ της Εκκλησίας",
    "Bishop, Confessor": "Επίσκοπος, ομολογητής",
    "Bishop, Equal-to-the-Apostles": "Επίσκοπος, ισαπόστολος",
    "Bishop, Hieromartyr": "Επίσκοπος, ιερομάρτυς",
    "Bishop, Monk": "Επίσκοπος, μοναχός",
    "Bishops": "Επίσκοποι",
    "Blessed Eldress": "Μακαρία γερόντισσα",
    "Chamberlain (cubicularius)": "Κουβικουλάριος",
    "Childmartyr": "Παιδομάρτυς",
    "Commander": "Στρατηλάτης",
    "Confessor": "Ομολογητής",
    "Confessor, Archpriest": "Ομολογητής, πρωτοπρεσβύτερος",
    "Deacon": "Διάκονος",
    "Deacon, Monk-martyr": "Διάκονος, οσιομάρτυς",
    "Deaconess": "Διακόνισσα",
    "Deaconess and Martyr": "Διακόνισσα και μάρτυς",
    "Elder": "Γέρων",
    "Empress": "Αυτοκράτειρα",
    "Equal-to-the-Apostles": "Ισαπόστολος",
    "Equal-to-the-Apostles, Emperor": "Ισαπόστολος, αυτοκράτωρ",
    "Equals-to-the-Apostles": "Ισαπόστολοι",
    "Feast": "Εορτή",
    "Fool-for-Christ": "Διά Χριστόν σαλός",
    "Grand Duchess": "Μεγάλη δούκισσα",
    "Grand Prince": "Μέγας ηγεμών",
    "Grand Princess": "Μεγάλη ηγεμονίδα",
    "Great Martyr": "Μεγαλομάρτυς",
    "Great Martyr, Equal-to-the-Apostles": "Μεγαλομάρτυς, ισαπόστολος",
    "Great Prince, Martyr": "Μέγας ηγεμών, μάρτυς",
    "Great-martyr": "Μεγαλομάρτυς",
    "Great-martyr, Prince": "Μεγαλομάρτυς, ηγεμών",
    "Hermit": "Ερημίτης",
    "Hermits": "Ερημίτες",
    "Hierarchs": "Ιεράρχες",
    "Hieromartyr": "Ιερομάρτυς",
    "Hieromartyr (Hermit)": "Ιερομάρτυς (ερημίτης)",
    "Hieromartyr, Apostle": "Ιερομάρτυς, απόστολος",
    "Hieromartyr, Archbishop": "Ιερομάρτυς, αρχιεπίσκοπος",
    "Hieromartyr, Archimandrite": "Ιερομάρτυς, αρχιμανδρίτης",
    "Hieromartyr, Archpriest": "Ιερομάρτυς, πρωτοπρεσβύτερος",
    "Hieromartyr, Bishop": "Ιερομάρτυς, επίσκοπος",
    "Hieromartyr, Confessor": "Ιερομάρτυς, ομολογητής",
    "Hieromartyr, Deacon": "Ιερομάρτυς, διάκονος",
    "Hieromartyr, Patriarch": "Ιερομάρτυς, πατριάρχης",
    "Hieromartyr, Pope": "Ιερομάρτυς, πάπας",
    "Hieromartyr, and his son": "Ιερομάρτυς και ο υιός αυτού",
    "Hieromartyrs": "Ιερομάρτυρες",
    "Hieromonk": "Ιερομόναχος",
    "Hieroschemamonk": "Ιεροσχημόναχος",
    "High Priest": "Αρχιερεύς",
    "Icon of the Mother of God": "Εικόνα της Θεοτόκου",
    "King and Martyr": "Βασιλεύς και μάρτυς",
    "King and Prophet": "Βασιλεύς και προφήτης",
    "Laity": "Λαϊκοί",
    "Layman": "Λαϊκός",
    "Laymen": "Λαϊκοί",
    "Laywoman": "Λαϊκή",
    "Martyr": "Μάρτυς",
    "Martyrs": "Μάρτυρες",
    "Master Builders, Monks": "Αρχιτέκτονες, μοναχοί",
    "Metropolitan": "Μητροπολίτης",
    "Metropolitan, Equal-to-the-Apostles": "Μητροπολίτης, ισαπόστολος",
    "Monastic": "Όσιος",
    "Monastic Martyr": "Οσιομάρτυς",
    "Monastic Martyrs": "Οσιομάρτυρες",
    "Monastic New Martyr": "Οσιονεομάρτυς",
    "Monastics": "Όσιοι",
    "Monk": "Μοναχός",
    "Monk (Founder)": "Μοναχός (κτίτωρ)",
    "Monk (Hermit)": "Μοναχός (ερημίτης)",
    "Monk (elder)": "Μοναχός (γέρων)",
    "Monk (hermit)": "Μοναχός (ερημίτης)",
    "Monk (novice)": "Μοναχός (δόκιμος)",
    "Monk (recluse)": "Μοναχός (έγκλειστος)",
    "Monk (stylite)": "Μοναχός (στυλίτης)",
    "Monk, Church Father": "Μοναχός, πατήρ της Εκκλησίας",
    "Monk, Confessor": "Μοναχός, ομολογητής",
    "Monk, Elder": "Μοναχός, γέρων",
    "Monk, Hymnographer": "Μοναχός, υμνογράφος",
    "Monk, Martyr": "Μοναχός, μάρτυς",
    "Monk, Recluse": "Μοναχός, έγκλειστος",
    "Monk, Unmercenary Physician": "Μοναχός, ανάργυρος ιατρός",
    "Monk, former Great Zhupan": "Μοναχός, πρώην Μέγας Ζουπάνος",
    "Monk-martyr": "Οσιομάρτυς",
    "Monk-martyrs": "Οσιομάρτυρες",
    "Monks": "Μοναχοί",
    "Monks (Founders)": "Μοναχοί (κτίτορες)",
    "Mother": "Μήτηρ",
    "Myrrhbearer": "Μυροφόρος",
    "New Martyr": "Νεομάρτυς",
    "New Martyrs": "Νεομάρτυρες",
    "New Martyrs and Confessors": "Νεομάρτυρες και ομολογητές",
    "Nun": "Μοναχή",
    "Nun-martyr": "Οσιομάρτυς",
    "Passion-bearer": "Παθοφόρος",
    "Patriarch": "Πατριάρχης",
    "Patriarch, Church Father": "Πατριάρχης, πατήρ της Εκκλησίας",
    "Patriarch, Confessor": "Πατριάρχης, ομολογητής",
    "Patriarch, Hieromartyr": "Πατριάρχης, ιερομάρτυς",
    "Physician": "Ιατρός",
    "Physicians": "Ιατροί",
    "Pope": "Πάπας",
    "Pope of Rome, Confessor": "Πάπας Ρώμης, ομολογητής",
    "Presbyter and Deacon": "Πρεσβύτερος και διάκονος",
    "Presbyters, Confessors": "Πρεσβύτεροι, ομολογητές",
    "Priest": "Ιερεύς",
    "Prince": "Ηγεμών",
    "Prince of Moldavia": "Ηγεμών της Μολδαβίας",
    "Prince, Passion-Bearer": "Ηγεμών, παθοφόρος",
    "Princes": "Ηγεμόνες",
    "Princess": "Ηγεμονίδα",
    "Princess, Nun": "Ηγεμονίδα, μοναχή",
    "Proconsul (military commander)": "Ανθύπατος (στρατηλάτης)",
    "Prophet": "Προφήτης",
    "Prophet and Forerunner": "Προφήτης και Πρόδρομος",
    "Prophetess": "Προφήτις",
    "Protomartyr": "Πρωτομάρτυς",
    "Protopresbyter": "Πρωτοπρεσβύτερος",
    "Recluse": "Έγκλειστος",
    "Right-believing Prince": "Ευσεβής ηγεμών",
    "Right-believing Prince (Monk)": "Ευσεβής ηγεμών (μοναχός)",
    "Right-believing Prince and Princess": "Ευσεβείς ηγεμών και ηγεμονίδα",
    "Right-believing Prince, Passion-bearer": "Ευσεβής ηγεμών, παθοφόρος",
    "Right-believing Princess (Nun)": "Ευσεβής ηγεμονίδα (μοναχή)",
    "Right-believing Princess, Martyr": "Ευσεβής ηγεμονίδα, μάρτυς",
    "Righteous": "Δίκαιος",
    "Righteous (Child)": "Δίκαιος (παιδίον)",
    "Righteous (Children)": "Δίκαιοι (παιδία)",
    "Righteous (Unmercenary)": "Δίκαιος (ανάργυρος)",
    "Righteous Forefather": "Δίκαιος προπάτωρ",
    "Righteous Virgin": "Δικαία παρθένος",
    "Righteous, Priest": "Δίκαιος, ιερεύς",
    "Roman soldier": "Ρωμαίος στρατιώτης",
    "Schemamonk": "Μεγαλόσχημος μοναχός",
    "Stylite": "Στυλίτης",
    "Synaxis": "Σύναξις",
    "Tsar and Imperial Family": "Τσάρος και η αυτοκρατορική οικογένεια",
    "Unmercenary Martyrs": "Ανάργυροι μάρτυρες",
    "Venerable": "Όσιος",
    "Venerable Prince": "Όσιος ηγεμών",
    "Venerable Princess": "Οσία ηγεμονίδα",
    "Virgin": "Παρθένος",
    "Virgin Martyr": "Παρθενομάρτυς",
    "Virgin Martyrs": "Παρθενομάρτυρες",
    "Virgin-martyr": "Παρθενομάρτυς",
    "Youths": "Παίδες",
})


# How a saint came to be numbered among the saints.
TEXT.update({
    "Ancient commemoration of the Church": "Αρχαία μνήμη της Εκκλησίας",
    "Ancient commemoration of the universal Church": "Αρχαία μνήμη της καθόλου Εκκλησίας",
    "Ancient observance of the Church": "Αρχαία τήρηση της Εκκλησίας",
    "Ancient observance of the universal Church": "Αρχαία τήρηση της καθόλου Εκκλησίας",
    "Church of Greece, glorified in 1921": "Εκκλησία της Ελλάδος, αγιοκατάταξη το 1921",
    "Church of Rus'": "Εκκλησία της Ρωσίας",
    "Church of Rus', among the fathers of the Caves": "Εκκλησία της Ρωσίας, μεταξύ των πατέρων των Σπηλαίων",
    "Church of Rus', glorified in 1108": "Εκκλησία της Ρωσίας, αγιοκατάταξη το 1108",
    "Church of Rus'; the common synaxis established for the whole company": "Εκκλησία της Ρωσίας· η κοινή σύναξη θεσπίστηκε για ολόκληρη τη χορεία",
    "Constantinople, under Patriarch Philotheos, within a generation of their death": "Κωνσταντινούπολη, επί πατριάρχου Φιλοθέου, μέσα σε μία γενεά από τον θάνατό τους",
    "Ecumenical Patriarchate": "Οικουμενικό Πατριαρχείο",
    "Ecumenical Patriarchate of Constantinople": "Οικουμενικό Πατριαρχείο Κωνσταντινουπόλεως",
    "Ecumenical Patriarchate of Constantinople, 1961": "Οικουμενικό Πατριαρχείο Κωνσταντινουπόλεως, 1961",
    "Ecumenical Patriarchate of Constantinople, 2015": "Οικουμενικό Πατριαρχείο Κωνσταντινουπόλεως, 2015",
    "Ecumenical Patriarchate of Constantinople, 2019": "Οικουμενικό Πατριαρχείο Κωνσταντινουπόλεως, 2019",
    "Ecumenical Patriarchate, 1703": "Οικουμενικό Πατριαρχείο, 1703",
    "Ecumenical Patriarchate, 1734": "Οικουμενικό Πατριαρχείο, 1734",
    "Ecumenical Patriarchate, 1961": "Οικουμενικό Πατριαρχείο, 1961",
    "Ecumenical Patriarchate, 1987": "Οικουμενικό Πατριαρχείο, 1987",
    "Ecumenical Patriarchate, November 27, 2013": "Οικουμενικό Πατριαρχείο, 27 Νοεμβρίου 2013",
    "Established by the Church at the restoration of the icons in 843": "Θεσπίστηκε από την Εκκλησία κατά την αναστήλωση των εικόνων το 843",
    "Established by the Church in thanksgiving for the deliverances of Constantinople": "Θεσπίστηκε από την Εκκλησία σε ευχαριστία για τις σωτηρίες της Κωνσταντινουπόλεως",
    "Established by the Church of Constantinople": "Θεσπίστηκε από την Εκκλησία της Κωνσταντινουπόλεως",
    "Established by the Russian Orthodox Church in 1964": "Θεσπίστηκε από τη Ρωσική Ορθόδοξη Εκκλησία το 1964",
    "Established by the observance of the Church": "Θεσπίστηκε από την τήρηση της Εκκλησίας",
    "Feast of the Church": "Εορτή της Εκκλησίας",
    "Feast of the Church of Rus'": "Εορτή της Εκκλησίας της Ρωσίας",
    "Feast of the Church, kept with especial devotion in the churches of Rus'": "Εορτή της Εκκλησίας, τηρούμενη με ιδιαίτερη ευλάβεια στις εκκλησίες της Ρωσίας",
    "Feast of the Russian Orthodox Church": "Εορτή της Ρωσικής Ορθόδοξης Εκκλησίας",
    "Feast of the Serbian Orthodox Church": "Εορτή της Σερβικής Ορθόδοξης Εκκλησίας",
    "Georgian Orthodox Church": "Γεωργιανή Ορθόδοξη Εκκλησία",
    "Glorified August 9, 1970, the first glorification on American soil": "Αγιοκατάταξη στις 9 Αυγούστου 1970, η πρώτη αγιοκατάταξη σε αμερικανικό έδαφος",
    "Glorified December 18, 1694, at Merkushino": "Αγιοκατάταξη στις 18 Δεκεμβρίου 1694, στο Μερκούσινο",
    "Glorified among the New Martyrs and Confessors of Russia by the Russian Orthodox Church": "Αγιοκατάταξη μεταξύ των Νεομαρτύρων και Ομολογητών της Ρωσίας από τη Ρωσική Ορθόδοξη Εκκλησία",
    "Glorified among the New Martyrs and Confessors of Russia by the Russian Orthodox Church in 2000": "Αγιοκατάταξη μεταξύ των Νεομαρτύρων και Ομολογητών της Ρωσίας από τη Ρωσική Ορθόδοξη Εκκλησία το 2000",
    "Glorified among the saints; his veneration embraced by the Churches of Constantinople and Rus'": "Αγιοκατάταξη μεταξύ των αγίων· η τιμή του έγινε δεκτή από τις Εκκλησίες της Κωνσταντινουπόλεως και της Ρωσίας",
    "Glorified by the Autocephalous Orthodox Church of Poland in 2003, among the New Martyrs of Chelm and Podlasie": "Αγιοκατάταξη από την Αυτοκέφαλη Ορθόδοξη Εκκλησία της Πολωνίας το 2003, μεταξύ των Νεομαρτύρων του Χελμ και του Ποντλάσιε",
    "Glorified by the Orthodox Church in America in 1994 at Saint Tikhon's monastery": "Αγιοκατάταξη από την Ορθόδοξη Εκκλησία στην Αμερική το 1994 στη μονή του Αγίου Τύχωνος",
    "Glorified by the Romanian Orthodox Church": "Αγιοκατάταξη από τη Ρουμανική Ορθόδοξη Εκκλησία",
    "Glorified by the Russian Orthodox Church": "Αγιοκατάταξη από τη Ρωσική Ορθόδοξη Εκκλησία",
    "Glorified by the Russian Orthodox Church in 1547": "Αγιοκατάταξη από τη Ρωσική Ορθόδοξη Εκκλησία το 1547",
    "Glorified by the Russian Orthodox Church in 1558": "Αγιοκατάταξη από τη Ρωσική Ορθόδοξη Εκκλησία το 1558",
    "Glorified by the Russian Orthodox Church in 1650; veneration restored in 1909": "Αγιοκατάταξη από τη Ρωσική Ορθόδοξη Εκκλησία το 1650· η τιμή αποκαταστάθηκε το 1909",
    "Glorified by the Russian Orthodox Church in 1916": "Αγιοκατάταξη από τη Ρωσική Ορθόδοξη Εκκλησία το 1916",
    "Glorified by the Russian Orthodox Church in 1989": "Αγιοκατάταξη από τη Ρωσική Ορθόδοξη Εκκλησία το 1989",
    "Glorified by the Russian Orthodox Church on May 12, 1913": "Αγιοκατάταξη από τη Ρωσική Ορθόδοξη Εκκλησία στις 12 Μαΐου 1913",
    "Glorified by the Russian Orthodox Church, locally in 1999 and for the whole Church in 2004": "Αγιοκατάταξη από τη Ρωσική Ορθόδοξη Εκκλησία, τοπικά το 1999 και για ολόκληρη την Εκκλησία το 2004",
    "Glorified in 1339, the first saint of Moscow": "Αγιοκατάταξη το 1339, ο πρώτος άγιος της Μόσχας",
    "Glorified in 2000": "Αγιοκατάταξη το 2000",
    "His veneration, springing from the revelation of 1950, was formally recognized by the Great Church of Christ": "Η τιμή του, που πήγασε από την αποκάλυψη του 1950, αναγνωρίστηκε επισήμως από τη Μεγάλη του Χριστού Εκκλησία",
    "Instituted by the Church of Constantinople": "Θεσπίστηκε από την Εκκλησία της Κωνσταντινουπόλεως",
    "Local veneration": "Τοπική τιμή",
    "Local veneration (glorified 1071)": "Τοπική τιμή (αγιοκατάταξη το 1071)",
    "Local veneration at the Murom monastery": "Τοπική τιμή στη μονή του Μουρόμ",
    "Local veneration in the Church of Rus'": "Τοπική τιμή στην Εκκλησία της Ρωσίας",
    "Local veneration of the Kyiv Caves": "Τοπική τιμή των Σπηλαίων του Κιέβου",
    "Local veneration of the Kyiv Caves; in the canon of the Caves fathers": "Τοπική τιμή των Σπηλαίων του Κιέβου· στον κανόνα των πατέρων των Σπηλαίων",
    "Numbered among the New Martyrs venerated by the Church": "Συγκαταλέγεται μεταξύ των Νεομαρτύρων που τιμά η Εκκλησία",
    "Numbered among the New Martyrs venerated by the Church of Greece": "Συγκαταλέγεται μεταξύ των Νεομαρτύρων που τιμά η Εκκλησία της Ελλάδος",
    "Numbered among the saints of Mount Athos": "Συγκαταλέγεται μεταξύ των αγίων του Αγίου Όρους",
    "Orthodox Church in America": "Ορθόδοξη Εκκλησία στην Αμερική",
    "Orthodox Church in America, 1980": "Ορθόδοξη Εκκλησία στην Αμερική, 1980",
    "Orthodox Church in America, 1994": "Ορθόδοξη Εκκλησία στην Αμερική, 1994",
    "Orthodox Church in America; glorified at Kwethluk, June 19, 2025": "Ορθόδοξη Εκκλησία στην Αμερική· αγιοκατάταξη στο Κουέθλουκ, 19 Ιουνίου 2025",
    "Orthodox Church, 1659": "Ορθόδοξη Εκκλησία, 1659",
    "Patriarchate of Antioch, 1993": "Πατριαρχείο Αντιοχείας, 1993",
    "Pre-congregational veneration": "Τιμή από αρχαιοτάτων χρόνων",
    "Pre-congregational veneration; Equals-to-the-Apostles": "Τιμή από αρχαιοτάτων χρόνων· ισαπόστολοι",
    "Pre-congregational veneration; among the first saints of Rus": "Τιμή από αρχαιοτάτων χρόνων· μεταξύ των πρώτων αγίων της Ρωσίας",
    "Pre-congregational veneration; glorified by miracles": "Τιμή από αρχαιοτάτων χρόνων· επιβεβαιωμένη με θαύματα",
    "Pre-congregational veneration; venerated as patron of Moldavia": "Τιμή από αρχαιοτάτων χρόνων· τιμάται ως προστάτης της Μολδαβίας",
    "Pre-congregational veneration; vindicated by the Sixth Ecumenical Council": "Τιμή από αρχαιοτάτων χρόνων· δικαιώθηκε από την Έκτη Οικουμενική Σύνοδο",
    "Prophet of the Old Covenant": "Προφήτης της Παλαιάς Διαθήκης",
    "Recognized among the New Martyrs by the Great Church of Christ": "Συγκαταλέχθηκε μεταξύ των Νεομαρτύρων από τη Μεγάλη του Χριστού Εκκλησία",
    "Recognized among the New Martyrs venerated in the Church of Greece": "Συγκαταλέχθηκε μεταξύ των Νεομαρτύρων που τιμώνται στην Εκκλησία της Ελλάδος",
    "Romanian Orthodox Church, 1992": "Ρουμανική Ορθόδοξη Εκκλησία, 1992",
    "Romanian Orthodox Church, 2008": "Ρουμανική Ορθόδοξη Εκκλησία, 2008",
    "Romanian Orthodox Church, glorified in 1955": "Ρουμανική Ορθόδοξη Εκκλησία, αγιοκατάταξη το 1955",
    "Russian Church Abroad, 1994": "Ρωσική Εκκλησία της Διασποράς, 1994",
    "Russian Orthodox Church": "Ρωσική Ορθόδοξη Εκκλησία",
    "Russian Orthodox Church, 1108": "Ρωσική Ορθόδοξη Εκκλησία, 1108",
    "Russian Orthodox Church, 1448": "Ρωσική Ορθόδοξη Εκκλησία, 1448",
    "Russian Orthodox Church, 1467": "Ρωσική Ορθόδοξη Εκκλησία, 1467",
    "Russian Orthodox Church, 1544 (local veneration)": "Ρωσική Ορθόδοξη Εκκλησία, 1544 (τοπική τιμή)",
    "Russian Orthodox Church, 1547": "Ρωσική Ορθόδοξη Εκκλησία, 1547",
    "Russian Orthodox Church, 1549": "Ρωσική Ορθόδοξη Εκκλησία, 1549",
    "Russian Orthodox Church, 1579": "Ρωσική Ορθόδοξη Εκκλησία, 1579",
    "Russian Orthodox Church, 1591": "Ρωσική Ορθόδοξη Εκκλησία, 1591",
    "Russian Orthodox Church, 1595": "Ρωσική Ορθόδοξη Εκκλησία, 1595",
    "Russian Orthodox Church, 1597": "Ρωσική Ορθόδοξη Εκκλησία, 1597",
    "Russian Orthodox Church, 1645": "Ρωσική Ορθόδοξη Εκκλησία, 1645",
    "Russian Orthodox Church, 1646": "Ρωσική Ορθόδοξη Εκκλησία, 1646",
    "Russian Orthodox Church, 1649": "Ρωσική Ορθόδοξη Εκκλησία, 1649",
    "Russian Orthodox Church, 1650; veneration restored 1909": "Ρωσική Ορθόδοξη Εκκλησία, 1650· η τιμή αποκαταστάθηκε το 1909",
    "Russian Orthodox Church, 1652": "Ρωσική Ορθόδοξη Εκκλησία, 1652",
    "Russian Orthodox Church, 1659": "Ρωσική Ορθόδοξη Εκκλησία, 1659",
    "Russian Orthodox Church, 1664": "Ρωσική Ορθόδοξη Εκκλησία, 1664",
    "Russian Orthodox Church, 1687": "Ρωσική Ορθόδοξη Εκκλησία, 1687",
    "Russian Orthodox Church, 1698": "Ρωσική Ορθόδοξη Εκκλησία, 1698",
    "Russian Orthodox Church, 1757": "Ρωσική Ορθόδοξη Εκκλησία, 1757",
    "Russian Orthodox Church, 1798": "Ρωσική Ορθόδοξη Εκκλησία, 1798",
    "Russian Orthodox Church, 1800": "Ρωσική Ορθόδοξη Εκκλησία, 1800",
    "Russian Orthodox Church, 1804": "Ρωσική Ορθόδοξη Εκκλησία, 1804",
    "Russian Orthodox Church, 1832": "Ρωσική Ορθόδοξη Εκκλησία, 1832",
    "Russian Orthodox Church, 1861": "Ρωσική Ορθόδοξη Εκκλησία, 1861",
    "Russian Orthodox Church, 1896": "Ρωσική Ορθόδοξη Εκκλησία, 1896",
    "Russian Orthodox Church, 1903": "Ρωσική Ορθόδοξη Εκκλησία, 1903",
    "Russian Orthodox Church, 1911": "Ρωσική Ορθόδοξη Εκκλησία, 1911",
    "Russian Orthodox Church, 1913": "Ρωσική Ορθόδοξη Εκκλησία, 1913",
    "Russian Orthodox Church, 1914": "Ρωσική Ορθόδοξη Εκκλησία, 1914",
    "Russian Orthodox Church, 1978": "Ρωσική Ορθόδοξη Εκκλησία, 1978",
    "Russian Orthodox Church, 1988": "Ρωσική Ορθόδοξη Εκκλησία, 1988",
    "Russian Orthodox Church, 1994": "Ρωσική Ορθόδοξη Εκκλησία, 1994",
    "Russian Orthodox Church, 2000": "Ρωσική Ορθόδοξη Εκκλησία, 2000",
    "Russian Orthodox Church, December 4, 1994": "Ρωσική Ορθόδοξη Εκκλησία, 4 Δεκεμβρίου 1994",
    "Russian Orthodox Church, Jubilee Council of 2000; earlier by the Russian Church Abroad, 1981": "Ρωσική Ορθόδοξη Εκκλησία, Ιωβηλαία Σύνοδος του 2000· νωρίτερα από τη Ρωσική Εκκλησία της Διασποράς, 1981",
    "Russian Orthodox Church, October 6, 1977": "Ρωσική Ορθόδοξη Εκκλησία, 6 Οκτωβρίου 1977",
    "Russian Orthodox Church, October 9, 1989": "Ρωσική Ορθόδοξη Εκκλησία, 9 Οκτωβρίου 1989",
    "Russian Orthodox Church, September 4, 1911": "Ρωσική Ορθόδοξη Εκκλησία, 4 Σεπτεμβρίου 1911",
    "Russian Orthodox Church, at the Council of 1547": "Ρωσική Ορθόδοξη Εκκλησία, στη Σύνοδο του 1547",
    "Russian Orthodox Church, at the Council of 1549": "Ρωσική Ορθόδοξη Εκκλησία, στη Σύνοδο του 1549",
    "Russian Orthodox Church, at the Moscow Council of 1549": "Ρωσική Ορθόδοξη Εκκλησία, στη Σύνοδο της Μόσχας του 1549",
    "Russian Orthodox Church, c. 1452": "Ρωσική Ορθόδοξη Εκκλησία, περ. 1452",
    "Russian Orthodox Church, commemoration established at the Council of 1547": "Ρωσική Ορθόδοξη Εκκλησία, η μνήμη θεσπίστηκε στη Σύνοδο του 1547",
    "Russian Orthodox Church, commemoration established at the Council of 1549": "Ρωσική Ορθόδοξη Εκκλησία, η μνήμη θεσπίστηκε στη Σύνοδο του 1549",
    "Russian Orthodox Church, glorified at the end of the sixteenth century": "Ρωσική Ορθόδοξη Εκκλησία, αγιοκατάταξη στα τέλη του δέκατου έκτου αιώνα",
    "Russian Orthodox Church, glorified in 1595": "Ρωσική Ορθόδοξη Εκκλησία, αγιοκατάταξη το 1595",
    "Russian Orthodox Church, glorified in 1820": "Ρωσική Ορθόδοξη Εκκλησία, αγιοκατάταξη το 1820",
    "Russian Orthodox Church, glorified in 1918": "Ρωσική Ορθόδοξη Εκκλησία, αγιοκατάταξη το 1918",
    "Russian Orthodox Church, glorified in 1977": "Ρωσική Ορθόδοξη Εκκλησία, αγιοκατάταξη το 1977",
    "Russian Orthodox Church, glorified in 2000": "Ρωσική Ορθόδοξη Εκκλησία, αγιοκατάταξη το 2000",
    "Russian Orthodox Church, local veneration": "Ρωσική Ορθόδοξη Εκκλησία, τοπική τιμή",
    "Russian Orthodox Church; commemoration restored in 1888": "Ρωσική Ορθόδοξη Εκκλησία· η μνήμη αποκαταστάθηκε το 1888",
    "Russian Orthodox Church; local veneration from 1715": "Ρωσική Ορθόδοξη Εκκλησία· τοπική τιμή από το 1715",
    "Serbian Orthodox Church": "Σερβική Ορθόδοξη Εκκλησία",
    "Serbian Orthodox Church, 1961": "Σερβική Ορθόδοξη Εκκλησία, 1961",
    "Serbian Orthodox Church, May 15, 2005": "Σερβική Ορθόδοξη Εκκλησία, 15 Μαΐου 2005",
    "Serbian Orthodox Church, May 29, 2015": "Σερβική Ορθόδοξη Εκκλησία, 29 Μαΐου 2015",
    "Serbian Orthodox Church, glorified in 2003": "Σερβική Ορθόδοξη Εκκλησία, αγιοκατάταξη το 2003",
    "Serbian Orthodox Church; venerated among the first saints of the Serbian lands": "Σερβική Ορθόδοξη Εκκλησία· τιμάται μεταξύ των πρώτων αγίων των σερβικών χωρών",
    "Serbian and Bulgarian Orthodox Churches": "Σερβική και Βουλγαρική Ορθόδοξη Εκκλησία",
    "Ukrainian Orthodox Church, 2001": "Ουκρανική Ορθόδοξη Εκκλησία, 2001",
    "Veneration established by the Russian Orthodox Church": "Η τιμή θεσπίστηκε από τη Ρωσική Ορθόδοξη Εκκλησία",
    "Veneration established in the Russian Orthodox Church": "Η τιμή θεσπίστηκε στη Ρωσική Ορθόδοξη Εκκλησία",
    "Veneration established on the Holy Mountain": "Η τιμή θεσπίστηκε στο Άγιον Όρος",
})


# The name a saint bore in the world.
TEXT.update({
    "Abraham": "Αβραάμ",
    "Alexander": "Αλέξανδρος",
    "Alexi": "Αλέξι",
    "Alexios": "Αλέξιος",
    "Alexis": "Αλέξιος",
    "Amos": "Αμώς",
    "Anastasios Kephalas": "Αναστάσιος Κεφαλάς",
    "Andrei": "Αντρέι",
    "Andrew": "Ανδρέας",
    "Anna": "Άννα",
    "Antipas": "Αντίπας",
    "Arsenios": "Αρσένιος",
    "Bartholomew": "Βαρθολομαίος",
    "Basil": "Βασίλειος",
    "Constantin Antonescu": "Κωνσταντίν Αντωνέσκου",
    "Constantine": "Κωνσταντίνος",
    "Constantine and Michael": "Κωνσταντίνος και Μιχαήλ",
    "Daniel": "Δανιήλ",
    "David": "Δαβίδ",
    "Diamantes": "Διαμαντής",
    "Diomedes": "Διομήδης",
    "Draganigos": "Δραγανίγος",
    "Eleutherios": "Ελευθέριος",
    "Eleutherius": "Ελευθέριος",
    "Elias": "Ηλίας",
    "Eudokia": "Ευδοκία",
    "Eusebia": "Ευσεβία",
    "Eustathius": "Ευστάθιος",
    "Evangelos": "Ευάγγελος",
    "Feodor": "Φεντόρ",
    "Feodor Kolychev": "Φεντόρ Κολίτσεφ",
    "Gabriel": "Γαβριήλ",
    "George": "Γεώργιος",
    "Georgios Angelopoulos": "Γεώργιος Αγγελόπουλος",
    "Gregory": "Γρηγόριος",
    "Helen": "Ελένη",
    "Irene": "Ειρήνη",
    "Ivan": "Ιβάν",
    "Ivan (John) Zhelezo": "Ιβάν (Ιωάννης) Ζελέζο",
    "Ivan Popov-Veniaminov": "Ιβάν Ποπόφ-Βενιαμίνοφ",
    "Joachim": "Ιωακείμ",
    "John": "Ιωάννης",
    "Joseph": "Ιωσήφ",
    "Jovan (John)": "Γιόβαν (Ιωάννης)",
    "Konon": "Κόνων",
    "Konstas": "Κώνστας",
    "Kosmas": "Κοσμάς",
    "Kumets, Nezhilo, and Kruglets": "Κούμετς, Νεζίλο και Κρούγκλετς",
    "Manuel": "Μανουήλ",
    "Mary": "Μαρία",
    "Matrona Dimitrievna Nikonova": "Ματρώνα Ντμίτριεβνα Νικόνοβα",
    "Matthew": "Ματθαίος",
    "Matthew Kozhin": "Ματθαίος Κόζιν",
    "Matthias": "Ματθίας",
    "Menas": "Μηνάς",
    "Michael": "Μιχαήλ",
    "Michael Trivolis": "Μιχαήλ Τριβώλης",
    "Mitrofan": "Μιτροφάν",
    "Neanius": "Νεάνιος",
    "Nicetas": "Νικήτας",
    "Nicholas": "Νικόλαος",
    "Nicholas Maikov": "Νικόλαος Μάικοφ",
    "Nikola Velimirovich": "Νικόλα Βελιμίροβιτς",
    "Nikon": "Νίκων",
    "Olga": "Όλγα",
    "Otar": "Οτάρ",
    "Parthenius": "Παρθένιος",
    "Penelope": "Πηνελόπη",
    "Peter": "Πέτρος",
    "Predislav": "Πρεντισλάβ",
    "Predslava": "Πρεντσλάβα",
    "Procopius": "Προκόπιος",
    "Prokhor": "Πρόχορος",
    "Rastko": "Ράστκο",
    "Reprebus": "Ρέπρεβος",
    "Roman and David": "Ρωμανός και Δαβίδ",
    "Romanus and David": "Ρωμανός και Δαβίδ",
    "Saul": "Σαύλος",
    "Semyon": "Σεμιόν",
    "Sergei": "Σεργκέι",
    "Sergius": "Σέργιος",
    "Simeon": "Συμεών",
    "Simon": "Σίμων",
    "Solomonia": "Σολομονία",
    "Stefan Kristalevsky": "Στέφαν Κρισταλέφσκι",
    "Stephen Nemanja": "Στέφανος Νεμάνια",
    "Stojan Jovanovic": "Στόγιαν Γιοβάνοβιτς",
    "Tarasius": "Ταράσιος",
    "Thekla": "Θέκλα",
    "Theodore": "Θεόδωρος",
    "Theodulia": "Θεοδουλία",
    "Theophilus": "Θεόφιλος",
    "Timothy": "Τιμόθεος",
    "Valentin": "Βαλεντίνος",
    "Vasily": "Βασίλι",
    "Vasily Ivanovich Bellavin": "Βασίλι Ιβάνοβιτς Μπελλάβιν",
    "Vasily Muravyov": "Βασίλι Μουράβιοφ",
    "Victorinus": "Βικτωρίνος",
    "Vojislav": "Βόισλαβ",
    "Yaroslav": "Γιαροσλάβ",
    "Yermolai": "Ερμόλαος",
})


# The places, which are not a list but a grammar: a card names a town, a
# province and a country in one line, and the same town appears on twenty
# other cards inside a different line. The pieces are rendered once here and
# the wholes are assembled from them, so a town cannot be spelled one way on
# one card and another way on the next.
PARTS = {}

def expand(phrases):
    """The compounds, assembled from the parts above."""
    out = {}
    for p in phrases:
        bits = p.split(", ")
        if all(b in PARTS for b in bits):
            out[p] = ", ".join(PARTS[b] for b in bits)
    return out


# The places, first part.
PARTS.update({
    "Abel-meholah": "Αβελμαουλά",
    "Abkhazeti": "Αμπχαζέτι",
    "Achaia": "Αχαΐα",
    "Adamovka": "Αντάμοβκα",
    "Adrianople": "Αδριανούπολη",
    "Adrianopolis": "Αδριανούπολις",
    "Aegae": "Αιγαί",
    "Aegean": "Αιγαίο",
    "Aegina": "Αίγινα",
    "Aetolia": "Αιτωλία",
    "Africa": "Αφρική",
    "Agrigentum": "Ακράγας",
    "Akhaltsikhe": "Αχαλτσίχε",
    "Aksum": "Αξούμ",
    "Alaska": "Αλάσκα",
    "Albania": "Αλβανία",
    "Albanopolis": "Αλβανόπολις",
    "Aleppo": "Χαλέπι",
    "Alexandria": "Αλεξάνδρεια",
    "All America": "Όλη η Αμερική",
    "Amasea": "Αμάσεια",
    "Amasia": "Αμάσεια",
    "Amastridea": "Αμάστριδα",
    "Amastris": "Άμαστρις",
    "Amathus": "Αμαθούς",
    "America": "Αμερική",
    "Amida": "Άμιδα",
    "Amisos": "Αμισός",
    "Amisus": "Αμισός",
    "Amnia": "Άμνια",
    "Amorion": "Αμόριον",
    "Amphipolis": "Αμφίπολη",
    "Anaplus": "Άναπλους",
    "Anastasiopolis": "Αναστασιούπολις",
    "Anathoth": "Αναθώθ",
    "Anatolia": "Ανατολία",
    "Anazarbus": "Ανάζαρβος",
    "Ancyra": "Άγκυρα",
    "Andronikov Monastery": "Μονή Αντρόνικωφ",
    "Anga": "Άνγκα",
    "Annesi": "Άννησα",
    "Annisa": "Άννησα",
    "Antinoe": "Αντινόη",
    "Antioch": "Αντιόχεια",
    "Antioch in Pisidia": "Αντιόχεια της Πισιδίας",
    "Antioch of Pisidia": "Αντιόχεια της Πισιδίας",
    "Anzersk": "Ανζέρσκ",
    "Anzersk Island": "Νήσος Ανζέρσκ",
    "Apamea": "Απάμεια",
    "Aphrodisias": "Αφροδισιάς",
    "Apollonia": "Απολλωνία",
    "Apulia": "Απουλία",
    "Aquileia": "Ακυληία",
    "Arabia": "Αραβία",
    "Arabian Desert": "Αραβική έρημος",
    "Arauraka": "Αραυράκα",
    "Arbela": "Άρβηλα",
    "Archangel Gabriel": "Αρχάγγελος Γαβριήλ",
    "Arethusa": "Αρέθουσα",
    "Argos": "Άργος",
    "Arianzus": "Αριανζός",
    "Arkhangelsk": "Αρχάγγελσκ",
    "Arkhangelsk lands": "Χώρες του Αρχάγγελσκ",
    "Armagh": "Άρμαγκ",
    "Armenia": "Αρμενία",
    "Armenia Minor": "Μικρά Αρμενία",
    "Arsinoe": "Αρσινόη",
    "Arta": "Άρτα",
    "Artanuji": "Αρτανούτζι",
    "Ascalon": "Ασκάλων",
    "Asia Minor": "Μικρά Ασία",
    "Asikha": "Ασίχα",
    "Athens": "Αθήνα",
    "Atka Island": "Νήσος Άτκα",
    "Atskuri": "Ατσκούρι",
    "Atsquri": "Ατσκούρι",
    "Attica": "Αττική",
    "Auleneia": "Αυλήνεια",
    "Auxerre": "Οσέρ",
    "Avnezh": "Αβνέζ",
    "Babylon": "Βαβυλώνα",
    "Balkans": "Βαλκάνια",
    "Barcelona": "Βαρκελώνη",
    "Bari": "Μπάρι",
    "Basarbov": "Μπασάρμποβο",
    "Beauvais": "Μποβέ",
    "Beirut": "Βηρυτός",
    "Belarus": "Λευκορωσία",
    "Belev": "Μπελέφ",
    "Belgorod": "Μπέλγκοροντ",
    "Belgorod (Akkerman)": "Μπέλγκοροντ (Ακέρμαν)",
    "Belgrade": "Βελιγράδι",
    "Belozersk": "Μπελοζέρσκ",
    "Belozersk lands": "Χώρες του Μπελοζέρσκ",
    "Belozersk lands and Mozhaisk": "Χώρες του Μπελοζέρσκ και Μοζάισκ",
    "Benevento": "Μπενεβέντο",
    "Beocin Monastery": "Μονή Μπέοτσιν",
    "Berezan": "Μπερεζάν",
    "Berezniko": "Μπερεζνίκο",
    "Beroea": "Βέροια",
    "Besanduc": "Βεσαντούκ",
    "Bethany": "Βηθανία",
    "Bethel": "Βαιθήλ",
    "Bethlapeta": "Βηθλαπέτα",
    "Bethlehem": "Βηθλεέμ",
    "Bethsaida": "Βηθσαϊδά",
    "Bethsaloe": "Βηθσαλόη",
    "Bezhetsk lands": "Χώρες του Μπεζέτσκ",
    "Bialystok": "Μπιάλιστοκ",
    "Bisericani Monastery": "Μονή Μπισερικάνι",
    "Bithynia": "Βιθυνία",
    "Blachernae": "Βλαχέρνες",
    "Black Lake": "Μαύρη Λίμνη",
    "Black Sea coast": "Ακτή του Ευξείνου Πόντου",
    "Bodbe": "Μπόντμπε",
    "Boeotia": "Βοιωτία",
    "Bogolyubovo": "Μπογκολιούμποβο",
    "Bohemia": "Βοημία",
    "Bolgar": "Μπολγκάρ",
    "Borovichi": "Μποροβιτσί",
})


# The places, second part.
PARTS.update({
    "Borovsk": "Μπορόφσκ",
    "Bosnia": "Βοσνία",
    "Boston": "Βοστώνη",
    "Bostra": "Βόστρα",
    "Braunton": "Μπράουντον",
    "Brest": "Μπρεστ",
    "Briansk": "Μπριάνσκ",
    "Britain": "Βρετανία",
    "British Isles": "Βρετανικές Νήσοι",
    "Brooklyn": "Μπρούκλιν",
    "Bryansk": "Μπριάνσκ",
    "Bucharest": "Βουκουρέστι",
    "Budimlje": "Μπούντιμλιε",
    "Bulgaria": "Βουλγαρία",
    "Butovo": "Μπούτοβο",
    "Buzau Mountains": "Όρη Μπουζέου",
    "Byblos": "Βύβλος",
    "Byzantine Empire": "Βυζαντινή Αυτοκρατορία",
    "Byzantium": "Βυζάντιο",
    "Byzantium (Constantinople)": "Βυζάντιο (Κωνσταντινούπολη)",
    "Caesarea": "Καισάρεια",
    "Caesarea Maritima": "Καισάρεια της Παλαιστίνης",
    "Caesarea in Cappadocia": "Καισάρεια της Καππαδοκίας",
    "California": "Καλιφόρνια",
    "Campania": "Καμπανία",
    "Cana": "Κανά",
    "Cana of Galilee": "Κανά της Γαλιλαίας",
    "Canaan": "Χαναάν",
    "Canopus": "Κάνωβος",
    "Capernaum": "Καπερναούμ",
    "Cappadocia": "Καππαδοκία",
    "Caria": "Καρία",
    "Carpathian Rus'": "Καρπαθορωσία",
    "Carpatho-Russia": "Καρπαθορωσία",
    "Carthage": "Καρχηδόνα",
    "Catania": "Κατάνη",
    "Cephalonia": "Κεφαλονιά",
    "Cernica": "Τσερνίκα",
    "Cernica Monastery": "Μονή Τσερνίκα",
    "Chalcedon": "Χαλκηδόνα",
    "Chalcis": "Χαλκίδα",
    "Chalcis desert": "Έρημος της Χαλκίδος",
    "Chelm": "Χελμ",
    "Chelma Hill": "Λόφος Τσέλμα",
    "Cherepovets": "Τσερεποβέτς",
    "Chernigov": "Τσερνίγκοφ",
    "Chernigov lands": "Χώρες του Τσερνίγκοφ",
    "Chernihiv": "Τσερνίχιφ",
    "Chernihiv lands": "Χώρες του Τσερνίχιφ",
    "Cherson": "Χερσών",
    "Chersonesus": "Χερσόνησος",
    "Chicago": "Σικάγο",
    "China": "Κίνα",
    "Chios": "Χίος",
    "Chonae": "Χώναι",
    "Choziba": "Χοζεβά",
    "Chukhloma": "Τσουχλομά",
    "Cilicia": "Κιλικία",
    "Claudiopolis": "Κλαυδιούπολις",
    "Colophon": "Κολοφών",
    "Colossae": "Κολοσσαί",
    "Coma": "Κόμα",
    "Comana": "Κόμανα",
    "Constantia": "Κωνσταντία",
    "Constantinople": "Κωνσταντινούπολη",
    "Cordoba": "Κόρδοβα",
    "Corfu": "Κέρκυρα",
    "Corinth": "Κόρινθος",
    "Corsica": "Κορσική",
    "Cotyaeum": "Κοτυάειον",
    "Crete": "Κρήτη",
    "Crimea": "Κριμαία",
    "Cucomo": "Κούκομο",
    "Cucusus": "Κουκουσός",
    "Cyprus": "Κύπρος",
    "Cyrene": "Κυρήνη",
    "Cyrenia": "Κερύνεια",
    "Cyrrhus": "Κύρρος",
    "Cyzicus": "Κύζικος",
    "Czech Lands": "Τσεχικές χώρες",
    "Dabuda": "Δαβούδα",
    "Dalmatia": "Δαλματία",
    "Dalmatian Monastery": "Μονή Δαλμάτου",
    "Damascus": "Δαμασκός",
    "Danube lands": "Παραδουνάβιες χώρες",
    "David Gareji": "Νταβίντ Γκαρέτζι",
    "Davit-Gareji": "Νταβίτ-Γκαρέτζι",
    "Decapolis": "Δεκάπολις",
    "Decapolis of Isauria": "Δεκάπολις της Ισαυρίας",
    "Demetsana": "Δημητσάνα",
    "Demitsana": "Δημητσάνα",
    "Desert beyond the Jordan": "Έρημος πέραν του Ιορδάνου",
    "Devich": "Ντέβιτς",
    "Devon": "Ντέβον",
    "Dimitsana": "Δημητσάνα",
    "Dioclea": "Διόκλεια",
    "Dioclea (Duklja)": "Διόκλεια (Ντούκλια)",
    "Disevi": "Ντισέβι",
    "Diveyevo": "Ντιβέγιεβο",
    "Dobrogea": "Δοβρουτσά",
    "Dorostolum": "Δορύστολον",
    "Dorostolum (Silistra)": "Δορύστολον (Σιλίστρα)",
    "Drenica": "Ντρένιτσα",
    "Durostorum": "Δορύστολον",
    "Dymsk": "Ντιμσκ",
    "Dymskoe Lake": "Λίμνη Ντίμσκογιε",
    "East Anglia": "Ανατολική Αγγλία",
    "Edessa": "Έδεσσα",
    "Edra": "Έδρα",
    "Egypt": "Αίγυπτος",
    "Egyptian Desert": "Αιγυπτιακή έρημος",
    "Elbasan": "Ελμπασάν",
    "Eleutheropolis": "Ελευθερόπολις",
    "Elkosh": "Ελκές",
    "Emesa": "Έμεσα",
    "England": "Αγγλία",
    "Ephesus": "Έφεσος",
    "Epirus": "Ήπειρος",
    "Epivato": "Επιβάται",
    "Essex": "Έσσεξ",
})


# The places, third part.
PARTS.update({
    "Ethiopia": "Αιθιοπία",
    "Euboea": "Εύβοια",
    "Euchaita": "Ευχάιτα",
    "Euroea": "Ευρόη",
    "European Russia": "Ευρωπαϊκή Ρωσία",
    "Evia": "Εύβοια",
    "Ferapontov": "Φεραπόντωφ",
    "Ferapontov Monastery": "Μονή Φεραπόντωφ",
    "Ferapontovo": "Φεραπόντοβο",
    "Feremane": "Φερεμάνη",
    "Ferentino": "Φερεντίνο",
    "Flavia Neapolis": "Φλαβία Νεάπολις",
    "Florishchi": "Φλορίστσι",
    "Formia": "Φορμία",
    "France": "Γαλλία",
    "Frasinei": "Φρασινέι",
    "Galata": "Γαλατάς",
    "Galatia": "Γαλατία",
    "Galich": "Γκάλιτς",
    "Galicia": "Γαλικία",
    "Galilee": "Γαλιλαία",
    "Gangra": "Γάγγρα",
    "Gareji": "Γκαρέτζι",
    "Gary": "Γκάρι",
    "Gath-hepher": "Γεθχοφέρ",
    "Gaul": "Γαλατία",
    "Gaza": "Γάζα",
    "Gdov": "Γκντοφ",
    "Gdov lands": "Χώρες του Γκντοφ",
    "George Hill": "Λόφος του Αγίου Γεωργίου",
    "Georgia": "Γεωργία",
    "Germany": "Γερμανία",
    "Gibeah of Phinehas": "Γαβαά του Φινεές",
    "Gilead": "Γαλαάδ",
    "Glendalough": "Γκλενταλόχ",
    "Glushitsa": "Γκλουσίτσα",
    "Gori district": "Περιφέρεια Γκόρι",
    "Gortyna": "Γόρτυνα",
    "Gothia": "Γοτθία",
    "Gothic lands": "Γοτθικές χώρες",
    "Great Lavra": "Μεγίστη Λαύρα",
    "Great Lavra of Saint Sabbas": "Μεγάλη Λαύρα του Αγίου Σάββα",
    "Great Moravia": "Μεγάλη Μοραβία",
    "Greece": "Ελλάδα",
    "Guria": "Γκουρία",
    "Hartland": "Χάρτλαντ",
    "Hauran": "Χαυράν",
    "Hebron": "Χεβρών",
    "Heliopolis": "Ηλιούπολις",
    "Hellas": "Ελλάς",
    "Hellespont": "Ελλήσποντος",
    "Heraclea": "Ηράκλεια",
    "Hereti": "Χερέτι",
    "Hermopolis": "Ερμούπολις",
    "Herzegovina": "Ερζεγοβίνη",
    "Hierapolis": "Ιεράπολις",
    "Hilandar": "Χιλανδάρι",
    "Holy Land": "Άγιοι Τόποι",
    "Holy Trinity-Saint Sergius Lavra": "Λαύρα της Αγίας Τριάδος και του Αγίου Σεργίου",
    "Hosios Loukas": "Όσιος Λουκάς",
    "Hungary": "Ουγγαρία",
    "Hypaepa": "Ύπαιπα",
    "Iași": "Ιάσιο",
    "Iconium": "Ικόνιο",
    "Iken": "Άικεν",
    "Illinois": "Ιλινόις",
    "Illyria": "Ιλλυρία",
    "Illyricum": "Ιλλυρικό",
    "India": "Ινδία",
    "Indiana": "Ιντιάνα",
    "Ioannina": "Ιωάννινα",
    "Irap": "Ιράπ",
    "Ireland": "Ιρλανδία",
    "Irenopolis": "Ειρηνούπολις",
    "Irkutsk": "Ιρκούτσκ",
    "Irkutsk province": "Επαρχία Ιρκούτσκ",
    "Isauria": "Ισαυρία",
    "Israel": "Ισραήλ",
    "Italy": "Ιταλία",
    "Iza": "Ίζα",
    "Jackson": "Τζάκσον",
    "Jerusalem": "Ιερουσαλήμ",
    "Joppa": "Ιόππη",
    "Jordan River": "Ποταμός Ιορδάνης",
    "Judah": "Ιουδαία",
    "Judea": "Ιουδαία",
    "Judean Desert": "Έρημος της Ιουδαίας",
    "Judean Wilderness": "Έρημος της Ιουδαίας",
    "Kallippi": "Καλλίππη",
    "Kaluga": "Καλούγκα",
    "Kaluga lands": "Χώρες της Καλούγκα",
    "Kalyazin": "Καλιάζιν",
    "Kampsada": "Καμψάδα",
    "Kaniv": "Κάνιφ",
    "Karelia": "Καρελία",
    "Kargopol": "Καργκοπόλ",
    "Kargopol lands": "Χώρες του Καργκοπόλ",
    "Kartli": "Καρτλί",
    "Kartli (Iberia)": "Καρτλί (Ιβηρία)",
    "Kashin": "Κάσιν",
    "Kasperovo": "Κασπέροβο",
    "Kastoria": "Καστοριά",
    "Kastorion": "Καστόριον",
    "Kavsokalyvia": "Καυσοκαλύβια",
    "Kazan": "Καζάν",
    "Kekhta": "Κέχτα",
    "Kellia": "Κελλία",
    "Keno Lake": "Λίμνη Κένο",
    "Kerch": "Κερτς",
    "Kerkyra": "Κέρκυρα",
    "Kerkyra (Corfu)": "Κέρκυρα",
    "Khakhuli": "Χαχούλι",
    "Khakhuli Monastery": "Μονή Χαχούλι",
    "Kharkiv": "Χάρκοβο",
    "Kherson": "Χερσώνα",
    "Kherson lands": "Χώρες της Χερσώνας",
    "Khlynov": "Χλίνοφ",
    "Kholm": "Χολμ",
    "Khust": "Χουστ",
    "Khutyn": "Χούτιν",
})
