# -*- coding: utf-8 -*-
"""Japanese for the vocabulary that stands beside the lives.

TEXT = {the phrase the index shows: the rendering}. The keys are the phrases
exactly as the index writes them, so a rendering cannot quietly attach itself
to the wrong saint.

A language may later declare PARTS and an expand() to assemble the compound
place-names from pieces rendered once, as the older languages do. It is an
optimisation and not a requirement: everything written in TEXT stands over
whatever expand() builds.
"""
TEXT = {
}

TEXT.update({
    "(Abibus) of Egypt": "（アビブ）エジプトの",
    "(Apphianus) and Edesius (Aedesius) of Lycia": "（アプフィアン）とリキアのエデシイ",
    "(Eustace) the Confessor, Bishop of Bithynia": "（エウスタフィイ）宣信者、ビフィニヤの主教",
    "(Jacob) the Presbyter, and Azadanes and Abdiesus the Deacons, of Persia": "（イアコフ）長老、及びペルシャの輔祭アザダンとアヴディイス",
    "(Vadim) of Persia": "（ワディム）ペルシャの",
    "(Voino-Yasenetsky), Archbishop of Simferopol and Crimea": "（ヴォイノ・ヤセネツキイ）、シンフェロポリ及びクリミヤの大主教",
    "(also called Susanna), New Martyr of Lesbos": "（スサンナとも呼ばれる）、レスボスの新致命女",
    "(tonsured David and Euphrosyne), Wonderworkers of Murom": "（剃髪してダヴィドとエフロシニヤ）、ムロムの成神者",
    "A Cappadocian centurion bowing beneath the sword with his eyes lifted in thanksgiving, the walnut tree of the tradition behind him, the churches of Byzantium rising over his relics.": "カッパドキヤの百人長が剣の下に身をかがめ、目を上げて感謝し、伝承の胡桃の木がその後ろにあり、ビザンティヤの聖堂がその聖遺物の上に立つ。",
    "A Celtic hermit of the Devon coast bearing his own severed head to the spring, the robbers behind him, crowned as a martyr among the saints of Britain.": "デヴォンの海岸のケルトの隠修士が自らの斬られた首を泉へ運び、強盗たちがその後ろにあり、ブリタニヤの聖人らの中に致命者として冠を受ける。",
    "A Christian general casting down the temples of Galatia, his twelve tribunes and his thousands of soldiers with their wives and children crowned around him, the converted sorcerer Callinicus among them.": "ハリストス教徒の将軍がガラティヤの神殿を倒し、十二人の千人長と幾千の兵士がその妻子とともにその周りで冠を受け、改宗した魔術師カリニクがその中にいる。",
    "A Christian of Alexandria standing before the tribunal to denounce its cruelty, the confession volunteered and the sword received.": "アレクサンドリヤのハリストス教徒が法廷の前に立ってその残酷を責め、自ら進んで信仰を告白し剣を受ける。",
    "A Creole-Aleut priest in vestments holding a Gospel and a cross, against an Alaskan landscape.": "祭服を着たクレオール・アレウトの司祭が福音書と十字架を持ち、アラスカの風景を背にする。",
    "A Georgian bishop with a book and a restored church, schoolchildren and monasteries behind him.": "グルジヤの主教が書物と再建された聖堂とともにあり、学童と修道院がその後ろにある。",
    "A Georgian commander marking his forehead with the cross in his own blood, his soldiers crowned around him.": "グルジヤの将軍が自らの血で額に十字を記し、その兵士たちがその周りで冠を受ける。",
    "A Georgian monk in prayer before the cave monastery of Gareji in the desert hills.": "グルジヤの修道士が荒野の丘のガレジの洞窟修道院の前で祈る。",
    "A Georgian monk-abbot holding a scroll or a book.": "グルジヤの修道院長たる修道士が巻物あるいは書物を持つ。",
    "A Georgian prince and commander refusing to trample the icon of Christ before the conqueror, crowned as a great-martyr, the defender of the Georgian faith.": "グルジヤの公にして将軍が征服者の前でハリストスの聖像を踏むことを拒み、大致命者として冠を受け、グルジヤの信仰の守護者となる。",
    "A Gothic congregation at worship within the burning church, twenty-six crowns rising with the smoke, the queen gathering the holy remains from the ashes.": "ゴトの会衆が燃える聖堂の中で祈り、二十六の冠が煙とともに立ち上り、王妃が灰から聖なる遺骨を集める。",
    "A Gothic general of Rome casting down his military belt before Aurelian, seventy soldiers confessing behind him, the river receiving the wonderworking commander.": "ロマのゴトの将軍がアウレリアヌスの前に軍帯を投げ捨て、七十人の兵士がその後ろで信仰を告白し、河が成神者たる将軍を受け入れる。",
    "A Great Prince of Kyiv with the churches of Smolensk he raised, the monastic habit he longed for held by an angel, the elder Polycarp pointing him back to his throne.": "キエフの大公が自ら建てたスモレンスクの聖堂とともにあり、望んだ修道服を天使が持ち、長老ポリカルプがその位へ帰るよう指し示す。",
    "A Greek bishop preaching Christ to the pagan Rostov land, the first shepherd of a hostile flock, the see of Rostov founded amid the idols of the north.": "ギリシヤの主教が異教のロストフの地にハリストスを説き、敵意ある群れの最初の牧者となり、ロストフの教区が北の偶像の中に建てられる。",
    "A Greek iconographer of Constantinople founding the island monastery of Lake Onega, the Sophia icon he copied in his hands, the peoples of the north gathering to his light at the age of one hundred and five.": "コンスタンディヌポリのギリシヤの聖像画家がオネガ湖の島の修道院を建て、写したソフィヤの聖像を手に持ち、北の諸民が百五歳のその光に集まる。",
    "A Greek metropolitan enthroned at Moscow beside the shrine of Peter, standing unbowed before the khan of the Horde, the Church's charter of freedom in his hand.": "ギリシヤの府主教がモスクワでペトルの棺の傍らに座し、オルダの汗の前に屈せず立ち、教会の自由の証書を手にする。",
    "A Greek of Ephesus at the Apostle Paul's side, the Temple riot swirling around his innocent presence, the sickbed of Miletus and the sword of Rome completing his long companionship.": "エフェスのギリシヤ人が使徒パウェルの傍らにあり、神殿の騒動がその無垢な姿を巡り、ミリトの病床とロマの剣がその長い同行を全うする。",
    "A Greek prince laying aside his rank for the monastic habit, the Uchma hermitage rising on the bank of the Volga, the exile made a wonderworker in his adopted land.": "ギリシヤの公が位を捨てて修道服を取り、ヴォルガの岸にウチマの隠居所が立ち、その追放者が新しい地で成神者となる。",
    "A Patriarch of Constantinople seated upright in death as in blessing, the Mgar monastery of Lubny receiving the traveler, the two worlds of Greece and Rus' joined at his throne.": "コンスタンディヌポリの総主教が死してなお祝福するごとく直立して座し、ルブヌイのムガル修道院がその旅人を受け入れ、ギリシヤとロシヤの二つの世界がその位で結ばれる。",
    "A Persian noble offering his severed members one by one, each with a prayer, angels gathering his prayers.": "ペルシャの貴人が斬られた肢を一つずつ祈りとともに献げ、天使らがその祈りを集める。",
    "A Persian soldier turned monk, the captive Cross of the Lord shining before him, the waters and the sword of Bethsaloe beneath his crown.": "修道士となったペルシャの兵士の前に囚われた主の十字架が輝き、その冠の下にヴェフサロエの水と剣がある。",
    "A Roman centurion kneeling before the Apostle Peter, or vested as a bishop holding a Gospel.": "ロマの百人長が使徒ペトルの前にひざまずき、あるいは主教として祭服を着て福音書を持つ。",
    "A Roman general in armor holding a cross, his soldiers behind him, a spring at his feet.": "ロマの将軍が甲冑を着て十字架を持ち、その兵士たちがその後ろにあり、泉がその足下にある。",
    "A Roman maiden in flight across the sea with two servants, the convent of Saint Stephen at Mylasa, a cross of stars brighter than the sun above her repose.": "ロマの乙女が二人の婢とともに海を渡って逃れ、ミラサの聖ステファンの女子修道院があり、日より明るい星の十字がその永眠の上にある。",
    "A Roman matron refusing the Arian rite, the fire kindled behind her, Saint Ambrose blessing from afar.": "ロマの婦人がアリイの儀を拒み、火がその後ろに焚かれ、聖アムウロシイが遠くから祝福する。",
    "A Roman noblewoman scattering deeds and treasure to the poor, thousands of freed slaves behind her, her small cell on the Mount of Olives before her.": "ロマの貴婦人が証文と財宝を貧しき者に散らし、解放された幾千の奴隷がその後ろにあり、オリヴェトの山の小さな庵がその前にある。",
    "A Roman senator opening his house to the Apostle Peter, the household at prayer becoming a church, the greeting of the epistle shining over the door.": "ロマの元老が使徒ペトルに家を開き、祈る家人が教会となり、書簡の挨拶が戸口の上に輝く。",
    "A Roman widow standing amid seven crowned sons, encouraging each to the contest, her own crown descending last.": "ロマの寡婦が冠を受けた七人の子の中に立ち、各々を戦いへ励まし、自らの冠が最後に降る。",
    "A Russian captive in the winter night of Kazan, bound and wounded in the snow, alive at dawn with his confession unbroken.": "カザンの冬の夜のロシヤの捕虜が縛られ傷ついて雪の中にあり、夜明けにその信仰の告白を破られずに生きている。",
    "A Russian soldier-slave at prayer in his master's stable, the Turkish household softened by his faith, his incorrupt relics glorified across the Greek world.": "ロシヤの兵士たる奴隷が主人の厩で祈り、トルコの家がその信仰に和らぎ、その朽ちざる聖遺物がギリシヤの世界に讃えられる。",
    "A Serbian prince leading his army at Kosovo, choosing the kingdom of heaven over the kingdom of earth, crowned as a great-martyr, his incorrupt relics the treasure of his people.": "セルビヤの公がコソヴォで軍を率い、地の国よりも天の国を選び、大致命者として冠を受け、その朽ちざる聖遺物がその民の宝となる。",
    "A Spanish dignitary in the Great Schema, the roads of his pilgrimage from Rome to Jerusalem behind him, the Saracen sword before him.": "大形を受けたイスパニヤの高官がロマからエルサレムへの巡礼の道を後ろにし、サラセンの剣を前にする。",
})

TEXT.update({
    "A Swedish princess become mother of Rus, her sainted son Vladimir beside her, the crowns of France, Hungary, and Norway among her daughters, the nun's habit her final vesture.": "ロシヤの母となったスウェーデンの王女、その聖なる子ウラジーミルがその傍らにあり、フランキヤ、ウグリヤ、ノルウェイの冠がその娘たちの中にあり、修道服が最後の衣となる。",
    "A Syrian stranger standing three days in prayer in the church of Spoleto, the garden thieves fed at his table and converted, the offered estates refused with a smiling shake of the head.": "シリヤの旅人がスポレトの聖堂で三日祈って立ち、その食卓で養われて改宗した園の盗人たち、微笑と首の振りで断られた献げられた領地。",
    "A Tatar captive baptized and tonsured, founding a monastery on the shore of Lake Kozha in the far north, the wilderness hallowed by his prayer.": "洗礼を受け剃髪されたタタルの捕虜が遠い北のコジャ湖の岸に修道院を建て、その祈りによって荒野が聖とされる。",
    "A Yup'ik mother in a kuspuk holding a basin and towel, the northern lights above the tundra behind her.": "クスパクを着たユピクの母が盥と手拭を持ち、その後ろのツンドラの上に北の光がある。",
    "A barefoot ascetic in rags, blessing, at Novgorod.": "ぼろをまとった裸足の修行者がノヴゴロドで祝福する。",
    "A barefoot fool in tattered clothing by a northern river, giving away what was given to him.": "北の河のほとりのぼろをまとった裸足の佯狂者が、与えられたものを人に与える。",
    "A barefoot fool-for-Christ holding a head of cabbage, at Novgorod by the river.": "裸足のハリストスの故の佯狂者が河のほとりのノヴゴロドでキャベツの玉を持つ。",
    "A barefoot fool-for-Christ in a sheepskin holding an axe, by the river defending the city.": "羊皮を着た裸足のハリストスの故の佯狂者が斧を持ち、河のほとりで市を守る。",
    "A barefoot holy fool with long hair, holding a Psalter, of gentle and sorrowful aspect.": "長い髪の裸足の佯狂者が聖詠経を持ち、柔和にして悲しげな相をなす。",
    "A basilica at Lydda, the tomb of Saint George within, hierarchs consecrating the church.": "リダの大聖堂、その中に聖ゲオルギイの墓があり、主教らが聖堂を成聖する。",
    "A bearded missionary priest with a traveler's bag, the church of Jackson and the hills of California behind him.": "髭を蓄えた宣教の司祭が旅の袋を持ち、ジャクソンの聖堂とカリフォルニヤの丘がその後ろにある。",
    "A beggar beneath the staircase of his father's palace, unknown to all his household, the finished scroll of his life clasped in his dead hand while the emperor and the pope kneel to read it.": "父の宮殿の階段の下の乞食が家中の誰にも知られず、その生涯の書き終えた巻物が死せる手に握られ、皇帝と教皇が跪いてそれを読む。",
    "A bent elder in white on his knees upon the rock, the Theotokos of Tenderness before him, a bear at the edge of the forest clearing.": "白衣の腰の曲がった長老が岩の上に跪き、その前に生神女の柔和の聖像があり、森の空地の端に熊がいる。",
    "A bishop alone in an emptied city awaiting the persecutors, then crucified at Perge, teaching from the cross until his voice failed into glory.": "主教が空となった市に独り迫害者を待ち、後にペルギヤで十字架にかけられ、その声が栄光に絶えるまで十字架から教える。",
    "A bishop and a presbyter of Persia holding crosses, swords above them.": "ペルシャの主教と長老が十字架を持ち、その上に剣がある。",
    "A bishop and a virgin holding crosses, broken books of sorcery burning at their feet.": "主教と童貞女が十字架を持ち、その足下で破られた魔術の書が燃える。",
    "A bishop and his companions holding crosses, cast into a furnace, a soldier among them.": "主教とその同伴者たちが十字架を持ち、炉に投げ込まれ、その中に一人の兵士がいる。",
    "A bishop and presbyter cast into a pit, angels crowning them from above.": "主教と長老が穴に投げ込まれ、天使らが上から冠を授ける。",
    "A bishop and theologian of Lycia with the scroll of his Banquet of the Ten Virgins, refuting the errors of Origen, crowned at the last with martyrdom.": "リキヤの主教にして神学者が十人の童貞女の宴の巻物を持ち、オリゲンの誤りを責め、最後に致命によって冠を受ける。",
    "A bishop answering the emperor that the Church's questions belong to the Church, the road of exile opening behind him.": "主教が皇帝に、教会の問いは教会に属すると答え、その後ろに追放の道が開ける。",
    "A bishop baptizing an African king, a boy captive and a royal tutor shown in the scenes of his life.": "主教がアフリカの王に洗礼を授け、捕われの少年と王の傅育者がその生涯の場面に示される。",
    "A bishop barring the church door to an emperor, a beehive at his feet, a scroll of his hymns in hand.": "主教が皇帝に聖堂の戸を閉ざし、その足下に蜜蜂の巣があり、その讃詞の巻物を手にする。",
    "A bishop before a fallen idol, a demon bearing a great stone altar behind him, hot springs at his feet.": "主教が倒れた偶像の前にあり、その後ろで悪魔が大きな石の祭壇を運び、その足下に温泉がある。",
    "A bishop before the burning temple of Marnas, the cross-guardian's keys at his belt, the Good Thief descending from the Cross in his vision, the Eudoxiana church rising over pagan Gaza.": "主教が燃えるマルナの神殿の前にあり、その帯に十字架守の鍵があり、その幻の中で善き盗賊が十字架から降り、エウドクシヤの聖堂が異教のガザの上に立つ。",
    "A bishop before the emperor, pointing to the emperor's son, teaching the honor due the Son of God.": "主教が皇帝の前で皇帝の子を指し、神の子に帰すべき尊敬を教える。",
    "A bishop beheaded at the altar in mid-Liturgy, twenty-eight years of tribunals and torments ranged behind him like waves, Agathangelus crowned at his side.": "主教が聖体礼儀の半ばに祭壇で斬られ、二十八年の裁きと苦しみが波のようにその後ろに連なり、アガファンゲルがその傍らで冠を受ける。",
    "A bishop beholding the ladder to heaven with his predecessor calling from above, one hundred and twenty-eight companions ascending behind him under the Persian sword.": "主教が天への梯子を見、その先任者が上から呼び、百二十八人の同伴者がペルシャの剣の下でその後を上る。",
    "A bishop by night in a plain cloak, leaving firewood at a poor widow's door, his cathedral of Belgorod behind him.": "主教が夜に質素な衣を着て、貧しい寡婦の戸口に薪を置き、その後ろにベルゴロドの大聖堂がある。",
    "A bishop drinking the sorcerer's cup unharmed, the magician kneeling converted beside his cast-down instruments.": "主教が魔術師の杯を害なく飲み、魔法使が倒された道具の傍らに跪いて改宗する。",
    "A bishop enthroned with a Gospel, the first hierarch of Jerusalem, of ascetic and venerable countenance.": "主教が福音書とともに位に座し、エルサレムの最初の主教として、修行者にして尊ぶべき相をなす。",
    "A bishop holding a Gospel, refuting heretics who shrink before his word.": "主教が福音書を持ち、その言葉の前に退く異端者を責める。",
    "A bishop holding a page of the alphabet he invented, the sacred birch of the Zyrians felled behind him, the sorcerer Pam turning from the fire and the water, a new people reading the Gospel in its own letters.": "主教が自ら作った文字の一葉を持ち、その後ろでズィリャンの聖なる樺が伐られ、魔術師パムが火と水から退き、新しい民が自らの文字で福音を読む。",
    "A bishop holding a scroll of the Creed, the Theotokos and John the Theologian appearing above, a mountain moved behind.": "主教が信経の巻物を持ち、上に生神女と神学者イオアンが現れ、後ろに動かされた山がある。",
    "A bishop holding an icon of Christ against the imperial decree, the sick healed at his hands.": "主教が皇帝の命に逆らってハリストスの聖像を持ち、その手で病者が癒される。",
    "A bishop holding the book of the Divine Names, the darkened sun of the Crucifixion above him.": "主教が神名論の書を持ち、その上に十字架の暗くなった太陽がある。",
    "A bishop in a laborer's tunic drawing water and hauling wood at Nitria, the omophorion of Damascus folded away, heaven alone reading the monk's true rank.": "主教が労働者の衣を着てニトリヤで水を汲み薪を運び、ダマスクの肩衣は脇に畳まれ、天のみが修道士の真の位を読む。",
    "A bishop in a mitre holding a crozier, with a gray beard and an ascetic, gentle face.": "宝冠を戴いた主教が牧杖を持ち、白い髭と修行者の柔和な顔をなす。",
    "A bishop in monastic poverty, Cernica's island monastery at one hand and the Frasinei he founded at the other, the seminary and the printing press of Ramnic behind him, his face worn bright by fasting.": "主教が修道の貧しさの中にあり、片手にチェルニカの島の修道院、他方に自ら建てたフラシネイがあり、その後ろにルムニクの学校と印刷所があり、その顔は斎によって輝くまで衰えている。",
    "A bishop in the omophorion and mantle holding a book, of gentle and humble aspect.": "肩衣と外套を着た主教が書物を持ち、柔和にして謙遜な相をなす。",
    "A bishop in the omophorion and sakkos holding a Gospel book, with a Greek-style beard.": "肩衣とサッコスを着た主教が福音書を持ち、ギリシヤ風の髭をなす。",
})

TEXT.update({
    "A bishop in the omophorion blessing the waters at a river confluence, holding a cross.": "肩衣を着た主教が河の合流で水を祝福し、十字架を持つ。",
    "A bishop in the omophorion blessing, holding a Gospel, before the cathedral of Tambov.": "肩衣を着た主教が祝福し、福音書を持ち、タンボフの大聖堂の前にある。",
    "A bishop in the omophorion holding a Gospel book or the scroll of his Great Canon.": "肩衣を着た主教が福音書あるいは自らの大カノンの巻物を持つ。",
    "A bishop in the omophorion holding a Gospel book, a white dove upon his head.": "肩衣を着た主教が福音書を持ち、その頭上に白い鳩がある。",
    "A bishop in the omophorion holding a Gospel, of humble aspect.": "肩衣を着た主教が福音書を持ち、謙遜な相をなす。",
    "A bishop in the omophorion holding a Gospel, sometimes with a banner or before a battle.": "肩衣を着た主教が福音書を持ち、時に旗とともに、あるいは戦の前にある。",
    "A bishop in the omophorion holding a Gospel, the cathedral of Saints Cyril and Methodius behind him.": "肩衣を着た主教が福音書を持ち、その後ろに聖キリルとメフォディイの大聖堂がある。",
    "A bishop in the omophorion holding an icon and a Gospel.": "肩衣を着た主教が聖像と福音書を持つ。",
    "A bishop in the omophorion surrounded by his ten disciples, all crowned as martyrs.": "肩衣を着た主教が十人の弟子に囲まれ、皆が致命者として冠を受ける。",
    "A bishop in the omophorion, his hands or face marked by charcoal, holding a Gospel.": "肩衣を着た主教の手あるいは顔が炭で汚され、福音書を持つ。",
    "A bishop in the schema and omophorion holding a Gospel, before the city of Voronezh.": "大形と肩衣を着た主教が福音書を持ち、ヴォロネジの市の前にある。",
    "A bishop in the snows of Siberia, a school of native children beside him, the gates of China closed behind.": "主教がシベリヤの雪の中にあり、その傍らに現地の子らの学校があり、後ろに中国の門が閉ざされている。",
    "A bishop laying aside his omophorion at the mouth of a desert gorge, the monastery of Choziba in the cliffs.": "主教が荒野の谷の入口で肩衣を脱ぎ、崖にホジヴァの修道院がある。",
    "A bishop led by an angel from torture to torture and city to city, Sirmium converted behind him and Formia receiving him, the lamps of the sailors burning at his name.": "主教が天使に導かれて苦しみから苦しみへ、市から市へ移り、その後ろでシルミイが改宗し、フォルミヤが彼を受け入れ、その名に船人らの灯が燃える。",
    "A bishop of Aegina laying down his omophorion and returning to the monastic habit, his island see behind him.": "エギナの主教が肩衣を脱いで修道服に帰り、その後ろに島の教区がある。",
    "A bishop of Amasea standing between the hunted virgin and the tyrant's demand, the sea giving back his body in the fishermen's nets, the last crowns of the persecution descending as the peace of the Church dawns.": "アマシヤの主教が追われる童貞女と暴君の要求の間に立ち、海が漁師の網でその体を返し、教会の平和が明ける時に迫害の最後の冠が降る。",
    "A bishop of Argos measuring out grain that does not diminish, the ransomed captives returning from the sea behind him, his monastic family in Christ around the one see he consented to hold.": "アルゴスの主教が尽きぬ穀物を量り、その後ろで贖われた捕虜が海から帰り、彼が受け入れた唯一の教区の周りにハリストスにある修道の家族がいる。",
    "A bishop of Benevento unharmed in the furnace, the beasts of the arena lying at his feet, Naples receiving his body and his blood, his deacons and companions crowned around him.": "ベネヴェントの主教が炉の中で害を受けず、闘技場の獣がその足下に伏し、ネアポリがその体と血を受け入れ、その輔祭と同伴者がその周りで冠を受ける。",
    "A bishop of Bithynia holding the icon of Christ and the open Scriptures together, the road of exile behind him.": "ビフィニヤの主教がハリストスの聖像と開かれた聖書をともに持ち、その後ろに追放の道がある。",
    "A bishop of Bithynia on the road of exile, his cathedral behind him and the icon of Christ unsurrendered before him.": "ビフィニヤの主教が追放の道にあり、その後ろに大聖堂があり、その前に渡さなかったハリストスの聖像がある。",
    "A bishop of Brooklyn with the map of a continent behind him, thirty parishes rising from immigrant streets, The Word in his hand, Tikhon of Moscow laying hands upon the first-consecrated of America.": "ブルックリンの主教がその後ろに大陸の地図を持ち、移民の街から三十の教区が立ち上がり、その手に言葉があり、モスクワの聖ティーホンがアメリカの最初に叙聖された者に手を置く。",
    "A bishop of Catania in exile for the holy images, the icon of Christ held fast against the imperial decree.": "カタニヤの主教が聖なる像のために追放され、皇帝の命に逆らってハリストスの聖像を固く保つ。",
    "A bishop of Chalcedon and his fellow ascetic standing together for the icons, the see of the Fourth Council refusing the new heresy, exile shared as the cell had been.": "ハルキドンの主教とその同修者が聖像のためにともに立ち、第四全地公会の教区が新しい異端を拒み、庵を分けたように追放を分かつ。",
    "A bishop of Chalcedon defending the holy icons, his hand open to the poor, the exile that crowned his confession before him.": "ハルキドンの主教が聖なる聖像を守り、その手は貧しき者に開かれ、その信仰告白に冠を授けた追放がその前にある。",
    "A bishop of Corinth falsely accused, the newborn infant speaking at his prayer to name its true father, the slander confounded and the saint vindicated.": "コリンフの主教が偽って訴えられ、その祈りによって新生児が語ってその真の父を告げ、中傷が破られ聖人が正しいと認められる。",
    "A bishop of Cyprus blessing a dry vine-branch that bears fruit before its time, the poor fed at his hand, the idols of the island cast down.": "キプルの主教が枯れた葡萄の枝を祝福して時ならぬ実を結ばせ、その手で貧しき者が養われ、島の偶像が倒される。",
    "A bishop of Cyprus crowned with martyrdom, his myrrh-streaming relics borne across the sea to Constantinople, the sick healed at his shrine.": "キプルの主教が致命によって冠を受け、その滲香する聖遺物が海を越えてコンスタンディヌポリへ運ばれ、その棺で病者が癒される。",
    "A bishop of Cyprus with the nails of his torture, teaching the faithful gathered at what he thought his end, the edict of Constantine opening his prison to a few more years of shepherding.": "キプルの主教がその責苦の釘とともにあり、自らの終わりと思ったところに集まった信者を教え、コンスタンチンの勅令がその獄を開いてなお数年の牧を与える。",
    "A bishop of Epirus striking down the great serpent at the poisoned spring, the rain descending on the parched fields at his prayer, a dead man rising from the bier to witness against the false creditor.": "エピルの主教が毒の泉の大蛇を打ち倒し、その祈りによって乾いた畑に雨が降り、死人が棺から起きて偽りの債主に対して証しする。",
    "A bishop of Melitene serene under the torturers, the emperor's own order opening his prison, the confessor's crown worn through years of peace.": "メリティナの主教が責め手の下で穏やかにあり、皇帝自らの命がその獄を開き、平和の年月を通じて宣信者の冠を帯びる。",
    "A bishop of Novgorod standing alone against an uncanonical council, the Caves that formed him receiving him in confinement and in death, Theodosius appearing to welcome him home.": "ノヴゴロドの主教が教規に反する公会に独り立ち向かい、彼を育てた洞窟が幽閉と死においてその者を受け入れ、フェオドシイが現れて家に迎える。",
    "A bishop of Pergamum standing where Satan's throne was, the brazen bull glowing behind him, the open Apocalypse naming him the faithful witness in the Lord's own voice.": "ペルガモの主教がサタナの座のあった所に立ち、その後ろで銅の牛が赤く燃え、開かれた黙示録が主自らの声で彼を忠実な証人と呼ぶ。",
    "A bishop of Perm baptizing the peoples of the far north, the idols of the Permians thrown down and the churches rising, the mission of Saint Stephen carried onward.": "ペルミの主教が遠い北の諸民に洗礼を授け、ペルミ人の偶像が倒され聖堂が立ち、聖ステファンの宣教が引き継がれる。",
    "A bishop of Persia with staff of prophecy, a ruined city behind him, two disciples at his side.": "ペルシャの主教が預言の杖を持ち、その後ろに荒れた市があり、その傍らに二人の弟子がいる。",
    "A bishop of Pisidian Antioch refusing the iconoclast decree, the icons standing in his churches while he goes into exile, the confessor's crown replacing the surrendered see.": "ピシディヤのアンティオキヤの主教が聖像破壊の勅令を拒み、彼が追放へ赴く間も聖像がその聖堂に立ち、宣信者の冠が捨てた教区に代わる。",
    "A bishop of Prusa destroying a great serpent by the sign of the Cross, preaching Christ under Julian the Apostate, crowned with martyrdom by the sword.": "プルサの主教が十字架の印によって大蛇を滅ぼし、背教者ユリアンの下でハリストスを説き、剣によって致命の冠を受ける。",
    "A bishop of Prusa standing unharmed in the boiling spring, preaching the God who made both the healing waters and the fire of hell, his three presbyters crowned beside him.": "プルサの主教が煮え立つ泉の中に害なく立ち、癒しの水と地獄の火をともに造られた神を説き、三人の長老がその傍らで冠を受ける。",
    "A bishop of Rome in the omophorion holding a Gospel, with a martyr's palm.": "肩衣を着たロマの主教が福音書を持ち、致命者の枝を携える。",
    "A bishop of Rome of the age of the martyrs, shepherding his flock in the catacombs, bringing the noble and the humble alike to the faith of Christ.": "致命者の時代のロマの主教が地下墓地でその群れを牧し、貴き者も賤しき者も等しくハリストスの信仰に導く。",
    "A bishop of Rostov preaching Christ to the half-pagan land, the idols thrown down and the churches rising, the grace of wonders confirming the word of the Caves-trained shepherd.": "ロストフの主教が半ば異教のその地にハリストスを説き、偶像が倒され聖堂が立ち、洞窟で育った牧者の言葉を奇跡の恵みが確かめる。",
})

TEXT.update({
    "A bishop of Rostov whose very funeral became a glorification, wonders flowing from his body before burial, the shepherd of the yoke-time honored as a saint from the hour of his death.": "ロストフの主教の葬儀そのものが列聖となり、埋葬の前からその体より奇跡が流れ、軛の時代の牧者がその死の時から聖人として崇められる。",
    "A bishop of Salamis with the five tongues of his learning and the Panarion of his refutations, the ascetic of the Palestinian desert crowned with the long white rule of Cyprus.": "サラミナの主教が五つの言葉の学識とその論駁のパナリオンとともにあり、パレスチナの荒野の修行者がキプルの長く輝かしい治めによって冠を受ける。",
    "A bishop of Samosata refusing to surrender the record of the faith though his hand be cut off, traveling in disguise to strengthen the Orthodox, crowned by the tile of an Arian.": "サモサタの主教が手を切られようとも信仰の記録を渡すことを拒み、正教徒を強めるため姿を変えて旅し、アリイ派の女の投げた瓦によって冠を受ける。",
    "A bishop of Sardis scourged for Christ, the dry wooden stake stained with his blood taking root and growing into a green tree of healing beside him.": "サルディの主教がハリストスのために打たれ、その血に染まった枯れた木の杭が根を張り、その傍らで癒しの緑の木に育つ。",
    "A bishop of Synnada bearing the icons he defended, the courts of caliph and emperor behind him, the exile that crowned his confession before him.": "シナダの主教が自ら守った聖像を携え、その後ろにカリフと皇帝の宮廷があり、その前にその信仰告白に冠を授けた追放がある。",
    "A bishop of Tver reconciling princes with the Gospel between them, the Zheltikov monastery rising by the river, the Kyiv Caves Paterikon copied out under his hand.": "トヴェリの主教が福音書を間に置いて公らを和解させ、河のほとりにジェルティコフ修道院が立ち、その手でキエフ洞窟のパテリクが書き写される。",
    "A bishop of Verona with a fishing rod and a line of catechumens for his catch, the Adige rising in flood behind him and standing like a wall at the open doors of his church.": "ヴェロナの主教が釣竿を持ち、その獲物として啓蒙者の列があり、その後ろでアディジェが溢れ、その聖堂の開かれた戸口に壁のように立つ。",
    "A bishop of Vladimir with the founding letter of the Caves Paterik in his hand, his friend Polikarp cautioned against vainglory, the Near Caves receiving the author home to the monastery of his heart.": "ウラジーミルの主教が手に洞窟のパテリクの創めの書簡を持ち、その友ポリカルプが虚栄を戒められ、近隔洞窟が著者をその心の修道院へ迎える。",
    "A bishop of ascetic countenance in the omophorion, blessing, his incorrupt relics in a shrine.": "修行者の相をなす主教が肩衣を着て祝福し、その朽ちざる聖遺物が棺にある。",
    "A bishop of gentle countenance distributing alms, a schema laid ready beside his omophorion.": "柔和な相をなす主教が施しを配り、その肩衣の傍らに大形が備えられている。",
    "A bishop of the Black Sea coast with his city walls behind him, Saracen raiders scattered by his prayer, the northern raiders frozen at his sepulcher until the captives go free.": "黒海の岸の主教がその後ろに市の城壁を持ち、サラセンの略奪者がその祈りによって散らされ、北の略奪者がその墓で凍りついて捕虜を放つまで動けない。",
    "A bishop of the Crimean Goths defending the holy icons, consecrated in Orthodox Georgia, sharing the sufferings of his people under the Khazar yoke.": "クリミヤのゴトの主教が聖なる聖像を守り、正教のグルジヤで叙聖され、ハザルの軛の下でその民の苦しみを分かつ。",
    "A bishop of the Hellespont in chains for the icons, the letters of Theodore the Studite in his hands.": "ゲレスポントの主教が聖像のために鎖につながれ、その手にストゥディオンのフェオドルの書簡がある。",
    "A bishop of the Hellespont on the road again, the iconoclasts' document forever unsigned behind him, the icon of Christ carried from refuge to refuge.": "ゲレスポントの主教が再び道にあり、その後ろに永久に署名されなかった聖像破壊の文書があり、ハリストスの聖像が避難所から避難所へ運ばれる。",
    "A bishop of the Nicene fathers leading the serpent by his staff into the fire, and on the mountain road the ambush of the heretics, the stone of the murderess turned against her until his grave healed her.": "ニケヤの父たちの一人たる主教が杖で蛇を火へ導き、山の道で異端者の待ち伏せに遭い、女の殺人者の石が彼女自身に向かい、その墓が彼女を癒すまで続く。",
    "A bishop of the Siberian frontier among the peoples of the east, the churches and schools of his planting behind him, the lamp of his night prayers burning over Irkutsk.": "シベリヤの辺境の主教が東の諸民の中にあり、その後ろに彼が植えた聖堂と学校があり、その夜の祈りの灯がイルクーツクの上に燃える。",
    "A bishop of the apostolic line blessing a bitter spring at Catania, the water running sweet and the city believing.": "使徒継承の主教がカタニヤの苦い泉を祝福し、水が甘く流れて市が信じる。",
    "A bishop ordained by the hand of the Theologian, laying his own hand on the young Polycarp, a myrtle flowering from his tomb.": "神学者の手によって叙聖された主教が自ら若きポリカルプに手を置き、その墓から桃金嬢が花咲く。",
    "A bishop rapt in divine song at the funeral of the Theotokos, the apostles around the bier.": "主教が生神女の葬儀で神なる歌に魅せられ、その棺の周りに使徒たちがいる。",
    "A bishop rising from a deep pit, the king with the face of a beast healed before him, a church shown from heaven.": "主教が深い穴から昇り、獣の顔をした王がその前で癒され、天から聖堂が示される。",
    "A bishop sailing upon his mantle across the lake, the city that expelled him kneeling on the shore.": "主教が自らの外套に乗って湖を渡り、彼を追い出した市が岸で跪く。",
    "A bishop scourged with ox-hide thongs, the icon of Christ held fast in his hands through four exiles.": "主教が牛の皮の紐で打たれ、四度の追放を通じてハリストスの聖像を手に固く保つ。",
    "A bishop serene in prison, the false witness healed and confessing, an open book of Ecclesiastes before him.": "主教が獄で穏やかにあり、偽証者が癒されて告白し、その前に伝道之書が開かれている。",
    "A bishop set upon by schismatics with swords, praying for his murderers as he falls.": "主教が剣を持った分離派に襲われ、倒れながら自らの殺害者のために祈る。",
    "A bishop standing unharmed in the flames with the sorcerer bound in his omophorion, the fire dividing the true wonder from the false before the whole city.": "主教が炎の中に害なく立ち、魔術師がその肩衣に縛られ、火が全市の前で真の奇跡を偽りから分かつ。",
    "A bishop standing upon his mantle spread on the waters of the Oka, the Murom icon of the Mother of God in his hands, borne upstream to Ryazan, his innocence proclaimed by the wonder.": "主教がオカの水面に広げた外套の上に立ち、その手にムロムの生神女の聖像を持ち、流れに逆らってリャザンへ運ばれ、その無実が奇跡によって告げられる。",
    "A bishop struck down at the altar during the Divine Liturgy, angels receiving his soul.": "主教が聖体礼儀の間に祭壇で打たれ、天使らがその霊を受ける。",
    "A bishop tried by fire, beasts, and sword, the great company of five hundred forty-six confessors about him, Jerusalem's name upon a martyrdom the whole East shared.": "主教が火と獣と剣によって試され、五百四十六人の宣信者の大いなる群れがその周りにあり、全東方が分かち合った致命にエルサレムの名が刻まれる。",
    "A bishop upon a pillar with a pen, the paschal sermons streaming from his mouth like light, the prayer book of the faithful open at the prayers he wrote for every day of the week.": "主教が筆を持って柱の上にあり、その口から復活祭の説教が光のように流れ出て、週の各日のために彼が書いた祈りのところで信者の祈祷書が開かれている。",
    "A bishop vested in the omophorion, with a short rounded beard, holding a Gospel book and blessing.": "肩衣を着けた主教が短く丸い髭をなし、福音書を持って祝福する。",
    "A bishop washing the wounds of lepers with his own hands, then standing before Leo the Armenian foretelling his swift destruction, the fortress of his thirty-year exile behind him.": "主教が自らの手で癩者の傷を洗い、次いでアルメニヤ人レフの前に立ってその速やかな滅びを予告し、その後ろに三十年の追放の城塞がある。",
    "A bishop who once wore Tatar chains preaching Christ in the Tatar tongue at Kazan, the Savior monastery rising in the kremlin, the sick of two faiths healed at his prayer.": "かつてタタルの鎖を負った主教がカザンでタタルの言葉によってハリストスを説き、クレムリに救世主修道院が立ち、二つの信仰の病者がその祈りによって癒される。",
    "A bishop who was a surgeon, the omophorion over his shoulders and the healing of the sick in his hands, the prisons and exiles of his confession behind him, the light of Christ in a godless age.": "外科医であった主教が肩に肩衣を掛け、その手に病者の癒しを持ち、その後ろにその信仰告白の獄と流刑があり、無神の時代におけるハリストスの光となる。",
    "A bishop with a Gospel preaching to the people of Volhynia, a cave monastery in the distance.": "主教が福音書を持ってヴォリニヤの民に説き、遠くに洞窟修道院がある。",
    "A bishop with a company of one hundred ninety-nine disciples, the sign of the Cross that saved him in battle above, the swords of Sicily gathering the whole school into one harvest.": "主教が百九十九人の弟子の群れとともにあり、戦で彼を救った十字架の印が上にあり、シチリヤの剣が学校全体を一つの収穫に集める。",
    "A bishop with a high domed forehead and short pointed beard, a thin ascetic face, vested in the omophorion and holding a Gospel book.": "高く丸い額と短く尖った髭、痩せた修行者の顔をなす主教が肩衣を着けて福音書を持つ。",
    "A bishop with a lamp, a serpent fleeing before him, the island of Crete behind.": "主教が灯を持ち、その前で蛇が逃げ、後ろにクリトの島がある。",
    "A bishop with a long dark tapering beard and high forehead, vested in the omophorion, holding a Gospel book and blessing.": "長く暗い先細りの髭と高い額をなす主教が肩衣を着け、福音書を持って祝福する。",
    "A bishop with the Prologue open in his hands, the lake of Ohrid behind one shoulder and the wire of Dachau behind the other, preaching Christ to the peoples in every tongue he knew.": "主教が開かれたプロログを手に持ち、片方の肩の後ろにオフリドの湖、他方の後ろにダハウの鉄条網があり、知る限りのあらゆる言葉で諸民にハリストスを説く。",
    "A bishop with the marks of long warfare, demons fleeing behind him, angels and the Theotokos receiving his soul before him.": "長い戦いの跡をとどめる主教の後ろで悪魔が逃げ、その前で天使と生神女がその霊を受ける。",
})

TEXT.update({
    "A bishop with the paschal fire blazing on the hill of Slane against the high king's darkness, the shamrock of the Trinity in his hand, the tribes of Ireland kneeling to the font.": "主教が大王の闇に抗してスレインの丘に復活祭の火を燃やし、その手に三位一体の三葉草を持ち、イルランジヤの諸族が洗礼盤に跪く。",
    "A bishop with verses branded upon his face, holding an icon of Christ and a scroll of canons.": "顔に詩句を焼き付けられた主教がハリストスの聖像と教規の巻物を持つ。",
    "A bishop writing canons at a desk, the Theotokos appearing to bless him.": "主教が机で規則を書き、生神女が現れて彼を祝福する。",
    "A bishop's omophorion hidden beneath a novice's habit, an aged hesychast silent in his cell at the Lavra.": "見習の衣の下に隠された主教の肩衣、ラヴラの庵で沈黙する老いた静修者。",
    "A bishop, a deacon, a servant, and a holy woman crowned together amid flames at Pergamum.": "主教、輔祭、僕、聖なる婦人がペルガモの炎の中でともに冠を受ける。",
    "A bishop-ascetic in chains beneath an iron cage, Saint George leading him from childhood as a companion, the possessed freed and the storms stilled at his prayer, the resigned omophorion folded beside the hermit's cave.": "鉄の檻の下で鎖につながれた修行者たる主教、幼き時より同伴者として彼を導く聖ゲオルギイ、その祈りによって解かれた憑かれし者と鎮まる嵐、隠者の洞窟の傍らに畳まれた辞した肩衣。",
    "A bishop-confessor bearing the marks of his wounds, holding a Gospel.": "その傷の跡を負う宣信者たる主教が福音書を持つ。",
    "A bishop-envoy on the road between empires, gifts flowing through his hands to the poor of his city.": "帝国の間の道にある使節たる主教、その手を通って市の貧しき者へ流れる贈物。",
    "A bishop-martyr barring an emperor from the church doors, three youths and their mother beside him.": "致命者たる主教が皇帝に聖堂の戸を閉ざし、三人の少年とその母がその傍らにいる。",
    "A bishop-martyr by the sea, ships in the distance, flames beneath his feet trampled down.": "海のほとりの致命者たる主教、遠くに船があり、その足下で炎が踏み消される。",
    "A bishop-martyr holding a Gospel, a lion at his feet praising God.": "致命者たる主教が福音書を持ち、その足下で獅子が神を讃える。",
    "A bishop-martyr in the omophorion holding a Gospel and a cross.": "肩衣を着た致命者たる主教が福音書と十字架を持つ。",
    "A bishop-martyr in the omophorion holding a Gospel or a scroll inscribed against heresy.": "肩衣を着た致命者たる主教が福音書あるいは異端に対する銘のある巻物を持つ。",
    "A bishop-martyr in the omophorion holding a Gospel or a scroll on the unity of the Church.": "肩衣を着た致命者たる主教が福音書あるいは教会の一致についての巻物を持つ。",
    "A bishop-martyr in the omophorion holding a Gospel, a burning church in the background.": "肩衣を着た致命者たる主教が福音書を持ち、後景に燃える聖堂がある。",
    "A bishop-martyr in the omophorion holding a Gospel, sometimes with a ship or flames.": "肩衣を着た致命者たる主教が福音書を持ち、時に船あるいは炎とともにある。",
    "A bishop-martyr in the omophorion holding a Gospel, with his three companions and tamed beasts.": "肩衣を着た致命者たる主教が福音書を持ち、三人の同伴者と馴らされた獣とともにある。",
    "A bishop-martyr with a soldier and four women, all crowned together.": "致命者たる主教が一人の兵士と四人の婦人とともにあり、皆がともに冠を受ける。",
    "A bishop-martyr with a young nun and two servants, holding crosses.": "致命者たる主教が若い修道女と二人の婢とともに十字架を持つ。",
    "A bishop-physician and his sister holding crosses, his hands extended in healing.": "医者たる主教とその妹が十字架を持ち、その手が癒しのために伸ばされる。",
    "A bishop-physician at the Persian court, the king healed and the hidden trickster unearthed from beneath the temple floor, caravans of martyrs' relics entering the city of his name.": "ペルシャの宮廷の医者たる主教、癒された王と神殿の床の下から掘り出された隠れた詐欺師、その名を負う市に入る致命者の聖遺物の隊列。",
    "A bishop-physician in a mountain cave with the wild beasts gathered gently around him, a child healed of a choking bone, seven women and two children crowned beside him.": "山の洞窟の医者たる主教の周りに野の獣が穏やかに集まり、喉の骨から癒された子、その傍らで冠を受ける七人の婦人と二人の子。",
    "A blind eldress seated small and radiant in a Moscow room, the lines of the troubled stretching through the Soviet dark to her door, her closed eyes seeing all of it in God.": "モスクワの一室に小さく輝いて座る盲目の女長老、ソヴィエトの闇を通してその戸口へ延びる悩める者の列、そのすべてを神において見る閉じた目。",
    "A boy bishop-to-be praying before an emptied granary as it fills again, coins and wine multiplying in his open hands.": "後に主教となる少年が空となった穀倉の前で祈るとその倉が再び満ち、その開いた手の中で貨幣と葡萄酒が増える。",
    "A boy confessing Christ with his tutor Modestus and nurse Crescentia beside him, the cauldron and the beasts before them, the child and his guardians crowned together.": "傅育者モデストと乳母クリスケンティヤを傍らにハリストスを告白する少年、その前の釜と獣、ともに冠を受ける幼子とその守り手。",
    "A boy in peasant dress with a harrow, lightning above, angels receiving his soul.": "農夫の衣を着た少年が馬鍬とともにあり、上に稲妻があり、天使らがその霊を受ける。",
    "A boy martyr with a white dove above him, water springing from the rock at his prayer, the lion of his mountain cave refusing to harm him in the arena.": "致命者たる少年の上に白い鳩があり、その祈りによって岩から水が湧き、その山の洞窟の獅子が闘技場で彼を害することを拒む。",
    "A boy prince in royal robes bearing the palm of the passion-bearer, the yard of Uglich behind him where he fell, his incorrupt relics enshrined in the Kremlin to confound the pretenders.": "王の衣を着た少年の公が受難者の枝を負い、その後ろに彼が倒れたウグリチの庭があり、その朽ちざる聖遺物が僭称者らを辱めるためクレムリに安置される。",
    "A bread merchant with pierced hands and feet, walking his last steps for Christ.": "手と足を貫かれたパン商人がハリストスのために最後の歩みを進む。",
    "A bridegroom and bride in virginal crowns, the lion guarding Daria's honor, the tribune Claudius converted with his whole house, the sand pit of the Via Salaria closing over the two alive.": "童貞の冠をかぶった花婿と花嫁、ダリヤの貞潔を守る獅子、全家とともに改宗した千人長クラウディイ、生きたまま二人の上に閉じる塩の道の砂の穴。",
    "A brother and sister crowned as martyrs, holding crosses and palms.": "致命者として冠を受けた兄と妹が十字架と枝を持つ。",
    "A brother and sister martyrs, he upon a tree, she with a spear, both crowned.": "兄妹の致命者、彼は木の上に、彼女は槍とともにあり、二人とも冠を受ける。",
    "A canonarch of the Far Caves directing the chanting of the brethren, the book of the services in his hand, the monastic life embraced from his childhood.": "遠隔洞窟の誦経者が兄弟たちの歌を導き、その手に奉事の書があり、幼き時より修道の生活を受け入れる。",
    "A captain of the guard bound to a tree and shot with arrows, the widow Irene tending him, his converted companions with their crowns around him.": "衛兵の長が木に縛られ矢で射られ、寡婦イリナが彼を看護し、その周りに冠を受けた改宗した同伴者がいる。",
    "A cathedral in flames on the night of the Nativity, the bishop baptizing and communing the multitude within, twenty thousand crowns rising in the smoke.": "降誕の夜に炎に包まれた大聖堂、その中で群衆に洗礼と領聖を授ける主教、煙の中に立ち上る二万の冠。",
    "A centurion striding from the desert into the crowded amphitheater, proclaiming Christ before the astonished city.": "百人長が荒野から人で満ちた円形劇場へ歩み入り、驚く市の前でハリストスを宣べる。",
    "A centurion with spear at the foot of the Cross, his eyes lifted to the Crucified, confessing.": "槍を持った百人長が十字架の足下にあり、その目を十字架にかけられた者へ上げて告白する。",
    "A church at Nicopolis in Armenia": "アルメニヤのニコポリの聖堂",
    "A church built over his grave at Skepsis": "スケプシスのその墓の上に建てられた聖堂",
    "A church in her honor at Chalcedon by 450": "四五〇年までにハルキドンに建てられたその名誉の聖堂",
})

TEXT.update({
    "A church in his honor at Constantinople": "コンスタンディヌポリのその名誉の聖堂",
    "A church sexton in poor clothing, a princely ring and gold chain revealed beside his coffin.": "貧しい衣を着た聖堂の管理人、その棺の傍らに現れた公の指輪と金の鎖。",
    "A church was later raised over their burial place": "後にその埋葬の地の上に聖堂が建てられた",
    "A church was raised over their grave by Saint John Chrysostom": "その墓の上に聖金口イオアンによって聖堂が建てられた",
    "A clergyman of Hagia Sophia radiant in his enclosed cell, a lamp newly kindled in the great city.": "閉ざされた庵に輝く聖ソフィヤの聖職者、大いなる市に新たに灯された燈。",
    "A commander and his son with seventy soldiers, bound to the trees of the marsh, the ten-day martyrdom of the smallest executioners, seventy-two crowns over the swamp.": "将軍とその子が七十人の兵士とともに沼の木に縛られ、最も小さき処刑者による十日の致命、沼の上の七十二の冠。",
    "A company of martyrs holding crosses amid flames.": "炎の中で十字架を持つ致命者の群れ。",
    "A company of martyrs with hands raised amid flames, an angel above bearing crowns.": "炎の中で手を上げる致命者の群れ、冠を運ぶ上の天使。",
    "A company of monks bearing icons and the marks of mutilation, crowned together after their father Stephen.": "聖像と切断の跡を負う修道士の群れ、その父ステファンに続いてともに冠を受ける。",
    "A company of one hundred twenty captives of Persia, nine consecrated virgins among them, refusing the worship of fire and sun, one crown descending in a hundred twenty parts.": "ペルシャの百二十人の捕虜の群れ、その中に九人の献身した童貞女があり、火と日の礼拝を拒み、一つの冠が百二十に分かれて降る。",
    "A company of soldier-martyrs of Sebaste laying down their military belts, fire and sword behind them.": "軍帯を捨てるセヴァスティヤの兵士たる致命者の群れ、その後ろに火と剣がある。",
    "A company of virgin-martyrs led by two, crowned, the churches of Etchmiadzin behind them.": "二人に率いられた童貞女たる致命者の群れが冠を受け、その後ろにエチミアジンの聖堂がある。",
    "A convert of Britain in the priest's cloak giving himself up in the priest's place, led to the hill above the city, the first martyr of the land crowned by the sword.": "司祭の衣を着たブリタニヤの改宗者が司祭の代わりに自ら身を渡し、市の上の丘へ引かれ、その地の最初の致命者として剣によって冠を受ける。",
    "A court official in fine dress holding a cross, a small church beside him.": "美しい衣を着た宮廷の役人が十字架を持ち、その傍らに小さな聖堂がある。",
    "A courtier and his bride exchanging rings for monastic crowns, the Chronography open on his desk, the prison of Leo the Armenian and the island of his exile behind.": "指輪を修道の冠と取り替える廷臣とその花嫁、その机に開かれた年代記、アルメニヤ人レフの獄と追放の島が後ろにある。",
    "A courtier casting his belt and mantle at the emperor's feet, declaring himself a soldier of the Heavenly King, the cage of fire receiving him.": "廷臣が皇帝の足下に帯と外套を投げ、自ら天の王の兵士であると宣し、火の檻が彼を受ける。",
    "A courtier of Maximian with his mother's letter open in his hands, the denied Christ confessed again, the sword of Nicomedia completing his repentance.": "マクシミアンの廷臣が母の手紙を開いて手に持ち、否んだハリストスを再び告白し、ニコミディヤの剣がその痛悔を全うする。",
    "A courtier with a prince and princess of Persia, all three holding crosses.": "廷臣がペルシャの王子と王女とともにあり、三人とも十字架を持つ。",
    "A courtier-martyr before the emperor, a multitude of crucified soldiers behind him.": "致命者たる廷臣が皇帝の前にあり、その後ろに十字架にかけられた多くの兵士がいる。",
    "A crowned king with harp and scroll of the Psalms, the shepherd's sling at his feet, the Son of David foreshown above his throne.": "冠をかぶった王が竪琴と聖詠の巻物を持ち、その足下に牧者の投石器があり、その位の上にダヴィドの子が予め示される。",
    "A crowned prince in royal robes holding a cross and a church, with a long beard.": "冠をかぶった公が王の衣を着て十字架と聖堂を持ち、長い髭をなす。",
    "A crowned prince in royal robes holding a model of a church, and sometimes a sword or cross.": "冠をかぶった公が王の衣を着て聖堂の像を持ち、時に剣あるいは十字架を携える。",
    "A crowned princess in royal robes holding a cross and a model of a church.": "冠をかぶった公妃が王の衣を着て十字架と聖堂の像を持つ。",
    "A dark-skinned monk-priest in the schema, of humble and peaceful aspect, holding a scroll.": "大形を着た浅黒い修道司祭が謙遜にして平和な相をなし、巻物を持つ。",
    "A deacon and his jailer bound in one net above the Danube, the third-day promise shining over the water.": "輔祭とその獄吏がドナウの上で一つの網に縛られ、三日目の約束が水の上に輝く。",
    "A deacon baptizing the Ethiopian eunuch beside a chariot on the desert road.": "輔祭が荒野の道の車の傍らでエチオピヤの宦官に洗礼を授ける。",
    "A deacon in a sticharion holding the Gospel book, sometimes with the book hung about his neck.": "スティハリを着た輔祭が福音書を持ち、時にその書を頸に掛ける。",
    "A deacon of Heliopolis given to the mob under Julian, the broken idols of his youth held against him, the crowns descending on him and the martyrs of Gaza and Ascalon.": "ヘリオポリの輔祭がユリアンの時に群衆に渡され、若き日に砕いた偶像が罪とされ、彼とガザとアスカロンの致命者らに冠が降る。",
    "A deacon of Rome confessing Christ in chains, his fellow-martyrs and the princess Artemia gathered about him, the crown of the Roman confessors descending.": "ロマの輔祭が鎖の中でハリストスを告白し、その同殉者と王女アルテミヤがその周りに集まり、ロマの宣信者の冠が降る。",
    "A deacon of the Near Caves at his fast, the lamp of the Egyptian Macarius shining upon his namesake's exploit.": "近隔洞窟の輔祭がその斎にあり、エジプトのマカリイの燈がその同名者の功に輝く。",
    "A deacon of the Near Caves with censer and lifted hands, every petition granted, the martyr's crown above his diaconal orarion.": "近隔洞窟の輔祭が振香炉と上げた手とともにあり、あらゆる願いが聴かれ、その輔祭の帯の上に致命者の冠がある。",
    "A deacon of the caves standing at prayer on the ambo, demons fleeing from the sick brought to him.": "洞窟の輔祭が説教台で祈って立ち、彼のもとへ連れられた病者から悪魔が逃げる。",
    "A deacon of the first seven with the vessels of service, the stones of Stephen's day falling upon the whole company.": "最初の七人の一人たる輔祭が奉事の器とともにあり、ステファンの日の石が群れ全体の上に落ちる。",
    "A deacon on the ambo with a scroll, the Theotokos above giving him the scroll to eat.": "説教台の輔祭が巻物を持ち、上の生神女がその巻物を食べるよう与える。",
    "A deacon upon a gridiron, angels filling his prison with light.": "鉄の格子の上の輔祭、その獄を光で満たす天使ら。",
    "A deacon with severed tongue still praising God, a child-martyr beside him, a prison rope above.": "舌を切られてなお神を讃える輔祭、その傍らの少年の致命者、上の獄の縄。",
    "A deacon with the harp of hymnody, tears on his face and the Lenten prayer on his scroll, the schools of Nisibis and Edessa singing behind him.": "輔祭が讃詠の竪琴を持ち、その顔に涙があり、その巻物に斎の祈りがあり、ニシビとエデッサの学校がその後ろで歌う。",
    "A deacon-bishop standing unharmed in a red-hot furnace, the crown descending upon him through the flames.": "輔祭にして主教が赤熱した炉の中に害なく立ち、炎を通してその上に冠が降る。",
    "A deacon-martyr in the sticharion holding a censer and a cross, stones at his feet.": "スティハリを着た致命者たる輔祭が振香炉と十字架を持ち、その足下に石がある。",
    "A deaconess in a maphorion holding a scroll, sometimes shown with Saint John Chrysostom.": "マフォリオンを着た女輔祭が巻物を持ち、時に聖金口イオアンとともに描かれる。",
})

TEXT.update({
    "A deaconess of Nisibis among the consecrated women of her founding, the Scriptures open in her hands, the daughters of the border city gathered into one prayer.": "ニシビの女輔祭が自ら興した献身の婦人たちの中にあり、その手に聖書が開かれ、辺境の市の娘らが一つの祈りに集められる。",
    "A deaconess with lifted hands, the idol of Apollo shattered behind her, her converted torturers crowned beside her, a lion at her feet.": "手を上げた女輔祭、その後ろで砕かれたアポロンの偶像、その傍らで冠を受けた改宗した責め手たち、その足下の獅子。",
    "A deported bishop with his presbyter and deacon and the long column of captives behind them, the sun of Persia refused its worship, the whole caravan crowned.": "移送された主教がその長老と輔祭、その後ろの長い捕虜の列とともにあり、ペルシャの太陽が礼拝を拒まれ、隊列のすべてが冠を受ける。",
    "A deposed archbishop of Novgorod in monastic simplicity at the Trinity Lavra, his omophorion laid aside, his forgiveness extended and received.": "低められたノヴゴロドの大主教が三位一体のラヴラで修道の質素の中にあり、その肩衣は置かれ、その赦しが与えられまた受けられる。",
    "A desert abbot by the Jordan drawing a thorn from a lion's paw, the lion tending the monastery donkey, and lying dead upon its master's grave.": "イオルダンのほとりの荒野の修道院長が獅子の足から棘を抜き、その獅子が修道院の驢馬を守り、主人の墓の上に死んで伏す。",
    "A desert elder gripping the bridle of the emperor Valens on the march, the fire of Adrianople foretold behind him, the first monastery of the City rising at his word.": "荒野の長老が行軍中の皇帝ワレントの手綱を掴み、その後ろにアドリアノポリの火が予告され、その言葉によって市の最初の修道院が立つ。",
    "A desert father of the first generation, his cell among his companions', the sand smoothing every record but the crown.": "最初の世代の荒野の父、その庵は同伴者たちの庵の中にあり、砂が冠のほかあらゆる記録を消し去る。",
    "A desert monk at the walls of the great city, healing a blind youth, his cave-shrine at Loutraki shown above.": "大いなる市の城壁のほとりの荒野の修道士が盲目の若者を癒し、上にルトラキのその洞窟の棺が示される。",
    "A desert mother teaching a circle of women in a tomb-cell, fire kindling through smoke in her open hand.": "荒野の母が墓の庵で婦人たちの輪を教え、その開いた手の中で煙を通して火が燃え上がる。",
    "A desert-dweller of the northern forests in the schema, a small cell among pines behind him.": "大形を着た北の森の荒野の住人、その後ろの松の中の小さな庵。",
    "A dignified elder of the Sanhedrin, sometimes shown at the burial of Christ bearing myrrh, holding a cross.": "尊ぶべきシネドリオンの長老、時にハリストスの埋葬で香を携えて描かれ、十字架を持つ。",
    "A dignitary in armor and cloak of office, holding a cross, a great stone above him.": "甲冑と職の外衣を着た高官が十字架を持ち、その上に大きな石がある。",
    "A disciple of Pachomius carrying on the common life, the virtue that earned him the name Sanctified shining in the ordered ranks of the Tabennisiot monks.": "共住の生活を継ぐパホミイの弟子、彼に成聖の名を得させた徳がタヴェニシイの修道士たちの整った列に輝く。",
    "A disciple of Saint Sergius carrying logs on foot through the stream to build his monastery, the house of Peshnosha rising from the marsh, the tradition of Radonezh planted anew.": "聖セルギイの弟子が自らの修道院を建てるため徒歩で流れを渡って丸太を運び、ペシュノシャの修道院が沼から立ち上がり、ラドネジの伝統が新たに植えられる。",
    "A disciple of Saint Sergius set by Metropolitan Alexis over the new monastery of the Savior, the Icon Not-made-by-hands above the gate, the house that would shelter Andrei Rublev.": "府主教アレクシイによって新しい救世主修道院の上に立てられた聖セルギイの弟子、門の上の人手ならざる聖像、後にアンドレイ・ルブリョフを匿うことになる修道院。",
    "A disciple of Saint Varlaam of Khutyn who chose purity from his youth, founding a monastery in the wilderness of the Robeika, a bright lamp of Great Novgorod.": "若き時より清さを選んだフツィニのワルラアムの弟子が、ロベイカの荒野に修道院を建て、大ノヴゴロドの明るい燈となる。",
    "A disciple of Saint Varlaam of Khutyn withdrawing to the shore of Lake Dymskoye, an iron cap upon his head, the monastery rising in the wilderness he hallowed.": "フツィニのワルラアムの弟子がディムスコエ湖の岸へ退き、その頭に鉄の帽子を戴き、彼が聖とした荒野に修道院が立つ。",
    "A disciple of Sergius deep in the Obnora forests, the peasant who found him kneeling for a blessing, the grove of his retreats standing behind the monastery the crowds compelled.": "オブノラの森の奥のセルギイの弟子、彼を見つけて祝福を求めて跪いた農夫、群衆が強いた修道院の後ろに立つその隠遁の林。",
    "A disciple of Sergius planting the Forerunner's monastery by the iron bogs of Kostroma, the wilderness lineage of the Trinity carried north in one obedient life.": "セルギイの弟子がコストロマの鉄の沼のほとりに前駆の修道院を植え、三位一体の荒野の系譜が一つの従順な生涯によって北へ運ばれる。",
    "A disciple of the great Alexander founding a hermitage on the neck of land between two lakes, the Dormition church small among the Karelian pines.": "大いなるアレクサンドルの弟子が二つの湖の間の地峡に隠居所を建て、カレリヤの松の中に小さな就寝の聖堂がある。",
    "A disheveled ascetic in rags feigning folly, blessing, his companion John shown as a desert hermit.": "ぼろをまとった乱れた髪の修行者が愚を装って祝福し、その同伴者イオアンが荒野の隠者として描かれる。",
    "A dying priest stretching his hand toward the deacon who will not forgive, the angel with the flaming spear between them, one man rising healed and one falling dead.": "死にゆく司祭が赦そうとしない輔祭へ手を伸ばし、その間に火の槍を持った天使があり、一人は癒されて起き、一人は死んで倒れる。",
    "A family of martyrs, a father, mother, and two sons, holding crosses.": "致命者の家族、父、母、二人の子が十字架を持つ。",
    "A faster of the Caves at his rule of prayer, bread and water in small measure beside him.": "洞窟の斎の者がその祈りの規則にあり、その傍らに少しの麺麭と水がある。",
    "A faster of the Caves at his small bread and water, the appetite mastered like a broken horse, the lightness of the fasting spirit shining through the thinned body.": "洞窟の斎の者がその少しの麺麭と水にあり、馴らされた馬のように抑えられた食欲、痩せた体を通して輝く斎の霊の軽さ。",
    "A faster of the Near Caves, his face bright with abstinence, bread and water his whole table.": "近隔洞窟の斎の者、その顔は節制によって明るく、麺麭と水がその食卓のすべてである。",
    "A father and his young deacon-son together in the fire and the cauldron at Iconium, crowned in one confession.": "父と輔祭たるその若い子がイコニヤで火と釜の中にともにあり、一つの信仰告白によって冠を受ける。",
    "A father and his young son holding crosses, standing before a pagan idol.": "父とその若い子が十字架を持ち、異教の偶像の前に立つ。",
    "A father, mother, and son holding crosses together.": "父、母、子がともに十字架を持つ。",
    "A first bishop receiving his charge from the hand of the Apostle Paul, the young church of Seleucia gathered at his teaching.": "最初の主教が使徒パウェルの手からその務めを受け、セレウキヤの若い教会がその教えのもとに集まる。",
    "A first secretary of the empire in patriarchal vestments, the Seventh Ecumenical Council assembled at his word, the icons held up restored, the emperor's unlawful marriage refused his blessing.": "総主教の祭服を着た帝国の第一書記、その言葉によって集められた第七全地公会、回復されて掲げられた聖像、その祝福を拒まれた皇帝の不法の婚姻。",
    "A first-century bishop in the omophorion holding a Gospel book, sometimes with the Apostle Peter.": "肩衣を着た一世紀の主教が福音書を持ち、時に使徒ペトルとともにある。",
    "A fisherman-bishop healing the sick of the Hellespont, the demon fleeing his offered hospitality, idol temples falling and churches rising behind him.": "漁師たる主教がゲレスポントの病者を癒し、彼が差し出した宿から悪魔が逃げ、その後ろで偶像の宮が倒れ聖堂が立つ。",
    "A flute player casting down his pipes before the altar of the idols, the governor and his guards converted behind him, the sea receiving the last martyrs.": "笛吹きが偶像の祭壇の前に自らの笛を投げ捨て、その後ろで総督と衛兵が改宗し、海が最後の致命者たちを受ける。",
    "A fool for Christ in a brushwood hut in the Rostov marsh, mockery and cold about him, the gift of prophecy shining through his feigned folly, the Ascension church rising on the waters over his rest.": "ロストフの沼の柴の小屋の中のハリストスの故の佯狂者、その周りの嘲りと寒さ、装った愚を通して輝く預言の賜物、その安息の上に水の上に立つ昇天の聖堂。",
    "A fool for Christ of Ustyug in rags upon the hot stones of the oven, feigning madness by day and praying by night, the gift of prophecy shining beneath his poverty.": "炉の熱い石の上のぼろをまとったウスチュグのハリストスの故の佯狂者、昼は狂を装い夜は祈り、その貧しさの下に輝く預言の賜物。",
    "A fool in rags offering raw meat to the tsar in Lent, the city of Pskov standing unburned behind him, the Trinity cathedral receiving his body among the princes.": "ぼろをまとった佯狂者が斎の間に皇帝に生肉を差し出し、その後ろに焼かれずに立つプスコフの市があり、三位一体の大聖堂が公らの中にその体を受ける。",
    "A former courier of the emperor in a tomb-cell above Antioch, one borrowed book his library, no bed and no lamp his furnishings.": "アンティオキヤの上の墓の庵にある皇帝のかつての使者、借りた一冊の書がその蔵書のすべてであり、寝台も燈もその調度のすべてである。",
    "A former equerry holding his martyred brother's head, the Boris and Gleb monastery of Torzhok rising behind him, the hospice door open to travelers.": "かつての馬丁が致命した兄の首を持ち、その後ろにトルジョクのボリスとグレブの修道院が立ち、旅人に開かれた宿の戸。",
    "A former merchant in monastic habit, a purse laid aside at his feet, the caves behind him.": "修道服を着たかつての商人、その足下に置かれた財布、その後ろの洞窟。",
})

TEXT.update({
    "A former pagan priest and his kinsmen confessing Christ at Ancyra, converted by the constancy of the martyrs, crowned together for the faith.": "かつての異教の祭司とその親族がアンキラでハリストスを告白し、致命者たちの堅固さによって改宗し、信仰のためにともに冠を受ける。",
    "A former slave in a bishop's omophorion, the little epistle of Philemon in his hands, the chains of his first flight and his last confession joined into one crown.": "主教の肩衣を着たかつての奴隷、その手にフィレモンへの小さな書簡があり、最初の逃亡の鎖と最後の告白の鎖が一つの冠に結ばれる。",
    "A former soldier turned monk copying books and turning wood at his lathe, in great poverty, refusing the priesthood out of humility, the monastery of Lukhov rising after him.": "修道士となったかつての兵士が大いなる貧しさの中で書を写し轆轤で木を挽き、謙遜から司祭職を拒み、その後にルホフの修道院が立つ。",
    "A former tax-collector in penitential chains upon his pillar, the words of Isaiah that broke his heart shining above, the healings of the great penitent flowing from his cell.": "かつての収税人がその柱の上で痛悔の鎖にあり、その心を砕いたイサイヤの言葉が上に輝き、大いなる痛悔者の癒しがその庵から流れ出る。",
    "A former tutor of emperors in a palm-plaiter's rags, his eyes worn with weeping, the three words of his rule shining about him: flee, be silent, be still.": "皇帝らのかつての師が棕櫚を編む者のぼろをまとい、その目は涙に衰え、その規則の三つの言葉がその周りに輝く。逃れよ、黙せよ、静まれ。",
    "A founder bearing the Konevskaya icon from Athos to the island of Konevets, the monastery rising on Lake Ladoga, the pagan idol-rock of the island hallowed by the Mother of God.": "アトスからコネヴェツの島へコネフスカヤの聖像を運ぶ創立者、ラドガ湖に立つ修道院、生神女によって聖とされた島の異教の偶像の岩。",
    "A founder of Athos beholding a column of light rising from the cliff, the monastery of the Forerunner built at that place, the chrysobull of the emperor in his hand.": "アトスの創立者が崖から立ち上る光の柱を見、その所に前駆の修道院が建てられ、その手に皇帝の金印勅書がある。",
    "A founder of Torzhok holding the head of his martyred brother, the Boris and Gleb monastery rising behind him, his incorrupt relics uncovered and glorified.": "トルジョクの創立者が致命した兄の首を持ち、その後ろにボリスとグレブの修道院が立ち、その朽ちざる聖遺物が発見され讃えられる。",
    "A founder of the Onega island with the Nativity church rising behind him, the desolate rock of Palii filled with the brethren his holiness drew across the water.": "オネガの島の創立者、その後ろに立つ降誕の聖堂、その聖性が水を越えて引き寄せた兄弟たちで満たされたパリイの荒れた岩。",
    "A founder of the Vologda forests with brush and panel writing an icon, the monastery of Glushitsa rising behind, the desert of the north filled with his disciples.": "ヴォログダの森の創立者が筆と板を持って聖像を書き、後ろにグルシツァの修道院が立ち、北の荒野がその弟子たちで満たされる。",
    "A founder of the Vologda forests with the rule of his monastery in hand, the desert of Komel filled with the cells of his disciples, the multitude he enlightened gathered about their teacher.": "ヴォログダの森の創立者が手にその修道院の規則を持ち、コメリの荒野がその弟子たちの庵で満たされ、彼が啓蒙した群衆がその師の周りに集まる。",
    "A founder of the northern forests with his fellow Cyril, the Ferapontov monastery rising by the White Lake and the Luzhetsky at Mozhaisk, the desert settled by his labors.": "北の森の創立者がその同伴者キリルとともにあり、白湖のほとりにフェラポントフ修道院、モジャイスクにルジェツキイが立ち、その労苦によって荒野が住まわれる。",
    "A frail young monk handing his own will piece by piece to his elder, the icon of judgment that converted him behind, the great ascetics making room for him among the crowned.": "弱く若い修道士がその意志を一つずつ長老に手渡し、彼を改宗させた審判の聖像が後ろにあり、大いなる修行者たちが冠を受けた者の中に彼のために場を空ける。",
    "A fuller with the cross painted openly upon his door, a stone and the sea awaiting him.": "戸の上に十字架を公然と描いた漂白工、彼を待つ石と海。",
    "A gathering of the North American saints, Herman of Alaska, Innocent, Tikhon and others, against the American land, with the Theotokos above.": "北アメリカの聖人の会衆、アラスカのゲルマン、インノケンティイ、ティーホンその他が、アメリカの地を背に、上に生神女とともにある。",
    "A gaunt ascetic in a cave, then borne upright in his shrine, the possessed healed at his relics.": "洞窟の痩せた修行者、次いでその棺に直立して運ばれ、その聖遺物で憑かれし者が癒される。",
    "A gaunt faster of the Caves, and beside him his beloved brother Paisius, one grave prepared for the two.": "洞窟の痩せた斎の者、その傍らに愛する兄弟パイシイ、二人のために備えられた一つの墓。",
    "A general in full armor with the serpent slain beneath him, golden idols broken into alms in his hands, the cross of his first martyrdom and the sword of his second behind.": "完全武装の将軍、その下に打ち倒された蛇、その手に施しへ砕かれた金の偶像、後ろに最初の致命の十字架と第二の致命の剣。",
    "A general on horseback beholding a stag with the radiant Cross between its antlers.": "馬上の将軍が角の間に輝く十字架を持つ鹿を見る。",
    "A gentle archbishop of Chernihiv with the Gospel, schools and restored monasteries behind him, his incorrupt relics radiant beneath.": "福音書を持つチェルニゴフの柔和な大主教、その後ろの学校と再建された修道院、その下に輝く朽ちざる聖遺物。",
    "A gentle hegumen among his brethren, the gift of wonders resting on a life of hidden obedience, the icon of Christ held fast.": "兄弟たちの中の柔和な修道院長、隠れた従順の生涯の上に留まる奇跡の賜物、固く保たれたハリストスの聖像。",
    "A giant of fearsome countenance bearing the Child who carries the world, the flowering staff in his hand, the soldiers and the two women he converted gathered as his first harvest.": "世を担う幼子を負う恐るべき相の巨人、その手の花咲く杖、その最初の収穫として集められた彼が改宗させた兵士と二人の婦人。",
    "A girl of thirteen with a lamb at her side, her loosened hair and a mantle of light covering her, the sword and the unharmed flame of her double contest behind.": "傍らに子羊を置く十三歳の少女、解かれた髪と彼女を覆う光の外衣、その二重の戦いの剣と焼かぬ炎が後ろにある。",
    "A girl of twelve confessing Christ before the governor, the heated rods and the flail before her, crowned as the bride of Christ, the young martyr of Byblos.": "総督の前でハリストスを告白する十二歳の少女、その前の熱した棒と鞭、ハリストスの花嫁として冠を受けるビブロスの若い致命女。",
    "A grand duchess in royal robes, or in the monastic veil, holding a model of a church.": "王の衣を着た、あるいは修道の被り物をかぶった大公妃が聖堂の像を持つ。",
    "A grand princess in royal robes over a hair shirt and chains, the Ascension monastery of the Kremlin rising by her gift, a blind man receiving his sight at the hem of her garment.": "毛衣と鎖の上に王の衣を着た大公妃、その施しによって立つクレムリの昇天修道院、その衣の裾で視力を受ける盲人。",
    "A gray-haired prophet with rounded beard, his scroll proclaiming the judgment of Edom.": "丸い髭をなす白髪の預言者、エドムへの審判を告げるその巻物。",
    "A great assembly of monastic saints in tiers about Saint Anthony, the Lavra and its caves beneath them.": "アントニイを囲んで段をなす修道の聖人の大いなる集まり、その下のラヴラとその洞窟。",
    "A great hermit of the Egyptian desert rapt in the vision of Christ, his long fasts and his prayer for the fallen made visible, the glory of the desert fathers upon him.": "ハリストスの幻に魅せられたエジプトの荒野の大隠者、その長い斎と堕ちた者のための祈りが目に見え、荒野の父たちの栄光がその上にある。",
    "A great lady of Justinian's court hidden as the eunuch monk of Scetis, Abba Daniel keeping her secret, the cave-cell of twenty-eight years opening at last upon her repose.": "スキトの宦官の修道士として隠れたユスティニアンの宮廷の貴婦人、その秘密を守るアヴヴァ・ダニイル、その永眠でついに開かれる二十八年の洞窟の庵。",
    "A great man of Novgorod laying aside the honors of his office to take the monastic habit, the monastery of the Vaga rising from his lands, his last years given wholly to God.": "ノヴゴロドの高貴な人が修道服を取るためその職の名誉を捨て、その領地からヴァガの修道院が立ち、その最後の年を全く神に献げる。",
    "A great martyr with a small vessel of medicine, prison doors open behind her, the four pillars and the fire of her end beneath her feet.": "小さな薬の器を持つ大致命女、その後ろに開かれた獄の戸、その足下にその終わりの四つの柱と火。",
    "A great prince fallen at the Sit river among his warriors, the burning cathedral of Vladimir holding his family behind him, his head restored to his body in the grave.": "シチ河でその戦士たちの中に倒れた大公、その後ろに家族を収めた燃えるウラジーミルの大聖堂、墓の中で体に返されたその首。",
    "A great princess in a nun's habit, the crown she lost laid aside, healings flowing from her tomb at the Protection convent.": "修道女の衣を着た大公妃、失った冠は脇に置かれ、庇護修道院のその墓から癒しが流れる。",
    "A grieving father taking counsel of a veiled monk who is his own lost daughter, the revelation at her deathbed, the father finishing his days in her cell.": "悲しむ父が被り物をかぶった修道士に助言を求めるが、それは自らの失った娘であり、その臨終での啓示、その庵で日を終える父。",
    "A group of Slavic bishops and priests holding Gospel books and scrolls in Slavonic, Clement in the omophorion.": "福音書とスラヴ語の巻物を持つスラヴの主教と司祭の一団、肩衣を着たクリメント。",
    "A group of monk-martyrs holding crosses, illumined by light, before the desert monastery of David Gareji.": "十字架を持つ致命した修道士の一団が光に照らされ、ダヴィド・ガレジの荒野の修道院の前にある。",
    "A herdsman of Tekoa called from his flock and his sycamore figs to prophesy at Bethel, the plumb line of God's judgment in his hand, crying for justice to roll down like waters.": "フェコアの牧者がその群れと桑の実からベテルで預言するよう召され、その手に神の審判の下げ振りがあり、正義が水のように流れるようにと叫ぶ。",
    "A hermit by the Pshinja meeting a hunter who would be emperor, the monastery of his relics rising by the river in fulfillment.": "プシニャのほとりの隠者が皇帝となる狩人に会い、その成就として河のほとりにその聖遺物の修道院が立つ。",
    "A hermit dwelling in the branches of an almond tree by the wall of Thessaloniki, and holding live coals unharmed in his hands before the ruler, a wonder of the ascetic life.": "テッサロニキの城壁のほとりの巴旦杏の枝に住む隠者が、支配者の前で燃える炭を手に害なく持ち、修行の生活の奇跡となる。",
})

TEXT.update({
    "A hermit dwelling in the hollow of a great oak by the river Vepreika, the deep forest about him, the hermitage of Kaluga rising from his solitude.": "ヴェプレイカ河のほとりの大きな樫の洞に住む隠者、その周りの深い森、その独居から立つカルガの隠居所。",
    "A hermit in a mountain wilderness fed by heaven, his relics borne in procession by tsars and hierarchs.": "天から養われる山の荒野の隠者、皇帝と主教らによって行列で運ばれるその聖遺物。",
    "A hermit in a roofless stone enclosure, serpent bites healed by the sign of the cross, the dwellings of the blind beside his wall and their psalmody rising like a second sky.": "屋根のない石の囲いの中の隠者、十字架の印によって癒される蛇の咬み傷、その壁の傍らの盲人の住まいと第二の天のように立ち上るその聖詠。",
    "A hermit in a single garment of rough hair, the capital's comforts renounced within sight of its walls, the myrrh of his relics answering the harshness of his shirt.": "粗い毛の一枚の衣を着た隠者、その城壁の見えるところで捨てられた都の慰め、その毛衣の厳しさに応えるその聖遺物の滲香。",
    "A hermit in a tomb-cell dividing his belt in two for a sick child, healings flowing from the woven half as from the Apostles' garments.": "墓の庵の隠者が病んだ子のためにその帯を二つに分け、使徒の衣からのように編んだその半分から癒しが流れる。",
    "A hermit in a worn habit, chains visible beneath, praying in a forest chapel.": "擦り切れた衣を着た隠者、その下に見える鎖、森の礼拝堂で祈る。",
    "A hermit in iron chains and hair shirt above the Cilician shore, sailors on a storm-tossed sea calling on the God of Theodosius.": "キリキヤの岸の上の鉄の鎖と毛衣をまとった隠者、荒れる海の船人らがフェオドシイの神を呼ぶ。",
    "A hermit naked to the frost and the burning sun in a stone cave above the Bistrița, sixty winters of snow around his unshaken prayer.": "ビストリツァの上の石の洞窟で霜と灼く日に裸なる隠者、その揺るがぬ祈りの周りの六十の冬の雪。",
    "A hermit of the Bithynian Olympus radiant with lifelong purity, the unclean spirits fleeing a vessel they never entered.": "生涯の清さに輝くビフィニヤのオリンポスの隠者、一度も入らなかった器から逃げる汚れた霊。",
    "A hermit of the Drenica forest with the healed child of the despot before him, the monastery of Devich rising in thanksgiving over his cell, the Serbian wilderness keeping his relics.": "その前に癒されたデスポトの子を置くドレニツァの森の隠者、その庵の上に感謝のうちに立つデヴィチの修道院、その聖遺物を守るセルビヤの荒野。",
    "A hermit of the Irish valley of the two lakes at prayer with arms outstretched, a bird nesting in his hand, the great monastery of Glendalough rising from his cell.": "手を広げて祈るイルランジヤの二つの湖の谷の隠者、その手に巣を作る鳥、その庵から立つグレンダロフの大いなる修道院。",
    "A hermit of the Red Mountain by the Vetluga river at prayer in his forest solitude, the wilderness hallowed by his long ascesis, the monastery rising after him.": "ヴェトルガ河のほとりの赤い山の隠者がその森の独居で祈り、その長い修行によって聖とされた荒野、その後に立つ修道院。",
    "A hermit of the Seliger island who never lay down to sleep, leaning on his hooks in prayer, his incorrupt relics uncovered and enshrined on the island of his labors.": "決して横になって眠らなかったセリゲルの島の隠者が祈りの中でその鉤に寄りかかり、その労苦の島で発見され安置されたその朽ちざる聖遺物。",
    "A hermit of the Vologda forests founding his monastery on the river Kushta, the desert by Lake Kubena filled with prayer, the tradition of the Thebaid of the North carried on.": "クシタ河にその修道院を建てるヴォログダの森の隠者、祈りに満ちたクベナ湖のほとりの荒野、受け継がれた北のフィヴァイダの伝統。",
    "A hermit of the holy mountain of Kyminas holding a sealed letter, its answer already written beside it.": "封をした手紙を持つキミナの聖なる山の隠者、その傍らにすでに書かれたその答え。",
    "A hermit of the trans-Volga forests raising the church of the Transfiguration on the Sokhot river, brethren gathering to the light in the wilderness.": "ソホト河に変容の聖堂を建てるヴォルガの向こうの森の隠者、荒野の光に集まる兄弟たち。",
    "A hermit on a bare Syrian height, iron upon his body and the sky for his roof, a quarter century of unwitnessed prayer.": "シリヤの裸の高地の隠者、その体の鉄と屋根としての空、証人なき四半世紀の祈り。",
    "A hermit on a forest hill among the northern people, the Theophany church rising at his life's end.": "北の民の中の森の丘の隠者、その生涯の終わりに立つ神現の聖堂。",
    "A hermit on the myrtle-covered mountain of the Peloponnese, his cell unseen and his prayer unceasing, the name alone carried down.": "ペロポネソスの桃金嬢に覆われた山の隠者、その庵は見えずその祈りは絶えず、名のみが伝えられる。",
    "A hermit reading by uncreated light in a tiny cell, a serpent destroyed by the sign of the Cross.": "狭い庵で創られざる光によって読む隠者、十字架の印によって滅ぼされた蛇。",
    "A hermit speaking through the small window of his mountain cell, crowds below singing the refrains he taught them, the council of Chalcedon honoring his confession.": "山の庵の小さな窓から語る隠者、下で彼が教えた句を歌う群衆、その信仰告白を讃えるハルキドンの公会。",
    "A hermit standing in fire against temptation, dolphins bearing him from his island, Zoe in her Bethlehem repentance and Photina on the sea rock, three crowns from one battle.": "誘惑に抗して火の中に立つ隠者、その島から彼を運ぶ海豚、ベツレヘムの痛悔にあるゾエと海の岩の上のフォティナ、一つの戦いからの三つの冠。",
    "A hermit upright in death, supported on the wooden crutches on which he slept standing, his island hermitage behind.": "死して直立する隠者が立ったまま眠った木の鉤に支えられ、その島の隠居所が後ろにある。",
    "A hermit-monk in the schema by a spring in the marshy forest, bears near him, a pillar of fire above.": "沼の森の泉のほとりの大形を着た隠修の修道士、その近くの熊、上の火の柱。",
    "A hermit-monk, once a soldier, at prayer on a mountain, sometimes shown with the Prophet Elijah.": "かつて兵士であった隠修の修道士が山で祈り、時に預言者イリヤとともに描かれる。",
    "A hierarch of Kazan with a child's alphabet book in hand, a prison cell with light streaming through its opened door behind him.": "手に子供の字引を持つカザンの聖德者、その後ろの開かれた戸から光の差し込む獄の庵。",
    "A hierarch of Khakhuli in the gorge of Tao, the translator's pen and the calligrapher's hand at rest, the golden stream of his preaching earning him the Chrysostom's own name.": "タオの峡谷のハフリの聖德者、休らう翻訳者の筆と書家の手、金口自身の名を彼に得させたその説教の金の流れ。",
    "A hierarch sheltering a fugitive within his monastery gate, the murdered brother's blood crying from the earth and the saint's hand raised in absolution over the murderer.": "修道院の門の内に逃亡者を匿う聖德者、地から叫ぶ殺された兄の血と、殺害者の上に赦しのために上げられた聖人の手。",
    "A hierarch with an anchor, the sea parting to reveal his tomb, Cyril and Methodius bearing his relics.": "錨を持つ聖德者、その墓を現すために分かれる海、その聖遺物を運ぶキリルとメフォディイ。",
    "A hierarch with the scroll of the Five Theological Orations, the little chapel of the Anastasia glowing behind him, the council throne laid down at his feet.": "五つの神学講話の巻物を持つ聖德者、その後ろに輝くアナスタシヤの小聖堂、その足下に置かれた公会の座。",
    "A hierarch with the scroll of the Life of Moses, Sinai's darkness luminous above him, his brother Basil and sister Macrina beside his formation.": "モイセイの生涯の巻物を持つ聖德者、その上に輝くシナイの闇、その形成に寄り添う兄ワシリイと姉マクリナ。",
    "A hierarch-ruler of Samtskhe before the ancient Atskuri Icon of the Mother of God, the see of the Apostle Andrew in his care, the lives of the saints flowing from his pen.": "古きアツクリの生神女の聖像の前のサムツヘの聖德者にして支配者、その配慮のもとの使徒アンドレイの教区、その筆から流れる聖人伝。",
    "A hieromonk bound to the mulberry tree of his monastery courtyard, the flames and nails of his long passion upon him, the abbess of five centuries later uncovering his fragrant relics in the ruins.": "修道院の庭の桑の木に縛られた修道司祭、その長い受難の炎と釘がその上にあり、五百年後の女修道院長が廃墟でその香る聖遺物を発見する。",
    "A hieromonk of the Far Caves anointing the sick with oil, healings flowing from the threefold rule of prayer, fasting, and unction.": "遠隔洞窟の修道司祭が病者に油を塗り、祈りと斎と傅油の三重の規則から癒しが流れる。",
    "A hieromonk of the Skete of Saint Anne preaching Christ openly before the Ottoman power, the tortures of Serres upon him, the Holy Mountain sending its own into the harvest of the new martyrs.": "聖アンナの隠居所の修道司祭がオスマンの権力の前で公然とハリストスを説き、セルライの責苦がその上にあり、聖なる山が新致命者の収穫に自らの者を送る。",
    "A hieromonk of the western sea raising a church at Braunton, the children of a king at his knee, Rome and Brittany on his pilgrim road behind.": "西の海の修道司祭がブラウントンに聖堂を建て、その膝に王の子らがあり、その後ろの巡礼の道にロマとブレタニヤがある。",
    "A hieromonk slain at the altar with the chalice before him, the burning monastery of the far north behind, one hundred and fifteen martyrs crowned around.": "その前に爵を置いて祭壇で殺された修道司祭、後ろの遠い北の燃える修道院、周りで冠を受ける百十五人の致命者。",
    "A hieromonk with censer in the caves, the reposed saints answering his paschal greeting.": "洞窟で振香炉を持つ修道司祭、その復活祭の挨拶に答える眠れる聖人たち。",
    "A hieromonk-hermit at prayer in his cave on Măgura Tazlăului, thirty disciples about the little altar he raised, the frost conquered beneath his knees.": "メグラ・タズレウルイのその洞窟で祈る隠修の修道司祭、彼が建てた小さな祭壇の周りの三十人の弟子、その膝の下に克たれた霜。",
    "A hieromonk-missionary with a cross before the peoples of Alaska, the waters of Iliamna behind him.": "アラスカの諸民の前で十字架を持つ宣教の修道司祭、その後ろのイリアムナの水。",
})

TEXT.update({
    "A holy virgin of Rome confessing Christ under torture, crowned with martyrdom, her relics borne over the sea to Sicily to be the treasure of a city.": "責苦の下でハリストスを告白するロマの聖なる童貞女、致命によって冠を受け、市の宝となるべく海を越えてシチリヤへ運ばれたその聖遺物。",
    "A humble elder of the northern forest with Alutiiq children about him, Spruce Island and the sea behind, the North Star above.": "アルティーク族の子らに囲まれた北の森の謙遜な長老、後ろの樅の島と海、上の北極星。",
    "A humble herdsman-monk in a cave by a river, the cathedral of Bucharest receiving his relics.": "河のほとりの洞窟の謙遜な牧者たる修道士、その聖遺物を受けるブカレストの大聖堂。",
    "A humble layman in simple dress by a river with a fishing line, a village church behind him.": "釣糸を持って河のほとりにある質素な衣の謙遜な俗人、その後ろの村の聖堂。",
    "A humble tailor by the Tura river with needle and fishing line, his coffin rising from the earth behind him, the Urals' churches gathered to his glorification.": "針と釣糸を持つトゥラ河のほとりの謙遜な仕立屋、その後ろで地から昇るその棺、その列聖に集まるウラルの聖堂。",
    "A husband and wife in monastic habits walking one road, two children's graves behind them, palms of Egypt ahead.": "修道服を着て一つの道を歩む夫と妻、その後ろの二つの子の墓、前方のエジプトの棕櫚。",
    "A husband and wife martyrs holding crosses, a prison and an infant near them.": "十字架を持つ夫と妻の致命者、その近くの獄と幼子。",
    "A husband and wife with the church in their house, a returned slave embraced as a brother, all crowned.": "その家に教会を持つ夫と妻、兄弟として抱かれた帰ってきた奴隷、皆が冠を受ける。",
    "A jailer laying the saint's chains upon his own limbs, the empty prison behind him where the angel had come, his confession before the prefect winning him the martyr's crown.": "聖人の鎖を自らの手足に掛ける獄吏、その後ろの天使が来た空の獄、その総督の前の告白が彼に致命者の冠を得させる。",
    "A king of Georgia refusing to deny Christ and embrace the faith of the conqueror, crowned with martyrdom, the defender and restorer of the churches of his land.": "ハリストスを否み征服者の信仰を受け入れることを拒むグルジヤの王、致命によって冠を受け、その地の聖堂の守護者にして再建者となる。",
    "A king raising churches and monasteries across a ravaged land, the castle church of Artanuji behind him, the assassins' swords answered by a martyr's crown.": "荒らされた地に聖堂と修道院を建てる王、その後ろのアルタヌジの城の聖堂、致命者の冠によって答えられた暗殺者の剣。",
    "A king's daughter in the tower of her girlhood, the dove with the olive branch at her window, the wheels and pits of four persecutors failing around her, the sealed tomb at Ephesus standing open and empty.": "少女の日の塔にいる王の娘、その窓辺の橄欖の枝を持つ鳩、その周りで力尽きる四人の迫害者の車輪と穴、開いて空のまま立つエフェスの封じられた墓。",
    "A laboring monk of the Near Caves at his work and prayer, the gift of wonders resting on him, his incorrupt relics honored among the fathers of the Lavra.": "その働きと祈りにある近隔洞窟の勤労の修道士、その上に留まる奇跡の賜物、ラヴラの父たちの中で崇められるその朽ちざる聖遺物。",
    "A layman distributing his goods to the poor, enduring sickness with a radiant face.": "その財を貧しき者に分ける俗人、輝く顔で病を耐える。",
    "A layman kneeling in the road begging forgiveness of a prisoner who will not give it, the crown passing at the block from the priest who denied to the friend who confessed.": "道に跪いて赦しを与えぬ囚人に赦しを乞う俗人、否んだ司祭から告白した友へ処刑の場で移る冠。",
    "A layman standing unbowed before Julian, the lioness of the arena at Caesarea awaiting his crown.": "ユリアンの前に屈せず立つ俗人、その冠を待つカイサリヤの闘技場の雌獅子。",
    "A learned bishop of Cyprus at the side of the unlettered Saint Spyridon, taught by him to despise the palace and the vineyard and to seek the treasures of heaven.": "学のない聖スピリドンの傍らにあるキプルの学識ある主教、宮殿と葡萄畑を軽んじ天の宝を求めるよう彼に教えられる。",
    "A maid of the imperial court in a fugitive's plain dress, the church of Amasea rising by her gifts, her soul taken up in peace while the tyrant's summons was still on the road.": "逃亡者の質素な衣を着た宮廷の乙女、その施しによって立つアマシヤの聖堂、暴君の召喚がなお道中にある間に平安のうちに取り上げられたその霊。",
    "A maiden of Novgorod among the city's wonderworkers, her hidden ascetic life known only to God, her incorrupt relics rising from the tomb behind the church of Florus and Laurus.": "市の成神者たちの中のノヴゴロドの乙女、神のみが知るその隠れた修行の生涯、フロルとラヴルの聖堂の後ろの墓から昇るその朽ちざる聖遺物。",
    "A maiden of Tarsus baptized by the bishop her dream revealed, the imperial marriage refused, the brazen ox glowing as her bridal chamber to Christ.": "その夢が示した主教によって洗礼を受けたタルソスの乙女、拒まれた皇帝との婚姻、ハリストスへの婚礼の部屋として赤く燃える銅の牛。",
    "A maiden of Thessalonica casting down the idol of Athena at Corinth, the wild beasts crouching harmless at her feet, an angel comforting her in her prison.": "コリンフでアテナの偶像を倒すテッサロニキの乙女、その足下に害なくうずくまる野の獣、その獄で彼女を慰める天使。",
    "A maiden of eighteen bowing to the chained confessors before the tribunal, her own seizure following her greeting, the sea of Caesarea receiving her.": "法廷の前で鎖につながれた宣信者に頭を下げる十八歳の乙女、その挨拶に続く自らの捕縛、彼女を受けるカイサリヤの海。",
    "A maiden standing in the sunlight of the pagan temple, the sign of the Cross shining on her brow, the idol of Zeus shattered and the angel descending to her prison.": "異教の宮の日の光の中に立つ乙女、その額に輝く十字架の印、砕かれたゼウスの偶像とその獄に降る天使。",
    "A man crying out from the roadside as a great company of prisoners passes, all crowned together.": "囚人の大いなる群れが通る時に道端から叫ぶ男、皆がともに冠を受ける。",
    "A man of Cana beneath his fig tree, the Lord's eye upon him before the calling, the confession of the Son of God rising at the first meeting.": "その無花果の木の下のカナの人、召される前に彼の上にある主の目、最初の出会いに立ち上る神の子の告白。",
    "A martyr amid flames, holding a cross, the city of Thessalonica behind him.": "炎の中で十字架を持つ致命者、その後ろのテッサロニキの市。",
    "A martyr amid his torments beholding a ladder to heaven and radiant men calling him to a city of light.": "その責苦の中で天への梯子と光の市へ呼ぶ輝く人々を見る致命者。",
    "A martyr beheaded by the sword, receiving his crown from Christ.": "剣によって斬られ、ハリストスからその冠を受ける致命者。",
    "A martyr enduring boiling pitch poured over him, his soul rising in glory.": "その上に注がれる煮え立つ瀝青を耐える致命者、栄光のうちに昇るその霊。",
    "A martyr holding a cross, tending to the bodies of the fallen faithful.": "十字架を持ち、倒れた信者の遺体を世話する致命者。",
    "A martyr holding a cross.": "十字架を持つ致命者。",
    "A martyr in a red-hot iron belt denouncing the apostate emperor, the cross of his final contest behind him.": "赤熱した鉄の帯をまとって背教の皇帝を責める致命者、その後ろの最後の戦いの十字架。",
    "A martyr in flames giving thanks, a spring gushing from a rock nearby.": "炎の中で感謝する致命者、近くの岩から噴き出す泉。",
    "A martyr in noble dress holding a cross, his companions around him.": "貴い衣を着て十字架を持つ致命者、その周りの同伴者たち。",
    "A martyr making the sign of the Cross, a road behind him.": "十字架の印を切る致命者、その後ろの道。",
    "A martyr of Heraclea slipping his captors on the road, the wounds of his tortures completing the sentence the executioners could not, the crown descending outside the walls.": "道で捕らえた者から逃れたイラクリヤの致命者、処刑者の果たしえなかった判決を全うしたその責苦の傷、城壁の外に降る冠。",
    "A martyr of Isauria with the Archangel Michael above him, demons sealed in clay vessels at his feet, the bridal candle of his parable in his hand.": "その上に大天使ミハイルを戴くイサヴリヤの致命者、その足下の土の器に封じられた悪魔、その手のたとえ話の婚礼の蝋燭。",
    "A martyr of Lycaonia driven along the road in sandals of nails, bound at last to a barren tree that puts forth fruit above him.": "釘の履物で道を追い立てられるリカオニヤの致命者、ついに実らぬ木に縛られ、その上でその木が実を結ぶ。",
    "A martyr of the Thebaid whose prayer held the governor's boat fast on the Nile until the judge confessed Christ, the river receiving the confessor as his crown.": "その祈りが総督の舟をナイルに留め、裁く者がハリストスを告白するまで解かなかったフィヴァイダの致命者、その冠としてその宣信者を受ける河。",
    "A martyr of the Thracian countryside beheaded for his confession, his crown descending from heaven.": "その告白のために斬られたトラキヤの田舎の致命者、天から降るその冠。",
})
