# -*- coding: utf-8 -*-
"""Korean for the vocabulary that stands beside the lives.

TEXT = {the phrase the index shows: the rendering}. The keys are the phrases
exactly as the index writes them, so a rendering cannot quietly attach itself
to the wrong saint.

A language may later declare PARTS and an expand() to assemble the compound
place-names from pieces rendered once, as the older languages do. It is an
optimisation and not a requirement: everything written in TEXT stands over
whatever expand() builds.
"""
TEXT = {
}

TEXT.update({
    "(Abibus) of Egypt": "(아비보) 이집트의",
    "(Apphianus) and Edesius (Aedesius) of Lycia": "(암피아노)와 리키아의 에데시오(아이데시오)",
    "(Eustace) the Confessor, Bishop of Bithynia": "(에우스타티오) 증거자, 비티니아의 주교",
    "(Jacob) the Presbyter, and Azadanes and Abdiesus the Deacons, of Persia": "(야고보) 사제와 부제 아자다네스와 압디에소, 페르시아의",
    "(Vadim) of Persia": "(바딤) 페르시아의",
    "(Voino-Yasenetsky), Archbishop of Simferopol and Crimea": "(보이노-야세네츠키), 심페로폴과 크림의 대주교",
    "(also called Susanna), New Martyr of Lesbos": "(수산나라고도 불림), 레스보스의 새 순교녀",
    "(tonsured David and Euphrosyne), Wonderworkers of Murom": "(수도명 다윗과 에우프로시네), 무롬의 기적행자",
    "A Cappadocian centurion bowing beneath the sword with his eyes lifted in thanksgiving, the walnut tree of the tradition behind him, the churches of Byzantium rising over his relics.": "카파도키아의 백부장이 칼 아래 몸을 굽히고 눈을 들어 감사드리며, 그 뒤에 전승의 호두나무가 있고, 그의 유물 위로 비잔티움의 성당들이 솟아오른다.",
    "A Celtic hermit of the Devon coast bearing his own severed head to the spring, the robbers behind him, crowned as a martyr among the saints of Britain.": "데번 해안의 켈트 은수자가 잘린 자기 머리를 들고 샘으로 가며, 뒤에는 강도들이 있고, 브리튼의 성인들 가운데 순교자로 관을 받는다.",
    "A Christian general casting down the temples of Galatia, his twelve tribunes and his thousands of soldiers with their wives and children crowned around him, the converted sorcerer Callinicus among them.": "갈라티아의 신전들을 무너뜨리는 그리스도인 장군, 그의 열두 천부장과 아내와 자녀를 거느린 수천의 군사가 그 둘레에서 관을 받으며, 그 가운데 회심한 마술사 칼리니코가 있다.",
    "A Christian of Alexandria standing before the tribunal to denounce its cruelty, the confession volunteered and the sword received.": "알렉산드리아의 한 그리스도인이 재판정 앞에 서서 그 잔혹함을 고발하니, 스스로 나선 고백과 받아들인 칼이 있다.",
    "A Creole-Aleut priest in vestments holding a Gospel and a cross, against an Alaskan landscape.": "제의를 입은 크레올-알류트 사제가 복음서와 십자가를 들고 알래스카의 풍경을 배경으로 서 있다.",
    "A Georgian bishop with a book and a restored church, schoolchildren and monasteries behind him.": "책을 든 조지아의 주교와 그가 다시 세운 성당, 그 뒤에 학생들과 수도원들이 있다.",
    "A Georgian commander marking his forehead with the cross in his own blood, his soldiers crowned around him.": "조지아의 장군이 자기 피로 이마에 십자가를 그으며, 그의 군사들이 둘레에서 관을 받는다.",
    "A Georgian monk in prayer before the cave monastery of Gareji in the desert hills.": "사막의 언덕에 자리한 가레지 동굴 수도원 앞에서 기도하는 조지아의 수도자.",
    "A Georgian monk-abbot holding a scroll or a book.": "두루마리나 책을 든 조지아의 수도원장 수도자.",
    "A Georgian prince and commander refusing to trample the icon of Christ before the conqueror, crowned as a great-martyr, the defender of the Georgian faith.": "정복자 앞에서 그리스도의 이콘 밟기를 거부하는 조지아의 공이자 장군, 대순교자로 관을 받은 조지아 신앙의 수호자.",
    "A Gothic congregation at worship within the burning church, twenty-six crowns rising with the smoke, the queen gathering the holy remains from the ashes.": "불타는 성당 안에서 예배드리는 고트인 회중, 연기와 함께 스물여섯 개의 관이 올라가고, 왕비가 재에서 거룩한 유물을 거둔다.",
    "A Gothic general of Rome casting down his military belt before Aurelian, seventy soldiers confessing behind him, the river receiving the wonderworking commander.": "아우렐리아누스 앞에 자기 군대 띠를 벗어 던지는 로마의 고트인 장군, 그 뒤에서 일흔 명의 군사가 고백하고, 강이 기적행자 장군을 받아들인다.",
    "A Great Prince of Kyiv with the churches of Smolensk he raised, the monastic habit he longed for held by an angel, the elder Polycarp pointing him back to his throne.": "자기가 세운 스몰렌스크의 성당들과 함께 있는 키예프의 대공, 그가 사모하던 수도복을 천사가 들고 있고, 폴리카르포 장로가 그를 그의 자리로 돌려보낸다.",
    "A Greek bishop preaching Christ to the pagan Rostov land, the first shepherd of a hostile flock, the see of Rostov founded amid the idols of the north.": "이교의 로스토프 땅에 그리스도를 전하는 그리스인 주교, 적대하는 무리의 첫 목자, 북방의 우상들 가운데 세워진 로스토프의 주교좌.",
    "A Greek iconographer of Constantinople founding the island monastery of Lake Onega, the Sophia icon he copied in his hands, the peoples of the north gathering to his light at the age of one hundred and five.": "오네가 호수의 섬 수도원을 세운 콘스탄티노폴리스의 그리스인 이콘 화가, 그가 옮겨 그린 소피아 이콘을 손에 들고, 백다섯 살에 이른 그의 빛으로 북방의 백성들이 모여든다.",
    "A Greek metropolitan enthroned at Moscow beside the shrine of Peter, standing unbowed before the khan of the Horde, the Church's charter of freedom in his hand.": "베드로의 성소 곁 모스크바 좌에 오른 그리스인 수도 대주교, 호르드의 칸 앞에 굽히지 않고 서서, 교회의 자유의 특허장을 손에 들고 있다.",
    "A Greek of Ephesus at the Apostle Paul's side, the Temple riot swirling around his innocent presence, the sickbed of Miletus and the sword of Rome completing his long companionship.": "사도 바오로 곁에 선 에페소스의 그리스인, 성전의 소요가 그의 무죄한 자리를 휘감고, 밀레토스의 병상과 로마의 칼이 그의 긴 동행을 마무리한다.",
    "A Greek prince laying aside his rank for the monastic habit, the Uchma hermitage rising on the bank of the Volga, the exile made a wonderworker in his adopted land.": "수도복을 위하여 자기 지위를 내려놓는 그리스인 공, 볼가 강가에 서는 우치마 은수처, 자기가 받아들인 땅에서 기적행자가 된 유배자.",
    "A Patriarch of Constantinople seated upright in death as in blessing, the Mgar monastery of Lubny receiving the traveler, the two worlds of Greece and Rus' joined at his throne.": "죽어서도 축복하듯 곧게 앉아 있는 콘스탄티노폴리스 총대주교, 루브니의 므가르 수도원이 나그네를 맞아들이고, 그리스와 루스의 두 세계가 그의 좌에서 만난다.",
    "A Persian noble offering his severed members one by one, each with a prayer, angels gathering his prayers.": "잘린 지체를 하나씩 기도와 함께 바치는 페르시아의 귀족, 천사들이 그의 기도를 거둔다.",
    "A Persian soldier turned monk, the captive Cross of the Lord shining before him, the waters and the sword of Bethsaloe beneath his crown.": "수도자가 된 페르시아의 군인, 사로잡힌 주님의 십자가가 그 앞에 빛나고, 그의 관 아래에 베트살로에의 물과 칼이 있다.",
    "A Roman centurion kneeling before the Apostle Peter, or vested as a bishop holding a Gospel.": "사도 베드로 앞에 무릎 꿇은 로마의 백부장, 또는 복음서를 든 주교의 제의 차림.",
    "A Roman general in armor holding a cross, his soldiers behind him, a spring at his feet.": "십자가를 든 갑옷 차림의 로마 장군, 그 뒤에 군사들이 있고, 그의 발치에 샘이 있다.",
    "A Roman maiden in flight across the sea with two servants, the convent of Saint Stephen at Mylasa, a cross of stars brighter than the sun above her repose.": "두 하녀와 함께 바다를 건너 달아나는 로마의 처녀, 밀라사의 성 스테파노 수도원, 그리고 그의 안식 위로 해보다 밝은 별들의 십자가.",
    "A Roman matron refusing the Arian rite, the fire kindled behind her, Saint Ambrose blessing from afar.": "아리우스파의 예식을 거부하는 로마의 귀부인, 그 뒤에 불이 지펴지고, 멀리서 성 암브로시오가 축복한다.",
    "A Roman noblewoman scattering deeds and treasure to the poor, thousands of freed slaves behind her, her small cell on the Mount of Olives before her.": "증서와 재물을 가난한 이들에게 흩는 로마의 귀부인, 그 뒤에 해방된 수천의 종들이 있고, 그 앞에 올리브 산의 작은 방이 있다.",
    "A Roman senator opening his house to the Apostle Peter, the household at prayer becoming a church, the greeting of the epistle shining over the door.": "사도 베드로에게 자기 집을 여는 로마의 원로원 의원, 기도하는 집안이 교회가 되고, 서간의 인사가 그 문 위에 빛난다.",
    "A Roman widow standing amid seven crowned sons, encouraging each to the contest, her own crown descending last.": "관을 쓴 일곱 아들 가운데 선 로마의 과부, 저마다를 싸움으로 격려하고, 자기 관은 마지막에 내려온다.",
    "A Russian captive in the winter night of Kazan, bound and wounded in the snow, alive at dawn with his confession unbroken.": "카잔의 겨울밤에 묶여 눈 속에 상한 러시아인 포로, 새벽에도 살아 그 고백이 꺾이지 않았다.",
    "A Russian soldier-slave at prayer in his master's stable, the Turkish household softened by his faith, his incorrupt relics glorified across the Greek world.": "주인의 마구간에서 기도하는 러시아인 종 군인, 터키인 집안이 그의 신앙에 누그러지고, 썩지 않은 그의 유물이 그리스 온 땅에서 영광을 받는다.",
    "A Serbian prince leading his army at Kosovo, choosing the kingdom of heaven over the kingdom of earth, crowned as a great-martyr, his incorrupt relics the treasure of his people.": "코소보에서 자기 군대를 이끄는 세르비아의 공, 땅의 나라보다 하늘의 나라를 택하고, 대순교자로 관을 받았으며, 썩지 않은 그의 유물이 제 백성의 보배가 되었다.",
    "A Spanish dignitary in the Great Schema, the roads of his pilgrimage from Rome to Jerusalem behind him, the Saracen sword before him.": "대수도자 품을 입은 스페인의 고관, 그 뒤에 로마에서 예루살렘까지의 순례 길이 있고, 그 앞에 사라센의 칼이 있다.",
})

TEXT.update({
    "A Swedish princess become mother of Rus, her sainted son Vladimir beside her, the crowns of France, Hungary, and Norway among her daughters, the nun's habit her final vesture.": "루스의 어머니가 된 스웨덴의 공주, 그 곁에 성인이 된 아들 블라디미르가 있고, 딸들 가운데 프랑스와 헝가리와 노르웨이의 왕관이 있으며, 수녀의 옷이 그의 마지막 예복이다.",
    "A Syrian stranger standing three days in prayer in the church of Spoleto, the garden thieves fed at his table and converted, the offered estates refused with a smiling shake of the head.": "스폴레토의 성당에서 사흘을 기도하며 서 있는 시리아의 나그네, 그의 식탁에서 먹고 회심한 정원의 도둑들, 미소로 고개를 저어 사양한 바쳐진 재산.",
    "A Tatar captive baptized and tonsured, founding a monastery on the shore of Lake Kozha in the far north, the wilderness hallowed by his prayer.": "세례를 받고 삭발한 타타르의 포로, 먼 북방 코자 호수 기슭에 수도원을 세우고, 그의 기도로 거룩해진 광야.",
    "A Yup'ik mother in a kuspuk holding a basin and towel, the northern lights above the tundra behind her.": "쿠스푹을 입은 유픽의 어머니가 대야와 수건을 들고, 그 뒤 툰드라 위로 북극광이 펼쳐진다.",
    "A barefoot ascetic in rags, blessing, at Novgorod.": "노브고로드에서 누더기를 걸치고 맨발로 축복하는 고행자.",
    "A barefoot fool in tattered clothing by a northern river, giving away what was given to him.": "북방의 강가에서 누더기를 걸친 맨발의 바보, 자기에게 주어진 것을 남에게 내어 준다.",
    "A barefoot fool-for-Christ holding a head of cabbage, at Novgorod by the river.": "노브고로드의 강가에서 양배추 한 통을 든 맨발의 그리스도를 위한 바보.",
    "A barefoot fool-for-Christ in a sheepskin holding an axe, by the river defending the city.": "양가죽을 걸치고 도끼를 든 맨발의 그리스도를 위한 바보, 강가에서 도시를 지킨다.",
    "A barefoot holy fool with long hair, holding a Psalter, of gentle and sorrowful aspect.": "긴 머리에 시편을 든 맨발의 거룩한 바보, 온화하고 슬픈 얼굴이다.",
    "A basilica at Lydda, the tomb of Saint George within, hierarchs consecrating the church.": "리다의 대성당, 그 안에 성 게오르기의 무덤이 있고, 주교들이 성당을 축성한다.",
    "A bearded missionary priest with a traveler's bag, the church of Jackson and the hills of California behind him.": "나그네의 봇짐을 든 수염 난 선교 사제, 그 뒤에 잭슨의 성당과 캘리포니아의 언덕이 있다.",
    "A beggar beneath the staircase of his father's palace, unknown to all his household, the finished scroll of his life clasped in his dead hand while the emperor and the pope kneel to read it.": "아버지 저택의 계단 아래 있는 걸인, 온 집안이 그를 알아보지 못하고, 죽은 손에 자기 생애를 적은 두루마리를 쥐었으며, 황제와 교황이 무릎 꿇고 그것을 읽는다.",
    "A bent elder in white on his knees upon the rock, the Theotokos of Tenderness before him, a bear at the edge of the forest clearing.": "바위 위에 무릎 꿇은 흰옷의 굽은 장로, 그 앞에 온유의 하느님의 어머니 이콘이 있고, 숲의 빈터 가장자리에 곰이 있다.",
    "A bishop alone in an emptied city awaiting the persecutors, then crucified at Perge, teaching from the cross until his voice failed into glory.": "비워진 도시에 홀로 남아 박해자들을 기다리는 주교, 이어 페르게에서 십자가에 달려 목소리가 다할 때까지 십자가에서 가르치다 영광에 들어간다.",
    "A bishop and a presbyter of Persia holding crosses, swords above them.": "십자가를 든 페르시아의 주교와 사제, 그 위에 칼이 있다.",
    "A bishop and a virgin holding crosses, broken books of sorcery burning at their feet.": "십자가를 든 주교와 동정녀, 그 발치에 마술의 책들이 부서져 불탄다.",
    "A bishop and his companions holding crosses, cast into a furnace, a soldier among them.": "십자가를 든 주교와 그 동료들이 화덕에 던져지고, 그 가운데 한 군인이 있다.",
    "A bishop and presbyter cast into a pit, angels crowning them from above.": "구덩이에 던져진 주교와 사제, 위에서 천사들이 그들에게 관을 씌운다.",
    "A bishop and theologian of Lycia with the scroll of his Banquet of the Ten Virgins, refuting the errors of Origen, crowned at the last with martyrdom.": "열 처녀의 향연 두루마리를 든 리키아의 주교이자 신학자, 오리게네스의 오류를 반박하고, 마침내 순교로 관을 받는다.",
    "A bishop answering the emperor that the Church's questions belong to the Church, the road of exile opening behind him.": "교회의 물음은 교회에 속한다고 황제에게 답하는 주교, 그 뒤로 유배의 길이 열린다.",
    "A bishop baptizing an African king, a boy captive and a royal tutor shown in the scenes of his life.": "아프리카의 왕에게 세례를 주는 주교, 그의 생애의 장면에 사로잡힌 소년과 왕실의 스승이 보인다.",
    "A bishop barring the church door to an emperor, a beehive at his feet, a scroll of his hymns in hand.": "황제에게 성당 문을 막아서는 주교, 그의 발치에 벌통이 있고, 손에 자기 찬가의 두루마리가 있다.",
    "A bishop before a fallen idol, a demon bearing a great stone altar behind him, hot springs at his feet.": "쓰러진 우상 앞에 선 주교, 그 뒤에서 마귀가 큰 돌 제단을 나르고, 그의 발치에 온천이 솟는다.",
    "A bishop before the burning temple of Marnas, the cross-guardian's keys at his belt, the Good Thief descending from the Cross in his vision, the Eudoxiana church rising over pagan Gaza.": "불타는 마르나스 신전 앞에 선 주교, 허리띠에 십자가 수호자의 열쇠를 차고, 환시 속에서 착한 강도가 십자가에서 내려오며, 이교의 가자 위로 에우독시아나 성당이 솟는다.",
    "A bishop before the emperor, pointing to the emperor's son, teaching the honor due the Son of God.": "황제 앞에서 그 아들을 가리키며 하느님의 아들께 드릴 공경을 가르치는 주교.",
    "A bishop beheaded at the altar in mid-Liturgy, twenty-eight years of tribunals and torments ranged behind him like waves, Agathangelus crowned at his side.": "성찬예배 중에 제대에서 목이 잘린 주교, 그 뒤로 스물여덟 해의 재판과 고문이 물결처럼 늘어서고, 그 곁에서 아가탕겔로가 관을 받는다.",
    "A bishop beholding the ladder to heaven with his predecessor calling from above, one hundred and twenty-eight companions ascending behind him under the Persian sword.": "하늘로 오르는 사다리를 바라보는 주교, 위에서 그의 선임자가 부르고, 페르시아의 칼 아래 백스물여덟 명의 동료가 그 뒤를 따라 오른다.",
    "A bishop by night in a plain cloak, leaving firewood at a poor widow's door, his cathedral of Belgorod behind him.": "수수한 겉옷을 입고 밤에 가난한 과부의 문 앞에 땔감을 놓아 두는 주교, 그 뒤에 벨고로드의 대성당이 있다.",
    "A bishop drinking the sorcerer's cup unharmed, the magician kneeling converted beside his cast-down instruments.": "마술사의 잔을 상함 없이 마시는 주교, 곁에서 마술사가 자기 도구를 버리고 회심하여 무릎 꿇는다.",
    "A bishop enthroned with a Gospel, the first hierarch of Jerusalem, of ascetic and venerable countenance.": "복음서를 들고 좌에 오른 주교, 예루살렘의 첫 주교이며, 고행자다운 존경할 얼굴이다.",
    "A bishop holding a Gospel, refuting heretics who shrink before his word.": "복음서를 든 주교, 그 말씀 앞에서 이단자들이 움츠러든다.",
    "A bishop holding a page of the alphabet he invented, the sacred birch of the Zyrians felled behind him, the sorcerer Pam turning from the fire and the water, a new people reading the Gospel in its own letters.": "자기가 지은 자모를 적은 낱장을 든 주교, 그 뒤에 지리안인의 신성한 자작나무가 베여 있고, 마술사 팜이 불과 물 앞에서 돌아서며, 한 새로운 백성이 제 글자로 복음을 읽는다.",
    "A bishop holding a scroll of the Creed, the Theotokos and John the Theologian appearing above, a mountain moved behind.": "신경의 두루마리를 든 주교, 위에 하느님의 어머니와 신학자 요한이 나타나고, 뒤에서 산이 옮겨진다.",
    "A bishop holding an icon of Christ against the imperial decree, the sick healed at his hands.": "황제의 칙령을 거슬러 그리스도의 이콘을 든 주교, 그의 손에서 병자들이 낫는다.",
    "A bishop holding the book of the Divine Names, the darkened sun of the Crucifixion above him.": "하느님의 이름들에 관한 책을 든 주교, 그 위에 십자가 처형의 어두워진 해가 있다.",
    "A bishop in a laborer's tunic drawing water and hauling wood at Nitria, the omophorion of Damascus folded away, heaven alone reading the monk's true rank.": "니트리아에서 일꾼의 옷을 입고 물을 긷고 나무를 나르는 주교, 다마스쿠스의 견대는 접어 두었고, 하늘만이 그 수도자의 참된 품계를 읽는다.",
    "A bishop in a mitre holding a crozier, with a gray beard and an ascetic, gentle face.": "주교관을 쓰고 목장을 든 주교, 흰 수염에 고행자다운 온화한 얼굴이다.",
    "A bishop in monastic poverty, Cernica's island monastery at one hand and the Frasinei he founded at the other, the seminary and the printing press of Ramnic behind him, his face worn bright by fasting.": "수도자의 가난 속에 있는 주교, 한 손에 체르니카의 섬 수도원이, 다른 손에 그가 세운 프라시네이가 있고, 뒤에 럼니쿠의 신학교와 인쇄소가 있으며, 그의 얼굴은 단식으로 맑게 닳았다.",
    "A bishop in the omophorion and mantle holding a book, of gentle and humble aspect.": "견대와 망토를 걸치고 책을 든 주교, 온화하고 겸손한 모습이다.",
    "A bishop in the omophorion and sakkos holding a Gospel book, with a Greek-style beard.": "견대와 사코스를 걸치고 복음서를 든 주교, 그리스식 수염을 하고 있다.",
})

TEXT.update({
    "A bishop in the omophorion blessing the waters at a river confluence, holding a cross.": "견대를 걸치고 십자가를 들고 두 강이 만나는 곳에서 물을 축복하는 주교.",
    "A bishop in the omophorion blessing, holding a Gospel, before the cathedral of Tambov.": "견대를 걸치고 복음서를 들고 축복하는 주교, 탐보프의 대성당 앞이다.",
    "A bishop in the omophorion holding a Gospel book or the scroll of his Great Canon.": "견대를 걸치고 복음서나 자기 대카논의 두루마리를 든 주교.",
    "A bishop in the omophorion holding a Gospel book, a white dove upon his head.": "견대를 걸치고 복음서를 든 주교, 그 머리 위에 흰 비둘기가 있다.",
    "A bishop in the omophorion holding a Gospel, of humble aspect.": "견대를 걸치고 복음서를 든 주교, 겸손한 모습이다.",
    "A bishop in the omophorion holding a Gospel, sometimes with a banner or before a battle.": "견대를 걸치고 복음서를 든 주교, 때로는 군기와 함께, 또는 전투를 앞두고 있다.",
    "A bishop in the omophorion holding a Gospel, the cathedral of Saints Cyril and Methodius behind him.": "견대를 걸치고 복음서를 든 주교, 그 뒤에 성 키릴로와 메토디오 대성당이 있다.",
    "A bishop in the omophorion holding an icon and a Gospel.": "견대를 걸치고 이콘과 복음서를 든 주교.",
    "A bishop in the omophorion surrounded by his ten disciples, all crowned as martyrs.": "견대를 걸치고 열 명의 제자에게 둘러싸인 주교, 모두 순교자로 관을 받았다.",
    "A bishop in the omophorion, his hands or face marked by charcoal, holding a Gospel.": "견대를 걸치고 복음서를 든 주교, 그의 손과 얼굴에 숯의 자국이 있다.",
    "A bishop in the schema and omophorion holding a Gospel, before the city of Voronezh.": "대수도자 품의 옷과 견대를 걸치고 복음서를 든 주교, 보로네시 성 앞이다.",
    "A bishop in the snows of Siberia, a school of native children beside him, the gates of China closed behind.": "시베리아의 눈 속에 선 주교, 그 곁에 원주민 아이들의 학교가 있고, 뒤에는 닫힌 중국의 문이 있다.",
    "A bishop laying aside his omophorion at the mouth of a desert gorge, the monastery of Choziba in the cliffs.": "사막 협곡의 어귀에서 견대를 벗어 놓는 주교, 절벽에 호제바 수도원이 있다.",
    "A bishop led by an angel from torture to torture and city to city, Sirmium converted behind him and Formia receiving him, the lamps of the sailors burning at his name.": "천사에게 이끌려 고문에서 고문으로, 도시에서 도시로 옮겨진 주교, 그 뒤에서 시르미움이 회심하고 포르미아가 그를 맞아들이며, 그의 이름에 뱃사람들의 등불이 타오른다.",
    "A bishop of Aegina laying down his omophorion and returning to the monastic habit, his island see behind him.": "견대를 벗어 놓고 수도복으로 돌아가는 에기나의 주교, 그 뒤에 그의 섬 주교좌가 있다.",
    "A bishop of Amasea standing between the hunted virgin and the tyrant's demand, the sea giving back his body in the fishermen's nets, the last crowns of the persecution descending as the peace of the Church dawns.": "쫓기는 동정녀와 참주의 요구 사이에 선 아마시아의 주교, 바다가 어부의 그물에 그의 몸을 돌려주고, 교회의 평화가 밝아 오면서 박해의 마지막 관들이 내려온다.",
    "A bishop of Argos measuring out grain that does not diminish, the ransomed captives returning from the sea behind him, his monastic family in Christ around the one see he consented to hold.": "줄지 않는 곡식을 되어 나누는 아르고스의 주교, 그 뒤에서 몸값을 치른 포로들이 바다에서 돌아오고, 그가 맡기를 허락한 하나의 주교좌 둘레에 그리스도 안의 수도 가족이 있다.",
    "A bishop of Benevento unharmed in the furnace, the beasts of the arena lying at his feet, Naples receiving his body and his blood, his deacons and companions crowned around him.": "화덕 속에서 상하지 않은 베네벤토의 주교, 원형 경기장의 짐승들이 그 발치에 엎드리고, 나폴리가 그의 몸과 피를 받아들이며, 그의 부제들과 동료들이 둘레에서 관을 받는다.",
    "A bishop of Bithynia holding the icon of Christ and the open Scriptures together, the road of exile behind him.": "그리스도의 이콘과 펼친 성경을 함께 든 비티니아의 주교, 그 뒤에 유배의 길이 있다.",
    "A bishop of Bithynia on the road of exile, his cathedral behind him and the icon of Christ unsurrendered before him.": "유배의 길에 선 비티니아의 주교, 그 뒤에 자기 대성당이 있고 그 앞에 내어 주지 않은 그리스도의 이콘이 있다.",
    "A bishop of Brooklyn with the map of a continent behind him, thirty parishes rising from immigrant streets, The Word in his hand, Tikhon of Moscow laying hands upon the first-consecrated of America.": "뒤에 한 대륙의 지도를 둔 브루클린의 주교, 이민의 거리에서 서른 개의 본당이 일어서고, 손에 \"말씀\"을 들었으며, 모스크바의 티혼이 아메리카에서 처음 축성된 이에게 손을 얹는다.",
    "A bishop of Catania in exile for the holy images, the icon of Christ held fast against the imperial decree.": "거룩한 형상을 위하여 유배된 카타니아의 주교, 황제의 칙령에 맞서 그리스도의 이콘을 굳게 붙든다.",
    "A bishop of Chalcedon and his fellow ascetic standing together for the icons, the see of the Fourth Council refusing the new heresy, exile shared as the cell had been.": "이콘을 위하여 함께 선 칼케돈의 주교와 그의 고행 동료, 제4차 공의회의 주교좌가 새 이단을 거부하고, 한 방을 나누었듯 유배를 나눈다.",
    "A bishop of Chalcedon defending the holy icons, his hand open to the poor, the exile that crowned his confession before him.": "거룩한 이콘을 지키는 칼케돈의 주교, 가난한 이들에게 손을 펴고, 그 앞에 그의 고백에 관을 씌운 유배가 있다.",
    "A bishop of Corinth falsely accused, the newborn infant speaking at his prayer to name its true father, the slander confounded and the saint vindicated.": "거짓 고발을 당한 코린토의 주교, 그의 기도에 갓난아이가 말하여 제 참된 아버지를 밝히고, 중상이 무너지며 성인이 무죄를 인정받는다.",
    "A bishop of Cyprus blessing a dry vine-branch that bears fruit before its time, the poor fed at his hand, the idols of the island cast down.": "때 아니게 열매 맺는 마른 포도 가지를 축복하는 키프로스의 주교, 그의 손에서 가난한 이들이 먹고, 섬의 우상들이 무너진다.",
    "A bishop of Cyprus crowned with martyrdom, his myrrh-streaming relics borne across the sea to Constantinople, the sick healed at his shrine.": "순교로 관을 받은 키프로스의 주교, 몰약을 흘리는 그의 유물이 바다를 건너 콘스탄티노폴리스로 옮겨지고, 그의 성소에서 병자들이 낫는다.",
    "A bishop of Cyprus with the nails of his torture, teaching the faithful gathered at what he thought his end, the edict of Constantine opening his prison to a few more years of shepherding.": "자기를 고문한 못을 지닌 키프로스의 주교, 자기 끝이라 여긴 자리에 모인 신자들을 가르치는데, 콘스탄티누스의 칙령이 그의 감옥을 열어 몇 해를 더 목자로 살게 한다.",
    "A bishop of Epirus striking down the great serpent at the poisoned spring, the rain descending on the parched fields at his prayer, a dead man rising from the bier to witness against the false creditor.": "독이 든 샘에서 큰 뱀을 쳐 죽이는 에피로스의 주교, 그의 기도에 마른 들에 비가 내리고, 죽은 이가 상여에서 일어나 거짓 채권자에게 맞서 증언한다.",
    "A bishop of Melitene serene under the torturers, the emperor's own order opening his prison, the confessor's crown worn through years of peace.": "고문하는 자들 아래에서 평온한 멜리테네의 주교, 황제 자신의 명이 그의 감옥을 열고, 평화의 여러 해 동안 증거자의 관을 쓴다.",
    "A bishop of Novgorod standing alone against an uncanonical council, the Caves that formed him receiving him in confinement and in death, Theodosius appearing to welcome him home.": "교회법에 어긋난 공의회에 홀로 맞선 노브고로드의 주교, 그를 길러 낸 동굴이 갇힌 그를 맞아 죽음까지 품고, 테오도시오가 나타나 그를 집으로 맞아들인다.",
    "A bishop of Pergamum standing where Satan's throne was, the brazen bull glowing behind him, the open Apocalypse naming him the faithful witness in the Lord's own voice.": "사탄의 좌가 있던 곳에 선 페르가몬의 주교, 그 뒤에서 놋쇠 황소가 달아오르고, 펼쳐진 요한 묵시록이 주님의 목소리로 그를 신실한 증인이라 부른다.",
    "A bishop of Perm baptizing the peoples of the far north, the idols of the Permians thrown down and the churches rising, the mission of Saint Stephen carried onward.": "먼 북방의 백성들에게 세례를 주는 페름의 주교, 페름인의 우상들이 무너지고 성당들이 일어서며, 성 스테파노의 선교가 이어진다.",
    "A bishop of Persia with staff of prophecy, a ruined city behind him, two disciples at his side.": "예언의 지팡이를 든 페르시아의 주교, 그 뒤에 무너진 도시가 있고, 곁에 두 제자가 있다.",
    "A bishop of Pisidian Antioch refusing the iconoclast decree, the icons standing in his churches while he goes into exile, the confessor's crown replacing the surrendered see.": "성상파괴의 칙령을 거부하는 피시디아 안티오키아의 주교, 그가 유배로 떠나는 동안 그의 성당들에는 이콘이 그대로 서 있고, 내어 준 주교좌를 증거자의 관이 대신한다.",
    "A bishop of Prusa destroying a great serpent by the sign of the Cross, preaching Christ under Julian the Apostate, crowned with martyrdom by the sword.": "십자성호로 큰 뱀을 없애는 프루사의 주교, 배교자 율리아누스 아래에서 그리스도를 전하고, 칼로 순교의 관을 받는다.",
    "A bishop of Prusa standing unharmed in the boiling spring, preaching the God who made both the healing waters and the fire of hell, his three presbyters crowned beside him.": "끓는 샘 속에 상함 없이 선 프루사의 주교, 치유의 물과 지옥의 불을 함께 지으신 하느님을 전하고, 그 곁에서 세 사제가 관을 받는다.",
    "A bishop of Rome in the omophorion holding a Gospel, with a martyr's palm.": "견대를 걸치고 복음서를 든 로마의 주교, 순교자의 종려나무 가지를 지녔다.",
    "A bishop of Rome of the age of the martyrs, shepherding his flock in the catacombs, bringing the noble and the humble alike to the faith of Christ.": "순교자들의 시대에 산 로마의 주교, 카타콤바에서 자기 무리를 돌보고, 귀한 이와 미천한 이를 한가지로 그리스도의 신앙으로 이끈다.",
    "A bishop of Rostov preaching Christ to the half-pagan land, the idols thrown down and the churches rising, the grace of wonders confirming the word of the Caves-trained shepherd.": "반쯤 이교로 남은 땅에 그리스도를 전하는 로스토프의 주교, 우상들이 무너지고 성당들이 일어서며, 기적의 은총이 동굴에서 배운 목자의 말씀을 굳혀 준다.",
})

TEXT.update({
    "A bishop of Rostov whose very funeral became a glorification, wonders flowing from his body before burial, the shepherd of the yoke-time honored as a saint from the hour of his death.": "장례 자체가 영광이 된 로스토프의 주교, 묻히기 전에 그 몸에서 기적이 흘러나오고, 멍에의 시대의 목자가 죽은 그 시각부터 성인으로 공경받는다.",
    "A bishop of Salamis with the five tongues of his learning and the Panarion of his refutations, the ascetic of the Palestinian desert crowned with the long white rule of Cyprus.": "다섯 언어의 학식과 반박의 파나리온을 지닌 살라미스의 주교, 팔레스타인 사막의 고행자가 키프로스에서 길고 흰 다스림으로 관을 받는다.",
    "A bishop of Samosata refusing to surrender the record of the faith though his hand be cut off, traveling in disguise to strengthen the Orthodox, crowned by the tile of an Arian.": "손이 잘리더라도 신앙의 기록을 내어 주기를 거부하는 사모사타의 주교, 변장하고 다니며 정교인들을 굳세게 하다가 아리우스파의 기왓장에 관을 받는다.",
    "A bishop of Sardis scourged for Christ, the dry wooden stake stained with his blood taking root and growing into a green tree of healing beside him.": "그리스도를 위하여 매 맞은 사르디스의 주교, 그의 피로 물든 마른 나무 말뚝이 뿌리를 내려 그 곁에서 치유의 푸른 나무로 자란다.",
    "A bishop of Synnada bearing the icons he defended, the courts of caliph and emperor behind him, the exile that crowned his confession before him.": "자기가 지킨 이콘들을 든 시나다의 주교, 그 뒤에 칼리프와 황제의 궁정이 있고, 그 앞에 그의 고백에 관을 씌운 유배가 있다.",
    "A bishop of Tver reconciling princes with the Gospel between them, the Zheltikov monastery rising by the river, the Kyiv Caves Paterikon copied out under his hand.": "복음을 사이에 두고 공후들을 화해시키는 트베르의 주교, 강가에 젤티코프 수도원이 일어서고, 그의 손 아래에서 키예프 동굴 파테리콘이 옮겨 적힌다.",
    "A bishop of Verona with a fishing rod and a line of catechumens for his catch, the Adige rising in flood behind him and standing like a wall at the open doors of his church.": "낚싯대를 들고 예비신자들의 줄을 어획으로 삼는 베로나의 주교, 그 뒤에서 아디제 강이 넘쳐 오르다가 그의 성당 열린 문 앞에서 성벽처럼 멈춰 선다.",
    "A bishop of Vladimir with the founding letter of the Caves Paterik in his hand, his friend Polikarp cautioned against vainglory, the Near Caves receiving the author home to the monastery of his heart.": "동굴 파테리크의 창시가 된 편지를 손에 든 블라디미르의 주교, 그의 벗 폴리카르프는 헛된 영광을 경계하라는 말을 듣고, 가까운 동굴이 그 지은이를 제 마음의 수도원으로 맞아들인다.",
    "A bishop of ascetic countenance in the omophorion, blessing, his incorrupt relics in a shrine.": "견대를 걸치고 축복하는 고행자다운 얼굴의 주교, 그의 썩지 않은 유물이 성소에 있다.",
    "A bishop of gentle countenance distributing alms, a schema laid ready beside his omophorion.": "자선을 나누어 주는 온화한 얼굴의 주교, 그의 견대 곁에 대수도자 품의 옷이 준비되어 놓여 있다.",
    "A bishop of the Black Sea coast with his city walls behind him, Saracen raiders scattered by his prayer, the northern raiders frozen at his sepulcher until the captives go free.": "뒤에 자기 성벽을 둔 흑해 연안의 주교, 그의 기도에 사라센의 침략자들이 흩어지고, 북방의 침략자들은 포로들이 풀려날 때까지 그의 무덤 앞에서 얼어붙는다.",
    "A bishop of the Crimean Goths defending the holy icons, consecrated in Orthodox Georgia, sharing the sufferings of his people under the Khazar yoke.": "거룩한 이콘을 지키는 크림 고트인의 주교, 정교의 조지아에서 축성되었고, 하자르의 멍에 아래에서 제 백성의 고난을 함께 나눈다.",
    "A bishop of the Hellespont in chains for the icons, the letters of Theodore the Studite in his hands.": "이콘을 위하여 쇠사슬에 매인 헬레스폰토스의 주교, 손에 스투디온의 테오도로의 편지들을 들었다.",
    "A bishop of the Hellespont on the road again, the iconoclasts' document forever unsigned behind him, the icon of Christ carried from refuge to refuge.": "다시 길 위에 선 헬레스폰토스의 주교, 그 뒤에 끝내 서명하지 않은 성상파괴자들의 문서가 있고, 그리스도의 이콘이 피난처에서 피난처로 옮겨진다.",
    "A bishop of the Nicene fathers leading the serpent by his staff into the fire, and on the mountain road the ambush of the heretics, the stone of the murderess turned against her until his grave healed her.": "지팡이로 뱀을 이끌어 불에 넣는 니케아 교부들 가운데 한 주교, 산길에서는 이단자들의 매복이 있고, 살해하려던 여인의 돌이 도리어 그를 치다가 그의 무덤이 그 여인을 고쳐 준다.",
    "A bishop of the Siberian frontier among the peoples of the east, the churches and schools of his planting behind him, the lamp of his night prayers burning over Irkutsk.": "동방의 백성들 가운데 있는 시베리아 변경의 주교, 그 뒤에 그가 세운 성당들과 학교들이 있고, 이르쿠츠크 위로 그의 밤기도의 등불이 타오른다.",
    "A bishop of the apostolic line blessing a bitter spring at Catania, the water running sweet and the city believing.": "카타니아에서 쓴 샘을 축복하는 사도 계승의 주교, 물이 달게 흐르고 도시가 믿는다.",
    "A bishop ordained by the hand of the Theologian, laying his own hand on the young Polycarp, a myrtle flowering from his tomb.": "신학자의 손으로 서품된 주교, 자기 손을 젊은 폴리카르포에게 얹으며, 그의 무덤에서 도금양이 꽃핀다.",
    "A bishop rapt in divine song at the funeral of the Theotokos, the apostles around the bier.": "하느님의 어머니의 장례에서 거룩한 노래에 사로잡힌 주교, 상여 둘레에 사도들이 있다.",
    "A bishop rising from a deep pit, the king with the face of a beast healed before him, a church shown from heaven.": "깊은 구덩이에서 올라오는 주교, 그 앞에서 짐승의 얼굴을 한 왕이 낫고, 하늘로부터 한 성당이 보인다.",
    "A bishop sailing upon his mantle across the lake, the city that expelled him kneeling on the shore.": "자기 망토를 타고 호수를 건너는 주교, 그를 내쫓은 도시가 물가에서 무릎 꿇는다.",
    "A bishop scourged with ox-hide thongs, the icon of Christ held fast in his hands through four exiles.": "쇠가죽 끈으로 매 맞은 주교, 네 번의 유배 내내 그리스도의 이콘을 손에 굳게 붙든다.",
    "A bishop serene in prison, the false witness healed and confessing, an open book of Ecclesiastes before him.": "감옥에서 평온한 주교, 거짓 증인이 낫고 자백하며, 그 앞에 코헬렛의 책이 펼쳐져 있다.",
    "A bishop set upon by schismatics with swords, praying for his murderers as he falls.": "칼을 든 분열자들에게 습격당한 주교, 쓰러지면서 자기를 죽이는 이들을 위하여 기도한다.",
    "A bishop standing unharmed in the flames with the sorcerer bound in his omophorion, the fire dividing the true wonder from the false before the whole city.": "불길 속에 상함 없이 선 주교, 마술사는 그의 견대에 묶여 있고, 불이 온 도시 앞에서 참된 기적과 거짓된 것을 갈라 놓는다.",
    "A bishop standing upon his mantle spread on the waters of the Oka, the Murom icon of the Mother of God in his hands, borne upstream to Ryazan, his innocence proclaimed by the wonder.": "오카 강 물 위에 편 자기 망토를 딛고 선 주교, 손에 무롬의 하느님의 어머니 이콘을 들고 물길을 거슬러 랴잔으로 옮겨지며, 그 기적이 그의 무죄를 알린다.",
    "A bishop struck down at the altar during the Divine Liturgy, angels receiving his soul.": "성찬예배 중에 제대에서 쓰러진 주교, 천사들이 그의 영혼을 받아들인다.",
    "A bishop tried by fire, beasts, and sword, the great company of five hundred forty-six confessors about him, Jerusalem's name upon a martyrdom the whole East shared.": "불과 짐승과 칼로 시험받은 주교, 그 둘레에 오백마흔여섯 증거자의 큰 무리가 있고, 온 동방이 함께한 순교 위에 예루살렘의 이름이 있다.",
    "A bishop upon a pillar with a pen, the paschal sermons streaming from his mouth like light, the prayer book of the faithful open at the prayers he wrote for every day of the week.": "붓을 들고 기둥 위에 선 주교, 부활의 설교가 빛처럼 그 입에서 흘러나오고, 그가 한 주의 날마다 지은 기도로 신자들의 기도서가 펼쳐져 있다.",
    "A bishop vested in the omophorion, with a short rounded beard, holding a Gospel book and blessing.": "견대를 걸치고 짧고 둥근 수염을 한 주교, 복음서를 들고 축복한다.",
    "A bishop washing the wounds of lepers with his own hands, then standing before Leo the Armenian foretelling his swift destruction, the fortress of his thirty-year exile behind him.": "자기 손으로 나병 환자의 상처를 씻는 주교, 이어 아르메니아인 레오 앞에 서서 그의 빠른 멸망을 예고하며, 그 뒤에 삼십 년 유배의 성채가 있다.",
    "A bishop who once wore Tatar chains preaching Christ in the Tatar tongue at Kazan, the Savior monastery rising in the kremlin, the sick of two faiths healed at his prayer.": "한때 타타르의 사슬을 찼던 주교가 카잔에서 타타르 말로 그리스도를 전하고, 크렘린 안에 구세주 수도원이 일어서며, 그의 기도에 두 신앙의 병자들이 낫는다.",
    "A bishop who was a surgeon, the omophorion over his shoulders and the healing of the sick in his hands, the prisons and exiles of his confession behind him, the light of Christ in a godless age.": "외과 의사였던 주교, 어깨에 견대를 걸치고 손에는 병자의 치유가 있으며, 그 뒤에 그의 고백이 치른 감옥과 유배가 있고, 하느님 없는 시대에 그리스도의 빛이 있다.",
    "A bishop with a Gospel preaching to the people of Volhynia, a cave monastery in the distance.": "복음서를 들고 볼히니아 백성에게 전하는 주교, 멀리 동굴 수도원이 있다.",
    "A bishop with a company of one hundred ninety-nine disciples, the sign of the Cross that saved him in battle above, the swords of Sicily gathering the whole school into one harvest.": "백아흔아홉 제자의 무리와 함께 있는 주교, 위에는 전투에서 그를 구한 십자성호가 있고, 시칠리아의 칼들이 그 학교 전체를 한 번의 수확으로 거둔다.",
    "A bishop with a high domed forehead and short pointed beard, a thin ascetic face, vested in the omophorion and holding a Gospel book.": "높고 둥근 이마에 짧고 뾰족한 수염을 한 주교, 여윈 고행자의 얼굴로 견대를 걸치고 복음서를 들었다.",
    "A bishop with a lamp, a serpent fleeing before him, the island of Crete behind.": "등불을 든 주교, 그 앞에서 뱀이 달아나고, 뒤에 크레타 섬이 있다.",
    "A bishop with a long dark tapering beard and high forehead, vested in the omophorion, holding a Gospel book and blessing.": "길고 검은 끝이 가는 수염에 높은 이마를 한 주교, 견대를 걸치고 복음서를 들고 축복한다.",
    "A bishop with the Prologue open in his hands, the lake of Ohrid behind one shoulder and the wire of Dachau behind the other, preaching Christ to the peoples in every tongue he knew.": "프롤로그를 펼쳐 든 주교, 한 어깨 뒤에 오흐리드 호수가, 다른 어깨 뒤에 다하우의 철조망이 있고, 자기가 아는 모든 말로 백성들에게 그리스도를 전한다.",
    "A bishop with the marks of long warfare, demons fleeing behind him, angels and the Theotokos receiving his soul before him.": "오랜 싸움의 자국을 지닌 주교, 그 뒤에서 마귀들이 달아나고, 그 앞에서 천사들과 하느님의 어머니가 그의 영혼을 맞아들인다.",
})

TEXT.update({
    "A bishop with the paschal fire blazing on the hill of Slane against the high king's darkness, the shamrock of the Trinity in his hand, the tribes of Ireland kneeling to the font.": "상왕의 어둠에 맞서 슬레인 언덕에서 부활의 불을 지피는 주교, 손에 삼위일체의 세잎클로버를 들었고, 아일랜드의 부족들이 세례반 앞에 무릎 꿇는다.",
    "A bishop with verses branded upon his face, holding an icon of Christ and a scroll of canons.": "얼굴에 시구가 새겨진 주교, 그리스도의 이콘과 교회법 두루마리를 들었다.",
    "A bishop writing canons at a desk, the Theotokos appearing to bless him.": "책상에서 교회법을 쓰는 주교, 하느님의 어머니가 나타나 그를 축복한다.",
    "A bishop's omophorion hidden beneath a novice's habit, an aged hesychast silent in his cell at the Lavra.": "초심자의 옷 아래 감춘 주교의 견대, 라브라의 자기 방에서 침묵하는 늙은 헤시카스트.",
    "A bishop, a deacon, a servant, and a holy woman crowned together amid flames at Pergamum.": "페르가몬에서 불길 가운데 함께 관을 받은 주교와 부제와 종과 거룩한 여인.",
    "A bishop-ascetic in chains beneath an iron cage, Saint George leading him from childhood as a companion, the possessed freed and the storms stilled at his prayer, the resigned omophorion folded beside the hermit's cave.": "쇠 우리 아래 사슬에 묶인 고행자 주교, 성 게오르기가 어린 시절부터 동행으로 그를 이끌고, 그의 기도에 사로잡힌 이들이 풀려나며 폭풍이 잦아들고, 은수처 동굴 곁에 내려놓은 견대가 접혀 있다.",
    "A bishop-confessor bearing the marks of his wounds, holding a Gospel.": "자기 상처의 자국을 지닌 증거자 주교, 복음서를 들었다.",
    "A bishop-envoy on the road between empires, gifts flowing through his hands to the poor of his city.": "제국들 사이의 길에 선 사절 주교, 그의 손을 거쳐 선물이 제 도시의 가난한 이들에게 흘러간다.",
    "A bishop-martyr barring an emperor from the church doors, three youths and their mother beside him.": "황제를 성당 문 앞에서 막아서는 순교자 주교, 그 곁에 세 젊은이와 그들의 어머니가 있다.",
    "A bishop-martyr by the sea, ships in the distance, flames beneath his feet trampled down.": "바닷가의 순교자 주교, 멀리 배들이 있고, 그 발 아래 불길이 짓밟혀 있다.",
    "A bishop-martyr holding a Gospel, a lion at his feet praising God.": "복음서를 든 순교자 주교, 그 발치에서 사자가 하느님을 찬양한다.",
    "A bishop-martyr in the omophorion holding a Gospel and a cross.": "견대를 걸치고 복음서와 십자가를 든 순교자 주교.",
    "A bishop-martyr in the omophorion holding a Gospel or a scroll inscribed against heresy.": "견대를 걸치고 복음서나 이단을 반박하는 두루마리를 든 순교자 주교.",
    "A bishop-martyr in the omophorion holding a Gospel or a scroll on the unity of the Church.": "견대를 걸치고 복음서나 교회의 일치에 관한 두루마리를 든 순교자 주교.",
    "A bishop-martyr in the omophorion holding a Gospel, a burning church in the background.": "견대를 걸치고 복음서를 든 순교자 주교, 뒤에 불타는 성당이 있다.",
    "A bishop-martyr in the omophorion holding a Gospel, sometimes with a ship or flames.": "견대를 걸치고 복음서를 든 순교자 주교, 때로는 배나 불길과 함께 있다.",
    "A bishop-martyr in the omophorion holding a Gospel, with his three companions and tamed beasts.": "견대를 걸치고 복음서를 든 순교자 주교, 세 동료와 길들여진 짐승들과 함께 있다.",
    "A bishop-martyr with a soldier and four women, all crowned together.": "한 군인과 네 여인과 함께 모두 관을 받은 순교자 주교.",
    "A bishop-martyr with a young nun and two servants, holding crosses.": "젊은 수녀와 두 종과 함께 십자가를 든 순교자 주교.",
    "A bishop-physician and his sister holding crosses, his hands extended in healing.": "십자가를 든 의사 주교와 그의 누이, 그의 손이 치유를 위하여 펼쳐져 있다.",
    "A bishop-physician at the Persian court, the king healed and the hidden trickster unearthed from beneath the temple floor, caravans of martyrs' relics entering the city of his name.": "페르시아 궁정의 의사 주교, 왕이 낫고 신전 바닥 밑에서 숨은 사기꾼이 드러나며, 순교자들의 유물을 실은 대상들이 그의 이름을 딴 도시로 들어온다.",
    "A bishop-physician in a mountain cave with the wild beasts gathered gently around him, a child healed of a choking bone, seven women and two children crowned beside him.": "산속 동굴에서 들짐승들이 순하게 둘러앉은 가운데 있는 의사 주교, 뼈가 목에 걸린 아이가 낫고, 일곱 여인과 두 아이가 그 곁에서 관을 받는다.",
    "A blind eldress seated small and radiant in a Moscow room, the lines of the troubled stretching through the Soviet dark to her door, her closed eyes seeing all of it in God.": "모스크바의 한 방에 작고 빛나게 앉은 눈먼 장로 여인, 소비에트의 어둠을 뚫고 괴로운 이들의 줄이 그의 문까지 이어지며, 감긴 그의 눈이 하느님 안에서 그 모두를 본다.",
    "A boy bishop-to-be praying before an emptied granary as it fills again, coins and wine multiplying in his open hands.": "비워진 곳간 앞에서 기도하니 다시 채워지는, 뒷날 주교가 될 소년, 펼친 그의 손에서 돈과 포도주가 불어난다.",
    "A boy confessing Christ with his tutor Modestus and nurse Crescentia beside him, the cauldron and the beasts before them, the child and his guardians crowned together.": "스승 모데스토와 유모 크레스켄티아를 곁에 두고 그리스도를 고백하는 소년, 그 앞에 가마솥과 짐승들이 있고, 아이와 그를 지킨 이들이 함께 관을 받는다.",
    "A boy in peasant dress with a harrow, lightning above, angels receiving his soul.": "써레를 든 농부 차림의 소년, 위에 번개가 치고, 천사들이 그의 영혼을 맞아들인다.",
    "A boy martyr with a white dove above him, water springing from the rock at his prayer, the lion of his mountain cave refusing to harm him in the arena.": "위에 흰 비둘기를 둔 소년 순교자, 그의 기도에 바위에서 물이 솟고, 그의 산속 동굴에 살던 사자가 원형 경기장에서 그를 해치기를 마다한다.",
    "A boy prince in royal robes bearing the palm of the passion-bearer, the yard of Uglich behind him where he fell, his incorrupt relics enshrined in the Kremlin to confound the pretenders.": "왕의 옷을 입고 수난자의 종려나무 가지를 든 소년 공, 그 뒤에 그가 쓰러진 우글리치의 뜰이 있고, 썩지 않은 그의 유물이 참칭자들을 무색하게 하려고 크렘린에 모셔진다.",
    "A bread merchant with pierced hands and feet, walking his last steps for Christ.": "손과 발이 꿰뚫린 빵 장수, 그리스도를 위하여 마지막 걸음을 걷는다.",
    "A bridegroom and bride in virginal crowns, the lion guarding Daria's honor, the tribune Claudius converted with his whole house, the sand pit of the Via Salaria closing over the two alive.": "동정의 관을 쓴 신랑과 신부, 사자가 다리아의 정절을 지키고, 천부장 클라우디오가 온 집안과 함께 회심하며, 살라리아 가도의 모래 구덩이가 산 두 사람 위로 닫힌다.",
    "A brother and sister crowned as martyrs, holding crosses and palms.": "십자가와 종려나무 가지를 들고 순교자로 관을 받은 오누이.",
    "A brother and sister martyrs, he upon a tree, she with a spear, both crowned.": "남매 순교자, 오라비는 나무 위에, 누이는 창에 찔려, 둘 다 관을 받는다.",
    "A canonarch of the Far Caves directing the chanting of the brethren, the book of the services in his hand, the monastic life embraced from his childhood.": "형제들의 노래를 이끄는 먼 동굴의 선창자, 손에 예배서를 들었고, 어린 시절부터 수도 생활을 받아들였다.",
    "A captain of the guard bound to a tree and shot with arrows, the widow Irene tending him, his converted companions with their crowns around him.": "나무에 묶여 화살을 맞은 근위대장, 과부 이리나가 그를 돌보고, 회심한 그의 동료들이 관을 쓰고 둘레에 있다.",
    "A cathedral in flames on the night of the Nativity, the bishop baptizing and communing the multitude within, twenty thousand crowns rising in the smoke.": "성탄 밤에 불타는 대성당, 그 안에서 주교가 무리에게 세례를 주고 성체를 나누며, 이만 개의 관이 연기와 함께 올라간다.",
    "A centurion striding from the desert into the crowded amphitheater, proclaiming Christ before the astonished city.": "사막에서 붐비는 원형 경기장으로 걸어 들어가 놀란 도시 앞에서 그리스도를 선포하는 백부장.",
    "A centurion with spear at the foot of the Cross, his eyes lifted to the Crucified, confessing.": "십자가 밑에 창을 들고 선 백부장, 눈을 들어 십자가에 달리신 분을 우러러 고백한다.",
    "A church at Nicopolis in Armenia": "아르메니아 니코폴리스의 성당",
    "A church built over his grave at Skepsis": "스켑시스에 있는 그의 무덤 위에 세워진 성당",
    "A church in her honor at Chalcedon by 450": "450년까지 칼케돈에 세워진 그를 기리는 성당",
})
