# -*- coding: utf-8 -*-
"""Korean for the vocabulary that stands beside the lives.

TEXT = {the phrase the index shows: the rendering}. The keys are the phrases
exactly as the index writes them, so a rendering cannot quietly attach itself
to the wrong saint.

A language may later declare PARTS and an expand() to assemble the compound
place-names from pieces rendered once, as the older languages do. It is an
optimisation and not a requirement: everything written in TEXT stands over
whatever expand() builds.
"""
TEXT = {
}

TEXT.update({
    "(Abibus) of Egypt": "(아비보) 이집트의",
    "(Apphianus) and Edesius (Aedesius) of Lycia": "(암피아노)와 리키아의 에데시오(아이데시오)",
    "(Eustace) the Confessor, Bishop of Bithynia": "(에우스타티오) 증거자, 비티니아의 주교",
    "(Jacob) the Presbyter, and Azadanes and Abdiesus the Deacons, of Persia": "(야고보) 사제와 부제 아자다네스와 압디에소, 페르시아의",
    "(Vadim) of Persia": "(바딤) 페르시아의",
    "(Voino-Yasenetsky), Archbishop of Simferopol and Crimea": "(보이노-야세네츠키), 심페로폴과 크림의 대주교",
    "(also called Susanna), New Martyr of Lesbos": "(수산나라고도 불림), 레스보스의 새 순교녀",
    "(tonsured David and Euphrosyne), Wonderworkers of Murom": "(수도명 다윗과 에우프로시네), 무롬의 기적행자",
    "A Cappadocian centurion bowing beneath the sword with his eyes lifted in thanksgiving, the walnut tree of the tradition behind him, the churches of Byzantium rising over his relics.": "카파도키아의 백부장이 칼 아래 몸을 굽히고 눈을 들어 감사드리며, 그 뒤에 전승의 호두나무가 있고, 그의 유물 위로 비잔티움의 성당들이 솟아오른다.",
    "A Celtic hermit of the Devon coast bearing his own severed head to the spring, the robbers behind him, crowned as a martyr among the saints of Britain.": "데번 해안의 켈트 은수자가 잘린 자기 머리를 들고 샘으로 가며, 뒤에는 강도들이 있고, 브리튼의 성인들 가운데 순교자로 관을 받는다.",
    "A Christian general casting down the temples of Galatia, his twelve tribunes and his thousands of soldiers with their wives and children crowned around him, the converted sorcerer Callinicus among them.": "갈라티아의 신전들을 무너뜨리는 그리스도인 장군, 그의 열두 천부장과 아내와 자녀를 거느린 수천의 군사가 그 둘레에서 관을 받으며, 그 가운데 회심한 마술사 칼리니코가 있다.",
    "A Christian of Alexandria standing before the tribunal to denounce its cruelty, the confession volunteered and the sword received.": "알렉산드리아의 한 그리스도인이 재판정 앞에 서서 그 잔혹함을 고발하니, 스스로 나선 고백과 받아들인 칼이 있다.",
    "A Creole-Aleut priest in vestments holding a Gospel and a cross, against an Alaskan landscape.": "제의를 입은 크레올-알류트 사제가 복음서와 십자가를 들고 알래스카의 풍경을 배경으로 서 있다.",
    "A Georgian bishop with a book and a restored church, schoolchildren and monasteries behind him.": "책을 든 조지아의 주교와 그가 다시 세운 성당, 그 뒤에 학생들과 수도원들이 있다.",
    "A Georgian commander marking his forehead with the cross in his own blood, his soldiers crowned around him.": "조지아의 장군이 자기 피로 이마에 십자가를 그으며, 그의 군사들이 둘레에서 관을 받는다.",
    "A Georgian monk in prayer before the cave monastery of Gareji in the desert hills.": "사막의 언덕에 자리한 가레지 동굴 수도원 앞에서 기도하는 조지아의 수도자.",
    "A Georgian monk-abbot holding a scroll or a book.": "두루마리나 책을 든 조지아의 수도원장 수도자.",
    "A Georgian prince and commander refusing to trample the icon of Christ before the conqueror, crowned as a great-martyr, the defender of the Georgian faith.": "정복자 앞에서 그리스도의 이콘 밟기를 거부하는 조지아의 공이자 장군, 대순교자로 관을 받은 조지아 신앙의 수호자.",
    "A Gothic congregation at worship within the burning church, twenty-six crowns rising with the smoke, the queen gathering the holy remains from the ashes.": "불타는 성당 안에서 예배드리는 고트인 회중, 연기와 함께 스물여섯 개의 관이 올라가고, 왕비가 재에서 거룩한 유물을 거둔다.",
    "A Gothic general of Rome casting down his military belt before Aurelian, seventy soldiers confessing behind him, the river receiving the wonderworking commander.": "아우렐리아누스 앞에 자기 군대 띠를 벗어 던지는 로마의 고트인 장군, 그 뒤에서 일흔 명의 군사가 고백하고, 강이 기적행자 장군을 받아들인다.",
    "A Great Prince of Kyiv with the churches of Smolensk he raised, the monastic habit he longed for held by an angel, the elder Polycarp pointing him back to his throne.": "자기가 세운 스몰렌스크의 성당들과 함께 있는 키예프의 대공, 그가 사모하던 수도복을 천사가 들고 있고, 폴리카르포 장로가 그를 그의 자리로 돌려보낸다.",
    "A Greek bishop preaching Christ to the pagan Rostov land, the first shepherd of a hostile flock, the see of Rostov founded amid the idols of the north.": "이교의 로스토프 땅에 그리스도를 전하는 그리스인 주교, 적대하는 무리의 첫 목자, 북방의 우상들 가운데 세워진 로스토프의 주교좌.",
    "A Greek iconographer of Constantinople founding the island monastery of Lake Onega, the Sophia icon he copied in his hands, the peoples of the north gathering to his light at the age of one hundred and five.": "오네가 호수의 섬 수도원을 세운 콘스탄티노폴리스의 그리스인 이콘 화가, 그가 옮겨 그린 소피아 이콘을 손에 들고, 백다섯 살에 이른 그의 빛으로 북방의 백성들이 모여든다.",
    "A Greek metropolitan enthroned at Moscow beside the shrine of Peter, standing unbowed before the khan of the Horde, the Church's charter of freedom in his hand.": "베드로의 성소 곁 모스크바 좌에 오른 그리스인 수도 대주교, 호르드의 칸 앞에 굽히지 않고 서서, 교회의 자유의 특허장을 손에 들고 있다.",
    "A Greek of Ephesus at the Apostle Paul's side, the Temple riot swirling around his innocent presence, the sickbed of Miletus and the sword of Rome completing his long companionship.": "사도 바오로 곁에 선 에페소스의 그리스인, 성전의 소요가 그의 무죄한 자리를 휘감고, 밀레토스의 병상과 로마의 칼이 그의 긴 동행을 마무리한다.",
    "A Greek prince laying aside his rank for the monastic habit, the Uchma hermitage rising on the bank of the Volga, the exile made a wonderworker in his adopted land.": "수도복을 위하여 자기 지위를 내려놓는 그리스인 공, 볼가 강가에 서는 우치마 은수처, 자기가 받아들인 땅에서 기적행자가 된 유배자.",
    "A Patriarch of Constantinople seated upright in death as in blessing, the Mgar monastery of Lubny receiving the traveler, the two worlds of Greece and Rus' joined at his throne.": "죽어서도 축복하듯 곧게 앉아 있는 콘스탄티노폴리스 총대주교, 루브니의 므가르 수도원이 나그네를 맞아들이고, 그리스와 루스의 두 세계가 그의 좌에서 만난다.",
    "A Persian noble offering his severed members one by one, each with a prayer, angels gathering his prayers.": "잘린 지체를 하나씩 기도와 함께 바치는 페르시아의 귀족, 천사들이 그의 기도를 거둔다.",
    "A Persian soldier turned monk, the captive Cross of the Lord shining before him, the waters and the sword of Bethsaloe beneath his crown.": "수도자가 된 페르시아의 군인, 사로잡힌 주님의 십자가가 그 앞에 빛나고, 그의 관 아래에 베트살로에의 물과 칼이 있다.",
    "A Roman centurion kneeling before the Apostle Peter, or vested as a bishop holding a Gospel.": "사도 베드로 앞에 무릎 꿇은 로마의 백부장, 또는 복음서를 든 주교의 제의 차림.",
    "A Roman general in armor holding a cross, his soldiers behind him, a spring at his feet.": "십자가를 든 갑옷 차림의 로마 장군, 그 뒤에 군사들이 있고, 그의 발치에 샘이 있다.",
    "A Roman maiden in flight across the sea with two servants, the convent of Saint Stephen at Mylasa, a cross of stars brighter than the sun above her repose.": "두 하녀와 함께 바다를 건너 달아나는 로마의 처녀, 밀라사의 성 스테파노 수도원, 그리고 그의 안식 위로 해보다 밝은 별들의 십자가.",
    "A Roman matron refusing the Arian rite, the fire kindled behind her, Saint Ambrose blessing from afar.": "아리우스파의 예식을 거부하는 로마의 귀부인, 그 뒤에 불이 지펴지고, 멀리서 성 암브로시오가 축복한다.",
    "A Roman noblewoman scattering deeds and treasure to the poor, thousands of freed slaves behind her, her small cell on the Mount of Olives before her.": "증서와 재물을 가난한 이들에게 흩는 로마의 귀부인, 그 뒤에 해방된 수천의 종들이 있고, 그 앞에 올리브 산의 작은 방이 있다.",
    "A Roman senator opening his house to the Apostle Peter, the household at prayer becoming a church, the greeting of the epistle shining over the door.": "사도 베드로에게 자기 집을 여는 로마의 원로원 의원, 기도하는 집안이 교회가 되고, 서간의 인사가 그 문 위에 빛난다.",
    "A Roman widow standing amid seven crowned sons, encouraging each to the contest, her own crown descending last.": "관을 쓴 일곱 아들 가운데 선 로마의 과부, 저마다를 싸움으로 격려하고, 자기 관은 마지막에 내려온다.",
    "A Russian captive in the winter night of Kazan, bound and wounded in the snow, alive at dawn with his confession unbroken.": "카잔의 겨울밤에 묶여 눈 속에 상한 러시아인 포로, 새벽에도 살아 그 고백이 꺾이지 않았다.",
    "A Russian soldier-slave at prayer in his master's stable, the Turkish household softened by his faith, his incorrupt relics glorified across the Greek world.": "주인의 마구간에서 기도하는 러시아인 종 군인, 터키인 집안이 그의 신앙에 누그러지고, 썩지 않은 그의 유물이 그리스 온 땅에서 영광을 받는다.",
    "A Serbian prince leading his army at Kosovo, choosing the kingdom of heaven over the kingdom of earth, crowned as a great-martyr, his incorrupt relics the treasure of his people.": "코소보에서 자기 군대를 이끄는 세르비아의 공, 땅의 나라보다 하늘의 나라를 택하고, 대순교자로 관을 받았으며, 썩지 않은 그의 유물이 제 백성의 보배가 되었다.",
    "A Spanish dignitary in the Great Schema, the roads of his pilgrimage from Rome to Jerusalem behind him, the Saracen sword before him.": "대수도자 품을 입은 스페인의 고관, 그 뒤에 로마에서 예루살렘까지의 순례 길이 있고, 그 앞에 사라센의 칼이 있다.",
})

TEXT.update({
    "A Swedish princess become mother of Rus, her sainted son Vladimir beside her, the crowns of France, Hungary, and Norway among her daughters, the nun's habit her final vesture.": "루스의 어머니가 된 스웨덴의 공주, 그 곁에 성인이 된 아들 블라디미르가 있고, 딸들 가운데 프랑스와 헝가리와 노르웨이의 왕관이 있으며, 수녀의 옷이 그의 마지막 예복이다.",
    "A Syrian stranger standing three days in prayer in the church of Spoleto, the garden thieves fed at his table and converted, the offered estates refused with a smiling shake of the head.": "스폴레토의 성당에서 사흘을 기도하며 서 있는 시리아의 나그네, 그의 식탁에서 먹고 회심한 정원의 도둑들, 미소로 고개를 저어 사양한 바쳐진 재산.",
    "A Tatar captive baptized and tonsured, founding a monastery on the shore of Lake Kozha in the far north, the wilderness hallowed by his prayer.": "세례를 받고 삭발한 타타르의 포로, 먼 북방 코자 호수 기슭에 수도원을 세우고, 그의 기도로 거룩해진 광야.",
    "A Yup'ik mother in a kuspuk holding a basin and towel, the northern lights above the tundra behind her.": "쿠스푹을 입은 유픽의 어머니가 대야와 수건을 들고, 그 뒤 툰드라 위로 북극광이 펼쳐진다.",
    "A barefoot ascetic in rags, blessing, at Novgorod.": "노브고로드에서 누더기를 걸치고 맨발로 축복하는 고행자.",
    "A barefoot fool in tattered clothing by a northern river, giving away what was given to him.": "북방의 강가에서 누더기를 걸친 맨발의 바보, 자기에게 주어진 것을 남에게 내어 준다.",
    "A barefoot fool-for-Christ holding a head of cabbage, at Novgorod by the river.": "노브고로드의 강가에서 양배추 한 통을 든 맨발의 그리스도를 위한 바보.",
    "A barefoot fool-for-Christ in a sheepskin holding an axe, by the river defending the city.": "양가죽을 걸치고 도끼를 든 맨발의 그리스도를 위한 바보, 강가에서 도시를 지킨다.",
    "A barefoot holy fool with long hair, holding a Psalter, of gentle and sorrowful aspect.": "긴 머리에 시편을 든 맨발의 거룩한 바보, 온화하고 슬픈 얼굴이다.",
    "A basilica at Lydda, the tomb of Saint George within, hierarchs consecrating the church.": "리다의 대성당, 그 안에 성 게오르기의 무덤이 있고, 주교들이 성당을 축성한다.",
    "A bearded missionary priest with a traveler's bag, the church of Jackson and the hills of California behind him.": "나그네의 봇짐을 든 수염 난 선교 사제, 그 뒤에 잭슨의 성당과 캘리포니아의 언덕이 있다.",
    "A beggar beneath the staircase of his father's palace, unknown to all his household, the finished scroll of his life clasped in his dead hand while the emperor and the pope kneel to read it.": "아버지 저택의 계단 아래 있는 걸인, 온 집안이 그를 알아보지 못하고, 죽은 손에 자기 생애를 적은 두루마리를 쥐었으며, 황제와 교황이 무릎 꿇고 그것을 읽는다.",
    "A bent elder in white on his knees upon the rock, the Theotokos of Tenderness before him, a bear at the edge of the forest clearing.": "바위 위에 무릎 꿇은 흰옷의 굽은 장로, 그 앞에 온유의 하느님의 어머니 이콘이 있고, 숲의 빈터 가장자리에 곰이 있다.",
    "A bishop alone in an emptied city awaiting the persecutors, then crucified at Perge, teaching from the cross until his voice failed into glory.": "비워진 도시에 홀로 남아 박해자들을 기다리는 주교, 이어 페르게에서 십자가에 달려 목소리가 다할 때까지 십자가에서 가르치다 영광에 들어간다.",
    "A bishop and a presbyter of Persia holding crosses, swords above them.": "십자가를 든 페르시아의 주교와 사제, 그 위에 칼이 있다.",
    "A bishop and a virgin holding crosses, broken books of sorcery burning at their feet.": "십자가를 든 주교와 동정녀, 그 발치에 마술의 책들이 부서져 불탄다.",
    "A bishop and his companions holding crosses, cast into a furnace, a soldier among them.": "십자가를 든 주교와 그 동료들이 화덕에 던져지고, 그 가운데 한 군인이 있다.",
    "A bishop and presbyter cast into a pit, angels crowning them from above.": "구덩이에 던져진 주교와 사제, 위에서 천사들이 그들에게 관을 씌운다.",
    "A bishop and theologian of Lycia with the scroll of his Banquet of the Ten Virgins, refuting the errors of Origen, crowned at the last with martyrdom.": "열 처녀의 향연 두루마리를 든 리키아의 주교이자 신학자, 오리게네스의 오류를 반박하고, 마침내 순교로 관을 받는다.",
    "A bishop answering the emperor that the Church's questions belong to the Church, the road of exile opening behind him.": "교회의 물음은 교회에 속한다고 황제에게 답하는 주교, 그 뒤로 유배의 길이 열린다.",
    "A bishop baptizing an African king, a boy captive and a royal tutor shown in the scenes of his life.": "아프리카의 왕에게 세례를 주는 주교, 그의 생애의 장면에 사로잡힌 소년과 왕실의 스승이 보인다.",
    "A bishop barring the church door to an emperor, a beehive at his feet, a scroll of his hymns in hand.": "황제에게 성당 문을 막아서는 주교, 그의 발치에 벌통이 있고, 손에 자기 찬가의 두루마리가 있다.",
    "A bishop before a fallen idol, a demon bearing a great stone altar behind him, hot springs at his feet.": "쓰러진 우상 앞에 선 주교, 그 뒤에서 마귀가 큰 돌 제단을 나르고, 그의 발치에 온천이 솟는다.",
    "A bishop before the burning temple of Marnas, the cross-guardian's keys at his belt, the Good Thief descending from the Cross in his vision, the Eudoxiana church rising over pagan Gaza.": "불타는 마르나스 신전 앞에 선 주교, 허리띠에 십자가 수호자의 열쇠를 차고, 환시 속에서 착한 강도가 십자가에서 내려오며, 이교의 가자 위로 에우독시아나 성당이 솟는다.",
    "A bishop before the emperor, pointing to the emperor's son, teaching the honor due the Son of God.": "황제 앞에서 그 아들을 가리키며 하느님의 아들께 드릴 공경을 가르치는 주교.",
    "A bishop beheaded at the altar in mid-Liturgy, twenty-eight years of tribunals and torments ranged behind him like waves, Agathangelus crowned at his side.": "성찬예배 중에 제대에서 목이 잘린 주교, 그 뒤로 스물여덟 해의 재판과 고문이 물결처럼 늘어서고, 그 곁에서 아가탕겔로가 관을 받는다.",
    "A bishop beholding the ladder to heaven with his predecessor calling from above, one hundred and twenty-eight companions ascending behind him under the Persian sword.": "하늘로 오르는 사다리를 바라보는 주교, 위에서 그의 선임자가 부르고, 페르시아의 칼 아래 백스물여덟 명의 동료가 그 뒤를 따라 오른다.",
    "A bishop by night in a plain cloak, leaving firewood at a poor widow's door, his cathedral of Belgorod behind him.": "수수한 겉옷을 입고 밤에 가난한 과부의 문 앞에 땔감을 놓아 두는 주교, 그 뒤에 벨고로드의 대성당이 있다.",
    "A bishop drinking the sorcerer's cup unharmed, the magician kneeling converted beside his cast-down instruments.": "마술사의 잔을 상함 없이 마시는 주교, 곁에서 마술사가 자기 도구를 버리고 회심하여 무릎 꿇는다.",
    "A bishop enthroned with a Gospel, the first hierarch of Jerusalem, of ascetic and venerable countenance.": "복음서를 들고 좌에 오른 주교, 예루살렘의 첫 주교이며, 고행자다운 존경할 얼굴이다.",
    "A bishop holding a Gospel, refuting heretics who shrink before his word.": "복음서를 든 주교, 그 말씀 앞에서 이단자들이 움츠러든다.",
    "A bishop holding a page of the alphabet he invented, the sacred birch of the Zyrians felled behind him, the sorcerer Pam turning from the fire and the water, a new people reading the Gospel in its own letters.": "자기가 지은 자모를 적은 낱장을 든 주교, 그 뒤에 지리안인의 신성한 자작나무가 베여 있고, 마술사 팜이 불과 물 앞에서 돌아서며, 한 새로운 백성이 제 글자로 복음을 읽는다.",
    "A bishop holding a scroll of the Creed, the Theotokos and John the Theologian appearing above, a mountain moved behind.": "신경의 두루마리를 든 주교, 위에 하느님의 어머니와 신학자 요한이 나타나고, 뒤에서 산이 옮겨진다.",
    "A bishop holding an icon of Christ against the imperial decree, the sick healed at his hands.": "황제의 칙령을 거슬러 그리스도의 이콘을 든 주교, 그의 손에서 병자들이 낫는다.",
    "A bishop holding the book of the Divine Names, the darkened sun of the Crucifixion above him.": "하느님의 이름들에 관한 책을 든 주교, 그 위에 십자가 처형의 어두워진 해가 있다.",
    "A bishop in a laborer's tunic drawing water and hauling wood at Nitria, the omophorion of Damascus folded away, heaven alone reading the monk's true rank.": "니트리아에서 일꾼의 옷을 입고 물을 긷고 나무를 나르는 주교, 다마스쿠스의 견대는 접어 두었고, 하늘만이 그 수도자의 참된 품계를 읽는다.",
    "A bishop in a mitre holding a crozier, with a gray beard and an ascetic, gentle face.": "주교관을 쓰고 목장을 든 주교, 흰 수염에 고행자다운 온화한 얼굴이다.",
    "A bishop in monastic poverty, Cernica's island monastery at one hand and the Frasinei he founded at the other, the seminary and the printing press of Ramnic behind him, his face worn bright by fasting.": "수도자의 가난 속에 있는 주교, 한 손에 체르니카의 섬 수도원이, 다른 손에 그가 세운 프라시네이가 있고, 뒤에 럼니쿠의 신학교와 인쇄소가 있으며, 그의 얼굴은 단식으로 맑게 닳았다.",
    "A bishop in the omophorion and mantle holding a book, of gentle and humble aspect.": "견대와 망토를 걸치고 책을 든 주교, 온화하고 겸손한 모습이다.",
    "A bishop in the omophorion and sakkos holding a Gospel book, with a Greek-style beard.": "견대와 사코스를 걸치고 복음서를 든 주교, 그리스식 수염을 하고 있다.",
})

TEXT.update({
    "A bishop in the omophorion blessing the waters at a river confluence, holding a cross.": "견대를 걸치고 십자가를 들고 두 강이 만나는 곳에서 물을 축복하는 주교.",
    "A bishop in the omophorion blessing, holding a Gospel, before the cathedral of Tambov.": "견대를 걸치고 복음서를 들고 축복하는 주교, 탐보프의 대성당 앞이다.",
    "A bishop in the omophorion holding a Gospel book or the scroll of his Great Canon.": "견대를 걸치고 복음서나 자기 대카논의 두루마리를 든 주교.",
    "A bishop in the omophorion holding a Gospel book, a white dove upon his head.": "견대를 걸치고 복음서를 든 주교, 그 머리 위에 흰 비둘기가 있다.",
    "A bishop in the omophorion holding a Gospel, of humble aspect.": "견대를 걸치고 복음서를 든 주교, 겸손한 모습이다.",
    "A bishop in the omophorion holding a Gospel, sometimes with a banner or before a battle.": "견대를 걸치고 복음서를 든 주교, 때로는 군기와 함께, 또는 전투를 앞두고 있다.",
    "A bishop in the omophorion holding a Gospel, the cathedral of Saints Cyril and Methodius behind him.": "견대를 걸치고 복음서를 든 주교, 그 뒤에 성 키릴로와 메토디오 대성당이 있다.",
    "A bishop in the omophorion holding an icon and a Gospel.": "견대를 걸치고 이콘과 복음서를 든 주교.",
    "A bishop in the omophorion surrounded by his ten disciples, all crowned as martyrs.": "견대를 걸치고 열 명의 제자에게 둘러싸인 주교, 모두 순교자로 관을 받았다.",
    "A bishop in the omophorion, his hands or face marked by charcoal, holding a Gospel.": "견대를 걸치고 복음서를 든 주교, 그의 손과 얼굴에 숯의 자국이 있다.",
    "A bishop in the schema and omophorion holding a Gospel, before the city of Voronezh.": "대수도자 품의 옷과 견대를 걸치고 복음서를 든 주교, 보로네시 성 앞이다.",
    "A bishop in the snows of Siberia, a school of native children beside him, the gates of China closed behind.": "시베리아의 눈 속에 선 주교, 그 곁에 원주민 아이들의 학교가 있고, 뒤에는 닫힌 중국의 문이 있다.",
    "A bishop laying aside his omophorion at the mouth of a desert gorge, the monastery of Choziba in the cliffs.": "사막 협곡의 어귀에서 견대를 벗어 놓는 주교, 절벽에 호제바 수도원이 있다.",
    "A bishop led by an angel from torture to torture and city to city, Sirmium converted behind him and Formia receiving him, the lamps of the sailors burning at his name.": "천사에게 이끌려 고문에서 고문으로, 도시에서 도시로 옮겨진 주교, 그 뒤에서 시르미움이 회심하고 포르미아가 그를 맞아들이며, 그의 이름에 뱃사람들의 등불이 타오른다.",
    "A bishop of Aegina laying down his omophorion and returning to the monastic habit, his island see behind him.": "견대를 벗어 놓고 수도복으로 돌아가는 에기나의 주교, 그 뒤에 그의 섬 주교좌가 있다.",
    "A bishop of Amasea standing between the hunted virgin and the tyrant's demand, the sea giving back his body in the fishermen's nets, the last crowns of the persecution descending as the peace of the Church dawns.": "쫓기는 동정녀와 참주의 요구 사이에 선 아마시아의 주교, 바다가 어부의 그물에 그의 몸을 돌려주고, 교회의 평화가 밝아 오면서 박해의 마지막 관들이 내려온다.",
    "A bishop of Argos measuring out grain that does not diminish, the ransomed captives returning from the sea behind him, his monastic family in Christ around the one see he consented to hold.": "줄지 않는 곡식을 되어 나누는 아르고스의 주교, 그 뒤에서 몸값을 치른 포로들이 바다에서 돌아오고, 그가 맡기를 허락한 하나의 주교좌 둘레에 그리스도 안의 수도 가족이 있다.",
    "A bishop of Benevento unharmed in the furnace, the beasts of the arena lying at his feet, Naples receiving his body and his blood, his deacons and companions crowned around him.": "화덕 속에서 상하지 않은 베네벤토의 주교, 원형 경기장의 짐승들이 그 발치에 엎드리고, 나폴리가 그의 몸과 피를 받아들이며, 그의 부제들과 동료들이 둘레에서 관을 받는다.",
    "A bishop of Bithynia holding the icon of Christ and the open Scriptures together, the road of exile behind him.": "그리스도의 이콘과 펼친 성경을 함께 든 비티니아의 주교, 그 뒤에 유배의 길이 있다.",
    "A bishop of Bithynia on the road of exile, his cathedral behind him and the icon of Christ unsurrendered before him.": "유배의 길에 선 비티니아의 주교, 그 뒤에 자기 대성당이 있고 그 앞에 내어 주지 않은 그리스도의 이콘이 있다.",
    "A bishop of Brooklyn with the map of a continent behind him, thirty parishes rising from immigrant streets, The Word in his hand, Tikhon of Moscow laying hands upon the first-consecrated of America.": "뒤에 한 대륙의 지도를 둔 브루클린의 주교, 이민의 거리에서 서른 개의 본당이 일어서고, 손에 \"말씀\"을 들었으며, 모스크바의 티혼이 아메리카에서 처음 축성된 이에게 손을 얹는다.",
    "A bishop of Catania in exile for the holy images, the icon of Christ held fast against the imperial decree.": "거룩한 형상을 위하여 유배된 카타니아의 주교, 황제의 칙령에 맞서 그리스도의 이콘을 굳게 붙든다.",
    "A bishop of Chalcedon and his fellow ascetic standing together for the icons, the see of the Fourth Council refusing the new heresy, exile shared as the cell had been.": "이콘을 위하여 함께 선 칼케돈의 주교와 그의 고행 동료, 제4차 공의회의 주교좌가 새 이단을 거부하고, 한 방을 나누었듯 유배를 나눈다.",
    "A bishop of Chalcedon defending the holy icons, his hand open to the poor, the exile that crowned his confession before him.": "거룩한 이콘을 지키는 칼케돈의 주교, 가난한 이들에게 손을 펴고, 그 앞에 그의 고백에 관을 씌운 유배가 있다.",
    "A bishop of Corinth falsely accused, the newborn infant speaking at his prayer to name its true father, the slander confounded and the saint vindicated.": "거짓 고발을 당한 코린토의 주교, 그의 기도에 갓난아이가 말하여 제 참된 아버지를 밝히고, 중상이 무너지며 성인이 무죄를 인정받는다.",
    "A bishop of Cyprus blessing a dry vine-branch that bears fruit before its time, the poor fed at his hand, the idols of the island cast down.": "때 아니게 열매 맺는 마른 포도 가지를 축복하는 키프로스의 주교, 그의 손에서 가난한 이들이 먹고, 섬의 우상들이 무너진다.",
    "A bishop of Cyprus crowned with martyrdom, his myrrh-streaming relics borne across the sea to Constantinople, the sick healed at his shrine.": "순교로 관을 받은 키프로스의 주교, 몰약을 흘리는 그의 유물이 바다를 건너 콘스탄티노폴리스로 옮겨지고, 그의 성소에서 병자들이 낫는다.",
    "A bishop of Cyprus with the nails of his torture, teaching the faithful gathered at what he thought his end, the edict of Constantine opening his prison to a few more years of shepherding.": "자기를 고문한 못을 지닌 키프로스의 주교, 자기 끝이라 여긴 자리에 모인 신자들을 가르치는데, 콘스탄티누스의 칙령이 그의 감옥을 열어 몇 해를 더 목자로 살게 한다.",
    "A bishop of Epirus striking down the great serpent at the poisoned spring, the rain descending on the parched fields at his prayer, a dead man rising from the bier to witness against the false creditor.": "독이 든 샘에서 큰 뱀을 쳐 죽이는 에피로스의 주교, 그의 기도에 마른 들에 비가 내리고, 죽은 이가 상여에서 일어나 거짓 채권자에게 맞서 증언한다.",
    "A bishop of Melitene serene under the torturers, the emperor's own order opening his prison, the confessor's crown worn through years of peace.": "고문하는 자들 아래에서 평온한 멜리테네의 주교, 황제 자신의 명이 그의 감옥을 열고, 평화의 여러 해 동안 증거자의 관을 쓴다.",
    "A bishop of Novgorod standing alone against an uncanonical council, the Caves that formed him receiving him in confinement and in death, Theodosius appearing to welcome him home.": "교회법에 어긋난 공의회에 홀로 맞선 노브고로드의 주교, 그를 길러 낸 동굴이 갇힌 그를 맞아 죽음까지 품고, 테오도시오가 나타나 그를 집으로 맞아들인다.",
    "A bishop of Pergamum standing where Satan's throne was, the brazen bull glowing behind him, the open Apocalypse naming him the faithful witness in the Lord's own voice.": "사탄의 좌가 있던 곳에 선 페르가몬의 주교, 그 뒤에서 놋쇠 황소가 달아오르고, 펼쳐진 요한 묵시록이 주님의 목소리로 그를 신실한 증인이라 부른다.",
    "A bishop of Perm baptizing the peoples of the far north, the idols of the Permians thrown down and the churches rising, the mission of Saint Stephen carried onward.": "먼 북방의 백성들에게 세례를 주는 페름의 주교, 페름인의 우상들이 무너지고 성당들이 일어서며, 성 스테파노의 선교가 이어진다.",
    "A bishop of Persia with staff of prophecy, a ruined city behind him, two disciples at his side.": "예언의 지팡이를 든 페르시아의 주교, 그 뒤에 무너진 도시가 있고, 곁에 두 제자가 있다.",
    "A bishop of Pisidian Antioch refusing the iconoclast decree, the icons standing in his churches while he goes into exile, the confessor's crown replacing the surrendered see.": "성상파괴의 칙령을 거부하는 피시디아 안티오키아의 주교, 그가 유배로 떠나는 동안 그의 성당들에는 이콘이 그대로 서 있고, 내어 준 주교좌를 증거자의 관이 대신한다.",
    "A bishop of Prusa destroying a great serpent by the sign of the Cross, preaching Christ under Julian the Apostate, crowned with martyrdom by the sword.": "십자성호로 큰 뱀을 없애는 프루사의 주교, 배교자 율리아누스 아래에서 그리스도를 전하고, 칼로 순교의 관을 받는다.",
    "A bishop of Prusa standing unharmed in the boiling spring, preaching the God who made both the healing waters and the fire of hell, his three presbyters crowned beside him.": "끓는 샘 속에 상함 없이 선 프루사의 주교, 치유의 물과 지옥의 불을 함께 지으신 하느님을 전하고, 그 곁에서 세 사제가 관을 받는다.",
    "A bishop of Rome in the omophorion holding a Gospel, with a martyr's palm.": "견대를 걸치고 복음서를 든 로마의 주교, 순교자의 종려나무 가지를 지녔다.",
    "A bishop of Rome of the age of the martyrs, shepherding his flock in the catacombs, bringing the noble and the humble alike to the faith of Christ.": "순교자들의 시대에 산 로마의 주교, 카타콤바에서 자기 무리를 돌보고, 귀한 이와 미천한 이를 한가지로 그리스도의 신앙으로 이끈다.",
    "A bishop of Rostov preaching Christ to the half-pagan land, the idols thrown down and the churches rising, the grace of wonders confirming the word of the Caves-trained shepherd.": "반쯤 이교로 남은 땅에 그리스도를 전하는 로스토프의 주교, 우상들이 무너지고 성당들이 일어서며, 기적의 은총이 동굴에서 배운 목자의 말씀을 굳혀 준다.",
})

TEXT.update({
    "A bishop of Rostov whose very funeral became a glorification, wonders flowing from his body before burial, the shepherd of the yoke-time honored as a saint from the hour of his death.": "장례 자체가 영광이 된 로스토프의 주교, 묻히기 전에 그 몸에서 기적이 흘러나오고, 멍에의 시대의 목자가 죽은 그 시각부터 성인으로 공경받는다.",
    "A bishop of Salamis with the five tongues of his learning and the Panarion of his refutations, the ascetic of the Palestinian desert crowned with the long white rule of Cyprus.": "다섯 언어의 학식과 반박의 파나리온을 지닌 살라미스의 주교, 팔레스타인 사막의 고행자가 키프로스에서 길고 흰 다스림으로 관을 받는다.",
    "A bishop of Samosata refusing to surrender the record of the faith though his hand be cut off, traveling in disguise to strengthen the Orthodox, crowned by the tile of an Arian.": "손이 잘리더라도 신앙의 기록을 내어 주기를 거부하는 사모사타의 주교, 변장하고 다니며 정교인들을 굳세게 하다가 아리우스파의 기왓장에 관을 받는다.",
    "A bishop of Sardis scourged for Christ, the dry wooden stake stained with his blood taking root and growing into a green tree of healing beside him.": "그리스도를 위하여 매 맞은 사르디스의 주교, 그의 피로 물든 마른 나무 말뚝이 뿌리를 내려 그 곁에서 치유의 푸른 나무로 자란다.",
    "A bishop of Synnada bearing the icons he defended, the courts of caliph and emperor behind him, the exile that crowned his confession before him.": "자기가 지킨 이콘들을 든 시나다의 주교, 그 뒤에 칼리프와 황제의 궁정이 있고, 그 앞에 그의 고백에 관을 씌운 유배가 있다.",
    "A bishop of Tver reconciling princes with the Gospel between them, the Zheltikov monastery rising by the river, the Kyiv Caves Paterikon copied out under his hand.": "복음을 사이에 두고 공후들을 화해시키는 트베르의 주교, 강가에 젤티코프 수도원이 일어서고, 그의 손 아래에서 키예프 동굴 파테리콘이 옮겨 적힌다.",
    "A bishop of Verona with a fishing rod and a line of catechumens for his catch, the Adige rising in flood behind him and standing like a wall at the open doors of his church.": "낚싯대를 들고 예비신자들의 줄을 어획으로 삼는 베로나의 주교, 그 뒤에서 아디제 강이 넘쳐 오르다가 그의 성당 열린 문 앞에서 성벽처럼 멈춰 선다.",
    "A bishop of Vladimir with the founding letter of the Caves Paterik in his hand, his friend Polikarp cautioned against vainglory, the Near Caves receiving the author home to the monastery of his heart.": "동굴 파테리크의 창시가 된 편지를 손에 든 블라디미르의 주교, 그의 벗 폴리카르프는 헛된 영광을 경계하라는 말을 듣고, 가까운 동굴이 그 지은이를 제 마음의 수도원으로 맞아들인다.",
    "A bishop of ascetic countenance in the omophorion, blessing, his incorrupt relics in a shrine.": "견대를 걸치고 축복하는 고행자다운 얼굴의 주교, 그의 썩지 않은 유물이 성소에 있다.",
    "A bishop of gentle countenance distributing alms, a schema laid ready beside his omophorion.": "자선을 나누어 주는 온화한 얼굴의 주교, 그의 견대 곁에 대수도자 품의 옷이 준비되어 놓여 있다.",
    "A bishop of the Black Sea coast with his city walls behind him, Saracen raiders scattered by his prayer, the northern raiders frozen at his sepulcher until the captives go free.": "뒤에 자기 성벽을 둔 흑해 연안의 주교, 그의 기도에 사라센의 침략자들이 흩어지고, 북방의 침략자들은 포로들이 풀려날 때까지 그의 무덤 앞에서 얼어붙는다.",
    "A bishop of the Crimean Goths defending the holy icons, consecrated in Orthodox Georgia, sharing the sufferings of his people under the Khazar yoke.": "거룩한 이콘을 지키는 크림 고트인의 주교, 정교의 조지아에서 축성되었고, 하자르의 멍에 아래에서 제 백성의 고난을 함께 나눈다.",
    "A bishop of the Hellespont in chains for the icons, the letters of Theodore the Studite in his hands.": "이콘을 위하여 쇠사슬에 매인 헬레스폰토스의 주교, 손에 스투디온의 테오도로의 편지들을 들었다.",
    "A bishop of the Hellespont on the road again, the iconoclasts' document forever unsigned behind him, the icon of Christ carried from refuge to refuge.": "다시 길 위에 선 헬레스폰토스의 주교, 그 뒤에 끝내 서명하지 않은 성상파괴자들의 문서가 있고, 그리스도의 이콘이 피난처에서 피난처로 옮겨진다.",
    "A bishop of the Nicene fathers leading the serpent by his staff into the fire, and on the mountain road the ambush of the heretics, the stone of the murderess turned against her until his grave healed her.": "지팡이로 뱀을 이끌어 불에 넣는 니케아 교부들 가운데 한 주교, 산길에서는 이단자들의 매복이 있고, 살해하려던 여인의 돌이 도리어 그를 치다가 그의 무덤이 그 여인을 고쳐 준다.",
    "A bishop of the Siberian frontier among the peoples of the east, the churches and schools of his planting behind him, the lamp of his night prayers burning over Irkutsk.": "동방의 백성들 가운데 있는 시베리아 변경의 주교, 그 뒤에 그가 세운 성당들과 학교들이 있고, 이르쿠츠크 위로 그의 밤기도의 등불이 타오른다.",
    "A bishop of the apostolic line blessing a bitter spring at Catania, the water running sweet and the city believing.": "카타니아에서 쓴 샘을 축복하는 사도 계승의 주교, 물이 달게 흐르고 도시가 믿는다.",
    "A bishop ordained by the hand of the Theologian, laying his own hand on the young Polycarp, a myrtle flowering from his tomb.": "신학자의 손으로 서품된 주교, 자기 손을 젊은 폴리카르포에게 얹으며, 그의 무덤에서 도금양이 꽃핀다.",
    "A bishop rapt in divine song at the funeral of the Theotokos, the apostles around the bier.": "하느님의 어머니의 장례에서 거룩한 노래에 사로잡힌 주교, 상여 둘레에 사도들이 있다.",
    "A bishop rising from a deep pit, the king with the face of a beast healed before him, a church shown from heaven.": "깊은 구덩이에서 올라오는 주교, 그 앞에서 짐승의 얼굴을 한 왕이 낫고, 하늘로부터 한 성당이 보인다.",
    "A bishop sailing upon his mantle across the lake, the city that expelled him kneeling on the shore.": "자기 망토를 타고 호수를 건너는 주교, 그를 내쫓은 도시가 물가에서 무릎 꿇는다.",
    "A bishop scourged with ox-hide thongs, the icon of Christ held fast in his hands through four exiles.": "쇠가죽 끈으로 매 맞은 주교, 네 번의 유배 내내 그리스도의 이콘을 손에 굳게 붙든다.",
    "A bishop serene in prison, the false witness healed and confessing, an open book of Ecclesiastes before him.": "감옥에서 평온한 주교, 거짓 증인이 낫고 자백하며, 그 앞에 코헬렛의 책이 펼쳐져 있다.",
    "A bishop set upon by schismatics with swords, praying for his murderers as he falls.": "칼을 든 분열자들에게 습격당한 주교, 쓰러지면서 자기를 죽이는 이들을 위하여 기도한다.",
    "A bishop standing unharmed in the flames with the sorcerer bound in his omophorion, the fire dividing the true wonder from the false before the whole city.": "불길 속에 상함 없이 선 주교, 마술사는 그의 견대에 묶여 있고, 불이 온 도시 앞에서 참된 기적과 거짓된 것을 갈라 놓는다.",
    "A bishop standing upon his mantle spread on the waters of the Oka, the Murom icon of the Mother of God in his hands, borne upstream to Ryazan, his innocence proclaimed by the wonder.": "오카 강 물 위에 편 자기 망토를 딛고 선 주교, 손에 무롬의 하느님의 어머니 이콘을 들고 물길을 거슬러 랴잔으로 옮겨지며, 그 기적이 그의 무죄를 알린다.",
    "A bishop struck down at the altar during the Divine Liturgy, angels receiving his soul.": "성찬예배 중에 제대에서 쓰러진 주교, 천사들이 그의 영혼을 받아들인다.",
    "A bishop tried by fire, beasts, and sword, the great company of five hundred forty-six confessors about him, Jerusalem's name upon a martyrdom the whole East shared.": "불과 짐승과 칼로 시험받은 주교, 그 둘레에 오백마흔여섯 증거자의 큰 무리가 있고, 온 동방이 함께한 순교 위에 예루살렘의 이름이 있다.",
    "A bishop upon a pillar with a pen, the paschal sermons streaming from his mouth like light, the prayer book of the faithful open at the prayers he wrote for every day of the week.": "붓을 들고 기둥 위에 선 주교, 부활의 설교가 빛처럼 그 입에서 흘러나오고, 그가 한 주의 날마다 지은 기도로 신자들의 기도서가 펼쳐져 있다.",
    "A bishop vested in the omophorion, with a short rounded beard, holding a Gospel book and blessing.": "견대를 걸치고 짧고 둥근 수염을 한 주교, 복음서를 들고 축복한다.",
    "A bishop washing the wounds of lepers with his own hands, then standing before Leo the Armenian foretelling his swift destruction, the fortress of his thirty-year exile behind him.": "자기 손으로 나병 환자의 상처를 씻는 주교, 이어 아르메니아인 레오 앞에 서서 그의 빠른 멸망을 예고하며, 그 뒤에 삼십 년 유배의 성채가 있다.",
    "A bishop who once wore Tatar chains preaching Christ in the Tatar tongue at Kazan, the Savior monastery rising in the kremlin, the sick of two faiths healed at his prayer.": "한때 타타르의 사슬을 찼던 주교가 카잔에서 타타르 말로 그리스도를 전하고, 크렘린 안에 구세주 수도원이 일어서며, 그의 기도에 두 신앙의 병자들이 낫는다.",
    "A bishop who was a surgeon, the omophorion over his shoulders and the healing of the sick in his hands, the prisons and exiles of his confession behind him, the light of Christ in a godless age.": "외과 의사였던 주교, 어깨에 견대를 걸치고 손에는 병자의 치유가 있으며, 그 뒤에 그의 고백이 치른 감옥과 유배가 있고, 하느님 없는 시대에 그리스도의 빛이 있다.",
    "A bishop with a Gospel preaching to the people of Volhynia, a cave monastery in the distance.": "복음서를 들고 볼히니아 백성에게 전하는 주교, 멀리 동굴 수도원이 있다.",
    "A bishop with a company of one hundred ninety-nine disciples, the sign of the Cross that saved him in battle above, the swords of Sicily gathering the whole school into one harvest.": "백아흔아홉 제자의 무리와 함께 있는 주교, 위에는 전투에서 그를 구한 십자성호가 있고, 시칠리아의 칼들이 그 학교 전체를 한 번의 수확으로 거둔다.",
    "A bishop with a high domed forehead and short pointed beard, a thin ascetic face, vested in the omophorion and holding a Gospel book.": "높고 둥근 이마에 짧고 뾰족한 수염을 한 주교, 여윈 고행자의 얼굴로 견대를 걸치고 복음서를 들었다.",
    "A bishop with a lamp, a serpent fleeing before him, the island of Crete behind.": "등불을 든 주교, 그 앞에서 뱀이 달아나고, 뒤에 크레타 섬이 있다.",
    "A bishop with a long dark tapering beard and high forehead, vested in the omophorion, holding a Gospel book and blessing.": "길고 검은 끝이 가는 수염에 높은 이마를 한 주교, 견대를 걸치고 복음서를 들고 축복한다.",
    "A bishop with the Prologue open in his hands, the lake of Ohrid behind one shoulder and the wire of Dachau behind the other, preaching Christ to the peoples in every tongue he knew.": "프롤로그를 펼쳐 든 주교, 한 어깨 뒤에 오흐리드 호수가, 다른 어깨 뒤에 다하우의 철조망이 있고, 자기가 아는 모든 말로 백성들에게 그리스도를 전한다.",
    "A bishop with the marks of long warfare, demons fleeing behind him, angels and the Theotokos receiving his soul before him.": "오랜 싸움의 자국을 지닌 주교, 그 뒤에서 마귀들이 달아나고, 그 앞에서 천사들과 하느님의 어머니가 그의 영혼을 맞아들인다.",
})

TEXT.update({
    "A bishop with the paschal fire blazing on the hill of Slane against the high king's darkness, the shamrock of the Trinity in his hand, the tribes of Ireland kneeling to the font.": "상왕의 어둠에 맞서 슬레인 언덕에서 부활의 불을 지피는 주교, 손에 삼위일체의 세잎클로버를 들었고, 아일랜드의 부족들이 세례반 앞에 무릎 꿇는다.",
    "A bishop with verses branded upon his face, holding an icon of Christ and a scroll of canons.": "얼굴에 시구가 새겨진 주교, 그리스도의 이콘과 교회법 두루마리를 들었다.",
    "A bishop writing canons at a desk, the Theotokos appearing to bless him.": "책상에서 교회법을 쓰는 주교, 하느님의 어머니가 나타나 그를 축복한다.",
    "A bishop's omophorion hidden beneath a novice's habit, an aged hesychast silent in his cell at the Lavra.": "초심자의 옷 아래 감춘 주교의 견대, 라브라의 자기 방에서 침묵하는 늙은 헤시카스트.",
    "A bishop, a deacon, a servant, and a holy woman crowned together amid flames at Pergamum.": "페르가몬에서 불길 가운데 함께 관을 받은 주교와 부제와 종과 거룩한 여인.",
    "A bishop-ascetic in chains beneath an iron cage, Saint George leading him from childhood as a companion, the possessed freed and the storms stilled at his prayer, the resigned omophorion folded beside the hermit's cave.": "쇠 우리 아래 사슬에 묶인 고행자 주교, 성 게오르기가 어린 시절부터 동행으로 그를 이끌고, 그의 기도에 사로잡힌 이들이 풀려나며 폭풍이 잦아들고, 은수처 동굴 곁에 내려놓은 견대가 접혀 있다.",
    "A bishop-confessor bearing the marks of his wounds, holding a Gospel.": "자기 상처의 자국을 지닌 증거자 주교, 복음서를 들었다.",
    "A bishop-envoy on the road between empires, gifts flowing through his hands to the poor of his city.": "제국들 사이의 길에 선 사절 주교, 그의 손을 거쳐 선물이 제 도시의 가난한 이들에게 흘러간다.",
    "A bishop-martyr barring an emperor from the church doors, three youths and their mother beside him.": "황제를 성당 문 앞에서 막아서는 순교자 주교, 그 곁에 세 젊은이와 그들의 어머니가 있다.",
    "A bishop-martyr by the sea, ships in the distance, flames beneath his feet trampled down.": "바닷가의 순교자 주교, 멀리 배들이 있고, 그 발 아래 불길이 짓밟혀 있다.",
    "A bishop-martyr holding a Gospel, a lion at his feet praising God.": "복음서를 든 순교자 주교, 그 발치에서 사자가 하느님을 찬양한다.",
    "A bishop-martyr in the omophorion holding a Gospel and a cross.": "견대를 걸치고 복음서와 십자가를 든 순교자 주교.",
    "A bishop-martyr in the omophorion holding a Gospel or a scroll inscribed against heresy.": "견대를 걸치고 복음서나 이단을 반박하는 두루마리를 든 순교자 주교.",
    "A bishop-martyr in the omophorion holding a Gospel or a scroll on the unity of the Church.": "견대를 걸치고 복음서나 교회의 일치에 관한 두루마리를 든 순교자 주교.",
    "A bishop-martyr in the omophorion holding a Gospel, a burning church in the background.": "견대를 걸치고 복음서를 든 순교자 주교, 뒤에 불타는 성당이 있다.",
    "A bishop-martyr in the omophorion holding a Gospel, sometimes with a ship or flames.": "견대를 걸치고 복음서를 든 순교자 주교, 때로는 배나 불길과 함께 있다.",
    "A bishop-martyr in the omophorion holding a Gospel, with his three companions and tamed beasts.": "견대를 걸치고 복음서를 든 순교자 주교, 세 동료와 길들여진 짐승들과 함께 있다.",
    "A bishop-martyr with a soldier and four women, all crowned together.": "한 군인과 네 여인과 함께 모두 관을 받은 순교자 주교.",
    "A bishop-martyr with a young nun and two servants, holding crosses.": "젊은 수녀와 두 종과 함께 십자가를 든 순교자 주교.",
    "A bishop-physician and his sister holding crosses, his hands extended in healing.": "십자가를 든 의사 주교와 그의 누이, 그의 손이 치유를 위하여 펼쳐져 있다.",
    "A bishop-physician at the Persian court, the king healed and the hidden trickster unearthed from beneath the temple floor, caravans of martyrs' relics entering the city of his name.": "페르시아 궁정의 의사 주교, 왕이 낫고 신전 바닥 밑에서 숨은 사기꾼이 드러나며, 순교자들의 유물을 실은 대상들이 그의 이름을 딴 도시로 들어온다.",
    "A bishop-physician in a mountain cave with the wild beasts gathered gently around him, a child healed of a choking bone, seven women and two children crowned beside him.": "산속 동굴에서 들짐승들이 순하게 둘러앉은 가운데 있는 의사 주교, 뼈가 목에 걸린 아이가 낫고, 일곱 여인과 두 아이가 그 곁에서 관을 받는다.",
    "A blind eldress seated small and radiant in a Moscow room, the lines of the troubled stretching through the Soviet dark to her door, her closed eyes seeing all of it in God.": "모스크바의 한 방에 작고 빛나게 앉은 눈먼 장로 여인, 소비에트의 어둠을 뚫고 괴로운 이들의 줄이 그의 문까지 이어지며, 감긴 그의 눈이 하느님 안에서 그 모두를 본다.",
    "A boy bishop-to-be praying before an emptied granary as it fills again, coins and wine multiplying in his open hands.": "비워진 곳간 앞에서 기도하니 다시 채워지는, 뒷날 주교가 될 소년, 펼친 그의 손에서 돈과 포도주가 불어난다.",
    "A boy confessing Christ with his tutor Modestus and nurse Crescentia beside him, the cauldron and the beasts before them, the child and his guardians crowned together.": "스승 모데스토와 유모 크레스켄티아를 곁에 두고 그리스도를 고백하는 소년, 그 앞에 가마솥과 짐승들이 있고, 아이와 그를 지킨 이들이 함께 관을 받는다.",
    "A boy in peasant dress with a harrow, lightning above, angels receiving his soul.": "써레를 든 농부 차림의 소년, 위에 번개가 치고, 천사들이 그의 영혼을 맞아들인다.",
    "A boy martyr with a white dove above him, water springing from the rock at his prayer, the lion of his mountain cave refusing to harm him in the arena.": "위에 흰 비둘기를 둔 소년 순교자, 그의 기도에 바위에서 물이 솟고, 그의 산속 동굴에 살던 사자가 원형 경기장에서 그를 해치기를 마다한다.",
    "A boy prince in royal robes bearing the palm of the passion-bearer, the yard of Uglich behind him where he fell, his incorrupt relics enshrined in the Kremlin to confound the pretenders.": "왕의 옷을 입고 수난자의 종려나무 가지를 든 소년 공, 그 뒤에 그가 쓰러진 우글리치의 뜰이 있고, 썩지 않은 그의 유물이 참칭자들을 무색하게 하려고 크렘린에 모셔진다.",
    "A bread merchant with pierced hands and feet, walking his last steps for Christ.": "손과 발이 꿰뚫린 빵 장수, 그리스도를 위하여 마지막 걸음을 걷는다.",
    "A bridegroom and bride in virginal crowns, the lion guarding Daria's honor, the tribune Claudius converted with his whole house, the sand pit of the Via Salaria closing over the two alive.": "동정의 관을 쓴 신랑과 신부, 사자가 다리아의 정절을 지키고, 천부장 클라우디오가 온 집안과 함께 회심하며, 살라리아 가도의 모래 구덩이가 산 두 사람 위로 닫힌다.",
    "A brother and sister crowned as martyrs, holding crosses and palms.": "십자가와 종려나무 가지를 들고 순교자로 관을 받은 오누이.",
    "A brother and sister martyrs, he upon a tree, she with a spear, both crowned.": "남매 순교자, 오라비는 나무 위에, 누이는 창에 찔려, 둘 다 관을 받는다.",
    "A canonarch of the Far Caves directing the chanting of the brethren, the book of the services in his hand, the monastic life embraced from his childhood.": "형제들의 노래를 이끄는 먼 동굴의 선창자, 손에 예배서를 들었고, 어린 시절부터 수도 생활을 받아들였다.",
    "A captain of the guard bound to a tree and shot with arrows, the widow Irene tending him, his converted companions with their crowns around him.": "나무에 묶여 화살을 맞은 근위대장, 과부 이리나가 그를 돌보고, 회심한 그의 동료들이 관을 쓰고 둘레에 있다.",
    "A cathedral in flames on the night of the Nativity, the bishop baptizing and communing the multitude within, twenty thousand crowns rising in the smoke.": "성탄 밤에 불타는 대성당, 그 안에서 주교가 무리에게 세례를 주고 성체를 나누며, 이만 개의 관이 연기와 함께 올라간다.",
    "A centurion striding from the desert into the crowded amphitheater, proclaiming Christ before the astonished city.": "사막에서 붐비는 원형 경기장으로 걸어 들어가 놀란 도시 앞에서 그리스도를 선포하는 백부장.",
    "A centurion with spear at the foot of the Cross, his eyes lifted to the Crucified, confessing.": "십자가 밑에 창을 들고 선 백부장, 눈을 들어 십자가에 달리신 분을 우러러 고백한다.",
    "A church at Nicopolis in Armenia": "아르메니아 니코폴리스의 성당",
    "A church built over his grave at Skepsis": "스켑시스에 있는 그의 무덤 위에 세워진 성당",
    "A church in her honor at Chalcedon by 450": "450년까지 칼케돈에 세워진 그를 기리는 성당",
})

TEXT.update({
    "A church in his honor at Constantinople": "콘스탄티노폴리스에 세워진 그를 기리는 성당",
    "A church sexton in poor clothing, a princely ring and gold chain revealed beside his coffin.": "허름한 옷을 입은 성당 관리인, 그의 관 곁에 공후의 반지와 금줄이 드러나 있다.",
    "A church was later raised over their burial place": "뒷날 그들의 매장지 위에 성당이 세워졌다",
    "A church was raised over their grave by Saint John Chrysostom": "성 요한 크리소스토모가 그들의 무덤 위에 성당을 세웠다",
    "A clergyman of Hagia Sophia radiant in his enclosed cell, a lamp newly kindled in the great city.": "하기아 소피아의 성직자가 자기 닫힌 방에서 빛나니, 큰 도시에 새로 켜진 등불이다.",
    "A commander and his son with seventy soldiers, bound to the trees of the marsh, the ten-day martyrdom of the smallest executioners, seventy-two crowns over the swamp.": "일흔 명의 군사와 함께 있는 지휘관과 그의 아들, 늪의 나무들에 묶여 가장 작은 처형자들에게 열흘의 순교를 당하고, 늪 위로 일흔두 개의 관이 오른다.",
    "A company of martyrs holding crosses amid flames.": "불길 가운데 십자가를 든 순교자들의 무리.",
    "A company of martyrs with hands raised amid flames, an angel above bearing crowns.": "불길 가운데 손을 들어 올린 순교자들의 무리, 위에서 천사가 관을 들고 있다.",
    "A company of monks bearing icons and the marks of mutilation, crowned together after their father Stephen.": "이콘을 들고 절단의 자국을 지닌 수도자들의 무리, 그들의 아버지 스테파노를 뒤따라 함께 관을 받는다.",
    "A company of one hundred twenty captives of Persia, nine consecrated virgins among them, refusing the worship of fire and sun, one crown descending in a hundred twenty parts.": "페르시아에 사로잡힌 백스무 명의 무리, 그 가운데 봉헌된 아홉 동정녀가 있고, 불과 해에 대한 경배를 거부하니, 하나의 관이 백스무 몫으로 내려온다.",
    "A company of soldier-martyrs of Sebaste laying down their military belts, fire and sword behind them.": "군대 띠를 내려놓는 세바스테의 군인 순교자들의 무리, 그 뒤에 불과 칼이 있다.",
    "A company of virgin-martyrs led by two, crowned, the churches of Etchmiadzin behind them.": "두 사람이 이끄는 동정 순교녀들의 무리, 관을 받았고, 그 뒤에 에치미아진의 성당들이 있다.",
    "A convert of Britain in the priest's cloak giving himself up in the priest's place, led to the hill above the city, the first martyr of the land crowned by the sword.": "사제의 겉옷을 입고 사제 대신 자수한 브리튼의 개종자, 도시 위 언덕으로 끌려가, 그 땅의 첫 순교자로 칼에 관을 받는다.",
    "A court official in fine dress holding a cross, a small church beside him.": "고운 옷을 입고 십자가를 든 궁정 관리, 그 곁에 작은 성당이 있다.",
    "A courtier and his bride exchanging rings for monastic crowns, the Chronography open on his desk, the prison of Leo the Armenian and the island of his exile behind.": "반지를 수도의 관과 맞바꾸는 궁정인과 그의 신부, 그의 책상에 연대기가 펼쳐져 있고, 뒤에 아르메니아인 레오의 감옥과 그의 유배지 섬이 있다.",
    "A courtier casting his belt and mantle at the emperor's feet, declaring himself a soldier of the Heavenly King, the cage of fire receiving him.": "황제의 발 앞에 자기 띠와 망토를 던지며 하늘 임금의 군사라 선언하는 궁정인, 불의 우리가 그를 받아들인다.",
    "A courtier of Maximian with his mother's letter open in his hands, the denied Christ confessed again, the sword of Nicomedia completing his repentance.": "어머니의 편지를 펼쳐 든 막시미아누스의 궁정인, 부인했던 그리스도를 다시 고백하고, 니코메디아의 칼이 그의 회개를 이룬다.",
    "A courtier with a prince and princess of Persia, all three holding crosses.": "페르시아의 공과 공주와 함께 있는 궁정인, 셋 다 십자가를 들었다.",
    "A courtier-martyr before the emperor, a multitude of crucified soldiers behind him.": "황제 앞에 선 순교자 궁정인, 그 뒤에 십자가에 달린 수많은 군사가 있다.",
    "A crowned king with harp and scroll of the Psalms, the shepherd's sling at his feet, the Son of David foreshown above his throne.": "수금과 시편 두루마리를 든 관 쓴 임금, 그 발치에 목자의 물매가 있고, 그의 좌 위에 다윗의 자손이 미리 보인다.",
    "A crowned prince in royal robes holding a cross and a church, with a long beard.": "십자가와 성당을 들고 왕의 옷을 입은 관 쓴 공, 긴 수염을 하고 있다.",
    "A crowned prince in royal robes holding a model of a church, and sometimes a sword or cross.": "성당 모형을 들고 왕의 옷을 입은 관 쓴 공, 때로는 칼이나 십자가도 함께 든다.",
    "A crowned princess in royal robes holding a cross and a model of a church.": "십자가와 성당 모형을 들고 왕의 옷을 입은 관 쓴 공주.",
    "A dark-skinned monk-priest in the schema, of humble and peaceful aspect, holding a scroll.": "대수도자 품의 옷을 입은 검은 피부의 수도 사제, 겸손하고 평온한 모습으로 두루마리를 들었다.",
    "A deacon and his jailer bound in one net above the Danube, the third-day promise shining over the water.": "다뉴브 강 위에서 한 그물에 함께 묶인 부제와 그의 옥지기, 물 위로 사흘의 약속이 빛난다.",
    "A deacon baptizing the Ethiopian eunuch beside a chariot on the desert road.": "사막 길가에서 수레 곁에 있는 에티오피아 내시에게 세례를 주는 부제.",
    "A deacon in a sticharion holding the Gospel book, sometimes with the book hung about his neck.": "장백의를 입고 복음서를 든 부제, 때로는 그 책을 목에 걸고 있다.",
    "A deacon of Heliopolis given to the mob under Julian, the broken idols of his youth held against him, the crowns descending on him and the martyrs of Gaza and Ascalon.": "율리아누스 아래에서 군중에게 넘겨진 헬리오폴리스의 부제, 젊은 날 그가 부순 우상들이 그의 죄목이 되고, 그와 가자와 아스칼론의 순교자들 위로 관이 내려온다.",
    "A deacon of Rome confessing Christ in chains, his fellow-martyrs and the princess Artemia gathered about him, the crown of the Roman confessors descending.": "사슬에 묶여 그리스도를 고백하는 로마의 부제, 그 둘레에 동료 순교자들과 아르테미아 공주가 모이고, 로마 증거자들의 관이 내려온다.",
    "A deacon of the Near Caves at his fast, the lamp of the Egyptian Macarius shining upon his namesake's exploit.": "단식 중인 가까운 동굴의 부제, 이집트의 마카리오의 등불이 그 이름을 이은 이의 수고를 비춘다.",
    "A deacon of the Near Caves with censer and lifted hands, every petition granted, the martyr's crown above his diaconal orarion.": "향로를 들고 손을 든 가까운 동굴의 부제, 그의 청이 모두 이루어지고, 그의 부제 영대 위에 순교자의 관이 있다.",
    "A deacon of the caves standing at prayer on the ambo, demons fleeing from the sick brought to him.": "독경대 위에서 기도하며 선 동굴의 부제, 그에게 데려온 병자들에게서 마귀들이 달아난다.",
    "A deacon of the first seven with the vessels of service, the stones of Stephen's day falling upon the whole company.": "섬김의 그릇을 든 첫 일곱 부제 가운데 한 사람, 스테파노의 날의 돌이 그 무리 전체 위에 떨어진다.",
    "A deacon on the ambo with a scroll, the Theotokos above giving him the scroll to eat.": "두루마리를 들고 독경대에 선 부제, 위에서 하느님의 어머니가 그에게 두루마리를 먹으라고 주신다.",
    "A deacon upon a gridiron, angels filling his prison with light.": "석쇠 위에 놓인 부제, 천사들이 그의 감옥을 빛으로 채운다.",
    "A deacon with severed tongue still praising God, a child-martyr beside him, a prison rope above.": "혀가 잘리고도 하느님을 찬양하는 부제, 그 곁에 어린 순교자가 있고, 위에 감옥의 밧줄이 있다.",
    "A deacon with the harp of hymnody, tears on his face and the Lenten prayer on his scroll, the schools of Nisibis and Edessa singing behind him.": "찬가의 수금을 든 부제, 얼굴에 눈물이 있고 두루마리에 대재의 기도가 적혀 있으며, 그 뒤에서 니시비스와 에데사의 학교들이 노래한다.",
    "A deacon-bishop standing unharmed in a red-hot furnace, the crown descending upon him through the flames.": "벌겋게 달군 화덕 속에 상함 없이 선 부제 주교, 불길을 뚫고 관이 그에게 내려온다.",
    "A deacon-martyr in the sticharion holding a censer and a cross, stones at his feet.": "장백의를 입고 향로와 십자가를 든 순교자 부제, 그 발치에 돌들이 있다.",
    "A deaconess in a maphorion holding a scroll, sometimes shown with Saint John Chrysostom.": "마포리온을 쓰고 두루마리를 든 여부제, 때로는 성 요한 크리소스토모와 함께 그려진다.",
})

TEXT.update({
    "A deaconess of Nisibis among the consecrated women of her founding, the Scriptures open in her hands, the daughters of the border city gathered into one prayer.": "자기가 세운 봉헌된 여인들 가운데 있는 니시비스의 여부제, 손에 성경을 펼쳐 들었고, 변경 도시의 딸들이 한 기도로 모여 있다.",
    "A deaconess with lifted hands, the idol of Apollo shattered behind her, her converted torturers crowned beside her, a lion at her feet.": "손을 든 여부제, 그 뒤에 아폴론의 우상이 부서져 있고, 회심한 고문하던 이들이 그 곁에서 관을 받으며, 발치에 사자가 있다.",
    "A deported bishop with his presbyter and deacon and the long column of captives behind them, the sun of Persia refused its worship, the whole caravan crowned.": "자기 사제와 부제와 함께 끌려가는 주교, 그 뒤에 포로들의 긴 행렬이 있고, 페르시아의 해에 대한 경배를 거부하니 온 무리가 관을 받는다.",
    "A deposed archbishop of Novgorod in monastic simplicity at the Trinity Lavra, his omophorion laid aside, his forgiveness extended and received.": "삼위일체 라브라에서 수도자의 소박함 가운데 있는 폐위된 노브고로드의 대주교, 견대를 내려놓았고, 용서를 베풀며 또한 받는다.",
    "A desert abbot by the Jordan drawing a thorn from a lion's paw, the lion tending the monastery donkey, and lying dead upon its master's grave.": "요르단 강가에서 사자의 발에서 가시를 뽑는 사막의 수도원장, 사자가 수도원의 나귀를 돌보고, 제 주인의 무덤 위에서 죽어 눕는다.",
    "A desert elder gripping the bridle of the emperor Valens on the march, the fire of Adrianople foretold behind him, the first monastery of the City rising at his word.": "행군 중인 황제 발렌스의 고삐를 붙잡는 사막의 장로, 그 뒤에 아드리아노폴리스의 불이 예고되고, 그의 말에 따라 도성의 첫 수도원이 일어선다.",
    "A desert father of the first generation, his cell among his companions', the sand smoothing every record but the crown.": "첫 세대의 사막 교부, 동료들 사이에 자기 방이 있고, 모래가 관 말고는 모든 기록을 지워 간다.",
    "A desert monk at the walls of the great city, healing a blind youth, his cave-shrine at Loutraki shown above.": "큰 도성의 성벽 앞에 선 사막의 수도자, 눈먼 젊은이를 고치고, 위에 루트라키의 동굴 성소가 보인다.",
    "A desert mother teaching a circle of women in a tomb-cell, fire kindling through smoke in her open hand.": "무덤 방에서 여인들의 무리를 가르치는 사막의 어머니, 펼친 그의 손에서 연기를 뚫고 불이 붙는다.",
    "A desert-dweller of the northern forests in the schema, a small cell among pines behind him.": "대수도자 품의 옷을 입은 북방 숲의 광야 거주자, 그 뒤 소나무 사이에 작은 방이 있다.",
    "A dignified elder of the Sanhedrin, sometimes shown at the burial of Christ bearing myrrh, holding a cross.": "산헤드린의 위엄 있는 원로, 때로는 몰약을 들고 그리스도의 장례에 있는 모습으로 그려지며, 십자가를 들었다.",
    "A dignitary in armor and cloak of office, holding a cross, a great stone above him.": "갑옷과 관복 차림의 고관, 십자가를 들었고, 그 위에 큰 돌이 있다.",
    "A disciple of Pachomius carrying on the common life, the virtue that earned him the name Sanctified shining in the ordered ranks of the Tabennisiot monks.": "파코미오의 제자로서 공주 생활을 이어 가는 이, 그에게 성화된 자라는 이름을 얻게 한 덕이 타벤니시 수도자들의 정연한 대열 속에 빛난다.",
    "A disciple of Saint Sergius carrying logs on foot through the stream to build his monastery, the house of Peshnosha rising from the marsh, the tradition of Radonezh planted anew.": "자기 수도원을 지으려고 걸어서 개울을 건너며 통나무를 나르는 성 세르기오의 제자, 늪에서 페슈노샤의 집이 일어서고, 라도네시의 전통이 새로 심긴다.",
    "A disciple of Saint Sergius set by Metropolitan Alexis over the new monastery of the Savior, the Icon Not-made-by-hands above the gate, the house that would shelter Andrei Rublev.": "알렉시 수도 대주교에게서 구세주의 새 수도원을 맡은 성 세르기오의 제자, 문 위에 사람 손으로 만들지 않은 이콘이 있고, 뒷날 안드레이 루블료프를 품을 집이다.",
    "A disciple of Saint Varlaam of Khutyn who chose purity from his youth, founding a monastery in the wilderness of the Robeika, a bright lamp of Great Novgorod.": "어린 시절부터 정결을 택한 흐르티노의 성 바를라암의 제자, 로베이카 광야에 수도원을 세우니, 대 노브고로드의 밝은 등불이다.",
    "A disciple of Saint Varlaam of Khutyn withdrawing to the shore of Lake Dymskoye, an iron cap upon his head, the monastery rising in the wilderness he hallowed.": "디므스코예 호숫가로 물러난 흐르티노의 성 바를라암의 제자, 머리에 쇠 모자를 쓰고, 그가 거룩하게 한 광야에 수도원이 일어선다.",
    "A disciple of Sergius deep in the Obnora forests, the peasant who found him kneeling for a blessing, the grove of his retreats standing behind the monastery the crowds compelled.": "오브노라 숲 깊이 들어간 세르기오의 제자, 그를 찾아낸 농부가 축복을 받으려고 무릎 꿇고, 무리가 떠밀어 세운 수도원 뒤에 그가 물러나 있던 숲이 서 있다.",
    "A disciple of Sergius planting the Forerunner's monastery by the iron bogs of Kostroma, the wilderness lineage of the Trinity carried north in one obedient life.": "코스트로마의 철 늪가에 선구자의 수도원을 심는 세르기오의 제자, 삼위일체의 광야 혈통이 순종하는 한 생애로 북방에 이어진다.",
    "A disciple of the great Alexander founding a hermitage on the neck of land between two lakes, the Dormition church small among the Karelian pines.": "두 호수 사이의 땅목에 은수처를 세우는 대 알렉산드로의 제자, 카렐리아의 소나무들 사이에 작은 영면 성당이 있다.",
    "A disheveled ascetic in rags feigning folly, blessing, his companion John shown as a desert hermit.": "누더기를 걸치고 바보인 체하며 축복하는 헝클어진 고행자, 그의 동료 요한은 사막의 은수자로 그려진다.",
    "A dying priest stretching his hand toward the deacon who will not forgive, the angel with the flaming spear between them, one man rising healed and one falling dead.": "용서하지 않으려는 부제를 향해 손을 뻗는 죽어 가는 사제, 그 사이에 불타는 창을 든 천사가 있고, 한 사람은 나아 일어나고 한 사람은 죽어 쓰러진다.",
    "A family of martyrs, a father, mother, and two sons, holding crosses.": "십자가를 든 순교자 가족, 아버지와 어머니와 두 아들이다.",
    "A faster of the Caves at his rule of prayer, bread and water in small measure beside him.": "기도 규칙을 지키는 동굴의 단식자, 그 곁에 적은 분량의 빵과 물이 있다.",
    "A faster of the Caves at his small bread and water, the appetite mastered like a broken horse, the lightness of the fasting spirit shining through the thinned body.": "적은 빵과 물 앞에 있는 동굴의 단식자, 길들인 말처럼 다스려진 식욕과, 여윈 몸을 뚫고 빛나는 단식하는 영의 가벼움.",
    "A faster of the Near Caves, his face bright with abstinence, bread and water his whole table.": "가까운 동굴의 단식자, 절제로 얼굴이 밝고, 빵과 물이 그의 온 밥상이다.",
    "A father and his young deacon-son together in the fire and the cauldron at Iconium, crowned in one confession.": "이코니온에서 불과 가마솥 속에 함께 있는 아버지와 그의 어린 부제 아들, 한 고백으로 관을 받는다.",
    "A father and his young son holding crosses, standing before a pagan idol.": "십자가를 들고 이교의 우상 앞에 선 아버지와 그의 어린 아들.",
    "A father, mother, and son holding crosses together.": "함께 십자가를 든 아버지와 어머니와 아들.",
    "A first bishop receiving his charge from the hand of the Apostle Paul, the young church of Seleucia gathered at his teaching.": "사도 바오로의 손에서 임무를 받는 첫 주교, 그의 가르침 앞에 셀레우키아의 어린 교회가 모여 있다.",
    "A first secretary of the empire in patriarchal vestments, the Seventh Ecumenical Council assembled at his word, the icons held up restored, the emperor's unlawful marriage refused his blessing.": "총대주교의 제의를 입은 제국의 수석 서기관, 그의 말에 제7차 세계 공의회가 모이고, 회복된 이콘들이 높이 들리며, 황제의 불법한 혼인은 그의 축복을 받지 못한다.",
    "A first-century bishop in the omophorion holding a Gospel book, sometimes with the Apostle Peter.": "견대를 걸치고 복음서를 든 1세기의 주교, 때로는 사도 베드로와 함께 있다.",
    "A fisherman-bishop healing the sick of the Hellespont, the demon fleeing his offered hospitality, idol temples falling and churches rising behind him.": "헬레스폰토스의 병자들을 고치는 어부 출신 주교, 그가 베푼 대접 앞에서 마귀가 달아나고, 그 뒤에서 우상의 신전들이 무너지고 성당들이 일어선다.",
    "A flute player casting down his pipes before the altar of the idols, the governor and his guards converted behind him, the sea receiving the last martyrs.": "우상의 제단 앞에 자기 피리를 던지는 피리 부는 이, 그 뒤에서 총독과 그의 호위병들이 회심하고, 바다가 마지막 순교자들을 받아들인다.",
    "A fool for Christ in a brushwood hut in the Rostov marsh, mockery and cold about him, the gift of prophecy shining through his feigned folly, the Ascension church rising on the waters over his rest.": "로스토프 늪의 나뭇가지 오두막에 있는 그리스도를 위한 바보, 조롱과 추위가 그를 둘러싸고, 꾸민 바보짓 사이로 예언의 은사가 빛나며, 그가 쉬는 물 위로 승천 성당이 일어선다.",
    "A fool for Christ of Ustyug in rags upon the hot stones of the oven, feigning madness by day and praying by night, the gift of prophecy shining beneath his poverty.": "누더기를 걸치고 화덕의 뜨거운 돌 위에 누운 우스튜그의 그리스도를 위한 바보, 낮에는 미친 체하고 밤에는 기도하며, 그의 가난 아래에서 예언의 은사가 빛난다.",
    "A fool in rags offering raw meat to the tsar in Lent, the city of Pskov standing unburned behind him, the Trinity cathedral receiving his body among the princes.": "대재에 차르에게 날고기를 내미는 누더기 차림의 바보, 그 뒤에 불타지 않은 프스코프 성이 서 있고, 삼위일체 대성당이 공후들 가운데 그의 몸을 받아들인다.",
    "A former courier of the emperor in a tomb-cell above Antioch, one borrowed book his library, no bed and no lamp his furnishings.": "안티오키아 위 무덤 방에 있는 황제의 옛 파발꾼, 빌려 온 책 한 권이 그의 서고이고, 침상도 등불도 없는 것이 그의 세간이다.",
    "A former equerry holding his martyred brother's head, the Boris and Gleb monastery of Torzhok rising behind him, the hospice door open to travelers.": "순교한 형의 머리를 든 옛 마부장, 그 뒤에 토르조크의 보리스와 글레브 수도원이 일어서고, 나그네를 위한 숙소의 문이 열려 있다.",
    "A former merchant in monastic habit, a purse laid aside at his feet, the caves behind him.": "수도복을 입은 옛 상인, 그 발치에 돈주머니가 놓여 있고, 뒤에 동굴들이 있다.",
})

TEXT.update({
    "A former pagan priest and his kinsmen confessing Christ at Ancyra, converted by the constancy of the martyrs, crowned together for the faith.": "안키라에서 그리스도를 고백하는 옛 이교 사제와 그의 친척들, 순교자들의 한결같음에 회심하여 신앙을 위하여 함께 관을 받는다.",
    "A former slave in a bishop's omophorion, the little epistle of Philemon in his hands, the chains of his first flight and his last confession joined into one crown.": "주교의 견대를 걸친 옛 종, 손에 필레몬에게 보낸 짧은 서간을 들었고, 처음 달아났을 때의 사슬과 마지막 고백이 한 관으로 이어진다.",
    "A former soldier turned monk copying books and turning wood at his lathe, in great poverty, refusing the priesthood out of humility, the monastery of Lukhov rising after him.": "수도자가 된 옛 군인이 책을 옮겨 적고 선반으로 나무를 깎으며, 큰 가난 속에서 겸손으로 사제직을 마다하고, 그가 떠난 뒤 루호프 수도원이 일어선다.",
    "A former tax-collector in penitential chains upon his pillar, the words of Isaiah that broke his heart shining above, the healings of the great penitent flowing from his cell.": "기둥 위에서 참회의 사슬을 두른 옛 세리, 그의 마음을 부순 이사야의 말씀이 위에 빛나고, 큰 참회자의 방에서 치유가 흘러나온다.",
    "A former tutor of emperors in a palm-plaiter's rags, his eyes worn with weeping, the three words of his rule shining about him: flee, be silent, be still.": "종려 잎을 엮는 이의 누더기를 걸친 황제들의 옛 스승, 눈은 울음으로 닳았고, 그의 규칙의 세 마디가 그를 둘러싸 빛난다. 달아나라, 침묵하라, 고요히 있으라.",
    "A founder bearing the Konevskaya icon from Athos to the island of Konevets, the monastery rising on Lake Ladoga, the pagan idol-rock of the island hallowed by the Mother of God.": "아토스에서 코네브스카야 이콘을 코네베츠 섬으로 옮겨 오는 창설자, 라도가 호수에 수도원이 일어서고, 섬의 이교 우상 바위가 하느님의 어머니로 거룩해진다.",
    "A founder of Athos beholding a column of light rising from the cliff, the monastery of the Forerunner built at that place, the chrysobull of the emperor in his hand.": "절벽에서 솟아오르는 빛기둥을 보는 아토스의 창설자, 그 자리에 선구자의 수도원이 세워지고, 손에 황제의 금인 칙서를 들었다.",
    "A founder of Torzhok holding the head of his martyred brother, the Boris and Gleb monastery rising behind him, his incorrupt relics uncovered and glorified.": "순교한 형의 머리를 든 토르조크의 창설자, 그 뒤에 보리스와 글레브 수도원이 일어서고, 썩지 않은 그의 유물이 드러나 영광을 받는다.",
    "A founder of the Onega island with the Nativity church rising behind him, the desolate rock of Palii filled with the brethren his holiness drew across the water.": "뒤에 성탄 성당이 일어서는 오네가 섬의 창설자, 그의 거룩함이 물 건너로 이끈 형제들로 팔리이의 헐벗은 바위가 채워진다.",
    "A founder of the Vologda forests with brush and panel writing an icon, the monastery of Glushitsa rising behind, the desert of the north filled with his disciples.": "붓과 판을 들고 이콘을 그리는 볼로그다 숲의 창설자, 뒤에 글루시차 수도원이 일어서고, 북방의 광야가 그의 제자들로 채워진다.",
    "A founder of the Vologda forests with the rule of his monastery in hand, the desert of Komel filled with the cells of his disciples, the multitude he enlightened gathered about their teacher.": "자기 수도원의 규칙을 손에 든 볼로그다 숲의 창설자, 코멜의 광야가 제자들의 방으로 채워지고, 그가 깨우친 무리가 스승 둘레에 모여 있다.",
    "A founder of the northern forests with his fellow Cyril, the Ferapontov monastery rising by the White Lake and the Luzhetsky at Mozhaisk, the desert settled by his labors.": "동료 키릴로와 함께 있는 북방 숲의 창설자, 백호 곁에 페라폰토프 수도원이, 모자이스크에 루제츠키 수도원이 일어서고, 그의 수고로 광야에 사람이 든다.",
    "A frail young monk handing his own will piece by piece to his elder, the icon of judgment that converted him behind, the great ascetics making room for him among the crowned.": "자기 뜻을 조각조각 장로에게 넘기는 연약한 젊은 수도자, 그 뒤에 그를 회심시킨 심판의 이콘이 있고, 큰 고행자들이 관 받은 이들 사이에 그의 자리를 내어 준다.",
    "A fuller with the cross painted openly upon his door, a stone and the sea awaiting him.": "자기 문 위에 십자가를 드러내어 그린 축융공, 돌 하나와 바다가 그를 기다린다.",
    "A gathering of the North American saints, Herman of Alaska, Innocent, Tikhon and others, against the American land, with the Theotokos above.": "북아메리카 성인들의 모임, 알래스카의 헤르만과 인노첸시오와 티혼과 그 밖의 이들이 아메리카 땅을 배경으로 서 있고, 위에 하느님의 어머니가 계신다.",
    "A gaunt ascetic in a cave, then borne upright in his shrine, the possessed healed at his relics.": "동굴 속의 여윈 고행자, 이어 자기 성소에 곧게 모셔지고, 그의 유물에서 사로잡힌 이들이 낫는다.",
    "A gaunt faster of the Caves, and beside him his beloved brother Paisius, one grave prepared for the two.": "동굴의 여윈 단식자, 그 곁에 사랑하던 형제 파이시오가 있고, 둘을 위하여 한 무덤이 마련되어 있다.",
    "A general in full armor with the serpent slain beneath him, golden idols broken into alms in his hands, the cross of his first martyrdom and the sword of his second behind.": "발밑에 죽인 뱀을 둔 완전 무장한 장군, 손에 부수어 자선으로 바꾼 금 우상들이 있고, 뒤에 그의 첫 순교의 십자가와 두 번째 순교의 칼이 있다.",
    "A general on horseback beholding a stag with the radiant Cross between its antlers.": "뿔 사이에 빛나는 십자가를 인 사슴을 바라보는 말 탄 장군.",
    "A gentle archbishop of Chernihiv with the Gospel, schools and restored monasteries behind him, his incorrupt relics radiant beneath.": "복음서를 든 체르니고프의 온화한 대주교, 뒤에 학교들과 다시 세운 수도원들이 있고, 아래에 썩지 않은 그의 유물이 빛난다.",
    "A gentle hegumen among his brethren, the gift of wonders resting on a life of hidden obedience, the icon of Christ held fast.": "형제들 가운데 있는 온화한 수도원장, 감추어진 순종의 삶 위에 기적의 은사가 머물고, 그리스도의 이콘을 굳게 붙들었다.",
    "A giant of fearsome countenance bearing the Child who carries the world, the flowering staff in his hand, the soldiers and the two women he converted gathered as his first harvest.": "세상을 지고 계신 아기를 업은 무서운 얼굴의 거인, 손에 꽃 핀 지팡이가 있고, 그가 회심시킨 군사들과 두 여인이 그의 첫 수확으로 모여 있다.",
    "A girl of thirteen with a lamb at her side, her loosened hair and a mantle of light covering her, the sword and the unharmed flame of her double contest behind.": "곁에 어린양을 둔 열세 살 소녀, 풀어 헤친 머리와 빛의 겉옷이 그를 덮고, 뒤에 그의 두 겹 싸움의 칼과 해치지 못한 불길이 있다.",
    "A girl of twelve confessing Christ before the governor, the heated rods and the flail before her, crowned as the bride of Christ, the young martyr of Byblos.": "총독 앞에서 그리스도를 고백하는 열두 살 소녀, 그 앞에 달군 쇠막대와 도리깨가 있고, 그리스도의 신부로 관을 받은 비블로스의 어린 순교자다.",
    "A grand duchess in royal robes, or in the monastic veil, holding a model of a church.": "왕의 옷을 입었거나 수도의 너울을 쓴 대공비, 성당 모형을 들었다.",
    "A grand princess in royal robes over a hair shirt and chains, the Ascension monastery of the Kremlin rising by her gift, a blind man receiving his sight at the hem of her garment.": "털옷과 사슬 위에 왕의 옷을 입은 대공비, 그의 기부로 크렘린에 승천 수도원이 일어서고, 눈먼 이가 그의 옷자락에서 시력을 받는다.",
    "A gray-haired prophet with rounded beard, his scroll proclaiming the judgment of Edom.": "둥근 수염을 한 백발의 예언자, 그의 두루마리가 에돔의 심판을 선포한다.",
    "A great assembly of monastic saints in tiers about Saint Anthony, the Lavra and its caves beneath them.": "성 안토니오 둘레에 층층이 모인 수도 성인들의 큰 무리, 그 아래에 라브라와 그 동굴들이 있다.",
    "A great hermit of the Egyptian desert rapt in the vision of Christ, his long fasts and his prayer for the fallen made visible, the glory of the desert fathers upon him.": "그리스도의 환시에 사로잡힌 이집트 사막의 큰 은수자, 그의 긴 단식과 넘어진 이들을 위한 기도가 드러나고, 사막 교부들의 영광이 그 위에 있다.",
    "A great lady of Justinian's court hidden as the eunuch monk of Scetis, Abba Daniel keeping her secret, the cave-cell of twenty-eight years opening at last upon her repose.": "스케티스의 내시 수도자로 몸을 감춘 유스티니아누스 궁정의 귀부인, 다니엘 압바가 그 비밀을 지켜 주고, 스물여덟 해의 동굴 방이 그의 안식에 이르러 마침내 열린다.",
    "A great man of Novgorod laying aside the honors of his office to take the monastic habit, the monastery of the Vaga rising from his lands, his last years given wholly to God.": "자기 직위의 영예를 내려놓고 수도복을 입는 노브고로드의 큰 인물, 그의 땅에서 바가의 수도원이 일어서고, 마지막 해들을 온전히 하느님께 드린다.",
    "A great martyr with a small vessel of medicine, prison doors open behind her, the four pillars and the fire of her end beneath her feet.": "작은 약병을 든 대순교녀, 그 뒤에 감옥 문이 열려 있고, 발 아래에 그의 마지막을 이룬 네 기둥과 불이 있다.",
    "A great prince fallen at the Sit river among his warriors, the burning cathedral of Vladimir holding his family behind him, his head restored to his body in the grave.": "자기 군사들 가운데 시트 강에서 쓰러진 대공, 그 뒤에 불타는 블라디미르 대성당이 그의 가족을 품고 있으며, 무덤에서 그의 머리가 몸에 다시 붙는다.",
    "A great princess in a nun's habit, the crown she lost laid aside, healings flowing from her tomb at the Protection convent.": "수녀의 옷을 입은 대공비, 잃은 관을 내려놓았고, 보호 수녀원의 그의 무덤에서 치유가 흘러나온다.",
    "A grieving father taking counsel of a veiled monk who is his own lost daughter, the revelation at her deathbed, the father finishing his days in her cell.": "너울 쓴 수도자에게 조언을 구하는 슬픔에 잠긴 아버지, 그 수도자가 바로 잃어버린 자기 딸이며, 임종의 자리에서 밝혀지고, 아버지는 그 방에서 여생을 마친다.",
    "A group of Slavic bishops and priests holding Gospel books and scrolls in Slavonic, Clement in the omophorion.": "슬라브어로 된 복음서와 두루마리를 든 슬라브 주교들과 사제들의 무리, 클레멘트가 견대를 걸치고 있다.",
    "A group of monk-martyrs holding crosses, illumined by light, before the desert monastery of David Gareji.": "십자가를 들고 빛에 싸인 수도 순교자들의 무리, 다윗 가레지의 사막 수도원 앞이다.",
    "A herdsman of Tekoa called from his flock and his sycamore figs to prophesy at Bethel, the plumb line of God's judgment in his hand, crying for justice to roll down like waters.": "자기 양 떼와 돌무화과나무에서 불리어 베텔에서 예언하는 트코아의 목자, 손에 하느님의 심판의 다림줄을 들고, 정의가 물처럼 흐르라고 외친다.",
    "A hermit by the Pshinja meeting a hunter who would be emperor, the monastery of his relics rising by the river in fulfillment.": "프신야 강가에서 뒷날 황제가 될 사냥꾼을 만나는 은수자, 그 말대로 강가에 그의 유물을 모신 수도원이 일어선다.",
    "A hermit dwelling in the branches of an almond tree by the wall of Thessaloniki, and holding live coals unharmed in his hands before the ruler, a wonder of the ascetic life.": "테살로니키 성벽 곁 편도나무 가지에 사는 은수자, 통치자 앞에서 숯불을 상함 없이 손에 드니, 고행 생활의 기적이다.",
})

TEXT.update({
    "A hermit dwelling in the hollow of a great oak by the river Vepreika, the deep forest about him, the hermitage of Kaluga rising from his solitude.": "베프레이카 강가의 큰 참나무 구멍 속에 사는 은수자, 그 둘레에 깊은 숲이 있고, 그의 홀로 있음에서 칼루가의 은수처가 일어선다.",
    "A hermit in a mountain wilderness fed by heaven, his relics borne in procession by tsars and hierarchs.": "하늘이 먹여 주는 산 광야의 은수자, 그의 유물을 차르들과 주교들이 행렬로 옮긴다.",
    "A hermit in a roofless stone enclosure, serpent bites healed by the sign of the cross, the dwellings of the blind beside his wall and their psalmody rising like a second sky.": "지붕 없는 돌 울타리 안의 은수자, 십자성호로 뱀에 물린 상처가 낫고, 그 담 곁에 눈먼 이들의 거처가 있어 그들의 시편 노래가 또 하나의 하늘처럼 오른다.",
    "A hermit in a single garment of rough hair, the capital's comforts renounced within sight of its walls, the myrrh of his relics answering the harshness of his shirt.": "거친 털옷 한 벌만 걸친 은수자, 도성의 안락을 그 성벽이 보이는 자리에서 버렸고, 그의 유물에서 나는 몰약이 그 거친 옷에 응답한다.",
    "A hermit in a tomb-cell dividing his belt in two for a sick child, healings flowing from the woven half as from the Apostles' garments.": "병든 아이를 위하여 자기 띠를 둘로 나누는 무덤 방의 은수자, 사도들의 옷에서처럼 그 짜인 반쪽에서 치유가 흘러나온다.",
    "A hermit in a worn habit, chains visible beneath, praying in a forest chapel.": "낡은 옷을 입고 그 아래 사슬이 보이는 은수자, 숲속 경당에서 기도한다.",
    "A hermit in iron chains and hair shirt above the Cilician shore, sailors on a storm-tossed sea calling on the God of Theodosius.": "킬리키아 해안 위에서 쇠사슬과 털옷을 걸친 은수자, 폭풍 이는 바다의 뱃사람들이 테오도시오의 하느님을 부른다.",
    "A hermit naked to the frost and the burning sun in a stone cave above the Bistrița, sixty winters of snow around his unshaken prayer.": "비스트리차 강 위 돌 동굴에서 서리와 타는 해에 벗은 몸으로 있는 은수자, 예순 겨울의 눈이 흔들리지 않는 그의 기도를 둘러싼다.",
    "A hermit of the Bithynian Olympus radiant with lifelong purity, the unclean spirits fleeing a vessel they never entered.": "평생의 정결로 빛나는 비티니아 올림포스의 은수자, 더러운 영들이 한 번도 들어가지 못한 그릇에서 달아난다.",
    "A hermit of the Drenica forest with the healed child of the despot before him, the monastery of Devich rising in thanksgiving over his cell, the Serbian wilderness keeping his relics.": "데스포트의 나은 아이를 앞에 둔 드레니차 숲의 은수자, 그의 방 위에 감사의 데비치 수도원이 일어서고, 세르비아의 광야가 그의 유물을 지킨다.",
    "A hermit of the Irish valley of the two lakes at prayer with arms outstretched, a bird nesting in his hand, the great monastery of Glendalough rising from his cell.": "두 호수의 아일랜드 골짜기에서 팔을 벌려 기도하는 은수자, 그의 손에 새가 둥지를 틀고, 그의 방에서 글렌달로흐의 큰 수도원이 일어선다.",
    "A hermit of the Red Mountain by the Vetluga river at prayer in his forest solitude, the wilderness hallowed by his long ascesis, the monastery rising after him.": "베틀루가 강가 붉은 산의 은수자, 숲의 홀로 있음 속에서 기도하고, 그의 오랜 고행으로 광야가 거룩해지며, 그가 떠난 뒤 수도원이 일어선다.",
    "A hermit of the Seliger island who never lay down to sleep, leaning on his hooks in prayer, his incorrupt relics uncovered and enshrined on the island of his labors.": "한 번도 누워 자지 않은 셀리게르 섬의 은수자, 갈고리에 몸을 기대고 기도하며, 그가 수고한 섬에서 썩지 않은 그의 유물이 드러나 모셔진다.",
    "A hermit of the Vologda forests founding his monastery on the river Kushta, the desert by Lake Kubena filled with prayer, the tradition of the Thebaid of the North carried on.": "쿠슈타 강가에 자기 수도원을 세우는 볼로그다 숲의 은수자, 쿠베나 호수 곁 광야가 기도로 채워지고, 북방 테바이드의 전통이 이어진다.",
    "A hermit of the holy mountain of Kyminas holding a sealed letter, its answer already written beside it.": "봉한 편지를 든 키미나스 거룩한 산의 은수자, 그 답이 이미 곁에 적혀 있다.",
    "A hermit of the trans-Volga forests raising the church of the Transfiguration on the Sokhot river, brethren gathering to the light in the wilderness.": "소호트 강에 주님 거룩한 변모 성당을 세우는 볼가 건너 숲의 은수자, 형제들이 광야의 빛으로 모여든다.",
    "A hermit on a bare Syrian height, iron upon his body and the sky for his roof, a quarter century of unwitnessed prayer.": "헐벗은 시리아의 언덕 위에 있는 은수자, 몸에 쇠를 두르고 하늘을 지붕 삼아, 사반세기를 아무도 보지 않는 기도로 지낸다.",
    "A hermit on a forest hill among the northern people, the Theophany church rising at his life's end.": "북방 백성들 가운데 숲 언덕에 있는 은수자, 그의 생애 끝에 신현 성당이 일어선다.",
    "A hermit on the myrtle-covered mountain of the Peloponnese, his cell unseen and his prayer unceasing, the name alone carried down.": "펠로폰네소스의 도금양 덮인 산 위의 은수자, 그의 방은 보이지 않고 기도는 그치지 않으며, 이름만이 전해 내려온다.",
    "A hermit reading by uncreated light in a tiny cell, a serpent destroyed by the sign of the Cross.": "아주 작은 방에서 창조되지 않은 빛으로 책을 읽는 은수자, 십자성호로 뱀 한 마리가 없어진다.",
    "A hermit speaking through the small window of his mountain cell, crowds below singing the refrains he taught them, the council of Chalcedon honoring his confession.": "산속 방의 작은 창으로 말하는 은수자, 아래에서 무리가 그가 가르쳐 준 후렴을 노래하고, 칼케돈 공의회가 그의 고백을 기린다.",
    "A hermit standing in fire against temptation, dolphins bearing him from his island, Zoe in her Bethlehem repentance and Photina on the sea rock, three crowns from one battle.": "유혹에 맞서 불 속에 선 은수자, 돌고래들이 그를 섬에서 실어 내고, 조에는 베들레헴의 참회 속에, 포티나는 바다 바위 위에 있으니, 한 싸움에서 세 관이 나온다.",
    "A hermit upright in death, supported on the wooden crutches on which he slept standing, his island hermitage behind.": "죽어서도 곧게 선 은수자, 서서 자던 나무 지팡이에 몸을 기댔고, 뒤에 그의 섬 은수처가 있다.",
    "A hermit-monk in the schema by a spring in the marshy forest, bears near him, a pillar of fire above.": "늪진 숲의 샘 곁에 대수도자 품의 옷을 입은 은수 수도자, 곁에 곰들이 있고, 위에 불기둥이 있다.",
    "A hermit-monk, once a soldier, at prayer on a mountain, sometimes shown with the Prophet Elijah.": "한때 군인이던 은수 수도자, 산에서 기도하며, 때로는 엘리야 예언자와 함께 그려진다.",
    "A hierarch of Kazan with a child's alphabet book in hand, a prison cell with light streaming through its opened door behind him.": "어린이 자모책을 손에 든 카잔의 주교, 그 뒤에 열린 문으로 빛이 쏟아지는 감옥 방이 있다.",
    "A hierarch of Khakhuli in the gorge of Tao, the translator's pen and the calligrapher's hand at rest, the golden stream of his preaching earning him the Chrysostom's own name.": "타오 협곡의 하후리의 주교, 번역가의 붓과 서예가의 손이 쉬고 있으며, 그의 설교의 금빛 흐름이 그에게 크리소스토모의 이름을 얻어 준다.",
    "A hierarch sheltering a fugitive within his monastery gate, the murdered brother's blood crying from the earth and the saint's hand raised in absolution over the murderer.": "자기 수도원 문 안에 도망자를 숨겨 주는 주교, 살해된 형제의 피가 땅에서 부르짖고, 성인의 손이 살인자 위에 사죄로 들려 있다.",
    "A hierarch with an anchor, the sea parting to reveal his tomb, Cyril and Methodius bearing his relics.": "닻을 든 주교, 바다가 갈라져 그의 무덤이 드러나고, 키릴로와 메토디오가 그의 유물을 옮긴다.",
    "A hierarch with the scroll of the Five Theological Orations, the little chapel of the Anastasia glowing behind him, the council throne laid down at his feet.": "다섯 신학 강론의 두루마리를 든 주교, 그 뒤에 아나스타시아의 작은 경당이 빛나고, 그의 발치에 내려놓은 공의회의 좌가 있다.",
    "A hierarch with the scroll of the Life of Moses, Sinai's darkness luminous above him, his brother Basil and sister Macrina beside his formation.": "모세의 생애 두루마리를 든 주교, 그 위에 시나이의 어둠이 빛나고, 그를 길러 낸 형 바실리오와 누이 마크리나가 곁에 있다.",
    "A hierarch-ruler of Samtskhe before the ancient Atskuri Icon of the Mother of God, the see of the Apostle Andrew in his care, the lives of the saints flowing from his pen.": "오래된 아츠쿠리의 하느님의 어머니 이콘 앞에 선 삼츠헤의 주교이자 통치자, 사도 안드레아의 주교좌를 맡았고, 그의 붓에서 성인들의 생애가 흘러나온다.",
    "A hieromonk bound to the mulberry tree of his monastery courtyard, the flames and nails of his long passion upon him, the abbess of five centuries later uncovering his fragrant relics in the ruins.": "자기 수도원 뜰의 뽕나무에 묶인 수도 사제, 오랜 수난의 불길과 못이 그 몸에 있고, 다섯 세기 뒤의 여수도원장이 폐허에서 향기로운 그의 유물을 찾아낸다.",
    "A hieromonk of the Far Caves anointing the sick with oil, healings flowing from the threefold rule of prayer, fasting, and unction.": "병자에게 기름을 바르는 먼 동굴의 수도 사제, 기도와 단식과 도유의 세 겹 규칙에서 치유가 흘러나온다.",
    "A hieromonk of the Skete of Saint Anne preaching Christ openly before the Ottoman power, the tortures of Serres upon him, the Holy Mountain sending its own into the harvest of the new martyrs.": "오스만의 권세 앞에서 드러내어 그리스도를 전하는 성 안나 스키티의 수도 사제, 세레스의 고문이 그 몸에 있고, 거룩한 산이 새 순교자들의 수확에 제 사람을 내어 준다.",
    "A hieromonk of the western sea raising a church at Braunton, the children of a king at his knee, Rome and Brittany on his pilgrim road behind.": "브라운턴에 성당을 세우는 서쪽 바다의 수도 사제, 그의 무릎에 임금의 자녀들이 있고, 뒤에 로마와 브르타뉴의 순례 길이 있다.",
    "A hieromonk slain at the altar with the chalice before him, the burning monastery of the far north behind, one hundred and fifteen martyrs crowned around.": "제대에서 성작을 앞에 두고 살해된 수도 사제, 뒤에 불타는 먼 북방의 수도원이 있고, 백열다섯 순교자가 둘레에서 관을 받는다.",
    "A hieromonk with censer in the caves, the reposed saints answering his paschal greeting.": "동굴에서 향로를 든 수도 사제, 안식한 성인들이 그의 부활 인사에 응답한다.",
    "A hieromonk-hermit at prayer in his cave on Măgura Tazlăului, thirty disciples about the little altar he raised, the frost conquered beneath his knees.": "머구라 타즐러울루이의 동굴에서 기도하는 은수 수도 사제, 그가 세운 작은 제대 둘레에 서른 명의 제자가 있고, 그의 무릎 아래에서 서리가 무릎 꿇는다.",
    "A hieromonk-missionary with a cross before the peoples of Alaska, the waters of Iliamna behind him.": "알래스카의 백성들 앞에 십자가를 든 선교 수도 사제, 그 뒤에 일리암나의 물이 있다.",
})

TEXT.update({
    "A holy virgin of Rome confessing Christ under torture, crowned with martyrdom, her relics borne over the sea to Sicily to be the treasure of a city.": "고문 아래에서 그리스도를 고백하는 로마의 거룩한 동정녀, 순교로 관을 받고, 그의 유물이 바다 건너 시칠리아로 옮겨져 한 도시의 보배가 된다.",
    "A humble elder of the northern forest with Alutiiq children about him, Spruce Island and the sea behind, the North Star above.": "알루티크 아이들에게 둘러싸인 북방 숲의 겸손한 장로, 뒤에 가문비섬과 바다가 있고, 위에 북극성이 있다.",
    "A humble herdsman-monk in a cave by a river, the cathedral of Bucharest receiving his relics.": "강가 동굴 속의 겸손한 목자 수도자, 부쿠레슈티의 대성당이 그의 유물을 받아들인다.",
    "A humble layman in simple dress by a river with a fishing line, a village church behind him.": "소박한 옷을 입고 강가에서 낚싯줄을 드리운 겸손한 평신도, 그 뒤에 마을 성당이 있다.",
    "A humble tailor by the Tura river with needle and fishing line, his coffin rising from the earth behind him, the Urals' churches gathered to his glorification.": "투라 강가에서 바늘과 낚싯줄을 든 겸손한 재봉사, 그 뒤에서 그의 관이 땅에서 솟아오르고, 우랄의 성당들이 그의 영광을 위하여 모인다.",
    "A husband and wife in monastic habits walking one road, two children's graves behind them, palms of Egypt ahead.": "수도복을 입고 한 길을 걷는 남편과 아내, 뒤에 두 아이의 무덤이 있고, 앞에 이집트의 종려나무가 있다.",
    "A husband and wife martyrs holding crosses, a prison and an infant near them.": "십자가를 든 순교자 부부, 그 곁에 감옥과 갓난아이가 있다.",
    "A husband and wife with the church in their house, a returned slave embraced as a brother, all crowned.": "자기 집에 교회를 둔 남편과 아내, 돌아온 종을 형제로 껴안고, 모두 관을 받는다.",
    "A jailer laying the saint's chains upon his own limbs, the empty prison behind him where the angel had come, his confession before the prefect winning him the martyr's crown.": "성인의 사슬을 제 몸에 채우는 옥지기, 그 뒤에 천사가 다녀간 빈 감옥이 있고, 총독 앞의 고백이 그에게 순교자의 관을 얻어 준다.",
    "A king of Georgia refusing to deny Christ and embrace the faith of the conqueror, crowned with martyrdom, the defender and restorer of the churches of his land.": "그리스도를 부인하고 정복자의 신앙을 받아들이기를 거부하는 조지아의 임금, 순교로 관을 받았고, 제 땅의 성당들을 지키고 다시 세운 이다.",
    "A king raising churches and monasteries across a ravaged land, the castle church of Artanuji behind him, the assassins' swords answered by a martyr's crown.": "황폐한 땅 곳곳에 성당과 수도원을 세우는 임금, 그 뒤에 아르타누지의 성채 성당이 있고, 자객들의 칼에 순교자의 관으로 응답한다.",
    "A king's daughter in the tower of her girlhood, the dove with the olive branch at her window, the wheels and pits of four persecutors failing around her, the sealed tomb at Ephesus standing open and empty.": "소녀 시절의 탑 안에 있는 임금의 딸, 그의 창가에 올리브 가지를 문 비둘기가 있고, 네 박해자의 수레바퀴와 구덩이가 그를 둘러싸고 헛되이 그치며, 에페소스의 봉인된 무덤이 열린 채 비어 있다.",
    "A laboring monk of the Near Caves at his work and prayer, the gift of wonders resting on him, his incorrupt relics honored among the fathers of the Lavra.": "자기 일과 기도에 매인 가까운 동굴의 수고하는 수도자, 기적의 은사가 그 위에 머물고, 썩지 않은 그의 유물이 라브라의 교부들 가운데 공경받는다.",
    "A layman distributing his goods to the poor, enduring sickness with a radiant face.": "자기 재산을 가난한 이들에게 나누어 주는 평신도, 빛나는 얼굴로 병을 견딘다.",
    "A layman kneeling in the road begging forgiveness of a prisoner who will not give it, the crown passing at the block from the priest who denied to the friend who confessed.": "길에 무릎 꿇고 용서를 빌지만 얻지 못하는 평신도, 사형대에서 관이 부인한 사제에게서 고백한 벗에게로 옮겨 간다.",
    "A layman standing unbowed before Julian, the lioness of the arena at Caesarea awaiting his crown.": "율리아누스 앞에 굽히지 않고 선 평신도, 카이사리아 원형 경기장의 암사자가 그의 관을 기다린다.",
    "A learned bishop of Cyprus at the side of the unlettered Saint Spyridon, taught by him to despise the palace and the vineyard and to seek the treasures of heaven.": "글을 배우지 못한 성 스피리돈 곁에 선 키프로스의 학식 있는 주교, 궁전과 포도밭을 업신여기고 하늘의 보화를 찾으라고 그에게 배운다.",
    "A maid of the imperial court in a fugitive's plain dress, the church of Amasea rising by her gifts, her soul taken up in peace while the tyrant's summons was still on the road.": "도망자의 수수한 옷을 입은 황궁의 시녀, 그의 기부로 아마시아의 성당이 일어서고, 참주의 소환장이 아직 길 위에 있을 때 그의 영혼이 평화로이 들어 올려진다.",
    "A maiden of Novgorod among the city's wonderworkers, her hidden ascetic life known only to God, her incorrupt relics rising from the tomb behind the church of Florus and Laurus.": "도시의 기적행자들 가운데 있는 노브고로드의 처녀, 감추어진 그의 고행 생활은 하느님만이 아셨고, 썩지 않은 그의 유물이 플로로와 라우로 성당 뒤 무덤에서 올라온다.",
    "A maiden of Tarsus baptized by the bishop her dream revealed, the imperial marriage refused, the brazen ox glowing as her bridal chamber to Christ.": "꿈이 알려 준 주교에게 세례를 받는 타르소스의 처녀, 황제와의 혼인을 거절하고, 달아오른 놋쇠 황소가 그리스도를 향한 그의 신방이 된다.",
    "A maiden of Thessalonica casting down the idol of Athena at Corinth, the wild beasts crouching harmless at her feet, an angel comforting her in her prison.": "코린토에서 아테나의 우상을 무너뜨리는 테살로니키의 처녀, 들짐승들이 해치지 않고 그 발치에 웅크리며, 천사가 감옥에서 그를 위로한다.",
    "A maiden of eighteen bowing to the chained confessors before the tribunal, her own seizure following her greeting, the sea of Caesarea receiving her.": "재판정 앞에서 사슬에 매인 증거자들에게 절하는 열여덟 살 처녀, 그 인사에 이어 자신도 붙잡히고, 카이사리아의 바다가 그를 받아들인다.",
    "A maiden standing in the sunlight of the pagan temple, the sign of the Cross shining on her brow, the idol of Zeus shattered and the angel descending to her prison.": "이교 신전의 햇빛 속에 선 처녀, 그의 이마에 십자성호가 빛나고, 제우스의 우상이 부서지며, 천사가 그의 감옥으로 내려온다.",
    "A man crying out from the roadside as a great company of prisoners passes, all crowned together.": "포로들의 큰 무리가 지나갈 때 길가에서 외치는 사람, 모두 함께 관을 받는다.",
    "A man of Cana beneath his fig tree, the Lord's eye upon him before the calling, the confession of the Son of God rising at the first meeting.": "자기 무화과나무 아래 있는 카나 사람, 부르심 전에 이미 주님의 눈이 그에게 머물고, 첫 만남에서 하느님의 아드님이라는 고백이 올라온다.",
    "A martyr amid flames, holding a cross, the city of Thessalonica behind him.": "불길 가운데 십자가를 든 순교자, 그 뒤에 테살로니키 성이 있다.",
    "A martyr amid his torments beholding a ladder to heaven and radiant men calling him to a city of light.": "고문 가운데 하늘로 오르는 사다리와 빛의 도성으로 부르는 빛나는 이들을 보는 순교자.",
    "A martyr beheaded by the sword, receiving his crown from Christ.": "칼로 목이 잘린 순교자, 그리스도에게서 자기 관을 받는다.",
    "A martyr enduring boiling pitch poured over him, his soul rising in glory.": "끓는 역청을 뒤집어쓰고 견디는 순교자, 그의 영혼이 영광 중에 올라간다.",
    "A martyr holding a cross, tending to the bodies of the fallen faithful.": "십자가를 들고 쓰러진 신자들의 주검을 거두는 순교자.",
    "A martyr holding a cross.": "십자가를 든 순교자.",
    "A martyr in a red-hot iron belt denouncing the apostate emperor, the cross of his final contest behind him.": "벌겋게 달군 쇠띠를 두른 채 배교한 황제를 꾸짖는 순교자, 그 뒤에 마지막 싸움의 십자가가 있다.",
    "A martyr in flames giving thanks, a spring gushing from a rock nearby.": "불길 가운데 감사드리는 순교자, 가까운 바위에서 샘이 솟는다.",
    "A martyr in noble dress holding a cross, his companions around him.": "귀한 옷을 입고 십자가를 든 순교자, 그 둘레에 동료들이 있다.",
    "A martyr making the sign of the Cross, a road behind him.": "십자성호를 긋는 순교자, 그 뒤에 길이 있다.",
    "A martyr of Heraclea slipping his captors on the road, the wounds of his tortures completing the sentence the executioners could not, the crown descending outside the walls.": "길에서 붙잡은 이들을 벗어난 헤라클레아의 순교자, 고문의 상처가 처형자들이 이루지 못한 선고를 마무리하고, 성벽 밖에서 관이 내려온다.",
    "A martyr of Isauria with the Archangel Michael above him, demons sealed in clay vessels at his feet, the bridal candle of his parable in his hand.": "위에 미카엘 대천사를 둔 이사우리아의 순교자, 그 발치에 흙 그릇에 봉인된 마귀들이 있고, 손에 그의 비유의 혼인 촛불이 있다.",
    "A martyr of Lycaonia driven along the road in sandals of nails, bound at last to a barren tree that puts forth fruit above him.": "못을 박은 신을 신고 길을 걷도록 내몰린 리카오니아의 순교자, 마침내 메마른 나무에 묶이니 그 위로 나무가 열매를 맺는다.",
    "A martyr of the Thebaid whose prayer held the governor's boat fast on the Nile until the judge confessed Christ, the river receiving the confessor as his crown.": "그의 기도가 나일 강에서 총독의 배를 붙들어 두어 재판관이 그리스도를 고백하게 한 테바이드의 순교자, 강이 그 증거자를 그의 관으로 받아들인다.",
    "A martyr of the Thracian countryside beheaded for his confession, his crown descending from heaven.": "자기 고백 때문에 목이 잘린 트라키아 시골의 순교자, 하늘에서 그의 관이 내려온다.",
})

TEXT.update({
    "A martyr of the early Church bowing his neck to the sword, his confession of Christ his whole and sufficient memorial.": "초대 교회의 한 순교자가 칼 아래 목을 숙이니, 그리스도를 고백한 그 한 가지가 그의 온전하고 넉넉한 기념이 된다.",
    "A martyr standing in flames, exhorting the bystanders, his body unharmed.": "불길 가운데 서서 구경하는 이들을 권면하는 순교자, 그 몸은 상하지 않는다.",
    "A martyr whom the saw cannot cut, a beheaded confessor beside him, and a former priest of idols receiving the crown.": "톱도 자르지 못하는 순교자, 그 곁에 목 베인 증거자, 그리고 우상의 사제였던 이가 면류관을 받는다.",
    "A martyr whose name declares his whole estate, the slave of Christ sealing his title in blood.": "이름이 그의 온 신분을 말해 주는 순교자, 그리스도의 종이 그 이름을 피로 봉인한다.",
    "A martyr-physician holding a medicine box and a cross.": "약상자와 십자가를 든 순교자 의사.",
    "A matron with hands raised in prayer, standing over her seven martyred sons amid flames.": "불길 속에서 순교한 일곱 아들 위에 서서 두 손을 들어 기도하는 부인.",
    "A merchant of the Volga preaching Christ in the bazaar of Bolgar, the tortures of his countrymen upon him, the boats of Vladimir bearing his relics up the river in honor.": "볼가의 상인이 볼가르의 장터에서 그리스도를 전하고, 동족의 고문을 몸에 받으며, 블라디미르의 배들이 그의 유물을 강 위로 영예롭게 모셔 올린다.",
    "A metropolitan at Florence with his pen withheld from the act of union, the assembled council behind him and the Orthodox faith whole in his hands.": "피렌체에서 합동 문서에 펜을 대지 않는 수도 대주교, 그의 뒤에 모인 공의회가 있고 그의 손에 정교 신앙이 온전히 있다.",
    "A metropolitan at his writing desk, the volumes of the Lives of the Saints before him.": "자기 책상 앞에 앉은 수도 대주교, 그 앞에 성인전 여러 권이 놓여 있다.",
    "A metropolitan baptizing the people of Kyiv in the waters of the Dnipro, idols cast down behind him.": "드니프로 강물에서 키이우 백성에게 세례를 베푸는 수도 대주교, 그 뒤로 우상들이 무너져 있다.",
    "A metropolitan barring the Dormition cathedral's blessing to the oprichnik tsar, the prison cell of Tver and the strangler's hands beneath, the returning relics received by a penitent throne above.": "오프리치니크 황제에게 성모 안식 대성당의 축복을 거두는 수도 대주교, 그 아래에 트베리의 감방과 목 조르는 자의 손이 있고, 그 위에 참회하는 왕좌가 돌아온 유물을 맞이한다.",
    "A metropolitan before the Nativity cathedral of Suzdal, the Florishchev hermitage he built rising in the forest behind.": "수즈달의 성모 탄생 대성당 앞에 선 수도 대주교, 그 뒤 숲에 그가 세운 플로리셰프 은수처가 솟아 있다.",
    "A metropolitan enthroned in a cave in the sheer cliff of Ostrog, the vine springing from the rock of his repose, pilgrims of every faith ascending the mountain to his incorrupt relics.": "오스트로그의 깎아지른 절벽 굴에 모셔진 수도 대주교, 그가 안식한 바위에서 포도나무가 돋아나고, 온갖 신앙의 순례자들이 그의 썩지 않는 유물을 향하여 산을 오른다.",
    "A metropolitan healing the blind khansha Taidula, the Chudov monastery rising on the Kremlin ground of her gratitude, the boy prince Dimitri under his guiding hand.": "눈먼 칸의 부인 타이둘라를 고치는 수도 대주교, 그 감사의 크렘린 땅에 추도프 수도원이 솟아나고, 어린 공후 드미트리가 그의 인도하는 손 아래 있다.",
    "A metropolitan holding a Gospel in the Aleut tongue, a kayak and the islands of Alaska behind him.": "알류트 말로 된 복음서를 든 수도 대주교, 그 뒤로 카약과 알래스카의 섬들이 있다.",
    "A metropolitan in the white klobuk and omophorion, blessing, holding a Gospel.": "흰 클로부크와 오모포리온을 걸치고 축복하며 복음서를 든 수도 대주교.",
    "A metropolitan in the white klobuk and omophorion, holding a Gospel book.": "흰 클로부크와 오모포리온을 걸치고 복음서를 든 수도 대주교.",
    "A metropolitan in the white klobuk holding a Gospel and a scroll of his translations.": "흰 클로부크를 쓰고 복음서와 자기 번역의 두루마리를 든 수도 대주교.",
    "A metropolitan of Kyiv laying aside all honor, asking in death the last place and the deepest abasement, the wonders of heaven answering his humility.": "모든 영예를 내려놓은 키이우의 수도 대주교, 죽음에서 가장 낮은 자리와 가장 깊은 낮춤을 구하니, 하늘의 기적들이 그 겸손에 응답한다.",
    "A metropolitan of Moscow raised to the primacy by the Russian bishops, guarding the Orthodox faith against the false union, the see of Moscow made the head of an independent Church.": "러시아 주교들의 손으로 수위에 오른 모스크바의 수도 대주교, 거짓 합동에 맞서 정교 신앙을 지키니, 모스크바 좌가 독립된 교회의 머리가 된다.",
    "A metropolitan of Tobolsk sending missionaries across Siberia and to China, the book of his Iliotropion in his hand, the will of God embraced as the sunflower turns to the sun.": "시베리아 전역과 중국으로 선교사를 보내는 토볼스크의 수도 대주교, 손에 그의 일리오트로피온 책을 들고, 해바라기가 해를 향하듯 하느님의 뜻을 품는다.",
    "A metropolitan receiving an omophorion from the hands of the Theotokos, the road from ruined Kyiv to Vladimir behind him.": "하느님의 어머니의 손에서 오모포리온을 받는 수도 대주교, 그 뒤로 폐허가 된 키이우에서 블라디미르로 가는 길이 있다.",
    "A metropolitan-iconographer laying the first stones of the Dormition cathedral, Moscow small behind him and glorious above him.": "성모 안식 대성당의 첫 돌을 놓는 수도 대주교이자 이콘 화가, 그 뒤에 모스크바가 작게 있고 그 위에 모스크바가 영광스럽게 있다.",
    "A mighty farmer with a severed hand confessing Christ, thirty-two companions crowned around him.": "잘린 손으로 그리스도를 고백하는 힘센 농부, 그 둘레에 서른두 동료가 면류관을 쓴다.",
    "A mighty warrior-monk of the Caves, his sword laid at the foot of the cross, his hand folded in blessing.": "동굴 수도원의 용맹한 수도 전사, 십자가 발치에 칼을 내려놓고 손을 들어 축복한다.",
    "A missionary bishop of the northern forests, the omophorion of his office become the instrument of his martyrdom, the Zyrian flock he guarded gathered behind him.": "북방 숲의 선교 주교, 그 직분의 오모포리온이 순교의 도구가 되고, 그가 지킨 지랸 양떼가 그 뒤에 모여 있다.",
    "A missionary bishop preaching Christ to the Gauls at Beauvais, his companions Maximian and Julian beside him, the crown of martyrdom descending on the enlighteners of the north.": "보베에서 갈리아 사람들에게 그리스도를 전하는 선교 주교, 그 곁에 동료 막시미아노와 율리아노가 있고, 북방의 계몽자들 위에 순교의 면류관이 내린다.",
    "A missionary priest in a kayak among the Aleutian islands with the Gospel in the Aleut tongue, and the same man enthroned as Metropolitan of Moscow, the two ends of one obedience.": "알류트 말 복음서를 들고 알류샨 열도를 카약으로 다니는 선교 사제, 그리고 같은 이가 모스크바의 수도 대주교 좌에 오르니, 한 순명의 두 끝이다.",
    "A monastic founder by a northern lake, a canal and monastery buildings the work of his hands.": "북방 호숫가의 수도원 창립자, 운하와 수도원 건물들이 그 손의 일이다.",
    "A monastic founder on a forested hill, a small wooden monastery of the Transfiguration behind him.": "숲 덮인 언덕 위의 수도원 창립자, 그 뒤에 작은 나무 주님 변모 수도원이 있다.",
    "A monastic founder on a lake island, a wooden church of the apostles Peter and Paul beside him.": "호수 섬 위의 수도원 창립자, 그 곁에 사도 베드로와 바오로의 나무 성당이 있다.",
    "A monk at a writing desk with quill and parchment, the Tale of Bygone Years open before him.": "깃펜과 양피지를 들고 책상 앞에 앉은 수도자, 그 앞에 지나간 세월의 이야기가 펼쳐져 있다.",
    "A monk at the monastery gates, reading the hearts of those who enter, keys at his belt.": "수도원 문간의 수도자, 허리에 열쇠를 차고 들어오는 이들의 마음을 읽는다.",
    "A monk atop a pillar in the schema, blessing.": "대수도자 품을 입고 기둥 위에 서서 축복하는 수도자.",
    "A monk atop a tall pillar in a small railed cell, blessing, a ladder against the column.": "난간 두른 작은 방이 있는 높은 기둥 위에서 축복하는 수도자, 기둥에 사다리가 걸려 있다.",
    "A monk atop a wooden pillar in the northern forest, a small monastery of the Ascension below.": "북방 숲의 나무 기둥 위에 선 수도자, 그 아래 작은 주님 승천 수도원이 있다.",
    "A monk bearing an abandoned body to burial on his own shoulders, the hill of the common graves crowned with the Trinity monastery, the infant tsar held at the font in his arms.": "버려진 주검을 제 어깨에 지고 묻으러 가는 수도자, 공동 무덤의 언덕 위에 삼위일체 수도원이 세워지고, 그 팔에 어린 황제가 세례대 앞에 안겨 있다.",
    "A monk beholding angels and demons contending over him, a broken money chest at his feet.": "자기를 두고 다투는 천사들과 마귀들을 바라보는 수도자, 그 발치에 부서진 돈궤가 있다.",
    "A monk blessing the forest bank of the Vologda, the Trinity church rising in the wilderness, the great city he foretold behind him.": "볼로그다의 숲 기슭을 축복하는 수도자, 광야에 삼위일체 성당이 솟아오르고, 그가 예언한 큰 도시가 그 뒤에 있다.",
    "A monk buried to the shoulders in the earth of his cave, at prayer.": "자기 굴의 흙에 어깨까지 묻힌 채 기도하는 수도자.",
})
