# -*- coding: utf-8 -*-
"""Romanian for the vocabulary that stands beside the lives.

TEXT = {the phrase the index shows: the Romanian}. PARTS holds the pieces the
compound place-names are built from, and expand() assembles the wholes, so a
town cannot be spelled one way on one card and another way on the next.

Romanian is a liturgical tongue of the Church and has its own received words
for what the English calls by Greek or Latin names, so the orders of
sanctity, the ranks of the Typikon, the estates and the ages are given as
the Romanian Church gives them: Cuvios for the monastic saint, Sfintit
Mucenic for the hieromartyr, Nebun pentru Hristos for the fool. Greek,
Slavic, Georgian and Latin place-names take the forms Romanian usage has
received - Constantinopol, Tesalonic, Nicomidia, Chiev - and where no
received form exists the name is transliterated.

Diacritics are written in full: a with breve, a and i with circumflex, s and
t with comma below.

The keys are the phrases exactly as the index writes them, so a rendering
cannot quietly attach itself to the wrong saint.
"""
TEXT = {}


# The orders of sanctity, as the badge on a card names them.
TEXT.update({
    "Angelic": "Puteri netrupești",
    "Apostle": "Apostol",
    "Confessor": "Mărturisitor",
    "Equal-to-the-Apostles": "Întocmai cu Apostolii",
    "Feast": "Praznic",
    "Fool-for-Christ": "Nebun pentru Hristos",
    "Great Martyr": "Mare Mucenic",
    "Hierarch": "Ierarh",
    "Hieromartyr": "Sfințit Mucenic",
    "Martyr": "Mucenic",
    "Monastic": "Cuvios",
    "New Martyr": "Mucenic Nou",
    "Other": "Altele",
    "Passion-bearer": "Purtător de patimi",
    "Prophet": "Prooroc",
    "Righteous": "Drept",
    "Unmercenary": "Doctor fără de arginți",
    "Virgin Martyr": "Muceniță fecioară",
})


# The attributes a life is marked with.
TEXT.update({
    "Church Father": "Părinte al Bisericii",
    "Desert ascetic": "Nevoitor al pustiei",
    "Enlightener": "Luminător",
    "Healing intercessor": "Tămăduitor",
    "Hymnographer": "Imnograf",
    "Iconographer": "Iconar",
    "Incorrupt relics": "Moaște nestricate",
    "Monastery founder": "Ctitor de mănăstire",
    "Myrrh-bearer": "Mironosiță",
    "Myrrh-streaming": "Izvorâtor de mir",
    "New martyr": "Mucenic nou",
    "Ruler or royal": "Domnitor sau din neam domnesc",
    "Stylite": "Stâlpnic",
    "Warrior saint": "Sfânt ostaș",
    "Wonderworker": "Făcător de minuni",
})


# The ranks the Typikon gives a feast.
TEXT.update({
    "Doxology": "Doxologie",
    "Great Feast": "Praznic împărătesc",
    "Polyeleos": "Polieleu",
    "Simple": "Simplă",
    "Vigil": "Priveghere",
})


# The jurisdictions whose calendars the index keeps.
TEXT.update({
    "Antiochian": "Antiohian",
    "Greek": "Grec",
    "OCA": "OCA",
    "Romanian": "Român",
    "Russian": "Rus",
    "Serbian": "Sârb",
    "Ukrainian": "Ucrainean",
})


# The estate a saint stood in.
TEXT.update({
    "Apostolic": "Apostolic",
    "Clergy": "Cler",
    "Laity": "Mireni",
    "Layman": "Mirean",
    "Laywoman": "Mireancă",
    "Laywomen": "Mirence",
    "Married": "Căsătorit",
    "Military": "Ostășesc",
    "Monastic": "Monahal",
    "Prophet": "Prooroc",
    "Royal": "Domnesc",
    "Royalty": "Neam domnesc",
    "Unknown": "Necunoscut",
    "Unmarried": "Necăsătorit",
    "Widowed": "Văduv",
})


# The ages the lives are set in.
TEXT.update({
    "Age of the Celtic Saints": "Veacul sfinților celți",
    "Age of the Ecumenical Councils": "Veacul Sinoadelor Ecumenice",
    "Age of the Martyrs": "Veacul mucenicilor",
    "Apostolic Age": "Veacul apostolic",
    "Byzantine": "Bizantin",
    "Byzantine Balkans": "Balcanii bizantini",
    "Byzantine Era": "Epoca bizantină",
    "Byzantine Iconoclasm": "Iconoclasmul bizantin",
    "Cossack Era": "Epoca cazacilor",
    "Desert Fathers": "Părinții pustiei",
    "Early Medieval West": "Apusul medieval timpuriu",
    "Imperial Russia": "Rusia imperială",
    "Kievan Rus'": "Rusia Chieveană",
    "Medieval Georgia": "Georgia medievală",
    "Medieval Rus'": "Rusia medievală",
    "Medieval Serbia": "Serbia medievală",
    "Modern": "Modern",
    "Modern Era": "Epoca modernă",
    "Muscovite Russia": "Rusia moscovită",
    "Old Testament": "Vechiul Testament",
    "Ottoman Balkans": "Balcanii otomani",
    "Ottoman Era": "Epoca otomană",
    "Ottoman period": "Perioada otomană",
    "Polish-Lithuanian period": "Perioada polono-lituaniană",
    "Soviet Era": "Epoca sovietică",
    "Soviet period": "Perioada sovietică",
    "Synodal Russia": "Rusia sinodală",
})


# The one movable commemoration the index names.
TEXT.update({
    "Sunday of the Holy Forefathers": "Duminica Sfinților Strămoși",
})


# The countries and the regions.
TEXT.update({
    "Aegean": "Marea Egee",
    "America": "America",
    "Arabia": "Arabia",
    "Armenia": "Armenia",
    "Asia Minor": "Asia Mică",
    "Balkans": "Balcani",
    "Belarus": "Belarus",
    "Bithynia": "Bitinia",
    "Britain": "Britania",
    "British Isles": "Insulele Britanice",
    "Bulgaria": "Bulgaria",
    "Cappadocia": "Capadocia",
    "Cilicia": "Cilicia",
    "Constantinople": "Constantinopol",
    "Crimea": "Crimeea",
    "Cyprus": "Cipru",
    "Czech Lands": "Țările Cehe",
    "Dalmatia": "Dalmația",
    "Danube lands": "Ținuturile Dunării",
    "Egypt": "Egipt",
    "England": "Anglia",
    "Ethiopia": "Etiopia",
    "Gaul": "Galia",
    "Georgia": "Georgia",
    "Greece": "Grecia",
    "Holy Land": "Țara Sfântă",
    "Illyria": "Iliria",
    "Illyricum": "Iliric",
    "India": "India",
    "Ireland": "Irlanda",
    "Italy": "Italia",
    "Lithuania": "Lituania",
    "Macedonia": "Macedonia",
    "Mesopotamia": "Mesopotamia",
    "Moldavia": "Moldova",
    "Montenegro": "Muntenegru",
    "Moravia": "Moravia",
    "Mount Athos": "Muntele Athos",
    "North Africa": "Africa de Nord",
    "North America": "America de Nord",
    "North Macedonia": "Macedonia de Nord",
    "Palestine": "Palestina",
    "Persia": "Persia",
    "Phoenicia": "Fenicia",
    "Poland": "Polonia",
    "Pontus": "Pont",
    "Romania": "România",
    "Rome": "Roma",
    "Russia": "Rusia",
    "Scythia": "Scitia",
    "Serbia": "Serbia",
    "Siberia": "Siberia",
    "Sinai": "Sinai",
    "Spain": "Spania",
    "Syria": "Siria",
    "Thrace": "Tracia",
    "Ukraine": "Ucraina",
    "Western Rus": "Rusia apuseană",
})


# The places, which are not a list but a grammar: a card names a town, a
# province and a country in one line, and the same town appears on twenty
# other cards inside a different line. The pieces are rendered once here and
# the wholes are assembled from them, so a town cannot be spelled one way on
# one card and another way on the next.
PARTS = {}

def expand(phrases):
    """The compounds, assembled from the parts above."""
    out = {}
    for p in phrases:
        bits = p.split(", ")
        if all(b in PARTS for b in bits):
            out[p] = ", ".join(PARTS[b] for b in bits)
    return out


# The lands the fasting rule is kept in.
TEXT.update({
    "Albania": "Albania",
    "Bohemia": "Boemia",
    "China": "China",
    "France": "Franța",
    "Judah": "Iuda",
    "Moesia": "Moesia",
    "Sicily": "Sicilia",
    "United States": "Statele Unite",
})


# The rank a saint is given.
TEXT.update({
    "Abbess": "Stareță",
    "Abbot (Archimandrite)": "Stareț (Arhimandrit)",
    "Abbot (Founder)": "Stareț (Ctitor)",
    "Abbot (Igumen)": "Stareț (Egumen)",
    "Abbot (Igumen), Confessor": "Stareț (Egumen), Mărturisitor",
    "Abbot (Igumen), Hieromartyr": "Stareț (Egumen), Sfințit Mucenic",
    "Abbot (Igumen), Martyr": "Stareț (Egumen), Mucenic",
    "Abbot (Igumen), Monastic Martyr": "Stareț (Egumen), Cuvios Mucenic",
    "Abbot, Confessor": "Stareț, Mărturisitor",
    "Abbot, Confessor-Martyr": "Stareț, Mărturisitor și Mucenic",
    "Abbot, Priest": "Stareț, Preot",
    "Abbots": "Stareți",
    "Anchorite": "Sihastru",
    "Apostle of the Seventy": "Apostol din cei Șaptezeci",
    "Apostle of the Seventy, Bishop": "Apostol din cei Șaptezeci, Episcop",
    "Apostle of the Seventy, Martyr": "Apostol din cei Șaptezeci, Mucenic",
    "Apostle, Evangelist": "Apostol, Evanghelist",
    "Apostle, Martyr": "Apostol, Mucenic",
    "Apostles": "Apostoli",
    "Apostles of the Seventy": "Apostoli din cei Șaptezeci",
    "Apostles of the Seventy, Martyrs": "Apostoli din cei Șaptezeci, Mucenici",
    "Archangel": "Arhanghel",
    "Archbishop": "Arhiepiscop",
    "Archbishop, Confessor": "Arhiepiscop, Mărturisitor",
    "Archbishop, Equal-to-the-Apostles": "Arhiepiscop, Întocmai cu Apostolii",
    "Archdeacon": "Arhidiacon",
    "Archimandrite": "Arhimandrit",
    "Bishop": "Episcop",
    "Bishop, Church Father": "Episcop, Părinte al Bisericii",
    "Bishop, Confessor": "Episcop, Mărturisitor",
    "Bishop, Equal-to-the-Apostles": "Episcop, Întocmai cu Apostolii",
    "Bishop, Hieromartyr": "Episcop, Sfințit Mucenic",
    "Bishop, Monk": "Episcop, Monah",
    "Bishops": "Episcopi",
    "Blessed Eldress": "Fericita Maică duhovnicească",
    "Chamberlain (cubicularius)": "Cubicular (cubicularius)",
    "Childmartyr": "Prunc mucenic",
    "Commander": "Comandant",
    "Confessor, Archpriest": "Mărturisitor, Protoiereu",
    "Deacon": "Diacon",
    "Deacon, Monk-martyr": "Diacon, Cuvios Mucenic",
    "Deaconess": "Diaconiță",
    "Deaconess and Martyr": "Diaconiță și Muceniță",
    "Elder": "Stareț",
    "Empress": "Împărăteasă",
    "Equal-to-the-Apostles, Emperor": "Întocmai cu Apostolii, Împărat",
    "Equals-to-the-Apostles": "Întocmai cu Apostolii",
    "Grand Duchess": "Mare Ducesă",
    "Grand Prince": "Mare Cneaz",
    "Grand Princess": "Mare Cneaghină",
    "Great Martyr, Equal-to-the-Apostles": "Mare Mucenic, Întocmai cu Apostolii",
    "Great Prince, Martyr": "Mare Cneaz, Mucenic",
    "Great-martyr": "Mare Mucenic",
    "Great-martyr, Prince": "Mare Mucenic, Cneaz",
    "Hermit": "Pustnic",
    "Hermits": "Pustnici",
    "Hierarchs": "Ierarhi",
    "Hieromartyr (Hermit)": "Sfințit Mucenic (Pustnic)",
    "Hieromartyr, Apostle": "Sfințit Mucenic, Apostol",
    "Hieromartyr, Archbishop": "Sfințit Mucenic, Arhiepiscop",
    "Hieromartyr, Archimandrite": "Sfințit Mucenic, Arhimandrit",
    "Hieromartyr, Archpriest": "Sfințit Mucenic, Protoiereu",
    "Hieromartyr, Bishop": "Sfințit Mucenic, Episcop",
    "Hieromartyr, Confessor": "Sfințit Mucenic, Mărturisitor",
    "Hieromartyr, Deacon": "Sfințit Mucenic, Diacon",
    "Hieromartyr, Patriarch": "Sfințit Mucenic, Patriarh",
    "Hieromartyr, Pope": "Sfințit Mucenic, Papă",
    "Hieromartyr, and his son": "Sfințit Mucenic, și fiul său",
    "Hieromartyrs": "Sfințiți Mucenici",
    "Hieromonk": "Ieromonah",
    "Hieroschemamonk": "Ieroschimonah",
    "High Priest": "Arhiereu",
    "Icon of the Mother of God": "Icoana Maicii Domnului",
    "King and Martyr": "Rege și Mucenic",
    "King and Prophet": "Rege și Prooroc",
    "Laymen": "Mireni",
    "Martyrs": "Mucenici",
    "Master Builders, Monks": "Meșteri zidari, Monahi",
    "Metropolitan": "Mitropolit",
    "Metropolitan, Equal-to-the-Apostles": "Mitropolit, Întocmai cu Apostolii",
    "Monastic Martyr": "Cuvios Mucenic",
    "Monastic Martyrs": "Cuvioși Mucenici",
    "Monastic New Martyr": "Cuvios Mucenic Nou",
    "Monastics": "Cuvioși",
    "Monk": "Monah",
    "Monk (Founder)": "Monah (Ctitor)",
    "Monk (Hermit)": "Monah (Pustnic)",
    "Monk (elder)": "Monah (stareț)",
    "Monk (hermit)": "Monah (pustnic)",
    "Monk (novice)": "Monah (novice)",
    "Monk (recluse)": "Monah (zăvorât)",
    "Monk (stylite)": "Monah (stâlpnic)",
    "Monk, Church Father": "Monah, Părinte al Bisericii",
    "Monk, Confessor": "Monah, Mărturisitor",
    "Monk, Elder": "Monah, Stareț",
    "Monk, Hymnographer": "Monah, Imnograf",
    "Monk, Martyr": "Monah, Mucenic",
    "Monk, Recluse": "Monah, Zăvorât",
    "Monk, Unmercenary Physician": "Monah, Doctor fără de arginți",
    "Monk, former Great Zhupan": "Monah, fost Mare Jupan",
    "Monk-martyr": "Cuvios Mucenic",
    "Monk-martyrs": "Cuvioși Mucenici",
    "Monks": "Monahi",
    "Monks (Founders)": "Monahi (Ctitori)",
    "Mother": "Maică",
    "Myrrhbearer": "Mironosiță",
    "New Martyrs": "Mucenici Noi",
    "New Martyrs and Confessors": "Mucenici Noi și Mărturisitori",
    "Nun": "Monahie",
    "Nun-martyr": "Cuvioasă Muceniță",
    "Patriarch": "Patriarh",
    "Patriarch, Church Father": "Patriarh, Părinte al Bisericii",
    "Patriarch, Confessor": "Patriarh, Mărturisitor",
    "Patriarch, Hieromartyr": "Patriarh, Sfințit Mucenic",
    "Physician": "Doctor",
    "Physicians": "Doctori",
    "Pope": "Papă",
    "Pope of Rome, Confessor": "Papă al Romei, Mărturisitor",
    "Presbyter and Deacon": "Preot și Diacon",
    "Presbyters, Confessors": "Preoți, Mărturisitori",
    "Priest": "Preot",
    "Prince": "Cneaz",
    "Prince of Moldavia": "Domn al Moldovei",
    "Prince, Passion-Bearer": "Cneaz, Purtător de patimi",
    "Princes": "Cneji",
    "Princess": "Cneaghină",
    "Princess, Nun": "Cneaghină, Monahie",
    "Proconsul (military commander)": "Proconsul (comandant de oaste)",
    "Prophet and Forerunner": "Prooroc și Înaintemergător",
    "Prophetess": "Proorociță",
    "Protomartyr": "Întâiul Mucenic",
    "Protopresbyter": "Protopresbiter",
    "Recluse": "Zăvorât",
    "Right-believing Prince": "Binecredinciosul Cneaz",
    "Right-believing Prince (Monk)": "Binecredinciosul Cneaz (Monah)",
    "Right-believing Prince and Princess": "Binecredincioșii Cneaz și Cneaghină",
    "Right-believing Prince, Passion-bearer": "Binecredinciosul Cneaz, Purtător de patimi",
    "Right-believing Princess (Nun)": "Binecredincioasa Cneaghină (Monahie)",
    "Right-believing Princess, Martyr": "Binecredincioasa Cneaghină, Muceniță",
    "Righteous (Child)": "Drept (Prunc)",
    "Righteous (Children)": "Drepți (Prunci)",
    "Righteous (Unmercenary)": "Drept (Doctor fără de arginți)",
    "Righteous Forefather": "Drept Strămoș",
    "Righteous Virgin": "Dreapta Fecioară",
    "Righteous, Priest": "Drept, Preot",
    "Roman soldier": "Ostaș roman",
    "Schemamonk": "Schimonah",
    "Synaxis": "Sobor",
    "Tsar and Imperial Family": "Țar și Familia Imperială",
    "Unmercenary Martyrs": "Mucenici doctori fără de arginți",
    "Venerable": "Cuvios",
    "Venerable Prince": "Cuviosul Cneaz",
    "Venerable Princess": "Cuvioasa Cneaghină",
    "Virgin": "Fecioară",
    "Virgin Martyrs": "Mucenițe fecioare",
    "Virgin-martyr": "Muceniță fecioară",
    "Youths": "Tineri",
})


# The places, first part.
PARTS.update({
    "Abel-meholah": "Abel-Mehola",
    "Abkhazeti": "Abhazeti",
    "Achaia": "Ahaia",
    "Adamovka": "Adamovka",
    "Adrianople": "Adrianopol",
    "Adrianopolis": "Adrianopolis",
    "Aegae": "Eghe",
    "Aegean": "Marea Egee",
    "Aegina": "Egina",
    "Aetolia": "Etolia",
    "Africa": "Africa",
    "Agrigentum": "Agrigent",
    "Akhaltsikhe": "Ahaltsihe",
    "Aksum": "Axum",
    "Alaska": "Alaska",
    "Albania": "Albania",
    "Albanopolis": "Albanopolis",
    "Aleppo": "Alep",
    "Alexandria": "Alexandria",
    "All America": "Toată America",
    "Amasea": "Amasia",
    "Amasia": "Amasia",
    "Amastridea": "Amastrida",
    "Amastris": "Amastris",
    "Amathus": "Amatunta",
    "America": "America",
    "Amida": "Amida",
    "Amisos": "Amisos",
    "Amisus": "Amisos",
    "Amnia": "Amnia",
    "Amorion": "Amorion",
    "Amphipolis": "Amfipoli",
    "Anaplus": "Anaplus",
    "Anastasiopolis": "Anastasiopolis",
    "Anathoth": "Anatot",
    "Anatolia": "Anatolia",
    "Anazarbus": "Anazarb",
    "Ancyra": "Ancira",
    "Andronikov Monastery": "Mănăstirea Andronikov",
    "Anga": "Anga",
    "Annesi": "Anesi",
    "Annisa": "Anesi",
    "Antinoe": "Antinoe",
    "Antioch": "Antiohia",
    "Antioch in Pisidia": "Antiohia Pisidiei",
    "Antioch of Pisidia": "Antiohia Pisidiei",
    "Anzersk": "Anzersk",
    "Anzersk Island": "Insula Anzersk",
    "Apamea": "Apameea",
    "Aphrodisias": "Afrodisia",
    "Apollonia": "Apolonia",
    "Apulia": "Apulia",
    "Aquileia": "Aquileia",
    "Arabia": "Arabia",
    "Arabian Desert": "Pustia Arabiei",
    "Arauraka": "Arauraca",
    "Arbela": "Arbela",
    "Archangel Gabriel": "Arhanghelul Gavriil",
    "Arethusa": "Aretusa",
    "Argos": "Argos",
    "Arianzus": "Arianz",
    "Arkhangelsk": "Arhanghelsk",
    "Arkhangelsk lands": "Ținuturile Arhanghelsk",
    "Armagh": "Armagh",
    "Armenia": "Armenia",
    "Armenia Minor": "Armenia Mică",
    "Arsinoe": "Arsinoe",
    "Arta": "Arta",
    "Artanuji": "Artanuji",
    "Ascalon": "Ascalon",
    "Asia Minor": "Asia Mică",
    "Asikha": "Asiha",
    "Athens": "Atena",
    "Atka Island": "Insula Atka",
    "Atskuri": "Ațkuri",
    "Atsquri": "Ațkuri",
    "Attica": "Atica",
    "Auleneia": "Auleneia",
    "Auxerre": "Auxerre",
    "Avnezh": "Avnej",
    "Babylon": "Babilon",
    "Balkans": "Balcani",
    "Barcelona": "Barcelona",
    "Bari": "Bari",
    "Basarbov": "Basarabov",
    "Beauvais": "Beauvais",
    "Beirut": "Beirut",
    "Belarus": "Belarus",
    "Belev": "Belev",
    "Belgorod": "Belgorod",
    "Belgorod (Akkerman)": "Cetatea Albă (Akkerman)",
    "Belgrade": "Belgrad",
    "Belozersk": "Belozersk",
    "Belozersk lands": "Ținuturile Belozersk",
    "Belozersk lands and Mozhaisk": "Ținuturile Belozersk și Mojaisk",
    "Benevento": "Benevento",
    "Beocin Monastery": "Mănăstirea Beocin",
    "Berezan": "Berezan",
    "Berezniko": "Berezniko",
    "Beroea": "Bereea",
    "Besanduc": "Besanduc",
    "Bethany": "Betania",
    "Bethel": "Betel",
    "Bethlapeta": "Betlapeta",
    "Bethlehem": "Betleem",
    "Bethsaida": "Betsaida",
    "Bethsaloe": "Betsaloe",
    "Bezhetsk lands": "Ținuturile Bejețk",
    "Bialystok": "Bialystok",
    "Bisericani Monastery": "Mănăstirea Bisericani",
    "Bithynia": "Bitinia",
    "Blachernae": "Vlaherne",
    "Black Lake": "Lacul Negru",
    "Black Sea coast": "Coasta Mării Negre",
    "Bodbe": "Bodbe",
    "Boeotia": "Beoția",
    "Bogolyubovo": "Bogoliubovo",
    "Bohemia": "Boemia",
    "Bolgar": "Bolgar",
    "Borovichi": "Borovici",
    "Borovsk": "Borovsk",
    "Bosnia": "Bosnia",
    "Boston": "Boston",
    "Bostra": "Bostra",
    "Braunton": "Braunton",
    "Brest": "Brest",
    "Briansk": "Briansk",
    "Britain": "Britania",
    "British Isles": "Insulele Britanice",
    "Brooklyn": "Brooklyn",
    "Bryansk": "Briansk",
    "Bucharest": "București",
    "Budimlje": "Budimlje",
    "Bulgaria": "Bulgaria",
    "Butovo": "Butovo",
    "Buzau Mountains": "Munții Buzăului",
    "Byblos": "Biblos",
    "Byzantine Empire": "Imperiul Bizantin",
    "Byzantium": "Bizanț",
    "Byzantium (Constantinople)": "Bizanț (Constantinopol)",
})


# The places, second part.
PARTS.update({
    "Caesarea": "Cezareea",
    "Caesarea Maritima": "Cezareea Palestinei",
    "Caesarea in Cappadocia": "Cezareea Capadociei",
    "California": "California",
    "Campania": "Campania",
    "Cana": "Cana",
    "Cana of Galilee": "Cana Galileii",
    "Canaan": "Canaan",
    "Canopus": "Canopus",
    "Capernaum": "Capernaum",
    "Cappadocia": "Capadocia",
    "Caria": "Caria",
    "Carpathian Rus'": "Rusia Carpatică",
    "Carpatho-Russia": "Rusia Carpatică",
    "Carthage": "Cartagina",
    "Catania": "Catania",
    "Cephalonia": "Cefalonia",
    "Cernica": "Cernica",
    "Cernica Monastery": "Mănăstirea Cernica",
    "Chalcedon": "Calcedon",
    "Chalcis": "Calcis",
    "Chalcis desert": "Pustia Calcidei",
    "Chelm": "Chelm",
    "Chelma Hill": "Dealul Celma",
    "Cherepovets": "Cerepoveț",
    "Chernigov": "Cernigov",
    "Chernigov lands": "Ținuturile Cernigov",
    "Chernihiv": "Cernihiv",
    "Chernihiv lands": "Ținuturile Cernihiv",
    "Cherson": "Herson",
    "Chersonesus": "Chersones",
    "Chicago": "Chicago",
    "China": "China",
    "Chios": "Chios",
    "Chonae": "Colose (Hone)",
    "Choziba": "Hozeva",
    "Chukhloma": "Cuhloma",
    "Cilicia": "Cilicia",
    "Claudiopolis": "Claudiopolis",
    "Colophon": "Colofon",
    "Colossae": "Colose",
    "Coma": "Coma",
    "Comana": "Comana",
    "Constantia": "Constanția",
    "Constantinople": "Constantinopol",
    "Cordoba": "Cordoba",
    "Corfu": "Corfu",
    "Corinth": "Corint",
    "Corsica": "Corsica",
    "Cotyaeum": "Cotieon",
    "Crete": "Creta",
    "Crimea": "Crimeea",
    "Cucomo": "Cucomo",
    "Cucusus": "Cucuz",
    "Cyprus": "Cipru",
    "Cyrene": "Cirene",
    "Cyrenia": "Chirenia",
    "Cyrrhus": "Cir",
    "Cyzicus": "Cizic",
    "Czech Lands": "Țările Cehe",
    "Dabuda": "Dabuda",
    "Dalmatia": "Dalmația",
    "Dalmatian Monastery": "Mănăstirea Dalmaților",
    "Damascus": "Damasc",
    "Danube lands": "Ținuturile Dunării",
    "David Gareji": "David Garegi",
    "Davit-Gareji": "Davit-Garegi",
    "Decapolis": "Decapole",
    "Decapolis of Isauria": "Decapolea Isauriei",
    "Demetsana": "Dimițana",
    "Demitsana": "Dimițana",
    "Desert beyond the Jordan": "Pustia de dincolo de Iordan",
    "Devich": "Devici",
    "Devon": "Devon",
    "Dimitsana": "Dimițana",
    "Dioclea": "Dioclea",
    "Dioclea (Duklja)": "Dioclea (Duklja)",
    "Disevi": "Disevi",
    "Diveyevo": "Diveevo",
    "Dobrogea": "Dobrogea",
    "Dorostolum": "Durostor",
    "Dorostolum (Silistra)": "Durostor (Silistra)",
    "Drenica": "Drenița",
    "Durostorum": "Durostor",
    "Dymsk": "Dîmsk",
    "Dymskoe Lake": "Lacul Dîmskoe",
    "East Anglia": "Anglia de Răsărit",
    "Edessa": "Edesa",
    "Edra": "Edra",
    "Egypt": "Egipt",
    "Egyptian Desert": "Pustia Egiptului",
    "Elbasan": "Elbasan",
    "Eleutheropolis": "Eleuteropolis",
    "Elkosh": "Elcoș",
    "Emesa": "Emesa",
    "England": "Anglia",
    "Ephesus": "Efes",
    "Epirus": "Epir",
    "Epivato": "Epivata",
    "Essex": "Essex",
    "Ethiopia": "Etiopia",
    "Euboea": "Evia",
    "Euchaita": "Evhaita",
    "Euroea": "Evroia",
    "European Russia": "Rusia europeană",
    "Evia": "Evia",
    "Ferapontov": "Ferapontov",
    "Ferapontov Monastery": "Mănăstirea Ferapontov",
    "Ferapontovo": "Ferapontovo",
    "Feremane": "Feremane",
    "Ferentino": "Ferentino",
    "Flavia Neapolis": "Flavia Neapolis",
    "Florishchi": "Florișci",
    "Formia": "Formia",
    "France": "Franța",
    "Frasinei": "Frăsinei",
    "Galata": "Galata",
    "Galatia": "Galatia",
    "Galich": "Galici",
    "Galicia": "Galiția",
    "Galilee": "Galileea",
    "Gangra": "Gangra",
    "Gareji": "Garegi",
    "Gary": "Gary",
    "Gath-hepher": "Gat-Hefer",
    "Gaul": "Galia",
    "Gaza": "Gaza",
    "Gdov": "Gdov",
    "Gdov lands": "Ținuturile Gdov",
    "George Hill": "Dealul Sfântului Gheorghe",
    "Georgia": "Georgia",
    "Germany": "Germania",
    "Gibeah of Phinehas": "Ghibeea lui Finees",
    "Gilead": "Galaad",
    "Glendalough": "Glendalough",
    "Glushitsa": "Glușița",
    "Gori district": "Ținutul Gori",
    "Gortyna": "Gortina",
    "Gothia": "Goția",
    "Gothic lands": "Ținuturile gotice",
    "Great Lavra": "Marea Lavră",
    "Great Lavra of Saint Sabbas": "Marea Lavră a Sfântului Sava",
    "Great Moravia": "Moravia Mare",
    "Greece": "Grecia",
    "Guria": "Guria",
    "Hartland": "Hartland",
    "Hauran": "Hauran",
    "Hebron": "Hebron",
    "Heliopolis": "Heliopolis",
    "Hellas": "Elada",
})


# The places, third part.
PARTS.update({
    "Hellespont": "Helespont",
    "Heraclea": "Heracleea",
    "Hereti": "Hereti",
    "Hermopolis": "Hermopolis",
    "Herzegovina": "Herțegovina",
    "Hierapolis": "Ierapole",
    "Hilandar": "Hilandar",
    "Holy Land": "Țara Sfântă",
    "Holy Trinity-Saint Sergius Lavra": "Lavra Sfintei Treimi a Sfântului Serghie",
    "Hosios Loukas": "Osios Lucas",
    "Hungary": "Ungaria",
    "Hypaepa": "Hipepa",
    "Iași": "Iași",
    "Iconium": "Iconium",
    "Iken": "Iken",
    "Illinois": "Illinois",
    "Illyria": "Iliria",
    "Illyricum": "Iliric",
    "India": "India",
    "Indiana": "Indiana",
    "Ioannina": "Ianina",
    "Irap": "Irap",
    "Ireland": "Irlanda",
    "Irenopolis": "Irinopolis",
    "Irkutsk": "Irkutsk",
    "Irkutsk province": "Ținutul Irkutsk",
    "Isauria": "Isauria",
    "Israel": "Israel",
    "Italy": "Italia",
    "Iza": "Iza",
    "Jackson": "Jackson",
    "Jerusalem": "Ierusalim",
    "Joppa": "Iope",
    "Jordan River": "Râul Iordan",
    "Judah": "Iuda",
    "Judea": "Iudeea",
    "Judean Desert": "Pustia Iudeii",
    "Judean Wilderness": "Pustia Iudeii",
    "Kallippi": "Calipi",
    "Kaluga": "Kaluga",
    "Kaluga lands": "Ținuturile Kaluga",
    "Kalyazin": "Kaliazin",
    "Kampsada": "Campsada",
    "Kaniv": "Kaniv",
    "Karelia": "Carelia",
    "Kargopol": "Kargopol",
    "Kargopol lands": "Ținuturile Kargopol",
    "Kartli": "Kartli",
    "Kartli (Iberia)": "Kartli (Iberia)",
    "Kashin": "Kașin",
    "Kasperovo": "Kasperovo",
    "Kastoria": "Castoria",
    "Kastorion": "Castorion",
    "Kavsokalyvia": "Cavsocalivia",
    "Kazan": "Kazan",
    "Kekhta": "Kehta",
    "Kellia": "Chilii",
    "Keno Lake": "Lacul Keno",
    "Kerch": "Kerci",
    "Kerkyra": "Corfu",
    "Kerkyra (Corfu)": "Corfu",
    "Khakhuli": "Hahuli",
    "Khakhuli Monastery": "Mănăstirea Hahuli",
    "Kharkiv": "Harkov",
    "Kherson": "Herson",
    "Kherson lands": "Ținuturile Herson",
    "Khlynov": "Hlînov",
    "Kholm": "Holm",
    "Khust": "Hust",
    "Khutyn": "Hutîn",
    "Kios": "Kios",
    "Klarjeti": "Klargeti",
    "Klops Monastery": "Mănăstirea Klops",
    "Kodiak": "Kodiak",
    "Kola": "Kola",
    "Komel": "Komel",
    "Komel Forest": "Pădurea Komel",
    "Kondakovo": "Kondakovo",
    "Konevets": "Konevets",
    "Korets": "Korets",
    "Korissos": "Corisos",
    "Kornet": "Kornet",
    "Korotsk": "Koroțk",
    "Kosinsk": "Kosinsk",
    "Kosovo": "Kosovo",
    "Kostroma": "Kostroma",
    "Kostroma lands": "Ținuturile Kostroma",
    "Kozelshchyna": "Kozelșcina",
    "Kozelsk": "Kozelsk",
    "Kozhe Lake": "Lacul Koje",
    "Krasny Kholm": "Krasnîi Holm",
    "Kratovo": "Kratovo",
    "Kremenets": "Kremeneț",
    "Kromna": "Cromna",
    "Kronstadt": "Kronstadt",
    "Krushedol": "Kruședol",
    "Kubensk": "Kubensk",
    "Kudinovo": "Kudinovo",
    "Kursk": "Kursk",
    "Kushta": "Kușta",
    "Kvabtakhevi Monastery": "Mănăstirea Kvabtahevi",
    "Kveli fortress": "Cetatea Kveli",
    "Kwethluk": "Kwethluk",
    "Kyiv": "Chiev",
    "Kyiv Caves": "Peșterile Chievului",
    "Kyiv Caves Lavra": "Lavra Peșterilor din Chiev",
    "Kyiv Far Caves": "Peșterile Depărtate ale Chievului",
    "Kyiv Near Caves": "Peșterile Apropiate ale Chievului",
    "Kyiv region": "Ținutul Chievului",
    "Laconia": "Laconia",
    "Lake Iliamna": "Lacul Iliamna",
    "Lake Ilmen": "Lacul Ilmen",
    "Lake Ilo": "Lacul Ilo",
    "Lake Kubenskoye": "Lacul Kubenskoe",
    "Lake Ladoga": "Lacul Ladoga",
    "Lake Onega": "Lacul Onega",
    "Lake Orta": "Lacul Orta",
    "Lake Pskov": "Lacul Pskov",
    "Lake Seliger": "Lacul Seliger",
    "Lake Vorbozomsk": "Lacul Vorbozomsk",
    "Lampsacus": "Lampsac",
    "Land of Asher": "Ținutul lui Așer",
    "Land of Uz": "Ținutul Uz",
    "Land of Zebulun": "Ținutul lui Zabulon",
    "Land of the tribe of Simeon": "Ținutul seminției lui Simeon",
    "Langres": "Langres",
    "Laodicea": "Laodiceea",
    "Lavra of Saint Sabbas": "Lavra Sfântului Sava",
    "Lazica": "Lazica",
    "Le Mans": "Le Mans",
    "Lebanon": "Liban",
    "Leinster": "Leinster",
    "Lelich": "Lelici",
    "Lentini": "Lentini",
    "Leokhnovo": "Leohnovo",
    "Leontini": "Leontini",
    "Lesbos": "Lesbos",
    "Leucosia (Nicosia)": "Nicosia",
    "Lezna River": "Râul Lezna",
    "Libertyville": "Libertyville",
    "Libya": "Libia",
    "Lindisfarne": "Lindisfarne",
    "Lipari": "Lipari",
    "Lithuania": "Lituania",
    "Little Russia (Ukraine)": "Rusia Mică (Ucraina)",
    "Liubech": "Liubeci",
    "Liubimograd": "Liubimograd",
    "Loma": "Loma",
    "Loutraki": "Loutraki",
    "Lubny": "Lubnî",
})


# The places, fourth part.
PARTS.update({
    "Lubyatov": "Liubiatovo",
    "Lucania": "Lucania",
    "Lukhov": "Luhov",
    "Lycaonia": "Licaonia",
    "Lycia": "Licia",
    "Lycopolis": "Licopolis",
    "Lydda": "Lida",
    "Lydia": "Lidia",
    "Lykaonia": "Licaonia",
    "Lyons": "Lyon",
    "Lystra": "Listra",
    "Lérins": "Lerins",
    "Macedonia": "Macedonia",
    "Magdala": "Magdala",
    "Magedon": "Maghedon",
    "Magnesia": "Magnezia",
    "Magydos": "Magidos",
    "Maiuma": "Maiuma",
    "Makarovo": "Makarovo",
    "Makhrishche": "Mahrișce",
    "Malopinega": "Malopinega",
    "Malta": "Malta",
    "Mandera": "Mandera",
    "Mangup": "Mangup",
    "Mantinea": "Mantineea",
    "Mar Saba": "Mar Saba",
    "Maratha": "Marata",
    "Marathon": "Maraton",
    "Marcianopolis": "Marcianopolis",
    "Marikat": "Marikat",
    "Marseilles": "Marsilia",
    "Martyropolis": "Martiropolis",
    "Mauretania": "Mauritania",
    "Medikion": "Medichion",
    "Medikion Monastery": "Mănăstirea Medichion",
    "Medin": "Medin",
    "Mega Dendron": "Mega Dendron",
    "Meglin": "Meglin",
    "Melitene": "Melitina",
    "Melitopolis": "Melitopolis",
    "Menuthis": "Menutis",
    "Menyusha": "Meniușa",
    "Merkushino": "Merkușino",
    "Mesopotamia": "Mesopotamia",
    "Mesteacăn": "Mesteacăn",
    "Methymna": "Metimna",
    "Mezen": "Mezen",
    "Mgvime": "Mgvime",
    "Milan": "Milan",
    "Mineo": "Mineo",
    "Minneapolis": "Minneapolis",
    "Moesia": "Moesia",
    "Mogarissos": "Mogarisos",
    "Mogilev": "Moghilev",
    "Moldavia": "Moldova",
    "Moldova": "Moldova",
    "Monembasia": "Monemvasia",
    "Monte Cassino": "Monte Cassino",
    "Monteluco": "Monteluco",
    "Montenegro": "Muntenegru",
    "Monza River": "Râul Monza",
    "Moravia": "Moravia",
    "Morea (Peloponnese)": "Moreea (Peloponez)",
    "Moresheth": "Moreșet",
    "Moscow": "Moscova",
    "Moscow lands": "Ținuturile Moscovei",
    "Mount Athos": "Muntele Athos",
    "Mount Colzim": "Muntele Colzim",
    "Mount Ephraim": "Muntele Efraim",
    "Mount Galesion": "Muntele Galision",
    "Mount Galesius": "Muntele Galision",
    "Mount Hor": "Muntele Hor",
    "Mount Kyminas": "Muntele Kiminas",
    "Mount Maleon": "Muntele Maleon",
    "Mount Myrsinon": "Muntele Mirsinon",
    "Mount Nebo": "Muntele Nebo",
    "Mount Olympus": "Muntele Olimp",
    "Mount Sagmata": "Muntele Sagmata",
    "Mount Sinai": "Muntele Sinai",
    "Mount Skopa": "Muntele Skopa",
    "Mount Taurus": "Munții Taurus",
    "Mount of Olives": "Muntele Măslinilor",
    "Mozhaisk": "Mojaisk",
    "Mrkonjici": "Mrkonjici",
    "Mtskheta": "Mțheta",
    "Murom": "Murom",
    "Murom Island": "Insula Murom",
    "Mutalaska": "Mutalasca",
    "Mylapore": "Mylapore",
    "Mylasa": "Milasa",
    "Myra": "Mira",
    "Myra in Lycia": "Mira Liciei",
    "Myrgorod": "Mîrgorod",
    "Mytilene": "Mitilene",
    "Naissus": "Naisus",
    "Najran": "Nagran",
    "Nalšia": "Nalșia",
    "Nanterre": "Nanterre",
    "Naples": "Napoli",
    "Nauplion": "Nauplion",
    "Nazareth": "Nazaret",
    "Nazianzus": "Nazianz",
    "Nea Makri": "Nea Makri",
    "Neamts Monastery": "Mănăstirea Neamț",
    "Neamț": "Neamț",
    "Neapolis": "Neapolis",
    "Near Constantinople": "Lângă Constantinopol",
    "Neocaesarea": "Neocezareea",
    "Nerchinsk": "Nercinsk",
    "New Lake": "Lacul Nou",
    "New York": "New York",
    "Nicaea": "Niceea",
    "Nicea": "Niceea",
    "Nicomedia": "Nicomidia",
    "Nicopolis": "Nicopole",
    "Nicosia": "Nicosia",
    "Nikiforovskaya": "Nikiforovskaia",
    "Nisibis": "Nisibi",
    "Nitria": "Nitria",
    "Nizhni-Novgorod": "Nijni Novgorod",
    "Nizhny Novgorod": "Nijni Novgorod",
    "Nizhny Novgorod lands": "Ținuturile Nijni Novgorod",
    "Nizhyn": "Nijîn",
    "North Africa": "Africa de Nord",
    "North America": "America de Nord",
    "North Macedonia": "Macedonia de Nord",
    "Northumbria": "Northumbria",
    "Novara": "Novara",
    "Novgorod": "Novgorod",
    "Novgorod lands": "Ținuturile Novgorod",
    "Noviodunum": "Noviodunum",
    "Novoezersk": "Novoezersk",
    "Nurma": "Nurma",
    "Nursia": "Nursia",
    "Nyssa": "Nisa",
    "Obnora River": "Râul Obnora",
    "Odessa": "Odesa",
    "Odrino": "Odrino",
    "Ohrid": "Ohrida",
    "Old Lavra of Chariton": "Vechea Lavră a lui Hariton",
    "Olonets": "Oloneț",
    "Olonets lands": "Ținuturile Oloneț",
    "Olshansk": "Olșansk",
    "Olympus": "Olimp",
    "Omala": "Omala",
    "Ondrusov": "Ondrusov",
    "Ophrah": "Ofra",
    "Opso": "Opso",
    "Orel lands": "Ținuturile Oriol",
    "Oshevensk": "Oșevensk",
})


# The places, fifth part.
PARTS.update({
    "Osrhoene": "Osroene",
    "Ostia": "Ostia",
    "Ostracine": "Ostracina",
    "Ostrog": "Ostrog",
    "Ovche Pole": "Ovce Pole",
    "Ovruch": "Ovruci",
    "Ozovia": "Ozovia",
    "Palermo": "Palermo",
    "Palestine": "Palestina",
    "Palii Island": "Insula Palii",
    "Pamphylia": "Pamfilia",
    "Pannonia": "Panonia",
    "Paphlagonia": "Paflagonia",
    "Paphos": "Pafos",
    "Paramythia": "Paramitia",
    "Paris": "Paris",
    "Parium": "Parion",
    "Paros": "Paros",
    "Parthia": "Partia",
    "Patara": "Patara",
    "Patmos": "Patmos",
    "Patras": "Patras",
    "Pec": "Peci",
    "Pechenga": "Pecenga",
    "Pechenga Monastery": "Mănăstirea Pecenga",
    "Pekhorka": "Pehorka",
    "Pelecete": "Pelechita",
    "Pelekete": "Pelechita",
    "Pelekete Monastery": "Mănăstirea Pelechita",
    "Peloponnese": "Peloponez",
    "Pelshma": "Pelșma",
    "Pelusium": "Pelusium",
    "Pennsylvania": "Pennsylvania",
    "Perekop (Perekomsky) Monastery": "Mănăstirea Perekop (Perekomski)",
    "Pereslavl": "Pereslavl",
    "Pereslavl-Zalessky": "Pereslavl-Zalesski",
    "Pereyaslavl": "Pereiaslavl",
    "Pereyaslavl-Zalessky": "Pereiaslavl-Zalesski",
    "Pergamum": "Pergam",
    "Perge": "Perga",
    "Peristerai": "Peristera",
    "Perm": "Perm",
    "Perm lands": "Ținuturile Perm",
    "Persia": "Persia",
    "Persia and the East": "Persia și Răsăritul",
    "Peshnosha": "Peșnoșa",
    "Petrograd": "Petrograd",
    "Peć": "Peci",
    "Pharan": "Faran",
    "Pharasa": "Farasa",
    "Philadelphia": "Filadelfia",
    "Philippopolis": "Filipopol",
    "Philotheou Monastery": "Mănăstirea Filoteu",
    "Phocis": "Focida",
    "Phoenicia": "Fenicia",
    "Phrygia": "Frigia",
    "Pinega": "Pinega",
    "Pinsk": "Pinsk",
    "Pisidia": "Pisidia",
    "Plousias": "Plusias",
    "Pochaev": "Pociaev",
    "Pochaiv": "Pociaiv",
    "Podolia": "Podolia",
    "Poiana Marului": "Poiana Mărului",
    "Pokutia": "Pocuția",
    "Poland": "Polonia",
    "Polotsk": "Poloțk",
    "Poltava": "Poltava",
    "Poltava lands": "Ținuturile Poltava",
    "Poltava region": "Ținutul Poltava",
    "Polybotum": "Polivot",
    "Pomorie": "Pomorie",
    "Pompeiopolis": "Pompeiopolis",
    "Pontus": "Pont",
    "Popovo": "Popovo",
    "Porkhov": "Porhov",
    "Poshekhonye": "Poșehonie",
    "Pozzuoli": "Pozzuoli",
    "Prague": "Praga",
    "Pretorium": "Pretoriu",
    "Priluki": "Priluki",
    "Prokopion": "Prokopion",
    "Protection Convent": "Mănăstirea Acoperământului Maicii Domnului",
    "Prusa": "Prusa",
    "Pryluky": "Priluki",
    "Prymnessus": "Primnesos",
    "Pshinja": "Pcinia",
    "Pskov": "Pskov",
    "Pskov Caves Monastery": "Mănăstirea Peșterilor din Pskov",
    "Ptinapor": "Ptinapor",
    "Ptolemais": "Ptolemaida",
    "Puteoli": "Puteoli",
    "Putna": "Putna",
    "Pythias": "Pitias",
    "Périgueux": "Perigueux",
    "Radonezh": "Radonej",
    "Radonezh and Serpukhov": "Radonej și Serpuhov",
    "Radoviste": "Radoviște",
    "Raithu": "Raitu",
    "Ramah": "Rama",
    "Ramathaim": "Armatem",
    "Ramathaim-Zophim": "Armatem-Țofim",
    "Ramnic": "Râmnic",
    "Ravanica": "Ravanița",
    "Ravenna": "Ravenna",
    "Resafa": "Resafa",
    "Rethymnon": "Retimno",
    "Rhosus": "Rosos",
    "Rila": "Rila",
    "Robeika": "Robeika",
    "Robeika River": "Râul Robeika",
    "Roman Britain": "Britania romană",
    "Romania": "România",
    "Rome": "Roma",
    "Rome and Milan": "Roma și Milan",
    "Rome and the East": "Roma și Răsăritul",
    "Rossos": "Rosos",
    "Rostov": "Rostov",
    "Rostov lands": "Ținuturile Rostov",
    "Rus'": "Rusia",
    "Russia": "Rusia",
    "Russian North": "Nordul Rusiei",
    "Russian nobility": "Boierimea rusă",
    "Ryazan": "Riazan",
    "Ryazan province": "Ținutul Riazan",
    "Rzhev": "Rjev",
    "Saint John": "Sfântul Ioan",
    "Saint Petersburg": "Sankt Petersburg",
    "Salamis": "Salamina",
    "Salamis (Constantia)": "Salamina (Constanția)",
    "Salona": "Salona",
    "Samaria": "Samaria",
    "Samegrelo": "Samegrelo",
    "Samosata": "Samosata",
    "Samothrace": "Samotracia",
    "Samtskhe": "Samțhe",
    "San Francisco": "San Francisco",
    "Saragossa": "Saragossa",
    "Sardis": "Sardes",
    "Sarov": "Sarov",
    "Scetis": "Schit",
    "Scotland": "Scoția",
    "Scythia": "Scitia",
    "Scythia Minor": "Scitia Mică",
    "Sebaste": "Sevastia",
    "Sebastea": "Sevastia",
    "Sebino": "Sebino",
    "Seleucia": "Seleucia",
    "Seleucia-Ctesiphon": "Seleucia-Ctesifon",
    "Selymbria": "Selimbria",
})


# The places, sixth part.
PARTS.update({
    "Serbia": "Serbia",
    "Sergiev Posad": "Serghiev Posad",
    "Serpukhov": "Serpuhov",
    "Serres": "Serres",
    "Shanghai": "Shanghai",
    "Shenkursk": "Șenkursk",
    "Shiloh": "Șilo",
    "Shio-Mgvime Monastery": "Mănăstirea Șio-Mgvime",
    "Shovskoe": "Șovskoe",
    "Shuya": "Șuia",
    "Shuzhgora": "Șujgora",
    "Siberia": "Siberia",
    "Siblag camps": "Lagărele Siblag",
    "Sicily": "Sicilia",
    "Side": "Side",
    "Sigriane": "Sigriana",
    "Silistra": "Silistra",
    "Simferopol": "Simferopol",
    "Sinai": "Sinai",
    "Sinai and Raithu": "Sinai și Raitu",
    "Sinai wilderness": "Pustia Sinaiului",
    "Singidunum": "Singidunum",
    "Sinope": "Sinope",
    "Sinope and Amasea": "Sinope și Amasia",
    "Sinozersk": "Sinozersk",
    "Sirmium": "Sirmium",
    "Sisan": "Sisan",
    "Sitka": "Sitka",
    "Siya Monastery": "Mănăstirea Siia",
    "Skepsis": "Schepsis",
    "Sketis": "Schit",
    "Skrino": "Skrino",
    "Slutsk": "Sluțk",
    "Smolensk": "Smolensk",
    "Smyrna": "Smirna",
    "Snetogorsk": "Snetogorsk",
    "Snetogorsk Monastery": "Mănăstirea Snetogorsk",
    "Sofia": "Sofia",
    "Sokhot River": "Râul Sohot",
    "Solovki": "Solovki",
    "Solovki Islands": "Insulele Solovki",
    "Solovki Monastery": "Mănăstirea Solovki",
    "Sophene": "Sofena",
    "Sora River": "Râul Sora",
    "Soreoi": "Sorei",
    "Spain": "Spania",
    "Spoleto": "Spoleto",
    "Spruce Island": "Insula Spruce",
    "Srem": "Srem",
    "St Albans": "St Albans",
    "St. Petersburg": "Sankt Petersburg",
    "Stara Zagora": "Stara Zagora",
    "Staritsa": "Starița",
    "Starytsa": "Starița",
    "Steirion": "Stirion",
    "Stolobny Island": "Insula Stolobnîi",
    "Storozhi Hill": "Dealul Storoji",
    "Strobil": "Strobil",
    "Strumica": "Strumița",
    "Studenica": "Studenița",
    "Subiaco": "Subiaco",
    "Suceava": "Suceava",
    "Sura": "Sura",
    "Susa": "Susa",
    "Suzdal": "Suzdal",
    "Svensky Monastery": "Mănăstirea Svenski",
    "Svir": "Svir",
    "Sviyazhsk": "Sviiajsk",
    "Sweden": "Suedia",
    "Syandeba": "Siandeba",
    "Syandemsk": "Siandemsk",
    "Syanzhema": "Sianjema",
    "Syanzhema River": "Râul Sianjema",
    "Sykeon": "Sicheon",
    "Symbola": "Simbola",
    "Symbola Monastery": "Mănăstirea Simbola",
    "Synnada": "Sinada",
    "Syracuse": "Siracuza",
    "Syria": "Siria",
    "Tabatha": "Tavata",
    "Tabenna": "Tavena",
    "Tabennisi": "Tavenisi",
    "Tambov": "Tambov",
    "Tao": "Tao",
    "Tao-Klarjeti": "Tao-Klargeti",
    "Taormina": "Taormina",
    "Taphanes": "Tafnes",
    "Targala": "Targala",
    "Tarnovo": "Târnovo",
    "Tarsus": "Tars",
    "Tarsus and Achaia": "Tars și Ahaia",
    "Tarsus and Rossos": "Tars și Rosos",
    "Tarsus and the East": "Tars și Răsăritul",
    "Tashkent": "Tașkent",
    "Tauresium": "Tauresium",
    "Tazlău": "Tazlău",
    "Tazlău Monastery": "Mănăstirea Tazlău",
    "Tbilisi": "Tbilisi",
    "Tekoa": "Tecoa",
    "Tenedos": "Tenedos",
    "Tennis": "Tenis",
    "Teratyn": "Teratîn",
    "Terracina": "Terracina",
    "The East": "Răsăritul",
    "The Jordan": "Iordanul",
    "Thebaid": "Tebaida",
    "Thebes": "Teba",
    "Thebes of Egypt": "Teba Egiptului",
    "Thessalonica": "Tesalonic",
    "Thessaloniki": "Tesalonic",
    "Thessaly": "Tesalia",
    "Thrace": "Tracia",
    "Thyateira": "Tiatira",
    "Tikhvin": "Tihvin",
    "Tiksna": "Tiksna",
    "Tishbe of Gilead": "Tișbe din Galaad",
    "Tmutarakan": "Tmutarakan",
    "Tobolsk": "Tobolsk",
    "Tolva": "Tolva",
    "Toropets": "Toropeț",
    "Torzhok": "Torjok",
    "Totma": "Totma",
    "Trajanopolis": "Traianopolis",
    "Tralles": "Tralles",
    "Transcarpathia": "Transcarpatia",
    "Trebia": "Trebia",
    "Trebizond": "Trapezunt",
    "Tremithus": "Trimitunta",
    "Trier": "Trier",
    "Triglia": "Triglia",
    "Trikala": "Trikala",
    "Trinity Lavra": "Lavra Sfintei Treimi",
    "Trinity-Sergius Lavra": "Lavra Sfintei Treimi a Sfântului Serghie",
    "Tripoli": "Tripoli",
    "Troas": "Troada",
    "Tsarskoye Selo": "Țarskoe Selo",
    "Tula lands": "Ținuturile Tula",
    "Turchasovo": "Turceasovo",
    "Turov": "Turov",
    "Tuscany": "Toscana",
    "Tver": "Tver",
    "Tver lands": "Ținuturile Tver",
    "Tyana": "Tiana",
    "Tyre": "Tir",
    "Uchma": "Ucima",
    "Uglich": "Uglici",
    "Ukraine": "Ucraina",
    "United States": "Statele Unite",
    "Unzha": "Unja",
    "Upper Thebaid": "Tebaida de Sus",
    "Ur of the Chaldees": "Urul Caldeilor",
    "Ushchelye": "Ușcelie",
    "Ust-Totma": "Ust-Totma",
    "Ust-Vym": "Ust-Vîm",
    "Ustiug": "Ustiug",
    "Ustyug": "Ustiug",
    "Vaga": "Vaga",
    "Vaga lands": "Ținuturile Vaga",
    "Vagharshapat": "Vagharshapat",
    "Valaam": "Valaam",
})


# The places, seventh and last part.
PARTS.update({
    "Valencia": "Valencia",
    "Varnitsa": "Varnița",
    "Varzuga": "Varzuga",
    "Vasilevo": "Vasilevo",
    "Vaste": "Vaste",
    "Vasyliv": "Vasiliv",
    "Vazheozero region": "Ținutul Vajeozero",
    "Velehrad": "Velehrad",
    "Veliki Luki": "Velikie Luki",
    "Veliky Ustiug": "Velikii Ustiug",
    "Veliky Ustyug": "Velikii Ustiug",
    "Venice": "Veneția",
    "Verkhoturye": "Verhoturie",
    "Verkola": "Verkola",
    "Verona": "Verona",
    "Verulamium": "Verulamium",
    "Verulamium (St Albans)": "Verulamium (St Albans)",
    "Vetluga": "Vetluga",
    "Videlebye": "Videlebie",
    "Vilnius": "Vilnius",
    "Vishera": "Vișera",
    "Vladimir": "Vladimir",
    "Vladimir lands": "Ținuturile Vladimir",
    "Vladimir-Suzdal": "Vladimir-Suzdal",
    "Vladimir-in-Volhynia": "Vladimir din Volînia",
    "Volga Bulgaria": "Bulgaria de pe Volga",
    "Volhynia": "Volînia",
    "Volissos": "Volisos",
    "Volodymyr-Volhynia": "Volodîmîr-Volînski",
    "Vologda": "Vologda",
    "Vologda lands": "Ținuturile Vologda",
    "Volokolamsk": "Volokolamsk",
    "Vorbozomsk Lake": "Lacul Vorbozomsk",
    "Voronezh": "Voronej",
    "Vracar": "Vracear",
    "Vyatka": "Viatka",
    "Vyazma": "Viazma",
    "Vyritsa": "Vîrița",
    "Vyshgorod": "Vîșgorod",
    "Vyshhorod": "Vîșgorod",
    "Wales": "Țara Galilor",
    "Warsaw": "Varșovia",
    "Western Rus": "Rusia apuseană",
    "White Lake": "Lacul Alb",
    "White Lake (Beloozero)": "Lacul Alb (Beloozero)",
    "White Lake region": "Ținutul Lacului Alb",
    "White Sea": "Marea Albă",
    "Wilkes-Barre": "Wilkes-Barre",
    "Wonderful Mountain": "Muntele Minunat",
    "Yakhroma": "Iahroma",
    "Yarenga": "Iarenga",
    "Yaroslavl": "Iaroslavl",
    "Yaroslavl lands": "Ținuturile Iaroslavl",
    "Yaroslavl province": "Ținutul Iaroslavl",
    "Yashezero": "Iașezero",
    "Yazvishche": "Iazvișce",
    "Yekaterinburg": "Ekaterinburg",
    "Yuriev (Tartu)": "Iuriev (Tartu)",
    "Yuriev Monastery": "Mănăstirea Iuriev",
    "Yuriev-Polsky": "Iuriev-Polski",
    "Yuryegorsk": "Iurieegorsk",
    "Zadonsk": "Zadonsk",
    "Zahumlje": "Zahumlje",
    "Zahumlje (Zakholm)": "Zahumlje (Zaholm)",
    "Zakynthos": "Zakintos",
    "Zaozersk": "Zaozersk",
    "Zelenets": "Zeleneț",
    "Zemplin region": "Ținutul Zemplin",
    "Zeta": "Zeta",
    "Zeugma": "Zeugma",
    "Zhabyn Monastery": "Mănăstirea Jabîn",
    "Zheleznoborov": "Jeleznoborov",
    "Zhicha": "Jicea",
    "Zhicha Monastery": "Mănăstirea Jicea",
    "Zvenigorod": "Zvenigorod",
    "Zverki": "Zverki",
    "all Greece": "toată Grecia",
    "all Rus'": "toată Rusia",
    "all Russia": "toată Rusia",
    "all Slavic lands": "toate țările slave",
    "all schools": "toate școlile",
    "all the Slavic lands": "toate țările slave",
    "and Ephesus": "și Efes",
    "beyond the Danube": "dincolo de Dunăre",
    "gardens and vineyards": "grădini și vii",
    "near Agrigentum": "lângă Agrigent",
    "near Alexandria": "lângă Alexandria",
    "near Ancyra": "lângă Ancira",
    "near Antioch": "lângă Antiohia",
    "near Apamea": "lângă Apameea",
    "near Bialystok": "lângă Bialystok",
    "near Borovsk": "lângă Borovsk",
    "near Cherepovets": "lângă Cerepoveț",
    "near Chernigov": "lângă Cernigov",
    "near Constantinople": "lângă Constantinopol",
    "near Cyrrhus": "lângă Cir",
    "near Dorostolum": "lângă Durostor",
    "near Edessa": "lângă Edesa",
    "near Ephesus": "lângă Efes",
    "near Galich": "lângă Galici",
    "near Gaza": "lângă Gaza",
    "near Kargopol": "lângă Kargopol",
    "near Kiev": "lângă Chiev",
    "near Kyiv": "lângă Chiev",
    "near Moscow": "lângă Moscova",
    "near Mount Tabor": "lângă Muntele Tabor",
    "near Mtskheta": "lângă Mțheta",
    "near Novgorod": "lângă Novgorod",
    "near Prusa": "lângă Prusa",
    "near Pskov": "lângă Pskov",
    "near Rostov": "lângă Rostov",
    "near Samosata": "lângă Samosata",
    "near Staraya Russa": "lângă Staraia Rusa",
    "near Totma": "lângă Totma",
    "near Uglich": "lângă Uglici",
    "near Verkhoturye": "lângă Verhoturie",
    "near Vladimir": "lângă Vladimir",
    "near Volokolamsk": "lângă Volokolamsk",
    "near the Dvina": "lângă Dvina",
    "on the Dvina": "pe Dvina",
    "on the Onega": "pe Onega",
    "the Balkans": "Balcanii",
    "the Belozersk country": "ținutul Belozersk",
    "the Bistrița valley": "valea Bistriței",
    "the Black Sea coast and the Caucasus": "coasta Mării Negre și Caucazul",
    "the Buzau Mountains": "Munții Buzăului",
    "the Caucasus": "Caucazul",
    "the Cells": "Chiliile",
    "the Cherepovets country": "ținutul Cerepoveț",
    "the Danube lands": "ținuturile Dunării",
    "the Dvina country": "ținutul Dvinei",
    "the East": "Răsăritul",
    "the Egyptian desert": "pustia Egiptului",
    "the Gentile nations": "neamurile",
    "the Golden Horde": "Hoarda de Aur",
    "the Holy Land": "Țara Sfântă",
    "the Jordan": "Iordanul",
    "the Jordan desert": "pustia Iordanului",
    "the Judean desert": "pustia Iudeii",
    "the Judean wilderness": "pustia Iudeii",
    "the Kola north": "nordul Kolei",
    "the Komi lands": "ținuturile komi",
    "the Mount of Olives": "Muntele Măslinilor",
    "the Obnora": "Obnora",
    "the Oka country": "ținutul Okăi",
    "the Olonets country": "ținutul Oloneț",
    "the Onega country": "ținutul Onegăi",
    "the Palestinian desert": "pustia Palestinei",
    "the Peloponnese": "Peloponezul",
    "the Pinega country": "ținutul Pinegăi",
    "the Pskov Caves": "Peșterile Pskovului",
    "the Pčinja valley": "valea Pcinei",
    "the Russian North": "Nordul Rusiei",
    "the Russian north": "nordul Rusiei",
    "the Seto lands": "ținuturile seto",
    "the Smolensk cemetery": "cimitirul Smolensk",
    "the Sora": "Sora",
    "the Studios monastery": "mănăstirea Studion",
    "the Thebaid": "Tebaida",
    "the Tikhvin country": "ținutul Tihvin",
    "the Urals": "Munții Ural",
    "the Volga lands": "ținuturile Volgăi",
    "the Vologda country": "ținutul Vologda",
    "the White Sea": "Marea Albă",
    "the White Sea coast": "coasta Mării Albe",
    "the Wonderful Mountain": "Muntele Minunat",
    "the Yakhroma": "Iahroma",
    "the desert of Egypt": "pustia Egiptului",
    "the inner Egyptian desert": "pustia lăuntrică a Egiptului",
    "the lands of the apostolic mission": "ținuturile propovăduirii apostolice",
    "the northern Thebaid": "Tebaida de Nord",
    "the northern missions": "misiunile din nord",
    "the whole world": "toată lumea",
    "the wilderness beyond Mesopotamia": "pustia de dincolo de Mesopotamia",
    "travelers' gates": "porțile călătorilor",
    "Žiča": "Jicea",
})
