# -*- coding: utf-8 -*-
"""Russian for the vocabulary beside a life. TEXT = {English: rendering}.

Keyed by the English phrase exactly as the index spells it, so a phrase that
is no longer there fails the build rather than quietly never appearing.

Received Russian forms throughout: the orders of sanctity as the menaia name
them, the Typikon's ranks of feast, and the ordinary Russian names of places
and peoples. Where no received form exists the name is transliterated.
"""

TEXT = {}

# The order of sanctity, which is the badge on every card. These follow the
# calendar's own renderings, so the two pages name a saint the same way.
TEXT.update({
    "Angelic": "Бесплотные Силы",
    "Apostle": "Апостол",
    "Confessor": "Исповедник",
    "Equal-to-the-Apostles": "Равноапостольный",
    "Feast": "Праздник",
    "Fool-for-Christ": "Юродивый",
    "Great Martyr": "Великомученик",
    "Hierarch": "Святитель",
    "Hieromartyr": "Священномученик",
    "Martyr": "Мученик",
    "Monastic": "Преподобный",
    "New Martyr": "Новомученик",
    "Other": "Иное",
    "Passion-bearer": "Страстотерпец",
    "Prophet": "Пророк",
    "Righteous": "Праведный",
    "Unmercenary": "Бессребреник",
    "Virgin Martyr": "Мученица дева",
})

# The Churches whose calendars keep the day.
TEXT.update({
    "Greek": "Греческая",
    "Antiochian": "Антиохийская",
    "Romanian": "Румынская",
    "Ukrainian": "Украинская",
    "Russian": "Русская",
    "Serbian": "Сербская",
    "OCA": "ПЦА",
})

# The chips under a name.
TEXT.update({
    "Monastery founder": "Основатель обители",
    "Wonderworker": "Чудотворец",
    "Ruler or royal": "Правитель или царского рода",
    "Desert ascetic": "Пустынник",
    "Enlightener": "Просветитель",
    "New martyr": "Новомученик",
    "Healing intercessor": "Целитель",
    "Stylite": "Столпник",
    "Hymnographer": "Песнописец",
    "Church Father": "Отец Церкви",
    "Iconographer": "Иконописец",
    "Myrrh-bearer": "Мироносица",
    "Myrrh-streaming": "Мироточивый",
    "Warrior saint": "Воин",
    "Incorrupt relics": "Нетленные мощи",
})

# The estate a saint lived in.
TEXT.update({
    "Apostolic": "Апостольское",
    "Clergy": "Духовенство",
    "Laity": "Миряне",
    "Layman": "Мирянин",
    "Laywoman": "Мирянка",
    "Laywomen": "Мирянки",
    "Married": "В браке",
    "Military": "Воинство",
    "Royal": "Царское",
    "Royalty": "Царский род",
    "Unknown": "Неизвестно",
    "Unmarried": "Безбрачие",
    "Widowed": "Вдовство",
})

# The rank of the service, as the Typikon reckons it.
TEXT.update({
    "Doxology": "Славословный",
    "Great Feast": "Великий праздник",
    "Polyeleos": "Полиелейный",
    "Simple": "Простой",
    "Vigil": "Бденный",
})

TEXT.update({
    "Age of the Celtic Saints": "Век кельтских святых",
    "Age of the Ecumenical Councils": "Век Вселенских Соборов",
    "Age of the Martyrs": "Век мучеников",
    "Apostolic Age": "Апостольский век",
    "Byzantine": "Византия",
    "Byzantine Balkans": "Византийские Балканы",
    "Byzantine Era": "Византийская эпоха",
    "Byzantine Iconoclasm": "Византийское иконоборчество",
    "Cossack Era": "Казачья эпоха",
    "Desert Fathers": "Отцы пустыни",
    "Early Medieval West": "Раннесредневековый Запад",
    "Imperial Russia": "Императорская Россия",
    "Kievan Rus'": "Киевская Русь",
    "Medieval Georgia": "Средневековая Грузия",
    "Medieval Rus'": "Средневековая Русь",
    "Medieval Serbia": "Средневековая Сербия",
    "Modern": "Новое время",
    "Modern Era": "Новейшая эпоха",
    "Muscovite Russia": "Московская Русь",
    "Old Testament": "Ветхий Завет",
    "Ottoman Balkans": "Османские Балканы",
    "Ottoman Era": "Османская эпоха",
    "Ottoman period": "Османский период",
    "Polish-Lithuanian period": "Польско-литовский период",
    "Soviet Era": "Советская эпоха",
    "Soviet period": "Советский период",
    "Synodal Russia": "Синодальная Россия",
})

# Lands and regions.
TEXT.update({
    "Aegean": "Эгейские острова",
    "Albania": "Албания",
    "America": "Америка",
    "Arabia": "Аравия",
    "Armenia": "Армения",
    "Asia Minor": "Малая Азия",
    "Balkans": "Балканы",
    "Belarus": "Белоруссия",
    "Bithynia": "Вифиния",
    "Bohemia": "Богемия",
    "Britain": "Британия",
    "British Isles": "Британские острова",
    "Bulgaria": "Болгария",
    "Cappadocia": "Каппадокия",
    "China": "Китай",
    "Cilicia": "Киликия",
    "Constantinople": "Константинополь",
    "Crimea": "Крым",
    "Cyprus": "Кипр",
    "Czech Lands": "Чешские земли",
    "Dalmatia": "Далмация",
    "Danube lands": "Подунавье",
    "Egypt": "Египет",
    "England": "Англия",
    "Ethiopia": "Эфиопия",
    "France": "Франция",
    "Gaul": "Галлия",
    "Georgia": "Грузия",
    "Greece": "Греция",
    "Holy Land": "Святая Земля",
    "Illyria": "Иллирия",
    "Illyricum": "Иллирик",
    "India": "Индия",
    "Ireland": "Ирландия",
    "Italy": "Италия",
    "Judah": "Иудея",
    "Lithuania": "Литва",
    "Macedonia": "Македония",
    "Mesopotamia": "Месопотамия",
    "Moesia": "Мёзия",
    "Moldavia": "Молдавия",
    "Montenegro": "Черногория",
    "Moravia": "Моравия",
    "Mount Athos": "Афон",
    "North Africa": "Северная Африка",
    "North America": "Северная Америка",
    "North Macedonia": "Северная Македония",
    "Palestine": "Палестина",
    "Persia": "Персия",
    "Phoenicia": "Финикия",
    "Poland": "Польша",
    "Pontus": "Понт",
    "Romania": "Румыния",
    "Rome": "Рим",
    "Russia": "Россия",
    "Scythia": "Скифия",
    "Serbia": "Сербия",
    "Siberia": "Сибирь",
    "Sicily": "Сицилия",
    "Sinai": "Синай",
    "Spain": "Испания",
    "Syria": "Сирия",
    "Thrace": "Фракия",
    "Ukraine": "Украина",
    "United States": "Соединённые Штаты",
    "Western Rus": "Западная Русь",
})

TEXT.update({
    "Sunday of the Holy Forefathers": "Неделя святых праотец",
})


# Places are compounds - a town, then the land it stood in - and the lands
# repeat, so the parts are rendered once and the wholes assembled from them.
# Church forms where the Church has one: Ефес, not Эфес; Медиолан, not Милан;
# Фессалоника for the city St Paul wrote to. Transliteration elsewhere.
PARTS = {
    "Adrianople": "Адрианополь",
    "Adrianopolis": "Адрианополь",
    "Aegae": "Эги",
    "Aegean": "Эгейские острова",
    "Aegina": "Эгина",
    "Aetolia": "Этолия",
    "Agrigentum": "Агригент",
    "Akhaltsikhe": "Ахалцихе",
    "Aksum": "Аксум",
    "Alaska": "Аляска",
    "Albanopolis": "Албанополь",
    "Aleppo": "Алеппо",
    "Alexandria": "Александрия",
    "All America": "Вся Америка",
    "Amasea": "Амасия",
    "Amastris": "Амастрида",
    "Amathus": "Амафунт",
    "America": "Америка",
    "Amisos": "Амис",
    "Amisus": "Амис",
    "Amorion": "Аморий",
    "Anaplus": "Анапл",
    "Anazarbus": "Аназарв",
    "Ancyra": "Анкира",
    "Andronikov Monastery": "Андроников монастырь",
    "Annesi": "Анниси",
    "Annisa": "Анниса",
    "Antinoe": "Антиноя",
    "Antioch": "Антиохия",
    "Antioch in Pisidia": "Антиохия Писидийская",
    "Antioch of Pisidia": "Антиохия Писидийская",
    "Anzersk Island": "Анзерский остров",
    "Apamea": "Апамея",
    "Aphrodisias": "Афродисиада",
    "Apollonia": "Аполлония",
    "Arabia": "Аравия",
    "Arabian Desert": "Аравийская пустыня",
    "Arbela": "Арбела",
    "Archangel Gabriel": "Архангел Гавриил",
    "Arethusa": "Аретуса",
    "Argos": "Аргос",
    "Arianzus": "Арианз",
    "Armagh": "Арма",
    "Armenia": "Армения",
    "Armenia Minor": "Малая Армения",
    "Artanuji": "Артануджи",
    "Ascalon": "Аскалон",
    "Asia Minor": "Малая Азия",
    "Asikha": "Асиха",
    "Athens": "Афины",
    "Atskuri": "Ацкури",
    "Atsquri": "Ацкури",
    "Attica": "Аттика",
    "Auleneia": "Авления",
    "Auxerre": "Осер",
    "Avnezh": "Авнеж",
    "Babylon": "Вавилон",
    "Balkans": "Балканы",
    "Barcelona": "Барселона",
    "Bari": "Бари",
    "Beauvais": "Бове",
    "Belarus": "Белоруссия",
    "Belev": "Белёв",
    "Belgorod": "Белгород",
    "Belgorod (Akkerman)": "Белгород (Аккерман)",
    "Belgrade": "Белград",
    "Belozersk": "Белозерск",
    "Belozersk lands": "Белозерские земли",
    "Belozersk lands and Mozhaisk": "Белозерские земли и Можайск",
    "Beocin Monastery": "Беочинский монастырь",
    "Beroea": "Берое",
    "Bethany": "Вифания",
    "Bethel": "Вефиль",
    "Bethlapeta": "Вифлапета",
    "Bethlehem": "Вифлеем",
    "Bethsaloe": "Вифсалое",
    "Bisericani Monastery": "Бисериканский монастырь",
    "Bithynia": "Вифиния",
    "Blachernae": "Влахерны",
    "Black Lake": "Чёрное озеро",
    "Black Sea coast": "Черноморское побережье",
    "Bodbe": "Бодбе",
    "Boeotia": "Беотия",
    "Bogolyubovo": "Боголюбово",
    "Bohemia": "Богемия",
    "Bolgar": "Болгар",
    "Borovichi": "Боровичи",
    "Borovsk": "Боровск",
    "Bostra": "Востра",
    "Braunton": "Браунтон",
    "Brest": "Брест",
    "Briansk": "Брянск",
    "Britain": "Британия",
    "British Isles": "Британские острова",
    "Brooklyn": "Бруклин",
    "Bryansk": "Брянск",
    "Bucharest": "Бухарест",
    "Bulgaria": "Болгария",
    "Butovo": "Бутово",
    "Buzau Mountains": "Бузэуские горы",
    "Byblos": "Библ",
    "Byzantium": "Византий",
    "Byzantium (Constantinople)": "Византий (Константинополь)",
    "Caesarea": "Кесария",
    "Caesarea Maritima": "Кесария Приморская",
    "California": "Калифорния",
    "Campania": "Кампания",
    "Cana of Galilee": "Кана Галилейская",
    "Canopus": "Каноп",
    "Cappadocia": "Каппадокия",
    "Caria": "Кария",
    "Carthage": "Карфаген",
    "Catania": "Катания",
    "Cephalonia": "Кефалония",
    "Cernica Monastery": "Черникский монастырь",
    "Chalcedon": "Халкидон",
    "Chalcis": "Халкида",
    "Chalcis desert": "Халкидская пустыня",
    "Chelma Hill": "Челмская гора",
    "Chernihiv": "Чернигов",
    "Cherson": "Херсон",
    "Chersonesus": "Херсонес",
    "Chios": "Хиос",
    "Chonae": "Хоны",
    "Choziba": "Хозива",
    "Cilicia": "Киликия",
    "Claudiopolis": "Клавдиополь",
    "Colophon": "Колофон",
    "Colossae": "Колоссы",
    "Comana": "Команы",
    "Constantia": "Констанция",
    "Constantinople": "Константинополь",
    "Cordoba": "Кордова",
    "Corinth": "Коринф",
    "Cotyaeum": "Котиэй",
    "Crete": "Крит",
    "Crimea": "Крым",
    "Cucomo": "Кукомо",
    "Cucusus": "Кукуз",
    "Cyprus": "Кипр",
    "Cyrene": "Кирена",
    "Cyrenia": "Кирения",
    "Cyrrhus": "Кир",
    "Cyzicus": "Кизик",
    "Dabuda": "Дабуда",
    "Dalmatia": "Далмация",
    "Dalmatian Monastery": "Далматский монастырь",
    "Damascus": "Дамаск",
    "David Gareji": "Давид-Гареджи",
    "Davit-Gareji": "Давид-Гареджи",
    "Decapolis": "Декаполь",
    "Desert beyond the Jordan": "Пустыня за Иорданом",
    "Devich": "Девич",
    "Devon": "Девон",
    "Dioclea (Duklja)": "Диоклея (Дукля)",
    "Dorostolum (Silistra)": "Доростол (Силистра)",
    "Drenica": "Дреница",
    "Durostorum": "Доростол",
    "Dymsk": "Дымск",
    "Dymskoe Lake": "Дымское озеро",
    "East Anglia": "Восточная Англия",
    "Edessa": "Эдесса",
    "Edra": "Эдра",
    "Egypt": "Египет",
    "Egyptian Desert": "Египетская пустыня",
    "Eleutheropolis": "Елевферополь",
    "Elkosh": "Элкош",
    "Emesa": "Эмеса",
    "England": "Англия",
    "Ephesus": "Ефес",
    "Epirus": "Эпир",
    "Essex": "Эссекс",
    "Ethiopia": "Эфиопия",
    "Euchaita": "Евхаиты",
    "Euroea": "Эвроя",
    "Ferapontov": "Ферапонтов",
    "Ferapontov Monastery": "Ферапонтов монастырь",
    "Feremane": "Феремане",
    "Ferentino": "Ферентино",
    "Formia": "Формия",
    "Galatia": "Галатия",
    "Galich": "Галич",
    "Galilee": "Галилея",
    "Gangra": "Гангра",
    "Gath-hepher": "Гафхефер",
    "Gaul": "Галлия",
    "Gaza": "Газа",
    "Gdov": "Гдов",
    "Gdov lands": "Гдовские земли",
    "George Hill": "Георгиева гора",
    "Georgia": "Грузия",
    "Gibeah of Phinehas": "Гива Финеесова",
    "Gilead": "Галаад",
    "Glendalough": "Глендалох",
    "Glushitsa": "Глушица",
    "Gortyna": "Гортина",
    "Gothia": "Готия",
    "Great Lavra": "Великая Лавра",
    "Great Lavra of Saint Sabbas": "Великая Лавра преподобного Саввы",
    "Great Moravia": "Великая Моравия",
    "Greece": "Греция",
    "Hartland": "Хартленд",
    "Hauran": "Хауран",
    "Hebron": "Хеврон",
    "Heliopolis": "Илиополь",
    "Hellas": "Эллада",
    "Hellespont": "Геллеспонт",
    "Heraclea": "Ираклия",
    "Hereti": "Эрети",
    "Hermopolis": "Ермополь",
    "Hierapolis": "Иераполь",
    "Hilandar": "Хиландар",
    "Holy Land": "Святая Земля",
    "Holy Trinity-Saint Sergius Lavra": "Свято-Троицкая Сергиева Лавра",
    "Hypaepa": "Ипепа",
    "Iași": "Яссы",
    "Iconium": "Иконий",
    "Iken": "Айкен",
    "Illinois": "Иллинойс",
    "Illyria": "Иллирия",
    "Illyricum": "Иллирик",
    "India": "Индия",
    "Irap": "Ирап",
    "Ireland": "Ирландия",
    "Irkutsk": "Иркутск",
    "Isauria": "Исаврия",
    "Israel": "Израиль",
    "Italy": "Италия",
    "Iza": "Иза",
    "Jerusalem": "Иерусалим",
    "Joppa": "Иоппия",
    "Jordan River": "река Иордан",
    "Judea": "Иудея",
    "Judean Desert": "Иудейская пустыня",
    "Judean Wilderness": "Иудейская пустыня",
    "Kaluga": "Калуга",
    "Kaluga lands": "Калужские земли",
    "Kalyazin": "Калязин",
    "Kaniv": "Канев",
    "Karelia": "Карелия",
    "Kargopol lands": "Каргопольские земли",
    "Kartli": "Картли",
    "Kartli (Iberia)": "Картли (Иверия)",
    "Kashin": "Кашин",
    "Kasperovo": "Касперово",
    "Kavsokalyvia": "Кавсокаливия",
    "Kazan": "Казань",
    "Kellia": "Келлии",
    "Keno Lake": "Кенозеро",
    "Kerkyra (Corfu)": "Керкира (Корфу)",
    "Khakhuli": "Хахули",
    "Khakhuli Monastery": "Хахульский монастырь",
    "Kharkiv": "Харьков",
    "Kherson lands": "Херсонские земли",
    "Khlynov": "Хлынов",
    "Kholm": "Холм",
    "Khutyn": "Хутынь",
    "Kios": "Кий",
    "Klops Monastery": "Клопский монастырь",
    "Kola": "Кола",
    "Komel": "Комель",
    "Komel Forest": "Комельский лес",
    "Konevets": "Коневец",
    "Korets": "Корец",
    "Kosinsk": "Косинское",
    "Kosovo": "Косово",
    "Kostroma lands": "Костромские земли",
    "Kozelshchyna": "Козельщина",
    "Kozhe Lake": "Кожеозеро",
    "Krasny Kholm": "Красный Холм",
    "Kronstadt": "Кронштадт",
    "Krushedol": "Крушедол",
    "Kubensk": "Кубенское",
    "Kursk": "Курск",
    "Kushta": "Кушта",
    "Kvabtakhevi Monastery": "Квабтахевский монастырь",
    "Kveli fortress": "крепость Квели",
    "Kwethluk": "Кветлук",
    "Kyiv": "Киев",
    "Kyiv Caves": "Киевские пещеры",
    "Kyiv Caves Lavra": "Киево-Печерская Лавра",
    "Kyiv Far Caves": "Киевские Дальние пещеры",
    "Kyiv Near Caves": "Киевские Ближние пещеры",
    "Laconia": "Лакония",
    "Lake Iliamna": "озеро Илиамна",
    "Lake Ilmen": "озеро Ильмень",
    "Lake Ilo": "Илоозеро",
    "Lake Ladoga": "Ладожское озеро",
    "Lake Onega": "Онежское озеро",
    "Lake Pskov": "Псковское озеро",
    "Lake Seliger": "озеро Селигер",
    "Lake Vorbozomsk": "Ворбозомское озеро",
    "Lampsacus": "Лампсак",
    "Land of Uz": "земля Уц",
    "Langres": "Лангр",
    "Laodicea": "Лаодикия",
    "Lavra of Saint Sabbas": "Лавра преподобного Саввы",
    "Lazica": "Лазика",
    "Le Mans": "Ле-Ман",
    "Lentini": "Лентини",
    "Leokhnovo": "Леохново",
    "Leontini": "Леонтины",
    "Lesbos": "Лесбос",
    "Leucosia (Nicosia)": "Левкосия (Никосия)",
    "Lezna River": "река Лезна",
    "Libertyville": "Либертивилль",
    "Libya": "Ливия",
    "Lindisfarne": "Линдисфарн",
    "Lipari": "Липари",
    "Lithuania": "Литва",
    "Loma": "Лома",
    "Lubny": "Лубны",
    "Lubyatov": "Любятово",
    "Lucania": "Лукания",
    "Lukhov": "Лухов",
    "Lycaonia": "Ликаония",
    "Lycia": "Ликия",
    "Lycopolis": "Ликополь",
    "Lydda": "Лидда",
    "Lydia": "Лидия",
    "Lyons": "Лион",
    "Lérins": "Лерин",
    "Macedonia": "Македония",
    "Magnesia": "Магнесия",
    "Maiuma": "Маиума",
    "Makhrishche": "Махрище",
    "Malopinega": "Малопинежье",
    "Mantinea": "Мантинея",
    "Mar Saba": "Мар-Саба",
    "Marseilles": "Марсель",
    "Martyropolis": "Мартирополь",
    "Mauretania": "Мавритания",
    "Medikion Monastery": "Мидикийский монастырь",
    "Melitene": "Мелитина",
    "Menuthis": "Менуфис",
    "Menyusha": "Менюша",
    "Merkushino": "Меркушино",
    "Mesopotamia": "Месопотамия",
    "Mezen": "Мезень",
    "Milan": "Медиолан",
    "Moesia": "Мёзия",
    "Moldavia": "Молдавия",
    "Monte Cassino": "Монтекассино",
    "Montenegro": "Черногория",
    "Monza River": "река Монза",
    "Moravia": "Моравия",
    "Morea (Peloponnese)": "Морея (Пелопоннес)",
    "Moresheth": "Морасфа",
    "Moscow": "Москва",
    "Mount Athos": "Афон",
    "Mount Colzim": "гора Колзим",
    "Mount Ephraim": "гора Ефремова",
    "Mount Galesion": "гора Галисий",
    "Mount Galesius": "гора Галисий",
    "Mount Hor": "гора Ор",
    "Mount Kyminas": "гора Кимин",
    "Mount Maleon": "гора Малеон",
    "Mount Myrsinon": "гора Мирсинон",
    "Mount Nebo": "гора Нево",
    "Mount Olympus": "гора Олимп",
    "Mount Sagmata": "гора Сагмата",
    "Mount Sinai": "гора Синай",
    "Mount Skopa": "гора Скопа",
    "Mount Taurus": "Таврские горы",
    "Mount of Olives": "Елеонская гора",
    "Murom": "Муром",
    "Murom Island": "Муромский остров",
    "Mylapore": "Милапур",
    "Mylasa": "Миласа",
    "Myra": "Миры",
    "Myra in Lycia": "Миры Ликийские",
    "Mytilene": "Митилина",
    "Najran": "Наджран",
    "Naples": "Неаполь",
    "Nazareth": "Назарет",
    "Nea Makri": "Неа-Макри",
    "Neamts Monastery": "Нямецкий монастырь",
    "Neamț": "Нямц",
    "Near Constantinople": "Близ Константинополя",
    "Neocaesarea": "Неокесария",
    "New Lake": "Новоозеро",
    "New York": "Нью-Йорк",
    "Nicaea": "Никея",
    "Nicea": "Никея",
    "Nicomedia": "Никомидия",
    "Nicopolis": "Никополь",
    "Nisibis": "Низибия",
    "Nitria": "Нитрия",
    "North Africa": "Северная Африка",
    "North America": "Северная Америка",
    "Novara": "Новара",
    "Novgorod": "Новгород",
    "Novgorod lands": "Новгородские земли",
    "Noviodunum": "Новиодун",
    "Novoezersk": "Новоезерск",
    "Nurma": "Нурма",
    "Nursia": "Нурсия",
    "Nyssa": "Нисса",
    "Obnora River": "река Обнора",
    "Odrino": "Одрино",
    "Ohrid": "Охрид",
    "Old Lavra of Chariton": "Древняя Лавра преподобного Харитона",
    "Olonets lands": "Олонецкие земли",
    "Omala": "Омала",
    "Ondrusov": "Ондрусов",
    "Ophrah": "Офра",
    "Orel lands": "Орловские земли",
    "Oshevensk": "Ошевенск",
    "Osrhoene": "Осроэна",
    "Ostia": "Остия",
    "Ostracine": "Острацина",
    "Ostrog": "Острог",
    "Ozovia": "Озовия",
    "Palestine": "Палестина",
    "Palii Island": "Палий остров",
    "Pamphylia": "Памфилия",
    "Pannonia": "Паннония",
    "Paphlagonia": "Пафлагония",
    "Paphos": "Пафос",
    "Paramythia": "Парамифия",
    "Paris": "Париж",
    "Parium": "Парий",
    "Paros": "Парос",
    "Patras": "Патры",
    "Pec": "Печ",
    "Pechenga Monastery": "Печенгский монастырь",
    "Pelecete": "Пелекета",
    "Pelekete Monastery": "Пелекетский монастырь",
    "Peloponnese": "Пелопоннес",
    "Pelshma": "Пельшма",
    "Pelusium": "Пелусий",
    "Pennsylvania": "Пенсильвания",
    "Perekop (Perekomsky) Monastery": "Перекопский (Перекомский) монастырь",
    "Pereslavl-Zalessky": "Переславль-Залесский",
    "Pereyaslavl": "Переяславль",
    "Pereyaslavl-Zalessky": "Переславль-Залесский",
    "Pergamum": "Пергам",
    "Perge": "Пергия",
    "Peristerai": "Перистеры",
    "Perm": "Пермь",
    "Perm lands": "Пермские земли",
    "Persia": "Персия",
    "Peshnosha": "Пешноша",
    "Petrograd": "Петроград",
    "Peć": "Печ",
    "Pharan": "Фаран",
    "Philadelphia": "Филадельфия",
    "Philippopolis": "Филиппополь",
    "Philotheou Monastery": "Филофеевский монастырь",
    "Phoenicia": "Финикия",
    "Phrygia": "Фригия",
    "Pinega": "Пинега",
    "Pisidia": "Писидия",
    "Plousias": "Плусиада",
    "Pochaev": "Почаев",
    "Pochaiv": "Почаев",
    "Poiana Marului": "Пояна-Мэрулуй",
    "Poland": "Польша",
    "Polotsk": "Полоцк",
    "Poltava lands": "Полтавские земли",
    "Polybotum": "Полиботы",
    "Pompeiopolis": "Помпейополь",
    "Pontus": "Понт",
    "Porkhov": "Порхов",
    "Poshekhonye": "Пошехонье",
    "Pozzuoli": "Поццуоли",
    "Prague": "Прага",
    "Priluki": "Прилуки",
    "Prokopion": "Прокопион",
    "Protection Convent": "Покровский монастырь",
    "Prusa": "Пруса",
    "Prymnessus": "Примнесс",
    "Pshinja": "Пшиня",
    "Pskov": "Псков",
    "Pskov Caves Monastery": "Псково-Печерский монастырь",
    "Ptolemais": "Птолемаида",
    "Puteoli": "Путеолы",
    "Putna": "Путна",
    "Pythias": "Пифия",
    "Périgueux": "Перигё",
    "Radonezh": "Радонеж",
    "Ramah": "Рама",
    "Ravenna": "Равенна",
    "Resafa": "Ресафа",
    "Rhosus": "Росс",
    "Rila": "Рила",
    "Robeika": "Робейка",
    "Robeika River": "река Робейка",
    "Romania": "Румыния",
    "Rome": "Рим",
    "Rome and the East": "Рим и Восток",
    "Rossos": "Росс",
    "Rostov": "Ростов",
    "Rus'": "Русь",
    "Russia": "Россия",
    "Russian North": "Русский Север",
    "Ryazan": "Рязань",
    "Rzhev": "Ржев",
    "Saint Petersburg": "Санкт-Петербург",
    "Salamis": "Саламин",
    "Salamis (Constantia)": "Саламин (Констанция)",
    "Salona": "Салона",
    "Samaria": "Самария",
    "Samosata": "Самосаты",
    "Samothrace": "Самофракия",
    "Samtskhe": "Самцхе",
    "San Francisco": "Сан-Франциско",
    "Sardis": "Сарды",
    "Sarov": "Саров",
    "Scetis": "Скит",
    "Scythia": "Скифия",
    "Scythia Minor": "Малая Скифия",
    "Sebaste": "Севастия",
    "Seleucia": "Селевкия",
    "Seleucia-Ctesiphon": "Селевкия-Ктесифон",
    "Serbia": "Сербия",
    "Sergiev Posad": "Сергиев Посад",
    "Serpukhov": "Серпухов",
    "Serres": "Серры",
    "Shenkursk": "Шенкурск",
    "Shiloh": "Силом",
    "Shio-Mgvime Monastery": "Шиомгвимский монастырь",
    "Shuya": "Шуя",
    "Shuzhgora": "Шужгора",
    "Siberia": "Сибирь",
    "Siblag camps": "Сиблаг",
    "Sicily": "Сицилия",
    "Side": "Сида",
    "Simferopol": "Симферополь",
    "Sinai and Raithu": "Синай и Раифа",
    "Sinai wilderness": "Синайская пустыня",
    "Sinope": "Синоп",
    "Sinope and Amasea": "Синоп и Амасия",
    "Sinozersk": "Синозерск",
    "Sirmium": "Сирмий",
    "Sitka": "Ситка",
    "Siya Monastery": "Сийский монастырь",
    "Skepsis": "Скепсия",
    "Sketis": "Скит",
    "Smolensk": "Смоленск",
    "Smyrna": "Смирна",
    "Snetogorsk Monastery": "Снетогорский монастырь",
    "Sofia": "София",
    "Sokhot River": "река Сохоть",
    "Solovki": "Соловки",
    "Solovki Islands": "Соловецкие острова",
    "Solovki Monastery": "Соловецкий монастырь",
    "Sora River": "река Сора",
    "Soreoi": "Сореи",
    "Spain": "Испания",
    "Spoleto": "Сполето",
    "Spruce Island": "Еловый остров",
    "St. Petersburg": "Санкт-Петербург",
    "Steirion": "Стирий",
    "Stolobny Island": "остров Столобный",
    "Storozhi Hill": "гора Сторожи",
    "Strobil": "Стровил",
    "Strumica": "Струмица",
    "Susa": "Сузы",
    "Suzdal": "Суздаль",
    "Svensky Monastery": "Свенский монастырь",
    "Svir": "Свирь",
    "Sviyazhsk": "Свияжск",
    "Syandemsk": "Сяндемск",
    "Syanzhema": "Сянжема",
    "Syanzhema River": "река Сянжема",
    "Sykeon": "Сикеон",
    "Symbola": "Символы",
    "Symbola Monastery": "монастырь Символов",
    "Synnada": "Синнады",
    "Syracuse": "Сиракузы",
    "Syria": "Сирия",
    "Tabenna": "Тавенна",
    "Tabennisi": "Тавенниси",
    "Tambov": "Тамбов",
    "Tao": "Тао",
    "Taormina": "Таормина",
    "Taphanes": "Тафнис",
    "Targala": "Таргала",
    "Tarnovo": "Тырново",
    "Tarsus": "Тарс",
    "Tazlău Monastery": "Тазлэуский монастырь",
    "Tbilisi": "Тбилиси",
    "Tenedos": "Тенедос",
    "Tennis": "Теннис",
    "Teratyn": "Тератин",
    "Terracina": "Террачина",
    "The East": "Восток",
    "The Jordan": "Иордан",
    "Thebaid": "Фиваида",
    "Thebes": "Фивы",
    "Thessalonica": "Фессалоника",
    "Thessaloniki": "Фессалоники",
    "Thessaly": "Фессалия",
    "Thrace": "Фракия",
    "Tiksna": "Тиксна",
    "Tobolsk": "Тобольск",
    "Tolva": "Толва",
    "Torzhok": "Торжок",
    "Totma": "Тотьма",
    "Trajanopolis": "Траянополь",
    "Tralles": "Траллы",
    "Transcarpathia": "Закарпатье",
    "Trebia": "Требия",
    "Trebizond": "Трапезунд",
    "Tremithus": "Тримифунт",
    "Triglia": "Триглия",
    "Trinity Lavra": "Троицкая Лавра",
    "Trinity-Sergius Lavra": "Троице-Сергиева Лавра",
    "Tripoli": "Триполи",
    "Tsarskoye Selo": "Царское Село",
    "Turov": "Туров",
    "Tver": "Тверь",
    "Tver lands": "Тверские земли",
    "Tyana": "Тиана",
    "Tyre": "Тир",
    "Uchma": "Учма",
    "Uglich": "Углич",
    "Ukraine": "Украина",
    "United States": "Соединённые Штаты",
    "Unzha": "Унжа",
    "Ushchelye": "Ущелье",
    "Ust-Vym": "Усть-Вымь",
    "Vaga lands": "Важские земли",
    "Vagharshapat": "Вагаршапат",
    "Valaam": "Валаам",
    "Valencia": "Валенсия",
    "Velehrad": "Велеград",
    "Veliky Ustiug": "Великий Устюг",
    "Veliky Ustyug": "Великий Устюг",
    "Verkhoturye": "Верхотурье",
    "Verkola": "Веркола",
    "Verona": "Верона",
    "Verulamium (St Albans)": "Веруламий (Сент-Олбанс)",
    "Vetluga": "Ветлуга",
    "Vilnius": "Вильнюс",
    "Vishera": "Вишера",
    "Vladimir": "Владимир",
    "Vladimir lands": "Владимирские земли",
    "Vladimir-in-Volhynia": "Владимир-Волынский",
    "Volga Bulgaria": "Волжская Булгария",
    "Volhynia": "Волынь",
    "Volissos": "Волиссос",
    "Volodymyr-Volhynia": "Владимир-Волынский",
    "Vologda": "Вологда",
    "Vologda lands": "Вологодские земли",
    "Volokolamsk": "Волоколамск",
    "Vorbozomsk Lake": "Ворбозомское озеро",
    "Voronezh": "Воронеж",
    "Vracar": "Врачар",
    "Vyatka": "Вятка",
    "Vyazma": "Вязьма",
    "Vyritsa": "Вырица",
    "Vyshgorod": "Вышгород",
    "Vyshhorod": "Вышгород",
    "White Lake (Beloozero)": "Белое озеро (Белоозеро)",
    "White Sea": "Белое море",
    "Wilkes-Barre": "Уилкс-Барре",
    "Wonderful Mountain": "Дивная гора",
    "Yakhroma": "Яхрома",
    "Yarenga": "Яренга",
    "Yaroslavl": "Ярославль",
    "Yaroslavl lands": "Ярославские земли",
    "Yashezero": "Яшезеро",
    "Yekaterinburg": "Екатеринбург",
    "Yuriev Monastery": "Юрьев монастырь",
    "Yuryegorsk": "Юрьегорск",
    "Zadonsk": "Задонск",
    "Zahumlje (Zakholm)": "Захумье (Захолмье)",
    "Zakynthos": "Закинф",
    "Zelenets": "Зеленец",
    "Zeugma": "Зевгма",
    "Zhabyn Monastery": "Жабынский монастырь",
    "Zheleznoborov": "Железноборовский",
    "Zhicha": "Жича",
    "Zhicha Monastery": "Жичский монастырь",
    "Zvenigorod": "Звенигород",
    "Zverki": "Зверки",
    "beyond the Danube": "за Дунаем",
    "near Alexandria": "близ Александрии",
    "near Antioch": "близ Антиохии",
    "near Bialystok": "близ Белостока",
    "near Cherepovets": "близ Череповца",
    "near Constantinople": "близ Константинополя",
    "near Cyrrhus": "близ Кира",
    "near Dorostolum": "близ Доростола",
    "near Edessa": "близ Эдессы",
    "near Ephesus": "близ Ефеса",
    "near Galich": "близ Галича",
    "near Kargopol": "близ Каргополя",
    "near Moscow": "близ Москвы",
    "near Mount Tabor": "близ горы Фавор",
    "near Mtskheta": "близ Мцхеты",
    "near Novgorod": "близ Новгорода",
    "near Prusa": "близ Прусы",
    "near Pskov": "близ Пскова",
    "near Staraya Russa": "близ Старой Руссы",
    "near Uglich": "близ Углича",
    "near Verkhoturye": "близ Верхотурья",
    "near Vladimir": "близ Владимира",
    "near the Dvina": "близ Двины",
    "the Black Sea coast and the Caucasus": "Черноморское побережье и Кавказ",
    "the desert of Egypt": "пустыня Египта",
    "the wilderness beyond Mesopotamia": "пустыня за Месопотамией",
}

PARTS.update({
    "Abel-meholah": "Авел-Мехола",
    "Abkhazeti": "Абхазети",
    "Achaia": "Ахаия",
    "Adamovka": "Адамовка",
    "Africa": "Африка",
    "Amasia": "Амасия",
    "Amastridea": "Амастрида",
    "Amida": "Амида",
    "Amnia": "Амния",
    "Amphipolis": "Амфиполь",
    "Anastasiopolis": "Анастасиополь",
    "Anathoth": "Анафоф",
    "Anatolia": "Анатолия",
    "Anga": "Анга",
    "Anzersk": "Анзерский",
    "Apulia": "Апулия",
    "Aquileia": "Аквилея",
    "Arauraka": "Араурака",
    "Arkhangelsk": "Архангельск",
    "Arkhangelsk lands": "Архангельские земли",
    "Arsinoe": "Арсиноя",
    "Arta": "Арта",
    "Atka Island": "остров Атка",
    "Basarbov": "Басарбово",
    "Beirut": "Бейрут",
    "Benevento": "Беневент",
    "Berezan": "Березань",
    "Berezniko": "Березник",
    "Besanduc": "Весандук",
    "Bethsaida": "Вифсаида",
    "Bezhetsk lands": "Бежецкие земли",
    "Bialystok": "Белосток",
    "Bosnia": "Босния",
    "Boston": "Бостон",
    "Budimlje": "Будимля",
    "Byzantine Empire": "Византийская империя",
    "Caesarea in Cappadocia": "Кесария Каппадокийская",
    "Cana": "Кана",
    "Canaan": "Ханаан",
    "Capernaum": "Капернаум",
    "Carpathian Rus'": "Карпатская Русь",
    "Carpatho-Russia": "Карпатская Русь",
    "Cernica": "Черника",
    "Chelm": "Холм",
    "Cherepovets": "Череповец",
    "Chernigov": "Чернигов",
    "Chernigov lands": "Черниговские земли",
    "Chernihiv lands": "Черниговские земли",
    "Chicago": "Чикаго",
    "Chukhloma": "Чухлома",
    "Coma": "Кома",
    "Corfu": "Корфу",
    "Corsica": "Корсика",
    "Decapolis of Isauria": "Исаврийский Декаполь",
    "Demetsana": "Димицана",
    "Demitsana": "Димицана",
    "Dimitsana": "Димицана",
    "Dioclea": "Диоклея",
    "Disevi": "Дисеви",
    "Diveyevo": "Дивеево",
    "Dobrogea": "Добруджа",
    "Dorostolum": "Доростол",
    "Elbasan": "Эльбасан",
    "Epivato": "Эпиват",
    "Euboea": "Эвбея",
    "European Russia": "Европейская Россия",
    "Evia": "Эвбея",
    "Ferapontovo": "Ферапонтово",
    "Flavia Neapolis": "Флавия Неаполь",
    "Florishchi": "Флорищи",
    "Frasinei": "Фрэсиней",
    "Galata": "Галата",
    "Galicia": "Галиция",
    "Gareji": "Гареджи",
    "Gary": "Гэри",
    "Germany": "Германия",
    "Gori district": "Горийский уезд",
    "Gothic lands": "Готские земли",
    "Guria": "Гурия",
    "Herzegovina": "Герцеговина",
    "Hosios Loukas": "Осиос-Лукас",
    "Hungary": "Венгрия",
    "Indiana": "Индиана",
    "Ioannina": "Янина",
    "Irenopolis": "Иринополь",
    "Irkutsk province": "Иркутская губерния",
    "Jackson": "Джексон",
    "Judah": "Иудея",
    "Kallippi": "Каллиппи",
    "Kampsada": "Кампсада",
    "Kargopol": "Каргополь",
    "Kastoria": "Кастория",
    "Kastorion": "Касторион",
    "Kekhta": "Кехта",
    "Kerch": "Керчь",
    "Kerkyra": "Керкира",
    "Kherson": "Херсон",
    "Khust": "Хуст",
    "Klarjeti": "Кларджети",
    "Kodiak": "Кадьяк",
    "Kondakovo": "Кондаково",
    "Korissos": "Кориссос",
    "Kornet": "Корнет",
    "Korotsk": "Короцко",
    "Kostroma": "Кострома",
    "Kozelsk": "Козельск",
    "Kratovo": "Кратово",
    "Kremenets": "Кременец",
    "Kromna": "Кромна",
    "Kudinovo": "Кудиново",
    "Kyiv region": "Киевская земля",
    "Lake Kubenskoye": "Кубенское озеро",
    "Lake Orta": "озеро Орта",
    "Land of Asher": "земля Асирова",
    "Land of Zebulun": "земля Завулонова",
    "Land of the tribe of Simeon": "земля колена Симеонова",
    "Lebanon": "Ливан",
    "Leinster": "Ленстер",
    "Lelich": "Лелич",
    "Little Russia (Ukraine)": "Малороссия (Украина)",
    "Liubech": "Любеч",
    "Liubimograd": "Любимоград",
    "Loutraki": "Лутраки",
    "Lykaonia": "Ликаония",
    "Lystra": "Листра",
    "Magdala": "Магдала",
    "Magedon": "Магедон",
    "Magydos": "Магидос",
    "Makarovo": "Макарово",
    "Malta": "Мальта",
    "Mandera": "Мандера",
    "Mangup": "Мангуп",
    "Maratha": "Марафа",
    "Marathon": "Марафон",
    "Marcianopolis": "Марцианополь",
    "Marikat": "Марикат",
    "Medikion": "Мидикий",
    "Medin": "Медынь",
    "Mega Dendron": "Мега-Дендрон",
    "Meglin": "Меглин",
    "Melitopolis": "Мелитополь",
    "Mesteacăn": "Местякэн",
    "Methymna": "Мифимна",
    "Mgvime": "Мгвиме",
    "Mineo": "Минео",
    "Minneapolis": "Миннеаполис",
    "Mogarissos": "Могарисс",
    "Mogilev": "Могилёв",
    "Moldova": "Молдова",
    "Monembasia": "Монемвасия",
    "Monteluco": "Монтелуко",
    "Moscow lands": "Московские земли",
    "Mozhaisk": "Можайск",
    "Mrkonjici": "Мрконьичи",
    "Mtskheta": "Мцхета",
    "Mutalaska": "Муталаска",
    "Myrgorod": "Миргород",
    "Naissus": "Наисс",
    "Nalšia": "Нальшя",
    "Nanterre": "Нантер",
    "Nauplion": "Навплион",
    "Nazianzus": "Назианз",
    "Neapolis": "Неаполь",
    "Nerchinsk": "Нерчинск",
    "Nicosia": "Никосия",
    "Nikiforovskaya": "Никифоровская",
    "Nizhni-Novgorod": "Нижний Новгород",
    "Nizhny Novgorod": "Нижний Новгород",
    "Nizhny Novgorod lands": "Нижегородские земли",
    "Nizhyn": "Нежин",
    "North Macedonia": "Северная Македония",
    "Northumbria": "Нортумбрия",
    "Odessa": "Одесса",
    "Olonets": "Олонец",
    "Olshansk": "Ольшанск",
    "Olympus": "Олимп",
    "Opso": "Опсо",
    "Ovche Pole": "Овче-Поле",
    "Ovruch": "Овруч",
    "Palermo": "Палермо",
    "Parthia": "Парфия",
    "Patara": "Патара",
    "Patmos": "Патмос",
    "Pechenga": "Печенга",
    "Pekhorka": "Пехорка",
    "Pelekete": "Пелекета",
    "Pereslavl": "Переславль",
    "Persia and the East": "Персия и Восток",
    "Pharasa": "Фараса",
    "Phocis": "Фокида",
    "Pinsk": "Пинск",
    "Podolia": "Подолия",
    "Pokutia": "Покутье",
    "Poltava": "Полтава",
    "Poltava region": "Полтавская земля",
    "Pomorie": "Поморье",
    "Popovo": "Попово",
    "Pretorium": "Преторий",
    "Pryluky": "Прилуки",
    "Ptinapor": "Птинапор",
    "Radonezh and Serpukhov": "Радонеж и Серпухов",
    "Radoviste": "Радовиште",
    "Raithu": "Раифа",
    "Ramathaim": "Рамафаим",
    "Ramathaim-Zophim": "Рамафаим-Цофим",
    "Ramnic": "Рымник",
    "Ravanica": "Раваница",
    "Rethymnon": "Ретимнон",
    "Roman Britain": "Римская Британия",
    "Rome and Milan": "Рим и Медиолан",
    "Rostov lands": "Ростовские земли",
    "Russian nobility": "русское дворянство",
    "Ryazan province": "Рязанская губерния",
    "Saint John": "Святой Иоанн",
    "Samegrelo": "Самегрело",
    "Saragossa": "Сарагоса",
    "Scotland": "Шотландия",
    "Sebastea": "Севастия",
    "Sebino": "Себино",
    "Selymbria": "Селимврия",
    "Shanghai": "Шанхай",
    "Shovskoe": "Шовское",
    "Sigriane": "Сигриана",
    "Silistra": "Силистра",
    "Singidunum": "Сингидун",
    "Sisan": "Сисан",
    "Skrino": "Скрино",
    "Slutsk": "Слуцк",
    "Snetogorsk": "Снетогорский",
    "Sophene": "Софена",
    "Srem": "Срем",
    "St Albans": "Сент-Олбанс",
    "Stara Zagora": "Стара-Загора",
    "Staritsa": "Старица",
    "Starytsa": "Старица",
    "Studenica": "Студеница",
    "Subiaco": "Субиако",
    "Suceava": "Сучава",
    "Sura": "Сура",
    "Sweden": "Швеция",
    "Syandeba": "Сяндеба",
    "Tabatha": "Тавафа",
    "Tao-Klarjeti": "Тао-Кларджети",
    "Tarsus and Achaia": "Тарс и Ахаия",
    "Tarsus and Rossos": "Тарс и Росс",
    "Tarsus and the East": "Тарс и Восток",
    "Tashkent": "Ташкент",
    "Tauresium": "Тавресий",
    "Tazlău": "Тазлэу",
    "Tekoa": "Фекоя",
    "Thebes of Egypt": "Фивы Египетские",
    "Thyateira": "Фиатира",
    "Tikhvin": "Тихвин",
    "Tishbe of Gilead": "Фесва Галаадская",
    "Tmutarakan": "Тмутаракань",
    "Toropets": "Торопец",
    "Trier": "Трир",
    "Trikala": "Трикала",
    "Troas": "Троада",
    "Tula lands": "Тульские земли",
    "Turchasovo": "Турчасово",
    "Tuscany": "Тоскана",
    "Upper Thebaid": "Верхняя Фиваида",
    "Ur of the Chaldees": "Ур Халдейский",
    "Ust-Totma": "Усть-Тотьма",
    "Ustiug": "Устюг",
    "Ustyug": "Устюг",
    "Vaga": "Вага",
    "Varnitsa": "Варницы",
    "Varzuga": "Варзуга",
    "Vasilevo": "Василево",
    "Vaste": "Васте",
    "Vasyliv": "Василев",
    "Vazheozero region": "Важеозерский край",
    "Veliki Luki": "Великие Луки",
    "Venice": "Венеция",
    "Verulamium": "Веруламий",
    "Videlebye": "Виделебье",
    "Vladimir-Suzdal": "Владимиро-Суздальская земля",
    "Wales": "Уэльс",
    "Warsaw": "Варшава",
    "White Lake": "Белое озеро",
    "White Lake region": "Белозерский край",
    "Yaroslavl province": "Ярославская губерния",
    "Yazvishche": "Язвище",
    "Yuriev (Tartu)": "Юрьев (Тарту)",
    "Yuriev-Polsky": "Юрьев-Польский",
    "Zahumlje": "Захумье",
    "Zaozersk": "Заозерск",
    "Zemplin region": "Земплинский край",
    "Zeta": "Зета",
    "all Greece": "вся Греция",
    "all Rus'": "вся Русь",
    "all Russia": "вся Россия",
    "all Slavic lands": "все славянские земли",
    "all schools": "все училища",
    "all the Slavic lands": "все славянские земли",
    "gardens and vineyards": "сады и виноградники",
    "near Agrigentum": "близ Агригента",
    "near Ancyra": "близ Анкиры",
    "near Apamea": "близ Апамеи",
    "near Borovsk": "близ Боровска",
    "near Chernigov": "близ Чернигова",
    "near Gaza": "близ Газы",
    "near Kiev": "близ Киева",
    "near Kyiv": "близ Киева",
    "near Rostov": "близ Ростова",
    "near Samosata": "близ Самосат",
    "near Totma": "близ Тотьмы",
    "near Volokolamsk": "близ Волоколамска",
    "on the Dvina": "на Двине",
    "on the Onega": "на Онеге",
    "the Balkans": "Балканы",
    "the Belozersk country": "Белозерский край",
    "the Bistrița valley": "долина Бистрицы",
    "the Buzau Mountains": "Бузэуские горы",
    "the Caucasus": "Кавказ",
    "the Cells": "Келлии",
    "the Cherepovets country": "Череповецкий край",
    "the Danube lands": "Подунавье",
    "the Dvina country": "Подвинье",
    "the East": "Восток",
    "the Egyptian desert": "Египетская пустыня",
    "the Gentile nations": "языческие народы",
    "the Golden Horde": "Золотая Орда",
    "the Holy Land": "Святая Земля",
    "the Jordan": "Иордан",
    "the Jordan desert": "Иорданская пустыня",
    "the Judean desert": "Иудейская пустыня",
    "the Judean wilderness": "Иудейская пустыня",
    "the Kola north": "Кольский север",
    "the Komi lands": "земли Коми",
    "the Mount of Olives": "Елеонская гора",
    "the Obnora": "Обнора",
    "the Oka country": "Приокский край",
    "the Olonets country": "Олонецкий край",
    "the Onega country": "Онежский край",
    "the Palestinian desert": "Палестинская пустыня",
    "the Peloponnese": "Пелопоннес",
    "the Pinega country": "Пинежский край",
    "the Pskov Caves": "Псково-Печерская обитель",
    "the Pčinja valley": "долина Пчини",
    "the Russian North": "Русский Север",
    "the Russian north": "Русский Север",
    "the Seto lands": "земли сету",
    "the Smolensk cemetery": "Смоленское кладбище",
    "the Sora": "Сора",
    "the Studios monastery": "Студийский монастырь",
    "the Thebaid": "Фиваида",
    "the Tikhvin country": "Тихвинский край",
    "the Urals": "Урал",
    "the Volga lands": "Поволжье",
    "the Vologda country": "Вологодский край",
    "the White Sea": "Белое море",
    "the White Sea coast": "Беломорское побережье",
    "the Wonderful Mountain": "Дивная гора",
    "the Yakhroma": "Яхрома",
    "the inner Egyptian desert": "внутренняя Египетская пустыня",
    "the lands of the apostolic mission": "земли апостольской проповеди",
    "the northern Thebaid": "Северная Фиваида",
    "the northern missions": "северные миссии",
    "the whole world": "весь мир",
    "travelers' gates": "врата путешествующих",
    "Žiča": "Жича",
})

# Two lands joined by "and" do not split on the comma.
TEXT["Rome, Side, and Ephesus"] = "Рим, Сида и Ефес"


def expand(phrases):
    """The compounds, assembled from the parts above."""
    out = {}
    for p in phrases:
        bits = p.split(", ")
        if all(b in PARTS for b in bits):
            out[p] = ", ".join(PARTS[b] for b in bits)
    return out


# The rank a saint held, as the menaia name it.
TEXT.update({
    "Abbess": "Игумения",
    "Abbot (Archimandrite)": "Игумен (архимандрит)",
    "Abbot (Founder)": "Игумен (основатель)",
    "Abbot (Igumen)": "Игумен",
    "Abbot (Igumen), Confessor": "Игумен, исповедник",
    "Abbot (Igumen), Hieromartyr": "Игумен, священномученик",
    "Abbot (Igumen), Martyr": "Игумен, мученик",
    "Abbot (Igumen), Monastic Martyr": "Игумен, преподобномученик",
    "Abbot, Confessor": "Игумен, исповедник",
    "Abbot, Confessor-Martyr": "Игумен, исповедник и мученик",
    "Abbot, Priest": "Игумен, иерей",
    "Abbots": "Игумены",
    "Anchorite": "Отшельник",
    "Apostle of the Seventy": "Апостол от семидесяти",
    "Apostle of the Seventy, Bishop": "Апостол от семидесяти, епископ",
    "Apostle of the Seventy, Martyr": "Апостол от семидесяти, мученик",
    "Apostle, Evangelist": "Апостол, евангелист",
    "Apostle, Martyr": "Апостол, мученик",
    "Apostles": "Апостолы",
    "Apostles of the Seventy": "Апостолы от семидесяти",
    "Apostles of the Seventy, Martyrs": "Апостолы от семидесяти, мученики",
    "Archangel": "Архангел",
    "Archbishop": "Архиепископ",
    "Archbishop, Confessor": "Архиепископ, исповедник",
    "Archbishop, Equal-to-the-Apostles": "Архиепископ, равноапостольный",
    "Archdeacon": "Архидиакон",
    "Archimandrite": "Архимандрит",
    "Bishop": "Епископ",
    "Bishop, Church Father": "Епископ, отец Церкви",
    "Bishop, Confessor": "Епископ, исповедник",
    "Bishop, Equal-to-the-Apostles": "Епископ, равноапостольный",
    "Bishop, Hieromartyr": "Епископ, священномученик",
    "Bishop, Monk": "Епископ, монах",
    "Bishops": "Епископы",
    "Blessed Eldress": "Блаженная старица",
    "Chamberlain (cubicularius)": "Постельничий (кувикуларий)",
    "Childmartyr": "Отрок-мученик",
    "Commander": "Военачальник",
    "Confessor, Archpriest": "Исповедник, протоиерей",
    "Deacon": "Диакон",
    "Deacon, Monk-martyr": "Диакон, преподобномученик",
    "Deaconess": "Диаконисса",
    "Deaconess and Martyr": "Диаконисса и мученица",
    "Elder": "Старец",
    "Empress": "Императрица",
    "Equal-to-the-Apostles, Emperor": "Равноапостольный, император",
    "Equals-to-the-Apostles": "Равноапостольные",
    "Grand Duchess": "Великая княгиня",
    "Grand Prince": "Великий князь",
    "Grand Princess": "Великая княгиня",
    "Great Martyr, Equal-to-the-Apostles": "Великомученик, равноапостольный",
    "Great Prince, Martyr": "Великий князь, мученик",
    "Great-martyr": "Великомученик",
    "Great-martyr, Prince": "Великомученик, князь",
    "Hermit": "Пустынник",
    "Hermits": "Пустынники",
    "Hierarchs": "Святители",
    "Hieromartyr (Hermit)": "Священномученик (пустынник)",
    "Hieromartyr, Apostle": "Священномученик, апостол",
    "Hieromartyr, Archbishop": "Священномученик, архиепископ",
    "Hieromartyr, Archimandrite": "Священномученик, архимандрит",
    "Hieromartyr, Archpriest": "Священномученик, протоиерей",
    "Hieromartyr, Bishop": "Священномученик, епископ",
    "Hieromartyr, Confessor": "Священномученик, исповедник",
    "Hieromartyr, Deacon": "Священномученик, диакон",
    "Hieromartyr, Patriarch": "Священномученик, патриарх",
    "Hieromartyr, Pope": "Священномученик, папа Римский",
    "Hieromartyr, and his son": "Священномученик и сын его",
    "Hieromartyrs": "Священномученики",
    "Hieromonk": "Иеромонах",
    "Hieroschemamonk": "Иеросхимонах",
    "High Priest": "Первосвященник",
    "Icon of the Mother of God": "Икона Божией Матери",
    "King and Martyr": "Царь и мученик",
    "King and Prophet": "Царь и пророк",
    "Laymen": "Миряне",
    "Martyrs": "Мученики",
    "Master Builders, Monks": "Зодчие, монахи",
    "Metropolitan": "Митрополит",
    "Metropolitan, Equal-to-the-Apostles": "Митрополит, равноапостольный",
    "Monastic Martyr": "Преподобномученик",
    "Monastic Martyrs": "Преподобномученики",
    "Monastic New Martyr": "Преподобномученик новый",
    "Monastics": "Преподобные",
    "Monk": "Монах",
    "Monk (Founder)": "Монах (основатель)",
    "Monk (Hermit)": "Монах (пустынник)",
    "Monk (elder)": "Монах (старец)",
    "Monk (hermit)": "Монах (пустынник)",
    "Monk (novice)": "Монах (послушник)",
    "Monk (recluse)": "Монах (затворник)",
    "Monk (stylite)": "Монах (столпник)",
    "Monk, Church Father": "Монах, отец Церкви",
    "Monk, Confessor": "Монах, исповедник",
    "Monk, Elder": "Монах, старец",
    "Monk, Hymnographer": "Монах, песнописец",
    "Monk, Martyr": "Монах, мученик",
    "Monk, Recluse": "Монах, затворник",
    "Monk, Unmercenary Physician": "Монах, бессребреник и врач",
    "Monk, former Great Zhupan": "Монах, бывший великий жупан",
    "Monk-martyr": "Преподобномученик",
    "Monk-martyrs": "Преподобномученики",
    "Monks": "Монахи",
    "Monks (Founders)": "Монахи (основатели)",
    "Mother": "Мать",
    "Myrrhbearer": "Мироносица",
    "New Martyrs": "Новомученики",
    "New Martyrs and Confessors": "Новомученики и исповедники",
    "Nun": "Монахиня",
    "Nun-martyr": "Преподобномученица",
    "Patriarch": "Патриарх",
    "Patriarch, Church Father": "Патриарх, отец Церкви",
    "Patriarch, Confessor": "Патриарх, исповедник",
    "Patriarch, Hieromartyr": "Патриарх, священномученик",
    "Physician": "Врач",
    "Physicians": "Врачи",
    "Pope": "Папа Римский",
    "Pope of Rome, Confessor": "Папа Римский, исповедник",
    "Presbyter and Deacon": "Пресвитер и диакон",
    "Presbyters, Confessors": "Пресвитеры, исповедники",
    "Priest": "Иерей",
    "Prince": "Князь",
    "Prince of Moldavia": "Господарь Молдавский",
    "Prince, Passion-Bearer": "Князь, страстотерпец",
    "Princes": "Князья",
    "Princess": "Княгиня",
    "Princess, Nun": "Княгиня, монахиня",
    "Proconsul (military commander)": "Проконсул (военачальник)",
    "Prophet and Forerunner": "Пророк и Предтеча",
    "Prophetess": "Пророчица",
    "Protomartyr": "Первомученик",
    "Protopresbyter": "Протопресвитер",
    "Recluse": "Затворник",
    "Right-believing Prince": "Благоверный князь",
    "Right-believing Prince (Monk)": "Благоверный князь (монах)",
    "Right-believing Prince and Princess": "Благоверные князь и княгиня",
    "Right-believing Prince, Passion-bearer": "Благоверный князь, страстотерпец",
    "Right-believing Princess (Nun)": "Благоверная княгиня (монахиня)",
    "Right-believing Princess, Martyr": "Благоверная княгиня, мученица",
    "Righteous (Child)": "Праведный (отрок)",
    "Righteous (Children)": "Праведные (отроки)",
    "Righteous (Unmercenary)": "Праведный (бессребреник)",
    "Righteous Forefather": "Праведный праотец",
    "Righteous Virgin": "Праведная дева",
    "Righteous, Priest": "Праведный, иерей",
    "Roman soldier": "Римский воин",
    "Schemamonk": "Схимонах",
    "Synaxis": "Собор",
    "Tsar and Imperial Family": "Царь и Царская семья",
    "Unmercenary Martyrs": "Бессребреники и мученики",
    "Venerable": "Преподобный",
    "Venerable Prince": "Преподобный князь",
    "Venerable Princess": "Преподобная княгиня",
    "Virgin": "Дева",
    "Virgin Martyrs": "Мученицы девы",
    "Virgin-martyr": "Мученица дева",
    "Youths": "Отроки",
})


# How the Church came to keep the day.
TEXT.update({
    "Ancient commemoration of the Church": "Древнее празднование Церкви",
    "Ancient commemoration of the universal Church": "Древнее празднование Вселенской Церкви",
    "Ancient observance of the Church": "Древнее чествование Церкви",
    "Ancient observance of the universal Church": "Древнее чествование Вселенской Церкви",
    "Church of Greece, glorified in 1921": "Элладская Церковь, прославлен в 1921 году",
    "Church of Rus'": "Церковь Русская",
    "Church of Rus', among the fathers of the Caves": "Церковь Русская, в сонме отцов Печерских",
    "Church of Rus', glorified in 1108": "Церковь Русская, прославлен в 1108 году",
    "Church of Rus'; the common synaxis established for the whole company": "Церковь Русская; общий собор установлен всему сонму",
    "Constantinople, under Patriarch Philotheos, within a generation of their death": "Константинополь, при патриархе Филофее, в одном поколении по кончине их",
    "Ecumenical Patriarchate": "Вселенская Патриархия",
    "Ecumenical Patriarchate of Constantinople": "Вселенская Константинопольская Патриархия",
    "Ecumenical Patriarchate of Constantinople, 1961": "Вселенская Константинопольская Патриархия, 1961 год",
    "Ecumenical Patriarchate of Constantinople, 2015": "Вселенская Константинопольская Патриархия, 2015 год",
    "Ecumenical Patriarchate of Constantinople, 2019": "Вселенская Константинопольская Патриархия, 2019 год",
    "Ecumenical Patriarchate, 1703": "Вселенская Патриархия, 1703 год",
    "Ecumenical Patriarchate, 1734": "Вселенская Патриархия, 1734 год",
    "Ecumenical Patriarchate, 1961": "Вселенская Патриархия, 1961 год",
    "Ecumenical Patriarchate, 1987": "Вселенская Патриархия, 1987 год",
    "Ecumenical Patriarchate, November 27, 2013": "Вселенская Патриархия, 27 ноября 2013 года",
    "Established by the Church at the restoration of the icons in 843": "Установлено Церковью при восстановлении икон в 843 году",
    "Established by the Church in thanksgiving for the deliverances of Constantinople": "Установлено Церковью в благодарение за избавления Константинополя",
    "Established by the Church of Constantinople": "Установлено Константинопольской Церковью",
    "Established by the Russian Orthodox Church in 1964": "Установлено Русской Православной Церковью в 1964 году",
    "Established by the observance of the Church": "Установлено чествованием Церкви",
    "Feast of the Church": "Праздник Церкви",
    "Feast of the Church of Rus'": "Праздник Церкви Русской",
    "Feast of the Church, kept with especial devotion in the churches of Rus'": "Праздник Церкви, с особым усердием хранимый в церквах Русских",
    "Feast of the Russian Orthodox Church": "Праздник Русской Православной Церкви",
    "Feast of the Serbian Orthodox Church": "Праздник Сербской Православной Церкви",
    "Georgian Orthodox Church": "Грузинская Православная Церковь",
    "Glorified August 9, 1970, the first glorification on American soil": "Прославлен 9 августа 1970 года, первое прославление на американской земле",
    "Glorified December 18, 1694, at Merkushino": "Прославлен 18 декабря 1694 года в Меркушине",
    "Glorified among the New Martyrs and Confessors of Russia by the Russian Orthodox Church": "Прославлен в сонме новомучеников и исповедников Российских Русской Православной Церковью",
    "Glorified among the New Martyrs and Confessors of Russia by the Russian Orthodox Church in 2000": "Прославлен в сонме новомучеников и исповедников Российских Русской Православной Церковью в 2000 году",
    "Glorified among the saints; his veneration embraced by the Churches of Constantinople and Rus'": "Прославлен во святых; чествование его принято Церквами Константинопольской и Русской",
    "Glorified by the Autocephalous Orthodox Church of Poland in 2003, among the New Martyrs of Chelm and Podlasie": "Прославлен Автокефальной Православной Церковью в Польше в 2003 году, в сонме новомучеников Холмских и Подляшских",
    "Glorified by the Orthodox Church in America in 1994 at Saint Tikhon's monastery": "Прославлен Православной Церковью в Америке в 1994 году в монастыре святителя Тихона",
    "Glorified by the Romanian Orthodox Church": "Прославлен Румынской Православной Церковью",
    "Glorified by the Russian Orthodox Church": "Прославлен Русской Православной Церковью",
    "Glorified by the Russian Orthodox Church in 1547": "Прославлен Русской Православной Церковью в 1547 году",
    "Glorified by the Russian Orthodox Church in 1558": "Прославлен Русской Православной Церковью в 1558 году",
    "Glorified by the Russian Orthodox Church in 1650; veneration restored in 1909": "Прославлен Русской Православной Церковью в 1650 году; чествование восстановлено в 1909 году",
    "Glorified by the Russian Orthodox Church in 1916": "Прославлен Русской Православной Церковью в 1916 году",
    "Glorified by the Russian Orthodox Church in 1989": "Прославлен Русской Православной Церковью в 1989 году",
    "Glorified by the Russian Orthodox Church on May 12, 1913": "Прославлен Русской Православной Церковью 12 мая 1913 года",
    "Glorified by the Russian Orthodox Church, locally in 1999 and for the whole Church in 2004": "Прославлен Русской Православной Церковью, местно в 1999 году и общецерковно в 2004 году",
    "Glorified in 1339, the first saint of Moscow": "Прославлен в 1339 году, первый святой Московский",
    "Glorified in 2000": "Прославлен в 2000 году",
    "His veneration, springing from the revelation of 1950, was formally recognized by the Great Church of Christ": "Чествование его, возникшее от откровения 1950 года, было признано Великой Церковью Христовой",
    "Instituted by the Church of Constantinople": "Установлено Константинопольской Церковью",
    "Local veneration": "Местное чествование",
    "Local veneration (glorified 1071)": "Местное чествование (прославлен в 1071 году)",
    "Local veneration at the Murom monastery": "Местное чествование в Муромской обители",
    "Local veneration in the Church of Rus'": "Местное чествование в Церкви Русской",
    "Local veneration of the Kyiv Caves": "Местное чествование Киево-Печерской обители",
    "Local veneration of the Kyiv Caves; in the canon of the Caves fathers": "Местное чествование Киево-Печерской обители; в каноне отцов Печерских",
    "Numbered among the New Martyrs venerated by the Church": "Причислен к новомученикам, чтимым Церковью",
    "Numbered among the New Martyrs venerated by the Church of Greece": "Причислен к новомученикам, чтимым Элладской Церковью",
    "Numbered among the saints of Mount Athos": "Причислен к святым Афонским",
    "Orthodox Church in America": "Православная Церковь в Америке",
    "Orthodox Church in America, 1980": "Православная Церковь в Америке, 1980 год",
    "Orthodox Church in America, 1994": "Православная Церковь в Америке, 1994 год",
    "Orthodox Church in America; glorified at Kwethluk, June 19, 2025": "Православная Церковь в Америке; прославлен в Кветлуке 19 июня 2025 года",
    "Orthodox Church, 1659": "Православная Церковь, 1659 год",
    "Patriarchate of Antioch, 1993": "Антиохийская Патриархия, 1993 год",
    "Pre-congregational veneration": "Чествование от древности",
    "Pre-congregational veneration; Equals-to-the-Apostles": "Чествование от древности; равноапостольные",
    "Pre-congregational veneration; among the first saints of Rus": "Чествование от древности; в числе первых святых Руси",
    "Pre-congregational veneration; glorified by miracles": "Чествование от древности; прославлен чудесами",
    "Pre-congregational veneration; venerated as patron of Moldavia": "Чествование от древности; чтится как покровитель Молдавии",
    "Pre-congregational veneration; vindicated by the Sixth Ecumenical Council": "Чествование от древности; оправдан Шестым Вселенским Собором",
    "Prophet of the Old Covenant": "Пророк Ветхого Завета",
    "Recognized among the New Martyrs by the Great Church of Christ": "Причислен к новомученикам Великой Церковью Христовой",
    "Recognized among the New Martyrs venerated in the Church of Greece": "Причислен к новомученикам, чтимым в Элладской Церкви",
    "Romanian Orthodox Church, 1992": "Румынская Православная Церковь, 1992 год",
    "Romanian Orthodox Church, 2008": "Румынская Православная Церковь, 2008 год",
    "Romanian Orthodox Church, glorified in 1955": "Румынская Православная Церковь, прославлен в 1955 году",
    "Russian Church Abroad, 1994": "Русская Зарубежная Церковь, 1994 год",
    "Russian Orthodox Church": "Русская Православная Церковь",
    "Russian Orthodox Church, 1108": "Русская Православная Церковь, 1108 год",
    "Russian Orthodox Church, 1448": "Русская Православная Церковь, 1448 год",
    "Russian Orthodox Church, 1467": "Русская Православная Церковь, 1467 год",
    "Russian Orthodox Church, 1544 (local veneration)": "Русская Православная Церковь, 1544 год (местное чествование)",
    "Russian Orthodox Church, 1547": "Русская Православная Церковь, 1547 год",
    "Russian Orthodox Church, 1549": "Русская Православная Церковь, 1549 год",
    "Russian Orthodox Church, 1579": "Русская Православная Церковь, 1579 год",
    "Russian Orthodox Church, 1591": "Русская Православная Церковь, 1591 год",
    "Russian Orthodox Church, 1595": "Русская Православная Церковь, 1595 год",
    "Russian Orthodox Church, 1597": "Русская Православная Церковь, 1597 год",
    "Russian Orthodox Church, 1645": "Русская Православная Церковь, 1645 год",
    "Russian Orthodox Church, 1646": "Русская Православная Церковь, 1646 год",
    "Russian Orthodox Church, 1649": "Русская Православная Церковь, 1649 год",
    "Russian Orthodox Church, 1650; veneration restored 1909": "Русская Православная Церковь, 1650 год; чествование восстановлено в 1909 году",
    "Russian Orthodox Church, 1652": "Русская Православная Церковь, 1652 год",
    "Russian Orthodox Church, 1659": "Русская Православная Церковь, 1659 год",
    "Russian Orthodox Church, 1664": "Русская Православная Церковь, 1664 год",
    "Russian Orthodox Church, 1687": "Русская Православная Церковь, 1687 год",
    "Russian Orthodox Church, 1698": "Русская Православная Церковь, 1698 год",
    "Russian Orthodox Church, 1757": "Русская Православная Церковь, 1757 год",
    "Russian Orthodox Church, 1798": "Русская Православная Церковь, 1798 год",
    "Russian Orthodox Church, 1800": "Русская Православная Церковь, 1800 год",
    "Russian Orthodox Church, 1804": "Русская Православная Церковь, 1804 год",
    "Russian Orthodox Church, 1832": "Русская Православная Церковь, 1832 год",
    "Russian Orthodox Church, 1861": "Русская Православная Церковь, 1861 год",
    "Russian Orthodox Church, 1896": "Русская Православная Церковь, 1896 год",
    "Russian Orthodox Church, 1903": "Русская Православная Церковь, 1903 год",
    "Russian Orthodox Church, 1911": "Русская Православная Церковь, 1911 год",
    "Russian Orthodox Church, 1913": "Русская Православная Церковь, 1913 год",
    "Russian Orthodox Church, 1914": "Русская Православная Церковь, 1914 год",
    "Russian Orthodox Church, 1978": "Русская Православная Церковь, 1978 год",
    "Russian Orthodox Church, 1988": "Русская Православная Церковь, 1988 год",
    "Russian Orthodox Church, 1994": "Русская Православная Церковь, 1994 год",
    "Russian Orthodox Church, 2000": "Русская Православная Церковь, 2000 год",
    "Russian Orthodox Church, December 4, 1994": "Русская Православная Церковь, 4 декабря 1994 года",
    "Russian Orthodox Church, Jubilee Council of 2000; earlier by the Russian Church Abroad, 1981": "Русская Православная Церковь, Юбилейный Собор 2000 года; ранее Русской Зарубежной Церковью в 1981 году",
    "Russian Orthodox Church, October 6, 1977": "Русская Православная Церковь, 6 октября 1977 года",
    "Russian Orthodox Church, October 9, 1989": "Русская Православная Церковь, 9 октября 1989 года",
    "Russian Orthodox Church, September 4, 1911": "Русская Православная Церковь, 4 сентября 1911 года",
    "Russian Orthodox Church, at the Council of 1547": "Русская Православная Церковь, на Соборе 1547 года",
    "Russian Orthodox Church, at the Council of 1549": "Русская Православная Церковь, на Соборе 1549 года",
    "Russian Orthodox Church, at the Moscow Council of 1549": "Русская Православная Церковь, на Московском Соборе 1549 года",
    "Russian Orthodox Church, c. 1452": "Русская Православная Церковь, около 1452 года",
    "Russian Orthodox Church, commemoration established at the Council of 1547": "Русская Православная Церковь, празднование установлено на Соборе 1547 года",
    "Russian Orthodox Church, commemoration established at the Council of 1549": "Русская Православная Церковь, празднование установлено на Соборе 1549 года",
    "Russian Orthodox Church, glorified at the end of the sixteenth century": "Русская Православная Церковь, прославлен в конце XVI века",
    "Russian Orthodox Church, glorified in 1595": "Русская Православная Церковь, прославлен в 1595 году",
    "Russian Orthodox Church, glorified in 1820": "Русская Православная Церковь, прославлен в 1820 году",
    "Russian Orthodox Church, glorified in 1918": "Русская Православная Церковь, прославлен в 1918 году",
    "Russian Orthodox Church, glorified in 1977": "Русская Православная Церковь, прославлен в 1977 году",
    "Russian Orthodox Church, glorified in 2000": "Русская Православная Церковь, прославлен в 2000 году",
    "Russian Orthodox Church, local veneration": "Русская Православная Церковь, местное чествование",
    "Russian Orthodox Church; commemoration restored in 1888": "Русская Православная Церковь; празднование восстановлено в 1888 году",
    "Russian Orthodox Church; local veneration from 1715": "Русская Православная Церковь; местное чествование с 1715 года",
    "Serbian Orthodox Church": "Сербская Православная Церковь",
    "Serbian Orthodox Church, 1961": "Сербская Православная Церковь, 1961 год",
    "Serbian Orthodox Church, May 15, 2005": "Сербская Православная Церковь, 15 мая 2005 года",
    "Serbian Orthodox Church, May 29, 2015": "Сербская Православная Церковь, 29 мая 2015 года",
    "Serbian Orthodox Church, glorified in 2003": "Сербская Православная Церковь, прославлен в 2003 году",
    "Serbian Orthodox Church; venerated among the first saints of the Serbian lands": "Сербская Православная Церковь; чтится в числе первых святых земли Сербской",
    "Serbian and Bulgarian Orthodox Churches": "Сербская и Болгарская Православные Церкви",
    "Ukrainian Orthodox Church, 2001": "Украинская Православная Церковь, 2001 год",
    "Veneration established by the Russian Orthodox Church": "Чествование установлено Русской Православной Церковью",
    "Veneration established in the Russian Orthodox Church": "Чествование установлено в Русской Православной Церкви",
    "Veneration established on the Holy Mountain": "Чествование установлено на Святой Горе",
})


# The name a saint bore in the world.
TEXT.update({
    "Abraham": "Авраам",
    "Alexander": "Александр",
    "Alexi": "Алексий",
    "Alexios": "Алексий",
    "Alexis": "Алексий",
    "Amos": "Амос",
    "Anastasios Kephalas": "Анастасий Кефалас",
    "Andrei": "Андрей",
    "Andrew": "Андрей",
    "Anna": "Анна",
    "Antipas": "Антипа",
    "Arsenios": "Арсений",
    "Bartholomew": "Варфоломей",
    "Basil": "Василий",
    "Constantin Antonescu": "Константин Антонеску",
    "Constantine": "Константин",
    "Constantine and Michael": "Константин и Михаил",
    "Daniel": "Даниил",
    "David": "Давид",
    "Diamantes": "Диамант",
    "Diomedes": "Диомид",
    "Draganigos": "Драганиг",
    "Eleutherios": "Елевферий",
    "Eleutherius": "Елевферий",
    "Elias": "Илия",
    "Eudokia": "Евдокия",
    "Eusebia": "Евсевия",
    "Eustathius": "Евстафий",
    "Evangelos": "Евангел",
    "Feodor": "Феодор",
    "Feodor Kolychev": "Феодор Колычев",
    "Gabriel": "Гавриил",
    "George": "Георгий",
    "Georgios Angelopoulos": "Георгий Ангелопулос",
    "Gregory": "Григорий",
    "Helen": "Елена",
    "Irene": "Ирина",
    "Ivan": "Иоанн",
    "Ivan (John) Zhelezo": "Иван (Иоанн) Железо",
    "Ivan Popov-Veniaminov": "Иван Попов-Вениаминов",
    "Joachim": "Иоаким",
    "John": "Иоанн",
    "Joseph": "Иосиф",
    "Jovan (John)": "Йован (Иоанн)",
    "Konon": "Конон",
    "Konstas": "Констас",
    "Kosmas": "Косма",
    "Kumets, Nezhilo, and Kruglets": "Кумец, Нежило и Круглец",
    "Manuel": "Мануил",
    "Mary": "Мария",
    "Matrona Dimitrievna Nikonova": "Матрона Димитриевна Никонова",
    "Matthew": "Матфей",
    "Matthew Kozhin": "Матфей Кожин",
    "Matthias": "Матфий",
    "Menas": "Мина",
    "Michael": "Михаил",
    "Michael Trivolis": "Михаил Триволис",
    "Mitrofan": "Митрофан",
    "Neanius": "Неаний",
    "Nicetas": "Никита",
    "Nicholas": "Николай",
    "Nicholas Maikov": "Николай Майков",
    "Nikola Velimirovich": "Никола Велимирович",
    "Nikon": "Никон",
    "Olga": "Ольга",
    "Otar": "Отар",
    "Parthenius": "Парфений",
    "Penelope": "Пенелопа",
    "Peter": "Пётр",
    "Predislav": "Предислав",
    "Predslava": "Предслава",
    "Procopius": "Прокопий",
    "Prokhor": "Прохор",
    "Rastko": "Растко",
    "Reprebus": "Репрев",
    "Roman and David": "Роман и Давид",
    "Romanus and David": "Роман и Давид",
    "Saul": "Савл",
    "Semyon": "Семён",
    "Sergei": "Сергей",
    "Sergius": "Сергий",
    "Simeon": "Симеон",
    "Simon": "Симон",
    "Solomonia": "Соломония",
    "Stefan Kristalevsky": "Стефан Кристалевский",
    "Stephen Nemanja": "Стефан Неманя",
    "Stojan Jovanovic": "Стоян Йованович",
    "Tarasius": "Тарасий",
    "Thekla": "Фекла",
    "Theodore": "Феодор",
    "Theodulia": "Феодулия",
    "Theophilus": "Феофил",
    "Timothy": "Тимофей",
    "Valentin": "Валентин",
    "Vasily": "Василий",
    "Vasily Ivanovich Bellavin": "Василий Иванович Беллавин",
    "Vasily Muravyov": "Василий Муравьёв",
    "Victorinus": "Викторин",
    "Vojislav": "Воислав",
    "Yaroslav": "Ярослав",
    "Yermolai": "Ермолай",
})
