# -*- coding: utf-8 -*-
"""Serbian for the vocabulary that stands beside the lives.

TEXT = {the phrase the index shows: the rendering}. The keys are the phrases
exactly as the index writes them, so a rendering cannot quietly attach itself
to the wrong saint.

A language may later declare PARTS and an expand() to assemble the compound
place-names from pieces rendered once, as the older languages do. It is an
optimisation and not a requirement: everything written in TEXT stands over
whatever expand() builds.
"""
TEXT = {
}

TEXT.update({
    "(Abibus) of Egypt": "(Авив) Египатски",
    "(Apphianus) and Edesius (Aedesius) of Lycia": "(Апфијан) и Едесије Ликијски",
    "(Eustace) the Confessor, Bishop of Bithynia": "(Евстатије) Исповедник, епископ витинијски",
    "(Jacob) the Presbyter, and Azadanes and Abdiesus the Deacons, of Persia": "(Јаков) презвитер, и Азадан и Авдијес ђакони, персијски",
    "(Vadim) of Persia": "(Вадим) Персијски",
    "(Voino-Yasenetsky), Archbishop of Simferopol and Crimea": "(Војно-Јасењецки), архиепископ симферопољски и кримски",
    "(also called Susanna), New Martyr of Lesbos": "(звана и Сузана), новомученица лезбоска",
    "(tonsured David and Euphrosyne), Wonderworkers of Murom": "(у монаштву Давид и Јефросинија), чудотворци муромски",
    "A Cappadocian centurion bowing beneath the sword with his eyes lifted in thanksgiving, the walnut tree of the tradition behind him, the churches of Byzantium rising over his relics.": "Кападокијски стотник приклања главу под мач, очију подигнутих у благодарењу, иза њега орах из предања, а над његовим моштима подижу се цркве Византије.",
    "A Celtic hermit of the Devon coast bearing his own severed head to the spring, the robbers behind him, crowned as a martyr among the saints of Britain.": "Келтски пустињак са девонске обале носи своју одсечену главу ка извору, разбојници за њим, овенчан као мученик међу светима Британије.",
    "A Christian general casting down the temples of Galatia, his twelve tribunes and his thousands of soldiers with their wives and children crowned around him, the converted sorcerer Callinicus among them.": "Хришћански војвода обара храмове Галатије, око њега овенчани његових дванаест трибуна и хиљаде војника са женама и децом, међу њима и обраћени врач Калиник.",
    "A Christian of Alexandria standing before the tribunal to denounce its cruelty, the confession volunteered and the sword received.": "Хришћанин из Александрије стоји пред судом да изобличи његову свирепост, исповедање дато својевољно и мач примљен.",
    "A Creole-Aleut priest in vestments holding a Gospel and a cross, against an Alaskan landscape.": "Свештеник креолско-алеутског рода у одеждама држи Јеванђеље и крст, а за њим аљаски предео.",
    "A Georgian bishop with a book and a restored church, schoolchildren and monasteries behind him.": "Грузијски епископ са књигом и обновљеном црквом, иза њега школска деца и манастири.",
    "A Georgian commander marking his forehead with the cross in his own blood, his soldiers crowned around him.": "Грузијски војвода знаменује чело крстом сопственом крвљу, око њега овенчани његови војници.",
    "A Georgian monk in prayer before the cave monastery of Gareji in the desert hills.": "Грузијски монах у молитви пред пећинским манастиром Гареџи у пустињским брдима.",
    "A Georgian monk-abbot holding a scroll or a book.": "Грузијски монах-игуман држи свитак или књигу.",
    "A Georgian prince and commander refusing to trample the icon of Christ before the conqueror, crowned as a great-martyr, the defender of the Georgian faith.": "Грузијски кнез и војвода одбија да пред освајачем згази икону Христову, овенчан као великомученик, бранилац грузијске вере.",
    "A Gothic congregation at worship within the burning church, twenty-six crowns rising with the smoke, the queen gathering the holy remains from the ashes.": "Готска паства на богослужењу у запаљеној цркви, двадесет шест венаца се уздиже са димом, а краљица сабира свете мошти из пепела.",
    "A Gothic general of Rome casting down his military belt before Aurelian, seventy soldiers confessing behind him, the river receiving the wonderworking commander.": "Готски војвода римски баца свој војнички појас пред Аурелијана, седамдесет војника исповеда веру за њим, а река прима чудотворног војводу.",
})

TEXT.update({
    "A Great Prince of Kyiv with the churches of Smolensk he raised, the monastic habit he longed for held by an angel, the elder Polycarp pointing him back to his throne.": "Велики кнез кијевски са црквама смоленским које је подигао, монашку ризу за којом је чезнуо држи анђео, а старац Поликарп га упућује натраг на престо.",
    "A Greek bishop preaching Christ to the pagan Rostov land, the first shepherd of a hostile flock, the see of Rostov founded amid the idols of the north.": "Грчки епископ проповеда Христа незнабожачкој ростовској земљи, први пастир непријатељског стада, а ростовска катедра утемељена усред северних идола.",
    "A Greek iconographer of Constantinople founding the island monastery of Lake Onega, the Sophia icon he copied in his hands, the peoples of the north gathering to his light at the age of one hundred and five.": "Грчки иконописац цариградски оснива острвски манастир на Оњешком језеру, у рукама му икона Софије коју је преписао, а северни народи се сабирају ка његовој светлости у сто петој години.",
    "A Greek metropolitan enthroned at Moscow beside the shrine of Peter, standing unbowed before the khan of the Horde, the Church's charter of freedom in his hand.": "Грчки митрополит устоличен у Москви крај раке Петрове, стоји неповијен пред каном Орде, а у руци му повеља црквене слободе.",
    "A Greek of Ephesus at the Apostle Paul's side, the Temple riot swirling around his innocent presence, the sickbed of Miletus and the sword of Rome completing his long companionship.": "Грк из Ефеса уз апостола Павла, метеж око храма ковитла се око његовог невиног присуства, а болеснички одар у Милиту и мач римски довршавају његово дуго сапутништво.",
    "A Greek prince laying aside his rank for the monastic habit, the Uchma hermitage rising on the bank of the Volga, the exile made a wonderworker in his adopted land.": "Грчки кнез оставља свој чин ради монашке ризе, учманска испосница се уздиже на обали Волге, а изгнаник постаје чудотворац у земљи која га је примила.",
    "A Patriarch of Constantinople seated upright in death as in blessing, the Mgar monastery of Lubny receiving the traveler, the two worlds of Greece and Rus' joined at his throne.": "Патријарх цариградски седи усправно у смрти као у благослову, мгарски манастир код Лубна прима путника, а два света, грчки и руски, састају се пред његовим престолом.",
    "A Persian noble offering his severed members one by one, each with a prayer, angels gathering his prayers.": "Персијски великаш приноси један по један своје одсечене удове, сваки уз молитву, а анђели сабирају његове молитве.",
    "A Persian soldier turned monk, the captive Cross of the Lord shining before him, the waters and the sword of Bethsaloe beneath his crown.": "Персијски војник постао монах, заробљени Крст Господњи сија пред њим, а воде и мач Витсалоја под његовим венцем.",
    "A Roman centurion kneeling before the Apostle Peter, or vested as a bishop holding a Gospel.": "Римски стотник клечи пред апостолом Петром, или у архијерејским одеждама држи Јеванђеље.",
    "A Roman general in armor holding a cross, his soldiers behind him, a spring at his feet.": "Римски војвода у оклопу држи крст, војници за њим, а извор код његових ногу.",
    "A Roman maiden in flight across the sea with two servants, the convent of Saint Stephen at Mylasa, a cross of stars brighter than the sun above her repose.": "Римска девојка бежи преко мора са две слушкиње, женски манастир Светог Стефана у Миласи, а крст од звезда, сјајнији од сунца, над њеним упокојењем.",
    "A Roman matron refusing the Arian rite, the fire kindled behind her, Saint Ambrose blessing from afar.": "Римска угледна жена одбија аријански обред, ватра запаљена за њом, а свети Амвросије благосиља издалека.",
    "A Roman noblewoman scattering deeds and treasure to the poor, thousands of freed slaves behind her, her small cell on the Mount of Olives before her.": "Римска племкиња раздаје сиромасима повеље и благо, за њом хиљаде ослобођених робова, а пред њом њена мала келија на Гори маслинској.",
    "A Roman senator opening his house to the Apostle Peter, the household at prayer becoming a church, the greeting of the epistle shining over the door.": "Римски сенатор отвара свој дом апостолу Петру, домаћи на молитви постају црква, а поздрав из посланице сија над вратима.",
    "A Roman widow standing amid seven crowned sons, encouraging each to the contest, her own crown descending last.": "Римска удовица стоји међу седам овенчаних синова, бодрећи свакога на подвиг, а њен венац силази последњи.",
    "A Russian captive in the winter night of Kazan, bound and wounded in the snow, alive at dawn with his confession unbroken.": "Руски заробљеник у зимској ноћи казањској, свезан и рањен у снегу, у зору жив са неповређеним исповедањем.",
    "A Russian soldier-slave at prayer in his master's stable, the Turkish household softened by his faith, his incorrupt relics glorified across the Greek world.": "Руски војник-роб на молитви у штали свога господара, турски дом омекшан његовом вером, а његове нетрулежне мошти прослављене по свему грчком свету.",
    "A Serbian prince leading his army at Kosovo, choosing the kingdom of heaven over the kingdom of earth, crowned as a great-martyr, his incorrupt relics the treasure of his people.": "Српски кнез води своју војску на Косову, определивши се за царство небеско а не за земаљско, овенчан као великомученик, а његове нетрулежне мошти благо су свога народа.",
    "A Spanish dignitary in the Great Schema, the roads of his pilgrimage from Rome to Jerusalem behind him, the Saracen sword before him.": "Шпански великодостојник у великој схими, за њим путеви његовог поклоњења од Рима до Јерусалима, а пред њим сараценски мач.",
    "A Swedish princess become mother of Rus, her sainted son Vladimir beside her, the crowns of France, Hungary, and Norway among her daughters, the nun's habit her final vesture.": "Шведска принцеза постала мати Русије, крај ње њен свети син Владимир, међу њеним кћерима круне Француске, Угарске и Норвешке, а монашка риза њено последње оденуће.",
    "A Syrian stranger standing three days in prayer in the church of Spoleto, the garden thieves fed at his table and converted, the offered estates refused with a smiling shake of the head.": "Сиријски странац стоји три дана на молитви у цркви у Сполету, лопови из врта нахрањени за његовом трпезом и обраћени, а понуђена имања одбијена осмехом и одмахивањем главе.",
    "A Tatar captive baptized and tonsured, founding a monastery on the shore of Lake Kozha in the far north, the wilderness hallowed by his prayer.": "Татарски заробљеник крштен и замонашен, оснива манастир на обали језера Коже на далеком северу, а пустиња освећена његовом молитвом.",
    "A Yup'ik mother in a kuspuk holding a basin and towel, the northern lights above the tundra behind her.": "Мати из народа Јупика у куспуку држи умиваоник и убрус, а за њом северна светлост над тундром.",
    "A barefoot ascetic in rags, blessing, at Novgorod.": "Босоноги подвижник у ритама благосиља, у Новгороду.",
    "A barefoot fool in tattered clothing by a northern river, giving away what was given to him.": "Босоноги јуродиви у подераном оделу крај северне реке, раздаје оно што му је дато.",
    "A barefoot fool-for-Christ holding a head of cabbage, at Novgorod by the river.": "Босоноги Христа ради јуродиви држи главицу купуса, у Новгороду крај реке.",
    "A barefoot fool-for-Christ in a sheepskin holding an axe, by the river defending the city.": "Босоноги Христа ради јуродиви у кожуху држи секиру, крај реке брани град.",
    "A barefoot holy fool with long hair, holding a Psalter, of gentle and sorrowful aspect.": "Босоноги јуродиви дуге косе држи Псалтир, кротког и жалосног лика.",
    "A basilica at Lydda, the tomb of Saint George within, hierarchs consecrating the church.": "Базилика у Лиди, у њој гроб светог Георгија, а архијереји освећују цркву.",
    "A bearded missionary priest with a traveler's bag, the church of Jackson and the hills of California behind him.": "Брадати свештеник мисионар са путничком торбом, за њим црква у Џексону и брда Калифорније.",
    "A beggar beneath the staircase of his father's palace, unknown to all his household, the finished scroll of his life clasped in his dead hand while the emperor and the pope kneel to read it.": "Просјак под степеништем очевог двора, непознат свима у дому свом, довршени свитак свога живота стеже у мртвој руци док цар и папа клече да га прочитају.",
    "A bent elder in white on his knees upon the rock, the Theotokos of Tenderness before him, a bear at the edge of the forest clearing.": "Погрбљени старац у белом на коленима на камену, пред њим Богородица Умиљенија, а медвед на рубу шумске чистине.",
    "A bishop alone in an emptied city awaiting the persecutors, then crucified at Perge, teaching from the cross until his voice failed into glory.": "Епископ сам у испражњеном граду чека гонитеље, потом распет у Перги, поучава са крста док му се глас не угаси у слави.",
    "A bishop and a presbyter of Persia holding crosses, swords above them.": "Епископ и презвитер персијски држе крстове, а мачеви над њима.",
    "A bishop and a virgin holding crosses, broken books of sorcery burning at their feet.": "Епископ и девојка држе крстове, а покидане књиге врачања горе им пред ногама.",
    "A bishop and his companions holding crosses, cast into a furnace, a soldier among them.": "Епископ и његови сапатници држе крстове, бачени у пећ, а међу њима војник.",
    "A bishop and presbyter cast into a pit, angels crowning them from above.": "Епископ и презвитер бачени у јаму, а анђели их одозго венчавају.",
    "A bishop and theologian of Lycia with the scroll of his Banquet of the Ten Virgins, refuting the errors of Origen, crowned at the last with martyrdom.": "Епископ и богослов ликијски са свитком свога Пира десет девојака, изобличава Оригенове заблуде, а на крају овенчан мучеништвом.",
    "A bishop answering the emperor that the Church's questions belong to the Church, the road of exile opening behind him.": "Епископ одговара цару да питања Цркве припадају Цркви, а пут изгнанства се отвара за њим.",
})

TEXT.update({
    "A bishop baptizing an African king, a boy captive and a royal tutor shown in the scenes of his life.": "Епископ крштава афричког краља, а у призорима његовог живота приказани су дечак заробљеник и краљевски учитељ.",
    "A bishop barring the church door to an emperor, a beehive at his feet, a scroll of his hymns in hand.": "Епископ забрањује цару улаз у цркву, кошница крај његових ногу, а у руци свитак његових песама.",
    "A bishop before a fallen idol, a demon bearing a great stone altar behind him, hot springs at his feet.": "Епископ пред обореним идолом, за њим демон носи велики камени жртвеник, а топли извори код његових ногу.",
    "A bishop before the burning temple of Marnas, the cross-guardian's keys at his belt, the Good Thief descending from the Cross in his vision, the Eudoxiana church rising over pagan Gaza.": "Епископ пред запаљеним храмом Марнасовим, кључеви чувара крста о појасу, благоразумни разбојник силази са Крста у његовом виђењу, а црква Евдоксијана се уздиже над незнабожачком Газом.",
    "A bishop before the emperor, pointing to the emperor's son, teaching the honor due the Son of God.": "Епископ пред царем показује на царевог сина, поучавајући о части која припада Сину Божјем.",
    "A bishop beheaded at the altar in mid-Liturgy, twenty-eight years of tribunals and torments ranged behind him like waves, Agathangelus crowned at his side.": "Епископ посечен пред жртвеником усред Литургије, двадесет осам година судова и мука ређају се за њим као таласи, а Агатангел овенчан крај њега.",
    "A bishop beholding the ladder to heaven with his predecessor calling from above, one hundred and twenty-eight companions ascending behind him under the Persian sword.": "Епископ гледа лествицу до неба, а претходник га зове одозго, сто двадесет осам сапатника се успињу за њим под персијским мачем.",
    "A bishop by night in a plain cloak, leaving firewood at a poor widow's door, his cathedral of Belgorod behind him.": "Епископ ноћу у простом огртачу оставља дрва пред вратима сиромашне удовице, а за њим саборна црква белгородска.",
    "A bishop drinking the sorcerer's cup unharmed, the magician kneeling converted beside his cast-down instruments.": "Епископ испија врачеву чашу без штете, а мађионичар клечи обраћен крај својих одбачених справа.",
    "A bishop enthroned with a Gospel, the first hierarch of Jerusalem, of ascetic and venerable countenance.": "Епископ устоличен са Јеванђељем, први архијереј јерусалимски, подвижничког и часног лика.",
    "A bishop holding a Gospel, refuting heretics who shrink before his word.": "Епископ држи Јеванђеље, изобличава јеретике који узмичу пред његовом речју.",
    "A bishop holding a page of the alphabet he invented, the sacred birch of the Zyrians felled behind him, the sorcerer Pam turning from the fire and the water, a new people reading the Gospel in its own letters.": "Епископ држи лист азбуке коју је саставио, за њим оборена света бреза Зирјана, врач Пам узмиче пред ватром и водом, а нови народ чита Јеванђеље својим словима.",
    "A bishop holding a scroll of the Creed, the Theotokos and John the Theologian appearing above, a mountain moved behind.": "Епископ држи свитак Символа вере, горе се јављају Богородица и Јован Богослов, а иза њега померена гора.",
    "A bishop holding an icon of Christ against the imperial decree, the sick healed at his hands.": "Епископ држи икону Христову насупрот царској наредби, а болесни се исцељују његовим рукама.",
    "A bishop holding the book of the Divine Names, the darkened sun of the Crucifixion above him.": "Епископ држи књигу О божанским именима, а над њим помрачено сунце Распећа.",
    "A bishop in a laborer's tunic drawing water and hauling wood at Nitria, the omophorion of Damascus folded away, heaven alone reading the monk's true rank.": "Епископ у радничкој хаљини захвата воду и носи дрва у Нитрији, дамаскински омофор склоњен, а само небо чита прави чин монахов.",
    "A bishop in a mitre holding a crozier, with a gray beard and an ascetic, gentle face.": "Епископ у митри држи жезло, седе браде и подвижничког, кротког лика.",
    "A bishop in monastic poverty, Cernica's island monastery at one hand and the Frasinei he founded at the other, the seminary and the printing press of Ramnic behind him, his face worn bright by fasting.": "Епископ у монашком сиромаштву, с једне стране острвски манастир Черника а с друге Фрасинеј који је основао, за њим богословија и штампарија у Рамнику, а лице му постом изнурено и просветљено.",
    "A bishop in the omophorion and mantle holding a book, of gentle and humble aspect.": "Епископ у омофору и мантији држи књигу, кроткога и смиреног лика.",
    "A bishop in the omophorion and sakkos holding a Gospel book, with a Greek-style beard.": "Епископ у омофору и сакосу држи Јеванђеље, са брадом по грчком обичају.",
    "A bishop in the omophorion blessing the waters at a river confluence, holding a cross.": "Епископ у омофору освећује воде на саставу река, држећи крст.",
    "A bishop in the omophorion blessing, holding a Gospel, before the cathedral of Tambov.": "Епископ у омофору благосиља, држећи Јеванђеље, пред саборном црквом тамбовском.",
    "A bishop in the omophorion holding a Gospel book or the scroll of his Great Canon.": "Епископ у омофору држи Јеванђеље или свитак свога Великог канона.",
    "A bishop in the omophorion holding a Gospel book, a white dove upon his head.": "Епископ у омофору држи Јеванђеље, а на глави му бели голуб.",
    "A bishop in the omophorion holding a Gospel, of humble aspect.": "Епископ у омофору држи Јеванђеље, смиреног лика.",
    "A bishop in the omophorion holding a Gospel, sometimes with a banner or before a battle.": "Епископ у омофору држи Јеванђеље, понекад са заставом или пред битком.",
    "A bishop in the omophorion holding a Gospel, the cathedral of Saints Cyril and Methodius behind him.": "Епископ у омофору држи Јеванђеље, а за њим саборна црква Светих Кирила и Методија.",
    "A bishop in the omophorion holding an icon and a Gospel.": "Епископ у омофору држи икону и Јеванђеље.",
    "A bishop in the omophorion surrounded by his ten disciples, all crowned as martyrs.": "Епископ у омофору окружен својих десет ученика, сви овенчани као мученици.",
    "A bishop in the omophorion, his hands or face marked by charcoal, holding a Gospel.": "Епископ у омофору, руку или лица обележених угљеном, држи Јеванђеље.",
    "A bishop in the schema and omophorion holding a Gospel, before the city of Voronezh.": "Епископ у схими и омофору држи Јеванђеље, пред градом Вороњежом.",
    "A bishop in the snows of Siberia, a school of native children beside him, the gates of China closed behind.": "Епископ у сибирским снеговима, крај њега школа домородачке деце, а за њим затворена врата Кине.",
    "A bishop laying aside his omophorion at the mouth of a desert gorge, the monastery of Choziba in the cliffs.": "Епископ оставља свој омофор на улазу у пустињску клисуру, а манастир Хозива у стенама.",
    "A bishop led by an angel from torture to torture and city to city, Sirmium converted behind him and Formia receiving him, the lamps of the sailors burning at his name.": "Епископа анђео води од муке до муке и од града до града, за њим обраћени Сирмијум а Формија га прима, и кандила морнарска горе на његово име.",
    "A bishop of Aegina laying down his omophorion and returning to the monastic habit, his island see behind him.": "Епископ егински оставља омофор и враћа се монашкој ризи, а за њим његова острвска катедра.",
    "A bishop of Amasea standing between the hunted virgin and the tyrant's demand, the sea giving back his body in the fishermen's nets, the last crowns of the persecution descending as the peace of the Church dawns.": "Епископ амасијски стоји између прогоњене девојке и мучитељевог захтева, море враћа његово тело у рибарским мрежама, а последњи венци гоњења силазе док свиће мир Цркве.",
    "A bishop of Argos measuring out grain that does not diminish, the ransomed captives returning from the sea behind him, his monastic family in Christ around the one see he consented to hold.": "Епископ аргоски одмерава жито које се не умањује, за њим се откупљени робови враћају с мора, а око једине катедре коју је пристао да држи његова монашка породица у Христу.",
    "A bishop of Benevento unharmed in the furnace, the beasts of the arena lying at his feet, Naples receiving his body and his blood, his deacons and companions crowned around him.": "Епископ беневентски неповређен у пећи, звери из арене леже му пред ногама, Напуљ прима његово тело и његову крв, а око њега овенчани његови ђакони и сапатници.",
    "A bishop of Bithynia holding the icon of Christ and the open Scriptures together, the road of exile behind him.": "Епископ витинијски држи заједно икону Христову и отворено Писмо, а за њим пут изгнанства.",
    "A bishop of Bithynia on the road of exile, his cathedral behind him and the icon of Christ unsurrendered before him.": "Епископ витинијски на путу изгнанства, за њим његова саборна црква а пред њим непредата икона Христова.",
})
