# -*- coding: utf-8 -*-
"""Ukrainian for the vocabulary that stands beside the lives.

TEXT = {the phrase the index shows: the Ukrainian}. PARTS holds the pieces
the compound place-names are built from, and expand() assembles the wholes,
so a town cannot be spelled one way on one card and another way on the next.

The rank vocabulary was settled before any of this was written, and is set
down in docs/UKRAINIAN.md. The reason is the defect that had to be swept out
of the three finished languages: in a Slavonic-tradition tongue a saint's
honorific is his rank, and the bare word святий stands before a rank and
never before a name. Преподобний Сергій, святитель Миколай, благовірний
князь Володимир, праведний Симеон Богоприїмець.

The nearer trap here is Russian. Ukrainian is close enough to it that a
rendering can be correct Russian and merely Russian-shaped Ukrainian, which
a reader feels at once and no checker sees. So the Church's own Ukrainian
words are used: Церква declining as Церкви, чернець for the monk, сповідник
for the confessor, безсрібник for the unmercenary, Успіння for the Dormition,
Києво-Печерська лавра and its печерські fathers. Placenames take their
Ukrainian shapes - Київ, Чернігів, Волинь, Переяслав - and the princes their
Ukrainian names: Володимир, Ярослав, Борис і Гліб.

The keys are the phrases exactly as the index writes them, so a rendering
cannot quietly attach itself to the wrong saint.
"""
TEXT = {}


# The orders of sanctity, as the badge on a card names them.
TEXT.update({
    "Angelic": "Безтілесні сили",
    "Apostle": "Апостол",
    "Confessor": "Сповідник",
    "Equal-to-the-Apostles": "Рівноапостольний",
    "Feast": "Свято",
    "Fool-for-Christ": "Христа ради юродивий",
    "Great Martyr": "Великомученик",
    "Hierarch": "Святитель",
    "Hieromartyr": "Священномученик",
    "Martyr": "Мученик",
    "Monastic": "Преподобний",
    "New Martyr": "Новомученик",
    "Other": "Інше",
    "Passion-bearer": "Страстотерпець",
    "Prophet": "Пророк",
    "Righteous": "Праведний",
    "Unmercenary": "Безсрібник",
    "Virgin Martyr": "Мучениця-діва",
})


# The attributes a life is marked with.
TEXT.update({
    "Church Father": "Отець Церкви",
    "Desert ascetic": "Подвижник пустелі",
    "Enlightener": "Просвітитель",
    "Healing intercessor": "Цілитель",
    "Hymnographer": "Піснописець",
    "Iconographer": "Іконописець",
    "Incorrupt relics": "Нетлінні мощі",
    "Monastery founder": "Засновник обителі",
    "Myrrh-bearer": "Мироносиця",
    "Myrrh-streaming": "Мироточивий",
    "New martyr": "Новомученик",
    "Ruler or royal": "Правитель або з княжого роду",
    "Stylite": "Стовпник",
    "Warrior saint": "Святий воїн",
    "Wonderworker": "Чудотворець",
})


# The ranks the Typikon gives a feast.
TEXT.update({
    "Doxology": "Славослів'я",
    "Great Feast": "Велике свято",
    "Polyeleos": "Полієлей",
    "Simple": "Проста",
    "Vigil": "Всенічне бдіння",
})


# The jurisdictions whose calendars the index keeps.
TEXT.update({
    "Antiochian": "Антіохійський",
    "Greek": "Грецький",
    "OCA": "OCA",
    "Romanian": "Румунський",
    "Russian": "Російський",
    "Serbian": "Сербський",
    "Ukrainian": "Український",
})


# The estate a saint stood in.
TEXT.update({
    "Apostolic": "Апостольський",
    "Clergy": "Духівництво",
    "Laity": "Миряни",
    "Layman": "Мирянин",
    "Laywoman": "Мирянка",
    "Laywomen": "Мирянки",
    "Married": "Одружений",
    "Military": "Військовий",
    "Monastic": "Чернечий",
    "Prophet": "Пророк",
    "Royal": "Княжий",
    "Royalty": "Княжий рід",
    "Unknown": "Невідомо",
    "Unmarried": "Неодружений",
    "Widowed": "Овдовілий",
})


# The ages the lives are set in.
TEXT.update({
    "Age of the Celtic Saints": "Доба кельтських святих",
    "Age of the Ecumenical Councils": "Доба Вселенських Соборів",
    "Age of the Martyrs": "Доба мучеників",
    "Apostolic Age": "Апостольська доба",
    "Byzantine": "Візантійський",
    "Byzantine Balkans": "Візантійські Балкани",
    "Byzantine Era": "Візантійська доба",
    "Byzantine Iconoclasm": "Візантійське іконоборство",
    "Cossack Era": "Козацька доба",
    "Desert Fathers": "Отці пустелі",
    "Early Medieval West": "Ранньосередньовічний Захід",
    "Imperial Russia": "Імперська Росія",
    "Kievan Rus'": "Київська Русь",
    "Medieval Georgia": "Середньовічна Грузія",
    "Medieval Rus'": "Середньовічна Русь",
    "Medieval Serbia": "Середньовічна Сербія",
    "Modern": "Новітній",
    "Modern Era": "Новітня доба",
    "Muscovite Russia": "Московська Русь",
    "Old Testament": "Старий Завіт",
    "Ottoman Balkans": "Османські Балкани",
    "Ottoman Era": "Османська доба",
    "Ottoman period": "Османський період",
    "Polish-Lithuanian period": "Польсько-литовський період",
    "Soviet Era": "Радянська доба",
    "Soviet period": "Радянський період",
    "Synodal Russia": "Синодальна Росія",
})


# The one movable commemoration the index names.
TEXT.update({
    "Sunday of the Holy Forefathers": "Неділя святих праотців",
})


# The countries and the regions.
TEXT.update({
    "Aegean": "Егейське море",
    "America": "Америка",
    "Arabia": "Аравія",
    "Armenia": "Вірменія",
    "Asia Minor": "Мала Азія",
    "Balkans": "Балкани",
    "Belarus": "Білорусь",
    "Bithynia": "Віфінія",
    "Britain": "Британія",
    "British Isles": "Британські острови",
    "Bulgaria": "Болгарія",
    "Cappadocia": "Каппадокія",
    "Cilicia": "Кілікія",
    "Constantinople": "Константинополь",
    "Crimea": "Крим",
    "Cyprus": "Кіпр",
    "Czech Lands": "Чеські землі",
    "Dalmatia": "Далмація",
    "Danube lands": "Подунав'я",
    "Egypt": "Єгипет",
    "England": "Англія",
    "Ethiopia": "Ефіопія",
    "Gaul": "Галлія",
    "Georgia": "Грузія",
    "Greece": "Греція",
    "Holy Land": "Свята Земля",
    "Illyria": "Іллірія",
    "Illyricum": "Іллірик",
    "India": "Індія",
    "Ireland": "Ірландія",
    "Italy": "Італія",
    "Lithuania": "Литва",
    "Macedonia": "Македонія",
    "Mesopotamia": "Месопотамія",
    "Moldavia": "Молдова",
    "Montenegro": "Чорногорія",
    "Moravia": "Моравія",
    "Mount Athos": "Свята Гора Афон",
    "North Africa": "Північна Африка",
    "North America": "Північна Америка",
    "North Macedonia": "Північна Македонія",
    "Palestine": "Палестина",
    "Persia": "Персія",
    "Phoenicia": "Фінікія",
    "Poland": "Польща",
    "Pontus": "Понт",
    "Romania": "Румунія",
    "Rome": "Рим",
    "Russia": "Росія",
    "Scythia": "Скіфія",
    "Serbia": "Сербія",
    "Siberia": "Сибір",
    "Sinai": "Синай",
    "Spain": "Іспанія",
    "Syria": "Сирія",
    "Thrace": "Фракія",
    "Ukraine": "Україна",
    "Western Rus": "Західна Русь",
})


# The lands the fasting rule is kept in.
TEXT.update({
    "Albania": "Албанія",
    "Bohemia": "Богемія",
    "China": "Китай",
    "France": "Франція",
    "Judah": "Юдея",
    "Moesia": "Мезія",
    "Sicily": "Сицилія",
    "United States": "Сполучені Штати",
})

# The rank a saint held, as the menaia name it.
TEXT.update({
    "Abbess": "Ігуменя",
    "Abbot (Archimandrite)": "Ігумен (архімандрит)",
    "Abbot (Founder)": "Ігумен (засновник)",
    "Abbot (Igumen)": "Ігумен",
    "Abbot (Igumen), Confessor": "Ігумен, сповідник",
    "Abbot (Igumen), Hieromartyr": "Ігумен, священномученик",
    "Abbot (Igumen), Martyr": "Ігумен, мученик",
    "Abbot (Igumen), Monastic Martyr": "Ігумен, преподобномученик",
    "Abbot, Confessor": "Ігумен, сповідник",
    "Abbot, Confessor-Martyr": "Ігумен, сповідник і мученик",
    "Abbot, Priest": "Ігумен, ієрей",
    "Abbots": "Ігумени",
    "Anchorite": "Самітник",
    "Apostle of the Seventy": "Апостол від сімдесяти",
    "Apostle of the Seventy, Bishop": "Апостол від сімдесяти, єпископ",
    "Apostle of the Seventy, Martyr": "Апостол від сімдесяти, мученик",
    "Apostle, Evangelist": "Апостол, євангелист",
    "Apostle, Martyr": "Апостол, мученик",
    "Apostles": "Апостоли",
    "Apostles of the Seventy": "Апостоли від сімдесяти",
    "Apostles of the Seventy, Martyrs": "Апостоли від сімдесяти, мученики",
    "Archangel": "Архангел",
    "Archbishop": "Архієпископ",
    "Archbishop, Confessor": "Архієпископ, сповідник",
    "Archbishop, Equal-to-the-Apostles": "Архієпископ, рівноапостольний",
    "Archdeacon": "Архідиякон",
    "Archimandrite": "Архімандрит",
    "Bishop": "Єпископ",
    "Bishop, Church Father": "Єпископ, отець Церкви",
    "Bishop, Confessor": "Єпископ, сповідник",
    "Bishop, Equal-to-the-Apostles": "Єпископ, рівноапостольний",
    "Bishop, Hieromartyr": "Єпископ, священномученик",
    "Bishop, Monk": "Єпископ, чернець",
    "Bishops": "Єпископи",
    "Blessed Eldress": "Блаженна стариця",
    "Chamberlain (cubicularius)": "Кувікуларій",
    "Childmartyr": "Отрок-мученик",
    "Commander": "Воєвода",
    "Confessor, Archpriest": "Сповідник, протоієрей",
    "Deacon": "Диякон",
    "Deacon, Monk-martyr": "Диякон, преподобномученик",
    "Deaconess": "Дияконіса",
    "Deaconess and Martyr": "Дияконіса і мучениця",
    "Elder": "Старець",
    "Empress": "Цариця",
    "Equal-to-the-Apostles, Emperor": "Рівноапостольний, цар",
    "Equals-to-the-Apostles": "Рівноапостольні",
    "Grand Duchess": "Велика княгиня",
    "Grand Prince": "Великий князь",
    "Grand Princess": "Велика княгиня",
    "Great Martyr, Equal-to-the-Apostles": "Великомученик, рівноапостольний",
    "Great Prince, Martyr": "Великий князь, мученик",
    "Great-martyr": "Великомученик",
    "Great-martyr, Prince": "Великомученик, князь",
    "Hermit": "Пустельник",
    "Hermits": "Пустельники",
    "Hierarchs": "Святителі",
    "Hieromartyr (Hermit)": "Священномученик (пустельник)",
    "Hieromartyr, Apostle": "Священномученик, апостол",
    "Hieromartyr, Archbishop": "Священномученик, архієпископ",
    "Hieromartyr, Archimandrite": "Священномученик, архімандрит",
    "Hieromartyr, Archpriest": "Священномученик, протоієрей",
    "Hieromartyr, Bishop": "Священномученик, єпископ",
    "Hieromartyr, Confessor": "Священномученик, сповідник",
    "Hieromartyr, Deacon": "Священномученик, диякон",
    "Hieromartyr, Patriarch": "Священномученик, патріарх",
    "Hieromartyr, Pope": "Священномученик, папа Римський",
    "Hieromartyr, and his son": "Священномученик і син його",
    "Hieromartyrs": "Священномученики",
    "Hieromonk": "Ієромонах",
    "Hieroschemamonk": "Ієросхимонах",
    "High Priest": "Первосвященник",
    "Icon of the Mother of God": "Ікона Божої Матері",
    "King and Martyr": "Цар і мученик",
    "King and Prophet": "Цар і пророк",
    "Laymen": "Миряни",
    "Martyrs": "Мученики",
    "Master Builders, Monks": "Зодчі, ченці",
    "Metropolitan": "Митрополит",
    "Metropolitan, Equal-to-the-Apostles": "Митрополит, рівноапостольний",
    "Monastic Martyr": "Преподобномученик",
    "Monastic Martyrs": "Преподобномученики",
    "Monastic New Martyr": "Преподобномученик новий",
    "Monastics": "Ченці",
    "Monk": "Чернець",
    "Monk (Founder)": "Чернець (засновник)",
    "Monk (Hermit)": "Чернець (пустельник)",
    "Monk (elder)": "Чернець (старець)",
    "Monk (hermit)": "Чернець (пустельник)",
    "Monk (novice)": "Чернець (послушник)",
    "Monk (recluse)": "Чернець (затворник)",
    "Monk (stylite)": "Чернець (стовпник)",
    "Monk, Church Father": "Чернець, отець Церкви",
    "Monk, Confessor": "Чернець, сповідник",
    "Monk, Elder": "Чернець, старець",
    "Monk, Hymnographer": "Чернець, піснописець",
    "Monk, Martyr": "Чернець, мученик",
    "Monk, Recluse": "Чернець, затворник",
    "Monk, Unmercenary Physician": "Чернець, безсрібник-лікар",
    "Monk, former Great Zhupan": "Чернець, колишній великий жупан",
    "Monk-martyr": "Преподобномученик",
    "Monk-martyrs": "Преподобномученики",
    "Monks": "Ченці",
    "Monks (Founders)": "Ченці (засновники)",
    "Mother": "Мати",
    "Myrrhbearer": "Мироносиця",
    "New Martyrs": "Новомученики",
    "New Martyrs and Confessors": "Новомученики і сповідники",
    "Nun": "Черниця",
    "Nun-martyr": "Преподобномучениця",
    "Patriarch": "Патріарх",
    "Patriarch, Church Father": "Патріарх, отець Церкви",
    "Patriarch, Confessor": "Патріарх, сповідник",
    "Patriarch, Hieromartyr": "Патріарх, священномученик",
    "Physician": "Лікар",
    "Physicians": "Лікарі",
    "Pope": "Папа Римський",
    "Pope of Rome, Confessor": "Папа Римський, сповідник",
    "Presbyter and Deacon": "Пресвітер і диякон",
    "Presbyters, Confessors": "Пресвітери, сповідники",
    "Priest": "Ієрей",
    "Prince": "Князь",
    "Prince of Moldavia": "Господар Молдавський",
    "Prince, Passion-Bearer": "Князь, страстотерпець",
    "Princes": "Князі",
    "Princess": "Княгиня",
    "Princess, Nun": "Княгиня, черниця",
    "Proconsul (military commander)": "Проконсул (воєвода)",
    "Prophet and Forerunner": "Пророк і Предтеча",
    "Prophetess": "Пророчиця",
    "Protomartyr": "Первомученик",
    "Protopresbyter": "Протопресвітер",
    "Recluse": "Затворник",
    "Right-believing Prince": "Благовірний князь",
    "Right-believing Prince (Monk)": "Благовірний князь (чернець)",
    "Right-believing Prince and Princess": "Благовірні князь і княгиня",
    "Right-believing Prince, Passion-bearer": "Благовірний князь, страстотерпець",
    "Right-believing Princess (Nun)": "Благовірна княгиня (черниця)",
    "Right-believing Princess, Martyr": "Благовірна княгиня, мучениця",
    "Righteous (Child)": "Праведний (отрок)",
    "Righteous (Children)": "Праведні (отроки)",
    "Righteous (Unmercenary)": "Праведний (безсрібник)",
    "Righteous Forefather": "Праведний праотець",
    "Righteous Virgin": "Праведна діва",
    "Righteous, Priest": "Праведний, ієрей",
    "Roman soldier": "Римський воїн",
    "Schemamonk": "Схимонах",
    "Synaxis": "Собор",
    "Tsar and Imperial Family": "Цар і Царська родина",
    "Unmercenary Martyrs": "Безсрібники-мученики",
    "Venerable": "Преподобний",
    "Venerable Prince": "Преподобний князь",
    "Venerable Princess": "Преподобна княгиня",
    "Virgin": "Діва",
    "Virgin Martyrs": "Мучениці-діви",
    "Virgin-martyr": "Мучениця-діва",
    "Youths": "Отроки",
})


# The places, which are not a list but a grammar: a card names a town, a
# province and a country in one line, and the same town appears on twenty
# other cards inside a different line. The pieces are rendered once here and
# the wholes are assembled from them, so a town cannot be spelled one way on
# one card and another way on the next.
PARTS = {}


def expand(phrases):
    """The compounds, assembled from the parts above.

    Only the place line is built here - a town and a province and a country
    set down in one line. The title a card hangs on a name is not built,
    because Ukrainian does not form it with a preposition the way Romanian
    forms it with din: "of Ancyra" is Анкірський, an adjective agreeing with
    the saint, and "of the Kyiv Caves" is Києво-Печерський. Those are
    written out in TEXT, as Russian writes them, since no rule assembles
    them from the name of the town.
    """
    out = {}
    for p in phrases:
        bits = p.split(", ")
        if all(b in PARTS for b in bits):
            out[p] = ", ".join(PARTS[b] for b in bits)
    return out


# The places, first part.
PARTS.update({
    "Abel-meholah": "Авел-Мехола",
    "Abkhazeti": "Абхазеті",
    "Achaia": "Ахая",
    "Adamovka": "Адамовка",
    "Adrianople": "Адріанополь",
    "Adrianopolis": "Адріанополь",
    "Aegae": "Егі",
    "Aegean": "Егейські острови",
    "Aegina": "Егіна",
    "Aetolia": "Етолія",
    "Africa": "Африка",
    "Agrigentum": "Агрігент",
    "Akhaltsikhe": "Ахалцихе",
    "Aksum": "Аксум",
    "Alaska": "Аляска",
    "Albania": "Албанія",
    "Albanopolis": "Албанополь",
    "Aleppo": "Алеппо",
    "Alexandria": "Олександрія",
    "All America": "Вся Америка",
    "Amasea": "Амасія",
    "Amasia": "Амасія",
    "Amastridea": "Амастрида",
    "Amastris": "Амастрида",
    "Amathus": "Амафунт",
    "America": "Америка",
    "Amida": "Аміда",
    "Amisos": "Аміс",
    "Amisus": "Аміс",
    "Amnia": "Амнія",
    "Amorion": "Аморій",
    "Amphipolis": "Амфіполь",
    "Anaplus": "Анапл",
    "Anastasiopolis": "Анастасіополь",
    "Anathoth": "Анафоф",
    "Anatolia": "Анатолія",
    "Anazarbus": "Аназарв",
    "Ancyra": "Анкіра",
    "Andronikov Monastery": "Андроників монастир",
    "Anga": "Анга",
    "Annesi": "Аннісі",
    "Annisa": "Анніса",
    "Antinoe": "Антиноя",
    "Antioch": "Антіохія",
    "Antioch in Pisidia": "Антіохія Пісидійська",
    "Antioch of Pisidia": "Антіохія Пісидійська",
    "Anzersk": "Анзерський",
    "Anzersk Island": "Анзерський острів",
    "Apamea": "Апамея",
    "Aphrodisias": "Афродисіада",
    "Apollonia": "Аполлонія",
    "Apulia": "Апулія",
    "Aquileia": "Аквілея",
    "Arabia": "Аравія",
    "Arabian Desert": "Аравійська пустеля",
    "Arauraka": "Араурака",
    "Arbela": "Арбела",
    "Archangel Gabriel": "Архангел Гавриїл",
    "Arethusa": "Аретуса",
    "Argos": "Аргос",
})


# The places, second part.
PARTS.update({
    "Arianzus": "Аріанз",
    "Arkhangelsk": "Архангельськ",
    "Arkhangelsk lands": "Архангельські землі",
    "Armagh": "Арма",
    "Armenia": "Вірменія",
    "Armenia Minor": "Мала Вірменія",
    "Arsinoe": "Арсиноя",
    "Arta": "Арта",
    "Artanuji": "Артануджі",
    "Ascalon": "Аскалон",
    "Asia Minor": "Мала Азія",
    "Asikha": "Асіха",
    "Athens": "Афіни",
    "Atka Island": "острів Атка",
    "Atskuri": "Ацкурі",
    "Atsquri": "Ацкурі",
    "Attica": "Аттика",
    "Auleneia": "Авленія",
    "Auxerre": "Осер",
    "Avnezh": "Авнеж",
    "Babylon": "Вавилон",
    "Balkans": "Балкани",
    "Barcelona": "Барселона",
    "Bari": "Барі",
    "Basarbov": "Басарбово",
    "Beauvais": "Бове",
    "Beirut": "Бейрут",
    "Belarus": "Білорусь",
    "Belev": "Бельов",
    "Belgorod": "Бєлгород",
    "Belgorod (Akkerman)": "Білгород (Аккерман)",
    "Belgrade": "Белград",
    "Belozersk": "Білозерськ",
    "Belozersk lands": "Білозерські землі",
    "Belozersk lands and Mozhaisk": "Білозерські землі і Можайськ",
    "Benevento": "Беневент",
    "Beocin Monastery": "Беочинський монастир",
    "Berezan": "Березань",
    "Berezniko": "Березник",
    "Beroea": "Верія",
    "Besanduc": "Весандук",
    "Bethany": "Віфанія",
    "Bethel": "Вефіль",
    "Bethlapeta": "Віфлапета",
    "Bethlehem": "Вифлеєм",
    "Bethsaida": "Віфсаїда",
    "Bethsaloe": "Віфсалоє",
    "Bezhetsk lands": "Бежецькі землі",
    "Bialystok": "Білосток",
    "Bisericani Monastery": "Бісериканський монастир",
    "Bithynia": "Віфінія",
    "Blachernae": "Влахерни",
    "Black Lake": "Чорне озеро",
    "Black Sea coast": "Чорноморське узбережжя",
    "Bodbe": "Бодбе",
    "Boeotia": "Беотія",
    "Bogolyubovo": "Боголюбово",
    "Bohemia": "Богемія",
    "Bolgar": "Болгар",
    "Borovichi": "Боровичі",
    "Borovsk": "Боровськ",
    "Bosnia": "Боснія",
    "Boston": "Бостон",
    "Bostra": "Востра",
    "Braunton": "Браунтон",
    "Brest": "Берестя",
    "Briansk": "Брянськ",
    "Britain": "Британія",
    "British Isles": "Британські острови",
    "Brooklyn": "Бруклін",
    "Bryansk": "Брянськ",
    "Bucharest": "Бухарест",
    "Budimlje": "Будимля",
    "Bulgaria": "Болгарія",
    "Butovo": "Бутово",
    "Buzau Mountains": "Бузеуські гори",
    "Byblos": "Бібл",
    "Byzantine Empire": "Візантійська імперія",
    "Byzantium": "Візантій",
    "Byzantium (Constantinople)": "Візантій (Константинополь)",
})


# The places, third part.
PARTS.update({
    "Caesarea": "Кесарія",
    "Caesarea Maritima": "Кесарія Приморська",
    "Caesarea in Cappadocia": "Кесарія Каппадокійська",
    "California": "Каліфорнія",
    "Campania": "Кампанія",
    "Cana": "Кана",
    "Cana of Galilee": "Кана Галілейська",
    "Canaan": "Ханаан",
    "Canopus": "Каноп",
    "Capernaum": "Капернаум",
    "Cappadocia": "Каппадокія",
    "Caria": "Карія",
    "Carpathian Rus'": "Карпатська Русь",
    "Carpatho-Russia": "Карпатська Русь",
    "Carthage": "Карфаген",
    "Catania": "Катанія",
    "Cephalonia": "Кефалонія",
    "Cernica": "Черніка",
    "Cernica Monastery": "Чернікський монастир",
    "Chalcedon": "Халкидон",
    "Chalcis": "Халкіда",
    "Chalcis desert": "Халкідська пустеля",
    "Chelm": "Холм",
    "Chelma Hill": "Чельмська гора",
    "Cherepovets": "Череповець",
    "Chernigov": "Чернігів",
    "Chernigov lands": "Чернігівські землі",
    "Chernihiv": "Чернігів",
    "Chernihiv lands": "Чернігівські землі",
    "Cherson": "Херсон",
    "Chersonesus": "Херсонес",
    "Chicago": "Чикаго",
    "China": "Китай",
    "Chios": "Хіос",
    "Chonae": "Хони",
    "Choziba": "Хозива",
    "Chukhloma": "Чухлома",
    "Cilicia": "Кілікія",
    "Claudiopolis": "Клавдіополь",
    "Colophon": "Колофон",
    "Colossae": "Колоси",
    "Coma": "Кома",
    "Comana": "Комани",
    "Constantia": "Констанція",
    "Constantinople": "Константинополь",
    "Cordoba": "Кордова",
    "Corfu": "Корфу",
    "Corinth": "Коринф",
    "Corsica": "Корсика",
    "Cotyaeum": "Котіей",
    "Crete": "Крит",
    "Crimea": "Крим",
    "Cucomo": "Кукомо",
    "Cucusus": "Кукуз",
    "Cyprus": "Кіпр",
    "Cyrene": "Кирена",
    "Cyrenia": "Кіренія",
    "Cyrrhus": "Кир",
    "Cyzicus": "Кізик",
    "Czech Lands": "Чеські землі",
    "Dabuda": "Дабуда",
    "Dalmatia": "Далмація",
    "Dalmatian Monastery": "Далматський монастир",
    "Damascus": "Дамаск",
    "Danube lands": "Подунав'я",
    "David Gareji": "Давид-Гареджі",
    "Davit-Gareji": "Давид-Гареджі",
    "Decapolis": "Декаполь",
    "Decapolis of Isauria": "Ісаврійський Декаполь",
    "Demetsana": "Димицана",
    "Demitsana": "Димицана",
    "Desert beyond the Jordan": "Пустеля за Йорданом",
    "Devich": "Девич",
    "Devon": "Девон",
    "Dimitsana": "Димицана",
    "Dioclea": "Діоклея",
    "Dioclea (Duklja)": "Діоклея (Дукля)",
    "Disevi": "Дісеві",
    "Diveyevo": "Дівеєво",
    "Dobrogea": "Добруджа",
})


# The places, fourth part.
PARTS.update({
    "Dorostolum": "Доростол",
    "Dorostolum (Silistra)": "Доростол (Сілістра)",
    "Drenica": "Дреница",
    "Durostorum": "Доростол",
    "Dymsk": "Димськ",
    "Dymskoe Lake": "Димське озеро",
    "East Anglia": "Східна Англія",
    "Edessa": "Едеса",
    "Edra": "Едра",
    "Egypt": "Єгипет",
    "Egyptian Desert": "Єгипетська пустеля",
    "Elbasan": "Ельбасан",
    "Eleutheropolis": "Елевферополь",
    "Elkosh": "Елкош",
    "Emesa": "Емеса",
    "England": "Англія",
    "Ephesus": "Ефес",
    "Epirus": "Епір",
    "Epivato": "Епіват",
    "Essex": "Ессекс",
    "Ethiopia": "Ефіопія",
    "Euboea": "Евбея",
    "Euchaita": "Євхаїти",
    "Euroea": "Евроя",
    "European Russia": "Європейська Росія",
    "Evia": "Евбея",
    "Ferapontov": "Ферапонтів",
    "Ferapontov Monastery": "Ферапонтів монастир",
    "Ferapontovo": "Ферапонтово",
    "Feremane": "Феремане",
    "Ferentino": "Ферентино",
    "Flavia Neapolis": "Флавія Неаполь",
    "Florishchi": "Флорищі",
    "Formia": "Формія",
    "France": "Франція",
    "Frasinei": "Фресіней",
    "Galata": "Галата",
    "Galatia": "Галатія",
    "Galich": "Галич",
    "Galicia": "Галичина",
    "Galilee": "Галілея",
    "Gangra": "Гангра",
    "Gareji": "Гареджі",
    "Gary": "Гері",
    "Gath-hepher": "Гафхефер",
    "Gaul": "Галлія",
    "Gaza": "Газа",
    "Gdov": "Гдов",
    "Gdov lands": "Гдовські землі",
    "George Hill": "Георгієва гора",
    "Georgia": "Грузія",
    "Germany": "Німеччина",
    "Gibeah of Phinehas": "Гіва Фінеєсова",
    "Gilead": "Галаад",
    "Glendalough": "Глендалох",
    "Glushitsa": "Глушиця",
    "Gori district": "Горійський повіт",
    "Gortyna": "Гортина",
    "Gothia": "Готія",
    "Gothic lands": "Готські землі",
    "Great Lavra": "Велика Лавра",
    "Great Lavra of Saint Sabbas": "Велика Лавра преподобного Сави",
    "Great Moravia": "Велика Моравія",
    "Greece": "Греція",
    "Guria": "Гурія",
    "Hartland": "Хартленд",
    "Hauran": "Хауран",
    "Hebron": "Хеврон",
    "Heliopolis": "Іліополь",
    "Hellas": "Еллада",
    "Hellespont": "Геллеспонт",
    "Heraclea": "Іраклія",
    "Hereti": "Ереті",
    "Hermopolis": "Ермополь",
    "Herzegovina": "Герцеговина",
    "Hierapolis": "Ієраполь",
    "Hilandar": "Хіландар",
    "Holy Land": "Свята Земля",
    "Holy Trinity-Saint Sergius Lavra": "Свято-Троїцька Сергієва Лавра",
    "Hosios Loukas": "Осіос-Лукас",
})


# The places, fifth part.
PARTS.update({
    "Hungary": "Угорщина",
    "Hypaepa": "Іпепа",
    "Iași": "Ясси",
    "Iconium": "Іконій",
    "Iken": "Айкен",
    "Illinois": "Іллінойс",
    "Illyria": "Іллірія",
    "Illyricum": "Іллірик",
    "India": "Індія",
    "Indiana": "Індіана",
    "Ioannina": "Яніна",
    "Irap": "Ірап",
    "Ireland": "Ірландія",
    "Irenopolis": "Іринополь",
    "Irkutsk": "Іркутськ",
    "Irkutsk province": "Іркутська губернія",
    "Isauria": "Ісаврія",
    "Israel": "Ізраїль",
    "Italy": "Італія",
    "Iza": "Іза",
    "Jackson": "Джексон",
    "Jerusalem": "Єрусалим",
    "Joppa": "Йоппія",
    "Jordan River": "річка Йордан",
    "Judah": "Юдея",
    "Judea": "Юдея",
    "Judean Desert": "Юдейська пустеля",
    "Judean Wilderness": "Юдейська пустеля",
    "Kallippi": "Калліппі",
    "Kaluga": "Калуга",
    "Kaluga lands": "Калузькі землі",
    "Kalyazin": "Калязин",
    "Kampsada": "Кампсада",
    "Kaniv": "Канів",
    "Karelia": "Карелія",
    "Kargopol": "Каргополь",
    "Kargopol lands": "Каргопольські землі",
    "Kartli": "Картлі",
    "Kartli (Iberia)": "Картлі (Іверія)",
    "Kashin": "Кашин",
    "Kasperovo": "Касперово",
    "Kastoria": "Касторія",
    "Kastorion": "Касторіон",
    "Kavsokalyvia": "Кавсокаливія",
    "Kazan": "Казань",
    "Kekhta": "Кехта",
    "Kellia": "Келії",
    "Keno Lake": "Кенозеро",
    "Kerch": "Керч",
    "Kerkyra": "Керкіра",
    "Kerkyra (Corfu)": "Керкіра (Корфу)",
    "Khakhuli": "Хахулі",
    "Khakhuli Monastery": "Хахульський монастир",
    "Kharkiv": "Харків",
    "Kherson": "Херсон",
    "Kherson lands": "Херсонські землі",
    "Khlynov": "Хлинов",
    "Kholm": "Холм",
    "Khust": "Хуст",
    "Khutyn": "Хутинь",
    "Kios": "Кій",
    "Klarjeti": "Кларджеті",
    "Klops Monastery": "Клопський монастир",
    "Kodiak": "Кадьяк",
    "Kola": "Кола",
    "Komel": "Комель",
    "Komel Forest": "Комельський ліс",
    "Kondakovo": "Кондаково",
    "Konevets": "Коневець",
    "Korets": "Корець",
    "Korissos": "Коріссос",
    "Kornet": "Корнет",
    "Korotsk": "Короцько",
    "Kosinsk": "Косинське",
    "Kosovo": "Косово",
    "Kostroma": "Кострома",
    "Kostroma lands": "Костромські землі",
    "Kozelshchyna": "Козельщина",
    "Kozelsk": "Козельськ",
    "Kozhe Lake": "Кожозеро",
    "Krasny Kholm": "Красний Холм",
    "Kratovo": "Кратово",
    "Kremenets": "Кременець",
    "Kromna": "Кромна",
    "Kronstadt": "Кронштадт",
})


# The places, sixth part.
PARTS.update({
    "Krushedol": "Крушедол",
    "Kubensk": "Кубенське",
    "Kudinovo": "Кудиново",
    "Kursk": "Курськ",
    "Kushta": "Кушта",
    "Kvabtakhevi Monastery": "Квабтахевський монастир",
    "Kveli fortress": "фортеця Квелі",
    "Kwethluk": "Кветлук",
    "Kyiv": "Київ",
    "Kyiv Caves": "Київські печери",
    "Kyiv Caves Lavra": "Києво-Печерська Лавра",
    "Kyiv Far Caves": "Київські Дальні печери",
    "Kyiv Near Caves": "Київські Ближні печери",
    "Kyiv region": "Київська земля",
    "Laconia": "Лаконія",
    "Lake Iliamna": "озеро Іліамна",
    "Lake Ilmen": "озеро Ільмень",
    "Lake Ilo": "Ілоозеро",
    "Lake Kubenskoye": "Кубенське озеро",
    "Lake Ladoga": "Ладозьке озеро",
    "Lake Onega": "Онезьке озеро",
    "Lake Orta": "озеро Орта",
    "Lake Pskov": "Псковське озеро",
    "Lake Seliger": "озеро Селігер",
    "Lake Vorbozomsk": "Ворбозомське озеро",
    "Lampsacus": "Лампсак",
    "Land of Asher": "земля Асирова",
    "Land of Uz": "земля Уц",
    "Land of Zebulun": "земля Завулонова",
    "Land of the tribe of Simeon": "земля коліна Симеонового",
    "Langres": "Лангр",
    "Laodicea": "Лаодикія",
    "Lavra of Saint Sabbas": "Лавра преподобного Сави",
    "Lazica": "Лазика",
    "Le Mans": "Ле-Ман",
    "Lebanon": "Ліван",
    "Leinster": "Ленстер",
    "Lelich": "Лелич",
    "Lentini": "Лентіні",
    "Leokhnovo": "Леохново",
    "Leontini": "Леонтини",
    "Lesbos": "Лесбос",
    "Leucosia (Nicosia)": "Левкосія (Нікосія)",
    "Lezna River": "річка Лезна",
    "Libertyville": "Лібертивілль",
    "Libya": "Лівія",
    "Lindisfarne": "Ліндісфарн",
    "Lipari": "Ліпарі",
    "Lithuania": "Литва",
    "Little Russia (Ukraine)": "Мала Русь (Україна)",
    "Liubech": "Любеч",
    "Liubimograd": "Любимоград",
    "Loma": "Лома",
    "Loutraki": "Лутракі",
    "Lubny": "Лубни",
    "Lubyatov": "Любятово",
    "Lucania": "Луканія",
    "Lukhov": "Лухов",
    "Lycaonia": "Лікаонія",
    "Lycia": "Лікія",
    "Lycopolis": "Лікополь",
    "Lydda": "Лідда",
    "Lydia": "Лідія",
    "Lykaonia": "Лікаонія",
    "Lyons": "Ліон",
    "Lystra": "Лістра",
    "Lérins": "Лерин",
    "Macedonia": "Македонія",
    "Magdala": "Магдала",
    "Magedon": "Магедон",
    "Magnesia": "Магнесія",
    "Magydos": "Магідос",
    "Maiuma": "Маіума",
    "Makarovo": "Макарово",
    "Makhrishche": "Махрище",
    "Malopinega": "Малопинежжя",
    "Malta": "Мальта",
    "Mandera": "Мандера",
    "Mangup": "Мангуп",
    "Mantinea": "Мантинея",
    "Mar Saba": "Мар-Саба",
    "Maratha": "Марафа",
    "Marathon": "Марафон",
    "Marcianopolis": "Марціанополь",
    "Marikat": "Марикат",
})


# The places, seventh part.
PARTS.update({
    "Marseilles": "Марсель",
    "Martyropolis": "Мартирополь",
    "Mauretania": "Мавританія",
    "Medikion": "Мідикій",
    "Medikion Monastery": "Мідикійський монастир",
    "Medin": "Мединь",
    "Mega Dendron": "Мега-Дендрон",
    "Meglin": "Меглин",
    "Melitene": "Мелітина",
    "Melitopolis": "Мелітополь",
    "Menuthis": "Менуфіс",
    "Menyusha": "Менюша",
    "Merkushino": "Меркушино",
    "Mesopotamia": "Месопотамія",
    "Mesteacăn": "Местякен",
    "Methymna": "Міфимна",
    "Mezen": "Мезень",
    "Mgvime": "Мгвіме",
    "Milan": "Медіолан",
    "Mineo": "Мінео",
    "Minneapolis": "Міннеаполіс",
    "Moesia": "Мезія",
    "Mogarissos": "Могарисс",
    "Mogilev": "Могильов",
    "Moldavia": "Молдавія",
    "Moldova": "Молдова",
    "Monembasia": "Монемвасія",
    "Monte Cassino": "Монтекассіно",
    "Monteluco": "Монтелуко",
    "Montenegro": "Чорногорія",
    "Monza River": "річка Монза",
    "Moravia": "Моравія",
    "Morea (Peloponnese)": "Морея (Пелопоннес)",
    "Moresheth": "Морасфа",
    "Moscow": "Москва",
    "Moscow lands": "Московські землі",
    "Mount Athos": "Афон",
    "Mount Colzim": "гора Колзім",
    "Mount Ephraim": "гора Єфремова",
    "Mount Galesion": "гора Галісій",
    "Mount Galesius": "гора Галісій",
    "Mount Hor": "гора Ор",
    "Mount Kyminas": "гора Кимин",
    "Mount Maleon": "гора Малеон",
    "Mount Myrsinon": "гора Мірсінон",
    "Mount Nebo": "гора Нево",
    "Mount Olympus": "гора Олімп",
    "Mount Sagmata": "гора Сагмата",
    "Mount Sinai": "гора Синай",
    "Mount Skopa": "гора Скопа",
    "Mount Taurus": "Таврські гори",
    "Mount of Olives": "Єлеонська гора",
    "Mozhaisk": "Можайськ",
    "Mrkonjici": "Мрконьїчі",
    "Mtskheta": "Мцхета",
    "Murom": "Муром",
    "Murom Island": "Муромський острів",
    "Mutalaska": "Муталаска",
    "Mylapore": "Мілапур",
    "Mylasa": "Міласа",
    "Myra": "Мири",
    "Myra in Lycia": "Мири Лікійські",
    "Myrgorod": "Миргород",
    "Mytilene": "Мітилина",
    "Naissus": "Наісс",
    "Najran": "Наджран",
    "Nalšia": "Нальшя",
    "Nanterre": "Нантер",
    "Naples": "Неаполь",
    "Nauplion": "Навпліон",
    "Nazareth": "Назарет",
    "Nazianzus": "Назіанз",
    "Nea Makri": "Неа-Макрі",
    "Neamts Monastery": "Нямецький монастир",
    "Neamț": "Нямц",
    "Neapolis": "Неаполь",
    "Near Constantinople": "Поблизу Константинополя",
    "Neocaesarea": "Неокесарія",
    "Nerchinsk": "Нерчинськ",
    "New Lake": "Новоозеро",
    "New York": "Нью-Йорк",
    "Nicaea": "Нікея",
    "Nicea": "Нікея",
    "Nicomedia": "Нікомидія",
    "Nicopolis": "Нікополь",
})


# The places, eighth part.
PARTS.update({
    "Nicosia": "Нікосія",
    "Nikiforovskaya": "Никифорівська",
    "Nisibis": "Нізібія",
    "Nitria": "Нітрія",
    "Nizhni-Novgorod": "Нижній Новгород",
    "Nizhny Novgorod": "Нижній Новгород",
    "Nizhny Novgorod lands": "Нижегородські землі",
    "Nizhyn": "Ніжин",
    "North Africa": "Північна Африка",
    "North America": "Північна Америка",
    "North Macedonia": "Північна Македонія",
    "Northumbria": "Нортумбрія",
    "Novara": "Новара",
    "Novgorod": "Новгород",
    "Novgorod lands": "Новгородські землі",
    "Noviodunum": "Новіодун",
    "Novoezersk": "Новоезерськ",
    "Nurma": "Нурма",
    "Nursia": "Нурсія",
    "Nyssa": "Нісса",
    "Obnora River": "річка Обнора",
    "Odessa": "Одеса",
    "Odrino": "Одрино",
    "Ohrid": "Охрид",
    "Old Lavra of Chariton": "Давня Лавра преподобного Харитона",
    "Olonets": "Олонець",
    "Olonets lands": "Олонецькі землі",
    "Olshansk": "Ольшанськ",
    "Olympus": "Олімп",
    "Omala": "Омала",
    "Ondrusov": "Ондрусов",
    "Ophrah": "Офра",
    "Opso": "Опсо",
    "Orel lands": "Орловські землі",
    "Oshevensk": "Ошевенськ",
    "Osrhoene": "Осроена",
    "Ostia": "Остія",
    "Ostracine": "Острацина",
    "Ostrog": "Острог",
    "Ovche Pole": "Овче-Поле",
    "Ovruch": "Овруч",
    "Ozovia": "Озовія",
    "Palermo": "Палермо",
    "Palestine": "Палестина",
    "Palii Island": "Палій острів",
    "Pamphylia": "Памфілія",
    "Pannonia": "Паннонія",
    "Paphlagonia": "Пафлагонія",
    "Paphos": "Пафос",
    "Paramythia": "Парамифія",
    "Paris": "Париж",
    "Parium": "Парій",
    "Paros": "Парос",
    "Parthia": "Парфія",
    "Patara": "Патара",
    "Patmos": "Патмос",
    "Patras": "Патри",
    "Pec": "Печ",
    "Pechenga": "Печенга",
    "Pechenga Monastery": "Печенгський монастир",
    "Pekhorka": "Пехорка",
    "Pelecete": "Пелекета",
    "Pelekete": "Пелекета",
    "Pelekete Monastery": "Пелекетський монастир",
    "Peloponnese": "Пелопоннес",
    "Pelshma": "Пельшма",
    "Pelusium": "Пелусій",
    "Pennsylvania": "Пенсильванія",
    "Perekop (Perekomsky) Monastery": "Перекопський (Перекомський) монастир",
    "Pereslavl": "Переславль",
    "Pereslavl-Zalessky": "Переславль-Залеський",
    "Pereyaslavl": "Переяславль",
    "Pereyaslavl-Zalessky": "Переславль-Залеський",
    "Pergamum": "Пергам",
    "Perge": "Пергія",
    "Peristerai": "Перистери",
    "Perm": "Перм",
    "Perm lands": "Пермські землі",
    "Persia": "Персія",
    "Persia and the East": "Персія і Схід",
    "Peshnosha": "Пешноша",
    "Petrograd": "Петроград",
    "Peć": "Печ",
    "Pharan": "Фаран",
    "Pharasa": "Фараса",
})


# The places, ninth part.
PARTS.update({
    "Philadelphia": "Філадельфія",
    "Philippopolis": "Філіппополь",
    "Philotheou Monastery": "Філофеївський монастир",
    "Phocis": "Фокида",
    "Phoenicia": "Фінікія",
    "Phrygia": "Фригія",
    "Pinega": "Пінега",
    "Pinsk": "Пінськ",
    "Pisidia": "Пісидія",
    "Plousias": "Плусіада",
    "Pochaev": "Почаїв",
    "Pochaiv": "Почаїв",
    "Podolia": "Поділля",
    "Poiana Marului": "Пояна-Мерулуй",
    "Pokutia": "Покуття",
    "Poland": "Польща",
    "Polotsk": "Полоцьк",
    "Poltava": "Полтава",
    "Poltava lands": "Полтавські землі",
    "Poltava region": "Полтавська земля",
    "Polybotum": "Поліботи",
    "Pomorie": "Помор'я",
    "Pompeiopolis": "Помпейополь",
    "Pontus": "Понт",
    "Popovo": "Попово",
    "Porkhov": "Порхов",
    "Poshekhonye": "Пошехоння",
    "Pozzuoli": "Поццуолі",
    "Prague": "Прага",
    "Pretorium": "Преторій",
    "Priluki": "Прилуки",
    "Prokopion": "Прокопіон",
    "Protection Convent": "Покровський монастир",
    "Prusa": "Пруса",
    "Pryluky": "Прилуки",
    "Prymnessus": "Примнесс",
    "Pshinja": "Пшиня",
    "Pskov": "Псков",
    "Pskov Caves Monastery": "Псково-Печерський монастир",
    "Ptinapor": "Птинапор",
    "Ptolemais": "Птолемаїда",
    "Puteoli": "Путеоли",
    "Putna": "Путна",
    "Pythias": "Піфія",
    "Périgueux": "Перигьо",
    "Radonezh": "Радонеж",
    "Radonezh and Serpukhov": "Радонеж і Серпухов",
    "Radoviste": "Радовиште",
    "Raithu": "Раїфа",
    "Ramah": "Рама",
    "Ramathaim": "Рамафаїм",
    "Ramathaim-Zophim": "Рамафаїм-Цофим",
    "Ramnic": "Римник",
    "Ravanica": "Раваниця",
    "Ravenna": "Равенна",
    "Resafa": "Ресафа",
    "Rethymnon": "Ретимнон",
    "Rhosus": "Росс",
    "Rila": "Рила",
    "Robeika": "Робейка",
    "Robeika River": "річка Робейка",
    "Roman Britain": "Римська Британія",
    "Romania": "Румунія",
    "Rome": "Рим",
    "Rome and Milan": "Рим і Медіолан",
    "Rome and the East": "Рим і Схід",
    "Rossos": "Росс",
    "Rostov": "Ростов",
    "Rostov lands": "Ростовські землі",
    "Rus'": "Русь",
    "Russia": "Росія",
    "Russian North": "Руська Північ",
    "Russian nobility": "руське боярство",
    "Ryazan": "Рязань",
    "Ryazan province": "Рязанська губернія",
    "Rzhev": "Ржев",
    "Saint John": "Святий Іоан",
    "Saint Petersburg": "Санкт-Петербург",
    "Salamis": "Саламін",
    "Salamis (Constantia)": "Саламін (Констанція)",
    "Salona": "Салона",
    "Samaria": "Самарія",
    "Samegrelo": "Самегрело",
    "Samosata": "Самосати",
    "Samothrace": "Самофракія",
})


# The places, tenth part.
PARTS.update({
    "Samtskhe": "Самцхе",
    "San Francisco": "Сан-Франциско",
    "Saragossa": "Сарагоса",
    "Sardis": "Сарди",
    "Sarov": "Саров",
    "Scetis": "Скит",
    "Scotland": "Шотландія",
    "Scythia": "Скіфія",
    "Scythia Minor": "Мала Скіфія",
    "Sebaste": "Севастія",
    "Sebastea": "Севастія",
    "Sebino": "Себіно",
    "Seleucia": "Селевкія",
    "Seleucia-Ctesiphon": "Селевкія-Ктесифон",
    "Selymbria": "Селімврія",
    "Serbia": "Сербія",
    "Sergiev Posad": "Сергіїв Посад",
    "Serpukhov": "Серпухов",
    "Serres": "Серри",
    "Shanghai": "Шанхай",
    "Shenkursk": "Шенкурськ",
    "Shiloh": "Силом",
    "Shio-Mgvime Monastery": "Шіомгвімський монастир",
    "Shovskoe": "Шовське",
    "Shuya": "Шуя",
    "Shuzhgora": "Шужгора",
    "Siberia": "Сибір",
    "Siblag camps": "Сиблаг",
    "Sicily": "Сицилія",
    "Side": "Сіда",
    "Sigriane": "Сигріана",
    "Silistra": "Сілістра",
    "Simferopol": "Сімферополь",
    "Sinai": "Синай",
    "Sinai and Raithu": "Синай і Раїфа",
    "Sinai wilderness": "Синайська пустеля",
    "Singidunum": "Сингідун",
    "Sinope": "Синоп",
    "Sinope and Amasea": "Синоп і Амасія",
    "Sinozersk": "Синозерськ",
    "Sirmium": "Сирмій",
    "Sisan": "Сісан",
    "Sitka": "Ситка",
    "Siya Monastery": "Сійський монастир",
    "Skepsis": "Скепсія",
    "Sketis": "Скит",
    "Skrino": "Скрино",
    "Slutsk": "Слуцьк",
    "Smolensk": "Смоленськ",
    "Smyrna": "Смирна",
    "Snetogorsk": "Снетогорський",
    "Snetogorsk Monastery": "Снетогорський монастир",
    "Sofia": "Софія",
    "Sokhot River": "річка Сохоть",
    "Solovki": "Соловки",
    "Solovki Islands": "Соловецькі острови",
    "Solovki Monastery": "Соловецький монастир",
    "Sophene": "Софена",
    "Sora River": "річка Сора",
    "Soreoi": "Сореї",
    "Spain": "Іспанія",
    "Spoleto": "Сполето",
    "Spruce Island": "Ялиновий острів",
    "Srem": "Срем",
    "St Albans": "Сент-Олбанс",
    "St. Petersburg": "Санкт-Петербург",
    "Stara Zagora": "Стара-Загора",
    "Staritsa": "Стариця",
    "Starytsa": "Стариця",
    "Steirion": "Стирій",
    "Stolobny Island": "острів Столобний",
    "Storozhi Hill": "гора Сторожі",
    "Strobil": "Стровил",
    "Strumica": "Струмиця",
    "Studenica": "Студениця",
    "Subiaco": "Субіако",
    "Suceava": "Сучава",
    "Sura": "Сура",
    "Susa": "Сузи",
    "Suzdal": "Суздаль",
    "Svensky Monastery": "Свенський монастир",
    "Svir": "Свір",
    "Sviyazhsk": "Свіяжськ",
    "Sweden": "Швеція",
    "Syandeba": "Сяндеба",
})


# The places, eleventh part.
PARTS.update({
    "Syandemsk": "Сяндемськ",
    "Syanzhema": "Сянжема",
    "Syanzhema River": "річка Сянжема",
    "Sykeon": "Сікеон",
    "Symbola": "Символи",
    "Symbola Monastery": "монастир Символів",
    "Synnada": "Синнади",
    "Syracuse": "Сиракузи",
    "Syria": "Сирія",
    "Tabatha": "Тавафа",
    "Tabenna": "Тавенна",
    "Tabennisi": "Тавенниси",
    "Tambov": "Тамбов",
    "Tao": "Тао",
    "Tao-Klarjeti": "Тао-Кларджеті",
    "Taormina": "Таорміна",
    "Taphanes": "Тафніс",
    "Targala": "Таргала",
    "Tarnovo": "Тирново",
    "Tarsus": "Тарс",
    "Tarsus and Achaia": "Тарс і Ахая",
    "Tarsus and Rossos": "Тарс і Росс",
    "Tarsus and the East": "Тарс і Схід",
    "Tashkent": "Ташкент",
    "Tauresium": "Тавресій",
    "Tazlău": "Тазлеу",
    "Tazlău Monastery": "Тазлеуський монастир",
    "Tbilisi": "Тбілісі",
    "Tekoa": "Фекоя",
    "Tenedos": "Тенедос",
    "Tennis": "Тенніс",
    "Teratyn": "Тератин",
    "Terracina": "Террачина",
    "The East": "Схід",
    "The Jordan": "Йордан",
    "Thebaid": "Фіваїда",
    "Thebes": "Фіви",
    "Thebes of Egypt": "Фіви Єгипетські",
    "Thessalonica": "Солунь",
    "Thessaloniki": "Солунь",
    "Thessaly": "Фессалія",
    "Thrace": "Фракія",
    "Thyateira": "Фіатира",
    "Tikhvin": "Тихвин",
    "Tiksna": "Тіксна",
    "Tishbe of Gilead": "Фесва Галаадська",
    "Tmutarakan": "Тмутаракань",
    "Tobolsk": "Тобольськ",
    "Tolva": "Толва",
    "Toropets": "Торопець",
    "Torzhok": "Торжок",
    "Totma": "Тотьма",
    "Trajanopolis": "Траянополь",
    "Tralles": "Тралли",
    "Transcarpathia": "Закарпаття",
    "Trebia": "Требія",
    "Trebizond": "Трапезунд",
    "Tremithus": "Тримифунт",
    "Trier": "Трір",
    "Triglia": "Триглія",
    "Trikala": "Трикала",
    "Trinity Lavra": "Троїцька Лавра",
    "Trinity-Sergius Lavra": "Троїце-Сергієва Лавра",
    "Tripoli": "Триполі",
    "Troas": "Троада",
    "Tsarskoye Selo": "Царське Село",
    "Tula lands": "Тульські землі",
    "Turchasovo": "Турчасово",
    "Turov": "Туров",
    "Tuscany": "Тоскана",
    "Tver": "Твер",
    "Tver lands": "Тверські землі",
    "Tyana": "Тіана",
    "Tyre": "Тир",
    "Uchma": "Учма",
    "Uglich": "Углич",
    "Ukraine": "Україна",
    "United States": "Сполучені Штати",
    "Unzha": "Унжа",
    "Upper Thebaid": "Верхня Фіваїда",
    "Ur of the Chaldees": "Ур Халдейський",
    "Ushchelye": "Ущелля",
    "Ust-Totma": "Усть-Тотьма",
    "Ust-Vym": "Усть-Вим",
    "Ustiug": "Устюг",
    "Ustyug": "Устюг",
    "Vaga": "Вага",
    "Vaga lands": "Важські землі",
    "Vagharshapat": "Вагаршапат",
    "Valaam": "Валаам",
})


# The places, twelfth part.
PARTS.update({
    "Valencia": "Валенсія",
    "Varnitsa": "Варниці",
    "Varzuga": "Варзуга",
    "Vasilevo": "Василево",
    "Vaste": "Васте",
    "Vasyliv": "Василів",
    "Vazheozero region": "Важеозерський край",
    "Velehrad": "Велеград",
    "Veliki Luki": "Великі Луки",
    "Veliky Ustiug": "Великий Устюг",
    "Veliky Ustyug": "Великий Устюг",
    "Venice": "Венеція",
    "Verkhoturye": "Верхотур'я",
    "Verkola": "Веркола",
    "Verona": "Верона",
    "Verulamium": "Веруламій",
    "Verulamium (St Albans)": "Веруламій (Сент-Олбанс)",
    "Vetluga": "Ветлуга",
    "Videlebye": "Виделеб'є",
    "Vilnius": "Вільнюс",
    "Vishera": "Вишера",
    "Vladimir": "Володимир",
    "Vladimir lands": "Володимирські землі",
    "Vladimir-Suzdal": "Володимиро-Суздальська земля",
    "Vladimir-in-Volhynia": "Володимир-Волинський",
    "Volga Bulgaria": "Волзька Булгарія",
    "Volhynia": "Волинь",
    "Volissos": "Воліссос",
    "Volodymyr-Volhynia": "Володимир-Волинський",
    "Vologda": "Вологда",
    "Vologda lands": "Вологодські землі",
    "Volokolamsk": "Волоколамськ",
    "Vorbozomsk Lake": "Ворбозомське озеро",
    "Voronezh": "Воронеж",
    "Vracar": "Врачар",
    "Vyatka": "В'ятка",
    "Vyazma": "Вязьма",
    "Vyritsa": "Вириця",
    "Vyshgorod": "Вишгород",
    "Vyshhorod": "Вишгород",
    "Wales": "Уельс",
    "Warsaw": "Варшава",
    "Western Rus": "Західна Русь",
    "White Lake": "Біле озеро",
    "White Lake (Beloozero)": "Біле озеро (Білоозеро)",
    "White Lake region": "Білозерський край",
    "White Sea": "Біле море",
    "Wilkes-Barre": "Уїлкс-Барре",
    "Wonderful Mountain": "Дивна гора",
    "Yakhroma": "Яхрома",
    "Yarenga": "Яренга",
    "Yaroslavl": "Ярославль",
    "Yaroslavl lands": "Ярославські землі",
    "Yaroslavl province": "Ярославська губернія",
    "Yashezero": "Яшезеро",
    "Yazvishche": "Язвище",
    "Yekaterinburg": "Єкатеринбург",
    "Yuriev (Tartu)": "Юр'їв (Тарту)",
    "Yuriev Monastery": "Юр'їв монастир",
    "Yuriev-Polsky": "Юр'їв-Польський",
    "Yuryegorsk": "Юр'єгорськ",
    "Zadonsk": "Задонськ",
    "Zahumlje": "Захум'я",
    "Zahumlje (Zakholm)": "Захум'я (Захолм'я)",
    "Zakynthos": "Закінф",
    "Zaozersk": "Заозерськ",
    "Zelenets": "Зеленець",
    "Zemplin region": "Земплинський край",
    "Zeta": "Зета",
    "Zeugma": "Зевгма",
    "Zhabyn Monastery": "Жабинський монастир",
    "Zheleznoborov": "Железноборовський",
    "Zhicha": "Жича",
    "Zhicha Monastery": "Жичський монастир",
    "Zvenigorod": "Звенигород",
    "Zverki": "Зверки",
    "all Greece": "вся Греція",
    "all Rus'": "вся Русь",
    "all Russia": "вся Росія",
    "all Slavic lands": "всі слов'янські землі",
    "all schools": "всі училища",
    "all the Slavic lands": "всі слов'янські землі",
    "and Ephesus": "і Ефес",
    "beyond the Danube": "за Дунаєм",
    "gardens and vineyards": "сади й виноградники",
    "near Agrigentum": "поблизу Агрігента",
    "near Alexandria": "поблизу Олександрії",
    "near Ancyra": "поблизу Анкіри",
    "near Antioch": "поблизу Антіохії",
    "near Apamea": "поблизу Апамеї",
    "near Bialystok": "поблизу Білостока",
    "near Borovsk": "поблизу Боровська",
    "near Cherepovets": "поблизу Череповця",
    "near Chernigov": "поблизу Чернігова",
    "near Constantinople": "поблизу Константинополя",
    "near Cyrrhus": "поблизу Кира",
    "near Dorostolum": "поблизу Доростола",
    "near Edessa": "поблизу Едеси",
    "near Ephesus": "поблизу Ефеса",
    "near Galich": "поблизу Галича",
    "near Gaza": "поблизу Гази",
    "near Kargopol": "поблизу Каргополя",
    "near Kiev": "поблизу Києва",
    "near Kyiv": "поблизу Києва",
    "near Moscow": "поблизу Москви",
    "near Mount Tabor": "поблизу гори Фавор",
    "near Mtskheta": "поблизу Мцхети",
    "near Novgorod": "поблизу Новгорода",
    "near Prusa": "поблизу Пруси",
    "near Pskov": "поблизу Пскова",
    "near Rostov": "поблизу Ростова",
    "near Samosata": "поблизу Самосат",
    "near Staraya Russa": "поблизу Старої Русси",
    "near Totma": "поблизу Тотьми",
    "near Uglich": "поблизу Углича",
    "near Verkhoturye": "поблизу Верхотур'я",
    "near Vladimir": "поблизу Володимира",
    "near Volokolamsk": "поблизу Волоколамська",
    "near the Dvina": "поблизу Двіни",
    "on the Dvina": "на Двіні",
    "on the Onega": "на Онезі",
    "the Balkans": "Балкани",
    "the Belozersk country": "Білозерський край",
    "the Bistrița valley": "долина Бистриці",
    "the Black Sea coast and the Caucasus": "Чорноморське узбережжя і Кавказ",
    "the Buzau Mountains": "Бузеуські гори",
    "the Caucasus": "Кавказ",
    "the Cells": "Келії",
    "the Cherepovets country": "Череповецький край",
    "the Danube lands": "Подунав'я",
    "the Dvina country": "Подвіння",
    "the East": "Схід",
    "the Egyptian desert": "Єгипетська пустеля",
    "the Gentile nations": "язичницькі народи",
    "the Golden Horde": "Золота Орда",
    "the Holy Land": "Свята Земля",
    "the Jordan": "Йордан",
    "the Jordan desert": "Йорданська пустеля",
    "the Judean desert": "Юдейська пустеля",
    "the Judean wilderness": "Юдейська пустеля",
    "the Kola north": "Кольська північ",
    "the Komi lands": "землі Комі",
    "the Mount of Olives": "Єлеонська гора",
    "the Obnora": "Обнора",
    "the Oka country": "Приоцький край",
    "the Olonets country": "Олонецький край",
    "the Onega country": "Онезький край",
    "the Palestinian desert": "Палестинська пустеля",
    "the Peloponnese": "Пелопоннес",
    "the Pinega country": "Пінезький край",
    "the Pskov Caves": "Псково-Печерська обитель",
    "the Pčinja valley": "долина Пчині",
    "the Russian North": "Руська Північ",
    "the Russian north": "Руська Північ",
    "the Seto lands": "землі сету",
    "the Smolensk cemetery": "Смоленський цвинтар",
    "the Sora": "Сора",
    "the Studios monastery": "Студійський монастир",
    "the Thebaid": "Фіваїда",
    "the Tikhvin country": "Тихвинський край",
    "the Urals": "Урал",
    "the Volga lands": "Поволжя",
    "the Vologda country": "Вологодський край",
    "the White Sea": "Біле море",
    "the White Sea coast": "Біломорське узбережжя",
    "the Wonderful Mountain": "Дивна гора",
    "the Yakhroma": "Яхрома",
    "the desert of Egypt": "пустеля Єгипту",
    "the inner Egyptian desert": "внутрішня Єгипетська пустеля",
    "the lands of the apostolic mission": "землі апостольської проповіді",
    "the northern Thebaid": "Північна Фіваїда",
    "the northern missions": "північні місії",
    "the whole world": "увесь світ",
    "the wilderness beyond Mesopotamia": "пустеля за Месопотамією",
    "travelers' gates": "врата подорожніх",
    "Žiča": "Жича",
})


# How else a saint is named: the place he is known by. Ukrainian would put this adjectivally - Анкірський - but the adjective agrees with the saint, and a hundred and thirty-four of those who carry a title are women while the vocabulary is a flat map with no gender in it. So the prepositional form, which is what Ukrainian uses when the bearer is not in view.
TEXT.update({
    "of Abyssinia": "з Абіссінії",
    "of Adrianopolis": "з Адріанополя",
    "of Aegae": "з Егів",
    "of Aegina": "з Егіни",
    "of Agrigentum": "з Агрігента",
    "of Akhaltsikhe": "з Ахалцихе",
    "of Alexandria": "з Олександрії",
    "of Amisos": "з Аміса",
    "of Amnia": "з Амнії",
    "of Amorion in Phrygia": "з Аморія у Фригії",
    "of Anazarbus": "з Аназарва",
    "of Ancyra": "з Анкіри",
    "of Antioch": "з Антіохії",
    "of Apollonia": "з Аполлонії",
    "of Arsinoe": "з Арсиної",
    "of Athens": "з Афін",
    "of Auxerre": "з Осера",
    "of Barcelona": "з Барселони",
    "of Belgorod": "з Бєлгорода",
    "of Belgrade": "з Белграда",
    "of Belozersk": "з Білозерська",
    "of Bialystok": "з Білостока",
    "of Bisericani": "з Бісерикан",
    "of Bithynia": "з Віфінії",
    "of Borovichi": "з Боровичів",
    "of Braunton": "з Браунтона",
    "of Brest": "з Берестя",
    "of Briansk": "з Брянська",
    "of Bulgaria": "з Болгарії",
    "of Byblos in Syria": "з Бібла в Сирії",
    "of Caesarea": "з Кесарії",
    "of Cappadocia": "з Каппадокії",
    "of Carthage": "з Карфагена",
    "of Chernihiv": "з Чернігова",
    "of Chernoezero": "з Чорноозера",
    "of Chicago and Tsarskoye Selo": "з Чикаго і Царського Села",
    "of Chios": "з Хіоса",
    "of Cilicia": "з Кілікії",
    "of Comana": "з Коман",
    "of Constantinople": "з Константинополя",
    "of Cordoba": "з Кордови",
    "of Crete": "з Криту",
    "of Cyprus": "з Кіпру",
    "of Cyrrhus": "з Кира",
    "of Cyzicus": "з Кізика",
    "of Dalmatia": "з Далмації",
    "of Damascus": "з Дамаска",
    "of David Gareji": "з Давид-Гареджі",
    "of Dionysiou": "з Діонісіату",
    "of Edessa": "з Едеси",
    "of Egypt": "з Єгипту",
    "of Emesa": "з Емеси",
    "of Ephesus": "з Ефеса",
    "of Epirus": "з Епіру",
    "of Essex": "з Ессексу",
    "of Gangra": "з Гангри",
    "of Gareji": "з Гареджі",
    "of Gaza": "з Гази",
    "of Gdov": "з Гдова",
    "of George Hill": "з Георгієвої гори",
    "of Glendalough": "з Глендалоха",
    "of Glushitsa": "з Глушиці",
    "of Gortyna": "з Гортини",
    "of Guria and Samegrelo": "з Гурії і Самегрело",
    "of Hartland": "з Хартленда",
    "of Heliopolis": "з Іліополя",
    "of Heraclea": "з Іраклії",
    "of Heraclea in Thrace": "з Іраклії Фракійської",
    "of Herapolis": "з Ієраполя",
    "of Hierapolis": "з Ієраполя",
    "of Hvosno": "з Хвосна",
    "of Iași": "з Ясс",
    "of Iconium": "з Іконія",
    "of Iken": "з Айкена",
    "of Iloezersk": "з Ілоозера",
    "of Irap": "з Ірапа",
    "of Isauria": "з Ісаврії",
    "of Jackson and San Francisco": "з Джексона і Сан-Франциско",
    "of Jerusalem": "з Єрусалима",
    "of Kaluga": "з Калуги",
    "of Kaluga or Medin": "з Калуги або Медині",
    "of Kashin": "з Кашина",
    "of Kavsokalyvia": "з Кавсокаливії",
    "of Kazan": "з Казані",
    "of Kazan and Tver": "з Казані і Твері",
    "of Keno Lake": "з Кенозера",
    "of Khutyn": "з Хутині",
    "of Komel": "з Комеля",
    "of Kosinsk": "з Косинського",
    "of Kostroma and Liubimograd": "з Костроми і Любимограда",
})


# How else a saint is named, continued.
TEXT.update({
    "of Kozhe Lake": "з Кожозера",
    "of Krasny Kholm": "з Красного Холма",
    "of Kubensk": "з Кубенського",
    "of Kyzikos": "з Кізика",
    "of Laodikeia": "з Лаодикії",
    "of Le Mans": "з Ле-Мана",
    "of Leokhnov": "з Леохнова",
    "of Lesbos": "з Лесбоса",
    "of Liconium": "з Іконія",
    "of Lindisfarne": "з Ліндісфарна",
    "of Loma and Yaroslavl": "з Ломи і Ярославля",
    "of Lyconia": "з Лікаонії",
    "of Lyons": "з Ліона",
    "of Lérins": "з Лерина",
    "of Maiuma": "з Маіуми",
    "of Malopinega": "з Малопинежжя",
    "of Mauretania": "з Мавританії",
    "of Mediolanum": "з Медіолана",
    "of Meglin": "з Меглина",
    "of Melitene": "з Мелітини",
    "of Melitene in Armenia": "з Мелітини Вірменської",
    "of Mesopotamia": "з Месопотамії",
    "of Milan": "з Медіолана",
    "of Monza": "з Монци",
    "of Moscow": "з Москви",
    "of Mount Athos": "з Афону",
    "of Mount Auxentius": "з гори Авксентія",
    "of Mount Galesion": "з гори Галісій",
    "of Mount Galesius": "з гори Галісій",
    "of Mount Maleon": "з гори Малеон",
    "of Mount Maleon in the Peloponnese": "з гори Малеон на Пелопоннесі",
    "of Mount Myrsinon in the Peloponnese": "з гори Мірсінон на Пелопоннесі",
    "of Murom": "з Мурома",
    "of Myra": "з Мир",
    "of Myra in Lycia": "з Мир Лікійських",
    "of Najran": "з Наджрана",
    "of Neocaesarea": "з Неокесарії",
    "of Nicaea": "з Нікеї",
    "of Nicomedia": "з Нікомидії",
    "of Novgorod": "з Новгорода",
    "of Novoezersk": "з Новоезерська",
    "of Novolotsk": "з Новолоцька",
    "of Novotorsk": "з Новоторзька",
    "of Novy Torg": "з Нового Торга",
    "of Nurma": "з Нурми",
    "of Nursia": "з Нурсії",
    "of Ondrusov": "з Ондрусова",
    "of Palermo in Sicily": "з Палермо в Сицилії",
    "of Palestine": "з Палестини",
    "of Paphlagonia": "з Пафлагонії",
    "of Paris": "з Парижа",
    "of Pec": "з Печі",
    "of Pelsheme": "з Пельшми",
    "of Pelusium": "з Пелусія",
    "of Perekop": "з Перекопу",
    "of Pergamum": "з Пергама",
    "of Perm": "з Перму",
    "of Persia": "з Персії",
    "of Philadelphia": "з Філадельфії",
    "of Phrygia": "з Фригії",
    "of Pochaev": "з Почаєва",
    "of Pochaiv": "з Почаєва",
    "of Poiana Marului": "з Пояна-Мерулуй",
    "of Polybotum": "з Полібот",
    "of Poshekhonsk": "з Пошехоння",
    "of Poshekhonye": "з Пошехоння",
    "of Prague": "з Праги",
    "of Pskov": "з Пскова",
    "of Radonezh": "з Радонежа",
    "of Ravenna": "з Равенни",
    "of Rila": "з Рили",
    "of Robeika": "з Робейки",
    "of Rome": "з Рима",
    "of Rostov": "з Ростова",
    "of Saint Anne's Skete": "зі скиту Святої Анни",
    "of Sebaste": "з Севастії",
    "of Serbia": "з Сербії",
    "of Shenkursk": "з Шенкурська",
    "of Shuzhgorsk": "з Шужгори",
    "of Sicily": "з Сицилії",
    "of Sinai": "з Синаю",
    "of Sinope": "з Синопа",
    "of Siya": "з Сії",
    "of Skepsis": "зі Скепсії",
    "of Smolensk": "зі Смоленська",
    "of Solovki": "з Соловків",
    "of Spain": "з Іспанії",
    "of Spaso-Eleazar": "зі Спасо-Єлеазарової обителі",
    "of St. Petersburg": "з Санкт-Петербурга",
    "of Stolbensk": "зі Столобного",
    "of Stolobny": "зі Столобного",
    "of Suzdal": "з Суздаля",
    "of Suzdal and Yuriev": "з Суздаля і Юр'єва",
    "of Svir": "зі Свіру",
    "of Syanzhemsk": "зі Сянжеми",
    "of Symbola": "з Символів",
    "of Symbola in Bithynia": "з Символів у Віфінії",
    "of Synnada": "зі Синнад",
    "of Syracuse": "зі Сиракуз",
    "of Tabenna": "з Тавенни",
    "of Tambov": "з Тамбова",
    "of Taormina": "з Таорміни",
    "of Tarsus": "з Тарса",
    "of Tazlău": "з Тазлеу",
    "of Terracina": "з Террачини",
    "of Thebes": "з Фів",
    "of Thessalonica": "з Солуня",
    "of Thessaloniki": "з Солуня",
    "of Thrace": "з Фракії",
    "of Tiksnensk": "з Тіксни",
    "of Totma": "з Тотьми",
    "of Trebia": "з Требії",
    "of Trebizond": "з Трапезунда",
    "of Tvali": "з Твалі",
    "of Tyre": "з Тира",
    "of Uglich": "з Углича",
    "of Ushchelsk": "з Ущелля",
    "of Valaam": "з Валаама",
    "of Verkhoturye": "з Верхотур'я",
    "of Verkneostrov": "з Верхньоострова",
    "of Verkola": "з Верколи",
    "of Vishera": "з Вишери",
    "of Vladimir in Volhynia": "з Володимира-Волинського",
    "of Volotsk": "з Волоцька",
    "of Vorbozomsk": "з Ворбозомського",
    "of Voronezh": "з Воронежа",
    "of Vyatka": "з В'ятки",
    "of Vyritsa": "з Вириці",
    "of Yakhrom": "з Яхроми",
    "of Yarenga": "з Яренги",
    "of Yashezersk": "з Яшезера",
    "of Zadonsk": "із Задонська",
    "of the Ancient Caves in Palestine": "з Давніх печер у Палестині",
    "of the Caves": "з Печер",
    "of the Jordan": "з Йордану",
    "of the Kvabtakhevi Monastery in Georgia": "з Квабтахевського монастиря в Грузії",
    "of the Kyiv Caves": "з Київських печер",
    "of the Kyiv Near Caves": "з Київських Ближніх печер",
    "of the Lavra": "з Лаври",
    "of the Seventy": "із сімдесяти",
    "of the Twelve": "з дванадцяти",
    "of the Venerable Fathers of the Kyiv Caves Lavra": "з преподобних отців Києво-Печерської Лаври",
    "of the Yellow Waters": "з Жовтих Вод",
})


# the place a saint is known by, where the title carries more than a place
TEXT.update({
    "of Alaska, Wonderworker of All America, Elder of Spruce Island": "з Аляски, чудотворець усієї Америки, старець Ялинового острова",
    "of Alexandria, Desert Mother": "з Олександрії, мати пустелі",
    "of Alexandria, the Citizen": "з Олександрії, Городянин",
    "of Alexandria, the Martyr": "з Олександрії, мученик",
    "of Anazarbus, with the Martyrs Helladius, Macarius, and Evagrius": "з Аназарва, з мучениками Елладієм, Макарієм та Євагрієм",
    "of Ancyra, and with him the seven Virgin Martyrs: Alexandra, Tecusa, Claudia, Phaine, Euphrasia, Matrona, and Julia": "з Анкіри, і з ним сім дів-мучениць: Олександра, Текуса, Клавдія, Фаїна, Євфрасія, Матрона і Юлія",
    "of Anzersk Island, Solovki": "з Анзерського острова на Соловках",
    "of Blue Jay Lake, Novgorod": "з Синього озера, Новгород",
    "of Bulgaria, Wonderworker of Vladimir": "з Болгарії, володимирський чудотворець",
    "of Caesarea, in Cappadocia": "з Кесарії Каппадокійської",
    "of Caesarea, in Palestine": "з Кесарії Палестинської",
    "of Carpatho-Russia, Apostle of Carpatho-Russia": "з Карпатської Русі, апостол Карпатської Русі",
    "of Cernica, Bishop of Ramnic": "з Черніки, єпископ Римницький",
    "of Chelma Hill, Enlightener of the Chud": "з Чельмської гори, просвітитель чуді",
    "of Constantia, Bishop of Cyprus": "з Констанції, єпископ Кіпрський",
    "of Constantinople, Archbishop": "з Константинополя, архієпископ",
    "of Crete, the Martyr": "з Криту, мученик",
    "of Devich, Serbia": "з Девича в Сербії",
    "of Dymsk, Novgorod": "з Димська, Новгород",
    "of Edessa, Confessors": "з Едеси, сповідники",
    "of Hellas, of Mount Steirion": "з Еллади, з гори Стиріон",
    "of Irkutsk, First Bishop": "з Іркутська, перший єпископ",
    "of Jerusalem, Archbishop": "з Єрусалима, архієпископ",
    "of Jerusalem, Hieromartyr": "з Єрусалима, священномученик",
    "of Kazan, First Archbishop": "з Казані, перший архієпископ",
    "of Khakhuli, called Chrysostom": "з Хахулі, названий Золотоустим",
    "of Komel and Vologda, disciple of Saint Nilus of Sora": "з Комеля і Вологди, учень преподобного Ніла Сорського",
    "of Lampsacus, Unmercenary": "з Лампсака, безсрібник",
    "of Libertyville, First Serbian Bishop of America": "з Лібертивілля, перший сербський єпископ Америки",
    "of Luchov, Kostroma": "з Лухова, Кострома",
    "of Lycia, and, with him, the Martyrs Callinica and Aquilina": "з Лікії, і з ним мучениці Каллініка та Акилина",
    "of Moscow, Metropolitan of Kyiv and All Rus, Wonderworker": "з Москви, митрополит Київський і всієї Русі, чудотворець",
    "of Moscow, the Blessed Eldress": "з Москви, блаженна стариця",
    "of Mount Athos, Makres, Abbot of the Pantokrator": "з Афону, Макрис, ігумен Пантократора",
    "of Mount Athos, Sweet Kissing": "з Афону, Солодке Лобзання",
    "of Mount Athos, the New Martyr": "з Афону, новомученик",
    "of Murom, Wonderworker of the Near Caves": "з Мурома, чудотворець Ближніх печер",
    "of New York, New Hieromartyr": "з Нью-Йорка, новий священномученик",
    "of Nicea, in Bithynia": "з Нікеї Віфінської",
    "of Nicomedia, with 500 men and 130 women": "з Нікомидії, з п'ятьмастами мужами і ста тридцятьма жінками",
    "of Nisibis, Syria": "з Нізібії в Сирії",
    "of Novgorod, Archbishop": "з Новгорода, архієпископ",
    "of Ostrog, Metropolitan of Zahumlje": "з Острога, митрополит Захум'я",
    "of Palestine, disciple of Venerable Dorotheos": "з Палестини, учень преподобного Дорофея",
    "of Pechenga, Priestmonk Martyr": "з Печенги, ієромонах-мученик",
    "of Perge in Pamphylia, his mother, Philippa, and Martyrs Dioscorus, Socrates, and Dionysius": "з Пергії Памфілійської, мати його Филипа та мученики Діоскор, Сократ і Діонісій",
    "of Prodromou, Mount Athos": "з Продрому на Афоні",
    "of Pskov, Lake Gdov": "з Пскова, Гдовське озеро",
    "of Rome, Deaconess": "з Рима, диякониса",
    "of Rome, and her two female servants": "з Рима, і дві її служниці",
    "of Rome, with Censorinus, Sabinus, Chryse the Virgin, and twenty others": "з Рима, з Кенсорином, Савином, дівою Хрисою та іншими двадцятьма",
    "of Rome, with her seven sons": "з Рима, із сімома синами її",
    "of Saint Petersburg, Fool-for-Christ": "з Санкт-Петербурга, Христа ради юродива",
    "of Sardis, Hieromartyr": "з Сард, священномученик",
    "of Sarov, Wonderworker": "з Сарова, чудотворець",
    "of Sicily, with his disciples Timothy and Agapius": "з Сицилії, з учнями його Тимофієм і Агапієм",
    "of Side, in Pamphylia": "з Сіди Памфілійської",
    "of Sinai, Author of the Ladder": "з Синаю, списатель Ліствиці",
    "of Storozhev, Zvenigorod Wonderworker": "зі Сторожів, звенигородський чудотворець",
    "of Suzdal, the Wonderworker": "з Суздаля, чудотворець",
    "of Syanzhemsk, Vologda": "з Сянжеми, Вологда",
    "of Synnada, the Convert": "з Синнад, навернений",
    "of Tarsus, in Asia Minor": "з Тарса в Малій Азії",
    "of Tarsus, in Cilicia": "з Тарса Кілікійського",
    "of Thebes, the First Hermit": "з Фів, перший пустельник",
    "of Totma, Sumorin": "з Тотьми, Суморин",
    "of Verkhoturye, Righteous Wonderworker": "з Верхотур'я, праведний чудотворець",
    "of Vyazma, Right-believing Princess": "з Вязьми, благовірна княгиня",
    "of Zakynthos, the Saint of Forgiveness": "із Закінфа, святий прощення",
    "of Zelenets, Pskov": "з Зеленця, Псков",
    "of Zhabyn, Wonderworker of Belev": "з Жабині, бельовський чудотворець",
    "of Zhicha and Ohrid, the New Chrysostom": "з Жичі та Охрида, новий Золотоуст",
    "of the Kyiv Caves, First Abbot": "з Київських печер, перший ігумен",
    "of the Kyiv Caves, in the Far Caves": "з Київських печер, у Дальніх печерах",
    "of the Kyiv Near Caves, the Chronicler": "з Київських Ближніх печер, літописець",
    "of the Lavra, Mount Athos": "з Лаври на Афоні",
    "of the Pandects, Sabbaite": "з Пандектів, савваїт",
    "of the Seventy, Apostle and Evangelist": "із сімдесяти, апостол і євангелист",
    "of the Seventy, Bishop of Britain": "із сімдесяти, єпископ Британії",
    "of the Seventy, and his fellow-laborer, Junia": "із сімдесяти, і співробітниця його Юнія",
    "of the Seventy, and those with him: Agabus, Rufus, Asyncritus, Phlegon, and Hermes": "із сімдесяти, і ті, що з ним: Агав, Руф, Асинкрит, Флегонт і Єрм",
    "of the Seventy, first Bishop of Ephesus": "із сімдесяти, перший єпископ Ефеський",
})


# how a saint is written in an icon, and some names as the calendar gives them
TEXT.update({
    "(Abibus) of Egypt": "(Авів) з Єгипту",
    "(Apphianus) and Edesius (Aedesius) of Lycia": "(Апфіан) та Едесій (Едезій) з Лікії",
    "(Eustace) the Confessor, Bishop of Bithynia": "(Євстафій) сповідник, єпископ Віфінський",
    "(Jacob) the Presbyter, and Azadanes and Abdiesus the Deacons, of Persia": "(Яків) пресвітер, та Азадан і Авдієс диякони, з Персії",
    "(Vadim) of Persia": "(Вадим) з Персії",
    "(Voino-Yasenetsky), Archbishop of Simferopol and Crimea": "(Войно-Ясенецький), архієпископ Сімферопольський і Кримський",
    "(also called Susanna), New Martyr of Lesbos": "(звана також Сусанною), новомучениця Лесбоська",
    "(tonsured David and Euphrosyne), Wonderworkers of Murom": "(у постригу Давид і Євфросинія), муромські чудотворці",
    "A Cappadocian centurion bowing beneath the sword with his eyes lifted in thanksgiving, the walnut tree of the tradition behind him, the churches of Byzantium rising over his relics.": "Каппадокійський сотник схиляється під меч, звівши очі в подяці; за ним горіхове дерево переказу, а над мощами його підносяться храми Візантії.",
    "A Celtic hermit of the Devon coast bearing his own severed head to the spring, the robbers behind him, crowned as a martyr among the saints of Britain.": "Кельтський пустельник з девонського узбережжя несе відтяту голову свою до джерела; за ним розбійники, а він увінчаний як мученик серед святих Британії.",
    "A Christian general casting down the temples of Galatia, his twelve tribunes and his thousands of soldiers with their wives and children crowned around him, the converted sorcerer Callinicus among them.": "Воєвода-християнин руйнує капища Галатії; довкола нього увінчані дванадцять трибунів і тисячі воїнів із жінками та дітьми, а між ними навернений чарівник Каллінік.",
    "A Christian of Alexandria standing before the tribunal to denounce its cruelty, the confession volunteered and the sword received.": "Християнин олександрійський стає перед судилищем, щоб викрити його жорстокість; сповідання принесене добровільно, а меч прийнятий.",
    "A Creole-Aleut priest in vestments holding a Gospel and a cross, against an Alaskan landscape.": "Священник креольсько-алеутського роду в ризах тримає Євангеліє і хрест на тлі аляскинського краєвиду.",
    "A Georgian bishop with a book and a restored church, schoolchildren and monasteries behind him.": "Грузинський єпископ з книгою і відновленим храмом; за ним школярі та монастирі.",
    "A Georgian commander marking his forehead with the cross in his own blood, his soldiers crowned around him.": "Грузинський воєвода знаменує чоло своє хрестом власною кров'ю; довкола нього увінчані воїни його.",
    "A Georgian monk in prayer before the cave monastery of Gareji in the desert hills.": "Грузинський чернець молиться перед печерною обителлю Гареджі серед пустельних пагорбів.",
    "A Georgian monk-abbot holding a scroll or a book.": "Грузинський чернець-ігумен тримає сувій або книгу.",
    "A Georgian prince and commander refusing to trample the icon of Christ before the conqueror, crowned as a great-martyr, the defender of the Georgian faith.": "Грузинський князь і воєвода відмовляється потоптати ікону Христову перед завойовником; увінчаний як великомученик, оборонець грузинської віри.",
    "A Gothic congregation at worship within the burning church, twenty-six crowns rising with the smoke, the queen gathering the holy remains from the ashes.": "Готська громада молиться в палаючому храмі; двадцять шість вінців підносяться з димом, а цариця збирає з попелу святі останки.",
    "A Gothic general of Rome casting down his military belt before Aurelian, seventy soldiers confessing behind him, the river receiving the wonderworking commander.": "Готський воєвода римський кидає військовий пояс свій перед Авреліаном; за ним сповідують сімдесят воїнів, а ріка приймає чудотворного полководця.",
    "A Great Prince of Kyiv with the churches of Smolensk he raised, the monastic habit he longed for held by an angel, the elder Polycarp pointing him back to his throne.": "Великий князь київський із храмами смоленськими, що він їх поставив; ангел тримає чернечий образ, якого він жадав, а старець Полікарп вказує йому назад на престол.",
    "A Greek bishop preaching Christ to the pagan Rostov land, the first shepherd of a hostile flock, the see of Rostov founded amid the idols of the north.": "Грецький єпископ проповідує Христа поганській землі Ростовській, перший пастир ворожого стада; ростовська кафедра засновується серед ідолів півночі.",
    "A Greek iconographer of Constantinople founding the island monastery of Lake Onega, the Sophia icon he copied in his hands, the peoples of the north gathering to his light at the age of one hundred and five.": "Грецький іконописець з Константинополя засновує острівну обитель на Онезькому озері; у руках його Софійська ікона, яку він списав, а народи півночі сходяться до світла його, коли йому сто п'ять років.",
    "A Greek metropolitan enthroned at Moscow beside the shrine of Peter, standing unbowed before the khan of the Horde, the Church's charter of freedom in his hand.": "Грецький митрополит на престолі в Москві біля раки Петрової стоїть непохитно перед ханом Орди; у руці його грамота церковної свободи.",
    "A Greek of Ephesus at the Apostle Paul's side, the Temple riot swirling around his innocent presence, the sickbed of Miletus and the sword of Rome completing his long companionship.": "Ефесянин-грек при боці апостола Павла; довкола безвинного його стояння вирує заколот при храмі, а недуга в Мілеті та римський меч довершують довге його супутництво.",
    "A Greek prince laying aside his rank for the monastic habit, the Uchma hermitage rising on the bank of the Volga, the exile made a wonderworker in his adopted land.": "Грецький князь складає сан свій задля чернечого образу; на березі Волги підноситься Учемська пустинь, і вигнанець стає чудотворцем у землі, що прийняла його.",
    "A Patriarch of Constantinople seated upright in death as in blessing, the Mgar monastery of Lubny receiving the traveler, the two worlds of Greece and Rus' joined at his throne.": "Патріарх константинопольський сидить у смерті прямо, немов благословляючи; Мгарська обитель під Лубнами приймає подорожнього, і два світи, Греція і Русь, сходяться при престолі його.",
    "A Persian noble offering his severed members one by one, each with a prayer, angels gathering his prayers.": "Перський вельможа подає відтяті члени свої один по одному, кожен з молитвою, а ангели збирають молитви його.",
    "A Persian soldier turned monk, the captive Cross of the Lord shining before him, the waters and the sword of Bethsaloe beneath his crown.": "Перський воїн, що став ченцем; перед ним сяє полонений Хрест Господній, а під вінцем його води й меч Вефсалойські.",
    "A Roman centurion kneeling before the Apostle Peter, or vested as a bishop holding a Gospel.": "Римський сотник на колінах перед апостолом Петром, або в святительських ризах з Євангелієм у руках.",
    "A Roman general in armor holding a cross, his soldiers behind him, a spring at his feet.": "Римський воєвода в броні тримає хрест; за ним воїни його, а біля ніг джерело.",
    "A Roman maiden in flight across the sea with two servants, the convent of Saint Stephen at Mylasa, a cross of stars brighter than the sun above her repose.": "Римська діва тікає морем із двома служницями; обитель святого Стефана в Міласі, а над упокоєнням її хрест із зір, ясніший за сонце.",
    "A Roman matron refusing the Arian rite, the fire kindled behind her, Saint Ambrose blessing from afar.": "Римська матрона відмовляється від аріанського обряду; за нею розпалений вогонь, а святитель Амвросій благословляє здалеку.",
    "A Roman noblewoman scattering deeds and treasure to the poor, thousands of freed slaves behind her, her small cell on the Mount of Olives before her.": "Римська вельможна жона роздає вбогим маєтки й скарби; за нею тисячі відпущених рабів, а перед нею тісна келія її на горі Елеонській.",
    "A Roman senator opening his house to the Apostle Peter, the household at prayer becoming a church, the greeting of the epistle shining over the door.": "Римський сенатор відчиняє дім свій апостолові Петру; домашні його на молитві стають церквою, а над дверима сяє вітання з послання.",
    "A Roman widow standing amid seven crowned sons, encouraging each to the contest, her own crown descending last.": "Римська вдова стоїть серед сімох увінчаних синів, підбадьорюючи кожного на подвиг; вінець її сходить останнім.",
    "A Russian captive in the winter night of Kazan, bound and wounded in the snow, alive at dawn with his confession unbroken.": "Полонений русич у зимовій ночі казанській, зв'язаний і зранений на снігу, живий на світанку, і сповідання його непорушене.",
    "A Russian soldier-slave at prayer in his master's stable, the Turkish household softened by his faith, his incorrupt relics glorified across the Greek world.": "Воїн-невільник русич молиться у стайні господаря свого; турецький дім лагідніє від віри його, а нетлінні мощі його прославляються по всьому грецькому світі.",
    "A Serbian prince leading his army at Kosovo, choosing the kingdom of heaven over the kingdom of earth, crowned as a great-martyr, his incorrupt relics the treasure of his people.": "Сербський князь веде військо своє на Косовому полі, обираючи царство небесне понад царство земне; увінчаний як великомученик, і нетлінні мощі його - скарб народу його.",
    "A Spanish dignitary in the Great Schema, the roads of his pilgrimage from Rome to Jerusalem behind him, the Saracen sword before him.": "Іспанський вельможа у великій схимі; за ним дороги прощі його від Рима до Єрусалима, а перед ним сарацинський меч.",
})


# how a saint is written in an icon
TEXT.update({
    "A Swedish princess become mother of Rus, her sainted son Vladimir beside her, the crowns of France, Hungary, and Norway among her daughters, the nun's habit her final vesture.": "Шведська княжна, що стала матір'ю Русі; при ній святий син її Володимир, між дочками її корони Франції, Угорщини й Норвегії, а останнє вбрання її - чернече.",
    "A Syrian stranger standing three days in prayer in the church of Spoleto, the garden thieves fed at his table and converted, the offered estates refused with a smiling shake of the head.": "Сирійський чужинець три дні стоїть на молитві у храмі Сполетському; злодії з городу нагодовані за столом його і навернені, а запропоновані маєтки відхилені усміхненим порухом голови.",
    "A Tatar captive baptized and tonsured, founding a monastery on the shore of Lake Kozha in the far north, the wilderness hallowed by his prayer.": "Полонений татарин, охрещений і постижений, засновує обитель на березі Кожозера на далекій півночі, і пустеля освячується молитвою його.",
    "A Yup'ik mother in a kuspuk holding a basin and towel, the northern lights above the tundra behind her.": "Мати з народу юпік у куспуку тримає умивальницю й рушник; за нею над тундрою північне сяйво.",
    "A barefoot ascetic in rags, blessing, at Novgorod.": "Босий подвижник у лахмітті благословляє, у Новгороді.",
    "A barefoot fool in tattered clothing by a northern river, giving away what was given to him.": "Босий юродивий у подертій одежі при північній ріці роздає те, що йому дали.",
    "A barefoot fool-for-Christ holding a head of cabbage, at Novgorod by the river.": "Босий Христа ради юродивий тримає головку капусти, у Новгороді при ріці.",
    "A barefoot fool-for-Christ in a sheepskin holding an axe, by the river defending the city.": "Босий Христа ради юродивий у кожусі тримає сокиру, при ріці обороняючи місто.",
    "A barefoot holy fool with long hair, holding a Psalter, of gentle and sorrowful aspect.": "Босий юродивий з довгим волоссям тримає Псалтир, лагідний і скорботний з виду.",
    "A basilica at Lydda, the tomb of Saint George within, hierarchs consecrating the church.": "Базиліка в Лідді, а в ній гроб святого Георгія; святителі освячують храм.",
    "A bearded missionary priest with a traveler's bag, the church of Jackson and the hills of California behind him.": "Бородатий священник-місіонер з подорожньою торбою; за ним храм у Джексоні та каліфорнійські пагорби.",
    "A beggar beneath the staircase of his father's palace, unknown to all his household, the finished scroll of his life clasped in his dead hand while the emperor and the pope kneel to read it.": "Жебрак під сходами батьківського дому, невпізнаний нікому з домашніх; у мертвій руці його затиснений дописаний сувій життя його, а імператор і папа на колінах читають його.",
    "A bent elder in white on his knees upon the rock, the Theotokos of Tenderness before him, a bear at the edge of the forest clearing.": "Згорблений старець у білому на колінах на камені; перед ним Богородиця Розчулення, а на краю лісової галявини ведмідь.",
    "A bishop alone in an emptied city awaiting the persecutors, then crucified at Perge, teaching from the cross until his voice failed into glory.": "Єпископ сам у спорожнілому місті чекає гонителів, а тоді, розп'ятий у Пергії, навчає з хреста, доки голос його не вгас у славу.",
    "A bishop and a presbyter of Persia holding crosses, swords above them.": "Єпископ і пресвітер перські тримають хрести, а над ними мечі.",
    "A bishop and a virgin holding crosses, broken books of sorcery burning at their feet.": "Єпископ і діва тримають хрести, а біля ніг їхніх горять подерті книги чарівницькі.",
    "A bishop and his companions holding crosses, cast into a furnace, a soldier among them.": "Єпископ і супутники його тримають хрести, вкинені в піч, а між ними воїн.",
    "A bishop and presbyter cast into a pit, angels crowning them from above.": "Єпископ і пресвітер укинені в яму, а ангели згори вінчають їх.",
    "A bishop and theologian of Lycia with the scroll of his Banquet of the Ten Virgins, refuting the errors of Origen, crowned at the last with martyrdom.": "Єпископ і богослов лікійський із сувоєм Бенкету десяти дів викриває блуди Оригенові, а наостанок вінчається мучеництвом.",
    "A bishop answering the emperor that the Church's questions belong to the Church, the road of exile opening behind him.": "Єпископ відповідає імператорові, що церковні питання належать Церкві, а за ним відкривається дорога вигнання.",
    "A bishop baptizing an African king, a boy captive and a royal tutor shown in the scenes of his life.": "Єпископ хрестить африканського царя; у клеймах життя його показані хлопець-бранець і царський навчитель.",
    "A bishop barring the church door to an emperor, a beehive at his feet, a scroll of his hymns in hand.": "Єпископ заступає імператорові двері храму; біля ніг його вулик, а в руці сувій пісень його.",
    "A bishop before a fallen idol, a demon bearing a great stone altar behind him, hot springs at his feet.": "Єпископ перед поваленим ідолом; за ним демон несе великий кам'яний жертовник, а біля ніг його гарячі джерела.",
    "A bishop before the burning temple of Marnas, the cross-guardian's keys at his belt, the Good Thief descending from the Cross in his vision, the Eudoxiana church rising over pagan Gaza.": "Єпископ перед палаючим капищем Марна; на поясі його ключі хрестохранителя, у видінні його благорозумний розбійник сходить із Хреста, а над поганською Газою підноситься храм Євдоксіани.",
    "A bishop before the emperor, pointing to the emperor's son, teaching the honor due the Son of God.": "Єпископ перед імператором вказує на сина його, навчаючи, яка честь належить Синові Божому.",
    "A bishop beheaded at the altar in mid-Liturgy, twenty-eight years of tribunals and torments ranged behind him like waves, Agathangelus crowned at his side.": "Єпископ обезглавлений при престолі посеред Літургії; за ним, наче хвилі, двадцять вісім років судилищ і мук, а поруч увінчаний Агафангел.",
    "A bishop beholding the ladder to heaven with his predecessor calling from above, one hundred and twenty-eight companions ascending behind him under the Persian sword.": "Єпископ бачить драбину до неба, а попередник його кличе згори; за ним сходять сто двадцять вісім супутників під перським мечем.",
    "A bishop by night in a plain cloak, leaving firewood at a poor widow's door, his cathedral of Belgorod behind him.": "Єпископ уночі в простій свиті лишає дрова під дверима вбогої вдови; за ним білгородський собор його.",
    "A bishop drinking the sorcerer's cup unharmed, the magician kneeling converted beside his cast-down instruments.": "Єпископ неушкоджено випиває чашу чарівника, а той навернений стоїть на колінах при відкинутім знарядді своїм.",
    "A bishop enthroned with a Gospel, the first hierarch of Jerusalem, of ascetic and venerable countenance.": "Єпископ на престолі з Євангелієм, перший святитель єрусалимський, з виду постницький і поважний.",
    "A bishop holding a Gospel, refuting heretics who shrink before his word.": "Єпископ тримає Євангеліє, викриваючи єретиків, що никнуть перед словом його.",
    "A bishop holding a page of the alphabet he invented, the sacred birch of the Zyrians felled behind him, the sorcerer Pam turning from the fire and the water, a new people reading the Gospel in its own letters.": "Єпископ тримає аркуш абетки, яку склав; за ним зрубана священна береза зирян, чарівник Пам відступає від вогню й від води, а новий народ читає Євангеліє власними письменами.",
    "A bishop holding a scroll of the Creed, the Theotokos and John the Theologian appearing above, a mountain moved behind.": "Єпископ тримає сувій Символу віри; вгорі являються Богородиця та Іван Богослов, а позаду зрушена гора.",
    "A bishop holding an icon of Christ against the imperial decree, the sick healed at his hands.": "Єпископ тримає ікону Христову всупереч царському указові, а недужі зціляються від рук його.",
    "A bishop holding the book of the Divine Names, the darkened sun of the Crucifixion above him.": "Єпископ тримає книгу Про Божественні імена, а над ним потьмарене сонце Розп'яття.",
    "A bishop in a laborer's tunic drawing water and hauling wood at Nitria, the omophorion of Damascus folded away, heaven alone reading the monk's true rank.": "Єпископ у робітничій одежі носить воду й дрова в Нітрії; омофор дамаський складений і схований, і саме тільки небо читає справжній сан ченця.",
    "A bishop in a mitre holding a crozier, with a gray beard and an ascetic, gentle face.": "Єпископ у митрі тримає жезл, із сивою бородою та постницьким лагідним обличчям.",
    "A bishop in monastic poverty, Cernica's island monastery at one hand and the Frasinei he founded at the other, the seminary and the printing press of Ramnic behind him, his face worn bright by fasting.": "Єпископ у чернечій убогості: по одну руку острівна обитель Черніки, по другу Фрасіней, що його він заснував; за ним семінарія і друкарня римницькі, а обличчя його світле від посту.",
    "A bishop in the omophorion and mantle holding a book, of gentle and humble aspect.": "Єпископ в омофорі й мантії тримає книгу, лагідний і смиренний з виду.",
    "A bishop in the omophorion and sakkos holding a Gospel book, with a Greek-style beard.": "Єпископ в омофорі й саккосі тримає Євангеліє, з бородою на грецький лад.",
    "A bishop in the omophorion blessing the waters at a river confluence, holding a cross.": "Єпископ в омофорі благословляє води при злитті рік, тримаючи хрест.",
    "A bishop in the omophorion blessing, holding a Gospel, before the cathedral of Tambov.": "Єпископ в омофорі благословляє, тримаючи Євангеліє, перед тамбовським собором.",
    "A bishop in the omophorion holding a Gospel book or the scroll of his Great Canon.": "Єпископ в омофорі тримає Євангеліє або сувій Великого канону свого.",
    "A bishop in the omophorion holding a Gospel book, a white dove upon his head.": "Єпископ в омофорі тримає Євангеліє, а на голові його білий голуб.",
    "A bishop in the omophorion holding a Gospel, of humble aspect.": "Єпископ в омофорі тримає Євангеліє, смиренний з виду.",
    "A bishop in the omophorion holding a Gospel, sometimes with a banner or before a battle.": "Єпископ в омофорі тримає Євангеліє, інколи з корогвою або перед битвою.",
    "A bishop in the omophorion holding a Gospel, the cathedral of Saints Cyril and Methodius behind him.": "Єпископ в омофорі тримає Євангеліє; за ним собор святих Кирила і Мефодія.",
    "A bishop in the omophorion holding an icon and a Gospel.": "Єпископ в омофорі тримає ікону та Євангеліє.",
    "A bishop in the omophorion surrounded by his ten disciples, all crowned as martyrs.": "Єпископ в омофорі, оточений десятьма учнями своїми, і всі вони увінчані як мученики.",
    "A bishop in the omophorion, his hands or face marked by charcoal, holding a Gospel.": "Єпископ в омофорі, з руками або обличчям, позначеними вугіллям, тримає Євангеліє.",
    "A bishop in the schema and omophorion holding a Gospel, before the city of Voronezh.": "Єпископ у схимі та омофорі тримає Євангеліє, перед містом Воронежем.",
    "A bishop in the snows of Siberia, a school of native children beside him, the gates of China closed behind.": "Єпископ у снігах Сибіру; поруч нього школа тубільних дітей, а позаду зачинені брами Китаю.",
    "A bishop laying aside his omophorion at the mouth of a desert gorge, the monastery of Choziba in the cliffs.": "Єпископ складає омофор свій при вході в пустельну ущелину, а в скелях обитель Хозівська.",
    "A bishop led by an angel from torture to torture and city to city, Sirmium converted behind him and Formia receiving him, the lamps of the sailors burning at his name.": "Ангел веде єпископа від муки до муки й від міста до міста; за ним навернений Сірмій, а Формія приймає його, і на ім'я його горять світильники корабельників.",
    "A bishop of Aegina laying down his omophorion and returning to the monastic habit, his island see behind him.": "Єпископ Егінський складає омофор свій і повертається до чернечого образу; за ним острівна кафедра його.",
    "A bishop of Amasea standing between the hunted virgin and the tyrant's demand, the sea giving back his body in the fishermen's nets, the last crowns of the persecution descending as the peace of the Church dawns.": "Єпископ Амасійський стає між гнаною дівою і вимогою мучителя; море віддає тіло його в рибальських сітях, і останні вінці гоніння сходять, коли світає мир Церкві.",
    "A bishop of Argos measuring out grain that does not diminish, the ransomed captives returning from the sea behind him, his monastic family in Christ around the one see he consented to hold.": "Єпископ Аргоський відмірює збіжжя, яке не меншає; за ним викуплені полонені вертаються з-за моря, а довкола єдиної кафедри, яку він згодився тримати, чернеча родина його у Христі.",
    "A bishop of Benevento unharmed in the furnace, the beasts of the arena lying at his feet, Naples receiving his body and his blood, his deacons and companions crowned around him.": "Єпископ Беневентський неушкоджений у печі; звірі на арені лежать при ногах його, Неаполь приймає тіло його і кров його, а довкола увінчані диякони та супутники його.",
    "A bishop of Bithynia holding the icon of Christ and the open Scriptures together, the road of exile behind him.": "Єпископ Віфінський тримає разом ікону Христову і відкрите Писання; за ним дорога вигнання.",
    "A bishop of Bithynia on the road of exile, his cathedral behind him and the icon of Christ unsurrendered before him.": "Єпископ Віфінський на дорозі вигнання; за ним собор його, а перед ним невіддана ікона Христова.",
})
