# -*- coding: utf-8 -*-
"""Ukrainian for the vocabulary that stands beside the lives.

TEXT = {the phrase the index shows: the Ukrainian}. PARTS holds the pieces
the compound place-names are built from, and expand() assembles the wholes,
so a town cannot be spelled one way on one card and another way on the next.

The rank vocabulary was settled before any of this was written, and is set
down in docs/UKRAINIAN.md. The reason is the defect that had to be swept out
of the three finished languages: in a Slavonic-tradition tongue a saint's
honorific is his rank, and the bare word святий stands before a rank and
never before a name. Преподобний Сергій, святитель Миколай, благовірний
князь Володимир, праведний Симеон Богоприїмець.

The nearer trap here is Russian. Ukrainian is close enough to it that a
rendering can be correct Russian and merely Russian-shaped Ukrainian, which
a reader feels at once and no checker sees. So the Church's own Ukrainian
words are used: Церква declining as Церкви, чернець for the monk, сповідник
for the confessor, безсрібник for the unmercenary, Успіння for the Dormition,
Києво-Печерська лавра and its печерські fathers. Placenames take their
Ukrainian shapes - Київ, Чернігів, Волинь, Переяслав - and the princes their
Ukrainian names: Володимир, Ярослав, Борис і Гліб.

The keys are the phrases exactly as the index writes them, so a rendering
cannot quietly attach itself to the wrong saint.
"""
TEXT = {}


# The orders of sanctity, as the badge on a card names them.
TEXT.update({
    "Angelic": "Безтілесні сили",
    "Apostle": "Апостол",
    "Confessor": "Сповідник",
    "Equal-to-the-Apostles": "Рівноапостольний",
    "Feast": "Свято",
    "Fool-for-Christ": "Христа ради юродивий",
    "Great Martyr": "Великомученик",
    "Hierarch": "Святитель",
    "Hieromartyr": "Священномученик",
    "Martyr": "Мученик",
    "Monastic": "Преподобний",
    "New Martyr": "Новомученик",
    "Other": "Інше",
    "Passion-bearer": "Страстотерпець",
    "Prophet": "Пророк",
    "Righteous": "Праведний",
    "Unmercenary": "Безсрібник",
    "Virgin Martyr": "Мучениця-діва",
})


# The attributes a life is marked with.
TEXT.update({
    "Church Father": "Отець Церкви",
    "Desert ascetic": "Подвижник пустелі",
    "Enlightener": "Просвітитель",
    "Healing intercessor": "Цілитель",
    "Hymnographer": "Піснописець",
    "Iconographer": "Іконописець",
    "Incorrupt relics": "Нетлінні мощі",
    "Monastery founder": "Засновник обителі",
    "Myrrh-bearer": "Мироносиця",
    "Myrrh-streaming": "Мироточивий",
    "New martyr": "Новомученик",
    "Ruler or royal": "Правитель або з княжого роду",
    "Stylite": "Стовпник",
    "Warrior saint": "Святий воїн",
    "Wonderworker": "Чудотворець",
})


# The ranks the Typikon gives a feast.
TEXT.update({
    "Doxology": "Славослів'я",
    "Great Feast": "Велике свято",
    "Polyeleos": "Полієлей",
    "Simple": "Проста",
    "Vigil": "Всенічне бдіння",
})


# The jurisdictions whose calendars the index keeps.
TEXT.update({
    "Antiochian": "Антіохійський",
    "Greek": "Грецький",
    "OCA": "OCA",
    "Romanian": "Румунський",
    "Russian": "Російський",
    "Serbian": "Сербський",
    "Ukrainian": "Український",
})


# The estate a saint stood in.
TEXT.update({
    "Apostolic": "Апостольський",
    "Clergy": "Духівництво",
    "Laity": "Миряни",
    "Layman": "Мирянин",
    "Laywoman": "Мирянка",
    "Laywomen": "Мирянки",
    "Married": "Одружений",
    "Military": "Військовий",
    "Monastic": "Чернечий",
    "Prophet": "Пророк",
    "Royal": "Княжий",
    "Royalty": "Княжий рід",
    "Unknown": "Невідомо",
    "Unmarried": "Неодружений",
    "Widowed": "Овдовілий",
})


# The ages the lives are set in.
TEXT.update({
    "Age of the Celtic Saints": "Доба кельтських святих",
    "Age of the Ecumenical Councils": "Доба Вселенських Соборів",
    "Age of the Martyrs": "Доба мучеників",
    "Apostolic Age": "Апостольська доба",
    "Byzantine": "Візантійський",
    "Byzantine Balkans": "Візантійські Балкани",
    "Byzantine Era": "Візантійська доба",
    "Byzantine Iconoclasm": "Візантійське іконоборство",
    "Cossack Era": "Козацька доба",
    "Desert Fathers": "Отці пустелі",
    "Early Medieval West": "Ранньосередньовічний Захід",
    "Imperial Russia": "Імперська Росія",
    "Kievan Rus'": "Київська Русь",
    "Medieval Georgia": "Середньовічна Грузія",
    "Medieval Rus'": "Середньовічна Русь",
    "Medieval Serbia": "Середньовічна Сербія",
    "Modern": "Новітній",
    "Modern Era": "Новітня доба",
    "Muscovite Russia": "Московська Русь",
    "Old Testament": "Старий Завіт",
    "Ottoman Balkans": "Османські Балкани",
    "Ottoman Era": "Османська доба",
    "Ottoman period": "Османський період",
    "Polish-Lithuanian period": "Польсько-литовський період",
    "Soviet Era": "Радянська доба",
    "Soviet period": "Радянський період",
    "Synodal Russia": "Синодальна Росія",
})


# The one movable commemoration the index names.
TEXT.update({
    "Sunday of the Holy Forefathers": "Неділя святих праотців",
})


# The countries and the regions.
TEXT.update({
    "Aegean": "Егейське море",
    "America": "Америка",
    "Arabia": "Аравія",
    "Armenia": "Вірменія",
    "Asia Minor": "Мала Азія",
    "Balkans": "Балкани",
    "Belarus": "Білорусь",
    "Bithynia": "Віфінія",
    "Britain": "Британія",
    "British Isles": "Британські острови",
    "Bulgaria": "Болгарія",
    "Cappadocia": "Каппадокія",
    "Cilicia": "Кілікія",
    "Constantinople": "Константинополь",
    "Crimea": "Крим",
    "Cyprus": "Кіпр",
    "Czech Lands": "Чеські землі",
    "Dalmatia": "Далмація",
    "Danube lands": "Подунав'я",
    "Egypt": "Єгипет",
    "England": "Англія",
    "Ethiopia": "Ефіопія",
    "Gaul": "Галлія",
    "Georgia": "Грузія",
    "Greece": "Греція",
    "Holy Land": "Свята Земля",
    "Illyria": "Іллірія",
    "Illyricum": "Іллірик",
    "India": "Індія",
    "Ireland": "Ірландія",
    "Italy": "Італія",
    "Lithuania": "Литва",
    "Macedonia": "Македонія",
    "Mesopotamia": "Месопотамія",
    "Moldavia": "Молдова",
    "Montenegro": "Чорногорія",
    "Moravia": "Моравія",
    "Mount Athos": "Свята Гора Афон",
    "North Africa": "Північна Африка",
    "North America": "Північна Америка",
    "North Macedonia": "Північна Македонія",
    "Palestine": "Палестина",
    "Persia": "Персія",
    "Phoenicia": "Фінікія",
    "Poland": "Польща",
    "Pontus": "Понт",
    "Romania": "Румунія",
    "Rome": "Рим",
    "Russia": "Росія",
    "Scythia": "Скіфія",
    "Serbia": "Сербія",
    "Siberia": "Сибір",
    "Sinai": "Синай",
    "Spain": "Іспанія",
    "Syria": "Сирія",
    "Thrace": "Фракія",
    "Ukraine": "Україна",
    "Western Rus": "Західна Русь",
})


# The lands the fasting rule is kept in.
TEXT.update({
    "Albania": "Албанія",
    "Bohemia": "Богемія",
    "China": "Китай",
    "France": "Франція",
    "Judah": "Юдея",
    "Moesia": "Мезія",
    "Sicily": "Сицилія",
    "United States": "Сполучені Штати",
})

# The rank a saint held, as the menaia name it.
TEXT.update({
    "Abbess": "Ігуменя",
    "Abbot (Archimandrite)": "Ігумен (архімандрит)",
    "Abbot (Founder)": "Ігумен (засновник)",
    "Abbot (Igumen)": "Ігумен",
    "Abbot (Igumen), Confessor": "Ігумен, сповідник",
    "Abbot (Igumen), Hieromartyr": "Ігумен, священномученик",
    "Abbot (Igumen), Martyr": "Ігумен, мученик",
    "Abbot (Igumen), Monastic Martyr": "Ігумен, преподобномученик",
    "Abbot, Confessor": "Ігумен, сповідник",
    "Abbot, Confessor-Martyr": "Ігумен, сповідник і мученик",
    "Abbot, Priest": "Ігумен, ієрей",
    "Abbots": "Ігумени",
    "Anchorite": "Самітник",
    "Apostle of the Seventy": "Апостол від сімдесяти",
    "Apostle of the Seventy, Bishop": "Апостол від сімдесяти, єпископ",
    "Apostle of the Seventy, Martyr": "Апостол від сімдесяти, мученик",
    "Apostle, Evangelist": "Апостол, євангелист",
    "Apostle, Martyr": "Апостол, мученик",
    "Apostles": "Апостоли",
    "Apostles of the Seventy": "Апостоли від сімдесяти",
    "Apostles of the Seventy, Martyrs": "Апостоли від сімдесяти, мученики",
    "Archangel": "Архангел",
    "Archbishop": "Архієпископ",
    "Archbishop, Confessor": "Архієпископ, сповідник",
    "Archbishop, Equal-to-the-Apostles": "Архієпископ, рівноапостольний",
    "Archdeacon": "Архідиякон",
    "Archimandrite": "Архімандрит",
    "Bishop": "Єпископ",
    "Bishop, Church Father": "Єпископ, отець Церкви",
    "Bishop, Confessor": "Єпископ, сповідник",
    "Bishop, Equal-to-the-Apostles": "Єпископ, рівноапостольний",
    "Bishop, Hieromartyr": "Єпископ, священномученик",
    "Bishop, Monk": "Єпископ, чернець",
    "Bishops": "Єпископи",
    "Blessed Eldress": "Блаженна стариця",
    "Chamberlain (cubicularius)": "Кувікуларій",
    "Childmartyr": "Отрок-мученик",
    "Commander": "Воєвода",
    "Confessor, Archpriest": "Сповідник, протоієрей",
    "Deacon": "Диякон",
    "Deacon, Monk-martyr": "Диякон, преподобномученик",
    "Deaconess": "Дияконіса",
    "Deaconess and Martyr": "Дияконіса і мучениця",
    "Elder": "Старець",
    "Empress": "Цариця",
    "Equal-to-the-Apostles, Emperor": "Рівноапостольний, цар",
    "Equals-to-the-Apostles": "Рівноапостольні",
    "Grand Duchess": "Велика княгиня",
    "Grand Prince": "Великий князь",
    "Grand Princess": "Велика княгиня",
    "Great Martyr, Equal-to-the-Apostles": "Великомученик, рівноапостольний",
    "Great Prince, Martyr": "Великий князь, мученик",
    "Great-martyr": "Великомученик",
    "Great-martyr, Prince": "Великомученик, князь",
    "Hermit": "Пустельник",
    "Hermits": "Пустельники",
    "Hierarchs": "Святителі",
    "Hieromartyr (Hermit)": "Священномученик (пустельник)",
    "Hieromartyr, Apostle": "Священномученик, апостол",
    "Hieromartyr, Archbishop": "Священномученик, архієпископ",
    "Hieromartyr, Archimandrite": "Священномученик, архімандрит",
    "Hieromartyr, Archpriest": "Священномученик, протоієрей",
    "Hieromartyr, Bishop": "Священномученик, єпископ",
    "Hieromartyr, Confessor": "Священномученик, сповідник",
    "Hieromartyr, Deacon": "Священномученик, диякон",
    "Hieromartyr, Patriarch": "Священномученик, патріарх",
    "Hieromartyr, Pope": "Священномученик, папа Римський",
    "Hieromartyr, and his son": "Священномученик і син його",
    "Hieromartyrs": "Священномученики",
    "Hieromonk": "Ієромонах",
    "Hieroschemamonk": "Ієросхимонах",
    "High Priest": "Первосвященник",
    "Icon of the Mother of God": "Ікона Божої Матері",
    "King and Martyr": "Цар і мученик",
    "King and Prophet": "Цар і пророк",
    "Laymen": "Миряни",
    "Martyrs": "Мученики",
    "Master Builders, Monks": "Зодчі, ченці",
    "Metropolitan": "Митрополит",
    "Metropolitan, Equal-to-the-Apostles": "Митрополит, рівноапостольний",
    "Monastic Martyr": "Преподобномученик",
    "Monastic Martyrs": "Преподобномученики",
    "Monastic New Martyr": "Преподобномученик новий",
    "Monastics": "Ченці",
    "Monk": "Чернець",
    "Monk (Founder)": "Чернець (засновник)",
    "Monk (Hermit)": "Чернець (пустельник)",
    "Monk (elder)": "Чернець (старець)",
    "Monk (hermit)": "Чернець (пустельник)",
    "Monk (novice)": "Чернець (послушник)",
    "Monk (recluse)": "Чернець (затворник)",
    "Monk (stylite)": "Чернець (стовпник)",
    "Monk, Church Father": "Чернець, отець Церкви",
    "Monk, Confessor": "Чернець, сповідник",
    "Monk, Elder": "Чернець, старець",
    "Monk, Hymnographer": "Чернець, піснописець",
    "Monk, Martyr": "Чернець, мученик",
    "Monk, Recluse": "Чернець, затворник",
    "Monk, Unmercenary Physician": "Чернець, безсрібник-лікар",
    "Monk, former Great Zhupan": "Чернець, колишній великий жупан",
    "Monk-martyr": "Преподобномученик",
    "Monk-martyrs": "Преподобномученики",
    "Monks": "Ченці",
    "Monks (Founders)": "Ченці (засновники)",
    "Mother": "Мати",
    "Myrrhbearer": "Мироносиця",
    "New Martyrs": "Новомученики",
    "New Martyrs and Confessors": "Новомученики і сповідники",
    "Nun": "Черниця",
    "Nun-martyr": "Преподобномучениця",
    "Patriarch": "Патріарх",
    "Patriarch, Church Father": "Патріарх, отець Церкви",
    "Patriarch, Confessor": "Патріарх, сповідник",
    "Patriarch, Hieromartyr": "Патріарх, священномученик",
    "Physician": "Лікар",
    "Physicians": "Лікарі",
    "Pope": "Папа Римський",
    "Pope of Rome, Confessor": "Папа Римський, сповідник",
    "Presbyter and Deacon": "Пресвітер і диякон",
    "Presbyters, Confessors": "Пресвітери, сповідники",
    "Priest": "Ієрей",
    "Prince": "Князь",
    "Prince of Moldavia": "Господар Молдавський",
    "Prince, Passion-Bearer": "Князь, страстотерпець",
    "Princes": "Князі",
    "Princess": "Княгиня",
    "Princess, Nun": "Княгиня, черниця",
    "Proconsul (military commander)": "Проконсул (воєвода)",
    "Prophet and Forerunner": "Пророк і Предтеча",
    "Prophetess": "Пророчиця",
    "Protomartyr": "Первомученик",
    "Protopresbyter": "Протопресвітер",
    "Recluse": "Затворник",
    "Right-believing Prince": "Благовірний князь",
    "Right-believing Prince (Monk)": "Благовірний князь (чернець)",
    "Right-believing Prince and Princess": "Благовірні князь і княгиня",
    "Right-believing Prince, Passion-bearer": "Благовірний князь, страстотерпець",
    "Right-believing Princess (Nun)": "Благовірна княгиня (черниця)",
    "Right-believing Princess, Martyr": "Благовірна княгиня, мучениця",
    "Righteous (Child)": "Праведний (отрок)",
    "Righteous (Children)": "Праведні (отроки)",
    "Righteous (Unmercenary)": "Праведний (безсрібник)",
    "Righteous Forefather": "Праведний праотець",
    "Righteous Virgin": "Праведна діва",
    "Righteous, Priest": "Праведний, ієрей",
    "Roman soldier": "Римський воїн",
    "Schemamonk": "Схимонах",
    "Synaxis": "Собор",
    "Tsar and Imperial Family": "Цар і Царська родина",
    "Unmercenary Martyrs": "Безсрібники-мученики",
    "Venerable": "Преподобний",
    "Venerable Prince": "Преподобний князь",
    "Venerable Princess": "Преподобна княгиня",
    "Virgin": "Діва",
    "Virgin Martyrs": "Мучениці-діви",
    "Virgin-martyr": "Мучениця-діва",
    "Youths": "Отроки",
})


# The places, which are not a list but a grammar: a card names a town, a
# province and a country in one line, and the same town appears on twenty
# other cards inside a different line. The pieces are rendered once here and
# the wholes are assembled from them, so a town cannot be spelled one way on
# one card and another way on the next.
PARTS = {}


def expand(phrases):
    """The compounds, assembled from the parts above.

    Only the place line is built here - a town and a province and a country
    set down in one line. The title a card hangs on a name is not built,
    because Ukrainian does not form it with a preposition the way Romanian
    forms it with din: "of Ancyra" is Анкірський, an adjective agreeing with
    the saint, and "of the Kyiv Caves" is Києво-Печерський. Those are
    written out in TEXT, as Russian writes them, since no rule assembles
    them from the name of the town.
    """
    out = {}
    for p in phrases:
        bits = p.split(", ")
        if all(b in PARTS for b in bits):
            out[p] = ", ".join(PARTS[b] for b in bits)
    return out


# The places, first part.
PARTS.update({
    "Abel-meholah": "Авел-Мехола",
    "Abkhazeti": "Абхазеті",
    "Achaia": "Ахая",
    "Adamovka": "Адамовка",
    "Adrianople": "Адріанополь",
    "Adrianopolis": "Адріанополь",
    "Aegae": "Егі",
    "Aegean": "Егейські острови",
    "Aegina": "Егіна",
    "Aetolia": "Етолія",
    "Africa": "Африка",
    "Agrigentum": "Агрігент",
    "Akhaltsikhe": "Ахалцихе",
    "Aksum": "Аксум",
    "Alaska": "Аляска",
    "Albania": "Албанія",
    "Albanopolis": "Албанополь",
    "Aleppo": "Алеппо",
    "Alexandria": "Олександрія",
    "All America": "Вся Америка",
    "Amasea": "Амасія",
    "Amasia": "Амасія",
    "Amastridea": "Амастрида",
    "Amastris": "Амастрида",
    "Amathus": "Амафунт",
    "America": "Америка",
    "Amida": "Аміда",
    "Amisos": "Аміс",
    "Amisus": "Аміс",
    "Amnia": "Амнія",
    "Amorion": "Аморій",
    "Amphipolis": "Амфіполь",
    "Anaplus": "Анапл",
    "Anastasiopolis": "Анастасіополь",
    "Anathoth": "Анафоф",
    "Anatolia": "Анатолія",
    "Anazarbus": "Аназарв",
    "Ancyra": "Анкіра",
    "Andronikov Monastery": "Андроників монастир",
    "Anga": "Анга",
    "Annesi": "Аннісі",
    "Annisa": "Анніса",
    "Antinoe": "Антиноя",
    "Antioch": "Антіохія",
    "Antioch in Pisidia": "Антіохія Пісидійська",
    "Antioch of Pisidia": "Антіохія Пісидійська",
    "Anzersk": "Анзерський",
    "Anzersk Island": "Анзерський острів",
    "Apamea": "Апамея",
    "Aphrodisias": "Афродисіада",
    "Apollonia": "Аполлонія",
    "Apulia": "Апулія",
    "Aquileia": "Аквілея",
    "Arabia": "Аравія",
    "Arabian Desert": "Аравійська пустеля",
    "Arauraka": "Араурака",
    "Arbela": "Арбела",
    "Archangel Gabriel": "Архангел Гавриїл",
    "Arethusa": "Аретуса",
    "Argos": "Аргос",
})


# The places, second part.
PARTS.update({
    "Arianzus": "Аріанз",
    "Arkhangelsk": "Архангельськ",
    "Arkhangelsk lands": "Архангельські землі",
    "Armagh": "Арма",
    "Armenia": "Вірменія",
    "Armenia Minor": "Мала Вірменія",
    "Arsinoe": "Арсиноя",
    "Arta": "Арта",
    "Artanuji": "Артануджі",
    "Ascalon": "Аскалон",
    "Asia Minor": "Мала Азія",
    "Asikha": "Асіха",
    "Athens": "Афіни",
    "Atka Island": "острів Атка",
    "Atskuri": "Ацкурі",
    "Atsquri": "Ацкурі",
    "Attica": "Аттика",
    "Auleneia": "Авленія",
    "Auxerre": "Осер",
    "Avnezh": "Авнеж",
    "Babylon": "Вавилон",
    "Balkans": "Балкани",
    "Barcelona": "Барселона",
    "Bari": "Барі",
    "Basarbov": "Басарбово",
    "Beauvais": "Бове",
    "Beirut": "Бейрут",
    "Belarus": "Білорусь",
    "Belev": "Бельов",
    "Belgorod": "Бєлгород",
    "Belgorod (Akkerman)": "Білгород (Аккерман)",
    "Belgrade": "Белград",
    "Belozersk": "Білозерськ",
    "Belozersk lands": "Білозерські землі",
    "Belozersk lands and Mozhaisk": "Білозерські землі і Можайськ",
    "Benevento": "Беневент",
    "Beocin Monastery": "Беочинський монастир",
    "Berezan": "Березань",
    "Berezniko": "Березник",
    "Beroea": "Верія",
    "Besanduc": "Весандук",
    "Bethany": "Віфанія",
    "Bethel": "Вефіль",
    "Bethlapeta": "Віфлапета",
    "Bethlehem": "Вифлеєм",
    "Bethsaida": "Віфсаїда",
    "Bethsaloe": "Віфсалоє",
    "Bezhetsk lands": "Бежецькі землі",
    "Bialystok": "Білосток",
    "Bisericani Monastery": "Бісериканський монастир",
    "Bithynia": "Віфінія",
    "Blachernae": "Влахерни",
    "Black Lake": "Чорне озеро",
    "Black Sea coast": "Чорноморське узбережжя",
    "Bodbe": "Бодбе",
    "Boeotia": "Беотія",
    "Bogolyubovo": "Боголюбово",
    "Bohemia": "Богемія",
    "Bolgar": "Болгар",
    "Borovichi": "Боровичі",
    "Borovsk": "Боровськ",
    "Bosnia": "Боснія",
    "Boston": "Бостон",
    "Bostra": "Востра",
    "Braunton": "Браунтон",
    "Brest": "Берестя",
    "Briansk": "Брянськ",
    "Britain": "Британія",
    "British Isles": "Британські острови",
    "Brooklyn": "Бруклін",
    "Bryansk": "Брянськ",
    "Bucharest": "Бухарест",
    "Budimlje": "Будимля",
    "Bulgaria": "Болгарія",
    "Butovo": "Бутово",
    "Buzau Mountains": "Бузеуські гори",
    "Byblos": "Бібл",
    "Byzantine Empire": "Візантійська імперія",
    "Byzantium": "Візантій",
    "Byzantium (Constantinople)": "Візантій (Константинополь)",
})


# The places, third part.
PARTS.update({
    "Caesarea": "Кесарія",
    "Caesarea Maritima": "Кесарія Приморська",
    "Caesarea in Cappadocia": "Кесарія Каппадокійська",
    "California": "Каліфорнія",
    "Campania": "Кампанія",
    "Cana": "Кана",
    "Cana of Galilee": "Кана Галілейська",
    "Canaan": "Ханаан",
    "Canopus": "Каноп",
    "Capernaum": "Капернаум",
    "Cappadocia": "Каппадокія",
    "Caria": "Карія",
    "Carpathian Rus'": "Карпатська Русь",
    "Carpatho-Russia": "Карпатська Русь",
    "Carthage": "Карфаген",
    "Catania": "Катанія",
    "Cephalonia": "Кефалонія",
    "Cernica": "Черніка",
    "Cernica Monastery": "Чернікський монастир",
    "Chalcedon": "Халкидон",
    "Chalcis": "Халкіда",
    "Chalcis desert": "Халкідська пустеля",
    "Chelm": "Холм",
    "Chelma Hill": "Чельмська гора",
    "Cherepovets": "Череповець",
    "Chernigov": "Чернігів",
    "Chernigov lands": "Чернігівські землі",
    "Chernihiv": "Чернігів",
    "Chernihiv lands": "Чернігівські землі",
    "Cherson": "Херсон",
    "Chersonesus": "Херсонес",
    "Chicago": "Чикаго",
    "China": "Китай",
    "Chios": "Хіос",
    "Chonae": "Хони",
    "Choziba": "Хозива",
    "Chukhloma": "Чухлома",
    "Cilicia": "Кілікія",
    "Claudiopolis": "Клавдіополь",
    "Colophon": "Колофон",
    "Colossae": "Колоси",
    "Coma": "Кома",
    "Comana": "Комани",
    "Constantia": "Констанція",
    "Constantinople": "Константинополь",
    "Cordoba": "Кордова",
    "Corfu": "Корфу",
    "Corinth": "Коринф",
    "Corsica": "Корсика",
    "Cotyaeum": "Котіей",
    "Crete": "Крит",
    "Crimea": "Крим",
    "Cucomo": "Кукомо",
    "Cucusus": "Кукуз",
    "Cyprus": "Кіпр",
    "Cyrene": "Кирена",
    "Cyrenia": "Кіренія",
    "Cyrrhus": "Кир",
    "Cyzicus": "Кізик",
    "Czech Lands": "Чеські землі",
    "Dabuda": "Дабуда",
    "Dalmatia": "Далмація",
    "Dalmatian Monastery": "Далматський монастир",
    "Damascus": "Дамаск",
    "Danube lands": "Подунав'я",
    "David Gareji": "Давид-Гареджі",
    "Davit-Gareji": "Давид-Гареджі",
    "Decapolis": "Декаполь",
    "Decapolis of Isauria": "Ісаврійський Декаполь",
    "Demetsana": "Димицана",
    "Demitsana": "Димицана",
    "Desert beyond the Jordan": "Пустеля за Йорданом",
    "Devich": "Девич",
    "Devon": "Девон",
    "Dimitsana": "Димицана",
    "Dioclea": "Діоклея",
    "Dioclea (Duklja)": "Діоклея (Дукля)",
    "Disevi": "Дісеві",
    "Diveyevo": "Дівеєво",
    "Dobrogea": "Добруджа",
})


# The places, fourth part.
PARTS.update({
    "Dorostolum": "Доростол",
    "Dorostolum (Silistra)": "Доростол (Сілістра)",
    "Drenica": "Дреница",
    "Durostorum": "Доростол",
    "Dymsk": "Димськ",
    "Dymskoe Lake": "Димське озеро",
    "East Anglia": "Східна Англія",
    "Edessa": "Едеса",
    "Edra": "Едра",
    "Egypt": "Єгипет",
    "Egyptian Desert": "Єгипетська пустеля",
    "Elbasan": "Ельбасан",
    "Eleutheropolis": "Елевферополь",
    "Elkosh": "Елкош",
    "Emesa": "Емеса",
    "England": "Англія",
    "Ephesus": "Ефес",
    "Epirus": "Епір",
    "Epivato": "Епіват",
    "Essex": "Ессекс",
    "Ethiopia": "Ефіопія",
    "Euboea": "Евбея",
    "Euchaita": "Євхаїти",
    "Euroea": "Евроя",
    "European Russia": "Європейська Росія",
    "Evia": "Евбея",
    "Ferapontov": "Ферапонтів",
    "Ferapontov Monastery": "Ферапонтів монастир",
    "Ferapontovo": "Ферапонтово",
    "Feremane": "Феремане",
    "Ferentino": "Ферентино",
    "Flavia Neapolis": "Флавія Неаполь",
    "Florishchi": "Флорищі",
    "Formia": "Формія",
    "France": "Франція",
    "Frasinei": "Фресіней",
    "Galata": "Галата",
    "Galatia": "Галатія",
    "Galich": "Галич",
    "Galicia": "Галичина",
    "Galilee": "Галілея",
    "Gangra": "Гангра",
    "Gareji": "Гареджі",
    "Gary": "Гері",
    "Gath-hepher": "Гафхефер",
    "Gaul": "Галлія",
    "Gaza": "Газа",
    "Gdov": "Гдов",
    "Gdov lands": "Гдовські землі",
    "George Hill": "Георгієва гора",
    "Georgia": "Грузія",
    "Germany": "Німеччина",
    "Gibeah of Phinehas": "Гіва Фінеєсова",
    "Gilead": "Галаад",
    "Glendalough": "Глендалох",
    "Glushitsa": "Глушиця",
    "Gori district": "Горійський повіт",
    "Gortyna": "Гортина",
    "Gothia": "Готія",
    "Gothic lands": "Готські землі",
    "Great Lavra": "Велика Лавра",
    "Great Lavra of Saint Sabbas": "Велика Лавра преподобного Сави",
    "Great Moravia": "Велика Моравія",
    "Greece": "Греція",
    "Guria": "Гурія",
    "Hartland": "Хартленд",
    "Hauran": "Хауран",
    "Hebron": "Хеврон",
    "Heliopolis": "Іліополь",
    "Hellas": "Еллада",
    "Hellespont": "Геллеспонт",
    "Heraclea": "Іраклія",
    "Hereti": "Ереті",
    "Hermopolis": "Ермополь",
    "Herzegovina": "Герцеговина",
    "Hierapolis": "Ієраполь",
    "Hilandar": "Хіландар",
    "Holy Land": "Свята Земля",
    "Holy Trinity-Saint Sergius Lavra": "Свято-Троїцька Сергієва Лавра",
    "Hosios Loukas": "Осіос-Лукас",
})


# The places, fifth part.
PARTS.update({
    "Hungary": "Угорщина",
    "Hypaepa": "Іпепа",
    "Iași": "Ясси",
    "Iconium": "Іконій",
    "Iken": "Айкен",
    "Illinois": "Іллінойс",
    "Illyria": "Іллірія",
    "Illyricum": "Іллірик",
    "India": "Індія",
    "Indiana": "Індіана",
    "Ioannina": "Яніна",
    "Irap": "Ірап",
    "Ireland": "Ірландія",
    "Irenopolis": "Іринополь",
    "Irkutsk": "Іркутськ",
    "Irkutsk province": "Іркутська губернія",
    "Isauria": "Ісаврія",
    "Israel": "Ізраїль",
    "Italy": "Італія",
    "Iza": "Іза",
    "Jackson": "Джексон",
    "Jerusalem": "Єрусалим",
    "Joppa": "Йоппія",
    "Jordan River": "річка Йордан",
    "Judah": "Юдея",
    "Judea": "Юдея",
    "Judean Desert": "Юдейська пустеля",
    "Judean Wilderness": "Юдейська пустеля",
    "Kallippi": "Калліппі",
    "Kaluga": "Калуга",
    "Kaluga lands": "Калузькі землі",
    "Kalyazin": "Калязин",
    "Kampsada": "Кампсада",
    "Kaniv": "Канів",
    "Karelia": "Карелія",
    "Kargopol": "Каргополь",
    "Kargopol lands": "Каргопольські землі",
    "Kartli": "Картлі",
    "Kartli (Iberia)": "Картлі (Іверія)",
    "Kashin": "Кашин",
    "Kasperovo": "Касперово",
    "Kastoria": "Касторія",
    "Kastorion": "Касторіон",
    "Kavsokalyvia": "Кавсокаливія",
    "Kazan": "Казань",
    "Kekhta": "Кехта",
    "Kellia": "Келії",
    "Keno Lake": "Кенозеро",
    "Kerch": "Керч",
    "Kerkyra": "Керкіра",
    "Kerkyra (Corfu)": "Керкіра (Корфу)",
    "Khakhuli": "Хахулі",
    "Khakhuli Monastery": "Хахульський монастир",
    "Kharkiv": "Харків",
    "Kherson": "Херсон",
    "Kherson lands": "Херсонські землі",
    "Khlynov": "Хлинов",
    "Kholm": "Холм",
    "Khust": "Хуст",
    "Khutyn": "Хутинь",
    "Kios": "Кій",
    "Klarjeti": "Кларджеті",
    "Klops Monastery": "Клопський монастир",
    "Kodiak": "Кадьяк",
    "Kola": "Кола",
    "Komel": "Комель",
    "Komel Forest": "Комельський ліс",
    "Kondakovo": "Кондаково",
    "Konevets": "Коневець",
    "Korets": "Корець",
    "Korissos": "Коріссос",
    "Kornet": "Корнет",
    "Korotsk": "Короцько",
    "Kosinsk": "Косинське",
    "Kosovo": "Косово",
    "Kostroma": "Кострома",
    "Kostroma lands": "Костромські землі",
    "Kozelshchyna": "Козельщина",
    "Kozelsk": "Козельськ",
    "Kozhe Lake": "Кожозеро",
    "Krasny Kholm": "Красний Холм",
    "Kratovo": "Кратово",
    "Kremenets": "Кременець",
    "Kromna": "Кромна",
    "Kronstadt": "Кронштадт",
})


# The places, sixth part.
PARTS.update({
    "Krushedol": "Крушедол",
    "Kubensk": "Кубенське",
    "Kudinovo": "Кудиново",
    "Kursk": "Курськ",
    "Kushta": "Кушта",
    "Kvabtakhevi Monastery": "Квабтахевський монастир",
    "Kveli fortress": "фортеця Квелі",
    "Kwethluk": "Кветлук",
    "Kyiv": "Київ",
    "Kyiv Caves": "Київські печери",
    "Kyiv Caves Lavra": "Києво-Печерська Лавра",
    "Kyiv Far Caves": "Київські Дальні печери",
    "Kyiv Near Caves": "Київські Ближні печери",
    "Kyiv region": "Київська земля",
    "Laconia": "Лаконія",
    "Lake Iliamna": "озеро Іліамна",
    "Lake Ilmen": "озеро Ільмень",
    "Lake Ilo": "Ілоозеро",
    "Lake Kubenskoye": "Кубенське озеро",
    "Lake Ladoga": "Ладозьке озеро",
    "Lake Onega": "Онезьке озеро",
    "Lake Orta": "озеро Орта",
    "Lake Pskov": "Псковське озеро",
    "Lake Seliger": "озеро Селігер",
    "Lake Vorbozomsk": "Ворбозомське озеро",
    "Lampsacus": "Лампсак",
    "Land of Asher": "земля Асирова",
    "Land of Uz": "земля Уц",
    "Land of Zebulun": "земля Завулонова",
    "Land of the tribe of Simeon": "земля коліна Симеонового",
    "Langres": "Лангр",
    "Laodicea": "Лаодикія",
    "Lavra of Saint Sabbas": "Лавра преподобного Сави",
    "Lazica": "Лазика",
    "Le Mans": "Ле-Ман",
    "Lebanon": "Ліван",
    "Leinster": "Ленстер",
    "Lelich": "Лелич",
    "Lentini": "Лентіні",
    "Leokhnovo": "Леохново",
    "Leontini": "Леонтини",
    "Lesbos": "Лесбос",
    "Leucosia (Nicosia)": "Левкосія (Нікосія)",
    "Lezna River": "річка Лезна",
    "Libertyville": "Лібертивілль",
    "Libya": "Лівія",
    "Lindisfarne": "Ліндісфарн",
    "Lipari": "Ліпарі",
    "Lithuania": "Литва",
    "Little Russia (Ukraine)": "Мала Русь (Україна)",
    "Liubech": "Любеч",
    "Liubimograd": "Любимоград",
    "Loma": "Лома",
    "Loutraki": "Лутракі",
    "Lubny": "Лубни",
    "Lubyatov": "Любятово",
    "Lucania": "Луканія",
    "Lukhov": "Лухов",
    "Lycaonia": "Лікаонія",
    "Lycia": "Лікія",
    "Lycopolis": "Лікополь",
    "Lydda": "Лідда",
    "Lydia": "Лідія",
    "Lykaonia": "Лікаонія",
    "Lyons": "Ліон",
    "Lystra": "Лістра",
    "Lérins": "Лерин",
    "Macedonia": "Македонія",
    "Magdala": "Магдала",
    "Magedon": "Магедон",
    "Magnesia": "Магнесія",
    "Magydos": "Магідос",
    "Maiuma": "Маіума",
    "Makarovo": "Макарово",
    "Makhrishche": "Махрище",
    "Malopinega": "Малопинежжя",
    "Malta": "Мальта",
    "Mandera": "Мандера",
    "Mangup": "Мангуп",
    "Mantinea": "Мантинея",
    "Mar Saba": "Мар-Саба",
    "Maratha": "Марафа",
    "Marathon": "Марафон",
    "Marcianopolis": "Марціанополь",
    "Marikat": "Марикат",
})


# The places, seventh part.
PARTS.update({
    "Marseilles": "Марсель",
    "Martyropolis": "Мартирополь",
    "Mauretania": "Мавританія",
    "Medikion": "Мідикій",
    "Medikion Monastery": "Мідикійський монастир",
    "Medin": "Мединь",
    "Mega Dendron": "Мега-Дендрон",
    "Meglin": "Меглин",
    "Melitene": "Мелітина",
    "Melitopolis": "Мелітополь",
    "Menuthis": "Менуфіс",
    "Menyusha": "Менюша",
    "Merkushino": "Меркушино",
    "Mesopotamia": "Месопотамія",
    "Mesteacăn": "Местякен",
    "Methymna": "Міфимна",
    "Mezen": "Мезень",
    "Mgvime": "Мгвіме",
    "Milan": "Медіолан",
    "Mineo": "Мінео",
    "Minneapolis": "Міннеаполіс",
    "Moesia": "Мезія",
    "Mogarissos": "Могарисс",
    "Mogilev": "Могильов",
    "Moldavia": "Молдавія",
    "Moldova": "Молдова",
    "Monembasia": "Монемвасія",
    "Monte Cassino": "Монтекассіно",
    "Monteluco": "Монтелуко",
    "Montenegro": "Чорногорія",
    "Monza River": "річка Монза",
    "Moravia": "Моравія",
    "Morea (Peloponnese)": "Морея (Пелопоннес)",
    "Moresheth": "Морасфа",
    "Moscow": "Москва",
    "Moscow lands": "Московські землі",
    "Mount Athos": "Афон",
    "Mount Colzim": "гора Колзім",
    "Mount Ephraim": "гора Єфремова",
    "Mount Galesion": "гора Галісій",
    "Mount Galesius": "гора Галісій",
    "Mount Hor": "гора Ор",
    "Mount Kyminas": "гора Кимин",
    "Mount Maleon": "гора Малеон",
    "Mount Myrsinon": "гора Мірсінон",
    "Mount Nebo": "гора Нево",
    "Mount Olympus": "гора Олімп",
    "Mount Sagmata": "гора Сагмата",
    "Mount Sinai": "гора Синай",
    "Mount Skopa": "гора Скопа",
    "Mount Taurus": "Таврські гори",
    "Mount of Olives": "Єлеонська гора",
    "Mozhaisk": "Можайськ",
    "Mrkonjici": "Мрконьїчі",
    "Mtskheta": "Мцхета",
    "Murom": "Муром",
    "Murom Island": "Муромський острів",
    "Mutalaska": "Муталаска",
    "Mylapore": "Мілапур",
    "Mylasa": "Міласа",
    "Myra": "Мири",
    "Myra in Lycia": "Мири Лікійські",
    "Myrgorod": "Миргород",
    "Mytilene": "Мітилина",
    "Naissus": "Наісс",
    "Najran": "Наджран",
    "Nalšia": "Нальшя",
    "Nanterre": "Нантер",
    "Naples": "Неаполь",
    "Nauplion": "Навпліон",
    "Nazareth": "Назарет",
    "Nazianzus": "Назіанз",
    "Nea Makri": "Неа-Макрі",
    "Neamts Monastery": "Нямецький монастир",
    "Neamț": "Нямц",
    "Neapolis": "Неаполь",
    "Near Constantinople": "Поблизу Константинополя",
    "Neocaesarea": "Неокесарія",
    "Nerchinsk": "Нерчинськ",
    "New Lake": "Новоозеро",
    "New York": "Нью-Йорк",
    "Nicaea": "Нікея",
    "Nicea": "Нікея",
    "Nicomedia": "Нікомидія",
    "Nicopolis": "Нікополь",
})


# The places, eighth part.
PARTS.update({
    "Nicosia": "Нікосія",
    "Nikiforovskaya": "Никифорівська",
    "Nisibis": "Нізібія",
    "Nitria": "Нітрія",
    "Nizhni-Novgorod": "Нижній Новгород",
    "Nizhny Novgorod": "Нижній Новгород",
    "Nizhny Novgorod lands": "Нижегородські землі",
    "Nizhyn": "Ніжин",
    "North Africa": "Північна Африка",
    "North America": "Північна Америка",
    "North Macedonia": "Північна Македонія",
    "Northumbria": "Нортумбрія",
    "Novara": "Новара",
    "Novgorod": "Новгород",
    "Novgorod lands": "Новгородські землі",
    "Noviodunum": "Новіодун",
    "Novoezersk": "Новоезерськ",
    "Nurma": "Нурма",
    "Nursia": "Нурсія",
    "Nyssa": "Нісса",
    "Obnora River": "річка Обнора",
    "Odessa": "Одеса",
    "Odrino": "Одрино",
    "Ohrid": "Охрид",
    "Old Lavra of Chariton": "Давня Лавра преподобного Харитона",
    "Olonets": "Олонець",
    "Olonets lands": "Олонецькі землі",
    "Olshansk": "Ольшанськ",
    "Olympus": "Олімп",
    "Omala": "Омала",
    "Ondrusov": "Ондрусов",
    "Ophrah": "Офра",
    "Opso": "Опсо",
    "Orel lands": "Орловські землі",
    "Oshevensk": "Ошевенськ",
    "Osrhoene": "Осроена",
    "Ostia": "Остія",
    "Ostracine": "Острацина",
    "Ostrog": "Острог",
    "Ovche Pole": "Овче-Поле",
    "Ovruch": "Овруч",
    "Ozovia": "Озовія",
    "Palermo": "Палермо",
    "Palestine": "Палестина",
    "Palii Island": "Палій острів",
    "Pamphylia": "Памфілія",
    "Pannonia": "Паннонія",
    "Paphlagonia": "Пафлагонія",
    "Paphos": "Пафос",
    "Paramythia": "Парамифія",
    "Paris": "Париж",
    "Parium": "Парій",
    "Paros": "Парос",
    "Parthia": "Парфія",
    "Patara": "Патара",
    "Patmos": "Патмос",
    "Patras": "Патри",
    "Pec": "Печ",
    "Pechenga": "Печенга",
    "Pechenga Monastery": "Печенгський монастир",
    "Pekhorka": "Пехорка",
    "Pelecete": "Пелекета",
    "Pelekete": "Пелекета",
    "Pelekete Monastery": "Пелекетський монастир",
    "Peloponnese": "Пелопоннес",
    "Pelshma": "Пельшма",
    "Pelusium": "Пелусій",
    "Pennsylvania": "Пенсильванія",
    "Perekop (Perekomsky) Monastery": "Перекопський (Перекомський) монастир",
    "Pereslavl": "Переславль",
    "Pereslavl-Zalessky": "Переславль-Залеський",
    "Pereyaslavl": "Переяславль",
    "Pereyaslavl-Zalessky": "Переславль-Залеський",
    "Pergamum": "Пергам",
    "Perge": "Пергія",
    "Peristerai": "Перистери",
    "Perm": "Перм",
    "Perm lands": "Пермські землі",
    "Persia": "Персія",
    "Persia and the East": "Персія і Схід",
    "Peshnosha": "Пешноша",
    "Petrograd": "Петроград",
    "Peć": "Печ",
    "Pharan": "Фаран",
    "Pharasa": "Фараса",
})


# The places, ninth part.
PARTS.update({
    "Philadelphia": "Філадельфія",
    "Philippopolis": "Філіппополь",
    "Philotheou Monastery": "Філофеївський монастир",
    "Phocis": "Фокида",
    "Phoenicia": "Фінікія",
    "Phrygia": "Фригія",
    "Pinega": "Пінега",
    "Pinsk": "Пінськ",
    "Pisidia": "Пісидія",
    "Plousias": "Плусіада",
    "Pochaev": "Почаїв",
    "Pochaiv": "Почаїв",
    "Podolia": "Поділля",
    "Poiana Marului": "Пояна-Мерулуй",
    "Pokutia": "Покуття",
    "Poland": "Польща",
    "Polotsk": "Полоцьк",
    "Poltava": "Полтава",
    "Poltava lands": "Полтавські землі",
    "Poltava region": "Полтавська земля",
    "Polybotum": "Поліботи",
    "Pomorie": "Помор'я",
    "Pompeiopolis": "Помпейополь",
    "Pontus": "Понт",
    "Popovo": "Попово",
    "Porkhov": "Порхов",
    "Poshekhonye": "Пошехоння",
    "Pozzuoli": "Поццуолі",
    "Prague": "Прага",
    "Pretorium": "Преторій",
    "Priluki": "Прилуки",
    "Prokopion": "Прокопіон",
    "Protection Convent": "Покровський монастир",
    "Prusa": "Пруса",
    "Pryluky": "Прилуки",
    "Prymnessus": "Примнесс",
    "Pshinja": "Пшиня",
    "Pskov": "Псков",
    "Pskov Caves Monastery": "Псково-Печерський монастир",
    "Ptinapor": "Птинапор",
    "Ptolemais": "Птолемаїда",
    "Puteoli": "Путеоли",
    "Putna": "Путна",
    "Pythias": "Піфія",
    "Périgueux": "Перигьо",
    "Radonezh": "Радонеж",
    "Radonezh and Serpukhov": "Радонеж і Серпухов",
    "Radoviste": "Радовиште",
    "Raithu": "Раїфа",
    "Ramah": "Рама",
    "Ramathaim": "Рамафаїм",
    "Ramathaim-Zophim": "Рамафаїм-Цофим",
    "Ramnic": "Римник",
    "Ravanica": "Раваниця",
    "Ravenna": "Равенна",
    "Resafa": "Ресафа",
    "Rethymnon": "Ретимнон",
    "Rhosus": "Росс",
    "Rila": "Рила",
    "Robeika": "Робейка",
    "Robeika River": "річка Робейка",
    "Roman Britain": "Римська Британія",
    "Romania": "Румунія",
    "Rome": "Рим",
    "Rome and Milan": "Рим і Медіолан",
    "Rome and the East": "Рим і Схід",
    "Rossos": "Росс",
    "Rostov": "Ростов",
    "Rostov lands": "Ростовські землі",
    "Rus'": "Русь",
    "Russia": "Росія",
    "Russian North": "Руська Північ",
    "Russian nobility": "руське боярство",
    "Ryazan": "Рязань",
    "Ryazan province": "Рязанська губернія",
    "Rzhev": "Ржев",
    "Saint John": "Святий Іоан",
    "Saint Petersburg": "Санкт-Петербург",
    "Salamis": "Саламін",
    "Salamis (Constantia)": "Саламін (Констанція)",
    "Salona": "Салона",
    "Samaria": "Самарія",
    "Samegrelo": "Самегрело",
    "Samosata": "Самосати",
    "Samothrace": "Самофракія",
})


# The places, tenth part.
PARTS.update({
    "Samtskhe": "Самцхе",
    "San Francisco": "Сан-Франциско",
    "Saragossa": "Сарагоса",
    "Sardis": "Сарди",
    "Sarov": "Саров",
    "Scetis": "Скит",
    "Scotland": "Шотландія",
    "Scythia": "Скіфія",
    "Scythia Minor": "Мала Скіфія",
    "Sebaste": "Севастія",
    "Sebastea": "Севастія",
    "Sebino": "Себіно",
    "Seleucia": "Селевкія",
    "Seleucia-Ctesiphon": "Селевкія-Ктесифон",
    "Selymbria": "Селімврія",
    "Serbia": "Сербія",
    "Sergiev Posad": "Сергіїв Посад",
    "Serpukhov": "Серпухов",
    "Serres": "Серри",
    "Shanghai": "Шанхай",
    "Shenkursk": "Шенкурськ",
    "Shiloh": "Силом",
    "Shio-Mgvime Monastery": "Шіомгвімський монастир",
    "Shovskoe": "Шовське",
    "Shuya": "Шуя",
    "Shuzhgora": "Шужгора",
    "Siberia": "Сибір",
    "Siblag camps": "Сиблаг",
    "Sicily": "Сицилія",
    "Side": "Сіда",
    "Sigriane": "Сигріана",
    "Silistra": "Сілістра",
    "Simferopol": "Сімферополь",
    "Sinai": "Синай",
    "Sinai and Raithu": "Синай і Раїфа",
    "Sinai wilderness": "Синайська пустеля",
    "Singidunum": "Сингідун",
    "Sinope": "Синоп",
    "Sinope and Amasea": "Синоп і Амасія",
    "Sinozersk": "Синозерськ",
    "Sirmium": "Сирмій",
    "Sisan": "Сісан",
    "Sitka": "Ситка",
    "Siya Monastery": "Сійський монастир",
    "Skepsis": "Скепсія",
    "Sketis": "Скит",
    "Skrino": "Скрино",
    "Slutsk": "Слуцьк",
    "Smolensk": "Смоленськ",
    "Smyrna": "Смирна",
    "Snetogorsk": "Снетогорський",
    "Snetogorsk Monastery": "Снетогорський монастир",
    "Sofia": "Софія",
    "Sokhot River": "річка Сохоть",
    "Solovki": "Соловки",
    "Solovki Islands": "Соловецькі острови",
    "Solovki Monastery": "Соловецький монастир",
    "Sophene": "Софена",
    "Sora River": "річка Сора",
    "Soreoi": "Сореї",
    "Spain": "Іспанія",
    "Spoleto": "Сполето",
    "Spruce Island": "Ялиновий острів",
    "Srem": "Срем",
    "St Albans": "Сент-Олбанс",
    "St. Petersburg": "Санкт-Петербург",
    "Stara Zagora": "Стара-Загора",
    "Staritsa": "Стариця",
    "Starytsa": "Стариця",
    "Steirion": "Стирій",
    "Stolobny Island": "острів Столобний",
    "Storozhi Hill": "гора Сторожі",
    "Strobil": "Стровил",
    "Strumica": "Струмиця",
    "Studenica": "Студениця",
    "Subiaco": "Субіако",
    "Suceava": "Сучава",
    "Sura": "Сура",
    "Susa": "Сузи",
    "Suzdal": "Суздаль",
    "Svensky Monastery": "Свенський монастир",
    "Svir": "Свір",
    "Sviyazhsk": "Свіяжськ",
    "Sweden": "Швеція",
    "Syandeba": "Сяндеба",
})


# The places, eleventh part.
PARTS.update({
    "Syandemsk": "Сяндемськ",
    "Syanzhema": "Сянжема",
    "Syanzhema River": "річка Сянжема",
    "Sykeon": "Сікеон",
    "Symbola": "Символи",
    "Symbola Monastery": "монастир Символів",
    "Synnada": "Синнади",
    "Syracuse": "Сиракузи",
    "Syria": "Сирія",
    "Tabatha": "Тавафа",
    "Tabenna": "Тавенна",
    "Tabennisi": "Тавенниси",
    "Tambov": "Тамбов",
    "Tao": "Тао",
    "Tao-Klarjeti": "Тао-Кларджеті",
    "Taormina": "Таорміна",
    "Taphanes": "Тафніс",
    "Targala": "Таргала",
    "Tarnovo": "Тирново",
    "Tarsus": "Тарс",
    "Tarsus and Achaia": "Тарс і Ахая",
    "Tarsus and Rossos": "Тарс і Росс",
    "Tarsus and the East": "Тарс і Схід",
    "Tashkent": "Ташкент",
    "Tauresium": "Тавресій",
    "Tazlău": "Тазлеу",
    "Tazlău Monastery": "Тазлеуський монастир",
    "Tbilisi": "Тбілісі",
    "Tekoa": "Фекоя",
    "Tenedos": "Тенедос",
    "Tennis": "Тенніс",
    "Teratyn": "Тератин",
    "Terracina": "Террачина",
    "The East": "Схід",
    "The Jordan": "Йордан",
    "Thebaid": "Фіваїда",
    "Thebes": "Фіви",
    "Thebes of Egypt": "Фіви Єгипетські",
    "Thessalonica": "Солунь",
    "Thessaloniki": "Солунь",
    "Thessaly": "Фессалія",
    "Thrace": "Фракія",
    "Thyateira": "Фіатира",
    "Tikhvin": "Тихвин",
    "Tiksna": "Тіксна",
    "Tishbe of Gilead": "Фесва Галаадська",
    "Tmutarakan": "Тмутаракань",
    "Tobolsk": "Тобольськ",
    "Tolva": "Толва",
    "Toropets": "Торопець",
    "Torzhok": "Торжок",
    "Totma": "Тотьма",
    "Trajanopolis": "Траянополь",
    "Tralles": "Тралли",
    "Transcarpathia": "Закарпаття",
    "Trebia": "Требія",
    "Trebizond": "Трапезунд",
    "Tremithus": "Тримифунт",
    "Trier": "Трір",
    "Triglia": "Триглія",
    "Trikala": "Трикала",
    "Trinity Lavra": "Троїцька Лавра",
    "Trinity-Sergius Lavra": "Троїце-Сергієва Лавра",
    "Tripoli": "Триполі",
    "Troas": "Троада",
    "Tsarskoye Selo": "Царське Село",
    "Tula lands": "Тульські землі",
    "Turchasovo": "Турчасово",
    "Turov": "Туров",
    "Tuscany": "Тоскана",
    "Tver": "Твер",
    "Tver lands": "Тверські землі",
    "Tyana": "Тіана",
    "Tyre": "Тир",
    "Uchma": "Учма",
    "Uglich": "Углич",
    "Ukraine": "Україна",
    "United States": "Сполучені Штати",
    "Unzha": "Унжа",
    "Upper Thebaid": "Верхня Фіваїда",
    "Ur of the Chaldees": "Ур Халдейський",
    "Ushchelye": "Ущелля",
    "Ust-Totma": "Усть-Тотьма",
    "Ust-Vym": "Усть-Вим",
    "Ustiug": "Устюг",
    "Ustyug": "Устюг",
    "Vaga": "Вага",
    "Vaga lands": "Важські землі",
    "Vagharshapat": "Вагаршапат",
    "Valaam": "Валаам",
})


# The places, twelfth part.
PARTS.update({
    "Valencia": "Валенсія",
    "Varnitsa": "Варниці",
    "Varzuga": "Варзуга",
    "Vasilevo": "Василево",
    "Vaste": "Васте",
    "Vasyliv": "Василів",
    "Vazheozero region": "Важеозерський край",
    "Velehrad": "Велеград",
    "Veliki Luki": "Великі Луки",
    "Veliky Ustiug": "Великий Устюг",
    "Veliky Ustyug": "Великий Устюг",
    "Venice": "Венеція",
    "Verkhoturye": "Верхотур'я",
    "Verkola": "Веркола",
    "Verona": "Верона",
    "Verulamium": "Веруламій",
    "Verulamium (St Albans)": "Веруламій (Сент-Олбанс)",
    "Vetluga": "Ветлуга",
    "Videlebye": "Виделеб'є",
    "Vilnius": "Вільнюс",
    "Vishera": "Вишера",
    "Vladimir": "Володимир",
    "Vladimir lands": "Володимирські землі",
    "Vladimir-Suzdal": "Володимиро-Суздальська земля",
    "Vladimir-in-Volhynia": "Володимир-Волинський",
    "Volga Bulgaria": "Волзька Булгарія",
    "Volhynia": "Волинь",
    "Volissos": "Воліссос",
    "Volodymyr-Volhynia": "Володимир-Волинський",
    "Vologda": "Вологда",
    "Vologda lands": "Вологодські землі",
    "Volokolamsk": "Волоколамськ",
    "Vorbozomsk Lake": "Ворбозомське озеро",
    "Voronezh": "Воронеж",
    "Vracar": "Врачар",
    "Vyatka": "В'ятка",
    "Vyazma": "Вязьма",
    "Vyritsa": "Вириця",
    "Vyshgorod": "Вишгород",
    "Vyshhorod": "Вишгород",
    "Wales": "Уельс",
    "Warsaw": "Варшава",
    "Western Rus": "Західна Русь",
    "White Lake": "Біле озеро",
    "White Lake (Beloozero)": "Біле озеро (Білоозеро)",
    "White Lake region": "Білозерський край",
    "White Sea": "Біле море",
    "Wilkes-Barre": "Уїлкс-Барре",
    "Wonderful Mountain": "Дивна гора",
    "Yakhroma": "Яхрома",
    "Yarenga": "Яренга",
    "Yaroslavl": "Ярославль",
    "Yaroslavl lands": "Ярославські землі",
    "Yaroslavl province": "Ярославська губернія",
    "Yashezero": "Яшезеро",
    "Yazvishche": "Язвище",
    "Yekaterinburg": "Єкатеринбург",
    "Yuriev (Tartu)": "Юр'їв (Тарту)",
    "Yuriev Monastery": "Юр'їв монастир",
    "Yuriev-Polsky": "Юр'їв-Польський",
    "Yuryegorsk": "Юр'єгорськ",
    "Zadonsk": "Задонськ",
    "Zahumlje": "Захум'я",
    "Zahumlje (Zakholm)": "Захум'я (Захолм'я)",
    "Zakynthos": "Закінф",
    "Zaozersk": "Заозерськ",
    "Zelenets": "Зеленець",
    "Zemplin region": "Земплинський край",
    "Zeta": "Зета",
    "Zeugma": "Зевгма",
    "Zhabyn Monastery": "Жабинський монастир",
    "Zheleznoborov": "Железноборовський",
    "Zhicha": "Жича",
    "Zhicha Monastery": "Жичський монастир",
    "Zvenigorod": "Звенигород",
    "Zverki": "Зверки",
    "all Greece": "вся Греція",
    "all Rus'": "вся Русь",
    "all Russia": "вся Росія",
    "all Slavic lands": "всі слов'янські землі",
    "all schools": "всі училища",
    "all the Slavic lands": "всі слов'янські землі",
    "and Ephesus": "і Ефес",
    "beyond the Danube": "за Дунаєм",
    "gardens and vineyards": "сади й виноградники",
    "near Agrigentum": "поблизу Агрігента",
    "near Alexandria": "поблизу Олександрії",
    "near Ancyra": "поблизу Анкіри",
    "near Antioch": "поблизу Антіохії",
    "near Apamea": "поблизу Апамеї",
    "near Bialystok": "поблизу Білостока",
    "near Borovsk": "поблизу Боровська",
    "near Cherepovets": "поблизу Череповця",
    "near Chernigov": "поблизу Чернігова",
    "near Constantinople": "поблизу Константинополя",
    "near Cyrrhus": "поблизу Кира",
    "near Dorostolum": "поблизу Доростола",
    "near Edessa": "поблизу Едеси",
    "near Ephesus": "поблизу Ефеса",
    "near Galich": "поблизу Галича",
    "near Gaza": "поблизу Гази",
    "near Kargopol": "поблизу Каргополя",
    "near Kiev": "поблизу Києва",
    "near Kyiv": "поблизу Києва",
    "near Moscow": "поблизу Москви",
    "near Mount Tabor": "поблизу гори Фавор",
    "near Mtskheta": "поблизу Мцхети",
    "near Novgorod": "поблизу Новгорода",
    "near Prusa": "поблизу Пруси",
    "near Pskov": "поблизу Пскова",
    "near Rostov": "поблизу Ростова",
    "near Samosata": "поблизу Самосат",
    "near Staraya Russa": "поблизу Старої Русси",
    "near Totma": "поблизу Тотьми",
    "near Uglich": "поблизу Углича",
    "near Verkhoturye": "поблизу Верхотур'я",
    "near Vladimir": "поблизу Володимира",
    "near Volokolamsk": "поблизу Волоколамська",
    "near the Dvina": "поблизу Двіни",
    "on the Dvina": "на Двіні",
    "on the Onega": "на Онезі",
    "the Balkans": "Балкани",
    "the Belozersk country": "Білозерський край",
    "the Bistrița valley": "долина Бистриці",
    "the Black Sea coast and the Caucasus": "Чорноморське узбережжя і Кавказ",
    "the Buzau Mountains": "Бузеуські гори",
    "the Caucasus": "Кавказ",
    "the Cells": "Келії",
    "the Cherepovets country": "Череповецький край",
    "the Danube lands": "Подунав'я",
    "the Dvina country": "Подвіння",
    "the East": "Схід",
    "the Egyptian desert": "Єгипетська пустеля",
    "the Gentile nations": "язичницькі народи",
    "the Golden Horde": "Золота Орда",
    "the Holy Land": "Свята Земля",
    "the Jordan": "Йордан",
    "the Jordan desert": "Йорданська пустеля",
    "the Judean desert": "Юдейська пустеля",
    "the Judean wilderness": "Юдейська пустеля",
    "the Kola north": "Кольська північ",
    "the Komi lands": "землі Комі",
    "the Mount of Olives": "Єлеонська гора",
    "the Obnora": "Обнора",
    "the Oka country": "Приоцький край",
    "the Olonets country": "Олонецький край",
    "the Onega country": "Онезький край",
    "the Palestinian desert": "Палестинська пустеля",
    "the Peloponnese": "Пелопоннес",
    "the Pinega country": "Пінезький край",
    "the Pskov Caves": "Псково-Печерська обитель",
    "the Pčinja valley": "долина Пчині",
    "the Russian North": "Руська Північ",
    "the Russian north": "Руська Північ",
    "the Seto lands": "землі сету",
    "the Smolensk cemetery": "Смоленський цвинтар",
    "the Sora": "Сора",
    "the Studios monastery": "Студійський монастир",
    "the Thebaid": "Фіваїда",
    "the Tikhvin country": "Тихвинський край",
    "the Urals": "Урал",
    "the Volga lands": "Поволжя",
    "the Vologda country": "Вологодський край",
    "the White Sea": "Біле море",
    "the White Sea coast": "Біломорське узбережжя",
    "the Wonderful Mountain": "Дивна гора",
    "the Yakhroma": "Яхрома",
    "the desert of Egypt": "пустеля Єгипту",
    "the inner Egyptian desert": "внутрішня Єгипетська пустеля",
    "the lands of the apostolic mission": "землі апостольської проповіді",
    "the northern Thebaid": "Північна Фіваїда",
    "the northern missions": "північні місії",
    "the whole world": "увесь світ",
    "the wilderness beyond Mesopotamia": "пустеля за Месопотамією",
    "travelers' gates": "врата подорожніх",
    "Žiča": "Жича",
})
