# -*- coding: utf-8 -*-
"""Chinese for the vocabulary that stands beside the lives.

TEXT = {the phrase the index shows: the rendering}. The keys are the phrases
exactly as the index writes them, so a rendering cannot quietly attach itself
to the wrong saint.

A language may later declare PARTS and an expand() to assemble the compound
place-names from pieces rendered once, as the older languages do. It is an
optimisation and not a requirement: everything written in TEXT stands over
whatever expand() builds.
"""
TEXT = {
}

TEXT.update({
    "(Abibus) of Egypt": "（阿比布斯）埃及的",
    "(Apphianus) and Edesius (Aedesius) of Lycia": "（安菲亚努斯）和吕基亚的埃德西乌斯（埃德修斯）",
    "(Eustace) the Confessor, Bishop of Bithynia": "（埃夫斯塔斯）证道者，比提尼亚主教",
    "(Jacob) the Presbyter, and Azadanes and Abdiesus the Deacons, of Persia": "（雅各）长老，及波斯的执事阿扎达内斯和阿布迪修斯",
    "(Vadim) of Persia": "（瓦迪姆）波斯的",
    "(Voino-Yasenetsky), Archbishop of Simferopol and Crimea": "（沃伊诺-亚谢涅茨基），辛菲罗波尔及克里米亚大主教",
    "(also called Susanna), New Martyr of Lesbos": "（又名苏珊娜），莱斯沃斯的新致命女",
    "(tonsured David and Euphrosyne), Wonderworkers of Murom": "（剃度名大卫和叶夫罗西尼娅），穆罗姆的行奇迹者",
    "A Cappadocian centurion bowing beneath the sword with his eyes lifted in thanksgiving, the walnut tree of the tradition behind him, the churches of Byzantium rising over his relics.": "一位卡帕多西亚的百夫长俯身于剑下，双目举起献上感谢，身后是传述所记的核桃树，拜占庭的众教堂在他的圣髑之上兴起。",
    "A Celtic hermit of the Devon coast bearing his own severed head to the spring, the robbers behind him, crowned as a martyr among the saints of Britain.": "一位德文海岸的凯尔特隐修士捧着自己被砍下的头颅走向泉边，强盗在他身后，他在不列颠诸圣之中戴上致命者的冠冕。",
    "A Christian general casting down the temples of Galatia, his twelve tribunes and his thousands of soldiers with their wives and children crowned around him, the converted sorcerer Callinicus among them.": "一位基督徒将军推倒加拉太的神庙，他的十二位千夫长和数千士兵连同妻子儿女在他四周戴上冠冕，归信的术士卡利尼库斯也在其中。",
    "A Christian of Alexandria standing before the tribunal to denounce its cruelty, the confession volunteered and the sword received.": "一位亚历山大的基督徒站在审判者面前控诉其残酷，认信出于自愿，剑也甘心领受。",
    "A Creole-Aleut priest in vestments holding a Gospel and a cross, against an Alaskan landscape.": "一位克里奥尔-阿留申血统的司祭身着祭衣，手持福音书和十字架，背景是阿拉斯加的山水。",
    "A Georgian bishop with a book and a restored church, schoolchildren and monasteries behind him.": "一位格鲁吉亚主教手持一部书，身旁是重建的教堂，学童与修道院在他身后。",
    "A Georgian commander marking his forehead with the cross in his own blood, his soldiers crowned around him.": "一位格鲁吉亚统帅以自己的血在额上画十字，他的士兵在他四周戴上冠冕。",
    "A Georgian monk in prayer before the cave monastery of Gareji in the desert hills.": "一位格鲁吉亚修士在旷野山间加雷吉洞穴修道院前祈祷。",
    "A Georgian monk-abbot holding a scroll or a book.": "一位格鲁吉亚的修士修道院长手持一卷经文或一部书。",
    "A Georgian prince and commander refusing to trample the icon of Christ before the conqueror, crowned as a great-martyr, the defender of the Georgian faith.": "一位格鲁吉亚的王公与统帅在征服者面前拒绝践踏基督的圣像，戴上大致命者的冠冕，格鲁吉亚信仰的护卫者。",
    "A Gothic congregation at worship within the burning church, twenty-six crowns rising with the smoke, the queen gathering the holy remains from the ashes.": "一群哥特信众在焚烧的教堂中礼拜，二十六顶冠冕随烟升起，王后从灰烬中收敛圣髑。",
    "A Gothic general of Rome casting down his military belt before Aurelian, seventy soldiers confessing behind him, the river receiving the wonderworking commander.": "一位罗马的哥特将军在奥勒良面前抛下军带，七十名士兵在他身后认信，河水接纳了这位行奇迹的统帅。",
    "A Great Prince of Kyiv with the churches of Smolensk he raised, the monastic habit he longed for held by an angel, the elder Polycarp pointing him back to his throne.": "一位基辅大公与他所建的斯摩棱斯克众教堂，他所渴慕的修士衣由天使捧着，长老波利卡尔普指点他返回宝座。",
    "A Greek bishop preaching Christ to the pagan Rostov land, the first shepherd of a hostile flock, the see of Rostov founded amid the idols of the north.": "一位希腊主教向异教的罗斯托夫之地传扬基督，敌意羊群的首位牧者，罗斯托夫的主教座在北方的偶像之中建立。",
    "A Greek iconographer of Constantinople founding the island monastery of Lake Onega, the Sophia icon he copied in his hands, the peoples of the north gathering to his light at the age of one hundred and five.": "一位君士坦丁堡的希腊圣像画家在奥涅加湖的岛上建立修道院，手中是他摹写的索菲亚圣像，北方的众民在他一百零五岁时聚集到他的光里。",
    "A Greek metropolitan enthroned at Moscow beside the shrine of Peter, standing unbowed before the khan of the Horde, the Church's charter of freedom in his hand.": "一位希腊都主教在莫斯科彼得的圣髑龛旁登座，在金帐汗国的可汗面前挺立不屈，手中握着教会自由的诏书。",
    "A Greek of Ephesus at the Apostle Paul's side, the Temple riot swirling around his innocent presence, the sickbed of Miletus and the sword of Rome completing his long companionship.": "一位以弗所的希腊人在使徒保罗身旁，圣殿的骚乱环绕着他无辜的身影，米利都的病榻与罗马的剑成全了他长久的同行。",
    "A Greek prince laying aside his rank for the monastic habit, the Uchma hermitage rising on the bank of the Volga, the exile made a wonderworker in his adopted land.": "一位希腊王公舍下自己的品级换取修士衣，乌奇马隐修院在伏尔加河岸兴起，这位流亡者在收留他的土地上成了行奇迹者。",
    "A Patriarch of Constantinople seated upright in death as in blessing, the Mgar monastery of Lubny receiving the traveler, the two worlds of Greece and Rus' joined at his throne.": "一位君士坦丁堡牧首在死中仍端坐如同祝福，卢布尼的姆加尔修道院接纳了这位远行者，希腊与罗斯两个世界在他的宝座上相会。",
    "A Persian noble offering his severed members one by one, each with a prayer, angels gathering his prayers.": "一位波斯贵人将被割下的肢体一件一件献上，每一件都伴着一句祈祷，众天使收集他的祈祷。",
    "A Persian soldier turned monk, the captive Cross of the Lord shining before him, the waters and the sword of Bethsaloe beneath his crown.": "一位由士兵成为修士的波斯人，被掳的主的十字架在他面前发光，贝特萨洛的水与剑在他的冠冕之下。",
    "A Roman centurion kneeling before the Apostle Peter, or vested as a bishop holding a Gospel.": "一位罗马百夫长跪在使徒彼得面前，或身着主教祭衣手持福音书。",
    "A Roman general in armor holding a cross, his soldiers behind him, a spring at his feet.": "一位罗马将军身披铠甲手持十字架，士兵在他身后，泉水在他脚前。",
    "A Roman maiden in flight across the sea with two servants, the convent of Saint Stephen at Mylasa, a cross of stars brighter than the sun above her repose.": "一位罗马少女带着两名仆人渡海逃亡，米拉萨的圣斯德望女修道院，一个比太阳更明亮的星辰十字架在她安息之处上方。",
    "A Roman matron refusing the Arian rite, the fire kindled behind her, Saint Ambrose blessing from afar.": "一位罗马贵妇拒绝阿里乌派的礼仪，火在她身后点起，圣安博从远处祝福。",
    "A Roman noblewoman scattering deeds and treasure to the poor, thousands of freed slaves behind her, her small cell on the Mount of Olives before her.": "一位罗马贵妇将地契与财宝散给穷人，数千获释的仆人在她身后，橄榄山上的小室在她面前。",
    "A Roman senator opening his house to the Apostle Peter, the household at prayer becoming a church, the greeting of the epistle shining over the door.": "一位罗马元老向使徒彼得敞开自己的家，全家的祈祷成了一所教会，书信中的问安在门楣上发光。",
    "A Roman widow standing amid seven crowned sons, encouraging each to the contest, her own crown descending last.": "一位罗马寡妇站在七个戴上冠冕的儿子中间，勉励每一个走上争战，她自己的冠冕最后降下。",
    "A Russian captive in the winter night of Kazan, bound and wounded in the snow, alive at dawn with his confession unbroken.": "一位俄罗斯的被掳者在喀山的冬夜里，被捆绑受伤躺在雪中，黎明时仍然活着，认信未曾折断。",
    "A Russian soldier-slave at prayer in his master's stable, the Turkish household softened by his faith, his incorrupt relics glorified across the Greek world.": "一位为奴的俄罗斯士兵在主人的马厩里祈祷，土耳其人的家因他的信德而变得柔和，他不朽的圣髑在希腊世界各处受到荣耀。",
    "A Serbian prince leading his army at Kosovo, choosing the kingdom of heaven over the kingdom of earth, crowned as a great-martyr, his incorrupt relics the treasure of his people.": "一位塞尔维亚王公在科索沃率领他的军队，拣选天上的国而非地上的国，戴上大致命者的冠冕，他不朽的圣髑是他子民的珍宝。",
    "A Spanish dignitary in the Great Schema, the roads of his pilgrimage from Rome to Jerusalem behind him, the Saracen sword before him.": "一位西班牙的显贵身居大修士品，从罗马到耶路撒冷的朝圣之路在他身后，撒拉森人的剑在他面前。",
})

TEXT.update({
    "A Swedish princess become mother of Rus, her sainted son Vladimir beside her, the crowns of France, Hungary, and Norway among her daughters, the nun's habit her final vesture.": "一位瑞典公主成了罗斯之母，她列入圣品的儿子弗拉基米尔在她身旁，法兰西、匈牙利和挪威的冠冕落在她的女儿们中间，修女衣是她最后的装束。",
    "A Syrian stranger standing three days in prayer in the church of Spoleto, the garden thieves fed at his table and converted, the offered estates refused with a smiling shake of the head.": "一位叙利亚的异乡人在斯波莱托的教堂里站着祈祷三日，园中的盗贼在他桌前得食而归信，人所奉送的田产被他含笑摇头推辞。",
    "A Tatar captive baptized and tonsured, founding a monastery on the shore of Lake Kozha in the far north, the wilderness hallowed by his prayer.": "一位受洗剃度的鞑靼俘虏在极北科扎湖畔建立一座修道院，旷野因他的祈祷而成圣。",
    "A Yup'ik mother in a kuspuk holding a basin and towel, the northern lights above the tundra behind her.": "一位身着尤皮克罩衣的母亲手捧盆与巾，北极光在她身后的苔原之上。",
    "A barefoot ascetic in rags, blessing, at Novgorod.": "一位赤足的苦修者身着破衣，在诺夫哥罗德祝福。",
    "A barefoot fool in tattered clothing by a northern river, giving away what was given to him.": "一位赤足的愚者身着褴褛的衣裳站在北方的河边，把人所给他的都转给别人。",
    "A barefoot fool-for-Christ holding a head of cabbage, at Novgorod by the river.": "一位赤足的为基督而愚者手持一颗白菜，在诺夫哥罗德的河边。",
    "A barefoot fool-for-Christ in a sheepskin holding an axe, by the river defending the city.": "一位赤足的为基督而愚者身披羊皮手持斧头，在河边护卫城池。",
    "A barefoot holy fool with long hair, holding a Psalter, of gentle and sorrowful aspect.": "一位赤足长发的圣愚手捧圣咏集，神情温和而带着哀伤。",
    "A basilica at Lydda, the tomb of Saint George within, hierarchs consecrating the church.": "吕大的一座大殿，圣乔治的墓在其中，众主教正在祝圣这座教堂。",
    "A bearded missionary priest with a traveler's bag, the church of Jackson and the hills of California behind him.": "一位蓄须的传教司祭背着行囊，杰克逊的教堂与加利福尼亚的山丘在他身后。",
    "A beggar beneath the staircase of his father's palace, unknown to all his household, the finished scroll of his life clasped in his dead hand while the emperor and the pope kneel to read it.": "一位乞丐住在他父亲宫殿的楼梯下，全家无人认得他，他写完的一卷生平握在已死的手中，皇帝与教宗跪下诵读。",
    "A bent elder in white on his knees upon the rock, the Theotokos of Tenderness before him, a bear at the edge of the forest clearing.": "一位身着白衣的伛偻长老跪在石上，「柔情」诞神女圣像在他面前，一头熊立在林间空地的边缘。",
    "A bishop alone in an emptied city awaiting the persecutors, then crucified at Perge, teaching from the cross until his voice failed into glory.": "一位主教独自留在空城中等候迫害者，随后在佩尔加被钉十字架，从十字架上继续施教，直到声音止息而入于荣耀。",
    "A bishop and a presbyter of Persia holding crosses, swords above them.": "波斯的一位主教与一位长老手持十字架，剑悬在他们头上。",
    "A bishop and a virgin holding crosses, broken books of sorcery burning at their feet.": "一位主教与一位童贞女手持十字架，被撕毁的巫术之书在他们脚前焚烧。",
    "A bishop and his companions holding crosses, cast into a furnace, a soldier among them.": "一位主教与他的同伴手持十字架，被投入火炉，其中有一名士兵。",
    "A bishop and presbyter cast into a pit, angels crowning them from above.": "一位主教与一位长老被投入坑中，众天使自上为他们加冠。",
    "A bishop and theologian of Lycia with the scroll of his Banquet of the Ten Virgins, refuting the errors of Origen, crowned at the last with martyrdom.": "一位吕基亚的主教与神学家手持他所著「十童贞女之宴」的书卷，驳斥奥利金的谬误，最后以致命受冠。",
    "A bishop answering the emperor that the Church's questions belong to the Church, the road of exile opening behind him.": "一位主教回答皇帝说，教会的事当归教会决断，流放之路在他身后展开。",
    "A bishop baptizing an African king, a boy captive and a royal tutor shown in the scenes of his life.": "一位主教为一位非洲君王施洗，他生平的各景中现出被掳的少年与王室的师傅。",
    "A bishop barring the church door to an emperor, a beehive at his feet, a scroll of his hymns in hand.": "一位主教在教堂门前拦阻皇帝，一个蜂箱在他脚前，他所作赞歌的书卷在手中。",
    "A bishop before a fallen idol, a demon bearing a great stone altar behind him, hot springs at his feet.": "一位主教站在倒下的偶像前，身后有一个魔鬼扛着巨大的石祭坛，温泉在他脚前。",
    "A bishop before the burning temple of Marnas, the cross-guardian's keys at his belt, the Good Thief descending from the Cross in his vision, the Eudoxiana church rising over pagan Gaza.": "一位主教站在焚烧的马尔纳斯神庙前，守十字架者的钥匙系在他腰间，异象中善盗自十字架上降下，欧多克西亚教堂在异教的加沙之上兴起。",
    "A bishop before the emperor, pointing to the emperor's son, teaching the honor due the Son of God.": "一位主教在皇帝面前指着皇帝的儿子，教导人当如何尊敬神之子。",
    "A bishop beheaded at the altar in mid-Liturgy, twenty-eight years of tribunals and torments ranged behind him like waves, Agathangelus crowned at his side.": "一位主教在事奉圣礼中于祭坛前被斩首，二十八年的审讯与刑罚如波浪排列在他身后，阿加桑格鲁斯在他身旁受冠。",
    "A bishop beholding the ladder to heaven with his predecessor calling from above, one hundred and twenty-eight companions ascending behind him under the Persian sword.": "一位主教看见通天的梯子，他的前任在上呼唤，一百二十八位同伴在波斯的剑下随他而上。",
    "A bishop by night in a plain cloak, leaving firewood at a poor widow's door, his cathedral of Belgorod behind him.": "一位主教在夜里身披素朴的斗篷，把柴火留在一位贫穷寡妇的门前，他别尔哥罗德的主教座堂在他身后。",
    "A bishop drinking the sorcerer's cup unharmed, the magician kneeling converted beside his cast-down instruments.": "一位主教饮下术士的毒杯而不受伤害，那行法术的人归信跪在他被抛下的器具旁。",
    "A bishop enthroned with a Gospel, the first hierarch of Jerusalem, of ascetic and venerable countenance.": "一位主教持福音书登座，耶路撒冷的首任主教，面容苦修而可敬。",
    "A bishop holding a Gospel, refuting heretics who shrink before his word.": "一位主教手持福音书驳斥异端，他们在他的话语前退缩。",
    "A bishop holding a page of the alphabet he invented, the sacred birch of the Zyrians felled behind him, the sorcerer Pam turning from the fire and the water, a new people reading the Gospel in its own letters.": "一位主教手持一页他所创的字母，兹梁人的神圣白桦在他身后被伐倒，术士帕姆在火与水面前退去，一个新的民族用自己的文字诵读福音。",
    "A bishop holding a scroll of the Creed, the Theotokos and John the Theologian appearing above, a mountain moved behind.": "一位主教手持一卷信经，诞神女与神学家约翰在上显现，身后有一座山被挪移。",
    "A bishop holding an icon of Christ against the imperial decree, the sick healed at his hands.": "一位主教不顾皇帝的诏令手持基督的圣像，病人在他手下得医治。",
    "A bishop holding the book of the Divine Names, the darkened sun of the Crucifixion above him.": "一位主教手持「神名论」一书，受难时昏暗的太阳在他上方。",
    "A bishop in a laborer's tunic drawing water and hauling wood at Nitria, the omophorion of Damascus folded away, heaven alone reading the monk's true rank.": "一位主教身着劳工的短衣，在尼特里亚打水搬柴，大马士革的肩带已收叠起来，惟有天上认得这修士真正的品级。",
    "A bishop in a mitre holding a crozier, with a gray beard and an ascetic, gentle face.": "一位主教戴着主教冠手持牧杖，须发斑白，面容苦修而温和。",
    "A bishop in monastic poverty, Cernica's island monastery at one hand and the Frasinei he founded at the other, the seminary and the printing press of Ramnic behind him, his face worn bright by fasting.": "一位安于修道贫穷的主教，一手是切尔尼卡的岛上修道院，一手是他所建的弗勒西内伊，勒姆尼库的神学院与印刷所在他身后，他的面容因斋戒而清瘦发亮。",
    "A bishop in the omophorion and mantle holding a book, of gentle and humble aspect.": "一位主教身着肩带与大氅手持一部书，神情温和谦逊。",
    "A bishop in the omophorion and sakkos holding a Gospel book, with a Greek-style beard.": "一位主教身着肩带与主教祭衣手持福音书，蓄着希腊式的胡须。",
})

TEXT.update({
    "A bishop in the omophorion blessing the waters at a river confluence, holding a cross.": "一位身着肩带的主教在两河交汇处手持十字架祝福水。",
    "A bishop in the omophorion blessing, holding a Gospel, before the cathedral of Tambov.": "一位身着肩带的主教手持福音书祝福，坦波夫的主教座堂在他面前。",
    "A bishop in the omophorion holding a Gospel book or the scroll of his Great Canon.": "一位身着肩带的主教手持福音书，或手持他所作大经规的书卷。",
    "A bishop in the omophorion holding a Gospel book, a white dove upon his head.": "一位身着肩带的主教手持福音书，一只白鸽落在他头上。",
    "A bishop in the omophorion holding a Gospel, of humble aspect.": "一位身着肩带的主教手持福音书，神情谦逊。",
    "A bishop in the omophorion holding a Gospel, sometimes with a banner or before a battle.": "一位身着肩带的主教手持福音书，有时手擎旗帜，或立于战阵之前。",
    "A bishop in the omophorion holding a Gospel, the cathedral of Saints Cyril and Methodius behind him.": "一位身着肩带的主教手持福音书，圣基里尔和圣梅福季主教座堂在他身后。",
    "A bishop in the omophorion holding an icon and a Gospel.": "一位身着肩带的主教手持一幅圣像和一部福音书。",
    "A bishop in the omophorion surrounded by his ten disciples, all crowned as martyrs.": "一位身着肩带的主教被他的十位门徒环绕，众人都戴上致命者的冠冕。",
    "A bishop in the omophorion, his hands or face marked by charcoal, holding a Gospel.": "一位身着肩带的主教手上或脸上留着炭的痕迹，手持福音书。",
    "A bishop in the schema and omophorion holding a Gospel, before the city of Voronezh.": "一位身着大修士品服饰与肩带的主教手持福音书，沃罗涅日城在他面前。",
    "A bishop in the snows of Siberia, a school of native children beside him, the gates of China closed behind.": "一位主教在西伯利亚的雪中，一所土著孩童的学堂在他身旁，中国的门在他身后关闭。",
    "A bishop laying aside his omophorion at the mouth of a desert gorge, the monastery of Choziba in the cliffs.": "一位主教在旷野峡谷的入口放下自己的肩带，霍济瓦修道院在崖壁之间。",
    "A bishop led by an angel from torture to torture and city to city, Sirmium converted behind him and Formia receiving him, the lamps of the sailors burning at his name.": "一位主教由天使带领，从一场刑罚到另一场刑罚，从一座城到另一座城，西尔米乌姆在他身后归信，福尔米亚接纳了他，水手们的灯为他的名字点燃。",
    "A bishop of Aegina laying down his omophorion and returning to the monastic habit, his island see behind him.": "一位埃伊纳的主教放下肩带重着修士衣，他海岛的主教座在他身后。",
    "A bishop of Amasea standing between the hunted virgin and the tyrant's demand, the sea giving back his body in the fishermen's nets, the last crowns of the persecution descending as the peace of the Church dawns.": "一位阿马西亚的主教站在被追捕的童贞女与暴君的索求之间，海把他的身体交还在渔人的网中，教会的平安初现时，迫害最后的冠冕降下。",
    "A bishop of Argos measuring out grain that does not diminish, the ransomed captives returning from the sea behind him, his monastic family in Christ around the one see he consented to hold.": "一位阿尔戈斯的主教量出永不减少的谷粮，被赎回的俘虏自海上归来在他身后，他在基督内的修道家人围绕着他所肯接受的唯一主教座。",
    "A bishop of Benevento unharmed in the furnace, the beasts of the arena lying at his feet, Naples receiving his body and his blood, his deacons and companions crowned around him.": "一位贝内文托的主教在火炉中不受伤害，斗兽场的野兽伏在他脚前，那不勒斯领受了他的身体与他的血，他的执事与同伴在他四周戴上冠冕。",
    "A bishop of Bithynia holding the icon of Christ and the open Scriptures together, the road of exile behind him.": "一位比提尼亚的主教同时手持基督的圣像与展开的圣经，流放之路在他身后。",
    "A bishop of Bithynia on the road of exile, his cathedral behind him and the icon of Christ unsurrendered before him.": "一位比提尼亚的主教走在流放的路上，他的主教座堂在他身后，未曾交出的基督圣像在他面前。",
    "A bishop of Brooklyn with the map of a continent behind him, thirty parishes rising from immigrant streets, The Word in his hand, Tikhon of Moscow laying hands upon the first-consecrated of America.": "一位布鲁克林的主教，身后是一整片大陆的地图，三十个堂区从移民的街巷中兴起，「圣言」在他手中，莫斯科的吉洪按手为美洲首位受祝圣者。",
    "A bishop of Catania in exile for the holy images, the icon of Christ held fast against the imperial decree.": "一位卡塔尼亚的主教为圣像的缘故被流放，不顾皇帝的诏令紧握基督的圣像。",
    "A bishop of Chalcedon and his fellow ascetic standing together for the icons, the see of the Fourth Council refusing the new heresy, exile shared as the cell had been.": "一位卡尔西顿的主教与同修的苦修者一同为圣像挺身，第四次大公会议的主教座拒绝新的异端，昔日同居一室，如今同受流放。",
    "A bishop of Chalcedon defending the holy icons, his hand open to the poor, the exile that crowned his confession before him.": "一位卡尔西顿的主教护卫圣像，向穷人伸开援手，那为他的认信加冕的流放在他面前。",
    "A bishop of Corinth falsely accused, the newborn infant speaking at his prayer to name its true father, the slander confounded and the saint vindicated.": "一位科林斯的主教被人诬告，初生的婴孩因他的祈祷开口说出自己真正的父亲，谗言被挫，圣人得雪。",
    "A bishop of Cyprus blessing a dry vine-branch that bears fruit before its time, the poor fed at his hand, the idols of the island cast down.": "一位塞浦路斯的主教祝福一根枯干的葡萄枝，它未及时候就结了果，穷人在他手下得食，海岛的偶像被推倒。",
    "A bishop of Cyprus crowned with martyrdom, his myrrh-streaming relics borne across the sea to Constantinople, the sick healed at his shrine.": "一位塞浦路斯的主教以致命受冠，他流香的圣髑渡海被送到君士坦丁堡，病人在他的圣髑龛前得医治。",
    "A bishop of Cyprus with the nails of his torture, teaching the faithful gathered at what he thought his end, the edict of Constantine opening his prison to a few more years of shepherding.": "一位塞浦路斯的主教带着刑罚所用的钉子，在他以为将终之时向聚集的信众施教，君士坦丁的诏令打开他的牢门，使他又牧养了几年。",
    "A bishop of Epirus striking down the great serpent at the poisoned spring, the rain descending on the parched fields at his prayer, a dead man rising from the bier to witness against the false creditor.": "一位伊庇鲁斯的主教在有毒的泉边击杀巨蛇，雨因他的祈祷降在干旱的田地上，一个死人从棺架上起来，指证那假冒的债主。",
    "A bishop of Melitene serene under the torturers, the emperor's own order opening his prison, the confessor's crown worn through years of peace.": "一位梅里泰内的主教在施刑者手下安然自若，皇帝亲自下令打开他的牢门，他在多年的平安中戴着证道者的冠冕。",
    "A bishop of Novgorod standing alone against an uncanonical council, the Caves that formed him receiving him in confinement and in death, Theodosius appearing to welcome him home.": "一位诺夫哥罗德的主教独自抵挡一次违反教规的会议，养育他的洞窟修道院在他被囚与去世时接纳了他，德奥多西显现迎他回家。",
    "A bishop of Pergamum standing where Satan's throne was, the brazen bull glowing behind him, the open Apocalypse naming him the faithful witness in the Lord's own voice.": "一位别迦摩的主教站在撒但宝座所在之处，烧红的铜牛在他身后，展开的默示录以主自己的声音称他为忠信的见证者。",
    "A bishop of Perm baptizing the peoples of the far north, the idols of the Permians thrown down and the churches rising, the mission of Saint Stephen carried onward.": "一位彼尔姆的主教为极北的众民施洗，彼尔姆人的偶像被推倒，众教堂兴起，圣斯德望的使命得以延续。",
    "A bishop of Persia with staff of prophecy, a ruined city behind him, two disciples at his side.": "一位波斯的主教手持先知的杖，一座荒废的城在他身后，两位门徒在他身旁。",
    "A bishop of Pisidian Antioch refusing the iconoclast decree, the icons standing in his churches while he goes into exile, the confessor's crown replacing the surrendered see.": "一位皮西迪亚安提阿的主教拒绝毁像者的诏令，他走上流放之路，圣像却仍立在他的众教堂里，证道者的冠冕取代了让出的主教座。",
    "A bishop of Prusa destroying a great serpent by the sign of the Cross, preaching Christ under Julian the Apostate, crowned with martyrdom by the sword.": "一位普鲁萨的主教以十字架的标记消灭一条巨蛇，在背教者尤利安治下传扬基督，以剑受致命的冠冕。",
    "A bishop of Prusa standing unharmed in the boiling spring, preaching the God who made both the healing waters and the fire of hell, his three presbyters crowned beside him.": "一位普鲁萨的主教立在沸腾的泉水中不受伤害，传扬那既造医治之水又造地狱之火的神，他的三位长老在他身旁戴上冠冕。",
    "A bishop of Rome in the omophorion holding a Gospel, with a martyr's palm.": "一位罗马的主教身着肩带手持福音书，并持致命者的棕枝。",
    "A bishop of Rome of the age of the martyrs, shepherding his flock in the catacombs, bringing the noble and the humble alike to the faith of Christ.": "一位致命者时代的罗马主教在地下墓穴中牧养他的羊群，把显贵与卑微的人一同带到基督的信仰里。",
    "A bishop of Rostov preaching Christ to the half-pagan land, the idols thrown down and the churches rising, the grace of wonders confirming the word of the Caves-trained shepherd.": "一位罗斯托夫的主教向半为异教的土地传扬基督，偶像被推倒，众教堂兴起，奇迹的恩宠印证这位在洞窟修道院受训的牧者所传的话。",
})

TEXT.update({
    "A bishop of Rostov whose very funeral became a glorification, wonders flowing from his body before burial, the shepherd of the yoke-time honored as a saint from the hour of his death.": "一位罗斯托夫的主教，他的葬礼本身就成了列圣，尚未安葬，奇迹已从他的身体涌流，这位轭下年代的牧者自去世之时起就受人尊为圣人。",
    "A bishop of Salamis with the five tongues of his learning and the Panarion of his refutations, the ascetic of the Palestinian desert crowned with the long white rule of Cyprus.": "一位萨拉米斯的主教，学问兼通五种语言，手持他驳斥异端的「帕纳里翁」，这位巴勒斯坦旷野的苦修者以塞浦路斯长久而洁白的治理受冠。",
    "A bishop of Samosata refusing to surrender the record of the faith though his hand be cut off, traveling in disguise to strengthen the Orthodox, crowned by the tile of an Arian.": "一位萨莫萨塔的主教宁可断手也不交出信仰的记录，改装易服四处坚固正教徒，最后被一名阿里乌派妇人所掷的瓦片加冕。",
    "A bishop of Sardis scourged for Christ, the dry wooden stake stained with his blood taking root and growing into a green tree of healing beside him.": "一位撒狄的主教为基督受鞭打，那沾了他血的枯木桩生根发芽，在他身旁长成一棵医治的青树。",
    "A bishop of Synnada bearing the icons he defended, the courts of caliph and emperor behind him, the exile that crowned his confession before him.": "一位辛纳达的主教捧着他所护卫的圣像，哈里发与皇帝的公堂在他身后，那为他的认信加冕的流放在他面前。",
    "A bishop of Tver reconciling princes with the Gospel between them, the Zheltikov monastery rising by the river, the Kyiv Caves Paterikon copied out under his hand.": "一位特维尔的主教以福音书置于诸王公之间使他们和好，热尔季科夫修道院在河边兴起，基辅洞窟教父传在他手下抄成。",
    "A bishop of Verona with a fishing rod and a line of catechumens for his catch, the Adige rising in flood behind him and standing like a wall at the open doors of his church.": "一位维罗纳的主教手持钓竿，一列望教者是他所得的鱼，阿迪杰河在他身后涨溢，却像墙一样立在他教堂敞开的门前。",
    "A bishop of Vladimir with the founding letter of the Caves Paterik in his hand, his friend Polikarp cautioned against vainglory, the Near Caves receiving the author home to the monastery of his heart.": "一位沃洛德米尔的主教手中拿着洞窟教父传的创始书信，他的朋友波利卡尔普受他告诫勿求虚荣，近洞窟迎这位作者回到他心之所系的修道院。",
    "A bishop of ascetic countenance in the omophorion, blessing, his incorrupt relics in a shrine.": "一位面容苦修的主教身着肩带祝福，他不朽的圣髑安放在圣髑龛中。",
    "A bishop of gentle countenance distributing alms, a schema laid ready beside his omophorion.": "一位面容温和的主教分发施舍，一件大修士品的服饰放在他的肩带旁备用。",
    "A bishop of the Black Sea coast with his city walls behind him, Saracen raiders scattered by his prayer, the northern raiders frozen at his sepulcher until the captives go free.": "一位黑海沿岸的主教，城墙在他身后，撒拉森的劫掠者因他的祈祷而溃散，北方的劫掠者在他的墓前僵立，直到俘虏得释。",
    "A bishop of the Crimean Goths defending the holy icons, consecrated in Orthodox Georgia, sharing the sufferings of his people under the Khazar yoke.": "一位克里米亚哥特人的主教护卫圣像，在正教的格鲁吉亚受祝圣，与他的子民一同担当哈扎尔轭下的苦难。",
    "A bishop of the Hellespont in chains for the icons, the letters of Theodore the Studite in his hands.": "一位赫勒斯滂的主教为圣像的缘故身负锁链，手中是斯图迪的德奥多尔写给他的书信。",
    "A bishop of the Hellespont on the road again, the iconoclasts' document forever unsigned behind him, the icon of Christ carried from refuge to refuge.": "一位赫勒斯滂的主教再度上路，毁像者的文书在他身后始终未曾签署，基督的圣像被他从一处避难所带到另一处。",
    "A bishop of the Nicene fathers leading the serpent by his staff into the fire, and on the mountain road the ambush of the heretics, the stone of the murderess turned against her until his grave healed her.": "一位尼西亚教父中的主教用他的杖把蛇引入火中，山路上有异端的埋伏，那行凶妇人的石头反击她自己，直到他的坟墓医好了她。",
    "A bishop of the Siberian frontier among the peoples of the east, the churches and schools of his planting behind him, the lamp of his night prayers burning over Irkutsk.": "一位西伯利亚边地的主教在东方诸民之间，他所栽植的众教堂与学堂在他身后，他夜祷的灯火在伊尔库茨克上空燃烧。",
    "A bishop of the apostolic line blessing a bitter spring at Catania, the water running sweet and the city believing.": "一位使徒传承中的主教在卡塔尼亚祝福一道苦泉，水变甘甜，全城归信。",
    "A bishop ordained by the hand of the Theologian, laying his own hand on the young Polycarp, a myrtle flowering from his tomb.": "一位由神学家亲手授职的主教，又亲手按在年少的波利卡普身上，一棵桃金娘从他的坟上开花。",
    "A bishop rapt in divine song at the funeral of the Theotokos, the apostles around the bier.": "一位主教在诞神女的葬礼上被神圣的歌声夺去心神，众使徒环绕在棺架四周。",
    "A bishop rising from a deep pit, the king with the face of a beast healed before him, a church shown from heaven.": "一位主教从深坑中上来，那面貌如兽的王在他面前得医治，一座教堂自天上显示出来。",
    "A bishop sailing upon his mantle across the lake, the city that expelled him kneeling on the shore.": "一位主教乘着自己的大氅渡湖，那驱逐他的城在岸上跪下。",
    "A bishop scourged with ox-hide thongs, the icon of Christ held fast in his hands through four exiles.": "一位主教被牛皮鞭抽打，历经四次流放，基督的圣像始终紧握在他手中。",
    "A bishop serene in prison, the false witness healed and confessing, an open book of Ecclesiastes before him.": "一位主教在狱中安然自若，作假见证的人得医治并认罪，一部展开的训道篇在他面前。",
    "A bishop set upon by schismatics with swords, praying for his murderers as he falls.": "一位主教被分裂教会的人持剑袭击，他倒下时仍为凶手祈祷。",
    "A bishop standing unharmed in the flames with the sorcerer bound in his omophorion, the fire dividing the true wonder from the false before the whole city.": "一位主教立在火焰中毫发无伤，术士被他的肩带捆住，火在全城面前分别出真奇迹与假奇迹。",
    "A bishop standing upon his mantle spread on the waters of the Oka, the Murom icon of the Mother of God in his hands, borne upstream to Ryazan, his innocence proclaimed by the wonder.": "一位主教立在铺于奥卡河水面的大氅上，穆罗姆的诞神女圣像在他手中，逆流被送到梁赞，这奇迹宣告了他的无辜。",
    "A bishop struck down at the altar during the Divine Liturgy, angels receiving his soul.": "一位主教在事奉圣礼中于祭坛前被击倒，众天使接他的灵魂。",
    "A bishop tried by fire, beasts, and sword, the great company of five hundred forty-six confessors about him, Jerusalem's name upon a martyrdom the whole East shared.": "一位主教经过火、野兽与刀剑的试炼，五百四十六位证道者的大群围绕着他，耶路撒冷的名字加在这场全东方共有的致命之上。",
    "A bishop upon a pillar with a pen, the paschal sermons streaming from his mouth like light, the prayer book of the faithful open at the prayers he wrote for every day of the week.": "一位主教立在柱上手持笔，复活节的讲道如光从他口中涌出，信众的祈祷书翻开在他为一周每一日所写的祷文处。",
    "A bishop vested in the omophorion, with a short rounded beard, holding a Gospel book and blessing.": "一位主教身着肩带，蓄着短而圆的胡须，手持福音书祝福。",
    "A bishop washing the wounds of lepers with his own hands, then standing before Leo the Armenian foretelling his swift destruction, the fortress of his thirty-year exile behind him.": "一位主教亲手洗净麻风病人的伤口，随后站在亚美尼亚人良面前预言他必速速灭亡，囚禁他三十年的堡垒在他身后。",
    "A bishop who once wore Tatar chains preaching Christ in the Tatar tongue at Kazan, the Savior monastery rising in the kremlin, the sick of two faiths healed at his prayer.": "一位曾戴鞑靼锁链的主教在喀山用鞑靼语传扬基督，救主修道院在克里姆林中兴起，两种信仰的病人都因他的祈祷得医治。",
    "A bishop who was a surgeon, the omophorion over his shoulders and the healing of the sick in his hands, the prisons and exiles of his confession behind him, the light of Christ in a godless age.": "一位身为外科医生的主教，肩带披在肩上，医治病人的能力在他手中，认信所带来的牢狱与流放在他身后，基督的光照在一个无神的时代。",
    "A bishop with a Gospel preaching to the people of Volhynia, a cave monastery in the distance.": "一位主教手持福音书向沃林的百姓传道，一座洞窟修道院在远处。",
    "A bishop with a company of one hundred ninety-nine disciples, the sign of the Cross that saved him in battle above, the swords of Sicily gathering the whole school into one harvest.": "一位主教与一百九十九位门徒同在，那在战阵中救他的十字架标记在上方，西西里的刀剑把整所学堂收成一束。",
    "A bishop with a high domed forehead and short pointed beard, a thin ascetic face, vested in the omophorion and holding a Gospel book.": "一位前额高耸圆隆、胡须短而尖的主教，面容清瘦苦修，身着肩带手持福音书。",
    "A bishop with a lamp, a serpent fleeing before him, the island of Crete behind.": "一位主教手持一盏灯，一条蛇在他面前逃走，克里特岛在身后。",
    "A bishop with a long dark tapering beard and high forehead, vested in the omophorion, holding a Gospel book and blessing.": "一位主教蓄着又长又黑、末端渐尖的胡须，前额高耸，身着肩带，手持福音书祝福。",
    "A bishop with the Prologue open in his hands, the lake of Ohrid behind one shoulder and the wire of Dachau behind the other, preaching Christ to the peoples in every tongue he knew.": "一位主教手中摊开圣人纪略，奥赫里德湖在一肩之后，达豪的铁丝网在另一肩之后，他用自己所懂的每一种语言向众民传扬基督。",
    "A bishop with the marks of long warfare, demons fleeing behind him, angels and the Theotokos receiving his soul before him.": "一位主教带着长久争战的痕迹，众魔鬼在他身后逃遁，众天使与诞神女在他面前接他的灵魂。",
})

TEXT.update({
    "A bishop with the paschal fire blazing on the hill of Slane against the high king's darkness, the shamrock of the Trinity in his hand, the tribes of Ireland kneeling to the font.": "一位主教在斯莱恩山上点起复活节的火，与至高王的黑暗相对，象征圣三的三叶草在他手中，爱尔兰的各族跪在洗礼池前。",
    "A bishop with verses branded upon his face, holding an icon of Christ and a scroll of canons.": "一位主教脸上被烙下诗句，手持基督的圣像与一卷教规。",
    "A bishop writing canons at a desk, the Theotokos appearing to bless him.": "一位主教伏案撰写教规，诞神女显现祝福他。",
    "A bishop's omophorion hidden beneath a novice's habit, an aged hesychast silent in his cell at the Lavra.": "一位主教的肩带藏在初学者的衣袍之下，一位年迈的静修者在大修道院的小室中默然不语。",
    "A bishop, a deacon, a servant, and a holy woman crowned together amid flames at Pergamum.": "一位主教、一位执事、一名仆人与一位圣洁的妇人在别迦摩的火焰中一同受冠。",
    "A bishop-ascetic in chains beneath an iron cage, Saint George leading him from childhood as a companion, the possessed freed and the storms stilled at his prayer, the resigned omophorion folded beside the hermit's cave.": "一位身负锁链、囚于铁笼之下的苦修主教，圣乔治自他幼年起就作伴引领他，附魔者因他的祈祷得释，风暴因他的祈祷平息，辞去的肩带折叠在隐修者的洞穴旁。",
    "A bishop-confessor bearing the marks of his wounds, holding a Gospel.": "一位带着伤痕的证道者主教手持福音书。",
    "A bishop-envoy on the road between empires, gifts flowing through his hands to the poor of his city.": "一位奉使的主教走在诸帝国之间的路上，礼物经他的手流向他城中的穷人。",
    "A bishop-martyr barring an emperor from the church doors, three youths and their mother beside him.": "一位致命主教在教堂门前拦阻皇帝，三个少年与他们的母亲在他身旁。",
    "A bishop-martyr by the sea, ships in the distance, flames beneath his feet trampled down.": "一位致命主教在海边，船只在远处，脚下的火焰被他踏灭。",
    "A bishop-martyr holding a Gospel, a lion at his feet praising God.": "一位致命主教手持福音书，一头狮子在他脚前赞美神。",
    "A bishop-martyr in the omophorion holding a Gospel and a cross.": "一位身着肩带的致命主教手持福音书与十字架。",
    "A bishop-martyr in the omophorion holding a Gospel or a scroll inscribed against heresy.": "一位身着肩带的致命主教手持福音书，或手持一卷驳斥异端的书。",
    "A bishop-martyr in the omophorion holding a Gospel or a scroll on the unity of the Church.": "一位身着肩带的致命主教手持福音书，或手持一卷论教会合一的书。",
    "A bishop-martyr in the omophorion holding a Gospel, a burning church in the background.": "一位身着肩带的致命主教手持福音书，背景是一座焚烧的教堂。",
    "A bishop-martyr in the omophorion holding a Gospel, sometimes with a ship or flames.": "一位身着肩带的致命主教手持福音书，有时旁有船只或火焰。",
    "A bishop-martyr in the omophorion holding a Gospel, with his three companions and tamed beasts.": "一位身着肩带的致命主教手持福音书，他的三位同伴与被驯服的野兽在旁。",
    "A bishop-martyr with a soldier and four women, all crowned together.": "一位致命主教与一名士兵和四位妇人一同受冠。",
    "A bishop-martyr with a young nun and two servants, holding crosses.": "一位致命主教与一位年轻的修女和两名仆人手持十字架。",
    "A bishop-physician and his sister holding crosses, his hands extended in healing.": "一位身为医者的主教与他的姐妹手持十字架，他伸手施行医治。",
    "A bishop-physician at the Persian court, the king healed and the hidden trickster unearthed from beneath the temple floor, caravans of martyrs' relics entering the city of his name.": "一位身为医者的主教在波斯的宫廷中，君王得医治，藏匿的骗子从神庙地板下被掘出，载着致命者圣髑的商队进入以他为名的城。",
    "A bishop-physician in a mountain cave with the wild beasts gathered gently around him, a child healed of a choking bone, seven women and two children crowned beside him.": "一位身为医者的主教在山洞中，野兽温驯地聚在他四周，一个孩子被骨头哽住而得医治，七位妇人与两个孩子在他身旁受冠。",
    "A blind eldress seated small and radiant in a Moscow room, the lines of the troubled stretching through the Soviet dark to her door, her closed eyes seeing all of it in God.": "一位失明的女长老小小地坐在莫斯科的一间屋子里，光彩照人，苦恼的人排成长队穿过苏维埃的黑暗来到她门前，她闭着的眼睛在神里看见这一切。",
    "A boy bishop-to-be praying before an emptied granary as it fills again, coins and wine multiplying in his open hands.": "一个将来要作主教的男孩在空了的粮仓前祈祷，粮仓重新装满，钱币与酒在他张开的手中增多。",
    "A boy confessing Christ with his tutor Modestus and nurse Crescentia beside him, the cauldron and the beasts before them, the child and his guardians crowned together.": "一个男孩认信基督，师傅莫杰斯特与乳母克雷斯肯提娅在他身旁，大锅与野兽在他们面前，孩子与他的看顾者一同受冠。",
    "A boy in peasant dress with a harrow, lightning above, angels receiving his soul.": "一个身着农夫衣裳的男孩扶着耙，闪电在上方，众天使接他的灵魂。",
    "A boy martyr with a white dove above him, water springing from the rock at his prayer, the lion of his mountain cave refusing to harm him in the arena.": "一个男孩致命者，一只白鸽在他上方，水因他的祈祷从磐石中涌出，他山洞中的狮子在斗兽场上不肯伤他。",
    "A boy prince in royal robes bearing the palm of the passion-bearer, the yard of Uglich behind him where he fell, his incorrupt relics enshrined in the Kremlin to confound the pretenders.": "一位身着王袍的少年王子手持受难者的棕枝，他倒下的乌格里奇院落在他身后，他不朽的圣髑供奉在克里姆林中，使冒名者哑口无言。",
    "A bread merchant with pierced hands and feet, walking his last steps for Christ.": "一位卖饼的商人手脚被刺穿，为基督走完最后的路程。",
    "A bridegroom and bride in virginal crowns, the lion guarding Daria's honor, the tribune Claudius converted with his whole house, the sand pit of the Via Salaria closing over the two alive.": "一对新郎与新娘头戴童贞的冠冕，狮子守护着达里娅的贞洁，千夫长克劳狄与全家归信，萨拉里亚大道的沙坑在两人活着时把他们掩埋。",
    "A brother and sister crowned as martyrs, holding crosses and palms.": "一对兄妹戴上致命者的冠冕，手持十字架与棕枝。",
    "A brother and sister martyrs, he upon a tree, she with a spear, both crowned.": "一对致命的兄妹，他在树上，她被长矛所刺，二人都受冠。",
    "A canonarch of the Far Caves directing the chanting of the brethren, the book of the services in his hand, the monastic life embraced from his childhood.": "一位远洞窟的领经员指挥众弟兄咏唱，礼仪的经书在他手中，自幼年起就领受了修道的生活。",
    "A captain of the guard bound to a tree and shot with arrows, the widow Irene tending him, his converted companions with their crowns around him.": "一位卫队长被绑在树上乱箭射穿，寡妇伊琳娜照料他，归信的同伴戴着冠冕围绕在他四周。",
    "A cathedral in flames on the night of the Nativity, the bishop baptizing and communing the multitude within, twenty thousand crowns rising in the smoke.": "一座主教座堂在圣诞之夜燃起大火，主教在其中为众人施洗并送圣体，两万顶冠冕随烟升起。",
    "A centurion striding from the desert into the crowded amphitheater, proclaiming Christ before the astonished city.": "一位百夫长自旷野大步走进人群拥挤的圆形剧场，在惊愕的全城面前宣扬基督。",
    "A centurion with spear at the foot of the Cross, his eyes lifted to the Crucified, confessing.": "一位百夫长持矛立在十字架下，双目仰望被钉者，口中认信。",
    "A church at Nicopolis in Armenia": "亚美尼亚尼科波利的一座教堂",
    "A church built over his grave at Skepsis": "在斯凯普西斯建于他墓上的一座教堂",
    "A church in her honor at Chalcedon by 450": "至450年已在卡尔西顿有一座为纪念她而建的教堂",
})
