# -*- coding: utf-8 -*-
"""The eparchies of the Moscow Patriarchate.

Read on 13 September 2026 from the Patriarchate's own register of its
organisations - the list of eparchies it publishes at patriarchia.ru, and the
page it publishes for each one, which is what every row cites. The register
holds 327 eparchies. 270 are here.

What is not here, and why:

  - The 54 eparchies in Ukraine. They are the Ukrainian Orthodox Church's own
    and stand under it, read from its own list; they are in
    tools/directory_rows/ukraine_uoc.py. Ten of them the register now places
    in Russia - Donetsk, Horlivka, Luhansk, Rovenky, Sievierodonetsk,
    Simferopol, Dzhankoi, Feodosia, Berdiansk and Skadovsk. A country code is
    a claim about a border, and this site does not make one; those sees are
    listed where their own Church lists them and nowhere else.
  - The three eparchies in Japan, which belong to the autonomous Japanese
    Orthodox Church and hang off it rather than off Moscow.

Names and seats are given in English; the see's own name stands beside it in
the language the register prints. Where a see is not named after the town it
sits in - Vyatka at Kirov, Melekess at Dimitrovgrad, Pokrovsk at Engels - the
see keeps its own name and the seat names the town.

Addresses are the register's own words, set out as an envelope wants them:
the street on one line, the postcode and town on the next. Nothing is
translated and nothing is added. The country line is dropped, because the
page writes it in the reader's language.

A site is written only where it answered when it was tried. Thirteen did not
- some refused the request, some answered on a certificate a browser will not
accept, some did not resolve at all - and those rows carry no link and fall
back to the register, which does answer. They are to be tried again, not
written off.
"""

ROWS = [

 dict(id="ru-abakan", parent="russia",
      name="Abakan Diocese",
      local=u"Абаканская епархия",
      seat="Abakan", country="RU",
      address=[u"ул. Катанова, 5", u"655012, Республика Хакасия, г. Абакан"],
      site="https://abakan-eparchy.ru/",
      sources=["https://patriarchia.ru/org/4"]),

 dict(id="ru-australia-and-new-zealand-rocor", parent="rocor",
      name="Diocese of Australia and New Zealand (ROCOR)",
      local=u"Австралийско-Новозеландская епархия (РПЦЗ)",
      seat="Sydney", country="AU",
      address=[u"20 Chelmsford Avenue, Croydon NSW 2132, Australia"],
      site="http://rocor.org.au/",
      sources=["https://patriarchia.ru/org/602"]),

 dict(id="ru-aktobe", parent="russia",
      name="Aktobe Diocese",
      local=u"Актюбинская епархия",
      seat="Aktobe", country="KZ",
      address=[u"ул. М. Маметовой, д.6 (Никольский собор)", u"г. Актобе"],
      site="https://aktobe-eparhiya.kz/",
      sources=["https://patriarchia.ru/org/569"]),

 dict(id="ru-alapayevsk", parent="russia",
      name="Alapayevsk Diocese",
      local=u"Алапаевская епархия",
      seat="Alapayevsk", country="RU",
      address=[u"ул. Ленина, 79", u"624600, Свердловская область, г. Алапаевск"],
      site="https://alapaevsk-eparchy.ru/",
      sources=["https://patriarchia.ru/org/541"]),

 dict(id="ru-alatyr", parent="russia",
      name="Alatyr Diocese",
      local=u"Алатырская епархия",
      seat="Alatyr", country="RU",
      address=[u"ул. Ленина, 130", u"429820, Чувашская Республика, г. Алатырь"],
      site="http://alat-eparhia.ru/",
      sources=["https://patriarchia.ru/org/401"]),

 dict(id="ru-aleksandrov", parent="russia",
      name="Aleksandrov Diocese",
      local=u"Александровская епархия",
      seat="Aleksandrov", country="RU",
      address=[u"пер. Советский, 6", u"601650, Владимирская область, г. Александров"],
      site="http://al-eparhiya.ru/",
      sources=["https://patriarchia.ru/org/440"]),

 dict(id="ru-almetevsk", parent="russia",
      name="Almetevsk Diocese",
      local=u"Альметьевская епархия",
      seat="Almetevsk", country="RU",
      address=[u"Соборная площадь, д. 1, корп. 1", u"423450, Республика Татарстан, г. Альметьевск"],
      site="https://almet-eparhia.info/",
      sources=["https://patriarchia.ru/org/371"]),

 dict(id="ru-amur", parent="russia",
      name="Amur Diocese",
      local=u"Амурская епархия",
      seat="Komsomolsk-on-Amur", country="RU",
      address=[u"пр-т Копылова, 54", u"681018, Хабаровский край, г. Комсомольск-на-Амуре"],
      site="https://amur-eparhia.ru/",
      sources=["https://patriarchia.ru/org/318"]),

 dict(id="ru-anadyr", parent="russia",
      name="Anadyr Diocese",
      local=u"Анадырская епархия",
      seat="Anadyr", country="RU",
      address=[u"ул. Ленина, д. 19", u"689000, Чукотский АО, г. Анадырь"],
      site="https://pravchukotka.ru/",
      sources=["https://patriarchia.ru/org/5"]),

 dict(id="ru-argentina-and-south-america", parent="russia",
      name="Diocese of Argentina and South America",
      local=u"Аргентинская и Южноамериканская епархия",
      seat="Buenos Aires", country="AR",
      address=[u"Bulnes 1743, c/p 1425, Buenos Aires (C.A.B.A.), Republica Argentina. На период ремонтных работ храм и епархиальное управление расположены по адресу: Anasagasti 2031, c/p 1425, Buenos Aires (C.A.B.A.), Republica Argentina"],
      site="https://southamerica.cerkov.ru/",
      sources=["https://patriarchia.ru/org/141"]),

 dict(id="ru-ardatov", parent="russia",
      name="Ardatov Diocese",
      local=u"Ардатовская епархия",
      seat="Ardatov", country="RU",
      address=[u"ул. Карла Маркса, 108", u"Республика Мордовия, г. Ардатов"],
      site="https://ardatep.ru/",
      sources=["https://patriarchia.ru/org/290"]),

 dict(id="ru-armavir", parent="russia",
      name="Armavir Diocese",
      local=u"Армавирская епархия",
      seat="Armavir", country="RU",
      address=[u"ул. Григорьянца, 1", u"352900, Краснодарский край, г. Армавир"],
      site="https://armavireparh.ru/",
      sources=["https://patriarchia.ru/org/426"]),

 dict(id="ru-arsenev", parent="russia",
      name="Arsenev Diocese",
      local=u"Арсеньевская епархия",
      seat="Arsenev", country="RU",
      address=[u"ул. Социалистическая, 115", u"692331, Приморский край, г. Арсеньев"],
      site="https://arseniev-eparhia.ru/",
      sources=["https://patriarchia.ru/org/298"]),

 dict(id="ru-arkhangelsk", parent="russia",
      name="Arkhangelsk Diocese",
      local=u"Архангельская епархия",
      seat="Arkhangelsk", country="RU",
      address=[u"ул. Ильинская, д. 5", u"163002, г. Архангельск"],
      site="http://www.arh-eparhia.ru/",
      sources=["https://patriarchia.ru/org/6"]),

 dict(id="ru-astana", parent="russia",
      name="Astana Diocese",
      local=u"Астанайская епархия",
      seat="Almaty", country="KZ",
      address=[u"ул. Ашимбаева, 26", u"050002, Республика Казахстан, г. Алма-Ата"],
      site="https://mitropolia.kz:443/",
      sources=["https://patriarchia.ru/org/151"]),

 dict(id="ru-astrakhan", parent="russia",
      name="Astrakhan Diocese",
      local=u"Астраханская епархия",
      seat="Astrakhan", country="RU",
      address=[u"Покровская площадь, 6", u"414056, Астраханская область, г. Астрахань"],
      site="https://astreparh.ru/",
      sources=["https://patriarchia.ru/org/7"]),

 dict(id="ru-akhtubinsk", parent="russia",
      name="Akhtubinsk Diocese",
      local=u"Ахтубинская епархия",
      seat="Akhtubinsk", country="RU",
      address=[u"ул. Волгоградская, 111А", u"416500, Астраханская обл., г. Ахтубинск"],
      site="https://ahtuba-eparhia.ru/",
      sources=["https://patriarchia.ru/org/429"]),

 dict(id="ru-baku", parent="russia",
      name="Baku Diocese",
      local=u"Бакинская епархия",
      seat="Baku", country="AZ",
      address=[u"ул. Эльдара Агаева, 19", u"Республика Азербайджан, г. Баку"],
      site="https://www.pravoslavie.az/",
      sources=["https://patriarchia.ru/org/140"]),

 dict(id="ru-balakovo", parent="russia",
      name="Balakovo Diocese",
      local=u"Балаковская епархия",
      seat="Balakovo", country="RU",
      address=[u"ул. Советская, 70", u"413865, Саратовская обл., г. Балаково"],
      site="https://eparhia-balakovo.ru/",
      sources=["https://patriarchia.ru/org/570"]),

 dict(id="ru-balashikha", parent="russia",
      name="Balashikha Diocese",
      local=u"Балашихинская епархия",
      seat="Balashikha", country="RU",
      address=[u"площадь Александра Невского, 2", u"143900, Московская область, город Балашиха"],
      site="http://mosbalepar.ru/",
      sources=["https://patriarchia.ru/org/557"]),

 dict(id="ru-balashov", parent="russia",
      name="Balashov Diocese",
      local=u"Балашовская епархия",
      seat="Balashov", country="RU",
      address=[u"ул. Советская, 168", u"412309, Саратовская область, г. Балашов"],
      site="https://balashovblag.ru/",
      sources=["https://patriarchia.ru/org/314"]),

 dict(id="ru-barnaul", parent="russia",
      name="Barnaul Diocese",
      local=u"Барнаульская епархия",
      seat="Barnaul", country="RU",
      address=[u"пр. Ленина, 17", u"656043, Алтайский край, г. Барнаул"],
      site="https://altayskaya-mitropolia.ru/",
      sources=["https://patriarchia.ru/org/8"]),

 dict(id="ru-barysh", parent="russia",
      name="Barysh Diocese",
      local=u"Барышская епархия",
      seat="Barysh", country="RU",
      address=[u"переулок Пушкина, 26", u"433750, Ульяновская область, г. Барыш"],
      site="http://barysh-eparhia.ru/",
      sources=["https://patriarchia.ru/org/382"]),

 dict(id="ru-bezhetsk", parent="russia",
      name="Bezhetsk Diocese",
      local=u"Бежецкая епархия",
      seat="Bezhetsk", country="RU",
      address=[u"ул. Нечаева, 45", u"171988, Тверская область, г. Бежецк"],
      site="http://bezheparhia.ru/",
      sources=["https://patriarchia.ru/org/344"]),

 dict(id="ru-belgorod", parent="russia",
      name="Belgorod Diocese",
      local=u"Белгородская епархия",
      seat="Belgorod", country="RU",
      address=[u"Свято-Троицкий бульвар, 24", u"308000, г. Белгород"],
      site="https://beleparh.ru/",
      sources=["https://patriarchia.ru/org/9"]),

 dict(id="ru-belyov", parent="russia",
      name="Belyov Diocese",
      local=u"Белевская епархия",
      seat="Belyov", country="RU",
      address=[u"ул. Советская, 2А (епархиальное управление)", u"301369, Тульская область, г. Алексин"],
      site="https://belev-eparhia.ru:443/",
      sources=["https://patriarchia.ru/org/331"]),

 dict(id="ru-balti", parent="russia",
      name="Balti Diocese",
      local=u"Бельцкая епархия",
      seat="Balti", country="MD",
      address=[u"ул. Виссариона Пую, 1", u"МД-3100, муниципия Бэлць"],
      site="https://ephbalti.md/",
      sources=["https://patriarchia.ru/org/237"]),

 dict(id="ru-berlin-and-germany", parent="russia",
      name="Diocese of Berlin and Germany",
      local=u"Берлинско-Германская епархия",
      seat="Berlin", country="DE",
      address=[u"Berliner Diözese der Russischen Orthodoxen Kirche des Moskauer Patriarchats, Wildensteiner Str. 10, 10318 Berlin, Deutschland"],
      site="https://rokmp.de/",
      sources=["https://patriarchia.ru/org/145"]),

 dict(id="ru-biysk", parent="russia",
      name="Biysk Diocese",
      local=u"Бийская епархия",
      seat="Biysk", country="RU",
      address=[u"ул. Советская, 13", u"659300, Алтайский край, г. Бийск"],
      site="https://biysk-eparhia.ru/",
      sources=["https://patriarchia.ru/org/490"]),

 dict(id="ru-birobidzhan", parent="russia",
      name="Birobidzhan Diocese",
      local=u"Биробиджанская епархия",
      seat="Birobidzhan", country="RU",
      address=[u"ул. Ленина, 34", u"679016, Еврейская АО, г. Биробиджан"],
      site="https://eparh.ru/",
      sources=["https://patriarchia.ru/org/10"]),

 dict(id="ru-birsk", parent="russia",
      name="Birsk Diocese",
      local=u"Бирская епархия",
      seat="Birsk", country="RU",
      address=[u"452450, Республика Башкортостан, г. Бирск, Октябрьская пл., 6А"],
      site="https://eparhiabirsk.ru/",
      sources=["https://patriarchia.ru/org/534"]),

 dict(id="ru-bishkek", parent="russia",
      name="Bishkek Diocese",
      local=u"Бишкекская епархия",
      seat="Bishkek", country="KG",
      address=[u"пр. Жибек-Жолу, 497", u"720033, г. Бишкек"],
      site="https://pravoslavie.kg/",
      sources=["https://patriarchia.ru/org/295"]),

 dict(id="ru-blagoveshchensk", parent="russia",
      name="Blagoveshchensk Diocese",
      local=u"Благовещенская епархия",
      seat="Blagoveshchensk", country="RU",
      address=[u"ул. Калинина, 120", u"675000, Амурская область, г. Благовещенск"],
      site="https://blaginform.ru/",
      sources=["https://patriarchia.ru/org/11"]),

 dict(id="ru-babruysk", parent="russia",
      name="Babruysk Diocese",
      local=u"Бобруйская епархия",
      seat="Babruysk", country="BY",
      address=[u"ул. Карбышева, 28-2", u"213809, Республика Беларусь, Могилёвская область, г. Бобруйск"],
      site="https://bobreparhiya.by/",
      sources=["https://patriarchia.ru/org/170"]),

 dict(id="ru-barysaw", parent="russia",
      name="Barysaw Diocese",
      local=u"Борисовская епархия",
      seat="Barysaw", country="BY",
      address=[u"ул. Лопатина, 32", u"222517, Республика Беларусь, Минская область, г. Борисов"],
      sources=["https://patriarchia.ru/org/475"]),

 dict(id="ru-borisoglebsk", parent="russia",
      name="Borisoglebsk Diocese",
      local=u"Борисоглебская епархия",
      seat="Borisoglebsk", country="RU",
      address=[u"ул. 40 лет Октября, 35А", u"397160, Воронежская область, г. Борисоглебск"],
      site="https://bsk-eparhia.ru/",
      sources=["https://patriarchia.ru/org/458"]),

 dict(id="ru-borovichi", parent="russia",
      name="Borovichi Diocese",
      local=u"Боровичская епархия",
      seat="Borovichi", country="RU",
      address=[u"ул. Александра Невского, 6", u"174401, Новгородская обл., г. Боровичи"],
      site="https://boreparhia.ru/",
      sources=["https://patriarchia.ru/org/341"]),

 dict(id="ru-bratsk", parent="russia",
      name="Bratsk Diocese",
      local=u"Братская епархия",
      seat="Bratsk", country="RU",
      address=[u"ул. Всесвятская, зд. 1 (а/я 1911)", u"665727, Иркутская область, г. Братск"],
      site="https://pravbratsk.ru/",
      sources=["https://patriarchia.ru/org/316"]),

 dict(id="ru-brest", parent="russia",
      name="Brest Diocese",
      local=u"Брестская епархия",
      seat="Brest", country="BY",
      address=[u"ул. Гоголя, 74", u"224030, Республика Беларусь, г. Брест"],
      site="https://pravbrest.by/",
      sources=["https://patriarchia.ru/org/130"]),

 dict(id="ru-brussels-and-belgium", parent="russia",
      name="Diocese of Brussels and Belgium",
      local=u"Брюссельско-Бельгийская епархия",
      seat="Brussels", country="BE",
      address=[u"Rue Des Chevaliers 29, 1050, Ixelles, Bruxelles, Belgique"],
      site="http://archiepiskopia.be/",
      sources=["https://patriarchia.ru/org/142"]),

 dict(id="ru-bryansk", parent="russia",
      name="Bryansk Diocese",
      local=u"Брянская епархия",
      seat="Bryansk", country="RU",
      address=[u"ул. Покровская Гора, 5", u"241050, г. Брянск"],
      site="http://www.bryansk-eparhia.ru/",
      sources=["https://patriarchia.ru/org/12"]),

 dict(id="ru-budapest-and-hungary", parent="russia",
      name="Diocese of Budapest and Hungary",
      local=u"Будапештско-Венгерская епархия",
      seat="Budapest", country="HU",
      address=[u"Hungary 1052. Budapest, Petőfi tér 2, 1. em. 2"],
      site="https://magyarortodox.hu/",
      sources=["https://patriarchia.ru/org/144"]),

 dict(id="ru-buzuluk", parent="russia",
      name="Buzuluk Diocese",
      local=u"Бузулукская епархия",
      seat="Buzuluk", country="RU",
      address=[u"461040, Оренбургская область, г. Бузулук, 2 мкрн, д. 34 «З»"],
      site="https://buzulukeparh.ru:443/",
      sources=["https://patriarchia.ru/org/310"]),

 dict(id="ru-valuyki", parent="russia",
      name="Valuyki Diocese",
      local=u"Валуйская епархия",
      seat="Valuyki", country="RU",
      address=[u"ул. Тимирязева, 123", u"309993, Белгородская область, Валуйский район, г. Валуйки"],
      site="https://val-eparh.ru/",
      sources=["https://patriarchia.ru/org/376"]),

 dict(id="ru-vanino", parent="russia",
      name="Vanino Diocese",
      local=u"Ванинская епархия",
      seat="Vanino", country="RU",
      address=[u"ул. Украинская, 9", u"682860, Хабаровский край, Ванинский район, р.п. Ванино"],
      site="https://vanino-eparchia.cerkov.ru/",
      sources=["https://patriarchia.ru/org/519"]),

 dict(id="ru-great-britain-and-western-europe-rocor", parent="rocor",
      name="Diocese of Great Britain and Western Europe (ROCOR)",
      local=u"Великобританская и Западно-Европейская епархия (РПЦЗ)",
      seat="London", country="GB",
      site="https://orthodox-europe.org/",
      sources=["https://patriarchia.ru/org/626"]),

 dict(id="ru-velikiye-luki", parent="russia",
      name="Velikiye Luki Diocese",
      local=u"Великолукская епархия",
      seat="Velikiye Luki", country="RU",
      address=[u"ул. Ставского, д. 63/4", u"182112, Псковская область, г. Великие Луки"],
      site="https://luki-eparhia.ru/",
      sources=["https://patriarchia.ru/org/483"]),

 dict(id="ru-veliky-ustyug", parent="russia",
      name="Veliky Ustyug Diocese",
      local=u"Великоустюжская епархия",
      seat="Veliky Ustyug", country="RU",
      address=[u"Советский проспект, 62", u"162390, Вологодская область, г. Великий Устюг"],
      site="https://vueparhia.ru/",
      sources=["https://patriarchia.ru/org/480"]),

 dict(id="ru-vienna-and-austria", parent="russia",
      name="Diocese of Vienna and Austria",
      local=u"Венско-Австрийская епархия",
      seat="Vienna", country="AT",
      address=[u"Jauresgasse, 2, A-1030 Vienna, Austria"],
      site="https://austria-diocese.com/",
      sources=["https://patriarchia.ru/org/139"]),

 dict(id="ru-vilnius", parent="russia",
      name="Vilnius Diocese",
      local=u"Виленская епархия",
      seat="Vilnius", country="LT",
      address=[u"ул. Аушрос Варту, 10)", u"Aušros vartų 10, Vilnius LT-01303 (Литва, г. Вильнюс"],
      site="https://www.orthodoxy.lt/",
      sources=["https://patriarchia.ru/org/155"]),

 dict(id="ru-vitebsk", parent="russia",
      name="Vitebsk Diocese",
      local=u"Витебская епархия",
      seat="Vitebsk", country="BY",
      address=[u"ул. Чехова, 19", u"210026, Республика Беларусь, г. Витебск"],
      site="https://vitprav.by/",
      sources=["https://patriarchia.ru/org/131"]),

 dict(id="ru-vladivostok", parent="russia",
      name="Vladivostok Diocese",
      local=u"Владивостокская епархия",
      seat="Vladivostok", country="RU",
      address=[u"ул. Пологая, д. 65", u"690091, г. Владивосток"],
      site="https://prim-mitropolia.ru/",
      sources=["https://patriarchia.ru/org/14"]),

 dict(id="ru-vladikavkaz", parent="russia",
      name="Vladikavkaz Diocese",
      local=u"Владикавказская епархия",
      seat="Vladikavkaz", country="RU",
      address=[u"ул. Церетели, 8", u"362040, Республика Северная Осетия-Алания, г. Владикавказ"],
      site="https://www.blagos.ru/",
      sources=["https://patriarchia.ru/org/283"]),

 dict(id="ru-vladimir", parent="russia",
      name="Vladimir Diocese",
      local=u"Владимирская епархия",
      seat="Vladimir", country="RU",
      address=[u"ул. Большая Московская, 68Б", u"600006, Владимирская область, г. Владимир"],
      site="https://eparh33.ru/",
      sources=["https://patriarchia.ru/org/13"]),

 dict(id="ru-volgograd", parent="russia",
      name="Volgograd Diocese",
      local=u"Волгоградская епархия",
      seat="Volgograd", country="RU",
      address=[u"ул. Чапаева, 26", u"400012, г. Волгоград"],
      site="https://volgeparhia.ru/",
      sources=["https://patriarchia.ru/org/15"]),

 dict(id="ru-volgodonsk", parent="russia",
      name="Volgodonsk Diocese",
      local=u"Волгодонская епархия",
      seat="Volgodonsk", country="RU",
      address=[u"ул. Маршала Кошевого, 9В", u"347383, Ростовская область, г. Волгодонск"],
      site="https://viseparchia.ru/",
      sources=["https://patriarchia.ru/org/302"]),

 dict(id="ru-volzhsk", parent="russia",
      name="Volzhsk Diocese",
      local=u"Волжская епархия",
      seat="Volzhsk", country="RU",
      address=[u"ул. Палантая, д. 38", u"425000, РМЭ, г. Волжск"],
      site="https://volzsk-eparhia.ru/",
      sources=["https://patriarchia.ru/org/536"]),

 dict(id="ru-vologda", parent="russia",
      name="Vologda Diocese",
      local=u"Вологодская епархия",
      seat="Vologda", country="RU",
      address=[u"ул. Галкинская, 62А", u"160000, г. Вологда"],
      site="https://vologda-mitropolia.ru/",
      sources=["https://patriarchia.ru/org/16"]),

 dict(id="ru-vorkuta", parent="russia",
      name="Vorkuta Diocese",
      local=u"Воркутинская епархия",
      seat="Vorkuta", country="RU",
      address=[u"пл. Победы, д. 1", u"169907, Республика Коми, г. Воркута"],
      site="https://vorkuta-eparchia.cerkov.ru/",
      sources=["https://patriarchia.ru/org/513"]),

 dict(id="ru-voronezh", parent="russia",
      name="Voronezh Diocese",
      local=u"Воронежская епархия",
      seat="Voronezh", country="RU",
      address=[u"ул. Освобождения труда, 20", u"394036, г. Воронеж"],
      site="https://www.vrn-eparhia.ru/",
      sources=["https://patriarchia.ru/org/3"]),

 dict(id="ru-eastern-america-rocor", parent="rocor",
      name="Diocese of Eastern America (ROCOR)",
      local=u"Восточно-Американская епархия (РПЦЗ)",
      seat="New York", country="US",
      address=[u"Eastern American Diocese, 210 Alexander Avenue, Howell, NJ 07731 USA"],
      site="https://eadiocese.org/",
      sources=["https://patriarchia.ru/org/608"]),

 dict(id="ru-vyborg", parent="russia",
      name="Vyborg Diocese",
      local=u"Выборгская епархия",
      seat="Vyborg", country="RU",
      address=[u"ул. Сторожевой башни, 27", u"Ленинградская область, г. Выборг"],
      site="https://eparhiya-viborg.ru/",
      sources=["https://patriarchia.ru/org/417"]),

 dict(id="ru-vyksa", parent="russia",
      name="Vyksa Diocese",
      local=u"Выксунская епархия",
      seat="Vyksa", country="RU",
      address=[u"ул. Спартака, 33", u"607060, Нижегородская область, г. Выкса"],
      site="https://vyksa-eparhia.ru/",
      sources=["https://patriarchia.ru/org/362"]),

 dict(id="ru-vyazma", parent="russia",
      name="Vyazma Diocese",
      local=u"Вяземская епархия",
      seat="Vyazma", country="RU",
      address=[u"пер. Нагорный, 1, Вяземское епархиальное управление", u"215110, Смоленская обл., г. Вязьма"],
      site="https://vyazmaeparh.ru/",
      sources=["https://patriarchia.ru/org/498"]),

 dict(id="ru-vyatka", parent="russia",
      name="Vyatka Diocese",
      local=u"Вятская епархия",
      seat="Kirov", country="RU",
      address=[u"ул. Горбачева, 4 (Успенский Трифонов мужской монастырь)", u"610000, Кировская область, г. Киров"],
      site="https://xn----7sbbfrtj7bkdk8b3heh.xn--p1ai:443/",
      sources=["https://patriarchia.ru/org/17"]),

 dict(id="ru-hague-and-the-netherlands", parent="russia",
      name="Diocese of The Hague and the Netherlands",
      local=u"Гаагско-Нидерландская епархия",
      seat="The Hague", country="NL",
      address=[u"1e Sweelinckstraat 54 2517 GE, Den Haag"],
      site="https://russian-diocese.nl/",
      sources=["https://patriarchia.ru/org/165"]),

 dict(id="ru-galich", parent="russia",
      name="Galich Diocese",
      local=u"Галичская епархия",
      seat="Galich", country="RU",
      address=[u"ул. Подбельского, 1", u"157201, Костромская обл., г. Галич"],
      site="https://galich-eparhia.cerkov.ru/",
      sources=["https://patriarchia.ru/org/523"]),

 dict(id="ru-gatchina", parent="russia",
      name="Gatchina Diocese",
      local=u"Гатчинская епархия",
      seat="Gatchina", country="RU",
      address=[u"ул. Красная, 1А", u"188300, Ленинградская обл., г. Гатчина"],
      site="https://gatchinaeparhia.ru/",
      sources=["https://patriarchia.ru/org/419"]),

 dict(id="ru-georgiyevsk", parent="russia",
      name="Georgiyevsk Diocese",
      local=u"Георгиевская епархия",
      seat="Georgiyevsk", country="RU",
      address=[u"ул. Строителей, 2", u"357831, Ставропольский край, г. Георгиевск"],
      site="https://georgeparhia.ru/",
      sources=["https://patriarchia.ru/org/369"]),

 dict(id="ru-germany-rocor", parent="rocor",
      name="Diocese of Germany (ROCOR)",
      local=u"Германская епархия (РПЦЗ)",
      seat="Munich", country="DE",
      address=[u"Hofbauernstr. 26, 81247 München"],
      site="https://rocor.de:443/ru/home",
      sources=["https://patriarchia.ru/org/619"]),

 dict(id="ru-glazov", parent="russia",
      name="Glazov Diocese",
      local=u"Глазовская епархия",
      seat="Glazov", country="RU",
      address=[u"пл. Свободы, 10А", u"427620, Удмуртская Республика, г. Глазов"],
      site="http://glazoveparhia.ru/",
      sources=["https://patriarchia.ru/org/461"]),

 dict(id="ru-homel", parent="russia",
      name="Homel Diocese",
      local=u"Гомельская епархия",
      seat="Homel", country="BY",
      address=[u"ул. Митрополита Филарета, 2", u"246014, Республика Беларусь, г. Гомель"],
      site="https://eparhiya.by:443/",
      sources=["https://patriarchia.ru/org/132"]),

 dict(id="ru-gorno-altaysk", parent="russia",
      name="Gorno-Altaysk Diocese",
      local=u"Горноалтайская епархия",
      seat="Gorno-Altaysk", country="RU",
      address=[u"проспект Коммунистический, 150", u"649002, Республика Алтай, г. Горно-Алтайск"],
      site="https://eparhia-gorniyaltay.ru/",
      sources=["https://patriarchia.ru/org/452"]),

 dict(id="ru-gorodets", parent="russia",
      name="Gorodets Diocese",
      local=u"Городецкая епархия",
      seat="Gorodets", country="RU",
      address=[u"пл. Пролетарская, 34Б", u"606502, Нижегородская обл., г. Городец"],
      site="https://egiv.ru/",
      sources=["https://patriarchia.ru/org/363"]),

 dict(id="ru-hrodna", parent="russia",
      name="Hrodna Diocese",
      local=u"Гродненская епархия",
      seat="Hrodna", country="BY",
      address=[u"ул. Митрополита Филарета, 1", u"230023, Республика Беларусь, г. Гродно"],
      site="https://orthos.org/",
      sources=["https://patriarchia.ru/org/133"]),

 dict(id="ru-grozny", parent="russia",
      name="Grozny Diocese",
      local=u"Грозненская епархия",
      seat="Grozny", country="RU",
      address=[u"пр-т А.-Х.А. Кадырова, 52", u"364024, Чеченская Республика, город Грозный"],
      site="https://pravgorcy.ru/",
      sources=["https://patriarchia.ru/org/638"]),

 dict(id="ru-gubkin", parent="russia",
      name="Gubkin Diocese",
      local=u"Губкинская епархия",
      seat="Gubkin", country="RU",
      address=[u"ул. Преображенская, 11", u"309183, Белгородская область, г. Губкин"],
      site="https://губепарх.рф/",
      sources=["https://patriarchia.ru/org/377"]),

 dict(id="ru-daugavpils", parent="russia",
      name="Daugavpils Diocese",
      local=u"Даугавпилсская епархия",
      seat="Daugavpils", country="LV",
      address=[u"18. Novembra iela 95, Daugavpils, LV-5404, Latvija"],
      site="http://eparhija.lv/",
      sources=["https://patriarchia.ru/org/421"]),

 dict(id="ru-dushanbe", parent="russia",
      name="Dushanbe Diocese",
      local=u"Душанбинская епархия",
      seat="Dushanbe", country="TJ",
      address=[u"пр. Дружбы народов (хиебони Дустии Халко), 58", u"734024, Республика Таджикистан, г. Душанбе"],
      site="https://lifted.asia/",
      sources=["https://patriarchia.ru/org/296"]),

 dict(id="ru-edinet", parent="russia",
      name="Edinet Diocese",
      local=u"Единецкая епархия",
      seat="Edinet", country="MD",
      address=[u"Молдова, МД-4601, Единец, Буковинское ш., 35/4"],
      site="https://eparhia-edinet.md/",
      sources=["https://patriarchia.ru/org/162"]),

 dict(id="ru-yeysk", parent="russia",
      name="Yeysk Diocese",
      local=u"Ейская епархия",
      seat="Yeysk", country="RU",
      address=[u"парк им. М. Горького", u"353680, Краснодарский кр., г. Ейск"],
      site="http://eisk-eparh.ru/",
      sources=["https://patriarchia.ru/org/425"]),

 dict(id="ru-yekaterinburg", parent="russia",
      name="Yekaterinburg Diocese",
      local=u"Екатеринбургская епархия",
      seat="Yekaterinburg", country="RU",
      address=[u"ул. Репина, 6А", u"620086, г. Екатеринбург"],
      site="http://www.ekaterinburg-eparhia.ru/",
      sources=["https://patriarchia.ru/org/19"]),

 dict(id="ru-yekaterinodar", parent="russia",
      name="Yekaterinodar Diocese",
      local=u"Екатеринодарская епархия",
      seat="Krasnodar", country="RU",
      address=[u"ул. Соборная (Ленина), д. 60 (время работы: понедельник-пятница 8.00-16.00)", u"350000, г. Краснодар"],
      site="https://mitropoliakuban.ru/",
      sources=["https://patriarchia.ru/org/18"]),

 dict(id="ru-yelets", parent="russia",
      name="Yelets Diocese",
      local=u"Елецкая епархия",
      seat="Yelets", country="RU",
      address=[u"ул. Коммунаров, 52", u"399770, Липецкая область, г. Елец"],
      site="http://el-eparhy.ru/",
      sources=["https://patriarchia.ru/org/436"]),

 dict(id="ru-yeniseysk", parent="russia",
      name="Yeniseysk Diocese",
      local=u"Енисейская епархия",
      seat="Yeniseysk", country="RU",
      address=[u"ул. Рабоче-Крестьянская, 101", u"663180, Красноярский край, г. Енисейск"],
      site="https://xn--80aanabpeej0a2anfc0etig.xn--p1ai:443/",
      sources=["https://patriarchia.ru/org/293"]),

 dict(id="ru-yerevan-and-armenia", parent="russia",
      name="Diocese of Yerevan and Armenia",
      local=u"Ереванско-Армянская епархия",
      seat="Yerevan", country="AM",
      address=[u"ул. Закария Канакерцу, 68", u"Республика Армения, 0091, г. Ереван"],
      site="https://armeparchy.org/",
      sources=["https://patriarchia.ru/org/564"]),

 dict(id="ru-zheleznogorsk", parent="russia",
      name="Zheleznogorsk Diocese",
      local=u"Железногорская епархия",
      seat="Zheleznogorsk", country="RU",
      address=[u"ул. Всесвятская, 3", u"307179, Курская область, г. Железногорск"],
      site="https://www.xn----7sbbjjadclpri2aobumgm1g7jh.xn--p1ai:443/",
      sources=["https://patriarchia.ru/org/386"]),

 dict(id="ru-western-america-rocor", parent="rocor",
      name="Diocese of Western America (ROCOR)",
      local=u"Западно-Американская епархия (РПЦЗ)",
      seat="San Francisco", country="US",
      address=[u"598 15th Avenue, San Francisco, CA 94118"],
      site="https://www.wadiocese.com/",
      sources=["https://patriarchia.ru/org/592"]),

 dict(id="ru-zlatoust", parent="russia",
      name="Zlatoust Diocese",
      local=u"Златоустовская епархия",
      seat="Zlatoust", country="RU",
      address=[u"ул. Таганайская, 45", u"456228, Челябинская область, г. Златоуст"],
      site="https://zlatousteparhiya.ru/",
      sources=["https://patriarchia.ru/org/525"]),

 dict(id="ru-ivanovo-voznesensk", parent="russia",
      name="Ivanovo-Voznesensk Diocese",
      local=u"Иваново-Вознесенская епархия",
      seat="Ivanovo", country="RU",
      address=[u"ул. Смирнова, 76", u"153000, г. Иваново"],
      site="https://iv-eparhya.cerkov.ru/",
      sources=["https://patriarchia.ru/org/21"]),

 dict(id="ru-izhevsk", parent="russia",
      name="Izhevsk Diocese",
      local=u"Ижевская епархия",
      seat="Izhevsk", country="RU",
      address=[u"ул. Максима Горького, 43А", u"426008, Удмуртская Республика, г. Ижевск"],
      site="https://udmeparhia.ru/",
      sources=["https://patriarchia.ru/org/22"]),

 dict(id="ru-irkutsk", parent="russia",
      name="Irkutsk Diocese",
      local=u"Иркутская епархия",
      seat="Irkutsk", country="RU",
      address=[u"ул. Ангарская, 14", u"664001, г. Иркутск"],
      site="http://www.iemp.ru/",
      sources=["https://patriarchia.ru/org/20"]),

 dict(id="ru-isilkul", parent="russia",
      name="Isilkul Diocese",
      local=u"Исилькульская епархия",
      seat="Isilkul", country="RU",
      address=[u"ул. Первомайская, 57", u"646023, Омская область, г. Исилькуль"],
      site="https://isilkuleparchia.ru/",
      sources=["https://patriarchia.ru/org/374"]),

 dict(id="ru-iskitim", parent="russia",
      name="Iskitim Diocese",
      local=u"Искитимская епархия",
      seat="Iskitim", country="RU",
      address=[u"ул. Коллективная, 1/1", u"633227, Новосибирская область, г. Искитим"],
      site="https://iskitimeparhia.ru/",
      sources=["https://patriarchia.ru/org/348"]),

 dict(id="ru-spain-and-portugal", parent="russia",
      name="Diocese of Spain and Portugal",
      local=u"Испанско-Португальская епархия",
      seat="Madrid", country="ES",
      address=[u"Gran Via de Hortaleza, 48 28043 Madrid"],
      site="https://orthodoxspain.com/",
      sources=["https://patriarchia.ru/org/544"]),

 dict(id="ru-ishim", parent="russia",
      name="Ishim Diocese",
      local=u"Ишимская епархия",
      seat="Ishim", country="RU",
      address=[u"ул. Ленинградская, 29", u"627750, Тюменская область, г. Ишим"],
      site="https://xn----7sbbtmaelr8amf3d5a4ih.xn--p1ai/",
      sources=["https://patriarchia.ru/org/448"]),

 dict(id="ru-yoshkar-ola", parent="russia",
      name="Yoshkar-Ola Diocese",
      local=u"Йошкар-Олинская епархия",
      seat="Yoshkar-Ola", country="RU",
      address=[u"ул. Вознесенская, 27", u"424000, Республика Марий Эл"],
      site="https://www.mari-eparhia.ru/",
      sources=["https://patriarchia.ru/org/23"]),

 dict(id="ru-cahul", parent="russia",
      name="Cahul Diocese",
      local=u"Кагульская епархия",
      seat="Cahul", country="MD",
      address=[u"Episcopia de Cahul şi Comrat, Republica Moldova, Mun. Cahul, MD-3900, str. Lev Tolstoi 1"],
      site="https://episcopiasud.md/ro/",
      sources=["https://patriarchia.ru/org/163"]),

 dict(id="ru-kazan", parent="russia",
      name="Kazan Diocese",
      local=u"Казанская епархия",
      seat="Kazan", country="RU",
      address=[u"ул. Карла Маркса, 9/15", u"420111, Республика Татарстан, г. Казань"],
      site="https://tatmitropolia.ru/",
      sources=["https://patriarchia.ru/org/69"]),

 dict(id="ru-kainsk", parent="russia",
      name="Kainsk Diocese",
      local=u"Каинская епархия",
      seat="Kuybyshev", country="RU",
      address=[u"ул. Пугачева, 2", u"632382, Новосибирская область, г. Куйбышев"],
      site="http://kainsk-eparhia.ru/",
      sources=["https://patriarchia.ru/org/346"]),

 dict(id="ru-kalach", parent="russia",
      name="Kalach Diocese",
      local=u"Калачевская епархия",
      seat="Kalach-on-Don", country="RU",
      address=[u"ул. Набережная, 12Б", u"404111, Волгоградская область, г. Волжский"],
      site="https://kalach-eparx.ru/",
      sources=["https://patriarchia.ru/org/354"]),

 dict(id="ru-kalachinsk", parent="russia",
      name="Kalachinsk Diocese",
      local=u"Калачинская епархия",
      seat="Kalachinsk", country="RU",
      address=[u"ул. Семашко, 21", u"646900, Омская обл., г. Калачинск"],
      site="http://kalachinsk-eparhiya.ru/",
      sources=["https://patriarchia.ru/org/373"]),

 dict(id="ru-kaliningrad", parent="russia",
      name="Kaliningrad Diocese",
      local=u"Калининградская епархия",
      seat="Kaliningrad", country="RU",
      address=[u"ул. Иванникова, 18", u"236040, г. Калининград"],
      site="https://kdeparh.ru/",
      sources=["https://patriarchia.ru/org/253"]),

 dict(id="ru-kaluga", parent="russia",
      name="Kaluga Diocese",
      local=u"Калужская епархия",
      seat="Kaluga", country="RU",
      address=[u"ул. Набережная, 4", u"248000, Калужская обл., г. Калуга"],
      site="https://eparhia-kaluga.ru/",
      sources=["https://patriarchia.ru/org/25"]),

 dict(id="ru-kamensk", parent="russia",
      name="Kamensk Diocese",
      local=u"Каменская епархия",
      seat="Kamensk-Uralsky", country="RU",
      address=[u"ул. Кирова, 18", u"623418, Свердловская обл., г. Каменск-Уральский"],
      site="https://kamensk-eparhiya.ru/",
      sources=["https://patriarchia.ru/org/299"]),

 dict(id="ru-canada-rocor", parent="rocor",
      name="Diocese of Canada (ROCOR)",
      local=u"Канадская епархия (РПЦЗ)",
      seat="Montreal", country="CA",
      site="http://mcdiocese.com/",
      sources=["https://patriarchia.ru/org/601"]),

 dict(id="ru-kanash", parent="russia",
      name="Kanash Diocese",
      local=u"Канашская епархия",
      seat="Kanash", country="RU",
      address=[u"ул. Филатова, 2", u"429335, Чувашская Республика"],
      site="http://kan-eparhia.ru/",
      sources=["https://patriarchia.ru/org/400"]),

 dict(id="ru-kansk", parent="russia",
      name="Kansk Diocese",
      local=u"Канская епархия",
      seat="Kansk", country="RU",
      address=[u"ул. Московская, 68", u"663600, г. Канск"],
      site="https://канскаяепархия.рф/",
      sources=["https://patriarchia.ru/org/338"]),

 dict(id="ru-karaganda", parent="russia",
      name="Karaganda Diocese",
      local=u"Карагандинская епархия",
      seat="Karaganda", country="KZ",
      address=[u"ул. Гапеева, 1А", u"100024, Республика Казахстан, г. Караганда"],
      site="http://eparhia.kz/",
      sources=["https://patriarchia.ru/org/271"]),

 dict(id="ru-karasuk", parent="russia",
      name="Karasuk Diocese",
      local=u"Карасукская епархия",
      seat="Karasuk", country="RU",
      address=[u"ул. Октябрьская, 31", u"632868, Новосибирская область, г. Карасук"],
      site="https://www.pravkarasuk.ru/",
      sources=["https://patriarchia.ru/org/347"]),

 dict(id="ru-kasimov", parent="russia",
      name="Kasimov Diocese",
      local=u"Касимовская епархия",
      seat="Kasimov", country="RU",
      address=[u"ул. Карла Маркса, 11", u"391300, Рязанская обл., г. Касимов"],
      site="https://kas-eparhia.ru/",
      sources=["https://patriarchia.ru/org/312"]),

 dict(id="ru-kemerovo", parent="russia",
      name="Kemerovo Diocese",
      local=u"Кемеровская епархия",
      seat="Kemerovo", country="RU",
      address=[u"ул. Соборная, 24, к5", u"650004, Кемеровская область-Кузбасс, г. Кемерово"],
      site="https://mitropolia42.ru/",
      sources=["https://patriarchia.ru/org/67"]),

 dict(id="ru-kinel", parent="russia",
      name="Kinel Diocese",
      local=u"Кинельская епархия",
      seat="Kinel", country="RU",
      address=[u"ул. Демьяна Бедного, 43Б", u"Самарская обл., г.о. Кинель"],
      site="https://kinelepar.ru/",
      sources=["https://patriarchia.ru/org/359"]),

 dict(id="ru-kineshma", parent="russia",
      name="Kineshma Diocese",
      local=u"Кинешемская епархия",
      seat="Kineshma", country="RU",
      address=[u"Волжский бульвар, 4", u"155800, Ивановская область, г. Кинешма"],
      site="https://kineshma-eparhia.tilda.ws/",
      sources=["https://patriarchia.ru/org/380"]),

 dict(id="ru-chisinau", parent="russia",
      name="Chisinau Diocese",
      local=u"Кишиневская епархия",
      seat="Chisinau", country="MD",
      address=[u"ул. Букурешть 119, мун. Кишинэу", u"MD-2004"],
      site="https://mitropolia.md/",
      sources=["https://patriarchia.ru/org/164"]),

 dict(id="ru-klintsy", parent="russia",
      name="Klintsy Diocese",
      local=u"Клинцовская епархия",
      seat="Klintsy", country="RU",
      address=[u"пер. Богунского полка, 13а", u"243140, Брянская область, г. Клинцы"],
      site="https://eparhia-klintsy.ru/",
      sources=["https://patriarchia.ru/org/438"]),

 dict(id="ru-kozelsk", parent="russia",
      name="Kozelsk Diocese",
      local=u"Козельская епархия",
      seat="Kozelsk", country="RU",
      address=[u"ул. Б. Советская, 6", u"Калужская обл., г. Козельск"],
      site="https://www.kozelsk-eparhia.ru/",
      sources=["https://patriarchia.ru/org/445"]),

 dict(id="ru-kokshetau", parent="russia",
      name="Kokshetau Diocese",
      local=u"Кокшетауская епархия",
      seat="Kokshetau", country="KZ",
      address=[u"ул. Валиханова, 68", u"020000, Республика Казахстан, Акмолинская обл., г. Кокшетау"],
      site="https://pravest-kokshe.kz/",
      sources=["https://patriarchia.ru/org/306"]),

 dict(id="ru-kolomna", parent="russia",
      name="Kolomna Diocese",
      local=u"Коломенская епархия",
      seat="Kolomna", country="RU",
      address=[u"площадь Соборная, дом 3, корпус 1 (Западная стена Ново-Голутвина женского монастыря)", u"140400, Московская область, город Коломна"],
      site="https://mosmit.ru/eparhy/",
      sources=["https://patriarchia.ru/org/556"]),

 dict(id="ru-kolpashevo", parent="russia",
      name="Kolpashevo Diocese",
      local=u"Колпашевская епархия",
      seat="Kolpashevo", country="RU",
      address=[u"ул. Белинского, 1", u"636460, Томская область, г. Колпашево"],
      site="https://svjatoynarym.ru/",
      sources=["https://patriarchia.ru/org/431"]),

 dict(id="ru-korea", parent="russia",
      name="Diocese of Korea",
      local=u"Корейская епархия",
      seat="Seoul", country="KR",
      address=[u"Korean Diocese of the Russian Orthodox Church Moscow Patriarchate, 45-11 Hangang-daero 62 gil, Hangangno-dong, Seoul, Korea 04382"],
      site="https://churchkr.com:443/",
      sources=["https://patriarchia.ru/org/547"]),

 dict(id="ru-korsun", parent="russia",
      name="Korsun Diocese",
      local=u"Корсунская епархия",
      seat="Paris", country="FR",
      address=[u"26, rue Péclet, 75015 Paris; 1 Quai Branly, 75007, Paris, France (физический)"],
      site="https://www.cerkov-ru.com/",
      sources=["https://patriarchia.ru/org/150"]),

 dict(id="ru-kostanay", parent="russia",
      name="Kostanay Diocese",
      local=u"Костанайская епархия",
      seat="Kostanay", country="KZ",
      address=[u"ул. Алтынсарина, 206, Константино-Еленинский кафедральный собор", u"110000, Республика Казахстан, г. Костанай"],
      site="https://kst-eparhia.kz/",
      sources=["https://patriarchia.ru/org/272"]),

 dict(id="ru-kostomuksha", parent="russia",
      name="Kostomuksha Diocese",
      local=u"Костомукшская епархия",
      seat="Kostomuksha", country="RU",
      address=[u"ул. Советская, д. 20", u"186931, Республика Карелия, г. Костомукша"],
      site="https://kosta.cerkov.ru/",
      sources=["https://patriarchia.ru/org/434"]),

 dict(id="ru-kostroma", parent="russia",
      name="Kostroma Diocese",
      local=u"Костромская епархия",
      seat="Kostroma", country="RU",
      address=[u"ул. Симановского, 26/37", u"156000, Кострома"],
      site="https://kostromamitropolia.ru/",
      sources=["https://patriarchia.ru/org/68"]),

 dict(id="ru-kotlas", parent="russia",
      name="Kotlas Diocese",
      local=u"Котласская епархия",
      seat="Kotlas", country="RU",
      address=[u"ул. Кедровая, 1", u"165651, Архангельская обл., г. Коряжма"],
      site="http://www.kotlas-eparhia.ru/",
      sources=["https://patriarchia.ru/org/333"]),

 dict(id="ru-krasnoslobodsk", parent="russia",
      name="Krasnoslobodsk Diocese",
      local=u"Краснослободская епархия",
      seat="Krasnoslobodsk", country="RU",
      address=[u"431260, Республика Мордовия, г. Краснослободск, Больничный пер., 2"],
      sources=["https://patriarchia.ru/org/289"]),

 dict(id="ru-krasnoyarsk", parent="russia",
      name="Krasnoyarsk Diocese",
      local=u"Красноярская епархия",
      seat="Krasnoyarsk", country="RU",
      address=[u"ул. Горького, 27", u"660021, г. Красноярск"],
      site="https://kerpc.ru/",
      sources=["https://patriarchia.ru/org/27"]),

 dict(id="ru-kudymkar", parent="russia",
      name="Kudymkar Diocese",
      local=u"Кудымкарская епархия",
      seat="Kudymkar", country="RU",
      address=[u"ул. Советская, 33", u"619000, Пермский край, г. Кудымкар"],
      site="https://pravparma.ru/",
      sources=["https://patriarchia.ru/org/466"]),

 dict(id="ru-kuznetsk", parent="russia",
      name="Kuznetsk Diocese",
      local=u"Кузнецкая епархия",
      seat="Kuznetsk", country="RU",
      address=[u"ул. Молодой Гвардии, 85", u"442530, Пензенская область, г. Кузнецк"],
      site="https://kuzneparhia.ru/",
      sources=["https://patriarchia.ru/org/392"]),

 dict(id="ru-kurgan", parent="russia",
      name="Kurgan Diocese",
      local=u"Курганская епархия",
      seat="Kurgan", country="RU",
      address=[u"ул. Володарского, 42", u"640000, г. Курган"],
      site="https://kurganvera.ru/",
      sources=["https://patriarchia.ru/org/28"]),

 dict(id="ru-kursk", parent="russia",
      name="Kursk Diocese",
      local=u"Курская епархия",
      seat="Kursk", country="RU",
      address=[u"ул. Ленина, 55", u"305000, г. Курск"],
      site="https://www.xn----7sbbtqha7begew9a9jh.xn--p1ai/",
      sources=["https://patriarchia.ru/org/29"]),

 dict(id="ru-kyzyl", parent="russia",
      name="Kyzyl Diocese",
      local=u"Кызыльская епархия",
      seat="Kyzyl", country="RU",
      address=[u"ул. Московская, д. 7 (Воскресенский кафедральный собор)", u"667008, Республика Тыва, г. Кызыл"],
      site="https://pravtyva.ru/",
      sources=["https://patriarchia.ru/org/309"]),

 dict(id="ru-livny", parent="russia",
      name="Livny Diocese",
      local=u"Ливенская епархия",
      seat="Livny", country="RU",
      address=[u"площадь Сергея Булгакова, 15", u"303850, Орловская область, г. Ливны"],
      site="https://livnyeparhia.online/",
      sources=["https://patriarchia.ru/org/472"]),

 dict(id="ru-lida", parent="russia",
      name="Lida Diocese",
      local=u"Лидская епархия",
      seat="Lida", country="BY",
      address=[u"ул. Советская, 20", u"231300, Республика Беларусь, Гродненская обл., г. Лида"],
      site="http://lida-eparhia.by/",
      sources=["https://patriarchia.ru/org/484"]),

 dict(id="ru-lipetsk", parent="russia",
      name="Lipetsk Diocese",
      local=u"Липецкая епархия",
      seat="Lipetsk", country="RU",
      address=[u"ул. Ленина, 34А", u"398020, г. Липецк"],
      site="https://mitropolia-lip.ru/",
      sources=["https://patriarchia.ru/org/30"]),

 dict(id="ru-lyskovo", parent="russia",
      name="Lyskovo Diocese",
      local=u"Лысковская епархия",
      seat="Lyskovo", country="RU",
      address=[u"ул. Луначарского, 24", u"606210, Нижегородская область, г. Лысково"],
      site="https://lyskovskaya-eparhya.ru/",
      sources=["https://patriarchia.ru/org/357"]),

 dict(id="ru-magadan", parent="russia",
      name="Magadan Diocese",
      local=u"Магаданская епархия",
      seat="Magadan", country="RU",
      address=[u"685000, г. Магадан, Соборная пл., д. 1"],
      site="https://www.magadan-eparchy.ru/",
      sources=["https://patriarchia.ru/org/31"]),

 dict(id="ru-magnitogorsk", parent="russia",
      name="Magnitogorsk Diocese",
      local=u"Магнитогорская епархия",
      seat="Magnitogorsk", country="RU",
      address=[u"ул. Вознесенская, 33", u"455045, Челябинская область, г. Магнитогорск"],
      site="https://mgn-eparhia.ru/",
      sources=["https://patriarchia.ru/org/390"]),

 dict(id="ru-maykop", parent="russia",
      name="Maykop Diocese",
      local=u"Майкопская епархия",
      seat="Maykop", country="RU",
      address=[u"ул. Дальняя, 1А", u"385008, Республика Адыгея, г. Майкоп"],
      site="https://adygeya-orthodoxia.ru/",
      sources=["https://patriarchia.ru/org/32"]),

 dict(id="ru-mariinsk", parent="russia",
      name="Mariinsk Diocese",
      local=u"Мариинская епархия",
      seat="Yurga", country="RU",
      address=[u"пр. Кузбасский, 15А", u"652062, Кемеровская область, г. Юрга"],
      sources=["https://patriarchia.ru/org/395"]),

 dict(id="ru-makhachkala", parent="russia",
      name="Makhachkala Diocese",
      local=u"Махачкалинская епархия",
      seat="Makhachkala", country="RU",
      address=[u"ул. Орджоникидзе, 148", u"367009, Республика Дагестан, г. Махачкала"],
      site="https://goragospodnya.ru:443/",
      sources=["https://patriarchia.ru/org/410"]),

 dict(id="ru-melekess", parent="russia",
      name="Melekess Diocese",
      local=u"Мелекесская епархия",
      seat="Dimitrovgrad", country="RU",
      address=[u"ул. Куйбышева, 215А", u"433508, Ульяновская область, г. Димитровград"],
      site="http://meleparhia.ru/",
      sources=["https://patriarchia.ru/org/383"]),

 dict(id="ru-minsk", parent="russia",
      name="Minsk Diocese",
      local=u"Минская епархия",
      seat="Minsk", country="BY",
      address=[u"ул. Освобождения, д. 10", u"220004, Республика Беларусь, г. Минск"],
      sources=["https://patriarchia.ru/org/129"]),

 dict(id="ru-minusinsk", parent="russia",
      name="Minusinsk Diocese",
      local=u"Минусинская епархия",
      seat="Minusinsk", country="RU",
      address=[u"ул. Комсомольская, д. 10", u"662608, Красноярский край, г. Минусинск"],
      site="http://минусинскаяепархия.рф/",
      sources=["https://patriarchia.ru/org/542"]),

 dict(id="ru-michurinsk", parent="russia",
      name="Michurinsk Diocese",
      local=u"Мичуринская епархия",
      seat="Michurinsk", country="RU",
      address=[u"ул. Революционная, 70", u"393760, Тамбовская область, г. Мичуринск"],
      site="http://michurinsk-eparchia.ru/",
      sources=["https://patriarchia.ru/org/412"]),

 dict(id="ru-mahilyow", parent="russia",
      name="Mahilyow Diocese",
      local=u"Могилевская епархия",
      seat="Mahilyow", country="BY",
      address=[u"ул. Первомайская, 75", u"212030, Республика Беларусь, г. Могилев"],
      site="http://mogeparhia.by/",
      sources=["https://patriarchia.ru/org/134"]),

 dict(id="ru-maladzyechna", parent="russia",
      name="Maladzyechna Diocese",
      local=u"Молодечненская епархия",
      seat="Maladzyechna", country="BY",
      address=[u"пл. Старое Место", u"юридический: Республика Беларусь, Минская обл., г. Молодечно"],
      site="https://molod-eparchy.by/en/",
      sources=["https://patriarchia.ru/org/476"]),

 dict(id="ru-moscow-city", parent="russia",
      name="Moscow City Diocese",
      local=u"Московская (городская) епархия",
      seat="Moscow", country="RU",
      address=[u"Чистый переулок, д. 5", u"119034, г. Москва"],
      site="https://moseparh.ru/",
      sources=["https://patriarchia.ru/org/279"]),

 dict(id="ru-murmansk", parent="russia",
      name="Murmansk Diocese",
      local=u"Мурманская епархия",
      seat="Murmansk", country="RU",
      address=[u"ул. Зеленая, 11", u"183010, г. Мурманск"],
      site="https://mmeparh.cerkov.ru/",
      sources=["https://patriarchia.ru/org/34"]),

 dict(id="ru-murom", parent="russia",
      name="Murom Diocese",
      local=u"Муромская епархия",
      seat="Murom", country="RU",
      address=[u"ул. Лакина, 1А", u"602267, Владимирская обл., г. Муром"],
      site="https://meparhiya.ru/",
      sources=["https://patriarchia.ru/org/442"]),

 dict(id="ru-naberezhnye-chelny", parent="russia",
      name="Naberezhnye Chelny Diocese",
      local=u"Набережночелнинская епархия",
      seat="Naberezhnye Chelny", country="RU",
      address=[u"пр-т Чулман, 127", u"423826, Республика Татарстан, г. Набережные Челны"],
      site="https://pravchelny.ru/",
      sources=["https://patriarchia.ru/org/635"]),

 dict(id="ru-narva", parent="russia",
      name="Narva Diocese",
      local=u"Нарвская епархия",
      seat="Narva", country="EE",
      address=[u"Estonia, Narva, 20308, Linda-11"],
      site="http://www.narvaeparhia.ee/",
      sources=["https://patriarchia.ru/org/287"]),

 dict(id="ru-naryan-mar", parent="russia",
      name="Naryan-Mar Diocese",
      local=u"Нарьян-Марская епархия",
      seat="Naryan-Mar", country="RU",
      address=[u"Соборная площадь, 7", u"166000, Ненецкий автономный округ, г. Нарьян-Мар"],
      site="https://pravarctic.cerkov.ru/",
      sources=["https://patriarchia.ru/org/335"]),

 dict(id="ru-nakhodka", parent="russia",
      name="Nakhodka Diocese",
      local=u"Находкинская епархия",
      seat="Nakhodka", country="RU",
      address=[u"692926, Приморский край, г. Находка, Находкинский пр-т, 33, стр.1"],
      site="http://rpcne.ru/",
      sources=["https://patriarchia.ru/org/297"]),

 dict(id="ru-nerchinsk", parent="russia",
      name="Nerchinsk Diocese",
      local=u"Нерчинская епархия",
      seat="Nerchinsk", country="RU",
      address=[u"ул. Погодаева, 85", u"673400, Забайкальский край, г. Нерчинск"],
      site="https://nerch-eparh.ru/",
      sources=["https://patriarchia.ru/org/488"]),

 dict(id="ru-neftekamsk", parent="russia",
      name="Neftekamsk Diocese",
      local=u"Нефтекамская епархия",
      seat="Neftekamsk", country="RU",
      address=[u"ул. Трактовая, 13А", u"452681, Республика Башкортостан, г. Нефтекамск"],
      site="http://nefeparhia.ru/",
      sources=["https://patriarchia.ru/org/337"]),

 dict(id="ru-nizhny-novgorod", parent="russia",
      name="Nizhny Novgorod Diocese",
      local=u"Нижегородская епархия",
      seat="Nizhny Novgorod", country="RU",
      address=[u"ул. Суздальская, 58", u"603058, г. Нижний Новгород"],
      site="https://nne.ru/",
      sources=["https://patriarchia.ru/org/35"]),

 dict(id="ru-nizhny-tagil", parent="russia",
      name="Nizhny Tagil Diocese",
      local=u"Нижнетагильская епархия",
      seat="Nizhny Tagil", country="RU",
      address=[u"ул. Первомайская, д. 15", u"622001, г. Нижний Тагил"],
      site="http://tagileparhiya.ru/",
      sources=["https://patriarchia.ru/org/300"]),

 dict(id="ru-nikolayevsk-on-amur", parent="russia",
      name="Nikolayevsk-on-Amur Diocese",
      local=u"Николаевская-на-Амуре епархия",
      seat="Nikolayevsk-on-Amur", country="RU",
      address=[u"ул. Луначарского, 105", u"Хабаровский край, г. Николаевск-на-Амуре"],
      site="https://nikolvikar.cerkov.ru/",
      sources=["https://patriarchia.ru/org/397"]),

 dict(id="ru-novgorod", parent="russia",
      name="Novgorod Diocese",
      local=u"Новгородская епархия",
      seat="Veliky Novgorod", country="RU",
      address=[u"Юрьевское шоссе, 10, Свято-Юрьев мужской монастырь", u"173007, город Великий Новгород"],
      site="https://www.vn-eparhia.ru:443/",
      sources=["https://patriarchia.ru/org/36"]),

 dict(id="ru-navahrudak", parent="russia",
      name="Navahrudak Diocese",
      local=u"Новогрудская епархия",
      seat="Navahrudak", country="BY",
      address=[u"ул. Соборная, 57", u"231822, Республика Беларусь, Гродненская область, Слонимский район, агрогородок Жировичи"],
      site="http://www.eparhia.by/novogrudskaja-eparkhija.html",
      sources=["https://patriarchia.ru/org/135"]),

 dict(id="ru-novokuznetsk", parent="russia",
      name="Novokuznetsk Diocese",
      local=u"Новокузнецкая епархия",
      seat="Novokuznetsk", country="RU",
      address=[u"Заводское шоссе, 32", u"654031, Кемеровская область, г. Новокузнецк"],
      site="http://eparhia-nk.ru/",
      sources=["https://patriarchia.ru/org/396"]),

 dict(id="ru-novorossiysk", parent="russia",
      name="Novorossiysk Diocese",
      local=u"Новороссийская епархия",
      seat="Novorossiysk", country="RU",
      address=[u"ул. Кирова, 13", u"353490, Краснодарский край, г. Геленджик, с. Дивноморское"],
      site="https://eparh.info/",
      sources=["https://patriarchia.ru/org/424"]),

 dict(id="ru-novosibirsk", parent="russia",
      name="Novosibirsk Diocese",
      local=u"Новосибирская епархия",
      seat="Novosibirsk", country="RU",
      address=[u"ул. Сибревкома, 8", u"630007, г. Новосибирск"],
      site="https://www.nskmi.ru/",
      sources=["https://patriarchia.ru/org/37"]),

 dict(id="ru-norilsk", parent="russia",
      name="Norilsk Diocese",
      local=u"Норильская епархия",
      seat="Norilsk", country="RU",
      address=[u"ул. Пушкина, 11", u"663305, Красноярский край, г. Норильск"],
      site="http://norilskeparhia.ru/",
      sources=["https://patriarchia.ru/org/470"]),

 dict(id="ru-odintsovo", parent="russia",
      name="Odintsovo Diocese",
      local=u"Одинцовская епархия",
      seat="Odintsovo", country="RU",
      address=[u"ул. Можайское шоссе, д. 72", u"143005, Московская обл., г. Одинцово"],
      site="https://odinceparh.ru/",
      sources=["https://patriarchia.ru/org/558"]),

 dict(id="ru-omsk", parent="russia",
      name="Omsk Diocese",
      local=u"Омская епархия",
      seat="Omsk", country="RU",
      address=[u"ул. Интернациональная, 25", u"644099, г. Омск"],
      site="http://omsk-eparhiya.ru/",
      sources=["https://patriarchia.ru/org/38"]),

 dict(id="ru-orenburg", parent="russia",
      name="Orenburg Diocese",
      local=u"Оренбургская епархия",
      seat="Orenburg", country="RU",
      address=[u"ул. Советская, 43", u"460000, г. Оренбург"],
      site="https://oren-eparh.ru/",
      sources=["https://patriarchia.ru/org/40"]),

 dict(id="ru-oryol", parent="russia",
      name="Oryol Diocese",
      local=u"Орловская епархия",
      seat="Oryol", country="RU",
      address=[u"Монастырская площадь, 1", u"302040, г. Орёл"],
      site="https://www.orel-eparhia.ru/",
      sources=["https://patriarchia.ru/org/39"]),

 dict(id="ru-orsk", parent="russia",
      name="Orsk Diocese",
      local=u"Орская епархия",
      seat="Orsk", country="RU",
      address=[u"ул. Ленинского Комсомола, 2", u"462428, Оренбургская обл., г. Орск"],
      site="http://www.orskeparh.ru/",
      sources=["https://patriarchia.ru/org/311"]),

 dict(id="ru-otradny", parent="russia",
      name="Otradny Diocese",
      local=u"Отрадненская епархия",
      seat="Otradny", country="RU",
      address=[u"ул. Орлова, 11А", u"446330, Самарская область, Кинель-Черкасский район, г. Отрадный"],
      site="https://otradnenskay.cerkov.ru/",
      sources=["https://patriarchia.ru/org/360"]),

 dict(id="ru-pavlodar", parent="russia",
      name="Pavlodar Diocese",
      local=u"Павлодарская епархия",
      seat="Pavlodar", country="KZ",
      address=[u"ул. Торайгырова, 1/5, Благовещенский кафедральный собор", u"140005, г. Павлодар"],
      site="http://pavlodar-eparhia.ru/",
      sources=["https://patriarchia.ru/org/273"]),

 dict(id="ru-turkmenistan", parent="russia",
      name="Patriarchal Deanery of the Parishes in Turkmenistan",
      local=u"Патриаршее благочиние приходов Русской Православной Церкви в Туркменистане",
      seat="Ashgabat", country="TM",
      address=[u"ул. 2091 ул. Амандурды Мередова, 1", u"744002, г. Ашхабад"],
      site="https://orthodoxy.tm/",
      sources=["https://patriarchia.ru/org/262"]),

 dict(id="ru-penza", parent="russia",
      name="Penza Diocese",
      local=u"Пензенская епархия",
      seat="Penza", country="RU",
      address=[u"Соборная площадь, д. 1", u"440026, г. Пенза"],
      site="https://xn----7sbbracknn1actjpi5e2ih.xn--p1ai/",
      sources=["https://patriarchia.ru/org/41"]),

 dict(id="ru-pereslavl", parent="russia",
      name="Pereslavl Diocese",
      local=u"Переславская епархия",
      seat="Pereslavl-Zalessky", country="RU",
      address=[u"ул. Московская, 85/8", u"152024, Ярославская область, г. Переславль-Залесский"],
      site="https://preparhia.ru/",
      sources=["https://patriarchia.ru/org/510"]),

 dict(id="ru-perm", parent="russia",
      name="Perm Diocese",
      local=u"Пермская епархия",
      seat="Perm", country="RU",
      address=[u"ул. Монастырская, 93", u"614990, г. Пермь"],
      site="http://www.pravperm.ru/",
      sources=["https://patriarchia.ru/org/42"]),

 dict(id="ru-pesochnya", parent="russia",
      name="Pesochnya Diocese",
      local=u"Песоченская епархия",
      seat="Kirov", country="RU",
      address=[u"ул. Пролетарская, 36А", u"249440, Калужская область, Кировский район, г. Киров"],
      site="https://pesochny-eparhia.cerkov.ru/",
      sources=["https://patriarchia.ru/org/446"]),

 dict(id="ru-petrozavodsk", parent="russia",
      name="Petrozavodsk Diocese",
      local=u"Петрозаводская епархия",
      seat="Petrozavodsk", country="RU",
      address=[u"ул. Федосовой, 10", u"185035, Республика Карелия, г. Петрозаводск"],
      site="https://eparhia10.ru/",
      sources=["https://patriarchia.ru/org/44"]),

 dict(id="ru-petropavlovsk", parent="russia",
      name="Petropavlovsk Diocese",
      local=u"Петропавловская епархия",
      seat="Petropavlovsk-Kamchatsky", country="RU",
      address=[u"ул. Владивостокская, 18", u"683000, г. Петропавловск-Камчатский"],
      site="http://pravkamchatka.ru/",
      sources=["https://patriarchia.ru/org/43"]),

 dict(id="ru-petropavl-and-bulayevo", parent="russia",
      name="Diocese of Petropavl and Bulayevo",
      local=u"Петропавловско-Булаевская епархия",
      seat="Petropavl", country="KZ",
      address=[u"ул. Жалела Кизатова, д. 55", u"150013, г. Петропавловск"],
      site="http://pbe.kz/",
      sources=["https://patriarchia.ru/org/308"]),

 dict(id="ru-pinsk", parent="russia",
      name="Pinsk Diocese",
      local=u"Пинская епархия",
      seat="Pinsk", country="BY",
      address=[u"ул. Первомайская, 15", u"225710, Республика Беларусь, Брестская обл., г. Пинск"],
      site="http://pinskeparh.by/",
      sources=["https://patriarchia.ru/org/136"]),

 dict(id="ru-plesetsk", parent="russia",
      name="Plesetsk Diocese",
      local=u"Плесецкая епархия",
      seat="Plesetsk", country="RU",
      address=[u"ул. Пушкина, 2А. Адрес епархиального управления в Плесецке: 164262, Архангельская обл., Плесецкий р-н, р.п. Плесецк, ул. Партизанская, 33", u"Адрес епархиального управления в г. Мирном (космодром «Плесецк»): 164170, Архангельская обл., городской округ Мирный"],
      sources=["https://patriarchia.ru/org/531"]),

 dict(id="ru-podolsk", parent="russia",
      name="Podolsk Diocese",
      local=u"Подольская епархия",
      seat="Podolsk", country="RU",
      address=[u"ул. Красная, 24Б", u"142100, Московская обл., г.о. Подольск"],
      site="https://podolskeparh.ru/",
      sources=["https://patriarchia.ru/org/559"]),

 dict(id="ru-pokrovsk", parent="russia",
      name="Pokrovsk Diocese",
      local=u"Покровская епархия",
      seat="Engels", country="RU",
      address=[u"пл. Свободы, 5", u"413100, Саратовская область, г. Энгельс"],
      site="https://pokrovprav.ru/",
      sources=["https://patriarchia.ru/org/315"]),

 dict(id="ru-polatsk", parent="russia",
      name="Polatsk Diocese",
      local=u"Полоцкая епархия",
      seat="Polatsk", country="BY",
      address=[u"ул. Евфросинии Полоцкой, 80", u"211404, Республика Беларусь, Витебская обл., г. Полоцк"],
      site="https://www.eparhia992.by/",
      sources=["https://patriarchia.ru/org/137"]),

 dict(id="ru-pskov", parent="russia",
      name="Pskov Diocese",
      local=u"Псковская епархия",
      seat="Pskov", country="RU",
      address=[u"ул. Советская, 21", u"180000, г. Псков"],
      site="https://pskov-eparhia.ru/",
      sources=["https://patriarchia.ru/org/45"]),

 dict(id="ru-pyatigorsk", parent="russia",
      name="Pyatigorsk Diocese",
      local=u"Пятигорская епархия",
      seat="Pyatigorsk", country="RU",
      address=[u"бульвар Гагарина, 2Б", u"357500, Ставропольский край, г. Пятигорск"],
      site="http://blago-kavkaz.ru/",
      sources=["https://patriarchia.ru/org/282"]),

 dict(id="ru-rzhev", parent="russia",
      name="Rzhev Diocese",
      local=u"Ржевская епархия",
      seat="Rzhev", country="RU",
      address=[u"ул. Большая Спасская, 33/57", u"172381, Тверская область, г. Ржев"],
      site="https://xn--80aaelcctm1cdig2dxhg.xn--p1ai/",
      sources=["https://patriarchia.ru/org/343"]),

 dict(id="ru-riga", parent="russia",
      name="Riga Diocese",
      local=u"Рижская епархия",
      seat="Riga", country="LV",
      site="http://www.pareizticiba.lv/",
      sources=["https://patriarchia.ru/org/422"]),

 dict(id="ru-roslavl", parent="russia",
      name="Roslavl Diocese",
      local=u"Рославльская епархия",
      seat="Roslavl", country="RU",
      address=[u"ул. Пролетарская, 52", u"216500, Смоленская обл., г. Рославль"],
      site="https://roslavlep.ru/",
      sources=["https://patriarchia.ru/org/533"]),

 dict(id="ru-rossosh", parent="russia",
      name="Rossosh Diocese",
      local=u"Россошанская епархия",
      seat="Rossosh", country="RU",
      address=[u"396659, Воронежская обл., г. Россошь, Октябрьская пл., 19А"],
      site="https://roseparhia.ru/",
      sources=["https://patriarchia.ru/org/456"]),

 dict(id="ru-rostov-on-don", parent="russia",
      name="Rostov-on-Don Diocese",
      local=u"Ростовская епархия",
      seat="Rostov-on-Don", country="RU",
      address=[u"ул. Московская, 56", u"344002, г. Ростов-на-Дону"],
      site="https://rostoveparhia.ru/",
      sources=["https://patriarchia.ru/org/46"]),

 dict(id="ru-rubtsovsk", parent="russia",
      name="Rubtsovsk Diocese",
      local=u"Рубцовская епархия",
      seat="Rubtsovsk", country="RU",
      address=[u"ул. Советская, 9", u"658224, Алтайский край, г. Рубцовск"],
      site="https://www.rubtsovsk-eparhia.ru/",
      sources=["https://patriarchia.ru/org/491"]),

 dict(id="ru-rybinsk", parent="russia",
      name="Rybinsk Diocese",
      local=u"Рыбинская епархия",
      seat="Rybinsk", country="RU",
      address=[u"ул. Крестовая, д. 3/5", u"152901, Ярославская обл., г. Рыбинск"],
      site="https://rybeparhia.ru/",
      sources=["https://patriarchia.ru/org/356"]),

 dict(id="ru-ryazan", parent="russia",
      name="Ryazan Diocese",
      local=u"Рязанская епархия",
      seat="Ryazan", country="RU",
      address=[u"пл. Соборная, 3", u"390000, г. Рязань"],
      site="https://ryazeparh.ru/",
      sources=["https://patriarchia.ru/org/47"]),

 dict(id="ru-salavat", parent="russia",
      name="Salavat Diocese",
      local=u"Салаватская епархия",
      seat="Salavat", country="RU",
      address=[u"ул. Уфимская, 35", u"453261, Республика Башкортостан, г. Салават"],
      site="https://www.eparhia-salavat.ru/",
      sources=["https://patriarchia.ru/org/339"]),

 dict(id="ru-salekhard", parent="russia",
      name="Salekhard Diocese",
      local=u"Салехардская епархия",
      seat="Salekhard", country="RU",
      address=[u"ул. Ного, 8", u"629007, Тюменская область, Ямало-Ненецкий автономный округ"],
      site="https://yamalrpc.ru/",
      sources=["https://patriarchia.ru/org/292"]),

 dict(id="ru-samara", parent="russia",
      name="Samara Diocese",
      local=u"Самарская епархия",
      seat="Samara", country="RU",
      address=[u"ул. Вилоновская, 22", u"443001, Самарская область, г. Самара"],
      site="http://samepar.ru/",
      sources=["https://patriarchia.ru/org/49"]),

 dict(id="ru-saint-petersburg", parent="russia",
      name="Saint Petersburg Diocese",
      local=u"Санкт-Петербургская епархия",
      seat="Saint Petersburg", country="RU",
      address=[u"набережная реки Монастырки, 1 (территория Александро-Невской лавры)", u"191167, г. Санкт-Петербург, Центральный район"],
      site="https://mitropolia.spb.ru/",
      sources=["https://patriarchia.ru/org/54"]),

 dict(id="ru-saransk", parent="russia",
      name="Saransk Diocese",
      local=u"Саранская епархия",
      seat="Saransk", country="RU",
      address=[u"ул. Московская, 2", u"430000, Республика Мордовия, г. Саранск"],
      site="http://www.sarep.ru/",
      sources=["https://patriarchia.ru/org/50"]),

 dict(id="ru-sarapul", parent="russia",
      name="Sarapul Diocese",
      local=u"Сарапульская епархия",
      seat="Sarapul", country="RU",
      address=[u"ул. Гончарова, 48А", u"427968, Удмуртская Республика, г. Сарапул"],
      site="https://eparhia-sarapul.ru/",
      sources=["https://patriarchia.ru/org/460"]),

 dict(id="ru-saratov", parent="russia",
      name="Saratov Diocese",
      local=u"Саратовская епархия",
      seat="Saratov", country="RU",
      address=[u"ул. Волжская, д. 36", u"410031, г. Саратов"],
      site="https://saratov-eparhia.ru/",
      sources=["https://patriarchia.ru/org/51"]),

 dict(id="ru-sayansk", parent="russia",
      name="Sayansk Diocese",
      local=u"Саянская епархия",
      seat="Sayansk", country="RU",
      address=[u"а/я 352", u"почтовый адрес: 666304, Иркутская область, г. Саянск"],
      site="https://sayansk-eparchy.ru:443/",
      sources=["https://patriarchia.ru/org/317"]),

 dict(id="ru-north-africa", parent="russia",
      name="Diocese of North Africa",
      local=u"Северо-Африканская епархия",
      seat="Cairo", country="EG",
      site="https://exarchate-africa.ru/",
      sources=["https://patriarchia.ru/org/566"]),

 dict(id="ru-severobaykalsk", parent="russia",
      name="Severobaykalsk Diocese",
      local=u"Северобайкальская епархия",
      seat="Severobaykalsk", country="RU",
      address=[u"ул. Мира, 10А", u"671701, Республика Бурятия, г. Северобайкальск"],
      site="https://sbk-eparhia.ru/",
      sources=["https://patriarchia.ru/org/494"]),

 dict(id="ru-severomorsk", parent="russia",
      name="Severomorsk Diocese",
      local=u"Североморская епархия",
      seat="Severomorsk", country="RU",
      address=[u"ул. Саши Ковалева, 3", u"184600, Мурманская область, г. Североморск"],
      sources=["https://patriarchia.ru/org/450"]),

 dict(id="ru-sergiyev-posad", parent="russia",
      name="Sergiyev Posad Diocese",
      local=u"Сергиево-Посадская епархия",
      seat="Sergiyev Posad", country="RU",
      address=[u"Свято-Троицкая Сергиева лавра", u"141300, Московская обл., г. Сергиев Посад"],
      site="https://eparhsp.ru:443/",
      sources=["https://patriarchia.ru/org/560"]),

 dict(id="ru-serdobsk", parent="russia",
      name="Serdobsk Diocese",
      local=u"Сердобская епархия",
      seat="Serdobsk", country="RU",
      address=[u"ул. Набережная, 58", u"442895, Пензенская область, г. Сердобск"],
      site="https://serdobsk-eparh.ru/",
      sources=["https://patriarchia.ru/org/393"]),

 dict(id="ru-serov", parent="russia",
      name="Serov Diocese",
      local=u"Серовская епархия",
      seat="Krasnoturyinsk", country="RU",
      address=[u"ул. Чапаева, 7", u"624441, Свердловская область, г. Краснотурьинск"],
      site="https://серов-епархия.рф/",
      sources=["https://patriarchia.ru/org/538"]),

 dict(id="ru-simbirsk", parent="russia",
      name="Simbirsk Diocese",
      local=u"Симбирская епархия",
      seat="Ulyanovsk", country="RU",
      address=[u"ул. Ульяновская, 2", u"432017, г. Ульяновск"],
      site="https://mitropolia-simbirsk.ru/",
      sources=["https://patriarchia.ru/org/52"]),

 dict(id="ru-singapore", parent="russia",
      name="Diocese of Singapore",
      local=u"Сингапурская епархия",
      seat="Singapore", country="SG",
      sources=["https://patriarchia.ru/org/546"]),

 dict(id="ru-skopin", parent="russia",
      name="Skopin Diocese",
      local=u"Скопинская епархия",
      seat="Skopin", country="RU",
      address=[u"ул. Октябрьская, 26", u"391800, Рязанская область, г. Скопин"],
      site="http://skopin-eparhia.ru/",
      sources=["https://patriarchia.ru/org/313"]),

 dict(id="ru-slavgorod", parent="russia",
      name="Slavgorod Diocese",
      local=u"Славгородская епархия",
      seat="Slavgorod", country="RU",
      address=[u"ул. Ленина, 191/1", u"658823, Алтайский край, г. Славгород"],
      site="https://slavgorodeparchya.ru/",
      sources=["https://patriarchia.ru/org/492"]),

 dict(id="ru-slutsk", parent="russia",
      name="Slutsk Diocese",
      local=u"Слуцкая епархия",
      seat="Slutsk", country="BY",
      site="https://sluck-eparchiya.by/",
      sources=["https://patriarchia.ru/org/477"]),

 dict(id="ru-smolensk", parent="russia",
      name="Smolensk Diocese",
      local=u"Смоленская епархия",
      seat="Smolensk", country="RU",
      address=[u"Соборный двор, 5", u"214000, г. Смоленск"],
      site="http://смоленскаямитрополия.рф/",
      sources=["https://patriarchia.ru/org/53"]),

 dict(id="ru-solikamsk", parent="russia",
      name="Solikamsk Diocese",
      local=u"Соликамская епархия",
      seat="Solikamsk", country="RU",
      address=[u"ул. Олега Кошевого, 4", u"618542, Пермский край, г. Соликамск"],
      site="https://solikamsk-eparhya.ru/",
      sources=["https://patriarchia.ru/org/467"]),

 dict(id="ru-soroca", parent="russia",
      name="Soroca Diocese",
      local=u"Сорокская епархия",
      seat="Soroca", country="MD",
      address=[u"Republica Moldova, mun. Soroca, MD-3006, str. Ștefan cel Mare, 32"],
      site="https://eparhiasoroca.md/",
      sources=["https://patriarchia.ru/org/581"]),

 dict(id="ru-sochi", parent="russia",
      name="Sochi Diocese",
      local=u"Сочинская епархия",
      seat="Sochi", country="RU",
      address=[u"ул. Москвина, 12", u"354000, Краснодарский край, г. Сочи"],
      site="https://sochi-eparhia.ru/",
      sources=["https://patriarchia.ru/org/540"]),

 dict(id="ru-mid-america-rocor", parent="rocor",
      name="Diocese of Mid-America (ROCOR)",
      local=u"Средне-Американская епархия (РПЦЗ)",
      seat="Des Plaines", country="US",
      address=[u"Diocese of Chicago & Detroit, ROCOR, P.O. Box 1367, Des Plaines, IL 60017"],
      site="https://chicagodiocese.org/",
      sources=["https://patriarchia.ru/org/600"]),

 dict(id="ru-stavropol", parent="russia",
      name="Stavropol Diocese",
      local=u"Ставропольская епархия",
      seat="Stavropol", country="RU",
      address=[u"ул. Дзержинского, 157", u"355017, г. Ставрополь"],
      site="https://stavropol-eparhia.ru/",
      sources=["https://patriarchia.ru/org/24"]),

 dict(id="ru-sourozh", parent="russia",
      name="Diocese of Sourozh",
      local=u"Сурожская епархия",
      seat="London", country="GB",
      address=[u"67 Ennismore Gardens, London SW7 1NH, UK"],
      site="https://www.sourozh.org/",
      sources=["https://patriarchia.ru/org/143"]),

 dict(id="ru-syzran", parent="russia",
      name="Syzran Diocese",
      local=u"Сызранская епархия",
      seat="Syzran", country="RU",
      address=[u"ул. Фрунзе, 8", u"446013, Самарская область, г. Сызрань"],
      sources=["https://patriarchia.ru/org/532"]),

 dict(id="ru-syktyvkar", parent="russia",
      name="Syktyvkar Diocese",
      local=u"Сыктывкарская епархия",
      seat="Syktyvkar", country="RU",
      address=[u"ул. Бабушкина, 20", u"167000, Республика Коми, г. Сыктывкар"],
      site="https://syktyvkar-eparchia.ru/",
      sources=["https://patriarchia.ru/org/55"]),

 dict(id="ru-thailand", parent="russia",
      name="Diocese of Thailand",
      local=u"Таиландская епархия",
      seat="Bangkok", country="TH",
      address=[u"26-28, Soi Wachiratham Sathit 36, Sukhumvit Soi 101/1, Bang Chak, Phra Кhanong, Bangkok, 10260, Kingdom of Thailand"],
      site="https://dioceseofthailand.org/",
      sources=["https://patriarchia.ru/org/548"]),

 dict(id="ru-taldykorgan-vicariate", parent="russia",
      name="Taldykorgan Vicariate",
      local=u"Талдыкорганское викариатство",
      seat="Taldykorgan", country="KZ",
      sources=["https://patriarchia.ru/org/630"]),

 dict(id="ru-tallinn", parent="russia",
      name="Tallinn Diocese",
      local=u"Таллинская епархия",
      seat="Tallinn", country="EE",
      address=[u"Pikk 64/1-4, 10133 Tallinn, Eesti"],
      site="https://et.orthodox.ee/",
      sources=["https://patriarchia.ru/org/288"]),

 dict(id="ru-tambov", parent="russia",
      name="Tambov Diocese",
      local=u"Тамбовская епархия",
      seat="Tambov", country="RU",
      address=[u"ул. Набережная, 80", u"392000, г. Тамбов"],
      site="https://eparhia-tmb.ru/",
      sources=["https://patriarchia.ru/org/56"]),

 dict(id="ru-tara", parent="russia",
      name="Tara Diocese",
      local=u"Тарская епархия",
      seat="Tara", country="RU",
      address=[u"ул. Дзержинского, 9", u"646530, Омская обл., г. Тара"],
      sources=["https://patriarchia.ru/org/372"]),

 dict(id="ru-tashkent", parent="russia",
      name="Tashkent Diocese",
      local=u"Ташкентская епархия",
      seat="Tashkent", country="UZ",
      address=[u"ул. Садыка Азимова, 3-й тупик, 22", u"100047, Узбекистан, г. Ташкент"],
      site="https://pravoslavie.uz/",
      sources=["https://patriarchia.ru/org/166"]),

 dict(id="ru-tver", parent="russia",
      name="Tver Diocese",
      local=u"Тверская епархия",
      seat="Tver", country="RU",
      address=[u"ул. Советская, д. 10", u"170100, г. Тверь"],
      site="https://tvereparhia.ru/",
      sources=["https://patriarchia.ru/org/60"]),

 dict(id="ru-tiraspol", parent="russia",
      name="Tiraspol Diocese",
      local=u"Тираспольская епархия",
      seat="Tiraspol", country="MD",
      address=[u"ул. Шевченко, 25", u"Республика Молдова, Приднестровье, МD-3300, г. Тирасполь"],
      site="http://www.diocese-tiras.org/",
      sources=["https://patriarchia.ru/org/66"]),

 dict(id="ru-tikhvin", parent="russia",
      name="Tikhvin Diocese",
      local=u"Тихвинская епархия",
      seat="Tikhvin", country="RU",
      address=[u"ул. Успенская, 16", u"187555, Ленинградская область, г. Тихвин"],
      site="http://www.tikhvin-eparhia.ru/",
      sources=["https://patriarchia.ru/org/418"]),

 dict(id="ru-tikhoretsk", parent="russia",
      name="Tikhoretsk Diocese",
      local=u"Тихорецкая епархия",
      seat="Tikhoretsk", country="RU",
      address=[u"ул. Ляпидевского, 2", u"352120, Краснодарский край, г. Тихорецк"],
      sources=["https://patriarchia.ru/org/427"]),

 dict(id="ru-tobolsk", parent="russia",
      name="Tobolsk Diocese",
      local=u"Тобольская епархия",
      seat="Tobolsk", country="RU",
      address=[u"ул. 2", u"626152, Тюменская область, г. Тобольск, Красная пл."],
      site="http://www.tobolsk-eparhia.ru/",
      sources=["https://patriarchia.ru/org/57"]),

 dict(id="ru-tolyatti", parent="russia",
      name="Tolyatti Diocese",
      local=u"Тольяттинская епархия",
      seat="Tolyatti", country="RU",
      address=[u"ул. Революционная, д. 19", u"445026, Самарская обл., г. Тольятти"],
      site="https://tltepar.ru/",
      sources=["https://patriarchia.ru/org/550"]),

 dict(id="ru-tomsk", parent="russia",
      name="Tomsk Diocese",
      local=u"Томская епархия",
      seat="Tomsk", country="RU",
      address=[u"пр-т Ленина, 119", u"634050, г. Томск"],
      site="https://tomskeparhia.ru/",
      sources=["https://patriarchia.ru/org/58"]),

 dict(id="ru-troitsk", parent="russia",
      name="Troitsk Diocese",
      local=u"Троицкая епархия",
      seat="Troitsk", country="RU",
      address=[u"ул. Красногвардейская, 81", u"457100, Челябинская область, г. Троицк"],
      site="https://xn----8sbokdi0amdhn9bg8k.xn--p1ai/",
      sources=["https://patriarchia.ru/org/389"]),

 dict(id="ru-tula", parent="russia",
      name="Tula Diocese",
      local=u"Тульская епархия",
      seat="Tula", country="RU",
      address=[u"ул. Жуковского, 61", u"300041, г. Тула"],
      site="https://tulaeparhia.ru/",
      sources=["https://patriarchia.ru/org/59"]),

 dict(id="ru-turaw", parent="russia",
      name="Turaw Diocese",
      local=u"Туровская епархия",
      seat="Mazyr", country="BY",
      address=[u"ул. Комсомольская, 16", u"247760, Республика Беларусь, Гомельская обл., г. Мозырь"],
      site="http://www.turov.by/",
      sources=["https://patriarchia.ru/org/138"]),

 dict(id="ru-uvarovo", parent="russia",
      name="Uvarovo Diocese",
      local=u"Уваровская епархия",
      seat="Uvarovo", country="RU",
      address=[u"пер. Первомайский, 17", u"393460, Тамбовская область, Уваровский район, г. Уварово"],
      site="https://uvar-eparhia.ru/",
      sources=["https://patriarchia.ru/org/413"]),

 dict(id="ru-ulan-ude", parent="russia",
      name="Ulan-Ude Diocese",
      local=u"Улан-Удэнская епархия",
      seat="Ulan-Ude", country="RU",
      address=[u"ул. Производственная, 6 (юридический адрес); 670000, г. Улан-Удэ, ул. Куйбышева, 37/1 (фактический адрес)", u"670031, Республика Бурятия, г. Улан-Удэ"],
      site="https://pravoslavnaya-buryatiya.ru/",
      sources=["https://patriarchia.ru/org/259"]),

 dict(id="ru-ungheni", parent="russia",
      name="Ungheni Diocese",
      local=u"Унгенская епархия",
      seat="Ungheni", country="MD",
      address=[u"улица Националэ, 8", u"Республика Молдова, муниципий Унгены"],
      site="https://episcopia-ungheni.md/ro/",
      sources=["https://patriarchia.ru/org/180"]),

 dict(id="ru-uralsk", parent="russia",
      name="Uralsk Diocese",
      local=u"Уральская епархия",
      seat="Uralsk", country="KZ",
      address=[u"ул. Абиша Кекилбаева, 69", u"Республика Казахстан, Западно-Казахстанская обл., г. Уральск"],
      site="https://uralsk-eparhiya.kz/",
      sources=["https://patriarchia.ru/org/152"]),

 dict(id="ru-urzhum", parent="russia",
      name="Urzhum Diocese",
      local=u"Уржумская епархия",
      seat="Urzhum", country="RU",
      address=[u"ул. Советская, 19", u"613530, Кировская область, г. Уржум"],
      site="http://urzhum-eparhiya.ru/",
      sources=["https://patriarchia.ru/org/403"]),

 dict(id="ru-uryupinsk", parent="russia",
      name="Uryupinsk Diocese",
      local=u"Урюпинская епархия",
      seat="Uryupinsk", country="RU",
      address=[u"ул. им. священномученика Николая Попова, 1", u"403115, Волгоградская обл., г. Урюпинск"],
      site="https://xn----7sbbtmejxqgdjgx6b2ixah.xn--p1ai/",
      sources=["https://patriarchia.ru/org/353"]),

 dict(id="ru-ust-kamenogorsk", parent="russia",
      name="Ust-Kamenogorsk Diocese",
      local=u"Усть-Каменогорская епархия",
      seat="Ust-Kamenogorsk", country="KZ",
      address=[u"ул. Лихарева, 16", u"070004, Республика Казахстан, Восточно-Казахстанская обл., г. Усть-Каменогорск"],
      site="https://vko-eparhia.kz/",
      sources=["https://patriarchia.ru/org/307"]),

 dict(id="ru-ufa", parent="russia",
      name="Ufa Diocese",
      local=u"Уфимская епархия",
      seat="Ufa", country="RU",
      address=[u"улица Коммунистическая 50/2", u"450077, Республика Башкортостан, город Уфа"],
      site="http://www.eparhia-ufa.ru/",
      sources=["https://patriarchia.ru/org/61"]),

 dict(id="ru-philippines-and-vietnam", parent="russia",
      name="Diocese of the Philippines and Vietnam",
      local=u"Филиппинско-Вьетнамская епархия",
      seat="Manila", country="PH",
      address=[u"35 Guam, Better Living Subd., Bgy. Don Bosco, Parñaque, Metro Manila, Philippines, 1711 (приход Иверской иконы Пресвятой Богородицы)"],
      site="https://phvieparchy.org/ru/",
      sources=["https://patriarchia.ru/org/549"]),

 dict(id="ru-khabarovsk", parent="russia",
      name="Khabarovsk Diocese",
      local=u"Хабаровская епархия",
      seat="Khabarovsk", country="RU",
      address=[u"ул. Ленинградская, 65", u"680021, г. Хабаровск"],
      site="http://pravkhabarovsk.ru/",
      sources=["https://patriarchia.ru/org/26"]),

 dict(id="ru-khanty-mansiysk", parent="russia",
      name="Khanty-Mansiysk Diocese",
      local=u"Ханты-Мансийская епархия",
      seat="Khanty-Mansiysk", country="RU",
      address=[u"ул. Чехова, 2", u"628011, Тюменская область, ХМАО-Югра, г. Ханты-Мансийск"],
      site="https://ugraeparhia.ru/",
      sources=["https://patriarchia.ru/org/291"]),

 dict(id="ru-cheboksary", parent="russia",
      name="Cheboksary Diocese",
      local=u"Чебоксарская епархия",
      seat="Cheboksary", country="RU",
      address=[u"ул. К. Иванова, 23", u"428018, г. Чебоксары"],
      site="http://www.cheb-eparhia.ru/",
      sources=["https://patriarchia.ru/org/62"]),

 dict(id="ru-chelyabinsk", parent="russia",
      name="Chelyabinsk Diocese",
      local=u"Челябинская епархия",
      seat="Chelyabinsk", country="RU",
      address=[u"ул. Кыштымская, 34", u"454087, г. Челябинск"],
      site="https://mitropolia74.ru:443/",
      sources=["https://patriarchia.ru/org/63"]),

 dict(id="ru-cherepovets", parent="russia",
      name="Cherepovets Diocese",
      local=u"Череповецкая епархия",
      seat="Cherepovets", country="RU",
      address=[u"территория Макаринская роща, 1", u"162601, Вологодская обл., г. Череповец"],
      sources=["https://patriarchia.ru/org/478"]),

 dict(id="ru-chernyakhovsk", parent="russia",
      name="Chernyakhovsk Diocese",
      local=u"Черняховская епархия",
      seat="Chernyakhovsk", country="RU",
      address=[u"ул. Пионерская, 20", u"238151, Калининградская обл., г. Черняховск"],
      site="https://cherneparh.ru/",
      sources=["https://patriarchia.ru/org/518"]),

 dict(id="ru-shymkent", parent="russia",
      name="Shymkent Diocese",
      local=u"Чимкентская епархия",
      seat="Shymkent", country="KZ",
      address=[u"ул. Нурымова, 6", u"160009, Казахстан, Енбекшинский р-н, г. Шымкент"],
      site="https://chim-eparhiya.cerkov.ru/",
      sources=["https://patriarchia.ru/org/153"]),

 dict(id="ru-chistopol", parent="russia",
      name="Chistopol Diocese",
      local=u"Чистопольская епархия",
      seat="Chistopol", country="RU",
      address=[u"ул. К. Либкнехта, 22Б", u"422980, Республика Татарстан, г. Чистополь"],
      site="https://chistopoleparhia.ru/",
      sources=["https://patriarchia.ru/org/368"]),

 dict(id="ru-chita", parent="russia",
      name="Chita Diocese",
      local=u"Читинская епархия",
      seat="Chita", country="RU",
      address=[u"ул. 9-го января, 50, корп. 2", u"672039, Забайкальский край, г. Чита"],
      sources=["https://patriarchia.ru/org/64"]),

 dict(id="ru-shadrinsk", parent="russia",
      name="Shadrinsk Diocese",
      local=u"Шадринская епархия",
      seat="Shadrinsk", country="RU",
      address=[u"ул. Пионерская, 38А", u"641870, Курганская область, г. Шадринск"],
      site="https://shadreparh.cerkov.ru/",
      sources=["https://patriarchia.ru/org/496"]),

 dict(id="ru-shakhty", parent="russia",
      name="Shakhty Diocese",
      local=u"Шахтинская епархия",
      seat="Shakhty", country="RU",
      address=[u"пл. Соборная, 1 (Советская, 74Б)", u"346500, Ростовская область, г. Шахты"],
      site="https://shahteparh.ru/",
      sources=["https://patriarchia.ru/org/301"]),

 dict(id="ru-shuya", parent="russia",
      name="Shuya Diocese",
      local=u"Шуйская епархия",
      seat="Shuya", country="RU",
      address=[u"ул. Театральная, 23, Управление Шуйской епархии", u"155900, Ивановская область, г. Шуя"],
      site="https://shuya-eparhia.ru:443/",
      sources=["https://patriarchia.ru/org/379"]),

 dict(id="ru-shchigry", parent="russia",
      name="Shchigry Diocese",
      local=u"Щигровская епархия",
      seat="Shchigry", country="RU",
      address=[u"ул. Ленина, д. 11", u"306530, Курская обл., г. Щигры"],
      site="http://щигровская-епархия.рф/",
      sources=["https://patriarchia.ru/org/387"]),

 dict(id="ru-elista", parent="russia",
      name="Elista Diocese",
      local=u"Элистинская епархия",
      seat="Elista", country="RU",
      address=[u"ул. Сергия Радонежского, 97", u"358001, Республика Калмыкия, г. Элиста"],
      site="https://blagovest-elista.ru/",
      sources=["https://patriarchia.ru/org/65"]),

 dict(id="ru-yugorsk", parent="russia",
      name="Yugorsk Diocese",
      local=u"Югорская епархия",
      seat="Yugorsk", country="RU",
      address=[u"ул. 40 лет Победы, д. 19", u"628260, г. Югорск"],
      site="http://yugorsk-eparhia.ru/",
      sources=["https://patriarchia.ru/org/485"]),

 dict(id="ru-south-america-rocor", parent="rocor",
      name="Diocese of South America (ROCOR)",
      local=u"Южно-Американская епархия (РПЦЗ)",
      seat="Buenos Aires", country="AR",
      site="https://iglesiarusa.info/",
      sources=["https://patriarchia.ru/org/594"]),

 dict(id="ru-south-africa", parent="russia",
      name="Diocese of South Africa",
      local=u"Южно-Африканская епархия",
      seat="Johannesburg", country="ZA",
      site="https://exarchate-africa.ru/",
      sources=["https://patriarchia.ru/org/567"]),

 dict(id="ru-yuzhno-sakhalinsk", parent="russia",
      name="Yuzhno-Sakhalinsk Diocese",
      local=u"Южно-Сахалинская епархия",
      seat="Yuzhno-Sakhalinsk", country="RU",
      address=[u"улица Ленина, 158", u"693020, Сахалинская область, город Южно-Сахалинск"],
      site="https://xn--80aaagntdxteaiocodn4cj5q.xn--p1ai/",
      sources=["https://patriarchia.ru/org/48"]),

 dict(id="ru-yakutsk", parent="russia",
      name="Yakutsk Diocese",
      local=u"Якутская епархия",
      seat="Yakutsk", country="RU",
      address=[u"ул. Кирова, 8", u"677018, Республика Саха (Якутия), г. Якутск"],
      site="https://pravyakutia.ru/",
      sources=["https://patriarchia.ru/org/70"]),

 dict(id="ru-yaransk", parent="russia",
      name="Yaransk Diocese",
      local=u"Яранская епархия",
      seat="Yaransk", country="RU",
      address=[u"ул. Карла Маркса, 14", u"612260, Кировская область, г. Яранск"],
      site="https://www.xn----7sbabytjxwdif3d6ggh.xn--p1ai/",
      sources=["https://patriarchia.ru/org/404"]),

 dict(id="ru-yaroslavl", parent="russia",
      name="Yaroslavl Diocese",
      local=u"Ярославская епархия",
      seat="Yaroslavl", country="RU",
      address=[u"Богоявленская площадь, 14", u"150000, г. Ярославль"],
      site="http://yareparhia.ru/",
      sources=["https://patriarchia.ru/org/71"]),

]
