# -*- coding: utf-8 -*-
"""The Churches' own commemorations, in Arabic.

See docs/LOCAL_NAMES.md.
"""
TEXT = {
    "St Isaac the Syrian": u"البار إسحق السرياني",
    "Martyr Elian of Homs": u"الشهيد إليان الحمصي",
    "St Joseph of Damascus & the New Martyrs of Damascus (1860)": u"الشهيد في الكهنة يوسف الدمشقي وشهداء دمشق الجدد (1860)",
    "Hieromartyrs Nicholas and Habib Khasha of Damascus": u"الشهيدان في الكهنة نيقولاوس وحبيب خاشة الدمشقيان",
    "St Gabriel of Lesnovo": u"البار غابرييل اللسنوفي",
    "St Joachim I, Patriarch of Tarnovo": u"القديس يواكيم الأول بطريرك ترنوفو",
    "St Euthymius, Patriarch of Tarnovo": u"القديس أفثيميوس بطريرك ترنوفو",
    "St Peter, King of Bulgaria": u"القديس بطرس قيصر بلغاريا",
    "St Romanus of Tarnovo": u"البار رومانوس الترنوفي",
    "St Sophronius, Bishop of Vratsa": u"القديس سوفرونيوس أسقف فراتسا",
    "St Boris-Michael, Equal-to-the-Apostles, Baptizer of Bulgaria": u"القديس بوريس-ميخائيل المعادل للرسل، معمّد بلغاريا",
    "Great Martyr Nicholas of Sofia": u"الشهيد العظيم نيقولاوس الصوفي",
    "St Paisius of Hilendar": u"البار باييسيوس الهيلنداري",
    "The Seven Holy Apostles (Sedmochislenitsi)": u"الرسل السبعة القديسون (سدموتشيسلينيتسي)",
    "St Joachim of Osogovo": u"البار يواكيم الأوسوغوفي",
    "Repose of St John of Rila": u"رقاد البار يوحنا الريلي",
    "New Martyr Simeon of Samokov": u"الشهيد الجديد سمعان الساموكوفي",
    "St Cosmas of Zographou": u"البار كوزماس الزوغرافي",
    "The 26 Martyrs of Zographou": u"شهداء زوغرافو الستة والعشرون",
    "St Demetrius of Basarbovo": u"البار ديمتريوس الباسارابوفي",
    "Venerable Pimen of Zographou": u"البار بيمن الزوغرافي",
    "Righteous Michael the Soldier of Bulgaria": u"الصدّيق ميخائيل الجندي البلغاري",
    "St Theodosius of Tarnovo": u"البار ثيودوسيوس الترنوفي",
    "St Nektarios the Bulgarian of Bitola": u"البار الشهيد نكتاريوس البيتولي",
    "St Nahum of Ohrid": u"البار ناحوم الأوخريدي",
    "Ss Salome of Ujarma and Perozhavra of Sivnia": u"الصدّيقتان سالومي الأوجارمية وبيروجافرا السيفنية",
    "St Eprem the Lesser, the Philosopher": u"البار إفرام الصغير الفيلسوف",
    "St David IV the Builder, King of Georgia": u"القديس داود الرابع الباني ملك جورجيا",
    "St Ioane the Catholicos": u"القديس يوحنا جاثليق جورجيا",
    "Holy King Demetre the Devoted": u"القديس ديميتري المضحّي بنفسه ملك جورجيا",
    "St Ambrosi the Confessor, Catholicos-Patriarch of All Georgia": u"القديس أمبروسيوس المعترف، جاثليق وبطريرك عموم جورجيا",
    "Venerable David of the Gareji Monastery": u"البار داود الغارجي",
    "St Tamar, Queen of Georgia": u"القديسة تامار ملكة جورجيا",
    "Venerable Ioane of Zedazeni and his Twelve Disciples": u"البار يوحنا الزيدازني وتلاميذه الاثنا عشر",
    "Venerable Ekvtime of Mount Athos, the Translator": u"البار إفتيمي الآثوسي المترجم",
    "St George the Hagiorite, and Hieromartyr Kirion II, Catholicos-Patriarch": u"البار جيورجي الآثوسي والشهيد في الكهنة كيريون الثاني جاثليق وبطريرك",
    "St Ilia the Righteous": u"الصدّيق إيليا تشافتشافادزه",
    "Holy Martyr Evstati of Mtskheta": u"الشهيد إفستاثيوس المتسختي",
    "St Tsotne Dadiani the Confessor": u"القديس تسوتنه داديانى المعترف",
    "St Razhden, Protomartyr of Georgia, and the Nine Kherkheulidze Brothers": u"أول شهداء جورجيا راجدن والإخوة التسعة خرخيوليدزه",
    "Holy Confessors Ioane and Giorgi-Ioane of Betania": u"المعترفان يوحنا وجيورجي-يوحنا البيتانيان",
    "Holy Great-martyr Queen Ketevan": u"الشهيدة العظيمة الملكة كيتيفان",
    "Holy Martyrs Bidzina, Shalva and Elizbar": u"الشهداء بيدزينا وشالفا وإليزبار",
    "Venerable Grigol of Khandzta": u"البار غريغول الخانزتي",
    "St Gabriel of Samtavro, Confessor and Fool for Christ": u"البار غابرييل السامتافري، المعترف والمتباله بالمسيح",
    "The 100,000 Martyrs of Tbilisi": u"شهداء تبليسي المئة ألف",
    "Holy King Vakhtang Gorgasali": u"القديس الملك فاختانغ غورغاسالي",
    "St Ise of Tsilkani": u"القديس إيسي التسيلكاني",
    "Synaxis of All Saints of Georgia": u"تذكار جميع قديسي جورجيا",
    "Venerable Giorgi the Scribe and his brother Saba of Khakhuli": u"البارّان جيورجي الكاتب وأخوه سابا الخاخولي",
    "St Nikephoros the Leper": u"البار نيقيفوروس الأبرص",
    "St Arsenios of Paros": u"البار أرسانيوس الباروسي",
    "St Ephraim of Katounakia": u"البار إفرام الكاتوناكي",
    "St Nikolaos Planas of Athens": u"الصدّيق نيقولاوس بلاناس الأثيني",
    "St Savvas the New of Kalymnos": u"البار سابا الجديد الكاليمنوسي",
    "St Amphilochios of Patmos": u"البار أمفيلوخيوس البطمي",
    "St Joseph the Hesychast": u"البار يوسف الهدوئي",
    "St Kosmas Aitolos, Equal-to-the-Apostles": u"القديس كوزماس الإيتولي المعادل للرسل",
    "St Arsenios of Cappadocia": u"البار أرسانيوس الكبادوكي",
    "St Iakovos of Evia": u"البار يعقوب الإيفياني",
    "St Antipa of Calapodești": u"البار أنتيبا الكالابوديشتي",
    "St Calinic of Cernica": u"القديس كالينيكوس التشرنيكي",
    "St Pahomie of Gledin, Bishop of Roman": u"القديس باخوميوس الغليديني أسقف رومان",
    "Ss Ilie Iorest, Sava Brancovici and Simion Ștefan, Metropolitans of Transylvania": u"القديسون إيليا يوريست وسافا برانكوفيتش وسيميون شتيفان مطارنة ترانسلفانيا",
    "St Irodion of Lainici": u"البار إيروديون اللاينيتشي",
    "St John the Wallachian, Martyr": u"الشهيد يوحنا الفلاشي",
    "St Iacob Putneanul, Metropolitan of Moldavia": u"القديس يعقوب البوتني مطران مولدافيا",
    "St Grigorie Dascălul, Metropolitan of Wallachia": u"القديس غريغوريوس داسكالول مطران والاشيا",
    "St Ghelasie of Râmeț": u"القديس غيلاسيوس الريميتسي",
    "St Leontie of Rădăuți": u"القديس لاونديوس الرادوتسي",
    "St Stephen the Great": u"القديس ستيفان الكبير أمير مولدافيا",
    "St Ioanichie the New of Muscel": u"البار يوانيكيوس الجديد الموشتشيلي",
    "St Ioan Iacob of Neamț": u"البار يوحنا يعقوب النيامتسي",
    "St Teodora of Sihla": u"البارة ثيودورا السيخلية",
    "The Brâncoveanu Martyrs: Prince Constantin and his four sons": u"شهداء برنكوفيانو: الأمير قسطنطين وأبناؤه الأربعة",
    "St Iosif the New of Partoș, Metropolitan of Banat": u"القديس يوسف الجديد البارتوشي مطران بانات",
    "St Neagoe Basarab, Voivode of Wallachia": u"القديس نياغوي باساراب أمير والاشيا",
    "St Antim Ivireanul, Hieromartyr, Metropolitan of Wallachia": u"الشهيد في الكهنة أنثيموس الإيبيري مطران والاشيا",
    "St Parascheva of Iași": u"البارة باراسكيفي الياشية",
    "St Dimitrie the New of Bucharest": u"البار ديمتريوس الجديد البوخارستي",
    "St Iachint, Metropolitan of Wallachia": u"القديس ياكينثوس مطران والاشيا",
    "St Andrei Șaguna, Metropolitan of Transylvania": u"القديس أندريه شاغونا مطران ترانسلفانيا",
    "St Gheorghe of Cernica": u"البار جيورجي التشرنيكي",
    "St Dosoftei, Metropolitan of Moldavia": u"القديس دوسيثيوس مطران مولدافيا",
    "St Daniil the Hesychast": u"البار دانيال الهدوئي",
    "St Nicodim of Tismana": u"البار نيقوديموس التيسماني",
    "St Seraphim of Sarov": u"البار سيرافيم الساروفي",
    "St Theophan the Recluse": u"القديس ثيوفان الحبيس",
    "St Xenia of St Petersburg": u"الطوباوية كسينيا البطرسبورجية",
    "St Ignatius (Brianchaninov), Bishop of the Caucasus": u"القديس إغناطيوس (بريانتشانينوف) أسقف القوقاز",
    "St Vladimir, Equal-to-the-Apostles": u"القديس فلاديمير المعادل للرسل",
    "St Sergius of Radonezh": u"البار سرجيوس الرادونيجي",
    "St Ambrose of Optina": u"البار أمبروسيوس الأوبتيني",
    "Synaxis of the Optina Elders": u"تذكار شيوخ أوبتينا الأبرار",
    "St Sava, First Archbishop of Serbia": u"القديس سافا أول رئيس أساقفة صربيا",
    "St Simeon the Myrrh-gusher": u"البار سمعان مفيض الطيب",
    "St Basil of Ostrog": u"القديس باسيليوس الأوستروغي",
    "St Justin Popovich of Ćelije": u"البار يوستينوس بوبوفيتش التشيليي",
    "St Petar of Koriša": u"البار بطرس الكوريشي",
    "Holy Great-martyr Tsar Lazar (Vidovdan)": u"الشهيد العظيم القيصر لازار (فيدوفدان)",
    "St Jefrem, Patriarch of Serbia": u"القديس إفرام بطريرك صربيا",
    "St Angelina of Serbia": u"البارة أنجلينا الصربية",
    "Synaxis of the Holy Hierarchs of Serbia": u"تذكار رؤساء كهنة صربيا القديسين",
    "The New Martyrs of Jasenovac": u"شهداء ياسينوفاتس الجدد",
    "St Stefan Vladislav, King of Serbia": u"القديس ستيفان فلاديسلاف ملك صربيا",
    "St Petar of Cetinje, Wonderworker": u"القديس بطرس التسيتينيي العجائبي",
    "St Prohor of Pčinja": u"البار بروخور البتشيني",
    "St Milutin the King and St Jelena the Queen of Serbia": u"القديسان الملك ميلوتين والملكة يلينا الصربيان",
    "St Stefan Dečanski, King of Serbia": u"القديس ستيفان ديتشانسكي ملك صربيا",
    "St Sebastian of Jackson": u"البار سيباستيان الجاكسوني",
    "St Joanikije of Devič": u"البار يوانيكيوس الديفيتشي",
    "St Danilo II, Archbishop of Serbia": u"القديس دانيال الثاني رئيس أساقفة صربيا",
    "St Amphilochius of Pochaiv": u"البار أمفيلوخيوس البوتشايفي",
    "St Feodosii of the Kyiv Caves": u"البار ثيودوسيوس الكهفي الكييفي",
    "St Antonii of the Kyiv Caves": u"البار أنطونيوس الكهفي الكييفي",
    "St Olha, Equal-to-the-Apostles": u"القديسة أولغا المعادلة للرسل",
    "St Volodymyr, Equal-to-the-Apostles": u"القديس فلاديمير المعادل للرسل",
    "St Petro Mohyla, Metropolitan of Kyiv": u"القديس بطرس موغيلا مطران كييف",
    "Synaxis of All Saints of Antioch": u"تذكار جميع قديسي أنطاكية",
    "Synaxis of All Bulgarian Saints": u"تذكار جميع قديسي بلغاريا",
    "Synaxis of All Saints of Mount Athos": u"تذكار جميع آباء الجبل المقدس الأبرار",
    "Synaxis of All Saints of North America": u"تذكار جميع قديسي أميركا الشمالية",
    "Synaxis of All Venerable Fathers of the Kyiv Caves": u"تذكار جميع آباء كهوف كييف الأبرار",
    "Synaxis of All Romanian Saints": u"تذكار جميع قديسي رومانيا",
    "Synaxis of All Saints of Russia": u"تذكار جميع قديسي روسيا",
    "Synaxis of All Saints of Ukraine": u"تذكار جميع قديسي أوكرانيا",
    "St Raphael, Bishop of Brooklyn": u"القديس رافائيل أسقف بروكلين",
}
