# -*- coding: utf-8 -*-
"""The Churches' own commemorations, in Syriac.

See docs/LOCAL_NAMES.md.
"""
TEXT = {
    "St Isaac the Syrian": u"ܡܝܩܪܐ ܐܝܣܚܩ ܣܘܪܝܝܐ",
    "Martyr Elian of Homs": u"ܣܗܕܐ ܐܠܝܢ ܕܚܡܨ",
    "St Joseph of Damascus & the New Martyrs of Damascus (1860)": u"ܟܗܢܐ ܣܗܕܐ ܝܘܣܦ ܕܕܪܡܣܘܩ ܘܣܗ̈ܕܐ ܚܕ̈ܬܐ ܕܕܪܡܣܘܩ (1860)",
    "Hieromartyrs Nicholas and Habib Khasha of Damascus": u"ܟܗ̈ܢܐ ܣܗ̈ܕܐ ܢܝܩܘܠܐܘܣ ܘܚܒܝܒ ܟܐܫܐ ܕܕܪܡܣܘܩ",
    "St Gabriel of Lesnovo": u"ܡܝܩܪܐ ܓܒܪܐܝܠ ܕܠܣܢܘܒܘ",
    "St Joachim I, Patriarch of Tarnovo": u"ܩܕܝܫܐ ܝܘܐܟܝܡ ܩܕܡܝܐ ܦܛܪܝܪܟܐ ܕܛܪܢܘܒܘ",
    "St Euthymius, Patriarch of Tarnovo": u"ܩܕܝܫܐ ܐܘܬܝܡܝܘܣ ܦܛܪܝܪܟܐ ܕܛܪܢܘܒܘ",
    "St Peter, King of Bulgaria": u"ܩܕܝܫܐ ܦܛܪܘܣ ܡܠܟܐ ܕܒܘܠܓܪܝܐ",
    "St Romanus of Tarnovo": u"ܡܝܩܪܐ ܪܘܡܢܘܣ ܕܛܪܢܘܒܘ",
    "St Sophronius, Bishop of Vratsa": u"ܩܕܝܫܐ ܣܘܦܪܘܢܝܘܣ ܐܦܣܩܘܦܐ ܕܒܪܨܐ",
    "St Boris-Michael, Equal-to-the-Apostles, Baptizer of Bulgaria": u"ܩܕܝܫܐ ܒܘܪܝܣ-ܡܝܟܐܝܠ ܫܘܐ ܠܫܠܝ̈ܚܐ، ܡܥܡܕܢܐ ܕܒܘܠܓܪܝܐ",
    "Great Martyr Nicholas of Sofia": u"ܣܗܕܐ ܪܒܐ ܢܝܩܘܠܐܘܣ ܕܣܘܦܝܐ",
    "St Paisius of Hilendar": u"ܡܝܩܪܐ ܦܐܝܣܝܘܣ ܕܚܝܠܢܕܪ",
    "The Seven Holy Apostles (Sedmochislenitsi)": u"ܫܠܝ̈ܚܐ ܩܕܝ̈ܫܐ ܫܒܥܐ (ܣܕܡܘܟܝܣܠܢܝܬܣܝ)",
    "St Joachim of Osogovo": u"ܡܝܩܪܐ ܝܘܐܟܝܡ ܕܐܘܣܘܓܘܒܘ",
    "Repose of St John of Rila": u"ܫܟܒܬܐ ܕܡܝܩܪܐ ܝܘܚܢܢ ܕܪܝܠܐ",
    "New Martyr Simeon of Samokov": u"ܣܗܕܐ ܚܕܬܐ ܫܡܥܘܢ ܕܣܡܘܩܘܒ",
    "St Cosmas of Zographou": u"ܡܝܩܪܐ ܩܘܣܡܐ ܕܙܘܓܪܦܘ",
    "The 26 Martyrs of Zographou": u"ܥܣܪܝܢ ܘܫܬܐ ܣܗ̈ܕܐ ܕܙܘܓܪܦܘ",
    "St Demetrius of Basarbovo": u"ܡܝܩܪܐ ܕܡܛܪܝܘܣ ܕܒܣܪܒܘܒܘ",
    "Venerable Pimen of Zographou": u"ܡܝܩܪܐ ܦܝܡܢ ܕܙܘܓܪܦܘ",
    "Righteous Michael the Soldier of Bulgaria": u"ܙܕܝܩܐ ܡܝܟܐܝܠ ܦܠܚܐ ܒܘܠܓܪܝܐ",
    "St Theodosius of Tarnovo": u"ܡܝܩܪܐ ܬܐܘܕܘܣܝܘܣ ܕܛܪܢܘܒܘ",
    "St Nektarios the Bulgarian of Bitola": u"ܡܝܩܪܐ ܣܗܕܐ ܢܩܛܪܝܘܣ ܕܒܝܛܘܠܐ",
    "St Nahum of Ohrid": u"ܡܝܩܪܐ ܢܚܘܡ ܕܐܘܚܪܝܕ",
    "Ss Salome of Ujarma and Perozhavra of Sivnia": u"ܙܕܝ̈ܩܬܐ ܫܠܘܡܝܬ ܕܐܘܓܪܡܐ ܘܦܪܘܙܐܒܪܐ ܕܣܝܒܢܝܐ",
    "St Eprem the Lesser, the Philosopher": u"ܡܝܩܪܐ ܐܦܪܝܡ ܙܥܘܪܐ ܦܝܠܘܣܘܦܐ",
    "St David IV the Builder, King of Georgia": u"ܩܕܝܫܐ ܕܘܝܕ ܪܒܝܥܝܐ ܒܢܝܐ ܡܠܟܐ ܕܓܘܪܓܝܐ",
    "St Ioane the Catholicos": u"ܩܕܝܫܐ ܝܘܚܢܢ ܩܬܘܠܝܩܐ ܕܓܘܪܓܝܐ",
    "Holy King Demetre the Devoted": u"ܩܕܝܫܐ ܕܡܛܪܐ ܝܗܘܒ ܢܦܫܗ ܡܠܟܐ ܕܓܘܪܓܝܐ",
    "St Ambrosi the Confessor, Catholicos-Patriarch of All Georgia": u"ܩܕܝܫܐ ܐܡܒܪܘܣܝܘܣ ܡܘܕܝܢܐ ܩܬܘܠܝܩܐ ܦܛܪܝܪܟܐ ܕܟܠܗ ܓܘܪܓܝܐ",
    "Venerable David of the Gareji Monastery": u"ܡܝܩܪܐ ܕܘܝܕ ܕܓܪܓܝ",
    "St Tamar, Queen of Georgia": u"ܩܕܝܫܬܐ ܬܡܪ ܡܠܟܬܐ ܕܓܘܪܓܝܐ",
    "Venerable Ioane of Zedazeni and his Twelve Disciples": u"ܡܝܩܪܐ ܝܘܚܢܢ ܕܙܕܙܢܝ ܘܬܪܥܣܪ ܬܠܡܝ̈ܕܘܗܝ",
    "Venerable Ekvtime of Mount Athos, the Translator": u"ܡܝܩܪܐ ܐܟܘܬܝܡ ܛܘܪܝܐ ܡܬܪܓܡܢܐ",
    "St George the Hagiorite, and Hieromartyr Kirion II, Catholicos-Patriarch": u"ܡܝܩܪܐ ܓܐܘܪܓܝܘܣ ܛܘܪܝܐ ܘܟܗܢܐ ܣܗܕܐ ܩܝܪܝܘܢ ܬܪܝܢܐ ܩܬܘܠܝܩܐ ܦܛܪܝܪܟܐ",
    "St Ilia the Righteous": u"ܙܕܝܩܐ ܐܝܠܝܐ ܟܐܒܟܐܒܐܕܙܐ",
    "Holy Martyr Evstati of Mtskheta": u"ܣܗܕܐ ܐܘܣܛܬܐܘܣ ܕܡܨܟܝܬܐ",
    "St Tsotne Dadiani the Confessor": u"ܩܕܝܫܐ ܨܘܛܢܐ ܕܕܝܢܝ ܡܘܕܝܢܐ",
    "St Razhden, Protomartyr of Georgia, and the Nine Kherkheulidze Brothers": u"ܣܗܕܐ ܩܕܡܝܐ ܕܓܘܪܓܝܐ ܪܙܕܢ ܘܬܫܥܐ ܐܚ̈ܐ ܟܪܟܐܘܠܝܕܙܐ",
    "Holy Confessors Ioane and Giorgi-Ioane of Betania": u"ܡܘܕܝ̈ܢܐ ܩܕܝ̈ܫܐ ܝܘܚܢܢ ܘܓܐܘܪܓܝܘܣ-ܝܘܚܢܢ ܕܒܝܬܢܝܐ",
    "Holy Great-martyr Queen Ketevan": u"ܣܗܕܬܐ ܪܒܬܐ ܩܛܒܢ ܡܠܟܬܐ",
    "Holy Martyrs Bidzina, Shalva and Elizbar": u"ܣܗ̈ܕܐ ܩܕܝ̈ܫܐ ܒܕܙܝܢܐ ܘܫܠܒܐ ܘܐܠܝܙܒܪ",
    "Venerable Grigol of Khandzta": u"ܡܝܩܪܐ ܓܪܝܓܘܠ ܕܟܢܕܙܬܐ",
    "St Gabriel of Samtavro, Confessor and Fool for Christ": u"ܡܝܩܪܐ ܓܒܪܐܝܠ ܕܣܡܬܒܪܘ، ܡܘܕܝܢܐ ܘܫܛܝܐ ܡܛܠ ܡܫܝܚܐ",
    "The 100,000 Martyrs of Tbilisi": u"ܡܐܐ ܐܠܦ̈ܝܢ ܣܗ̈ܕܐ ܕܬܒܝܠܝܣܝ",
    "Holy King Vakhtang Gorgasali": u"ܩܕܝܫܐ ܘܟܬܢܓ ܓܘܪܓܣܠܝ ܡܠܟܐ ܕܓܘܪܓܝܐ",
    "St Ise of Tsilkani": u"ܩܕܝܫܐ ܐܝܣܐ ܕܨܝܠܩܢܝ",
    "Synaxis of All Saints of Georgia": u"ܟܢܘܫܝܐ ܕܟܠܗܘܢ ܩܕܝ̈ܫܐ ܕܓܘܪܓܝܐ",
    "Venerable Giorgi the Scribe and his brother Saba of Khakhuli": u"ܡܝܩܪ̈ܐ ܓܐܘܪܓܝܘܣ ܣܦܪܐ ܘܐܚܘܗܝ ܣܒܐ ܕܟܟܘܠܝ",
    "St Nikephoros the Leper": u"ܡܝܩܪܐ ܢܝܩܝܦܘܪܘܣ ܓܪܒܢܐ",
    "St Arsenios of Paros": u"ܡܝܩܪܐ ܐܪܣܢܝܘܣ ܕܦܪܘܣ",
    "St Ephraim of Katounakia": u"ܡܝܩܪܐ ܐܦܪܝܡ ܕܩܛܘܢܩܝܐ",
    "St Nikolaos Planas of Athens": u"ܙܕܝܩܐ ܢܝܩܘܠܐܘܣ ܦܠܢܣ ܕܐܬܝܢܐ",
    "St Savvas the New of Kalymnos": u"ܡܝܩܪܐ ܣܒܐ ܚܕܬܐ ܕܩܠܝܡܢܘܣ",
    "St Amphilochios of Patmos": u"ܡܝܩܪܐ ܐܡܦܝܠܘܟܝܘܣ ܕܦܛܡܘܣ",
    "St Joseph the Hesychast": u"ܡܝܩܪܐ ܝܘܣܦ ܫܠܝܐ",
    "St Kosmas Aitolos, Equal-to-the-Apostles": u"ܩܕܝܫܐ ܩܘܣܡܐ ܐܝܛܘܠܝܐ، ܫܘܐ ܠܫܠܝ̈ܚܐ",
    "St Arsenios of Cappadocia": u"ܡܝܩܪܐ ܐܪܣܢܝܘܣ ܩܦܕܘܩܝܐ",
    "St Iakovos of Evia": u"ܡܝܩܪܐ ܝܥܩܘܒ ܕܐܘܒܝܐ",
    "St Antipa of Calapodești": u"ܡܝܩܪܐ ܐܢܛܝܦܐ ܕܩܠܦܘܕܫܬܝ",
    "St Calinic of Cernica": u"ܩܕܝܫܐ ܩܠܝܢܝܩܘܣ ܕܟܪܢܝܩܐ",
    "St Pahomie of Gledin, Bishop of Roman": u"ܩܕܝܫܐ ܦܟܘܡܝܘܣ ܕܓܠܕܝܢ ܐܦܣܩܘܦܐ ܕܪܘܡܢ",
    "Ss Ilie Iorest, Sava Brancovici and Simion Ștefan, Metropolitans of Transylvania": u"ܩܕܝ̈ܫܐ ܐܠܝܐ ܝܘܪܣܛ ܘܣܒܐ ܒܪܢܩܘܒܝܟ ܘܫܡܥܘܢ ܐܣܛܦܢ ܡܝ̈ܛܪܘܦܘܠܝܛܐ ܕܛܪܢܣܠܒܢܝܐ",
    "St Irodion of Lainici": u"ܡܝܩܪܐ ܐܝܪܘܕܝܘܢ ܕܠܝܢܝܟܝ",
    "St John the Wallachian, Martyr": u"ܣܗܕܐ ܝܘܚܢܢ ܘܠܟܝܐ",
    "St Iacob Putneanul, Metropolitan of Moldavia": u"ܩܕܝܫܐ ܝܥܩܘܒ ܦܘܛܢܢܘܠ ܡܝܛܪܘܦܘܠܝܛܐ ܕܡܘܠܕܒܝܐ",
    "St Grigorie Dascălul, Metropolitan of Wallachia": u"ܩܕܝܫܐ ܓܪܝܓܘܪܝܘܣ ܕܣܟܠܘܠ ܡܝܛܪܘܦܘܠܝܛܐ ܕܘܠܟܝܐ",
    "St Ghelasie of Râmeț": u"ܩܕܝܫܐ ܓܠܣܝܘܣ ܕܪܡܛ",
    "St Leontie of Rădăuți": u"ܩܕܝܫܐ ܠܐܘܢܛܝܘܣ ܕܪܕܘܛܝ",
    "St Stephen the Great": u"ܩܕܝܫܐ ܐܣܛܦܢܘܣ ܪܒܐ",
    "St Ioanichie the New of Muscel": u"ܡܝܩܪܐ ܝܘܐܢܝܩܝܘܣ ܚܕܬܐ ܕܡܘܣܟܠ",
    "St Ioan Iacob of Neamț": u"ܡܝܩܪܐ ܝܘܚܢܢ ܝܥܩܘܒ ܕܢܝܡܨ",
    "St Teodora of Sihla": u"ܡܝܩܪܬܐ ܬܐܘܕܘܪܐ ܕܣܝܟܠܐ",
    "The Brâncoveanu Martyrs: Prince Constantin and his four sons": u"ܣܗ̈ܕܐ ܒܪܢܩܘܒܢܘ: ܪܝܫܢܐ ܩܘܣܛܢܛܝܢܘܣ ܘܐܪܒܥܐ ܒܢܘ̈ܗܝ",
    "St Iosif the New of Partoș, Metropolitan of Banat": u"ܩܕܝܫܐ ܝܘܣܦ ܚܕܬܐ ܕܦܪܛܘܫ ܡܝܛܪܘܦܘܠܝܛܐ ܕܒܢܛ",
    "St Neagoe Basarab, Voivode of Wallachia": u"ܩܕܝܫܐ ܢܐܓܘܐ ܒܣܪܒ ܪܝܫܢܐ ܕܘܠܟܝܐ",
    "St Antim Ivireanul, Hieromartyr, Metropolitan of Wallachia": u"ܟܗܢܐ ܣܗܕܐ ܐܢܬܝܡ ܐܝܒܝܪܝܐ ܡܝܛܪܘܦܘܠܝܛܐ ܕܘܠܟܝܐ",
    "St Parascheva of Iași": u"ܡܝܩܪܬܐ ܦܪܣܩܐܘܝ ܕܝܫܝ",
    "St Dimitrie the New of Bucharest": u"ܩܕܝܫܐ ܕܡܛܪܝܐ ܚܕܬܐ ܕܒܘܟܪܣܛ",
    "St Iachint, Metropolitan of Wallachia": u"ܩܕܝܫܐ ܝܟܝܢܬܘܣ ܡܝܛܪܘܦܘܠܝܛܐ ܕܘܠܟܝܐ",
    "St Andrei Șaguna, Metropolitan of Transylvania": u"ܩܕܝܫܐ ܐܢܕܪܐܝ ܫܓܘܢܐ ܡܝܛܪܘܦܘܠܝܛܐ ܕܛܪܢܣܠܒܢܝܐ",
    "St Gheorghe of Cernica": u"ܡܝܩܪܐ ܓܐܘܪܓܝܘܣ ܕܟܪܢܝܩܐ",
    "St Dosoftei, Metropolitan of Moldavia": u"ܩܕܝܫܐ ܕܘܣܝܬܐܘܣ ܡܝܛܪܘܦܘܠܝܛܐ ܕܡܘܠܕܒܝܐ",
    "St Daniil the Hesychast": u"ܡܝܩܪܐ ܕܢܝܐܝܠ ܫܠܝܐ",
    "St Nicodim of Tismana": u"ܡܝܩܪܐ ܢܝܩܘܕܝܡܘܣ ܕܛܝܣܡܢܐ",
    "St Seraphim of Sarov": u"ܩܕܝܫܐ ܣܪܦܝܡ ܕܣܪܘܒ",
    "St Theophan the Recluse": u"ܩܕܝܫܐ ܬܐܘܦܢ ܚܒܝܫܐ",
    "St Xenia of St Petersburg": u"ܩܕܝܫܬܐ ܟܣܢܝܐ ܕܣܢܛ ܦܛܪܣܒܘܪܓ",
    "St Ignatius (Brianchaninov), Bishop of the Caucasus": u"ܩܕܝܫܐ ܐܝܓܢܛܝܘܣ (ܒܪܝܢܟܢܝܢܘܒ) ܐܦܣܩܘܦܐ ܕܩܘܩܣ",
    "St Vladimir, Equal-to-the-Apostles": u"ܩܕܝܫܐ ܒܠܕܝܡܝܪ، ܫܘܐ ܠܫܠܝ̈ܚܐ",
    "St Sergius of Radonezh": u"ܩܕܝܫܐ ܣܪܓܝܘܣ ܕܪܕܘܢܙ",
    "St Ambrose of Optina": u"ܡܝܩܪܐ ܐܡܒܪܘܣܝܘܣ ܕܐܘܦܛܝܢܐ",
    "Synaxis of the Optina Elders": u"ܟܢܘܫܝܐ ܕܣ̈ܒܐ ܡܝܩܪ̈ܐ ܕܐܘܦܛܝܢܐ",
    "St Sava, First Archbishop of Serbia": u"ܩܕܝܫܐ ܣܒܐ ܪܝܫ ܐܦܣܩܘܦܐ ܩܕܡܝܐ ܕܣܪܒܝܐ",
    "St Simeon the Myrrh-gusher": u"ܩܕܝܫܐ ܫܡܥܘܢ ܡܪܕܐ ܡܘܪܘܢ",
    "St Basil of Ostrog": u"ܩܕܝܫܐ ܒܣܝܠܝܘܣ ܕܐܘܣܛܪܘܓ",
    "St Justin Popovich of Ćelije": u"ܡܝܩܪܐ ܝܘܣܛܝܢܘܣ ܦܘܦܘܒܝܟ ܕܟܠܝܐ",
    "St Petar of Koriša": u"ܡܝܩܪܐ ܦܛܪܘܣ ܕܩܘܪܝܫܐ",
    "Holy Great-martyr Tsar Lazar (Vidovdan)": u"ܣܗܕܐ ܪܒܐ ܩܕܝܫܐ ܩܣܪ ܠܙܪ (ܒܝܕܘܒܕܢ)",
    "St Jefrem, Patriarch of Serbia": u"ܩܕܝܫܐ ܐܦܪܝܡ ܦܛܪܝܪܟܐ ܕܣܪܒܝܐ",
    "St Angelina of Serbia": u"ܡܝܩܪܬܐ ܐܢܓܠܝܢܐ ܕܣܪܒܝܐ",
    "Synaxis of the Holy Hierarchs of Serbia": u"ܟܢܘܫܝܐ ܕܪ̈ܝܫܝ ܟܗ̈ܢܐ ܩܕܝ̈ܫܐ ܕܣܪܒܝܐ",
    "The New Martyrs of Jasenovac": u"ܣܗ̈ܕܐ ܚܕ̈ܬܐ ܕܝܣܢܘܒܨ",
    "St Stefan Vladislav, King of Serbia": u"ܩܕܝܫܐ ܐܣܛܦܢ ܒܠܕܝܣܠܒ ܡܠܟܐ ܕܣܪܒܝܐ",
    "St Petar of Cetinje, Wonderworker": u"ܩܕܝܫܐ ܦܛܪܘܣ ܕܨܛܝܢܝܐ ܥܒܕ ܬܕܡܪ̈ܬܐ",
    "St Prohor of Pčinja": u"ܡܝܩܪܐ ܦܪܘܟܘܪ ܕܦܟܝܢܝܐ",
    "St Milutin the King and St Jelena the Queen of Serbia": u"ܩܕܝ̈ܫܐ ܡܝܠܘܛܝܢ ܡܠܟܐ ܘܝܠܢܐ ܡܠܟܬܐ ܕܣܪܒܝܐ",
    "St Stefan Dečanski, King of Serbia": u"ܩܕܝܫܐ ܐܣܛܦܢ ܕܝܟܢܣܩܝ ܡܠܟܐ ܕܣܪܒܝܐ",
    "St Sebastian of Jackson": u"ܡܝܩܪܐ ܣܒܣܛܝܢܘܣ ܕܓܟܣܘܢ",
    "St Joanikije of Devič": u"ܡܝܩܪܐ ܝܘܐܢܝܩܝܘܣ ܕܕܒܝܟ",
    "St Danilo II, Archbishop of Serbia": u"ܩܕܝܫܐ ܕܢܝܐܝܠ ܬܪܝܢܐ ܪܝܫ ܐܦܣܩܘܦܐ ܕܣܪܒܝܐ",
    "St Amphilochius of Pochaiv": u"ܡܝܩܪܐ ܐܡܦܝܠܘܟܝܘܣ ܕܦܘܟܝܒ",
    "St Feodosii of the Kyiv Caves": u"ܡܝܩܪܐ ܬܐܘܕܘܣܝܘܣ ܕܡܥܪ̈ܬܐ ܕܟܝܒ",
    "St Antonii of the Kyiv Caves": u"ܡܝܩܪܐ ܐܢܛܘܢܝܘܣ ܕܡܥܪ̈ܬܐ ܕܟܝܒ",
    "St Olha, Equal-to-the-Apostles": u"ܩܕܝܫܬܐ ܐܘܠܓܐ، ܫܘܝܬ ܠܫܠܝ̈ܚܐ",
    "St Volodymyr, Equal-to-the-Apostles": u"ܩܕܝܫܐ ܒܘܠܘܕܝܡܝܪ، ܫܘܐ ܠܫܠܝ̈ܚܐ",
    "St Petro Mohyla, Metropolitan of Kyiv": u"ܩܕܝܫܐ ܦܛܪܘܣ ܡܘܓܝܠܐ ܡܝܛܪܘܦܘܠܝܛܐ ܕܟܝܒ",
    "Synaxis of All Saints of Antioch": u"ܟܢܘܫܝܐ ܕܟܠܗܘܢ ܩܕܝ̈ܫܐ ܕܐܢܛܝܘܟܝܐ",
    "Synaxis of All Bulgarian Saints": u"ܟܢܘܫܝܐ ܕܟܠܗܘܢ ܩܕܝ̈ܫܐ ܕܒܘܠܓܪܝܐ",
    "Synaxis of All Saints of Mount Athos": u"ܟܢܘܫܝܐ ܕܟܠܗܘܢ ܐܒܗ̈ܬܐ ܡܝܩܪ̈ܐ ܕܛܘܪܐ ܩܕܝܫܐ",
    "Synaxis of All Saints of North America": u"ܟܢܘܫܝܐ ܕܟܠܗܘܢ ܩܕܝ̈ܫܐ ܕܐܡܪܝܟܐ ܓܪܒܝܝܬܐ",
    "Synaxis of All Venerable Fathers of the Kyiv Caves": u"ܟܢܘܫܝܐ ܕܟܠܗܘܢ ܐܒܗ̈ܬܐ ܡܝܩܪ̈ܐ ܕܡܥܪ̈ܬܐ ܕܟܝܒ",
    "Synaxis of All Romanian Saints": u"ܟܢܘܫܝܐ ܕܟܠܗܘܢ ܩܕܝ̈ܫܐ ܕܪܘܡܢܝܐ",
    "Synaxis of All Saints of Russia": u"ܟܢܘܫܝܐ ܕܟܠܗܘܢ ܩܕܝ̈ܫܐ ܕܪܘܣܝܐ",
    "Synaxis of All Saints of Ukraine": u"ܟܢܘܫܝܐ ܕܟܠܗܘܢ ܩܕܝ̈ܫܐ ܕܐܘܟܪܢܝܐ",
    "St Raphael, Bishop of Brooklyn": u"ܩܕܝܫܐ ܪܦܐܝܠ ܐܦܣܩܘܦܐ ܕܒܪܘܩܠܝܢ",
}
