# -*- coding: utf-8 -*-
"""The Churches' own commemorations, in Bulgarian.

See docs/LOCAL_NAMES.md.
"""
TEXT = {
    "St Isaac the Syrian": u"Преподобни Исаак Сирин",
    "Martyr Elian of Homs": u"Свети мъченик Елиан Емески",
    "St Joseph of Damascus & the New Martyrs of Damascus (1860)": u"Свети свещеномъченик Йосиф Дамаскин и новомъчениците Дамаски (1860)",
    "Hieromartyrs Nicholas and Habib Khasha of Damascus": u"Светите свещеномъченици Николай и Хабиб Хаша Дамаски",
    "St Gabriel of Lesnovo": u"Преподобни Гавриил Лесновски",
    "St Joachim I, Patriarch of Tarnovo": u"Свети Йоаким I, патриарх Търновски",
    "St Euthymius, Patriarch of Tarnovo": u"Свети Евтимий, патриарх Търновски",
    "St Peter, King of Bulgaria": u"Свети благоверен цар Петър Български",
    "St Romanus of Tarnovo": u"Преподобни Роман Търновски",
    "St Sophronius, Bishop of Vratsa": u"Свети Софроний, епископ Врачански",
    "St Boris-Michael, Equal-to-the-Apostles, Baptizer of Bulgaria": u"Свети равноапостолен цар Борис-Михаил, покръстител на България",
    "Great Martyr Nicholas of Sofia": u"Свети великомъченик Николай Софийски",
    "St Paisius of Hilendar": u"Преподобни Паисий Хилендарски",
    "The Seven Holy Apostles (Sedmochislenitsi)": u"Светите седем апостоли (Седмочисленици)",
    "St Joachim of Osogovo": u"Преподобни Йоаким Осоговски",
    "Repose of St John of Rila": u"Успение на преподобни Йоан Рилски Чудотворец",
    "New Martyr Simeon of Samokov": u"Свети новомъченик Симеон Самоковски",
    "St Cosmas of Zographou": u"Преподобни Козма Зографски",
    "The 26 Martyrs of Zographou": u"Светите 26 преподобномъченици Зографски",
    "St Demetrius of Basarbovo": u"Преподобни Димитрий Басарбовски",
    "Venerable Pimen of Zographou": u"Преподобни Пимен Зографски",
    "Righteous Michael the Soldier of Bulgaria": u"Свети праведен Михаил воин, българин",
    "St Theodosius of Tarnovo": u"Преподобни Теодосий Търновски",
    "St Nektarios the Bulgarian of Bitola": u"Преподобни Нектарий Битолски, българин",
    "St Nahum of Ohrid": u"Преподобни Наум Охридски",
    "Ss Salome of Ujarma and Perozhavra of Sivnia": u"Светите праведни Саломия Уджармска и Перожавра Сивнийска",
    "St Eprem the Lesser, the Philosopher": u"Преподобни Ефрем Малки, философ",
    "St David IV the Builder, King of Georgia": u"Свети благоверен цар Давид IV Строител на Грузия",
    "St Ioane the Catholicos": u"Светител Йоан, католикос на Грузия",
    "Holy King Demetre the Devoted": u"Свети благоверен цар Димитрий Саможертвени",
    "St Ambrosi the Confessor, Catholicos-Patriarch of All Georgia": u"Светител Амвросий Изповедник, католикос-патриарх на цяла Грузия",
    "Venerable David of the Gareji Monastery": u"Преподобни Давид Гареджийски",
    "St Tamar, Queen of Georgia": u"Света благоверна царица Тамара Грузинска",
    "Venerable Ioane of Zedazeni and his Twelve Disciples": u"Преподобни Йоан Зедазнийски и неговите дванадесет ученици",
    "Venerable Ekvtime of Mount Athos, the Translator": u"Преподобни Евтимий Светогорец, преводач",
    "St George the Hagiorite, and Hieromartyr Kirion II, Catholicos-Patriarch": u"Преподобни Георги Светогорец и свещеномъченик Кирион II, католикос-патриарх",
    "St Ilia the Righteous": u"Свети праведен Илия Чавчавадзе",
    "Holy Martyr Evstati of Mtskheta": u"Свети мъченик Евстатий Мцхетски",
    "St Tsotne Dadiani the Confessor": u"Свети Цотне Дадиани Изповедник",
    "St Razhden, Protomartyr of Georgia, and the Nine Kherkheulidze Brothers": u"Свети първомъченик Ражден Грузински и деветимата братя Херхеулидзе",
    "Holy Confessors Ioane and Giorgi-Ioane of Betania": u"Светите изповедници Йоан и Георги-Йоан Бетанийски",
    "Holy Great-martyr Queen Ketevan": u"Света великомъченица царица Кетеван",
    "Holy Martyrs Bidzina, Shalva and Elizbar": u"Светите мъченици Бидзина, Шалва и Елизбар",
    "Venerable Grigol of Khandzta": u"Преподобни Григорий Хандзтийски",
    "St Gabriel of Samtavro, Confessor and Fool for Christ": u"Преподобни Гавриил Самтаврийски, изповедник и юродив заради Христа",
    "The 100,000 Martyrs of Tbilisi": u"Светите 100 000 мъченици Тбилиски",
    "Holy King Vakhtang Gorgasali": u"Свети благоверен цар Вахтанг Горгасали",
    "St Ise of Tsilkani": u"Светител Иесей Цилкански",
    "Synaxis of All Saints of Georgia": u"Събор на всички светии, просияли в Грузия",
    "Venerable Giorgi the Scribe and his brother Saba of Khakhuli": u"Преподобните Георги Книжовник и брат му Сава Хахулски",
    "St Nikephoros the Leper": u"Преподобни Никифор Прокажени",
    "St Arsenios of Paros": u"Преподобни Арсений Пароски",
    "St Ephraim of Katounakia": u"Преподобни Ефрем Катунакийски",
    "St Nikolaos Planas of Athens": u"Свети праведен Николай Планас Атински",
    "St Savvas the New of Kalymnos": u"Преподобни Сава Нови Калимноски",
    "St Amphilochios of Patmos": u"Преподобни Амфилохий Патмоски",
    "St Joseph the Hesychast": u"Преподобни Йосиф Исихаст",
    "St Kosmas Aitolos, Equal-to-the-Apostles": u"Свети равноапостолен Козма Етолийски",
    "St Arsenios of Cappadocia": u"Преподобни Арсений Кападокийски",
    "St Iakovos of Evia": u"Преподобни Яков Евбейски",
    "St Antipa of Calapodești": u"Преподобни Антипа Калаподещки",
    "St Calinic of Cernica": u"Светител Калиник Чернишки",
    "St Pahomie of Gledin, Bishop of Roman": u"Светител Пахомий Гледински, епископ Романски",
    "Ss Ilie Iorest, Sava Brancovici and Simion Ștefan, Metropolitans of Transylvania": u"Светителите Илия Йорест, Сава Бранкович и Симеон Щефан, митрополити Трансилвански",
    "St Irodion of Lainici": u"Преподобни Иродион Лайнички",
    "St John the Wallachian, Martyr": u"Свети мъченик Йоан Влах",
    "St Iacob Putneanul, Metropolitan of Moldavia": u"Светител Яков Путнянул, митрополит Молдавски",
    "St Grigorie Dascălul, Metropolitan of Wallachia": u"Светител Григорий Учител, митрополит Влашки",
    "St Ghelasie of Râmeț": u"Преподобни Геласий Ръмеци",
    "St Leontie of Rădăuți": u"Светител Леонтий Ръдъуцки",
    "St Stephen the Great": u"Свети благоверен Стефан Велики, владетел Молдавски",
    "St Ioanichie the New of Muscel": u"Преподобни Йоаникий Нови Мусчелски",
    "St Ioan Iacob of Neamț": u"Преподобни Йоан Яков Нямецки",
    "St Teodora of Sihla": u"Преподобна Теодора Сихленска",
    "The Brâncoveanu Martyrs: Prince Constantin and his four sons": u"Светите мъченици Бранковяну: княз Константин и четиримата му синове",
    "St Iosif the New of Partoș, Metropolitan of Banat": u"Светител Йосиф Нови Партошки, митрополит Банатски",
    "St Neagoe Basarab, Voivode of Wallachia": u"Свети благоверен Нягое Басараб, воевода Влашки",
    "St Antim Ivireanul, Hieromartyr, Metropolitan of Wallachia": u"Свети свещеномъченик Антим Иверски, митрополит Влашки",
    "St Parascheva of Iași": u"Преподобна Параскева Яшка",
    "St Dimitrie the New of Bucharest": u"Преподобни Димитрий Нови Букурещки",
    "St Iachint, Metropolitan of Wallachia": u"Светител Якинт, митрополит Влашки",
    "St Andrei Șaguna, Metropolitan of Transylvania": u"Светител Андрей Шагуна, митрополит Трансилвански",
    "St Gheorghe of Cernica": u"Преподобни Георги Чернишки",
    "St Dosoftei, Metropolitan of Moldavia": u"Светител Доситей, митрополит Молдавски",
    "St Daniil the Hesychast": u"Преподобни Даниил Исихаст",
    "St Nicodim of Tismana": u"Преподобни Никодим Тисмански",
    "St Seraphim of Sarov": u"Преподобни Серафим Саровски",
    "St Theophan the Recluse": u"Свети Теофан Затворник",
    "St Xenia of St Petersburg": u"Блажена Ксения Петербургска",
    "St Ignatius (Brianchaninov), Bishop of the Caucasus": u"Светител Игнатий (Брянчанинов), епископ Кавказки",
    "St Vladimir, Equal-to-the-Apostles": u"Свети равноапостолен велик княз Владимир",
    "St Sergius of Radonezh": u"Преподобни Сергий Радонежки",
    "St Ambrose of Optina": u"Преподобни Амвросий Оптински",
    "Synaxis of the Optina Elders": u"Събор на преподобните Оптински старци",
    "St Sava, First Archbishop of Serbia": u"Светител Сава, първи архиепископ Сръбски",
    "St Simeon the Myrrh-gusher": u"Преподобни Симеон Мироточиви",
    "St Basil of Ostrog": u"Светител Василий Острожки",
    "St Justin Popovich of Ćelije": u"Преподобни Юстин (Попович) Челийски",
    "St Petar of Koriša": u"Преподобни Петър Коришки",
    "Holy Great-martyr Tsar Lazar (Vidovdan)": u"Свети великомъченик цар Лазар (Видовден)",
    "St Jefrem, Patriarch of Serbia": u"Светител Ефрем, патриарх Сръбски",
    "St Angelina of Serbia": u"Преподобна Ангелина Сръбска",
    "Synaxis of the Holy Hierarchs of Serbia": u"Събор на светите сръбски светители",
    "The New Martyrs of Jasenovac": u"Светите новомъченици Ясеновацки",
    "St Stefan Vladislav, King of Serbia": u"Свети благоверен крал Стефан Владислав Сръбски",
    "St Petar of Cetinje, Wonderworker": u"Светител Петър Цетински, Чудотворец",
    "St Prohor of Pčinja": u"Преподобни Прохор Пчински",
    "St Milutin the King and St Jelena the Queen of Serbia": u"Светите благоверни крал Милутин и кралица Елена Сръбски",
    "St Stefan Dečanski, King of Serbia": u"Свети благоверен крал Стефан Дечански",
    "St Sebastian of Jackson": u"Преподобни Севастиан Джаксонски",
    "St Joanikije of Devič": u"Преподобни Йоаникий Девички",
    "St Danilo II, Archbishop of Serbia": u"Светител Даниил II, архиепископ Сръбски",
    "St Amphilochius of Pochaiv": u"Преподобни Амфилохий Почаевски",
    "St Feodosii of the Kyiv Caves": u"Преподобни Теодосий Киево-Печерски",
    "St Antonii of the Kyiv Caves": u"Преподобни Антоний Киево-Печерски",
    "St Olha, Equal-to-the-Apostles": u"Света равноапостолна княгиня Олга",
    "St Volodymyr, Equal-to-the-Apostles": u"Свети равноапостолен велик княз Владимир",
    "St Petro Mohyla, Metropolitan of Kyiv": u"Светител Петър Могила, митрополит Киевски",
    "Synaxis of All Saints of Antioch": u"Събор на всички Антиохийски светии",
    "Synaxis of All Bulgarian Saints": u"Събор на всички български светии",
    "Synaxis of All Saints of Mount Athos": u"Събор на всички преподобни отци Светогорци",
    "Synaxis of All Saints of North America": u"Събор на всички светии, просияли в Северна Америка",
    "Synaxis of All Venerable Fathers of the Kyiv Caves": u"Събор на всички преподобни отци Киево-Печерски",
    "Synaxis of All Romanian Saints": u"Събор на всички румънски светии",
    "Synaxis of All Saints of Russia": u"Събор на всички светии, просияли в Руската земя",
    "Synaxis of All Saints of Ukraine": u"Събор на всички светии, просияли в Украинската земя",
    "St Raphael, Bishop of Brooklyn": u"Светител Рафаил, епископ Бруклински",
}
