# -*- coding: utf-8 -*-
"""The Churches' own commemorations, in Bengali.

See docs/LOCAL_NAMES.md.
"""
TEXT = {
    "St Isaac the Syrian": u"সিরিয়ার শ্রদ্ধেয় ইসহাক",
    "Martyr Elian of Homs": u"হোমসের শহীদ এলিয়ান",
    "St Joseph of Damascus & the New Martyrs of Damascus (1860)": u"দামেস্কের যাজক-শহীদ ইউসুফ ও দামেস্কের নতুন শহীদগণ (১৮৬০)",
    "Hieromartyrs Nicholas and Habib Khasha of Damascus": u"দামেস্কের যাজক-শহীদ নিকোলাস ও হাবিব খাশা",
    "St Gabriel of Lesnovo": u"লেসনোভোর শ্রদ্ধেয় গ্যাব্রিয়েল",
    "St Joachim I, Patriarch of Tarnovo": u"তারনোভোর প্যাট্রিয়ার্ক সন্ত জোয়াকিম প্রথম",
    "St Euthymius, Patriarch of Tarnovo": u"তারনোভোর প্যাট্রিয়ার্ক সন্ত ইউথিমিয়াস",
    "St Peter, King of Bulgaria": u"বুলগেরিয়ার রাজা সন্ত পিটার",
    "St Romanus of Tarnovo": u"তারনোভোর শ্রদ্ধেয় রোমানুস",
    "St Sophronius, Bishop of Vratsa": u"ভ্রাৎসার বিশপ সন্ত সোফ্রোনিয়াস",
    "St Boris-Michael, Equal-to-the-Apostles, Baptizer of Bulgaria": u"বুলগেরিয়ার বাপ্তিস্মদাতা সন্ত বোরিস-মিখাইল, প্রেরিতদের সমতুল্য",
    "Great Martyr Nicholas of Sofia": u"সোফিয়ার মহান শহীদ নিকোলাস",
    "St Paisius of Hilendar": u"হিলান্দারের শ্রদ্ধেয় পাইসিয়াস",
    "The Seven Holy Apostles (Sedmochislenitsi)": u"সাতজন পবিত্র প্রেরিত (সেদমোচিসলেনিৎসি)",
    "St Joachim of Osogovo": u"ওসোগোভোর শ্রদ্ধেয় জোয়াকিম",
    "Repose of St John of Rila": u"রিলার শ্রদ্ধেয় যোহনের বিশ্রাম",
    "New Martyr Simeon of Samokov": u"সামোকোভের নতুন শহীদ শিমিওন",
    "St Cosmas of Zographou": u"জোগ্রাফুর শ্রদ্ধেয় কোসমাস",
    "The 26 Martyrs of Zographou": u"জোগ্রাফুর ছাব্বিশ শহীদ",
    "St Demetrius of Basarbovo": u"বাসারাবোভোর শ্রদ্ধেয় দিমিত্রিয়াস",
    "Venerable Pimen of Zographou": u"জোগ্রাফুর শ্রদ্ধেয় পিমেন",
    "Righteous Michael the Soldier of Bulgaria": u"বুলগেরিয়ার ধার্মিক সৈনিক মিখাইল",
    "St Theodosius of Tarnovo": u"তারনোভোর শ্রদ্ধেয় থিওডোসিয়াস",
    "St Nektarios the Bulgarian of Bitola": u"বিতোলার শ্রদ্ধেয় শহীদ নেক্তারিয়াস",
    "St Nahum of Ohrid": u"ওহরিদের শ্রদ্ধেয় নাহুম",
    "Ss Salome of Ujarma and Perozhavra of Sivnia": u"উজারমার ধার্মিক সালোমি ও সিভনিয়ার পেরোজাভরা",
    "St Eprem the Lesser, the Philosopher": u"শ্রদ্ধেয় এপ্রেম ক্ষুদ্র, দার্শনিক",
    "St David IV the Builder, King of Georgia": u"জর্জিয়ার রাজা সন্ত দাউদ চতুর্থ নির্মাতা",
    "St Ioane the Catholicos": u"জর্জিয়ার ক্যাথলিকোস সন্ত ইওয়ানে",
    "Holy King Demetre the Devoted": u"জর্জিয়ার রাজা সন্ত দেমেত্রে আত্মোৎসর্গী",
    "St Ambrosi the Confessor, Catholicos-Patriarch of All Georgia": u"সমগ্র জর্জিয়ার ক্যাথলিকোস-প্যাট্রিয়ার্ক স্বীকারকারী সন্ত আমব্রোসি",
    "Venerable David of the Gareji Monastery": u"গারেজির শ্রদ্ধেয় দাউদ",
    "St Tamar, Queen of Georgia": u"জর্জিয়ার রানী সন্ত তামার",
    "Venerable Ioane of Zedazeni and his Twelve Disciples": u"জেদাজেনির শ্রদ্ধেয় ইওয়ানে ও তাঁর বারোজন শিষ্য",
    "Venerable Ekvtime of Mount Athos, the Translator": u"আথোস পর্বতের শ্রদ্ধেয় এক্‌ভতিমে, অনুবাদক",
    "St George the Hagiorite, and Hieromartyr Kirion II, Catholicos-Patriarch": u"আথোস পর্বতের শ্রদ্ধেয় গিওর্গি ও যাজক-শহীদ কিরিওন দ্বিতীয়, ক্যাথলিকোস-প্যাট্রিয়ার্ক",
    "St Ilia the Righteous": u"ধার্মিক সন্ত ইলিয়া",
    "Holy Martyr Evstati of Mtskheta": u"মৎসখেতার শহীদ এভস্তাতি",
    "St Tsotne Dadiani the Confessor": u"স্বীকারকারী সন্ত ৎসোৎনে দাদিয়ানি",
    "St Razhden, Protomartyr of Georgia, and the Nine Kherkheulidze Brothers": u"জর্জিয়ার প্রথম শহীদ রাজদেন ও খেরখেউলিদজের নয় ভাই",
    "Holy Confessors Ioane and Giorgi-Ioane of Betania": u"বেতানিয়ার স্বীকারকারী সন্ত ইওয়ানে ও গিওর্গি-ইওয়ানে",
    "Holy Great-martyr Queen Ketevan": u"মহান শহীদ রানী কেতেভান",
    "Holy Martyrs Bidzina, Shalva and Elizbar": u"শহীদ বিদজিনা, শালভা ও এলিজবার",
    "Venerable Grigol of Khandzta": u"খানদজতার শ্রদ্ধেয় গ্রিগোল",
    "St Gabriel of Samtavro, Confessor and Fool for Christ": u"সামতাভরোর শ্রদ্ধেয় গ্যাব্রিয়েল, স্বীকারকারী ও খ্রিষ্টের জন্য মূর্খ",
    "The 100,000 Martyrs of Tbilisi": u"তিবি‌লিসির এক লক্ষ শহীদ",
    "Holy King Vakhtang Gorgasali": u"জর্জিয়ার রাজা সন্ত ভাখতাং গোর্গাসালি",
    "St Ise of Tsilkani": u"ৎসিলকানির সন্ত ইসে",
    "Synaxis of All Saints of Georgia": u"জর্জিয়ার সমস্ত সন্তগণ",
    "Venerable Giorgi the Scribe and his brother Saba of Khakhuli": u"খাখুলির শ্রদ্ধেয় লেখক গিওর্গি ও তাঁর ভাই সাবা",
    "St Nikephoros the Leper": u"শ্রদ্ধেয় কুষ্ঠরোগী নিকিফোরোস",
    "St Arsenios of Paros": u"পারোসের শ্রদ্ধেয় আর্সেনিয়াস",
    "St Ephraim of Katounakia": u"কাতুনাকিয়ার শ্রদ্ধেয় এপ্রেম",
    "St Nikolaos Planas of Athens": u"এথেন্সের ধার্মিক নিকোলাস প্লানাস",
    "St Savvas the New of Kalymnos": u"কালিমনোসের শ্রদ্ধেয় নতুন সাভা",
    "St Amphilochios of Patmos": u"পাতমোসের শ্রদ্ধেয় আম্ফিলোখিয়াস",
    "St Joseph the Hesychast": u"শ্রদ্ধেয় নীরবতাসাধক ইউসুফ",
    "St Kosmas Aitolos, Equal-to-the-Apostles": u"এতোলিয়ার সন্ত কোসমাস, প্রেরিতদের সমতুল্য",
    "St Arsenios of Cappadocia": u"কাপাদোকিয়ার শ্রদ্ধেয় আর্সেনিয়াস",
    "St Iakovos of Evia": u"এভিয়ার শ্রদ্ধেয় ইয়াকোভোস",
    "St Antipa of Calapodești": u"কালাপোদেশতির শ্রদ্ধেয় আন্তিপা",
    "St Calinic of Cernica": u"চেরনিকার সন্ত কালিনিক",
    "St Pahomie of Gledin, Bishop of Roman": u"গ্লেদিনের সন্ত পাহোমিয়ে, রোমানের বিশপ",
    "Ss Ilie Iorest, Sava Brancovici and Simion Ștefan, Metropolitans of Transylvania": u"ট্রান্সিলভানিয়ার মেট্রোপলিটন সন্ত ইলিয়ে ইওরেস্ত, সাভা ব্রানকোভিচি ও সিমিওন শ্তেফান",
    "St Irodion of Lainici": u"লাইনিচির শ্রদ্ধেয় ইরোদিওন",
    "St John the Wallachian, Martyr": u"শহীদ যোহন ভ্লাখ",
    "St Iacob Putneanul, Metropolitan of Moldavia": u"মলদাভিয়ার মেট্রোপলিটন সন্ত ইয়াকোব পুতনেয়ানুল",
    "St Grigorie Dascălul, Metropolitan of Wallachia": u"ওয়ালাখিয়ার মেট্রোপলিটন সন্ত গ্রিগোরিয়ে দাসকালুল",
    "St Ghelasie of Râmeț": u"রিমেৎসের সন্ত ঘেলাসিয়ে",
    "St Leontie of Rădăuți": u"রাদাউৎসির সন্ত লেওন্তিয়ে",
    "St Stephen the Great": u"সন্ত মহান স্টিফেন",
    "St Ioanichie the New of Muscel": u"মুশ্চেলের শ্রদ্ধেয় নতুন ইওয়ানিকিয়ে",
    "St Ioan Iacob of Neamț": u"নিয়ামৎসের শ্রদ্ধেয় ইওয়ান ইয়াকোব",
    "St Teodora of Sihla": u"সিহলার শ্রদ্ধেয় থিওডোরা",
    "The Brâncoveanu Martyrs: Prince Constantin and his four sons": u"ব্রিনকোভেয়ানু শহীদগণ: শাসক কনস্তান্তিন ও তাঁর চার পুত্র",
    "St Iosif the New of Partoș, Metropolitan of Banat": u"বানাতের মেট্রোপলিটন, পার্তোশের সন্ত নতুন ইওসিফ",
    "St Neagoe Basarab, Voivode of Wallachia": u"ওয়ালাখিয়ার শাসক সন্ত নিয়াগোয়ে বাসারাব",
    "St Antim Ivireanul, Hieromartyr, Metropolitan of Wallachia": u"ওয়ালাখিয়ার মেট্রোপলিটন, যাজক-শহীদ আন্তিম ইভিরেয়ানুল",
    "St Parascheva of Iași": u"ইয়াশির শ্রদ্ধেয় পারাস্কেভা",
    "St Dimitrie the New of Bucharest": u"বুখারেস্টের সন্ত নতুন দিমিত্রিয়ে",
    "St Iachint, Metropolitan of Wallachia": u"ওয়ালাখিয়ার মেট্রোপলিটন সন্ত ইয়াকিন্ত",
    "St Andrei Șaguna, Metropolitan of Transylvania": u"ট্রান্সিলভানিয়ার মেট্রোপলিটন সন্ত আন্দ্রেই শাগুনা",
    "St Gheorghe of Cernica": u"চেরনিকার শ্রদ্ধেয় ঘেওর্ঘে",
    "St Dosoftei, Metropolitan of Moldavia": u"মলদাভিয়ার মেট্রোপলিটন সন্ত দোসোফতেই",
    "St Daniil the Hesychast": u"শ্রদ্ধেয় নীরবতাসাধক দানিইল",
    "St Nicodim of Tismana": u"তিসমানার শ্রদ্ধেয় নিকোদিম",
    "St Seraphim of Sarov": u"সারোভের সন্ত সেরাফিম",
    "St Theophan the Recluse": u"সন্ত নিভৃতবাসী থিওফান",
    "St Xenia of St Petersburg": u"সেন্ট পিটার্সবার্গের সন্ত জেনিয়া",
    "St Ignatius (Brianchaninov), Bishop of the Caucasus": u"ককেশাসের বিশপ সন্ত ইগ্নাতিয়াস (ব্রিয়ানচানিনভ)",
    "St Vladimir, Equal-to-the-Apostles": u"সন্ত ভ্লাদিমির, প্রেরিতদের সমতুল্য",
    "St Sergius of Radonezh": u"রাদোনেজের সন্ত সের্গিয়াস",
    "St Ambrose of Optina": u"অপ্তিনার শ্রদ্ধেয় আমব্রোসিয়াস",
    "Synaxis of the Optina Elders": u"অপ্তিনার শ্রদ্ধেয় প্রবীণগণ",
    "St Sava, First Archbishop of Serbia": u"সার্বিয়ার প্রথম আর্চবিশপ সন্ত সাভা",
    "St Simeon the Myrrh-gusher": u"মির্‌-ক্ষরা সন্ত সিমিওন",
    "St Basil of Ostrog": u"ওস্ত্রোগের সন্ত বাসিল",
    "St Justin Popovich of Ćelije": u"চেলিয়ের শ্রদ্ধেয় ইউস্তিন পোপোভিচ",
    "St Petar of Koriša": u"কোরিশার শ্রদ্ধেয় পেতার",
    "Holy Great-martyr Tsar Lazar (Vidovdan)": u"পবিত্র মহান শহীদ জার লাজার (ভিদোভদান)",
    "St Jefrem, Patriarch of Serbia": u"সার্বিয়ার প্যাট্রিয়ার্ক সন্ত ইয়েফ্রেম",
    "St Angelina of Serbia": u"সার্বিয়ার শ্রদ্ধেয় আঙ্গেলিনা",
    "Synaxis of the Holy Hierarchs of Serbia": u"সার্বিয়ার পবিত্র বিশপগণ",
    "The New Martyrs of Jasenovac": u"ইয়াসেনোভাৎসের নতুন শহীদগণ",
    "St Stefan Vladislav, King of Serbia": u"সার্বিয়ার রাজা সন্ত স্তেফান ভ্লাদিস্লাভ",
    "St Petar of Cetinje, Wonderworker": u"চেতিনিয়ের সন্ত পেতার, অলৌকিককর্মী",
    "St Prohor of Pčinja": u"প্চিনিয়ার শ্রদ্ধেয় প্রোহোর",
    "St Milutin the King and St Jelena the Queen of Serbia": u"সার্বিয়ার রাজা সন্ত মিলুতিন ও রানী সন্ত ইয়েলেনা",
    "St Stefan Dečanski, King of Serbia": u"সার্বিয়ার রাজা সন্ত স্তেফান দেচানস্কি",
    "St Sebastian of Jackson": u"জ্যাকসনের শ্রদ্ধেয় সেবাস্তিয়ান",
    "St Joanikije of Devič": u"দেভিচের শ্রদ্ধেয় ইওয়ানিকিয়ে",
    "St Danilo II, Archbishop of Serbia": u"সার্বিয়ার আর্চবিশপ সন্ত দানিলো দ্বিতীয়",
    "St Amphilochius of Pochaiv": u"পোচাইভের শ্রদ্ধেয় আম্ফিলোখিয়াস",
    "St Feodosii of the Kyiv Caves": u"কিয়েভের গুহার শ্রদ্ধেয় থিওডোসিয়াস",
    "St Antonii of the Kyiv Caves": u"কিয়েভের গুহার শ্রদ্ধেয় আন্তোনি",
    "St Olha, Equal-to-the-Apostles": u"সন্ত ওলহা, প্রেরিতদের সমতুল্য",
    "St Volodymyr, Equal-to-the-Apostles": u"সন্ত ভোলোদিমির, প্রেরিতদের সমতুল্য",
    "St Petro Mohyla, Metropolitan of Kyiv": u"কিয়েভের মেট্রোপলিটন সন্ত পেত্রো মোহিলা",
    "Synaxis of All Saints of Antioch": u"আন্তিয়খিয়ার সমস্ত সন্তগণ",
    "Synaxis of All Bulgarian Saints": u"বুলগেরিয়ার সমস্ত সন্তগণ",
    "Synaxis of All Saints of Mount Athos": u"আথোস পর্বতের সমস্ত শ্রদ্ধেয় পিতৃগণ",
    "Synaxis of All Saints of North America": u"উত্তর আমেরিকার সমস্ত সন্তগণ",
    "Synaxis of All Venerable Fathers of the Kyiv Caves": u"কিয়েভের গুহার সমস্ত শ্রদ্ধেয় পিতৃগণ",
    "Synaxis of All Romanian Saints": u"রোমানিয়ার সমস্ত সন্তগণ",
    "Synaxis of All Saints of Russia": u"রাশিয়ার সমস্ত সন্তগণ",
    "Synaxis of All Saints of Ukraine": u"ইউক্রেনের সমস্ত সন্তগণ",
    "St Raphael, Bishop of Brooklyn": u"ব্রুকলিনের সন্ত রাফায়েল, বিশপ",
}
