# -*- coding: utf-8 -*-
"""The Churches' own commemorations, in German.

See docs/LOCAL_NAMES.md.
"""
TEXT = {
    "St Isaac the Syrian": u"Hl. Isaak der Syrer",
    "Martyr Elian of Homs": u"Hl. Märtyrer Elian von Homs",
    "St Joseph of Damascus & the New Martyrs of Damascus (1860)": u"Hl. Hieromärtyrer Joseph von Damaskus und die Neumärtyrer von Damaskus (1860)",
    "Hieromartyrs Nicholas and Habib Khasha of Damascus": u"Hl. Hieromärtyrer Nikolaus und Habib Khasha von Damaskus",
    "St Gabriel of Lesnovo": u"Hl. Gabriel von Lesnovo",
    "St Joachim I, Patriarch of Tarnovo": u"Hl. Joachim I., Patriarch von Tarnowo",
    "St Euthymius, Patriarch of Tarnovo": u"Hl. Euthymius, Patriarch von Tarnowo",
    "St Peter, King of Bulgaria": u"Hl. Zar Peter von Bulgarien",
    "St Romanus of Tarnovo": u"Hl. Romanus von Tarnowo",
    "St Sophronius, Bishop of Vratsa": u"Hl. Sophronius, Bischof von Wratza",
    "St Boris-Michael, Equal-to-the-Apostles, Baptizer of Bulgaria": u"Hl. Boris-Michael, den Aposteln gleich, Täufer Bulgariens",
    "Great Martyr Nicholas of Sofia": u"Hl. Grossmärtyrer Nikolaus von Sofia",
    "St Paisius of Hilendar": u"Hl. Paisius von Hilandar",
    "The Seven Holy Apostles (Sedmochislenitsi)": u"Die Heiligen Sieben Apostel (Sedmotschislenizi)",
    "St Joachim of Osogovo": u"Hl. Joachim von Osogovo",
    "Repose of St John of Rila": u"Entschlafung des hl. Johannes von Rila",
    "New Martyr Simeon of Samokov": u"Hl. Neumärtyrer Simeon von Samokow",
    "St Cosmas of Zographou": u"Hl. Kosmas von Zographou",
    "The 26 Martyrs of Zographou": u"Die 26 Märtyrer von Zographou",
    "St Demetrius of Basarbovo": u"Hl. Demetrius von Bassarabovo",
    "Venerable Pimen of Zographou": u"Hl. Pimen von Zographou",
    "Righteous Michael the Soldier of Bulgaria": u"Der gerechte Michael der Soldat von Bulgarien",
    "St Theodosius of Tarnovo": u"Hl. Theodosius von Tarnowo",
    "St Nektarios the Bulgarian of Bitola": u"Hl. Märtyrer Nektarios von Bitola",
    "St Nahum of Ohrid": u"Hl. Naum von Ohrid",
    "Ss Salome of Ujarma and Perozhavra of Sivnia": u"Die gerechten Salome von Udscharma und Peroschawra von Siwnia",
    "St Eprem the Lesser, the Philosopher": u"Hl. Ephräm der Jüngere, der Philosoph",
    "St David IV the Builder, King of Georgia": u"Hl. König David IV. der Erbauer von Georgien",
    "St Ioane the Catholicos": u"Hl. Ioane, Katholikos von Georgien",
    "Holy King Demetre the Devoted": u"Hl. König Demetre der Hingebende",
    "St Ambrosi the Confessor, Catholicos-Patriarch of All Georgia": u"Hl. Ambrosi der Bekenner, Katholikos-Patriarch von ganz Georgien",
    "Venerable David of the Gareji Monastery": u"Hl. David vom Kloster Garedscha",
    "St Tamar, Queen of Georgia": u"Hl. Tamar, Königin von Georgien",
    "Venerable Ioane of Zedazeni and his Twelve Disciples": u"Hl. Ioane von Sedaseni und seine zwölf Schüler",
    "Venerable Ekvtime of Mount Athos, the Translator": u"Hl. Ekwtime vom Berg Athos, der Übersetzer",
    "St George the Hagiorite, and Hieromartyr Kirion II, Catholicos-Patriarch": u"Hl. Georg der Hagiorit und Hieromärtyrer Kirion II., Katholikos-Patriarch",
    "St Ilia the Righteous": u"Der gerechte Ilia",
    "Holy Martyr Evstati of Mtskheta": u"Hl. Märtyrer Evstati von Mzcheta",
    "St Tsotne Dadiani the Confessor": u"Hl. Zotne Dadiani der Bekenner",
    "St Razhden, Protomartyr of Georgia, and the Nine Kherkheulidze Brothers": u"Hl. Erstmärtyrer Raschden von Georgien und die neun Brüder Kherkheulidse",
    "Holy Confessors Ioane and Giorgi-Ioane of Betania": u"Hl. Bekenner Ioane und Giorgi-Ioane von Betania",
    "Holy Great-martyr Queen Ketevan": u"Hl. Grossmärtyrerin Königin Ketevan",
    "Holy Martyrs Bidzina, Shalva and Elizbar": u"Hl. Märtyrer Bidsina, Schalwa und Elisbar",
    "Venerable Grigol of Khandzta": u"Hl. Grigol von Chandsta",
    "St Gabriel of Samtavro, Confessor and Fool for Christ": u"Hl. Gabriel von Samtawro, Bekenner und Narr in Christo",
    "The 100,000 Martyrs of Tbilisi": u"Die 100.000 Märtyrer von Tiflis",
    "Holy King Vakhtang Gorgasali": u"Hl. König Wachtang Gorgasali",
    "St Ise of Tsilkani": u"Hl. Ise von Zilkani",
    "Synaxis of All Saints of Georgia": u"Synaxis aller Heiligen Georgiens",
    "Venerable Giorgi the Scribe and his brother Saba of Khakhuli": u"Hl. Giorgi der Schreiber und sein Bruder Saba von Chachuli",
    "St Nikephoros the Leper": u"Hl. Nikephoros der Aussätzige",
    "St Arsenios of Paros": u"Hl. Arsenios von Paros",
    "St Ephraim of Katounakia": u"Hl. Ephraim von Katounakia",
    "St Nikolaos Planas of Athens": u"Der gerechte Nikolaos Planas von Athen",
    "St Savvas the New of Kalymnos": u"Hl. Savvas der Neue von Kalymnos",
    "St Amphilochios of Patmos": u"Hl. Amphilochios von Patmos",
    "St Joseph the Hesychast": u"Hl. Joseph der Hesychast",
    "St Kosmas Aitolos, Equal-to-the-Apostles": u"Hl. Kosmas der Ätoler, den Aposteln gleich",
    "St Arsenios of Cappadocia": u"Hl. Arsenios von Kappadokien",
    "St Iakovos of Evia": u"Hl. Iakovos von Euböa",
    "St Antipa of Calapodești": u"Hl. Antipa von Calapodesti",
    "St Calinic of Cernica": u"Hl. Kalinik von Cernica",
    "St Pahomie of Gledin, Bishop of Roman": u"Hl. Pahomie von Gledin, Bischof von Roman",
    "Ss Ilie Iorest, Sava Brancovici and Simion Ștefan, Metropolitans of Transylvania": u"Hl. Ilie Iorest, Sava Brancovici und Simion Stefan, Metropoliten von Siebenbürgen",
    "St Irodion of Lainici": u"Hl. Irodion von Lainici",
    "St John the Wallachian, Martyr": u"Hl. Märtyrer Johannes der Walache",
    "St Iacob Putneanul, Metropolitan of Moldavia": u"Hl. Iacob Putneanul, Metropolit der Moldau",
    "St Grigorie Dascălul, Metropolitan of Wallachia": u"Hl. Grigorie Dascalul, Metropolit der Walachei",
    "St Ghelasie of Râmeț": u"Hl. Ghelasie von Ramet",
    "St Leontie of Rădăuți": u"Hl. Leontie von Radauti",
    "St Stephen the Great": u"Hl. Stefan der Grosse",
    "St Ioanichie the New of Muscel": u"Hl. Ioanichie der Neue von Muscel",
    "St Ioan Iacob of Neamț": u"Hl. Ioan Iacob von Neamt",
    "St Teodora of Sihla": u"Hl. Teodora von Sihla",
    "The Brâncoveanu Martyrs: Prince Constantin and his four sons": u"Die Brancoveanu-Märtyrer: Fürst Constantin und seine vier Söhne",
    "St Iosif the New of Partoș, Metropolitan of Banat": u"Hl. Iosif der Neue von Partos, Metropolit des Banats",
    "St Neagoe Basarab, Voivode of Wallachia": u"Hl. Neagoe Basarab, Fürst der Walachei",
    "St Antim Ivireanul, Hieromartyr, Metropolitan of Wallachia": u"Hl. Hieromärtyrer Antim Ivireanul, Metropolit der Walachei",
    "St Parascheva of Iași": u"Hl. Parascheva von Jassy",
    "St Dimitrie the New of Bucharest": u"Hl. Dimitrie der Neue von Bukarest",
    "St Iachint, Metropolitan of Wallachia": u"Hl. Iachint, Metropolit der Walachei",
    "St Andrei Șaguna, Metropolitan of Transylvania": u"Hl. Andrei Saguna, Metropolit von Siebenbürgen",
    "St Gheorghe of Cernica": u"Hl. Gheorghe von Cernica",
    "St Dosoftei, Metropolitan of Moldavia": u"Hl. Dosoftei, Metropolit der Moldau",
    "St Daniil the Hesychast": u"Hl. Daniil der Hesychast",
    "St Nicodim of Tismana": u"Hl. Nicodim von Tismana",
    "St Seraphim of Sarov": u"Hl. Seraphim von Sarow",
    "St Theophan the Recluse": u"Hl. Theophan der Klausner",
    "St Xenia of St Petersburg": u"Hl. Xenia von St. Petersburg",
    "St Ignatius (Brianchaninov), Bishop of the Caucasus": u"Hl. Ignatius (Brjantschaninow), Bischof des Kaukasus",
    "St Vladimir, Equal-to-the-Apostles": u"Hl. Wladimir, den Aposteln gleich",
    "St Sergius of Radonezh": u"Hl. Sergius von Radonesch",
    "St Ambrose of Optina": u"Hl. Ambrosius von Optina",
    "Synaxis of the Optina Elders": u"Synaxis der Starzen von Optina",
    "St Sava, First Archbishop of Serbia": u"Hl. Sava, erster Erzbischof von Serbien",
    "St Simeon the Myrrh-gusher": u"Hl. Simeon der Myronspender",
    "St Basil of Ostrog": u"Hl. Basilius von Ostrog",
    "St Justin Popovich of Ćelije": u"Hl. Justin Popovic von Celije",
    "St Petar of Koriša": u"Hl. Petar von Korisa",
    "Holy Great-martyr Tsar Lazar (Vidovdan)": u"Hl. Grossmärtyrer Fürst Lazar (Vidovdan)",
    "St Jefrem, Patriarch of Serbia": u"Hl. Jefrem, Patriarch von Serbien",
    "St Angelina of Serbia": u"Hl. Angelina von Serbien",
    "Synaxis of the Holy Hierarchs of Serbia": u"Synaxis der heiligen Hierarchen Serbiens",
    "The New Martyrs of Jasenovac": u"Die Neumärtyrer von Jasenovac",
    "St Stefan Vladislav, King of Serbia": u"Hl. Stefan Vladislav, König von Serbien",
    "St Petar of Cetinje, Wonderworker": u"Hl. Petar von Cetinje, der Wundertäter",
    "St Prohor of Pčinja": u"Hl. Prohor von Pcinja",
    "St Milutin the King and St Jelena the Queen of Serbia": u"Hl. König Milutin und hl. Königin Jelena von Serbien",
    "St Stefan Dečanski, King of Serbia": u"Hl. Stefan Decanski, König von Serbien",
    "St Sebastian of Jackson": u"Hl. Sebastian von Jackson",
    "St Joanikije of Devič": u"Hl. Joanikije von Devic",
    "St Danilo II, Archbishop of Serbia": u"Hl. Danilo II., Erzbischof von Serbien",
    "St Amphilochius of Pochaiv": u"Hl. Amphilochius von Potschajiw",
    "St Feodosii of the Kyiv Caves": u"Hl. Theodosius vom Kiewer Höhlenkloster",
    "St Antonii of the Kyiv Caves": u"Hl. Antonius vom Kiewer Höhlenkloster",
    "St Olha, Equal-to-the-Apostles": u"Hl. Olga, den Aposteln gleich",
    "St Volodymyr, Equal-to-the-Apostles": u"Hl. Wladimir, den Aposteln gleich",
    "St Petro Mohyla, Metropolitan of Kyiv": u"Hl. Petro Mohyla, Metropolit von Kiew",
    "Synaxis of All Saints of Antioch": u"Synaxis aller Heiligen von Antiochien",
    "Synaxis of All Bulgarian Saints": u"Synaxis aller Heiligen Bulgariens",
    "Synaxis of All Saints of Mount Athos": u"Synaxis aller Heiligen vom Berg Athos",
    "Synaxis of All Saints of North America": u"Synaxis aller Heiligen Nordamerikas",
    "Synaxis of All Venerable Fathers of the Kyiv Caves": u"Synaxis aller Väter des Kiewer Höhlenklosters",
    "Synaxis of All Romanian Saints": u"Synaxis aller Heiligen Rumäniens",
    "Synaxis of All Saints of Russia": u"Synaxis aller Heiligen Russlands",
    "Synaxis of All Saints of Ukraine": u"Synaxis aller Heiligen der Ukraine",
    "St Raphael, Bishop of Brooklyn": u"Hl. Raphael, Bischof von Brooklyn",
}
