# -*- coding: utf-8 -*-
"""The Churches' own commemorations, in Greek.

Monotonic, as the rest of the calendar's Greek is.

See docs/LOCAL_NAMES.md.
"""
TEXT = {
    "St Isaac the Syrian": u"Όσιος Ισαάκ ο Σύρος",
    "Martyr Elian of Homs": u"Άγιος μάρτυς Ηλιανός ο εν Εμέση",
    "St Joseph of Damascus & the New Martyrs of Damascus (1860)": u"Ιερομάρτυς Ιωσήφ ο Δαμασκηνός και οι νεομάρτυρες Δαμασκού (1860)",
    "Hieromartyrs Nicholas and Habib Khasha of Damascus": u"Ιερομάρτυρες Νικόλαος και Χαμπίμπ Χάσα οι Δαμασκηνοί",
    "St Gabriel of Lesnovo": u"Όσιος Γαβριήλ του Λεσνόβου",
    "St Joachim I, Patriarch of Tarnovo": u"Άγιος Ιωακείμ Α', πατριάρχης Τυρνόβου",
    "St Euthymius, Patriarch of Tarnovo": u"Άγιος Ευθύμιος, πατριάρχης Τυρνόβου",
    "St Peter, King of Bulgaria": u"Άγιος Πέτρος, τσάρος των Βουλγάρων",
    "St Romanus of Tarnovo": u"Όσιος Ρωμανός του Τυρνόβου",
    "St Sophronius, Bishop of Vratsa": u"Άγιος Σωφρόνιος, επίσκοπος Βράτσης",
    "St Boris-Michael, Equal-to-the-Apostles, Baptizer of Bulgaria": u"Άγιος ισαπόστολος Βόρις-Μιχαήλ, ο φωτιστής των Βουλγάρων",
    "Great Martyr Nicholas of Sofia": u"Άγιος μεγαλομάρτυς Νικόλαος ο εν Σόφια",
    "St Paisius of Hilendar": u"Όσιος Παΐσιος ο Χιλανδαρινός",
    "The Seven Holy Apostles (Sedmochislenitsi)": u"Οι Άγιοι Επτά Απόστολοι (Επταρίθμιοι)",
    "St Joachim of Osogovo": u"Όσιος Ιωακείμ του Οσογόβου",
    "Repose of St John of Rila": u"Κοίμησις του οσίου Ιωάννου της Ρίλας",
    "New Martyr Simeon of Samokov": u"Άγιος νεομάρτυς Συμεών ο Σαμοκοβίου",
    "St Cosmas of Zographou": u"Όσιος Κοσμάς ο Ζωγραφίτης",
    "The 26 Martyrs of Zographou": u"Οι 26 μάρτυρες της Μονής Ζωγράφου",
    "St Demetrius of Basarbovo": u"Όσιος Δημήτριος του Μπασάρμποβο",
    "Venerable Pimen of Zographou": u"Όσιος Ποιμήν ο Ζωγραφίτης",
    "Righteous Michael the Soldier of Bulgaria": u"Δίκαιος Μιχαήλ ο στρατιώτης ο Βούλγαρος",
    "St Theodosius of Tarnovo": u"Όσιος Θεοδόσιος του Τυρνόβου",
    "St Nektarios the Bulgarian of Bitola": u"Οσιομάρτυς Νεκτάριος ο εκ Μοναστηρίου",
    "St Nahum of Ohrid": u"Όσιος Ναούμ της Αχρίδος",
    "Ss Salome of Ujarma and Perozhavra of Sivnia": u"Δίκαιες Σαλώμη της Ουτζάρμα και Περοζάβρα της Σιβνίας",
    "St Eprem the Lesser, the Philosopher": u"Όσιος Εφραίμ ο Μικρός, ο φιλόσοφος",
    "St David IV the Builder, King of Georgia": u"Άγιος Δαβίδ Δ' ο Ανοικοδομητής, βασιλεύς της Γεωργίας",
    "St Ioane the Catholicos": u"Άγιος Ιωάννης, καθολικός της Γεωργίας",
    "Holy King Demetre the Devoted": u"Άγιος Δημήτριος ο Αυτοθυσιαστής, βασιλεύς της Γεωργίας",
    "St Ambrosi the Confessor, Catholicos-Patriarch of All Georgia": u"Άγιος Αμβρόσιος ο ομολογητής, καθολικός-πατριάρχης πάσης Γεωργίας",
    "Venerable David of the Gareji Monastery": u"Όσιος Δαβίδ της Γαρέτζα",
    "St Tamar, Queen of Georgia": u"Αγία Θάμαρ, βασίλισσα της Γεωργίας",
    "Venerable Ioane of Zedazeni and his Twelve Disciples": u"Όσιος Ιωάννης της Ζενταζένι και οι δώδεκα μαθητές του",
    "Venerable Ekvtime of Mount Athos, the Translator": u"Όσιος Ευθύμιος ο Αγιορείτης, ο μεταφραστής",
    "St George the Hagiorite, and Hieromartyr Kirion II, Catholicos-Patriarch": u"Όσιος Γεώργιος ο Αγιορείτης και ιερομάρτυς Κυρίων Β', καθολικός-πατριάρχης",
    "St Ilia the Righteous": u"Δίκαιος Ηλίας ο Τσαβτσαβάτζε",
    "Holy Martyr Evstati of Mtskheta": u"Άγιος μάρτυς Ευστάθιος ο εν Μτσχέτα",
    "St Tsotne Dadiani the Confessor": u"Άγιος Τσότνε Νταντιάνι ο ομολογητής",
    "St Razhden, Protomartyr of Georgia, and the Nine Kherkheulidze Brothers": u"Άγιος πρωτομάρτυς Ραζδέν και οι εννέα αδελφοί Χερχεουλίτζε",
    "Holy Confessors Ioane and Giorgi-Ioane of Betania": u"Άγιοι ομολογητές Ιωάννης και Γεώργιος-Ιωάννης της Μπετάνια",
    "Holy Great-martyr Queen Ketevan": u"Αγία μεγαλομάρτυς Κετεβάν η βασίλισσα",
    "Holy Martyrs Bidzina, Shalva and Elizbar": u"Άγιοι μάρτυρες Μπιτζίνας, Σάλβας και Ελισβάρ",
    "Venerable Grigol of Khandzta": u"Όσιος Γρηγόριος της Χάντζτα",
    "St Gabriel of Samtavro, Confessor and Fool for Christ": u"Όσιος Γαβριήλ της Σαμτάβρο, ομολογητής και διά Χριστόν σαλός",
    "The 100,000 Martyrs of Tbilisi": u"Οι 100.000 μάρτυρες της Τιφλίδας",
    "Holy King Vakhtang Gorgasali": u"Άγιος Βαχτάνγκ Γοργασάλης, βασιλεύς της Γεωργίας",
    "St Ise of Tsilkani": u"Άγιος Ιεσσαί του Τσίλκανι",
    "Synaxis of All Saints of Georgia": u"Σύναξις Πάντων των εν Γεωργία Αγίων",
    "Venerable Giorgi the Scribe and his brother Saba of Khakhuli": u"Όσιοι Γεώργιος ο Γραφεύς και ο αδελφός αυτού Σάββας του Χαχούλι",
    "St Nikephoros the Leper": u"Όσιος Νικηφόρος ο Λεπρός",
    "St Arsenios of Paros": u"Όσιος Αρσένιος ο εν Πάρω",
    "St Ephraim of Katounakia": u"Όσιος Εφραίμ ο Κατουνακιώτης",
    "St Nikolaos Planas of Athens": u"Δίκαιος Νικόλαος Πλανάς ο εν Αθήναις",
    "St Savvas the New of Kalymnos": u"Όσιος Σάββας ο Νέος ο εν Καλύμνω",
    "St Amphilochios of Patmos": u"Όσιος Αμφιλόχιος ο εν Πάτμω",
    "St Joseph the Hesychast": u"Όσιος Ιωσήφ ο Ησυχαστής",
    "St Kosmas Aitolos, Equal-to-the-Apostles": u"Άγιος Κοσμάς ο Αιτωλός, ισαπόστολος",
    "St Arsenios of Cappadocia": u"Όσιος Αρσένιος ο Καππαδόκης",
    "St Iakovos of Evia": u"Όσιος Ιάκωβος ο εν Ευβοία",
    "St Antipa of Calapodești": u"Όσιος Αντίπας ο εκ Καλαποδεστίου",
    "St Calinic of Cernica": u"Άγιος Καλλίνικος της Τσερνίκα",
    "St Pahomie of Gledin, Bishop of Roman": u"Άγιος Παχώμιος του Γκλεντίν, επίσκοπος Ρωμανίου",
    "Ss Ilie Iorest, Sava Brancovici and Simion Ștefan, Metropolitans of Transylvania": u"Άγιοι Ηλίας Ιορέστ, Σάββας Μπρανκόβιτς και Συμεών Στέφαν, μητροπολίτες Τρανσυλβανίας",
    "St Irodion of Lainici": u"Όσιος Ηρωδίων του Λαϊνίτσι",
    "St John the Wallachian, Martyr": u"Άγιος μάρτυς Ιωάννης ο Βλάχος",
    "St Iacob Putneanul, Metropolitan of Moldavia": u"Άγιος Ιάκωβος Πουτνεάνουλ, μητροπολίτης Μολδαβίας",
    "St Grigorie Dascălul, Metropolitan of Wallachia": u"Άγιος Γρηγόριος Δασκάλουλ, μητροπολίτης Ουγγροβλαχίας",
    "St Ghelasie of Râmeț": u"Άγιος Γελάσιος του Ραμέτς",
    "St Leontie of Rădăuți": u"Άγιος Λεόντιος του Ραντάουτσι",
    "St Stephen the Great": u"Άγιος Στέφανος ο Μέγας, ηγεμών Μολδαβίας",
    "St Ioanichie the New of Muscel": u"Όσιος Ιωαννίκιος ο Νέος του Μουσκέλ",
    "St Ioan Iacob of Neamț": u"Όσιος Ιωάννης Ιακώβ ο εκ Νεάμτς",
    "St Teodora of Sihla": u"Οσία Θεοδώρα της Σίχλα",
    "The Brâncoveanu Martyrs: Prince Constantin and his four sons": u"Οι μάρτυρες Μπρανκοβεάνου: ο ηγεμών Κωνσταντίνος και οι τέσσερις υιοί του",
    "St Iosif the New of Partoș, Metropolitan of Banat": u"Άγιος Ιωσήφ ο Νέος του Παρτός, μητροπολίτης Βανάτου",
    "St Neagoe Basarab, Voivode of Wallachia": u"Άγιος Νεάγκοε Μπασαράμπ, ηγεμών Ουγγροβλαχίας",
    "St Antim Ivireanul, Hieromartyr, Metropolitan of Wallachia": u"Ιερομάρτυς Άνθιμος ο Ίβηρ, μητροπολίτης Ουγγροβλαχίας",
    "St Parascheva of Iași": u"Οσία Παρασκευή η εν Ιασίω",
    "St Dimitrie the New of Bucharest": u"Όσιος Δημήτριος ο Νέος του Βουκουρεστίου",
    "St Iachint, Metropolitan of Wallachia": u"Άγιος Υάκινθος, μητροπολίτης Ουγγροβλαχίας",
    "St Andrei Șaguna, Metropolitan of Transylvania": u"Άγιος Ανδρέας Σαγκούνα, μητροπολίτης Τρανσυλβανίας",
    "St Gheorghe of Cernica": u"Όσιος Γεώργιος της Τσερνίκα",
    "St Dosoftei, Metropolitan of Moldavia": u"Άγιος Δοσίθεος, μητροπολίτης Μολδαβίας",
    "St Daniil the Hesychast": u"Όσιος Δανιήλ ο Ησυχαστής",
    "St Nicodim of Tismana": u"Όσιος Νικόδημος της Τισμάνα",
    "St Seraphim of Sarov": u"Όσιος Σεραφείμ του Σάρωφ",
    "St Theophan the Recluse": u"Άγιος Θεοφάνης ο Έγκλειστος",
    "St Xenia of St Petersburg": u"Αγία Ξένια της Πετρουπόλεως",
    "St Ignatius (Brianchaninov), Bishop of the Caucasus": u"Άγιος Ιγνάτιος Μπριαντσανίνωφ, επίσκοπος Καυκάσου",
    "St Vladimir, Equal-to-the-Apostles": u"Άγιος Βλαδίμηρος ο ισαπόστολος",
    "St Sergius of Radonezh": u"Όσιος Σέργιος του Ραντονέζ",
    "St Ambrose of Optina": u"Όσιος Αμβρόσιος της Όπτινα",
    "Synaxis of the Optina Elders": u"Σύναξις των Οσίων Γερόντων της Όπτινα",
    "St Sava, First Archbishop of Serbia": u"Άγιος Σάββας, πρώτος αρχιεπίσκοπος Σερβίας",
    "St Simeon the Myrrh-gusher": u"Όσιος Συμεών ο Μυροβλύτης",
    "St Basil of Ostrog": u"Άγιος Βασίλειος του Οστρόγου",
    "St Justin Popovich of Ćelije": u"Όσιος Ιουστίνος Πόποβιτς της Τσέλιε",
    "St Petar of Koriša": u"Όσιος Πέτρος της Κόριτσα",
    "Holy Great-martyr Tsar Lazar (Vidovdan)": u"Άγιος μεγαλομάρτυς Λάζαρος ο τσάρος (Βιντοβντάν)",
    "St Jefrem, Patriarch of Serbia": u"Άγιος Εφραίμ, πατριάρχης Σερβίας",
    "St Angelina of Serbia": u"Οσία Αγγελίνα της Σερβίας",
    "Synaxis of the Holy Hierarchs of Serbia": u"Σύναξις των Αγίων Ιεραρχών της Σερβίας",
    "The New Martyrs of Jasenovac": u"Οι νεομάρτυρες του Γιάσενοβατς",
    "St Stefan Vladislav, King of Serbia": u"Άγιος Στέφανος Βλαδισλάβος, βασιλεύς της Σερβίας",
    "St Petar of Cetinje, Wonderworker": u"Άγιος Πέτρος του Τσέτινιε, ο θαυματουργός",
    "St Prohor of Pčinja": u"Όσιος Πρόχορος της Πτσίνια",
    "St Milutin the King and St Jelena the Queen of Serbia": u"Άγιοι Μιλούτιν ο βασιλεύς και Ελένη η βασίλισσα της Σερβίας",
    "St Stefan Dečanski, King of Serbia": u"Άγιος Στέφανος Ντετσάνσκι, βασιλεύς της Σερβίας",
    "St Sebastian of Jackson": u"Όσιος Σεβαστιανός του Τζάκσον",
    "St Joanikije of Devič": u"Όσιος Ιωαννίκιος του Ντέβιτς",
    "St Danilo II, Archbishop of Serbia": u"Άγιος Δανιήλ Β', αρχιεπίσκοπος Σερβίας",
    "St Amphilochius of Pochaiv": u"Όσιος Αμφιλόχιος της Ποτσάεφ",
    "St Feodosii of the Kyiv Caves": u"Όσιος Θεοδόσιος της Λαύρας των Σπηλαίων του Κιέβου",
    "St Antonii of the Kyiv Caves": u"Όσιος Αντώνιος της Λαύρας των Σπηλαίων του Κιέβου",
    "St Olha, Equal-to-the-Apostles": u"Αγία Όλγα η ισαπόστολος",
    "St Volodymyr, Equal-to-the-Apostles": u"Άγιος Βλαδίμηρος ο ισαπόστολος",
    "St Petro Mohyla, Metropolitan of Kyiv": u"Άγιος Πέτρος Μογίλας, μητροπολίτης Κιέβου",
    "Synaxis of All Saints of Antioch": u"Σύναξις Πάντων των εν Αντιοχεία Αγίων",
    "Synaxis of All Bulgarian Saints": u"Σύναξις Πάντων των εν Βουλγαρία Αγίων",
    "Synaxis of All Saints of Mount Athos": u"Σύναξις Πάντων των Αγιορειτών Πατέρων",
    "Synaxis of All Saints of North America": u"Σύναξις Πάντων των εν Βορείω Αμερική Αγίων",
    "Synaxis of All Venerable Fathers of the Kyiv Caves": u"Σύναξις Πάντων των Οσίων Πατέρων της Λαύρας των Σπηλαίων του Κιέβου",
    "Synaxis of All Romanian Saints": u"Σύναξις Πάντων των εν Ρουμανία Αγίων",
    "Synaxis of All Saints of Russia": u"Σύναξις Πάντων των εν Ρωσία Αγίων",
    "Synaxis of All Saints of Ukraine": u"Σύναξις Πάντων των εν Ουκρανία Αγίων",
    "St Raphael, Bishop of Brooklyn": u"Άγιος Ραφαήλ, επίσκοπος Μπρούκλιν",
}
