# -*- coding: utf-8 -*-
"""The Churches' own commemorations, in Spanish.

See docs/LOCAL_NAMES.md.
"""
TEXT = {
    "St Isaac the Syrian": u"San Isaac el Sirio",
    "Martyr Elian of Homs": u"San Mártir Elián de Homs",
    "St Joseph of Damascus & the New Martyrs of Damascus (1860)": u"San Hieromártir José de Damasco y los Nuevos Mártires de Damasco (1860)",
    "Hieromartyrs Nicholas and Habib Khasha of Damascus": u"Santos Hieromártires Nicolás y Habib Khasha de Damasco",
    "St Gabriel of Lesnovo": u"San Gabriel de Lesnovo",
    "St Joachim I, Patriarch of Tarnovo": u"San Joaquín I, Patriarca de Tarnovo",
    "St Euthymius, Patriarch of Tarnovo": u"San Eutimio, Patriarca de Tarnovo",
    "St Peter, King of Bulgaria": u"San Pedro, Zar de Bulgaria",
    "St Romanus of Tarnovo": u"San Román de Tarnovo",
    "St Sophronius, Bishop of Vratsa": u"San Sofronio, Obispo de Vratsa",
    "St Boris-Michael, Equal-to-the-Apostles, Baptizer of Bulgaria": u"San Boris-Miguel, Igual a los Apóstoles, Bautizador de Bulgaria",
    "Great Martyr Nicholas of Sofia": u"San Gran Mártir Nicolás de Sofía",
    "St Paisius of Hilendar": u"San Paisio de Hilandar",
    "The Seven Holy Apostles (Sedmochislenitsi)": u"Los Siete Santos Apóstoles (Sedmochislenitsi)",
    "St Joachim of Osogovo": u"San Joaquín de Osogovo",
    "Repose of St John of Rila": u"Dormición de san Juan de Rila",
    "New Martyr Simeon of Samokov": u"Nuevo Mártir Simeón de Samokov",
    "St Cosmas of Zographou": u"San Cosme de Zografou",
    "The 26 Martyrs of Zographou": u"Los 26 Mártires de Zografou",
    "St Demetrius of Basarbovo": u"San Demetrio de Basarabovo",
    "Venerable Pimen of Zographou": u"San Pimen de Zografou",
    "Righteous Michael the Soldier of Bulgaria": u"Justo Miguel el Soldado de Bulgaria",
    "St Theodosius of Tarnovo": u"San Teodosio de Tarnovo",
    "St Nektarios the Bulgarian of Bitola": u"San Mártir Nectario de Bitola",
    "St Nahum of Ohrid": u"San Naúm de Ohrid",
    "Ss Salome of Ujarma and Perozhavra of Sivnia": u"Justas Salomé de Ujarma y Perozhavra de Sivnia",
    "St Eprem the Lesser, the Philosopher": u"San Efrén el Menor, el Filósofo",
    "St David IV the Builder, King of Georgia": u"Santo Rey David IV el Constructor de Georgia",
    "St Ioane the Catholicos": u"San Ioane, Catolicós de Georgia",
    "Holy King Demetre the Devoted": u"Santo Rey Demetre el Abnegado",
    "St Ambrosi the Confessor, Catholicos-Patriarch of All Georgia": u"San Ambrosi el Confesor, Catolicós-Patriarca de toda Georgia",
    "Venerable David of the Gareji Monastery": u"San David del Monasterio de Gareji",
    "St Tamar, Queen of Georgia": u"Santa Tamar, Reina de Georgia",
    "Venerable Ioane of Zedazeni and his Twelve Disciples": u"San Ioane de Zedazeni y sus doce discípulos",
    "Venerable Ekvtime of Mount Athos, the Translator": u"San Ekvtime del Monte Athos, el Traductor",
    "St George the Hagiorite, and Hieromartyr Kirion II, Catholicos-Patriarch": u"San Jorge el Hagiorita y el Hieromártir Kirion II, Catolicós-Patriarca",
    "St Ilia the Righteous": u"Justo Ilia",
    "Holy Martyr Evstati of Mtskheta": u"San Mártir Evstati de Mtsjeta",
    "St Tsotne Dadiani the Confessor": u"San Tsotne Dadiani el Confesor",
    "St Razhden, Protomartyr of Georgia, and the Nine Kherkheulidze Brothers": u"San Protomártir Razhden de Georgia y los nueve hermanos Kherkheulidze",
    "Holy Confessors Ioane and Giorgi-Ioane of Betania": u"Santos Confesores Ioane y Giorgi-Ioane de Betania",
    "Holy Great-martyr Queen Ketevan": u"Santa Gran Mártir Reina Ketevan",
    "Holy Martyrs Bidzina, Shalva and Elizbar": u"Santos Mártires Bidzina, Shalva y Elizbar",
    "Venerable Grigol of Khandzta": u"San Grigol de Khandzta",
    "St Gabriel of Samtavro, Confessor and Fool for Christ": u"San Gabriel de Samtavro, Confesor y Loco por Cristo",
    "The 100,000 Martyrs of Tbilisi": u"Los 100.000 Mártires de Tiflis",
    "Holy King Vakhtang Gorgasali": u"Santo Rey Vajtang Gorgasali",
    "St Ise of Tsilkani": u"San Ise de Tsilkani",
    "Synaxis of All Saints of Georgia": u"Sínaxis de todos los Santos de Georgia",
    "Venerable Giorgi the Scribe and his brother Saba of Khakhuli": u"Santos Giorgi el Escriba y su hermano Saba de Khakhuli",
    "St Nikephoros the Leper": u"San Nicéforo el Leproso",
    "St Arsenios of Paros": u"San Arsenio de Paros",
    "St Ephraim of Katounakia": u"San Efrén de Katounakia",
    "St Nikolaos Planas of Athens": u"Justo Nicolás Planas de Atenas",
    "St Savvas the New of Kalymnos": u"San Sava el Nuevo de Kálimnos",
    "St Amphilochios of Patmos": u"San Anfiloquio de Patmos",
    "St Joseph the Hesychast": u"San José el Hesicasta",
    "St Kosmas Aitolos, Equal-to-the-Apostles": u"San Cosme de Etolia, Igual a los Apóstoles",
    "St Arsenios of Cappadocia": u"San Arsenio de Capadocia",
    "St Iakovos of Evia": u"San Jacobo de Evia",
    "St Antipa of Calapodești": u"San Antipa de Calapodesti",
    "St Calinic of Cernica": u"San Calínico de Cernica",
    "St Pahomie of Gledin, Bishop of Roman": u"San Pahomie de Gledin, Obispo de Roman",
    "Ss Ilie Iorest, Sava Brancovici and Simion Ștefan, Metropolitans of Transylvania": u"Santos Ilie Iorest, Sava Brancovici y Simion Stefan, Metropolitanos de Transilvania",
    "St Irodion of Lainici": u"San Irodion de Lainici",
    "St John the Wallachian, Martyr": u"San Mártir Juan el Valaco",
    "St Iacob Putneanul, Metropolitan of Moldavia": u"San Iacob Putneanul, Metropolitano de Moldavia",
    "St Grigorie Dascălul, Metropolitan of Wallachia": u"San Grigorie Dascalul, Metropolitano de Valaquia",
    "St Ghelasie of Râmeț": u"San Ghelasie de Ramet",
    "St Leontie of Rădăuți": u"San Leontie de Radauti",
    "St Stephen the Great": u"San Esteban el Grande",
    "St Ioanichie the New of Muscel": u"San Ioanichie el Nuevo de Muscel",
    "St Ioan Iacob of Neamț": u"San Ioan Iacob de Neamt",
    "St Teodora of Sihla": u"Santa Teodora de Sihla",
    "The Brâncoveanu Martyrs: Prince Constantin and his four sons": u"Los Mártires Brancoveanu: el príncipe Constantin y sus cuatro hijos",
    "St Iosif the New of Partoș, Metropolitan of Banat": u"San Iosif el Nuevo de Partos, Metropolitano del Banato",
    "St Neagoe Basarab, Voivode of Wallachia": u"San Neagoe Basarab, Voivoda de Valaquia",
    "St Antim Ivireanul, Hieromartyr, Metropolitan of Wallachia": u"San Hieromártir Antim Ivireanul, Metropolitano de Valaquia",
    "St Parascheva of Iași": u"Santa Parascheva de Iasi",
    "St Dimitrie the New of Bucharest": u"San Demetrio el Nuevo de Bucarest",
    "St Iachint, Metropolitan of Wallachia": u"San Iachint, Metropolitano de Valaquia",
    "St Andrei Șaguna, Metropolitan of Transylvania": u"San Andrei Saguna, Metropolitano de Transilvania",
    "St Gheorghe of Cernica": u"San Gheorghe de Cernica",
    "St Dosoftei, Metropolitan of Moldavia": u"San Dosoftei, Metropolitano de Moldavia",
    "St Daniil the Hesychast": u"San Daniil el Hesicasta",
    "St Nicodim of Tismana": u"San Nicodim de Tismana",
    "St Seraphim of Sarov": u"San Serafín de Sarov",
    "St Theophan the Recluse": u"San Teofano el Recluso",
    "St Xenia of St Petersburg": u"Santa Xenia de San Petersburgo",
    "St Ignatius (Brianchaninov), Bishop of the Caucasus": u"San Ignacio (Brianchaninov), Obispo del Cáucaso",
    "St Vladimir, Equal-to-the-Apostles": u"San Vladimiro, Igual a los Apóstoles",
    "St Sergius of Radonezh": u"San Sergio de Rádonezh",
    "St Ambrose of Optina": u"San Ambrosio de Optina",
    "Synaxis of the Optina Elders": u"Sínaxis de los Ancianos de Optina",
    "St Sava, First Archbishop of Serbia": u"San Sava, Primer Arzobispo de Serbia",
    "St Simeon the Myrrh-gusher": u"San Simeón el Mirovlita",
    "St Basil of Ostrog": u"San Basilio de Ostrog",
    "St Justin Popovich of Ćelije": u"San Justino Popovic de Celije",
    "St Petar of Koriša": u"San Pedro de Korisa",
    "Holy Great-martyr Tsar Lazar (Vidovdan)": u"San Gran Mártir Príncipe Lázaro (Vidovdan)",
    "St Jefrem, Patriarch of Serbia": u"San Jefrem, Patriarca de Serbia",
    "St Angelina of Serbia": u"Santa Angelina de Serbia",
    "Synaxis of the Holy Hierarchs of Serbia": u"Sínaxis de los Santos Jerarcas de Serbia",
    "The New Martyrs of Jasenovac": u"Los Nuevos Mártires de Jasenovac",
    "St Stefan Vladislav, King of Serbia": u"Santo Rey Stefan Vladislav de Serbia",
    "St Petar of Cetinje, Wonderworker": u"San Petar de Cetinje, el Taumaturgo",
    "St Prohor of Pčinja": u"San Prohor de Pcinja",
    "St Milutin the King and St Jelena the Queen of Serbia": u"Santo Rey Milutin y Santa Reina Jelena de Serbia",
    "St Stefan Dečanski, King of Serbia": u"Santo Rey Stefan Decanski de Serbia",
    "St Sebastian of Jackson": u"San Sebastián de Jackson",
    "St Joanikije of Devič": u"San Joanikije de Devic",
    "St Danilo II, Archbishop of Serbia": u"San Danilo II, Arzobispo de Serbia",
    "St Amphilochius of Pochaiv": u"San Anfiloquio de Pochaiv",
    "St Feodosii of the Kyiv Caves": u"San Teodosio de las Cuevas de Kyiv",
    "St Antonii of the Kyiv Caves": u"San Antonio de las Cuevas de Kyiv",
    "St Olha, Equal-to-the-Apostles": u"Santa Olha, Igual a los Apóstoles",
    "St Volodymyr, Equal-to-the-Apostles": u"San Volodymyr, Igual a los Apóstoles",
    "St Petro Mohyla, Metropolitan of Kyiv": u"San Petro Mohyla, Metropolitano de Kyiv",
    "Synaxis of All Saints of Antioch": u"Sínaxis de todos los Santos de Antioquía",
    "Synaxis of All Bulgarian Saints": u"Sínaxis de todos los Santos de Bulgaria",
    "Synaxis of All Saints of Mount Athos": u"Sínaxis de todos los Santos del Monte Athos",
    "Synaxis of All Saints of North America": u"Sínaxis de todos los Santos de América del Norte",
    "Synaxis of All Venerable Fathers of the Kyiv Caves": u"Sínaxis de todos los Padres de las Cuevas de Kyiv",
    "Synaxis of All Romanian Saints": u"Sínaxis de todos los Santos de Rumanía",
    "Synaxis of All Saints of Russia": u"Sínaxis de todos los Santos de Rusia",
    "Synaxis of All Saints of Ukraine": u"Sínaxis de todos los Santos de Ucrania",
    "St Raphael, Bishop of Brooklyn": u"San Rafael, Obispo de Brooklyn",
}
