# -*- coding: utf-8 -*-
"""The Churches' own commemorations, in French.

See docs/LOCAL_NAMES.md.
"""
TEXT = {
    "St Isaac the Syrian": u"Le vénérable Isaac le Syrien",
    "Martyr Elian of Homs": u"Saint Élian de Homs, martyr",
    "St Joseph of Damascus & the New Martyrs of Damascus (1860)": u"Saint hiéromartyr Joseph de Damas et les nouveaux martyrs de Damas (1860)",
    "Hieromartyrs Nicholas and Habib Khasha of Damascus": u"Saints hiéromartyrs Nicolas et Habib Khasha de Damas",
    "St Gabriel of Lesnovo": u"Le vénérable Gabriel de Lesnovo",
    "St Joachim I, Patriarch of Tarnovo": u"Saint Joachim Ier, patriarche de Tarnovo",
    "St Euthymius, Patriarch of Tarnovo": u"Saint Euthyme, patriarche de Tarnovo",
    "St Peter, King of Bulgaria": u"Saint Pierre, tsar de Bulgarie",
    "St Romanus of Tarnovo": u"Le vénérable Romain de Tarnovo",
    "St Sophronius, Bishop of Vratsa": u"Saint Sophrone, évêque de Vratsa",
    "St Boris-Michael, Equal-to-the-Apostles, Baptizer of Bulgaria": u"Saint Boris-Michel, égal aux apôtres, baptiseur de la Bulgarie",
    "Great Martyr Nicholas of Sofia": u"Saint grand-martyr Nicolas de Sofia",
    "St Paisius of Hilendar": u"Le vénérable Païssios de Hilandar",
    "The Seven Holy Apostles (Sedmochislenitsi)": u"Les sept saints apôtres (Sedmotchislenitsi)",
    "St Joachim of Osogovo": u"Le vénérable Joachim d'Osogovo",
    "Repose of St John of Rila": u"Dormition du vénérable Jean de Rila",
    "New Martyr Simeon of Samokov": u"Saint nouveau martyr Siméon de Samokov",
    "St Cosmas of Zographou": u"Le vénérable Cosmas de Zographou",
    "The 26 Martyrs of Zographou": u"Les 26 martyrs de Zographou",
    "St Demetrius of Basarbovo": u"Le vénérable Dimitri de Basarbovo",
    "Venerable Pimen of Zographou": u"Le vénérable Pimen de Zographou",
    "Righteous Michael the Soldier of Bulgaria": u"Le juste Michel le soldat de Bulgarie",
    "St Theodosius of Tarnovo": u"Le vénérable Théodose de Tarnovo",
    "St Nektarios the Bulgarian of Bitola": u"Le vénérable martyr Nectaire de Bitola",
    "St Nahum of Ohrid": u"Le vénérable Naum d'Ohrid",
    "Ss Salome of Ujarma and Perozhavra of Sivnia": u"Les justes Salomé d'Oudjarma et Perojavra de Sivnia",
    "St Eprem the Lesser, the Philosopher": u"Le vénérable Éprem le Mineur, le philosophe",
    "St David IV the Builder, King of Georgia": u"Saint David IV le Bâtisseur, roi de Géorgie",
    "St Ioane the Catholicos": u"Saint Ioané, catholicos de Géorgie",
    "Holy King Demetre the Devoted": u"Saint Démétré le Dévoué, roi de Géorgie",
    "St Ambrosi the Confessor, Catholicos-Patriarch of All Georgia": u"Saint Ambrosi le confesseur, catholicos-patriarche de toute la Géorgie",
    "Venerable David of the Gareji Monastery": u"Le vénérable David de Garedja",
    "St Tamar, Queen of Georgia": u"Sainte Thamar, reine de Géorgie",
    "Venerable Ioane of Zedazeni and his Twelve Disciples": u"Le vénérable Ioané de Zedazeni et ses douze disciples",
    "Venerable Ekvtime of Mount Athos, the Translator": u"Le vénérable Ekvtimé du Mont Athos, le traducteur",
    "St George the Hagiorite, and Hieromartyr Kirion II, Catholicos-Patriarch": u"Le vénérable Georges l'Hagiorite et le hiéromartyr Kirion II, catholicos-patriarche",
    "St Ilia the Righteous": u"Le juste Ilia",
    "Holy Martyr Evstati of Mtskheta": u"Saint Evstati de Mtskheta, martyr",
    "St Tsotne Dadiani the Confessor": u"Saint Tsotné Dadiani le confesseur",
    "St Razhden, Protomartyr of Georgia, and the Nine Kherkheulidze Brothers": u"Saint Rajden, protomartyr de Géorgie, et les neuf frères Kherkheulidzé",
    "Holy Confessors Ioane and Giorgi-Ioane of Betania": u"Saints confesseurs Ioané et Giorgi-Ioané de Bétania",
    "Holy Great-martyr Queen Ketevan": u"Sainte grande-martyre la reine Kétévan",
    "Holy Martyrs Bidzina, Shalva and Elizbar": u"Saints martyrs Bidzina, Chalva et Élizbar",
    "Venerable Grigol of Khandzta": u"Le vénérable Grigol de Khandzta",
    "St Gabriel of Samtavro, Confessor and Fool for Christ": u"Le vénérable Gabriel de Samtavro, confesseur et fol-en-Christ",
    "The 100,000 Martyrs of Tbilisi": u"Les 100 000 martyrs de Tbilissi",
    "Holy King Vakhtang Gorgasali": u"Saint Vakhtang Gorgasali, roi de Géorgie",
    "St Ise of Tsilkani": u"Saint Isé de Tsilkani",
    "Synaxis of All Saints of Georgia": u"Synaxe de tous les saints de Géorgie",
    "Venerable Giorgi the Scribe and his brother Saba of Khakhuli": u"Les vénérables Giorgi le Scribe et son frère Saba de Khakhouli",
    "St Nikephoros the Leper": u"Le vénérable Nicéphore le Lépreux",
    "St Arsenios of Paros": u"Le vénérable Arsène de Paros",
    "St Ephraim of Katounakia": u"Le vénérable Éphrem de Katounakia",
    "St Nikolaos Planas of Athens": u"Le juste Nicolas Planas d'Athènes",
    "St Savvas the New of Kalymnos": u"Le vénérable Savvas le Nouveau de Kalymnos",
    "St Amphilochios of Patmos": u"Le vénérable Amphiloque de Patmos",
    "St Joseph the Hesychast": u"Le vénérable Joseph l'Hésychaste",
    "St Kosmas Aitolos, Equal-to-the-Apostles": u"Saint Cosmas l'Étolien, égal aux apôtres",
    "St Arsenios of Cappadocia": u"Le vénérable Arsène de Cappadoce",
    "St Iakovos of Evia": u"Le vénérable Jacques d'Eubée",
    "St Antipa of Calapodești": u"Le vénérable Antipa de Calapodesti",
    "St Calinic of Cernica": u"Saint Calinic de Cernica",
    "St Pahomie of Gledin, Bishop of Roman": u"Saint Pahomie de Gledin, évêque de Roman",
    "Ss Ilie Iorest, Sava Brancovici and Simion Ștefan, Metropolitans of Transylvania": u"Saints Ilie Iorest, Sava Brancovici et Simion Stefan, métropolites de Transylvanie",
    "St Irodion of Lainici": u"Le vénérable Irodion de Lainici",
    "St John the Wallachian, Martyr": u"Saint Jean le Valaque, martyr",
    "St Iacob Putneanul, Metropolitan of Moldavia": u"Saint Iacob Putneanul, métropolite de Moldavie",
    "St Grigorie Dascălul, Metropolitan of Wallachia": u"Saint Grigorie Dascalul, métropolite de Valachie",
    "St Ghelasie of Râmeț": u"Saint Ghelasie de Ramet",
    "St Leontie of Rădăuți": u"Saint Leontie de Radauti",
    "St Stephen the Great": u"Saint Étienne le Grand",
    "St Ioanichie the New of Muscel": u"Le vénérable Ioanichie le Nouveau de Muscel",
    "St Ioan Iacob of Neamț": u"Le vénérable Ioan Iacob de Neamt",
    "St Teodora of Sihla": u"La vénérable Théodora de Sihla",
    "The Brâncoveanu Martyrs: Prince Constantin and his four sons": u"Les martyrs Brancoveanu: le prince Constantin et ses quatre fils",
    "St Iosif the New of Partoș, Metropolitan of Banat": u"Saint Iosif le Nouveau de Partos, métropolite du Banat",
    "St Neagoe Basarab, Voivode of Wallachia": u"Saint Neagoe Basarab, prince de Valachie",
    "St Antim Ivireanul, Hieromartyr, Metropolitan of Wallachia": u"Saint hiéromartyr Antim Ivireanul, métropolite de Valachie",
    "St Parascheva of Iași": u"La vénérable Parascève de Iasi",
    "St Dimitrie the New of Bucharest": u"Le vénérable Dimitri le Nouveau de Bucarest",
    "St Iachint, Metropolitan of Wallachia": u"Saint Iachint, métropolite de Valachie",
    "St Andrei Șaguna, Metropolitan of Transylvania": u"Saint Andrei Saguna, métropolite de Transylvanie",
    "St Gheorghe of Cernica": u"Le vénérable Gheorghe de Cernica",
    "St Dosoftei, Metropolitan of Moldavia": u"Saint Dosoftei, métropolite de Moldavie",
    "St Daniil the Hesychast": u"Le vénérable Daniil l'Hésychaste",
    "St Nicodim of Tismana": u"Le vénérable Nicodème de Tismana",
    "St Seraphim of Sarov": u"Le vénérable Séraphin de Sarov",
    "St Theophan the Recluse": u"Saint Théophane le Reclus",
    "St Xenia of St Petersburg": u"Sainte Xénia de Saint-Pétersbourg",
    "St Ignatius (Brianchaninov), Bishop of the Caucasus": u"Saint Ignace (Briantchaninov), évêque du Caucase",
    "St Vladimir, Equal-to-the-Apostles": u"Saint Vladimir, égal aux apôtres",
    "St Sergius of Radonezh": u"Le vénérable Serge de Radonège",
    "St Ambrose of Optina": u"Le vénérable Ambroise d'Optina",
    "Synaxis of the Optina Elders": u"Synaxe des startsy d'Optina",
    "St Sava, First Archbishop of Serbia": u"Saint Sava, premier archevêque de Serbie",
    "St Simeon the Myrrh-gusher": u"Le vénérable Siméon le myroblyte",
    "St Basil of Ostrog": u"Saint Basile d'Ostrog",
    "St Justin Popovich of Ćelije": u"Le vénérable Justin Popovitch de Tchélié",
    "St Petar of Koriša": u"Le vénérable Pierre de Koricha",
    "Holy Great-martyr Tsar Lazar (Vidovdan)": u"Saint grand-martyr tsar Lazar (Vidovdan)",
    "St Jefrem, Patriarch of Serbia": u"Saint Jefrem, patriarche de Serbie",
    "St Angelina of Serbia": u"La vénérable Angéline de Serbie",
    "Synaxis of the Holy Hierarchs of Serbia": u"Synaxe des saints hiérarques de Serbie",
    "The New Martyrs of Jasenovac": u"Les nouveaux martyrs de Jasenovac",
    "St Stefan Vladislav, King of Serbia": u"Saint Stefan Vladislav, roi de Serbie",
    "St Petar of Cetinje, Wonderworker": u"Saint Petar de Cetinje, le thaumaturge",
    "St Prohor of Pčinja": u"Le vénérable Prohor de Pcinja",
    "St Milutin the King and St Jelena the Queen of Serbia": u"Saint Milutin le roi et sainte Jelena la reine de Serbie",
    "St Stefan Dečanski, King of Serbia": u"Saint Stefan Decanski, roi de Serbie",
    "St Sebastian of Jackson": u"Le vénérable Sébastien de Jackson",
    "St Joanikije of Devič": u"Le vénérable Joanikije de Devic",
    "St Danilo II, Archbishop of Serbia": u"Saint Danilo II, archevêque de Serbie",
    "St Amphilochius of Pochaiv": u"Le vénérable Amphiloque de Potchaïv",
    "St Feodosii of the Kyiv Caves": u"Le vénérable Théodose des Grottes de Kyiv",
    "St Antonii of the Kyiv Caves": u"Le vénérable Antoine des Grottes de Kyiv",
    "St Olha, Equal-to-the-Apostles": u"Sainte Olha, égale aux apôtres",
    "St Volodymyr, Equal-to-the-Apostles": u"Saint Volodymyr, égal aux apôtres",
    "St Petro Mohyla, Metropolitan of Kyiv": u"Saint Petro Mohyla, métropolite de Kyiv",
    "Synaxis of All Saints of Antioch": u"Synaxe de tous les saints d'Antioche",
    "Synaxis of All Bulgarian Saints": u"Synaxe de tous les saints de Bulgarie",
    "Synaxis of All Saints of Mount Athos": u"Synaxe de tous les saints du Mont Athos",
    "Synaxis of All Saints of North America": u"Synaxe de tous les saints d'Amérique du Nord",
    "Synaxis of All Venerable Fathers of the Kyiv Caves": u"Synaxe de tous les vénérables pères des Grottes de Kyiv",
    "Synaxis of All Romanian Saints": u"Synaxe de tous les saints de Roumanie",
    "Synaxis of All Saints of Russia": u"Synaxe de tous les saints de Russie",
    "Synaxis of All Saints of Ukraine": u"Synaxe de tous les saints d'Ukraine",
    "St Raphael, Bishop of Brooklyn": u"Saint Raphaël, évêque de Brooklyn",
}
