# -*- coding: utf-8 -*-
"""The Churches' own commemorations, in Hindi.

See docs/LOCAL_NAMES.md.
"""
TEXT = {
    "St Isaac the Syrian": u"सीरिया के आदरणीय इसहाक",
    "Martyr Elian of Homs": u"होम्स के शहीद एलियान",
    "St Joseph of Damascus & the New Martyrs of Damascus (1860)": u"दमिश्क के पुरोहित-शहीद यूसुफ और दमिश्क के नव शहीद (1860)",
    "Hieromartyrs Nicholas and Habib Khasha of Damascus": u"दमिश्क के पुरोहित-शहीद निकोलस और हबीब खाशा",
    "St Gabriel of Lesnovo": u"लेस्नोवो के आदरणीय गब्रिएल",
    "St Joachim I, Patriarch of Tarnovo": u"तरनोवो के कुलपति संत योआकिम प्रथम",
    "St Euthymius, Patriarch of Tarnovo": u"तरनोवो के कुलपति संत यूथिमियुस",
    "St Peter, King of Bulgaria": u"बुल्गारिया के राजा संत पीटर",
    "St Romanus of Tarnovo": u"तरनोवो के आदरणीय रोमानुस",
    "St Sophronius, Bishop of Vratsa": u"व्रात्सा के बिशप संत सोफ्रोनियुस",
    "St Boris-Michael, Equal-to-the-Apostles, Baptizer of Bulgaria": u"बुल्गारिया के बपतिस्मादाता संत बोरिस-मिखाइल, प्रेरितों के समतुल्य",
    "Great Martyr Nicholas of Sofia": u"सोफिया के महान शहीद निकोलस",
    "St Paisius of Hilendar": u"हिलंदार के आदरणीय पाइसियुस",
    "The Seven Holy Apostles (Sedmochislenitsi)": u"सात पवित्र प्रेरित (सेदमोचिस्लेनित्सी)",
    "St Joachim of Osogovo": u"ओसोगोवो के आदरणीय योआकिम",
    "Repose of St John of Rila": u"रिला के आदरणीय यूहन्ना का विश्राम",
    "New Martyr Simeon of Samokov": u"समोकोव के नव शहीद शिमोन",
    "St Cosmas of Zographou": u"ज़ोग्राफू के आदरणीय कोस्मास",
    "The 26 Martyrs of Zographou": u"ज़ोग्राफू के छब्बीस शहीद",
    "St Demetrius of Basarbovo": u"बसाराबोवो के आदरणीय दिमित्रियुस",
    "Venerable Pimen of Zographou": u"ज़ोग्राफू के आदरणीय पिमेन",
    "Righteous Michael the Soldier of Bulgaria": u"बुल्गारिया के धर्मी सैनिक मिखाइल",
    "St Theodosius of Tarnovo": u"तरनोवो के आदरणीय थियोदोसियुस",
    "St Nektarios the Bulgarian of Bitola": u"बितोला के आदरणीय शहीद नेक्तारियुस",
    "St Nahum of Ohrid": u"ओहरिद के आदरणीय नाहूम",
    "Ss Salome of Ujarma and Perozhavra of Sivnia": u"उजार्मा की धर्मी सलोमी और सिव्निया की पेरोजाव्रा",
    "St Eprem the Lesser, the Philosopher": u"आदरणीय एप्रेम लघु, दार्शनिक",
    "St David IV the Builder, King of Georgia": u"जॉर्जिया के राजा संत दाऊद चतुर्थ निर्माता",
    "St Ioane the Catholicos": u"जॉर्जिया के काथोलिकोस संत योआने",
    "Holy King Demetre the Devoted": u"जॉर्जिया के राजा संत देमेत्रे आत्मबलिदानी",
    "St Ambrosi the Confessor, Catholicos-Patriarch of All Georgia": u"समस्त जॉर्जिया के काथोलिकोस-कुलपति स्वीकारकर्ता संत अम्ब्रोसी",
    "Venerable David of the Gareji Monastery": u"गारेजी के आदरणीय दाऊद",
    "St Tamar, Queen of Georgia": u"जॉर्जिया की रानी संत तामार",
    "Venerable Ioane of Zedazeni and his Twelve Disciples": u"ज़ेदाज़ेनी के आदरणीय योआने और उनके बारह शिष्य",
    "Venerable Ekvtime of Mount Athos, the Translator": u"आथोस पर्वत के आदरणीय एक्वतिमे, अनुवादक",
    "St George the Hagiorite, and Hieromartyr Kirion II, Catholicos-Patriarch": u"आथोस पर्वत के आदरणीय गिओर्गी और पुरोहित-शहीद किरिओन द्वितीय, काथोलिकोस-कुलपति",
    "St Ilia the Righteous": u"धर्मी संत इलिया",
    "Holy Martyr Evstati of Mtskheta": u"म्त्सखेता के शहीद एव्स्ताती",
    "St Tsotne Dadiani the Confessor": u"स्वीकारकर्ता संत त्सोत्ने दादियानी",
    "St Razhden, Protomartyr of Georgia, and the Nine Kherkheulidze Brothers": u"जॉर्जिया के प्रथम शहीद रज्देन और खेरखेउलिद्ज़े के नौ भाई",
    "Holy Confessors Ioane and Giorgi-Ioane of Betania": u"बेतानिया के स्वीकारकर्ता संत योआने और गिओर्गी-योआने",
    "Holy Great-martyr Queen Ketevan": u"महान शहीद रानी केतेवान",
    "Holy Martyrs Bidzina, Shalva and Elizbar": u"शहीद बिद्ज़िना, शाल्वा और एलिज़बार",
    "Venerable Grigol of Khandzta": u"खान्द्ज़्ता के आदरणीय ग्रिगोल",
    "St Gabriel of Samtavro, Confessor and Fool for Christ": u"सम्तावरो के आदरणीय गब्रिएल, स्वीकारकर्ता और मसीह के लिए मूर्ख",
    "The 100,000 Martyrs of Tbilisi": u"त्बिलिसी के एक लाख शहीद",
    "Holy King Vakhtang Gorgasali": u"जॉर्जिया के राजा संत वख्तांग गोर्गासाली",
    "St Ise of Tsilkani": u"त्सिल्कानी के संत इसे",
    "Synaxis of All Saints of Georgia": u"जॉर्जिया के सभी संत",
    "Venerable Giorgi the Scribe and his brother Saba of Khakhuli": u"खाखुली के आदरणीय लेखक गिओर्गी और उनके भाई साबा",
    "St Nikephoros the Leper": u"आदरणीय कुष्ठरोगी निकिफोरोस",
    "St Arsenios of Paros": u"पारोस के आदरणीय अर्सेनियुस",
    "St Ephraim of Katounakia": u"कातूनाकिया के आदरणीय एप्रेम",
    "St Nikolaos Planas of Athens": u"एथेंस के धर्मी निकोलस प्लानास",
    "St Savvas the New of Kalymnos": u"कालिम्नोस के आदरणीय नवीन सावा",
    "St Amphilochios of Patmos": u"पात्मोस के आदरणीय अम्फिलोखियुस",
    "St Joseph the Hesychast": u"आदरणीय मौनसाधक यूसुफ",
    "St Kosmas Aitolos, Equal-to-the-Apostles": u"एतोलिया के संत कोस्मास, प्रेरितों के समतुल्य",
    "St Arsenios of Cappadocia": u"कप्पदूकिया के आदरणीय अर्सेनियुस",
    "St Iakovos of Evia": u"एविया के आदरणीय याकोवोस",
    "St Antipa of Calapodești": u"कालापोदेश्ती के आदरणीय अंतिपा",
    "St Calinic of Cernica": u"चेर्निका के संत कालिनिक",
    "St Pahomie of Gledin, Bishop of Roman": u"ग्लेदिन के संत पाहोमिए, रोमान के बिशप",
    "Ss Ilie Iorest, Sava Brancovici and Simion Ștefan, Metropolitans of Transylvania": u"त्रांसिल्वानिया के महानगराध्यक्ष संत इलिए योरेस्त, सावा ब्रांकोविची और सिमिओन श्तेफान",
    "St Irodion of Lainici": u"लाइनिची के आदरणीय इरोदिओन",
    "St John the Wallachian, Martyr": u"शहीद यूहन्ना वलाखी",
    "St Iacob Putneanul, Metropolitan of Moldavia": u"मोल्दाविया के महानगराध्यक्ष संत याकोब पुत्नेआनुल",
    "St Grigorie Dascălul, Metropolitan of Wallachia": u"वलाखिया के महानगराध्यक्ष संत ग्रिगोरिए दास्कालुल",
    "St Ghelasie of Râmeț": u"रिमेत्स के संत घेलासिए",
    "St Leontie of Rădăuți": u"रादाउत्सी के संत लेओन्तिए",
    "St Stephen the Great": u"संत महान स्तेफन",
    "St Ioanichie the New of Muscel": u"मुश्चेल के आदरणीय नवीन योआनिकिए",
    "St Ioan Iacob of Neamț": u"न्यामत्स के आदरणीय योआन याकोब",
    "St Teodora of Sihla": u"सिहला की आदरणीय थेओदोरा",
    "The Brâncoveanu Martyrs: Prince Constantin and his four sons": u"ब्रिन्कोवेआनु के शहीद: राजकुमार कोन्स्तान्तिन और उनके चार पुत्र",
    "St Iosif the New of Partoș, Metropolitan of Banat": u"बानात के महानगराध्यक्ष, पार्तोश के संत नवीन योसिफ",
    "St Neagoe Basarab, Voivode of Wallachia": u"वलाखिया के शासक संत न्यागोए बसाराब",
    "St Antim Ivireanul, Hieromartyr, Metropolitan of Wallachia": u"वलाखिया के महानगराध्यक्ष, पुरोहित-शहीद अंतिम इविरेआनुल",
    "St Parascheva of Iași": u"इयासी की आदरणीय पारास्केवा",
    "St Dimitrie the New of Bucharest": u"बुखारेस्त के संत नवीन दिमित्रिए",
    "St Iachint, Metropolitan of Wallachia": u"वलाखिया के महानगराध्यक्ष संत याकिन्त",
    "St Andrei Șaguna, Metropolitan of Transylvania": u"त्रांसिल्वानिया के महानगराध्यक्ष संत आंद्रेई शागुना",
    "St Gheorghe of Cernica": u"चेर्निका के आदरणीय घेओर्घे",
    "St Dosoftei, Metropolitan of Moldavia": u"मोल्दाविया के महानगराध्यक्ष संत दोसोफ्तेई",
    "St Daniil the Hesychast": u"आदरणीय मौनसाधक दानिइल",
    "St Nicodim of Tismana": u"तिस्माना के आदरणीय निकोदिम",
    "St Seraphim of Sarov": u"सरोव के संत सेराफिम",
    "St Theophan the Recluse": u"संत एकांतवासी थियोफान",
    "St Xenia of St Petersburg": u"सेंट पीटर्सबर्ग की संत ज़ेनिया",
    "St Ignatius (Brianchaninov), Bishop of the Caucasus": u"काकेशस के बिशप संत इग्नातियुस (ब्रियानचानिनोव)",
    "St Vladimir, Equal-to-the-Apostles": u"संत व्लादिमीर, प्रेरितों के समतुल्य",
    "St Sergius of Radonezh": u"रादोनेज के संत सर्गियुस",
    "St Ambrose of Optina": u"ओप्तिना के आदरणीय अम्ब्रोसियुस",
    "Synaxis of the Optina Elders": u"ओप्तिना के आदरणीय वृद्धजन",
    "St Sava, First Archbishop of Serbia": u"सर्बिया के प्रथम महाधर्माध्यक्ष संत सावा",
    "St Simeon the Myrrh-gusher": u"मुर्र-स्रावी संत शिमोन",
    "St Basil of Ostrog": u"ओस्त्रोग के संत बेसिल",
    "St Justin Popovich of Ćelije": u"चेलिए के आदरणीय युस्तिन पोपोविच",
    "St Petar of Koriša": u"कोरिशा के आदरणीय पेतर",
    "Holy Great-martyr Tsar Lazar (Vidovdan)": u"पवित्र महान शहीद ज़ार लज़ार (विदोवदान)",
    "St Jefrem, Patriarch of Serbia": u"सर्बिया के कुलपति संत येफ्रेम",
    "St Angelina of Serbia": u"सर्बिया की आदरणीय अंजेलिना",
    "Synaxis of the Holy Hierarchs of Serbia": u"सर्बिया के पवित्र धर्माध्यक्ष",
    "The New Martyrs of Jasenovac": u"यासेनोवाच के नव शहीद",
    "St Stefan Vladislav, King of Serbia": u"सर्बिया के राजा संत स्तेफान व्लादिस्लाव",
    "St Petar of Cetinje, Wonderworker": u"चेतिन्ये के संत पेतर, चमत्कारकर्ता",
    "St Prohor of Pčinja": u"प्चिन्या के आदरणीय प्रोहोर",
    "St Milutin the King and St Jelena the Queen of Serbia": u"सर्बिया के राजा संत मिलुतिन और रानी संत येलेना",
    "St Stefan Dečanski, King of Serbia": u"सर्बिया के राजा संत स्तेफान देचान्स्की",
    "St Sebastian of Jackson": u"जैक्सन के आदरणीय सेबास्तियन",
    "St Joanikije of Devič": u"देविच के आदरणीय योआनिकिए",
    "St Danilo II, Archbishop of Serbia": u"सर्बिया के महाधर्माध्यक्ष संत दानिलो द्वितीय",
    "St Amphilochius of Pochaiv": u"पोचाइव के आदरणीय अम्फिलोखियुस",
    "St Feodosii of the Kyiv Caves": u"कीव गुफाओं के आदरणीय थियोदोसियुस",
    "St Antonii of the Kyiv Caves": u"कीव गुफाओं के आदरणीय अंतोनी",
    "St Olha, Equal-to-the-Apostles": u"संत ओल्हा, प्रेरितों के समतुल्य",
    "St Volodymyr, Equal-to-the-Apostles": u"संत वोलोदिमिर, प्रेरितों के समतुल्य",
    "St Petro Mohyla, Metropolitan of Kyiv": u"कीव के महानगराध्यक्ष संत पेत्रो मोहिला",
    "Synaxis of All Saints of Antioch": u"अंताकिया के सभी संत",
    "Synaxis of All Bulgarian Saints": u"बुल्गारिया के सभी संत",
    "Synaxis of All Saints of Mount Athos": u"आथोस पर्वत के सभी आदरणीय पिता",
    "Synaxis of All Saints of North America": u"उत्तरी अमेरिका के सभी संत",
    "Synaxis of All Venerable Fathers of the Kyiv Caves": u"कीव गुफाओं के सभी आदरणीय पिता",
    "Synaxis of All Romanian Saints": u"रोमानिया के सभी संत",
    "Synaxis of All Saints of Russia": u"रूस के सभी संत",
    "Synaxis of All Saints of Ukraine": u"यूक्रेन के सभी संत",
    "St Raphael, Bishop of Brooklyn": u"ब्रुकलिन के संत राफेल, बिशप",
}
