# -*- coding: utf-8 -*-
"""The Churches' own commemorations, in Armenian.

The classical orthography the rest of the calendar's Armenian keeps.

See docs/LOCAL_NAMES.md.
"""
TEXT = {
    "St Isaac the Syrian": u"Ասորի երանելի Իսահակ",
    "Martyr Elian of Homs": u"Եմեսայի նահատակ Էլիան",
    "St Joseph of Damascus & the New Martyrs of Damascus (1860)": u"Դամասկոսի Քահանայ-նահատակ Յովսէփ եւ Դամասկոսի նոր նահատակներ (1860)",
    "Hieromartyrs Nicholas and Habib Khasha of Damascus": u"Դամասկոսի Քահանայ-նահատակներ Նիկողայոս եւ Հաբիբ Խաշա",
    "St Gabriel of Lesnovo": u"Լեսնովոյի երանելի Գաբրիէլ",
    "St Joachim I, Patriarch of Tarnovo": u"Տրնովոյի պատրիարք սուրբ Յովակիմ Ա",
    "St Euthymius, Patriarch of Tarnovo": u"Տրնովոյի պատրիարք սուրբ Եւթիմիոս",
    "St Peter, King of Bulgaria": u"Բուլղարիոյ սուրբ թագաւոր Պետրոս",
    "St Romanus of Tarnovo": u"Տրնովոյի երանելի Ռոմանոս",
    "St Sophronius, Bishop of Vratsa": u"Վրացայի եպիսկոպոս սուրբ Սոփրոնիոս",
    "St Boris-Michael, Equal-to-the-Apostles, Baptizer of Bulgaria": u"Բուլղարիոյ մկրտիչ սուրբ Բորիս-Միքայէլ, առաքելահաւասար",
    "Great Martyr Nicholas of Sofia": u"Սոֆիայի Մեծ նահատակ Նիկողայոս",
    "St Paisius of Hilendar": u"Հիլանդարի երանելի Պայիսիոս",
    "The Seven Holy Apostles (Sedmochislenitsi)": u"Սուրբ եօթը առաքեալներ (Սեդմոչիսլենիցի)",
    "St Joachim of Osogovo": u"Օսոգովոյի երանելի Յովակիմ",
    "Repose of St John of Rila": u"Ռիլայի երանելի Յովհաննէսի հանգիստը",
    "New Martyr Simeon of Samokov": u"Սամոկովի նոր նահատակ Սիմէոն",
    "St Cosmas of Zographou": u"Զոգրաֆուի երանելի Կոսմաս",
    "The 26 Martyrs of Zographou": u"Զոգրաֆուի քսանվեց նահատակներ",
    "St Demetrius of Basarbovo": u"Բասարբովոյի երանելի Դիմիտրիոս",
    "Venerable Pimen of Zographou": u"Զոգրաֆուի երանելի Պիմեն",
    "Righteous Michael the Soldier of Bulgaria": u"Բուլղարիոյ արդար Միքայէլ զինուոր",
    "St Theodosius of Tarnovo": u"Տրնովոյի երանելի Թէոդոսիոս",
    "St Nektarios the Bulgarian of Bitola": u"Բիտոլայի երանելի նահատակ Նեկտարիոս",
    "St Nahum of Ohrid": u"Օխրիդի երանելի Նաում",
    "Ss Salome of Ujarma and Perozhavra of Sivnia": u"Ուջարմայի Սալոմէ եւ Սիվնիայի Պերոժավրա արդարներ",
    "St Eprem the Lesser, the Philosopher": u"Երանելի Եփրեմ Փոքր, փիլիսոփայ",
    "St David IV the Builder, King of Georgia": u"Վրաստանի սուրբ թագաւոր Դաւիթ Դ Շինարար",
    "St Ioane the Catholicos": u"Վրաստանի կաթողիկոս սուրբ Յովհաննէս",
    "Holy King Demetre the Devoted": u"Սուրբ թագաւոր Դեմետրէ Անձնուէր",
    "St Ambrosi the Confessor, Catholicos-Patriarch of All Georgia": u"Համայն Վրաստանի կաթողիկոս-պատրիարք սուրբ խոստովանող Ամբրոսիոս",
    "Venerable David of the Gareji Monastery": u"Գարեջիի երանելի Դաւիթ",
    "St Tamar, Queen of Georgia": u"Վրաստանի սուրբ Թամար թագուհի",
    "Venerable Ioane of Zedazeni and his Twelve Disciples": u"Զեդազենիի երանելի Յովհաննէս եւ իր տասներկու աշակերտները",
    "Venerable Ekvtime of Mount Athos, the Translator": u"Աթոսի երանելի Եւթիմէ թարգմանիչ",
    "St George the Hagiorite, and Hieromartyr Kirion II, Catholicos-Patriarch": u"Աթոսի երանելի Գէորգ եւ Քահանայ-նահատակ Կիրիոն Բ կաթողիկոս-պատրիարք",
    "St Ilia the Righteous": u"Սուրբ Իլիա Արդար",
    "Holy Martyr Evstati of Mtskheta": u"Մցխեթայի սուրբ նահատակ Եւստաթի",
    "St Tsotne Dadiani the Confessor": u"Սուրբ խոստովանող Ցոտնէ Դադիանի",
    "St Razhden, Protomartyr of Georgia, and the Nine Kherkheulidze Brothers": u"Վրաստանի առաջին նահատակ սուրբ Ռաժդեն եւ Խերխեուլիձէ ինը եղբայրները",
    "Holy Confessors Ioane and Giorgi-Ioane of Betania": u"Բեթանիայի սուրբ խոստովանողներ Յովհաննէս եւ Գէորգ-Յովհաննէս",
    "Holy Great-martyr Queen Ketevan": u"Սուրբ Մեծ նահատակ Քեթեւան թագուհի",
    "Holy Martyrs Bidzina, Shalva and Elizbar": u"Սուրբ նահատակներ Բիձինա, Շալվա եւ Էլիզբար",
    "Venerable Grigol of Khandzta": u"Խանձթայի երանելի Գրիգոլ",
    "St Gabriel of Samtavro, Confessor and Fool for Christ": u"Սամթավրոյի երանելի Գաբրիէլ, խոստովանող եւ Քրիստոսի յիմար",
    "The 100,000 Martyrs of Tbilisi": u"Թբիլիսիի հարիւր հազար նահատակներ",
    "Holy King Vakhtang Gorgasali": u"Սուրբ թագաւոր Վախթանգ Գորգասալի",
    "St Ise of Tsilkani": u"Ցիլկանիի սուրբ Իսէ",
    "Synaxis of All Saints of Georgia": u"Վրաստանի բոլոր սուրբերի յիշատակ",
    "Venerable Giorgi the Scribe and his brother Saba of Khakhuli": u"Խախուլիի երանելի Գէորգ Գրիչ եւ իր եղբայր Սաբա",
    "St Nikephoros the Leper": u"Երանելի Նիկիփոր Բորոտ",
    "St Arsenios of Paros": u"Պարոսի երանելի Արսենիոս",
    "St Ephraim of Katounakia": u"Կատունակիայի երանելի Եփրեմ",
    "St Nikolaos Planas of Athens": u"Աթէնքի արդար Նիկողայոս Պլանաս",
    "St Savvas the New of Kalymnos": u"Կալիմնոսի երանելի Սավա Նոր",
    "St Amphilochios of Patmos": u"Պատմոսի երանելի Ամփիլոքիոս",
    "St Joseph the Hesychast": u"Երանելի Յովսէփ Լռակեաց",
    "St Kosmas Aitolos, Equal-to-the-Apostles": u"Էտոլիացի սուրբ Կոսմաս, առաքելահաւասար",
    "St Arsenios of Cappadocia": u"Կապադովկիացի երանելի Արսենիոս",
    "St Iakovos of Evia": u"Եւբիայի երանելի Յակովբոս",
    "St Antipa of Calapodești": u"Կալապոդեշտի երանելի Անտիպա",
    "St Calinic of Cernica": u"Չերնիկայի սուրբ Կալինիկոս",
    "St Pahomie of Gledin, Bishop of Roman": u"Ռոմանի եպիսկոպոս Գլեդինի սուրբ Պախոմիոս",
    "Ss Ilie Iorest, Sava Brancovici and Simion Ștefan, Metropolitans of Transylvania": u"Տրանսիլվանիոյ մետրոպոլիտներ սուրբ Իլիէ Յորեստ, Սավա Բրանկովիչ եւ Սիմիոն Շտեֆան",
    "St Irodion of Lainici": u"Լայնիչի երանելի Իրոդիոն",
    "St John the Wallachian, Martyr": u"Նահատակ Յովհաննէս Վլախ",
    "St Iacob Putneanul, Metropolitan of Moldavia": u"Մոլդովայի մետրոպոլիտ սուրբ Յակովբ Պուտնեանուլ",
    "St Grigorie Dascălul, Metropolitan of Wallachia": u"Վալախիոյ մետրոպոլիտ սուրբ Գրիգոր Դասկալուլ",
    "St Ghelasie of Râmeț": u"Ռըմեցի սուրբ Գելասիոս",
    "St Leontie of Rădăuți": u"Ռադաուցիի սուրբ Լեոնտիոս",
    "St Stephen the Great": u"Սուրբ Ստեփանոս Մեծ",
    "St Ioanichie the New of Muscel": u"Մուսչելի երանելի Յովհաննիկիոս Նոր",
    "St Ioan Iacob of Neamț": u"Նեամցի երանելի Յովհաննէս Յակովբ",
    "St Teodora of Sihla": u"Սիխլայի երանելի Թէոդորա",
    "The Brâncoveanu Martyrs: Prince Constantin and his four sons": u"Բրնկովեանու նահատակներ: իշխան Կոստանդին եւ իր չորս որդիները",
    "St Iosif the New of Partoș, Metropolitan of Banat": u"Բանատի մետրոպոլիտ Պարտոշի սուրբ Յովսէփ Նոր",
    "St Neagoe Basarab, Voivode of Wallachia": u"Վալախիոյ իշխան սուրբ Նեագոէ Բասարաբ",
    "St Antim Ivireanul, Hieromartyr, Metropolitan of Wallachia": u"Վալախիոյ մետրոպոլիտ Քահանայ-նահատակ Անթիմ Իվիրեան",
    "St Parascheva of Iași": u"Յաշիի երանելի Պարասկեւի",
    "St Dimitrie the New of Bucharest": u"Բուխարեստի սուրբ Դիմիտրիէ Նոր",
    "St Iachint, Metropolitan of Wallachia": u"Վալախիոյ մետրոպոլիտ սուրբ Յակինթոս",
    "St Andrei Șaguna, Metropolitan of Transylvania": u"Տրանսիլվանիոյ մետրոպոլիտ սուրբ Անդրէյ Շագունա",
    "St Gheorghe of Cernica": u"Չերնիկայի երանելի Գէորգ",
    "St Dosoftei, Metropolitan of Moldavia": u"Մոլդովայի մետրոպոլիտ սուրբ Դոսիթէոս",
    "St Daniil the Hesychast": u"Երանելի Դանիէլ Լռակեաց",
    "St Nicodim of Tismana": u"Տիսմանայի երանելի Նիկոդիմոս",
    "St Seraphim of Sarov": u"Սարովի սուրբ Սերաֆիմ",
    "St Theophan the Recluse": u"Սուրբ Թէոփան Փակեալ",
    "St Xenia of St Petersburg": u"Սանկտ Պետերբուրգի սուրբ Քսենիա",
    "St Ignatius (Brianchaninov), Bishop of the Caucasus": u"Կովկասի եպիսկոպոս սուրբ Իգնատիոս (Բրեանչանինով)",
    "St Vladimir, Equal-to-the-Apostles": u"Սուրբ Վլադիմիր, առաքելահաւասար",
    "St Sergius of Radonezh": u"Ռադոնեժի սուրբ Սերգիոս",
    "St Ambrose of Optina": u"Օպտինայի երանելի Ամբրոսիոս",
    "Synaxis of the Optina Elders": u"Օպտինայի երանելի ծերերի յիշատակ",
    "St Sava, First Archbishop of Serbia": u"Սերբիոյ առաջին արքեպիսկոպոս սուրբ Սավա",
    "St Simeon the Myrrh-gusher": u"Իւղահոս սուրբ Սիմէոն",
    "St Basil of Ostrog": u"Օստրոգի սուրբ Բարսեղ",
    "St Justin Popovich of Ćelije": u"Չելիէի երանելի Յուստինոս Պոպովիչ",
    "St Petar of Koriša": u"Կորիշայի երանելի Պետրոս",
    "Holy Great-martyr Tsar Lazar (Vidovdan)": u"Սուրբ Մեծ նահատակ ցար Լազար (Վիդովդան)",
    "St Jefrem, Patriarch of Serbia": u"Սերբիոյ պատրիարք սուրբ Եփրեմ",
    "St Angelina of Serbia": u"Սերբիոյ երանելի Անգելինա",
    "Synaxis of the Holy Hierarchs of Serbia": u"Սերբիոյ սուրբ հայրապետների յիշատակ",
    "The New Martyrs of Jasenovac": u"Յասենովացի նոր նահատակներ",
    "St Stefan Vladislav, King of Serbia": u"Սերբիոյ սուրբ թագաւոր Ստեփան Վլադիսլավ",
    "St Petar of Cetinje, Wonderworker": u"Ցետինիէի սուրբ Պետրոս սքանչելագործ",
    "St Prohor of Pčinja": u"Պչինիայի երանելի Պրոխոր",
    "St Milutin the King and St Jelena the Queen of Serbia": u"Սերբիոյ սուրբ Միլուտին թագաւոր եւ սուրբ Յելենա թագուհի",
    "St Stefan Dečanski, King of Serbia": u"Սերբիոյ սուրբ թագաւոր Ստեփան Դեչանսկի",
    "St Sebastian of Jackson": u"Ջեքսոնի երանելի Սեբաստիանոս",
    "St Joanikije of Devič": u"Դեվիչի երանելի Յովհաննիկիոս",
    "St Danilo II, Archbishop of Serbia": u"Սերբիոյ արքեպիսկոպոս սուրբ Դանիէլ Բ",
    "St Amphilochius of Pochaiv": u"Պոչայեւի երանելի Ամփիլոքիոս",
    "St Feodosii of the Kyiv Caves": u"Կիեւի քարայրների երանելի Թէոդոսիոս",
    "St Antonii of the Kyiv Caves": u"Կիեւի քարայրների երանելի Անտոնիոս",
    "St Olha, Equal-to-the-Apostles": u"Սուրբ Օլգա, առաքելահաւասար",
    "St Volodymyr, Equal-to-the-Apostles": u"Սուրբ Վոլոդիմիր, առաքելահաւասար",
    "St Petro Mohyla, Metropolitan of Kyiv": u"Կիեւի մետրոպոլիտ սուրբ Պետրոս Մոգիլա",
    "Synaxis of All Saints of Antioch": u"Անտիոքի բոլոր սուրբերի յիշատակ",
    "Synaxis of All Bulgarian Saints": u"Բուլղարիոյ բոլոր սուրբերի յիշատակ",
    "Synaxis of All Saints of Mount Athos": u"Սուրբ Լերան բոլոր երանելի հայրերի յիշատակ",
    "Synaxis of All Saints of North America": u"Հիւսիսային Ամերիկայի բոլոր սուրբերի յիշատակ",
    "Synaxis of All Venerable Fathers of the Kyiv Caves": u"Կիեւի քարայրների բոլոր երանելի հայրերի յիշատակ",
    "Synaxis of All Romanian Saints": u"Ռումինիոյ բոլոր սուրբերի յիշատակ",
    "Synaxis of All Saints of Russia": u"Ռուսիոյ բոլոր սուրբերի յիշատակ",
    "Synaxis of All Saints of Ukraine": u"Ուկրաինայի բոլոր սուրբերի յիշատակ",
    "St Raphael, Bishop of Brooklyn": u"Բրուքլինի եպիսկոպոս սուրբ Ռաֆայէլ",
}
