# -*- coding: utf-8 -*-
"""The Churches' own commemorations, in Italian.

See docs/LOCAL_NAMES.md.
"""
TEXT = {
    "St Isaac the Syrian": u"Il venerabile Isacco il Siro",
    "Martyr Elian of Homs": u"San martire Elian di Homs",
    "St Joseph of Damascus & the New Martyrs of Damascus (1860)": u"San ieromartire Giuseppe di Damasco e i nuovi martiri di Damasco (1860)",
    "Hieromartyrs Nicholas and Habib Khasha of Damascus": u"Santi ieromartiri Nicola e Habib Khasha di Damasco",
    "St Gabriel of Lesnovo": u"Il venerabile Gabriele di Lesnovo",
    "St Joachim I, Patriarch of Tarnovo": u"San Gioacchino I, patriarca di Tarnovo",
    "St Euthymius, Patriarch of Tarnovo": u"Sant'Eutimio, patriarca di Tarnovo",
    "St Peter, King of Bulgaria": u"San Pietro, zar di Bulgaria",
    "St Romanus of Tarnovo": u"Il venerabile Romano di Tarnovo",
    "St Sophronius, Bishop of Vratsa": u"San Sofronio, vescovo di Vratsa",
    "St Boris-Michael, Equal-to-the-Apostles, Baptizer of Bulgaria": u"San Boris-Michele, pari agli apostoli, battezzatore della Bulgaria",
    "Great Martyr Nicholas of Sofia": u"San grande martire Nicola di Sofia",
    "St Paisius of Hilendar": u"Il venerabile Paisio di Hilandar",
    "The Seven Holy Apostles (Sedmochislenitsi)": u"I sette santi apostoli (Sedmochislenitsi)",
    "St Joachim of Osogovo": u"Il venerabile Gioacchino di Osogovo",
    "Repose of St John of Rila": u"Dormizione del venerabile Giovanni di Rila",
    "New Martyr Simeon of Samokov": u"San nuovo martire Simeone di Samokov",
    "St Cosmas of Zographou": u"Il venerabile Cosma di Zografou",
    "The 26 Martyrs of Zographou": u"I 26 martiri di Zografou",
    "St Demetrius of Basarbovo": u"Il venerabile Demetrio di Basarbovo",
    "Venerable Pimen of Zographou": u"Il venerabile Pimen di Zografou",
    "Righteous Michael the Soldier of Bulgaria": u"Il giusto Michele il soldato di Bulgaria",
    "St Theodosius of Tarnovo": u"Il venerabile Teodosio di Tarnovo",
    "St Nektarios the Bulgarian of Bitola": u"Il venerabile martire Nettario di Bitola",
    "St Nahum of Ohrid": u"San Naum di Ocrida",
    "Ss Salome of Ujarma and Perozhavra of Sivnia": u"Le giuste Salome di Ujarma e Perozhavra di Sivnia",
    "St Eprem the Lesser, the Philosopher": u"Il venerabile Eprem il Minore, il filosofo",
    "St David IV the Builder, King of Georgia": u"San Davide IV il Costruttore, re di Georgia",
    "St Ioane the Catholicos": u"San Ioane, catholicos di Georgia",
    "Holy King Demetre the Devoted": u"San Demetre il Devoto, re di Georgia",
    "St Ambrosi the Confessor, Catholicos-Patriarch of All Georgia": u"Sant'Ambrosi il confessore, catholicos-patriarca di tutta la Georgia",
    "Venerable David of the Gareji Monastery": u"Il venerabile Davide di Gareji",
    "St Tamar, Queen of Georgia": u"Santa Tamar, regina di Georgia",
    "Venerable Ioane of Zedazeni and his Twelve Disciples": u"Il venerabile Ioane di Zedazeni e i suoi dodici discepoli",
    "Venerable Ekvtime of Mount Athos, the Translator": u"Il venerabile Ekvtime del Monte Athos, il traduttore",
    "St George the Hagiorite, and Hieromartyr Kirion II, Catholicos-Patriarch": u"San Giorgio l'Aghiorita e il ieromartire Kirion II, catholicos-patriarca",
    "St Ilia the Righteous": u"Il giusto Ilia",
    "Holy Martyr Evstati of Mtskheta": u"San martire Evstati di Mtskheta",
    "St Tsotne Dadiani the Confessor": u"San Tsotne Dadiani il confessore",
    "St Razhden, Protomartyr of Georgia, and the Nine Kherkheulidze Brothers": u"San protomartire Razhden di Georgia e i nove fratelli Kherkheulidze",
    "Holy Confessors Ioane and Giorgi-Ioane of Betania": u"Santi confessori Ioane e Giorgi-Ioane di Betania",
    "Holy Great-martyr Queen Ketevan": u"Santa grande martire la regina Ketevan",
    "Holy Martyrs Bidzina, Shalva and Elizbar": u"Santi martiri Bidzina, Shalva ed Elizbar",
    "Venerable Grigol of Khandzta": u"Il venerabile Grigol di Khandzta",
    "St Gabriel of Samtavro, Confessor and Fool for Christ": u"Il venerabile Gabriele di Samtavro, confessore e folle per Cristo",
    "The 100,000 Martyrs of Tbilisi": u"I 100.000 martiri di Tbilisi",
    "Holy King Vakhtang Gorgasali": u"San Vakhtang Gorgasali, re di Georgia",
    "St Ise of Tsilkani": u"San Ise di Tsilkani",
    "Synaxis of All Saints of Georgia": u"Sinassi di tutti i santi della Georgia",
    "Venerable Giorgi the Scribe and his brother Saba of Khakhuli": u"I venerabili Giorgi lo Scriba e suo fratello Saba di Khakhuli",
    "St Nikephoros the Leper": u"Il venerabile Niceforo il Lebbroso",
    "St Arsenios of Paros": u"Il venerabile Arsenio di Paros",
    "St Ephraim of Katounakia": u"Il venerabile Efrem di Katounakia",
    "St Nikolaos Planas of Athens": u"Il giusto Nicola Planas di Atene",
    "St Savvas the New of Kalymnos": u"Il venerabile Savva il Nuovo di Kalymnos",
    "St Amphilochios of Patmos": u"Il venerabile Anfilochio di Patmos",
    "St Joseph the Hesychast": u"Il venerabile Giuseppe l'Esicasta",
    "St Kosmas Aitolos, Equal-to-the-Apostles": u"San Cosma Etolo, pari agli apostoli",
    "St Arsenios of Cappadocia": u"Il venerabile Arsenio di Cappadocia",
    "St Iakovos of Evia": u"Il venerabile Giacomo di Evia",
    "St Antipa of Calapodești": u"Il venerabile Antipa di Calapodesti",
    "St Calinic of Cernica": u"San Calinico di Cernica",
    "St Pahomie of Gledin, Bishop of Roman": u"San Pahomie di Gledin, vescovo di Roman",
    "Ss Ilie Iorest, Sava Brancovici and Simion Ștefan, Metropolitans of Transylvania": u"Santi Ilie Iorest, Sava Brancovici e Simion Stefan, metropoliti di Transilvania",
    "St Irodion of Lainici": u"Il venerabile Irodion di Lainici",
    "St John the Wallachian, Martyr": u"San martire Giovanni il Valacco",
    "St Iacob Putneanul, Metropolitan of Moldavia": u"San Iacob Putneanul, metropolita di Moldavia",
    "St Grigorie Dascălul, Metropolitan of Wallachia": u"San Grigorie Dascalul, metropolita di Valacchia",
    "St Ghelasie of Râmeț": u"San Ghelasie di Ramet",
    "St Leontie of Rădăuți": u"San Leontie di Radauti",
    "St Stephen the Great": u"Santo Stefano il Grande",
    "St Ioanichie the New of Muscel": u"Il venerabile Ioanichie il Nuovo di Muscel",
    "St Ioan Iacob of Neamț": u"Il venerabile Ioan Iacob di Neamt",
    "St Teodora of Sihla": u"La venerabile Teodora di Sihla",
    "The Brâncoveanu Martyrs: Prince Constantin and his four sons": u"I martiri Brancoveanu: il principe Constantin e i suoi quattro figli",
    "St Iosif the New of Partoș, Metropolitan of Banat": u"San Iosif il Nuovo di Partos, metropolita del Banato",
    "St Neagoe Basarab, Voivode of Wallachia": u"San Neagoe Basarab, voivoda di Valacchia",
    "St Antim Ivireanul, Hieromartyr, Metropolitan of Wallachia": u"San ieromartire Antim Ivireanul, metropolita di Valacchia",
    "St Parascheva of Iași": u"La venerabile Parascheva di Iasi",
    "St Dimitrie the New of Bucharest": u"San Dimitrie il Nuovo di Bucarest",
    "St Iachint, Metropolitan of Wallachia": u"San Iachint, metropolita di Valacchia",
    "St Andrei Șaguna, Metropolitan of Transylvania": u"San Andrei Saguna, metropolita di Transilvania",
    "St Gheorghe of Cernica": u"Il venerabile Gheorghe di Cernica",
    "St Dosoftei, Metropolitan of Moldavia": u"San Dosoftei, metropolita di Moldavia",
    "St Daniil the Hesychast": u"Il venerabile Daniil l'Esicasta",
    "St Nicodim of Tismana": u"Il venerabile Nicodim di Tismana",
    "St Seraphim of Sarov": u"San Serafino di Sarov",
    "St Theophan the Recluse": u"San Teofane il Recluso",
    "St Xenia of St Petersburg": u"Santa Xenia di San Pietroburgo",
    "St Ignatius (Brianchaninov), Bishop of the Caucasus": u"Sant'Ignazio (Brjancaninov), vescovo del Caucaso",
    "St Vladimir, Equal-to-the-Apostles": u"San Vladimir, pari agli apostoli",
    "St Sergius of Radonezh": u"San Sergio di Radonež",
    "St Ambrose of Optina": u"Il venerabile Ambrogio di Optina",
    "Synaxis of the Optina Elders": u"Sinassi degli anziani di Optina",
    "St Sava, First Archbishop of Serbia": u"San Sava, primo arcivescovo di Serbia",
    "St Simeon the Myrrh-gusher": u"San Simeone il mirovlita",
    "St Basil of Ostrog": u"San Basilio di Ostrog",
    "St Justin Popovich of Ćelije": u"Il venerabile Giustino Popovic di Celije",
    "St Petar of Koriša": u"Il venerabile Pietro di Korisa",
    "Holy Great-martyr Tsar Lazar (Vidovdan)": u"Santo grande martire zar Lazar (Vidovdan)",
    "St Jefrem, Patriarch of Serbia": u"San Jefrem, patriarca di Serbia",
    "St Angelina of Serbia": u"La venerabile Angelina di Serbia",
    "Synaxis of the Holy Hierarchs of Serbia": u"Sinassi dei santi gerarchi di Serbia",
    "The New Martyrs of Jasenovac": u"I nuovi martiri di Jasenovac",
    "St Stefan Vladislav, King of Serbia": u"San Stefan Vladislav, re di Serbia",
    "St Petar of Cetinje, Wonderworker": u"San Petar di Cetinje, il taumaturgo",
    "St Prohor of Pčinja": u"Il venerabile Prohor di Pcinja",
    "St Milutin the King and St Jelena the Queen of Serbia": u"San Milutin il re e santa Jelena la regina di Serbia",
    "St Stefan Dečanski, King of Serbia": u"San Stefan Decanski, re di Serbia",
    "St Sebastian of Jackson": u"Il venerabile Sebastiano di Jackson",
    "St Joanikije of Devič": u"Il venerabile Joanikije di Devic",
    "St Danilo II, Archbishop of Serbia": u"San Danilo II, arcivescovo di Serbia",
    "St Amphilochius of Pochaiv": u"Il venerabile Anfilochio di Pochaiv",
    "St Feodosii of the Kyiv Caves": u"Il venerabile Teodosio delle Grotte di Kyiv",
    "St Antonii of the Kyiv Caves": u"Il venerabile Antonio delle Grotte di Kyiv",
    "St Olha, Equal-to-the-Apostles": u"Sant'Olha, pari agli apostoli",
    "St Volodymyr, Equal-to-the-Apostles": u"San Volodymyr, pari agli apostoli",
    "St Petro Mohyla, Metropolitan of Kyiv": u"San Petro Mohyla, metropolita di Kyiv",
    "Synaxis of All Saints of Antioch": u"Sinassi di tutti i santi di Antiochia",
    "Synaxis of All Bulgarian Saints": u"Sinassi di tutti i santi di Bulgaria",
    "Synaxis of All Saints of Mount Athos": u"Sinassi di tutti i santi del Monte Athos",
    "Synaxis of All Saints of North America": u"Sinassi di tutti i santi dell'America del Nord",
    "Synaxis of All Venerable Fathers of the Kyiv Caves": u"Sinassi di tutti i venerabili padri delle Grotte di Kyiv",
    "Synaxis of All Romanian Saints": u"Sinassi di tutti i santi di Romania",
    "Synaxis of All Saints of Russia": u"Sinassi di tutti i santi di Russia",
    "Synaxis of All Saints of Ukraine": u"Sinassi di tutti i santi di Ucraina",
    "St Raphael, Bishop of Brooklyn": u"San Raffaele, vescovo di Brooklyn",
}
