# -*- coding: utf-8 -*-
"""The Churches' own commemorations, in Japanese.

Following docs/JAPANESE.md and the calendar's own table of names.

See docs/LOCAL_NAMES.md.
"""
TEXT = {
    "St Isaac the Syrian": u"シリアの克肖なるイサアク",
    "Martyr Elian of Homs": u"エメサの致命者エリアン",
    "St Joseph of Damascus & the New Martyrs of Damascus (1860)": u"ダマスクの致命神品イオシフとダマスクの新致命者たち（1860）",
    "Hieromartyrs Nicholas and Habib Khasha of Damascus": u"ダマスクの致命神品ニコライとハビブ・ハシャ",
    "St Gabriel of Lesnovo": u"レスノヴォの克肖なるガウリイル",
    "St Joachim I, Patriarch of Tarnovo": u"タルノヴォの総主教聖イオアキム一世",
    "St Euthymius, Patriarch of Tarnovo": u"タルノヴォの総主教聖エフフィミイ",
    "St Peter, King of Bulgaria": u"ブルガリアの王聖ペトル",
    "St Romanus of Tarnovo": u"タルノヴォの克肖なるロマン",
    "St Sophronius, Bishop of Vratsa": u"ヴラツァの主教聖ソフロニイ",
    "St Boris-Michael, Equal-to-the-Apostles, Baptizer of Bulgaria": u"ブルガリアを洗礼に導いた亜使徒の王ボリス・ミハイル",
    "Great Martyr Nicholas of Sofia": u"ソフィアの大致命者ニコライ",
    "St Paisius of Hilendar": u"ヒランダルの克肖なるパイシイ",
    "The Seven Holy Apostles (Sedmochislenitsi)": u"聖なる七人の使徒（セドモチスレニツィ）",
    "St Joachim of Osogovo": u"オソゴヴォの克肖なるイオアキム",
    "Repose of St John of Rila": u"リラの克肖なるイオアンの永眠",
    "New Martyr Simeon of Samokov": u"サモコフの新致命者シメオン",
    "St Cosmas of Zographou": u"ゾグラフの克肖なるコスマ",
    "The 26 Martyrs of Zographou": u"ゾグラフの二十六致命者",
    "St Demetrius of Basarbovo": u"バサラボヴォの克肖なるディミトリイ",
    "Venerable Pimen of Zographou": u"ゾグラフの克肖なるピメン",
    "Righteous Michael the Soldier of Bulgaria": u"ブルガリアの義人ミハイル兵士",
    "St Theodosius of Tarnovo": u"タルノヴォの克肖なるフェオドシイ",
    "St Nektarios the Bulgarian of Bitola": u"ビトラの克肖致命者ネクタリイ",
    "St Nahum of Ohrid": u"オフリドの克肖なるナウム",
    "Ss Salome of Ujarma and Perozhavra of Sivnia": u"ウジャルマの義人サロメとシヴニヤのペロジャヴラ",
    "St Eprem the Lesser, the Philosopher": u"克肖なるエフレム・ムツィレ、愛智者",
    "St David IV the Builder, King of Georgia": u"グルジアの王聖ダヴィド四世建設者",
    "St Ioane the Catholicos": u"グルジアのカトリコス聖イオアン",
    "Holy King Demetre the Devoted": u"グルジアの王聖ディミトリエ献身者",
    "St Ambrosi the Confessor, Catholicos-Patriarch of All Georgia": u"全グルジアのカトリコス・総主教、宣信者聖アムウロシイ",
    "Venerable David of the Gareji Monastery": u"ガレジの克肖なるダヴィド",
    "St Tamar, Queen of Georgia": u"グルジアの女王聖タマル",
    "Venerable Ioane of Zedazeni and his Twelve Disciples": u"ゼダズニの克肖なるイオアンとその十二人の弟子",
    "Venerable Ekvtime of Mount Athos, the Translator": u"アトスの克肖なるエクフティメ、翻訳者",
    "St George the Hagiorite, and Hieromartyr Kirion II, Catholicos-Patriarch": u"アトスの克肖なるギオルギと致命神品キリオン二世、カトリコス・総主教",
    "St Ilia the Righteous": u"義人聖イリヤ",
    "Holy Martyr Evstati of Mtskheta": u"ムツヘタの致命者エウスタフィ",
    "St Tsotne Dadiani the Confessor": u"宣信者聖ツォトネ・ダディアニ",
    "St Razhden, Protomartyr of Georgia, and the Nine Kherkheulidze Brothers": u"グルジアの首致命者ラジデンとヘルヘウリゼの九兄弟",
    "Holy Confessors Ioane and Giorgi-Ioane of Betania": u"ベタニヤの宣信者聖イオアンとギオルギ・イオアン",
    "Holy Great-martyr Queen Ketevan": u"大致命女ケテワン女王",
    "Holy Martyrs Bidzina, Shalva and Elizbar": u"聖致命者ビジナ、シャルワ、エリズバル",
    "Venerable Grigol of Khandzta": u"ハンヅタの克肖なるグリゴル",
    "St Gabriel of Samtavro, Confessor and Fool for Christ": u"サムタヴロの克肖なるガウリイル、宣信者にして佯狂者",
    "The 100,000 Martyrs of Tbilisi": u"トビリシの十万致命者",
    "Holy King Vakhtang Gorgasali": u"グルジアの王聖ワフタング・ゴルガサリ",
    "St Ise of Tsilkani": u"ツィルカニの聖イセ",
    "Synaxis of All Saints of Georgia": u"グルジアの諸聖人のシナクシス",
    "Venerable Giorgi the Scribe and his brother Saba of Khakhuli": u"ハフリの克肖なる書記ギオルギとその兄弟サバ",
    "St Nikephoros the Leper": u"克肖なる癩者ニキフォル",
    "St Arsenios of Paros": u"パロスの克肖なるアルセニイ",
    "St Ephraim of Katounakia": u"カトゥナキヤの克肖なるエフレム",
    "St Nikolaos Planas of Athens": u"アティナの義人ニコラオス・プラナス",
    "St Savvas the New of Kalymnos": u"カリムノスの克肖なる新サワ",
    "St Amphilochios of Patmos": u"パトモスの克肖なるアムフィロヒイ",
    "St Joseph the Hesychast": u"克肖なる静修者イオシフ",
    "St Kosmas Aitolos, Equal-to-the-Apostles": u"アイトリアの聖コスマス、亜使徒",
    "St Arsenios of Cappadocia": u"カパドキヤの克肖なるアルセニイ",
    "St Iakovos of Evia": u"エウィアの克肖なるイアコフ",
    "St Antipa of Calapodești": u"カラポデシュティの克肖なるアンティパ",
    "St Calinic of Cernica": u"チェルニカの聖カリニク",
    "St Pahomie of Gledin, Bishop of Roman": u"グレディンの聖パホミイ、ロマンの主教",
    "Ss Ilie Iorest, Sava Brancovici and Simion Ștefan, Metropolitans of Transylvania": u"トランシルヴァニアの府主教聖イリエ・ヨレスト、サワ・ブランコヴィチ、シミオン・シュテファン",
    "St Irodion of Lainici": u"ライニチの克肖なるイロディオン",
    "St John the Wallachian, Martyr": u"致命者ワラヒアのイオアン",
    "St Iacob Putneanul, Metropolitan of Moldavia": u"モルダヴィアの府主教聖イアコフ・プトネアヌル",
    "St Grigorie Dascălul, Metropolitan of Wallachia": u"ワラヒアの府主教聖グリゴリエ・ダスカルル",
    "St Ghelasie of Râmeț": u"ルィメツの聖ゲラシエ",
    "St Leontie of Rădăuți": u"ラダウツィの聖レオンティエ",
    "St Stephen the Great": u"聖大ステファン",
    "St Ioanichie the New of Muscel": u"ムシュチェルの克肖なる新イオアニキエ",
    "St Ioan Iacob of Neamț": u"ニャムツの克肖なるイオアン・イアコフ",
    "St Teodora of Sihla": u"シフラの克肖女フェオドラ",
    "The Brâncoveanu Martyrs: Prince Constantin and his four sons": u"ブルンコヴャヌの致命者、公コンスタンティンとその四人の子",
    "St Iosif the New of Partoș, Metropolitan of Banat": u"バナトの府主教、パルトシュの聖新イオシフ",
    "St Neagoe Basarab, Voivode of Wallachia": u"ワラヒアの公聖ニャゴエ・バサラブ",
    "St Antim Ivireanul, Hieromartyr, Metropolitan of Wallachia": u"ワラヒアの府主教、致命神品アンティム・イヴィレアヌル",
    "St Parascheva of Iași": u"ヤシの克肖女パラスケワ",
    "St Dimitrie the New of Bucharest": u"ブカレストの聖新ディミトリエ",
    "St Iachint, Metropolitan of Wallachia": u"ワラヒアの府主教聖イアキント",
    "St Andrei Șaguna, Metropolitan of Transylvania": u"トランシルヴァニアの府主教聖アンドレイ・シャグナ",
    "St Gheorghe of Cernica": u"チェルニカの克肖なるゲオルゲ",
    "St Dosoftei, Metropolitan of Moldavia": u"モルダヴィアの府主教聖ドソフテイ",
    "St Daniil the Hesychast": u"克肖なる静修者ダニイル",
    "St Nicodim of Tismana": u"ティスマナの克肖なるニコディム",
    "St Seraphim of Sarov": u"サロフの聖セラフィム",
    "St Theophan the Recluse": u"聖幽居者フェオファン",
    "St Xenia of St Petersburg": u"サンクトペテルブルクの聖クセニヤ",
    "St Ignatius (Brianchaninov), Bishop of the Caucasus": u"カフカスの主教聖イグナティイ（ブリャンチャニノフ）",
    "St Vladimir, Equal-to-the-Apostles": u"聖ウラジーミル、亜使徒",
    "St Sergius of Radonezh": u"ラドネジの聖セルギイ",
    "St Ambrose of Optina": u"オプチナの克肖なるアムウロシイ",
    "Synaxis of the Optina Elders": u"オプチナの克肖なる長老たちのシナクシス",
    "St Sava, First Archbishop of Serbia": u"セルビアの初代大主教聖サワ",
    "St Simeon the Myrrh-gusher": u"滲香者聖シメオン",
    "St Basil of Ostrog": u"オストログの聖ワシリイ",
    "St Justin Popovich of Ćelije": u"チェリエの克肖なるイウスティン・ポポヴィチ",
    "St Petar of Koriša": u"コリシャの克肖なるペトル",
    "Holy Great-martyr Tsar Lazar (Vidovdan)": u"聖大致命者ツァーリ・ラザル（ヴィドヴダン）",
    "St Jefrem, Patriarch of Serbia": u"セルビアの総主教聖エフレム",
    "St Angelina of Serbia": u"セルビアの克肖女アンゲリナ",
    "Synaxis of the Holy Hierarchs of Serbia": u"セルビアの聖なる主教たちのシナクシス",
    "The New Martyrs of Jasenovac": u"ヤセノヴァツの新致命者たち",
    "St Stefan Vladislav, King of Serbia": u"セルビアの王聖ステファン・ウラジスラフ",
    "St Petar of Cetinje, Wonderworker": u"ツェティニェの聖ペトル、奇蹟者",
    "St Prohor of Pčinja": u"プチニャの克肖なるプロホル",
    "St Milutin the King and St Jelena the Queen of Serbia": u"セルビアの王聖ミルティンと女王聖イェレナ",
    "St Stefan Dečanski, King of Serbia": u"セルビアの王聖ステファン・デチャンスキ",
    "St Sebastian of Jackson": u"ジャクソンの克肖なるセワスティアン",
    "St Joanikije of Devič": u"デヴィチの克肖なるイオアニキイ",
    "St Danilo II, Archbishop of Serbia": u"セルビアの大主教聖ダニロ二世",
    "St Amphilochius of Pochaiv": u"ポチャエフの克肖なるアムフィロヒイ",
    "St Feodosii of the Kyiv Caves": u"キエフ洞窟の克肖なるフェオドシイ",
    "St Antonii of the Kyiv Caves": u"キエフ洞窟の克肖なるアントニイ",
    "St Olha, Equal-to-the-Apostles": u"聖オリガ、亜使徒",
    "St Volodymyr, Equal-to-the-Apostles": u"聖ヴォロディーミル、亜使徒",
    "St Petro Mohyla, Metropolitan of Kyiv": u"キエフの府主教聖ペトル・モギラ",
    "Synaxis of All Saints of Antioch": u"アンティオキアの諸聖人のシナクシス",
    "Synaxis of All Bulgarian Saints": u"ブルガリアの諸聖人のシナクシス",
    "Synaxis of All Saints of Mount Athos": u"アトス山の諸克肖者のシナクシス",
    "Synaxis of All Saints of North America": u"北アメリカの諸聖人のシナクシス",
    "Synaxis of All Venerable Fathers of the Kyiv Caves": u"キエフ洞窟の諸克肖なる父のシナクシス",
    "Synaxis of All Romanian Saints": u"ルーマニアの諸聖人のシナクシス",
    "Synaxis of All Saints of Russia": u"ロシアの諸聖人のシナクシス",
    "Synaxis of All Saints of Ukraine": u"ウクライナの諸聖人のシナクシス",
    "St Raphael, Bishop of Brooklyn": u"ブルックリンの主教聖ラファイル",
}
