# -*- coding: utf-8 -*-
"""The Churches' own commemorations, in Georgian.

Mkhedruli, and the truncated honorific before a name, as docs/GEORGIAN.md has it.

See docs/LOCAL_NAMES.md.
"""
TEXT = {
    "St Isaac the Syrian": u"ღირს ისააკ ასურელი",
    "Martyr Elian of Homs": u"წმინდა მოწამე ელიანე ემესელი",
    "St Joseph of Damascus & the New Martyrs of Damascus (1860)": u"წმინდა მღვდელმოწამე იოსებ დამასკელი და დამასკოს ახალმოწამენი (1860)",
    "Hieromartyrs Nicholas and Habib Khasha of Damascus": u"წმინდა მღვდელმოწამენი ნიკოლოზ და ჰაბიბ ხაშა დამასკელნი",
    "St Gabriel of Lesnovo": u"ღირს გაბრიელ ლესნოველი",
    "St Joachim I, Patriarch of Tarnovo": u"წმინდა იოაკიმ I, ტარნოვოს პატრიარქი",
    "St Euthymius, Patriarch of Tarnovo": u"წმინდა ევთიმი, ტარნოვოს პატრიარქი",
    "St Peter, King of Bulgaria": u"წმინდა კეთილმსახური მეფე პეტრე ბულგარელი",
    "St Romanus of Tarnovo": u"ღირს რომანოზ ტარნოველი",
    "St Sophronius, Bishop of Vratsa": u"წმინდა სოფრონი, ვრაცის ეპისკოპოსი",
    "St Boris-Michael, Equal-to-the-Apostles, Baptizer of Bulgaria": u"მოციქულთა სწორი მეფე ბორის-მიქაელი, ბულგარეთის ნათლისმცემელი",
    "Great Martyr Nicholas of Sofia": u"წმინდა დიდმოწამე ნიკოლოზ სოფიელი",
    "St Paisius of Hilendar": u"ღირს პაისი ხილანდარელი",
    "The Seven Holy Apostles (Sedmochislenitsi)": u"წმინდა შვიდი მოციქული (სედმოჩისლენიცი)",
    "St Joachim of Osogovo": u"ღირს იოაკიმ ოსოგოველი",
    "Repose of St John of Rila": u"ღირსი იოანე რილელის მიცვალება",
    "New Martyr Simeon of Samokov": u"წმინდა ახალმოწამე სვიმეონ სამოკოველი",
    "St Cosmas of Zographou": u"ღირს კოზმან ზოგრაფელი",
    "The 26 Martyrs of Zographou": u"ზოგრაფის 26 მოწამე",
    "St Demetrius of Basarbovo": u"ღირს დიმიტრი ბასარბოველი",
    "Venerable Pimen of Zographou": u"ღირს პიმენ ზოგრაფელი",
    "Righteous Michael the Soldier of Bulgaria": u"მართალი მიქაელ მეომარი ბულგარელი",
    "St Theodosius of Tarnovo": u"ღირს თეოდოსი ტარნოველი",
    "St Nektarios the Bulgarian of Bitola": u"ღირსმოწამე ნეკტარიოს ბიტოლელი",
    "St Nahum of Ohrid": u"ღირს ნაუმ ოხრიდელი",
    "Ss Salome of Ujarma and Perozhavra of Sivnia": u"წმინდა სალომე უჯარმელი და პეროჟავრა სივნიელი",
    "St Eprem the Lesser, the Philosopher": u"ღირს ეფრემ მცირე, ფილოსოფოსი",
    "St David IV the Builder, King of Georgia": u"წმინდა მეფე დავით IV აღმაშენებელი",
    "St Ioane the Catholicos": u"წმინდა იოანე კათოლიკოსი",
    "Holy King Demetre the Devoted": u"წმინდა მეფე დემეტრე თავდადებული",
    "St Ambrosi the Confessor, Catholicos-Patriarch of All Georgia": u"წმინდა ამბროსი აღმსარებელი, სრულიად საქართველოს კათოლიკოს-პატრიარქი",
    "Venerable David of the Gareji Monastery": u"ღირს დავით გარეჯელი",
    "St Tamar, Queen of Georgia": u"წმინდა თამარ მეფე",
    "Venerable Ioane of Zedazeni and his Twelve Disciples": u"ღირს იოანე ზედაზნელი და მისი თორმეტი მოწაფე",
    "Venerable Ekvtime of Mount Athos, the Translator": u"ღირს ექვთიმე მთაწმინდელი, მთარგმნელი",
    "St George the Hagiorite, and Hieromartyr Kirion II, Catholicos-Patriarch": u"ღირს გიორგი მთაწმინდელი და წმინდა მღვდელმოწამე კირიონ II, კათოლიკოს-პატრიარქი",
    "St Ilia the Righteous": u"წმინდა ილია მართალი",
    "Holy Martyr Evstati of Mtskheta": u"წმინდა მოწამე ევსტათი მცხეთელი",
    "St Tsotne Dadiani the Confessor": u"წმინდა ცოტნე დადიანი აღმსარებელი",
    "St Razhden, Protomartyr of Georgia, and the Nine Kherkheulidze Brothers": u"წმინდა პირველმოწამე რაჟდენი და ცხრა ძმა ხერხეულიძე",
    "Holy Confessors Ioane and Giorgi-Ioane of Betania": u"წმინდა აღმსარებელნი იოანე და გიორგი-იოანე ბეთანიელნი",
    "Holy Great-martyr Queen Ketevan": u"წმინდა დიდმოწამე ქეთევან დედოფალი",
    "Holy Martyrs Bidzina, Shalva and Elizbar": u"წმინდა მოწამენი ბიძინა, შალვა და ელიზბარი",
    "Venerable Grigol of Khandzta": u"ღირს გრიგოლ ხანძთელი",
    "St Gabriel of Samtavro, Confessor and Fool for Christ": u"ღირს გაბრიელ სამტავროელი, აღმსარებელი და ქრისტესთვის სული",
    "The 100,000 Martyrs of Tbilisi": u"ასი ათასი მოწამე თბილისისა",
    "Holy King Vakhtang Gorgasali": u"წმინდა მეფე ვახტანგ გორგასალი",
    "St Ise of Tsilkani": u"წმინდა იესე წილკნელი",
    "Synaxis of All Saints of Georgia": u"ყოველთა წმინდათა საქართველოსათა ხსენება",
    "Venerable Giorgi the Scribe and his brother Saba of Khakhuli": u"ღირსნი გიორგი მწერალი და მისი ძმა საბა ხახულელნი",
    "St Nikephoros the Leper": u"ღირს ნიკიფორე კეთროვანი",
    "St Arsenios of Paros": u"ღირს არსენი პაროსელი",
    "St Ephraim of Katounakia": u"ღირს ეფრემ კატუნაკიელი",
    "St Nikolaos Planas of Athens": u"მართალი ნიკოლოზ პლანასი ათენელი",
    "St Savvas the New of Kalymnos": u"ღირს საბა ახალი კალიმნოსელი",
    "St Amphilochios of Patmos": u"ღირს ამფილოქე პატმოსელი",
    "St Joseph the Hesychast": u"ღირს იოსებ ისიხასტი",
    "St Kosmas Aitolos, Equal-to-the-Apostles": u"მოციქულთა სწორი კოზმა ეტოლიელი",
    "St Arsenios of Cappadocia": u"ღირს არსენი კაბადოკიელი",
    "St Iakovos of Evia": u"ღირს იაკობ ევბეელი",
    "St Antipa of Calapodești": u"ღირს ანტიპა კალაპოდეშტელი",
    "St Calinic of Cernica": u"წმინდა კალინიკე ჩერნიკელი",
    "St Pahomie of Gledin, Bishop of Roman": u"წმინდა პახომი გლედინელი, რომანის ეპისკოპოსი",
    "Ss Ilie Iorest, Sava Brancovici and Simion Ștefan, Metropolitans of Transylvania": u"წმინდანი ილია იორესტი, საბა ბრანკოვიჩი და სვიმეონ შტეფანი, ტრანსილვანიის მიტროპოლიტები",
    "St Irodion of Lainici": u"ღირს იროდიონ ლაინიჩელი",
    "St John the Wallachian, Martyr": u"წმინდა მოწამე იოანე ვლახი",
    "St Iacob Putneanul, Metropolitan of Moldavia": u"წმინდა იაკობ პუტნელი, მოლდავეთის მიტროპოლიტი",
    "St Grigorie Dascălul, Metropolitan of Wallachia": u"წმინდა გრიგოლ დასკალული, ვლახეთის მიტროპოლიტი",
    "St Ghelasie of Râmeț": u"წმინდა ღელასი რიმეცელი",
    "St Leontie of Rădăuți": u"წმინდა ლეონტი რედეუცელი",
    "St Stephen the Great": u"წმინდა კეთილმსახური სტეფანე დიდი, მოლდავეთის მთავარი",
    "St Ioanichie the New of Muscel": u"ღირს იოანიკე ახალი მუშჩელელი",
    "St Ioan Iacob of Neamț": u"ღირს იოანე იაკობ ნიამცელი",
    "St Teodora of Sihla": u"ღირს თეოდორა სიხლელი",
    "The Brâncoveanu Martyrs: Prince Constantin and his four sons": u"ბრინკოვიანუს მოწამენი: მთავარი კონსტანტინე და მისი ოთხი ძე",
    "St Iosif the New of Partoș, Metropolitan of Banat": u"წმინდა იოსებ ახალი პარტოშელი, ბანატის მიტროპოლიტი",
    "St Neagoe Basarab, Voivode of Wallachia": u"წმინდა კეთილმსახური ნიაგოე ბასარაბი, ვლახეთის მთავარი",
    "St Antim Ivireanul, Hieromartyr, Metropolitan of Wallachia": u"წმინდა მღვდელმოწამე ანთიმოზ ივერიელი, ვლახეთის მიტროპოლიტი",
    "St Parascheva of Iași": u"ღირს პარასკევა იაშელი",
    "St Dimitrie the New of Bucharest": u"ღირს დიმიტრი ახალი ბუქარესტელი",
    "St Iachint, Metropolitan of Wallachia": u"წმინდა იაკინთე, ვლახეთის მიტროპოლიტი",
    "St Andrei Șaguna, Metropolitan of Transylvania": u"წმინდა ანდრია შაგუნა, ტრანსილვანიის მიტროპოლიტი",
    "St Gheorghe of Cernica": u"ღირს გიორგი ჩერნიკელი",
    "St Dosoftei, Metropolitan of Moldavia": u"წმინდა დოსითეოზ, მოლდავეთის მიტროპოლიტი",
    "St Daniil the Hesychast": u"ღირს დანიელ ისიხასტი",
    "St Nicodim of Tismana": u"ღირს ნიკოდიმოს ტისმანელი",
    "St Seraphim of Sarov": u"ღირს სერაფიმ საროველი",
    "St Theophan the Recluse": u"წმინდა თეოფანე დაყუდებული",
    "St Xenia of St Petersburg": u"ნეტარი ქსენია პეტერბურგელი",
    "St Ignatius (Brianchaninov), Bishop of the Caucasus": u"წმინდა იგნატი (ბრიანჩანინოვი), კავკასიის ეპისკოპოსი",
    "St Vladimir, Equal-to-the-Apostles": u"მოციქულთა სწორი დიდი მთავარი ვლადიმერი",
    "St Sergius of Radonezh": u"ღირს სერგი რადონეჟელი",
    "St Ambrose of Optina": u"ღირს ამბროსი ოპტინელი",
    "Synaxis of the Optina Elders": u"ოპტინის ღირსთა ბერთა ხსენება",
    "St Sava, First Archbishop of Serbia": u"წმინდა საბა, სერბეთის პირველი მთავარეპისკოპოსი",
    "St Simeon the Myrrh-gusher": u"ღირს სვიმეონ მირონმდინარე",
    "St Basil of Ostrog": u"წმინდა ვასილი ოსტროგელი",
    "St Justin Popovich of Ćelije": u"ღირს იუსტინე პოპოვიჩი ჩელიელი",
    "St Petar of Koriša": u"ღირს პეტრე კორიშელი",
    "Holy Great-martyr Tsar Lazar (Vidovdan)": u"წმინდა დიდმოწამე მეფე ლაზარი (ვიდოვდანი)",
    "St Jefrem, Patriarch of Serbia": u"წმინდა ეფრემ, სერბეთის პატრიარქი",
    "St Angelina of Serbia": u"ღირსი ანგელინა სერბი",
    "Synaxis of the Holy Hierarchs of Serbia": u"სერბეთის წმინდა მღვდელმთავართა ხსენება",
    "The New Martyrs of Jasenovac": u"იასენოვაცის ახალმოწამენი",
    "St Stefan Vladislav, King of Serbia": u"წმინდა კეთილმსახური მეფე სტეფან ვლადისლავი",
    "St Petar of Cetinje, Wonderworker": u"წმინდა პეტრე ცეტინელი, სასწაულმოქმედი",
    "St Prohor of Pčinja": u"ღირს პროხორე პჩინელი",
    "St Milutin the King and St Jelena the Queen of Serbia": u"წმინდა კეთილმსახური მეფე მილუტინი და დედოფალი ელენე სერბნი",
    "St Stefan Dečanski, King of Serbia": u"წმინდა კეთილმსახური მეფე სტეფან დეჩანელი",
    "St Sebastian of Jackson": u"ღირს სებასტიანე ჯექსონელი",
    "St Joanikije of Devič": u"ღირს იოანიკე დევიჩელი",
    "St Danilo II, Archbishop of Serbia": u"წმინდა დანიელ II, სერბეთის მთავარეპისკოპოსი",
    "St Amphilochius of Pochaiv": u"ღირს ამფილოქე პოჩაელი",
    "St Feodosii of the Kyiv Caves": u"ღირს თეოდოსი კიევის მღვიმელი",
    "St Antonii of the Kyiv Caves": u"ღირს ანტონი კიევის მღვიმელი",
    "St Olha, Equal-to-the-Apostles": u"მოციქულთა სწორი ოლღა დედოფალი",
    "St Volodymyr, Equal-to-the-Apostles": u"მოციქულთა სწორი დიდი მთავარი ვლადიმერი",
    "St Petro Mohyla, Metropolitan of Kyiv": u"წმინდა პეტრე მოგილა, კიევის მიტროპოლიტი",
    "Synaxis of All Saints of Antioch": u"ყოველთა წმინდათა ანტიოქიისათა ხსენება",
    "Synaxis of All Bulgarian Saints": u"ყოველთა წმინდათა ბულგარეთისათა ხსენება",
    "Synaxis of All Saints of Mount Athos": u"ათონის მთის ყოველთა ღირსთა მამათა ხსენება",
    "Synaxis of All Saints of North America": u"ყოველთა წმინდათა ჩრდილოეთ ამერიკისათა ხსენება",
    "Synaxis of All Venerable Fathers of the Kyiv Caves": u"კიევის მღვიმის ყოველთა ღირსთა მამათა ხსენება",
    "Synaxis of All Romanian Saints": u"ყოველთა წმინდათა რუმინეთისათა ხსენება",
    "Synaxis of All Saints of Russia": u"ყოველთა წმინდათა რუსეთისათა ხსენება",
    "Synaxis of All Saints of Ukraine": u"ყოველთა წმინდათა უკრაინისათა ხსენება",
    "St Raphael, Bishop of Brooklyn": u"წმინდა რაფაელ, ბრუკლინის ეპისკოპოსი",
}
