# -*- coding: utf-8 -*-
"""The Churches' own commemorations, in Korean.

See docs/LOCAL_NAMES.md.
"""
TEXT = {
    "St Isaac the Syrian": u"시리아의 존경하올 이사악",
    "Martyr Elian of Homs": u"에메사의 순교자 엘리안",
    "St Joseph of Damascus & the New Martyrs of Damascus (1860)": u"다마스쿠스의 사제 순교자 요셉과 다마스쿠스의 새 순교자들(1860)",
    "Hieromartyrs Nicholas and Habib Khasha of Damascus": u"다마스쿠스의 사제 순교자 니콜라오와 하비브 하샤",
    "St Gabriel of Lesnovo": u"레스노보의 존경하올 가브리엘",
    "St Joachim I, Patriarch of Tarnovo": u"터르노보의 총대주교 성 요아킴 1세",
    "St Euthymius, Patriarch of Tarnovo": u"터르노보의 총대주교 성 에우티미오",
    "St Peter, King of Bulgaria": u"불가리아의 왕 성 베드로",
    "St Romanus of Tarnovo": u"터르노보의 존경하올 로마노",
    "St Sophronius, Bishop of Vratsa": u"브라차의 주교 성 소프로니오",
    "St Boris-Michael, Equal-to-the-Apostles, Baptizer of Bulgaria": u"불가리아를 세례한 성 보리스-미카엘, 사도와 동등한 자",
    "Great Martyr Nicholas of Sofia": u"소피아의 대순교자 니콜라오",
    "St Paisius of Hilendar": u"힐란다르의 존경하올 파이시오",
    "The Seven Holy Apostles (Sedmochislenitsi)": u"거룩한 일곱 사도(세드모치슬레니치)",
    "St Joachim of Osogovo": u"오소고보의 존경하올 요아킴",
    "Repose of St John of Rila": u"릴라의 존경하올 요한의 안식",
    "New Martyr Simeon of Samokov": u"사모코프의 새 순교자 시메온",
    "St Cosmas of Zographou": u"조그라푸의 존경하올 코스마",
    "The 26 Martyrs of Zographou": u"조그라푸의 스물여섯 순교자",
    "St Demetrius of Basarbovo": u"바사라보보의 존경하올 디미트리오",
    "Venerable Pimen of Zographou": u"조그라푸의 존경하올 피멘",
    "Righteous Michael the Soldier of Bulgaria": u"불가리아의 의인 군인 미카엘",
    "St Theodosius of Tarnovo": u"터르노보의 존경하올 테오도시오",
    "St Nektarios the Bulgarian of Bitola": u"비톨라의 존경하올 순교자 넥타리오",
    "St Nahum of Ohrid": u"오흐리드의 존경하올 나훔",
    "Ss Salome of Ujarma and Perozhavra of Sivnia": u"우자르마의 의인 살로메와 시브니아의 페로자브라",
    "St Eprem the Lesser, the Philosopher": u"존경하올 에프렘 므치레, 철학자",
    "St David IV the Builder, King of Georgia": u"조지아의 왕 성 다윗 4세 건설자",
    "St Ioane the Catholicos": u"조지아의 총대주교 성 요한",
    "Holy King Demetre the Devoted": u"조지아의 왕 성 데메트레, 자신을 바친 이",
    "St Ambrosi the Confessor, Catholicos-Patriarch of All Georgia": u"온 조지아의 총대주교 증거자 성 암브로시오",
    "Venerable David of the Gareji Monastery": u"가레지의 존경하올 다윗",
    "St Tamar, Queen of Georgia": u"조지아의 여왕 성 타마르",
    "Venerable Ioane of Zedazeni and his Twelve Disciples": u"제다제니의 존경하올 요한과 그의 열두 제자",
    "Venerable Ekvtime of Mount Athos, the Translator": u"아토스의 존경하올 에크브티메, 번역자",
    "St George the Hagiorite, and Hieromartyr Kirion II, Catholicos-Patriarch": u"아토스의 존경하올 게오르기와 사제 순교자 키리온 2세 총대주교",
    "St Ilia the Righteous": u"의인 성 일리아",
    "Holy Martyr Evstati of Mtskheta": u"므츠헤타의 순교자 에우스타티오",
    "St Tsotne Dadiani the Confessor": u"증거자 성 초트네 다디아니",
    "St Razhden, Protomartyr of Georgia, and the Nine Kherkheulidze Brothers": u"조지아의 첫 순교자 라즈덴과 케르케울리제 아홉 형제",
    "Holy Confessors Ioane and Giorgi-Ioane of Betania": u"베타니아의 증거자 성 요한과 게오르기-요한",
    "Holy Great-martyr Queen Ketevan": u"대순교녀 케테반 여왕",
    "Holy Martyrs Bidzina, Shalva and Elizbar": u"순교자 비지나, 샬바, 엘리즈바르",
    "Venerable Grigol of Khandzta": u"한즈타의 존경하올 그리골",
    "St Gabriel of Samtavro, Confessor and Fool for Christ": u"삼타브로의 존경하올 가브리엘, 증거자이며 그리스도를 위한 바보",
    "The 100,000 Martyrs of Tbilisi": u"트빌리시의 십만 순교자",
    "Holy King Vakhtang Gorgasali": u"조지아의 왕 성 바흐탕 고르가살리",
    "St Ise of Tsilkani": u"칠카니의 성 이세",
    "Synaxis of All Saints of Georgia": u"조지아의 모든 성인",
    "Venerable Giorgi the Scribe and his brother Saba of Khakhuli": u"하훌리의 존경하올 필경사 게오르기와 그의 형제 사바",
    "St Nikephoros the Leper": u"존경하올 나병자 니키포로",
    "St Arsenios of Paros": u"파로스의 존경하올 아르세니오",
    "St Ephraim of Katounakia": u"카투나키아의 존경하올 에프렘",
    "St Nikolaos Planas of Athens": u"아테네의 의인 니콜라오 플라나스",
    "St Savvas the New of Kalymnos": u"칼림노스의 존경하올 새 사바",
    "St Amphilochios of Patmos": u"파트모스의 존경하올 암필로키오",
    "St Joseph the Hesychast": u"존경하올 정적주의자 요셉",
    "St Kosmas Aitolos, Equal-to-the-Apostles": u"아이톨로스의 성 코스마스, 사도와 동등한 자",
    "St Arsenios of Cappadocia": u"카파도키아의 존경하올 아르세니오",
    "St Iakovos of Evia": u"에비아의 존경하올 야고보",
    "St Antipa of Calapodești": u"칼라포데슈티의 존경하올 안티파",
    "St Calinic of Cernica": u"체르니카의 성 칼리닉",
    "St Pahomie of Gledin, Bishop of Roman": u"글레딘의 성 파호미오, 로만의 주교",
    "Ss Ilie Iorest, Sava Brancovici and Simion Ștefan, Metropolitans of Transylvania": u"트란실바니아의 수도 대주교 성 일리에 요레스트, 사바 브란코비치, 시메온 슈테판",
    "St Irodion of Lainici": u"라이니치의 존경하올 이로디온",
    "St John the Wallachian, Martyr": u"순교자 왈라키아의 요한",
    "St Iacob Putneanul, Metropolitan of Moldavia": u"몰다비아의 수도 대주교 성 야고보 푸트네아눌",
    "St Grigorie Dascălul, Metropolitan of Wallachia": u"왈라키아의 수도 대주교 성 그리고리에 다스칼룰",
    "St Ghelasie of Râmeț": u"르메츠의 성 겔라시에",
    "St Leontie of Rădăuți": u"러더우치의 성 레온티에",
    "St Stephen the Great": u"성 대 스테파노",
    "St Ioanichie the New of Muscel": u"무셸의 존경하올 새 요아니키에",
    "St Ioan Iacob of Neamț": u"네암츠의 존경하올 요한 야고보",
    "St Teodora of Sihla": u"시흘라의 존경하올 테오도라",
    "The Brâncoveanu Martyrs: Prince Constantin and his four sons": u"브른코베아누 순교자들, 콘스탄틴 공과 그의 네 아들",
    "St Iosif the New of Partoș, Metropolitan of Banat": u"바나트의 수도 대주교, 파르토슈의 성 새 요셉",
    "St Neagoe Basarab, Voivode of Wallachia": u"왈라키아의 공 성 네아고에 바사라브",
    "St Antim Ivireanul, Hieromartyr, Metropolitan of Wallachia": u"왈라키아의 수도 대주교, 사제 순교자 안팀 이비레아눌",
    "St Parascheva of Iași": u"이아시의 존경하올 파라스케바",
    "St Dimitrie the New of Bucharest": u"부쿠레슈티의 성 새 디미트리에",
    "St Iachint, Metropolitan of Wallachia": u"왈라키아의 수도 대주교 성 이아킨트",
    "St Andrei Șaguna, Metropolitan of Transylvania": u"트란실바니아의 수도 대주교 성 안드레이 샤구나",
    "St Gheorghe of Cernica": u"체르니카의 존경하올 게오르게",
    "St Dosoftei, Metropolitan of Moldavia": u"몰다비아의 수도 대주교 성 도소프테이",
    "St Daniil the Hesychast": u"존경하올 정적주의자 다니엘",
    "St Nicodim of Tismana": u"티스마나의 존경하올 니코딤",
    "St Seraphim of Sarov": u"사로프의 성 세라핌",
    "St Theophan the Recluse": u"성 은수자 테오판",
    "St Xenia of St Petersburg": u"상트페테르부르크의 성 크세니아",
    "St Ignatius (Brianchaninov), Bishop of the Caucasus": u"캅카스의 주교 성 이그나티오(브랸차니노프)",
    "St Vladimir, Equal-to-the-Apostles": u"성 블라디미르, 사도와 동등한 자",
    "St Sergius of Radonezh": u"라도네시의 성 세르기오",
    "St Ambrose of Optina": u"옵티나의 존경하올 암브로시오",
    "Synaxis of the Optina Elders": u"옵티나의 존경하올 장로들",
    "St Sava, First Archbishop of Serbia": u"세르비아 초대 대주교 성 사바",
    "St Simeon the Myrrh-gusher": u"몰약을 흘리는 성 시메온",
    "St Basil of Ostrog": u"오스트로그의 성 바실리오",
    "St Justin Popovich of Ćelije": u"첼리에의 존경하올 유스틴 포포비치",
    "St Petar of Koriša": u"코리샤의 존경하올 베드로",
    "Holy Great-martyr Tsar Lazar (Vidovdan)": u"거룩한 대순교자 차르 라자르(비도브단)",
    "St Jefrem, Patriarch of Serbia": u"세르비아의 총대주교 성 에프렘",
    "St Angelina of Serbia": u"세르비아의 존경하올 안젤리나",
    "Synaxis of the Holy Hierarchs of Serbia": u"세르비아의 거룩한 주교들",
    "The New Martyrs of Jasenovac": u"야세노바츠의 새 순교자들",
    "St Stefan Vladislav, King of Serbia": u"세르비아의 왕 성 스테판 블라디슬라브",
    "St Petar of Cetinje, Wonderworker": u"체티녜의 성 베드로, 기적행자",
    "St Prohor of Pčinja": u"프치냐의 존경하올 프로호르",
    "St Milutin the King and St Jelena the Queen of Serbia": u"세르비아의 왕 성 밀루틴과 여왕 성 옐레나",
    "St Stefan Dečanski, King of Serbia": u"세르비아의 왕 성 스테판 데찬스키",
    "St Sebastian of Jackson": u"잭슨의 존경하올 세바스티아노",
    "St Joanikije of Devič": u"데비치의 존경하올 요아니키오",
    "St Danilo II, Archbishop of Serbia": u"세르비아의 대주교 성 다닐로 2세",
    "St Amphilochius of Pochaiv": u"포차이우의 존경하올 암필로키오",
    "St Feodosii of the Kyiv Caves": u"키예프 동굴의 존경하올 테오도시오",
    "St Antonii of the Kyiv Caves": u"키예프 동굴의 존경하올 안토니오",
    "St Olha, Equal-to-the-Apostles": u"성 올하, 사도와 동등한 자",
    "St Volodymyr, Equal-to-the-Apostles": u"성 볼로디미르, 사도와 동등한 자",
    "St Petro Mohyla, Metropolitan of Kyiv": u"키예프의 수도 대주교 성 베드로 모힐라",
    "Synaxis of All Saints of Antioch": u"안티오키아의 모든 성인",
    "Synaxis of All Bulgarian Saints": u"불가리아의 모든 성인",
    "Synaxis of All Saints of Mount Athos": u"아토스 성산의 모든 존경하올 교부들",
    "Synaxis of All Saints of North America": u"북아메리카의 모든 성인",
    "Synaxis of All Venerable Fathers of the Kyiv Caves": u"키예프 동굴의 모든 존경하올 교부들",
    "Synaxis of All Romanian Saints": u"루마니아의 모든 성인",
    "Synaxis of All Saints of Russia": u"러시아의 모든 성인",
    "Synaxis of All Saints of Ukraine": u"우크라이나의 모든 성인",
    "St Raphael, Bishop of Brooklyn": u"브루클린의 주교 성 라파엘",
}
