# -*- coding: utf-8 -*-
"""The Churches' own commemorations, in Portuguese.

See docs/LOCAL_NAMES.md.
"""
TEXT = {
    "St Isaac the Syrian": u"O Venerável Isaac, o Sírio",
    "Martyr Elian of Homs": u"São Mártir Elian de Homs",
    "St Joseph of Damascus & the New Martyrs of Damascus (1860)": u"São Hieromártir José de Damasco e os Novos Mártires de Damasco (1860)",
    "Hieromartyrs Nicholas and Habib Khasha of Damascus": u"Santos Hieromártires Nicolau e Habib Khasha de Damasco",
    "St Gabriel of Lesnovo": u"O Venerável Gabriel de Lesnovo",
    "St Joachim I, Patriarch of Tarnovo": u"São Joaquim I, Patriarca de Tarnovo",
    "St Euthymius, Patriarch of Tarnovo": u"São Eutímio, Patriarca de Tarnovo",
    "St Peter, King of Bulgaria": u"São Pedro, Czar da Bulgária",
    "St Romanus of Tarnovo": u"O Venerável Romano de Tarnovo",
    "St Sophronius, Bishop of Vratsa": u"São Sofrônio, Bispo de Vratsa",
    "St Boris-Michael, Equal-to-the-Apostles, Baptizer of Bulgaria": u"São Boris-Miguel, Igual aos Apóstolos, Batizador da Bulgária",
    "Great Martyr Nicholas of Sofia": u"São Grande Mártir Nicolau de Sófia",
    "St Paisius of Hilendar": u"O Venerável Paísio de Hilandar",
    "The Seven Holy Apostles (Sedmochislenitsi)": u"Os Sete Santos Apóstolos (Sedmochislenitsi)",
    "St Joachim of Osogovo": u"O Venerável Joaquim de Osogovo",
    "Repose of St John of Rila": u"Dormição do venerável João de Rila",
    "New Martyr Simeon of Samokov": u"Novo Mártir Simeão de Samokov",
    "St Cosmas of Zographou": u"O Venerável Cosme de Zografou",
    "The 26 Martyrs of Zographou": u"Os 26 Mártires de Zografou",
    "St Demetrius of Basarbovo": u"O Venerável Demétrio de Basarabovo",
    "Venerable Pimen of Zographou": u"O Venerável Pimen de Zografou",
    "Righteous Michael the Soldier of Bulgaria": u"O Justo Miguel, o Soldado da Bulgária",
    "St Theodosius of Tarnovo": u"O Venerável Teodósio de Tarnovo",
    "St Nektarios the Bulgarian of Bitola": u"O Venerável Mártir Nectário de Bitola",
    "St Nahum of Ohrid": u"São Naum de Ohrid",
    "Ss Salome of Ujarma and Perozhavra of Sivnia": u"As Justas Salomé de Ujarma e Perozhavra de Sivnia",
    "St Eprem the Lesser, the Philosopher": u"O Venerável Efrém, o Menor, o Filósofo",
    "St David IV the Builder, King of Georgia": u"São Rei Davi IV, o Construtor, da Geórgia",
    "St Ioane the Catholicos": u"São Ioane, Catholicos da Geórgia",
    "Holy King Demetre the Devoted": u"São Rei Demetre, o Abnegado",
    "St Ambrosi the Confessor, Catholicos-Patriarch of All Georgia": u"São Ambrosi, o Confessor, Catholicos-Patriarca de toda a Geórgia",
    "Venerable David of the Gareji Monastery": u"O Venerável Davi do Mosteiro de Gareji",
    "St Tamar, Queen of Georgia": u"Santa Tamar, Rainha da Geórgia",
    "Venerable Ioane of Zedazeni and his Twelve Disciples": u"O Venerável Ioane de Zedazeni e seus doze discípulos",
    "Venerable Ekvtime of Mount Athos, the Translator": u"O Venerável Ekvtime do Monte Athos, o Tradutor",
    "St George the Hagiorite, and Hieromartyr Kirion II, Catholicos-Patriarch": u"São Jorge, o Hagiorita, e o Hieromártir Kirion II, Catholicos-Patriarca",
    "St Ilia the Righteous": u"O Justo Ilia",
    "Holy Martyr Evstati of Mtskheta": u"São Mártir Evstati de Mtskheta",
    "St Tsotne Dadiani the Confessor": u"São Tsotne Dadiani, o Confessor",
    "St Razhden, Protomartyr of Georgia, and the Nine Kherkheulidze Brothers": u"São Protomártir Razhden da Geórgia e os nove irmãos Kherkheulidze",
    "Holy Confessors Ioane and Giorgi-Ioane of Betania": u"Santos Confessores Ioane e Giorgi-Ioane de Betânia",
    "Holy Great-martyr Queen Ketevan": u"Santa Grande Mártir Rainha Ketevan",
    "Holy Martyrs Bidzina, Shalva and Elizbar": u"Santos Mártires Bidzina, Shalva e Elizbar",
    "Venerable Grigol of Khandzta": u"O Venerável Grigol de Khandzta",
    "St Gabriel of Samtavro, Confessor and Fool for Christ": u"O Venerável Gabriel de Samtavro, Confessor e Louco por Cristo",
    "The 100,000 Martyrs of Tbilisi": u"Os 100.000 Mártires de Tbilisi",
    "Holy King Vakhtang Gorgasali": u"São Rei Vakhtang Gorgasali",
    "St Ise of Tsilkani": u"São Ise de Tsilkani",
    "Synaxis of All Saints of Georgia": u"Sínaxe de todos os Santos da Geórgia",
    "Venerable Giorgi the Scribe and his brother Saba of Khakhuli": u"Os Veneráveis Giorgi, o Escriba, e seu irmão Saba de Khakhuli",
    "St Nikephoros the Leper": u"O Venerável Nicéforo, o Leproso",
    "St Arsenios of Paros": u"O Venerável Arsênio de Paros",
    "St Ephraim of Katounakia": u"O Venerável Efrém de Katounakia",
    "St Nikolaos Planas of Athens": u"O Justo Nicolau Planas de Atenas",
    "St Savvas the New of Kalymnos": u"O Venerável Sava, o Novo, de Kalymnos",
    "St Amphilochios of Patmos": u"O Venerável Anfilóquio de Patmos",
    "St Joseph the Hesychast": u"O Venerável José, o Hesicasta",
    "St Kosmas Aitolos, Equal-to-the-Apostles": u"São Cosme, o Etólio, Igual aos Apóstolos",
    "St Arsenios of Cappadocia": u"O Venerável Arsênio da Capadócia",
    "St Iakovos of Evia": u"O Venerável Jacó de Évia",
    "St Antipa of Calapodești": u"O Venerável Antipa de Calapodesti",
    "St Calinic of Cernica": u"São Calínico de Cernica",
    "St Pahomie of Gledin, Bishop of Roman": u"São Pahomie de Gledin, Bispo de Roman",
    "Ss Ilie Iorest, Sava Brancovici and Simion Ștefan, Metropolitans of Transylvania": u"Santos Ilie Iorest, Sava Brancovici e Simion Stefan, Metropolitas da Transilvânia",
    "St Irodion of Lainici": u"O Venerável Irodion de Lainici",
    "St John the Wallachian, Martyr": u"São Mártir João, o Valáquio",
    "St Iacob Putneanul, Metropolitan of Moldavia": u"São Iacob Putneanul, Metropolita da Moldávia",
    "St Grigorie Dascălul, Metropolitan of Wallachia": u"São Grigorie Dascalul, Metropolita da Valáquia",
    "St Ghelasie of Râmeț": u"São Ghelasie de Ramet",
    "St Leontie of Rădăuți": u"São Leontie de Radauti",
    "St Stephen the Great": u"Santo Estêvão, o Grande",
    "St Ioanichie the New of Muscel": u"O Venerável Ioanichie, o Novo, de Muscel",
    "St Ioan Iacob of Neamț": u"O Venerável Ioan Iacob de Neamt",
    "St Teodora of Sihla": u"A Venerável Teodora de Sihla",
    "The Brâncoveanu Martyrs: Prince Constantin and his four sons": u"Os Mártires Brancoveanu: o príncipe Constantin e seus quatro filhos",
    "St Iosif the New of Partoș, Metropolitan of Banat": u"São Iosif, o Novo, de Partos, Metropolita do Banato",
    "St Neagoe Basarab, Voivode of Wallachia": u"São Neagoe Basarab, Voivoda da Valáquia",
    "St Antim Ivireanul, Hieromartyr, Metropolitan of Wallachia": u"São Hieromártir Antim Ivireanul, Metropolita da Valáquia",
    "St Parascheva of Iași": u"A Venerável Parascheva de Iasi",
    "St Dimitrie the New of Bucharest": u"São Dimitrie, o Novo, de Bucareste",
    "St Iachint, Metropolitan of Wallachia": u"São Iachint, Metropolita da Valáquia",
    "St Andrei Șaguna, Metropolitan of Transylvania": u"São Andrei Saguna, Metropolita da Transilvânia",
    "St Gheorghe of Cernica": u"O Venerável Gheorghe de Cernica",
    "St Dosoftei, Metropolitan of Moldavia": u"São Dosoftei, Metropolita da Moldávia",
    "St Daniil the Hesychast": u"O Venerável Daniil, o Hesicasta",
    "St Nicodim of Tismana": u"O Venerável Nicodim de Tismana",
    "St Seraphim of Sarov": u"São Serafim de Sarov",
    "St Theophan the Recluse": u"São Teófano, o Recluso",
    "St Xenia of St Petersburg": u"Santa Xênia de São Petersburgo",
    "St Ignatius (Brianchaninov), Bishop of the Caucasus": u"Santo Inácio (Brianchaninov), Bispo do Cáucaso",
    "St Vladimir, Equal-to-the-Apostles": u"São Vladimir, Igual aos Apóstolos",
    "St Sergius of Radonezh": u"São Sérgio de Radonej",
    "St Ambrose of Optina": u"O Venerável Ambrósio de Optina",
    "Synaxis of the Optina Elders": u"Sínaxe dos Anciãos de Optina",
    "St Sava, First Archbishop of Serbia": u"São Sava, primeiro Arcebispo da Sérvia",
    "St Simeon the Myrrh-gusher": u"São Simeão, o Mirroblita",
    "St Basil of Ostrog": u"São Basílio de Ostrog",
    "St Justin Popovich of Ćelije": u"O Venerável Justino Popovich de Celije",
    "St Petar of Koriša": u"O Venerável Pedro de Korisa",
    "Holy Great-martyr Tsar Lazar (Vidovdan)": u"Santo Grande Mártir Czar Lázaro (Vidovdan)",
    "St Jefrem, Patriarch of Serbia": u"São Jefrem, Patriarca da Sérvia",
    "St Angelina of Serbia": u"A Venerável Angelina da Sérvia",
    "Synaxis of the Holy Hierarchs of Serbia": u"Sínaxe dos Santos Hierarcas da Sérvia",
    "The New Martyrs of Jasenovac": u"Os Novos Mártires de Jasenovac",
    "St Stefan Vladislav, King of Serbia": u"São Rei Stefan Vladislav da Sérvia",
    "St Petar of Cetinje, Wonderworker": u"São Petar de Cetinje, o Taumaturgo",
    "St Prohor of Pčinja": u"O Venerável Prohor de Pcinja",
    "St Milutin the King and St Jelena the Queen of Serbia": u"São Rei Milutin e Santa Rainha Jelena da Sérvia",
    "St Stefan Dečanski, King of Serbia": u"São Rei Stefan Decanski da Sérvia",
    "St Sebastian of Jackson": u"O Venerável Sebastião de Jackson",
    "St Joanikije of Devič": u"O Venerável Joanikije de Devic",
    "St Danilo II, Archbishop of Serbia": u"São Danilo II, Arcebispo da Sérvia",
    "St Amphilochius of Pochaiv": u"O Venerável Anfilóquio de Pochaiv",
    "St Feodosii of the Kyiv Caves": u"O Venerável Teodósio das Cavernas de Kyiv",
    "St Antonii of the Kyiv Caves": u"O Venerável Antônio das Cavernas de Kyiv",
    "St Olha, Equal-to-the-Apostles": u"Santa Olha, Igual aos Apóstolos",
    "St Volodymyr, Equal-to-the-Apostles": u"São Volodymyr, Igual aos Apóstolos",
    "St Petro Mohyla, Metropolitan of Kyiv": u"São Petro Mohyla, Metropolita de Kyiv",
    "Synaxis of All Saints of Antioch": u"Sínaxe de todos os Santos de Antioquia",
    "Synaxis of All Bulgarian Saints": u"Sínaxe de todos os Santos da Bulgária",
    "Synaxis of All Saints of Mount Athos": u"Sínaxe de todos os Santos do Monte Athos",
    "Synaxis of All Saints of North America": u"Sínaxe de todos os Santos da América do Norte",
    "Synaxis of All Venerable Fathers of the Kyiv Caves": u"Sínaxe de todos os Veneráveis Padres das Cavernas de Kyiv",
    "Synaxis of All Romanian Saints": u"Sínaxe de todos os Santos da Romênia",
    "Synaxis of All Saints of Russia": u"Sínaxe de todos os Santos da Rússia",
    "Synaxis of All Saints of Ukraine": u"Sínaxe de todos os Santos da Ucrânia",
    "St Raphael, Bishop of Brooklyn": u"São Rafael, Bispo de Brooklyn",
}
