# -*- coding: utf-8 -*-
"""The Churches' own commemorations, in Romanian.

See docs/LOCAL_NAMES.md.
"""
TEXT = {
    "St Isaac the Syrian": u"Cuviosul Isaac Sirul",
    "Martyr Elian of Homs": u"Sfântul Mucenic Elian din Emesa",
    "St Joseph of Damascus & the New Martyrs of Damascus (1860)": u"Sfântul Sfințit Mucenic Iosif din Damasc și noii mucenici din Damasc (1860)",
    "Hieromartyrs Nicholas and Habib Khasha of Damascus": u"Sfinții Sfințiți Mucenici Nicolae și Habib Hașa din Damasc",
    "St Gabriel of Lesnovo": u"Cuviosul Gavriil de la Lesnovo",
    "St Joachim I, Patriarch of Tarnovo": u"Sfântul Ierarh Ioachim I, patriarhul Târnovei",
    "St Euthymius, Patriarch of Tarnovo": u"Sfântul Ierarh Eftimie, patriarhul Târnovei",
    "St Peter, King of Bulgaria": u"Sfântul Țar Petru al Bulgariei",
    "St Romanus of Tarnovo": u"Cuviosul Roman de la Târnovo",
    "St Sophronius, Bishop of Vratsa": u"Sfântul Ierarh Sofronie, episcopul Vraței",
    "St Boris-Michael, Equal-to-the-Apostles, Baptizer of Bulgaria": u"Sfântul Țar Boris-Mihail, întocmai cu apostolii, luminătorul bulgarilor",
    "Great Martyr Nicholas of Sofia": u"Sfântul Mare Mucenic Nicolae din Sofia",
    "St Paisius of Hilendar": u"Cuviosul Paisie de la Hilandar",
    "The Seven Holy Apostles (Sedmochislenitsi)": u"Sfinții Șapte Apostoli (Sedmocislenici)",
    "St Joachim of Osogovo": u"Cuviosul Ioachim de la Osogovo",
    "Repose of St John of Rila": u"Adormirea Cuviosului Ioan de la Rila",
    "New Martyr Simeon of Samokov": u"Sfântul Nou Mucenic Simeon din Samokov",
    "St Cosmas of Zographou": u"Cuviosul Cosma de la Zografu",
    "The 26 Martyrs of Zographou": u"Cei 26 de mucenici de la Zografu",
    "St Demetrius of Basarbovo": u"Cuviosul Dimitrie de la Basarabov",
    "Venerable Pimen of Zographou": u"Cuviosul Pimen de la Zografu",
    "Righteous Michael the Soldier of Bulgaria": u"Dreptul Mihail Ostașul din Bulgaria",
    "St Theodosius of Tarnovo": u"Cuviosul Teodosie de la Târnovo",
    "St Nektarios the Bulgarian of Bitola": u"Cuviosul Mucenic Nectarie Bitolianul",
    "St Nahum of Ohrid": u"Sfântul Naum de la Ohrida",
    "Ss Salome of Ujarma and Perozhavra of Sivnia": u"Dreptele Salomeea de la Ujarma și Perojavra de la Sivnia",
    "St Eprem the Lesser, the Philosopher": u"Cuviosul Efrem cel Mic, filosoful",
    "St David IV the Builder, King of Georgia": u"Sfântul Rege David al IV-lea Ziditorul al Georgiei",
    "St Ioane the Catholicos": u"Sfântul Ierarh Ioane, catolicosul Georgiei",
    "Holy King Demetre the Devoted": u"Sfântul Rege Dimitrie cel Jertfelnic",
    "St Ambrosi the Confessor, Catholicos-Patriarch of All Georgia": u"Sfântul Ierarh Ambrozie Mărturisitorul, catolicos-patriarhul întregii Georgii",
    "Venerable David of the Gareji Monastery": u"Cuviosul David de la Gareji",
    "St Tamar, Queen of Georgia": u"Sfânta Tamara, regina Georgiei",
    "Venerable Ioane of Zedazeni and his Twelve Disciples": u"Cuviosul Ioane de la Zedazeni și cei doisprezece ucenici ai săi",
    "Venerable Ekvtime of Mount Athos, the Translator": u"Cuviosul Ecvtime Athonitul, tălmăcitorul",
    "St George the Hagiorite, and Hieromartyr Kirion II, Catholicos-Patriarch": u"Sfântul Gheorghe Athonitul și Sfântul Sfințit Mucenic Kirion al II-lea, catolicos-patriarh",
    "St Ilia the Righteous": u"Dreptul Ilia Ceavceavadze",
    "Holy Martyr Evstati of Mtskheta": u"Sfântul Mucenic Evstati din Mțheta",
    "St Tsotne Dadiani the Confessor": u"Sfântul Țotne Dadiani Mărturisitorul",
    "St Razhden, Protomartyr of Georgia, and the Nine Kherkheulidze Brothers": u"Sfântul Întâiul Mucenic Rajden și cei nouă frați Herheulidze",
    "Holy Confessors Ioane and Giorgi-Ioane of Betania": u"Sfinții Mărturisitori Ioane și Giorgi-Ioane de la Betania",
    "Holy Great-martyr Queen Ketevan": u"Sfânta Mare Muceniță regina Ketevan",
    "Holy Martyrs Bidzina, Shalva and Elizbar": u"Sfinții Mucenici Bidzina, Șalva și Elizbar",
    "Venerable Grigol of Khandzta": u"Cuviosul Grigol de la Handzta",
    "St Gabriel of Samtavro, Confessor and Fool for Christ": u"Cuviosul Gavriil de la Samtavro, mărturisitor și nebun pentru Hristos",
    "The 100,000 Martyrs of Tbilisi": u"Cei 100 000 de mucenici din Tbilisi",
    "Holy King Vakhtang Gorgasali": u"Sfântul Rege Vahtang Gorgasali",
    "St Ise of Tsilkani": u"Sfântul Ierarh Ise de Țilkani",
    "Synaxis of All Saints of Georgia": u"Soborul tuturor sfinților georgieni",
    "Venerable Giorgi the Scribe and his brother Saba of Khakhuli": u"Cuvioșii Giorgi Scriitorul și fratele său Saba de la Hahuli",
    "St Nikephoros the Leper": u"Cuviosul Nichifor Leprosul",
    "St Arsenios of Paros": u"Cuviosul Arsenie din Paros",
    "St Ephraim of Katounakia": u"Cuviosul Efrem Katunakiotul",
    "St Nikolaos Planas of Athens": u"Dreptul Nicolae Planas din Atena",
    "St Savvas the New of Kalymnos": u"Cuviosul Sava cel Nou din Kalymnos",
    "St Amphilochios of Patmos": u"Cuviosul Amfilohie din Patmos",
    "St Joseph the Hesychast": u"Cuviosul Iosif Isihastul",
    "St Kosmas Aitolos, Equal-to-the-Apostles": u"Sfântul Cosma Etolianul, întocmai cu apostolii",
    "St Arsenios of Cappadocia": u"Cuviosul Arsenie Capadocianul",
    "St Iakovos of Evia": u"Cuviosul Iacov din Evia",
    "St Antipa of Calapodești": u"Cuviosul Antipa de la Calapodești",
    "St Calinic of Cernica": u"Sfântul Ierarh Calinic de la Cernica",
    "St Pahomie of Gledin, Bishop of Roman": u"Sfântul Ierarh Pahomie de la Gledin, episcopul Romanului",
    "Ss Ilie Iorest, Sava Brancovici and Simion Ștefan, Metropolitans of Transylvania": u"Sfinții Ierarhi Ilie Iorest, Sava Brancovici și Simion Ștefan, mitropoliții Transilvaniei",
    "St Irodion of Lainici": u"Cuviosul Irodion de la Lainici",
    "St John the Wallachian, Martyr": u"Sfântul Mucenic Ioan Valahul",
    "St Iacob Putneanul, Metropolitan of Moldavia": u"Sfântul Ierarh Iacob Putneanul, mitropolitul Moldovei",
    "St Grigorie Dascălul, Metropolitan of Wallachia": u"Sfântul Ierarh Grigorie Dascălul, mitropolitul Țării Românești",
    "St Ghelasie of Râmeț": u"Sfântul Ierarh Ghelasie de la Râmeț",
    "St Leontie of Rădăuți": u"Sfântul Ierarh Leontie de la Rădăuți",
    "St Stephen the Great": u"Sfântul Voievod Ștefan cel Mare",
    "St Ioanichie the New of Muscel": u"Cuviosul Ioanichie cel Nou de la Muscel",
    "St Ioan Iacob of Neamț": u"Cuviosul Ioan Iacob de la Neamț",
    "St Teodora of Sihla": u"Cuvioasa Teodora de la Sihla",
    "The Brâncoveanu Martyrs: Prince Constantin and his four sons": u"Sfinții Mucenici Brâncoveni: voievodul Constantin și cei patru fii ai săi",
    "St Iosif the New of Partoș, Metropolitan of Banat": u"Sfântul Ierarh Iosif cel Nou de la Partoș, mitropolitul Banatului",
    "St Neagoe Basarab, Voivode of Wallachia": u"Sfântul Voievod Neagoe Basarab",
    "St Antim Ivireanul, Hieromartyr, Metropolitan of Wallachia": u"Sfântul Sfințit Mucenic Antim Ivireanul, mitropolitul Țării Românești",
    "St Parascheva of Iași": u"Cuvioasa Parascheva de la Iași",
    "St Dimitrie the New of Bucharest": u"Cuviosul Dimitrie cel Nou, ocrotitorul Bucureștilor",
    "St Iachint, Metropolitan of Wallachia": u"Sfântul Ierarh Iachint de Vicina, mitropolitul Țării Românești",
    "St Andrei Șaguna, Metropolitan of Transylvania": u"Sfântul Ierarh Andrei Șaguna, mitropolitul Transilvaniei",
    "St Gheorghe of Cernica": u"Cuviosul Gheorghe de la Cernica",
    "St Dosoftei, Metropolitan of Moldavia": u"Sfântul Ierarh Dosoftei, mitropolitul Moldovei",
    "St Daniil the Hesychast": u"Cuviosul Daniil Sihastrul",
    "St Nicodim of Tismana": u"Cuviosul Nicodim de la Tismana",
    "St Seraphim of Sarov": u"Cuviosul Serafim de Sarov",
    "St Theophan the Recluse": u"Sfântul Ierarh Teofan Zăvorâtul",
    "St Xenia of St Petersburg": u"Fericita Xenia din Petersburg",
    "St Ignatius (Brianchaninov), Bishop of the Caucasus": u"Sfântul Ierarh Ignatie Briancianinov, episcopul Caucazului",
    "St Vladimir, Equal-to-the-Apostles": u"Sfântul Vladimir, întocmai cu apostolii",
    "St Sergius of Radonezh": u"Cuviosul Serghie de Radonej",
    "St Ambrose of Optina": u"Cuviosul Ambrozie de la Optina",
    "Synaxis of the Optina Elders": u"Soborul stareților de la Optina",
    "St Sava, First Archbishop of Serbia": u"Sfântul Sava, întâiul arhiepiscop al Serbiei",
    "St Simeon the Myrrh-gusher": u"Cuviosul Simeon Izvorâtorul de Mir",
    "St Basil of Ostrog": u"Sfântul Ierarh Vasile de la Ostrog",
    "St Justin Popovich of Ćelije": u"Cuviosul Iustin Popovici de la Celie",
    "St Petar of Koriša": u"Cuviosul Petru de la Koriša",
    "Holy Great-martyr Tsar Lazar (Vidovdan)": u"Sfântul Mare Mucenic Țarul Lazăr (Vidovdan)",
    "St Jefrem, Patriarch of Serbia": u"Sfântul Ierarh Efrem, patriarhul Serbiei",
    "St Angelina of Serbia": u"Cuvioasa Anghelina a Serbiei",
    "Synaxis of the Holy Hierarchs of Serbia": u"Soborul Sfinților Ierarhi ai Serbiei",
    "The New Martyrs of Jasenovac": u"Sfinții Noi Mucenici de la Iasenovaț",
    "St Stefan Vladislav, King of Serbia": u"Sfântul Rege Ștefan Vladislav al Serbiei",
    "St Petar of Cetinje, Wonderworker": u"Sfântul Ierarh Petru de la Cetinje, făcătorul de minuni",
    "St Prohor of Pčinja": u"Cuviosul Prohor de la Pcinia",
    "St Milutin the King and St Jelena the Queen of Serbia": u"Sfântul Rege Milutin și Sfânta Regină Elena ai Serbiei",
    "St Stefan Dečanski, King of Serbia": u"Sfântul Rege Ștefan Decianski",
    "St Sebastian of Jackson": u"Cuviosul Sebastian din Jackson",
    "St Joanikije of Devič": u"Cuviosul Ioanichie de la Devici",
    "St Danilo II, Archbishop of Serbia": u"Sfântul Ierarh Danilo al II-lea, arhiepiscopul Serbiei",
    "St Amphilochius of Pochaiv": u"Cuviosul Amfilohie de la Poceaev",
    "St Feodosii of the Kyiv Caves": u"Cuviosul Teodosie de la Peșterile Kievului",
    "St Antonii of the Kyiv Caves": u"Cuviosul Antonie de la Peșterile Kievului",
    "St Olha, Equal-to-the-Apostles": u"Sfânta Olga, întocmai cu apostolii",
    "St Volodymyr, Equal-to-the-Apostles": u"Sfântul Volodimir, întocmai cu apostolii",
    "St Petro Mohyla, Metropolitan of Kyiv": u"Sfântul Ierarh Petru Movilă, mitropolitul Kievului",
    "Synaxis of All Saints of Antioch": u"Soborul tuturor sfinților din Antiohia",
    "Synaxis of All Bulgarian Saints": u"Soborul tuturor sfinților bulgari",
    "Synaxis of All Saints of Mount Athos": u"Soborul tuturor cuvioșilor părinți athoniți",
    "Synaxis of All Saints of North America": u"Soborul tuturor sfinților din America de Nord",
    "Synaxis of All Venerable Fathers of the Kyiv Caves": u"Soborul tuturor cuvioșilor părinți de la Peșterile Kievului",
    "Synaxis of All Romanian Saints": u"Soborul tuturor sfinților români",
    "Synaxis of All Saints of Russia": u"Soborul tuturor sfinților ruși",
    "Synaxis of All Saints of Ukraine": u"Soborul tuturor sfinților ucraineni",
    "St Raphael, Bishop of Brooklyn": u"Sfântul Ierarh Rafail, episcopul Brooklynului",
}
