# -*- coding: utf-8 -*-
"""The Churches' own commemorations, in Russian.

See docs/LOCAL_NAMES.md.
"""
TEXT = {
    "St Isaac the Syrian": u"преподобный Исаак Сирин",
    "Martyr Elian of Homs": u"мученик Илиан Эмесский",
    "St Joseph of Damascus & the New Martyrs of Damascus (1860)": u"священномученик Иосиф Дамасский и новомученики Дамасские (1860)",
    "Hieromartyrs Nicholas and Habib Khasha of Damascus": u"священномученики Николай и Хабиб Хаша Дамасские",
    "St Gabriel of Lesnovo": u"преподобный Гавриил Лесновский",
    "St Joachim I, Patriarch of Tarnovo": u"святитель Иоаким I, патриарх Тырновский",
    "St Euthymius, Patriarch of Tarnovo": u"святитель Евфимий, патриарх Тырновский",
    "St Peter, King of Bulgaria": u"благоверный царь Петр Болгарский",
    "St Romanus of Tarnovo": u"преподобный Роман Тырновский",
    "St Sophronius, Bishop of Vratsa": u"святитель Софроний, епископ Врачанский",
    "St Boris-Michael, Equal-to-the-Apostles, Baptizer of Bulgaria": u"равноапостольный царь Борис-Михаил, креститель Болгарии",
    "Great Martyr Nicholas of Sofia": u"великомученик Николай Софийский",
    "St Paisius of Hilendar": u"преподобный Паисий Хилендарский",
    "The Seven Holy Apostles (Sedmochislenitsi)": u"святые Седмочисленники",
    "St Joachim of Osogovo": u"преподобный Иоаким Осоговский",
    "Repose of St John of Rila": u"Преставление преподобного Иоанна Рыльского",
    "New Martyr Simeon of Samokov": u"новомученик Симеон Самоковский",
    "St Cosmas of Zographou": u"преподобный Косма Зографский",
    "The 26 Martyrs of Zographou": u"26 мучеников Зографских",
    "St Demetrius of Basarbovo": u"преподобный Димитрий Басарбовский",
    "Venerable Pimen of Zographou": u"преподобный Пимен Зографский",
    "Righteous Michael the Soldier of Bulgaria": u"праведный Михаил воин Болгарский",
    "St Theodosius of Tarnovo": u"преподобный Феодосий Тырновский",
    "St Nektarios the Bulgarian of Bitola": u"преподобномученик Нектарий Битольский",
    "St Nahum of Ohrid": u"преподобный Наум Охридский",
    "Ss Salome of Ujarma and Perozhavra of Sivnia": u"праведные Саломия Уджармская и Перожавра Сивнийская",
    "St Eprem the Lesser, the Philosopher": u"преподобный Ефрем Мцире, философ",
    "St David IV the Builder, King of Georgia": u"благоверный Давид IV Строитель, царь Грузии",
    "St Ioane the Catholicos": u"святитель Иоанн, католикос Грузии",
    "Holy King Demetre the Devoted": u"благоверный царь Димитрий II Самопожертвователь",
    "St Ambrosi the Confessor, Catholicos-Patriarch of All Georgia": u"святитель Амвросий исповедник, католикос-патриарх всея Грузии",
    "Venerable David of the Gareji Monastery": u"преподобный Давид Гареджийский",
    "St Tamar, Queen of Georgia": u"благоверная царица Тамара",
    "Venerable Ioane of Zedazeni and his Twelve Disciples": u"преподобный Иоанн Зедазнийский и двенадцать его учеников",
    "Venerable Ekvtime of Mount Athos, the Translator": u"преподобный Евфимий Святогорец, переводчик",
    "St George the Hagiorite, and Hieromartyr Kirion II, Catholicos-Patriarch": u"преподобный Георгий Святогорец и священномученик Кирион II, католикос-патриарх",
    "St Ilia the Righteous": u"праведный Илия Чавчавадзе",
    "Holy Martyr Evstati of Mtskheta": u"мученик Евстафий Мцхетский",
    "St Tsotne Dadiani the Confessor": u"благоверный Цотнэ Дадиани исповедник",
    "St Razhden, Protomartyr of Georgia, and the Nine Kherkheulidze Brothers": u"первомученик Ражден Персиянин и девять братьев Херхеулидзе",
    "Holy Confessors Ioane and Giorgi-Ioane of Betania": u"преподобные исповедники Иоанн и Георгий-Иоанн Бетанийские",
    "Holy Great-martyr Queen Ketevan": u"великомученица царица Кетеван",
    "Holy Martyrs Bidzina, Shalva and Elizbar": u"мученики Бидзина, Шалва и Элизбар",
    "Venerable Grigol of Khandzta": u"преподобный Григорий Хандзтийский",
    "St Gabriel of Samtavro, Confessor and Fool for Christ": u"преподобный Гавриил Самтаврийский, исповедник и Христа ради юродивый",
    "The 100,000 Martyrs of Tbilisi": u"100 000 мучеников Тбилисских",
    "Holy King Vakhtang Gorgasali": u"благоверный царь Вахтанг Горгасали",
    "St Ise of Tsilkani": u"святитель Иессей Цилканский",
    "Synaxis of All Saints of Georgia": u"Собор всех святых, в земле Грузинской просиявших",
    "Venerable Giorgi the Scribe and his brother Saba of Khakhuli": u"преподобные Георгий Писатель и брат его Савва Хахульские",
    "St Nikephoros the Leper": u"преподобный Никифор Прокаженный",
    "St Arsenios of Paros": u"преподобный Арсений Паросский",
    "St Ephraim of Katounakia": u"преподобный Ефрем Катунакский",
    "St Nikolaos Planas of Athens": u"праведный Николай Планас Афинский",
    "St Savvas the New of Kalymnos": u"преподобный Савва Новый Калимносский",
    "St Amphilochios of Patmos": u"преподобный Амфилохий Патмосский",
    "St Joseph the Hesychast": u"преподобный Иосиф Исихаст",
    "St Kosmas Aitolos, Equal-to-the-Apostles": u"равноапостольный Косма Этолийский",
    "St Arsenios of Cappadocia": u"преподобный Арсений Каппадокийский",
    "St Iakovos of Evia": u"преподобный Иаков Эвбейский",
    "St Antipa of Calapodești": u"преподобный Антипа Калаподештский",
    "St Calinic of Cernica": u"святитель Каллиник Черникский",
    "St Pahomie of Gledin, Bishop of Roman": u"святитель Пахомий Глединский, епископ Романский",
    "Ss Ilie Iorest, Sava Brancovici and Simion Ștefan, Metropolitans of Transylvania": u"святители Илия Иорест, Савва Бранкович и Симеон Штефан, митрополиты Трансильванские",
    "St Irodion of Lainici": u"преподобный Иродион Лайничский",
    "St John the Wallachian, Martyr": u"мученик Иоанн Валах",
    "St Iacob Putneanul, Metropolitan of Moldavia": u"святитель Иаков Путнянский, митрополит Молдавский",
    "St Grigorie Dascălul, Metropolitan of Wallachia": u"святитель Григорий Дэскэлул, митрополит Валашский",
    "St Ghelasie of Râmeț": u"преподобный Гелазий Рымецкий",
    "St Leontie of Rădăuți": u"святитель Леонтий Рэдэуцкий",
    "St Stephen the Great": u"благоверный Стефан Великий, господарь Молдавский",
    "St Ioanichie the New of Muscel": u"преподобный Иоанникий Новый Мушчелский",
    "St Ioan Iacob of Neamț": u"преподобный Иоанн Иаков Нямецкий",
    "St Teodora of Sihla": u"преподобная Феодора Сихлская",
    "The Brâncoveanu Martyrs: Prince Constantin and his four sons": u"Мученики Брынковяну: господарь Константин и четыре его сына",
    "St Iosif the New of Partoș, Metropolitan of Banat": u"святитель Иосиф Новый Партошский, митрополит Банатский",
    "St Neagoe Basarab, Voivode of Wallachia": u"благоверный Нягое Басараб, господарь Валашский",
    "St Antim Ivireanul, Hieromartyr, Metropolitan of Wallachia": u"священномученик Антим Ивериец, митрополит Валашский",
    "St Parascheva of Iași": u"преподобная Параскева Ясская",
    "St Dimitrie the New of Bucharest": u"преподобный Димитрий Новый Бухарестский",
    "St Iachint, Metropolitan of Wallachia": u"святитель Иакинф, митрополит Валашский",
    "St Andrei Șaguna, Metropolitan of Transylvania": u"святитель Андрей Шагуна, митрополит Трансильванский",
    "St Gheorghe of Cernica": u"преподобный Георгий Черникский",
    "St Dosoftei, Metropolitan of Moldavia": u"святитель Досифей, митрополит Молдавский",
    "St Daniil the Hesychast": u"преподобный Даниил Исихаст",
    "St Nicodim of Tismana": u"преподобный Никодим Тисманский",
    "St Seraphim of Sarov": u"преподобный Серафим Саровский",
    "St Theophan the Recluse": u"святитель Феофан Затворник",
    "St Xenia of St Petersburg": u"блаженная Ксения Петербургская",
    "St Ignatius (Brianchaninov), Bishop of the Caucasus": u"святитель Игнатий (Брянчанинов), епископ Кавказский",
    "St Vladimir, Equal-to-the-Apostles": u"равноапостольный великий князь Владимир",
    "St Sergius of Radonezh": u"преподобный Сергий Радонежский",
    "St Ambrose of Optina": u"преподобный Амвросий Оптинский",
    "Synaxis of the Optina Elders": u"Собор преподобных Оптинских старцев",
    "St Sava, First Archbishop of Serbia": u"святитель Савва, первый архиепископ Сербский",
    "St Simeon the Myrrh-gusher": u"преподобный Симеон Мироточивый",
    "St Basil of Ostrog": u"святитель Василий Острожский",
    "St Justin Popovich of Ćelije": u"преподобный Иустин (Попович) Челийский",
    "St Petar of Koriša": u"преподобный Петр Коришский",
    "Holy Great-martyr Tsar Lazar (Vidovdan)": u"великомученик царь Лазарь (Видовдан)",
    "St Jefrem, Patriarch of Serbia": u"святитель Ефрем, патриарх Сербский",
    "St Angelina of Serbia": u"преподобная Ангелина Сербская",
    "Synaxis of the Holy Hierarchs of Serbia": u"Собор святителей Сербских",
    "The New Martyrs of Jasenovac": u"новомученики Ясеновацкие",
    "St Stefan Vladislav, King of Serbia": u"благоверный Стефан Владислав, король Сербский",
    "St Petar of Cetinje, Wonderworker": u"святитель Петр Цетинский, чудотворец",
    "St Prohor of Pčinja": u"преподобный Прохор Пшинский",
    "St Milutin the King and St Jelena the Queen of Serbia": u"благоверные Милутин король и Елена королева Сербские",
    "St Stefan Dečanski, King of Serbia": u"благоверный Стефан Дечанский, король Сербский",
    "St Sebastian of Jackson": u"преподобный Севастиан Джексонский",
    "St Joanikije of Devič": u"преподобный Иоанникий Девичский",
    "St Danilo II, Archbishop of Serbia": u"святитель Даниил II, архиепископ Сербский",
    "St Amphilochius of Pochaiv": u"преподобный Амфилохий Почаевский",
    "St Feodosii of the Kyiv Caves": u"преподобный Феодосий Печерский",
    "St Antonii of the Kyiv Caves": u"преподобный Антоний Печерский",
    "St Olha, Equal-to-the-Apostles": u"равноапостольная великая княгиня Ольга",
    "St Volodymyr, Equal-to-the-Apostles": u"равноапостольный великий князь Владимир",
    "St Petro Mohyla, Metropolitan of Kyiv": u"святитель Петр Могила, митрополит Киевский",
    "Synaxis of All Saints of Antioch": u"Собор всех святых Антиохийских",
    "Synaxis of All Bulgarian Saints": u"Собор всех святых, в земле Болгарской просиявших",
    "Synaxis of All Saints of Mount Athos": u"Собор всех преподобных отцов Афонских",
    "Synaxis of All Saints of North America": u"Собор всех святых, в земле Северо-Американской просиявших",
    "Synaxis of All Venerable Fathers of the Kyiv Caves": u"Собор всех преподобных отцов Киево-Печерских",
    "Synaxis of All Romanian Saints": u"Собор всех святых, в земле Румынской просиявших",
    "Synaxis of All Saints of Russia": u"Собор всех святых, в земле Русской просиявших",
    "Synaxis of All Saints of Ukraine": u"Собор всех святых, в земле Украинской просиявших",
    "St Raphael, Bishop of Brooklyn": u"святитель Рафаил, епископ Бруклинский",
}
