# -*- coding: utf-8 -*-
"""The Churches' own commemorations, in Serbian.

Cyrillic and ekavian, as the rest of the calendar's Serbian is.

See docs/LOCAL_NAMES.md.
"""
TEXT = {
    "St Isaac the Syrian": u"Преподобни Исаак Сирин",
    "Martyr Elian of Homs": u"Свети мученик Илијан Емески",
    "St Joseph of Damascus & the New Martyrs of Damascus (1860)": u"Свештеномученик Јосиф Дамаскин и новомученици дамаскински (1860)",
    "Hieromartyrs Nicholas and Habib Khasha of Damascus": u"Свештеномученици Никола и Хабиб Хаша дамаскински",
    "St Gabriel of Lesnovo": u"Преподобни Гаврило Лесновски",
    "St Joachim I, Patriarch of Tarnovo": u"Свети Јоаким I, патријарх трновски",
    "St Euthymius, Patriarch of Tarnovo": u"Свети Јефтимије, патријарх трновски",
    "St Peter, King of Bulgaria": u"Свети цар Петар Бугарски",
    "St Romanus of Tarnovo": u"Преподобни Роман Трновски",
    "St Sophronius, Bishop of Vratsa": u"Свети Софроније, епископ врачански",
    "St Boris-Michael, Equal-to-the-Apostles, Baptizer of Bulgaria": u"Свети равноапостолни цар Борис-Михаило, крститељ Бугарске",
    "Great Martyr Nicholas of Sofia": u"Свети великомученик Никола Софијски",
    "St Paisius of Hilendar": u"Преподобни Пајсије Хиландарац",
    "The Seven Holy Apostles (Sedmochislenitsi)": u"Свети Седмочисленици",
    "St Joachim of Osogovo": u"Преподобни Јоаким Осоговски",
    "Repose of St John of Rila": u"Упокојење преподобног Јована Рилског",
    "New Martyr Simeon of Samokov": u"Свети новомученик Симеон Самоковски",
    "St Cosmas of Zographou": u"Преподобни Козма Зографски",
    "The 26 Martyrs of Zographou": u"26 мученика зографских",
    "St Demetrius of Basarbovo": u"Преподобни Димитрије Басарбовски",
    "Venerable Pimen of Zographou": u"Преподобни Пимен Зографски",
    "Righteous Michael the Soldier of Bulgaria": u"Праведни Михаило војник бугарски",
    "St Theodosius of Tarnovo": u"Преподобни Теодосије Трновски",
    "St Nektarios the Bulgarian of Bitola": u"Преподобномученик Нектарије Битољски",
    "St Nahum of Ohrid": u"Преподобни Наум Охридски",
    "Ss Salome of Ujarma and Perozhavra of Sivnia": u"Праведне Саломија Ујармска и Перожавра Сивнијска",
    "St Eprem the Lesser, the Philosopher": u"Преподобни Јефрем Мцире, философ",
    "St David IV the Builder, King of Georgia": u"Свети благоверни Давид IV Обновитељ, цар Грузије",
    "St Ioane the Catholicos": u"Свети Јован, католикос грузијски",
    "Holy King Demetre the Devoted": u"Свети благоверни цар Димитрије II Самопожртвовани",
    "St Ambrosi the Confessor, Catholicos-Patriarch of All Georgia": u"Свети Амвросије исповедник, католикос-патријарх све Грузије",
    "Venerable David of the Gareji Monastery": u"Преподобни Давид Гаређијски",
    "St Tamar, Queen of Georgia": u"Света благоверна царица Тамара",
    "Venerable Ioane of Zedazeni and his Twelve Disciples": u"Преподобни Јован Зедазнијски и дванаест његових ученика",
    "Venerable Ekvtime of Mount Athos, the Translator": u"Преподобни Јевтимије Светогорац, преводилац",
    "St George the Hagiorite, and Hieromartyr Kirion II, Catholicos-Patriarch": u"Преподобни Георгије Светогорац и свештеномученик Кирион II, католикос-патријарх",
    "St Ilia the Righteous": u"Праведни Илија Чавчавадзе",
    "Holy Martyr Evstati of Mtskheta": u"Свети мученик Јевстатије Мцхетски",
    "St Tsotne Dadiani the Confessor": u"Свети благоверни Цотне Дадијани исповедник",
    "St Razhden, Protomartyr of Georgia, and the Nine Kherkheulidze Brothers": u"Свети првомученик Ражден Персијанац и деветорица браће Херхеулидзе",
    "Holy Confessors Ioane and Giorgi-Ioane of Betania": u"Свети исповедници Јован и Георгије-Јован бетанијски",
    "Holy Great-martyr Queen Ketevan": u"Света великомученица царица Кетевана",
    "Holy Martyrs Bidzina, Shalva and Elizbar": u"Свети мученици Бидзина, Шалва и Елизбар",
    "Venerable Grigol of Khandzta": u"Преподобни Григорије Хандзтијски",
    "St Gabriel of Samtavro, Confessor and Fool for Christ": u"Преподобни Гаврило Самтаврски, исповедник и јуродиви Христа ради",
    "The 100,000 Martyrs of Tbilisi": u"100 000 мученика тбилиских",
    "Holy King Vakhtang Gorgasali": u"Свети благоверни цар Вахтанг Горгасали",
    "St Ise of Tsilkani": u"Свети Јесеј Цилкански",
    "Synaxis of All Saints of Georgia": u"Сабор свих светих грузијских",
    "Venerable Giorgi the Scribe and his brother Saba of Khakhuli": u"Преподобни Георгије Писар и брат његов Сава Хахулски",
    "St Nikephoros the Leper": u"Преподобни Никифор Губави",
    "St Arsenios of Paros": u"Преподобни Арсеније Пароски",
    "St Ephraim of Katounakia": u"Преподобни Јефрем Катунакијски",
    "St Nikolaos Planas of Athens": u"Праведни Никола Планас атински",
    "St Savvas the New of Kalymnos": u"Преподобни Сава Нови Калимноски",
    "St Amphilochios of Patmos": u"Преподобни Амфилохије Патмоски",
    "St Joseph the Hesychast": u"Преподобни Јосиф Исихаста",
    "St Kosmas Aitolos, Equal-to-the-Apostles": u"Свети равноапостолни Козма Етолски",
    "St Arsenios of Cappadocia": u"Преподобни Арсеније Кападокијски",
    "St Iakovos of Evia": u"Преподобни Јаков Евбејски",
    "St Antipa of Calapodești": u"Преподобни Антипа Калаподештски",
    "St Calinic of Cernica": u"Свети Калиник Черникски",
    "St Pahomie of Gledin, Bishop of Roman": u"Свети Пахомије Гледински, епископ романски",
    "Ss Ilie Iorest, Sava Brancovici and Simion Ștefan, Metropolitans of Transylvania": u"Свети Илија Јорест, Сава Бранковић и Симеон Штефан, митрополити ердељски",
    "St Irodion of Lainici": u"Преподобни Иродион Лајнички",
    "St John the Wallachian, Martyr": u"Свети мученик Јован Влах",
    "St Iacob Putneanul, Metropolitan of Moldavia": u"Свети Јаков Путњански, митрополит молдавски",
    "St Grigorie Dascălul, Metropolitan of Wallachia": u"Свети Григорије Даскал, митрополит влашки",
    "St Ghelasie of Râmeț": u"Преподобни Геласије Ремецки",
    "St Leontie of Rădăuți": u"Свети Леонтије Радаутски",
    "St Stephen the Great": u"Свети благоверни Стефан Велики, господар молдавски",
    "St Ioanichie the New of Muscel": u"Преподобни Јоаникије Нови Мушчелски",
    "St Ioan Iacob of Neamț": u"Преподобни Јован Јаков Њамацки",
    "St Teodora of Sihla": u"Преподобна Теодора Сихланска",
    "The Brâncoveanu Martyrs: Prince Constantin and his four sons": u"Мученици Бранковјану: господар Константин и четири његова сина",
    "St Iosif the New of Partoș, Metropolitan of Banat": u"Свети Јосиф Нови Партошки, митрополит банатски",
    "St Neagoe Basarab, Voivode of Wallachia": u"Свети благоверни Њагое Басараб, господар влашки",
    "St Antim Ivireanul, Hieromartyr, Metropolitan of Wallachia": u"Свештеномученик Антим Иверски, митрополит влашки",
    "St Parascheva of Iași": u"Преподобна Петка Јашка",
    "St Dimitrie the New of Bucharest": u"Преподобни Димитрије Нови Букурешки",
    "St Iachint, Metropolitan of Wallachia": u"Свети Јакинт, митрополит влашки",
    "St Andrei Șaguna, Metropolitan of Transylvania": u"Свети Андреј Шагуна, митрополит ердељски",
    "St Gheorghe of Cernica": u"Преподобни Георгије Черникски",
    "St Dosoftei, Metropolitan of Moldavia": u"Свети Доситеј, митрополит молдавски",
    "St Daniil the Hesychast": u"Преподобни Данило Исихаста",
    "St Nicodim of Tismana": u"Преподобни Никодим Тисмански",
    "St Seraphim of Sarov": u"Преподобни Серафим Саровски",
    "St Theophan the Recluse": u"Свети Теофан Затворник",
    "St Xenia of St Petersburg": u"Блажена Ксенија Петроградска",
    "St Ignatius (Brianchaninov), Bishop of the Caucasus": u"Свети Игњатије (Брјанчанинов), епископ кавкаски",
    "St Vladimir, Equal-to-the-Apostles": u"Свети равноапостолни кнез Владимир",
    "St Sergius of Radonezh": u"Преподобни Сергије Радоњешки",
    "St Ambrose of Optina": u"Преподобни Амвросије Оптински",
    "Synaxis of the Optina Elders": u"Сабор преподобних оптинских стараца",
    "St Sava, First Archbishop of Serbia": u"Свети Сава, први архиепископ српски",
    "St Simeon the Myrrh-gusher": u"Преподобни Симеон Мироточиви",
    "St Basil of Ostrog": u"Свети Василије Острошки",
    "St Justin Popovich of Ćelije": u"Преподобни Јустин Ћелијски",
    "St Petar of Koriša": u"Преподобни Петар Коришки",
    "Holy Great-martyr Tsar Lazar (Vidovdan)": u"Свети великомученик цар Лазар (Видовдан)",
    "St Jefrem, Patriarch of Serbia": u"Свети Јефрем, патријарх српски",
    "St Angelina of Serbia": u"Преподобна мати Ангелина српска",
    "Synaxis of the Holy Hierarchs of Serbia": u"Сабор српских светитеља",
    "The New Martyrs of Jasenovac": u"Свети новомученици јасеновачки",
    "St Stefan Vladislav, King of Serbia": u"Свети краљ Стефан Владислав",
    "St Petar of Cetinje, Wonderworker": u"Свети Петар Цетињски, чудотворац",
    "St Prohor of Pčinja": u"Преподобни Прохор Пчињски",
    "St Milutin the King and St Jelena the Queen of Serbia": u"Свети краљ Милутин и света краљица Јелена српска",
    "St Stefan Dečanski, King of Serbia": u"Свети краљ Стефан Дечански",
    "St Sebastian of Jackson": u"Преподобни Севастијан Џексонски",
    "St Joanikije of Devič": u"Преподобни Јоаникије Девички",
    "St Danilo II, Archbishop of Serbia": u"Свети Данило II, архиепископ српски",
    "St Amphilochius of Pochaiv": u"Преподобни Амфилохије Почајевски",
    "St Feodosii of the Kyiv Caves": u"Преподобни Теодосије Печерски",
    "St Antonii of the Kyiv Caves": u"Преподобни Антоније Печерски",
    "St Olha, Equal-to-the-Apostles": u"Света равноапостолна кнегиња Олга",
    "St Volodymyr, Equal-to-the-Apostles": u"Свети равноапостолни кнез Владимир",
    "St Petro Mohyla, Metropolitan of Kyiv": u"Свети Петар Могила, митрополит кијевски",
    "Synaxis of All Saints of Antioch": u"Сабор свих светих антиохијских",
    "Synaxis of All Bulgarian Saints": u"Сабор свих светих бугарских",
    "Synaxis of All Saints of Mount Athos": u"Сабор свих преподобних отаца светогорских",
    "Synaxis of All Saints of North America": u"Сабор свих светих северноамеричких",
    "Synaxis of All Venerable Fathers of the Kyiv Caves": u"Сабор свих преподобних отаца кијевопечерских",
    "Synaxis of All Romanian Saints": u"Сабор свих светих румунских",
    "Synaxis of All Saints of Russia": u"Сабор свих светих руских",
    "Synaxis of All Saints of Ukraine": u"Сабор свих светих украјинских",
    "St Raphael, Bishop of Brooklyn": u"Свети Рафаило, епископ бруклински",
}
