# -*- coding: utf-8 -*-
"""The Churches' own commemorations, in Swahili.

See docs/LOCAL_NAMES.md.
"""
TEXT = {
    "St Isaac the Syrian": u"Mheshimiwa Isaka wa Siria",
    "Martyr Elian of Homs": u"Shahidi Elian wa Homs",
    "St Joseph of Damascus & the New Martyrs of Damascus (1860)": u"Kuhani Shahidi Yosefu wa Damasko na Mashahidi Wapya wa Damasko (1860)",
    "Hieromartyrs Nicholas and Habib Khasha of Damascus": u"Makuhani Mashahidi Nikolao na Habib Khasha wa Damasko",
    "St Gabriel of Lesnovo": u"Mheshimiwa Gabrieli wa Lesnovo",
    "St Joachim I, Patriarch of Tarnovo": u"Mtakatifu Yoakimu wa Kwanza, Patriaki wa Tarnovo",
    "St Euthymius, Patriarch of Tarnovo": u"Mtakatifu Euthymio, Patriaki wa Tarnovo",
    "St Peter, King of Bulgaria": u"Mtakatifu Petro, Mfalme wa Bulgaria",
    "St Romanus of Tarnovo": u"Mheshimiwa Romano wa Tarnovo",
    "St Sophronius, Bishop of Vratsa": u"Mtakatifu Sofronio, Askofu wa Vratsa",
    "St Boris-Michael, Equal-to-the-Apostles, Baptizer of Bulgaria": u"Mtakatifu Boris-Mikaeli, Sawa na Mitume, Mbatizaji wa Bulgaria",
    "Great Martyr Nicholas of Sofia": u"Shahidi Mkuu Nikolao wa Sofia",
    "St Paisius of Hilendar": u"Mheshimiwa Paisio wa Hilandar",
    "The Seven Holy Apostles (Sedmochislenitsi)": u"Mitume Watakatifu Saba (Sedmochislenitsi)",
    "St Joachim of Osogovo": u"Mheshimiwa Yoakimu wa Osogovo",
    "Repose of St John of Rila": u"Kupumzika kwa Mheshimiwa Yohane wa Rila",
    "New Martyr Simeon of Samokov": u"Shahidi Mpya Simeoni wa Samokov",
    "St Cosmas of Zographou": u"Mheshimiwa Kosma wa Zografou",
    "The 26 Martyrs of Zographou": u"Mashahidi 26 wa Zografou",
    "St Demetrius of Basarbovo": u"Mheshimiwa Dimitri wa Basarbovo",
    "Venerable Pimen of Zographou": u"Mheshimiwa Pimen wa Zografou",
    "Righteous Michael the Soldier of Bulgaria": u"Mwenye Haki Mikaeli Askari wa Bulgaria",
    "St Theodosius of Tarnovo": u"Mheshimiwa Theodosio wa Tarnovo",
    "St Nektarios the Bulgarian of Bitola": u"Mheshimiwa Shahidi Nektario wa Bitola",
    "St Nahum of Ohrid": u"Mheshimiwa Nahumu wa Ohrid",
    "Ss Salome of Ujarma and Perozhavra of Sivnia": u"Wenye Haki Salome wa Ujarma na Perozhavra wa Sivnia",
    "St Eprem the Lesser, the Philosopher": u"Mheshimiwa Eprem Mdogo, Mwanafalsafa",
    "St David IV the Builder, King of Georgia": u"Mtakatifu Daudi wa Nne Mjenzi, Mfalme wa Georgia",
    "St Ioane the Catholicos": u"Mtakatifu Yohane, Katoliko wa Georgia",
    "Holy King Demetre the Devoted": u"Mtakatifu Demetre Mfalme Aliyejitoa",
    "St Ambrosi the Confessor, Catholicos-Patriarch of All Georgia": u"Mtakatifu Ambrosi Mkiri, Katoliko-Patriaki wa Georgia Yote",
    "Venerable David of the Gareji Monastery": u"Mheshimiwa Daudi wa Monasteri ya Gareji",
    "St Tamar, Queen of Georgia": u"Mtakatifu Tamar, Malkia wa Georgia",
    "Venerable Ioane of Zedazeni and his Twelve Disciples": u"Mheshimiwa Yohane wa Zedazeni na Wanafunzi wake Kumi na Wawili",
    "Venerable Ekvtime of Mount Athos, the Translator": u"Mheshimiwa Ekvtime wa Mlima Athos, Mfasiri",
    "St George the Hagiorite, and Hieromartyr Kirion II, Catholicos-Patriarch": u"Mheshimiwa Giorgi wa Mlima Athos na Kuhani Shahidi Kirion wa Pili, Katoliko-Patriaki",
    "St Ilia the Righteous": u"Mwenye Haki Ilia",
    "Holy Martyr Evstati of Mtskheta": u"Shahidi Evstati wa Mtskheta",
    "St Tsotne Dadiani the Confessor": u"Mtakatifu Tsotne Dadiani Mkiri",
    "St Razhden, Protomartyr of Georgia, and the Nine Kherkheulidze Brothers": u"Shahidi wa Kwanza Razhden wa Georgia na Ndugu Tisa wa Kherkheulidze",
    "Holy Confessors Ioane and Giorgi-Ioane of Betania": u"Wakiri Watakatifu Yohane na Giorgi-Yohane wa Betania",
    "Holy Great-martyr Queen Ketevan": u"Shahidi Mkuu Malkia Ketevan",
    "Holy Martyrs Bidzina, Shalva and Elizbar": u"Mashahidi Bidzina, Shalva na Elizbar",
    "Venerable Grigol of Khandzta": u"Mheshimiwa Grigol wa Khandzta",
    "St Gabriel of Samtavro, Confessor and Fool for Christ": u"Mheshimiwa Gabrieli wa Samtavro, Mkiri na Mpumbavu kwa ajili ya Kristo",
    "The 100,000 Martyrs of Tbilisi": u"Mashahidi 100,000 wa Tbilisi",
    "Holy King Vakhtang Gorgasali": u"Mtakatifu Vakhtang Gorgasali, Mfalme wa Georgia",
    "St Ise of Tsilkani": u"Mtakatifu Ise wa Tsilkani",
    "Synaxis of All Saints of Georgia": u"Watakatifu Wote wa Georgia",
    "Venerable Giorgi the Scribe and his brother Saba of Khakhuli": u"Waheshimiwa Giorgi Mwandishi na ndugu yake Saba wa Khakhuli",
    "St Nikephoros the Leper": u"Mheshimiwa Nikiforo Mkoma",
    "St Arsenios of Paros": u"Mheshimiwa Arsenio wa Paros",
    "St Ephraim of Katounakia": u"Mheshimiwa Efraimu wa Katounakia",
    "St Nikolaos Planas of Athens": u"Mwenye Haki Nikolao Planas wa Athene",
    "St Savvas the New of Kalymnos": u"Mheshimiwa Savva Mpya wa Kalymnos",
    "St Amphilochios of Patmos": u"Mheshimiwa Amfilokio wa Patmos",
    "St Joseph the Hesychast": u"Mheshimiwa Yosefu Mkimya",
    "St Kosmas Aitolos, Equal-to-the-Apostles": u"Mtakatifu Kosmas Aitolos, Sawa na Mitume",
    "St Arsenios of Cappadocia": u"Mheshimiwa Arsenio wa Kapadokia",
    "St Iakovos of Evia": u"Mheshimiwa Yakobo wa Evia",
    "St Antipa of Calapodești": u"Mheshimiwa Antipa wa Calapodesti",
    "St Calinic of Cernica": u"Mtakatifu Calinic wa Cernica",
    "St Pahomie of Gledin, Bishop of Roman": u"Mtakatifu Pahomie wa Gledin, Askofu wa Roman",
    "Ss Ilie Iorest, Sava Brancovici and Simion Ștefan, Metropolitans of Transylvania": u"Watakatifu Ilie Iorest, Sava Brancovici na Simion Stefan, Mametropolita wa Transilvania",
    "St Irodion of Lainici": u"Mheshimiwa Irodion wa Lainici",
    "St John the Wallachian, Martyr": u"Shahidi Yohane wa Wallachia",
    "St Iacob Putneanul, Metropolitan of Moldavia": u"Mtakatifu Iacob Putneanul, Metropolita wa Moldavia",
    "St Grigorie Dascălul, Metropolitan of Wallachia": u"Mtakatifu Grigorie Dascalul, Metropolita wa Wallachia",
    "St Ghelasie of Râmeț": u"Mtakatifu Ghelasie wa Ramet",
    "St Leontie of Rădăuți": u"Mtakatifu Leontie wa Radauti",
    "St Stephen the Great": u"Mtakatifu Stefano Mkuu",
    "St Ioanichie the New of Muscel": u"Mheshimiwa Ioanichie Mpya wa Muscel",
    "St Ioan Iacob of Neamț": u"Mheshimiwa Ioan Iacob wa Neamt",
    "St Teodora of Sihla": u"Mheshimiwa Teodora wa Sihla",
    "The Brâncoveanu Martyrs: Prince Constantin and his four sons": u"Mashahidi wa Brancoveanu: Mkuu Constantin na wanawe wanne",
    "St Iosif the New of Partoș, Metropolitan of Banat": u"Mtakatifu Iosif Mpya wa Partos, Metropolita wa Banat",
    "St Neagoe Basarab, Voivode of Wallachia": u"Mtakatifu Neagoe Basarab, Mkuu wa Wallachia",
    "St Antim Ivireanul, Hieromartyr, Metropolitan of Wallachia": u"Kuhani Shahidi Antim Ivireanul, Metropolita wa Wallachia",
    "St Parascheva of Iași": u"Mheshimiwa Parascheva wa Iasi",
    "St Dimitrie the New of Bucharest": u"Mtakatifu Dimitrie Mpya wa Bucharest",
    "St Iachint, Metropolitan of Wallachia": u"Mtakatifu Iachint, Metropolita wa Wallachia",
    "St Andrei Șaguna, Metropolitan of Transylvania": u"Mtakatifu Andrei Saguna, Metropolita wa Transilvania",
    "St Gheorghe of Cernica": u"Mheshimiwa Gheorghe wa Cernica",
    "St Dosoftei, Metropolitan of Moldavia": u"Mtakatifu Dosoftei, Metropolita wa Moldavia",
    "St Daniil the Hesychast": u"Mheshimiwa Daniil Mkimya",
    "St Nicodim of Tismana": u"Mheshimiwa Nicodim wa Tismana",
    "St Seraphim of Sarov": u"Mtakatifu Serafimu wa Sarov",
    "St Theophan the Recluse": u"Mtakatifu Theophan Mfungwa",
    "St Xenia of St Petersburg": u"Mtakatifu Xenia wa St Petersburg",
    "St Ignatius (Brianchaninov), Bishop of the Caucasus": u"Mtakatifu Ignatio (Brianchaninov), Askofu wa Kaukasia",
    "St Vladimir, Equal-to-the-Apostles": u"Mtakatifu Vladimir, Sawa na Mitume",
    "St Sergius of Radonezh": u"Mtakatifu Sergio wa Radonezh",
    "St Ambrose of Optina": u"Mheshimiwa Ambrosi wa Optina",
    "Synaxis of the Optina Elders": u"Wazee Waheshimiwa wa Optina",
    "St Sava, First Archbishop of Serbia": u"Mtakatifu Sava, Askofu Mkuu wa kwanza wa Serbia",
    "St Simeon the Myrrh-gusher": u"Mtakatifu Simeoni Atiririkaye Manemane",
    "St Basil of Ostrog": u"Mtakatifu Basili wa Ostrog",
    "St Justin Popovich of Ćelije": u"Mheshimiwa Justin Popovich wa Celije",
    "St Petar of Koriša": u"Mheshimiwa Petar wa Korisa",
    "Holy Great-martyr Tsar Lazar (Vidovdan)": u"Shahidi Mkuu Mtakatifu Tsar Lazar (Vidovdan)",
    "St Jefrem, Patriarch of Serbia": u"Mtakatifu Jefrem, Patriaki wa Serbia",
    "St Angelina of Serbia": u"Mheshimiwa Angelina wa Serbia",
    "Synaxis of the Holy Hierarchs of Serbia": u"Maaskofu Watakatifu wa Serbia",
    "The New Martyrs of Jasenovac": u"Mashahidi Wapya wa Jasenovac",
    "St Stefan Vladislav, King of Serbia": u"Mtakatifu Stefan Vladislav, Mfalme wa Serbia",
    "St Petar of Cetinje, Wonderworker": u"Mtakatifu Petar wa Cetinje, Mtenda-Miujiza",
    "St Prohor of Pčinja": u"Mheshimiwa Prohor wa Pcinja",
    "St Milutin the King and St Jelena the Queen of Serbia": u"Mtakatifu Milutin Mfalme na Mtakatifu Jelena Malkia wa Serbia",
    "St Stefan Dečanski, King of Serbia": u"Mtakatifu Stefan Decanski, Mfalme wa Serbia",
    "St Sebastian of Jackson": u"Mheshimiwa Sebastian wa Jackson",
    "St Joanikije of Devič": u"Mheshimiwa Joanikije wa Devic",
    "St Danilo II, Archbishop of Serbia": u"Mtakatifu Danilo wa Pili, Askofu Mkuu wa Serbia",
    "St Amphilochius of Pochaiv": u"Mheshimiwa Amfilokio wa Pochaiv",
    "St Feodosii of the Kyiv Caves": u"Mheshimiwa Theodosio wa Mapango ya Kyiv",
    "St Antonii of the Kyiv Caves": u"Mheshimiwa Antonio wa Mapango ya Kyiv",
    "St Olha, Equal-to-the-Apostles": u"Mtakatifu Olha, Sawa na Mitume",
    "St Volodymyr, Equal-to-the-Apostles": u"Mtakatifu Volodymyr, Sawa na Mitume",
    "St Petro Mohyla, Metropolitan of Kyiv": u"Mtakatifu Petro Mohyla, Metropolita wa Kyiv",
    "Synaxis of All Saints of Antioch": u"Watakatifu Wote wa Antiokia",
    "Synaxis of All Bulgarian Saints": u"Watakatifu Wote wa Bulgaria",
    "Synaxis of All Saints of Mount Athos": u"Mababa Waheshimiwa Wote wa Mlima Athos",
    "Synaxis of All Saints of North America": u"Watakatifu Wote wa Amerika Kaskazini",
    "Synaxis of All Venerable Fathers of the Kyiv Caves": u"Mababa Waheshimiwa Wote wa Mapango ya Kyiv",
    "Synaxis of All Romanian Saints": u"Watakatifu Wote wa Romania",
    "Synaxis of All Saints of Russia": u"Watakatifu Wote wa Urusi",
    "Synaxis of All Saints of Ukraine": u"Watakatifu Wote wa Ukraine",
    "St Raphael, Bishop of Brooklyn": u"Mtakatifu Rafael, Askofu wa Brooklyn",
}
