# -*- coding: utf-8 -*-
"""The Churches' own commemorations, in Ukrainian.

See docs/LOCAL_NAMES.md.
"""
TEXT = {
    "St Isaac the Syrian": u"преподобний Ісаак Сирін",
    "Martyr Elian of Homs": u"мученик Іліан Емеський",
    "St Joseph of Damascus & the New Martyrs of Damascus (1860)": u"священномученик Йосиф Дамаскин і новомученики Дамаські (1860)",
    "Hieromartyrs Nicholas and Habib Khasha of Damascus": u"священномученики Миколай і Хабіб Хаша Дамаські",
    "St Gabriel of Lesnovo": u"преподобний Гавриїл Лесновський",
    "St Joachim I, Patriarch of Tarnovo": u"святитель Йоаким I, патріарх Тирновський",
    "St Euthymius, Patriarch of Tarnovo": u"святитель Євтимій, патріарх Тирновський",
    "St Peter, King of Bulgaria": u"благовірний цар Петро Болгарський",
    "St Romanus of Tarnovo": u"преподобний Роман Тирновський",
    "St Sophronius, Bishop of Vratsa": u"святитель Софроній, єпископ Врачанський",
    "St Boris-Michael, Equal-to-the-Apostles, Baptizer of Bulgaria": u"рівноапостольний цар Борис-Михаїл, хреститель Болгарії",
    "Great Martyr Nicholas of Sofia": u"великомученик Миколай Софійський",
    "St Paisius of Hilendar": u"преподобний Паїсій Хілендарський",
    "The Seven Holy Apostles (Sedmochislenitsi)": u"святі Седмочисленники",
    "St Joachim of Osogovo": u"преподобний Йоаким Осоговський",
    "Repose of St John of Rila": u"Преставлення преподобного Іоана Рильського",
    "New Martyr Simeon of Samokov": u"новомученик Симеон Самоковський",
    "St Cosmas of Zographou": u"преподобний Косма Зографський",
    "The 26 Martyrs of Zographou": u"26 мучеників Зографських",
    "St Demetrius of Basarbovo": u"преподобний Димитрій Басарбовський",
    "Venerable Pimen of Zographou": u"преподобний Пимен Зографський",
    "Righteous Michael the Soldier of Bulgaria": u"праведний Михаїл воїн Болгарський",
    "St Theodosius of Tarnovo": u"преподобний Феодосій Тирновський",
    "St Nektarios the Bulgarian of Bitola": u"преподобномученик Нектарій Бітольський",
    "St Nahum of Ohrid": u"преподобний Наум Охридський",
    "Ss Salome of Ujarma and Perozhavra of Sivnia": u"праведні Саломія Уджармська і Перожавра Сивнійська",
    "St Eprem the Lesser, the Philosopher": u"преподобний Єфрем Мцире, філософ",
    "St David IV the Builder, King of Georgia": u"благовірний Давид IV Будівничий, цар Грузії",
    "St Ioane the Catholicos": u"святитель Іоан, католикос Грузії",
    "Holy King Demetre the Devoted": u"благовірний цар Димитрій II Самопожертвувач",
    "St Ambrosi the Confessor, Catholicos-Patriarch of All Georgia": u"святитель Амвросій сповідник, католикос-патріарх усієї Грузії",
    "Venerable David of the Gareji Monastery": u"преподобний Давид Гареджійський",
    "St Tamar, Queen of Georgia": u"благовірна цариця Тамара",
    "Venerable Ioane of Zedazeni and his Twelve Disciples": u"преподобний Іоан Зедазнійський і дванадцять його учнів",
    "Venerable Ekvtime of Mount Athos, the Translator": u"преподобний Євтимій Святогорець, перекладач",
    "St George the Hagiorite, and Hieromartyr Kirion II, Catholicos-Patriarch": u"преподобний Георгій Святогорець і священномученик Кіріон II, католикос-патріарх",
    "St Ilia the Righteous": u"праведний Ілля Чавчавадзе",
    "Holy Martyr Evstati of Mtskheta": u"мученик Євстафій Мцхетський",
    "St Tsotne Dadiani the Confessor": u"благовірний Цотне Дадіані сповідник",
    "St Razhden, Protomartyr of Georgia, and the Nine Kherkheulidze Brothers": u"першомученик Ражден Перський і дев'ять братів Херхеулідзе",
    "Holy Confessors Ioane and Giorgi-Ioane of Betania": u"преподобні сповідники Іоан і Георгій-Іоан Бетанійські",
    "Holy Great-martyr Queen Ketevan": u"великомучениця цариця Кетеван",
    "Holy Martyrs Bidzina, Shalva and Elizbar": u"мученики Бідзіна, Шалва і Елізбар",
    "Venerable Grigol of Khandzta": u"преподобний Григорій Хандзтійський",
    "St Gabriel of Samtavro, Confessor and Fool for Christ": u"преподобний Гавриїл Самтаврійський, сповідник і Христа ради юродивий",
    "The 100,000 Martyrs of Tbilisi": u"100 000 мучеників Тбіліських",
    "Holy King Vakhtang Gorgasali": u"благовірний цар Вахтанг Горгасалі",
    "St Ise of Tsilkani": u"святитель Ієссей Цілканський",
    "Synaxis of All Saints of Georgia": u"Собор усіх святих, що в землі Грузинській просіяли",
    "Venerable Giorgi the Scribe and his brother Saba of Khakhuli": u"преподобні Георгій Писар і брат його Сава Хахульські",
    "St Nikephoros the Leper": u"преподобний Никифор Прокажений",
    "St Arsenios of Paros": u"преподобний Арсеній Паросський",
    "St Ephraim of Katounakia": u"преподобний Єфрем Катунакський",
    "St Nikolaos Planas of Athens": u"праведний Миколай Планас Афінський",
    "St Savvas the New of Kalymnos": u"преподобний Сава Новий Калімноський",
    "St Amphilochios of Patmos": u"преподобний Амфілохій Патмоський",
    "St Joseph the Hesychast": u"преподобний Йосиф Ісихаст",
    "St Kosmas Aitolos, Equal-to-the-Apostles": u"рівноапостольний Косма Етолійський",
    "St Arsenios of Cappadocia": u"преподобний Арсеній Каппадокійський",
    "St Iakovos of Evia": u"преподобний Яків Евбейський",
    "St Antipa of Calapodești": u"преподобний Антипа Калаподештський",
    "St Calinic of Cernica": u"святитель Калинік Чернікський",
    "St Pahomie of Gledin, Bishop of Roman": u"святитель Пахомій Глединський, єпископ Романський",
    "Ss Ilie Iorest, Sava Brancovici and Simion Ștefan, Metropolitans of Transylvania": u"святителі Ілля Йорест, Сава Бранкович і Симеон Штефан, митрополити Трансильванські",
    "St Irodion of Lainici": u"преподобний Іродіон Лайніцький",
    "St John the Wallachian, Martyr": u"мученик Іоан Валах",
    "St Iacob Putneanul, Metropolitan of Moldavia": u"святитель Яків Путнянський, митрополит Молдавський",
    "St Grigorie Dascălul, Metropolitan of Wallachia": u"святитель Григорій Даскел, митрополит Волоський",
    "St Ghelasie of Râmeț": u"преподобний Гелазій Римецький",
    "St Leontie of Rădăuți": u"святитель Леонтій Радівецький",
    "St Stephen the Great": u"благовірний Стефан Великий, господар Молдавський",
    "St Ioanichie the New of Muscel": u"преподобний Іоанникій Новий Мушчельський",
    "St Ioan Iacob of Neamț": u"преподобний Іоан Яків Нямецький",
    "St Teodora of Sihla": u"преподобна Феодора Сихлська",
    "The Brâncoveanu Martyrs: Prince Constantin and his four sons": u"Мученики Бринковяну: господар Константин і четверо його синів",
    "St Iosif the New of Partoș, Metropolitan of Banat": u"святитель Йосиф Новий Партошський, митрополит Банатський",
    "St Neagoe Basarab, Voivode of Wallachia": u"благовірний Нягое Басараб, господар Волоський",
    "St Antim Ivireanul, Hieromartyr, Metropolitan of Wallachia": u"священномученик Антим Іверський, митрополит Волоський",
    "St Parascheva of Iași": u"преподобна Параскева Ясська",
    "St Dimitrie the New of Bucharest": u"преподобний Димитрій Новий Бухарестський",
    "St Iachint, Metropolitan of Wallachia": u"святитель Іакинф, митрополит Волоський",
    "St Andrei Șaguna, Metropolitan of Transylvania": u"святитель Андрій Шагуна, митрополит Трансильванський",
    "St Gheorghe of Cernica": u"преподобний Георгій Чернікський",
    "St Dosoftei, Metropolitan of Moldavia": u"святитель Досифей, митрополит Молдавський",
    "St Daniil the Hesychast": u"преподобний Даниїл Ісихаст",
    "St Nicodim of Tismana": u"преподобний Никодим Тисманський",
    "St Seraphim of Sarov": u"преподобний Серафим Саровський",
    "St Theophan the Recluse": u"святитель Феофан Затворник",
    "St Xenia of St Petersburg": u"блаженна Ксенія Петербурзька",
    "St Ignatius (Brianchaninov), Bishop of the Caucasus": u"святитель Ігнатій (Брянчанінов), єпископ Кавказький",
    "St Vladimir, Equal-to-the-Apostles": u"рівноапостольний великий князь Володимир",
    "St Sergius of Radonezh": u"преподобний Сергій Радонезький",
    "St Ambrose of Optina": u"преподобний Амвросій Оптинський",
    "Synaxis of the Optina Elders": u"Собор преподобних Оптинських старців",
    "St Sava, First Archbishop of Serbia": u"святитель Сава, перший архієпископ Сербський",
    "St Simeon the Myrrh-gusher": u"преподобний Симеон Мироточивий",
    "St Basil of Ostrog": u"святитель Василій Острозький",
    "St Justin Popovich of Ćelije": u"преподобний Іустин (Попович) Челійський",
    "St Petar of Koriša": u"преподобний Петро Коришський",
    "Holy Great-martyr Tsar Lazar (Vidovdan)": u"великомученик цар Лазар (Видовдан)",
    "St Jefrem, Patriarch of Serbia": u"святитель Єфрем, патріарх Сербський",
    "St Angelina of Serbia": u"преподобна Ангеліна Сербська",
    "Synaxis of the Holy Hierarchs of Serbia": u"Собор святителів Сербських",
    "The New Martyrs of Jasenovac": u"новомученики Ясеновацькі",
    "St Stefan Vladislav, King of Serbia": u"благовірний Стефан Владислав, король Сербський",
    "St Petar of Cetinje, Wonderworker": u"святитель Петро Цетинський, чудотворець",
    "St Prohor of Pčinja": u"преподобний Прохор Пшинський",
    "St Milutin the King and St Jelena the Queen of Serbia": u"благовірні Милутин король і Єлена королева Сербські",
    "St Stefan Dečanski, King of Serbia": u"благовірний Стефан Дечанський, король Сербський",
    "St Sebastian of Jackson": u"преподобний Севастіан Джексонський",
    "St Joanikije of Devič": u"преподобний Іоанникій Девицький",
    "St Danilo II, Archbishop of Serbia": u"святитель Даниїл II, архієпископ Сербський",
    "St Amphilochius of Pochaiv": u"преподобний Амфілохій Почаївський",
    "St Feodosii of the Kyiv Caves": u"преподобний Феодосій Печерський",
    "St Antonii of the Kyiv Caves": u"преподобний Антоній Печерський",
    "St Olha, Equal-to-the-Apostles": u"рівноапостольна княгиня Ольга",
    "St Volodymyr, Equal-to-the-Apostles": u"рівноапостольний великий князь Володимир",
    "St Petro Mohyla, Metropolitan of Kyiv": u"святитель Петро Могила, митрополит Київський",
    "Synaxis of All Saints of Antioch": u"Собор усіх святих Антиохійських",
    "Synaxis of All Bulgarian Saints": u"Собор усіх святих, що в землі Болгарській просіяли",
    "Synaxis of All Saints of Mount Athos": u"Собор усіх преподобних отців Афонських",
    "Synaxis of All Saints of North America": u"Собор усіх святих, що в землі Північноамериканській просіяли",
    "Synaxis of All Venerable Fathers of the Kyiv Caves": u"Собор усіх преподобних отців Києво-Печерських",
    "Synaxis of All Romanian Saints": u"Собор усіх святих, що в землі Румунській просіяли",
    "Synaxis of All Saints of Russia": u"Собор усіх святих, що в землі Руській просіяли",
    "Synaxis of All Saints of Ukraine": u"Собор усіх святих, що в землі Українській просіяли",
    "St Raphael, Bishop of Brooklyn": u"святитель Рафаїл, єпископ Бруклінський",
}
