# -*- coding: utf-8 -*-
"""The Churches' own commemorations, in Urdu.

See docs/LOCAL_NAMES.md.
"""
TEXT = {
    "St Isaac the Syrian": u"شام کے جلیل القدر اسحاق",
    "Martyr Elian of Homs": u"حمص کے شہید ایلیان",
    "St Joseph of Damascus & the New Martyrs of Damascus (1860)": u"دمشق کے کاہن شہید یوسف اور دمشق کے نئے شہداء (1860)",
    "Hieromartyrs Nicholas and Habib Khasha of Damascus": u"دمشق کے کاہن شہید نکولس اور حبیب خاشہ",
    "St Gabriel of Lesnovo": u"لیسنووو کے جلیل القدر جبرائیل",
    "St Joachim I, Patriarch of Tarnovo": u"ترنووو کے بطریرک سینٹ یوآکیم اول",
    "St Euthymius, Patriarch of Tarnovo": u"ترنووو کے بطریرک سینٹ یوتھیمیس",
    "St Peter, King of Bulgaria": u"بلغاریہ کے بادشاہ سینٹ پطرس",
    "St Romanus of Tarnovo": u"ترنووو کے جلیل القدر رومانس",
    "St Sophronius, Bishop of Vratsa": u"وراتسا کے بشپ سینٹ سوفرونیس",
    "St Boris-Michael, Equal-to-the-Apostles, Baptizer of Bulgaria": u"بلغاریہ کے بپتسمہ دینے والے سینٹ بورس-میخائیل، رسولوں کے ہمسر",
    "Great Martyr Nicholas of Sofia": u"صوفیہ کے عظیم شہید نکولس",
    "St Paisius of Hilendar": u"ہلندار کے جلیل القدر پائسیس",
    "The Seven Holy Apostles (Sedmochislenitsi)": u"سات مقدس رسول (سدموچسلینیتسی)",
    "St Joachim of Osogovo": u"اوسوگوو کے جلیل القدر یوآکیم",
    "Repose of St John of Rila": u"ریلا کے جلیل القدر یوحنا کا انتقال",
    "New Martyr Simeon of Samokov": u"ساموکوو کے نئے شہید شمعون",
    "St Cosmas of Zographou": u"زوگرافو کے جلیل القدر کوسماس",
    "The 26 Martyrs of Zographou": u"زوگرافو کے چھبیس شہید",
    "St Demetrius of Basarbovo": u"باساربووو کے جلیل القدر دیمتریس",
    "Venerable Pimen of Zographou": u"زوگرافو کے جلیل القدر پیمن",
    "Righteous Michael the Soldier of Bulgaria": u"بلغاریہ کے راستباز سپاہی میخائیل",
    "St Theodosius of Tarnovo": u"ترنووو کے جلیل القدر تھیوڈوسیس",
    "St Nektarios the Bulgarian of Bitola": u"بتولا کے جلیل القدر شہید نکتاریس",
    "St Nahum of Ohrid": u"اوہرد کے جلیل القدر ناحوم",
    "Ss Salome of Ujarma and Perozhavra of Sivnia": u"اوجارما کی راستباز سالومی اور سیونیا کی پیروژاورا",
    "St Eprem the Lesser, the Philosopher": u"جلیل القدر ایفریم اصغر، فلسفی",
    "St David IV the Builder, King of Georgia": u"جارجیا کے بادشاہ سینٹ داؤد چہارم معمار",
    "St Ioane the Catholicos": u"جارجیا کے کاتھولیکوس سینٹ یوآنے",
    "Holy King Demetre the Devoted": u"جارجیا کے بادشاہ سینٹ دیمیتره جاں نثار",
    "St Ambrosi the Confessor, Catholicos-Patriarch of All Georgia": u"تمام جارجیا کے کاتھولیکوس-بطریرک معترف سینٹ امبروسی",
    "Venerable David of the Gareji Monastery": u"گاریجی کے جلیل القدر داؤد",
    "St Tamar, Queen of Georgia": u"جارجیا کی ملکہ سینٹ تامار",
    "Venerable Ioane of Zedazeni and his Twelve Disciples": u"زیدازینی کے جلیل القدر یوآنے اور ان کے بارہ شاگرد",
    "Venerable Ekvtime of Mount Athos, the Translator": u"کوہ آتھوس کے جلیل القدر ایکوتیمے، مترجم",
    "St George the Hagiorite, and Hieromartyr Kirion II, Catholicos-Patriarch": u"کوہ آتھوس کے جلیل القدر گیورگی اور کاہن شہید کیریون دوم، کاتھولیکوس-بطریرک",
    "St Ilia the Righteous": u"راستباز سینٹ الیا",
    "Holy Martyr Evstati of Mtskheta": u"متسخیتا کے شہید ایوستاتی",
    "St Tsotne Dadiani the Confessor": u"معترف سینٹ تسوتنے دادیانی",
    "St Razhden, Protomartyr of Georgia, and the Nine Kherkheulidze Brothers": u"جارجیا کے پہلے شہید راژدن اور خرخیولیدزے کے نو بھائی",
    "Holy Confessors Ioane and Giorgi-Ioane of Betania": u"بیتانیا کے معترف سینٹ یوآنے اور گیورگی-یوآنے",
    "Holy Great-martyr Queen Ketevan": u"عظیم شہید ملکہ کیتیوان",
    "Holy Martyrs Bidzina, Shalva and Elizbar": u"شہداء بدزینا، شالوا اور الیزبار",
    "Venerable Grigol of Khandzta": u"خاندزتا کے جلیل القدر گریگول",
    "St Gabriel of Samtavro, Confessor and Fool for Christ": u"سامتاورو کے جلیل القدر جبرائیل، معترف اور مسیح کے لیے احمق",
    "The 100,000 Martyrs of Tbilisi": u"تبلیسی کے ایک لاکھ شہید",
    "Holy King Vakhtang Gorgasali": u"جارجیا کے بادشاہ سینٹ وختانگ گورگاسالی",
    "St Ise of Tsilkani": u"تسلکانی کے سینٹ ایسے",
    "Synaxis of All Saints of Georgia": u"جارجیا کے تمام سینٹس",
    "Venerable Giorgi the Scribe and his brother Saba of Khakhuli": u"خاخولی کے جلیل القدر کاتب گیورگی اور ان کے بھائی سابا",
    "St Nikephoros the Leper": u"جلیل القدر کوڑھی نکیفوروس",
    "St Arsenios of Paros": u"پاروس کے جلیل القدر ارسینیس",
    "St Ephraim of Katounakia": u"کاتوناکیا کے جلیل القدر ایفریم",
    "St Nikolaos Planas of Athens": u"ایتھنز کے راستباز نکولس پلاناس",
    "St Savvas the New of Kalymnos": u"کالیمنوس کے جلیل القدر نئے ساوا",
    "St Amphilochios of Patmos": u"پاتموس کے جلیل القدر امفیلوخیس",
    "St Joseph the Hesychast": u"جلیل القدر خاموش نشین یوسف",
    "St Kosmas Aitolos, Equal-to-the-Apostles": u"ایتولیا کے سینٹ کوسماس، رسولوں کے ہمسر",
    "St Arsenios of Cappadocia": u"کپادوکیا کے جلیل القدر ارسینیس",
    "St Iakovos of Evia": u"ایویا کے جلیل القدر یعقوب",
    "St Antipa of Calapodești": u"کالاپودیشتی کے جلیل القدر انتیپا",
    "St Calinic of Cernica": u"چرنیکا کے سینٹ کالینک",
    "St Pahomie of Gledin, Bishop of Roman": u"گلیدین کے سینٹ پاہومیے، رومان کے بشپ",
    "Ss Ilie Iorest, Sava Brancovici and Simion Ștefan, Metropolitans of Transylvania": u"ٹرانسلوانیا کے میٹروپولیٹن سینٹ ایلیے یوریست، ساوا برانکوویچی اور سیمیون شتیفان",
    "St Irodion of Lainici": u"لائنیچی کے جلیل القدر ایروڈیون",
    "St John the Wallachian, Martyr": u"شہید یوحنا والاخی",
    "St Iacob Putneanul, Metropolitan of Moldavia": u"مالدویا کے میٹروپولیٹن سینٹ یعقوب پُتنیانول",
    "St Grigorie Dascălul, Metropolitan of Wallachia": u"والاخیا کے میٹروپولیٹن سینٹ گریگوریے داسکالول",
    "St Ghelasie of Râmeț": u"ریمیتس کے سینٹ گیلاسیے",
    "St Leontie of Rădăuți": u"راداؤتسی کے سینٹ لیونتیے",
    "St Stephen the Great": u"سینٹ عظیم اسٹیفن",
    "St Ioanichie the New of Muscel": u"موشچیل کے جلیل القدر نئے یوآنیکیے",
    "St Ioan Iacob of Neamț": u"نیامتس کے جلیل القدر یوآن یعقوب",
    "St Teodora of Sihla": u"سیہلا کی جلیل القدر تھیوڈورا",
    "The Brâncoveanu Martyrs: Prince Constantin and his four sons": u"برنکووینو کے شہداء: حکمران قسطنطین اور ان کے چار بیٹے",
    "St Iosif the New of Partoș, Metropolitan of Banat": u"باناط کے میٹروپولیٹن، پارتوش کے سینٹ نئے یوسف",
    "St Neagoe Basarab, Voivode of Wallachia": u"والاخیا کے حکمران سینٹ نیاگوئے باساراب",
    "St Antim Ivireanul, Hieromartyr, Metropolitan of Wallachia": u"والاخیا کے میٹروپولیٹن، کاہن شہید انتیم ایویریانول",
    "St Parascheva of Iași": u"یاشی کی جلیل القدر پاراسکیوا",
    "St Dimitrie the New of Bucharest": u"بخارسٹ کے سینٹ نئے دیمتری",
    "St Iachint, Metropolitan of Wallachia": u"والاخیا کے میٹروپولیٹن سینٹ یاکنت",
    "St Andrei Șaguna, Metropolitan of Transylvania": u"ٹرانسلوانیا کے میٹروپولیٹن سینٹ آندرے شاگونا",
    "St Gheorghe of Cernica": u"چرنیکا کے جلیل القدر گیورگے",
    "St Dosoftei, Metropolitan of Moldavia": u"مالدویا کے میٹروپولیٹن سینٹ دوسوفتے",
    "St Daniil the Hesychast": u"جلیل القدر خاموش نشین دانی ایل",
    "St Nicodim of Tismana": u"تسمانا کے جلیل القدر نکودیم",
    "St Seraphim of Sarov": u"ساروف کے سینٹ سیرافیم",
    "St Theophan the Recluse": u"سینٹ گوشہ نشین تھیوفان",
    "St Xenia of St Petersburg": u"سینٹ پیٹرز برگ کی سینٹ زینیا",
    "St Ignatius (Brianchaninov), Bishop of the Caucasus": u"قفقاز کے بشپ سینٹ اگنیشیس (بریانچانینوف)",
    "St Vladimir, Equal-to-the-Apostles": u"سینٹ ولادیمیر، رسولوں کے ہمسر",
    "St Sergius of Radonezh": u"رادونیج کے سینٹ سرجیس",
    "St Ambrose of Optina": u"اوپتینا کے جلیل القدر امبروسیس",
    "Synaxis of the Optina Elders": u"اوپتینا کے جلیل القدر بزرگ",
    "St Sava, First Archbishop of Serbia": u"سربیا کے پہلے سردار اسقف سینٹ ساوا",
    "St Simeon the Myrrh-gusher": u"مُر بہانے والے سینٹ شمعون",
    "St Basil of Ostrog": u"اوستروگ کے سینٹ بازل",
    "St Justin Popovich of Ćelije": u"چیلیے کے جلیل القدر یوستن پوپووچ",
    "St Petar of Koriša": u"کوریشا کے جلیل القدر پیتر",
    "Holy Great-martyr Tsar Lazar (Vidovdan)": u"مقدس عظیم شہید زار لازار (ودوودان)",
    "St Jefrem, Patriarch of Serbia": u"سربیا کے بطریرک سینٹ یفریم",
    "St Angelina of Serbia": u"سربیا کی جلیل القدر انجلینا",
    "Synaxis of the Holy Hierarchs of Serbia": u"سربیا کے مقدس بشپ",
    "The New Martyrs of Jasenovac": u"یاسینوواتس کے نئے شہداء",
    "St Stefan Vladislav, King of Serbia": u"سربیا کے بادشاہ سینٹ استیفان ولادیسلاو",
    "St Petar of Cetinje, Wonderworker": u"تسیتینیے کے سینٹ پیتر، معجزہ گر",
    "St Prohor of Pčinja": u"پچینیا کے جلیل القدر پروہور",
    "St Milutin the King and St Jelena the Queen of Serbia": u"سربیا کے بادشاہ سینٹ میلوتین اور ملکہ سینٹ یلینا",
    "St Stefan Dečanski, King of Serbia": u"سربیا کے بادشاہ سینٹ استیفان دیچانسکی",
    "St Sebastian of Jackson": u"جیکسن کے جلیل القدر سیباستیان",
    "St Joanikije of Devič": u"دیویچ کے جلیل القدر یوآنیکیے",
    "St Danilo II, Archbishop of Serbia": u"سربیا کے سردار اسقف سینٹ دانیلو دوم",
    "St Amphilochius of Pochaiv": u"پوچائیو کے جلیل القدر امفیلوخیس",
    "St Feodosii of the Kyiv Caves": u"کیف غاروں کے جلیل القدر تھیوڈوسیس",
    "St Antonii of the Kyiv Caves": u"کیف غاروں کے جلیل القدر انتونی",
    "St Olha, Equal-to-the-Apostles": u"سینٹ اولہا، رسولوں کے ہمسر",
    "St Volodymyr, Equal-to-the-Apostles": u"سینٹ وولودیمیر، رسولوں کے ہمسر",
    "St Petro Mohyla, Metropolitan of Kyiv": u"کیف کے میٹروپولیٹن سینٹ پیترو موہیلا",
    "Synaxis of All Saints of Antioch": u"انطاکیہ کے تمام سینٹس",
    "Synaxis of All Bulgarian Saints": u"بلغاریہ کے تمام سینٹس",
    "Synaxis of All Saints of Mount Athos": u"کوہ آتھوس کے تمام جلیل القدر آباء",
    "Synaxis of All Saints of North America": u"شمالی امریکہ کے تمام سینٹس",
    "Synaxis of All Venerable Fathers of the Kyiv Caves": u"کیف غاروں کے تمام جلیل القدر آباء",
    "Synaxis of All Romanian Saints": u"رومانیہ کے تمام سینٹس",
    "Synaxis of All Saints of Russia": u"روس کے تمام سینٹس",
    "Synaxis of All Saints of Ukraine": u"یوکرین کے تمام سینٹس",
    "St Raphael, Bishop of Brooklyn": u"بروکلین کے سینٹ رافیل، بشپ",
}
