# -*- coding: utf-8 -*-
"""The Churches' own commemorations, in Chinese.

See docs/LOCAL_NAMES.md.
"""
TEXT = {
    "St Isaac the Syrian": u"叙利亚的可敬者以撒",
    "Martyr Elian of Homs": u"埃梅萨的致命者埃利安",
    "St Joseph of Damascus & the New Martyrs of Damascus (1860)": u"大马士革的司祭致命者约瑟及大马士革新致命者们（1860）",
    "Hieromartyrs Nicholas and Habib Khasha of Damascus": u"大马士革的司祭致命者尼古拉与哈比布·哈沙",
    "St Gabriel of Lesnovo": u"莱斯诺沃的可敬者加百列",
    "St Joachim I, Patriarch of Tarnovo": u"特尔诺沃牧首圣约阿希姆一世",
    "St Euthymius, Patriarch of Tarnovo": u"特尔诺沃牧首圣欧提弥",
    "St Peter, King of Bulgaria": u"保加利亚国王圣彼得",
    "St Romanus of Tarnovo": u"特尔诺沃的可敬者罗曼",
    "St Sophronius, Bishop of Vratsa": u"弗拉察主教圣索弗罗尼",
    "St Boris-Michael, Equal-to-the-Apostles, Baptizer of Bulgaria": u"保加利亚的施洗者圣鲍里斯-弥哈伊尔，与使徒同等",
    "Great Martyr Nicholas of Sofia": u"索非亚的大致命者尼古拉",
    "St Paisius of Hilendar": u"希兰达尔的可敬者帕伊西",
    "The Seven Holy Apostles (Sedmochislenitsi)": u"七位圣使徒（塞德莫奇斯列尼齐）",
    "St Joachim of Osogovo": u"奥索戈沃的可敬者约阿希姆",
    "Repose of St John of Rila": u"里拉的可敬者约翰的安息",
    "New Martyr Simeon of Samokov": u"萨莫科夫的新致命者西梅翁",
    "St Cosmas of Zographou": u"佐格拉福的可敬者科斯马",
    "The 26 Martyrs of Zographou": u"佐格拉福的二十六位致命者",
    "St Demetrius of Basarbovo": u"巴萨拉博沃的可敬者迪米特里",
    "Venerable Pimen of Zographou": u"佐格拉福的可敬者皮门",
    "Righteous Michael the Soldier of Bulgaria": u"保加利亚的义人军人弥哈伊尔",
    "St Theodosius of Tarnovo": u"特尔诺沃的可敬者德奥多西",
    "St Nektarios the Bulgarian of Bitola": u"比托拉的可敬致命者奈克塔里",
    "St Nahum of Ohrid": u"奥赫里德的可敬者纳鸿",
    "Ss Salome of Ujarma and Perozhavra of Sivnia": u"乌贾尔马的义人萨洛米与西夫尼亚的佩罗扎夫拉",
    "St Eprem the Lesser, the Philosopher": u"可敬者小埃夫雷姆，哲学家",
    "St David IV the Builder, King of Georgia": u"格鲁吉亚国王圣大卫四世建造者",
    "St Ioane the Catholicos": u"格鲁吉亚卡托利科斯圣约翰",
    "Holy King Demetre the Devoted": u"格鲁吉亚国王圣德梅特雷，舍身者",
    "St Ambrosi the Confessor, Catholicos-Patriarch of All Georgia": u"全格鲁吉亚卡托利科斯牧首、宣信者圣安勃罗西",
    "Venerable David of the Gareji Monastery": u"加雷吉的可敬者大卫",
    "St Tamar, Queen of Georgia": u"格鲁吉亚女王圣塔玛尔",
    "Venerable Ioane of Zedazeni and his Twelve Disciples": u"泽达泽尼的可敬者约翰及其十二门徒",
    "Venerable Ekvtime of Mount Athos, the Translator": u"阿托斯的可敬者埃克夫季梅，译经者",
    "St George the Hagiorite, and Hieromartyr Kirion II, Catholicos-Patriarch": u"阿托斯的可敬者乔治与司祭致命者基里翁二世，卡托利科斯牧首",
    "St Ilia the Righteous": u"义人圣伊利亚",
    "Holy Martyr Evstati of Mtskheta": u"姆茨赫塔的致命者埃夫斯塔提",
    "St Tsotne Dadiani the Confessor": u"宣信者圣佐特内·达迪亚尼",
    "St Razhden, Protomartyr of Georgia, and the Nine Kherkheulidze Brothers": u"格鲁吉亚首位致命者拉日登与赫尔赫乌利泽九兄弟",
    "Holy Confessors Ioane and Giorgi-Ioane of Betania": u"贝塔尼亚的宣信者圣约翰与乔治-约翰",
    "Holy Great-martyr Queen Ketevan": u"大致命女克特万王后",
    "Holy Martyrs Bidzina, Shalva and Elizbar": u"致命者比济纳、沙尔瓦与埃利兹巴尔",
    "Venerable Grigol of Khandzta": u"汉兹塔的可敬者格里戈尔",
    "St Gabriel of Samtavro, Confessor and Fool for Christ": u"萨姆塔夫罗的可敬者加百列，宣信者及为基督而愚者",
    "The 100,000 Martyrs of Tbilisi": u"第比利斯的十万致命者",
    "Holy King Vakhtang Gorgasali": u"格鲁吉亚国王圣瓦赫唐·戈尔加萨利",
    "St Ise of Tsilkani": u"齐尔卡尼的圣伊塞",
    "Synaxis of All Saints of Georgia": u"格鲁吉亚诸圣纪念",
    "Venerable Giorgi the Scribe and his brother Saba of Khakhuli": u"哈胡里的可敬者书记乔治与其兄弟萨巴",
    "St Nikephoros the Leper": u"可敬者麻风病人尼基弗鲁",
    "St Arsenios of Paros": u"帕罗斯的可敬者阿尔塞尼",
    "St Ephraim of Katounakia": u"卡图纳基亚的可敬者埃夫雷姆",
    "St Nikolaos Planas of Athens": u"雅典的义人尼古拉·普拉纳斯",
    "St Savvas the New of Kalymnos": u"卡林诺斯的可敬者新萨瓦",
    "St Amphilochios of Patmos": u"帕特莫斯的可敬者安菲洛基",
    "St Joseph the Hesychast": u"可敬者静修者约瑟",
    "St Kosmas Aitolos, Equal-to-the-Apostles": u"埃托利亚的圣科斯马斯，与使徒同等",
    "St Arsenios of Cappadocia": u"卡帕多西亚的可敬者阿尔塞尼",
    "St Iakovos of Evia": u"埃维亚的可敬者雅各",
    "St Antipa of Calapodești": u"卡拉波德什蒂的可敬者安提帕",
    "St Calinic of Cernica": u"切尔尼卡的圣卡利尼克",
    "St Pahomie of Gledin, Bishop of Roman": u"格莱丁的圣帕霍米，罗曼主教",
    "Ss Ilie Iorest, Sava Brancovici and Simion Ștefan, Metropolitans of Transylvania": u"特兰西瓦尼亚都主教圣伊利耶·约雷斯特、萨瓦·布兰科维奇与西米翁·什特凡",
    "St Irodion of Lainici": u"莱尼奇的可敬者伊罗迪翁",
    "St John the Wallachian, Martyr": u"致命者瓦拉几亚的约翰",
    "St Iacob Putneanul, Metropolitan of Moldavia": u"摩尔多瓦都主教圣雅各·普特内亚努",
    "St Grigorie Dascălul, Metropolitan of Wallachia": u"瓦拉几亚都主教圣格里戈里耶·达斯卡卢",
    "St Ghelasie of Râmeț": u"勒梅茨的圣格拉西耶",
    "St Leontie of Rădăuți": u"勒杜齐的圣莱昂蒂耶",
    "St Stephen the Great": u"圣大斯特凡",
    "St Ioanichie the New of Muscel": u"穆谢尔的可敬者新约安尼基耶",
    "St Ioan Iacob of Neamț": u"尼亚姆茨的可敬者约翰·雅各",
    "St Teodora of Sihla": u"西赫拉的可敬者德奥多拉",
    "The Brâncoveanu Martyrs: Prince Constantin and his four sons": u"布伦科韦亚努诸致命者，君主康斯坦丁及其四子",
    "St Iosif the New of Partoș, Metropolitan of Banat": u"巴纳特都主教、帕尔托什的圣新约瑟",
    "St Neagoe Basarab, Voivode of Wallachia": u"瓦拉几亚君主圣尼亚戈埃·巴萨拉布",
    "St Antim Ivireanul, Hieromartyr, Metropolitan of Wallachia": u"瓦拉几亚都主教、司祭致命者安提姆·伊维雷亚努",
    "St Parascheva of Iași": u"雅西的可敬者帕拉斯克瓦",
    "St Dimitrie the New of Bucharest": u"布加勒斯特的圣新迪米特里",
    "St Iachint, Metropolitan of Wallachia": u"瓦拉几亚都主教圣雅金特",
    "St Andrei Șaguna, Metropolitan of Transylvania": u"特兰西瓦尼亚都主教圣安德烈·沙古纳",
    "St Gheorghe of Cernica": u"切尔尼卡的可敬者乔治",
    "St Dosoftei, Metropolitan of Moldavia": u"摩尔多瓦都主教圣多索夫泰",
    "St Daniil the Hesychast": u"可敬者静修者达尼尔",
    "St Nicodim of Tismana": u"蒂斯马纳的可敬者尼科迪姆",
    "St Seraphim of Sarov": u"萨罗夫的圣塞拉芬",
    "St Theophan the Recluse": u"圣隐居者德奥梵",
    "St Xenia of St Petersburg": u"圣彼得堡的圣克谢尼娅",
    "St Ignatius (Brianchaninov), Bishop of the Caucasus": u"高加索主教圣伊格纳提（布良恰尼诺夫）",
    "St Vladimir, Equal-to-the-Apostles": u"圣弗拉基米尔，与使徒同等",
    "St Sergius of Radonezh": u"拉多涅日的圣谢尔盖",
    "St Ambrose of Optina": u"奥普提纳的可敬者安勃罗西",
    "Synaxis of the Optina Elders": u"奥普提纳诸可敬长老纪念",
    "St Sava, First Archbishop of Serbia": u"塞尔维亚首任大主教圣萨瓦",
    "St Simeon the Myrrh-gusher": u"流圣液者圣西梅翁",
    "St Basil of Ostrog": u"奥斯特罗格的圣瓦西里",
    "St Justin Popovich of Ćelije": u"切利耶的可敬者尤斯丁·波波维奇",
    "St Petar of Koriša": u"科里沙的可敬者彼得",
    "Holy Great-martyr Tsar Lazar (Vidovdan)": u"圣大致命者拉扎尔沙皇（维多夫丹）",
    "St Jefrem, Patriarch of Serbia": u"塞尔维亚牧首圣埃夫雷姆",
    "St Angelina of Serbia": u"塞尔维亚的可敬者安杰利娜",
    "Synaxis of the Holy Hierarchs of Serbia": u"塞尔维亚诸圣主教纪念",
    "The New Martyrs of Jasenovac": u"亚塞诺瓦茨的新致命者们",
    "St Stefan Vladislav, King of Serbia": u"塞尔维亚国王圣斯特凡·弗拉迪斯拉夫",
    "St Petar of Cetinje, Wonderworker": u"采蒂涅的圣彼得，行奇迹者",
    "St Prohor of Pčinja": u"普钦亚的可敬者普罗霍尔",
    "St Milutin the King and St Jelena the Queen of Serbia": u"塞尔维亚国王圣米卢廷与王后圣叶莲娜",
    "St Stefan Dečanski, King of Serbia": u"塞尔维亚国王圣斯特凡·德昌斯基",
    "St Sebastian of Jackson": u"杰克逊的可敬者塞巴斯蒂安",
    "St Joanikije of Devič": u"德维奇的可敬者约安尼基",
    "St Danilo II, Archbishop of Serbia": u"塞尔维亚大主教圣达尼洛二世",
    "St Amphilochius of Pochaiv": u"波恰耶夫的可敬者安菲洛基",
    "St Feodosii of the Kyiv Caves": u"基辅洞窟的可敬者德奥多西",
    "St Antonii of the Kyiv Caves": u"基辅洞窟的可敬者安东尼",
    "St Olha, Equal-to-the-Apostles": u"圣奥莉加，与使徒同等",
    "St Volodymyr, Equal-to-the-Apostles": u"圣弗拉基米尔（沃洛迪米尔），与使徒同等",
    "St Petro Mohyla, Metropolitan of Kyiv": u"基辅都主教圣彼得·莫吉拉",
    "Synaxis of All Saints of Antioch": u"安提约基亚诸圣纪念",
    "Synaxis of All Bulgarian Saints": u"保加利亚诸圣纪念",
    "Synaxis of All Saints of Mount Athos": u"圣山诸可敬教父纪念",
    "Synaxis of All Saints of North America": u"北美洲诸圣纪念",
    "Synaxis of All Venerable Fathers of the Kyiv Caves": u"基辅洞窟诸可敬教父纪念",
    "Synaxis of All Romanian Saints": u"罗马尼亚诸圣纪念",
    "Synaxis of All Saints of Russia": u"俄罗斯诸圣纪念",
    "Synaxis of All Saints of Ukraine": u"乌克兰诸圣纪念",
    "St Raphael, Bishop of Brooklyn": u"布鲁克林主教圣拉斐尔",
}
